SUMMARY = "GAP: Automata groups"
DESCRIPTION = "The AutomGrp package provides methods for computations with groups \
and semigroups generated by finite automata or given by wreath \
recursions, as well as with their finitely generated subgroups, \
subsemigroups and elements."
LICENSE = "MIT"

PV = "1.3.3"

RPM_NAME = "gap-automgrp-1.3.3-1.2.noarch.rpm"
RPM_HASH = "f4b170f66f384998fd26332a4a5cb89a20a0451ff82af6610490eac6eefc7b27fc5706e51e02904e21a9708e0ebce7bf8c601a1d9ed669e9a3829728daf6f642"
REPO_ARCH = "noarch"

RPROVIDES:${PN} += "gap-automgrp"

RDEPENDS:${PN} += "/usr/bin/perl \
/usr/bin/sh \
gap-core \
gap-fga"

inherit rpm
