SUMMARY = "Linux Studio Plugins (GStreamer)"
DESCRIPTION = "LSP (Linux Studio Plugins) is a collection of open-source plugins \
currently compatible with LADSPA, LV2, CLAP and LinuxVST formats. \
 \
The basic idea is to fill the lack of good and useful plugins under \
the GNU/Linux platform. \
 \
This is the GStreamer version of the plugins."
LICENSE = "LGPL-3.0-or-later"

PV = "1.2.34"

RPM_NAME = "gstreamer-lsp-plugins-1.2.34-1.1.aarch64.rpm"
RPM_HASH = "bded286de52194ba54fd8f82d790dbe6bfd52d57b5eaafe99fd3f4a9a8e4eabd13eaa298c30660e18bb711846d2f32a99f5a6298d7ba419227b5eaa34dcf7ce3"

RPROVIDES:${PN} += "gstreamer-lsp-plugins \
libgstlsp-plugins-ab-tester-x2-mono.so \
libgstlsp-plugins-ab-tester-x2-stereo.so \
libgstlsp-plugins-ab-tester-x4-mono.so \
libgstlsp-plugins-ab-tester-x4-stereo.so \
libgstlsp-plugins-ab-tester-x8-mono.so \
libgstlsp-plugins-ab-tester-x8-stereo.so \
libgstlsp-plugins-art-delay-mono.so \
libgstlsp-plugins-art-delay-stereo.so \
libgstlsp-plugins-autogain-mono.so \
libgstlsp-plugins-autogain-stereo.so \
libgstlsp-plugins-beat-breather-mono.so \
libgstlsp-plugins-beat-breather-stereo.so \
libgstlsp-plugins-chorus-mono.so \
libgstlsp-plugins-chorus-stereo.so \
libgstlsp-plugins-clipper-mono.so \
libgstlsp-plugins-clipper-stereo.so \
libgstlsp-plugins-comp-delay-mono.so \
libgstlsp-plugins-comp-delay-stereo.so \
libgstlsp-plugins-comp-delay-x2-stereo.so \
libgstlsp-plugins-compressor-lr.so \
libgstlsp-plugins-compressor-mono.so \
libgstlsp-plugins-compressor-ms.so \
libgstlsp-plugins-compressor-stereo.so \
libgstlsp-plugins-crossover-lr.so \
libgstlsp-plugins-crossover-mono.so \
libgstlsp-plugins-crossover-ms.so \
libgstlsp-plugins-crossover-stereo.so \
libgstlsp-plugins-deesser-mono.so \
libgstlsp-plugins-deesser-stereo.so \
libgstlsp-plugins-dyna-processor-lr.so \
libgstlsp-plugins-dyna-processor-mono.so \
libgstlsp-plugins-dyna-processor-ms.so \
libgstlsp-plugins-dyna-processor-stereo.so \
libgstlsp-plugins-expander-lr.so \
libgstlsp-plugins-expander-mono.so \
libgstlsp-plugins-expander-ms.so \
libgstlsp-plugins-expander-stereo.so \
libgstlsp-plugins-filter-mono.so \
libgstlsp-plugins-filter-stereo.so \
libgstlsp-plugins-flanger-mono.so \
libgstlsp-plugins-flanger-stereo.so \
libgstlsp-plugins-gate-lr.so \
libgstlsp-plugins-gate-mono.so \
libgstlsp-plugins-gate-ms.so \
libgstlsp-plugins-gate-stereo.so \
libgstlsp-plugins-gott-compressor-lr.so \
libgstlsp-plugins-gott-compressor-mono.so \
libgstlsp-plugins-gott-compressor-ms.so \
libgstlsp-plugins-gott-compressor-stereo.so \
libgstlsp-plugins-graph-equalizer-x16-lr.so \
libgstlsp-plugins-graph-equalizer-x16-mono.so \
libgstlsp-plugins-graph-equalizer-x16-ms.so \
libgstlsp-plugins-graph-equalizer-x16-stereo.so \
libgstlsp-plugins-graph-equalizer-x32-lr.so \
libgstlsp-plugins-graph-equalizer-x32-mono.so \
libgstlsp-plugins-graph-equalizer-x32-ms.so \
libgstlsp-plugins-graph-equalizer-x32-stereo.so \
libgstlsp-plugins-impulse-responses-mono.so \
libgstlsp-plugins-impulse-responses-stereo.so \
libgstlsp-plugins-impulse-reverb-mono.so \
libgstlsp-plugins-impulse-reverb-stereo.so \
libgstlsp-plugins-latency-meter.so \
libgstlsp-plugins-limiter-mono.so \
libgstlsp-plugins-limiter-stereo.so \
libgstlsp-plugins-loud-comp-mono.so \
libgstlsp-plugins-loud-comp-stereo.so \
libgstlsp-plugins-matcher-mono.so \
libgstlsp-plugins-matcher-stereo.so \
libgstlsp-plugins-mb-clipper-mono.so \
libgstlsp-plugins-mb-clipper-stereo.so \
libgstlsp-plugins-mb-compressor-lr.so \
libgstlsp-plugins-mb-compressor-mono.so \
libgstlsp-plugins-mb-compressor-ms.so \
libgstlsp-plugins-mb-compressor-stereo.so \
libgstlsp-plugins-mb-dyna-processor-lr.so \
libgstlsp-plugins-mb-dyna-processor-mono.so \
libgstlsp-plugins-mb-dyna-processor-ms.so \
libgstlsp-plugins-mb-dyna-processor-stereo.so \
libgstlsp-plugins-mb-expander-lr.so \
libgstlsp-plugins-mb-expander-mono.so \
libgstlsp-plugins-mb-expander-ms.so \
libgstlsp-plugins-mb-expander-stereo.so \
libgstlsp-plugins-mb-gate-lr.so \
libgstlsp-plugins-mb-gate-mono.so \
libgstlsp-plugins-mb-gate-ms.so \
libgstlsp-plugins-mb-gate-stereo.so \
libgstlsp-plugins-mb-limiter-mono.so \
libgstlsp-plugins-mb-limiter-stereo.so \
libgstlsp-plugins-mb-ringmod-sc-mono.so \
libgstlsp-plugins-mb-ringmod-sc-stereo.so \
libgstlsp-plugins-mixer-x16-mono.so \
libgstlsp-plugins-mixer-x16-stereo.so \
libgstlsp-plugins-mixer-x4-mono.so \
libgstlsp-plugins-mixer-x4-stereo.so \
libgstlsp-plugins-mixer-x8-mono.so \
libgstlsp-plugins-mixer-x8-stereo.so \
libgstlsp-plugins-multisampler-x12-do.so \
libgstlsp-plugins-multisampler-x12.so \
libgstlsp-plugins-multisampler-x24-do.so \
libgstlsp-plugins-multisampler-x24.so \
libgstlsp-plugins-multisampler-x48-do.so \
libgstlsp-plugins-multisampler-x48.so \
libgstlsp-plugins-noise-generator-x1.so \
libgstlsp-plugins-noise-generator-x2.so \
libgstlsp-plugins-noise-generator-x4.so \
libgstlsp-plugins-oscillator-mono.so \
libgstlsp-plugins-oscilloscope-x1.so \
libgstlsp-plugins-oscilloscope-x2.so \
libgstlsp-plugins-oscilloscope-x4.so \
libgstlsp-plugins-para-equalizer-x16-lr.so \
libgstlsp-plugins-para-equalizer-x16-mono.so \
libgstlsp-plugins-para-equalizer-x16-ms.so \
libgstlsp-plugins-para-equalizer-x16-stereo.so \
libgstlsp-plugins-para-equalizer-x32-lr.so \
libgstlsp-plugins-para-equalizer-x32-mono.so \
libgstlsp-plugins-para-equalizer-x32-ms.so \
libgstlsp-plugins-para-equalizer-x32-stereo.so \
libgstlsp-plugins-para-equalizer-x8-lr.so \
libgstlsp-plugins-para-equalizer-x8-mono.so \
libgstlsp-plugins-para-equalizer-x8-ms.so \
libgstlsp-plugins-para-equalizer-x8-stereo.so \
libgstlsp-plugins-phase-detector.so \
libgstlsp-plugins-phaser-mono.so \
libgstlsp-plugins-phaser-stereo.so \
libgstlsp-plugins-profiler-mono.so \
libgstlsp-plugins-profiler-stereo.so \
libgstlsp-plugins-referencer-mono.so \
libgstlsp-plugins-referencer-stereo.so \
libgstlsp-plugins-return-mono.so \
libgstlsp-plugins-return-stereo.so \
libgstlsp-plugins-ringmod-sc-mono.so \
libgstlsp-plugins-ringmod-sc-stereo.so \
libgstlsp-plugins-room-builder-mono.so \
libgstlsp-plugins-room-builder-stereo.so \
libgstlsp-plugins-sampler-mono.so \
libgstlsp-plugins-sampler-stereo.so \
libgstlsp-plugins-sc-autogain-mono.so \
libgstlsp-plugins-sc-autogain-stereo.so \
libgstlsp-plugins-sc-compressor-lr.so \
libgstlsp-plugins-sc-compressor-mono.so \
libgstlsp-plugins-sc-compressor-ms.so \
libgstlsp-plugins-sc-compressor-stereo.so \
libgstlsp-plugins-sc-deesser-mono.so \
libgstlsp-plugins-sc-deesser-stereo.so \
libgstlsp-plugins-sc-dyna-processor-lr.so \
libgstlsp-plugins-sc-dyna-processor-mono.so \
libgstlsp-plugins-sc-dyna-processor-ms.so \
libgstlsp-plugins-sc-dyna-processor-stereo.so \
libgstlsp-plugins-sc-expander-lr.so \
libgstlsp-plugins-sc-expander-mono.so \
libgstlsp-plugins-sc-expander-ms.so \
libgstlsp-plugins-sc-expander-stereo.so \
libgstlsp-plugins-sc-gate-lr.so \
libgstlsp-plugins-sc-gate-mono.so \
libgstlsp-plugins-sc-gate-ms.so \
libgstlsp-plugins-sc-gate-stereo.so \
libgstlsp-plugins-sc-gott-compressor-lr.so \
libgstlsp-plugins-sc-gott-compressor-mono.so \
libgstlsp-plugins-sc-gott-compressor-ms.so \
libgstlsp-plugins-sc-gott-compressor-stereo.so \
libgstlsp-plugins-sc-limiter-mono.so \
libgstlsp-plugins-sc-limiter-stereo.so \
libgstlsp-plugins-sc-matcher-mono.so \
libgstlsp-plugins-sc-matcher-stereo.so \
libgstlsp-plugins-sc-mb-compressor-lr.so \
libgstlsp-plugins-sc-mb-compressor-mono.so \
libgstlsp-plugins-sc-mb-compressor-ms.so \
libgstlsp-plugins-sc-mb-compressor-stereo.so \
libgstlsp-plugins-sc-mb-dyna-processor-lr.so \
libgstlsp-plugins-sc-mb-dyna-processor-mono.so \
libgstlsp-plugins-sc-mb-dyna-processor-ms.so \
libgstlsp-plugins-sc-mb-dyna-processor-stereo.so \
libgstlsp-plugins-sc-mb-expander-lr.so \
libgstlsp-plugins-sc-mb-expander-mono.so \
libgstlsp-plugins-sc-mb-expander-ms.so \
libgstlsp-plugins-sc-mb-expander-stereo.so \
libgstlsp-plugins-sc-mb-gate-lr.so \
libgstlsp-plugins-sc-mb-gate-mono.so \
libgstlsp-plugins-sc-mb-gate-ms.so \
libgstlsp-plugins-sc-mb-gate-stereo.so \
libgstlsp-plugins-sc-mb-limiter-mono.so \
libgstlsp-plugins-sc-mb-limiter-stereo.so \
libgstlsp-plugins-send-mono.so \
libgstlsp-plugins-send-stereo.so \
libgstlsp-plugins-slap-delay-mono.so \
libgstlsp-plugins-slap-delay-stereo.so \
libgstlsp-plugins-spectrum-analyzer-x1.so \
libgstlsp-plugins-spectrum-analyzer-x12.so \
libgstlsp-plugins-spectrum-analyzer-x16.so \
libgstlsp-plugins-spectrum-analyzer-x2.so \
libgstlsp-plugins-spectrum-analyzer-x4.so \
libgstlsp-plugins-spectrum-analyzer-x8.so \
libgstlsp-plugins-surge-filter-mono.so \
libgstlsp-plugins-surge-filter-stereo.so \
libgstlsp-plugins-trigger-midi-mono.so \
libgstlsp-plugins-trigger-midi-stereo.so \
libgstlsp-plugins-trigger-mono.so \
libgstlsp-plugins-trigger-stereo.so \
liblsp-plugins-gstreamer-1.2.34.so"

RDEPENDS:${PN} += "ld-linux-aarch64.so.1 \
libc.so.6 \
libglib-2.0.so.0 \
libgobject-2.0.so.0 \
libgstaudio-1.0.so.0 \
libgstreamer-1.0.so.0 \
libm.so.6 \
libsndfile.so.1 \
libstdc++.so.6 \
lsp-plugins-common"

inherit rpm
