SUMMARY = "OldStandard fonts with LaTeX support"
DESCRIPTION = "Old Standard is designed to reproduce the actual printing style \
of the early 20th century, reviving a specific type of Modern \
(classicist) style of serif typefaces, very commonly used in \
various editions of the late 19th and early 20th century, but \
almost completely abandoned later. The font supports \
typesetting of Old and Middle English, Old Icelandic, Cyrillic \
(with historical characters, extensions for Old Slavonic and \
localised forms), Gothic transliterations, critical editions of \
Classical Greek and Latin, and many more. This package works \
with TeX engines that directly support OpenType features, such \
as XeTeX and LuaTeX, as well as traditional engines such as TeX \
and pdfTeX."
LICENSE = "OFL-1.1"

PV = "2026.226.2.7asvn70421"

RPM_NAME = "texlive-oldstandard-2026.226.2.7asvn70421-61.2.noarch.rpm"
RPM_HASH = "94f6894bd2bfa65c61bc45ebd2083f10193aa377600f6bbc7c0fa412c7ed1c46399ed9d607910adf960fadd661a416ade99ef2a7281add8f866f980fdcc7b60f"
REPO_ARCH = "noarch"

RPROVIDES:${PN} += "tex-LGROldStandard-Inf.fd \
tex-LGROldStandard-LF.fd \
tex-LGROldStandard-OsF.fd \
tex-LGROldStandard-Sup.fd \
tex-LGROldStandard-TLF.fd \
tex-LGROldStandard-TOsF.fd \
tex-LY1OldStandard-Inf.fd \
tex-LY1OldStandard-LF.fd \
tex-LY1OldStandard-OsF.fd \
tex-LY1OldStandard-Sup.fd \
tex-LY1OldStandard-TLF.fd \
tex-LY1OldStandard-TOsF.fd \
tex-OT1OldStandard-Inf.fd \
tex-OT1OldStandard-LF.fd \
tex-OT1OldStandard-OsF.fd \
tex-OT1OldStandard-Sup.fd \
tex-OT1OldStandard-TLF.fd \
tex-OT1OldStandard-TOsF.fd \
tex-OldStandard-Bold-inf-lgr.tfm \
tex-OldStandard-Bold-inf-ly1.tfm \
tex-OldStandard-Bold-inf-ot1.tfm \
tex-OldStandard-Bold-inf-t1--base.tfm \
tex-OldStandard-Bold-inf-t1.tfm \
tex-OldStandard-Bold-inf-t1.vf \
tex-OldStandard-Bold-inf-t2a.tfm \
tex-OldStandard-Bold-inf-t2b.tfm \
tex-OldStandard-Bold-inf-t2c.tfm \
tex-OldStandard-Bold-lf-lgr.tfm \
tex-OldStandard-Bold-lf-ly1.tfm \
tex-OldStandard-Bold-lf-ot1.tfm \
tex-OldStandard-Bold-lf-sc-lgr.tfm \
tex-OldStandard-Bold-lf-sc-ly1--base.tfm \
tex-OldStandard-Bold-lf-sc-ly1.tfm \
tex-OldStandard-Bold-lf-sc-ly1.vf \
tex-OldStandard-Bold-lf-sc-ot1--base.tfm \
tex-OldStandard-Bold-lf-sc-ot1.tfm \
tex-OldStandard-Bold-lf-sc-ot1.vf \
tex-OldStandard-Bold-lf-sc-t1--base.tfm \
tex-OldStandard-Bold-lf-sc-t1.tfm \
tex-OldStandard-Bold-lf-sc-t1.vf \
tex-OldStandard-Bold-lf-sc-t2a--base.tfm \
tex-OldStandard-Bold-lf-sc-t2a.tfm \
tex-OldStandard-Bold-lf-sc-t2a.vf \
tex-OldStandard-Bold-lf-sc-t2b--base.tfm \
tex-OldStandard-Bold-lf-sc-t2b.tfm \
tex-OldStandard-Bold-lf-sc-t2b.vf \
tex-OldStandard-Bold-lf-sc-t2c--base.tfm \
tex-OldStandard-Bold-lf-sc-t2c.tfm \
tex-OldStandard-Bold-lf-sc-t2c.vf \
tex-OldStandard-Bold-lf-t1--base.tfm \
tex-OldStandard-Bold-lf-t1.tfm \
tex-OldStandard-Bold-lf-t1.vf \
tex-OldStandard-Bold-lf-t2a.tfm \
tex-OldStandard-Bold-lf-t2b.tfm \
tex-OldStandard-Bold-lf-t2c.tfm \
tex-OldStandard-Bold-lf-ts1--base.tfm \
tex-OldStandard-Bold-lf-ts1.tfm \
tex-OldStandard-Bold-lf-ts1.vf \
tex-OldStandard-Bold-osf-lgr.tfm \
tex-OldStandard-Bold-osf-ly1.tfm \
tex-OldStandard-Bold-osf-ot1.tfm \
tex-OldStandard-Bold-osf-sc-lgr.tfm \
tex-OldStandard-Bold-osf-sc-ly1--base.tfm \
tex-OldStandard-Bold-osf-sc-ly1.tfm \
tex-OldStandard-Bold-osf-sc-ly1.vf \
tex-OldStandard-Bold-osf-sc-ot1--base.tfm \
tex-OldStandard-Bold-osf-sc-ot1.tfm \
tex-OldStandard-Bold-osf-sc-ot1.vf \
tex-OldStandard-Bold-osf-sc-t1--base.tfm \
tex-OldStandard-Bold-osf-sc-t1.tfm \
tex-OldStandard-Bold-osf-sc-t1.vf \
tex-OldStandard-Bold-osf-sc-t2a--base.tfm \
tex-OldStandard-Bold-osf-sc-t2a.tfm \
tex-OldStandard-Bold-osf-sc-t2a.vf \
tex-OldStandard-Bold-osf-sc-t2b--base.tfm \
tex-OldStandard-Bold-osf-sc-t2b.tfm \
tex-OldStandard-Bold-osf-sc-t2b.vf \
tex-OldStandard-Bold-osf-sc-t2c--base.tfm \
tex-OldStandard-Bold-osf-sc-t2c.tfm \
tex-OldStandard-Bold-osf-sc-t2c.vf \
tex-OldStandard-Bold-osf-t1--base.tfm \
tex-OldStandard-Bold-osf-t1.tfm \
tex-OldStandard-Bold-osf-t1.vf \
tex-OldStandard-Bold-osf-t2a.tfm \
tex-OldStandard-Bold-osf-t2b.tfm \
tex-OldStandard-Bold-osf-t2c.tfm \
tex-OldStandard-Bold-osf-ts1--base.tfm \
tex-OldStandard-Bold-osf-ts1.tfm \
tex-OldStandard-Bold-osf-ts1.vf \
tex-OldStandard-Bold-sup-lgr.tfm \
tex-OldStandard-Bold-sup-ly1.tfm \
tex-OldStandard-Bold-sup-ot1.tfm \
tex-OldStandard-Bold-sup-t1--base.tfm \
tex-OldStandard-Bold-sup-t1.tfm \
tex-OldStandard-Bold-sup-t1.vf \
tex-OldStandard-Bold-sup-t2a.tfm \
tex-OldStandard-Bold-sup-t2b.tfm \
tex-OldStandard-Bold-sup-t2c.tfm \
tex-OldStandard-Bold-tlf-lgr.tfm \
tex-OldStandard-Bold-tlf-ly1.tfm \
tex-OldStandard-Bold-tlf-ot1.tfm \
tex-OldStandard-Bold-tlf-sc-lgr.tfm \
tex-OldStandard-Bold-tlf-sc-ly1--base.tfm \
tex-OldStandard-Bold-tlf-sc-ly1.tfm \
tex-OldStandard-Bold-tlf-sc-ly1.vf \
tex-OldStandard-Bold-tlf-sc-ot1--base.tfm \
tex-OldStandard-Bold-tlf-sc-ot1.tfm \
tex-OldStandard-Bold-tlf-sc-ot1.vf \
tex-OldStandard-Bold-tlf-sc-t1--base.tfm \
tex-OldStandard-Bold-tlf-sc-t1.tfm \
tex-OldStandard-Bold-tlf-sc-t1.vf \
tex-OldStandard-Bold-tlf-sc-t2a--base.tfm \
tex-OldStandard-Bold-tlf-sc-t2a.tfm \
tex-OldStandard-Bold-tlf-sc-t2a.vf \
tex-OldStandard-Bold-tlf-sc-t2b--base.tfm \
tex-OldStandard-Bold-tlf-sc-t2b.tfm \
tex-OldStandard-Bold-tlf-sc-t2b.vf \
tex-OldStandard-Bold-tlf-sc-t2c--base.tfm \
tex-OldStandard-Bold-tlf-sc-t2c.tfm \
tex-OldStandard-Bold-tlf-sc-t2c.vf \
tex-OldStandard-Bold-tlf-t1--base.tfm \
tex-OldStandard-Bold-tlf-t1.tfm \
tex-OldStandard-Bold-tlf-t1.vf \
tex-OldStandard-Bold-tlf-t2a.tfm \
tex-OldStandard-Bold-tlf-t2b.tfm \
tex-OldStandard-Bold-tlf-t2c.tfm \
tex-OldStandard-Bold-tlf-ts1--base.tfm \
tex-OldStandard-Bold-tlf-ts1.tfm \
tex-OldStandard-Bold-tlf-ts1.vf \
tex-OldStandard-Bold-tosf-lgr.tfm \
tex-OldStandard-Bold-tosf-ly1.tfm \
tex-OldStandard-Bold-tosf-ot1.tfm \
tex-OldStandard-Bold-tosf-sc-lgr.tfm \
tex-OldStandard-Bold-tosf-sc-ly1--base.tfm \
tex-OldStandard-Bold-tosf-sc-ly1.tfm \
tex-OldStandard-Bold-tosf-sc-ly1.vf \
tex-OldStandard-Bold-tosf-sc-ot1--base.tfm \
tex-OldStandard-Bold-tosf-sc-ot1.tfm \
tex-OldStandard-Bold-tosf-sc-ot1.vf \
tex-OldStandard-Bold-tosf-sc-t1--base.tfm \
tex-OldStandard-Bold-tosf-sc-t1.tfm \
tex-OldStandard-Bold-tosf-sc-t1.vf \
tex-OldStandard-Bold-tosf-sc-t2a--base.tfm \
tex-OldStandard-Bold-tosf-sc-t2a.tfm \
tex-OldStandard-Bold-tosf-sc-t2a.vf \
tex-OldStandard-Bold-tosf-sc-t2b--base.tfm \
tex-OldStandard-Bold-tosf-sc-t2b.tfm \
tex-OldStandard-Bold-tosf-sc-t2b.vf \
tex-OldStandard-Bold-tosf-sc-t2c--base.tfm \
tex-OldStandard-Bold-tosf-sc-t2c.tfm \
tex-OldStandard-Bold-tosf-sc-t2c.vf \
tex-OldStandard-Bold-tosf-t1--base.tfm \
tex-OldStandard-Bold-tosf-t1.tfm \
tex-OldStandard-Bold-tosf-t1.vf \
tex-OldStandard-Bold-tosf-t2a.tfm \
tex-OldStandard-Bold-tosf-t2b.tfm \
tex-OldStandard-Bold-tosf-t2c.tfm \
tex-OldStandard-Bold-tosf-ts1--base.tfm \
tex-OldStandard-Bold-tosf-ts1.tfm \
tex-OldStandard-Bold-tosf-ts1.vf \
tex-OldStandard-BoldItalic-inf-lgr.tfm \
tex-OldStandard-BoldItalic-inf-ly1.tfm \
tex-OldStandard-BoldItalic-inf-ot1.tfm \
tex-OldStandard-BoldItalic-inf-t1--base.tfm \
tex-OldStandard-BoldItalic-inf-t1.tfm \
tex-OldStandard-BoldItalic-inf-t1.vf \
tex-OldStandard-BoldItalic-inf-t2a.tfm \
tex-OldStandard-BoldItalic-inf-t2b.tfm \
tex-OldStandard-BoldItalic-inf-t2c.tfm \
tex-OldStandard-BoldItalic-lf-lgr.tfm \
tex-OldStandard-BoldItalic-lf-ly1.tfm \
tex-OldStandard-BoldItalic-lf-ot1.tfm \
tex-OldStandard-BoldItalic-lf-sc-lgr.tfm \
tex-OldStandard-BoldItalic-lf-sc-ly1--base.tfm \
tex-OldStandard-BoldItalic-lf-sc-ly1.tfm \
tex-OldStandard-BoldItalic-lf-sc-ly1.vf \
tex-OldStandard-BoldItalic-lf-sc-ot1--base.tfm \
tex-OldStandard-BoldItalic-lf-sc-ot1.tfm \
tex-OldStandard-BoldItalic-lf-sc-ot1.vf \
tex-OldStandard-BoldItalic-lf-sc-t1--base.tfm \
tex-OldStandard-BoldItalic-lf-sc-t1.tfm \
tex-OldStandard-BoldItalic-lf-sc-t1.vf \
tex-OldStandard-BoldItalic-lf-sc-t2a--base.tfm \
tex-OldStandard-BoldItalic-lf-sc-t2a.tfm \
tex-OldStandard-BoldItalic-lf-sc-t2a.vf \
tex-OldStandard-BoldItalic-lf-sc-t2b--base.tfm \
tex-OldStandard-BoldItalic-lf-sc-t2b.tfm \
tex-OldStandard-BoldItalic-lf-sc-t2b.vf \
tex-OldStandard-BoldItalic-lf-sc-t2c--base.tfm \
tex-OldStandard-BoldItalic-lf-sc-t2c.tfm \
tex-OldStandard-BoldItalic-lf-sc-t2c.vf \
tex-OldStandard-BoldItalic-lf-t1--base.tfm \
tex-OldStandard-BoldItalic-lf-t1.tfm \
tex-OldStandard-BoldItalic-lf-t1.vf \
tex-OldStandard-BoldItalic-lf-t2a.tfm \
tex-OldStandard-BoldItalic-lf-t2b.tfm \
tex-OldStandard-BoldItalic-lf-t2c.tfm \
tex-OldStandard-BoldItalic-lf-ts1--base.tfm \
tex-OldStandard-BoldItalic-lf-ts1.tfm \
tex-OldStandard-BoldItalic-lf-ts1.vf \
tex-OldStandard-BoldItalic-osf-lgr.tfm \
tex-OldStandard-BoldItalic-osf-ly1.tfm \
tex-OldStandard-BoldItalic-osf-ot1.tfm \
tex-OldStandard-BoldItalic-osf-sc-lgr.tfm \
tex-OldStandard-BoldItalic-osf-sc-ly1--base.tfm \
tex-OldStandard-BoldItalic-osf-sc-ly1.tfm \
tex-OldStandard-BoldItalic-osf-sc-ly1.vf \
tex-OldStandard-BoldItalic-osf-sc-ot1--base.tfm \
tex-OldStandard-BoldItalic-osf-sc-ot1.tfm \
tex-OldStandard-BoldItalic-osf-sc-ot1.vf \
tex-OldStandard-BoldItalic-osf-sc-t1--base.tfm \
tex-OldStandard-BoldItalic-osf-sc-t1.tfm \
tex-OldStandard-BoldItalic-osf-sc-t1.vf \
tex-OldStandard-BoldItalic-osf-sc-t2a--base.tfm \
tex-OldStandard-BoldItalic-osf-sc-t2a.tfm \
tex-OldStandard-BoldItalic-osf-sc-t2a.vf \
tex-OldStandard-BoldItalic-osf-sc-t2b--base.tfm \
tex-OldStandard-BoldItalic-osf-sc-t2b.tfm \
tex-OldStandard-BoldItalic-osf-sc-t2b.vf \
tex-OldStandard-BoldItalic-osf-sc-t2c--base.tfm \
tex-OldStandard-BoldItalic-osf-sc-t2c.tfm \
tex-OldStandard-BoldItalic-osf-sc-t2c.vf \
tex-OldStandard-BoldItalic-osf-t1--base.tfm \
tex-OldStandard-BoldItalic-osf-t1.tfm \
tex-OldStandard-BoldItalic-osf-t1.vf \
tex-OldStandard-BoldItalic-osf-t2a.tfm \
tex-OldStandard-BoldItalic-osf-t2b.tfm \
tex-OldStandard-BoldItalic-osf-t2c.tfm \
tex-OldStandard-BoldItalic-osf-ts1--base.tfm \
tex-OldStandard-BoldItalic-osf-ts1.tfm \
tex-OldStandard-BoldItalic-osf-ts1.vf \
tex-OldStandard-BoldItalic-sup-lgr.tfm \
tex-OldStandard-BoldItalic-sup-ly1.tfm \
tex-OldStandard-BoldItalic-sup-ot1.tfm \
tex-OldStandard-BoldItalic-sup-t1--base.tfm \
tex-OldStandard-BoldItalic-sup-t1.tfm \
tex-OldStandard-BoldItalic-sup-t1.vf \
tex-OldStandard-BoldItalic-sup-t2a.tfm \
tex-OldStandard-BoldItalic-sup-t2b.tfm \
tex-OldStandard-BoldItalic-sup-t2c.tfm \
tex-OldStandard-BoldItalic-tlf-lgr.tfm \
tex-OldStandard-BoldItalic-tlf-ly1.tfm \
tex-OldStandard-BoldItalic-tlf-ot1.tfm \
tex-OldStandard-BoldItalic-tlf-sc-lgr.tfm \
tex-OldStandard-BoldItalic-tlf-sc-ly1--base.tfm \
tex-OldStandard-BoldItalic-tlf-sc-ly1.tfm \
tex-OldStandard-BoldItalic-tlf-sc-ly1.vf \
tex-OldStandard-BoldItalic-tlf-sc-ot1--base.tfm \
tex-OldStandard-BoldItalic-tlf-sc-ot1.tfm \
tex-OldStandard-BoldItalic-tlf-sc-ot1.vf \
tex-OldStandard-BoldItalic-tlf-sc-t1--base.tfm \
tex-OldStandard-BoldItalic-tlf-sc-t1.tfm \
tex-OldStandard-BoldItalic-tlf-sc-t1.vf \
tex-OldStandard-BoldItalic-tlf-sc-t2a--base.tfm \
tex-OldStandard-BoldItalic-tlf-sc-t2a.tfm \
tex-OldStandard-BoldItalic-tlf-sc-t2a.vf \
tex-OldStandard-BoldItalic-tlf-sc-t2b--base.tfm \
tex-OldStandard-BoldItalic-tlf-sc-t2b.tfm \
tex-OldStandard-BoldItalic-tlf-sc-t2b.vf \
tex-OldStandard-BoldItalic-tlf-sc-t2c--base.tfm \
tex-OldStandard-BoldItalic-tlf-sc-t2c.tfm \
tex-OldStandard-BoldItalic-tlf-sc-t2c.vf \
tex-OldStandard-BoldItalic-tlf-t1--base.tfm \
tex-OldStandard-BoldItalic-tlf-t1.tfm \
tex-OldStandard-BoldItalic-tlf-t1.vf \
tex-OldStandard-BoldItalic-tlf-t2a.tfm \
tex-OldStandard-BoldItalic-tlf-t2b.tfm \
tex-OldStandard-BoldItalic-tlf-t2c.tfm \
tex-OldStandard-BoldItalic-tlf-ts1--base.tfm \
tex-OldStandard-BoldItalic-tlf-ts1.tfm \
tex-OldStandard-BoldItalic-tlf-ts1.vf \
tex-OldStandard-BoldItalic-tosf-lgr.tfm \
tex-OldStandard-BoldItalic-tosf-ly1.tfm \
tex-OldStandard-BoldItalic-tosf-ot1.tfm \
tex-OldStandard-BoldItalic-tosf-sc-lgr.tfm \
tex-OldStandard-BoldItalic-tosf-sc-ly1--base.tfm \
tex-OldStandard-BoldItalic-tosf-sc-ly1.tfm \
tex-OldStandard-BoldItalic-tosf-sc-ly1.vf \
tex-OldStandard-BoldItalic-tosf-sc-ot1--base.tfm \
tex-OldStandard-BoldItalic-tosf-sc-ot1.tfm \
tex-OldStandard-BoldItalic-tosf-sc-ot1.vf \
tex-OldStandard-BoldItalic-tosf-sc-t1--base.tfm \
tex-OldStandard-BoldItalic-tosf-sc-t1.tfm \
tex-OldStandard-BoldItalic-tosf-sc-t1.vf \
tex-OldStandard-BoldItalic-tosf-sc-t2a--base.tfm \
tex-OldStandard-BoldItalic-tosf-sc-t2a.tfm \
tex-OldStandard-BoldItalic-tosf-sc-t2a.vf \
tex-OldStandard-BoldItalic-tosf-sc-t2b--base.tfm \
tex-OldStandard-BoldItalic-tosf-sc-t2b.tfm \
tex-OldStandard-BoldItalic-tosf-sc-t2b.vf \
tex-OldStandard-BoldItalic-tosf-sc-t2c--base.tfm \
tex-OldStandard-BoldItalic-tosf-sc-t2c.tfm \
tex-OldStandard-BoldItalic-tosf-sc-t2c.vf \
tex-OldStandard-BoldItalic-tosf-t1--base.tfm \
tex-OldStandard-BoldItalic-tosf-t1.tfm \
tex-OldStandard-BoldItalic-tosf-t1.vf \
tex-OldStandard-BoldItalic-tosf-t2a.tfm \
tex-OldStandard-BoldItalic-tosf-t2b.tfm \
tex-OldStandard-BoldItalic-tosf-t2c.tfm \
tex-OldStandard-BoldItalic-tosf-ts1--base.tfm \
tex-OldStandard-BoldItalic-tosf-ts1.tfm \
tex-OldStandard-BoldItalic-tosf-ts1.vf \
tex-OldStandard-Italic-inf-lgr.tfm \
tex-OldStandard-Italic-inf-ly1.tfm \
tex-OldStandard-Italic-inf-ot1.tfm \
tex-OldStandard-Italic-inf-t1--base.tfm \
tex-OldStandard-Italic-inf-t1.tfm \
tex-OldStandard-Italic-inf-t1.vf \
tex-OldStandard-Italic-inf-t2a.tfm \
tex-OldStandard-Italic-inf-t2b.tfm \
tex-OldStandard-Italic-inf-t2c.tfm \
tex-OldStandard-Italic-lf-lgr.tfm \
tex-OldStandard-Italic-lf-ly1.tfm \
tex-OldStandard-Italic-lf-ot1.tfm \
tex-OldStandard-Italic-lf-sc-lgr.tfm \
tex-OldStandard-Italic-lf-sc-ly1--base.tfm \
tex-OldStandard-Italic-lf-sc-ly1.tfm \
tex-OldStandard-Italic-lf-sc-ly1.vf \
tex-OldStandard-Italic-lf-sc-ot1--base.tfm \
tex-OldStandard-Italic-lf-sc-ot1.tfm \
tex-OldStandard-Italic-lf-sc-ot1.vf \
tex-OldStandard-Italic-lf-sc-t1--base.tfm \
tex-OldStandard-Italic-lf-sc-t1.tfm \
tex-OldStandard-Italic-lf-sc-t1.vf \
tex-OldStandard-Italic-lf-sc-t2a--base.tfm \
tex-OldStandard-Italic-lf-sc-t2a.tfm \
tex-OldStandard-Italic-lf-sc-t2a.vf \
tex-OldStandard-Italic-lf-sc-t2b--base.tfm \
tex-OldStandard-Italic-lf-sc-t2b.tfm \
tex-OldStandard-Italic-lf-sc-t2b.vf \
tex-OldStandard-Italic-lf-sc-t2c--base.tfm \
tex-OldStandard-Italic-lf-sc-t2c.tfm \
tex-OldStandard-Italic-lf-sc-t2c.vf \
tex-OldStandard-Italic-lf-t1--base.tfm \
tex-OldStandard-Italic-lf-t1.tfm \
tex-OldStandard-Italic-lf-t1.vf \
tex-OldStandard-Italic-lf-t2a.tfm \
tex-OldStandard-Italic-lf-t2b.tfm \
tex-OldStandard-Italic-lf-t2c.tfm \
tex-OldStandard-Italic-lf-ts1--base.tfm \
tex-OldStandard-Italic-lf-ts1.tfm \
tex-OldStandard-Italic-lf-ts1.vf \
tex-OldStandard-Italic-osf-lgr.tfm \
tex-OldStandard-Italic-osf-ly1.tfm \
tex-OldStandard-Italic-osf-ot1.tfm \
tex-OldStandard-Italic-osf-sc-lgr.tfm \
tex-OldStandard-Italic-osf-sc-ly1--base.tfm \
tex-OldStandard-Italic-osf-sc-ly1.tfm \
tex-OldStandard-Italic-osf-sc-ly1.vf \
tex-OldStandard-Italic-osf-sc-ot1--base.tfm \
tex-OldStandard-Italic-osf-sc-ot1.tfm \
tex-OldStandard-Italic-osf-sc-ot1.vf \
tex-OldStandard-Italic-osf-sc-t1--base.tfm \
tex-OldStandard-Italic-osf-sc-t1.tfm \
tex-OldStandard-Italic-osf-sc-t1.vf \
tex-OldStandard-Italic-osf-sc-t2a--base.tfm \
tex-OldStandard-Italic-osf-sc-t2a.tfm \
tex-OldStandard-Italic-osf-sc-t2a.vf \
tex-OldStandard-Italic-osf-sc-t2b--base.tfm \
tex-OldStandard-Italic-osf-sc-t2b.tfm \
tex-OldStandard-Italic-osf-sc-t2b.vf \
tex-OldStandard-Italic-osf-sc-t2c--base.tfm \
tex-OldStandard-Italic-osf-sc-t2c.tfm \
tex-OldStandard-Italic-osf-sc-t2c.vf \
tex-OldStandard-Italic-osf-t1--base.tfm \
tex-OldStandard-Italic-osf-t1.tfm \
tex-OldStandard-Italic-osf-t1.vf \
tex-OldStandard-Italic-osf-t2a.tfm \
tex-OldStandard-Italic-osf-t2b.tfm \
tex-OldStandard-Italic-osf-t2c.tfm \
tex-OldStandard-Italic-osf-ts1--base.tfm \
tex-OldStandard-Italic-osf-ts1.tfm \
tex-OldStandard-Italic-osf-ts1.vf \
tex-OldStandard-Italic-sup-lgr.tfm \
tex-OldStandard-Italic-sup-ly1.tfm \
tex-OldStandard-Italic-sup-ot1.tfm \
tex-OldStandard-Italic-sup-t1--base.tfm \
tex-OldStandard-Italic-sup-t1.tfm \
tex-OldStandard-Italic-sup-t1.vf \
tex-OldStandard-Italic-sup-t2a.tfm \
tex-OldStandard-Italic-sup-t2b.tfm \
tex-OldStandard-Italic-sup-t2c.tfm \
tex-OldStandard-Italic-tlf-lgr.tfm \
tex-OldStandard-Italic-tlf-ly1.tfm \
tex-OldStandard-Italic-tlf-ot1.tfm \
tex-OldStandard-Italic-tlf-sc-lgr.tfm \
tex-OldStandard-Italic-tlf-sc-ly1--base.tfm \
tex-OldStandard-Italic-tlf-sc-ly1.tfm \
tex-OldStandard-Italic-tlf-sc-ly1.vf \
tex-OldStandard-Italic-tlf-sc-ot1--base.tfm \
tex-OldStandard-Italic-tlf-sc-ot1.tfm \
tex-OldStandard-Italic-tlf-sc-ot1.vf \
tex-OldStandard-Italic-tlf-sc-t1--base.tfm \
tex-OldStandard-Italic-tlf-sc-t1.tfm \
tex-OldStandard-Italic-tlf-sc-t1.vf \
tex-OldStandard-Italic-tlf-sc-t2a--base.tfm \
tex-OldStandard-Italic-tlf-sc-t2a.tfm \
tex-OldStandard-Italic-tlf-sc-t2a.vf \
tex-OldStandard-Italic-tlf-sc-t2b--base.tfm \
tex-OldStandard-Italic-tlf-sc-t2b.tfm \
tex-OldStandard-Italic-tlf-sc-t2b.vf \
tex-OldStandard-Italic-tlf-sc-t2c--base.tfm \
tex-OldStandard-Italic-tlf-sc-t2c.tfm \
tex-OldStandard-Italic-tlf-sc-t2c.vf \
tex-OldStandard-Italic-tlf-t1--base.tfm \
tex-OldStandard-Italic-tlf-t1.tfm \
tex-OldStandard-Italic-tlf-t1.vf \
tex-OldStandard-Italic-tlf-t2a.tfm \
tex-OldStandard-Italic-tlf-t2b.tfm \
tex-OldStandard-Italic-tlf-t2c.tfm \
tex-OldStandard-Italic-tlf-ts1--base.tfm \
tex-OldStandard-Italic-tlf-ts1.tfm \
tex-OldStandard-Italic-tlf-ts1.vf \
tex-OldStandard-Italic-tosf-lgr.tfm \
tex-OldStandard-Italic-tosf-ly1.tfm \
tex-OldStandard-Italic-tosf-ot1.tfm \
tex-OldStandard-Italic-tosf-sc-lgr.tfm \
tex-OldStandard-Italic-tosf-sc-ly1--base.tfm \
tex-OldStandard-Italic-tosf-sc-ly1.tfm \
tex-OldStandard-Italic-tosf-sc-ly1.vf \
tex-OldStandard-Italic-tosf-sc-ot1--base.tfm \
tex-OldStandard-Italic-tosf-sc-ot1.tfm \
tex-OldStandard-Italic-tosf-sc-ot1.vf \
tex-OldStandard-Italic-tosf-sc-t1--base.tfm \
tex-OldStandard-Italic-tosf-sc-t1.tfm \
tex-OldStandard-Italic-tosf-sc-t1.vf \
tex-OldStandard-Italic-tosf-sc-t2a--base.tfm \
tex-OldStandard-Italic-tosf-sc-t2a.tfm \
tex-OldStandard-Italic-tosf-sc-t2a.vf \
tex-OldStandard-Italic-tosf-sc-t2b--base.tfm \
tex-OldStandard-Italic-tosf-sc-t2b.tfm \
tex-OldStandard-Italic-tosf-sc-t2b.vf \
tex-OldStandard-Italic-tosf-sc-t2c--base.tfm \
tex-OldStandard-Italic-tosf-sc-t2c.tfm \
tex-OldStandard-Italic-tosf-sc-t2c.vf \
tex-OldStandard-Italic-tosf-t1--base.tfm \
tex-OldStandard-Italic-tosf-t1.tfm \
tex-OldStandard-Italic-tosf-t1.vf \
tex-OldStandard-Italic-tosf-t2a.tfm \
tex-OldStandard-Italic-tosf-t2b.tfm \
tex-OldStandard-Italic-tosf-t2c.tfm \
tex-OldStandard-Italic-tosf-ts1--base.tfm \
tex-OldStandard-Italic-tosf-ts1.tfm \
tex-OldStandard-Italic-tosf-ts1.vf \
tex-OldStandard-Regular-inf-lgr.tfm \
tex-OldStandard-Regular-inf-ly1.tfm \
tex-OldStandard-Regular-inf-ot1.tfm \
tex-OldStandard-Regular-inf-t1--base.tfm \
tex-OldStandard-Regular-inf-t1.tfm \
tex-OldStandard-Regular-inf-t1.vf \
tex-OldStandard-Regular-inf-t2a.tfm \
tex-OldStandard-Regular-inf-t2b.tfm \
tex-OldStandard-Regular-inf-t2c.tfm \
tex-OldStandard-Regular-lf-lgr.tfm \
tex-OldStandard-Regular-lf-ly1.tfm \
tex-OldStandard-Regular-lf-ot1.tfm \
tex-OldStandard-Regular-lf-sc-lgr.tfm \
tex-OldStandard-Regular-lf-sc-ly1--base.tfm \
tex-OldStandard-Regular-lf-sc-ly1.tfm \
tex-OldStandard-Regular-lf-sc-ly1.vf \
tex-OldStandard-Regular-lf-sc-ot1--base.tfm \
tex-OldStandard-Regular-lf-sc-ot1.tfm \
tex-OldStandard-Regular-lf-sc-ot1.vf \
tex-OldStandard-Regular-lf-sc-t1--base.tfm \
tex-OldStandard-Regular-lf-sc-t1.tfm \
tex-OldStandard-Regular-lf-sc-t1.vf \
tex-OldStandard-Regular-lf-sc-t2a--base.tfm \
tex-OldStandard-Regular-lf-sc-t2a.tfm \
tex-OldStandard-Regular-lf-sc-t2a.vf \
tex-OldStandard-Regular-lf-sc-t2b--base.tfm \
tex-OldStandard-Regular-lf-sc-t2b.tfm \
tex-OldStandard-Regular-lf-sc-t2b.vf \
tex-OldStandard-Regular-lf-sc-t2c--base.tfm \
tex-OldStandard-Regular-lf-sc-t2c.tfm \
tex-OldStandard-Regular-lf-sc-t2c.vf \
tex-OldStandard-Regular-lf-t1--base.tfm \
tex-OldStandard-Regular-lf-t1.tfm \
tex-OldStandard-Regular-lf-t1.vf \
tex-OldStandard-Regular-lf-t2a.tfm \
tex-OldStandard-Regular-lf-t2b.tfm \
tex-OldStandard-Regular-lf-t2c.tfm \
tex-OldStandard-Regular-lf-ts1--base.tfm \
tex-OldStandard-Regular-lf-ts1.tfm \
tex-OldStandard-Regular-lf-ts1.vf \
tex-OldStandard-Regular-osf-lgr.tfm \
tex-OldStandard-Regular-osf-ly1.tfm \
tex-OldStandard-Regular-osf-ot1.tfm \
tex-OldStandard-Regular-osf-sc-lgr.tfm \
tex-OldStandard-Regular-osf-sc-ly1--base.tfm \
tex-OldStandard-Regular-osf-sc-ly1.tfm \
tex-OldStandard-Regular-osf-sc-ly1.vf \
tex-OldStandard-Regular-osf-sc-ot1--base.tfm \
tex-OldStandard-Regular-osf-sc-ot1.tfm \
tex-OldStandard-Regular-osf-sc-ot1.vf \
tex-OldStandard-Regular-osf-sc-t1--base.tfm \
tex-OldStandard-Regular-osf-sc-t1.tfm \
tex-OldStandard-Regular-osf-sc-t1.vf \
tex-OldStandard-Regular-osf-sc-t2a--base.tfm \
tex-OldStandard-Regular-osf-sc-t2a.tfm \
tex-OldStandard-Regular-osf-sc-t2a.vf \
tex-OldStandard-Regular-osf-sc-t2b--base.tfm \
tex-OldStandard-Regular-osf-sc-t2b.tfm \
tex-OldStandard-Regular-osf-sc-t2b.vf \
tex-OldStandard-Regular-osf-sc-t2c--base.tfm \
tex-OldStandard-Regular-osf-sc-t2c.tfm \
tex-OldStandard-Regular-osf-sc-t2c.vf \
tex-OldStandard-Regular-osf-t1--base.tfm \
tex-OldStandard-Regular-osf-t1.tfm \
tex-OldStandard-Regular-osf-t1.vf \
tex-OldStandard-Regular-osf-t2a.tfm \
tex-OldStandard-Regular-osf-t2b.tfm \
tex-OldStandard-Regular-osf-t2c.tfm \
tex-OldStandard-Regular-osf-ts1--base.tfm \
tex-OldStandard-Regular-osf-ts1.tfm \
tex-OldStandard-Regular-osf-ts1.vf \
tex-OldStandard-Regular-sup-lgr.tfm \
tex-OldStandard-Regular-sup-ly1.tfm \
tex-OldStandard-Regular-sup-ot1.tfm \
tex-OldStandard-Regular-sup-t1--base.tfm \
tex-OldStandard-Regular-sup-t1.tfm \
tex-OldStandard-Regular-sup-t1.vf \
tex-OldStandard-Regular-sup-t2a.tfm \
tex-OldStandard-Regular-sup-t2b.tfm \
tex-OldStandard-Regular-sup-t2c.tfm \
tex-OldStandard-Regular-tlf-lgr.tfm \
tex-OldStandard-Regular-tlf-ly1.tfm \
tex-OldStandard-Regular-tlf-ot1.tfm \
tex-OldStandard-Regular-tlf-sc-lgr.tfm \
tex-OldStandard-Regular-tlf-sc-ly1--base.tfm \
tex-OldStandard-Regular-tlf-sc-ly1.tfm \
tex-OldStandard-Regular-tlf-sc-ly1.vf \
tex-OldStandard-Regular-tlf-sc-ot1--base.tfm \
tex-OldStandard-Regular-tlf-sc-ot1.tfm \
tex-OldStandard-Regular-tlf-sc-ot1.vf \
tex-OldStandard-Regular-tlf-sc-t1--base.tfm \
tex-OldStandard-Regular-tlf-sc-t1.tfm \
tex-OldStandard-Regular-tlf-sc-t1.vf \
tex-OldStandard-Regular-tlf-sc-t2a--base.tfm \
tex-OldStandard-Regular-tlf-sc-t2a.tfm \
tex-OldStandard-Regular-tlf-sc-t2a.vf \
tex-OldStandard-Regular-tlf-sc-t2b--base.tfm \
tex-OldStandard-Regular-tlf-sc-t2b.tfm \
tex-OldStandard-Regular-tlf-sc-t2b.vf \
tex-OldStandard-Regular-tlf-sc-t2c--base.tfm \
tex-OldStandard-Regular-tlf-sc-t2c.tfm \
tex-OldStandard-Regular-tlf-sc-t2c.vf \
tex-OldStandard-Regular-tlf-t1--base.tfm \
tex-OldStandard-Regular-tlf-t1.tfm \
tex-OldStandard-Regular-tlf-t1.vf \
tex-OldStandard-Regular-tlf-t2a.tfm \
tex-OldStandard-Regular-tlf-t2b.tfm \
tex-OldStandard-Regular-tlf-t2c.tfm \
tex-OldStandard-Regular-tlf-ts1--base.tfm \
tex-OldStandard-Regular-tlf-ts1.tfm \
tex-OldStandard-Regular-tlf-ts1.vf \
tex-OldStandard-Regular-tosf-lgr.tfm \
tex-OldStandard-Regular-tosf-ly1.tfm \
tex-OldStandard-Regular-tosf-ot1.tfm \
tex-OldStandard-Regular-tosf-sc-lgr.tfm \
tex-OldStandard-Regular-tosf-sc-ly1--base.tfm \
tex-OldStandard-Regular-tosf-sc-ly1.tfm \
tex-OldStandard-Regular-tosf-sc-ly1.vf \
tex-OldStandard-Regular-tosf-sc-ot1--base.tfm \
tex-OldStandard-Regular-tosf-sc-ot1.tfm \
tex-OldStandard-Regular-tosf-sc-ot1.vf \
tex-OldStandard-Regular-tosf-sc-t1--base.tfm \
tex-OldStandard-Regular-tosf-sc-t1.tfm \
tex-OldStandard-Regular-tosf-sc-t1.vf \
tex-OldStandard-Regular-tosf-sc-t2a--base.tfm \
tex-OldStandard-Regular-tosf-sc-t2a.tfm \
tex-OldStandard-Regular-tosf-sc-t2a.vf \
tex-OldStandard-Regular-tosf-sc-t2b--base.tfm \
tex-OldStandard-Regular-tosf-sc-t2b.tfm \
tex-OldStandard-Regular-tosf-sc-t2b.vf \
tex-OldStandard-Regular-tosf-sc-t2c--base.tfm \
tex-OldStandard-Regular-tosf-sc-t2c.tfm \
tex-OldStandard-Regular-tosf-sc-t2c.vf \
tex-OldStandard-Regular-tosf-t1--base.tfm \
tex-OldStandard-Regular-tosf-t1.tfm \
tex-OldStandard-Regular-tosf-t1.vf \
tex-OldStandard-Regular-tosf-t2a.tfm \
tex-OldStandard-Regular-tosf-t2b.tfm \
tex-OldStandard-Regular-tosf-t2c.tfm \
tex-OldStandard-Regular-tosf-ts1--base.tfm \
tex-OldStandard-Regular-tosf-ts1.tfm \
tex-OldStandard-Regular-tosf-ts1.vf \
tex-OldStandard.map \
tex-OldStandard.sty \
tex-T1OldStandard-Inf.fd \
tex-T1OldStandard-LF.fd \
tex-T1OldStandard-OsF.fd \
tex-T1OldStandard-Sup.fd \
tex-T1OldStandard-TLF.fd \
tex-T1OldStandard-TOsF.fd \
tex-T2AOldStandard-Inf.fd \
tex-T2AOldStandard-LF.fd \
tex-T2AOldStandard-OsF.fd \
tex-T2AOldStandard-Sup.fd \
tex-T2AOldStandard-TLF.fd \
tex-T2AOldStandard-TOsF.fd \
tex-T2BOldStandard-Inf.fd \
tex-T2BOldStandard-LF.fd \
tex-T2BOldStandard-OsF.fd \
tex-T2BOldStandard-Sup.fd \
tex-T2BOldStandard-TLF.fd \
tex-T2BOldStandard-TOsF.fd \
tex-T2COldStandard-Inf.fd \
tex-T2COldStandard-LF.fd \
tex-T2COldStandard-OsF.fd \
tex-T2COldStandard-Sup.fd \
tex-T2COldStandard-TLF.fd \
tex-T2COldStandard-TOsF.fd \
tex-TS1OldStandard-LF.fd \
tex-TS1OldStandard-OsF.fd \
tex-TS1OldStandard-TLF.fd \
tex-TS1OldStandard-TOsF.fd \
tex-ostd-2deiwc.enc \
tex-ostd-2zpmqe.enc \
tex-ostd-3r5o6v.enc \
tex-ostd-4gryax.enc \
tex-ostd-4hnb2u.enc \
tex-ostd-4ubwsr.enc \
tex-ostd-4xjl64.enc \
tex-ostd-527apm.enc \
tex-ostd-575fq6.enc \
tex-ostd-5nnl5u.enc \
tex-ostd-5rtehp.enc \
tex-ostd-5v66ff.enc \
tex-ostd-5whbgv.enc \
tex-ostd-6nwgzp.enc \
tex-ostd-6wre6c.enc \
tex-ostd-6xqr26.enc \
tex-ostd-7gnfsl.enc \
tex-ostd-7n5i5q.enc \
tex-ostd-7y46wx.enc \
tex-ostd-a443ms.enc \
tex-ostd-afiklh.enc \
tex-ostd-angj2q.enc \
tex-ostd-aqd6wu.enc \
tex-ostd-asyrwx.enc \
tex-ostd-atz7lk.enc \
tex-ostd-azf2jb.enc \
tex-ostd-b2vwpe.enc \
tex-ostd-bgjn75.enc \
tex-ostd-bjztjg.enc \
tex-ostd-bqhfkj.enc \
tex-ostd-c6qnrb.enc \
tex-ostd-ci7iv4.enc \
tex-ostd-dkkaom.enc \
tex-ostd-dqfezc.enc \
tex-ostd-e6nyrk.enc \
tex-ostd-eyrxhh.enc \
tex-ostd-f7vsty.enc \
tex-ostd-fjf63q.enc \
tex-ostd-g5ynre.enc \
tex-ostd-h6u75t.enc \
tex-ostd-hb32qs.enc \
tex-ostd-hh4e6w.enc \
tex-ostd-hn3tfb.enc \
tex-ostd-hsswj7.enc \
tex-ostd-hzb6ae.enc \
tex-ostd-i5zx33.enc \
tex-ostd-im33zw.enc \
tex-ostd-itaeek.enc \
tex-ostd-iweqgd.enc \
tex-ostd-jbzagu.enc \
tex-ostd-jsesfs.enc \
tex-ostd-jybbtr.enc \
tex-ostd-k2izil.enc \
tex-ostd-kb3yb7.enc \
tex-ostd-khmigf.enc \
tex-ostd-lnckqk.enc \
tex-ostd-lr5cn2.enc \
tex-ostd-lzdf4k.enc \
tex-ostd-m5okja.enc \
tex-ostd-mknljf.enc \
tex-ostd-nbavde.enc \
tex-ostd-niq2ca.enc \
tex-ostd-nlwaka.enc \
tex-ostd-ntnv4i.enc \
tex-ostd-o47vxq.enc \
tex-ostd-obie6d.enc \
tex-ostd-ojlsna.enc \
tex-ostd-onlb5v.enc \
tex-ostd-op3it5.enc \
tex-ostd-oq4ymx.enc \
tex-ostd-ottywi.enc \
tex-ostd-ou25yo.enc \
tex-ostd-p56nol.enc \
tex-ostd-pczwbl.enc \
tex-ostd-pkraxu.enc \
tex-ostd-ppxooj.enc \
tex-ostd-q2bw7q.enc \
tex-ostd-qje6pz.enc \
tex-ostd-ra2ua5.enc \
tex-ostd-recs4b.enc \
tex-ostd-rkoszz.enc \
tex-ostd-roofh6.enc \
tex-ostd-rs2jfd.enc \
tex-ostd-rybegg.enc \
tex-ostd-sef3nf.enc \
tex-ostd-sfa7gz.enc \
tex-ostd-smvurd.enc \
tex-ostd-sqlbxq.enc \
tex-ostd-sygszf.enc \
tex-ostd-sykxvg.enc \
tex-ostd-t5o4op.enc \
tex-ostd-tbxs5z.enc \
tex-ostd-uaalcg.enc \
tex-ostd-uj34jt.enc \
tex-ostd-um5doh.enc \
tex-ostd-us4lbu.enc \
tex-ostd-v4egie.enc \
tex-ostd-v72l3h.enc \
tex-ostd-vznixw.enc \
tex-ostd-w2wa52.enc \
tex-ostd-w6t7up.enc \
tex-ostd-wgdj7s.enc \
tex-ostd-wj5nxr.enc \
tex-ostd-wjmggu.enc \
tex-ostd-x3pcti.enc \
tex-ostd-xe4omp.enc \
tex-ostd-xjjslf.enc \
tex-ostd-xnwpio.enc \
tex-ostd-xo5j4s.enc \
tex-ostd-xqworl.enc \
tex-ostd-y2jfiq.enc \
tex-ostd-yfaj3b.enc \
tex-ostd-yi4alo.enc \
tex-ostd-yni53c.enc \
tex-ostd-yp4wmb.enc \
tex-ostd-ytxedg.enc \
tex-ostd-z6cmae.enc \
texlive-oldstandard"

RDEPENDS:${PN} += "/usr/bin/sh \
coreutils \
ed \
findutils \
grep \
sed \
tex-fontaxes.sty \
tex-fontenc.sty \
tex-fontspec.sty \
tex-ifluatex.sty \
tex-ifxetex.sty \
tex-textcomp.sty \
tex-updmap.cfg \
tex-xkeyval.sty \
texlive \
texlive-filesystem \
texlive-kpathsea \
texlive-kpathsea-bin \
texlive-oldstandard-fonts \
texlive-scripts \
texlive-scripts-bin"

inherit rpm
