SUMMARY = "Kernel driver for Realtek rtl88x2bu wifi cards"
DESCRIPTION = "Kernel driver for Realtek 88x2bu wifi cards \
 \
The sources were obtained from https://github.com/cilynx/rtl88x2bu, which adapts the official driver \
released by Realtek to build on recent kernels."
LICENSE = "GPL-2.0-only"

PV = "5.8.7.1+git20260818.04ed700_k7.2.4_1"

RPM_NAME = "rtl88x2bu-kmp-64kb-5.8.7.1+git20260818.04ed700_k7.2.4_1-2.1.aarch64.rpm"
RPM_HASH = "bf8e6cf280edb4a80a021caabce9fccb70614a96ec033371dddacef9b757409d5dd3af0df0e3fde560ec3d2a2f3e3b4068191d1c1eff2d7a65189d35ed9534cf"

RPROVIDES:${PN} += "kmod-88x2bu.ko \
multiversion-kernel \
rtl88x2bu-kmp \
rtl88x2bu-kmp-64kb \
rtl88x2bu-kmp-64kb-k7.2.4-1"

RDEPENDS:${PN} += "/usr/bin/sh \
coreutils \
grep \
kernel-64kb \
ksym-default---arch-copy-from-user \
ksym-default---arch-copy-to-user \
ksym-default---cfg80211-alloc-event-skb \
ksym-default---cfg80211-alloc-reply-skb \
ksym-default---cfg80211-get-bss \
ksym-default---cfg80211-send-event-skb \
ksym-default---check-object-size \
ksym-default---const-udelay \
ksym-default---fortify-panic \
ksym-default---init-swait-queue-head \
ksym-default---kmalloc-noprof \
ksym-default---list-add-valid-or-report \
ksym-default---list-del-entry-valid-or-report \
ksym-default---msecs-to-jiffies \
ksym-default---napi-schedule \
ksym-default---netdev-alloc-skb \
ksym-default---netif-napi-del-locked \
ksym-default---pskb-copy-fclone \
ksym-default---pskb-pull-tail \
ksym-default---rcu-read-lock \
ksym-default---rcu-read-unlock \
ksym-default---stack-chk-fail \
ksym-default---tasklet-hi-schedule \
ksym-default---tasklet-schedule \
ksym-default---trace-set-current-state \
ksym-default---tracepoint-sched-set-state-tp \
ksym-default---udelay \
ksym-default---usecs-to-jiffies \
ksym-default---warn-printk \
ksym-default--printk \
ksym-default--raw-spin-lock \
ksym-default--raw-spin-lock-bh \
ksym-default--raw-spin-lock-irqsave \
ksym-default--raw-spin-unlock \
ksym-default--raw-spin-unlock-bh \
ksym-default--raw-spin-unlock-irqrestore \
ksym-default-alloc-etherdev-mqs \
ksym-default-alt-cb-patch-nops \
ksym-default-cancel-work-sync \
ksym-default-cfg80211-ch-switch-notify \
ksym-default-cfg80211-ch-switch-started-notify \
ksym-default-cfg80211-connect-done \
ksym-default-cfg80211-del-sta-sinfo \
ksym-default-cfg80211-disconnected \
ksym-default-cfg80211-external-auth-request \
ksym-default-cfg80211-ibss-joined \
ksym-default-cfg80211-inform-bss-frame-data \
ksym-default-cfg80211-mgmt-tx-status-ext \
ksym-default-cfg80211-michael-mic-failure \
ksym-default-cfg80211-new-sta \
ksym-default-cfg80211-put-bss \
ksym-default-cfg80211-ready-on-channel \
ksym-default-cfg80211-remain-on-channel-expired \
ksym-default-cfg80211-roamed \
ksym-default-cfg80211-rx-mgmt-ext \
ksym-default-cfg80211-scan-done \
ksym-default-cfg80211-unlink-bss \
ksym-default-cfg80211-vendor-cmd-reply \
ksym-default-complete \
ksym-default-csum-ipv6-magic \
ksym-default-csum-partial \
ksym-default-dev-addr-mod \
ksym-default-dev-alloc-name \
ksym-default-dev-get-by-name \
ksym-default-dev-kfree-skb-any-reason \
ksym-default-device-set-wakeup-capable \
ksym-default-device-wakeup-enable \
ksym-default-down-interruptible \
ksym-default-dynamic-preempt-schedule-notrace \
ksym-default-eth-type-trans \
ksym-default-filp-close \
ksym-default-filp-open \
ksym-default-find-vpid \
ksym-default-flush-signals \
ksym-default-free-netdev \
ksym-default-get-random-u32 \
ksym-default-gro-receive-skb \
ksym-default-ieee80211-freq-khz-to-channel \
ksym-default-ieee80211-get-channel-khz \
ksym-default-init-net \
ksym-default-iwe-stream-add-event \
ksym-default-iwe-stream-add-point \
ksym-default-jiffies \
ksym-default-kern-path \
ksym-default-kernel-read \
ksym-default-kernel-sigaction \
ksym-default-kernel-write \
ksym-default-kfree \
ksym-default-kill-pid \
ksym-default-kthread-complete-and-exit \
ksym-default-kthread-create-on-node \
ksym-default-kthread-should-stop \
ksym-default-kthread-stop \
ksym-default-ktime-get-with-offset \
ksym-default-memcmp \
ksym-default-memcpy \
ksym-default-memmove \
ksym-default-memset \
ksym-default-mod-timer \
ksym-default-module-layout \
ksym-default-msleep \
ksym-default-mutex-init-generic \
ksym-default-mutex-lock \
ksym-default-mutex-lock-interruptible \
ksym-default-mutex-unlock \
ksym-default-napi-complete-done \
ksym-default-napi-disable \
ksym-default-napi-enable \
ksym-default-napi-schedule-prep \
ksym-default-netif-carrier-off \
ksym-default-netif-carrier-on \
ksym-default-netif-napi-add-weight-locked \
ksym-default-netif-receive-skb \
ksym-default-netif-rx \
ksym-default-netif-tx-stop-all-queues \
ksym-default-netif-tx-wake-queue \
ksym-default-nla-put \
ksym-default-nla-put-nohdr \
ksym-default-param-array-ops \
ksym-default-param-ops-charp \
ksym-default-param-ops-int \
ksym-default-param-ops-uint \
ksym-default-proc-create-data \
ksym-default-proc-get-parent-data \
ksym-default-proc-mkdir-data \
ksym-default-queue-work-on \
ksym-default-register-inet6addr-notifier \
ksym-default-register-inetaddr-notifier \
ksym-default-register-netdev \
ksym-default-register-netdevice \
ksym-default-register-netdevice-notifier \
ksym-default-remove-proc-entry \
ksym-default-rtnl-is-locked \
ksym-default-schedule \
ksym-default-schedule-timeout \
ksym-default-seq-lseek \
ksym-default-seq-open \
ksym-default-seq-printf \
ksym-default-seq-read \
ksym-default-seq-release \
ksym-default-simple-strtoul \
ksym-default-single-open \
ksym-default-single-open-size \
ksym-default-single-release \
ksym-default-skb-clone \
ksym-default-skb-copy \
ksym-default-skb-copy-bits \
ksym-default-skb-dequeue \
ksym-default-skb-pull \
ksym-default-skb-push \
ksym-default-skb-put \
ksym-default-skb-queue-tail \
ksym-default-skb-trim \
ksym-default-snprintf \
ksym-default-sprintf \
ksym-default-sscanf \
ksym-default-strcasecmp \
ksym-default-strchr \
ksym-default-strcmp \
ksym-default-strcpy \
ksym-default-strlen \
ksym-default-strncasecmp \
ksym-default-strncmp \
ksym-default-strnlen \
ksym-default-strpbrk \
ksym-default-strrchr \
ksym-default-strsep \
ksym-default-strstr \
ksym-default-synchronize-net \
ksym-default-system-percpu-wq \
ksym-default-tasklet-init \
ksym-default-tasklet-kill \
ksym-default-timer-delete-sync \
ksym-default-timer-init-key \
ksym-default-unregister-inet6addr-notifier \
ksym-default-unregister-inetaddr-notifier \
ksym-default-unregister-netdev \
ksym-default-unregister-netdevice-notifier \
ksym-default-unregister-netdevice-queue \
ksym-default-up \
ksym-default-usb-alloc-coherent \
ksym-default-usb-alloc-urb \
ksym-default-usb-autopm-get-interface \
ksym-default-usb-autopm-put-interface \
ksym-default-usb-control-msg \
ksym-default-usb-deregister \
ksym-default-usb-free-coherent \
ksym-default-usb-free-urb \
ksym-default-usb-get-dev \
ksym-default-usb-kill-urb \
ksym-default-usb-put-dev \
ksym-default-usb-register-driver \
ksym-default-usb-submit-urb \
ksym-default-usleep-range-state \
ksym-default-validate-usercopy-range \
ksym-default-vfree \
ksym-default-vmalloc-noprof \
ksym-default-wait-for-completion \
ksym-default-wait-for-completion-timeout \
ksym-default-wake-up-process \
ksym-default-wiphy-free \
ksym-default-wiphy-new-nm \
ksym-default-wiphy-register \
ksym-default-wiphy-unregister \
ksym-default-yield \
suse-kernel-rpm-scriptlets"

inherit rpm
