SUMMARY = "Development files for hashlink"
DESCRIPTION = "Contains the files required to compile to a native executable the HashLink/C \
code generated by the haxe compiler."
LICENSE = "MIT"

PV = "1.15"

RPM_NAME = "hashlink-devel-1.15-4.2.aarch64.rpm"
RPM_HASH = "0008db7eeb62c506d5e71f3750195582cf6fc07cb4bd78d0be6a2f8969090b582ae8b87105a9f400b209a4739c255fd27ae4023d7a27ce1a4dd17fc367f7e3ec"

RPROVIDES:${PN} += "hashlink-devel"

RDEPENDS:${PN} += "hashlink-hdlls \
libhl1"

inherit rpm
