SUMMARY = "A structural diff that understands syntax"
DESCRIPTION = "Difftastic is a structural diff tool that compares files based on their syntax."
LICENSE = "Apache-2.0 & MIT"

PV = "0.70.0"

RPM_NAME = "difftastic-0.70.0-1.2.aarch64.rpm"
RPM_HASH = "a8afeacea4b233f319b86fce1e46ab4041ba5ba0ef0382289c1759a52bc4a960672c0762cb9c02dc788169d5a5b6aeca70d8f8baf818dff4f0eb40aa033da310"

RPROVIDES:${PN} += "bundled-rust-crate-aho-corasick \
bundled-rust-crate-allocator-api2 \
bundled-rust-crate-anstream \
bundled-rust-crate-anstyle \
bundled-rust-crate-anstyle-parse \
bundled-rust-crate-anstyle-query \
bundled-rust-crate-autocfg \
bundled-rust-crate-bitflags \
bundled-rust-crate-bstr \
bundled-rust-crate-bumpalo \
bundled-rust-crate-cc \
bundled-rust-crate-cfg-if \
bundled-rust-crate-clap \
bundled-rust-crate-clap-builder \
bundled-rust-crate-clap-lex \
bundled-rust-crate-colorchoice \
bundled-rust-crate-crossbeam-deque \
bundled-rust-crate-crossbeam-epoch \
bundled-rust-crate-crossbeam-utils \
bundled-rust-crate-crossterm \
bundled-rust-crate-difftastic \
bundled-rust-crate-either \
bundled-rust-crate-encoding-rs \
bundled-rust-crate-env-logger \
bundled-rust-crate-equivalent \
bundled-rust-crate-errno \
bundled-rust-crate-find-msvc-tools \
bundled-rust-crate-fixedbitset \
bundled-rust-crate-foldhash \
bundled-rust-crate-glob \
bundled-rust-crate-globset \
bundled-rust-crate-hashbrown \
bundled-rust-crate-heck \
bundled-rust-crate-humansize \
bundled-rust-crate-humantime \
bundled-rust-crate-ignore \
bundled-rust-crate-indexmap \
bundled-rust-crate-is-terminal \
bundled-rust-crate-is-terminal-polyfill \
bundled-rust-crate-itoa \
bundled-rust-crate-lazy-static \
bundled-rust-crate-libc \
bundled-rust-crate-libm \
bundled-rust-crate-line-numbers \
bundled-rust-crate-linux-raw-sys \
bundled-rust-crate-lock-api \
bundled-rust-crate-log \
bundled-rust-crate-memchr \
bundled-rust-crate-mio \
bundled-rust-crate-nom \
bundled-rust-crate-owo-colors \
bundled-rust-crate-parking-lot \
bundled-rust-crate-parking-lot-core \
bundled-rust-crate-petgraph \
bundled-rust-crate-pretty-env-logger \
bundled-rust-crate-proc-macro2 \
bundled-rust-crate-quote \
bundled-rust-crate-radix-heap \
bundled-rust-crate-rayon \
bundled-rust-crate-rayon-core \
bundled-rust-crate-regex \
bundled-rust-crate-regex-automata \
bundled-rust-crate-regex-syntax \
bundled-rust-crate-rustc-hash \
bundled-rust-crate-rustix \
bundled-rust-crate-ryu \
bundled-rust-crate-same-file \
bundled-rust-crate-scopeguard \
bundled-rust-crate-serde \
bundled-rust-crate-serde-core \
bundled-rust-crate-serde-derive \
bundled-rust-crate-serde-json \
bundled-rust-crate-shlex \
bundled-rust-crate-signal-hook \
bundled-rust-crate-signal-hook-mio \
bundled-rust-crate-signal-hook-registry \
bundled-rust-crate-smallvec \
bundled-rust-crate-streaming-iterator \
bundled-rust-crate-strsim \
bundled-rust-crate-strum \
bundled-rust-crate-strum-macros \
bundled-rust-crate-syn \
bundled-rust-crate-termcolor \
bundled-rust-crate-terminal-size \
bundled-rust-crate-tikv-jemalloc-sys \
bundled-rust-crate-tikv-jemallocator \
bundled-rust-crate-tree-magic-mini \
bundled-rust-crate-tree-sitter \
bundled-rust-crate-tree-sitter-ada \
bundled-rust-crate-tree-sitter-asm \
bundled-rust-crate-tree-sitter-bash \
bundled-rust-crate-tree-sitter-c \
bundled-rust-crate-tree-sitter-c-sharp \
bundled-rust-crate-tree-sitter-clojure-orchard \
bundled-rust-crate-tree-sitter-cmake \
bundled-rust-crate-tree-sitter-commonlisp \
bundled-rust-crate-tree-sitter-containerfile \
bundled-rust-crate-tree-sitter-cpp \
bundled-rust-crate-tree-sitter-css \
bundled-rust-crate-tree-sitter-dart-orchard \
bundled-rust-crate-tree-sitter-devicetree \
bundled-rust-crate-tree-sitter-elisp \
bundled-rust-crate-tree-sitter-elixir \
bundled-rust-crate-tree-sitter-elm \
bundled-rust-crate-tree-sitter-erlang \
bundled-rust-crate-tree-sitter-fish \
bundled-rust-crate-tree-sitter-fortran \
bundled-rust-crate-tree-sitter-fsharp \
bundled-rust-crate-tree-sitter-gleam \
bundled-rust-crate-tree-sitter-go \
bundled-rust-crate-tree-sitter-haskell \
bundled-rust-crate-tree-sitter-hcl \
bundled-rust-crate-tree-sitter-html \
bundled-rust-crate-tree-sitter-java-orchard \
bundled-rust-crate-tree-sitter-javascript \
bundled-rust-crate-tree-sitter-json \
bundled-rust-crate-tree-sitter-julia \
bundled-rust-crate-tree-sitter-language \
bundled-rust-crate-tree-sitter-lua \
bundled-rust-crate-tree-sitter-make \
bundled-rust-crate-tree-sitter-newick \
bundled-rust-crate-tree-sitter-nix \
bundled-rust-crate-tree-sitter-objc \
bundled-rust-crate-tree-sitter-ocaml \
bundled-rust-crate-tree-sitter-pascal \
bundled-rust-crate-tree-sitter-php \
bundled-rust-crate-tree-sitter-proto \
bundled-rust-crate-tree-sitter-python \
bundled-rust-crate-tree-sitter-qmljs \
bundled-rust-crate-tree-sitter-r \
bundled-rust-crate-tree-sitter-racket \
bundled-rust-crate-tree-sitter-ruby \
bundled-rust-crate-tree-sitter-rust-orchard \
bundled-rust-crate-tree-sitter-scala \
bundled-rust-crate-tree-sitter-scheme \
bundled-rust-crate-tree-sitter-sequel \
bundled-rust-crate-tree-sitter-sfapex \
bundled-rust-crate-tree-sitter-solidity \
bundled-rust-crate-tree-sitter-swift \
bundled-rust-crate-tree-sitter-toml-ng \
bundled-rust-crate-tree-sitter-typescript \
bundled-rust-crate-tree-sitter-verilog \
bundled-rust-crate-tree-sitter-vhdl \
bundled-rust-crate-tree-sitter-xml \
bundled-rust-crate-tree-sitter-yaml \
bundled-rust-crate-tree-sitter-zig \
bundled-rust-crate-ts-parser-perl \
bundled-rust-crate-typed-arena \
bundled-rust-crate-unicode-ident \
bundled-rust-crate-unicode-width \
bundled-rust-crate-utf8parse \
bundled-rust-crate-version-check \
bundled-rust-crate-walkdir \
bundled-rust-crate-wu-diff \
difftastic"

RDEPENDS:${PN} += "libc.so.6 \
libgcc-s.so.1 \
shared-mime-info"

inherit rpm
