SUMMARY = "Hassle-free Python project manager in Rust"
DESCRIPTION = "Rye is a comprehensive project and package management solution for Python. Born \
from its creator's desire to establish a one-stop-shop for all Python users, \
Rye provides a unified experience to install and manage Python installations, \
pyproject.toml based projects, dependencies and virtualenvs seamlessly. It's \
designed to accommodate complex projects, monorepos and to facilitate global \
tool installations."
LICENSE = "MIT"

PV = "0.44.0"

RPM_NAME = "rye-0.44.0-1.8.aarch64.rpm"
RPM_HASH = "209eee51d803ce4fd87b6daa9061fc024970d2978f05059518963fa7b1506eea050686a75321ff388dae1b8b7ca3618b30f5169a5878ae5d96ed0573647aed25"

RPROVIDES:${PN} += "bundled-rust-crate-addr2line \
bundled-rust-crate-adler2 \
bundled-rust-crate-aead \
bundled-rust-crate-age \
bundled-rust-crate-age-core \
bundled-rust-crate-ahash \
bundled-rust-crate-aho-corasick \
bundled-rust-crate-allocator-api2 \
bundled-rust-crate-anstyle \
bundled-rust-crate-anyhow \
bundled-rust-crate-arc-swap \
bundled-rust-crate-autocfg \
bundled-rust-crate-backtrace \
bundled-rust-crate-base64 \
bundled-rust-crate-basic-toml \
bundled-rust-crate-bech32 \
bundled-rust-crate-bitflags \
bundled-rust-crate-block-buffer \
bundled-rust-crate-bstr \
bundled-rust-crate-bumpalo \
bundled-rust-crate-byteorder \
bundled-rust-crate-bzip2 \
bundled-rust-crate-bzip2-sys \
bundled-rust-crate-cc \
bundled-rust-crate-cfg-aliases \
bundled-rust-crate-cfg-if \
bundled-rust-crate-chacha20 \
bundled-rust-crate-chacha20poly1305 \
bundled-rust-crate-charset \
bundled-rust-crate-chumsky \
bundled-rust-crate-cipher \
bundled-rust-crate-clap \
bundled-rust-crate-clap-builder \
bundled-rust-crate-clap-complete \
bundled-rust-crate-clap-complete-nushell \
bundled-rust-crate-clap-derive \
bundled-rust-crate-clap-lex \
bundled-rust-crate-configparser \
bundled-rust-crate-console \
bundled-rust-crate-cookie-factory \
bundled-rust-crate-cpufeatures \
bundled-rust-crate-crc32fast \
bundled-rust-crate-crypto-common \
bundled-rust-crate-ctrlc \
bundled-rust-crate-curl \
bundled-rust-crate-curl-sys \
bundled-rust-crate-curve25519-dalek \
bundled-rust-crate-dashmap \
bundled-rust-crate-data-encoding \
bundled-rust-crate-deranged \
bundled-rust-crate-deunicode \
bundled-rust-crate-dialoguer \
bundled-rust-crate-digest \
bundled-rust-crate-displaydoc \
bundled-rust-crate-dotenvy \
bundled-rust-crate-either \
bundled-rust-crate-encoding-rs \
bundled-rust-crate-equivalent \
bundled-rust-crate-errno \
bundled-rust-crate-fastrand \
bundled-rust-crate-filetime \
bundled-rust-crate-find-crate \
bundled-rust-crate-flate2 \
bundled-rust-crate-fluent \
bundled-rust-crate-fluent-bundle \
bundled-rust-crate-fluent-langneg \
bundled-rust-crate-fluent-syntax \
bundled-rust-crate-form-urlencoded \
bundled-rust-crate-fs-err \
bundled-rust-crate-fs2 \
bundled-rust-crate-futures \
bundled-rust-crate-futures-channel \
bundled-rust-crate-futures-core \
bundled-rust-crate-futures-executor \
bundled-rust-crate-futures-io \
bundled-rust-crate-futures-macro \
bundled-rust-crate-futures-sink \
bundled-rust-crate-futures-task \
bundled-rust-crate-futures-util \
bundled-rust-crate-generic-array \
bundled-rust-crate-getrandom \
bundled-rust-crate-gimli \
bundled-rust-crate-git-testament \
bundled-rust-crate-git-testament-derive \
bundled-rust-crate-globset \
bundled-rust-crate-hashbrown \
bundled-rust-crate-heck \
bundled-rust-crate-hex \
bundled-rust-crate-hkdf \
bundled-rust-crate-hmac \
bundled-rust-crate-home \
bundled-rust-crate-i18n-config \
bundled-rust-crate-i18n-embed \
bundled-rust-crate-i18n-embed-fl \
bundled-rust-crate-i18n-embed-impl \
bundled-rust-crate-icu-collections \
bundled-rust-crate-icu-locale-core \
bundled-rust-crate-icu-normalizer \
bundled-rust-crate-icu-normalizer-data \
bundled-rust-crate-icu-properties \
bundled-rust-crate-icu-properties-data \
bundled-rust-crate-icu-provider \
bundled-rust-crate-idna \
bundled-rust-crate-idna-adapter \
bundled-rust-crate-indexmap \
bundled-rust-crate-indicatif \
bundled-rust-crate-inout \
bundled-rust-crate-intl-memoizer \
bundled-rust-crate-intl-pluralrules \
bundled-rust-crate-io-tee \
bundled-rust-crate-itoa \
bundled-rust-crate-jobserver \
bundled-rust-crate-junction \
bundled-rust-crate-lazy-static \
bundled-rust-crate-libc \
bundled-rust-crate-libz-sys \
bundled-rust-crate-license \
bundled-rust-crate-linux-raw-sys \
bundled-rust-crate-litemap \
bundled-rust-crate-lock-api \
bundled-rust-crate-log \
bundled-rust-crate-mailparse \
bundled-rust-crate-memchr \
bundled-rust-crate-minijinja \
bundled-rust-crate-minimal-lexical \
bundled-rust-crate-miniz-oxide \
bundled-rust-crate-monotrail-utils \
bundled-rust-crate-nix \
bundled-rust-crate-nom \
bundled-rust-crate-num-conv \
bundled-rust-crate-number-prefix \
bundled-rust-crate-object \
bundled-rust-crate-once-cell \
bundled-rust-crate-opaque-debug \
bundled-rust-crate-openssl-probe \
bundled-rust-crate-openssl-src \
bundled-rust-crate-openssl-sys \
bundled-rust-crate-parking-lot \
bundled-rust-crate-parking-lot-core \
bundled-rust-crate-pathdiff \
bundled-rust-crate-pbkdf2 \
bundled-rust-crate-pep440-rs \
bundled-rust-crate-pep508-rs \
bundled-rust-crate-percent-encoding \
bundled-rust-crate-pin-project \
bundled-rust-crate-pin-project-internal \
bundled-rust-crate-pin-project-lite \
bundled-rust-crate-pin-utils \
bundled-rust-crate-pkg-config \
bundled-rust-crate-poly1305 \
bundled-rust-crate-portable-atomic \
bundled-rust-crate-potential-utf \
bundled-rust-crate-powerfmt \
bundled-rust-crate-ppv-lite86 \
bundled-rust-crate-proc-macro-error \
bundled-rust-crate-proc-macro-error-attr \
bundled-rust-crate-proc-macro2 \
bundled-rust-crate-psm \
bundled-rust-crate-python-pkginfo \
bundled-rust-crate-quote \
bundled-rust-crate-quoted-printable \
bundled-rust-crate-rand \
bundled-rust-crate-rand-chacha \
bundled-rust-crate-rand-core \
bundled-rust-crate-regex \
bundled-rust-crate-regex-automata \
bundled-rust-crate-regex-syntax \
bundled-rust-crate-reword \
bundled-rust-crate-rfc2047-decoder \
bundled-rust-crate-ring \
bundled-rust-crate-rust-embed \
bundled-rust-crate-rust-embed-impl \
bundled-rust-crate-rust-embed-utils \
bundled-rust-crate-rustc-demangle \
bundled-rust-crate-rustc-hash \
bundled-rust-crate-rustc-version \
bundled-rust-crate-rustix \
bundled-rust-crate-rustls \
bundled-rust-crate-rustls-pki-types \
bundled-rust-crate-rustls-webpki \
bundled-rust-crate-rye \
bundled-rust-crate-ryu \
bundled-rust-crate-salsa20 \
bundled-rust-crate-same-file \
bundled-rust-crate-scopeguard \
bundled-rust-crate-scrypt \
bundled-rust-crate-secrecy \
bundled-rust-crate-self-cell \
bundled-rust-crate-self-replace \
bundled-rust-crate-semver \
bundled-rust-crate-serde \
bundled-rust-crate-serde-derive \
bundled-rust-crate-serde-json \
bundled-rust-crate-serde-spanned \
bundled-rust-crate-sha2 \
bundled-rust-crate-shell-words \
bundled-rust-crate-shlex \
bundled-rust-crate-simd-adler32 \
bundled-rust-crate-slab \
bundled-rust-crate-slug \
bundled-rust-crate-smallvec \
bundled-rust-crate-socket2 \
bundled-rust-crate-stable-deref-trait \
bundled-rust-crate-stacker \
bundled-rust-crate-strsim \
bundled-rust-crate-subtle \
bundled-rust-crate-syn \
bundled-rust-crate-synstructure \
bundled-rust-crate-tar \
bundled-rust-crate-target-lexicon \
bundled-rust-crate-tempfile \
bundled-rust-crate-terminal-size \
bundled-rust-crate-thiserror \
bundled-rust-crate-thiserror-impl \
bundled-rust-crate-time \
bundled-rust-crate-time-core \
bundled-rust-crate-time-macros \
bundled-rust-crate-tinystr \
bundled-rust-crate-toml \
bundled-rust-crate-toml-datetime \
bundled-rust-crate-toml-edit \
bundled-rust-crate-toml-write \
bundled-rust-crate-tracing \
bundled-rust-crate-tracing-attributes \
bundled-rust-crate-tracing-core \
bundled-rust-crate-type-map \
bundled-rust-crate-typenum \
bundled-rust-crate-unic-langid \
bundled-rust-crate-unic-langid-impl \
bundled-rust-crate-unicode-ident \
bundled-rust-crate-unicode-segmentation \
bundled-rust-crate-unicode-width \
bundled-rust-crate-universal-hash \
bundled-rust-crate-unscanny \
bundled-rust-crate-untrusted \
bundled-rust-crate-ureq \
bundled-rust-crate-url \
bundled-rust-crate-utf8-iter \
bundled-rust-crate-vcpkg \
bundled-rust-crate-version-check \
bundled-rust-crate-walkdir \
bundled-rust-crate-webpki-roots \
bundled-rust-crate-which \
bundled-rust-crate-winnow \
bundled-rust-crate-writeable \
bundled-rust-crate-x25519-dalek \
bundled-rust-crate-xattr \
bundled-rust-crate-yoke \
bundled-rust-crate-yoke-derive \
bundled-rust-crate-zerocopy \
bundled-rust-crate-zerofrom \
bundled-rust-crate-zerofrom-derive \
bundled-rust-crate-zeroize \
bundled-rust-crate-zeroize-derive \
bundled-rust-crate-zerotrie \
bundled-rust-crate-zerovec \
bundled-rust-crate-zerovec-derive \
bundled-rust-crate-zip \
bundled-rust-crate-zopfli \
bundled-rust-crate-zstd \
bundled-rust-crate-zstd-safe \
bundled-rust-crate-zstd-sys \
rye"

RDEPENDS:${PN} += "libc.so.6 \
libgcc-s.so.1 \
libm.so.6 \
python3"

inherit rpm
