SUMMARY = "Support for the Atkinson Hyperlegible family of fonts"
DESCRIPTION = "This package provides LaTeX, pdfLaTeX, XeLaTeX and LuaLaTeX \
support for the Atkinson Hyperlegible family of fonts, named \
after Braille Institute founder, J. Robert Atkinson. What makes \
it different from traditional typography design is that it \
focuses on letterform distinction to increase character \
recognition, ultimately improving readability."
LICENSE = "LPPL-1.0"

PV = "2026.226.svn77682"

RPM_NAME = "texlive-atkinson-2026.226.svn77682-60.2.noarch.rpm"
RPM_HASH = "5ce9bc6aad3cc58393db219ad03eee526843b739cee91ff14acd8222c60f90134c228ca62527a28fcf36f8f18c52d593b4b3fa4262dda4b226d711283e219965"
REPO_ARCH = "noarch"

RPROVIDES:${PN} += "tex-LY1atkinsn-LF.fd \
tex-LY1atkinsn-Sup.fd \
tex-LY1atkinsn-TLF.fd \
tex-LY1atkinsnmono-Sup.fd \
tex-LY1atkinsnmono-TLF.fd \
tex-OT1atkinsn-LF.fd \
tex-OT1atkinsn-Sup.fd \
tex-OT1atkinsn-TLF.fd \
tex-OT1atkinsnmono-Sup.fd \
tex-OT1atkinsnmono-TLF.fd \
tex-T1atkinsn-LF.fd \
tex-T1atkinsn-Sup.fd \
tex-T1atkinsn-TLF.fd \
tex-T1atkinsnmono-Sup.fd \
tex-T1atkinsnmono-TLF.fd \
tex-TS1atkinsn-LF.fd \
tex-TS1atkinsn-TLF.fd \
tex-TS1atkinsnmono-TLF.fd \
tex-atkinsn-2euc5w.enc \
tex-atkinsn-7pe33p.enc \
tex-atkinsn-Bold-lf-ly1--base.tfm \
tex-atkinsn-Bold-lf-ly1.tfm \
tex-atkinsn-Bold-lf-ly1.vf \
tex-atkinsn-Bold-lf-ot1.tfm \
tex-atkinsn-Bold-lf-t1--base.tfm \
tex-atkinsn-Bold-lf-t1.tfm \
tex-atkinsn-Bold-lf-t1.vf \
tex-atkinsn-Bold-lf-ts1--base.tfm \
tex-atkinsn-Bold-lf-ts1.tfm \
tex-atkinsn-Bold-lf-ts1.vf \
tex-atkinsn-Bold-sup-ly1--base.tfm \
tex-atkinsn-Bold-sup-ly1.tfm \
tex-atkinsn-Bold-sup-ly1.vf \
tex-atkinsn-Bold-sup-ot1.tfm \
tex-atkinsn-Bold-sup-t1--base.tfm \
tex-atkinsn-Bold-sup-t1.tfm \
tex-atkinsn-Bold-sup-t1.vf \
tex-atkinsn-Bold-tlf-ly1--base.tfm \
tex-atkinsn-Bold-tlf-ly1.tfm \
tex-atkinsn-Bold-tlf-ly1.vf \
tex-atkinsn-Bold-tlf-ot1.tfm \
tex-atkinsn-Bold-tlf-t1--base.tfm \
tex-atkinsn-Bold-tlf-t1.tfm \
tex-atkinsn-Bold-tlf-t1.vf \
tex-atkinsn-Bold-tlf-ts1--base.tfm \
tex-atkinsn-Bold-tlf-ts1.tfm \
tex-atkinsn-Bold-tlf-ts1.vf \
tex-atkinsn-BoldItalic-lf-ly1--base.tfm \
tex-atkinsn-BoldItalic-lf-ly1.tfm \
tex-atkinsn-BoldItalic-lf-ly1.vf \
tex-atkinsn-BoldItalic-lf-ot1.tfm \
tex-atkinsn-BoldItalic-lf-t1--base.tfm \
tex-atkinsn-BoldItalic-lf-t1.tfm \
tex-atkinsn-BoldItalic-lf-t1.vf \
tex-atkinsn-BoldItalic-lf-ts1--base.tfm \
tex-atkinsn-BoldItalic-lf-ts1.tfm \
tex-atkinsn-BoldItalic-lf-ts1.vf \
tex-atkinsn-BoldItalic-sup-ly1--base.tfm \
tex-atkinsn-BoldItalic-sup-ly1.tfm \
tex-atkinsn-BoldItalic-sup-ly1.vf \
tex-atkinsn-BoldItalic-sup-ot1.tfm \
tex-atkinsn-BoldItalic-sup-t1--base.tfm \
tex-atkinsn-BoldItalic-sup-t1.tfm \
tex-atkinsn-BoldItalic-sup-t1.vf \
tex-atkinsn-BoldItalic-tlf-ly1--base.tfm \
tex-atkinsn-BoldItalic-tlf-ly1.tfm \
tex-atkinsn-BoldItalic-tlf-ly1.vf \
tex-atkinsn-BoldItalic-tlf-ot1.tfm \
tex-atkinsn-BoldItalic-tlf-t1--base.tfm \
tex-atkinsn-BoldItalic-tlf-t1.tfm \
tex-atkinsn-BoldItalic-tlf-t1.vf \
tex-atkinsn-BoldItalic-tlf-ts1--base.tfm \
tex-atkinsn-BoldItalic-tlf-ts1.tfm \
tex-atkinsn-BoldItalic-tlf-ts1.vf \
tex-atkinsn-ExtraBold-lf-ly1--base.tfm \
tex-atkinsn-ExtraBold-lf-ly1.tfm \
tex-atkinsn-ExtraBold-lf-ly1.vf \
tex-atkinsn-ExtraBold-lf-ot1.tfm \
tex-atkinsn-ExtraBold-lf-t1--base.tfm \
tex-atkinsn-ExtraBold-lf-t1.tfm \
tex-atkinsn-ExtraBold-lf-t1.vf \
tex-atkinsn-ExtraBold-lf-ts1--base.tfm \
tex-atkinsn-ExtraBold-lf-ts1.tfm \
tex-atkinsn-ExtraBold-lf-ts1.vf \
tex-atkinsn-ExtraBold-sup-ly1--base.tfm \
tex-atkinsn-ExtraBold-sup-ly1.tfm \
tex-atkinsn-ExtraBold-sup-ly1.vf \
tex-atkinsn-ExtraBold-sup-ot1.tfm \
tex-atkinsn-ExtraBold-sup-t1--base.tfm \
tex-atkinsn-ExtraBold-sup-t1.tfm \
tex-atkinsn-ExtraBold-sup-t1.vf \
tex-atkinsn-ExtraBold-tlf-ly1--base.tfm \
tex-atkinsn-ExtraBold-tlf-ly1.tfm \
tex-atkinsn-ExtraBold-tlf-ly1.vf \
tex-atkinsn-ExtraBold-tlf-ot1.tfm \
tex-atkinsn-ExtraBold-tlf-t1--base.tfm \
tex-atkinsn-ExtraBold-tlf-t1.tfm \
tex-atkinsn-ExtraBold-tlf-t1.vf \
tex-atkinsn-ExtraBold-tlf-ts1--base.tfm \
tex-atkinsn-ExtraBold-tlf-ts1.tfm \
tex-atkinsn-ExtraBold-tlf-ts1.vf \
tex-atkinsn-ExtraBoldItalic-lf-ly1--base.tfm \
tex-atkinsn-ExtraBoldItalic-lf-ly1.tfm \
tex-atkinsn-ExtraBoldItalic-lf-ly1.vf \
tex-atkinsn-ExtraBoldItalic-lf-ot1.tfm \
tex-atkinsn-ExtraBoldItalic-lf-t1--base.tfm \
tex-atkinsn-ExtraBoldItalic-lf-t1.tfm \
tex-atkinsn-ExtraBoldItalic-lf-t1.vf \
tex-atkinsn-ExtraBoldItalic-lf-ts1--base.tfm \
tex-atkinsn-ExtraBoldItalic-lf-ts1.tfm \
tex-atkinsn-ExtraBoldItalic-lf-ts1.vf \
tex-atkinsn-ExtraBoldItalic-sup-ly1--base.tfm \
tex-atkinsn-ExtraBoldItalic-sup-ly1.tfm \
tex-atkinsn-ExtraBoldItalic-sup-ly1.vf \
tex-atkinsn-ExtraBoldItalic-sup-ot1.tfm \
tex-atkinsn-ExtraBoldItalic-sup-t1--base.tfm \
tex-atkinsn-ExtraBoldItalic-sup-t1.tfm \
tex-atkinsn-ExtraBoldItalic-sup-t1.vf \
tex-atkinsn-ExtraBoldItalic-tlf-ly1--base.tfm \
tex-atkinsn-ExtraBoldItalic-tlf-ly1.tfm \
tex-atkinsn-ExtraBoldItalic-tlf-ly1.vf \
tex-atkinsn-ExtraBoldItalic-tlf-ot1.tfm \
tex-atkinsn-ExtraBoldItalic-tlf-t1--base.tfm \
tex-atkinsn-ExtraBoldItalic-tlf-t1.tfm \
tex-atkinsn-ExtraBoldItalic-tlf-t1.vf \
tex-atkinsn-ExtraBoldItalic-tlf-ts1--base.tfm \
tex-atkinsn-ExtraBoldItalic-tlf-ts1.tfm \
tex-atkinsn-ExtraBoldItalic-tlf-ts1.vf \
tex-atkinsn-ExtraLight-lf-ly1--base.tfm \
tex-atkinsn-ExtraLight-lf-ly1.tfm \
tex-atkinsn-ExtraLight-lf-ly1.vf \
tex-atkinsn-ExtraLight-lf-ot1.tfm \
tex-atkinsn-ExtraLight-lf-t1--base.tfm \
tex-atkinsn-ExtraLight-lf-t1.tfm \
tex-atkinsn-ExtraLight-lf-t1.vf \
tex-atkinsn-ExtraLight-lf-ts1--base.tfm \
tex-atkinsn-ExtraLight-lf-ts1.tfm \
tex-atkinsn-ExtraLight-lf-ts1.vf \
tex-atkinsn-ExtraLight-sup-ly1--base.tfm \
tex-atkinsn-ExtraLight-sup-ly1.tfm \
tex-atkinsn-ExtraLight-sup-ly1.vf \
tex-atkinsn-ExtraLight-sup-ot1.tfm \
tex-atkinsn-ExtraLight-sup-t1--base.tfm \
tex-atkinsn-ExtraLight-sup-t1.tfm \
tex-atkinsn-ExtraLight-sup-t1.vf \
tex-atkinsn-ExtraLight-tlf-ly1--base.tfm \
tex-atkinsn-ExtraLight-tlf-ly1.tfm \
tex-atkinsn-ExtraLight-tlf-ly1.vf \
tex-atkinsn-ExtraLight-tlf-ot1.tfm \
tex-atkinsn-ExtraLight-tlf-t1--base.tfm \
tex-atkinsn-ExtraLight-tlf-t1.tfm \
tex-atkinsn-ExtraLight-tlf-t1.vf \
tex-atkinsn-ExtraLight-tlf-ts1--base.tfm \
tex-atkinsn-ExtraLight-tlf-ts1.tfm \
tex-atkinsn-ExtraLight-tlf-ts1.vf \
tex-atkinsn-ExtraLightItalic-lf-ly1--base.tfm \
tex-atkinsn-ExtraLightItalic-lf-ly1.tfm \
tex-atkinsn-ExtraLightItalic-lf-ly1.vf \
tex-atkinsn-ExtraLightItalic-lf-ot1.tfm \
tex-atkinsn-ExtraLightItalic-lf-t1--base.tfm \
tex-atkinsn-ExtraLightItalic-lf-t1.tfm \
tex-atkinsn-ExtraLightItalic-lf-t1.vf \
tex-atkinsn-ExtraLightItalic-lf-ts1--base.tfm \
tex-atkinsn-ExtraLightItalic-lf-ts1.tfm \
tex-atkinsn-ExtraLightItalic-lf-ts1.vf \
tex-atkinsn-ExtraLightItalic-sup-ly1--base.tfm \
tex-atkinsn-ExtraLightItalic-sup-ly1.tfm \
tex-atkinsn-ExtraLightItalic-sup-ly1.vf \
tex-atkinsn-ExtraLightItalic-sup-ot1.tfm \
tex-atkinsn-ExtraLightItalic-sup-t1--base.tfm \
tex-atkinsn-ExtraLightItalic-sup-t1.tfm \
tex-atkinsn-ExtraLightItalic-sup-t1.vf \
tex-atkinsn-ExtraLightItalic-tlf-ly1--base.tfm \
tex-atkinsn-ExtraLightItalic-tlf-ly1.tfm \
tex-atkinsn-ExtraLightItalic-tlf-ly1.vf \
tex-atkinsn-ExtraLightItalic-tlf-ot1.tfm \
tex-atkinsn-ExtraLightItalic-tlf-t1--base.tfm \
tex-atkinsn-ExtraLightItalic-tlf-t1.tfm \
tex-atkinsn-ExtraLightItalic-tlf-t1.vf \
tex-atkinsn-ExtraLightItalic-tlf-ts1--base.tfm \
tex-atkinsn-ExtraLightItalic-tlf-ts1.tfm \
tex-atkinsn-ExtraLightItalic-tlf-ts1.vf \
tex-atkinsn-Light-lf-ly1--base.tfm \
tex-atkinsn-Light-lf-ly1.tfm \
tex-atkinsn-Light-lf-ly1.vf \
tex-atkinsn-Light-lf-ot1.tfm \
tex-atkinsn-Light-lf-t1--base.tfm \
tex-atkinsn-Light-lf-t1.tfm \
tex-atkinsn-Light-lf-t1.vf \
tex-atkinsn-Light-lf-ts1--base.tfm \
tex-atkinsn-Light-lf-ts1.tfm \
tex-atkinsn-Light-lf-ts1.vf \
tex-atkinsn-Light-sup-ly1--base.tfm \
tex-atkinsn-Light-sup-ly1.tfm \
tex-atkinsn-Light-sup-ly1.vf \
tex-atkinsn-Light-sup-ot1.tfm \
tex-atkinsn-Light-sup-t1--base.tfm \
tex-atkinsn-Light-sup-t1.tfm \
tex-atkinsn-Light-sup-t1.vf \
tex-atkinsn-Light-tlf-ly1--base.tfm \
tex-atkinsn-Light-tlf-ly1.tfm \
tex-atkinsn-Light-tlf-ly1.vf \
tex-atkinsn-Light-tlf-ot1.tfm \
tex-atkinsn-Light-tlf-t1--base.tfm \
tex-atkinsn-Light-tlf-t1.tfm \
tex-atkinsn-Light-tlf-t1.vf \
tex-atkinsn-Light-tlf-ts1--base.tfm \
tex-atkinsn-Light-tlf-ts1.tfm \
tex-atkinsn-Light-tlf-ts1.vf \
tex-atkinsn-LightItalic-lf-ly1--base.tfm \
tex-atkinsn-LightItalic-lf-ly1.tfm \
tex-atkinsn-LightItalic-lf-ly1.vf \
tex-atkinsn-LightItalic-lf-ot1.tfm \
tex-atkinsn-LightItalic-lf-t1--base.tfm \
tex-atkinsn-LightItalic-lf-t1.tfm \
tex-atkinsn-LightItalic-lf-t1.vf \
tex-atkinsn-LightItalic-lf-ts1--base.tfm \
tex-atkinsn-LightItalic-lf-ts1.tfm \
tex-atkinsn-LightItalic-lf-ts1.vf \
tex-atkinsn-LightItalic-sup-ly1--base.tfm \
tex-atkinsn-LightItalic-sup-ly1.tfm \
tex-atkinsn-LightItalic-sup-ly1.vf \
tex-atkinsn-LightItalic-sup-ot1.tfm \
tex-atkinsn-LightItalic-sup-t1--base.tfm \
tex-atkinsn-LightItalic-sup-t1.tfm \
tex-atkinsn-LightItalic-sup-t1.vf \
tex-atkinsn-LightItalic-tlf-ly1--base.tfm \
tex-atkinsn-LightItalic-tlf-ly1.tfm \
tex-atkinsn-LightItalic-tlf-ly1.vf \
tex-atkinsn-LightItalic-tlf-ot1.tfm \
tex-atkinsn-LightItalic-tlf-t1--base.tfm \
tex-atkinsn-LightItalic-tlf-t1.tfm \
tex-atkinsn-LightItalic-tlf-t1.vf \
tex-atkinsn-LightItalic-tlf-ts1--base.tfm \
tex-atkinsn-LightItalic-tlf-ts1.tfm \
tex-atkinsn-LightItalic-tlf-ts1.vf \
tex-atkinsn-Medium-lf-ly1--base.tfm \
tex-atkinsn-Medium-lf-ly1.tfm \
tex-atkinsn-Medium-lf-ly1.vf \
tex-atkinsn-Medium-lf-ot1.tfm \
tex-atkinsn-Medium-lf-t1--base.tfm \
tex-atkinsn-Medium-lf-t1.tfm \
tex-atkinsn-Medium-lf-t1.vf \
tex-atkinsn-Medium-lf-ts1--base.tfm \
tex-atkinsn-Medium-lf-ts1.tfm \
tex-atkinsn-Medium-lf-ts1.vf \
tex-atkinsn-Medium-sup-ly1--base.tfm \
tex-atkinsn-Medium-sup-ly1.tfm \
tex-atkinsn-Medium-sup-ly1.vf \
tex-atkinsn-Medium-sup-ot1.tfm \
tex-atkinsn-Medium-sup-t1--base.tfm \
tex-atkinsn-Medium-sup-t1.tfm \
tex-atkinsn-Medium-sup-t1.vf \
tex-atkinsn-Medium-tlf-ly1--base.tfm \
tex-atkinsn-Medium-tlf-ly1.tfm \
tex-atkinsn-Medium-tlf-ly1.vf \
tex-atkinsn-Medium-tlf-ot1.tfm \
tex-atkinsn-Medium-tlf-t1--base.tfm \
tex-atkinsn-Medium-tlf-t1.tfm \
tex-atkinsn-Medium-tlf-t1.vf \
tex-atkinsn-Medium-tlf-ts1--base.tfm \
tex-atkinsn-Medium-tlf-ts1.tfm \
tex-atkinsn-Medium-tlf-ts1.vf \
tex-atkinsn-MediumItalic-lf-ly1--base.tfm \
tex-atkinsn-MediumItalic-lf-ly1.tfm \
tex-atkinsn-MediumItalic-lf-ly1.vf \
tex-atkinsn-MediumItalic-lf-ot1.tfm \
tex-atkinsn-MediumItalic-lf-t1--base.tfm \
tex-atkinsn-MediumItalic-lf-t1.tfm \
tex-atkinsn-MediumItalic-lf-t1.vf \
tex-atkinsn-MediumItalic-lf-ts1--base.tfm \
tex-atkinsn-MediumItalic-lf-ts1.tfm \
tex-atkinsn-MediumItalic-lf-ts1.vf \
tex-atkinsn-MediumItalic-sup-ly1--base.tfm \
tex-atkinsn-MediumItalic-sup-ly1.tfm \
tex-atkinsn-MediumItalic-sup-ly1.vf \
tex-atkinsn-MediumItalic-sup-ot1.tfm \
tex-atkinsn-MediumItalic-sup-t1--base.tfm \
tex-atkinsn-MediumItalic-sup-t1.tfm \
tex-atkinsn-MediumItalic-sup-t1.vf \
tex-atkinsn-MediumItalic-tlf-ly1--base.tfm \
tex-atkinsn-MediumItalic-tlf-ly1.tfm \
tex-atkinsn-MediumItalic-tlf-ly1.vf \
tex-atkinsn-MediumItalic-tlf-ot1.tfm \
tex-atkinsn-MediumItalic-tlf-t1--base.tfm \
tex-atkinsn-MediumItalic-tlf-t1.tfm \
tex-atkinsn-MediumItalic-tlf-t1.vf \
tex-atkinsn-MediumItalic-tlf-ts1--base.tfm \
tex-atkinsn-MediumItalic-tlf-ts1.tfm \
tex-atkinsn-MediumItalic-tlf-ts1.vf \
tex-atkinsn-Regular-lf-ly1--base.tfm \
tex-atkinsn-Regular-lf-ly1.tfm \
tex-atkinsn-Regular-lf-ly1.vf \
tex-atkinsn-Regular-lf-ot1.tfm \
tex-atkinsn-Regular-lf-t1--base.tfm \
tex-atkinsn-Regular-lf-t1.tfm \
tex-atkinsn-Regular-lf-t1.vf \
tex-atkinsn-Regular-lf-ts1--base.tfm \
tex-atkinsn-Regular-lf-ts1.tfm \
tex-atkinsn-Regular-lf-ts1.vf \
tex-atkinsn-Regular-sup-ly1--base.tfm \
tex-atkinsn-Regular-sup-ly1.tfm \
tex-atkinsn-Regular-sup-ly1.vf \
tex-atkinsn-Regular-sup-ot1.tfm \
tex-atkinsn-Regular-sup-t1--base.tfm \
tex-atkinsn-Regular-sup-t1.tfm \
tex-atkinsn-Regular-sup-t1.vf \
tex-atkinsn-Regular-tlf-ly1--base.tfm \
tex-atkinsn-Regular-tlf-ly1.tfm \
tex-atkinsn-Regular-tlf-ly1.vf \
tex-atkinsn-Regular-tlf-ot1.tfm \
tex-atkinsn-Regular-tlf-t1--base.tfm \
tex-atkinsn-Regular-tlf-t1.tfm \
tex-atkinsn-Regular-tlf-t1.vf \
tex-atkinsn-Regular-tlf-ts1--base.tfm \
tex-atkinsn-Regular-tlf-ts1.tfm \
tex-atkinsn-Regular-tlf-ts1.vf \
tex-atkinsn-RegularItalic-lf-ly1--base.tfm \
tex-atkinsn-RegularItalic-lf-ly1.tfm \
tex-atkinsn-RegularItalic-lf-ly1.vf \
tex-atkinsn-RegularItalic-lf-ot1.tfm \
tex-atkinsn-RegularItalic-lf-t1--base.tfm \
tex-atkinsn-RegularItalic-lf-t1.tfm \
tex-atkinsn-RegularItalic-lf-t1.vf \
tex-atkinsn-RegularItalic-lf-ts1--base.tfm \
tex-atkinsn-RegularItalic-lf-ts1.tfm \
tex-atkinsn-RegularItalic-lf-ts1.vf \
tex-atkinsn-RegularItalic-sup-ly1--base.tfm \
tex-atkinsn-RegularItalic-sup-ly1.tfm \
tex-atkinsn-RegularItalic-sup-ly1.vf \
tex-atkinsn-RegularItalic-sup-ot1.tfm \
tex-atkinsn-RegularItalic-sup-t1--base.tfm \
tex-atkinsn-RegularItalic-sup-t1.tfm \
tex-atkinsn-RegularItalic-sup-t1.vf \
tex-atkinsn-RegularItalic-tlf-ly1--base.tfm \
tex-atkinsn-RegularItalic-tlf-ly1.tfm \
tex-atkinsn-RegularItalic-tlf-ly1.vf \
tex-atkinsn-RegularItalic-tlf-ot1.tfm \
tex-atkinsn-RegularItalic-tlf-t1--base.tfm \
tex-atkinsn-RegularItalic-tlf-t1.tfm \
tex-atkinsn-RegularItalic-tlf-t1.vf \
tex-atkinsn-RegularItalic-tlf-ts1--base.tfm \
tex-atkinsn-RegularItalic-tlf-ts1.tfm \
tex-atkinsn-RegularItalic-tlf-ts1.vf \
tex-atkinsn-SemiBold-lf-ly1--base.tfm \
tex-atkinsn-SemiBold-lf-ly1.tfm \
tex-atkinsn-SemiBold-lf-ly1.vf \
tex-atkinsn-SemiBold-lf-ot1.tfm \
tex-atkinsn-SemiBold-lf-t1--base.tfm \
tex-atkinsn-SemiBold-lf-t1.tfm \
tex-atkinsn-SemiBold-lf-t1.vf \
tex-atkinsn-SemiBold-lf-ts1--base.tfm \
tex-atkinsn-SemiBold-lf-ts1.tfm \
tex-atkinsn-SemiBold-lf-ts1.vf \
tex-atkinsn-SemiBold-sup-ly1--base.tfm \
tex-atkinsn-SemiBold-sup-ly1.tfm \
tex-atkinsn-SemiBold-sup-ly1.vf \
tex-atkinsn-SemiBold-sup-ot1.tfm \
tex-atkinsn-SemiBold-sup-t1--base.tfm \
tex-atkinsn-SemiBold-sup-t1.tfm \
tex-atkinsn-SemiBold-sup-t1.vf \
tex-atkinsn-SemiBold-tlf-ly1--base.tfm \
tex-atkinsn-SemiBold-tlf-ly1.tfm \
tex-atkinsn-SemiBold-tlf-ly1.vf \
tex-atkinsn-SemiBold-tlf-ot1.tfm \
tex-atkinsn-SemiBold-tlf-t1--base.tfm \
tex-atkinsn-SemiBold-tlf-t1.tfm \
tex-atkinsn-SemiBold-tlf-t1.vf \
tex-atkinsn-SemiBold-tlf-ts1--base.tfm \
tex-atkinsn-SemiBold-tlf-ts1.tfm \
tex-atkinsn-SemiBold-tlf-ts1.vf \
tex-atkinsn-SemiBoldItalic-lf-ly1--base.tfm \
tex-atkinsn-SemiBoldItalic-lf-ly1.tfm \
tex-atkinsn-SemiBoldItalic-lf-ly1.vf \
tex-atkinsn-SemiBoldItalic-lf-ot1.tfm \
tex-atkinsn-SemiBoldItalic-lf-t1--base.tfm \
tex-atkinsn-SemiBoldItalic-lf-t1.tfm \
tex-atkinsn-SemiBoldItalic-lf-t1.vf \
tex-atkinsn-SemiBoldItalic-lf-ts1--base.tfm \
tex-atkinsn-SemiBoldItalic-lf-ts1.tfm \
tex-atkinsn-SemiBoldItalic-lf-ts1.vf \
tex-atkinsn-SemiBoldItalic-sup-ly1--base.tfm \
tex-atkinsn-SemiBoldItalic-sup-ly1.tfm \
tex-atkinsn-SemiBoldItalic-sup-ly1.vf \
tex-atkinsn-SemiBoldItalic-sup-ot1.tfm \
tex-atkinsn-SemiBoldItalic-sup-t1--base.tfm \
tex-atkinsn-SemiBoldItalic-sup-t1.tfm \
tex-atkinsn-SemiBoldItalic-sup-t1.vf \
tex-atkinsn-SemiBoldItalic-tlf-ly1--base.tfm \
tex-atkinsn-SemiBoldItalic-tlf-ly1.tfm \
tex-atkinsn-SemiBoldItalic-tlf-ly1.vf \
tex-atkinsn-SemiBoldItalic-tlf-ot1.tfm \
tex-atkinsn-SemiBoldItalic-tlf-t1--base.tfm \
tex-atkinsn-SemiBoldItalic-tlf-t1.tfm \
tex-atkinsn-SemiBoldItalic-tlf-t1.vf \
tex-atkinsn-SemiBoldItalic-tlf-ts1--base.tfm \
tex-atkinsn-SemiBoldItalic-tlf-ts1.tfm \
tex-atkinsn-SemiBoldItalic-tlf-ts1.vf \
tex-atkinsn-bbsfwk.enc \
tex-atkinsn-bxlfxu.enc \
tex-atkinsn-ehsai2.enc \
tex-atkinsn-ghg2ik.enc \
tex-atkinsn-gjro6p.enc \
tex-atkinsn-k53f2f.enc \
tex-atkinsn-sxa7r4.enc \
tex-atkinsn-tlrdxq.enc \
tex-atkinsnmono-2euc5w.enc \
tex-atkinsnmono-Bold-sup-ly1--base.tfm \
tex-atkinsnmono-Bold-sup-ly1.tfm \
tex-atkinsnmono-Bold-sup-ly1.vf \
tex-atkinsnmono-Bold-sup-ot1.tfm \
tex-atkinsnmono-Bold-sup-t1--base.tfm \
tex-atkinsnmono-Bold-sup-t1.tfm \
tex-atkinsnmono-Bold-sup-t1.vf \
tex-atkinsnmono-Bold-tlf-ly1--base.tfm \
tex-atkinsnmono-Bold-tlf-ly1.tfm \
tex-atkinsnmono-Bold-tlf-ly1.vf \
tex-atkinsnmono-Bold-tlf-ot1.tfm \
tex-atkinsnmono-Bold-tlf-t1--base.tfm \
tex-atkinsnmono-Bold-tlf-t1.tfm \
tex-atkinsnmono-Bold-tlf-t1.vf \
tex-atkinsnmono-Bold-tlf-ts1--base.tfm \
tex-atkinsnmono-Bold-tlf-ts1.tfm \
tex-atkinsnmono-Bold-tlf-ts1.vf \
tex-atkinsnmono-BoldItalic-sup-ly1--base.tfm \
tex-atkinsnmono-BoldItalic-sup-ly1.tfm \
tex-atkinsnmono-BoldItalic-sup-ly1.vf \
tex-atkinsnmono-BoldItalic-sup-ot1.tfm \
tex-atkinsnmono-BoldItalic-sup-t1--base.tfm \
tex-atkinsnmono-BoldItalic-sup-t1.tfm \
tex-atkinsnmono-BoldItalic-sup-t1.vf \
tex-atkinsnmono-BoldItalic-tlf-ly1--base.tfm \
tex-atkinsnmono-BoldItalic-tlf-ly1.tfm \
tex-atkinsnmono-BoldItalic-tlf-ly1.vf \
tex-atkinsnmono-BoldItalic-tlf-ot1.tfm \
tex-atkinsnmono-BoldItalic-tlf-t1--base.tfm \
tex-atkinsnmono-BoldItalic-tlf-t1.tfm \
tex-atkinsnmono-BoldItalic-tlf-t1.vf \
tex-atkinsnmono-BoldItalic-tlf-ts1--base.tfm \
tex-atkinsnmono-BoldItalic-tlf-ts1.tfm \
tex-atkinsnmono-BoldItalic-tlf-ts1.vf \
tex-atkinsnmono-ExtraBold-sup-ly1--base.tfm \
tex-atkinsnmono-ExtraBold-sup-ly1.tfm \
tex-atkinsnmono-ExtraBold-sup-ly1.vf \
tex-atkinsnmono-ExtraBold-sup-ot1.tfm \
tex-atkinsnmono-ExtraBold-sup-t1--base.tfm \
tex-atkinsnmono-ExtraBold-sup-t1.tfm \
tex-atkinsnmono-ExtraBold-sup-t1.vf \
tex-atkinsnmono-ExtraBold-tlf-ly1--base.tfm \
tex-atkinsnmono-ExtraBold-tlf-ly1.tfm \
tex-atkinsnmono-ExtraBold-tlf-ly1.vf \
tex-atkinsnmono-ExtraBold-tlf-ot1.tfm \
tex-atkinsnmono-ExtraBold-tlf-t1--base.tfm \
tex-atkinsnmono-ExtraBold-tlf-t1.tfm \
tex-atkinsnmono-ExtraBold-tlf-t1.vf \
tex-atkinsnmono-ExtraBold-tlf-ts1--base.tfm \
tex-atkinsnmono-ExtraBold-tlf-ts1.tfm \
tex-atkinsnmono-ExtraBold-tlf-ts1.vf \
tex-atkinsnmono-ExtraBoldItalic-sup-ly1--base.tfm \
tex-atkinsnmono-ExtraBoldItalic-sup-ly1.tfm \
tex-atkinsnmono-ExtraBoldItalic-sup-ly1.vf \
tex-atkinsnmono-ExtraBoldItalic-sup-ot1.tfm \
tex-atkinsnmono-ExtraBoldItalic-sup-t1--base.tfm \
tex-atkinsnmono-ExtraBoldItalic-sup-t1.tfm \
tex-atkinsnmono-ExtraBoldItalic-sup-t1.vf \
tex-atkinsnmono-ExtraBoldItalic-tlf-ly1--base.tfm \
tex-atkinsnmono-ExtraBoldItalic-tlf-ly1.tfm \
tex-atkinsnmono-ExtraBoldItalic-tlf-ly1.vf \
tex-atkinsnmono-ExtraBoldItalic-tlf-ot1.tfm \
tex-atkinsnmono-ExtraBoldItalic-tlf-t1--base.tfm \
tex-atkinsnmono-ExtraBoldItalic-tlf-t1.tfm \
tex-atkinsnmono-ExtraBoldItalic-tlf-t1.vf \
tex-atkinsnmono-ExtraBoldItalic-tlf-ts1--base.tfm \
tex-atkinsnmono-ExtraBoldItalic-tlf-ts1.tfm \
tex-atkinsnmono-ExtraBoldItalic-tlf-ts1.vf \
tex-atkinsnmono-ExtraLight-sup-ly1--base.tfm \
tex-atkinsnmono-ExtraLight-sup-ly1.tfm \
tex-atkinsnmono-ExtraLight-sup-ly1.vf \
tex-atkinsnmono-ExtraLight-sup-ot1.tfm \
tex-atkinsnmono-ExtraLight-sup-t1--base.tfm \
tex-atkinsnmono-ExtraLight-sup-t1.tfm \
tex-atkinsnmono-ExtraLight-sup-t1.vf \
tex-atkinsnmono-ExtraLight-tlf-ly1--base.tfm \
tex-atkinsnmono-ExtraLight-tlf-ly1.tfm \
tex-atkinsnmono-ExtraLight-tlf-ly1.vf \
tex-atkinsnmono-ExtraLight-tlf-ot1.tfm \
tex-atkinsnmono-ExtraLight-tlf-t1--base.tfm \
tex-atkinsnmono-ExtraLight-tlf-t1.tfm \
tex-atkinsnmono-ExtraLight-tlf-t1.vf \
tex-atkinsnmono-ExtraLight-tlf-ts1--base.tfm \
tex-atkinsnmono-ExtraLight-tlf-ts1.tfm \
tex-atkinsnmono-ExtraLight-tlf-ts1.vf \
tex-atkinsnmono-ExtraLightItalic-sup-ly1--base.tfm \
tex-atkinsnmono-ExtraLightItalic-sup-ly1.tfm \
tex-atkinsnmono-ExtraLightItalic-sup-ly1.vf \
tex-atkinsnmono-ExtraLightItalic-sup-ot1.tfm \
tex-atkinsnmono-ExtraLightItalic-sup-t1--base.tfm \
tex-atkinsnmono-ExtraLightItalic-sup-t1.tfm \
tex-atkinsnmono-ExtraLightItalic-sup-t1.vf \
tex-atkinsnmono-ExtraLightItalic-tlf-ly1--base.tfm \
tex-atkinsnmono-ExtraLightItalic-tlf-ly1.tfm \
tex-atkinsnmono-ExtraLightItalic-tlf-ly1.vf \
tex-atkinsnmono-ExtraLightItalic-tlf-ot1.tfm \
tex-atkinsnmono-ExtraLightItalic-tlf-t1--base.tfm \
tex-atkinsnmono-ExtraLightItalic-tlf-t1.tfm \
tex-atkinsnmono-ExtraLightItalic-tlf-t1.vf \
tex-atkinsnmono-ExtraLightItalic-tlf-ts1--base.tfm \
tex-atkinsnmono-ExtraLightItalic-tlf-ts1.tfm \
tex-atkinsnmono-ExtraLightItalic-tlf-ts1.vf \
tex-atkinsnmono-Light-sup-ly1--base.tfm \
tex-atkinsnmono-Light-sup-ly1.tfm \
tex-atkinsnmono-Light-sup-ly1.vf \
tex-atkinsnmono-Light-sup-ot1.tfm \
tex-atkinsnmono-Light-sup-t1--base.tfm \
tex-atkinsnmono-Light-sup-t1.tfm \
tex-atkinsnmono-Light-sup-t1.vf \
tex-atkinsnmono-Light-tlf-ly1--base.tfm \
tex-atkinsnmono-Light-tlf-ly1.tfm \
tex-atkinsnmono-Light-tlf-ly1.vf \
tex-atkinsnmono-Light-tlf-ot1.tfm \
tex-atkinsnmono-Light-tlf-t1--base.tfm \
tex-atkinsnmono-Light-tlf-t1.tfm \
tex-atkinsnmono-Light-tlf-t1.vf \
tex-atkinsnmono-Light-tlf-ts1--base.tfm \
tex-atkinsnmono-Light-tlf-ts1.tfm \
tex-atkinsnmono-Light-tlf-ts1.vf \
tex-atkinsnmono-LightItalic-sup-ly1--base.tfm \
tex-atkinsnmono-LightItalic-sup-ly1.tfm \
tex-atkinsnmono-LightItalic-sup-ly1.vf \
tex-atkinsnmono-LightItalic-sup-ot1.tfm \
tex-atkinsnmono-LightItalic-sup-t1--base.tfm \
tex-atkinsnmono-LightItalic-sup-t1.tfm \
tex-atkinsnmono-LightItalic-sup-t1.vf \
tex-atkinsnmono-LightItalic-tlf-ly1--base.tfm \
tex-atkinsnmono-LightItalic-tlf-ly1.tfm \
tex-atkinsnmono-LightItalic-tlf-ly1.vf \
tex-atkinsnmono-LightItalic-tlf-ot1.tfm \
tex-atkinsnmono-LightItalic-tlf-t1--base.tfm \
tex-atkinsnmono-LightItalic-tlf-t1.tfm \
tex-atkinsnmono-LightItalic-tlf-t1.vf \
tex-atkinsnmono-LightItalic-tlf-ts1--base.tfm \
tex-atkinsnmono-LightItalic-tlf-ts1.tfm \
tex-atkinsnmono-LightItalic-tlf-ts1.vf \
tex-atkinsnmono-Medium-sup-ly1--base.tfm \
tex-atkinsnmono-Medium-sup-ly1.tfm \
tex-atkinsnmono-Medium-sup-ly1.vf \
tex-atkinsnmono-Medium-sup-ot1.tfm \
tex-atkinsnmono-Medium-sup-t1--base.tfm \
tex-atkinsnmono-Medium-sup-t1.tfm \
tex-atkinsnmono-Medium-sup-t1.vf \
tex-atkinsnmono-Medium-tlf-ly1--base.tfm \
tex-atkinsnmono-Medium-tlf-ly1.tfm \
tex-atkinsnmono-Medium-tlf-ly1.vf \
tex-atkinsnmono-Medium-tlf-ot1.tfm \
tex-atkinsnmono-Medium-tlf-t1--base.tfm \
tex-atkinsnmono-Medium-tlf-t1.tfm \
tex-atkinsnmono-Medium-tlf-t1.vf \
tex-atkinsnmono-Medium-tlf-ts1--base.tfm \
tex-atkinsnmono-Medium-tlf-ts1.tfm \
tex-atkinsnmono-Medium-tlf-ts1.vf \
tex-atkinsnmono-MediumItalic-sup-ly1--base.tfm \
tex-atkinsnmono-MediumItalic-sup-ly1.tfm \
tex-atkinsnmono-MediumItalic-sup-ly1.vf \
tex-atkinsnmono-MediumItalic-sup-ot1.tfm \
tex-atkinsnmono-MediumItalic-sup-t1--base.tfm \
tex-atkinsnmono-MediumItalic-sup-t1.tfm \
tex-atkinsnmono-MediumItalic-sup-t1.vf \
tex-atkinsnmono-MediumItalic-tlf-ly1--base.tfm \
tex-atkinsnmono-MediumItalic-tlf-ly1.tfm \
tex-atkinsnmono-MediumItalic-tlf-ly1.vf \
tex-atkinsnmono-MediumItalic-tlf-ot1.tfm \
tex-atkinsnmono-MediumItalic-tlf-t1--base.tfm \
tex-atkinsnmono-MediumItalic-tlf-t1.tfm \
tex-atkinsnmono-MediumItalic-tlf-t1.vf \
tex-atkinsnmono-MediumItalic-tlf-ts1--base.tfm \
tex-atkinsnmono-MediumItalic-tlf-ts1.tfm \
tex-atkinsnmono-MediumItalic-tlf-ts1.vf \
tex-atkinsnmono-Regular-sup-ly1--base.tfm \
tex-atkinsnmono-Regular-sup-ly1.tfm \
tex-atkinsnmono-Regular-sup-ly1.vf \
tex-atkinsnmono-Regular-sup-ot1.tfm \
tex-atkinsnmono-Regular-sup-t1--base.tfm \
tex-atkinsnmono-Regular-sup-t1.tfm \
tex-atkinsnmono-Regular-sup-t1.vf \
tex-atkinsnmono-Regular-tlf-ly1--base.tfm \
tex-atkinsnmono-Regular-tlf-ly1.tfm \
tex-atkinsnmono-Regular-tlf-ly1.vf \
tex-atkinsnmono-Regular-tlf-ot1.tfm \
tex-atkinsnmono-Regular-tlf-t1--base.tfm \
tex-atkinsnmono-Regular-tlf-t1.tfm \
tex-atkinsnmono-Regular-tlf-t1.vf \
tex-atkinsnmono-Regular-tlf-ts1--base.tfm \
tex-atkinsnmono-Regular-tlf-ts1.tfm \
tex-atkinsnmono-Regular-tlf-ts1.vf \
tex-atkinsnmono-RegularItalic-sup-ly1--base.tfm \
tex-atkinsnmono-RegularItalic-sup-ly1.tfm \
tex-atkinsnmono-RegularItalic-sup-ly1.vf \
tex-atkinsnmono-RegularItalic-sup-ot1.tfm \
tex-atkinsnmono-RegularItalic-sup-t1--base.tfm \
tex-atkinsnmono-RegularItalic-sup-t1.tfm \
tex-atkinsnmono-RegularItalic-sup-t1.vf \
tex-atkinsnmono-RegularItalic-tlf-ly1--base.tfm \
tex-atkinsnmono-RegularItalic-tlf-ly1.tfm \
tex-atkinsnmono-RegularItalic-tlf-ly1.vf \
tex-atkinsnmono-RegularItalic-tlf-ot1.tfm \
tex-atkinsnmono-RegularItalic-tlf-t1--base.tfm \
tex-atkinsnmono-RegularItalic-tlf-t1.tfm \
tex-atkinsnmono-RegularItalic-tlf-t1.vf \
tex-atkinsnmono-RegularItalic-tlf-ts1--base.tfm \
tex-atkinsnmono-RegularItalic-tlf-ts1.tfm \
tex-atkinsnmono-RegularItalic-tlf-ts1.vf \
tex-atkinsnmono-SemiBold-sup-ly1--base.tfm \
tex-atkinsnmono-SemiBold-sup-ly1.tfm \
tex-atkinsnmono-SemiBold-sup-ly1.vf \
tex-atkinsnmono-SemiBold-sup-ot1.tfm \
tex-atkinsnmono-SemiBold-sup-t1--base.tfm \
tex-atkinsnmono-SemiBold-sup-t1.tfm \
tex-atkinsnmono-SemiBold-sup-t1.vf \
tex-atkinsnmono-SemiBold-tlf-ly1--base.tfm \
tex-atkinsnmono-SemiBold-tlf-ly1.tfm \
tex-atkinsnmono-SemiBold-tlf-ly1.vf \
tex-atkinsnmono-SemiBold-tlf-ot1.tfm \
tex-atkinsnmono-SemiBold-tlf-t1--base.tfm \
tex-atkinsnmono-SemiBold-tlf-t1.tfm \
tex-atkinsnmono-SemiBold-tlf-t1.vf \
tex-atkinsnmono-SemiBold-tlf-ts1--base.tfm \
tex-atkinsnmono-SemiBold-tlf-ts1.tfm \
tex-atkinsnmono-SemiBold-tlf-ts1.vf \
tex-atkinsnmono-SemiBoldItalic-sup-ly1--base.tfm \
tex-atkinsnmono-SemiBoldItalic-sup-ly1.tfm \
tex-atkinsnmono-SemiBoldItalic-sup-ly1.vf \
tex-atkinsnmono-SemiBoldItalic-sup-ot1.tfm \
tex-atkinsnmono-SemiBoldItalic-sup-t1--base.tfm \
tex-atkinsnmono-SemiBoldItalic-sup-t1.tfm \
tex-atkinsnmono-SemiBoldItalic-sup-t1.vf \
tex-atkinsnmono-SemiBoldItalic-tlf-ly1--base.tfm \
tex-atkinsnmono-SemiBoldItalic-tlf-ly1.tfm \
tex-atkinsnmono-SemiBoldItalic-tlf-ly1.vf \
tex-atkinsnmono-SemiBoldItalic-tlf-ot1.tfm \
tex-atkinsnmono-SemiBoldItalic-tlf-t1--base.tfm \
tex-atkinsnmono-SemiBoldItalic-tlf-t1.tfm \
tex-atkinsnmono-SemiBoldItalic-tlf-t1.vf \
tex-atkinsnmono-SemiBoldItalic-tlf-ts1--base.tfm \
tex-atkinsnmono-SemiBoldItalic-tlf-ts1.tfm \
tex-atkinsnmono-SemiBoldItalic-tlf-ts1.vf \
tex-atkinsnmono-bbsfwk.enc \
tex-atkinsnmono-bxlfxu.enc \
tex-atkinsnmono-ehsai2.enc \
tex-atkinsnmono-ghg2ik.enc \
tex-atkinsnmono-k53f2f.enc \
tex-atkinsnmono-sxa7r4.enc \
tex-atkinson.map \
tex-atkinson.sty \
texlive-atkinson"

RDEPENDS:${PN} += "/usr/bin/sh \
coreutils \
ed \
findutils \
grep \
sed \
tex-fontaxes.sty \
tex-fontenc.sty \
tex-fontspec.sty \
tex-ifluatex.sty \
tex-ifxetex.sty \
tex-mweights.sty \
tex-textcomp.sty \
tex-updmap.cfg \
tex-xkeyval.sty \
texlive \
texlive-atkinson-fonts \
texlive-filesystem \
texlive-kpathsea \
texlive-kpathsea-bin \
texlive-scripts \
texlive-scripts-bin"

inherit rpm
