SUMMARY = "Command-line interface for email management"
DESCRIPTION = "Command-line interface for email management."
LICENSE = "AGPL-3.0-only & AGPL-3.0-or-later & GPL-2.0-or-later & MIT & bzip2-1.0.6 & MPL-2.0 & CC-BY-3.0 & BSD-4-Clause & OpenSSL & OFL-1.1"

PV = "2.1.0"

RPM_NAME = "himalaya-2.1.0-1.2.aarch64.rpm"
RPM_HASH = "b1324edf16ac7369048c09f501da268bfaafc8a611449e091dbf84033e4054c8ccc3212da6e9f7284c069537b702faed2a686ea333da7601cee66650f219cbeb"

RPROVIDES:${PN} += "bundled-rust-crate-abnf-core \
bundled-rust-crate-aho-corasick \
bundled-rust-crate-allocator-api2 \
bundled-rust-crate-anstream \
bundled-rust-crate-anstyle \
bundled-rust-crate-anstyle-parse \
bundled-rust-crate-anstyle-query \
bundled-rust-crate-anyhow \
bundled-rust-crate-ar-archive-writer \
bundled-rust-crate-ariadne \
bundled-rust-crate-autocfg \
bundled-rust-crate-base64 \
bundled-rust-crate-bitflags \
bundled-rust-crate-block-buffer \
bundled-rust-crate-bounded-static \
bundled-rust-crate-bounded-static-derive \
bundled-rust-crate-bumpalo \
bundled-rust-crate-bytes \
bundled-rust-crate-cc \
bundled-rust-crate-cfg-aliases \
bundled-rust-crate-cfg-if \
bundled-rust-crate-chacha20 \
bundled-rust-crate-charset \
bundled-rust-crate-chrono \
bundled-rust-crate-chumsky \
bundled-rust-crate-clap \
bundled-rust-crate-clap-builder \
bundled-rust-crate-clap-complete \
bundled-rust-crate-clap-derive \
bundled-rust-crate-clap-lex \
bundled-rust-crate-clap-mangen \
bundled-rust-crate-cmov \
bundled-rust-crate-colorchoice \
bundled-rust-crate-comfy-table \
bundled-rust-crate-convert-case \
bundled-rust-crate-cpufeatures \
bundled-rust-crate-crossterm \
bundled-rust-crate-crypto-common \
bundled-rust-crate-ctrlc \
bundled-rust-crate-ctutils \
bundled-rust-crate-defmt \
bundled-rust-crate-defmt-macros \
bundled-rust-crate-defmt-parser \
bundled-rust-crate-derive-more \
bundled-rust-crate-derive-more-impl \
bundled-rust-crate-digest \
bundled-rust-crate-dirs \
bundled-rust-crate-dirs-sys \
bundled-rust-crate-displaydoc \
bundled-rust-crate-document-features \
bundled-rust-crate-domain \
bundled-rust-crate-domain-macros \
bundled-rust-crate-dyn-clone \
bundled-rust-crate-encoding-rs \
bundled-rust-crate-env-filter \
bundled-rust-crate-env-logger \
bundled-rust-crate-equivalent \
bundled-rust-crate-errno \
bundled-rust-crate-fallible-iterator \
bundled-rust-crate-fallible-streaming-iterator \
bundled-rust-crate-find-msvc-tools \
bundled-rust-crate-foldhash \
bundled-rust-crate-form-urlencoded \
bundled-rust-crate-fuzzy-matcher \
bundled-rust-crate-gethostname \
bundled-rust-crate-getrandom \
bundled-rust-crate-git2 \
bundled-rust-crate-hashbrown \
bundled-rust-crate-hashify \
bundled-rust-crate-heck \
bundled-rust-crate-himalaya \
bundled-rust-crate-hmac \
bundled-rust-crate-httparse \
bundled-rust-crate-humansize \
bundled-rust-crate-hybrid-array \
bundled-rust-crate-iana-time-zone \
bundled-rust-crate-icu-collections \
bundled-rust-crate-icu-locale-core \
bundled-rust-crate-icu-normalizer \
bundled-rust-crate-icu-normalizer-data \
bundled-rust-crate-icu-properties \
bundled-rust-crate-icu-properties-data \
bundled-rust-crate-icu-provider \
bundled-rust-crate-idna \
bundled-rust-crate-idna-adapter \
bundled-rust-crate-imap-codec \
bundled-rust-crate-imap-types \
bundled-rust-crate-indexmap \
bundled-rust-crate-inquire \
bundled-rust-crate-io-gmail \
bundled-rust-crate-io-http \
bundled-rust-crate-io-imap \
bundled-rust-crate-io-jmap \
bundled-rust-crate-io-m2dir \
bundled-rust-crate-io-maildir \
bundled-rust-crate-io-msgraph \
bundled-rust-crate-io-pim-discovery \
bundled-rust-crate-io-pimdir \
bundled-rust-crate-io-proxy \
bundled-rust-crate-io-replica \
bundled-rust-crate-io-sasl \
bundled-rust-crate-io-smtp \
bundled-rust-crate-is-docker \
bundled-rust-crate-is-terminal-polyfill \
bundled-rust-crate-is-wsl \
bundled-rust-crate-itoa \
bundled-rust-crate-jiff \
bundled-rust-crate-jiff-core \
bundled-rust-crate-jobserver \
bundled-rust-crate-libc \
bundled-rust-crate-libgit2-sys \
bundled-rust-crate-libm \
bundled-rust-crate-libsqlite3-sys \
bundled-rust-crate-libz-sys \
bundled-rust-crate-linux-raw-sys \
bundled-rust-crate-litemap \
bundled-rust-crate-litrs \
bundled-rust-crate-lock-api \
bundled-rust-crate-log \
bundled-rust-crate-mail-builder \
bundled-rust-crate-mail-parser \
bundled-rust-crate-memchr \
bundled-rust-crate-mime \
bundled-rust-crate-mime-guess \
bundled-rust-crate-minimal-lexical \
bundled-rust-crate-mio \
bundled-rust-crate-nix \
bundled-rust-crate-nom \
bundled-rust-crate-num-traits \
bundled-rust-crate-object \
bundled-rust-crate-octseq \
bundled-rust-crate-once-cell \
bundled-rust-crate-open \
bundled-rust-crate-openssl-probe \
bundled-rust-crate-option-ext \
bundled-rust-crate-parking-lot \
bundled-rust-crate-parking-lot-core \
bundled-rust-crate-pbkdf2 \
bundled-rust-crate-percent-encoding \
bundled-rust-crate-pimalaya-cli \
bundled-rust-crate-pimalaya-config \
bundled-rust-crate-pimalaya-stream \
bundled-rust-crate-pkg-config \
bundled-rust-crate-potential-utf \
bundled-rust-crate-proc-macro2 \
bundled-rust-crate-psm \
bundled-rust-crate-quote \
bundled-rust-crate-quoted-printable \
bundled-rust-crate-rand \
bundled-rust-crate-rand-core \
bundled-rust-crate-ref-cast \
bundled-rust-crate-ref-cast-impl \
bundled-rust-crate-regex \
bundled-rust-crate-regex-automata \
bundled-rust-crate-regex-syntax \
bundled-rust-crate-resolv-conf \
bundled-rust-crate-rfc2047-decoder \
bundled-rust-crate-ring \
bundled-rust-crate-roff \
bundled-rust-crate-rusqlite \
bundled-rust-crate-rustc-version \
bundled-rust-crate-rustix \
bundled-rust-crate-rustls \
bundled-rust-crate-rustls-native-certs \
bundled-rust-crate-rustls-pki-types \
bundled-rust-crate-rustls-platform-verifier \
bundled-rust-crate-rustls-webpki \
bundled-rust-crate-schemars \
bundled-rust-crate-schemars-derive \
bundled-rust-crate-scopeguard \
bundled-rust-crate-secrecy \
bundled-rust-crate-semver \
bundled-rust-crate-serde \
bundled-rust-crate-serde-core \
bundled-rust-crate-serde-derive \
bundled-rust-crate-serde-derive-internals \
bundled-rust-crate-serde-json \
bundled-rust-crate-serde-spanned \
bundled-rust-crate-serde-variant \
bundled-rust-crate-serde-xml-rs \
bundled-rust-crate-sha2 \
bundled-rust-crate-shellexpand \
bundled-rust-crate-shlex \
bundled-rust-crate-signal-hook \
bundled-rust-crate-signal-hook-mio \
bundled-rust-crate-signal-hook-registry \
bundled-rust-crate-smallvec \
bundled-rust-crate-stable-deref-trait \
bundled-rust-crate-stacker \
bundled-rust-crate-strsim \
bundled-rust-crate-subtle \
bundled-rust-crate-syn \
bundled-rust-crate-synstructure \
bundled-rust-crate-terminal-size \
bundled-rust-crate-thiserror \
bundled-rust-crate-thiserror-impl \
bundled-rust-crate-thread-local \
bundled-rust-crate-tinystr \
bundled-rust-crate-toml \
bundled-rust-crate-toml-datetime \
bundled-rust-crate-toml-parser \
bundled-rust-crate-toml-writer \
bundled-rust-crate-typenum \
bundled-rust-crate-unicase \
bundled-rust-crate-unicode-ident \
bundled-rust-crate-unicode-segmentation \
bundled-rust-crate-unicode-width \
bundled-rust-crate-untrusted \
bundled-rust-crate-url \
bundled-rust-crate-utf8-iter \
bundled-rust-crate-utf8parse \
bundled-rust-crate-vcpkg \
bundled-rust-crate-winnow \
bundled-rust-crate-writeable \
bundled-rust-crate-xml \
bundled-rust-crate-yansi \
bundled-rust-crate-yoke \
bundled-rust-crate-yoke-derive \
bundled-rust-crate-zerofrom \
bundled-rust-crate-zerofrom-derive \
bundled-rust-crate-zeroize \
bundled-rust-crate-zerotrie \
bundled-rust-crate-zerovec \
bundled-rust-crate-zerovec-derive \
bundled-rust-crate-zmij \
himalaya"

RDEPENDS:${PN} += "libc.so.6 \
libgcc-s.so.1 \
libm.so.6"

inherit rpm
