SUMMARY = "Firmware data files for SOF Drivers"
DESCRIPTION = "Firmware data files for Sound Open Firmware (SOF) drivers."
LICENSE = "BSD-3-Clause"

PV = "2025.12.2"

RPM_NAME = "sof-firmware-2025.12.2-1.2.noarch.rpm"
RPM_HASH = "305efa4bfdc6add4f42d46b761236bb135b1db7fa2e6cd85e05b571ea8b91376ab236f726260f7b7ab58a219d658892c0c7ad6bc6cd07a664757988b585d6ee0"
REPO_ARCH = "noarch"

RPROVIDES:${PN} += "firmware-intel/sof-ace-tplg/sof-adl-cs42l43-l0-cs35l56-l23.tplg \
firmware-intel/sof-ace-tplg/sof-adl-rt711-4ch.tplg \
firmware-intel/sof-ace-tplg/sof-adl-rt711-l0-rt1308-l12-rt715-l3.tplg \
firmware-intel/sof-ace-tplg/sof-adl-rt711-l0-rt1316-l12-rt714-l3.tplg \
firmware-intel/sof-ace-tplg/sof-adl-rt711-l0-rt1316-l13-rt714-l2.tplg \
firmware-intel/sof-ace-tplg/sof-arl-cs42l43-l0-cs35l56-l2-2ch.tplg \
firmware-intel/sof-ace-tplg/sof-arl-cs42l43-l0-cs35l56-l2.tplg \
firmware-intel/sof-ace-tplg/sof-arl-cs42l43-l0-cs35l56-l23.tplg \
firmware-intel/sof-ace-tplg/sof-arl-cs42l43-l0.tplg \
firmware-intel/sof-ace-tplg/sof-arl-cs42l43-l2-cs35l56-l3-2ch.tplg \
firmware-intel/sof-ace-tplg/sof-arl-cs42l43-l2-cs35l56-l3.tplg \
firmware-intel/sof-ace-tplg/sof-arl-cs42l43-l2.tplg \
firmware-intel/sof-ace-tplg/sof-arl-dmic-2ch-id2.tplg \
firmware-intel/sof-ace-tplg/sof-arl-dmic-2ch-id3.tplg \
firmware-intel/sof-ace-tplg/sof-arl-dmic-2ch-id4.tplg \
firmware-intel/sof-ace-tplg/sof-arl-dmic-2ch-id5.tplg \
firmware-intel/sof-ace-tplg/sof-arl-dmic-4ch-id2.tplg \
firmware-intel/sof-ace-tplg/sof-arl-dmic-4ch-id3.tplg \
firmware-intel/sof-ace-tplg/sof-arl-dmic-4ch-id4.tplg \
firmware-intel/sof-ace-tplg/sof-arl-dmic-4ch-id5.tplg \
firmware-intel/sof-ace-tplg/sof-arl-rt711-l0-2ch.tplg \
firmware-intel/sof-ace-tplg/sof-arl-rt711-l0-4ch.tplg \
firmware-intel/sof-ace-tplg/sof-arl-rt711-l0-rt1316-l3-2ch.tplg \
firmware-intel/sof-ace-tplg/sof-arl-rt711-l0-rt1316-l3-4ch.tplg \
firmware-intel/sof-ace-tplg/sof-arl-rt711-l0-rt1316-l3.tplg \
firmware-intel/sof-ace-tplg/sof-arl-rt711-l0.tplg \
firmware-intel/sof-ace-tplg/sof-arl-rt722-l0-rt1320-l2.tplg \
firmware-intel/sof-ace-tplg/sof-hda-generic-1ch.tplg \
firmware-intel/sof-ace-tplg/sof-hda-generic-2ch.tplg \
firmware-intel/sof-ace-tplg/sof-hda-generic-4ch.tplg \
firmware-intel/sof-ace-tplg/sof-hda-generic-ace1-1ch.tplg \
firmware-intel/sof-ace-tplg/sof-hda-generic-ace1-2ch.tplg \
firmware-intel/sof-ace-tplg/sof-hda-generic-ace1-4ch.tplg \
firmware-intel/sof-ace-tplg/sof-hda-generic-ace1-idisp-2ch.tplg \
firmware-intel/sof-ace-tplg/sof-hda-generic-ace1-idisp-4ch.tplg \
firmware-intel/sof-ace-tplg/sof-hda-generic-ace3-1ch.tplg \
firmware-intel/sof-ace-tplg/sof-hda-generic-ace3-2ch.tplg \
firmware-intel/sof-ace-tplg/sof-hda-generic-ace3-4ch.tplg \
firmware-intel/sof-ace-tplg/sof-hda-generic-ace3-idisp-2ch.tplg \
firmware-intel/sof-ace-tplg/sof-hda-generic-ace3-idisp-4ch.tplg \
firmware-intel/sof-ace-tplg/sof-hda-generic-cavs25-1ch.tplg \
firmware-intel/sof-ace-tplg/sof-hda-generic-cavs25-2ch.tplg \
firmware-intel/sof-ace-tplg/sof-hda-generic-cavs25-4ch.tplg \
firmware-intel/sof-ace-tplg/sof-hda-generic-cavs25-idisp-2ch.tplg \
firmware-intel/sof-ace-tplg/sof-hda-generic-cavs25-idisp-4ch.tplg \
firmware-intel/sof-ace-tplg/sof-hda-generic-idisp-2ch.tplg \
firmware-intel/sof-ace-tplg/sof-hda-generic-idisp-4ch.tplg \
firmware-intel/sof-ace-tplg/sof-hda-generic-idisp.tplg \
firmware-intel/sof-ace-tplg/sof-hda-generic.tplg \
firmware-intel/sof-ace-tplg/sof-hdmi-pcm5-id2.tplg \
firmware-intel/sof-ace-tplg/sof-hdmi-pcm5-id3.tplg \
firmware-intel/sof-ace-tplg/sof-hdmi-pcm5-id4.tplg \
firmware-intel/sof-ace-tplg/sof-hdmi-pcm5-id5.tplg \
firmware-intel/sof-ace-tplg/sof-hdmi-pcm5-id6.tplg \
firmware-intel/sof-ace-tplg/sof-hdmi-pcm5-id7.tplg \
firmware-intel/sof-ace-tplg/sof-lnl-cs42l43-l0-2ch.tplg \
firmware-intel/sof-ace-tplg/sof-lnl-cs42l43-l0-4ch.tplg \
firmware-intel/sof-ace-tplg/sof-lnl-cs42l43-l0-cs35l56-l23-2ch.tplg \
firmware-intel/sof-ace-tplg/sof-lnl-cs42l43-l0-cs35l56-l23-4ch.tplg \
firmware-intel/sof-ace-tplg/sof-lnl-cs42l43-l0-cs35l56-l23.tplg \
firmware-intel/sof-ace-tplg/sof-lnl-cs42l43-l0-cs35l56-l3-2ch.tplg \
firmware-intel/sof-ace-tplg/sof-lnl-cs42l43-l0-cs35l56-l3.tplg \
firmware-intel/sof-ace-tplg/sof-lnl-cs42l43-l0.tplg \
firmware-intel/sof-ace-tplg/sof-lnl-cs42l43-l2-cs35l56x6-l13.tplg \
firmware-intel/sof-ace-tplg/sof-lnl-dmic-2ch-id2.tplg \
firmware-intel/sof-ace-tplg/sof-lnl-dmic-2ch-id3.tplg \
firmware-intel/sof-ace-tplg/sof-lnl-dmic-2ch-id4.tplg \
firmware-intel/sof-ace-tplg/sof-lnl-dmic-2ch-id5.tplg \
firmware-intel/sof-ace-tplg/sof-lnl-dmic-4ch-id2.tplg \
firmware-intel/sof-ace-tplg/sof-lnl-dmic-4ch-id3.tplg \
firmware-intel/sof-ace-tplg/sof-lnl-dmic-4ch-id4.tplg \
firmware-intel/sof-ace-tplg/sof-lnl-dmic-4ch-id5.tplg \
firmware-intel/sof-ace-tplg/sof-lnl-rt1318-l12-rt714-l0.tplg \
firmware-intel/sof-ace-tplg/sof-lnl-rt1320-l12-rt714-l0.tplg \
firmware-intel/sof-ace-tplg/sof-lnl-rt711-4ch.tplg \
firmware-intel/sof-ace-tplg/sof-lnl-rt711-l0-rt1316-l23-rt714-l1.tplg \
firmware-intel/sof-ace-tplg/sof-lnl-rt712-l2-rt1320-l1.tplg \
firmware-intel/sof-ace-tplg/sof-lnl-rt712-l2-rt1712-l3.tplg \
firmware-intel/sof-ace-tplg/sof-lnl-rt713-l0-rt1318-l1-2ch.tplg \
firmware-intel/sof-ace-tplg/sof-lnl-rt713-l0-rt1318-l1.tplg \
firmware-intel/sof-ace-tplg/sof-lnl-rt713-l2-rt1320-l13.tplg \
firmware-intel/sof-ace-tplg/sof-lnl-rt722-l0.tplg \
firmware-intel/sof-ace-tplg/sof-mtl-cs35l56-l01-fb6.tplg \
firmware-intel/sof-ace-tplg/sof-mtl-cs35l56-l01-fb8.tplg \
firmware-intel/sof-ace-tplg/sof-mtl-cs42l43-l0-cs35l56-l12.tplg \
firmware-intel/sof-ace-tplg/sof-mtl-cs42l43-l0-cs35l56-l23.tplg \
firmware-intel/sof-ace-tplg/sof-mtl-cs42l43-l0.tplg \
firmware-intel/sof-ace-tplg/sof-mtl-cs42l43-l3-cs35l56-l01-spkagg.tplg \
firmware-intel/sof-ace-tplg/sof-mtl-dmic-2ch-id2.tplg \
firmware-intel/sof-ace-tplg/sof-mtl-dmic-2ch-id3.tplg \
firmware-intel/sof-ace-tplg/sof-mtl-dmic-2ch-id4.tplg \
firmware-intel/sof-ace-tplg/sof-mtl-dmic-2ch-id5.tplg \
firmware-intel/sof-ace-tplg/sof-mtl-dmic-4ch-id2.tplg \
firmware-intel/sof-ace-tplg/sof-mtl-dmic-4ch-id3.tplg \
firmware-intel/sof-ace-tplg/sof-mtl-dmic-4ch-id4.tplg \
firmware-intel/sof-ace-tplg/sof-mtl-dmic-4ch-id5.tplg \
firmware-intel/sof-ace-tplg/sof-mtl-es83x6-ssp1-hdmi-ssp02.tplg \
firmware-intel/sof-ace-tplg/sof-mtl-es83x6-ssp1.tplg \
firmware-intel/sof-ace-tplg/sof-mtl-hdmi-ssp02.tplg \
firmware-intel/sof-ace-tplg/sof-mtl-max98357a-rt5682-google-aec.tplg \
firmware-intel/sof-ace-tplg/sof-mtl-max98357a-rt5682-ssp2-ssp0-2ch-pdm1-google-aec.tplg \
firmware-intel/sof-ace-tplg/sof-mtl-max98357a-rt5682-ssp2-ssp0-2ch-pdm1.tplg \
firmware-intel/sof-ace-tplg/sof-mtl-max98357a-rt5682-ssp2-ssp0-google-aec.tplg \
firmware-intel/sof-ace-tplg/sof-mtl-max98357a-rt5682-ssp2-ssp0.tplg \
firmware-intel/sof-ace-tplg/sof-mtl-max98357a-rt5682.tplg \
firmware-intel/sof-ace-tplg/sof-mtl-max98360a-rt5682.tplg \
firmware-intel/sof-ace-tplg/sof-mtl-rt1019-rt5682.tplg \
firmware-intel/sof-ace-tplg/sof-mtl-rt1318-l12-rt714-l0.tplg \
firmware-intel/sof-ace-tplg/sof-mtl-rt5650-dts-google-aec.tplg \
firmware-intel/sof-ace-tplg/sof-mtl-rt5650-dts.tplg \
firmware-intel/sof-ace-tplg/sof-mtl-rt5650.tplg \
firmware-intel/sof-ace-tplg/sof-mtl-rt711-2ch.tplg \
firmware-intel/sof-ace-tplg/sof-mtl-rt711-4ch.tplg \
firmware-intel/sof-ace-tplg/sof-mtl-rt711-l0-rt1316-l23-rt714-l1.tplg \
firmware-intel/sof-ace-tplg/sof-mtl-rt711-l0-rt1316-l3-2ch.tplg \
firmware-intel/sof-ace-tplg/sof-mtl-rt711-l0-rt1316-l3-4ch.tplg \
firmware-intel/sof-ace-tplg/sof-mtl-rt711-l0-rt1316-l3.tplg \
firmware-intel/sof-ace-tplg/sof-mtl-rt712-l0-2ch.tplg \
firmware-intel/sof-ace-tplg/sof-mtl-rt712-l0-4ch.tplg \
firmware-intel/sof-ace-tplg/sof-mtl-rt712-l0-rt1712-l3.tplg \
firmware-intel/sof-ace-tplg/sof-mtl-rt712-l0.tplg \
firmware-intel/sof-ace-tplg/sof-mtl-rt712-vb-l0.tplg \
firmware-intel/sof-ace-tplg/sof-mtl-rt713-l0-rt1316-l12-rt1713-l3.tplg \
firmware-intel/sof-ace-tplg/sof-mtl-rt713-l0-rt1316-l12.tplg \
firmware-intel/sof-ace-tplg/sof-mtl-rt713-l0-rt1318-l1-rt1713-l3.tplg \
firmware-intel/sof-ace-tplg/sof-mtl-rt713-l0-rt1318-l12-rt1713-l3.tplg \
firmware-intel/sof-ace-tplg/sof-mtl-rt722-l0.tplg \
firmware-intel/sof-ace-tplg/sof-mtl-sdw-cs42l42-l0-max98363-l2.tplg \
firmware-intel/sof-ace-tplg/sof-ptl-cs42l43-agg-l3-cs35l56-l2-4ch.tplg \
firmware-intel/sof-ace-tplg/sof-ptl-cs42l43-agg-l3-cs35l56-l2.tplg \
firmware-intel/sof-ace-tplg/sof-ptl-cs42l43-l2-cs35l56x6-l13.tplg \
firmware-intel/sof-ace-tplg/sof-ptl-dmic-2ch-id2.tplg \
firmware-intel/sof-ace-tplg/sof-ptl-dmic-2ch-id3.tplg \
firmware-intel/sof-ace-tplg/sof-ptl-dmic-2ch-id4.tplg \
firmware-intel/sof-ace-tplg/sof-ptl-dmic-2ch-id5.tplg \
firmware-intel/sof-ace-tplg/sof-ptl-dmic-4ch-id2.tplg \
firmware-intel/sof-ace-tplg/sof-ptl-dmic-4ch-id3.tplg \
firmware-intel/sof-ace-tplg/sof-ptl-dmic-4ch-id4.tplg \
firmware-intel/sof-ace-tplg/sof-ptl-dmic-4ch-id5.tplg \
firmware-intel/sof-ace-tplg/sof-ptl-es8336-ssp1.tplg \
firmware-intel/sof-ace-tplg/sof-ptl-es83x6-ssp1-hdmi-ssp02.tplg \
firmware-intel/sof-ace-tplg/sof-ptl-hdmi-ssp02.tplg \
firmware-intel/sof-ace-tplg/sof-ptl-rt711-2ch.tplg \
firmware-intel/sof-ace-tplg/sof-ptl-rt711-4ch.tplg \
firmware-intel/sof-ace-tplg/sof-ptl-rt711-rt1308-mono-rt715.tplg \
firmware-intel/sof-ace-tplg/sof-ptl-rt711-rt1308-rt715.tplg \
firmware-intel/sof-ace-tplg/sof-ptl-rt711.tplg \
firmware-intel/sof-ace-tplg/sof-ptl-rt712-l2-rt1320-l1.tplg \
firmware-intel/sof-ace-tplg/sof-ptl-rt712-l3-rt1320-l2.tplg \
firmware-intel/sof-ace-tplg/sof-ptl-rt712-l3-rt1320-l3-4ch.tplg \
firmware-intel/sof-ace-tplg/sof-ptl-rt712-l3-rt1320-l3.tplg \
firmware-intel/sof-ace-tplg/sof-ptl-rt713-l2-rt1320-l13.tplg \
firmware-intel/sof-ace-tplg/sof-ptl-rt713-l3-rt1320-l12.tplg \
firmware-intel/sof-ace-tplg/sof-ptl-rt715-rt711-rt1308-mono.tplg \
firmware-intel/sof-ace-tplg/sof-ptl-rt721-4ch-96k.tplg \
firmware-intel/sof-ace-tplg/sof-ptl-rt721-4ch.tplg \
firmware-intel/sof-ace-tplg/sof-ptl-rt721.tplg \
firmware-intel/sof-ace-tplg/sof-ptl-rt722-192k.tplg \
firmware-intel/sof-ace-tplg/sof-ptl-rt722-2ch.tplg \
firmware-intel/sof-ace-tplg/sof-ptl-rt722-4ch.tplg \
firmware-intel/sof-ace-tplg/sof-ptl-rt722-96k.tplg \
firmware-intel/sof-ace-tplg/sof-ptl-rt722-l0-rt1320-l23-2ch.tplg \
firmware-intel/sof-ace-tplg/sof-ptl-rt722-l0-rt1320-l23-4ch.tplg \
firmware-intel/sof-ace-tplg/sof-ptl-rt722-l0-rt1320-l23.tplg \
firmware-intel/sof-ace-tplg/sof-ptl-rt722.tplg \
firmware-intel/sof-ace-tplg/sof-ptl-tas2563-rt5682.tplg \
firmware-intel/sof-ace-tplg/sof-rpl-cs42l43-l0.tplg \
firmware-intel/sof-ace-tplg/sof-sdca-1amp-id2.tplg \
firmware-intel/sof-ace-tplg/sof-sdca-2amp-id2.tplg \
firmware-intel/sof-ace-tplg/sof-sdca-3amp-id2.tplg \
firmware-intel/sof-ace-tplg/sof-sdca-4amp-id2.tplg \
firmware-intel/sof-ace-tplg/sof-sdca-jack-id0.tplg \
firmware-intel/sof-ace-tplg/sof-sdca-mic-id4.tplg \
firmware-intel/sof-ace-tplg/sof-sdw-generic.tplg \
firmware-intel/sof-ace-tplg/sof-tgl-cs35l56-l01-fb8.tplg \
firmware-intel/sof-ace-tplg/sof-tgl-cs42l43-l3-cs35l56-l01.tplg \
firmware-intel/sof-ace-tplg/sof-tgl-rt711-rt1308-4ch.tplg \
firmware-intel/sof-ace-tplg/sof-tgl-rt711-rt1308-rt715.tplg \
firmware-intel/sof-ace-tplg/sof-tgl-rt711-rt1316-rt714.tplg \
firmware-intel/sof-ace-tplg/sof-tgl-rt712.tplg \
firmware-intel/sof-ace-tplg/sof-tgl-rt715-rt711-rt1308-mono.tplg \
firmware-intel/sof-ace-tplg/sof-wcl-dmic-2ch-id2.tplg \
firmware-intel/sof-ace-tplg/sof-wcl-dmic-2ch-id3.tplg \
firmware-intel/sof-ace-tplg/sof-wcl-dmic-2ch-id4.tplg \
firmware-intel/sof-ace-tplg/sof-wcl-dmic-2ch-id5.tplg \
firmware-intel/sof-ace-tplg/sof-wcl-dmic-4ch-id2.tplg \
firmware-intel/sof-ace-tplg/sof-wcl-dmic-4ch-id3.tplg \
firmware-intel/sof-ace-tplg/sof-wcl-dmic-4ch-id4.tplg \
firmware-intel/sof-ace-tplg/sof-wcl-dmic-4ch-id5.tplg \
firmware-intel/sof-ipc4-lib/lnl/B36EE4DA-006F-47F9-A06D-FECBE2D8B6CE.bin \
firmware-intel/sof-ipc4-lib/lnl/community/B36EE4DA-006F-47F9-A06D-FECBE2D8B6CE.bin \
firmware-intel/sof-ipc4-lib/lnl/community/drc.llext \
firmware-intel/sof-ipc4-lib/lnl/intel-signed/B36EE4DA-006F-47F9-A06D-FECBE2D8B6CE.bin \
firmware-intel/sof-ipc4-lib/lnl/intel-signed/drc.llext \
firmware-intel/sof-ipc4-tplg/sof-adl-cs42l43-l0-cs35l56-l23.tplg \
firmware-intel/sof-ipc4-tplg/sof-adl-rt711-4ch.tplg \
firmware-intel/sof-ipc4-tplg/sof-adl-rt711-l0-rt1308-l12-rt715-l3.tplg \
firmware-intel/sof-ipc4-tplg/sof-adl-rt711-l0-rt1316-l12-rt714-l3.tplg \
firmware-intel/sof-ipc4-tplg/sof-adl-rt711-l0-rt1316-l13-rt714-l2.tplg \
firmware-intel/sof-ipc4-tplg/sof-arl-cs42l43-l0-cs35l56-l2-2ch.tplg \
firmware-intel/sof-ipc4-tplg/sof-arl-cs42l43-l0-cs35l56-l2.tplg \
firmware-intel/sof-ipc4-tplg/sof-arl-cs42l43-l0-cs35l56-l23.tplg \
firmware-intel/sof-ipc4-tplg/sof-arl-cs42l43-l0.tplg \
firmware-intel/sof-ipc4-tplg/sof-arl-cs42l43-l2-cs35l56-l3-2ch.tplg \
firmware-intel/sof-ipc4-tplg/sof-arl-cs42l43-l2-cs35l56-l3.tplg \
firmware-intel/sof-ipc4-tplg/sof-arl-cs42l43-l2.tplg \
firmware-intel/sof-ipc4-tplg/sof-arl-dmic-2ch-id2.tplg \
firmware-intel/sof-ipc4-tplg/sof-arl-dmic-2ch-id3.tplg \
firmware-intel/sof-ipc4-tplg/sof-arl-dmic-2ch-id4.tplg \
firmware-intel/sof-ipc4-tplg/sof-arl-dmic-2ch-id5.tplg \
firmware-intel/sof-ipc4-tplg/sof-arl-dmic-4ch-id2.tplg \
firmware-intel/sof-ipc4-tplg/sof-arl-dmic-4ch-id3.tplg \
firmware-intel/sof-ipc4-tplg/sof-arl-dmic-4ch-id4.tplg \
firmware-intel/sof-ipc4-tplg/sof-arl-dmic-4ch-id5.tplg \
firmware-intel/sof-ipc4-tplg/sof-arl-rt711-l0-2ch.tplg \
firmware-intel/sof-ipc4-tplg/sof-arl-rt711-l0-4ch.tplg \
firmware-intel/sof-ipc4-tplg/sof-arl-rt711-l0-rt1316-l3-2ch.tplg \
firmware-intel/sof-ipc4-tplg/sof-arl-rt711-l0-rt1316-l3-4ch.tplg \
firmware-intel/sof-ipc4-tplg/sof-arl-rt711-l0-rt1316-l3.tplg \
firmware-intel/sof-ipc4-tplg/sof-arl-rt711-l0.tplg \
firmware-intel/sof-ipc4-tplg/sof-arl-rt722-l0-rt1320-l2.tplg \
firmware-intel/sof-ipc4-tplg/sof-hda-generic-1ch.tplg \
firmware-intel/sof-ipc4-tplg/sof-hda-generic-2ch.tplg \
firmware-intel/sof-ipc4-tplg/sof-hda-generic-4ch.tplg \
firmware-intel/sof-ipc4-tplg/sof-hda-generic-ace1-1ch.tplg \
firmware-intel/sof-ipc4-tplg/sof-hda-generic-ace1-2ch.tplg \
firmware-intel/sof-ipc4-tplg/sof-hda-generic-ace1-4ch.tplg \
firmware-intel/sof-ipc4-tplg/sof-hda-generic-ace1-idisp-2ch.tplg \
firmware-intel/sof-ipc4-tplg/sof-hda-generic-ace1-idisp-4ch.tplg \
firmware-intel/sof-ipc4-tplg/sof-hda-generic-ace3-1ch.tplg \
firmware-intel/sof-ipc4-tplg/sof-hda-generic-ace3-2ch.tplg \
firmware-intel/sof-ipc4-tplg/sof-hda-generic-ace3-4ch.tplg \
firmware-intel/sof-ipc4-tplg/sof-hda-generic-ace3-idisp-2ch.tplg \
firmware-intel/sof-ipc4-tplg/sof-hda-generic-ace3-idisp-4ch.tplg \
firmware-intel/sof-ipc4-tplg/sof-hda-generic-cavs25-1ch.tplg \
firmware-intel/sof-ipc4-tplg/sof-hda-generic-cavs25-2ch.tplg \
firmware-intel/sof-ipc4-tplg/sof-hda-generic-cavs25-4ch.tplg \
firmware-intel/sof-ipc4-tplg/sof-hda-generic-cavs25-idisp-2ch.tplg \
firmware-intel/sof-ipc4-tplg/sof-hda-generic-cavs25-idisp-4ch.tplg \
firmware-intel/sof-ipc4-tplg/sof-hda-generic-idisp-2ch.tplg \
firmware-intel/sof-ipc4-tplg/sof-hda-generic-idisp-4ch.tplg \
firmware-intel/sof-ipc4-tplg/sof-hda-generic-idisp.tplg \
firmware-intel/sof-ipc4-tplg/sof-hda-generic.tplg \
firmware-intel/sof-ipc4-tplg/sof-hdmi-pcm5-id2.tplg \
firmware-intel/sof-ipc4-tplg/sof-hdmi-pcm5-id3.tplg \
firmware-intel/sof-ipc4-tplg/sof-hdmi-pcm5-id4.tplg \
firmware-intel/sof-ipc4-tplg/sof-hdmi-pcm5-id5.tplg \
firmware-intel/sof-ipc4-tplg/sof-hdmi-pcm5-id6.tplg \
firmware-intel/sof-ipc4-tplg/sof-hdmi-pcm5-id7.tplg \
firmware-intel/sof-ipc4-tplg/sof-lnl-cs42l43-l0-2ch.tplg \
firmware-intel/sof-ipc4-tplg/sof-lnl-cs42l43-l0-4ch.tplg \
firmware-intel/sof-ipc4-tplg/sof-lnl-cs42l43-l0-cs35l56-l23-2ch.tplg \
firmware-intel/sof-ipc4-tplg/sof-lnl-cs42l43-l0-cs35l56-l23-4ch.tplg \
firmware-intel/sof-ipc4-tplg/sof-lnl-cs42l43-l0-cs35l56-l23.tplg \
firmware-intel/sof-ipc4-tplg/sof-lnl-cs42l43-l0-cs35l56-l3-2ch.tplg \
firmware-intel/sof-ipc4-tplg/sof-lnl-cs42l43-l0-cs35l56-l3.tplg \
firmware-intel/sof-ipc4-tplg/sof-lnl-cs42l43-l0.tplg \
firmware-intel/sof-ipc4-tplg/sof-lnl-cs42l43-l2-cs35l56x6-l13.tplg \
firmware-intel/sof-ipc4-tplg/sof-lnl-dmic-2ch-id2.tplg \
firmware-intel/sof-ipc4-tplg/sof-lnl-dmic-2ch-id3.tplg \
firmware-intel/sof-ipc4-tplg/sof-lnl-dmic-2ch-id4.tplg \
firmware-intel/sof-ipc4-tplg/sof-lnl-dmic-2ch-id5.tplg \
firmware-intel/sof-ipc4-tplg/sof-lnl-dmic-4ch-id2.tplg \
firmware-intel/sof-ipc4-tplg/sof-lnl-dmic-4ch-id3.tplg \
firmware-intel/sof-ipc4-tplg/sof-lnl-dmic-4ch-id4.tplg \
firmware-intel/sof-ipc4-tplg/sof-lnl-dmic-4ch-id5.tplg \
firmware-intel/sof-ipc4-tplg/sof-lnl-rt1318-l12-rt714-l0.tplg \
firmware-intel/sof-ipc4-tplg/sof-lnl-rt1320-l12-rt714-l0.tplg \
firmware-intel/sof-ipc4-tplg/sof-lnl-rt711-4ch.tplg \
firmware-intel/sof-ipc4-tplg/sof-lnl-rt711-l0-rt1316-l23-rt714-l1.tplg \
firmware-intel/sof-ipc4-tplg/sof-lnl-rt712-l2-rt1320-l1.tplg \
firmware-intel/sof-ipc4-tplg/sof-lnl-rt712-l2-rt1712-l3.tplg \
firmware-intel/sof-ipc4-tplg/sof-lnl-rt713-l0-rt1318-l1-2ch.tplg \
firmware-intel/sof-ipc4-tplg/sof-lnl-rt713-l0-rt1318-l1.tplg \
firmware-intel/sof-ipc4-tplg/sof-lnl-rt713-l2-rt1320-l13.tplg \
firmware-intel/sof-ipc4-tplg/sof-lnl-rt722-l0.tplg \
firmware-intel/sof-ipc4-tplg/sof-mtl-cs35l56-l01-fb6.tplg \
firmware-intel/sof-ipc4-tplg/sof-mtl-cs35l56-l01-fb8.tplg \
firmware-intel/sof-ipc4-tplg/sof-mtl-cs42l43-l0-cs35l56-l12.tplg \
firmware-intel/sof-ipc4-tplg/sof-mtl-cs42l43-l0-cs35l56-l23.tplg \
firmware-intel/sof-ipc4-tplg/sof-mtl-cs42l43-l0.tplg \
firmware-intel/sof-ipc4-tplg/sof-mtl-cs42l43-l3-cs35l56-l01-spkagg.tplg \
firmware-intel/sof-ipc4-tplg/sof-mtl-dmic-2ch-id2.tplg \
firmware-intel/sof-ipc4-tplg/sof-mtl-dmic-2ch-id3.tplg \
firmware-intel/sof-ipc4-tplg/sof-mtl-dmic-2ch-id4.tplg \
firmware-intel/sof-ipc4-tplg/sof-mtl-dmic-2ch-id5.tplg \
firmware-intel/sof-ipc4-tplg/sof-mtl-dmic-4ch-id2.tplg \
firmware-intel/sof-ipc4-tplg/sof-mtl-dmic-4ch-id3.tplg \
firmware-intel/sof-ipc4-tplg/sof-mtl-dmic-4ch-id4.tplg \
firmware-intel/sof-ipc4-tplg/sof-mtl-dmic-4ch-id5.tplg \
firmware-intel/sof-ipc4-tplg/sof-mtl-es83x6-ssp1-hdmi-ssp02.tplg \
firmware-intel/sof-ipc4-tplg/sof-mtl-es83x6-ssp1.tplg \
firmware-intel/sof-ipc4-tplg/sof-mtl-hdmi-ssp02.tplg \
firmware-intel/sof-ipc4-tplg/sof-mtl-max98357a-rt5682-google-aec.tplg \
firmware-intel/sof-ipc4-tplg/sof-mtl-max98357a-rt5682-ssp2-ssp0-2ch-pdm1-google-aec.tplg \
firmware-intel/sof-ipc4-tplg/sof-mtl-max98357a-rt5682-ssp2-ssp0-2ch-pdm1.tplg \
firmware-intel/sof-ipc4-tplg/sof-mtl-max98357a-rt5682-ssp2-ssp0-google-aec.tplg \
firmware-intel/sof-ipc4-tplg/sof-mtl-max98357a-rt5682-ssp2-ssp0.tplg \
firmware-intel/sof-ipc4-tplg/sof-mtl-max98357a-rt5682.tplg \
firmware-intel/sof-ipc4-tplg/sof-mtl-max98360a-rt5682.tplg \
firmware-intel/sof-ipc4-tplg/sof-mtl-rt1019-rt5682.tplg \
firmware-intel/sof-ipc4-tplg/sof-mtl-rt1318-l12-rt714-l0.tplg \
firmware-intel/sof-ipc4-tplg/sof-mtl-rt5650-dts-google-aec.tplg \
firmware-intel/sof-ipc4-tplg/sof-mtl-rt5650-dts.tplg \
firmware-intel/sof-ipc4-tplg/sof-mtl-rt5650.tplg \
firmware-intel/sof-ipc4-tplg/sof-mtl-rt711-2ch.tplg \
firmware-intel/sof-ipc4-tplg/sof-mtl-rt711-4ch.tplg \
firmware-intel/sof-ipc4-tplg/sof-mtl-rt711-l0-rt1316-l23-rt714-l1.tplg \
firmware-intel/sof-ipc4-tplg/sof-mtl-rt711-l0-rt1316-l3-2ch.tplg \
firmware-intel/sof-ipc4-tplg/sof-mtl-rt711-l0-rt1316-l3-4ch.tplg \
firmware-intel/sof-ipc4-tplg/sof-mtl-rt711-l0-rt1316-l3.tplg \
firmware-intel/sof-ipc4-tplg/sof-mtl-rt712-l0-2ch.tplg \
firmware-intel/sof-ipc4-tplg/sof-mtl-rt712-l0-4ch.tplg \
firmware-intel/sof-ipc4-tplg/sof-mtl-rt712-l0-rt1712-l3.tplg \
firmware-intel/sof-ipc4-tplg/sof-mtl-rt712-l0.tplg \
firmware-intel/sof-ipc4-tplg/sof-mtl-rt712-vb-l0.tplg \
firmware-intel/sof-ipc4-tplg/sof-mtl-rt713-l0-rt1316-l12-rt1713-l3.tplg \
firmware-intel/sof-ipc4-tplg/sof-mtl-rt713-l0-rt1316-l12.tplg \
firmware-intel/sof-ipc4-tplg/sof-mtl-rt713-l0-rt1318-l1-rt1713-l3.tplg \
firmware-intel/sof-ipc4-tplg/sof-mtl-rt713-l0-rt1318-l12-rt1713-l3.tplg \
firmware-intel/sof-ipc4-tplg/sof-mtl-rt722-l0.tplg \
firmware-intel/sof-ipc4-tplg/sof-mtl-sdw-cs42l42-l0-max98363-l2.tplg \
firmware-intel/sof-ipc4-tplg/sof-ptl-cs42l43-agg-l3-cs35l56-l2-4ch.tplg \
firmware-intel/sof-ipc4-tplg/sof-ptl-cs42l43-agg-l3-cs35l56-l2.tplg \
firmware-intel/sof-ipc4-tplg/sof-ptl-cs42l43-l2-cs35l56x6-l13.tplg \
firmware-intel/sof-ipc4-tplg/sof-ptl-dmic-2ch-id2.tplg \
firmware-intel/sof-ipc4-tplg/sof-ptl-dmic-2ch-id3.tplg \
firmware-intel/sof-ipc4-tplg/sof-ptl-dmic-2ch-id4.tplg \
firmware-intel/sof-ipc4-tplg/sof-ptl-dmic-2ch-id5.tplg \
firmware-intel/sof-ipc4-tplg/sof-ptl-dmic-4ch-id2.tplg \
firmware-intel/sof-ipc4-tplg/sof-ptl-dmic-4ch-id3.tplg \
firmware-intel/sof-ipc4-tplg/sof-ptl-dmic-4ch-id4.tplg \
firmware-intel/sof-ipc4-tplg/sof-ptl-dmic-4ch-id5.tplg \
firmware-intel/sof-ipc4-tplg/sof-ptl-es8336-ssp1.tplg \
firmware-intel/sof-ipc4-tplg/sof-ptl-es83x6-ssp1-hdmi-ssp02.tplg \
firmware-intel/sof-ipc4-tplg/sof-ptl-hdmi-ssp02.tplg \
firmware-intel/sof-ipc4-tplg/sof-ptl-rt711-2ch.tplg \
firmware-intel/sof-ipc4-tplg/sof-ptl-rt711-4ch.tplg \
firmware-intel/sof-ipc4-tplg/sof-ptl-rt711-rt1308-mono-rt715.tplg \
firmware-intel/sof-ipc4-tplg/sof-ptl-rt711-rt1308-rt715.tplg \
firmware-intel/sof-ipc4-tplg/sof-ptl-rt711.tplg \
firmware-intel/sof-ipc4-tplg/sof-ptl-rt712-l2-rt1320-l1.tplg \
firmware-intel/sof-ipc4-tplg/sof-ptl-rt712-l3-rt1320-l2.tplg \
firmware-intel/sof-ipc4-tplg/sof-ptl-rt712-l3-rt1320-l3-4ch.tplg \
firmware-intel/sof-ipc4-tplg/sof-ptl-rt712-l3-rt1320-l3.tplg \
firmware-intel/sof-ipc4-tplg/sof-ptl-rt713-l2-rt1320-l13.tplg \
firmware-intel/sof-ipc4-tplg/sof-ptl-rt713-l3-rt1320-l12.tplg \
firmware-intel/sof-ipc4-tplg/sof-ptl-rt715-rt711-rt1308-mono.tplg \
firmware-intel/sof-ipc4-tplg/sof-ptl-rt721-4ch-96k.tplg \
firmware-intel/sof-ipc4-tplg/sof-ptl-rt721-4ch.tplg \
firmware-intel/sof-ipc4-tplg/sof-ptl-rt721.tplg \
firmware-intel/sof-ipc4-tplg/sof-ptl-rt722-192k.tplg \
firmware-intel/sof-ipc4-tplg/sof-ptl-rt722-2ch.tplg \
firmware-intel/sof-ipc4-tplg/sof-ptl-rt722-4ch.tplg \
firmware-intel/sof-ipc4-tplg/sof-ptl-rt722-96k.tplg \
firmware-intel/sof-ipc4-tplg/sof-ptl-rt722-l0-rt1320-l23-2ch.tplg \
firmware-intel/sof-ipc4-tplg/sof-ptl-rt722-l0-rt1320-l23-4ch.tplg \
firmware-intel/sof-ipc4-tplg/sof-ptl-rt722-l0-rt1320-l23.tplg \
firmware-intel/sof-ipc4-tplg/sof-ptl-rt722.tplg \
firmware-intel/sof-ipc4-tplg/sof-ptl-tas2563-rt5682.tplg \
firmware-intel/sof-ipc4-tplg/sof-rpl-cs42l43-l0.tplg \
firmware-intel/sof-ipc4-tplg/sof-sdca-1amp-id2.tplg \
firmware-intel/sof-ipc4-tplg/sof-sdca-2amp-id2.tplg \
firmware-intel/sof-ipc4-tplg/sof-sdca-3amp-id2.tplg \
firmware-intel/sof-ipc4-tplg/sof-sdca-4amp-id2.tplg \
firmware-intel/sof-ipc4-tplg/sof-sdca-jack-id0.tplg \
firmware-intel/sof-ipc4-tplg/sof-sdca-mic-id4.tplg \
firmware-intel/sof-ipc4-tplg/sof-sdw-generic.tplg \
firmware-intel/sof-ipc4-tplg/sof-tgl-cs35l56-l01-fb8.tplg \
firmware-intel/sof-ipc4-tplg/sof-tgl-cs42l43-l3-cs35l56-l01.tplg \
firmware-intel/sof-ipc4-tplg/sof-tgl-rt711-rt1308-4ch.tplg \
firmware-intel/sof-ipc4-tplg/sof-tgl-rt711-rt1308-rt715.tplg \
firmware-intel/sof-ipc4-tplg/sof-tgl-rt711-rt1316-rt714.tplg \
firmware-intel/sof-ipc4-tplg/sof-tgl-rt712.tplg \
firmware-intel/sof-ipc4-tplg/sof-tgl-rt715-rt711-rt1308-mono.tplg \
firmware-intel/sof-ipc4-tplg/sof-wcl-dmic-2ch-id2.tplg \
firmware-intel/sof-ipc4-tplg/sof-wcl-dmic-2ch-id3.tplg \
firmware-intel/sof-ipc4-tplg/sof-wcl-dmic-2ch-id4.tplg \
firmware-intel/sof-ipc4-tplg/sof-wcl-dmic-2ch-id5.tplg \
firmware-intel/sof-ipc4-tplg/sof-wcl-dmic-4ch-id2.tplg \
firmware-intel/sof-ipc4-tplg/sof-wcl-dmic-4ch-id3.tplg \
firmware-intel/sof-ipc4-tplg/sof-wcl-dmic-4ch-id4.tplg \
firmware-intel/sof-ipc4-tplg/sof-wcl-dmic-4ch-id5.tplg \
firmware-intel/sof-ipc4/adl-n/community/sof-adl-n.ri \
firmware-intel/sof-ipc4/adl-n/intel-signed/sof-adl-n.ri \
firmware-intel/sof-ipc4/adl-n/sof-adl-n.ri \
firmware-intel/sof-ipc4/adl-s/community/sof-adl-s.ri \
firmware-intel/sof-ipc4/adl-s/intel-signed/sof-adl-s.ri \
firmware-intel/sof-ipc4/adl-s/sof-adl-s.ri \
firmware-intel/sof-ipc4/adl/community/sof-adl.ri \
firmware-intel/sof-ipc4/adl/intel-signed/sof-adl.ri \
firmware-intel/sof-ipc4/adl/sof-adl.ri \
firmware-intel/sof-ipc4/arl-s/community/sof-arl-s.ri \
firmware-intel/sof-ipc4/arl-s/intel-signed/sof-arl-s.ri \
firmware-intel/sof-ipc4/arl-s/sof-arl-s.ri \
firmware-intel/sof-ipc4/arl/community/sof-arl.ri \
firmware-intel/sof-ipc4/arl/intel-signed/sof-arl.ri \
firmware-intel/sof-ipc4/arl/sof-arl.ri \
firmware-intel/sof-ipc4/ehl/community/sof-ehl.ri \
firmware-intel/sof-ipc4/lnl/community/sof-lnl.ri \
firmware-intel/sof-ipc4/lnl/intel-signed/sof-lnl.ri \
firmware-intel/sof-ipc4/lnl/sof-lnl.ri \
firmware-intel/sof-ipc4/mtl/community/sof-mtl.ri \
firmware-intel/sof-ipc4/mtl/intel-signed/sof-mtl.ri \
firmware-intel/sof-ipc4/mtl/sof-mtl.ri \
firmware-intel/sof-ipc4/ptl/community/sof-ptl-openmodules.ri \
firmware-intel/sof-ipc4/ptl/community/sof-ptl.ri \
firmware-intel/sof-ipc4/ptl/intel-signed/sof-ptl-openmodules.ri \
firmware-intel/sof-ipc4/ptl/intel-signed/sof-ptl.ri \
firmware-intel/sof-ipc4/ptl/sof-ptl-openmodules.ri \
firmware-intel/sof-ipc4/ptl/sof-ptl.ri \
firmware-intel/sof-ipc4/rpl-s/community/sof-rpl-s.ri \
firmware-intel/sof-ipc4/rpl-s/intel-signed/sof-rpl-s.ri \
firmware-intel/sof-ipc4/rpl-s/sof-rpl-s.ri \
firmware-intel/sof-ipc4/rpl/community/sof-rpl.ri \
firmware-intel/sof-ipc4/rpl/intel-signed/sof-rpl.ri \
firmware-intel/sof-ipc4/rpl/sof-rpl.ri \
firmware-intel/sof-ipc4/tgl-h/community/sof-tgl-h.ri \
firmware-intel/sof-ipc4/tgl-h/intel-signed/sof-tgl-h.ri \
firmware-intel/sof-ipc4/tgl-h/sof-tgl-h.ri \
firmware-intel/sof-ipc4/tgl/community/sof-tgl.ri \
firmware-intel/sof-ipc4/tgl/intel-signed/sof-tgl.ri \
firmware-intel/sof-ipc4/tgl/sof-tgl.ri \
firmware-intel/sof-ipc4/wcl/community/sof-wcl-openmodules.ri \
firmware-intel/sof-ipc4/wcl/community/sof-wcl.ri \
firmware-intel/sof-ipc4/wcl/intel-signed/sof-wcl-openmodules.ri \
firmware-intel/sof-ipc4/wcl/intel-signed/sof-wcl.ri \
firmware-intel/sof-ipc4/wcl/sof-wcl-openmodules.ri \
firmware-intel/sof-ipc4/wcl/sof-wcl.ri \
firmware-intel/sof-tplg/sof-acp.tplg \
firmware-intel/sof-tplg/sof-adl-cs35l41.tplg \
firmware-intel/sof-tplg/sof-adl-es8336-dmic2ch-ssp0.tplg \
firmware-intel/sof-tplg/sof-adl-es8336-dmic2ch-ssp1.tplg \
firmware-intel/sof-tplg/sof-adl-es8336-dmic2ch-ssp2.tplg \
firmware-intel/sof-tplg/sof-adl-es8336-dmic4ch-ssp0.tplg \
firmware-intel/sof-tplg/sof-adl-es8336-dmic4ch-ssp1.tplg \
firmware-intel/sof-tplg/sof-adl-es8336-dmic4ch-ssp2.tplg \
firmware-intel/sof-tplg/sof-adl-es8336-ssp0.tplg \
firmware-intel/sof-tplg/sof-adl-es8336-ssp1-hdmi-ssp02-4ch.tplg \
firmware-intel/sof-tplg/sof-adl-es8336-ssp1-hdmi-ssp02.tplg \
firmware-intel/sof-tplg/sof-adl-es8336-ssp1.tplg \
firmware-intel/sof-tplg/sof-adl-es8336-ssp2.tplg \
firmware-intel/sof-tplg/sof-adl-es8336.tplg \
firmware-intel/sof-tplg/sof-adl-max98357a-rt5682-2way.tplg \
firmware-intel/sof-tplg/sof-adl-max98357a-rt5682-4ch.tplg \
firmware-intel/sof-tplg/sof-adl-max98357a-rt5682-rtnr.tplg \
firmware-intel/sof-tplg/sof-adl-max98357a-rt5682-waves-2way.tplg \
firmware-intel/sof-tplg/sof-adl-max98357a-rt5682-waves.tplg \
firmware-intel/sof-tplg/sof-adl-max98357a-rt5682.tplg \
firmware-intel/sof-tplg/sof-adl-max98360a-da7219.tplg \
firmware-intel/sof-tplg/sof-adl-max98360a-nau8825.tplg \
firmware-intel/sof-tplg/sof-adl-max98360a-rt5682-2way.tplg \
firmware-intel/sof-tplg/sof-adl-max98360a-rt5682-4ch.tplg \
firmware-intel/sof-tplg/sof-adl-max98360a-rt5682-rtnr.tplg \
firmware-intel/sof-tplg/sof-adl-max98360a-rt5682-waves.tplg \
firmware-intel/sof-tplg/sof-adl-max98360a-rt5682.tplg \
firmware-intel/sof-tplg/sof-adl-max98373-nau8825-dts.tplg \
firmware-intel/sof-tplg/sof-adl-max98373-nau8825.tplg \
firmware-intel/sof-tplg/sof-adl-max98390-rt5682-google-aec.tplg \
firmware-intel/sof-tplg/sof-adl-max98390-rt5682-rtnr.tplg \
firmware-intel/sof-tplg/sof-adl-max98390-rt5682.tplg \
firmware-intel/sof-tplg/sof-adl-max98390-ssp2-rt5682-ssp0.tplg \
firmware-intel/sof-tplg/sof-adl-nau8318-nau8825.tplg \
firmware-intel/sof-tplg/sof-adl-nau8825.tplg \
firmware-intel/sof-tplg/sof-adl-nocodec-ci.tplg \
firmware-intel/sof-tplg/sof-adl-nocodec-hdmi-ssp02.tplg \
firmware-intel/sof-tplg/sof-adl-nocodec.tplg \
firmware-intel/sof-tplg/sof-adl-rt1015-nau8825.tplg \
firmware-intel/sof-tplg/sof-adl-rt1019-nau8825.tplg \
firmware-intel/sof-tplg/sof-adl-rt1019-rt5682.tplg \
firmware-intel/sof-tplg/sof-adl-rt1316-l02-4ch.tplg \
firmware-intel/sof-tplg/sof-adl-rt1316-l1-mono-rt714-l0.tplg \
firmware-intel/sof-tplg/sof-adl-rt1316-l12-rt714-l0.tplg \
firmware-intel/sof-tplg/sof-adl-rt1316-l2-mono-rt714-l0.tplg \
firmware-intel/sof-tplg/sof-adl-rt1316-l2-mono-rt714-l3.tplg \
firmware-intel/sof-tplg/sof-adl-rt5650.tplg \
firmware-intel/sof-tplg/sof-adl-rt5682.tplg \
firmware-intel/sof-tplg/sof-adl-rt711-4ch.tplg \
firmware-intel/sof-tplg/sof-adl-rt711-l0-rt1308-l12-rt715-l3.tplg \
firmware-intel/sof-tplg/sof-adl-rt711-l0-rt1316-l12-rt714-l3.tplg \
firmware-intel/sof-tplg/sof-adl-rt711-l0-rt1316-l13-rt714-l2.tplg \
firmware-intel/sof-tplg/sof-adl-rt711-l0-rt1316-l2-2ch.tplg \
firmware-intel/sof-tplg/sof-adl-rt711-l0-rt1316-l2-4ch.tplg \
firmware-intel/sof-tplg/sof-adl-rt711-l0-rt1316-l3-2ch.tplg \
firmware-intel/sof-tplg/sof-adl-rt711-l2-rt1316-l01-rt714-l3.tplg \
firmware-intel/sof-tplg/sof-adl-rt711-l2-rt1316-l01.tplg \
firmware-intel/sof-tplg/sof-adl-rt711.tplg \
firmware-intel/sof-tplg/sof-adl-sdw-cs42l42-4ch.tplg \
firmware-intel/sof-tplg/sof-adl-sdw-max98373-rt5682.tplg \
firmware-intel/sof-tplg/sof-apl-da7219.tplg \
firmware-intel/sof-tplg/sof-apl-demux-pcm512x.tplg \
firmware-intel/sof-tplg/sof-apl-es8336-dmic2ch-ssp0.tplg \
firmware-intel/sof-tplg/sof-apl-es8336-dmic2ch-ssp1.tplg \
firmware-intel/sof-tplg/sof-apl-es8336-dmic2ch-ssp2.tplg \
firmware-intel/sof-tplg/sof-apl-es8336-dmic2ch-ssp5.tplg \
firmware-intel/sof-tplg/sof-apl-es8336-dmic4ch-ssp0.tplg \
firmware-intel/sof-tplg/sof-apl-es8336-dmic4ch-ssp1.tplg \
firmware-intel/sof-tplg/sof-apl-es8336-dmic4ch-ssp2.tplg \
firmware-intel/sof-tplg/sof-apl-es8336-dmic4ch-ssp5.tplg \
firmware-intel/sof-tplg/sof-apl-es8336-ssp0.tplg \
firmware-intel/sof-tplg/sof-apl-es8336-ssp1.tplg \
firmware-intel/sof-tplg/sof-apl-es8336-ssp2.tplg \
firmware-intel/sof-tplg/sof-apl-es8336-ssp5.tplg \
firmware-intel/sof-tplg/sof-apl-es8336.tplg \
firmware-intel/sof-tplg/sof-apl-keyword-detect.tplg \
firmware-intel/sof-tplg/sof-apl-nocodec-ci.tplg \
firmware-intel/sof-tplg/sof-apl-nocodec.tplg \
firmware-intel/sof-tplg/sof-apl-pcm512x-master-44100.tplg \
firmware-intel/sof-tplg/sof-apl-pcm512x-master.tplg \
firmware-intel/sof-tplg/sof-apl-pcm512x.tplg \
firmware-intel/sof-tplg/sof-apl-rt298.tplg \
firmware-intel/sof-tplg/sof-apl-tdf8532.tplg \
firmware-intel/sof-tplg/sof-apl-wm8804.tplg \
firmware-intel/sof-tplg/sof-bdw-nocodec.tplg \
firmware-intel/sof-tplg/sof-bdw-rt286.tplg \
firmware-intel/sof-tplg/sof-bdw-rt5640.tplg \
firmware-intel/sof-tplg/sof-bdw-rt5677.tplg \
firmware-intel/sof-tplg/sof-byt-cx2072x-ssp0.tplg \
firmware-intel/sof-tplg/sof-byt-cx2072x.tplg \
firmware-intel/sof-tplg/sof-byt-da7213-ssp0.tplg \
firmware-intel/sof-tplg/sof-byt-da7213.tplg \
firmware-intel/sof-tplg/sof-byt-es8316-ssp0.tplg \
firmware-intel/sof-tplg/sof-byt-es8316.tplg \
firmware-intel/sof-tplg/sof-byt-max98090.tplg \
firmware-intel/sof-tplg/sof-byt-nocodec.tplg \
firmware-intel/sof-tplg/sof-byt-rt5640-ssp0.tplg \
firmware-intel/sof-tplg/sof-byt-rt5640.tplg \
firmware-intel/sof-tplg/sof-byt-rt5645-ssp0.tplg \
firmware-intel/sof-tplg/sof-byt-rt5645.tplg \
firmware-intel/sof-tplg/sof-byt-rt5651-ssp0.tplg \
firmware-intel/sof-tplg/sof-byt-rt5651.tplg \
firmware-intel/sof-tplg/sof-byt-rt5670-ssp0.tplg \
firmware-intel/sof-tplg/sof-byt-rt5670.tplg \
firmware-intel/sof-tplg/sof-byt-rt5682-ssp0.tplg \
firmware-intel/sof-tplg/sof-byt-rt5682.tplg \
firmware-intel/sof-tplg/sof-byt-wm5102-ssp0.tplg \
firmware-intel/sof-tplg/sof-cht-cx2072x.tplg \
firmware-intel/sof-tplg/sof-cht-da7213.tplg \
firmware-intel/sof-tplg/sof-cht-es8316.tplg \
firmware-intel/sof-tplg/sof-cht-max98090.tplg \
firmware-intel/sof-tplg/sof-cht-nau8824.tplg \
firmware-intel/sof-tplg/sof-cht-nocodec.tplg \
firmware-intel/sof-tplg/sof-cht-rt5640.tplg \
firmware-intel/sof-tplg/sof-cht-rt5645.tplg \
firmware-intel/sof-tplg/sof-cht-rt5651.tplg \
firmware-intel/sof-tplg/sof-cht-rt5670.tplg \
firmware-intel/sof-tplg/sof-cht-rt5682.tplg \
firmware-intel/sof-tplg/sof-cml-da7219-max98357a.tplg \
firmware-intel/sof-tplg/sof-cml-da7219-max98390.tplg \
firmware-intel/sof-tplg/sof-cml-demux-rt5682-max98357a.tplg \
firmware-intel/sof-tplg/sof-cml-demux-rt5682.tplg \
firmware-intel/sof-tplg/sof-cml-es8336-dmic2ch-ssp0.tplg \
firmware-intel/sof-tplg/sof-cml-es8336-dmic2ch-ssp1.tplg \
firmware-intel/sof-tplg/sof-cml-es8336-dmic2ch-ssp2.tplg \
firmware-intel/sof-tplg/sof-cml-es8336-dmic4ch-ssp0.tplg \
firmware-intel/sof-tplg/sof-cml-es8336-dmic4ch-ssp1.tplg \
firmware-intel/sof-tplg/sof-cml-es8336-dmic4ch-ssp2.tplg \
firmware-intel/sof-tplg/sof-cml-es8336-ssp0.tplg \
firmware-intel/sof-tplg/sof-cml-es8336-ssp1.tplg \
firmware-intel/sof-tplg/sof-cml-es8336-ssp2.tplg \
firmware-intel/sof-tplg/sof-cml-nocodec.tplg \
firmware-intel/sof-tplg/sof-cml-rt1011-rt5682.tplg \
firmware-intel/sof-tplg/sof-cml-rt5682-kwd.tplg \
firmware-intel/sof-tplg/sof-cml-rt5682-max98357a.tplg \
firmware-intel/sof-tplg/sof-cml-rt5682.tplg \
firmware-intel/sof-tplg/sof-cml-rt700-2ch.tplg \
firmware-intel/sof-tplg/sof-cml-rt700-4ch.tplg \
firmware-intel/sof-tplg/sof-cml-rt700.tplg \
firmware-intel/sof-tplg/sof-cml-rt711-rt1308-mono-rt715.tplg \
firmware-intel/sof-tplg/sof-cml-rt711-rt1308-rt715.tplg \
firmware-intel/sof-tplg/sof-cnl-nocodec.tplg \
firmware-intel/sof-tplg/sof-cnl-rt274.tplg \
firmware-intel/sof-tplg/sof-ehl-nocodec.tplg \
firmware-intel/sof-tplg/sof-ehl-rt5660-nohdmi.tplg \
firmware-intel/sof-tplg/sof-ehl-rt5660.tplg \
firmware-intel/sof-tplg/sof-glk-cs42l42.tplg \
firmware-intel/sof-tplg/sof-glk-da7219-kwd.tplg \
firmware-intel/sof-tplg/sof-glk-da7219.tplg \
firmware-intel/sof-tplg/sof-glk-es8336-dmic2ch-ssp0.tplg \
firmware-intel/sof-tplg/sof-glk-es8336-dmic2ch-ssp1.tplg \
firmware-intel/sof-tplg/sof-glk-es8336-dmic2ch-ssp2.tplg \
firmware-intel/sof-tplg/sof-glk-es8336-dmic2ch-ssp5.tplg \
firmware-intel/sof-tplg/sof-glk-es8336-dmic4ch-ssp0.tplg \
firmware-intel/sof-tplg/sof-glk-es8336-dmic4ch-ssp1.tplg \
firmware-intel/sof-tplg/sof-glk-es8336-dmic4ch-ssp2.tplg \
firmware-intel/sof-tplg/sof-glk-es8336-dmic4ch-ssp5.tplg \
firmware-intel/sof-tplg/sof-glk-es8336-ssp0.tplg \
firmware-intel/sof-tplg/sof-glk-es8336-ssp1.tplg \
firmware-intel/sof-tplg/sof-glk-es8336-ssp2.tplg \
firmware-intel/sof-tplg/sof-glk-es8336-ssp5.tplg \
firmware-intel/sof-tplg/sof-glk-es8336.tplg \
firmware-intel/sof-tplg/sof-glk-nocodec.tplg \
firmware-intel/sof-tplg/sof-glk-rt5682.tplg \
firmware-intel/sof-tplg/sof-hda-generic-1ch-pdm1.tplg \
firmware-intel/sof-tplg/sof-hda-generic-1ch.tplg \
firmware-intel/sof-tplg/sof-hda-generic-2ch-kwd.tplg \
firmware-intel/sof-tplg/sof-hda-generic-2ch-pdm1.tplg \
firmware-intel/sof-tplg/sof-hda-generic-2ch.tplg \
firmware-intel/sof-tplg/sof-hda-generic-3ch.tplg \
firmware-intel/sof-tplg/sof-hda-generic-4ch-bt.tplg \
firmware-intel/sof-tplg/sof-hda-generic-4ch-kwd.tplg \
firmware-intel/sof-tplg/sof-hda-generic-4ch.tplg \
firmware-intel/sof-tplg/sof-hda-generic-idisp-2ch.tplg \
firmware-intel/sof-tplg/sof-hda-generic-idisp-4ch.tplg \
firmware-intel/sof-tplg/sof-hda-generic-idisp.tplg \
firmware-intel/sof-tplg/sof-hda-generic.tplg \
firmware-intel/sof-tplg/sof-icl-dmic-4ch.tplg \
firmware-intel/sof-tplg/sof-icl-es8336-dmic2ch-ssp0.tplg \
firmware-intel/sof-tplg/sof-icl-es8336-dmic2ch-ssp1.tplg \
firmware-intel/sof-tplg/sof-icl-es8336-dmic2ch-ssp2.tplg \
firmware-intel/sof-tplg/sof-icl-es8336-dmic4ch-ssp0.tplg \
firmware-intel/sof-tplg/sof-icl-es8336-dmic4ch-ssp1.tplg \
firmware-intel/sof-tplg/sof-icl-es8336-dmic4ch-ssp2.tplg \
firmware-intel/sof-tplg/sof-icl-es8336-ssp0.tplg \
firmware-intel/sof-tplg/sof-icl-es8336-ssp1.tplg \
firmware-intel/sof-tplg/sof-icl-es8336-ssp2.tplg \
firmware-intel/sof-tplg/sof-icl-nocodec.tplg \
firmware-intel/sof-tplg/sof-icl-rt5682-kwd.tplg \
firmware-intel/sof-tplg/sof-icl-rt5682.tplg \
firmware-intel/sof-tplg/sof-icl-rt700-2ch.tplg \
firmware-intel/sof-tplg/sof-icl-rt700-4ch.tplg \
firmware-intel/sof-tplg/sof-icl-rt700.tplg \
firmware-intel/sof-tplg/sof-icl-rt711-rt1308-rt715.tplg \
firmware-intel/sof-tplg/sof-imx8-compr-wm8960-mixer.tplg \
firmware-intel/sof-tplg/sof-imx8-cs42888-mixer.tplg \
firmware-intel/sof-tplg/sof-imx8-cs42888.tplg \
firmware-intel/sof-tplg/sof-imx8-drc-wm8960.tplg \
firmware-intel/sof-tplg/sof-imx8-eq-fir-wm8960.tplg \
firmware-intel/sof-tplg/sof-imx8-eq-iir-wm8960.tplg \
firmware-intel/sof-tplg/sof-imx8-nocodec-sai.tplg \
firmware-intel/sof-tplg/sof-imx8-nocodec.tplg \
firmware-intel/sof-tplg/sof-imx8-wm8960-kwd.tplg \
firmware-intel/sof-tplg/sof-imx8-wm8960-mixer.tplg \
firmware-intel/sof-tplg/sof-imx8-wm8960.tplg \
firmware-intel/sof-tplg/sof-imx8mp-compr-wm8960-mixer.tplg \
firmware-intel/sof-tplg/sof-imx8mp-drc-wm8960.tplg \
firmware-intel/sof-tplg/sof-imx8mp-eq-fir-wm8960.tplg \
firmware-intel/sof-tplg/sof-imx8mp-eq-iir-wm8960.tplg \
firmware-intel/sof-tplg/sof-imx8mp-wm8904.tplg \
firmware-intel/sof-tplg/sof-imx8mp-wm8960-kwd.tplg \
firmware-intel/sof-tplg/sof-imx8mp-wm8960-mixer.tplg \
firmware-intel/sof-tplg/sof-imx8mp-wm8960.tplg \
firmware-intel/sof-tplg/sof-imx8ulp-9x9-btsco.tplg \
firmware-intel/sof-tplg/sof-imx8ulp-btsco.tplg \
firmware-intel/sof-tplg/sof-jsl-cs42l42-mx98360a.tplg \
firmware-intel/sof-tplg/sof-jsl-da7219-mx98360a.tplg \
firmware-intel/sof-tplg/sof-jsl-da7219.tplg \
firmware-intel/sof-tplg/sof-jsl-es8336-dmic2ch-ssp0.tplg \
firmware-intel/sof-tplg/sof-jsl-es8336-dmic2ch-ssp1.tplg \
firmware-intel/sof-tplg/sof-jsl-es8336-dmic2ch-ssp2.tplg \
firmware-intel/sof-tplg/sof-jsl-es8336-dmic4ch-ssp0.tplg \
firmware-intel/sof-tplg/sof-jsl-es8336-dmic4ch-ssp1.tplg \
firmware-intel/sof-tplg/sof-jsl-es8336-dmic4ch-ssp2.tplg \
firmware-intel/sof-tplg/sof-jsl-es8336-ssp0.tplg \
firmware-intel/sof-tplg/sof-jsl-es8336-ssp1.tplg \
firmware-intel/sof-tplg/sof-jsl-es8336-ssp2.tplg \
firmware-intel/sof-tplg/sof-jsl-nocodec.tplg \
firmware-intel/sof-tplg/sof-jsl-rt5650.tplg \
firmware-intel/sof-tplg/sof-jsl-rt5682-mx98360a.tplg \
firmware-intel/sof-tplg/sof-jsl-rt5682-rt1015-xperi.tplg \
firmware-intel/sof-tplg/sof-jsl-rt5682-rt1015.tplg \
firmware-intel/sof-tplg/sof-jsl-rt5682.tplg \
firmware-intel/sof-tplg/sof-mt8186-mt6366-da7219-max98357.tplg \
firmware-intel/sof-tplg/sof-mt8186-mt6366-rt1019-rt5682s.tplg \
firmware-intel/sof-tplg/sof-mt8195-mt6359-max98390-rt5682-google-aec-rtnr.tplg \
firmware-intel/sof-tplg/sof-mt8195-mt6359-max98390-rt5682-rtnr.tplg \
firmware-intel/sof-tplg/sof-mt8195-mt6359-max98390-rt5682.tplg \
firmware-intel/sof-tplg/sof-mt8195-mt6359-rt1019-rt5682-dts.tplg \
firmware-intel/sof-tplg/sof-mt8195-mt6359-rt1019-rt5682.tplg \
firmware-intel/sof-tplg/sof-rn-rt5682-max98360.tplg \
firmware-intel/sof-tplg/sof-rn-rt5682-rt1019.tplg \
firmware-intel/sof-tplg/sof-rpl-cs42l43-l0.tplg \
firmware-intel/sof-tplg/sof-rpl-nocodec.tplg \
firmware-intel/sof-tplg/sof-rpl-rt1316-l12-rt714-l0.tplg \
firmware-intel/sof-tplg/sof-rpl-rt711-4ch.tplg \
firmware-intel/sof-tplg/sof-rpl-rt711-l0-rt1316-l12-rt714-l3.tplg \
firmware-intel/sof-tplg/sof-rpl-rt711-l0-rt1316-l12.tplg \
firmware-intel/sof-tplg/sof-rpl-rt711-l0-rt1318-l12-rt714-l3.tplg \
firmware-intel/sof-tplg/sof-rpl-rt711-l0-rt1318-l12.tplg \
firmware-intel/sof-tplg/sof-rpl-rt711-l0.tplg \
firmware-intel/sof-tplg/sof-rpl-rt711-l2-rt1316-l01-rt714-l3.tplg \
firmware-intel/sof-tplg/sof-rpl-rt711-l2-rt1316-l01.tplg \
firmware-intel/sof-tplg/sof-rpl-rt711-l2.tplg \
firmware-intel/sof-tplg/sof-rpl-rt711.tplg \
firmware-intel/sof-tplg/sof-smart-amplifier-nocodec.tplg \
firmware-intel/sof-tplg/sof-tgl-es8336-dmic2ch-ssp0.tplg \
firmware-intel/sof-tplg/sof-tgl-es8336-dmic2ch-ssp1.tplg \
firmware-intel/sof-tplg/sof-tgl-es8336-dmic2ch-ssp2.tplg \
firmware-intel/sof-tplg/sof-tgl-es8336-dmic4ch-ssp0.tplg \
firmware-intel/sof-tplg/sof-tgl-es8336-dmic4ch-ssp1.tplg \
firmware-intel/sof-tplg/sof-tgl-es8336-dmic4ch-ssp2.tplg \
firmware-intel/sof-tplg/sof-tgl-es8336-ssp0.tplg \
firmware-intel/sof-tplg/sof-tgl-es8336-ssp1.tplg \
firmware-intel/sof-tplg/sof-tgl-es8336-ssp2.tplg \
firmware-intel/sof-tplg/sof-tgl-es8336.tplg \
firmware-intel/sof-tplg/sof-tgl-h-nocodec.tplg \
firmware-intel/sof-tplg/sof-tgl-max98357a-rt5682-pdm1-drceq.tplg \
firmware-intel/sof-tplg/sof-tgl-max98357a-rt5682-pdm1-google-aec.tplg \
firmware-intel/sof-tplg/sof-tgl-max98357a-rt5682-pdm1.tplg \
firmware-intel/sof-tplg/sof-tgl-max98357a-rt5682-rtnr.tplg \
firmware-intel/sof-tplg/sof-tgl-max98357a-rt5682.tplg \
firmware-intel/sof-tplg/sof-tgl-max98373-rt5682-igonr.tplg \
firmware-intel/sof-tplg/sof-tgl-max98373-rt5682-xperi.tplg \
firmware-intel/sof-tplg/sof-tgl-max98373-rt5682.tplg \
firmware-intel/sof-tplg/sof-tgl-nocodec-ci.tplg \
firmware-intel/sof-tplg/sof-tgl-nocodec-hdmi-ssp15.tplg \
firmware-intel/sof-tplg/sof-tgl-nocodec.tplg \
firmware-intel/sof-tplg/sof-tgl-rt1011-rt5682.tplg \
firmware-intel/sof-tplg/sof-tgl-rt1308-ssp2-hdmi-ssp15.tplg \
firmware-intel/sof-tplg/sof-tgl-rt5682-ssp0-max98373-ssp2-xperi.tplg \
firmware-intel/sof-tplg/sof-tgl-rt5682-ssp0-max98373-ssp2.tplg \
firmware-intel/sof-tplg/sof-tgl-rt711-4ch.tplg \
firmware-intel/sof-tplg/sof-tgl-rt711-l0-rt1316-l1-mono-rt714-l3.tplg \
firmware-intel/sof-tplg/sof-tgl-rt711-rt1308-2ch.tplg \
firmware-intel/sof-tplg/sof-tgl-rt711-rt1308-4ch.tplg \
firmware-intel/sof-tplg/sof-tgl-rt711-rt1308-mono-rt715.tplg \
firmware-intel/sof-tplg/sof-tgl-rt711-rt1308-rt715.tplg \
firmware-intel/sof-tplg/sof-tgl-rt711-rt1316-rt714.tplg \
firmware-intel/sof-tplg/sof-tgl-rt715-rt711-rt1308-mono.tplg \
firmware-intel/sof-tplg/sof-tgl-sdw-max98373-rt5682.tplg \
firmware-intel/sof-tplg/sof-whl-demux-rt5682.tplg \
firmware-intel/sof-tplg/sof-whl-rt5682-kwd.tplg \
firmware-intel/sof-tplg/sof-whl-rt5682.tplg \
firmware-intel/sof/community/sof-adl-n.ri \
firmware-intel/sof/community/sof-adl-s.ri \
firmware-intel/sof/community/sof-adl.ri \
firmware-intel/sof/community/sof-apl.ri \
firmware-intel/sof/community/sof-cfl.ri \
firmware-intel/sof/community/sof-cml.ri \
firmware-intel/sof/community/sof-cnl.ri \
firmware-intel/sof/community/sof-ehl.ri \
firmware-intel/sof/community/sof-glk.ri \
firmware-intel/sof/community/sof-icl.ri \
firmware-intel/sof/community/sof-jsl.ri \
firmware-intel/sof/community/sof-rpl-s.ri \
firmware-intel/sof/community/sof-rpl.ri \
firmware-intel/sof/community/sof-tgl-h.ri \
firmware-intel/sof/community/sof-tgl.ri \
firmware-intel/sof/intel-signed/sof-adl-n.ri \
firmware-intel/sof/intel-signed/sof-adl-s.ri \
firmware-intel/sof/intel-signed/sof-adl.ri \
firmware-intel/sof/intel-signed/sof-apl.ri \
firmware-intel/sof/intel-signed/sof-cfl.ri \
firmware-intel/sof/intel-signed/sof-cml.ri \
firmware-intel/sof/intel-signed/sof-cnl.ri \
firmware-intel/sof/intel-signed/sof-ehl.ri \
firmware-intel/sof/intel-signed/sof-glk.ri \
firmware-intel/sof/intel-signed/sof-icl.ri \
firmware-intel/sof/intel-signed/sof-jsl.ri \
firmware-intel/sof/intel-signed/sof-rpl-s.ri \
firmware-intel/sof/intel-signed/sof-rpl.ri \
firmware-intel/sof/intel-signed/sof-tgl-h.ri \
firmware-intel/sof/intel-signed/sof-tgl.ri \
firmware-intel/sof/sof-adl-n.ldc \
firmware-intel/sof/sof-adl-n.ri \
firmware-intel/sof/sof-adl-s.ldc \
firmware-intel/sof/sof-adl-s.ri \
firmware-intel/sof/sof-adl.ldc \
firmware-intel/sof/sof-adl.ri \
firmware-intel/sof/sof-apl.ldc \
firmware-intel/sof/sof-apl.ri \
firmware-intel/sof/sof-bdw.ldc \
firmware-intel/sof/sof-bdw.ri \
firmware-intel/sof/sof-byt.ldc \
firmware-intel/sof/sof-byt.ri \
firmware-intel/sof/sof-cfl.ldc \
firmware-intel/sof/sof-cfl.ri \
firmware-intel/sof/sof-cht.ldc \
firmware-intel/sof/sof-cht.ri \
firmware-intel/sof/sof-cml.ldc \
firmware-intel/sof/sof-cml.ri \
firmware-intel/sof/sof-cnl.ldc \
firmware-intel/sof/sof-cnl.ri \
firmware-intel/sof/sof-ehl.ldc \
firmware-intel/sof/sof-ehl.ri \
firmware-intel/sof/sof-glk.ldc \
firmware-intel/sof/sof-glk.ri \
firmware-intel/sof/sof-icl.ldc \
firmware-intel/sof/sof-icl.ri \
firmware-intel/sof/sof-jsl.ldc \
firmware-intel/sof/sof-jsl.ri \
firmware-intel/sof/sof-rpl-s.ldc \
firmware-intel/sof/sof-rpl-s.ri \
firmware-intel/sof/sof-rpl.ldc \
firmware-intel/sof/sof-rpl.ri \
firmware-intel/sof/sof-tgl-h.ldc \
firmware-intel/sof/sof-tgl-h.ri \
firmware-intel/sof/sof-tgl.ldc \
firmware-intel/sof/sof-tgl.ri \
sof-firmware"

RDEPENDS:${PN} += "/usr/bin/sh \
coreutils"

inherit rpm
