SUMMARY = "Low level PipeWire control GUI"
DESCRIPTION = "coppwr is a tool that provides low level control over the PipeWire \
multimedia server."
LICENSE = "GPL-3.0-or-later"

PV = "1.7.1"

RPM_NAME = "coppwr-1.7.1-1.6.aarch64.rpm"
RPM_HASH = "c8aa0f7e9a836cdd9b9c34db920007ef5f45b9b1fc58afe47a1326320bd284a5c5740e9fa87f39688f225afc5136a0cd615418bf05efdea388619f50564e4725"

RPROVIDES:${PN} += "bundled-rust-crate-ab-glyph \
bundled-rust-crate-ab-glyph-rasterizer \
bundled-rust-crate-accesskit \
bundled-rust-crate-accesskit-atspi-common \
bundled-rust-crate-accesskit-consumer \
bundled-rust-crate-accesskit-unix \
bundled-rust-crate-accesskit-winit \
bundled-rust-crate-adler2 \
bundled-rust-crate-ahash \
bundled-rust-crate-aho-corasick \
bundled-rust-crate-annotate-snippets \
bundled-rust-crate-anstyle \
bundled-rust-crate-anyhow \
bundled-rust-crate-arboard \
bundled-rust-crate-arrayref \
bundled-rust-crate-arrayvec \
bundled-rust-crate-as-raw-xcb-connection \
bundled-rust-crate-ash \
bundled-rust-crate-ashpd \
bundled-rust-crate-async-broadcast \
bundled-rust-crate-async-channel \
bundled-rust-crate-async-executor \
bundled-rust-crate-async-fs \
bundled-rust-crate-async-io \
bundled-rust-crate-async-lock \
bundled-rust-crate-async-net \
bundled-rust-crate-async-process \
bundled-rust-crate-async-signal \
bundled-rust-crate-async-task \
bundled-rust-crate-async-trait \
bundled-rust-crate-atomic-waker \
bundled-rust-crate-atspi \
bundled-rust-crate-atspi-common \
bundled-rust-crate-atspi-connection \
bundled-rust-crate-atspi-proxies \
bundled-rust-crate-autocfg \
bundled-rust-crate-base64 \
bundled-rust-crate-bindgen \
bundled-rust-crate-bit-set \
bundled-rust-crate-bit-vec \
bundled-rust-crate-bitflags \
bundled-rust-crate-blocking \
bundled-rust-crate-bytemuck \
bundled-rust-crate-bytemuck-derive \
bundled-rust-crate-byteorder-lite \
bundled-rust-crate-calloop \
bundled-rust-crate-calloop-wayland-source \
bundled-rust-crate-cc \
bundled-rust-crate-cexpr \
bundled-rust-crate-cfg-aliases \
bundled-rust-crate-cfg-expr \
bundled-rust-crate-cfg-if \
bundled-rust-crate-clang-sys \
bundled-rust-crate-codespan-reporting \
bundled-rust-crate-concurrent-queue \
bundled-rust-crate-convert-case \
bundled-rust-crate-cookie-factory \
bundled-rust-crate-coppwr \
bundled-rust-crate-crc32fast \
bundled-rust-crate-crossbeam-deque \
bundled-rust-crate-crossbeam-epoch \
bundled-rust-crate-crossbeam-utils \
bundled-rust-crate-cursor-icon \
bundled-rust-crate-displaydoc \
bundled-rust-crate-dlib \
bundled-rust-crate-document-features \
bundled-rust-crate-downcast-rs \
bundled-rust-crate-dpi \
bundled-rust-crate-duplicate \
bundled-rust-crate-ecolor \
bundled-rust-crate-eframe \
bundled-rust-crate-egui \
bundled-rust-crate-egui-dock \
bundled-rust-crate-egui-glow \
bundled-rust-crate-egui-plot \
bundled-rust-crate-egui-snarl \
bundled-rust-crate-egui-wgpu \
bundled-rust-crate-egui-winit \
bundled-rust-crate-either \
bundled-rust-crate-emath \
bundled-rust-crate-endi \
bundled-rust-crate-enumflags2 \
bundled-rust-crate-enumflags2-derive \
bundled-rust-crate-enumn \
bundled-rust-crate-epaint \
bundled-rust-crate-epaint-default-fonts \
bundled-rust-crate-equivalent \
bundled-rust-crate-errno \
bundled-rust-crate-event-listener \
bundled-rust-crate-event-listener-strategy \
bundled-rust-crate-fastrand \
bundled-rust-crate-fax \
bundled-rust-crate-fax-derive \
bundled-rust-crate-fdeflate \
bundled-rust-crate-find-msvc-tools \
bundled-rust-crate-flate2 \
bundled-rust-crate-foldhash \
bundled-rust-crate-form-urlencoded \
bundled-rust-crate-futures-channel \
bundled-rust-crate-futures-core \
bundled-rust-crate-futures-io \
bundled-rust-crate-futures-lite \
bundled-rust-crate-futures-macro \
bundled-rust-crate-futures-task \
bundled-rust-crate-futures-util \
bundled-rust-crate-gethostname \
bundled-rust-crate-getrandom \
bundled-rust-crate-gl-generator \
bundled-rust-crate-glob \
bundled-rust-crate-glow \
bundled-rust-crate-glutin \
bundled-rust-crate-glutin-egl-sys \
bundled-rust-crate-glutin-glx-sys \
bundled-rust-crate-glutin-winit \
bundled-rust-crate-gpu-alloc \
bundled-rust-crate-gpu-alloc-types \
bundled-rust-crate-gpu-descriptor \
bundled-rust-crate-gpu-descriptor-types \
bundled-rust-crate-half \
bundled-rust-crate-hashbrown \
bundled-rust-crate-heck \
bundled-rust-crate-hex \
bundled-rust-crate-hexf-parse \
bundled-rust-crate-home \
bundled-rust-crate-icu-collections \
bundled-rust-crate-icu-locale-core \
bundled-rust-crate-icu-normalizer \
bundled-rust-crate-icu-normalizer-data \
bundled-rust-crate-icu-properties \
bundled-rust-crate-icu-properties-data \
bundled-rust-crate-icu-provider \
bundled-rust-crate-idna \
bundled-rust-crate-idna-adapter \
bundled-rust-crate-image \
bundled-rust-crate-indexmap \
bundled-rust-crate-itertools \
bundled-rust-crate-jobserver \
bundled-rust-crate-khronos-api \
bundled-rust-crate-khronos-egl \
bundled-rust-crate-libc \
bundled-rust-crate-libloading \
bundled-rust-crate-libm \
bundled-rust-crate-libspa \
bundled-rust-crate-libspa-sys \
bundled-rust-crate-linux-raw-sys \
bundled-rust-crate-litemap \
bundled-rust-crate-litrs \
bundled-rust-crate-lock-api \
bundled-rust-crate-log \
bundled-rust-crate-memchr \
bundled-rust-crate-memmap2 \
bundled-rust-crate-memoffset \
bundled-rust-crate-minimal-lexical \
bundled-rust-crate-miniz-oxide \
bundled-rust-crate-moxcms \
bundled-rust-crate-naga \
bundled-rust-crate-nix \
bundled-rust-crate-nohash-hasher \
bundled-rust-crate-nom \
bundled-rust-crate-num-traits \
bundled-rust-crate-once-cell \
bundled-rust-crate-ordered-float \
bundled-rust-crate-ordered-stream \
bundled-rust-crate-owned-ttf-parser \
bundled-rust-crate-parking \
bundled-rust-crate-parking-lot \
bundled-rust-crate-parking-lot-core \
bundled-rust-crate-paste \
bundled-rust-crate-percent-encoding \
bundled-rust-crate-pin-project-lite \
bundled-rust-crate-pin-utils \
bundled-rust-crate-piper \
bundled-rust-crate-pipewire \
bundled-rust-crate-pipewire-sys \
bundled-rust-crate-pkg-config \
bundled-rust-crate-png \
bundled-rust-crate-polling \
bundled-rust-crate-pollster \
bundled-rust-crate-potential-utf \
bundled-rust-crate-ppv-lite86 \
bundled-rust-crate-proc-macro-crate \
bundled-rust-crate-proc-macro2 \
bundled-rust-crate-proc-macro2-diagnostics \
bundled-rust-crate-profiling \
bundled-rust-crate-pxfm \
bundled-rust-crate-quick-error \
bundled-rust-crate-quick-xml \
bundled-rust-crate-quote \
bundled-rust-crate-rand \
bundled-rust-crate-rand-chacha \
bundled-rust-crate-rand-core \
bundled-rust-crate-raw-window-handle \
bundled-rust-crate-rayon \
bundled-rust-crate-rayon-core \
bundled-rust-crate-regex \
bundled-rust-crate-regex-automata \
bundled-rust-crate-regex-syntax \
bundled-rust-crate-renderdoc-sys \
bundled-rust-crate-ron \
bundled-rust-crate-rustc-hash \
bundled-rust-crate-rustix \
bundled-rust-crate-scoped-tls \
bundled-rust-crate-scopeguard \
bundled-rust-crate-sctk-adwaita \
bundled-rust-crate-serde \
bundled-rust-crate-serde-core \
bundled-rust-crate-serde-derive \
bundled-rust-crate-serde-repr \
bundled-rust-crate-serde-spanned \
bundled-rust-crate-shlex \
bundled-rust-crate-signal-hook-registry \
bundled-rust-crate-simd-adler32 \
bundled-rust-crate-slab \
bundled-rust-crate-smallvec \
bundled-rust-crate-smithay-client-toolkit \
bundled-rust-crate-smithay-clipboard \
bundled-rust-crate-smol-str \
bundled-rust-crate-spirv \
bundled-rust-crate-stable-deref-trait \
bundled-rust-crate-static-assertions \
bundled-rust-crate-strict-num \
bundled-rust-crate-syn \
bundled-rust-crate-synstructure \
bundled-rust-crate-system-deps \
bundled-rust-crate-target-lexicon \
bundled-rust-crate-termcolor \
bundled-rust-crate-thiserror \
bundled-rust-crate-thiserror-impl \
bundled-rust-crate-tiff \
bundled-rust-crate-tiny-skia \
bundled-rust-crate-tiny-skia-path \
bundled-rust-crate-tinystr \
bundled-rust-crate-toml \
bundled-rust-crate-toml-datetime \
bundled-rust-crate-toml-edit \
bundled-rust-crate-toml-parser \
bundled-rust-crate-toml-writer \
bundled-rust-crate-tracing \
bundled-rust-crate-tracing-attributes \
bundled-rust-crate-tracing-core \
bundled-rust-crate-ttf-parser \
bundled-rust-crate-type-map \
bundled-rust-crate-unicode-ident \
bundled-rust-crate-unicode-segmentation \
bundled-rust-crate-unicode-width \
bundled-rust-crate-url \
bundled-rust-crate-utf8-iter \
bundled-rust-crate-uuid \
bundled-rust-crate-version-check \
bundled-rust-crate-version-compare \
bundled-rust-crate-wayland-backend \
bundled-rust-crate-wayland-client \
bundled-rust-crate-wayland-csd-frame \
bundled-rust-crate-wayland-cursor \
bundled-rust-crate-wayland-protocols \
bundled-rust-crate-wayland-protocols-experimental \
bundled-rust-crate-wayland-protocols-misc \
bundled-rust-crate-wayland-protocols-plasma \
bundled-rust-crate-wayland-protocols-wlr \
bundled-rust-crate-wayland-scanner \
bundled-rust-crate-wayland-sys \
bundled-rust-crate-web-time \
bundled-rust-crate-webbrowser \
bundled-rust-crate-weezl \
bundled-rust-crate-wgpu \
bundled-rust-crate-wgpu-core \
bundled-rust-crate-wgpu-core-deps-windows-linux-android \
bundled-rust-crate-wgpu-hal \
bundled-rust-crate-wgpu-types \
bundled-rust-crate-winit \
bundled-rust-crate-winnow \
bundled-rust-crate-writeable \
bundled-rust-crate-x11-dl \
bundled-rust-crate-x11rb \
bundled-rust-crate-x11rb-protocol \
bundled-rust-crate-xcursor \
bundled-rust-crate-xkbcommon-dl \
bundled-rust-crate-xkeysym \
bundled-rust-crate-xml-rs \
bundled-rust-crate-yoke \
bundled-rust-crate-yoke-derive \
bundled-rust-crate-zbus \
bundled-rust-crate-zbus-lockstep \
bundled-rust-crate-zbus-lockstep-macros \
bundled-rust-crate-zbus-macros \
bundled-rust-crate-zbus-names \
bundled-rust-crate-zbus-xml \
bundled-rust-crate-zerocopy \
bundled-rust-crate-zerocopy-derive \
bundled-rust-crate-zerofrom \
bundled-rust-crate-zerofrom-derive \
bundled-rust-crate-zerotrie \
bundled-rust-crate-zerovec \
bundled-rust-crate-zerovec-derive \
bundled-rust-crate-zune-core \
bundled-rust-crate-zune-jpeg \
bundled-rust-crate-zvariant \
bundled-rust-crate-zvariant-derive \
bundled-rust-crate-zvariant-utils \
coppwr"

RDEPENDS:${PN} += "libc.so.6 \
libgcc-s.so.1 \
libm.so.6 \
libpipewire-0.3.so.0"

inherit rpm
