SUMMARY = "Feature rich terminal UI file transfer and explorer"
DESCRIPTION = "Termscp is a feature rich terminal file transfer and explorer, with support for \
SCP/SFTP/FTP/Kube/S3/WebDAV. So basically is a terminal utility with an TUI to \
connect to a remote server to retrieve and upload files and to interact with \
the local file system. It is Linux, MacOS, FreeBSD, NetBSD and Windows \
compatible."
LICENSE = "MIT"

PV = "1.1.1"

RPM_NAME = "termscp-1.1.1-1.4.aarch64.rpm"
RPM_HASH = "11c3896e83d9ee90fb2d30861b01d6afc76cf643296f3b2831f869f35bb16b41e6f2973d7021ba3a05fb99f2049e40651850b9649ca89960a22dfb4e49511e62"

RPROVIDES:${PN} += "bundled-rust-crate-adler2 \
bundled-rust-crate-aead \
bundled-rust-crate-aes \
bundled-rust-crate-aes-gcm \
bundled-rust-crate-aho-corasick \
bundled-rust-crate-allocator-api2 \
bundled-rust-crate-anyhow \
bundled-rust-crate-approx \
bundled-rust-crate-argh \
bundled-rust-crate-argh-derive \
bundled-rust-crate-argh-shared \
bundled-rust-crate-argon2 \
bundled-rust-crate-arrayvec \
bundled-rust-crate-async-trait \
bundled-rust-crate-atomic-waker \
bundled-rust-crate-autocfg \
bundled-rust-crate-aws-config \
bundled-rust-crate-aws-credential-types \
bundled-rust-crate-aws-lc-rs \
bundled-rust-crate-aws-lc-sys \
bundled-rust-crate-aws-runtime \
bundled-rust-crate-aws-sdk-s3 \
bundled-rust-crate-aws-sdk-sso \
bundled-rust-crate-aws-sdk-ssooidc \
bundled-rust-crate-aws-sdk-sts \
bundled-rust-crate-aws-sigv4 \
bundled-rust-crate-aws-smithy-async \
bundled-rust-crate-aws-smithy-checksums \
bundled-rust-crate-aws-smithy-eventstream \
bundled-rust-crate-aws-smithy-http \
bundled-rust-crate-aws-smithy-http-client \
bundled-rust-crate-aws-smithy-json \
bundled-rust-crate-aws-smithy-observability \
bundled-rust-crate-aws-smithy-query \
bundled-rust-crate-aws-smithy-runtime \
bundled-rust-crate-aws-smithy-runtime-api \
bundled-rust-crate-aws-smithy-types \
bundled-rust-crate-aws-smithy-xml \
bundled-rust-crate-aws-types \
bundled-rust-crate-base16ct \
bundled-rust-crate-base64 \
bundled-rust-crate-base64-simd \
bundled-rust-crate-base64ct \
bundled-rust-crate-bcrypt-pbkdf \
bundled-rust-crate-bitflags \
bundled-rust-crate-blake2 \
bundled-rust-crate-block-buffer \
bundled-rust-crate-block-padding \
bundled-rust-crate-blowfish \
bundled-rust-crate-bumpalo \
bundled-rust-crate-by-address \
bundled-rust-crate-byteorder \
bundled-rust-crate-bytes \
bundled-rust-crate-bytes-utils \
bundled-rust-crate-bytesize \
bundled-rust-crate-bytestring \
bundled-rust-crate-castaway \
bundled-rust-crate-cbc \
bundled-rust-crate-cc \
bundled-rust-crate-cfg-aliases \
bundled-rust-crate-cfg-if \
bundled-rust-crate-chacha20 \
bundled-rust-crate-chrono \
bundled-rust-crate-cipher \
bundled-rust-crate-cmake \
bundled-rust-crate-cmov \
bundled-rust-crate-compact-str \
bundled-rust-crate-console \
bundled-rust-crate-const-oid \
bundled-rust-crate-content-inspector \
bundled-rust-crate-convert-case \
bundled-rust-crate-cpubits \
bundled-rust-crate-cpufeatures \
bundled-rust-crate-crc \
bundled-rust-crate-crc-catalog \
bundled-rust-crate-crc-fast \
bundled-rust-crate-crc32fast \
bundled-rust-crate-critical-section \
bundled-rust-crate-crossbeam-deque \
bundled-rust-crate-crossbeam-epoch \
bundled-rust-crate-crossbeam-utils \
bundled-rust-crate-crossterm \
bundled-rust-crate-crypto-bigint \
bundled-rust-crate-crypto-common \
bundled-rust-crate-crypto-primes \
bundled-rust-crate-ctr \
bundled-rust-crate-ctutils \
bundled-rust-crate-curve25519-dalek \
bundled-rust-crate-darling \
bundled-rust-crate-darling-core \
bundled-rust-crate-darling-macro \
bundled-rust-crate-dashmap \
bundled-rust-crate-data-encoding \
bundled-rust-crate-dbus \
bundled-rust-crate-dbus-secret-service \
bundled-rust-crate-dbus-secret-service-keyring-store \
bundled-rust-crate-delegate \
bundled-rust-crate-der \
bundled-rust-crate-deranged \
bundled-rust-crate-derive-more \
bundled-rust-crate-derive-more-impl \
bundled-rust-crate-des \
bundled-rust-crate-digest \
bundled-rust-crate-dirs \
bundled-rust-crate-dirs-sys \
bundled-rust-crate-displaydoc \
bundled-rust-crate-document-features \
bundled-rust-crate-dunce \
bundled-rust-crate-dyn-clone \
bundled-rust-crate-ecdsa \
bundled-rust-crate-ed25519 \
bundled-rust-crate-ed25519-dalek \
bundled-rust-crate-edit \
bundled-rust-crate-either \
bundled-rust-crate-elliptic-curve \
bundled-rust-crate-encoding-rs \
bundled-rust-crate-enum-dispatch \
bundled-rust-crate-equivalent \
bundled-rust-crate-errno \
bundled-rust-crate-fast-srgb8 \
bundled-rust-crate-fastrand \
bundled-rust-crate-ff \
bundled-rust-crate-fiat-crypto \
bundled-rust-crate-filetime \
bundled-rust-crate-find-msvc-tools \
bundled-rust-crate-flate2 \
bundled-rust-crate-fnv \
bundled-rust-crate-foldhash \
bundled-rust-crate-foreign-types \
bundled-rust-crate-foreign-types-shared \
bundled-rust-crate-form-urlencoded \
bundled-rust-crate-fs-extra \
bundled-rust-crate-futures \
bundled-rust-crate-futures-channel \
bundled-rust-crate-futures-core \
bundled-rust-crate-futures-executor \
bundled-rust-crate-futures-io \
bundled-rust-crate-futures-lite \
bundled-rust-crate-futures-macro \
bundled-rust-crate-futures-sink \
bundled-rust-crate-futures-task \
bundled-rust-crate-futures-util \
bundled-rust-crate-generic-array \
bundled-rust-crate-getrandom \
bundled-rust-crate-ghash \
bundled-rust-crate-git2 \
bundled-rust-crate-glob \
bundled-rust-crate-group \
bundled-rust-crate-h2 \
bundled-rust-crate-hashbrown \
bundled-rust-crate-headers \
bundled-rust-crate-headers-core \
bundled-rust-crate-heck \
bundled-rust-crate-hex \
bundled-rust-crate-hex-literal \
bundled-rust-crate-hkdf \
bundled-rust-crate-hmac \
bundled-rust-crate-home \
bundled-rust-crate-http \
bundled-rust-crate-http-body \
bundled-rust-crate-http-body-util \
bundled-rust-crate-httparse \
bundled-rust-crate-httpdate \
bundled-rust-crate-hybrid-array \
bundled-rust-crate-hyper \
bundled-rust-crate-hyper-http-proxy \
bundled-rust-crate-hyper-rustls \
bundled-rust-crate-hyper-timeout \
bundled-rust-crate-hyper-tls \
bundled-rust-crate-hyper-util \
bundled-rust-crate-iana-time-zone \
bundled-rust-crate-icu-collections \
bundled-rust-crate-icu-locale-core \
bundled-rust-crate-icu-normalizer \
bundled-rust-crate-icu-normalizer-data \
bundled-rust-crate-icu-properties \
bundled-rust-crate-icu-properties-data \
bundled-rust-crate-icu-provider \
bundled-rust-crate-ident-case \
bundled-rust-crate-idna \
bundled-rust-crate-idna-adapter \
bundled-rust-crate-indexmap \
bundled-rust-crate-indicatif \
bundled-rust-crate-indoc \
bundled-rust-crate-inotify \
bundled-rust-crate-inotify-sys \
bundled-rust-crate-inout \
bundled-rust-crate-instability \
bundled-rust-crate-internal-russh-num-bigint \
bundled-rust-crate-ipnet \
bundled-rust-crate-is-docker \
bundled-rust-crate-is-wsl \
bundled-rust-crate-itertools \
bundled-rust-crate-itoa \
bundled-rust-crate-jobserver \
bundled-rust-crate-jsonpath-rust \
bundled-rust-crate-k8s-openapi \
bundled-rust-crate-kasuari \
bundled-rust-crate-keccak \
bundled-rust-crate-kem \
bundled-rust-crate-keyring-core \
bundled-rust-crate-kube \
bundled-rust-crate-kube-client \
bundled-rust-crate-kube-core \
bundled-rust-crate-lazy-regex \
bundled-rust-crate-lazy-regex-proc-macros \
bundled-rust-crate-lazy-static \
bundled-rust-crate-libc \
bundled-rust-crate-libdbus-sys \
bundled-rust-crate-libgit2-sys \
bundled-rust-crate-libm \
bundled-rust-crate-libssh2-sys \
bundled-rust-crate-libz-sys \
bundled-rust-crate-line-clipping \
bundled-rust-crate-linux-raw-sys \
bundled-rust-crate-litemap \
bundled-rust-crate-litrs \
bundled-rust-crate-lock-api \
bundled-rust-crate-log \
bundled-rust-crate-lru \
bundled-rust-crate-lru-slab \
bundled-rust-crate-md-5 \
bundled-rust-crate-md5 \
bundled-rust-crate-memchr \
bundled-rust-crate-mime \
bundled-rust-crate-miniz-oxide \
bundled-rust-crate-mio \
bundled-rust-crate-ml-kem \
bundled-rust-crate-module-lattice \
bundled-rust-crate-native-tls \
bundled-rust-crate-nix \
bundled-rust-crate-nonempty \
bundled-rust-crate-notify \
bundled-rust-crate-notify-rust \
bundled-rust-crate-notify-types \
bundled-rust-crate-nucleo \
bundled-rust-crate-nucleo-matcher \
bundled-rust-crate-num \
bundled-rust-crate-num-bigint \
bundled-rust-crate-num-bigint-dig \
bundled-rust-crate-num-complex \
bundled-rust-crate-num-conv \
bundled-rust-crate-num-integer \
bundled-rust-crate-num-iter \
bundled-rust-crate-num-rational \
bundled-rust-crate-num-threads \
bundled-rust-crate-num-traits \
bundled-rust-crate-number-prefix \
bundled-rust-crate-once-cell \
bundled-rust-crate-opaque-debug \
bundled-rust-crate-open \
bundled-rust-crate-openssl \
bundled-rust-crate-openssl-macros \
bundled-rust-crate-openssl-probe \
bundled-rust-crate-openssl-src \
bundled-rust-crate-openssl-sys \
bundled-rust-crate-option-ext \
bundled-rust-crate-ordered-float \
bundled-rust-crate-outref \
bundled-rust-crate-p256 \
bundled-rust-crate-p384 \
bundled-rust-crate-p521 \
bundled-rust-crate-palette \
bundled-rust-crate-palette-derive \
bundled-rust-crate-parking \
bundled-rust-crate-parking-lot \
bundled-rust-crate-parking-lot-core \
bundled-rust-crate-password-hash \
bundled-rust-crate-pathdiff \
bundled-rust-crate-pavao \
bundled-rust-crate-pavao-sys \
bundled-rust-crate-pbkdf2 \
bundled-rust-crate-pem \
bundled-rust-crate-pem-rfc7468 \
bundled-rust-crate-percent-encoding \
bundled-rust-crate-pest \
bundled-rust-crate-pest-derive \
bundled-rust-crate-pest-generator \
bundled-rust-crate-pest-meta \
bundled-rust-crate-phc \
bundled-rust-crate-pin-project \
bundled-rust-crate-pin-project-internal \
bundled-rust-crate-pin-project-lite \
bundled-rust-crate-pin-utils \
bundled-rust-crate-pkcs1 \
bundled-rust-crate-pkcs5 \
bundled-rust-crate-pkcs8 \
bundled-rust-crate-pkg-config \
bundled-rust-crate-poly1305 \
bundled-rust-crate-polyval \
bundled-rust-crate-portable-atomic \
bundled-rust-crate-potential-utf \
bundled-rust-crate-powerfmt \
bundled-rust-crate-ppv-lite86 \
bundled-rust-crate-primefield \
bundled-rust-crate-primeorder \
bundled-rust-crate-proc-macro2 \
bundled-rust-crate-quick-xml \
bundled-rust-crate-quinn \
bundled-rust-crate-quinn-proto \
bundled-rust-crate-quinn-udp \
bundled-rust-crate-quote \
bundled-rust-crate-rand \
bundled-rust-crate-rand-chacha \
bundled-rust-crate-rand-core \
bundled-rust-crate-ratatui \
bundled-rust-crate-ratatui-core \
bundled-rust-crate-ratatui-crossterm \
bundled-rust-crate-ratatui-widgets \
bundled-rust-crate-rayon \
bundled-rust-crate-rayon-core \
bundled-rust-crate-regex \
bundled-rust-crate-regex-automata \
bundled-rust-crate-regex-lite \
bundled-rust-crate-regex-syntax \
bundled-rust-crate-remotefs \
bundled-rust-crate-remotefs-aws-s3 \
bundled-rust-crate-remotefs-ftp \
bundled-rust-crate-remotefs-kube \
bundled-rust-crate-remotefs-smb \
bundled-rust-crate-remotefs-ssh \
bundled-rust-crate-remotefs-webdav \
bundled-rust-crate-reqwest \
bundled-rust-crate-rfc6979 \
bundled-rust-crate-ring \
bundled-rust-crate-rpassword \
bundled-rust-crate-rsa \
bundled-rust-crate-rtoolbox \
bundled-rust-crate-russh \
bundled-rust-crate-russh-cryptovec \
bundled-rust-crate-russh-keys \
bundled-rust-crate-russh-sftp \
bundled-rust-crate-russh-util \
bundled-rust-crate-rustc-hash \
bundled-rust-crate-rustc-version \
bundled-rust-crate-rustix \
bundled-rust-crate-rustls \
bundled-rust-crate-rustls-native-certs \
bundled-rust-crate-rustls-pemfile \
bundled-rust-crate-rustls-pki-types \
bundled-rust-crate-rustls-webpki \
bundled-rust-crate-rustversion \
bundled-rust-crate-rustydav \
bundled-rust-crate-ryu \
bundled-rust-crate-salsa20 \
bundled-rust-crate-same-file \
bundled-rust-crate-scopeguard \
bundled-rust-crate-scrypt \
bundled-rust-crate-sct \
bundled-rust-crate-sec1 \
bundled-rust-crate-secrecy \
bundled-rust-crate-self-replace \
bundled-rust-crate-self-update \
bundled-rust-crate-semver \
bundled-rust-crate-serde \
bundled-rust-crate-serde-bytes \
bundled-rust-crate-serde-core \
bundled-rust-crate-serde-derive \
bundled-rust-crate-serde-json \
bundled-rust-crate-serde-spanned \
bundled-rust-crate-serde-urlencoded \
bundled-rust-crate-serde-value \
bundled-rust-crate-serde-yaml \
bundled-rust-crate-serdect \
bundled-rust-crate-sha1 \
bundled-rust-crate-sha2 \
bundled-rust-crate-sha3 \
bundled-rust-crate-shellexpand \
bundled-rust-crate-shlex \
bundled-rust-crate-signal-hook \
bundled-rust-crate-signal-hook-mio \
bundled-rust-crate-signal-hook-registry \
bundled-rust-crate-signature \
bundled-rust-crate-simd-adler32 \
bundled-rust-crate-simplelog \
bundled-rust-crate-slab \
bundled-rust-crate-smallvec \
bundled-rust-crate-smawk \
bundled-rust-crate-socket2 \
bundled-rust-crate-spin \
bundled-rust-crate-spki \
bundled-rust-crate-ssh-cipher \
bundled-rust-crate-ssh-encoding \
bundled-rust-crate-ssh-key \
bundled-rust-crate-ssh2-config \
bundled-rust-crate-stable-deref-trait \
bundled-rust-crate-static-assertions \
bundled-rust-crate-strsim \
bundled-rust-crate-strum \
bundled-rust-crate-strum-macros \
bundled-rust-crate-subtle \
bundled-rust-crate-suppaftp \
bundled-rust-crate-syn \
bundled-rust-crate-sync-wrapper \
bundled-rust-crate-synstructure \
bundled-rust-crate-tar \
bundled-rust-crate-tempfile \
bundled-rust-crate-termcolor \
bundled-rust-crate-termscp \
bundled-rust-crate-textwrap \
bundled-rust-crate-thiserror \
bundled-rust-crate-thiserror-impl \
bundled-rust-crate-time \
bundled-rust-crate-time-core \
bundled-rust-crate-time-macros \
bundled-rust-crate-tinystr \
bundled-rust-crate-tinyvec \
bundled-rust-crate-tinyvec-macros \
bundled-rust-crate-tokio \
bundled-rust-crate-tokio-macros \
bundled-rust-crate-tokio-native-tls \
bundled-rust-crate-tokio-rustls \
bundled-rust-crate-tokio-stream \
bundled-rust-crate-tokio-tungstenite \
bundled-rust-crate-tokio-util \
bundled-rust-crate-toml \
bundled-rust-crate-toml-datetime \
bundled-rust-crate-toml-parser \
bundled-rust-crate-toml-writer \
bundled-rust-crate-tower \
bundled-rust-crate-tower-http \
bundled-rust-crate-tower-layer \
bundled-rust-crate-tower-service \
bundled-rust-crate-tracing \
bundled-rust-crate-tracing-attributes \
bundled-rust-crate-tracing-core \
bundled-rust-crate-try-lock \
bundled-rust-crate-tui-realm-stdlib \
bundled-rust-crate-tui-term \
bundled-rust-crate-tuirealm \
bundled-rust-crate-tuirealm-derive \
bundled-rust-crate-tungstenite \
bundled-rust-crate-typenum \
bundled-rust-crate-ucd-trie \
bundled-rust-crate-unicode-ident \
bundled-rust-crate-unicode-linebreak \
bundled-rust-crate-unicode-segmentation \
bundled-rust-crate-unicode-truncate \
bundled-rust-crate-unicode-width \
bundled-rust-crate-universal-hash \
bundled-rust-crate-unsafe-libyaml \
bundled-rust-crate-untrusted \
bundled-rust-crate-url \
bundled-rust-crate-urlencoding \
bundled-rust-crate-utf-8 \
bundled-rust-crate-utf8-iter \
bundled-rust-crate-uuid \
bundled-rust-crate-uzers \
bundled-rust-crate-vcpkg \
bundled-rust-crate-version-check \
bundled-rust-crate-vsimd \
bundled-rust-crate-vt100 \
bundled-rust-crate-vte \
bundled-rust-crate-walkdir \
bundled-rust-crate-want \
bundled-rust-crate-webpki-roots \
bundled-rust-crate-which \
bundled-rust-crate-whoami \
bundled-rust-crate-wildmatch \
bundled-rust-crate-winnow \
bundled-rust-crate-writeable \
bundled-rust-crate-xattr \
bundled-rust-crate-xmlparser \
bundled-rust-crate-yoke \
bundled-rust-crate-yoke-derive \
bundled-rust-crate-zerocopy \
bundled-rust-crate-zerofrom \
bundled-rust-crate-zerofrom-derive \
bundled-rust-crate-zeroize \
bundled-rust-crate-zeroize-derive \
bundled-rust-crate-zerotrie \
bundled-rust-crate-zerovec \
bundled-rust-crate-zerovec-derive \
bundled-rust-crate-zip \
bundled-rust-crate-zipsign-api \
bundled-rust-crate-zmij \
bundled-rust-crate-zopfli \
termscp"

RDEPENDS:${PN} += "libc.so.6 \
libgcc-s.so.1 \
libm.so.6 \
libsmbclient.so.0"

inherit rpm
