SUMMARY = "Customised BibTeX styles"
DESCRIPTION = "Package generating customized BibTeX bibliography styles from a \
generic file using docstrip driven by parameters generated by a \
menu application. Includes support for the Harvard style of \
citations."
LICENSE = "LPPL-1.0"

PV = "2026.226.4.33svn76790"

RPM_NAME = "texlive-custom-bib-2026.226.4.33svn76790-61.2.noarch.rpm"
RPM_HASH = "e5f95599c6f26388dd174fb0aec18ebeb404552fa9d0bcf997d9575f7c1d7aaf298391bc52dd2ab8beefc7c153ccf4db8f7dbc83f1f2c8067d3deb766398700f"
REPO_ARCH = "noarch"

RPROVIDES:${PN} += "tex-geophys.tex \
tex-makebst.tex \
tex-shorthnd.tex \
texlive-custom-bib"

RDEPENDS:${PN} += "/usr/bin/sh \
coreutils \
ed \
findutils \
grep \
sed \
texlive \
texlive-filesystem \
texlive-kpathsea \
texlive-kpathsea-bin \
texlive-scripts \
texlive-scripts-bin"

inherit rpm
