SUMMARY = "MATE system log viewer"
DESCRIPTION = "This is the MATE system log viewer as shipped with the MATE utilities. \
mate-system-log is a program which can view logs generated by the \
operating system."
LICENSE = "GPL-2.0-or-later & GPL-3.0-or-later"

PV = "1.28.0"

RPM_NAME = "mate-system-log-1.28.0-2.6.aarch64.rpm"
RPM_HASH = "fcaef118e7c9396856f903339f553bf4c69363d0d27991eb2f9a86a5f49b49ef7c32562c0a820633139e8303f782fbdabc9d83fef78d2c37cbbe40596d455aef"

RPROVIDES:${PN} += "mate-system-log"

RDEPENDS:${PN} += "ld-linux-aarch64.so.1 \
libc.so.6 \
libgdk-3.so.0 \
libgio-2.0.so.0 \
libglib-2.0.so.0 \
libgobject-2.0.so.0 \
libgtk-3.so.0 \
libm.so.6 \
libpango-1.0.so.0 \
libz.so.1 \
mate-desktop-gschemas"

inherit rpm
