SUMMARY = "Development files for libt3key, a terminal key sequence db library"
DESCRIPTION = "libt3key is library that provides a database of mappings from escape \
sequences as generated by different consoles and terminals or \
emulators, to key symbols. \
 \
This subpackage contains libraries and header files for developing \
applications that want to make use of libt3key."
LICENSE = "GPL-3.0-only"

PV = "0.2.11"

RPM_NAME = "libt3key-devel-0.2.11-1.8.aarch64.rpm"
RPM_HASH = "252a079ddfc478a7fad39e39383d1ffb7738eef9b46d9e6645586243bca9ec3a6a661b5f8168fce0383440886a6f85da9c260be569dbf9badbb8fdee798a2fe4"

RPROVIDES:${PN} += "libt3key-devel \
pkgconfig-libt3key"

RDEPENDS:${PN} += "/usr/bin/pkg-config \
libt3key1 \
pkgconfig-libt3config \
pkgconfig-tinfo"

inherit rpm
