SUMMARY = "A simple Django application to demonstrate RRD plots"
DESCRIPTION = "django-collectd-rest is a simple Django application to demonstrate RRD plots generated by collectd or any other rrd data. \
The application is built on top of django-rest-framework and provides REST API to access the plots."
LICENSE = "BSD-2-Clause"

PV = "0.2.6"

RPM_NAME = "python314-django-collectd-rest-0.2.6-1.10.aarch64.rpm"
RPM_HASH = "022ce758aee2f9b365e33afa116235d20766e43d3bdc2ab24e2935f8e80e93c07991b23f308b08ff7891be5da8eb9c49f956045727833eb27e735e73d2f45d2e"

RPROVIDES:${PN} += "python3.14dist-django-collectd-rest \
python314-django-collectd-rest \
python3dist-django-collectd-rest"

RDEPENDS:${PN} += "libc.so.6 \
librrd.so.8 \
python-abi \
python314-djangorestframework \
rrdtool"

inherit rpm
