SUMMARY = "NVIDIA open kernel module driver for GeForce 16 series (GTX 16xx) and newer"
DESCRIPTION = "This package provides the open-source NVIDIA kernel module driver \
for GeForce 16 series (GTX 16xx) and newer GPUs, i.e. Turing GPU family \
and newer (Turing, Ampere, Ada Lavelace, Hopper, Blackwell, ...). \
This driver variant is meant to be used when using the GFX repository \
below \
 \
  https://download.nvidia.com/suse/ \
  https://download.nvidia.com/opensuse/ \
 \
for user-space driver installation."
LICENSE = "GPL-2.0-only & MIT"

PV = "595.99.02_k6.18.51_1"

RPM_NAME = "nvidia-open-driver-G07-signed-kmp-longterm-595.99.02_k6.18.51_1-2.2.aarch64.rpm"
RPM_HASH = "4e0cbfeccaac768356d52ad956cf9c8e76d515b44a1fb03c340c389834e86732a86fd497a11befd9df4a197cd3851d6ba70efd7957c76b35364ab4eec949213c"

RPROVIDES:${PN} += "kmod-nvidia-drm.ko \
kmod-nvidia-modeset.ko \
kmod-nvidia-uvm.ko \
kmod-nvidia.ko \
ksym-longterm-nvKmsKapiF16ToF32 \
ksym-longterm-nvKmsKapiF32Add \
ksym-longterm-nvKmsKapiF32Div \
ksym-longterm-nvKmsKapiF32Mul \
ksym-longterm-nvKmsKapiF32ToF16 \
ksym-longterm-nvKmsKapiF32ToUI32RMinMag \
ksym-longterm-nvKmsKapiGetFunctionsTable \
ksym-longterm-nvKmsKapiUI32ToF32 \
ksym-longterm-nvUvmInterfaceAccessBitsBufAlloc \
ksym-longterm-nvUvmInterfaceAccessBitsBufFree \
ksym-longterm-nvUvmInterfaceAccessBitsDump \
ksym-longterm-nvUvmInterfaceAddressSpaceCreate \
ksym-longterm-nvUvmInterfaceAddressSpaceDestroy \
ksym-longterm-nvUvmInterfaceBindChannelResources \
ksym-longterm-nvUvmInterfaceChannelAllocate \
ksym-longterm-nvUvmInterfaceChannelDestroy \
ksym-longterm-nvUvmInterfaceCslDecrypt \
ksym-longterm-nvUvmInterfaceCslEncrypt \
ksym-longterm-nvUvmInterfaceCslIncrementIv \
ksym-longterm-nvUvmInterfaceCslInitContext \
ksym-longterm-nvUvmInterfaceCslLogEncryption \
ksym-longterm-nvUvmInterfaceCslQueryMessagePool \
ksym-longterm-nvUvmInterfaceCslRotateIv \
ksym-longterm-nvUvmInterfaceCslRotateKey \
ksym-longterm-nvUvmInterfaceCslSign \
ksym-longterm-nvUvmInterfaceDeRegisterUvmEvents \
ksym-longterm-nvUvmInterfaceDeinitCslContext \
ksym-longterm-nvUvmInterfaceDestroyAccessCntrInfo \
ksym-longterm-nvUvmInterfaceDestroyFaultInfo \
ksym-longterm-nvUvmInterfaceDeviceCreate \
ksym-longterm-nvUvmInterfaceDeviceDestroy \
ksym-longterm-nvUvmInterfaceDisableAccessCntr \
ksym-longterm-nvUvmInterfaceDupAddressSpace \
ksym-longterm-nvUvmInterfaceDupAllocation \
ksym-longterm-nvUvmInterfaceDupMemory \
ksym-longterm-nvUvmInterfaceEnableAccessCntr \
ksym-longterm-nvUvmInterfaceFlushReplayableFaultBuffer \
ksym-longterm-nvUvmInterfaceFreeDupedHandle \
ksym-longterm-nvUvmInterfaceGetChannelResourcePtes \
ksym-longterm-nvUvmInterfaceGetEccInfo \
ksym-longterm-nvUvmInterfaceGetExternalAllocPhysAddrs \
ksym-longterm-nvUvmInterfaceGetExternalAllocPtes \
ksym-longterm-nvUvmInterfaceGetFbInfo \
ksym-longterm-nvUvmInterfaceGetGpuInfo \
ksym-longterm-nvUvmInterfaceGetNonReplayableFaults \
ksym-longterm-nvUvmInterfaceGetNvlinkInfo \
ksym-longterm-nvUvmInterfaceGetP2PCaps \
ksym-longterm-nvUvmInterfaceGetPmaObject \
ksym-longterm-nvUvmInterfaceHasPendingNonReplayableFaults \
ksym-longterm-nvUvmInterfaceInitAccessCntrInfo \
ksym-longterm-nvUvmInterfaceInitFaultInfo \
ksym-longterm-nvUvmInterfaceMemoryAllocFB \
ksym-longterm-nvUvmInterfaceMemoryAllocSys \
ksym-longterm-nvUvmInterfaceMemoryCpuMap \
ksym-longterm-nvUvmInterfaceMemoryCpuUnMap \
ksym-longterm-nvUvmInterfaceMemoryFree \
ksym-longterm-nvUvmInterfaceOwnPageFaultIntr \
ksym-longterm-nvUvmInterfaceP2pObjectCreate \
ksym-longterm-nvUvmInterfaceP2pObjectDestroy \
ksym-longterm-nvUvmInterfacePagingChannelAllocate \
ksym-longterm-nvUvmInterfacePagingChannelDestroy \
ksym-longterm-nvUvmInterfacePagingChannelPushStream \
ksym-longterm-nvUvmInterfacePagingChannelsMap \
ksym-longterm-nvUvmInterfacePagingChannelsUnmap \
ksym-longterm-nvUvmInterfacePmaAllocPages \
ksym-longterm-nvUvmInterfacePmaFreePages \
ksym-longterm-nvUvmInterfacePmaPinPages \
ksym-longterm-nvUvmInterfacePmaRegisterEvictionCallbacks \
ksym-longterm-nvUvmInterfacePmaUnregisterEvictionCallbacks \
ksym-longterm-nvUvmInterfaceQueryCaps \
ksym-longterm-nvUvmInterfaceQueryCopyEnginesCaps \
ksym-longterm-nvUvmInterfaceRegisterGpu \
ksym-longterm-nvUvmInterfaceRegisterUvmEvents \
ksym-longterm-nvUvmInterfaceReleaseChannel \
ksym-longterm-nvUvmInterfaceReportFatalError \
ksym-longterm-nvUvmInterfaceReportNonReplayableFault \
ksym-longterm-nvUvmInterfaceRetainChannel \
ksym-longterm-nvUvmInterfaceServiceDeviceInterruptsRM \
ksym-longterm-nvUvmInterfaceSessionCreate \
ksym-longterm-nvUvmInterfaceSessionDestroy \
ksym-longterm-nvUvmInterfaceSetPageDirectory \
ksym-longterm-nvUvmInterfaceStopChannel \
ksym-longterm-nvUvmInterfaceTogglePrefetchFaults \
ksym-longterm-nvUvmInterfaceTsgAllocate \
ksym-longterm-nvUvmInterfaceTsgDestroy \
ksym-longterm-nvUvmInterfaceUnregisterGpu \
ksym-longterm-nvUvmInterfaceUnsetPageDirectory \
ksym-longterm-nvidia-get-rm-ops \
ksym-longterm-nvidia-p2p-destroy-mapping \
ksym-longterm-nvidia-p2p-dma-map-pages \
ksym-longterm-nvidia-p2p-dma-unmap-pages \
ksym-longterm-nvidia-p2p-free-dma-mapping \
ksym-longterm-nvidia-p2p-free-page-table \
ksym-longterm-nvidia-p2p-get-pages \
ksym-longterm-nvidia-p2p-get-pages-persistent \
ksym-longterm-nvidia-p2p-get-rsync-registers \
ksym-longterm-nvidia-p2p-init-mapping \
ksym-longterm-nvidia-p2p-put-pages \
ksym-longterm-nvidia-p2p-put-pages-persistent \
ksym-longterm-nvidia-p2p-put-rsync-registers \
ksym-longterm-nvidia-p2p-register-rsync-driver \
ksym-longterm-nvidia-p2p-unregister-rsync-driver \
ksym-longterm-nvidia-register-error-cb \
ksym-longterm-nvidia-unregister-error-cb \
nvidia-open-driver-G07 \
nvidia-open-driver-G07-signed-kmp \
nvidia-open-driver-G07-signed-kmp-longterm \
nvidia-open-driver-G07-signed-kmp-longterm-k6.18.51-1 \
nvidia-open-signed-kmp \
nvidia-open-signed-kmp-gfx \
open-driver-non-cuda-variant"

RDEPENDS:${PN} += "/usr/bin/bash \
/usr/bin/sh \
coreutils \
grep \
group-video \
ksym-longterm----ratelimit \
ksym-longterm---acpi-video-get-backlight-type \
ksym-longterm---alloc-pages-noprof \
ksym-longterm---arch-copy-from-user \
ksym-longterm---arch-copy-to-user \
ksym-longterm---bitmap-and \
ksym-longterm---bitmap-andnot \
ksym-longterm---bitmap-clear \
ksym-longterm---bitmap-complement \
ksym-longterm---bitmap-equal \
ksym-longterm---bitmap-intersects \
ksym-longterm---bitmap-or \
ksym-longterm---bitmap-set \
ksym-longterm---bitmap-shift-left \
ksym-longterm---bitmap-shift-right \
ksym-longterm---bitmap-subset \
ksym-longterm---bitmap-weight \
ksym-longterm---check-object-size \
ksym-longterm---clk-get-name \
ksym-longterm---const-udelay \
ksym-longterm---cpu-online-mask \
ksym-longterm---cpu-possible-mask \
ksym-longterm---dma-sync-sg-for-device \
ksym-longterm---dma-sync-single-for-cpu \
ksym-longterm---dma-sync-single-for-device \
ksym-longterm---drm-atomic-helper-connector-destroy-state \
ksym-longterm---drm-atomic-helper-connector-duplicate-state \
ksym-longterm---drm-atomic-helper-connector-reset \
ksym-longterm---drm-atomic-helper-crtc-destroy-state \
ksym-longterm---drm-atomic-helper-crtc-duplicate-state \
ksym-longterm---drm-atomic-helper-plane-destroy-state \
ksym-longterm---drm-atomic-helper-plane-duplicate-state \
ksym-longterm---drm-atomic-state-free \
ksym-longterm---drm-dev-dbg \
ksym-longterm---drm-err \
ksym-longterm---folio-lock \
ksym-longterm---folio-put \
ksym-longterm---fortify-panic \
ksym-longterm---free-pages \
ksym-longterm---init-rwsem \
ksym-longterm---init-swait-queue-head \
ksym-longterm---init-waitqueue-head \
ksym-longterm---ioremap-prot \
ksym-longterm---kmalloc-cache-noprof \
ksym-longterm---kmalloc-large-noprof \
ksym-longterm---kmalloc-noprof \
ksym-longterm---kmem-cache-create-args \
ksym-longterm---kvmalloc-node-noprof \
ksym-longterm---list-add-valid-or-report \
ksym-longterm---list-del-entry-valid-or-report \
ksym-longterm---mmap-lock-do-trace-acquire-returned \
ksym-longterm---mmap-lock-do-trace-released \
ksym-longterm---mmap-lock-do-trace-start-locking \
ksym-longterm---mmdrop \
ksym-longterm---mmu-notifier-register \
ksym-longterm---msecs-to-jiffies \
ksym-longterm---mutex-init \
ksym-longterm---ndelay \
ksym-longterm---node-distance \
ksym-longterm---of-parse-phandle-with-args \
ksym-longterm---pci-register-driver \
ksym-longterm---per-cpu-offset \
ksym-longterm---platform-driver-register \
ksym-longterm---pm-runtime-disable \
ksym-longterm---pm-runtime-use-autosuspend \
ksym-longterm---printk-ratelimit \
ksym-longterm---rcu-read-lock \
ksym-longterm---rcu-read-unlock \
ksym-longterm---refrigerator \
ksym-longterm---release-region \
ksym-longterm---request-region \
ksym-longterm---seq-puts \
ksym-longterm---sg-page-iter-dma-next \
ksym-longterm---sg-page-iter-start \
ksym-longterm---stack-chk-fail \
ksym-longterm---sw-hweight32 \
ksym-longterm---sw-hweight64 \
ksym-longterm---sw-hweight8 \
ksym-longterm---task-pid-nr-ns \
ksym-longterm---trace-set-current-state \
ksym-longterm---trace-trigger-soft-disabled \
ksym-longterm---tracepoint-mmap-lock-acquire-returned \
ksym-longterm---tracepoint-mmap-lock-released \
ksym-longterm---tracepoint-mmap-lock-start-locking \
ksym-longterm---tracepoint-sched-set-state-tp \
ksym-longterm---udelay \
ksym-longterm---usecs-to-jiffies \
ksym-longterm---vma-start-write \
ksym-longterm---vmalloc-noprof \
ksym-longterm---wake-up \
ksym-longterm---warn-printk \
ksym-longterm--ctype \
ksym-longterm--find-first-bit \
ksym-longterm--find-first-zero-bit \
ksym-longterm--find-last-bit \
ksym-longterm--find-next-bit \
ksym-longterm--find-next-zero-bit \
ksym-longterm--printk \
ksym-longterm--raw-read-lock \
ksym-longterm--raw-read-unlock \
ksym-longterm--raw-spin-lock \
ksym-longterm--raw-spin-lock-irq \
ksym-longterm--raw-spin-lock-irqsave \
ksym-longterm--raw-spin-unlock \
ksym-longterm--raw-spin-unlock-irq \
ksym-longterm--raw-spin-unlock-irqrestore \
ksym-longterm-acpi-evaluate-integer \
ksym-longterm-acpi-evaluate-object \
ksym-longterm-acpi-gbl-FADT \
ksym-longterm-acpi-get-handle \
ksym-longterm-acpi-get-next-object \
ksym-longterm-acpi-get-table \
ksym-longterm-acpi-install-notify-handler \
ksym-longterm-acpi-put-table \
ksym-longterm-acpi-remove-notify-handler \
ksym-longterm-acpi-video-register-backlight \
ksym-longterm-acpi-walk-namespace \
ksym-longterm-add-memory-driver-managed \
ksym-longterm-address-space-init-once \
ksym-longterm-alloc-chrdev-region \
ksym-longterm-alloc-pages-noprof \
ksym-longterm-alt-cb-patch-nops \
ksym-longterm-aperture-remove-conflicting-devices \
ksym-longterm-aperture-remove-conflicting-pci-devices \
ksym-longterm-arm64-use-ng-mappings \
ksym-longterm-backlight-device-register \
ksym-longterm-backlight-device-unregister \
ksym-longterm-bit-wait \
ksym-longterm-bpf-trace-run3 \
ksym-longterm-cache-line-size \
ksym-longterm-cancel-delayed-work \
ksym-longterm-cancel-delayed-work-sync \
ksym-longterm-capable \
ksym-longterm-cc-platform-has \
ksym-longterm-cdev-add \
ksym-longterm-cdev-del \
ksym-longterm-cdev-init \
ksym-longterm-class-create \
ksym-longterm-class-destroy \
ksym-longterm-clear-page \
ksym-longterm-clk-disable \
ksym-longterm-clk-enable \
ksym-longterm-clk-get-rate \
ksym-longterm-clk-prepare \
ksym-longterm-clk-round-rate \
ksym-longterm-clk-set-rate \
ksym-longterm-clk-unprepare \
ksym-longterm-close-fd \
ksym-longterm-complete \
ksym-longterm-complete-all \
ksym-longterm-completion-done \
ksym-longterm-console-lock \
ksym-longterm-console-unlock \
ksym-longterm-cpu-all-bits \
ksym-longterm-cpufreq-get \
ksym-longterm-crypto-aead-decrypt \
ksym-longterm-crypto-aead-encrypt \
ksym-longterm-crypto-aead-setkey \
ksym-longterm-crypto-alloc-aead \
ksym-longterm-crypto-alloc-shash \
ksym-longterm-crypto-alloc-sig \
ksym-longterm-crypto-destroy-tfm \
ksym-longterm-crypto-ecdh-shared-secret \
ksym-longterm-crypto-req-done \
ksym-longterm-crypto-shash-export \
ksym-longterm-crypto-shash-finup \
ksym-longterm-crypto-shash-import \
ksym-longterm-crypto-shash-init \
ksym-longterm-crypto-shash-setkey \
ksym-longterm-crypto-shash-tfm-digest \
ksym-longterm-delayed-work-timer-fn \
ksym-longterm-dev-driver-string \
ksym-longterm-dev-pm-domain-attach \
ksym-longterm-dev-pm-domain-detach \
ksym-longterm-dev-pm-domain-set \
ksym-longterm-dev-pm-genpd-resume \
ksym-longterm-dev-pm-genpd-suspend \
ksym-longterm-dev-pm-opp-add-dynamic \
ksym-longterm-dev-pm-opp-remove \
ksym-longterm-dev-set-name \
ksym-longterm-devfreq-resume-device \
ksym-longterm-devfreq-suspend-device \
ksym-longterm-device-create \
ksym-longterm-device-destroy \
ksym-longterm-device-property-read-u64-array \
ksym-longterm-device-register \
ksym-longterm-device-unregister \
ksym-longterm-devm-clk-bulk-get-all \
ksym-longterm-devm-clk-get \
ksym-longterm-devm-clk-put \
ksym-longterm-devm-devfreq-add-device \
ksym-longterm-devm-devfreq-remove-device \
ksym-longterm-devm-gpio-request-one \
ksym-longterm-devm-ioremap \
ksym-longterm-devm-kmalloc \
ksym-longterm-devm-memunmap-pages \
ksym-longterm-devm-of-icc-get \
ksym-longterm-disable-irq-nosync \
ksym-longterm-dma-alloc-attrs \
ksym-longterm-dma-buf-attach \
ksym-longterm-dma-buf-detach \
ksym-longterm-dma-buf-export \
ksym-longterm-dma-buf-fd \
ksym-longterm-dma-buf-get \
ksym-longterm-dma-buf-map-attachment \
ksym-longterm-dma-buf-put \
ksym-longterm-dma-buf-unmap-attachment \
ksym-longterm-dma-fence-add-callback \
ksym-longterm-dma-fence-context-alloc \
ksym-longterm-dma-fence-default-wait \
ksym-longterm-dma-fence-init \
ksym-longterm-dma-fence-release \
ksym-longterm-dma-fence-signal \
ksym-longterm-dma-free-attrs \
ksym-longterm-dma-map-page-attrs \
ksym-longterm-dma-map-sg-attrs \
ksym-longterm-dma-resv-add-fence \
ksym-longterm-dma-resv-reserve-fences \
ksym-longterm-dma-set-coherent-mask \
ksym-longterm-dma-set-mask \
ksym-longterm-dma-unmap-page-attrs \
ksym-longterm-dma-unmap-sg-attrs \
ksym-longterm-dmi-get-system-info \
ksym-longterm-down \
ksym-longterm-down-interruptible \
ksym-longterm-down-read \
ksym-longterm-down-read-trylock \
ksym-longterm-down-trylock \
ksym-longterm-down-write \
ksym-longterm-down-write-trylock \
ksym-longterm-downgrade-write \
ksym-longterm-drm-atomic-add-affected-connectors \
ksym-longterm-drm-atomic-add-affected-planes \
ksym-longterm-drm-atomic-commit \
ksym-longterm-drm-atomic-get-connector-state \
ksym-longterm-drm-atomic-get-crtc-state \
ksym-longterm-drm-atomic-get-plane-state \
ksym-longterm-drm-atomic-helper-check \
ksym-longterm-drm-atomic-helper-crtc-reset \
ksym-longterm-drm-atomic-helper-disable-plane \
ksym-longterm-drm-atomic-helper-page-flip \
ksym-longterm-drm-atomic-helper-plane-reset \
ksym-longterm-drm-atomic-helper-prepare-planes \
ksym-longterm-drm-atomic-helper-set-config \
ksym-longterm-drm-atomic-helper-shutdown \
ksym-longterm-drm-atomic-helper-swap-state \
ksym-longterm-drm-atomic-helper-update-legacy-modeset-state \
ksym-longterm-drm-atomic-helper-update-plane \
ksym-longterm-drm-atomic-set-crtc-for-connector \
ksym-longterm-drm-atomic-set-crtc-for-plane \
ksym-longterm-drm-atomic-set-fb-for-plane \
ksym-longterm-drm-atomic-set-mode-prop-for-crtc \
ksym-longterm-drm-atomic-state-alloc \
ksym-longterm-drm-atomic-state-default-clear \
ksym-longterm-drm-atomic-state-default-release \
ksym-longterm-drm-atomic-state-init \
ksym-longterm-drm-client-setup \
ksym-longterm-drm-compat-ioctl \
ksym-longterm-drm-connector-atomic-hdr-metadata-equal \
ksym-longterm-drm-connector-attach-colorspace-property \
ksym-longterm-drm-connector-attach-encoder \
ksym-longterm-drm-connector-attach-hdr-output-metadata-property \
ksym-longterm-drm-connector-attach-vrr-capable-property \
ksym-longterm-drm-connector-cleanup \
ksym-longterm-drm-connector-init \
ksym-longterm-drm-connector-list-iter-begin \
ksym-longterm-drm-connector-list-iter-end \
ksym-longterm-drm-connector-list-iter-next \
ksym-longterm-drm-connector-register \
ksym-longterm-drm-connector-set-vrr-capable-property \
ksym-longterm-drm-connector-unregister \
ksym-longterm-drm-connector-update-edid-property \
ksym-longterm-drm-crtc-cleanup \
ksym-longterm-drm-crtc-enable-color-mgmt \
ksym-longterm-drm-crtc-init-with-planes \
ksym-longterm-drm-crtc-send-vblank-event \
ksym-longterm-drm-dev-alloc \
ksym-longterm-drm-dev-put \
ksym-longterm-drm-dev-register \
ksym-longterm-drm-dev-unplug \
ksym-longterm-drm-dev-unregister \
ksym-longterm-drm-edid-override-connector-update \
ksym-longterm-drm-encoder-cleanup \
ksym-longterm-drm-encoder-init \
ksym-longterm-drm-fb-helper-set-suspend-unlocked \
ksym-longterm-drm-fbdev-ttm-driver-fbdev-probe \
ksym-longterm-drm-file-get-master \
ksym-longterm-drm-format-info \
ksym-longterm-drm-framebuffer-cleanup \
ksym-longterm-drm-framebuffer-init \
ksym-longterm-drm-gem-create-mmap-offset \
ksym-longterm-drm-gem-handle-create \
ksym-longterm-drm-gem-mmap-obj \
ksym-longterm-drm-gem-object-free \
ksym-longterm-drm-gem-object-lookup \
ksym-longterm-drm-gem-object-release \
ksym-longterm-drm-gem-prime-export \
ksym-longterm-drm-gem-prime-fd-to-handle \
ksym-longterm-drm-gem-prime-handle-to-fd \
ksym-longterm-drm-gem-prime-import \
ksym-longterm-drm-gem-private-object-init \
ksym-longterm-drm-gem-vm-close \
ksym-longterm-drm-gem-vm-open \
ksym-longterm-drm-helper-hpd-irq-event \
ksym-longterm-drm-helper-mode-fill-fb-struct \
ksym-longterm-drm-helper-probe-single-connector-modes \
ksym-longterm-drm-ioctl \
ksym-longterm-drm-kms-helper-hotplug-event \
ksym-longterm-drm-kms-helper-poll-disable \
ksym-longterm-drm-kms-helper-poll-enable \
ksym-longterm-drm-kms-helper-poll-fini \
ksym-longterm-drm-kms-helper-poll-init \
ksym-longterm-drm-master-put \
ksym-longterm-drm-mode-config-cleanup \
ksym-longterm-drm-mode-config-reset \
ksym-longterm-drm-mode-create \
ksym-longterm-drm-mode-create-dp-colorspace-property \
ksym-longterm-drm-mode-create-dvi-i-properties \
ksym-longterm-drm-mode-create-hdmi-colorspace-property \
ksym-longterm-drm-mode-crtc-set-gamma-size \
ksym-longterm-drm-mode-object-find \
ksym-longterm-drm-mode-object-put \
ksym-longterm-drm-mode-probed-add \
ksym-longterm-drm-mode-set-name \
ksym-longterm-drm-mode-vrefresh \
ksym-longterm-drm-modeset-acquire-fini \
ksym-longterm-drm-modeset-acquire-init \
ksym-longterm-drm-modeset-backoff \
ksym-longterm-drm-modeset-drop-locks \
ksym-longterm-drm-modeset-lock-all \
ksym-longterm-drm-modeset-lock-all-ctx \
ksym-longterm-drm-modeset-unlock-all \
ksym-longterm-drm-object-attach-property \
ksym-longterm-drm-object-property-set-value \
ksym-longterm-drm-open \
ksym-longterm-drm-plane-cleanup \
ksym-longterm-drm-plane-create-alpha-property \
ksym-longterm-drm-plane-create-blend-mode-property \
ksym-longterm-drm-plane-create-color-properties \
ksym-longterm-drm-plane-create-rotation-property \
ksym-longterm-drm-poll \
ksym-longterm-drm-prime-gem-destroy \
ksym-longterm-drm-prime-pages-to-sg \
ksym-longterm-drm-property-blob-get \
ksym-longterm-drm-property-blob-put \
ksym-longterm-drm-property-create \
ksym-longterm-drm-property-create-enum \
ksym-longterm-drm-property-create-range \
ksym-longterm-drm-property-lookup-blob \
ksym-longterm-drm-read \
ksym-longterm-drm-release \
ksym-longterm-drm-universal-plane-init \
ksym-longterm-drm-vma-node-is-allowed \
ksym-longterm-drm-vma-offset-lookup-locked \
ksym-longterm-drmm-mode-config-init \
ksym-longterm-dump-stack \
ksym-longterm-dynamic-cond-resched \
ksym-longterm-dynamic-might-resched \
ksym-longterm-dynamic-preempt-schedule \
ksym-longterm-dynamic-preempt-schedule-notrace \
ksym-longterm-ecc-digits-from-bytes \
ksym-longterm-ecc-gen-privkey \
ksym-longterm-ecc-get-curve \
ksym-longterm-ecc-is-pubkey-valid-full \
ksym-longterm-ecc-make-pub-key \
ksym-longterm-efi \
ksym-longterm-empty-zero-page \
ksym-longterm-enable-irq \
ksym-longterm-fd-install \
ksym-longterm-fget \
ksym-longterm-filp-close \
ksym-longterm-filp-open \
ksym-longterm-find-vma \
ksym-longterm-find-vma-intersection \
ksym-longterm-finish-wait \
ksym-longterm-flush-dcache-page \
ksym-longterm-follow-pfnmap-end \
ksym-longterm-follow-pfnmap-start \
ksym-longterm-fput \
ksym-longterm-free-irq \
ksym-longterm-free-pages \
ksym-longterm-freezer-active \
ksym-longterm-freezing-slow-path \
ksym-longterm-full-name-hash \
ksym-longterm-get-dev-pagemap \
ksym-longterm-get-free-pages-noprof \
ksym-longterm-get-mem-cgroup-from-mm \
ksym-longterm-get-random-bytes \
ksym-longterm-get-task-pid \
ksym-longterm-get-unused-fd-flags \
ksym-longterm-get-user-pages-remote \
ksym-longterm-gpio-free \
ksym-longterm-gpio-request \
ksym-longterm-gpio-to-desc \
ksym-longterm-gpiod-direction-input \
ksym-longterm-gpiod-direction-output-raw \
ksym-longterm-gpiod-get-raw-value \
ksym-longterm-gpiod-set-raw-value \
ksym-longterm-gpiod-to-irq \
ksym-longterm-handle-mm-fault \
ksym-longterm-hmm-range-fault \
ksym-longterm-hrtimer-cancel \
ksym-longterm-hrtimer-setup \
ksym-longterm-hrtimer-start-range-ns \
ksym-longterm-i2c-add-adapter \
ksym-longterm-i2c-del-adapter \
ksym-longterm-icc-set-bw \
ksym-longterm-idr-get-next \
ksym-longterm-init-pid-ns \
ksym-longterm-init-wait-entry \
ksym-longterm-int-active-memcg \
ksym-longterm-iomem-resource \
ksym-longterm-iommu-get-domain-for-dev \
ksym-longterm-iommu-sva-bind-device \
ksym-longterm-iommu-sva-get-pasid \
ksym-longterm-iommu-sva-unbind-device \
ksym-longterm-iounmap \
ksym-longterm-iov-iter-kvec \
ksym-longterm-is-acpi-device-node \
ksym-longterm-is-vmalloc-addr \
ksym-longterm-iterate-fd \
ksym-longterm-jiffies \
ksym-longterm-jiffies-to-timespec64 \
ksym-longterm-jiffies-to-usecs \
ksym-longterm-kernel-read \
ksym-longterm-kernel-write \
ksym-longterm-key-type-asymmetric \
ksym-longterm-kfree \
ksym-longterm-kfree-sensitive \
ksym-longterm-kimage-voffset \
ksym-longterm-kmalloc-caches \
ksym-longterm-kmem-cache-alloc-noprof \
ksym-longterm-kmem-cache-destroy \
ksym-longterm-kmem-cache-free \
ksym-longterm-krealloc-node-align-noprof \
ksym-longterm-ksize \
ksym-longterm-kthread-create-on-node \
ksym-longterm-kthread-should-stop \
ksym-longterm-kthread-stop \
ksym-longterm-ktime-get-raw-ts64 \
ksym-longterm-ktime-get-real-ts64 \
ksym-longterm-kvasprintf \
ksym-longterm-kvfree \
ksym-longterm-logic-inb \
ksym-longterm-logic-inl \
ksym-longterm-logic-inw \
ksym-longterm-logic-outb \
ksym-longterm-logic-outl \
ksym-longterm-logic-outw \
ksym-longterm-make-device-exclusive \
ksym-longterm-memcmp \
ksym-longterm-memcpy \
ksym-longterm-memcpy-fromio \
ksym-longterm-memcpy-toio \
ksym-longterm-memmove \
ksym-longterm-memory-block-size-bytes \
ksym-longterm-memory-failure-queue \
ksym-longterm-memremap-pages \
ksym-longterm-memset \
ksym-longterm-memset-io \
ksym-longterm-memstart-addr \
ksym-longterm-memunmap-pages \
ksym-longterm-migrate-device-finalize \
ksym-longterm-migrate-device-pages \
ksym-longterm-migrate-device-range \
ksym-longterm-migrate-vma-finalize \
ksym-longterm-migrate-vma-pages \
ksym-longterm-migrate-vma-setup \
ksym-longterm-mmput \
ksym-longterm-mmu-interval-notifier-insert \
ksym-longterm-mmu-interval-notifier-remove \
ksym-longterm-mmu-interval-read-begin \
ksym-longterm-mod-node-page-state \
ksym-longterm-mod-timer \
ksym-longterm-module-layout \
ksym-longterm-module-put \
ksym-longterm-mpi-alloc \
ksym-longterm-mpi-free \
ksym-longterm-mpi-powm \
ksym-longterm-mpi-read-buffer \
ksym-longterm-mpi-read-raw-data \
ksym-longterm-msleep \
ksym-longterm-mtree-load \
ksym-longterm-mutex-is-locked \
ksym-longterm-mutex-lock \
ksym-longterm-mutex-lock-interruptible \
ksym-longterm-mutex-trylock \
ksym-longterm-mutex-unlock \
ksym-longterm-node-data \
ksym-longterm-node-states \
ksym-longterm-node-to-cpumask-map \
ksym-longterm-noop-llseek \
ksym-longterm-nr-cpu-ids \
ksym-longterm-numa-node \
ksym-longterm-of-address-to-resource \
ksym-longterm-of-device-is-available \
ksym-longterm-of-find-compatible-node \
ksym-longterm-of-find-matching-node-and-match \
ksym-longterm-of-find-node-opts-by-path \
ksym-longterm-of-find-property \
ksym-longterm-of-get-child-by-name \
ksym-longterm-of-get-named-gpio \
ksym-longterm-of-get-property \
ksym-longterm-of-node-put \
ksym-longterm-of-prop-next-u32 \
ksym-longterm-of-property-count-elems-of-size \
ksym-longterm-of-property-read-bool \
ksym-longterm-of-property-read-string \
ksym-longterm-of-property-read-u64 \
ksym-longterm-of-property-read-variable-u32-array \
ksym-longterm-offline-and-remove-memory \
ksym-longterm-on-each-cpu-cond-mask \
ksym-longterm-out-of-line-wait-on-bit-lock \
ksym-longterm-panic \
ksym-longterm-param-ops-bool \
ksym-longterm-param-ops-charp \
ksym-longterm-param-ops-int \
ksym-longterm-param-ops-uint \
ksym-longterm-param-ops-ulong \
ksym-longterm-pci-assign-unassigned-bus-resources \
ksym-longterm-pci-ats-supported \
ksym-longterm-pci-bus-type \
ksym-longterm-pci-clear-master \
ksym-longterm-pci-dev-present \
ksym-longterm-pci-dev-put \
ksym-longterm-pci-device-is-present \
ksym-longterm-pci-disable-device \
ksym-longterm-pci-disable-msi \
ksym-longterm-pci-disable-msix \
ksym-longterm-pci-enable-atomic-ops-to-root \
ksym-longterm-pci-enable-device \
ksym-longterm-pci-enable-msi \
ksym-longterm-pci-enable-msix-range \
ksym-longterm-pci-find-capability \
ksym-longterm-pci-find-host-bridge \
ksym-longterm-pci-get-class \
ksym-longterm-pci-get-domain-bus-and-slot \
ksym-longterm-pci-iomap \
ksym-longterm-pci-iounmap \
ksym-longterm-pci-read-config-byte \
ksym-longterm-pci-read-config-dword \
ksym-longterm-pci-read-config-word \
ksym-longterm-pci-rebar-get-possible-sizes \
ksym-longterm-pci-release-regions \
ksym-longterm-pci-release-resource \
ksym-longterm-pci-request-regions \
ksym-longterm-pci-resize-resource \
ksym-longterm-pci-restore-state \
ksym-longterm-pci-save-state \
ksym-longterm-pci-set-master \
ksym-longterm-pci-stop-and-remove-bus-device \
ksym-longterm-pci-unregister-driver \
ksym-longterm-pci-write-config-byte \
ksym-longterm-pci-write-config-dword \
ksym-longterm-pci-write-config-word \
ksym-longterm-pcibios-resource-to-bus \
ksym-longterm-pcie-capability-read-word \
ksym-longterm-pcie-reset-flr \
ksym-longterm-percpu-counter-add-batch \
ksym-longterm-percpu-counter-batch \
ksym-longterm-perf-trace-buf-alloc \
ksym-longterm-perf-trace-run-bpf-submit \
ksym-longterm-pfn-is-map-memory \
ksym-longterm-pid-vnr \
ksym-longterm-pin-user-pages \
ksym-longterm-pin-user-pages-remote \
ksym-longterm-platform-driver-unregister \
ksym-longterm-pm-runtime-allow \
ksym-longterm-pm-runtime-enable \
ksym-longterm-pm-runtime-forbid \
ksym-longterm-pm-runtime-set-autosuspend-delay \
ksym-longterm-pm-vt-switch-required \
ksym-longterm-pm-vt-switch-unregister \
ksym-longterm-prepare-to-wait-event \
ksym-longterm-proc-create-data \
ksym-longterm-proc-mkdir-mode \
ksym-longterm-proc-remove \
ksym-longterm-proc-symlink \
ksym-longterm-prot-ns-shared \
ksym-longterm-public-key-verify-signature \
ksym-longterm-put-pid \
ksym-longterm-put-unused-fd \
ksym-longterm-pxm-to-node \
ksym-longterm-queue-delayed-work-on \
ksym-longterm-queue-work-on \
ksym-longterm-radix-tree-delete \
ksym-longterm-radix-tree-gang-lookup \
ksym-longterm-radix-tree-insert \
ksym-longterm-radix-tree-lookup \
ksym-longterm-radix-tree-next-chunk \
ksym-longterm-random-kmalloc-seed \
ksym-longterm-rb-erase \
ksym-longterm-rb-first \
ksym-longterm-rb-insert-color \
ksym-longterm-refcount-warn-saturate \
ksym-longterm-register-acpi-notifier \
ksym-longterm-register-chrdev-region \
ksym-longterm-register-memory-notifier \
ksym-longterm-register-pm-notifier \
ksym-longterm-release-firmware \
ksym-longterm-remap-pfn-range \
ksym-longterm-remove-proc-entry \
ksym-longterm-request-firmware \
ksym-longterm-request-free-mem-region \
ksym-longterm-request-threaded-irq \
ksym-longterm-rsi-present \
ksym-longterm-schedule \
ksym-longterm-schedule-timeout \
ksym-longterm-screen-info \
ksym-longterm-seq-lseek \
ksym-longterm-seq-printf \
ksym-longterm-seq-read \
ksym-longterm-seq-read-iter \
ksym-longterm-set-cpus-allowed-ptr \
ksym-longterm-set-memory-decrypted \
ksym-longterm-set-memory-encrypted \
ksym-longterm-set-normalized-timespec64 \
ksym-longterm-set-page-dirty \
ksym-longterm-set-page-dirty-lock \
ksym-longterm-sg-alloc-table \
ksym-longterm-sg-alloc-table-from-pages-segment \
ksym-longterm-sg-free-table \
ksym-longterm-sg-init-table \
ksym-longterm-shrinker-alloc \
ksym-longterm-shrinker-free \
ksym-longterm-shrinker-register \
ksym-longterm-simple-strtoul \
ksym-longterm-single-open \
ksym-longterm-single-release \
ksym-longterm-sized-strscpy \
ksym-longterm-snprintf \
ksym-longterm-sort \
ksym-longterm-sprintf \
ksym-longterm-sscanf \
ksym-longterm-strcasecmp \
ksym-longterm-strchr \
ksym-longterm-strcmp \
ksym-longterm-strcpy \
ksym-longterm-strlcat \
ksym-longterm-strlen \
ksym-longterm-strncat \
ksym-longterm-strncmp \
ksym-longterm-strnlen \
ksym-longterm-strrchr \
ksym-longterm-strsep \
ksym-longterm-strstr \
ksym-longterm-sync-file-create \
ksym-longterm-sync-file-get-fence \
ksym-longterm-system-percpu-wq \
ksym-longterm-task-active-pid-ns \
ksym-longterm-tegra-bpmp-get \
ksym-longterm-tegra-bpmp-transfer \
ksym-longterm-timer-delete-sync \
ksym-longterm-timer-init-key \
ksym-longterm-trace-event-buffer-commit \
ksym-longterm-trace-event-buffer-reserve \
ksym-longterm-trace-event-printf \
ksym-longterm-trace-event-raw-init \
ksym-longterm-trace-event-reg \
ksym-longterm-trace-handle-return \
ksym-longterm-trace-raw-output-prep \
ksym-longterm-try-module-get \
ksym-longterm-unlock-page \
ksym-longterm-unmap-mapping-range \
ksym-longterm-unpin-user-page \
ksym-longterm-unregister-acpi-notifier \
ksym-longterm-unregister-chrdev-region \
ksym-longterm-unregister-memory-notifier \
ksym-longterm-unregister-pm-notifier \
ksym-longterm-up \
ksym-longterm-up-read \
ksym-longterm-up-write \
ksym-longterm-update-devfreq \
ksym-longterm-usleep-range-state \
ksym-longterm-validate-usercopy-range \
ksym-longterm-vfree \
ksym-longterm-vga-set-legacy-decoding \
ksym-longterm-vm-get-page-prot \
ksym-longterm-vm-insert-page \
ksym-longterm-vmalloc-noprof \
ksym-longterm-vmalloc-to-page \
ksym-longterm-vmap \
ksym-longterm-vmf-insert-mixed \
ksym-longterm-vmf-insert-pfn \
ksym-longterm-vmf-insert-pfn-prot \
ksym-longterm-vprintk \
ksym-longterm-vsnprintf \
ksym-longterm-vunmap \
ksym-longterm-vzalloc-noprof \
ksym-longterm-wait-for-completion \
ksym-longterm-wait-for-completion-interruptible \
ksym-longterm-wait-for-random-bytes \
ksym-longterm-wake-up-bit \
ksym-longterm-wake-up-process \
ksym-longterm-ww-mutex-lock \
ksym-longterm-ww-mutex-unlock \
ksym-longterm-zone-device-page-init \
perl-Bootloader \
suse-kernel-rpm-scriptlets \
update-alternatives"

inherit rpm
