SUMMARY = "Replace pk fonts in PostScript with Type 1 fonts"
DESCRIPTION = "The perl script pkfix looks for DVIPSBitmapFont comments in \
PostScript files, generated by 'not too old' dvips, and \
replaces them by type 1 versions of the fonts, if possible."
LICENSE = "LPPL-1.0"

PV = "2026.226.1.7svn26032"

RPM_NAME = "texlive-pkfix-2026.226.1.7svn26032-58.2.noarch.rpm"
RPM_HASH = "a606bfb8790c5a75feac45f4379049e72e2ddafa88b9192e1e7b3d5090715680f9a918b5a03ea25597367c695613d7e88026b98ca89b36ddfe6a4477faff240d"
REPO_ARCH = "noarch"

RPROVIDES:${PN} += "texlive-pkfix"

RDEPENDS:${PN} += "/usr/bin/perl \
/usr/bin/sh \
coreutils \
ed \
findutils \
grep \
perl-Getopt--Long \
perl-strict \
sed \
texlive \
texlive-filesystem \
texlive-kpathsea \
texlive-kpathsea-bin \
texlive-pkfix-bin \
texlive-scripts \
texlive-scripts-bin"

inherit rpm
