SUMMARY = "Libraries used internal to the OCaml Compiler"
DESCRIPTION = "OCaml is a high-level, strongly-typed, functional and object-oriented \
programming language from the ML family of languages. \
 \
This package contains libraries and signature files for developing \
applications that use Ocaml."
LICENSE = "QPL-1.0"

PV = "5.5.0"

RPM_NAME = "ocaml-compiler-libs-devel-5.5.0-2.1.aarch64.rpm"
RPM_HASH = "2d23aca5d81dfe8dbaeab4074eee0402571ed3fa7d783411f369a2e8d9cbf3a02341ab7c9668b27bd4b995595b72f01af1a66d690487aa0265685ff383789f78"

RPROVIDES:${PN} += "ocaml-Afl-instrument \
ocaml-Alias-analysis \
ocaml-Allocated-const \
ocaml-Arch \
ocaml-Arg-helper \
ocaml-Asmgen \
ocaml-Asmlibrarian \
ocaml-Asmlink \
ocaml-Asmpackager \
ocaml-Ast-helper \
ocaml-Ast-invariants \
ocaml-Ast-iterator \
ocaml-Ast-mapper \
ocaml-Asttypes \
ocaml-Attr-helper \
ocaml-Augment-specialised-args \
ocaml-Backend-var \
ocaml-Binutils \
ocaml-Branch-relaxation \
ocaml-Btype \
ocaml-Build-export-info \
ocaml-Build-path-prefix-map \
ocaml-Builtin-attributes \
ocaml-Bytegen \
ocaml-Bytelibrarian \
ocaml-Bytelink \
ocaml-Bytepackager \
ocaml-Byterntm \
ocaml-Bytesections \
ocaml-CSE \
ocaml-CSEgen \
ocaml-CamlinternalMenhirLib \
ocaml-Ccomp \
ocaml-Clambda \
ocaml-Clambda-primitives \
ocaml-Clflags \
ocaml-Closure \
ocaml-Closure-conversion \
ocaml-Closure-conversion-aux \
ocaml-Closure-element \
ocaml-Closure-id \
ocaml-Closure-middle-end \
ocaml-Closure-offsets \
ocaml-Closure-origin \
ocaml-Cmi-format \
ocaml-Cmm \
ocaml-Cmm-helpers \
ocaml-Cmm-invariants \
ocaml-Cmmgen \
ocaml-Cmmgen-state \
ocaml-Cmt-format \
ocaml-Cmt2annot \
ocaml-Coloring \
ocaml-Comballoc \
ocaml-Compenv \
ocaml-Compilation-unit \
ocaml-Compile \
ocaml-Compile-common \
ocaml-Compilenv \
ocaml-Compmisc \
ocaml-Compression \
ocaml-Config \
ocaml-Consistbl \
ocaml-Convert-primitives \
ocaml-Ctype \
ocaml-Data-types \
ocaml-Dataflow \
ocaml-Datarepr \
ocaml-Deadcode \
ocaml-Debuginfo \
ocaml-Depend \
ocaml-Diffing \
ocaml-Diffing-with-keys \
ocaml-Dll \
ocaml-Docstrings \
ocaml-Domainstate \
ocaml-Effect-analysis \
ocaml-Emit \
ocaml-Emitaux \
ocaml-Emitcode \
ocaml-Env \
ocaml-Envaux \
ocaml-Errors \
ocaml-Errortrace \
ocaml-Errortrace-report \
ocaml-Export-id \
ocaml-Export-info \
ocaml-Export-info-for-pack \
ocaml-Extract-projections \
ocaml-Find-recursive-functions \
ocaml-Flambda \
ocaml-Flambda-invariants \
ocaml-Flambda-iterators \
ocaml-Flambda-middle-end \
ocaml-Flambda-to-clambda \
ocaml-Flambda-utils \
ocaml-Format-doc \
ocaml-Freshening \
ocaml-Genprintval \
ocaml-Gprinttyp \
ocaml-Id-types \
ocaml-Ident \
ocaml-Identifiable \
ocaml-Import-approx \
ocaml-Includeclass \
ocaml-Includecore \
ocaml-Includemod \
ocaml-Includemod-errorprinter \
ocaml-Inconstant-idents \
ocaml-Initialize-symbol-to-let-symbol \
ocaml-Inline-and-simplify \
ocaml-Inline-and-simplify-aux \
ocaml-Inlining-cost \
ocaml-Inlining-decision \
ocaml-Inlining-stats \
ocaml-Inlining-stats-types \
ocaml-Inlining-transforms \
ocaml-Instruct \
ocaml-Int-replace-polymorphic-compare \
ocaml-Interf \
ocaml-Internal-variable-names \
ocaml-Interval \
ocaml-Invariant-params \
ocaml-Lambda \
ocaml-Lazy-backtrack \
ocaml-Lexer \
ocaml-Lift-code \
ocaml-Lift-constants \
ocaml-Lift-let-to-initialize-symbol \
ocaml-Linear \
ocaml-Linear-format \
ocaml-Linearize \
ocaml-Linkage-name \
ocaml-Linkdeps \
ocaml-Linscan \
ocaml-Liveness \
ocaml-Load-path \
ocaml-Local-store \
ocaml-Location \
ocaml-Longident \
ocaml-Mach \
ocaml-Main \
ocaml-Main-args \
ocaml-Maindriver \
ocaml-Makedepend \
ocaml-Matching \
ocaml-Meta \
ocaml-Misc \
ocaml-Mtype \
ocaml-Mutable-variable \
ocaml-Numbers \
ocaml-Opcodes \
ocaml-Oprint \
ocaml-Optcompile \
ocaml-Opterrors \
ocaml-Optmain \
ocaml-Optmaindriver \
ocaml-Out-type \
ocaml-Parameter \
ocaml-Parmatch \
ocaml-Parse \
ocaml-Parser \
ocaml-Pass-wrapper \
ocaml-Path \
ocaml-Patterns \
ocaml-Persistent-env \
ocaml-Polling \
ocaml-Pparse \
ocaml-Pprintast \
ocaml-Predef \
ocaml-Primitive \
ocaml-Printast \
ocaml-Printclambda \
ocaml-Printclambda-primitives \
ocaml-Printcmm \
ocaml-Printinstr \
ocaml-Printlambda \
ocaml-Printlinear \
ocaml-Printmach \
ocaml-Printpat \
ocaml-Printtyp \
ocaml-Printtyped \
ocaml-Proc \
ocaml-Profile \
ocaml-Projection \
ocaml-Rawprinttyp \
ocaml-Ref-to-variables \
ocaml-Reg \
ocaml-Reload \
ocaml-Reloadgen \
ocaml-Remove-free-vars-equal-to-args \
ocaml-Remove-unused-arguments \
ocaml-Remove-unused-closure-vars \
ocaml-Remove-unused-program-constructs \
ocaml-Runtimedef \
ocaml-Schedgen \
ocaml-Scheduling \
ocaml-Selectgen \
ocaml-Selection \
ocaml-Semantics-of-primitives \
ocaml-Set-of-closures-id \
ocaml-Set-of-closures-origin \
ocaml-Shape \
ocaml-Shape-reduce \
ocaml-Share-constants \
ocaml-Signature-group \
ocaml-Signature-matching \
ocaml-Simple-value-approx \
ocaml-Simplif \
ocaml-Simplify-boxed-integer-ops \
ocaml-Simplify-common \
ocaml-Simplify-primitives \
ocaml-Spill \
ocaml-Split \
ocaml-Stable-matching \
ocaml-Stackframe \
ocaml-Stackframegen \
ocaml-Static-exception \
ocaml-Strmatch \
ocaml-Strongly-connected-components \
ocaml-Stypes \
ocaml-Subst \
ocaml-Switch \
ocaml-Symbol \
ocaml-Symtable \
ocaml-Syntaxerr \
ocaml-Tag \
ocaml-Targetint \
ocaml-Tast-iterator \
ocaml-Tast-mapper \
ocaml-Terminfo \
ocaml-Thread-sanitizer \
ocaml-Tmc \
ocaml-Topcommon \
ocaml-Topdirs \
ocaml-Topeval \
ocaml-Tophooks \
ocaml-Toploop \
ocaml-Topmain \
ocaml-Topprinters \
ocaml-Topstart \
ocaml-Trace \
ocaml-Translattribute \
ocaml-Translclass \
ocaml-Translcore \
ocaml-Translmod \
ocaml-Translobj \
ocaml-Translprim \
ocaml-Traverse-for-exported-symbols \
ocaml-Type-immediacy \
ocaml-Typeclass \
ocaml-Typecore \
ocaml-Typedecl \
ocaml-Typedecl-immediacy \
ocaml-Typedecl-properties \
ocaml-Typedecl-separability \
ocaml-Typedecl-unboxed \
ocaml-Typedecl-variance \
ocaml-Typedtree \
ocaml-Typemod \
ocaml-Typeopt \
ocaml-Types \
ocaml-Typetexp \
ocaml-Un-anf \
ocaml-Unbox-closures \
ocaml-Unbox-free-vars-of-closures \
ocaml-Unbox-specialised-args \
ocaml-Unit-info \
ocaml-Untypeast \
ocaml-Value-rec-check \
ocaml-Value-rec-compiler \
ocaml-Var-within-closure \
ocaml-Variable \
ocaml-Warnings \
ocaml-compiler-libs-devel \
ocamlfind-compiler-libs \
ocamlfind-compiler-libs.bytecomp \
ocamlfind-compiler-libs.common \
ocamlfind-compiler-libs.native-toplevel \
ocamlfind-compiler-libs.optcomp \
ocamlfind-compiler-libs.toplevel \
ocamlx-Afl-instrument \
ocamlx-Alias-analysis \
ocamlx-Allocated-const \
ocamlx-Arch \
ocamlx-Arg-helper \
ocamlx-Asmgen \
ocamlx-Asmlibrarian \
ocamlx-Asmlink \
ocamlx-Asmpackager \
ocamlx-Ast-helper \
ocamlx-Ast-invariants \
ocamlx-Ast-iterator \
ocamlx-Ast-mapper \
ocamlx-Asttypes \
ocamlx-Attr-helper \
ocamlx-Augment-specialised-args \
ocamlx-Backend-var \
ocamlx-Binutils \
ocamlx-Branch-relaxation \
ocamlx-Btype \
ocamlx-Build-export-info \
ocamlx-Build-path-prefix-map \
ocamlx-Builtin-attributes \
ocamlx-Bytegen \
ocamlx-Bytelibrarian \
ocamlx-Bytelink \
ocamlx-Bytepackager \
ocamlx-Byterntm \
ocamlx-Bytesections \
ocamlx-CSE \
ocamlx-CSEgen \
ocamlx-CamlinternalMenhirLib \
ocamlx-Ccomp \
ocamlx-Clambda \
ocamlx-Clambda-primitives \
ocamlx-Clflags \
ocamlx-Closure \
ocamlx-Closure-conversion \
ocamlx-Closure-conversion-aux \
ocamlx-Closure-element \
ocamlx-Closure-id \
ocamlx-Closure-middle-end \
ocamlx-Closure-offsets \
ocamlx-Closure-origin \
ocamlx-Cmi-format \
ocamlx-Cmm \
ocamlx-Cmm-helpers \
ocamlx-Cmm-invariants \
ocamlx-Cmmgen \
ocamlx-Cmmgen-state \
ocamlx-Cmt-format \
ocamlx-Cmt2annot \
ocamlx-Coloring \
ocamlx-Comballoc \
ocamlx-Compenv \
ocamlx-Compilation-unit \
ocamlx-Compile \
ocamlx-Compile-common \
ocamlx-Compilenv \
ocamlx-Compmisc \
ocamlx-Compression \
ocamlx-Config \
ocamlx-Consistbl \
ocamlx-Convert-primitives \
ocamlx-Ctype \
ocamlx-Data-types \
ocamlx-Dataflow \
ocamlx-Datarepr \
ocamlx-Deadcode \
ocamlx-Debuginfo \
ocamlx-Depend \
ocamlx-Diffing \
ocamlx-Diffing-with-keys \
ocamlx-Dll \
ocamlx-Docstrings \
ocamlx-Domainstate \
ocamlx-Effect-analysis \
ocamlx-Emit \
ocamlx-Emitaux \
ocamlx-Emitcode \
ocamlx-Env \
ocamlx-Envaux \
ocamlx-Errors \
ocamlx-Errortrace \
ocamlx-Errortrace-report \
ocamlx-Export-id \
ocamlx-Export-info \
ocamlx-Export-info-for-pack \
ocamlx-Extract-projections \
ocamlx-Find-recursive-functions \
ocamlx-Flambda \
ocamlx-Flambda-invariants \
ocamlx-Flambda-iterators \
ocamlx-Flambda-middle-end \
ocamlx-Flambda-to-clambda \
ocamlx-Flambda-utils \
ocamlx-Format-doc \
ocamlx-Freshening \
ocamlx-Genprintval \
ocamlx-Gprinttyp \
ocamlx-Id-types \
ocamlx-Ident \
ocamlx-Identifiable \
ocamlx-Import-approx \
ocamlx-Includeclass \
ocamlx-Includecore \
ocamlx-Includemod \
ocamlx-Includemod-errorprinter \
ocamlx-Inconstant-idents \
ocamlx-Initialize-symbol-to-let-symbol \
ocamlx-Inline-and-simplify \
ocamlx-Inline-and-simplify-aux \
ocamlx-Inlining-cost \
ocamlx-Inlining-decision \
ocamlx-Inlining-stats \
ocamlx-Inlining-stats-types \
ocamlx-Inlining-transforms \
ocamlx-Instruct \
ocamlx-Int-replace-polymorphic-compare \
ocamlx-Interf \
ocamlx-Internal-variable-names \
ocamlx-Interval \
ocamlx-Invariant-params \
ocamlx-Lambda \
ocamlx-Lazy-backtrack \
ocamlx-Lexer \
ocamlx-Lift-code \
ocamlx-Lift-constants \
ocamlx-Lift-let-to-initialize-symbol \
ocamlx-Linear \
ocamlx-Linear-format \
ocamlx-Linearize \
ocamlx-Linkage-name \
ocamlx-Linkdeps \
ocamlx-Linscan \
ocamlx-Liveness \
ocamlx-Load-path \
ocamlx-Local-store \
ocamlx-Location \
ocamlx-Longident \
ocamlx-Mach \
ocamlx-Main \
ocamlx-Main-args \
ocamlx-Maindriver \
ocamlx-Makedepend \
ocamlx-Matching \
ocamlx-Meta \
ocamlx-Misc \
ocamlx-Mtype \
ocamlx-Mutable-variable \
ocamlx-Numbers \
ocamlx-Opcodes \
ocamlx-Oprint \
ocamlx-Optcompile \
ocamlx-Opterrors \
ocamlx-Optmain \
ocamlx-Optmaindriver \
ocamlx-Out-type \
ocamlx-Parameter \
ocamlx-Parmatch \
ocamlx-Parse \
ocamlx-Parser \
ocamlx-Pass-wrapper \
ocamlx-Path \
ocamlx-Patterns \
ocamlx-Persistent-env \
ocamlx-Polling \
ocamlx-Pparse \
ocamlx-Pprintast \
ocamlx-Predef \
ocamlx-Primitive \
ocamlx-Printast \
ocamlx-Printclambda \
ocamlx-Printclambda-primitives \
ocamlx-Printcmm \
ocamlx-Printinstr \
ocamlx-Printlambda \
ocamlx-Printlinear \
ocamlx-Printmach \
ocamlx-Printpat \
ocamlx-Printtyp \
ocamlx-Printtyped \
ocamlx-Proc \
ocamlx-Profile \
ocamlx-Projection \
ocamlx-Rawprinttyp \
ocamlx-Ref-to-variables \
ocamlx-Reg \
ocamlx-Reload \
ocamlx-Reloadgen \
ocamlx-Remove-free-vars-equal-to-args \
ocamlx-Remove-unused-arguments \
ocamlx-Remove-unused-closure-vars \
ocamlx-Remove-unused-program-constructs \
ocamlx-Runtimedef \
ocamlx-Schedgen \
ocamlx-Scheduling \
ocamlx-Selectgen \
ocamlx-Selection \
ocamlx-Semantics-of-primitives \
ocamlx-Set-of-closures-id \
ocamlx-Set-of-closures-origin \
ocamlx-Shape \
ocamlx-Shape-reduce \
ocamlx-Share-constants \
ocamlx-Signature-group \
ocamlx-Signature-matching \
ocamlx-Simple-value-approx \
ocamlx-Simplif \
ocamlx-Simplify-boxed-integer-ops \
ocamlx-Simplify-common \
ocamlx-Simplify-primitives \
ocamlx-Spill \
ocamlx-Split \
ocamlx-Stable-matching \
ocamlx-Stackframe \
ocamlx-Stackframegen \
ocamlx-Static-exception \
ocamlx-Strmatch \
ocamlx-Strongly-connected-components \
ocamlx-Stypes \
ocamlx-Subst \
ocamlx-Switch \
ocamlx-Symbol \
ocamlx-Symtable \
ocamlx-Syntaxerr \
ocamlx-Tag \
ocamlx-Targetint \
ocamlx-Tast-iterator \
ocamlx-Tast-mapper \
ocamlx-Terminfo \
ocamlx-Thread-sanitizer \
ocamlx-Tmc \
ocamlx-Topcommon \
ocamlx-Topdirs \
ocamlx-Topeval \
ocamlx-Tophooks \
ocamlx-Toploop \
ocamlx-Topmain \
ocamlx-Topprinters \
ocamlx-Topstart \
ocamlx-Trace \
ocamlx-Translattribute \
ocamlx-Translclass \
ocamlx-Translcore \
ocamlx-Translmod \
ocamlx-Translobj \
ocamlx-Translprim \
ocamlx-Traverse-for-exported-symbols \
ocamlx-Type-immediacy \
ocamlx-Typeclass \
ocamlx-Typecore \
ocamlx-Typedecl \
ocamlx-Typedecl-immediacy \
ocamlx-Typedecl-properties \
ocamlx-Typedecl-separability \
ocamlx-Typedecl-unboxed \
ocamlx-Typedecl-variance \
ocamlx-Typedtree \
ocamlx-Typemod \
ocamlx-Typeopt \
ocamlx-Types \
ocamlx-Typetexp \
ocamlx-Un-anf \
ocamlx-Unbox-closures \
ocamlx-Unbox-free-vars-of-closures \
ocamlx-Unbox-specialised-args \
ocamlx-Unit-info \
ocamlx-Untypeast \
ocamlx-Value-rec-check \
ocamlx-Value-rec-compiler \
ocamlx-Var-within-closure \
ocamlx-Variable \
ocamlx-Warnings"

RDEPENDS:${PN} += "ocaml-Annot \
ocaml-Backend-intf \
ocaml-Branch-relaxation-intf \
ocaml-CamlinternalFormat \
ocaml-CamlinternalFormatBasics \
ocaml-CamlinternalLazy \
ocaml-CamlinternalOO \
ocaml-Cmo-format \
ocaml-Cmx-format \
ocaml-Cmxs-format \
ocaml-Dynlink \
ocaml-Emitenv \
ocaml-Inlining-decision-intf \
ocaml-Outcometree \
ocaml-Parsetree \
ocaml-Simplify-boxed-integer-ops-intf \
ocaml-Stdlib \
ocaml-Stdlib--Arg \
ocaml-Stdlib--Array \
ocaml-Stdlib--Bigarray \
ocaml-Stdlib--Bool \
ocaml-Stdlib--Buffer \
ocaml-Stdlib--Bytes \
ocaml-Stdlib--Char \
ocaml-Stdlib--Complex \
ocaml-Stdlib--Digest \
ocaml-Stdlib--Domain \
ocaml-Stdlib--Either \
ocaml-Stdlib--Filename \
ocaml-Stdlib--Float \
ocaml-Stdlib--Format \
ocaml-Stdlib--Fun \
ocaml-Stdlib--Gc \
ocaml-Stdlib--Hashtbl \
ocaml-Stdlib--In-channel \
ocaml-Stdlib--Int \
ocaml-Stdlib--Int32 \
ocaml-Stdlib--Int64 \
ocaml-Stdlib--Lazy \
ocaml-Stdlib--Lexing \
ocaml-Stdlib--List \
ocaml-Stdlib--Map \
ocaml-Stdlib--Marshal \
ocaml-Stdlib--Nativeint \
ocaml-Stdlib--Obj \
ocaml-Stdlib--Option \
ocaml-Stdlib--Out-channel \
ocaml-Stdlib--Pair \
ocaml-Stdlib--Parsing \
ocaml-Stdlib--Printexc \
ocaml-Stdlib--Printf \
ocaml-Stdlib--Queue \
ocaml-Stdlib--Random \
ocaml-Stdlib--Result \
ocaml-Stdlib--Scanf \
ocaml-Stdlib--Seq \
ocaml-Stdlib--Set \
ocaml-Stdlib--Stack \
ocaml-Stdlib--String \
ocaml-Stdlib--StringLabels \
ocaml-Stdlib--Sys \
ocaml-Stdlib--Uchar \
ocaml-Value-rec-types \
ocaml-compiler-libs \
ocamlfind-compiler-libs \
ocamlfind-compiler-libs.bytecomp \
ocamlfind-compiler-libs.common \
ocamlfind-compiler-libs.optcomp \
ocamlfind-dynlink \
ocamlx-CamlinternalFormat \
ocamlx-CamlinternalLazy \
ocamlx-CamlinternalOO \
ocamlx-Dynlink \
ocamlx-Stdlib \
ocamlx-Stdlib--Arg \
ocamlx-Stdlib--Array \
ocamlx-Stdlib--Bigarray \
ocamlx-Stdlib--Bool \
ocamlx-Stdlib--Buffer \
ocamlx-Stdlib--Bytes \
ocamlx-Stdlib--Char \
ocamlx-Stdlib--Digest \
ocamlx-Stdlib--Filename \
ocamlx-Stdlib--Float \
ocamlx-Stdlib--Format \
ocamlx-Stdlib--Fun \
ocamlx-Stdlib--Gc \
ocamlx-Stdlib--Hashtbl \
ocamlx-Stdlib--In-channel \
ocamlx-Stdlib--Int \
ocamlx-Stdlib--Int32 \
ocamlx-Stdlib--Int64 \
ocamlx-Stdlib--Lazy \
ocamlx-Stdlib--Lexing \
ocamlx-Stdlib--List \
ocamlx-Stdlib--Map \
ocamlx-Stdlib--Marshal \
ocamlx-Stdlib--Nativeint \
ocamlx-Stdlib--Obj \
ocamlx-Stdlib--Option \
ocamlx-Stdlib--Out-channel \
ocamlx-Stdlib--Pair \
ocamlx-Stdlib--Parsing \
ocamlx-Stdlib--Printexc \
ocamlx-Stdlib--Printf \
ocamlx-Stdlib--Queue \
ocamlx-Stdlib--Random \
ocamlx-Stdlib--Result \
ocamlx-Stdlib--Scanf \
ocamlx-Stdlib--Seq \
ocamlx-Stdlib--Set \
ocamlx-Stdlib--Stack \
ocamlx-Stdlib--String \
ocamlx-Stdlib--StringLabels \
ocamlx-Stdlib--Sys \
ocamlx-Stdlib--Uchar"

inherit rpm
