SUMMARY = "MFB Oldstyle serif fonts"
DESCRIPTION = "Oldstyle is a serif font family designed for body text. This \
typeface was originally designed by Morris Fuller Benton and \
released by American Type Founders in 1909 as Century Oldstyle. \
The family contains three fonts: regular, italic and bold. \
(Currently, no bold italic font is provided.) Superior and \
inferior figures are available for all fonts in the family. \
Small capitals and old-style figures are available only for the \
regular font."
LICENSE = "LPPL-1.0"

PV = "2026.226.1.0svn77682"

RPM_NAME = "texlive-mfb-oldstyle-2026.226.1.0svn77682-61.2.noarch.rpm"
RPM_HASH = "32a63cb58403cfd113a0316f47407c504d6f11869f129d7c63a55d5acac2ab58bcb89b5e9b4fafcbec73b41e806e68e5c651eca4329fa72ef83315c245c81aa6"
REPO_ARCH = "noarch"

RPROVIDES:${PN} += "tex-LY1MFBOldstyle-Dnom.fd \
tex-LY1MFBOldstyle-Inf.fd \
tex-LY1MFBOldstyle-LF.fd \
tex-LY1MFBOldstyle-Numr.fd \
tex-LY1MFBOldstyle-OsF.fd \
tex-LY1MFBOldstyle-Sup.fd \
tex-LY1MFBOldstyle-TLF.fd \
tex-LY1MFBOldstyle-TOsF.fd \
tex-MFBOldstyle-Bold-dnom-ly1--base.tfm \
tex-MFBOldstyle-Bold-dnom-ly1.tfm \
tex-MFBOldstyle-Bold-dnom-ly1.vf \
tex-MFBOldstyle-Bold-dnom-ot1.tfm \
tex-MFBOldstyle-Bold-dnom-t1--base.tfm \
tex-MFBOldstyle-Bold-dnom-t1.tfm \
tex-MFBOldstyle-Bold-dnom-t1.vf \
tex-MFBOldstyle-Bold-dnom-t5--base.tfm \
tex-MFBOldstyle-Bold-dnom-t5.tfm \
tex-MFBOldstyle-Bold-dnom-t5.vf \
tex-MFBOldstyle-Bold-inf-ly1--base.tfm \
tex-MFBOldstyle-Bold-inf-ly1.tfm \
tex-MFBOldstyle-Bold-inf-ly1.vf \
tex-MFBOldstyle-Bold-inf-ot1.tfm \
tex-MFBOldstyle-Bold-inf-t1--base.tfm \
tex-MFBOldstyle-Bold-inf-t1.tfm \
tex-MFBOldstyle-Bold-inf-t1.vf \
tex-MFBOldstyle-Bold-inf-t5--base.tfm \
tex-MFBOldstyle-Bold-inf-t5.tfm \
tex-MFBOldstyle-Bold-inf-t5.vf \
tex-MFBOldstyle-Bold-lf-ly1--base.tfm \
tex-MFBOldstyle-Bold-lf-ly1.tfm \
tex-MFBOldstyle-Bold-lf-ly1.vf \
tex-MFBOldstyle-Bold-lf-ot1.tfm \
tex-MFBOldstyle-Bold-lf-t1--base.tfm \
tex-MFBOldstyle-Bold-lf-t1.tfm \
tex-MFBOldstyle-Bold-lf-t1.vf \
tex-MFBOldstyle-Bold-lf-t5--base.tfm \
tex-MFBOldstyle-Bold-lf-t5.tfm \
tex-MFBOldstyle-Bold-lf-t5.vf \
tex-MFBOldstyle-Bold-lf-ts1--base.tfm \
tex-MFBOldstyle-Bold-lf-ts1.tfm \
tex-MFBOldstyle-Bold-lf-ts1.vf \
tex-MFBOldstyle-Bold-numr-ly1--base.tfm \
tex-MFBOldstyle-Bold-numr-ly1.tfm \
tex-MFBOldstyle-Bold-numr-ly1.vf \
tex-MFBOldstyle-Bold-numr-ot1.tfm \
tex-MFBOldstyle-Bold-numr-t1--base.tfm \
tex-MFBOldstyle-Bold-numr-t1.tfm \
tex-MFBOldstyle-Bold-numr-t1.vf \
tex-MFBOldstyle-Bold-numr-t5--base.tfm \
tex-MFBOldstyle-Bold-numr-t5.tfm \
tex-MFBOldstyle-Bold-numr-t5.vf \
tex-MFBOldstyle-Bold-sup-ly1--base.tfm \
tex-MFBOldstyle-Bold-sup-ly1.tfm \
tex-MFBOldstyle-Bold-sup-ly1.vf \
tex-MFBOldstyle-Bold-sup-ot1.tfm \
tex-MFBOldstyle-Bold-sup-t1--base.tfm \
tex-MFBOldstyle-Bold-sup-t1.tfm \
tex-MFBOldstyle-Bold-sup-t1.vf \
tex-MFBOldstyle-Bold-sup-t5--base.tfm \
tex-MFBOldstyle-Bold-sup-t5.tfm \
tex-MFBOldstyle-Bold-sup-t5.vf \
tex-MFBOldstyle-Bold-tlf-ly1--base.tfm \
tex-MFBOldstyle-Bold-tlf-ly1.tfm \
tex-MFBOldstyle-Bold-tlf-ly1.vf \
tex-MFBOldstyle-Bold-tlf-ot1.tfm \
tex-MFBOldstyle-Bold-tlf-t1--base.tfm \
tex-MFBOldstyle-Bold-tlf-t1.tfm \
tex-MFBOldstyle-Bold-tlf-t1.vf \
tex-MFBOldstyle-Bold-tlf-t5--base.tfm \
tex-MFBOldstyle-Bold-tlf-t5.tfm \
tex-MFBOldstyle-Bold-tlf-t5.vf \
tex-MFBOldstyle-Bold-tlf-ts1--base.tfm \
tex-MFBOldstyle-Bold-tlf-ts1.tfm \
tex-MFBOldstyle-Bold-tlf-ts1.vf \
tex-MFBOldstyle-Italic-dnom-ly1--base.tfm \
tex-MFBOldstyle-Italic-dnom-ly1.tfm \
tex-MFBOldstyle-Italic-dnom-ly1.vf \
tex-MFBOldstyle-Italic-dnom-ot1.tfm \
tex-MFBOldstyle-Italic-dnom-t1--base.tfm \
tex-MFBOldstyle-Italic-dnom-t1.tfm \
tex-MFBOldstyle-Italic-dnom-t1.vf \
tex-MFBOldstyle-Italic-dnom-t5--base.tfm \
tex-MFBOldstyle-Italic-dnom-t5.tfm \
tex-MFBOldstyle-Italic-dnom-t5.vf \
tex-MFBOldstyle-Italic-inf-ly1--base.tfm \
tex-MFBOldstyle-Italic-inf-ly1.tfm \
tex-MFBOldstyle-Italic-inf-ly1.vf \
tex-MFBOldstyle-Italic-inf-ot1.tfm \
tex-MFBOldstyle-Italic-inf-t1--base.tfm \
tex-MFBOldstyle-Italic-inf-t1.tfm \
tex-MFBOldstyle-Italic-inf-t1.vf \
tex-MFBOldstyle-Italic-inf-t5--base.tfm \
tex-MFBOldstyle-Italic-inf-t5.tfm \
tex-MFBOldstyle-Italic-inf-t5.vf \
tex-MFBOldstyle-Italic-lf-ly1--base.tfm \
tex-MFBOldstyle-Italic-lf-ly1.tfm \
tex-MFBOldstyle-Italic-lf-ly1.vf \
tex-MFBOldstyle-Italic-lf-ot1.tfm \
tex-MFBOldstyle-Italic-lf-t1--base.tfm \
tex-MFBOldstyle-Italic-lf-t1.tfm \
tex-MFBOldstyle-Italic-lf-t1.vf \
tex-MFBOldstyle-Italic-lf-t5--base.tfm \
tex-MFBOldstyle-Italic-lf-t5.tfm \
tex-MFBOldstyle-Italic-lf-t5.vf \
tex-MFBOldstyle-Italic-lf-ts1--base.tfm \
tex-MFBOldstyle-Italic-lf-ts1.tfm \
tex-MFBOldstyle-Italic-lf-ts1.vf \
tex-MFBOldstyle-Italic-numr-ly1--base.tfm \
tex-MFBOldstyle-Italic-numr-ly1.tfm \
tex-MFBOldstyle-Italic-numr-ly1.vf \
tex-MFBOldstyle-Italic-numr-ot1.tfm \
tex-MFBOldstyle-Italic-numr-t1--base.tfm \
tex-MFBOldstyle-Italic-numr-t1.tfm \
tex-MFBOldstyle-Italic-numr-t1.vf \
tex-MFBOldstyle-Italic-numr-t5--base.tfm \
tex-MFBOldstyle-Italic-numr-t5.tfm \
tex-MFBOldstyle-Italic-numr-t5.vf \
tex-MFBOldstyle-Italic-sup-ly1--base.tfm \
tex-MFBOldstyle-Italic-sup-ly1.tfm \
tex-MFBOldstyle-Italic-sup-ly1.vf \
tex-MFBOldstyle-Italic-sup-ot1.tfm \
tex-MFBOldstyle-Italic-sup-t1--base.tfm \
tex-MFBOldstyle-Italic-sup-t1.tfm \
tex-MFBOldstyle-Italic-sup-t1.vf \
tex-MFBOldstyle-Italic-sup-t5--base.tfm \
tex-MFBOldstyle-Italic-sup-t5.tfm \
tex-MFBOldstyle-Italic-sup-t5.vf \
tex-MFBOldstyle-Italic-tlf-ly1--base.tfm \
tex-MFBOldstyle-Italic-tlf-ly1.tfm \
tex-MFBOldstyle-Italic-tlf-ly1.vf \
tex-MFBOldstyle-Italic-tlf-ot1.tfm \
tex-MFBOldstyle-Italic-tlf-t1--base.tfm \
tex-MFBOldstyle-Italic-tlf-t1.tfm \
tex-MFBOldstyle-Italic-tlf-t1.vf \
tex-MFBOldstyle-Italic-tlf-t5--base.tfm \
tex-MFBOldstyle-Italic-tlf-t5.tfm \
tex-MFBOldstyle-Italic-tlf-t5.vf \
tex-MFBOldstyle-Italic-tlf-ts1--base.tfm \
tex-MFBOldstyle-Italic-tlf-ts1.tfm \
tex-MFBOldstyle-Italic-tlf-ts1.vf \
tex-MFBOldstyle-Regular-dnom-ly1--base.tfm \
tex-MFBOldstyle-Regular-dnom-ly1.tfm \
tex-MFBOldstyle-Regular-dnom-ly1.vf \
tex-MFBOldstyle-Regular-dnom-ot1.tfm \
tex-MFBOldstyle-Regular-dnom-t1--base.tfm \
tex-MFBOldstyle-Regular-dnom-t1.tfm \
tex-MFBOldstyle-Regular-dnom-t1.vf \
tex-MFBOldstyle-Regular-dnom-t5--base.tfm \
tex-MFBOldstyle-Regular-dnom-t5.tfm \
tex-MFBOldstyle-Regular-dnom-t5.vf \
tex-MFBOldstyle-Regular-inf-ly1--base.tfm \
tex-MFBOldstyle-Regular-inf-ly1.tfm \
tex-MFBOldstyle-Regular-inf-ly1.vf \
tex-MFBOldstyle-Regular-inf-ot1.tfm \
tex-MFBOldstyle-Regular-inf-t1--base.tfm \
tex-MFBOldstyle-Regular-inf-t1.tfm \
tex-MFBOldstyle-Regular-inf-t1.vf \
tex-MFBOldstyle-Regular-inf-t5--base.tfm \
tex-MFBOldstyle-Regular-inf-t5.tfm \
tex-MFBOldstyle-Regular-inf-t5.vf \
tex-MFBOldstyle-Regular-lf-ly1--base.tfm \
tex-MFBOldstyle-Regular-lf-ly1.tfm \
tex-MFBOldstyle-Regular-lf-ly1.vf \
tex-MFBOldstyle-Regular-lf-ot1.tfm \
tex-MFBOldstyle-Regular-lf-sc-ly1--base.tfm \
tex-MFBOldstyle-Regular-lf-sc-ly1.tfm \
tex-MFBOldstyle-Regular-lf-sc-ly1.vf \
tex-MFBOldstyle-Regular-lf-sc-ot1--base.tfm \
tex-MFBOldstyle-Regular-lf-sc-ot1.tfm \
tex-MFBOldstyle-Regular-lf-sc-ot1.vf \
tex-MFBOldstyle-Regular-lf-sc-t1--base.tfm \
tex-MFBOldstyle-Regular-lf-sc-t1.tfm \
tex-MFBOldstyle-Regular-lf-sc-t1.vf \
tex-MFBOldstyle-Regular-lf-sc-t5--base.tfm \
tex-MFBOldstyle-Regular-lf-sc-t5.tfm \
tex-MFBOldstyle-Regular-lf-sc-t5.vf \
tex-MFBOldstyle-Regular-lf-t1--base.tfm \
tex-MFBOldstyle-Regular-lf-t1.tfm \
tex-MFBOldstyle-Regular-lf-t1.vf \
tex-MFBOldstyle-Regular-lf-t5--base.tfm \
tex-MFBOldstyle-Regular-lf-t5.tfm \
tex-MFBOldstyle-Regular-lf-t5.vf \
tex-MFBOldstyle-Regular-lf-ts1--base.tfm \
tex-MFBOldstyle-Regular-lf-ts1.tfm \
tex-MFBOldstyle-Regular-lf-ts1.vf \
tex-MFBOldstyle-Regular-numr-ly1--base.tfm \
tex-MFBOldstyle-Regular-numr-ly1.tfm \
tex-MFBOldstyle-Regular-numr-ly1.vf \
tex-MFBOldstyle-Regular-numr-ot1.tfm \
tex-MFBOldstyle-Regular-numr-t1--base.tfm \
tex-MFBOldstyle-Regular-numr-t1.tfm \
tex-MFBOldstyle-Regular-numr-t1.vf \
tex-MFBOldstyle-Regular-numr-t5--base.tfm \
tex-MFBOldstyle-Regular-numr-t5.tfm \
tex-MFBOldstyle-Regular-numr-t5.vf \
tex-MFBOldstyle-Regular-osf-ly1--base.tfm \
tex-MFBOldstyle-Regular-osf-ly1.tfm \
tex-MFBOldstyle-Regular-osf-ly1.vf \
tex-MFBOldstyle-Regular-osf-ot1.tfm \
tex-MFBOldstyle-Regular-osf-sc-ly1--base.tfm \
tex-MFBOldstyle-Regular-osf-sc-ly1.tfm \
tex-MFBOldstyle-Regular-osf-sc-ly1.vf \
tex-MFBOldstyle-Regular-osf-sc-ot1--base.tfm \
tex-MFBOldstyle-Regular-osf-sc-ot1.tfm \
tex-MFBOldstyle-Regular-osf-sc-ot1.vf \
tex-MFBOldstyle-Regular-osf-sc-t1--base.tfm \
tex-MFBOldstyle-Regular-osf-sc-t1.tfm \
tex-MFBOldstyle-Regular-osf-sc-t1.vf \
tex-MFBOldstyle-Regular-osf-sc-t5--base.tfm \
tex-MFBOldstyle-Regular-osf-sc-t5.tfm \
tex-MFBOldstyle-Regular-osf-sc-t5.vf \
tex-MFBOldstyle-Regular-osf-t1--base.tfm \
tex-MFBOldstyle-Regular-osf-t1.tfm \
tex-MFBOldstyle-Regular-osf-t1.vf \
tex-MFBOldstyle-Regular-osf-t5--base.tfm \
tex-MFBOldstyle-Regular-osf-t5.tfm \
tex-MFBOldstyle-Regular-osf-t5.vf \
tex-MFBOldstyle-Regular-osf-ts1--base.tfm \
tex-MFBOldstyle-Regular-osf-ts1.tfm \
tex-MFBOldstyle-Regular-osf-ts1.vf \
tex-MFBOldstyle-Regular-sup-ly1--base.tfm \
tex-MFBOldstyle-Regular-sup-ly1.tfm \
tex-MFBOldstyle-Regular-sup-ly1.vf \
tex-MFBOldstyle-Regular-sup-ot1.tfm \
tex-MFBOldstyle-Regular-sup-t1--base.tfm \
tex-MFBOldstyle-Regular-sup-t1.tfm \
tex-MFBOldstyle-Regular-sup-t1.vf \
tex-MFBOldstyle-Regular-sup-t5--base.tfm \
tex-MFBOldstyle-Regular-sup-t5.tfm \
tex-MFBOldstyle-Regular-sup-t5.vf \
tex-MFBOldstyle-Regular-tlf-ly1--base.tfm \
tex-MFBOldstyle-Regular-tlf-ly1.tfm \
tex-MFBOldstyle-Regular-tlf-ly1.vf \
tex-MFBOldstyle-Regular-tlf-ot1.tfm \
tex-MFBOldstyle-Regular-tlf-sc-ly1--base.tfm \
tex-MFBOldstyle-Regular-tlf-sc-ly1.tfm \
tex-MFBOldstyle-Regular-tlf-sc-ly1.vf \
tex-MFBOldstyle-Regular-tlf-sc-ot1--base.tfm \
tex-MFBOldstyle-Regular-tlf-sc-ot1.tfm \
tex-MFBOldstyle-Regular-tlf-sc-ot1.vf \
tex-MFBOldstyle-Regular-tlf-sc-t1--base.tfm \
tex-MFBOldstyle-Regular-tlf-sc-t1.tfm \
tex-MFBOldstyle-Regular-tlf-sc-t1.vf \
tex-MFBOldstyle-Regular-tlf-sc-t5--base.tfm \
tex-MFBOldstyle-Regular-tlf-sc-t5.tfm \
tex-MFBOldstyle-Regular-tlf-sc-t5.vf \
tex-MFBOldstyle-Regular-tlf-t1--base.tfm \
tex-MFBOldstyle-Regular-tlf-t1.tfm \
tex-MFBOldstyle-Regular-tlf-t1.vf \
tex-MFBOldstyle-Regular-tlf-t5--base.tfm \
tex-MFBOldstyle-Regular-tlf-t5.tfm \
tex-MFBOldstyle-Regular-tlf-t5.vf \
tex-MFBOldstyle-Regular-tlf-ts1--base.tfm \
tex-MFBOldstyle-Regular-tlf-ts1.tfm \
tex-MFBOldstyle-Regular-tlf-ts1.vf \
tex-MFBOldstyle-Regular-tosf-ly1--base.tfm \
tex-MFBOldstyle-Regular-tosf-ly1.tfm \
tex-MFBOldstyle-Regular-tosf-ly1.vf \
tex-MFBOldstyle-Regular-tosf-ot1.tfm \
tex-MFBOldstyle-Regular-tosf-sc-ly1--base.tfm \
tex-MFBOldstyle-Regular-tosf-sc-ly1.tfm \
tex-MFBOldstyle-Regular-tosf-sc-ly1.vf \
tex-MFBOldstyle-Regular-tosf-sc-ot1--base.tfm \
tex-MFBOldstyle-Regular-tosf-sc-ot1.tfm \
tex-MFBOldstyle-Regular-tosf-sc-ot1.vf \
tex-MFBOldstyle-Regular-tosf-sc-t1--base.tfm \
tex-MFBOldstyle-Regular-tosf-sc-t1.tfm \
tex-MFBOldstyle-Regular-tosf-sc-t1.vf \
tex-MFBOldstyle-Regular-tosf-sc-t5--base.tfm \
tex-MFBOldstyle-Regular-tosf-sc-t5.tfm \
tex-MFBOldstyle-Regular-tosf-sc-t5.vf \
tex-MFBOldstyle-Regular-tosf-t1--base.tfm \
tex-MFBOldstyle-Regular-tosf-t1.tfm \
tex-MFBOldstyle-Regular-tosf-t1.vf \
tex-MFBOldstyle-Regular-tosf-t5--base.tfm \
tex-MFBOldstyle-Regular-tosf-t5.tfm \
tex-MFBOldstyle-Regular-tosf-t5.vf \
tex-MFBOldstyle-Regular-tosf-ts1--base.tfm \
tex-MFBOldstyle-Regular-tosf-ts1.tfm \
tex-MFBOldstyle-Regular-tosf-ts1.vf \
tex-MFBOldstyle.map \
tex-OT1MFBOldstyle-Dnom.fd \
tex-OT1MFBOldstyle-Inf.fd \
tex-OT1MFBOldstyle-LF.fd \
tex-OT1MFBOldstyle-Numr.fd \
tex-OT1MFBOldstyle-OsF.fd \
tex-OT1MFBOldstyle-Sup.fd \
tex-OT1MFBOldstyle-TLF.fd \
tex-OT1MFBOldstyle-TOsF.fd \
tex-T1MFBOldstyle-Dnom.fd \
tex-T1MFBOldstyle-Inf.fd \
tex-T1MFBOldstyle-LF.fd \
tex-T1MFBOldstyle-Numr.fd \
tex-T1MFBOldstyle-OsF.fd \
tex-T1MFBOldstyle-Sup.fd \
tex-T1MFBOldstyle-TLF.fd \
tex-T1MFBOldstyle-TOsF.fd \
tex-T5MFBOldstyle-Dnom.fd \
tex-T5MFBOldstyle-Inf.fd \
tex-T5MFBOldstyle-LF.fd \
tex-T5MFBOldstyle-Numr.fd \
tex-T5MFBOldstyle-OsF.fd \
tex-T5MFBOldstyle-Sup.fd \
tex-T5MFBOldstyle-TLF.fd \
tex-T5MFBOldstyle-TOsF.fd \
tex-TS1MFBOldstyle-LF.fd \
tex-TS1MFBOldstyle-OsF.fd \
tex-TS1MFBOldstyle-TLF.fd \
tex-TS1MFBOldstyle-TOsF.fd \
tex-a-2k4lec.enc \
tex-a-2r5ytu.enc \
tex-a-5lrov3.enc \
tex-a-6mghgo.enc \
tex-a-73nks5.enc \
tex-a-777sfz.enc \
tex-a-7nlkbe.enc \
tex-a-7q6l4s.enc \
tex-a-ahcimn.enc \
tex-a-bgdhbr.enc \
tex-a-cgi3xl.enc \
tex-a-cwrjrk.enc \
tex-a-e5y2zy.enc \
tex-a-fy4cgk.enc \
tex-a-hi6bgi.enc \
tex-a-ikcbof.enc \
tex-a-in623c.enc \
tex-a-jaulpu.enc \
tex-a-kod5rh.enc \
tex-a-kosxnn.enc \
tex-a-nduqlz.enc \
tex-a-nrcrlb.enc \
tex-a-oyw33c.enc \
tex-a-q4fonx.enc \
tex-a-qmdrba.enc \
tex-a-radqz3.enc \
tex-a-rxfd27.enc \
tex-a-s7hq75.enc \
tex-a-sbbrr6.enc \
tex-a-traljt.enc \
tex-a-uyp43f.enc \
tex-a-wvbwpg.enc \
tex-a-x5sf3h.enc \
tex-a-xkajg4.enc \
tex-a-xqrvjh.enc \
tex-a-xx37di.enc \
tex-a-y2ngde.enc \
tex-a-y57hi6.enc \
tex-a-ybcvk5.enc \
tex-a-yjlipp.enc \
tex-a-ztec7x.enc \
tex-mfb-oldstyle.sty \
texlive-mfb-oldstyle"

RDEPENDS:${PN} += "/usr/bin/sh \
coreutils \
ed \
findutils \
grep \
sed \
tex-fontaxes.sty \
tex-fontenc.sty \
tex-ifthen.sty \
tex-mweights.sty \
tex-textcomp.sty \
tex-updmap.cfg \
tex-xkeyval.sty \
texlive \
texlive-filesystem \
texlive-kpathsea \
texlive-kpathsea-bin \
texlive-mfb-oldstyle-fonts \
texlive-scripts \
texlive-scripts-bin"

inherit rpm
