SUMMARY = "Menu for quickly navigating places in the system"
DESCRIPTION = "Menu for quickly navigating places in the system."
LICENSE = "GPL-3.0-only"

PV = "0.1.0+git20240607.a341006"

RPM_NAME = "cosmic-ext-applet-places-status-indicator-0.1.0+git20240607.a341006-1.14.aarch64.rpm"
RPM_HASH = "fd022752e67bb2743ee32cbfadf64c4e87b2726642664d7557aaf83e85ad81b4ca9b14bd6601b64b91127280295cf981d568b8ec766363df40af0aebf9649c1d"

RPROVIDES:${PN} += "bundled-rust-crate-accesskit \
bundled-rust-crate-accesskit-consumer \
bundled-rust-crate-accesskit-unix \
bundled-rust-crate-adler \
bundled-rust-crate-ahash \
bundled-rust-crate-aho-corasick \
bundled-rust-crate-aliasable \
bundled-rust-crate-allocator-api2 \
bundled-rust-crate-almost \
bundled-rust-crate-anyhow \
bundled-rust-crate-apply \
bundled-rust-crate-approx \
bundled-rust-crate-arc-swap \
bundled-rust-crate-arrayref \
bundled-rust-crate-arrayvec \
bundled-rust-crate-as-raw-xcb-connection \
bundled-rust-crate-ash \
bundled-rust-crate-ashpd \
bundled-rust-crate-async-broadcast \
bundled-rust-crate-async-channel \
bundled-rust-crate-async-executor \
bundled-rust-crate-async-fs \
bundled-rust-crate-async-io \
bundled-rust-crate-async-lock \
bundled-rust-crate-async-net \
bundled-rust-crate-async-recursion \
bundled-rust-crate-async-task \
bundled-rust-crate-async-trait \
bundled-rust-crate-atomic-waker \
bundled-rust-crate-atomicwrites \
bundled-rust-crate-atspi \
bundled-rust-crate-atspi-common \
bundled-rust-crate-atspi-connection \
bundled-rust-crate-atspi-proxies \
bundled-rust-crate-autocfg \
bundled-rust-crate-base64 \
bundled-rust-crate-bit-field \
bundled-rust-crate-bit-set \
bundled-rust-crate-bit-vec \
bundled-rust-crate-bitflags \
bundled-rust-crate-block-buffer \
bundled-rust-crate-blocking \
bundled-rust-crate-by-address \
bundled-rust-crate-bytemuck \
bundled-rust-crate-bytemuck-derive \
bundled-rust-crate-byteorder \
bundled-rust-crate-bytes \
bundled-rust-crate-calloop \
bundled-rust-crate-calloop-wayland-source \
bundled-rust-crate-cc \
bundled-rust-crate-cfg-aliases \
bundled-rust-crate-cfg-if \
bundled-rust-crate-chrono \
bundled-rust-crate-clipboard-wayland \
bundled-rust-crate-clipboard-x11 \
bundled-rust-crate-codespan-reporting \
bundled-rust-crate-color-quant \
bundled-rust-crate-concurrent-queue \
bundled-rust-crate-const-random \
bundled-rust-crate-const-random-macro \
bundled-rust-crate-cosmic-applet-places-status-indicator \
bundled-rust-crate-cosmic-client-toolkit \
bundled-rust-crate-cosmic-config \
bundled-rust-crate-cosmic-config-derive \
bundled-rust-crate-cosmic-panel-config \
bundled-rust-crate-cosmic-protocols \
bundled-rust-crate-cosmic-text \
bundled-rust-crate-cosmic-theme \
bundled-rust-crate-cpufeatures \
bundled-rust-crate-crc32fast \
bundled-rust-crate-crossbeam-channel \
bundled-rust-crate-crossbeam-deque \
bundled-rust-crate-crossbeam-epoch \
bundled-rust-crate-crossbeam-utils \
bundled-rust-crate-crunchy \
bundled-rust-crate-crypto-common \
bundled-rust-crate-css-color \
bundled-rust-crate-csscolorparser \
bundled-rust-crate-ctor-lite \
bundled-rust-crate-cursor-icon \
bundled-rust-crate-darling \
bundled-rust-crate-darling-core \
bundled-rust-crate-darling-macro \
bundled-rust-crate-dashmap \
bundled-rust-crate-data-url \
bundled-rust-crate-derivative \
bundled-rust-crate-derive-setters \
bundled-rust-crate-digest \
bundled-rust-crate-dirs \
bundled-rust-crate-dirs-sys \
bundled-rust-crate-displaydoc \
bundled-rust-crate-dlib \
bundled-rust-crate-dlv-list \
bundled-rust-crate-dnd \
bundled-rust-crate-downcast-rs \
bundled-rust-crate-drm \
bundled-rust-crate-drm-ffi \
bundled-rust-crate-drm-fourcc \
bundled-rust-crate-drm-sys \
bundled-rust-crate-either \
bundled-rust-crate-endi \
bundled-rust-crate-enum-repr \
bundled-rust-crate-enumflags2 \
bundled-rust-crate-enumflags2-derive \
bundled-rust-crate-equivalent \
bundled-rust-crate-errno \
bundled-rust-crate-etagere \
bundled-rust-crate-euclid \
bundled-rust-crate-event-listener \
bundled-rust-crate-event-listener-strategy \
bundled-rust-crate-exr \
bundled-rust-crate-fast-srgb8 \
bundled-rust-crate-fastrand \
bundled-rust-crate-fdeflate \
bundled-rust-crate-filetime \
bundled-rust-crate-find-crate \
bundled-rust-crate-flate2 \
bundled-rust-crate-float-cmp \
bundled-rust-crate-float-next-after \
bundled-rust-crate-fluent \
bundled-rust-crate-fluent-bundle \
bundled-rust-crate-fluent-langneg \
bundled-rust-crate-fluent-syntax \
bundled-rust-crate-flume \
bundled-rust-crate-fnv \
bundled-rust-crate-font-types \
bundled-rust-crate-fontconfig-parser \
bundled-rust-crate-fontdb \
bundled-rust-crate-form-urlencoded \
bundled-rust-crate-fraction \
bundled-rust-crate-freedesktop-icons \
bundled-rust-crate-futures \
bundled-rust-crate-futures-channel \
bundled-rust-crate-futures-core \
bundled-rust-crate-futures-executor \
bundled-rust-crate-futures-io \
bundled-rust-crate-futures-lite \
bundled-rust-crate-futures-macro \
bundled-rust-crate-futures-sink \
bundled-rust-crate-futures-task \
bundled-rust-crate-futures-util \
bundled-rust-crate-generic-array \
bundled-rust-crate-getrandom \
bundled-rust-crate-gif \
bundled-rust-crate-glam \
bundled-rust-crate-glow \
bundled-rust-crate-glyphon \
bundled-rust-crate-gpu-alloc \
bundled-rust-crate-gpu-alloc-types \
bundled-rust-crate-gpu-descriptor \
bundled-rust-crate-gpu-descriptor-types \
bundled-rust-crate-grid \
bundled-rust-crate-guillotiere \
bundled-rust-crate-half \
bundled-rust-crate-hashbrown \
bundled-rust-crate-heck \
bundled-rust-crate-hex \
bundled-rust-crate-hexf-parse \
bundled-rust-crate-i18n-config \
bundled-rust-crate-i18n-embed \
bundled-rust-crate-i18n-embed-fl \
bundled-rust-crate-i18n-embed-impl \
bundled-rust-crate-iana-time-zone \
bundled-rust-crate-iced \
bundled-rust-crate-iced-accessibility \
bundled-rust-crate-iced-core \
bundled-rust-crate-iced-futures \
bundled-rust-crate-iced-graphics \
bundled-rust-crate-iced-renderer \
bundled-rust-crate-iced-runtime \
bundled-rust-crate-iced-sctk \
bundled-rust-crate-iced-style \
bundled-rust-crate-iced-tiny-skia \
bundled-rust-crate-iced-wgpu \
bundled-rust-crate-iced-widget \
bundled-rust-crate-ident-case \
bundled-rust-crate-idna \
bundled-rust-crate-image \
bundled-rust-crate-imagesize \
bundled-rust-crate-indexmap \
bundled-rust-crate-inotify \
bundled-rust-crate-inotify-sys \
bundled-rust-crate-intl-memoizer \
bundled-rust-crate-intl-pluralrules \
bundled-rust-crate-io-lifetimes \
bundled-rust-crate-itertools \
bundled-rust-crate-itoa \
bundled-rust-crate-jpeg-decoder \
bundled-rust-crate-kamadak-exif \
bundled-rust-crate-khronos-egl \
bundled-rust-crate-kurbo \
bundled-rust-crate-lazy-static \
bundled-rust-crate-lebe \
bundled-rust-crate-libc \
bundled-rust-crate-libcosmic \
bundled-rust-crate-libloading \
bundled-rust-crate-libm \
bundled-rust-crate-linux-raw-sys \
bundled-rust-crate-locale-config \
bundled-rust-crate-lock-api \
bundled-rust-crate-log \
bundled-rust-crate-lru \
bundled-rust-crate-lyon \
bundled-rust-crate-lyon-algorithms \
bundled-rust-crate-lyon-geom \
bundled-rust-crate-lyon-path \
bundled-rust-crate-lyon-tessellation \
bundled-rust-crate-memchr \
bundled-rust-crate-memmap2 \
bundled-rust-crate-memoffset \
bundled-rust-crate-mime \
bundled-rust-crate-miniz-oxide \
bundled-rust-crate-mio \
bundled-rust-crate-mutate-once \
bundled-rust-crate-naga \
bundled-rust-crate-nix \
bundled-rust-crate-notify \
bundled-rust-crate-num \
bundled-rust-crate-num-bigint \
bundled-rust-crate-num-complex \
bundled-rust-crate-num-cpus \
bundled-rust-crate-num-integer \
bundled-rust-crate-num-iter \
bundled-rust-crate-num-rational \
bundled-rust-crate-num-traits \
bundled-rust-crate-once-cell \
bundled-rust-crate-option-ext \
bundled-rust-crate-ordered-multimap \
bundled-rust-crate-ordered-stream \
bundled-rust-crate-ouroboros \
bundled-rust-crate-ouroboros-macro \
bundled-rust-crate-palette \
bundled-rust-crate-palette-derive \
bundled-rust-crate-parking \
bundled-rust-crate-parking-lot \
bundled-rust-crate-parking-lot-core \
bundled-rust-crate-paste \
bundled-rust-crate-percent-encoding \
bundled-rust-crate-phf \
bundled-rust-crate-phf-generator \
bundled-rust-crate-phf-macros \
bundled-rust-crate-phf-shared \
bundled-rust-crate-pico-args \
bundled-rust-crate-pin-project-lite \
bundled-rust-crate-pin-utils \
bundled-rust-crate-piper \
bundled-rust-crate-pkg-config \
bundled-rust-crate-png \
bundled-rust-crate-polling \
bundled-rust-crate-pollster \
bundled-rust-crate-ppv-lite86 \
bundled-rust-crate-proc-macro-crate \
bundled-rust-crate-proc-macro-error \
bundled-rust-crate-proc-macro-error-attr \
bundled-rust-crate-proc-macro2 \
bundled-rust-crate-profiling \
bundled-rust-crate-qoi \
bundled-rust-crate-quick-xml \
bundled-rust-crate-quote \
bundled-rust-crate-rand \
bundled-rust-crate-rand-chacha \
bundled-rust-crate-rand-core \
bundled-rust-crate-rangemap \
bundled-rust-crate-raw-window-handle \
bundled-rust-crate-rayon \
bundled-rust-crate-rayon-core \
bundled-rust-crate-rctree \
bundled-rust-crate-read-fonts \
bundled-rust-crate-regex \
bundled-rust-crate-regex-automata \
bundled-rust-crate-regex-syntax \
bundled-rust-crate-renderdoc-sys \
bundled-rust-crate-resvg \
bundled-rust-crate-rfd \
bundled-rust-crate-rgb \
bundled-rust-crate-ron \
bundled-rust-crate-roxmltree \
bundled-rust-crate-rust-embed \
bundled-rust-crate-rust-embed-impl \
bundled-rust-crate-rust-embed-utils \
bundled-rust-crate-rust-ini \
bundled-rust-crate-rustc-hash \
bundled-rust-crate-rustix \
bundled-rust-crate-rustybuzz \
bundled-rust-crate-ryu \
bundled-rust-crate-same-file \
bundled-rust-crate-scoped-tls \
bundled-rust-crate-scopeguard \
bundled-rust-crate-self-cell \
bundled-rust-crate-serde \
bundled-rust-crate-serde-derive \
bundled-rust-crate-serde-json \
bundled-rust-crate-serde-repr \
bundled-rust-crate-serde-spanned \
bundled-rust-crate-sha1 \
bundled-rust-crate-sha2 \
bundled-rust-crate-signal-hook-registry \
bundled-rust-crate-simd-adler32 \
bundled-rust-crate-simplecss \
bundled-rust-crate-siphasher \
bundled-rust-crate-slab \
bundled-rust-crate-slotmap \
bundled-rust-crate-smallvec \
bundled-rust-crate-smithay-client-toolkit \
bundled-rust-crate-smithay-clipboard \
bundled-rust-crate-smol-str \
bundled-rust-crate-socket2 \
bundled-rust-crate-softbuffer \
bundled-rust-crate-spin \
bundled-rust-crate-spirv \
bundled-rust-crate-static-assertions \
bundled-rust-crate-strict-num \
bundled-rust-crate-strsim \
bundled-rust-crate-svg-fmt \
bundled-rust-crate-svgtypes \
bundled-rust-crate-swash \
bundled-rust-crate-syn \
bundled-rust-crate-sys-locale \
bundled-rust-crate-taffy \
bundled-rust-crate-tempfile \
bundled-rust-crate-termcolor \
bundled-rust-crate-thiserror \
bundled-rust-crate-thiserror-impl \
bundled-rust-crate-tiff \
bundled-rust-crate-tiny-keccak \
bundled-rust-crate-tiny-skia \
bundled-rust-crate-tiny-skia-path \
bundled-rust-crate-tiny-xlib \
bundled-rust-crate-tinystr \
bundled-rust-crate-tinyvec \
bundled-rust-crate-tinyvec-macros \
bundled-rust-crate-tokio \
bundled-rust-crate-toml \
bundled-rust-crate-toml-datetime \
bundled-rust-crate-toml-edit \
bundled-rust-crate-tracing \
bundled-rust-crate-tracing-attributes \
bundled-rust-crate-tracing-core \
bundled-rust-crate-trash \
bundled-rust-crate-ttf-parser \
bundled-rust-crate-type-map \
bundled-rust-crate-typenum \
bundled-rust-crate-unic-langid \
bundled-rust-crate-unic-langid-impl \
bundled-rust-crate-unicode-bidi \
bundled-rust-crate-unicode-bidi-mirroring \
bundled-rust-crate-unicode-ccc \
bundled-rust-crate-unicode-ident \
bundled-rust-crate-unicode-linebreak \
bundled-rust-crate-unicode-normalization \
bundled-rust-crate-unicode-properties \
bundled-rust-crate-unicode-script \
bundled-rust-crate-unicode-segmentation \
bundled-rust-crate-unicode-vo \
bundled-rust-crate-unicode-width \
bundled-rust-crate-unicode-xid \
bundled-rust-crate-url \
bundled-rust-crate-urlencoding \
bundled-rust-crate-usvg \
bundled-rust-crate-usvg-parser \
bundled-rust-crate-usvg-text-layout \
bundled-rust-crate-usvg-tree \
bundled-rust-crate-version-check \
bundled-rust-crate-waker-fn \
bundled-rust-crate-walkdir \
bundled-rust-crate-wayland-backend \
bundled-rust-crate-wayland-client \
bundled-rust-crate-wayland-csd-frame \
bundled-rust-crate-wayland-cursor \
bundled-rust-crate-wayland-protocols \
bundled-rust-crate-wayland-protocols-wlr \
bundled-rust-crate-wayland-scanner \
bundled-rust-crate-wayland-server \
bundled-rust-crate-wayland-sys \
bundled-rust-crate-web-time \
bundled-rust-crate-weezl \
bundled-rust-crate-wgpu \
bundled-rust-crate-wgpu-core \
bundled-rust-crate-wgpu-hal \
bundled-rust-crate-wgpu-types \
bundled-rust-crate-window-clipboard \
bundled-rust-crate-winnow \
bundled-rust-crate-x11rb \
bundled-rust-crate-x11rb-protocol \
bundled-rust-crate-xcursor \
bundled-rust-crate-xdg \
bundled-rust-crate-xdg-home \
bundled-rust-crate-xdg-shell-wrapper-config \
bundled-rust-crate-xkbcommon \
bundled-rust-crate-xkbcommon-dl \
bundled-rust-crate-xkeysym \
bundled-rust-crate-xmlwriter \
bundled-rust-crate-xxhash-rust \
bundled-rust-crate-yazi \
bundled-rust-crate-zbus \
bundled-rust-crate-zbus-macros \
bundled-rust-crate-zbus-names \
bundled-rust-crate-zeno \
bundled-rust-crate-zerocopy \
bundled-rust-crate-zune-inflate \
bundled-rust-crate-zvariant \
bundled-rust-crate-zvariant-derive \
bundled-rust-crate-zvariant-utils \
cosmic-ext-applet-places-status-indicator"

RDEPENDS:${PN} += "libc.so.6 \
libgcc-s.so.1 \
libm.so.6 \
libxkbcommon.so.0"

inherit rpm
