SUMMARY = "A simple class for electronic presentations"
DESCRIPTION = "The elpres class is intended to be used for presentations on a \
screen or with a beamer/projector. It is derived from LaTeX's \
article class and can be used with LaTeX, pdfLaTeX, and \
LuaLaTeX. The default 'virtual paper size' of presentations \
generated by this class corresponds to a 4:3 (width:height) \
aspect ratio. Other aspect ratios for widescreen monitors \
(16:9, 16:10) may be selected."
LICENSE = "LPPL-1.0"

PV = "2026.226.1.1svn76790"

RPM_NAME = "texlive-elpres-2026.226.1.1svn76790-61.4.noarch.rpm"
RPM_HASH = "23bbd970107bd8ec4b823c095ca992ceaf7ea7e39b9bc7804eb1b2da8636eeef5de871aae1ff2a52b82874fc1526ae47ac79b7365e35f75a736c4c5e8c05e35a"
REPO_ARCH = "noarch"

RPROVIDES:${PN} += "tex-elpres.cls \
tex-elpresbluelightgrayscheme.sty \
tex-elpresgrayscheme.sty \
tex-elpreswhitebluescheme.sty \
tex-elpreswhiteredscheme.sty \
tex-elpreswhitetealscheme.sty \
texlive-elpres"

RDEPENDS:${PN} += "/usr/bin/sh \
coreutils \
ed \
findutils \
grep \
sed \
tex-article.cls \
tex-courier.sty \
tex-fancyhdr.sty \
tex-graphicx.sty \
tex-helvet.sty \
tex-hyperref.sty \
tex-ifthen.sty \
tex-mathptmx.sty \
tex-xcolor.sty \
texlive \
texlive-filesystem \
texlive-kpathsea \
texlive-kpathsea-bin \
texlive-scripts \
texlive-scripts-bin"

inherit rpm
