SUMMARY = "Core hyphenation support files"
DESCRIPTION = "Includes Knuth's original hyphen.tex, zerohyph.tex to disable \
hyphenation, language.us which starts the autogenerated files \
language.dat and language.def (and default versions of those), \
etc."
LICENSE = "LPPL-1.0"

PV = "2026.226.svn78076"

RPM_NAME = "texlive-hyphen-base-2026.226.svn78076-60.2.noarch.rpm"
RPM_HASH = "04edaaac467b696838de8debb98743a8804695499cfbd792cede353a3f6078d92a2bbd5a1aa66c5fd50b78fc002004034cccfccfdee52ba0393fc8a30dc676bd"
REPO_ARCH = "noarch"

RPROVIDES:${PN} += "config-texlive-hyphen-base \
tex-dumyhyph.tex \
tex-hyphen.tex \
tex-hypht1.tex \
tex-language.dat \
tex-language.dat.lua \
tex-language.def \
tex-language.us.def \
tex-zerohyph.tex \
texlive-hyphen-base"

RDEPENDS:${PN} += "/usr/bin/sh \
coreutils \
ed \
findutils \
grep \
sed \
texlive \
texlive-filesystem \
texlive-kpathsea \
texlive-kpathsea-bin \
texlive-scripts \
texlive-scripts-bin"

inherit rpm
