SUMMARY = "A better way to navigate directories"
DESCRIPTION = "A better way to navigate directories. \
Tree-like commandline directory navigator written in Rust."
LICENSE = "GPL-2.0-only & MIT & MPL-2.0 & GPL-2.0-only-with-GCC-exception-2.0"

PV = "1.60.1"

RPM_NAME = "broot-1.60.1-1.1.aarch64.rpm"
RPM_HASH = "46bfa6b85168ffff6e8152c50f2f3f78b869942a824fcd51baa0babab65363ac388fcd2c74e1f9ac3863a44d81d020fba0833f567ec9a3300875166c191a56b6"

RPROVIDES:${PN} += "broot \
bundled-rust-crate-adler2 \
bundled-rust-crate-ahash \
bundled-rust-crate-aho-corasick \
bundled-rust-crate-aligned \
bundled-rust-crate-aligned-vec \
bundled-rust-crate-allocator-api2 \
bundled-rust-crate-anstream \
bundled-rust-crate-anstyle \
bundled-rust-crate-anstyle-parse \
bundled-rust-crate-anstyle-query \
bundled-rust-crate-anyhow \
bundled-rust-crate-arc-swap \
bundled-rust-crate-arg-enum-proc-macro \
bundled-rust-crate-arrayref \
bundled-rust-crate-arrayvec \
bundled-rust-crate-as-slice \
bundled-rust-crate-autocfg \
bundled-rust-crate-av-scenechange \
bundled-rust-crate-av1-grain \
bundled-rust-crate-avif-serialize \
bundled-rust-crate-base64 \
bundled-rust-crate-bet \
bundled-rust-crate-bincode \
bundled-rust-crate-bit-field \
bundled-rust-crate-bit-set \
bundled-rust-crate-bit-vec \
bundled-rust-crate-bitflags \
bundled-rust-crate-bitstream-io \
bundled-rust-crate-block-buffer \
bundled-rust-crate-broot \
bundled-rust-crate-bstr \
bundled-rust-crate-built \
bundled-rust-crate-bumpalo \
bundled-rust-crate-bytemuck \
bundled-rust-crate-bytemuck-derive \
bundled-rust-crate-byteorder \
bundled-rust-crate-byteorder-lite \
bundled-rust-crate-bytes \
bundled-rust-crate-cfg-aliases \
bundled-rust-crate-cfg-if \
bundled-rust-crate-chacha20 \
bundled-rust-crate-char-reader \
bundled-rust-crate-chrono \
bundled-rust-crate-clap \
bundled-rust-crate-clap-builder \
bundled-rust-crate-clap-complete \
bundled-rust-crate-clap-derive \
bundled-rust-crate-clap-help \
bundled-rust-crate-clap-lex \
bundled-rust-crate-clap-mangen \
bundled-rust-crate-cli-log \
bundled-rust-crate-clru \
bundled-rust-crate-color-quant \
bundled-rust-crate-colorchoice \
bundled-rust-crate-convert-case \
bundled-rust-crate-coolor \
bundled-rust-crate-cpufeatures \
bundled-rust-crate-crc32fast \
bundled-rust-crate-crokey \
bundled-rust-crate-crokey-proc-macros \
bundled-rust-crate-crossbeam \
bundled-rust-crate-crossbeam-channel \
bundled-rust-crate-crossbeam-deque \
bundled-rust-crate-crossbeam-epoch \
bundled-rust-crate-crossbeam-queue \
bundled-rust-crate-crossbeam-utils \
bundled-rust-crate-crossterm \
bundled-rust-crate-crypto-common \
bundled-rust-crate-custom-error \
bundled-rust-crate-dashmap \
bundled-rust-crate-data-url \
bundled-rust-crate-defmt \
bundled-rust-crate-defmt-macros \
bundled-rust-crate-defmt-parser \
bundled-rust-crate-deranged \
bundled-rust-crate-derive-more \
bundled-rust-crate-derive-more-impl \
bundled-rust-crate-deser-hjson \
bundled-rust-crate-digest \
bundled-rust-crate-directories \
bundled-rust-crate-dirs-sys \
bundled-rust-crate-document-features \
bundled-rust-crate-either \
bundled-rust-crate-encoding-rs \
bundled-rust-crate-equator \
bundled-rust-crate-equator-macro \
bundled-rust-crate-equivalent \
bundled-rust-crate-errno \
bundled-rust-crate-euclid \
bundled-rust-crate-exr \
bundled-rust-crate-fancy-regex \
bundled-rust-crate-faster-hex \
bundled-rust-crate-fastrand \
bundled-rust-crate-fax \
bundled-rust-crate-fdeflate \
bundled-rust-crate-file-size \
bundled-rust-crate-filetime \
bundled-rust-crate-flate2 \
bundled-rust-crate-flex-grow \
bundled-rust-crate-float-cmp \
bundled-rust-crate-fnv \
bundled-rust-crate-foldhash \
bundled-rust-crate-font-types \
bundled-rust-crate-fontconfig-parser \
bundled-rust-crate-fontdb \
bundled-rust-crate-generic-array \
bundled-rust-crate-getrandom \
bundled-rust-crate-gif \
bundled-rust-crate-gix \
bundled-rust-crate-gix-actor \
bundled-rust-crate-gix-attributes \
bundled-rust-crate-gix-bitmap \
bundled-rust-crate-gix-chunk \
bundled-rust-crate-gix-command \
bundled-rust-crate-gix-commitgraph \
bundled-rust-crate-gix-config \
bundled-rust-crate-gix-config-value \
bundled-rust-crate-gix-date \
bundled-rust-crate-gix-diff \
bundled-rust-crate-gix-dir \
bundled-rust-crate-gix-discover \
bundled-rust-crate-gix-error \
bundled-rust-crate-gix-features \
bundled-rust-crate-gix-filter \
bundled-rust-crate-gix-fs \
bundled-rust-crate-gix-glob \
bundled-rust-crate-gix-hash \
bundled-rust-crate-gix-hashtable \
bundled-rust-crate-gix-ignore \
bundled-rust-crate-gix-imara-diff \
bundled-rust-crate-gix-index \
bundled-rust-crate-gix-lock \
bundled-rust-crate-gix-macros \
bundled-rust-crate-gix-note \
bundled-rust-crate-gix-object \
bundled-rust-crate-gix-odb \
bundled-rust-crate-gix-pack \
bundled-rust-crate-gix-packetline \
bundled-rust-crate-gix-path \
bundled-rust-crate-gix-pathspec \
bundled-rust-crate-gix-protocol \
bundled-rust-crate-gix-quote \
bundled-rust-crate-gix-ref \
bundled-rust-crate-gix-refspec \
bundled-rust-crate-gix-revision \
bundled-rust-crate-gix-revwalk \
bundled-rust-crate-gix-sec \
bundled-rust-crate-gix-shallow \
bundled-rust-crate-gix-status \
bundled-rust-crate-gix-submodule \
bundled-rust-crate-gix-tempfile \
bundled-rust-crate-gix-trace \
bundled-rust-crate-gix-transport \
bundled-rust-crate-gix-traverse \
bundled-rust-crate-gix-url \
bundled-rust-crate-gix-utils \
bundled-rust-crate-gix-validate \
bundled-rust-crate-gix-worktree \
bundled-rust-crate-gix-worktree-stream \
bundled-rust-crate-gix-zlib \
bundled-rust-crate-glob \
bundled-rust-crate-half \
bundled-rust-crate-harfrust \
bundled-rust-crate-hash32 \
bundled-rust-crate-hashbrown \
bundled-rust-crate-heapless \
bundled-rust-crate-heck \
bundled-rust-crate-home \
bundled-rust-crate-iana-time-zone \
bundled-rust-crate-id-arena \
bundled-rust-crate-image \
bundled-rust-crate-image-webp \
bundled-rust-crate-imagesize \
bundled-rust-crate-imgref \
bundled-rust-crate-include-dir \
bundled-rust-crate-include-dir-macros \
bundled-rust-crate-indexmap \
bundled-rust-crate-inotify \
bundled-rust-crate-inotify-sys \
bundled-rust-crate-is-terminal-polyfill \
bundled-rust-crate-itertools \
bundled-rust-crate-itoa \
bundled-rust-crate-jiff \
bundled-rust-crate-jiff-core \
bundled-rust-crate-jiff-static \
bundled-rust-crate-jpeg-encoder \
bundled-rust-crate-kamadak-exif \
bundled-rust-crate-kurbo \
bundled-rust-crate-lazy-regex \
bundled-rust-crate-lazy-regex-proc-macros \
bundled-rust-crate-lebe \
bundled-rust-crate-lfs-core \
bundled-rust-crate-libc \
bundled-rust-crate-libm \
bundled-rust-crate-linked-hash-map \
bundled-rust-crate-linux-raw-sys \
bundled-rust-crate-litrs \
bundled-rust-crate-lock-api \
bundled-rust-crate-log \
bundled-rust-crate-loop9 \
bundled-rust-crate-lru \
bundled-rust-crate-maybe-rayon \
bundled-rust-crate-memchr \
bundled-rust-crate-memmap2 \
bundled-rust-crate-minimad \
bundled-rust-crate-miniz-oxide \
bundled-rust-crate-mio \
bundled-rust-crate-moxcms \
bundled-rust-crate-mutate-once \
bundled-rust-crate-new-debug-unreachable \
bundled-rust-crate-nix \
bundled-rust-crate-no-std-io2 \
bundled-rust-crate-nom \
bundled-rust-crate-nonempty \
bundled-rust-crate-noop-proc-macro \
bundled-rust-crate-notify \
bundled-rust-crate-notify-types \
bundled-rust-crate-num-bigint \
bundled-rust-crate-num-complex \
bundled-rust-crate-num-conv \
bundled-rust-crate-num-derive \
bundled-rust-crate-num-integer \
bundled-rust-crate-num-rational \
bundled-rust-crate-num-traits \
bundled-rust-crate-once-cell \
bundled-rust-crate-opener \
bundled-rust-crate-parking-lot \
bundled-rust-crate-parking-lot-core \
bundled-rust-crate-paste \
bundled-rust-crate-pastey \
bundled-rust-crate-pathdiff \
bundled-rust-crate-percent-encoding \
bundled-rust-crate-phf \
bundled-rust-crate-phf-generator \
bundled-rust-crate-phf-macros \
bundled-rust-crate-phf-shared \
bundled-rust-crate-pico-args \
bundled-rust-crate-plist \
bundled-rust-crate-png \
bundled-rust-crate-polycool \
bundled-rust-crate-powerfmt \
bundled-rust-crate-proc-macro2 \
bundled-rust-crate-proc-status \
bundled-rust-crate-prodash \
bundled-rust-crate-profiling \
bundled-rust-crate-profiling-procmacros \
bundled-rust-crate-pulp \
bundled-rust-crate-pulp-wasm-simd-flag \
bundled-rust-crate-pxfm \
bundled-rust-crate-qoi \
bundled-rust-crate-quick-error \
bundled-rust-crate-quick-xml \
bundled-rust-crate-quote \
bundled-rust-crate-rand \
bundled-rust-crate-rand-core \
bundled-rust-crate-rav1e \
bundled-rust-crate-ravif \
bundled-rust-crate-rayon \
bundled-rust-crate-rayon-core \
bundled-rust-crate-read-fonts \
bundled-rust-crate-reborrow \
bundled-rust-crate-regex \
bundled-rust-crate-regex-automata \
bundled-rust-crate-regex-syntax \
bundled-rust-crate-resvg \
bundled-rust-crate-rgb \
bundled-rust-crate-roff \
bundled-rust-crate-roxmltree \
bundled-rust-crate-rustc-hash \
bundled-rust-crate-rustc-version \
bundled-rust-crate-rustix \
bundled-rust-crate-rustversion \
bundled-rust-crate-same-file \
bundled-rust-crate-scopeguard \
bundled-rust-crate-secular \
bundled-rust-crate-semver \
bundled-rust-crate-serde \
bundled-rust-crate-serde-core \
bundled-rust-crate-serde-derive \
bundled-rust-crate-serde-json \
bundled-rust-crate-serde-spanned \
bundled-rust-crate-sha1 \
bundled-rust-crate-sha1-checked \
bundled-rust-crate-signal-hook \
bundled-rust-crate-signal-hook-mio \
bundled-rust-crate-signal-hook-registry \
bundled-rust-crate-simd-adler32 \
bundled-rust-crate-simd-helpers \
bundled-rust-crate-simplecss \
bundled-rust-crate-siphasher \
bundled-rust-crate-skrifa \
bundled-rust-crate-slotmap \
bundled-rust-crate-smallvec \
bundled-rust-crate-snafu \
bundled-rust-crate-snafu-derive \
bundled-rust-crate-splitty \
bundled-rust-crate-stable-deref-trait \
bundled-rust-crate-strict \
bundled-rust-crate-strict-num \
bundled-rust-crate-strsim \
bundled-rust-crate-svgtypes \
bundled-rust-crate-syn \
bundled-rust-crate-syntect-no-panic \
bundled-rust-crate-tempfile \
bundled-rust-crate-termimad \
bundled-rust-crate-terminal-light \
bundled-rust-crate-thiserror \
bundled-rust-crate-thiserror-impl \
bundled-rust-crate-tiff \
bundled-rust-crate-time \
bundled-rust-crate-time-core \
bundled-rust-crate-time-macros \
bundled-rust-crate-tiny-skia \
bundled-rust-crate-tiny-skia-path \
bundled-rust-crate-tinyvec \
bundled-rust-crate-tinyvec-macros \
bundled-rust-crate-toml \
bundled-rust-crate-toml-datetime \
bundled-rust-crate-toml-parser \
bundled-rust-crate-toml-writer \
bundled-rust-crate-trash \
bundled-rust-crate-typenum \
bundled-rust-crate-uluru \
bundled-rust-crate-umask \
bundled-rust-crate-unicode-bidi \
bundled-rust-crate-unicode-bom \
bundled-rust-crate-unicode-ident \
bundled-rust-crate-unicode-normalization \
bundled-rust-crate-unicode-script \
bundled-rust-crate-unicode-segmentation \
bundled-rust-crate-unicode-vo \
bundled-rust-crate-unicode-width \
bundled-rust-crate-urlencoding \
bundled-rust-crate-usvg \
bundled-rust-crate-utf8parse \
bundled-rust-crate-uzers \
bundled-rust-crate-v-frame \
bundled-rust-crate-version-check \
bundled-rust-crate-vte \
bundled-rust-crate-walkdir \
bundled-rust-crate-wasm-bindgen \
bundled-rust-crate-wasm-bindgen-macro \
bundled-rust-crate-wasm-bindgen-macro-support \
bundled-rust-crate-wasm-bindgen-shared \
bundled-rust-crate-weezl \
bundled-rust-crate-which \
bundled-rust-crate-winnow \
bundled-rust-crate-xmlwriter \
bundled-rust-crate-xterm-query \
bundled-rust-crate-y4m \
bundled-rust-crate-yaml-rust \
bundled-rust-crate-zerocopy \
bundled-rust-crate-zerocopy-derive \
bundled-rust-crate-zlib-rs \
bundled-rust-crate-zmij \
bundled-rust-crate-zune-bmp \
bundled-rust-crate-zune-core \
bundled-rust-crate-zune-farbfeld \
bundled-rust-crate-zune-hdr \
bundled-rust-crate-zune-image \
bundled-rust-crate-zune-inflate \
bundled-rust-crate-zune-jpeg \
bundled-rust-crate-zune-png \
bundled-rust-crate-zune-ppm \
bundled-rust-crate-zune-psd \
bundled-rust-crate-zune-qoi"

RDEPENDS:${PN} += "libc.so.6 \
libgcc-s.so.1 \
libm.so.6"

inherit rpm
