SUMMARY = "GNU patch"
DESCRIPTION = "The GNU patch program is used to apply diffs between original and \
changed files (generated by the diff command) to the original files."
LICENSE = "GPL-3.0-or-later"

PV = "2.8"

RPM_NAME = "patch-2.8-3.2.aarch64.rpm"
RPM_HASH = "4fea5bc5953cb2509b8ab07562bd779e6251ba0bd236ac8412e0d42d3a0f60abb49779502cfef94a36a6725bc6b5315ecc0f47a9af6ca357fc8d4c766409c529"

RPROVIDES:${PN} += "patch"

RDEPENDS:${PN} += "ld-linux-aarch64.so.1 \
libc.so.6"

inherit rpm
