SUMMARY = "Data Plane Development Kit runtime libraries"
DESCRIPTION = "This package contains the runtime libraries needed for 3rd party application \
to use the Data Plane Development Kit."
LICENSE = "BSD-3-Clause & GPL-2.0-only & LGPL-2.1-only"

PV = "25.11.3"

RPM_NAME = "libdpdk-26-25.11.3-1.1.aarch64.rpm"
RPM_HASH = "09ee21080bd221685557c0325fb0265149d8cf04023213f443d688deed17e3cb3c5a357a6ba8239de8fc24caaa4faa59d8f88f206e71f826db8458e36013d45e"

RPROVIDES:${PN} += "libdpdk-26 \
libdpdk-26-any \
librte-acl.so.26 \
librte-argparse.so.26 \
librte-baseband-acc.so.26 \
librte-baseband-fpga-5gnr-fec.so.26 \
librte-baseband-fpga-lte-fec.so.26 \
librte-baseband-la12xx.so.26 \
librte-baseband-null.so.26 \
librte-baseband-turbo-sw.so.26 \
librte-bbdev.so.26 \
librte-bitratestats.so.26 \
librte-bpf.so.26 \
librte-bus-auxiliary.so.26 \
librte-bus-cdx.so.26 \
librte-bus-dpaa.so.26 \
librte-bus-fslmc.so.26 \
librte-bus-ifpga.so.26 \
librte-bus-pci.so.26 \
librte-bus-platform.so.26 \
librte-bus-uacce.so.26 \
librte-bus-vdev.so.26 \
librte-bus-vmbus.so.26 \
librte-cfgfile.so.26 \
librte-cmdline.so.26 \
librte-common-cnxk.so.26 \
librte-common-cpt.so.26 \
librte-common-dpaax.so.26 \
librte-common-ionic.so.26 \
librte-common-mlx5.so.26 \
librte-common-nfp.so.26 \
librte-common-nitrox.so.26 \
librte-common-octeontx.so.26 \
librte-common-qat.so.26 \
librte-common-sfc-efx.so.26 \
librte-common-zsda.so.26 \
librte-compress-mlx5.so.26 \
librte-compress-nitrox.so.26 \
librte-compress-octeontx.so.26 \
librte-compress-zlib.so.26 \
librte-compressdev.so.26 \
librte-crypto-bcmfs.so.26 \
librte-crypto-caam-jr.so.26 \
librte-crypto-ccp.so.26 \
librte-crypto-cnxk.so.26 \
librte-crypto-dpaa-sec.so.26 \
librte-crypto-dpaa2-sec.so.26 \
librte-crypto-ionic.so.26 \
librte-crypto-mlx5.so.26 \
librte-crypto-nitrox.so.26 \
librte-crypto-null.so.26 \
librte-crypto-octeontx.so.26 \
librte-crypto-openssl.so.26 \
librte-crypto-scheduler.so.26 \
librte-crypto-virtio.so.26 \
librte-cryptodev.so.26 \
librte-dispatcher.so.26 \
librte-distributor.so.26 \
librte-dma-cnxk.so.26 \
librte-dma-dpaa.so.26 \
librte-dma-dpaa2.so.26 \
librte-dma-hisi-acc.so.26 \
librte-dma-hisi-pciep.so.26 \
librte-dma-odm.so.26 \
librte-dma-skeleton.so.26 \
librte-dmadev.so.26 \
librte-eal.so.26 \
librte-efd.so.26 \
librte-ethdev.so.26 \
librte-event-cnxk.so.26 \
librte-event-dpaa.so.26 \
librte-event-dpaa2.so.26 \
librte-event-dsw.so.26 \
librte-event-octeontx.so.26 \
librte-event-opdl.so.26 \
librte-event-skeleton.so.26 \
librte-event-sw.so.26 \
librte-eventdev.so.26 \
librte-fib.so.26 \
librte-gpudev.so.26 \
librte-graph.so.26 \
librte-gro.so.26 \
librte-gso.so.26 \
librte-hash.so.26 \
librte-ip-frag.so.26 \
librte-ipsec.so.26 \
librte-jobstats.so.26 \
librte-kvargs.so.26 \
librte-latencystats.so.26 \
librte-log.so.26 \
librte-lpm.so.26 \
librte-mbuf.so.26 \
librte-member.so.26 \
librte-mempool-bucket.so.26 \
librte-mempool-cnxk.so.26 \
librte-mempool-dpaa.so.26 \
librte-mempool-dpaa2.so.26 \
librte-mempool-octeontx.so.26 \
librte-mempool-ring.so.26 \
librte-mempool-stack.so.26 \
librte-mempool.so.26 \
librte-meter.so.26 \
librte-metrics.so.26 \
librte-ml-cnxk.so.26 \
librte-mldev.so.26 \
librte-net-af-packet.so.26 \
librte-net-ark.so.26 \
librte-net-atlantic.so.26 \
librte-net-avp.so.26 \
librte-net-axgbe.so.26 \
librte-net-bnx2x.so.26 \
librte-net-bnxt.so.26 \
librte-net-bond.so.26 \
librte-net-cnxk.so.26 \
librte-net-cpfl.so.26 \
librte-net-cxgbe.so.26 \
librte-net-dpaa.so.26 \
librte-net-dpaa2.so.26 \
librte-net-e1000.so.26 \
librte-net-ena.so.26 \
librte-net-enetc.so.26 \
librte-net-enetfec.so.26 \
librte-net-enic.so.26 \
librte-net-failsafe.so.26 \
librte-net-fm10k.so.26 \
librte-net-gve.so.26 \
librte-net-hinic.so.26 \
librte-net-hinic3.so.26 \
librte-net-hns3.so.26 \
librte-net-i40e.so.26 \
librte-net-iavf.so.26 \
librte-net-ice.so.26 \
librte-net-idpf.so.26 \
librte-net-ionic.so.26 \
librte-net-ipn3ke.so.26 \
librte-net-ixgbe.so.26 \
librte-net-mana.so.26 \
librte-net-memif.so.26 \
librte-net-mlx4.so.26 \
librte-net-mlx5.so.26 \
librte-net-nbl.so.26 \
librte-net-netvsc.so.26 \
librte-net-nfp.so.26 \
librte-net-ngbe.so.26 \
librte-net-null.so.26 \
librte-net-octeon-ep.so.26 \
librte-net-octeontx.so.26 \
librte-net-pcap.so.26 \
librte-net-pfe.so.26 \
librte-net-qede.so.26 \
librte-net-r8169.so.26 \
librte-net-ring.so.26 \
librte-net-rnp.so.26 \
librte-net-sfc.so.26 \
librte-net-softnic.so.26 \
librte-net-tap.so.26 \
librte-net-thunderx.so.26 \
librte-net-txgbe.so.26 \
librte-net-vdev-netvsc.so.26 \
librte-net-vhost.so.26 \
librte-net-virtio.so.26 \
librte-net-vmxnet3.so.26 \
librte-net-xsc.so.26 \
librte-net-zxdh.so.26 \
librte-net.so.26 \
librte-node.so.26 \
librte-pcapng.so.26 \
librte-pci.so.26 \
librte-pdcp.so.26 \
librte-pdump.so.26 \
librte-pipeline.so.26 \
librte-pmu.so.26 \
librte-port.so.26 \
librte-power-acpi.so.26 \
librte-power-amd-pstate.so.26 \
librte-power-cppc.so.26 \
librte-power-intel-pstate.so.26 \
librte-power-intel-uncore.so.26 \
librte-power-kvm-vm.so.26 \
librte-power.so.26 \
librte-raw-cnxk-bphy.so.26 \
librte-raw-cnxk-gpio.so.26 \
librte-raw-cnxk-rvu-lf.so.26 \
librte-raw-dpaa2-cmdif.so.26 \
librte-raw-gdtc.so.26 \
librte-raw-ifpga.so.26 \
librte-raw-ntb.so.26 \
librte-raw-skeleton.so.26 \
librte-rawdev.so.26 \
librte-rcu.so.26 \
librte-regex-cn9k.so.26 \
librte-regex-mlx5.so.26 \
librte-regexdev.so.26 \
librte-reorder.so.26 \
librte-rib.so.26 \
librte-ring.so.26 \
librte-sched.so.26 \
librte-security.so.26 \
librte-stack.so.26 \
librte-table.so.26 \
librte-telemetry.so.26 \
librte-timer.so.26 \
librte-vdpa-ifc.so.26 \
librte-vdpa-mlx5.so.26 \
librte-vdpa-nfp.so.26 \
librte-vdpa-sfc.so.26 \
librte-vhost.so.26"

RDEPENDS:${PN} += "/sbin/ldconfig \
ld-linux-aarch64.so.1 \
libarchive.so.13 \
libatomic.so.1 \
libc.so.6 \
libcrypto.so.3 \
libelf.so.1 \
libfdt.so.1 \
libibverbs.so.1 \
libjansson.so.4 \
libm.so.6 \
libmana.so.1 \
libmlx4.so.1 \
libmlx5.so.1 \
libnuma.so.1 \
libpcap.so.1 \
libz.so.1"

inherit rpm
