SUMMARY = "The Tilde Toolkit's terminal key sequence database library"
DESCRIPTION = "libt3key is library that provides a database of mappings from escape \
sequences as generated by different consoles and terminals or \
emulators, to key symbols."
LICENSE = "GPL-3.0-only"

PV = "0.2.11"

RPM_NAME = "libt3key1-0.2.11-1.8.aarch64.rpm"
RPM_HASH = "1788be7c42e0be7425cbf8662392016a3f0f4427c392ef7eb56efed7354b136a188fa01a90d6e46d8904af998c0463f0a500a65599856620d02e7f4f207449f7"

RPROVIDES:${PN} += "libt3key.so.1 \
libt3key1"

RDEPENDS:${PN} += "/sbin/ldconfig \
libc.so.6 \
libt3config.so.0 \
libtinfo.so.6"

inherit rpm
