SUMMARY = "Lightning-fast and Powerful Code Editor written in Rust"
DESCRIPTION = "Lapce is written in pure Rust, with the UI in Druid \
It uses Xi-Editor's Rope Science for text editing, and the \
Wgpu Graphics API for rendering."
LICENSE = "(0BSD | Apache-2.0 | MIT) & (Apache-2.0 | MIT) & (Apache-2.0 | BSL-1.0) & (Apache-2.0 | ISC | MIT) & (Apache-2.0 | MIT) & (Apache-2.0 | MIT | Zlib) & MIT & (Artistic-2.0 | CC0-1.0) & BSD-2-Clause & BSD-3-Clause & BSL-1.0 & CC0-1.0 & ISC & MIT & (MIT | Unlicense) & MPL-2.0 & MPL-2.0+ & Zlib & zlib-acknowledgement & Apache-2.0"

PV = "0.4.5"

RPM_NAME = "lapce-0.4.5-1.6.aarch64.rpm"
RPM_HASH = "1e9a432690a7b76018a8dcda566cb6eb965f63e5d00f5570153659d75c8aaf533c517e1d8d7df5d125066ea74650eb4995f731bc5a136f2e41242f4becbbb6bb"

RPROVIDES:${PN} += "bundled-rust-crate-Inflector \
bundled-rust-crate-ab-glyph \
bundled-rust-crate-ab-glyph-rasterizer \
bundled-rust-crate-addr2line \
bundled-rust-crate-adler \
bundled-rust-crate-ahash \
bundled-rust-crate-aho-corasick \
bundled-rust-crate-alacritty-terminal \
bundled-rust-crate-allocator-api2 \
bundled-rust-crate-ambient-authority \
bundled-rust-crate-anstyle \
bundled-rust-crate-anyhow \
bundled-rust-crate-arbitrary \
bundled-rust-crate-arc-swap \
bundled-rust-crate-arrayref \
bundled-rust-crate-arrayvec \
bundled-rust-crate-as-raw-xcb-connection \
bundled-rust-crate-ash \
bundled-rust-crate-ashpd \
bundled-rust-crate-async-broadcast \
bundled-rust-crate-async-channel \
bundled-rust-crate-async-executor \
bundled-rust-crate-async-fs \
bundled-rust-crate-async-io \
bundled-rust-crate-async-lock \
bundled-rust-crate-async-net \
bundled-rust-crate-async-process \
bundled-rust-crate-async-signal \
bundled-rust-crate-async-task \
bundled-rust-crate-async-trait \
bundled-rust-crate-atomic-waker \
bundled-rust-crate-autocfg \
bundled-rust-crate-backtrace \
bundled-rust-crate-base64 \
bundled-rust-crate-bincode \
bundled-rust-crate-bit-set \
bundled-rust-crate-bit-vec \
bundled-rust-crate-bitflags \
bundled-rust-crate-bitmaps \
bundled-rust-crate-block-buffer \
bundled-rust-crate-blocking \
bundled-rust-crate-borsh \
bundled-rust-crate-bstr \
bundled-rust-crate-bumpalo \
bundled-rust-crate-bytecount \
bundled-rust-crate-bytemuck \
bundled-rust-crate-bytemuck-derive \
bundled-rust-crate-byteorder \
bundled-rust-crate-byteorder-lite \
bundled-rust-crate-bytes \
bundled-rust-crate-calloop \
bundled-rust-crate-calloop-wayland-source \
bundled-rust-crate-cap-fs-ext \
bundled-rust-crate-cap-net-ext \
bundled-rust-crate-cap-primitives \
bundled-rust-crate-cap-rand \
bundled-rust-crate-cap-std \
bundled-rust-crate-cap-time-ext \
bundled-rust-crate-cc \
bundled-rust-crate-cfg-aliases \
bundled-rust-crate-cfg-if \
bundled-rust-crate-chrono \
bundled-rust-crate-clap \
bundled-rust-crate-clap-builder \
bundled-rust-crate-clap-derive \
bundled-rust-crate-clap-lex \
bundled-rust-crate-codespan-reporting \
bundled-rust-crate-color \
bundled-rust-crate-color-quant \
bundled-rust-crate-concurrent-queue \
bundled-rust-crate-config \
bundled-rust-crate-copypasta \
bundled-rust-crate-core-maths \
bundled-rust-crate-cosmic-text \
bundled-rust-crate-cpp-demangle \
bundled-rust-crate-cpufeatures \
bundled-rust-crate-cranelift-bforest \
bundled-rust-crate-cranelift-codegen \
bundled-rust-crate-cranelift-codegen-meta \
bundled-rust-crate-cranelift-codegen-shared \
bundled-rust-crate-cranelift-control \
bundled-rust-crate-cranelift-entity \
bundled-rust-crate-cranelift-frontend \
bundled-rust-crate-cranelift-isle \
bundled-rust-crate-cranelift-native \
bundled-rust-crate-cranelift-wasm \
bundled-rust-crate-crc32fast \
bundled-rust-crate-crossbeam-channel \
bundled-rust-crate-crossbeam-deque \
bundled-rust-crate-crossbeam-epoch \
bundled-rust-crate-crossbeam-utils \
bundled-rust-crate-crypto-common \
bundled-rust-crate-ctor \
bundled-rust-crate-cursor-icon \
bundled-rust-crate-darling \
bundled-rust-crate-darling-core \
bundled-rust-crate-darling-macro \
bundled-rust-crate-data-url \
bundled-rust-crate-debugid \
bundled-rust-crate-deranged \
bundled-rust-crate-digest \
bundled-rust-crate-directories \
bundled-rust-crate-directories-next \
bundled-rust-crate-dirs \
bundled-rust-crate-dirs-sys \
bundled-rust-crate-dirs-sys-next \
bundled-rust-crate-displaydoc \
bundled-rust-crate-dlib \
bundled-rust-crate-document-features \
bundled-rust-crate-downcast-rs \
bundled-rust-crate-dpi \
bundled-rust-crate-drm \
bundled-rust-crate-drm-ffi \
bundled-rust-crate-drm-fourcc \
bundled-rust-crate-drm-sys \
bundled-rust-crate-dyn-clone \
bundled-rust-crate-educe \
bundled-rust-crate-either \
bundled-rust-crate-encoding-rs \
bundled-rust-crate-encoding-rs-io \
bundled-rust-crate-endi \
bundled-rust-crate-enum-ordinalize \
bundled-rust-crate-enum-ordinalize-derive \
bundled-rust-crate-enumflags2 \
bundled-rust-crate-enumflags2-derive \
bundled-rust-crate-equivalent \
bundled-rust-crate-errno \
bundled-rust-crate-euclid \
bundled-rust-crate-event-listener \
bundled-rust-crate-event-listener-strategy \
bundled-rust-crate-fallible-iterator \
bundled-rust-crate-fastrand \
bundled-rust-crate-fdeflate \
bundled-rust-crate-filetime \
bundled-rust-crate-flate2 \
bundled-rust-crate-float-cmp \
bundled-rust-crate-floem \
bundled-rust-crate-floem-editor-core \
bundled-rust-crate-floem-reactive \
bundled-rust-crate-floem-renderer \
bundled-rust-crate-floem-tiny-skia-renderer \
bundled-rust-crate-floem-vger \
bundled-rust-crate-floem-vger-renderer \
bundled-rust-crate-fnv \
bundled-rust-crate-foldhash \
bundled-rust-crate-font-types \
bundled-rust-crate-fontconfig-parser \
bundled-rust-crate-fontdb \
bundled-rust-crate-fontdue \
bundled-rust-crate-foreign-types \
bundled-rust-crate-foreign-types-shared \
bundled-rust-crate-form-urlencoded \
bundled-rust-crate-fs-set-times \
bundled-rust-crate-futures \
bundled-rust-crate-futures-channel \
bundled-rust-crate-futures-core \
bundled-rust-crate-futures-executor \
bundled-rust-crate-futures-io \
bundled-rust-crate-futures-lite \
bundled-rust-crate-futures-macro \
bundled-rust-crate-futures-sink \
bundled-rust-crate-futures-task \
bundled-rust-crate-futures-util \
bundled-rust-crate-fxhash \
bundled-rust-crate-fxprof-processed-profile \
bundled-rust-crate-generic-array \
bundled-rust-crate-getopts \
bundled-rust-crate-getrandom \
bundled-rust-crate-gif \
bundled-rust-crate-gimli \
bundled-rust-crate-git2 \
bundled-rust-crate-globset \
bundled-rust-crate-glow \
bundled-rust-crate-gpu-alloc \
bundled-rust-crate-gpu-alloc-types \
bundled-rust-crate-gpu-descriptor \
bundled-rust-crate-gpu-descriptor-types \
bundled-rust-crate-grep-matcher \
bundled-rust-crate-grep-regex \
bundled-rust-crate-grep-searcher \
bundled-rust-crate-grid \
bundled-rust-crate-h2 \
bundled-rust-crate-hashbrown \
bundled-rust-crate-heck \
bundled-rust-crate-hex \
bundled-rust-crate-hexf-parse \
bundled-rust-crate-home \
bundled-rust-crate-http \
bundled-rust-crate-http-body \
bundled-rust-crate-httparse \
bundled-rust-crate-httpdate \
bundled-rust-crate-human-sort \
bundled-rust-crate-hyper \
bundled-rust-crate-hyper-tls \
bundled-rust-crate-iana-time-zone \
bundled-rust-crate-icu-collections \
bundled-rust-crate-icu-locale-core \
bundled-rust-crate-icu-normalizer \
bundled-rust-crate-icu-normalizer-data \
bundled-rust-crate-icu-properties \
bundled-rust-crate-icu-properties-data \
bundled-rust-crate-icu-provider \
bundled-rust-crate-id-arena \
bundled-rust-crate-ident-case \
bundled-rust-crate-idna \
bundled-rust-crate-idna-adapter \
bundled-rust-crate-ignore \
bundled-rust-crate-im \
bundled-rust-crate-im-rc \
bundled-rust-crate-image \
bundled-rust-crate-image-webp \
bundled-rust-crate-imagesize \
bundled-rust-crate-include-dir \
bundled-rust-crate-include-dir-macros \
bundled-rust-crate-indexmap \
bundled-rust-crate-inotify \
bundled-rust-crate-inotify-sys \
bundled-rust-crate-interprocess \
bundled-rust-crate-intmap \
bundled-rust-crate-io-extras \
bundled-rust-crate-io-lifetimes \
bundled-rust-crate-ipnet \
bundled-rust-crate-is-docker \
bundled-rust-crate-is-wsl \
bundled-rust-crate-itertools \
bundled-rust-crate-itoa \
bundled-rust-crate-jobserver \
bundled-rust-crate-jsonrpc-lite \
bundled-rust-crate-khronos-egl \
bundled-rust-crate-kurbo \
bundled-rust-crate-lapce-app \
bundled-rust-crate-lapce-core \
bundled-rust-crate-lapce-proxy \
bundled-rust-crate-lapce-rpc \
bundled-rust-crate-lapce-xi-rope \
bundled-rust-crate-lazy-static \
bundled-rust-crate-leb128 \
bundled-rust-crate-libc \
bundled-rust-crate-libgit2-sys \
bundled-rust-crate-libloading \
bundled-rust-crate-libm \
bundled-rust-crate-libssh2-sys \
bundled-rust-crate-libz-sys \
bundled-rust-crate-linux-raw-sys \
bundled-rust-crate-litemap \
bundled-rust-crate-litrs \
bundled-rust-crate-lock-api \
bundled-rust-crate-log \
bundled-rust-crate-lsp-types \
bundled-rust-crate-maybe-owned \
bundled-rust-crate-memchr \
bundled-rust-crate-memfd \
bundled-rust-crate-memmap2 \
bundled-rust-crate-memoffset \
bundled-rust-crate-mime \
bundled-rust-crate-minimal-lexical \
bundled-rust-crate-miniz-oxide \
bundled-rust-crate-mio \
bundled-rust-crate-naga \
bundled-rust-crate-native-tls \
bundled-rust-crate-nix \
bundled-rust-crate-nom \
bundled-rust-crate-notify \
bundled-rust-crate-nu-ansi-term \
bundled-rust-crate-nucleo \
bundled-rust-crate-nucleo-matcher \
bundled-rust-crate-num-conv \
bundled-rust-crate-num-cpus \
bundled-rust-crate-num-traits \
bundled-rust-crate-object \
bundled-rust-crate-once-cell \
bundled-rust-crate-open \
bundled-rust-crate-openssl \
bundled-rust-crate-openssl-macros \
bundled-rust-crate-openssl-probe \
bundled-rust-crate-openssl-src \
bundled-rust-crate-openssl-sys \
bundled-rust-crate-ordered-float \
bundled-rust-crate-ordered-stream \
bundled-rust-crate-overload \
bundled-rust-crate-owned-ttf-parser \
bundled-rust-crate-parking \
bundled-rust-crate-parking-lot \
bundled-rust-crate-parking-lot-core \
bundled-rust-crate-paste \
bundled-rust-crate-pathdiff \
bundled-rust-crate-peniko \
bundled-rust-crate-percent-encoding \
bundled-rust-crate-pico-args \
bundled-rust-crate-pin-project-lite \
bundled-rust-crate-pin-utils \
bundled-rust-crate-piper \
bundled-rust-crate-pkg-config \
bundled-rust-crate-png \
bundled-rust-crate-polling \
bundled-rust-crate-pollster \
bundled-rust-crate-potential-utf \
bundled-rust-crate-powerfmt \
bundled-rust-crate-ppv-lite86 \
bundled-rust-crate-proc-macro-crate \
bundled-rust-crate-proc-macro2 \
bundled-rust-crate-profiling \
bundled-rust-crate-psp-types \
bundled-rust-crate-pulldown-cmark \
bundled-rust-crate-pulldown-cmark-escape \
bundled-rust-crate-quick-error \
bundled-rust-crate-quick-xml \
bundled-rust-crate-quote \
bundled-rust-crate-rand \
bundled-rust-crate-rand-chacha \
bundled-rust-crate-rand-core \
bundled-rust-crate-rand-xoshiro \
bundled-rust-crate-rangemap \
bundled-rust-crate-raw-window-handle \
bundled-rust-crate-rayon \
bundled-rust-crate-rayon-core \
bundled-rust-crate-read-fonts \
bundled-rust-crate-rect-packer \
bundled-rust-crate-regalloc2 \
bundled-rust-crate-regex \
bundled-rust-crate-regex-automata \
bundled-rust-crate-regex-syntax \
bundled-rust-crate-remain \
bundled-rust-crate-renderdoc-sys \
bundled-rust-crate-reqwest \
bundled-rust-crate-resvg \
bundled-rust-crate-rfd \
bundled-rust-crate-rgb \
bundled-rust-crate-roxmltree \
bundled-rust-crate-rustc-demangle \
bundled-rust-crate-rustc-hash \
bundled-rust-crate-rustc-version \
bundled-rust-crate-rustix \
bundled-rust-crate-rustix-openpty \
bundled-rust-crate-rustls-pemfile \
bundled-rust-crate-rustversion \
bundled-rust-crate-rustybuzz \
bundled-rust-crate-ryu \
bundled-rust-crate-same-file \
bundled-rust-crate-scoped-tls \
bundled-rust-crate-scopeguard \
bundled-rust-crate-sctk-adwaita \
bundled-rust-crate-self-cell \
bundled-rust-crate-semver \
bundled-rust-crate-serde \
bundled-rust-crate-serde-bytes \
bundled-rust-crate-serde-derive \
bundled-rust-crate-serde-json \
bundled-rust-crate-serde-repr \
bundled-rust-crate-serde-spanned \
bundled-rust-crate-serde-urlencoded \
bundled-rust-crate-sha2 \
bundled-rust-crate-sharded-slab \
bundled-rust-crate-shellexpand \
bundled-rust-crate-signal-hook \
bundled-rust-crate-signal-hook-registry \
bundled-rust-crate-simd-adler32 \
bundled-rust-crate-simplecss \
bundled-rust-crate-siphasher \
bundled-rust-crate-sized-chunks \
bundled-rust-crate-skrifa \
bundled-rust-crate-slab \
bundled-rust-crate-slice-group-by \
bundled-rust-crate-slotmap \
bundled-rust-crate-smallvec \
bundled-rust-crate-smithay-client-toolkit \
bundled-rust-crate-smithay-clipboard \
bundled-rust-crate-smol-str \
bundled-rust-crate-socket2 \
bundled-rust-crate-softbuffer \
bundled-rust-crate-spinning \
bundled-rust-crate-spirv \
bundled-rust-crate-sptr \
bundled-rust-crate-stable-deref-trait \
bundled-rust-crate-static-assertions \
bundled-rust-crate-strict-num \
bundled-rust-crate-strsim \
bundled-rust-crate-structdesc \
bundled-rust-crate-strum \
bundled-rust-crate-strum-macros \
bundled-rust-crate-svgtypes \
bundled-rust-crate-swash \
bundled-rust-crate-syn \
bundled-rust-crate-sync-wrapper \
bundled-rust-crate-synstructure \
bundled-rust-crate-sys-locale \
bundled-rust-crate-system-interface \
bundled-rust-crate-taffy \
bundled-rust-crate-tar \
bundled-rust-crate-target-lexicon \
bundled-rust-crate-tempfile \
bundled-rust-crate-termcolor \
bundled-rust-crate-thiserror \
bundled-rust-crate-thiserror-impl \
bundled-rust-crate-thread-local \
bundled-rust-crate-time \
bundled-rust-crate-time-core \
bundled-rust-crate-time-macros \
bundled-rust-crate-tiny-skia \
bundled-rust-crate-tiny-skia-path \
bundled-rust-crate-tiny-xlib \
bundled-rust-crate-tinystr \
bundled-rust-crate-tinyvec \
bundled-rust-crate-tinyvec-macros \
bundled-rust-crate-to-method \
bundled-rust-crate-tokio \
bundled-rust-crate-tokio-macros \
bundled-rust-crate-tokio-native-tls \
bundled-rust-crate-tokio-socks \
bundled-rust-crate-tokio-util \
bundled-rust-crate-toml \
bundled-rust-crate-toml-datetime \
bundled-rust-crate-toml-edit \
bundled-rust-crate-tower-service \
bundled-rust-crate-tracing \
bundled-rust-crate-tracing-appender \
bundled-rust-crate-tracing-attributes \
bundled-rust-crate-tracing-core \
bundled-rust-crate-tracing-log \
bundled-rust-crate-tracing-subscriber \
bundled-rust-crate-trash \
bundled-rust-crate-tree-sitter \
bundled-rust-crate-try-lock \
bundled-rust-crate-ttf-parser \
bundled-rust-crate-typenum \
bundled-rust-crate-unicase \
bundled-rust-crate-unicode-bidi \
bundled-rust-crate-unicode-bidi-mirroring \
bundled-rust-crate-unicode-ccc \
bundled-rust-crate-unicode-ident \
bundled-rust-crate-unicode-linebreak \
bundled-rust-crate-unicode-properties \
bundled-rust-crate-unicode-script \
bundled-rust-crate-unicode-segmentation \
bundled-rust-crate-unicode-vo \
bundled-rust-crate-unicode-width \
bundled-rust-crate-unicode-xid \
bundled-rust-crate-url \
bundled-rust-crate-urlencoding \
bundled-rust-crate-usvg \
bundled-rust-crate-utf8-iter \
bundled-rust-crate-utf8parse \
bundled-rust-crate-uuid \
bundled-rust-crate-vcpkg \
bundled-rust-crate-version-check \
bundled-rust-crate-vte \
bundled-rust-crate-vte-generate-state-changes \
bundled-rust-crate-walkdir \
bundled-rust-crate-want \
bundled-rust-crate-wasi-cap-std-sync \
bundled-rust-crate-wasi-common \
bundled-rust-crate-wasi-experimental-http-wasmtime \
bundled-rust-crate-wasm-encoder \
bundled-rust-crate-wasmparser \
bundled-rust-crate-wasmprinter \
bundled-rust-crate-wasmtime \
bundled-rust-crate-wasmtime-asm-macros \
bundled-rust-crate-wasmtime-cache \
bundled-rust-crate-wasmtime-component-macro \
bundled-rust-crate-wasmtime-component-util \
bundled-rust-crate-wasmtime-cranelift \
bundled-rust-crate-wasmtime-cranelift-shared \
bundled-rust-crate-wasmtime-environ \
bundled-rust-crate-wasmtime-fiber \
bundled-rust-crate-wasmtime-jit \
bundled-rust-crate-wasmtime-jit-debug \
bundled-rust-crate-wasmtime-jit-icache-coherence \
bundled-rust-crate-wasmtime-runtime \
bundled-rust-crate-wasmtime-types \
bundled-rust-crate-wasmtime-versioned-export-macros \
bundled-rust-crate-wasmtime-wasi \
bundled-rust-crate-wasmtime-winch \
bundled-rust-crate-wasmtime-wit-bindgen \
bundled-rust-crate-wasmtime-wmemcheck \
bundled-rust-crate-wast \
bundled-rust-crate-wat \
bundled-rust-crate-wayland-backend \
bundled-rust-crate-wayland-client \
bundled-rust-crate-wayland-csd-frame \
bundled-rust-crate-wayland-cursor \
bundled-rust-crate-wayland-protocols \
bundled-rust-crate-wayland-protocols-plasma \
bundled-rust-crate-wayland-protocols-wlr \
bundled-rust-crate-wayland-scanner \
bundled-rust-crate-wayland-sys \
bundled-rust-crate-weezl \
bundled-rust-crate-wgpu \
bundled-rust-crate-wgpu-core \
bundled-rust-crate-wgpu-hal \
bundled-rust-crate-wgpu-types \
bundled-rust-crate-wiggle \
bundled-rust-crate-wiggle-generate \
bundled-rust-crate-wiggle-macro \
bundled-rust-crate-winch-codegen \
bundled-rust-crate-winit \
bundled-rust-crate-winnow \
bundled-rust-crate-wit-parser \
bundled-rust-crate-witx \
bundled-rust-crate-writeable \
bundled-rust-crate-x11-clipboard \
bundled-rust-crate-x11-dl \
bundled-rust-crate-x11rb \
bundled-rust-crate-x11rb-protocol \
bundled-rust-crate-xattr \
bundled-rust-crate-xcursor \
bundled-rust-crate-xkbcommon-dl \
bundled-rust-crate-xkeysym \
bundled-rust-crate-xmlwriter \
bundled-rust-crate-yazi \
bundled-rust-crate-yoke \
bundled-rust-crate-yoke-derive \
bundled-rust-crate-zbus \
bundled-rust-crate-zbus-macros \
bundled-rust-crate-zbus-names \
bundled-rust-crate-zeno \
bundled-rust-crate-zerocopy \
bundled-rust-crate-zerofrom \
bundled-rust-crate-zerofrom-derive \
bundled-rust-crate-zerotrie \
bundled-rust-crate-zerovec \
bundled-rust-crate-zerovec-derive \
bundled-rust-crate-zip \
bundled-rust-crate-zstd \
bundled-rust-crate-zstd-safe \
bundled-rust-crate-zstd-sys \
bundled-rust-crate-zune-core \
bundled-rust-crate-zune-jpeg \
bundled-rust-crate-zvariant \
bundled-rust-crate-zvariant-derive \
bundled-rust-crate-zvariant-utils \
lapce"

RDEPENDS:${PN} += "libc.so.6 \
libgcc-s.so.1 \
libm.so.6 \
libz.so.1"

inherit rpm
