SUMMARY = "A friendly language for building type-safe, scalable systems!"
DESCRIPTION = "The power of a type system, the expressiveness of functional programming, \
and the reliability of the highly concurrent, fault tolerant Erlang runtime, \
with a familiar and modern syntax."
LICENSE = "Apache-2.0"

PV = "1.18.1"

RPM_NAME = "gleam-1.18.1-1.2.aarch64.rpm"
RPM_HASH = "9144a7ad636037a9ebcf04d5d322bdaaedc12e17c5fbe487db2b388251cc867dda394aa32d7a8468a32bae50672388ea583b669a3564e1b2f4f49d972bc4c7e1"

RPROVIDES:${PN} += "bundled-rust-crate-adler2 \
bundled-rust-crate-aead \
bundled-rust-crate-age \
bundled-rust-crate-age-core \
bundled-rust-crate-aho-corasick \
bundled-rust-crate-anstream \
bundled-rust-crate-anstyle \
bundled-rust-crate-anstyle-parse \
bundled-rust-crate-anstyle-query \
bundled-rust-crate-anyhow \
bundled-rust-crate-arc-swap \
bundled-rust-crate-askama \
bundled-rust-crate-askama-derive \
bundled-rust-crate-askama-macros \
bundled-rust-crate-askama-parser \
bundled-rust-crate-asn1-rs \
bundled-rust-crate-asn1-rs-derive \
bundled-rust-crate-asn1-rs-impl \
bundled-rust-crate-async-trait \
bundled-rust-crate-atomic-waker \
bundled-rust-crate-autocfg \
bundled-rust-crate-aws-lc-rs \
bundled-rust-crate-aws-lc-sys \
bundled-rust-crate-base16 \
bundled-rust-crate-base64 \
bundled-rust-crate-base64-simd \
bundled-rust-crate-basic-toml \
bundled-rust-crate-bech32 \
bundled-rust-crate-bimap \
bundled-rust-crate-bincode \
bundled-rust-crate-bincode-derive \
bundled-rust-crate-bitflags \
bundled-rust-crate-bitmaps \
bundled-rust-crate-bitvec \
bundled-rust-crate-block-buffer \
bundled-rust-crate-bstr \
bundled-rust-crate-bumpalo \
bundled-rust-crate-bytes \
bundled-rust-crate-camino \
bundled-rust-crate-cc \
bundled-rust-crate-cfg-aliases \
bundled-rust-crate-cfg-if \
bundled-rust-crate-chacha20 \
bundled-rust-crate-chacha20poly1305 \
bundled-rust-crate-cipher \
bundled-rust-crate-clap \
bundled-rust-crate-clap-builder \
bundled-rust-crate-clap-derive \
bundled-rust-crate-clap-lex \
bundled-rust-crate-cmake \
bundled-rust-crate-codespan-reporting \
bundled-rust-crate-colorchoice \
bundled-rust-crate-cookie-factory \
bundled-rust-crate-cpufeatures \
bundled-rust-crate-crc32fast \
bundled-rust-crate-crossbeam-channel \
bundled-rust-crate-crossbeam-deque \
bundled-rust-crate-crossbeam-epoch \
bundled-rust-crate-crossbeam-utils \
bundled-rust-crate-crypto-common \
bundled-rust-crate-ctrlc \
bundled-rust-crate-curve25519-dalek \
bundled-rust-crate-dashmap \
bundled-rust-crate-data-encoding \
bundled-rust-crate-debug-ignore \
bundled-rust-crate-debugid \
bundled-rust-crate-der-parser \
bundled-rust-crate-deranged \
bundled-rust-crate-diff \
bundled-rust-crate-digest \
bundled-rust-crate-dirs-next \
bundled-rust-crate-dirs-sys-next \
bundled-rust-crate-displaydoc \
bundled-rust-crate-dunce \
bundled-rust-crate-ecow \
bundled-rust-crate-either \
bundled-rust-crate-endian-type \
bundled-rust-crate-equivalent \
bundled-rust-crate-erlang-generation \
bundled-rust-crate-erlang-term-format \
bundled-rust-crate-errno \
bundled-rust-crate-fastrand \
bundled-rust-crate-filetime \
bundled-rust-crate-find-crate \
bundled-rust-crate-find-msvc-tools \
bundled-rust-crate-fixedbitset \
bundled-rust-crate-flate2 \
bundled-rust-crate-fluent \
bundled-rust-crate-fluent-bundle \
bundled-rust-crate-fluent-langneg \
bundled-rust-crate-fluent-syntax \
bundled-rust-crate-foldhash \
bundled-rust-crate-form-urlencoded \
bundled-rust-crate-fs-extra \
bundled-rust-crate-fslock \
bundled-rust-crate-funty \
bundled-rust-crate-futures \
bundled-rust-crate-futures-channel \
bundled-rust-crate-futures-core \
bundled-rust-crate-futures-executor \
bundled-rust-crate-futures-io \
bundled-rust-crate-futures-macro \
bundled-rust-crate-futures-sink \
bundled-rust-crate-futures-task \
bundled-rust-crate-futures-util \
bundled-rust-crate-gen-lsp-types \
bundled-rust-crate-generic-array \
bundled-rust-crate-getrandom \
bundled-rust-crate-gleam \
bundled-rust-crate-gleam-cli \
bundled-rust-crate-gleam-core \
bundled-rust-crate-gleam-format \
bundled-rust-crate-gleam-language-server \
bundled-rust-crate-glob \
bundled-rust-crate-globset \
bundled-rust-crate-hashbrown \
bundled-rust-crate-heck \
bundled-rust-crate-hexpm \
bundled-rust-crate-hkdf \
bundled-rust-crate-hmac \
bundled-rust-crate-hostname \
bundled-rust-crate-http \
bundled-rust-crate-http-auth-basic \
bundled-rust-crate-http-body \
bundled-rust-crate-http-body-util \
bundled-rust-crate-http-serde \
bundled-rust-crate-httparse \
bundled-rust-crate-hyper \
bundled-rust-crate-hyper-rustls \
bundled-rust-crate-hyper-util \
bundled-rust-crate-i18n-config \
bundled-rust-crate-i18n-embed \
bundled-rust-crate-i18n-embed-fl \
bundled-rust-crate-i18n-embed-impl \
bundled-rust-crate-icu-collections \
bundled-rust-crate-icu-locale-core \
bundled-rust-crate-icu-normalizer \
bundled-rust-crate-icu-normalizer-data \
bundled-rust-crate-icu-properties \
bundled-rust-crate-icu-properties-data \
bundled-rust-crate-icu-provider \
bundled-rust-crate-id-arena \
bundled-rust-crate-idna \
bundled-rust-crate-idna-adapter \
bundled-rust-crate-if-chain \
bundled-rust-crate-ignore \
bundled-rust-crate-im \
bundled-rust-crate-indexmap \
bundled-rust-crate-inout \
bundled-rust-crate-intl-memoizer \
bundled-rust-crate-intl-pluralrules \
bundled-rust-crate-io-tee \
bundled-rust-crate-ipnet \
bundled-rust-crate-iri-string \
bundled-rust-crate-is-terminal-polyfill \
bundled-rust-crate-itertools \
bundled-rust-crate-itoa \
bundled-rust-crate-jobserver \
bundled-rust-crate-lazy-static \
bundled-rust-crate-libc \
bundled-rust-crate-libm \
bundled-rust-crate-linux-raw-sys \
bundled-rust-crate-litemap \
bundled-rust-crate-lock-api \
bundled-rust-crate-log \
bundled-rust-crate-lru-slab \
bundled-rust-crate-lsp-server \
bundled-rust-crate-matchers \
bundled-rust-crate-memchr \
bundled-rust-crate-minimal-lexical \
bundled-rust-crate-miniz-oxide \
bundled-rust-crate-mio \
bundled-rust-crate-multimap \
bundled-rust-crate-nibble-vec \
bundled-rust-crate-nix \
bundled-rust-crate-nom \
bundled-rust-crate-nu-ansi-term \
bundled-rust-crate-num-bigint \
bundled-rust-crate-num-conv \
bundled-rust-crate-num-integer \
bundled-rust-crate-num-traits \
bundled-rust-crate-oid-registry \
bundled-rust-crate-once-cell \
bundled-rust-crate-opaque-debug \
bundled-rust-crate-opener \
bundled-rust-crate-openssl-probe \
bundled-rust-crate-outref \
bundled-rust-crate-parking-lot \
bundled-rust-crate-parking-lot-core \
bundled-rust-crate-pathdiff \
bundled-rust-crate-pbkdf2 \
bundled-rust-crate-percent-encoding \
bundled-rust-crate-petgraph \
bundled-rust-crate-pin-project \
bundled-rust-crate-pin-project-internal \
bundled-rust-crate-pin-project-lite \
bundled-rust-crate-pin-utils \
bundled-rust-crate-poly1305 \
bundled-rust-crate-potential-utf \
bundled-rust-crate-powerfmt \
bundled-rust-crate-ppv-lite86 \
bundled-rust-crate-pretty-arena \
bundled-rust-crate-pretty-assertions \
bundled-rust-crate-prettyplease \
bundled-rust-crate-priority-queue \
bundled-rust-crate-proc-macro-error-attr2 \
bundled-rust-crate-proc-macro-error2 \
bundled-rust-crate-proc-macro2 \
bundled-rust-crate-prost \
bundled-rust-crate-prost-build \
bundled-rust-crate-prost-derive \
bundled-rust-crate-prost-types \
bundled-rust-crate-psm \
bundled-rust-crate-pubgrub \
bundled-rust-crate-pulldown-cmark \
bundled-rust-crate-pulldown-cmark-escape \
bundled-rust-crate-quinn \
bundled-rust-crate-quinn-proto \
bundled-rust-crate-quinn-udp \
bundled-rust-crate-quote \
bundled-rust-crate-radium \
bundled-rust-crate-radix-trie \
bundled-rust-crate-rand \
bundled-rust-crate-rand-chacha \
bundled-rust-crate-rand-core \
bundled-rust-crate-rand-pcg \
bundled-rust-crate-rand-xoshiro \
bundled-rust-crate-regex \
bundled-rust-crate-regex-automata \
bundled-rust-crate-regex-syntax \
bundled-rust-crate-reqwest \
bundled-rust-crate-ring \
bundled-rust-crate-rpassword \
bundled-rust-crate-rtoolbox \
bundled-rust-crate-rust-embed \
bundled-rust-crate-rust-embed-impl \
bundled-rust-crate-rust-embed-utils \
bundled-rust-crate-rustc-hash \
bundled-rust-crate-rustc-version \
bundled-rust-crate-rusticata-macros \
bundled-rust-crate-rustix \
bundled-rust-crate-rustls \
bundled-rust-crate-rustls-native-certs \
bundled-rust-crate-rustls-pki-types \
bundled-rust-crate-rustls-platform-verifier \
bundled-rust-crate-rustls-webpki \
bundled-rust-crate-salsa20 \
bundled-rust-crate-same-file \
bundled-rust-crate-scopeguard \
bundled-rust-crate-scrypt \
bundled-rust-crate-secrecy \
bundled-rust-crate-self-cell \
bundled-rust-crate-semver \
bundled-rust-crate-semver-parser \
bundled-rust-crate-serde \
bundled-rust-crate-serde-core \
bundled-rust-crate-serde-derive \
bundled-rust-crate-serde-json \
bundled-rust-crate-serde-spanned \
bundled-rust-crate-sha2 \
bundled-rust-crate-sharded-slab \
bundled-rust-crate-shlex \
bundled-rust-crate-simd-abstraction \
bundled-rust-crate-simd-adler32 \
bundled-rust-crate-sized-chunks \
bundled-rust-crate-slab \
bundled-rust-crate-smallvec \
bundled-rust-crate-socket2 \
bundled-rust-crate-sourcemap \
bundled-rust-crate-spdx \
bundled-rust-crate-stable-deref-trait \
bundled-rust-crate-stacker \
bundled-rust-crate-strsim \
bundled-rust-crate-strum \
bundled-rust-crate-strum-macros \
bundled-rust-crate-subtle \
bundled-rust-crate-syn \
bundled-rust-crate-sync-wrapper \
bundled-rust-crate-synstructure \
bundled-rust-crate-tap \
bundled-rust-crate-tar \
bundled-rust-crate-tempfile \
bundled-rust-crate-termcolor \
bundled-rust-crate-thiserror \
bundled-rust-crate-thiserror-impl \
bundled-rust-crate-thread-local \
bundled-rust-crate-time \
bundled-rust-crate-time-core \
bundled-rust-crate-time-macros \
bundled-rust-crate-tinystr \
bundled-rust-crate-tinyvec \
bundled-rust-crate-tinyvec-macros \
bundled-rust-crate-tokio \
bundled-rust-crate-tokio-rustls \
bundled-rust-crate-toml \
bundled-rust-crate-toml-datetime \
bundled-rust-crate-toml-edit \
bundled-rust-crate-toml-parser \
bundled-rust-crate-toml-write \
bundled-rust-crate-toml-writer \
bundled-rust-crate-tower \
bundled-rust-crate-tower-http \
bundled-rust-crate-tower-layer \
bundled-rust-crate-tower-service \
bundled-rust-crate-tracing \
bundled-rust-crate-tracing-attributes \
bundled-rust-crate-tracing-core \
bundled-rust-crate-tracing-log \
bundled-rust-crate-tracing-subscriber \
bundled-rust-crate-try-lock \
bundled-rust-crate-type-map \
bundled-rust-crate-typed-arena \
bundled-rust-crate-typed-path \
bundled-rust-crate-typenum \
bundled-rust-crate-unic-langid \
bundled-rust-crate-unic-langid-impl \
bundled-rust-crate-unicase \
bundled-rust-crate-unicode-id-start \
bundled-rust-crate-unicode-ident \
bundled-rust-crate-unicode-segmentation \
bundled-rust-crate-unicode-width \
bundled-rust-crate-universal-hash \
bundled-rust-crate-untrusted \
bundled-rust-crate-unty \
bundled-rust-crate-url \
bundled-rust-crate-utf8-iter \
bundled-rust-crate-utf8parse \
bundled-rust-crate-uuid \
bundled-rust-crate-vec1 \
bundled-rust-crate-version-check \
bundled-rust-crate-version-ranges \
bundled-rust-crate-virtue \
bundled-rust-crate-walkdir \
bundled-rust-crate-want \
bundled-rust-crate-winnow \
bundled-rust-crate-writeable \
bundled-rust-crate-wyz \
bundled-rust-crate-x25519-dalek \
bundled-rust-crate-x509-parser \
bundled-rust-crate-xattr \
bundled-rust-crate-xxhash-rust \
bundled-rust-crate-yansi \
bundled-rust-crate-yoke \
bundled-rust-crate-yoke-derive \
bundled-rust-crate-zerofrom \
bundled-rust-crate-zerofrom-derive \
bundled-rust-crate-zeroize \
bundled-rust-crate-zeroize-derive \
bundled-rust-crate-zerotrie \
bundled-rust-crate-zerovec \
bundled-rust-crate-zerovec-derive \
bundled-rust-crate-zip \
bundled-rust-crate-zlib-rs \
bundled-rust-crate-zmij \
bundled-rust-crate-zopfli \
gleam"

RDEPENDS:${PN} += "erlang \
erlang-rebar3 \
libc.so.6 \
libgcc-s.so.1 \
libm.so.6"

inherit rpm
