SUMMARY = "Extensible Virtual Display Interface (EVDI) is a Linux Kernel Module"
DESCRIPTION = "The Extensible Virtual Display Interface (EVDI) is a Linux kernel module \
that enables management of multiple screens, allowing user-space programs \
to take control over what happens with the image. It is essentially \
a virtual display you can add, remove and receive screen updates for, in \
an application that uses the libevdi library."
LICENSE = "GPL-2.0-only & LGPL-2.1-only"

PV = "1.15.0_k7.2.4_1"

RPM_NAME = "evdi-kmp-64kb-1.15.0_k7.2.4_1-1.2.aarch64.rpm"
RPM_HASH = "1aea8ff7574e29445a5bfa7110ce58bef193c833fb75edbbbb1867751d9308510285f1cfdb06395501a85e6d6c9abcdeddbb42309dcc0887dee4e293634a9b38"

RPROVIDES:${PN} += "evdi-kmp \
evdi-kmp-64kb \
evdi-kmp-64kb-k7.2.4-1 \
kmod-evdi.ko \
multiversion-kernel"

RDEPENDS:${PN} += "/usr/bin/sh \
coreutils \
grep \
kernel-64kb \
ksym-64kb---arch-copy-from-user \
ksym-64kb---arch-copy-to-user \
ksym-64kb---check-object-size \
ksym-64kb---copy-overflow \
ksym-64kb---drm-dev-dbg \
ksym-64kb---drm-err \
ksym-64kb---drmm-add-action-or-reset \
ksym-64kb---fortify-panic \
ksym-64kb---init-swait-queue-head \
ksym-64kb---kmalloc-cache-noprof \
ksym-64kb---kmalloc-noprof \
ksym-64kb---kvmalloc-node-noprof \
ksym-64kb---list-add-valid-or-report \
ksym-64kb---list-del-entry-valid-or-report \
ksym-64kb---platform-driver-register \
ksym-64kb---root-device-register \
ksym-64kb---sg-page-iter-next \
ksym-64kb---sg-page-iter-start \
ksym-64kb---stack-chk-fail \
ksym-64kb---vma-start-write \
ksym-64kb---warn-printk \
ksym-64kb--printk \
ksym-64kb--raw-spin-lock \
ksym-64kb--raw-spin-lock-irqsave \
ksym-64kb--raw-spin-unlock \
ksym-64kb--raw-spin-unlock-irqrestore \
ksym-64kb-alt-cb-patch-nops \
ksym-64kb-arm64-use-ng-mappings \
ksym-64kb-cancel-delayed-work-sync \
ksym-64kb-complete \
ksym-64kb-debugfs-attr-read \
ksym-64kb-debugfs-attr-write \
ksym-64kb-debugfs-create-file-full \
ksym-64kb-debugfs-lookup-and-remove \
ksym-64kb-delayed-work-timer-fn \
ksym-64kb-device-create-file \
ksym-64kb-device-remove-file \
ksym-64kb-dma-buf-begin-cpu-access \
ksym-64kb-dma-buf-end-cpu-access \
ksym-64kb-dma-buf-vmap-unlocked \
ksym-64kb-dma-buf-vunmap-unlocked \
ksym-64kb-dma-set-mask \
ksym-64kb-drm-add-edid-modes \
ksym-64kb-drm-atomic-helper-check \
ksym-64kb-drm-atomic-helper-commit \
ksym-64kb-drm-atomic-helper-connector-destroy-state \
ksym-64kb-drm-atomic-helper-connector-duplicate-state \
ksym-64kb-drm-atomic-helper-connector-reset \
ksym-64kb-drm-atomic-helper-crtc-destroy-state \
ksym-64kb-drm-atomic-helper-crtc-duplicate-state \
ksym-64kb-drm-atomic-helper-crtc-reset \
ksym-64kb-drm-atomic-helper-damage-iter-init \
ksym-64kb-drm-atomic-helper-damage-iter-next \
ksym-64kb-drm-atomic-helper-dirtyfb \
ksym-64kb-drm-atomic-helper-disable-plane \
ksym-64kb-drm-atomic-helper-page-flip \
ksym-64kb-drm-atomic-helper-plane-destroy-state \
ksym-64kb-drm-atomic-helper-plane-duplicate-state \
ksym-64kb-drm-atomic-helper-plane-reset \
ksym-64kb-drm-atomic-helper-set-config \
ksym-64kb-drm-atomic-helper-shutdown \
ksym-64kb-drm-atomic-helper-update-plane \
ksym-64kb-drm-compat-ioctl \
ksym-64kb-drm-connector-attach-encoder \
ksym-64kb-drm-connector-cleanup \
ksym-64kb-drm-connector-init \
ksym-64kb-drm-connector-register \
ksym-64kb-drm-connector-unregister \
ksym-64kb-drm-connector-update-edid-property \
ksym-64kb-drm-crtc-cleanup \
ksym-64kb-drm-crtc-init-with-planes \
ksym-64kb-drm-crtc-send-vblank-event \
ksym-64kb-drm-crtc-vblank-off \
ksym-64kb-drm-dev-alloc \
ksym-64kb-drm-dev-put \
ksym-64kb-drm-dev-register \
ksym-64kb-drm-dev-unplug \
ksym-64kb-drm-encoder-cleanup \
ksym-64kb-drm-encoder-init \
ksym-64kb-drm-event-cancel-free \
ksym-64kb-drm-event-reserve-init-locked \
ksym-64kb-drm-format-info \
ksym-64kb-drm-framebuffer-cleanup \
ksym-64kb-drm-framebuffer-init \
ksym-64kb-drm-framebuffer-lookup \
ksym-64kb-drm-gem-create-mmap-offset \
ksym-64kb-drm-gem-dmabuf-vmap \
ksym-64kb-drm-gem-fb-begin-cpu-access \
ksym-64kb-drm-gem-fb-end-cpu-access \
ksym-64kb-drm-gem-free-mmap-offset \
ksym-64kb-drm-gem-get-pages \
ksym-64kb-drm-gem-handle-create \
ksym-64kb-drm-gem-mmap \
ksym-64kb-drm-gem-object-free \
ksym-64kb-drm-gem-object-init \
ksym-64kb-drm-gem-object-lookup \
ksym-64kb-drm-gem-object-release \
ksym-64kb-drm-gem-plane-helper-prepare-fb \
ksym-64kb-drm-gem-prime-export \
ksym-64kb-drm-gem-prime-fd-to-handle \
ksym-64kb-drm-gem-prime-handle-to-fd \
ksym-64kb-drm-gem-prime-import \
ksym-64kb-drm-gem-put-pages \
ksym-64kb-drm-gem-ttm-vmap \
ksym-64kb-drm-gem-ttm-vunmap \
ksym-64kb-drm-gem-vm-close \
ksym-64kb-drm-gem-vm-open \
ksym-64kb-drm-get-format-info \
ksym-64kb-drm-helper-hpd-irq-event \
ksym-64kb-drm-helper-mode-fill-fb-struct \
ksym-64kb-drm-helper-probe-single-connector-modes \
ksym-64kb-drm-ioctl \
ksym-64kb-drm-ioctl-kernel \
ksym-64kb-drm-kms-helper-poll-fini \
ksym-64kb-drm-kms-helper-poll-init \
ksym-64kb-drm-mode-config-reset \
ksym-64kb-drm-mode-object-get \
ksym-64kb-drm-mode-object-put \
ksym-64kb-drm-mode-vrefresh \
ksym-64kb-drm-open \
ksym-64kb-drm-plane-cleanup \
ksym-64kb-drm-plane-enable-fb-damage-clips \
ksym-64kb-drm-poll \
ksym-64kb-drm-prime-gem-destroy \
ksym-64kb-drm-prime-pages-to-sg \
ksym-64kb-drm-prime-sg-to-page-array \
ksym-64kb-drm-read \
ksym-64kb-drm-release \
ksym-64kb-drm-send-event-locked \
ksym-64kb-drm-universal-plane-init \
ksym-64kb-drm-vblank-init \
ksym-64kb-drmm-mode-config-init \
ksym-64kb-fg-console \
ksym-64kb-i2c-add-adapter \
ksym-64kb-i2c-del-adapter \
ksym-64kb-idr-get-next \
ksym-64kb-kfree \
ksym-64kb-kmalloc-caches \
ksym-64kb-kstrdup \
ksym-64kb-kstrtouint \
ksym-64kb-ktime-get \
ksym-64kb-kvfree \
ksym-64kb-memcpy \
ksym-64kb-memset \
ksym-64kb-module-layout \
ksym-64kb-mutex-init-generic \
ksym-64kb-mutex-lock \
ksym-64kb-mutex-unlock \
ksym-64kb-noop-llseek \
ksym-64kb-param-ops-int \
ksym-64kb-param-ops-ushort \
ksym-64kb-platform-device-register-full \
ksym-64kb-platform-device-unregister \
ksym-64kb-platform-driver-unregister \
ksym-64kb-queue-delayed-work-on \
ksym-64kb-random-kmalloc-seed \
ksym-64kb-refcount-warn-saturate \
ksym-64kb-register-vt-notifier \
ksym-64kb-root-device-unregister \
ksym-64kb-simple-attr-open \
ksym-64kb-simple-attr-release \
ksym-64kb-sized-strscpy \
ksym-64kb-snprintf \
ksym-64kb-strcmp \
ksym-64kb-strim \
ksym-64kb-strncmp \
ksym-64kb-strnlen \
ksym-64kb-strnstr \
ksym-64kb-strsep \
ksym-64kb-sysfs-create-link \
ksym-64kb-sysfs-remove-link \
ksym-64kb-system-percpu-wq \
ksym-64kb-timer-init-key \
ksym-64kb-unregister-vt-notifier \
ksym-64kb-usb-for-each-dev \
ksym-64kb-usb-register-notify \
ksym-64kb-usb-unregister-notify \
ksym-64kb-validate-usercopy-range \
ksym-64kb-vfree \
ksym-64kb-vm-insert-page \
ksym-64kb-vmalloc-noprof \
ksym-64kb-vmap \
ksym-64kb-vunmap \
ksym-64kb-wait-for-completion-interruptible-timeout \
ksym-64kb-ww-mutex-lock \
ksym-64kb-ww-mutex-unlock \
suse-kernel-rpm-scriptlets"

inherit rpm
