SUMMARY = "Isolate an arbitrary application over the Tor network"
DESCRIPTION = "This is still considered experimental software! \
oniux is a tool that utilizes various Linux namespaces(7) in order to isolate \
an arbitrary application over the Tor network. To achieve this, it makes heavy \
use of the onionmasq, which offers a TUN device to send Tor traffic through."
LICENSE = "Apache-2.0 | MIT"

PV = "0.12.0~0"

RPM_NAME = "oniux-0.12.0~0-1.2.aarch64.rpm"
RPM_HASH = "e1478e3d5870316493a285abbaf181f2131d302845beb1b2efc5941e935d2f62b5b2b79dca17206f661f7f12a6d15effa71fd5ff54a91846edc142496cd10cd1"

RPROVIDES:${PN} += "bundled-rust-crate-adler2 \
bundled-rust-crate-aes \
bundled-rust-crate-ahash \
bundled-rust-crate-aho-corasick \
bundled-rust-crate-allocator-api2 \
bundled-rust-crate-amplify \
bundled-rust-crate-amplify-derive \
bundled-rust-crate-amplify-num \
bundled-rust-crate-amplify-syn \
bundled-rust-crate-anstream \
bundled-rust-crate-anstyle \
bundled-rust-crate-anstyle-parse \
bundled-rust-crate-anstyle-query \
bundled-rust-crate-anyhow \
bundled-rust-crate-arrayvec \
bundled-rust-crate-arti \
bundled-rust-crate-arti-client \
bundled-rust-crate-ascii \
bundled-rust-crate-asn1-rs \
bundled-rust-crate-asn1-rs-derive \
bundled-rust-crate-asn1-rs-impl \
bundled-rust-crate-assert-matches \
bundled-rust-crate-async-compression \
bundled-rust-crate-async-executors \
bundled-rust-crate-async-native-tls \
bundled-rust-crate-async-trait \
bundled-rust-crate-asynchronous-codec \
bundled-rust-crate-atomic \
bundled-rust-crate-autocfg \
bundled-rust-crate-aws-lc-rs \
bundled-rust-crate-aws-lc-sys \
bundled-rust-crate-base16ct \
bundled-rust-crate-base64 \
bundled-rust-crate-base64ct \
bundled-rust-crate-bbqueue \
bundled-rust-crate-bincode \
bundled-rust-crate-bitflags \
bundled-rust-crate-bitvec \
bundled-rust-crate-blanket \
bundled-rust-crate-block-buffer \
bundled-rust-crate-bs58 \
bundled-rust-crate-bstr \
bundled-rust-crate-by-address \
bundled-rust-crate-byteorder \
bundled-rust-crate-bytes \
bundled-rust-crate-cached \
bundled-rust-crate-cached-proc-macro \
bundled-rust-crate-cached-proc-macro-types \
bundled-rust-crate-caps \
bundled-rust-crate-caret \
bundled-rust-crate-cc \
bundled-rust-crate-cfg-aliases \
bundled-rust-crate-cfg-if \
bundled-rust-crate-chacha20 \
bundled-rust-crate-chrono \
bundled-rust-crate-cipher \
bundled-rust-crate-clap \
bundled-rust-crate-clap-builder \
bundled-rust-crate-clap-derive \
bundled-rust-crate-clap-lex \
bundled-rust-crate-cmake \
bundled-rust-crate-coarsetime \
bundled-rust-crate-colorchoice \
bundled-rust-crate-const-oid \
bundled-rust-crate-convert-case \
bundled-rust-crate-cookie-factory \
bundled-rust-crate-cpufeatures \
bundled-rust-crate-crc32fast \
bundled-rust-crate-critical-section \
bundled-rust-crate-crossbeam-channel \
bundled-rust-crate-crossbeam-queue \
bundled-rust-crate-crossbeam-utils \
bundled-rust-crate-crypto-bigint \
bundled-rust-crate-crypto-common \
bundled-rust-crate-ctr \
bundled-rust-crate-curve25519-dalek \
bundled-rust-crate-darling \
bundled-rust-crate-darling-core \
bundled-rust-crate-darling-macro \
bundled-rust-crate-data-encoding \
bundled-rust-crate-defmt \
bundled-rust-crate-defmt-macros \
bundled-rust-crate-defmt-parser \
bundled-rust-crate-der \
bundled-rust-crate-der-parser \
bundled-rust-crate-deranged \
bundled-rust-crate-derive-builder-core-fork-arti \
bundled-rust-crate-derive-builder-fork-arti \
bundled-rust-crate-derive-builder-macro-fork-arti \
bundled-rust-crate-derive-deftly \
bundled-rust-crate-derive-deftly-macros \
bundled-rust-crate-derive-more \
bundled-rust-crate-derive-more-impl \
bundled-rust-crate-digest \
bundled-rust-crate-directories \
bundled-rust-crate-dirs \
bundled-rust-crate-dirs-sys \
bundled-rust-crate-displaydoc \
bundled-rust-crate-dns-message-parser \
bundled-rust-crate-downcast-rs \
bundled-rust-crate-dunce \
bundled-rust-crate-dyn-clone \
bundled-rust-crate-ecdsa \
bundled-rust-crate-ed25519 \
bundled-rust-crate-ed25519-dalek \
bundled-rust-crate-educe \
bundled-rust-crate-either \
bundled-rust-crate-elliptic-curve \
bundled-rust-crate-enum-dispatch \
bundled-rust-crate-enum-ordinalize \
bundled-rust-crate-enumset \
bundled-rust-crate-enumset-derive \
bundled-rust-crate-equivalent \
bundled-rust-crate-errno \
bundled-rust-crate-event-listener \
bundled-rust-crate-fallible-iterator \
bundled-rust-crate-fallible-streaming-iterator \
bundled-rust-crate-fastrand \
bundled-rust-crate-ff \
bundled-rust-crate-figment \
bundled-rust-crate-filetime \
bundled-rust-crate-find-msvc-tools \
bundled-rust-crate-flate2 \
bundled-rust-crate-fluid-let \
bundled-rust-crate-fnv \
bundled-rust-crate-foldhash \
bundled-rust-crate-foreign-types \
bundled-rust-crate-foreign-types-shared \
bundled-rust-crate-form-urlencoded \
bundled-rust-crate-fs-extra \
bundled-rust-crate-fs-mistrust \
bundled-rust-crate-fslock-guard \
bundled-rust-crate-funty \
bundled-rust-crate-futures \
bundled-rust-crate-futures-channel \
bundled-rust-crate-futures-copy \
bundled-rust-crate-futures-core \
bundled-rust-crate-futures-executor \
bundled-rust-crate-futures-io \
bundled-rust-crate-futures-macro \
bundled-rust-crate-futures-rustls \
bundled-rust-crate-futures-sink \
bundled-rust-crate-futures-task \
bundled-rust-crate-futures-util \
bundled-rust-crate-generic-array \
bundled-rust-crate-getrandom \
bundled-rust-crate-getset \
bundled-rust-crate-glob-match \
bundled-rust-crate-group \
bundled-rust-crate-hash32 \
bundled-rust-crate-hashbrown \
bundled-rust-crate-hashlink \
bundled-rust-crate-heapless \
bundled-rust-crate-heck \
bundled-rust-crate-hex \
bundled-rust-crate-hickory-proto \
bundled-rust-crate-hkdf \
bundled-rust-crate-hmac \
bundled-rust-crate-hostname-validator \
bundled-rust-crate-http \
bundled-rust-crate-httparse \
bundled-rust-crate-httpdate \
bundled-rust-crate-humantime \
bundled-rust-crate-humantime-serde \
bundled-rust-crate-hybrid-array \
bundled-rust-crate-iana-time-zone \
bundled-rust-crate-icu-collections \
bundled-rust-crate-icu-locale-core \
bundled-rust-crate-icu-normalizer \
bundled-rust-crate-icu-normalizer-data \
bundled-rust-crate-icu-properties \
bundled-rust-crate-icu-properties-data \
bundled-rust-crate-icu-provider \
bundled-rust-crate-ident-case \
bundled-rust-crate-idna \
bundled-rust-crate-idna-adapter \
bundled-rust-crate-imara-diff \
bundled-rust-crate-indexmap \
bundled-rust-crate-inotify \
bundled-rust-crate-inotify-sys \
bundled-rust-crate-inout \
bundled-rust-crate-inventory \
bundled-rust-crate-ipnet \
bundled-rust-crate-is-terminal-polyfill \
bundled-rust-crate-itertools \
bundled-rust-crate-itoa \
bundled-rust-crate-jobserver \
bundled-rust-crate-keccak \
bundled-rust-crate-lazy-static \
bundled-rust-crate-libc \
bundled-rust-crate-libm \
bundled-rust-crate-libsqlite3-sys \
bundled-rust-crate-linux-raw-sys \
bundled-rust-crate-litemap \
bundled-rust-crate-lock-api \
bundled-rust-crate-log \
bundled-rust-crate-lzma-sys \
bundled-rust-crate-managed \
bundled-rust-crate-matchers \
bundled-rust-crate-memchr \
bundled-rust-crate-memmap2 \
bundled-rust-crate-merlin \
bundled-rust-crate-minimal-lexical \
bundled-rust-crate-miniz-oxide \
bundled-rust-crate-mio \
bundled-rust-crate-native-tls \
bundled-rust-crate-netlink-packet-core \
bundled-rust-crate-netlink-packet-route \
bundled-rust-crate-netlink-sys \
bundled-rust-crate-nix \
bundled-rust-crate-nom \
bundled-rust-crate-nonany \
bundled-rust-crate-notify \
bundled-rust-crate-notify-types \
bundled-rust-crate-nu-ansi-term \
bundled-rust-crate-num-bigint \
bundled-rust-crate-num-bigint-dig \
bundled-rust-crate-num-conv \
bundled-rust-crate-num-enum \
bundled-rust-crate-num-enum-derive \
bundled-rust-crate-num-integer \
bundled-rust-crate-num-iter \
bundled-rust-crate-num-traits \
bundled-rust-crate-once-cell \
bundled-rust-crate-oneshot-fused-workaround \
bundled-rust-crate-onion-tunnel \
bundled-rust-crate-onionmasq-device-testing \
bundled-rust-crate-oniux \
bundled-rust-crate-openssl \
bundled-rust-crate-openssl-macros \
bundled-rust-crate-openssl-probe \
bundled-rust-crate-openssl-src \
bundled-rust-crate-openssl-sys \
bundled-rust-crate-option-ext \
bundled-rust-crate-ordered-float \
bundled-rust-crate-os-str-bytes \
bundled-rust-crate-p256 \
bundled-rust-crate-p384 \
bundled-rust-crate-p521 \
bundled-rust-crate-parking \
bundled-rust-crate-parking-lot \
bundled-rust-crate-parking-lot-core \
bundled-rust-crate-paste \
bundled-rust-crate-pem-rfc7468 \
bundled-rust-crate-percent-encoding \
bundled-rust-crate-phf \
bundled-rust-crate-phf-generator \
bundled-rust-crate-phf-macros \
bundled-rust-crate-phf-shared \
bundled-rust-crate-pin-project \
bundled-rust-crate-pin-project-internal \
bundled-rust-crate-pin-project-lite \
bundled-rust-crate-pkcs1 \
bundled-rust-crate-pkcs8 \
bundled-rust-crate-pkg-config \
bundled-rust-crate-portable-atomic \
bundled-rust-crate-postage \
bundled-rust-crate-potential-utf \
bundled-rust-crate-powerfmt \
bundled-rust-crate-ppv-lite86 \
bundled-rust-crate-primeorder \
bundled-rust-crate-priority-queue \
bundled-rust-crate-proc-macro-crate \
bundled-rust-crate-proc-macro2 \
bundled-rust-crate-pwd-grp \
bundled-rust-crate-quote \
bundled-rust-crate-radium \
bundled-rust-crate-rand \
bundled-rust-crate-rand-chacha \
bundled-rust-crate-rand-core \
bundled-rust-crate-rand-jitter \
bundled-rust-crate-rangemap \
bundled-rust-crate-ref-cast \
bundled-rust-crate-ref-cast-impl \
bundled-rust-crate-regex \
bundled-rust-crate-regex-automata \
bundled-rust-crate-regex-syntax \
bundled-rust-crate-reseeding-rng \
bundled-rust-crate-retry-error \
bundled-rust-crate-rfc6979 \
bundled-rust-crate-ring \
bundled-rust-crate-rlimit \
bundled-rust-crate-rsa \
bundled-rust-crate-rusqlite \
bundled-rust-crate-rustc-version \
bundled-rust-crate-rusticata-macros \
bundled-rust-crate-rustix \
bundled-rust-crate-rustix-linux-procfs \
bundled-rust-crate-rustls \
bundled-rust-crate-rustls-pki-types \
bundled-rust-crate-rustls-webpki \
bundled-rust-crate-rustversion \
bundled-rust-crate-safelog \
bundled-rust-crate-same-file \
bundled-rust-crate-sanitize-filename \
bundled-rust-crate-saturating-time \
bundled-rust-crate-schemars \
bundled-rust-crate-scopeguard \
bundled-rust-crate-sec1 \
bundled-rust-crate-secmem-proc \
bundled-rust-crate-semver \
bundled-rust-crate-sendfd \
bundled-rust-crate-serde \
bundled-rust-crate-serde-core \
bundled-rust-crate-serde-derive \
bundled-rust-crate-serde-ignored \
bundled-rust-crate-serde-json \
bundled-rust-crate-serde-spanned \
bundled-rust-crate-serde-value \
bundled-rust-crate-serde-with \
bundled-rust-crate-serde-with-macros \
bundled-rust-crate-sha1 \
bundled-rust-crate-sha2 \
bundled-rust-crate-sha3 \
bundled-rust-crate-sharded-slab \
bundled-rust-crate-shellexpand \
bundled-rust-crate-shlex \
bundled-rust-crate-signal-hook-registry \
bundled-rust-crate-signature \
bundled-rust-crate-simd-adler32 \
bundled-rust-crate-simple-proc-net \
bundled-rust-crate-siphasher \
bundled-rust-crate-slab \
bundled-rust-crate-slotmap \
bundled-rust-crate-slotmap-careful \
bundled-rust-crate-smallvec \
bundled-rust-crate-smoltcp \
bundled-rust-crate-socket2 \
bundled-rust-crate-spin \
bundled-rust-crate-spki \
bundled-rust-crate-sponge-cursor \
bundled-rust-crate-ssh-cipher-fork-arti \
bundled-rust-crate-ssh-encoding-fork-arti \
bundled-rust-crate-ssh-key-fork-arti \
bundled-rust-crate-stable-deref-trait \
bundled-rust-crate-static-assertions \
bundled-rust-crate-strsim \
bundled-rust-crate-strum \
bundled-rust-crate-strum-macros \
bundled-rust-crate-subtle \
bundled-rust-crate-symlink \
bundled-rust-crate-syn \
bundled-rust-crate-sync-wrapper \
bundled-rust-crate-synstructure \
bundled-rust-crate-sysinfo \
bundled-rust-crate-tap \
bundled-rust-crate-tempfile \
bundled-rust-crate-terminal-size \
bundled-rust-crate-thiserror \
bundled-rust-crate-thiserror-impl \
bundled-rust-crate-thread-local \
bundled-rust-crate-time \
bundled-rust-crate-time-core \
bundled-rust-crate-time-macros \
bundled-rust-crate-tinystr \
bundled-rust-crate-tinyvec \
bundled-rust-crate-tinyvec-macros \
bundled-rust-crate-tokio \
bundled-rust-crate-tokio-macros \
bundled-rust-crate-tokio-util \
bundled-rust-crate-toml \
bundled-rust-crate-toml-datetime \
bundled-rust-crate-toml-edit \
bundled-rust-crate-toml-parser \
bundled-rust-crate-toml-write \
bundled-rust-crate-toml-writer \
bundled-rust-crate-tor-async-utils \
bundled-rust-crate-tor-basic-utils \
bundled-rust-crate-tor-bytes \
bundled-rust-crate-tor-cell \
bundled-rust-crate-tor-cert \
bundled-rust-crate-tor-chanmgr \
bundled-rust-crate-tor-checkable \
bundled-rust-crate-tor-circmgr \
bundled-rust-crate-tor-config \
bundled-rust-crate-tor-config-path \
bundled-rust-crate-tor-consdiff \
bundled-rust-crate-tor-dirclient \
bundled-rust-crate-tor-dircommon \
bundled-rust-crate-tor-dirmgr \
bundled-rust-crate-tor-error \
bundled-rust-crate-tor-general-addr \
bundled-rust-crate-tor-geoip \
bundled-rust-crate-tor-geoip-db \
bundled-rust-crate-tor-guardmgr \
bundled-rust-crate-tor-hsclient \
bundled-rust-crate-tor-hscrypto \
bundled-rust-crate-tor-key-forge \
bundled-rust-crate-tor-keymgr \
bundled-rust-crate-tor-linkspec \
bundled-rust-crate-tor-llcrypto \
bundled-rust-crate-tor-log-ratelim \
bundled-rust-crate-tor-memquota \
bundled-rust-crate-tor-memquota-cost \
bundled-rust-crate-tor-netdir \
bundled-rust-crate-tor-netdoc \
bundled-rust-crate-tor-persist \
bundled-rust-crate-tor-proto \
bundled-rust-crate-tor-protover \
bundled-rust-crate-tor-ptmgr \
bundled-rust-crate-tor-relay-selection \
bundled-rust-crate-tor-rtcompat \
bundled-rust-crate-tor-rtmock \
bundled-rust-crate-tor-socksproto \
bundled-rust-crate-tor-units \
bundled-rust-crate-tracing \
bundled-rust-crate-tracing-appender \
bundled-rust-crate-tracing-attributes \
bundled-rust-crate-tracing-core \
bundled-rust-crate-tracing-log \
bundled-rust-crate-tracing-subscriber \
bundled-rust-crate-tracing-test \
bundled-rust-crate-tracing-test-macro \
bundled-rust-crate-typed-index-collections \
bundled-rust-crate-typenum \
bundled-rust-crate-uncased \
bundled-rust-crate-unicode-ident \
bundled-rust-crate-unicode-segmentation \
bundled-rust-crate-unicode-xid \
bundled-rust-crate-untrusted \
bundled-rust-crate-unty \
bundled-rust-crate-url \
bundled-rust-crate-utf8-iter \
bundled-rust-crate-utf8parse \
bundled-rust-crate-vcpkg \
bundled-rust-crate-version-check \
bundled-rust-crate-visibility \
bundled-rust-crate-void \
bundled-rust-crate-walkdir \
bundled-rust-crate-weak-table \
bundled-rust-crate-web-time \
bundled-rust-crate-web-time-compat \
bundled-rust-crate-winnow \
bundled-rust-crate-writeable \
bundled-rust-crate-wyz \
bundled-rust-crate-x25519-dalek \
bundled-rust-crate-xz2 \
bundled-rust-crate-yoke \
bundled-rust-crate-yoke-derive \
bundled-rust-crate-zerocopy \
bundled-rust-crate-zerofrom \
bundled-rust-crate-zerofrom-derive \
bundled-rust-crate-zeroize \
bundled-rust-crate-zeroize-derive \
bundled-rust-crate-zerotrie \
bundled-rust-crate-zerovec \
bundled-rust-crate-zerovec-derive \
bundled-rust-crate-zmij \
bundled-rust-crate-zstd \
bundled-rust-crate-zstd-safe \
bundled-rust-crate-zstd-sys \
oniux"

RDEPENDS:${PN} += "libc.so.6 \
libgcc-s.so.1 \
libm.so.6"

inherit rpm
