SUMMARY = "Development files for ocaml-ctypes"
DESCRIPTION = "The ocaml-ctypes-devel package contains libraries and signature files for \
developing applications that use ocaml-ctypes."
LICENSE = "ISC"

PV = "0.24.0"

RPM_NAME = "ocaml-ctypes-devel-0.24.0-2.3.aarch64.rpm"
RPM_HASH = "ff16675c935235813d6dd44177495163cea0f3787029922799efa768674ad02ef6960ff5bd5d92afb8f04ae396371b19b70c191287131e7ba1798dc80b8ba286"

RPROVIDES:${PN} += "config-ocaml-ctypes-devel \
ocaml-ComplexL \
ocaml-Cstubs \
ocaml-Cstubs-analysis \
ocaml-Cstubs-c-language \
ocaml-Cstubs-emit-c \
ocaml-Cstubs-errors \
ocaml-Cstubs-generate-c \
ocaml-Cstubs-generate-ml \
ocaml-Cstubs-internals \
ocaml-Cstubs-inverted \
ocaml-Cstubs-public-name \
ocaml-Cstubs-structs \
ocaml-Ctypes \
ocaml-Ctypes-bigarray \
ocaml-Ctypes-bigarray-stubs \
ocaml-Ctypes-closure-properties \
ocaml-Ctypes-coerce \
ocaml-Ctypes-ffi \
ocaml-Ctypes-ffi-stubs \
ocaml-Ctypes-foreign-basis \
ocaml-Ctypes-foreign-threaded-stubs \
ocaml-Ctypes-memory \
ocaml-Ctypes-memory-stubs \
ocaml-Ctypes-path \
ocaml-Ctypes-primitive-types \
ocaml-Ctypes-primitives \
ocaml-Ctypes-ptr \
ocaml-Ctypes-roots-stubs \
ocaml-Ctypes-static \
ocaml-Ctypes-std-view-stubs \
ocaml-Ctypes-std-views \
ocaml-Ctypes-structs \
ocaml-Ctypes-structs-computed \
ocaml-Ctypes-top \
ocaml-Ctypes-top--Install-ctypes-printers \
ocaml-Ctypes-type-printing \
ocaml-Ctypes-types \
ocaml-Ctypes-value-printing \
ocaml-Ctypes-value-printing-stubs \
ocaml-Ctypes-weak-ref \
ocaml-Dl \
ocaml-Foreign \
ocaml-LDouble \
ocaml-Libffi-abi \
ocaml-PosixTypes \
ocaml-ctypes-devel \
ocamlfind-ctypes \
ocamlfind-ctypes-foreign \
ocamlfind-ctypes.stubs \
ocamlfind-ctypes.top \
ocamlx-ComplexL \
ocamlx-Cstubs \
ocamlx-Cstubs-analysis \
ocamlx-Cstubs-c-language \
ocamlx-Cstubs-emit-c \
ocamlx-Cstubs-errors \
ocamlx-Cstubs-generate-c \
ocamlx-Cstubs-generate-ml \
ocamlx-Cstubs-internals \
ocamlx-Cstubs-inverted \
ocamlx-Cstubs-public-name \
ocamlx-Cstubs-structs \
ocamlx-Ctypes \
ocamlx-Ctypes-bigarray \
ocamlx-Ctypes-bigarray-stubs \
ocamlx-Ctypes-closure-properties \
ocamlx-Ctypes-coerce \
ocamlx-Ctypes-ffi \
ocamlx-Ctypes-ffi-stubs \
ocamlx-Ctypes-foreign-basis \
ocamlx-Ctypes-foreign-threaded-stubs \
ocamlx-Ctypes-memory \
ocamlx-Ctypes-memory-stubs \
ocamlx-Ctypes-path \
ocamlx-Ctypes-primitive-types \
ocamlx-Ctypes-primitives \
ocamlx-Ctypes-ptr \
ocamlx-Ctypes-roots-stubs \
ocamlx-Ctypes-static \
ocamlx-Ctypes-std-view-stubs \
ocamlx-Ctypes-std-views \
ocamlx-Ctypes-structs \
ocamlx-Ctypes-structs-computed \
ocamlx-Ctypes-top \
ocamlx-Ctypes-top--Install-ctypes-printers \
ocamlx-Ctypes-type-printing \
ocamlx-Ctypes-value-printing \
ocamlx-Ctypes-value-printing-stubs \
ocamlx-Ctypes-weak-ref \
ocamlx-Dl \
ocamlx-Foreign \
ocamlx-LDouble \
ocamlx-Libffi-abi \
ocamlx-PosixTypes"

RDEPENDS:${PN} += "libc.so.6 \
libffi.so.8 \
ocaml-Asttypes \
ocaml-Build-path-prefix-map \
ocaml-CamlinternalFormatBasics \
ocaml-CamlinternalLazy \
ocaml-CamlinternalOO \
ocaml-Cmi-format \
ocaml-Data-types \
ocaml-Env \
ocaml-Format-doc \
ocaml-Ident \
ocaml-Identifiable \
ocaml-Load-path \
ocaml-Location \
ocaml-Longident \
ocaml-Misc \
ocaml-Oprint \
ocaml-Outcometree \
ocaml-Parsetree \
ocaml-Path \
ocaml-Primitive \
ocaml-Shape \
ocaml-Signed \
ocaml-Stdlib \
ocaml-Stdlib--Array \
ocaml-Stdlib--Bigarray \
ocaml-Stdlib--Buffer \
ocaml-Stdlib--Bytes \
ocaml-Stdlib--Callback \
ocaml-Stdlib--Complex \
ocaml-Stdlib--Digest \
ocaml-Stdlib--Domain \
ocaml-Stdlib--Either \
ocaml-Stdlib--Format \
ocaml-Stdlib--Gc \
ocaml-Stdlib--Hashtbl \
ocaml-Stdlib--Int32 \
ocaml-Stdlib--Int64 \
ocaml-Stdlib--Lazy \
ocaml-Stdlib--Lexing \
ocaml-Stdlib--List \
ocaml-Stdlib--ListLabels \
ocaml-Stdlib--Map \
ocaml-Stdlib--Mutex \
ocaml-Stdlib--Nativeint \
ocaml-Stdlib--Obj \
ocaml-Stdlib--Oo \
ocaml-Stdlib--Printexc \
ocaml-Stdlib--Printf \
ocaml-Stdlib--Result \
ocaml-Stdlib--Seq \
ocaml-Stdlib--Set \
ocaml-Stdlib--String \
ocaml-Stdlib--Sys \
ocaml-Stdlib--Uchar \
ocaml-Stdlib--Weak \
ocaml-Str \
ocaml-Subst \
ocaml-Thread \
ocaml-Toploop \
ocaml-Type-immediacy \
ocaml-Types \
ocaml-Unit-info \
ocaml-Unix \
ocaml-Unsigned \
ocaml-Warnings \
ocaml-ctypes \
ocamlfind-bigarray \
ocamlfind-compiler-libs \
ocamlfind-ctypes \
ocamlfind-integers \
ocamlfind-str \
ocamlfind-threads \
ocamlx-CamlinternalOO \
ocamlx-Signed \
ocamlx-Stdlib \
ocamlx-Stdlib--Array \
ocamlx-Stdlib--Bigarray \
ocamlx-Stdlib--Bytes \
ocamlx-Stdlib--Callback \
ocamlx-Stdlib--Format \
ocamlx-Stdlib--Gc \
ocamlx-Stdlib--Hashtbl \
ocamlx-Stdlib--Int64 \
ocamlx-Stdlib--Lexing \
ocamlx-Stdlib--List \
ocamlx-Stdlib--ListLabels \
ocamlx-Stdlib--Mutex \
ocamlx-Stdlib--Nativeint \
ocamlx-Stdlib--Printexc \
ocamlx-Stdlib--Printf \
ocamlx-Stdlib--String \
ocamlx-Stdlib--Weak \
ocamlx-Str \
ocamlx-Thread \
ocamlx-Toploop \
ocamlx-Unsigned"

inherit rpm
