SUMMARY = "A SAML 2.0 authentication module for the Apache Server"
DESCRIPTION = "The mod_auth_mellon module is an authentication service that implements the \
SAML 2.0 federation protocol. It grants access based on the attributes \
received in assertions generated by a IdP server."
LICENSE = "GPL-2.0-or-later"

PV = "0.19.1"

RPM_NAME = "apache2-mod_auth_mellon-0.19.1-1.9.aarch64.rpm"
RPM_HASH = "5aafcaf148dd837d8ab2858a75c3d6b66347f7c1783dd3e99fd86e2735248b63ef33fc8469f7764c6774f6e7da599dad6a76bdc6a7d64b8e22107d0ad0fe584d"

RPROVIDES:${PN} += "apache2-mod-auth-mellon \
config-apache2-mod-auth-mellon"

RDEPENDS:${PN} += "/usr/bin/bash \
/usr/bin/sh \
apache-mmn-20120211 \
ld-linux-aarch64.so.1 \
libc.so.6 \
libcrypto.so.3 \
libcurl.so.4 \
libglib-2.0.so.0 \
liblasso.so.3 \
liblasso3 \
suse-maintenance-mmn-0"

inherit rpm
