SUMMARY = "Use of Linux Libertine and Biolinum fonts with LaTeX"
DESCRIPTION = "The package provides the Libertine and Biolinum fonts in both \
Type 1 and OTF styles, together with support macros for their \
use. Monospaced and display fonts, and the 'keyboard' set are \
also included, in OTF style, only. The mweights package is used \
to manage the selection of font weights. The package supersedes \
both the libertineotf and the libertine-legacy packages."
LICENSE = "GPL-2.0-or-later"

PV = "2026.226.5.3.0svn77682"

RPM_NAME = "texlive-libertine-2026.226.5.3.0svn77682-61.2.noarch.rpm"
RPM_HASH = "a240eaf194a3cde4c171b5b79124b5ff3cbf1bcf3d0bf8548c854ae074f371beff66476b4874d0cea94ec4bc4fc06a0f5d37b1db8b05f59b62b09b3c77d2af18"
REPO_ARCH = "noarch"

RPROVIDES:${PN} += "tex-LKey.tex \
tex-LY1LinuxBiolinumT-LF.fd \
tex-LY1LinuxBiolinumT-OsF.fd \
tex-LY1LinuxBiolinumT-Sup.fd \
tex-LY1LinuxBiolinumT-TLF.fd \
tex-LY1LinuxBiolinumT-TOsF.fd \
tex-LY1LinuxLibertineDisplayT-LF.fd \
tex-LY1LinuxLibertineDisplayT-OsF.fd \
tex-LY1LinuxLibertineDisplayT-Sup.fd \
tex-LY1LinuxLibertineDisplayT-TLF.fd \
tex-LY1LinuxLibertineDisplayT-TOsF.fd \
tex-LY1LinuxLibertineInitialsT-LF.fd \
tex-LY1LinuxLibertineInitialsT-OsF.fd \
tex-LY1LinuxLibertineInitialsT-TLF.fd \
tex-LY1LinuxLibertineMonoT-LF.fd \
tex-LY1LinuxLibertineMonoT-Sup.fd \
tex-LY1LinuxLibertineMonoT-TLF.fd \
tex-LY1LinuxLibertineT-LF.fd \
tex-LY1LinuxLibertineT-OsF.fd \
tex-LY1LinuxLibertineT-Sup.fd \
tex-LY1LinuxLibertineT-TLF.fd \
tex-LY1LinuxLibertineT-TOsF.fd \
tex-LinBiolinum-K.tex \
tex-LinBiolinum-R.tex \
tex-LinBiolinumT-lf-ly1--base.tfm \
tex-LinBiolinumT-lf-ly1.tfm \
tex-LinBiolinumT-lf-ly1.vf \
tex-LinBiolinumT-lf-ot1--base.tfm \
tex-LinBiolinumT-lf-ot1.tfm \
tex-LinBiolinumT-lf-ot1.vf \
tex-LinBiolinumT-lf-sc-ly1--base.tfm \
tex-LinBiolinumT-lf-sc-ly1.tfm \
tex-LinBiolinumT-lf-sc-ly1.vf \
tex-LinBiolinumT-lf-sc-ot1--base.tfm \
tex-LinBiolinumT-lf-sc-ot1.tfm \
tex-LinBiolinumT-lf-sc-ot1.vf \
tex-LinBiolinumT-lf-sc-t1--base.tfm \
tex-LinBiolinumT-lf-sc-t1.tfm \
tex-LinBiolinumT-lf-sc-t1.vf \
tex-LinBiolinumT-lf-t1--base.tfm \
tex-LinBiolinumT-lf-t1.tfm \
tex-LinBiolinumT-lf-t1.vf \
tex-LinBiolinumT-lf-ts1--base.tfm \
tex-LinBiolinumT-lf-ts1.tfm \
tex-LinBiolinumT-lf-ts1.vf \
tex-LinBiolinumT-osf-ly1--base.tfm \
tex-LinBiolinumT-osf-ly1.tfm \
tex-LinBiolinumT-osf-ly1.vf \
tex-LinBiolinumT-osf-ot1--base.tfm \
tex-LinBiolinumT-osf-ot1.tfm \
tex-LinBiolinumT-osf-ot1.vf \
tex-LinBiolinumT-osf-sc-ly1--base.tfm \
tex-LinBiolinumT-osf-sc-ly1.tfm \
tex-LinBiolinumT-osf-sc-ly1.vf \
tex-LinBiolinumT-osf-sc-ot1--base.tfm \
tex-LinBiolinumT-osf-sc-ot1.tfm \
tex-LinBiolinumT-osf-sc-ot1.vf \
tex-LinBiolinumT-osf-sc-t1--base.tfm \
tex-LinBiolinumT-osf-sc-t1.tfm \
tex-LinBiolinumT-osf-sc-t1.vf \
tex-LinBiolinumT-osf-t1--base.tfm \
tex-LinBiolinumT-osf-t1.tfm \
tex-LinBiolinumT-osf-t1.vf \
tex-LinBiolinumT-osf-ts1--base.tfm \
tex-LinBiolinumT-osf-ts1.tfm \
tex-LinBiolinumT-osf-ts1.vf \
tex-LinBiolinumT-sup-ly1--base.tfm \
tex-LinBiolinumT-sup-ly1.tfm \
tex-LinBiolinumT-sup-ly1.vf \
tex-LinBiolinumT-sup-ot1.tfm \
tex-LinBiolinumT-sup-t1--base.tfm \
tex-LinBiolinumT-sup-t1.tfm \
tex-LinBiolinumT-sup-t1.vf \
tex-LinBiolinumT-tlf-ly1--base.tfm \
tex-LinBiolinumT-tlf-ly1.tfm \
tex-LinBiolinumT-tlf-ly1.vf \
tex-LinBiolinumT-tlf-ot1--base.tfm \
tex-LinBiolinumT-tlf-ot1.tfm \
tex-LinBiolinumT-tlf-ot1.vf \
tex-LinBiolinumT-tlf-sc-ly1--base.tfm \
tex-LinBiolinumT-tlf-sc-ly1.tfm \
tex-LinBiolinumT-tlf-sc-ly1.vf \
tex-LinBiolinumT-tlf-sc-ot1--base.tfm \
tex-LinBiolinumT-tlf-sc-ot1.tfm \
tex-LinBiolinumT-tlf-sc-ot1.vf \
tex-LinBiolinumT-tlf-sc-t1--base.tfm \
tex-LinBiolinumT-tlf-sc-t1.tfm \
tex-LinBiolinumT-tlf-sc-t1.vf \
tex-LinBiolinumT-tlf-t1--base.tfm \
tex-LinBiolinumT-tlf-t1.tfm \
tex-LinBiolinumT-tlf-t1.vf \
tex-LinBiolinumT-tlf-ts1--base.tfm \
tex-LinBiolinumT-tlf-ts1.tfm \
tex-LinBiolinumT-tlf-ts1.vf \
tex-LinBiolinumT-tosf-ly1--base.tfm \
tex-LinBiolinumT-tosf-ly1.tfm \
tex-LinBiolinumT-tosf-ly1.vf \
tex-LinBiolinumT-tosf-ot1--base.tfm \
tex-LinBiolinumT-tosf-ot1.tfm \
tex-LinBiolinumT-tosf-ot1.vf \
tex-LinBiolinumT-tosf-sc-ly1--base.tfm \
tex-LinBiolinumT-tosf-sc-ly1.tfm \
tex-LinBiolinumT-tosf-sc-ly1.vf \
tex-LinBiolinumT-tosf-sc-ot1--base.tfm \
tex-LinBiolinumT-tosf-sc-ot1.tfm \
tex-LinBiolinumT-tosf-sc-ot1.vf \
tex-LinBiolinumT-tosf-sc-t1--base.tfm \
tex-LinBiolinumT-tosf-sc-t1.tfm \
tex-LinBiolinumT-tosf-sc-t1.vf \
tex-LinBiolinumT-tosf-t1--base.tfm \
tex-LinBiolinumT-tosf-t1.tfm \
tex-LinBiolinumT-tosf-t1.vf \
tex-LinBiolinumT-tosf-ts1--base.tfm \
tex-LinBiolinumT-tosf-ts1.tfm \
tex-LinBiolinumT-tosf-ts1.vf \
tex-LinBiolinumTB-lf-ly1--base.tfm \
tex-LinBiolinumTB-lf-ly1.tfm \
tex-LinBiolinumTB-lf-ly1.vf \
tex-LinBiolinumTB-lf-ot1--base.tfm \
tex-LinBiolinumTB-lf-ot1.tfm \
tex-LinBiolinumTB-lf-ot1.vf \
tex-LinBiolinumTB-lf-sc-ly1--base.tfm \
tex-LinBiolinumTB-lf-sc-ly1.tfm \
tex-LinBiolinumTB-lf-sc-ly1.vf \
tex-LinBiolinumTB-lf-sc-ot1--base.tfm \
tex-LinBiolinumTB-lf-sc-ot1.tfm \
tex-LinBiolinumTB-lf-sc-ot1.vf \
tex-LinBiolinumTB-lf-sc-t1--base.tfm \
tex-LinBiolinumTB-lf-sc-t1.tfm \
tex-LinBiolinumTB-lf-sc-t1.vf \
tex-LinBiolinumTB-lf-t1--base.tfm \
tex-LinBiolinumTB-lf-t1.tfm \
tex-LinBiolinumTB-lf-t1.vf \
tex-LinBiolinumTB-lf-ts1--base.tfm \
tex-LinBiolinumTB-lf-ts1.tfm \
tex-LinBiolinumTB-lf-ts1.vf \
tex-LinBiolinumTB-osf-ly1--base.tfm \
tex-LinBiolinumTB-osf-ly1.tfm \
tex-LinBiolinumTB-osf-ly1.vf \
tex-LinBiolinumTB-osf-ot1--base.tfm \
tex-LinBiolinumTB-osf-ot1.tfm \
tex-LinBiolinumTB-osf-ot1.vf \
tex-LinBiolinumTB-osf-sc-ly1--base.tfm \
tex-LinBiolinumTB-osf-sc-ly1.tfm \
tex-LinBiolinumTB-osf-sc-ly1.vf \
tex-LinBiolinumTB-osf-sc-ot1--base.tfm \
tex-LinBiolinumTB-osf-sc-ot1.tfm \
tex-LinBiolinumTB-osf-sc-ot1.vf \
tex-LinBiolinumTB-osf-sc-t1--base.tfm \
tex-LinBiolinumTB-osf-sc-t1.tfm \
tex-LinBiolinumTB-osf-sc-t1.vf \
tex-LinBiolinumTB-osf-t1--base.tfm \
tex-LinBiolinumTB-osf-t1.tfm \
tex-LinBiolinumTB-osf-t1.vf \
tex-LinBiolinumTB-osf-ts1--base.tfm \
tex-LinBiolinumTB-osf-ts1.tfm \
tex-LinBiolinumTB-osf-ts1.vf \
tex-LinBiolinumTB-sup-ly1--base.tfm \
tex-LinBiolinumTB-sup-ly1.tfm \
tex-LinBiolinumTB-sup-ly1.vf \
tex-LinBiolinumTB-sup-ot1.tfm \
tex-LinBiolinumTB-sup-t1--base.tfm \
tex-LinBiolinumTB-sup-t1.tfm \
tex-LinBiolinumTB-sup-t1.vf \
tex-LinBiolinumTB-tlf-ly1--base.tfm \
tex-LinBiolinumTB-tlf-ly1.tfm \
tex-LinBiolinumTB-tlf-ly1.vf \
tex-LinBiolinumTB-tlf-ot1--base.tfm \
tex-LinBiolinumTB-tlf-ot1.tfm \
tex-LinBiolinumTB-tlf-ot1.vf \
tex-LinBiolinumTB-tlf-sc-ly1--base.tfm \
tex-LinBiolinumTB-tlf-sc-ly1.tfm \
tex-LinBiolinumTB-tlf-sc-ly1.vf \
tex-LinBiolinumTB-tlf-sc-ot1--base.tfm \
tex-LinBiolinumTB-tlf-sc-ot1.tfm \
tex-LinBiolinumTB-tlf-sc-ot1.vf \
tex-LinBiolinumTB-tlf-sc-t1--base.tfm \
tex-LinBiolinumTB-tlf-sc-t1.tfm \
tex-LinBiolinumTB-tlf-sc-t1.vf \
tex-LinBiolinumTB-tlf-t1--base.tfm \
tex-LinBiolinumTB-tlf-t1.tfm \
tex-LinBiolinumTB-tlf-t1.vf \
tex-LinBiolinumTB-tlf-ts1--base.tfm \
tex-LinBiolinumTB-tlf-ts1.tfm \
tex-LinBiolinumTB-tlf-ts1.vf \
tex-LinBiolinumTB-tosf-ly1--base.tfm \
tex-LinBiolinumTB-tosf-ly1.tfm \
tex-LinBiolinumTB-tosf-ly1.vf \
tex-LinBiolinumTB-tosf-ot1--base.tfm \
tex-LinBiolinumTB-tosf-ot1.tfm \
tex-LinBiolinumTB-tosf-ot1.vf \
tex-LinBiolinumTB-tosf-sc-ly1--base.tfm \
tex-LinBiolinumTB-tosf-sc-ly1.tfm \
tex-LinBiolinumTB-tosf-sc-ly1.vf \
tex-LinBiolinumTB-tosf-sc-ot1--base.tfm \
tex-LinBiolinumTB-tosf-sc-ot1.tfm \
tex-LinBiolinumTB-tosf-sc-ot1.vf \
tex-LinBiolinumTB-tosf-sc-t1--base.tfm \
tex-LinBiolinumTB-tosf-sc-t1.tfm \
tex-LinBiolinumTB-tosf-sc-t1.vf \
tex-LinBiolinumTB-tosf-t1--base.tfm \
tex-LinBiolinumTB-tosf-t1.tfm \
tex-LinBiolinumTB-tosf-t1.vf \
tex-LinBiolinumTB-tosf-ts1--base.tfm \
tex-LinBiolinumTB-tosf-ts1.tfm \
tex-LinBiolinumTB-tosf-ts1.vf \
tex-LinBiolinumTBO-lf-ly1--base.tfm \
tex-LinBiolinumTBO-lf-ly1.tfm \
tex-LinBiolinumTBO-lf-ly1.vf \
tex-LinBiolinumTBO-lf-ot1--base.tfm \
tex-LinBiolinumTBO-lf-ot1.tfm \
tex-LinBiolinumTBO-lf-ot1.vf \
tex-LinBiolinumTBO-lf-sc-ly1--base.tfm \
tex-LinBiolinumTBO-lf-sc-ly1.tfm \
tex-LinBiolinumTBO-lf-sc-ly1.vf \
tex-LinBiolinumTBO-lf-sc-ot1--base.tfm \
tex-LinBiolinumTBO-lf-sc-ot1.tfm \
tex-LinBiolinumTBO-lf-sc-ot1.vf \
tex-LinBiolinumTBO-lf-sc-t1--base.tfm \
tex-LinBiolinumTBO-lf-sc-t1.tfm \
tex-LinBiolinumTBO-lf-sc-t1.vf \
tex-LinBiolinumTBO-lf-t1--base.tfm \
tex-LinBiolinumTBO-lf-t1.tfm \
tex-LinBiolinumTBO-lf-t1.vf \
tex-LinBiolinumTBO-lf-ts1--base.tfm \
tex-LinBiolinumTBO-lf-ts1.tfm \
tex-LinBiolinumTBO-lf-ts1.vf \
tex-LinBiolinumTBO-osf-ly1--base.tfm \
tex-LinBiolinumTBO-osf-ly1.tfm \
tex-LinBiolinumTBO-osf-ly1.vf \
tex-LinBiolinumTBO-osf-ot1--base.tfm \
tex-LinBiolinumTBO-osf-ot1.tfm \
tex-LinBiolinumTBO-osf-ot1.vf \
tex-LinBiolinumTBO-osf-sc-ly1--base.tfm \
tex-LinBiolinumTBO-osf-sc-ly1.tfm \
tex-LinBiolinumTBO-osf-sc-ly1.vf \
tex-LinBiolinumTBO-osf-sc-ot1--base.tfm \
tex-LinBiolinumTBO-osf-sc-ot1.tfm \
tex-LinBiolinumTBO-osf-sc-ot1.vf \
tex-LinBiolinumTBO-osf-sc-t1--base.tfm \
tex-LinBiolinumTBO-osf-sc-t1.tfm \
tex-LinBiolinumTBO-osf-sc-t1.vf \
tex-LinBiolinumTBO-osf-t1--base.tfm \
tex-LinBiolinumTBO-osf-t1.tfm \
tex-LinBiolinumTBO-osf-t1.vf \
tex-LinBiolinumTBO-osf-ts1--base.tfm \
tex-LinBiolinumTBO-osf-ts1.tfm \
tex-LinBiolinumTBO-osf-ts1.vf \
tex-LinBiolinumTBO-sup-ly1--base.tfm \
tex-LinBiolinumTBO-sup-ly1.tfm \
tex-LinBiolinumTBO-sup-ly1.vf \
tex-LinBiolinumTBO-sup-ot1.tfm \
tex-LinBiolinumTBO-sup-t1--base.tfm \
tex-LinBiolinumTBO-sup-t1.tfm \
tex-LinBiolinumTBO-sup-t1.vf \
tex-LinBiolinumTBO-tlf-ly1--base.tfm \
tex-LinBiolinumTBO-tlf-ly1.tfm \
tex-LinBiolinumTBO-tlf-ly1.vf \
tex-LinBiolinumTBO-tlf-ot1--base.tfm \
tex-LinBiolinumTBO-tlf-ot1.tfm \
tex-LinBiolinumTBO-tlf-ot1.vf \
tex-LinBiolinumTBO-tlf-sc-ly1--base.tfm \
tex-LinBiolinumTBO-tlf-sc-ly1.tfm \
tex-LinBiolinumTBO-tlf-sc-ly1.vf \
tex-LinBiolinumTBO-tlf-sc-ot1--base.tfm \
tex-LinBiolinumTBO-tlf-sc-ot1.tfm \
tex-LinBiolinumTBO-tlf-sc-ot1.vf \
tex-LinBiolinumTBO-tlf-sc-t1--base.tfm \
tex-LinBiolinumTBO-tlf-sc-t1.tfm \
tex-LinBiolinumTBO-tlf-sc-t1.vf \
tex-LinBiolinumTBO-tlf-t1--base.tfm \
tex-LinBiolinumTBO-tlf-t1.tfm \
tex-LinBiolinumTBO-tlf-t1.vf \
tex-LinBiolinumTBO-tlf-ts1--base.tfm \
tex-LinBiolinumTBO-tlf-ts1.tfm \
tex-LinBiolinumTBO-tlf-ts1.vf \
tex-LinBiolinumTBO-tosf-ly1--base.tfm \
tex-LinBiolinumTBO-tosf-ly1.tfm \
tex-LinBiolinumTBO-tosf-ly1.vf \
tex-LinBiolinumTBO-tosf-ot1--base.tfm \
tex-LinBiolinumTBO-tosf-ot1.tfm \
tex-LinBiolinumTBO-tosf-ot1.vf \
tex-LinBiolinumTBO-tosf-sc-ly1--base.tfm \
tex-LinBiolinumTBO-tosf-sc-ly1.tfm \
tex-LinBiolinumTBO-tosf-sc-ly1.vf \
tex-LinBiolinumTBO-tosf-sc-ot1--base.tfm \
tex-LinBiolinumTBO-tosf-sc-ot1.tfm \
tex-LinBiolinumTBO-tosf-sc-ot1.vf \
tex-LinBiolinumTBO-tosf-sc-t1--base.tfm \
tex-LinBiolinumTBO-tosf-sc-t1.tfm \
tex-LinBiolinumTBO-tosf-sc-t1.vf \
tex-LinBiolinumTBO-tosf-t1--base.tfm \
tex-LinBiolinumTBO-tosf-t1.tfm \
tex-LinBiolinumTBO-tosf-t1.vf \
tex-LinBiolinumTBO-tosf-ts1--base.tfm \
tex-LinBiolinumTBO-tosf-ts1.tfm \
tex-LinBiolinumTBO-tosf-ts1.vf \
tex-LinBiolinumTI-lf-ly1--base.tfm \
tex-LinBiolinumTI-lf-ly1.tfm \
tex-LinBiolinumTI-lf-ly1.vf \
tex-LinBiolinumTI-lf-ot1--base.tfm \
tex-LinBiolinumTI-lf-ot1.tfm \
tex-LinBiolinumTI-lf-ot1.vf \
tex-LinBiolinumTI-lf-sc-ly1--base.tfm \
tex-LinBiolinumTI-lf-sc-ly1.tfm \
tex-LinBiolinumTI-lf-sc-ly1.vf \
tex-LinBiolinumTI-lf-sc-ot1--base.tfm \
tex-LinBiolinumTI-lf-sc-ot1.tfm \
tex-LinBiolinumTI-lf-sc-ot1.vf \
tex-LinBiolinumTI-lf-sc-t1--base.tfm \
tex-LinBiolinumTI-lf-sc-t1.tfm \
tex-LinBiolinumTI-lf-sc-t1.vf \
tex-LinBiolinumTI-lf-t1--base.tfm \
tex-LinBiolinumTI-lf-t1.tfm \
tex-LinBiolinumTI-lf-t1.vf \
tex-LinBiolinumTI-lf-ts1--base.tfm \
tex-LinBiolinumTI-lf-ts1.tfm \
tex-LinBiolinumTI-lf-ts1.vf \
tex-LinBiolinumTI-osf-ly1--base.tfm \
tex-LinBiolinumTI-osf-ly1.tfm \
tex-LinBiolinumTI-osf-ly1.vf \
tex-LinBiolinumTI-osf-ot1--base.tfm \
tex-LinBiolinumTI-osf-ot1.tfm \
tex-LinBiolinumTI-osf-ot1.vf \
tex-LinBiolinumTI-osf-sc-ly1--base.tfm \
tex-LinBiolinumTI-osf-sc-ly1.tfm \
tex-LinBiolinumTI-osf-sc-ly1.vf \
tex-LinBiolinumTI-osf-sc-ot1--base.tfm \
tex-LinBiolinumTI-osf-sc-ot1.tfm \
tex-LinBiolinumTI-osf-sc-ot1.vf \
tex-LinBiolinumTI-osf-sc-t1--base.tfm \
tex-LinBiolinumTI-osf-sc-t1.tfm \
tex-LinBiolinumTI-osf-sc-t1.vf \
tex-LinBiolinumTI-osf-t1--base.tfm \
tex-LinBiolinumTI-osf-t1.tfm \
tex-LinBiolinumTI-osf-t1.vf \
tex-LinBiolinumTI-osf-ts1--base.tfm \
tex-LinBiolinumTI-osf-ts1.tfm \
tex-LinBiolinumTI-osf-ts1.vf \
tex-LinBiolinumTI-sup-ly1--base.tfm \
tex-LinBiolinumTI-sup-ly1.tfm \
tex-LinBiolinumTI-sup-ly1.vf \
tex-LinBiolinumTI-sup-ot1.tfm \
tex-LinBiolinumTI-sup-t1--base.tfm \
tex-LinBiolinumTI-sup-t1.tfm \
tex-LinBiolinumTI-sup-t1.vf \
tex-LinBiolinumTI-tlf-ly1--base.tfm \
tex-LinBiolinumTI-tlf-ly1.tfm \
tex-LinBiolinumTI-tlf-ly1.vf \
tex-LinBiolinumTI-tlf-ot1--base.tfm \
tex-LinBiolinumTI-tlf-ot1.tfm \
tex-LinBiolinumTI-tlf-ot1.vf \
tex-LinBiolinumTI-tlf-sc-ly1--base.tfm \
tex-LinBiolinumTI-tlf-sc-ly1.tfm \
tex-LinBiolinumTI-tlf-sc-ly1.vf \
tex-LinBiolinumTI-tlf-sc-ot1--base.tfm \
tex-LinBiolinumTI-tlf-sc-ot1.tfm \
tex-LinBiolinumTI-tlf-sc-ot1.vf \
tex-LinBiolinumTI-tlf-sc-t1--base.tfm \
tex-LinBiolinumTI-tlf-sc-t1.tfm \
tex-LinBiolinumTI-tlf-sc-t1.vf \
tex-LinBiolinumTI-tlf-t1--base.tfm \
tex-LinBiolinumTI-tlf-t1.tfm \
tex-LinBiolinumTI-tlf-t1.vf \
tex-LinBiolinumTI-tlf-ts1--base.tfm \
tex-LinBiolinumTI-tlf-ts1.tfm \
tex-LinBiolinumTI-tlf-ts1.vf \
tex-LinBiolinumTI-tosf-ly1--base.tfm \
tex-LinBiolinumTI-tosf-ly1.tfm \
tex-LinBiolinumTI-tosf-ly1.vf \
tex-LinBiolinumTI-tosf-ot1--base.tfm \
tex-LinBiolinumTI-tosf-ot1.tfm \
tex-LinBiolinumTI-tosf-ot1.vf \
tex-LinBiolinumTI-tosf-sc-ly1--base.tfm \
tex-LinBiolinumTI-tosf-sc-ly1.tfm \
tex-LinBiolinumTI-tosf-sc-ly1.vf \
tex-LinBiolinumTI-tosf-sc-ot1--base.tfm \
tex-LinBiolinumTI-tosf-sc-ot1.tfm \
tex-LinBiolinumTI-tosf-sc-ot1.vf \
tex-LinBiolinumTI-tosf-sc-t1--base.tfm \
tex-LinBiolinumTI-tosf-sc-t1.tfm \
tex-LinBiolinumTI-tosf-sc-t1.vf \
tex-LinBiolinumTI-tosf-t1--base.tfm \
tex-LinBiolinumTI-tosf-t1.tfm \
tex-LinBiolinumTI-tosf-t1.vf \
tex-LinBiolinumTI-tosf-ts1--base.tfm \
tex-LinBiolinumTI-tosf-ts1.tfm \
tex-LinBiolinumTI-tosf-ts1.vf \
tex-LinLibertine-I.tex \
tex-LinLibertine-R.tex \
tex-LinLibertineDisplayT-lf-ly1--base.tfm \
tex-LinLibertineDisplayT-lf-ly1.tfm \
tex-LinLibertineDisplayT-lf-ly1.vf \
tex-LinLibertineDisplayT-lf-ot1--base.tfm \
tex-LinLibertineDisplayT-lf-ot1.tfm \
tex-LinLibertineDisplayT-lf-ot1.vf \
tex-LinLibertineDisplayT-lf-t1--base.tfm \
tex-LinLibertineDisplayT-lf-t1.tfm \
tex-LinLibertineDisplayT-lf-t1.vf \
tex-LinLibertineDisplayT-lf-ts1--base.tfm \
tex-LinLibertineDisplayT-lf-ts1.tfm \
tex-LinLibertineDisplayT-lf-ts1.vf \
tex-LinLibertineDisplayT-osf-ly1--base.tfm \
tex-LinLibertineDisplayT-osf-ly1.tfm \
tex-LinLibertineDisplayT-osf-ly1.vf \
tex-LinLibertineDisplayT-osf-ot1--base.tfm \
tex-LinLibertineDisplayT-osf-ot1.tfm \
tex-LinLibertineDisplayT-osf-ot1.vf \
tex-LinLibertineDisplayT-osf-t1--base.tfm \
tex-LinLibertineDisplayT-osf-t1.tfm \
tex-LinLibertineDisplayT-osf-t1.vf \
tex-LinLibertineDisplayT-osf-ts1--base.tfm \
tex-LinLibertineDisplayT-osf-ts1.tfm \
tex-LinLibertineDisplayT-osf-ts1.vf \
tex-LinLibertineDisplayT-sup-ly1--base.tfm \
tex-LinLibertineDisplayT-sup-ly1.tfm \
tex-LinLibertineDisplayT-sup-ly1.vf \
tex-LinLibertineDisplayT-sup-ot1.tfm \
tex-LinLibertineDisplayT-sup-t1--base.tfm \
tex-LinLibertineDisplayT-sup-t1.tfm \
tex-LinLibertineDisplayT-sup-t1.vf \
tex-LinLibertineDisplayT-tlf-ly1--base.tfm \
tex-LinLibertineDisplayT-tlf-ly1.tfm \
tex-LinLibertineDisplayT-tlf-ly1.vf \
tex-LinLibertineDisplayT-tlf-ot1--base.tfm \
tex-LinLibertineDisplayT-tlf-ot1.tfm \
tex-LinLibertineDisplayT-tlf-ot1.vf \
tex-LinLibertineDisplayT-tlf-t1--base.tfm \
tex-LinLibertineDisplayT-tlf-t1.tfm \
tex-LinLibertineDisplayT-tlf-t1.vf \
tex-LinLibertineDisplayT-tlf-ts1--base.tfm \
tex-LinLibertineDisplayT-tlf-ts1.tfm \
tex-LinLibertineDisplayT-tlf-ts1.vf \
tex-LinLibertineDisplayT-tosf-ly1--base.tfm \
tex-LinLibertineDisplayT-tosf-ly1.tfm \
tex-LinLibertineDisplayT-tosf-ly1.vf \
tex-LinLibertineDisplayT-tosf-ot1--base.tfm \
tex-LinLibertineDisplayT-tosf-ot1.tfm \
tex-LinLibertineDisplayT-tosf-ot1.vf \
tex-LinLibertineDisplayT-tosf-t1--base.tfm \
tex-LinLibertineDisplayT-tosf-t1.tfm \
tex-LinLibertineDisplayT-tosf-t1.vf \
tex-LinLibertineDisplayT-tosf-ts1--base.tfm \
tex-LinLibertineDisplayT-tosf-ts1.tfm \
tex-LinLibertineDisplayT-tosf-ts1.vf \
tex-LinLibertineIT-lf-ly1--base.tfm \
tex-LinLibertineIT-lf-ly1.tfm \
tex-LinLibertineIT-lf-ly1.vf \
tex-LinLibertineIT-lf-ot1.tfm \
tex-LinLibertineIT-lf-t1--base.tfm \
tex-LinLibertineIT-lf-t1.tfm \
tex-LinLibertineIT-lf-t1.vf \
tex-LinLibertineIT-lf-ts1--base.tfm \
tex-LinLibertineIT-lf-ts1.tfm \
tex-LinLibertineIT-lf-ts1.vf \
tex-LinLibertineIT-tlf-ly1--base.tfm \
tex-LinLibertineIT-tlf-ly1.tfm \
tex-LinLibertineIT-tlf-ly1.vf \
tex-LinLibertineIT-tlf-ot1.tfm \
tex-LinLibertineIT-tlf-t1--base.tfm \
tex-LinLibertineIT-tlf-t1.tfm \
tex-LinLibertineIT-tlf-t1.vf \
tex-LinLibertineIT-tlf-ts1--base.tfm \
tex-LinLibertineIT-tlf-ts1.tfm \
tex-LinLibertineIT-tlf-ts1.vf \
tex-LinLibertineMT-lf-ly1--base.tfm \
tex-LinLibertineMT-lf-ly1.tfm \
tex-LinLibertineMT-lf-ly1.vf \
tex-LinLibertineMT-lf-ot1.tfm \
tex-LinLibertineMT-lf-t1--base.tfm \
tex-LinLibertineMT-lf-t1.tfm \
tex-LinLibertineMT-lf-t1.vf \
tex-LinLibertineMT-lf-ts1--base.tfm \
tex-LinLibertineMT-lf-ts1.tfm \
tex-LinLibertineMT-lf-ts1.vf \
tex-LinLibertineMT-sup-ly1--base.tfm \
tex-LinLibertineMT-sup-ly1.tfm \
tex-LinLibertineMT-sup-ly1.vf \
tex-LinLibertineMT-sup-ot1.tfm \
tex-LinLibertineMT-sup-t1--base.tfm \
tex-LinLibertineMT-sup-t1.tfm \
tex-LinLibertineMT-sup-t1.vf \
tex-LinLibertineMT-tlf-ly1--base.tfm \
tex-LinLibertineMT-tlf-ly1.tfm \
tex-LinLibertineMT-tlf-ly1.vf \
tex-LinLibertineMT-tlf-ot1.tfm \
tex-LinLibertineMT-tlf-t1--base.tfm \
tex-LinLibertineMT-tlf-t1.tfm \
tex-LinLibertineMT-tlf-t1.vf \
tex-LinLibertineMT-tlf-ts1--base.tfm \
tex-LinLibertineMT-tlf-ts1.tfm \
tex-LinLibertineMT-tlf-ts1.vf \
tex-LinLibertineMTB-lf-ly1--base.tfm \
tex-LinLibertineMTB-lf-ly1.tfm \
tex-LinLibertineMTB-lf-ly1.vf \
tex-LinLibertineMTB-lf-ot1.tfm \
tex-LinLibertineMTB-lf-t1--base.tfm \
tex-LinLibertineMTB-lf-t1.tfm \
tex-LinLibertineMTB-lf-t1.vf \
tex-LinLibertineMTB-lf-ts1--base.tfm \
tex-LinLibertineMTB-lf-ts1.tfm \
tex-LinLibertineMTB-lf-ts1.vf \
tex-LinLibertineMTB-sup-ly1--base.tfm \
tex-LinLibertineMTB-sup-ly1.tfm \
tex-LinLibertineMTB-sup-ly1.vf \
tex-LinLibertineMTB-sup-ot1.tfm \
tex-LinLibertineMTB-sup-t1--base.tfm \
tex-LinLibertineMTB-sup-t1.tfm \
tex-LinLibertineMTB-sup-t1.vf \
tex-LinLibertineMTB-tlf-ly1--base.tfm \
tex-LinLibertineMTB-tlf-ly1.tfm \
tex-LinLibertineMTB-tlf-ly1.vf \
tex-LinLibertineMTB-tlf-ot1.tfm \
tex-LinLibertineMTB-tlf-t1--base.tfm \
tex-LinLibertineMTB-tlf-t1.tfm \
tex-LinLibertineMTB-tlf-t1.vf \
tex-LinLibertineMTB-tlf-ts1--base.tfm \
tex-LinLibertineMTB-tlf-ts1.tfm \
tex-LinLibertineMTB-tlf-ts1.vf \
tex-LinLibertineMTBO-lf-ly1--base.tfm \
tex-LinLibertineMTBO-lf-ly1.tfm \
tex-LinLibertineMTBO-lf-ly1.vf \
tex-LinLibertineMTBO-lf-ot1.tfm \
tex-LinLibertineMTBO-lf-t1--base.tfm \
tex-LinLibertineMTBO-lf-t1.tfm \
tex-LinLibertineMTBO-lf-t1.vf \
tex-LinLibertineMTBO-lf-ts1--base.tfm \
tex-LinLibertineMTBO-lf-ts1.tfm \
tex-LinLibertineMTBO-lf-ts1.vf \
tex-LinLibertineMTBO-sup-ly1--base.tfm \
tex-LinLibertineMTBO-sup-ly1.tfm \
tex-LinLibertineMTBO-sup-ly1.vf \
tex-LinLibertineMTBO-sup-ot1.tfm \
tex-LinLibertineMTBO-sup-t1--base.tfm \
tex-LinLibertineMTBO-sup-t1.tfm \
tex-LinLibertineMTBO-sup-t1.vf \
tex-LinLibertineMTBO-tlf-ly1--base.tfm \
tex-LinLibertineMTBO-tlf-ly1.tfm \
tex-LinLibertineMTBO-tlf-ly1.vf \
tex-LinLibertineMTBO-tlf-ot1.tfm \
tex-LinLibertineMTBO-tlf-t1--base.tfm \
tex-LinLibertineMTBO-tlf-t1.tfm \
tex-LinLibertineMTBO-tlf-t1.vf \
tex-LinLibertineMTBO-tlf-ts1--base.tfm \
tex-LinLibertineMTBO-tlf-ts1.tfm \
tex-LinLibertineMTBO-tlf-ts1.vf \
tex-LinLibertineMTO-lf-ly1--base.tfm \
tex-LinLibertineMTO-lf-ly1.tfm \
tex-LinLibertineMTO-lf-ly1.vf \
tex-LinLibertineMTO-lf-ot1.tfm \
tex-LinLibertineMTO-lf-t1--base.tfm \
tex-LinLibertineMTO-lf-t1.tfm \
tex-LinLibertineMTO-lf-t1.vf \
tex-LinLibertineMTO-lf-ts1--base.tfm \
tex-LinLibertineMTO-lf-ts1.tfm \
tex-LinLibertineMTO-lf-ts1.vf \
tex-LinLibertineMTO-sup-ly1--base.tfm \
tex-LinLibertineMTO-sup-ly1.tfm \
tex-LinLibertineMTO-sup-ly1.vf \
tex-LinLibertineMTO-sup-ot1.tfm \
tex-LinLibertineMTO-sup-t1--base.tfm \
tex-LinLibertineMTO-sup-t1.tfm \
tex-LinLibertineMTO-sup-t1.vf \
tex-LinLibertineMTO-tlf-ly1--base.tfm \
tex-LinLibertineMTO-tlf-ly1.tfm \
tex-LinLibertineMTO-tlf-ly1.vf \
tex-LinLibertineMTO-tlf-ot1.tfm \
tex-LinLibertineMTO-tlf-t1--base.tfm \
tex-LinLibertineMTO-tlf-t1.tfm \
tex-LinLibertineMTO-tlf-t1.vf \
tex-LinLibertineMTO-tlf-ts1--base.tfm \
tex-LinLibertineMTO-tlf-ts1.tfm \
tex-LinLibertineMTO-tlf-ts1.vf \
tex-LinLibertineT-lf-ly1--base.tfm \
tex-LinLibertineT-lf-ly1.tfm \
tex-LinLibertineT-lf-ly1.vf \
tex-LinLibertineT-lf-ot1--base.tfm \
tex-LinLibertineT-lf-ot1.tfm \
tex-LinLibertineT-lf-ot1.vf \
tex-LinLibertineT-lf-sc-ly1--base.tfm \
tex-LinLibertineT-lf-sc-ly1.tfm \
tex-LinLibertineT-lf-sc-ly1.vf \
tex-LinLibertineT-lf-sc-ot1--base.tfm \
tex-LinLibertineT-lf-sc-ot1.tfm \
tex-LinLibertineT-lf-sc-ot1.vf \
tex-LinLibertineT-lf-sc-t1--base.tfm \
tex-LinLibertineT-lf-sc-t1.tfm \
tex-LinLibertineT-lf-sc-t1.vf \
tex-LinLibertineT-lf-t1--base.tfm \
tex-LinLibertineT-lf-t1.tfm \
tex-LinLibertineT-lf-t1.vf \
tex-LinLibertineT-lf-ts1--base.tfm \
tex-LinLibertineT-lf-ts1.tfm \
tex-LinLibertineT-lf-ts1.vf \
tex-LinLibertineT-osf-ly1--base.tfm \
tex-LinLibertineT-osf-ly1.tfm \
tex-LinLibertineT-osf-ly1.vf \
tex-LinLibertineT-osf-ot1--base.tfm \
tex-LinLibertineT-osf-ot1.tfm \
tex-LinLibertineT-osf-ot1.vf \
tex-LinLibertineT-osf-sc-ly1--base.tfm \
tex-LinLibertineT-osf-sc-ly1.tfm \
tex-LinLibertineT-osf-sc-ly1.vf \
tex-LinLibertineT-osf-sc-ot1--base.tfm \
tex-LinLibertineT-osf-sc-ot1.tfm \
tex-LinLibertineT-osf-sc-ot1.vf \
tex-LinLibertineT-osf-sc-t1--base.tfm \
tex-LinLibertineT-osf-sc-t1.tfm \
tex-LinLibertineT-osf-sc-t1.vf \
tex-LinLibertineT-osf-t1--base.tfm \
tex-LinLibertineT-osf-t1.tfm \
tex-LinLibertineT-osf-t1.vf \
tex-LinLibertineT-osf-ts1--base.tfm \
tex-LinLibertineT-osf-ts1.tfm \
tex-LinLibertineT-osf-ts1.vf \
tex-LinLibertineT-sup-ly1--base.tfm \
tex-LinLibertineT-sup-ly1.tfm \
tex-LinLibertineT-sup-ly1.vf \
tex-LinLibertineT-sup-ot1.tfm \
tex-LinLibertineT-sup-t1--base.tfm \
tex-LinLibertineT-sup-t1.tfm \
tex-LinLibertineT-sup-t1.vf \
tex-LinLibertineT-tlf-ly1--base.tfm \
tex-LinLibertineT-tlf-ly1.tfm \
tex-LinLibertineT-tlf-ly1.vf \
tex-LinLibertineT-tlf-ot1--base.tfm \
tex-LinLibertineT-tlf-ot1.tfm \
tex-LinLibertineT-tlf-ot1.vf \
tex-LinLibertineT-tlf-sc-ly1--base.tfm \
tex-LinLibertineT-tlf-sc-ly1.tfm \
tex-LinLibertineT-tlf-sc-ly1.vf \
tex-LinLibertineT-tlf-sc-ot1--base.tfm \
tex-LinLibertineT-tlf-sc-ot1.tfm \
tex-LinLibertineT-tlf-sc-ot1.vf \
tex-LinLibertineT-tlf-sc-t1--base.tfm \
tex-LinLibertineT-tlf-sc-t1.tfm \
tex-LinLibertineT-tlf-sc-t1.vf \
tex-LinLibertineT-tlf-t1--base.tfm \
tex-LinLibertineT-tlf-t1.tfm \
tex-LinLibertineT-tlf-t1.vf \
tex-LinLibertineT-tlf-ts1--base.tfm \
tex-LinLibertineT-tlf-ts1.tfm \
tex-LinLibertineT-tlf-ts1.vf \
tex-LinLibertineT-tosf-ly1--base.tfm \
tex-LinLibertineT-tosf-ly1.tfm \
tex-LinLibertineT-tosf-ly1.vf \
tex-LinLibertineT-tosf-ot1--base.tfm \
tex-LinLibertineT-tosf-ot1.tfm \
tex-LinLibertineT-tosf-ot1.vf \
tex-LinLibertineT-tosf-sc-ly1--base.tfm \
tex-LinLibertineT-tosf-sc-ly1.tfm \
tex-LinLibertineT-tosf-sc-ly1.vf \
tex-LinLibertineT-tosf-sc-ot1--base.tfm \
tex-LinLibertineT-tosf-sc-ot1.tfm \
tex-LinLibertineT-tosf-sc-ot1.vf \
tex-LinLibertineT-tosf-sc-t1--base.tfm \
tex-LinLibertineT-tosf-sc-t1.tfm \
tex-LinLibertineT-tosf-sc-t1.vf \
tex-LinLibertineT-tosf-t1--base.tfm \
tex-LinLibertineT-tosf-t1.tfm \
tex-LinLibertineT-tosf-t1.vf \
tex-LinLibertineT-tosf-ts1--base.tfm \
tex-LinLibertineT-tosf-ts1.tfm \
tex-LinLibertineT-tosf-ts1.vf \
tex-LinLibertineTB-lf-ly1--base.tfm \
tex-LinLibertineTB-lf-ly1.tfm \
tex-LinLibertineTB-lf-ly1.vf \
tex-LinLibertineTB-lf-ot1--base.tfm \
tex-LinLibertineTB-lf-ot1.tfm \
tex-LinLibertineTB-lf-ot1.vf \
tex-LinLibertineTB-lf-sc-ly1--base.tfm \
tex-LinLibertineTB-lf-sc-ly1.tfm \
tex-LinLibertineTB-lf-sc-ly1.vf \
tex-LinLibertineTB-lf-sc-ot1--base.tfm \
tex-LinLibertineTB-lf-sc-ot1.tfm \
tex-LinLibertineTB-lf-sc-ot1.vf \
tex-LinLibertineTB-lf-sc-t1--base.tfm \
tex-LinLibertineTB-lf-sc-t1.tfm \
tex-LinLibertineTB-lf-sc-t1.vf \
tex-LinLibertineTB-lf-t1--base.tfm \
tex-LinLibertineTB-lf-t1.tfm \
tex-LinLibertineTB-lf-t1.vf \
tex-LinLibertineTB-lf-ts1--base.tfm \
tex-LinLibertineTB-lf-ts1.tfm \
tex-LinLibertineTB-lf-ts1.vf \
tex-LinLibertineTB-osf-ly1--base.tfm \
tex-LinLibertineTB-osf-ly1.tfm \
tex-LinLibertineTB-osf-ly1.vf \
tex-LinLibertineTB-osf-ot1--base.tfm \
tex-LinLibertineTB-osf-ot1.tfm \
tex-LinLibertineTB-osf-ot1.vf \
tex-LinLibertineTB-osf-sc-ly1--base.tfm \
tex-LinLibertineTB-osf-sc-ly1.tfm \
tex-LinLibertineTB-osf-sc-ly1.vf \
tex-LinLibertineTB-osf-sc-ot1--base.tfm \
tex-LinLibertineTB-osf-sc-ot1.tfm \
tex-LinLibertineTB-osf-sc-ot1.vf \
tex-LinLibertineTB-osf-sc-t1--base.tfm \
tex-LinLibertineTB-osf-sc-t1.tfm \
tex-LinLibertineTB-osf-sc-t1.vf \
tex-LinLibertineTB-osf-t1--base.tfm \
tex-LinLibertineTB-osf-t1.tfm \
tex-LinLibertineTB-osf-t1.vf \
tex-LinLibertineTB-osf-ts1--base.tfm \
tex-LinLibertineTB-osf-ts1.tfm \
tex-LinLibertineTB-osf-ts1.vf \
tex-LinLibertineTB-sup-ly1--base.tfm \
tex-LinLibertineTB-sup-ly1.tfm \
tex-LinLibertineTB-sup-ly1.vf \
tex-LinLibertineTB-sup-ot1.tfm \
tex-LinLibertineTB-sup-t1--base.tfm \
tex-LinLibertineTB-sup-t1.tfm \
tex-LinLibertineTB-sup-t1.vf \
tex-LinLibertineTB-tlf-ly1--base.tfm \
tex-LinLibertineTB-tlf-ly1.tfm \
tex-LinLibertineTB-tlf-ly1.vf \
tex-LinLibertineTB-tlf-ot1--base.tfm \
tex-LinLibertineTB-tlf-ot1.tfm \
tex-LinLibertineTB-tlf-ot1.vf \
tex-LinLibertineTB-tlf-sc-ly1--base.tfm \
tex-LinLibertineTB-tlf-sc-ly1.tfm \
tex-LinLibertineTB-tlf-sc-ly1.vf \
tex-LinLibertineTB-tlf-sc-ot1--base.tfm \
tex-LinLibertineTB-tlf-sc-ot1.tfm \
tex-LinLibertineTB-tlf-sc-ot1.vf \
tex-LinLibertineTB-tlf-sc-t1--base.tfm \
tex-LinLibertineTB-tlf-sc-t1.tfm \
tex-LinLibertineTB-tlf-sc-t1.vf \
tex-LinLibertineTB-tlf-t1--base.tfm \
tex-LinLibertineTB-tlf-t1.tfm \
tex-LinLibertineTB-tlf-t1.vf \
tex-LinLibertineTB-tlf-ts1--base.tfm \
tex-LinLibertineTB-tlf-ts1.tfm \
tex-LinLibertineTB-tlf-ts1.vf \
tex-LinLibertineTB-tosf-ly1--base.tfm \
tex-LinLibertineTB-tosf-ly1.tfm \
tex-LinLibertineTB-tosf-ly1.vf \
tex-LinLibertineTB-tosf-ot1--base.tfm \
tex-LinLibertineTB-tosf-ot1.tfm \
tex-LinLibertineTB-tosf-ot1.vf \
tex-LinLibertineTB-tosf-sc-ly1--base.tfm \
tex-LinLibertineTB-tosf-sc-ly1.tfm \
tex-LinLibertineTB-tosf-sc-ly1.vf \
tex-LinLibertineTB-tosf-sc-ot1--base.tfm \
tex-LinLibertineTB-tosf-sc-ot1.tfm \
tex-LinLibertineTB-tosf-sc-ot1.vf \
tex-LinLibertineTB-tosf-sc-t1--base.tfm \
tex-LinLibertineTB-tosf-sc-t1.tfm \
tex-LinLibertineTB-tosf-sc-t1.vf \
tex-LinLibertineTB-tosf-t1--base.tfm \
tex-LinLibertineTB-tosf-t1.tfm \
tex-LinLibertineTB-tosf-t1.vf \
tex-LinLibertineTB-tosf-ts1--base.tfm \
tex-LinLibertineTB-tosf-ts1.tfm \
tex-LinLibertineTB-tosf-ts1.vf \
tex-LinLibertineTBI-lf-ly1--base.tfm \
tex-LinLibertineTBI-lf-ly1.tfm \
tex-LinLibertineTBI-lf-ly1.vf \
tex-LinLibertineTBI-lf-ot1--base.tfm \
tex-LinLibertineTBI-lf-ot1.tfm \
tex-LinLibertineTBI-lf-ot1.vf \
tex-LinLibertineTBI-lf-sc-ly1--base.tfm \
tex-LinLibertineTBI-lf-sc-ly1.tfm \
tex-LinLibertineTBI-lf-sc-ly1.vf \
tex-LinLibertineTBI-lf-sc-ot1--base.tfm \
tex-LinLibertineTBI-lf-sc-ot1.tfm \
tex-LinLibertineTBI-lf-sc-ot1.vf \
tex-LinLibertineTBI-lf-sc-t1--base.tfm \
tex-LinLibertineTBI-lf-sc-t1.tfm \
tex-LinLibertineTBI-lf-sc-t1.vf \
tex-LinLibertineTBI-lf-t1--base.tfm \
tex-LinLibertineTBI-lf-t1.tfm \
tex-LinLibertineTBI-lf-t1.vf \
tex-LinLibertineTBI-lf-ts1--base.tfm \
tex-LinLibertineTBI-lf-ts1.tfm \
tex-LinLibertineTBI-lf-ts1.vf \
tex-LinLibertineTBI-osf-ly1--base.tfm \
tex-LinLibertineTBI-osf-ly1.tfm \
tex-LinLibertineTBI-osf-ly1.vf \
tex-LinLibertineTBI-osf-ot1--base.tfm \
tex-LinLibertineTBI-osf-ot1.tfm \
tex-LinLibertineTBI-osf-ot1.vf \
tex-LinLibertineTBI-osf-sc-ly1--base.tfm \
tex-LinLibertineTBI-osf-sc-ly1.tfm \
tex-LinLibertineTBI-osf-sc-ly1.vf \
tex-LinLibertineTBI-osf-sc-ot1--base.tfm \
tex-LinLibertineTBI-osf-sc-ot1.tfm \
tex-LinLibertineTBI-osf-sc-ot1.vf \
tex-LinLibertineTBI-osf-sc-t1--base.tfm \
tex-LinLibertineTBI-osf-sc-t1.tfm \
tex-LinLibertineTBI-osf-sc-t1.vf \
tex-LinLibertineTBI-osf-t1--base.tfm \
tex-LinLibertineTBI-osf-t1.tfm \
tex-LinLibertineTBI-osf-t1.vf \
tex-LinLibertineTBI-osf-ts1--base.tfm \
tex-LinLibertineTBI-osf-ts1.tfm \
tex-LinLibertineTBI-osf-ts1.vf \
tex-LinLibertineTBI-sup-ly1--base.tfm \
tex-LinLibertineTBI-sup-ly1.tfm \
tex-LinLibertineTBI-sup-ly1.vf \
tex-LinLibertineTBI-sup-ot1.tfm \
tex-LinLibertineTBI-sup-t1--base.tfm \
tex-LinLibertineTBI-sup-t1.tfm \
tex-LinLibertineTBI-sup-t1.vf \
tex-LinLibertineTBI-tlf-ly1--base.tfm \
tex-LinLibertineTBI-tlf-ly1.tfm \
tex-LinLibertineTBI-tlf-ly1.vf \
tex-LinLibertineTBI-tlf-ot1--base.tfm \
tex-LinLibertineTBI-tlf-ot1.tfm \
tex-LinLibertineTBI-tlf-ot1.vf \
tex-LinLibertineTBI-tlf-sc-ly1--base.tfm \
tex-LinLibertineTBI-tlf-sc-ly1.tfm \
tex-LinLibertineTBI-tlf-sc-ly1.vf \
tex-LinLibertineTBI-tlf-sc-ot1--base.tfm \
tex-LinLibertineTBI-tlf-sc-ot1.tfm \
tex-LinLibertineTBI-tlf-sc-ot1.vf \
tex-LinLibertineTBI-tlf-sc-t1--base.tfm \
tex-LinLibertineTBI-tlf-sc-t1.tfm \
tex-LinLibertineTBI-tlf-sc-t1.vf \
tex-LinLibertineTBI-tlf-t1--base.tfm \
tex-LinLibertineTBI-tlf-t1.tfm \
tex-LinLibertineTBI-tlf-t1.vf \
tex-LinLibertineTBI-tlf-ts1--base.tfm \
tex-LinLibertineTBI-tlf-ts1.tfm \
tex-LinLibertineTBI-tlf-ts1.vf \
tex-LinLibertineTBI-tosf-ly1--base.tfm \
tex-LinLibertineTBI-tosf-ly1.tfm \
tex-LinLibertineTBI-tosf-ly1.vf \
tex-LinLibertineTBI-tosf-ot1--base.tfm \
tex-LinLibertineTBI-tosf-ot1.tfm \
tex-LinLibertineTBI-tosf-ot1.vf \
tex-LinLibertineTBI-tosf-sc-ly1--base.tfm \
tex-LinLibertineTBI-tosf-sc-ly1.tfm \
tex-LinLibertineTBI-tosf-sc-ly1.vf \
tex-LinLibertineTBI-tosf-sc-ot1--base.tfm \
tex-LinLibertineTBI-tosf-sc-ot1.tfm \
tex-LinLibertineTBI-tosf-sc-ot1.vf \
tex-LinLibertineTBI-tosf-sc-t1--base.tfm \
tex-LinLibertineTBI-tosf-sc-t1.tfm \
tex-LinLibertineTBI-tosf-sc-t1.vf \
tex-LinLibertineTBI-tosf-t1--base.tfm \
tex-LinLibertineTBI-tosf-t1.tfm \
tex-LinLibertineTBI-tosf-t1.vf \
tex-LinLibertineTBI-tosf-ts1--base.tfm \
tex-LinLibertineTBI-tosf-ts1.tfm \
tex-LinLibertineTBI-tosf-ts1.vf \
tex-LinLibertineTI-lf-ly1--base.tfm \
tex-LinLibertineTI-lf-ly1.tfm \
tex-LinLibertineTI-lf-ly1.vf \
tex-LinLibertineTI-lf-ot1--base.tfm \
tex-LinLibertineTI-lf-ot1.tfm \
tex-LinLibertineTI-lf-ot1.vf \
tex-LinLibertineTI-lf-sc-ly1--base.tfm \
tex-LinLibertineTI-lf-sc-ly1.tfm \
tex-LinLibertineTI-lf-sc-ly1.vf \
tex-LinLibertineTI-lf-sc-ot1--base.tfm \
tex-LinLibertineTI-lf-sc-ot1.tfm \
tex-LinLibertineTI-lf-sc-ot1.vf \
tex-LinLibertineTI-lf-sc-t1--base.tfm \
tex-LinLibertineTI-lf-sc-t1.tfm \
tex-LinLibertineTI-lf-sc-t1.vf \
tex-LinLibertineTI-lf-t1--base.tfm \
tex-LinLibertineTI-lf-t1.tfm \
tex-LinLibertineTI-lf-t1.vf \
tex-LinLibertineTI-lf-ts1--base.tfm \
tex-LinLibertineTI-lf-ts1.tfm \
tex-LinLibertineTI-lf-ts1.vf \
tex-LinLibertineTI-osf-ly1--base.tfm \
tex-LinLibertineTI-osf-ly1.tfm \
tex-LinLibertineTI-osf-ly1.vf \
tex-LinLibertineTI-osf-ot1--base.tfm \
tex-LinLibertineTI-osf-ot1.tfm \
tex-LinLibertineTI-osf-ot1.vf \
tex-LinLibertineTI-osf-sc-ly1--base.tfm \
tex-LinLibertineTI-osf-sc-ly1.tfm \
tex-LinLibertineTI-osf-sc-ly1.vf \
tex-LinLibertineTI-osf-sc-ot1--base.tfm \
tex-LinLibertineTI-osf-sc-ot1.tfm \
tex-LinLibertineTI-osf-sc-ot1.vf \
tex-LinLibertineTI-osf-sc-t1--base.tfm \
tex-LinLibertineTI-osf-sc-t1.tfm \
tex-LinLibertineTI-osf-sc-t1.vf \
tex-LinLibertineTI-osf-t1--base.tfm \
tex-LinLibertineTI-osf-t1.tfm \
tex-LinLibertineTI-osf-t1.vf \
tex-LinLibertineTI-osf-ts1--base.tfm \
tex-LinLibertineTI-osf-ts1.tfm \
tex-LinLibertineTI-osf-ts1.vf \
tex-LinLibertineTI-sup-ly1--base.tfm \
tex-LinLibertineTI-sup-ly1.tfm \
tex-LinLibertineTI-sup-ly1.vf \
tex-LinLibertineTI-sup-ot1.tfm \
tex-LinLibertineTI-sup-t1--base.tfm \
tex-LinLibertineTI-sup-t1.tfm \
tex-LinLibertineTI-sup-t1.vf \
tex-LinLibertineTI-tlf-ly1--base.tfm \
tex-LinLibertineTI-tlf-ly1.tfm \
tex-LinLibertineTI-tlf-ly1.vf \
tex-LinLibertineTI-tlf-ot1--base.tfm \
tex-LinLibertineTI-tlf-ot1.tfm \
tex-LinLibertineTI-tlf-ot1.vf \
tex-LinLibertineTI-tlf-sc-ly1--base.tfm \
tex-LinLibertineTI-tlf-sc-ly1.tfm \
tex-LinLibertineTI-tlf-sc-ly1.vf \
tex-LinLibertineTI-tlf-sc-ot1--base.tfm \
tex-LinLibertineTI-tlf-sc-ot1.tfm \
tex-LinLibertineTI-tlf-sc-ot1.vf \
tex-LinLibertineTI-tlf-sc-t1--base.tfm \
tex-LinLibertineTI-tlf-sc-t1.tfm \
tex-LinLibertineTI-tlf-sc-t1.vf \
tex-LinLibertineTI-tlf-t1--base.tfm \
tex-LinLibertineTI-tlf-t1.tfm \
tex-LinLibertineTI-tlf-t1.vf \
tex-LinLibertineTI-tlf-ts1--base.tfm \
tex-LinLibertineTI-tlf-ts1.tfm \
tex-LinLibertineTI-tlf-ts1.vf \
tex-LinLibertineTI-tosf-ly1--base.tfm \
tex-LinLibertineTI-tosf-ly1.tfm \
tex-LinLibertineTI-tosf-ly1.vf \
tex-LinLibertineTI-tosf-ot1--base.tfm \
tex-LinLibertineTI-tosf-ot1.tfm \
tex-LinLibertineTI-tosf-ot1.vf \
tex-LinLibertineTI-tosf-sc-ly1--base.tfm \
tex-LinLibertineTI-tosf-sc-ly1.tfm \
tex-LinLibertineTI-tosf-sc-ly1.vf \
tex-LinLibertineTI-tosf-sc-ot1--base.tfm \
tex-LinLibertineTI-tosf-sc-ot1.tfm \
tex-LinLibertineTI-tosf-sc-ot1.vf \
tex-LinLibertineTI-tosf-sc-t1--base.tfm \
tex-LinLibertineTI-tosf-sc-t1.tfm \
tex-LinLibertineTI-tosf-sc-t1.vf \
tex-LinLibertineTI-tosf-t1--base.tfm \
tex-LinLibertineTI-tosf-t1.tfm \
tex-LinLibertineTI-tosf-t1.vf \
tex-LinLibertineTI-tosf-ts1--base.tfm \
tex-LinLibertineTI-tosf-ts1.tfm \
tex-LinLibertineTI-tosf-ts1.vf \
tex-LinLibertineTZ-lf-ly1--base.tfm \
tex-LinLibertineTZ-lf-ly1.tfm \
tex-LinLibertineTZ-lf-ly1.vf \
tex-LinLibertineTZ-lf-ot1--base.tfm \
tex-LinLibertineTZ-lf-ot1.tfm \
tex-LinLibertineTZ-lf-ot1.vf \
tex-LinLibertineTZ-lf-sc-ly1--base.tfm \
tex-LinLibertineTZ-lf-sc-ly1.tfm \
tex-LinLibertineTZ-lf-sc-ly1.vf \
tex-LinLibertineTZ-lf-sc-ot1--base.tfm \
tex-LinLibertineTZ-lf-sc-ot1.tfm \
tex-LinLibertineTZ-lf-sc-ot1.vf \
tex-LinLibertineTZ-lf-sc-t1--base.tfm \
tex-LinLibertineTZ-lf-sc-t1.tfm \
tex-LinLibertineTZ-lf-sc-t1.vf \
tex-LinLibertineTZ-lf-t1--base.tfm \
tex-LinLibertineTZ-lf-t1.tfm \
tex-LinLibertineTZ-lf-t1.vf \
tex-LinLibertineTZ-lf-ts1--base.tfm \
tex-LinLibertineTZ-lf-ts1.tfm \
tex-LinLibertineTZ-lf-ts1.vf \
tex-LinLibertineTZ-osf-ly1--base.tfm \
tex-LinLibertineTZ-osf-ly1.tfm \
tex-LinLibertineTZ-osf-ly1.vf \
tex-LinLibertineTZ-osf-ot1--base.tfm \
tex-LinLibertineTZ-osf-ot1.tfm \
tex-LinLibertineTZ-osf-ot1.vf \
tex-LinLibertineTZ-osf-sc-ly1--base.tfm \
tex-LinLibertineTZ-osf-sc-ly1.tfm \
tex-LinLibertineTZ-osf-sc-ly1.vf \
tex-LinLibertineTZ-osf-sc-ot1--base.tfm \
tex-LinLibertineTZ-osf-sc-ot1.tfm \
tex-LinLibertineTZ-osf-sc-ot1.vf \
tex-LinLibertineTZ-osf-sc-t1--base.tfm \
tex-LinLibertineTZ-osf-sc-t1.tfm \
tex-LinLibertineTZ-osf-sc-t1.vf \
tex-LinLibertineTZ-osf-t1--base.tfm \
tex-LinLibertineTZ-osf-t1.tfm \
tex-LinLibertineTZ-osf-t1.vf \
tex-LinLibertineTZ-osf-ts1--base.tfm \
tex-LinLibertineTZ-osf-ts1.tfm \
tex-LinLibertineTZ-osf-ts1.vf \
tex-LinLibertineTZ-sup-ly1--base.tfm \
tex-LinLibertineTZ-sup-ly1.tfm \
tex-LinLibertineTZ-sup-ly1.vf \
tex-LinLibertineTZ-sup-ot1.tfm \
tex-LinLibertineTZ-sup-t1--base.tfm \
tex-LinLibertineTZ-sup-t1.tfm \
tex-LinLibertineTZ-sup-t1.vf \
tex-LinLibertineTZ-tlf-ly1--base.tfm \
tex-LinLibertineTZ-tlf-ly1.tfm \
tex-LinLibertineTZ-tlf-ly1.vf \
tex-LinLibertineTZ-tlf-ot1--base.tfm \
tex-LinLibertineTZ-tlf-ot1.tfm \
tex-LinLibertineTZ-tlf-ot1.vf \
tex-LinLibertineTZ-tlf-sc-ly1--base.tfm \
tex-LinLibertineTZ-tlf-sc-ly1.tfm \
tex-LinLibertineTZ-tlf-sc-ly1.vf \
tex-LinLibertineTZ-tlf-sc-ot1--base.tfm \
tex-LinLibertineTZ-tlf-sc-ot1.tfm \
tex-LinLibertineTZ-tlf-sc-ot1.vf \
tex-LinLibertineTZ-tlf-sc-t1--base.tfm \
tex-LinLibertineTZ-tlf-sc-t1.tfm \
tex-LinLibertineTZ-tlf-sc-t1.vf \
tex-LinLibertineTZ-tlf-t1--base.tfm \
tex-LinLibertineTZ-tlf-t1.tfm \
tex-LinLibertineTZ-tlf-t1.vf \
tex-LinLibertineTZ-tlf-ts1--base.tfm \
tex-LinLibertineTZ-tlf-ts1.tfm \
tex-LinLibertineTZ-tlf-ts1.vf \
tex-LinLibertineTZ-tosf-ly1--base.tfm \
tex-LinLibertineTZ-tosf-ly1.tfm \
tex-LinLibertineTZ-tosf-ly1.vf \
tex-LinLibertineTZ-tosf-ot1--base.tfm \
tex-LinLibertineTZ-tosf-ot1.tfm \
tex-LinLibertineTZ-tosf-ot1.vf \
tex-LinLibertineTZ-tosf-sc-ly1--base.tfm \
tex-LinLibertineTZ-tosf-sc-ly1.tfm \
tex-LinLibertineTZ-tosf-sc-ly1.vf \
tex-LinLibertineTZ-tosf-sc-ot1--base.tfm \
tex-LinLibertineTZ-tosf-sc-ot1.tfm \
tex-LinLibertineTZ-tosf-sc-ot1.vf \
tex-LinLibertineTZ-tosf-sc-t1--base.tfm \
tex-LinLibertineTZ-tosf-sc-t1.tfm \
tex-LinLibertineTZ-tosf-sc-t1.vf \
tex-LinLibertineTZ-tosf-t1--base.tfm \
tex-LinLibertineTZ-tosf-t1.tfm \
tex-LinLibertineTZ-tosf-t1.vf \
tex-LinLibertineTZ-tosf-ts1--base.tfm \
tex-LinLibertineTZ-tosf-ts1.tfm \
tex-LinLibertineTZ-tosf-ts1.vf \
tex-LinLibertineTZI-lf-ly1.tfm \
tex-LinLibertineTZI-lf-ot1--base.tfm \
tex-LinLibertineTZI-lf-ot1.tfm \
tex-LinLibertineTZI-lf-ot1.vf \
tex-LinLibertineTZI-lf-sc-ly1--base.tfm \
tex-LinLibertineTZI-lf-sc-ly1.tfm \
tex-LinLibertineTZI-lf-sc-ly1.vf \
tex-LinLibertineTZI-lf-sc-ot1--base.tfm \
tex-LinLibertineTZI-lf-sc-ot1.tfm \
tex-LinLibertineTZI-lf-sc-ot1.vf \
tex-LinLibertineTZI-lf-sc-t1--base.tfm \
tex-LinLibertineTZI-lf-sc-t1.tfm \
tex-LinLibertineTZI-lf-sc-t1.vf \
tex-LinLibertineTZI-lf-t1--base.tfm \
tex-LinLibertineTZI-lf-t1.tfm \
tex-LinLibertineTZI-lf-t1.vf \
tex-LinLibertineTZI-lf-ts1--base.tfm \
tex-LinLibertineTZI-lf-ts1.tfm \
tex-LinLibertineTZI-lf-ts1.vf \
tex-LinLibertineTZI-osf-ly1.tfm \
tex-LinLibertineTZI-osf-ot1--base.tfm \
tex-LinLibertineTZI-osf-ot1.tfm \
tex-LinLibertineTZI-osf-ot1.vf \
tex-LinLibertineTZI-osf-sc-ly1--base.tfm \
tex-LinLibertineTZI-osf-sc-ly1.tfm \
tex-LinLibertineTZI-osf-sc-ly1.vf \
tex-LinLibertineTZI-osf-sc-ot1--base.tfm \
tex-LinLibertineTZI-osf-sc-ot1.tfm \
tex-LinLibertineTZI-osf-sc-ot1.vf \
tex-LinLibertineTZI-osf-sc-t1--base.tfm \
tex-LinLibertineTZI-osf-sc-t1.tfm \
tex-LinLibertineTZI-osf-sc-t1.vf \
tex-LinLibertineTZI-osf-t1--base.tfm \
tex-LinLibertineTZI-osf-t1.tfm \
tex-LinLibertineTZI-osf-t1.vf \
tex-LinLibertineTZI-osf-ts1--base.tfm \
tex-LinLibertineTZI-osf-ts1.tfm \
tex-LinLibertineTZI-osf-ts1.vf \
tex-LinLibertineTZI-sup-ly1.tfm \
tex-LinLibertineTZI-sup-ot1.tfm \
tex-LinLibertineTZI-sup-t1--base.tfm \
tex-LinLibertineTZI-sup-t1.tfm \
tex-LinLibertineTZI-sup-t1.vf \
tex-LinLibertineTZI-tlf-ly1.tfm \
tex-LinLibertineTZI-tlf-ot1--base.tfm \
tex-LinLibertineTZI-tlf-ot1.tfm \
tex-LinLibertineTZI-tlf-ot1.vf \
tex-LinLibertineTZI-tlf-sc-ly1--base.tfm \
tex-LinLibertineTZI-tlf-sc-ly1.tfm \
tex-LinLibertineTZI-tlf-sc-ly1.vf \
tex-LinLibertineTZI-tlf-sc-ot1--base.tfm \
tex-LinLibertineTZI-tlf-sc-ot1.tfm \
tex-LinLibertineTZI-tlf-sc-ot1.vf \
tex-LinLibertineTZI-tlf-sc-t1--base.tfm \
tex-LinLibertineTZI-tlf-sc-t1.tfm \
tex-LinLibertineTZI-tlf-sc-t1.vf \
tex-LinLibertineTZI-tlf-t1--base.tfm \
tex-LinLibertineTZI-tlf-t1.tfm \
tex-LinLibertineTZI-tlf-t1.vf \
tex-LinLibertineTZI-tlf-ts1--base.tfm \
tex-LinLibertineTZI-tlf-ts1.tfm \
tex-LinLibertineTZI-tlf-ts1.vf \
tex-LinLibertineTZI-tosf-ly1.tfm \
tex-LinLibertineTZI-tosf-ot1--base.tfm \
tex-LinLibertineTZI-tosf-ot1.tfm \
tex-LinLibertineTZI-tosf-ot1.vf \
tex-LinLibertineTZI-tosf-sc-ly1--base.tfm \
tex-LinLibertineTZI-tosf-sc-ly1.tfm \
tex-LinLibertineTZI-tosf-sc-ly1.vf \
tex-LinLibertineTZI-tosf-sc-ot1--base.tfm \
tex-LinLibertineTZI-tosf-sc-ot1.tfm \
tex-LinLibertineTZI-tosf-sc-ot1.vf \
tex-LinLibertineTZI-tosf-sc-t1--base.tfm \
tex-LinLibertineTZI-tosf-sc-t1.tfm \
tex-LinLibertineTZI-tosf-sc-t1.vf \
tex-LinLibertineTZI-tosf-t1--base.tfm \
tex-LinLibertineTZI-tosf-t1.tfm \
tex-LinLibertineTZI-tosf-t1.vf \
tex-LinLibertineTZI-tosf-ts1--base.tfm \
tex-LinLibertineTZI-tosf-ts1.tfm \
tex-LinLibertineTZI-tosf-ts1.vf \
tex-OT1LinuxBiolinumT-LF.fd \
tex-OT1LinuxBiolinumT-OsF.fd \
tex-OT1LinuxBiolinumT-Sup.fd \
tex-OT1LinuxBiolinumT-TLF.fd \
tex-OT1LinuxBiolinumT-TOsF.fd \
tex-OT1LinuxLibertineDisplayT-LF.fd \
tex-OT1LinuxLibertineDisplayT-OsF.fd \
tex-OT1LinuxLibertineDisplayT-Sup.fd \
tex-OT1LinuxLibertineDisplayT-TLF.fd \
tex-OT1LinuxLibertineDisplayT-TOsF.fd \
tex-OT1LinuxLibertineInitialsT-LF.fd \
tex-OT1LinuxLibertineInitialsT-OsF.fd \
tex-OT1LinuxLibertineInitialsT-TLF.fd \
tex-OT1LinuxLibertineMonoT-LF.fd \
tex-OT1LinuxLibertineMonoT-Sup.fd \
tex-OT1LinuxLibertineMonoT-TLF.fd \
tex-OT1LinuxLibertineT-LF.fd \
tex-OT1LinuxLibertineT-OsF.fd \
tex-OT1LinuxLibertineT-Sup.fd \
tex-OT1LinuxLibertineT-TLF.fd \
tex-OT1LinuxLibertineT-TOsF.fd \
tex-T1LinuxBiolinumT-LF.fd \
tex-T1LinuxBiolinumT-OsF.fd \
tex-T1LinuxBiolinumT-Sup.fd \
tex-T1LinuxBiolinumT-TLF.fd \
tex-T1LinuxBiolinumT-TOsF.fd \
tex-T1LinuxLibertineDisplayT-LF.fd \
tex-T1LinuxLibertineDisplayT-OsF.fd \
tex-T1LinuxLibertineDisplayT-Sup.fd \
tex-T1LinuxLibertineDisplayT-TLF.fd \
tex-T1LinuxLibertineDisplayT-TOsF.fd \
tex-T1LinuxLibertineInitialsT-LF.fd \
tex-T1LinuxLibertineInitialsT-OsF.fd \
tex-T1LinuxLibertineInitialsT-TLF.fd \
tex-T1LinuxLibertineMonoT-LF.fd \
tex-T1LinuxLibertineMonoT-Sup.fd \
tex-T1LinuxLibertineMonoT-TLF.fd \
tex-T1LinuxLibertineT-LF.fd \
tex-T1LinuxLibertineT-OsF.fd \
tex-T1LinuxLibertineT-Sup.fd \
tex-T1LinuxLibertineT-TLF.fd \
tex-T1LinuxLibertineT-TOsF.fd \
tex-TS1LinuxBiolinumT-LF.fd \
tex-TS1LinuxBiolinumT-OsF.fd \
tex-TS1LinuxBiolinumT-TLF.fd \
tex-TS1LinuxBiolinumT-TOsF.fd \
tex-TS1LinuxLibertineDisplayT-LF.fd \
tex-TS1LinuxLibertineDisplayT-OsF.fd \
tex-TS1LinuxLibertineDisplayT-TLF.fd \
tex-TS1LinuxLibertineDisplayT-TOsF.fd \
tex-TS1LinuxLibertineInitialsT-LF.fd \
tex-TS1LinuxLibertineInitialsT-OsF.fd \
tex-TS1LinuxLibertineInitialsT-TLF.fd \
tex-TS1LinuxLibertineMonoT-LF.fd \
tex-TS1LinuxLibertineMonoT-TLF.fd \
tex-TS1LinuxLibertineT-LF.fd \
tex-TS1LinuxLibertineT-OsF.fd \
tex-TS1LinuxLibertineT-TLF.fd \
tex-TS1LinuxLibertineT-TOsF.fd \
tex-biolinum.sty \
tex-lbtn-25tcsq.enc \
tex-lbtn-2exa4z.enc \
tex-lbtn-2ezly2.enc \
tex-lbtn-2jy62z.enc \
tex-lbtn-2lhpup.enc \
tex-lbtn-2mruj6.enc \
tex-lbtn-2or2lf.enc \
tex-lbtn-2vtnkl.enc \
tex-lbtn-2xw2fz.enc \
tex-lbtn-2yk3ov.enc \
tex-lbtn-3acize.enc \
tex-lbtn-3c7nkx.enc \
tex-lbtn-3dk467.enc \
tex-lbtn-3gqkkc.enc \
tex-lbtn-3i7fl4.enc \
tex-lbtn-3ocgcu.enc \
tex-lbtn-3r2fe2.enc \
tex-lbtn-3zs4uy.enc \
tex-lbtn-44kw74.enc \
tex-lbtn-4fqbzh.enc \
tex-lbtn-4gizrm.enc \
tex-lbtn-4h5nuw.enc \
tex-lbtn-4ifdhd.enc \
tex-lbtn-4lzzdn.enc \
tex-lbtn-4p7cpr.enc \
tex-lbtn-4pa5s6.enc \
tex-lbtn-4qdwcl.enc \
tex-lbtn-4wvzw4.enc \
tex-lbtn-4xgrig.enc \
tex-lbtn-4zgdm7.enc \
tex-lbtn-5t7yy5.enc \
tex-lbtn-5yotx4.enc \
tex-lbtn-64fcpm.enc \
tex-lbtn-67ud6q.enc \
tex-lbtn-6fbtzc.enc \
tex-lbtn-6icwtb.enc \
tex-lbtn-6igaju.enc \
tex-lbtn-6koeqx.enc \
tex-lbtn-6mhf45.enc \
tex-lbtn-6p6dn5.enc \
tex-lbtn-75c3wo.enc \
tex-lbtn-76gpa5.enc \
tex-lbtn-77vsbz.enc \
tex-lbtn-7aljsl.enc \
tex-lbtn-7f4ce4.enc \
tex-lbtn-7fko2h.enc \
tex-lbtn-7gfcac.enc \
tex-lbtn-7grukw.enc \
tex-lbtn-7gvbi7.enc \
tex-lbtn-7ukmos.enc \
tex-lbtn-7wxhd7.enc \
tex-lbtn-7yry24.enc \
tex-lbtn-7zzaqc.enc \
tex-lbtn-a6mubu.enc \
tex-lbtn-a7ysm3.enc \
tex-lbtn-ac44fr.enc \
tex-lbtn-afusau.enc \
tex-lbtn-aiatc4.enc \
tex-lbtn-ashjgg.enc \
tex-lbtn-avrf3y.enc \
tex-lbtn-azutla.enc \
tex-lbtn-b7buxp.enc \
tex-lbtn-b7tf5m.enc \
tex-lbtn-bgokdj.enc \
tex-lbtn-bgqvqi.enc \
tex-lbtn-bkwvsw.enc \
tex-lbtn-bvtjwh.enc \
tex-lbtn-bxcpwt.enc \
tex-lbtn-c3m4uk.enc \
tex-lbtn-c4mbat.enc \
tex-lbtn-c5qhbu.enc \
tex-lbtn-c6yh3y.enc \
tex-lbtn-c7hqsr.enc \
tex-lbtn-c7kyj5.enc \
tex-lbtn-ccye3h.enc \
tex-lbtn-coqhcm.enc \
tex-lbtn-crxz7j.enc \
tex-lbtn-ctsnwr.enc \
tex-lbtn-d4efeo.enc \
tex-lbtn-d5t6d3.enc \
tex-lbtn-d6jdyt.enc \
tex-lbtn-dc4jmj.enc \
tex-lbtn-dgc7p3.enc \
tex-lbtn-dgwfac.enc \
tex-lbtn-dh3kuf.enc \
tex-lbtn-dhi6qf.enc \
tex-lbtn-djk3hd.enc \
tex-lbtn-dm3bvq.enc \
tex-lbtn-dobmnc.enc \
tex-lbtn-doxsfd.enc \
tex-lbtn-drc7cb.enc \
tex-lbtn-dukpkt.enc \
tex-lbtn-dvvysc.enc \
tex-lbtn-dylq3g.enc \
tex-lbtn-e2nnp6.enc \
tex-lbtn-edcawa.enc \
tex-lbtn-ee6wgp.enc \
tex-lbtn-eh2cuc.enc \
tex-lbtn-ehpgim.enc \
tex-lbtn-ek5o26.enc \
tex-lbtn-ep5ow4.enc \
tex-lbtn-etetpy.enc \
tex-lbtn-ew6fhv.enc \
tex-lbtn-ewm74v.enc \
tex-lbtn-ezf25l.enc \
tex-lbtn-f3437j.enc \
tex-lbtn-f4vjgq.enc \
tex-lbtn-f75mth.enc \
tex-lbtn-fah7mx.enc \
tex-lbtn-fdphbq.enc \
tex-lbtn-ffhb5a.enc \
tex-lbtn-fgflse.enc \
tex-lbtn-flx7j2.enc \
tex-lbtn-fmcq3c.enc \
tex-lbtn-fte2ql.enc \
tex-lbtn-fygcup.enc \
tex-lbtn-g3iycs.enc \
tex-lbtn-g3y3rv.enc \
tex-lbtn-gannye.enc \
tex-lbtn-ggtxir.enc \
tex-lbtn-gj2vz5.enc \
tex-lbtn-glqt35.enc \
tex-lbtn-gppru4.enc \
tex-lbtn-gw5dl2.enc \
tex-lbtn-gwx7x5.enc \
tex-lbtn-gzistf.enc \
tex-lbtn-h7zthp.enc \
tex-lbtn-hj4mhx.enc \
tex-lbtn-hk6flg.enc \
tex-lbtn-hmhe76.enc \
tex-lbtn-hraow7.enc \
tex-lbtn-hrou5r.enc \
tex-lbtn-hx6qbg.enc \
tex-lbtn-hxgvkt.enc \
tex-lbtn-i5uqjc.enc \
tex-lbtn-igd6cx.enc \
tex-lbtn-ijo4o4.enc \
tex-lbtn-ilz2ox.enc \
tex-lbtn-imzna7.enc \
tex-lbtn-indkeb.enc \
tex-lbtn-io54zc.enc \
tex-lbtn-ip3srb.enc \
tex-lbtn-iqbcqn.enc \
tex-lbtn-ism4pi.enc \
tex-lbtn-itwafr.enc \
tex-lbtn-j3xg3k.enc \
tex-lbtn-j6rzs3.enc \
tex-lbtn-jbwhst.enc \
tex-lbtn-jk65vs.enc \
tex-lbtn-jkqd5u.enc \
tex-lbtn-jm7hzd.enc \
tex-lbtn-jnah33.enc \
tex-lbtn-jr2l53.enc \
tex-lbtn-jtbvjr.enc \
tex-lbtn-jtta5h.enc \
tex-lbtn-jubyw6.enc \
tex-lbtn-jvhpxk.enc \
tex-lbtn-jx6jsy.enc \
tex-lbtn-k2din5.enc \
tex-lbtn-ka7zfp.enc \
tex-lbtn-ki75ao.enc \
tex-lbtn-kijugd.enc \
tex-lbtn-kmbcyi.enc \
tex-lbtn-kozgsn.enc \
tex-lbtn-kqi56g.enc \
tex-lbtn-ks2ukx.enc \
tex-lbtn-kuli6n.enc \
tex-lbtn-kvn6mi.enc \
tex-lbtn-l4ygyh.enc \
tex-lbtn-l5ekfx.enc \
tex-lbtn-ldz4vi.enc \
tex-lbtn-lmduqq.enc \
tex-lbtn-lqfkm2.enc \
tex-lbtn-lrrvac.enc \
tex-lbtn-lu7m2n.enc \
tex-lbtn-lyu3x3.enc \
tex-lbtn-m4ul6s.enc \
tex-lbtn-m7vdvu.enc \
tex-lbtn-mdetlm.enc \
tex-lbtn-mlkyly.enc \
tex-lbtn-mmutss.enc \
tex-lbtn-mx3chd.enc \
tex-lbtn-mywn7m.enc \
tex-lbtn-n3ddym.enc \
tex-lbtn-n3gv2c.enc \
tex-lbtn-n3xw57.enc \
tex-lbtn-n7uljd.enc \
tex-lbtn-naooyc.enc \
tex-lbtn-ncsllp.enc \
tex-lbtn-nh77jq.enc \
tex-lbtn-nifh3d.enc \
tex-lbtn-o3jfbt.enc \
tex-lbtn-o3v7gd.enc \
tex-lbtn-o7ljol.enc \
tex-lbtn-oexx6f.enc \
tex-lbtn-oie7e6.enc \
tex-lbtn-okxbyw.enc \
tex-lbtn-omcwp2.enc \
tex-lbtn-ooant5.enc \
tex-lbtn-ouu7z6.enc \
tex-lbtn-ov2e4f.enc \
tex-lbtn-owmg2c.enc \
tex-lbtn-pagsao.enc \
tex-lbtn-pc62jw.enc \
tex-lbtn-pfnu67.enc \
tex-lbtn-pjjyzv.enc \
tex-lbtn-pjxd67.enc \
tex-lbtn-pkft74.enc \
tex-lbtn-pq6qgt.enc \
tex-lbtn-prxh5x.enc \
tex-lbtn-puhpfk.enc \
tex-lbtn-pwsgbx.enc \
tex-lbtn-q2zrjv.enc \
tex-lbtn-q6vmp6.enc \
tex-lbtn-qac756.enc \
tex-lbtn-qacof3.enc \
tex-lbtn-qgimbz.enc \
tex-lbtn-qlw4xk.enc \
tex-lbtn-qnd5b5.enc \
tex-lbtn-qwz7uv.enc \
tex-lbtn-r4tgzq.enc \
tex-lbtn-rat5le.enc \
tex-lbtn-rh4gvg.enc \
tex-lbtn-roevjg.enc \
tex-lbtn-rvmawp.enc \
tex-lbtn-sakzps.enc \
tex-lbtn-sdmuhw.enc \
tex-lbtn-sfn3yq.enc \
tex-lbtn-sjkbhb.enc \
tex-lbtn-soyanm.enc \
tex-lbtn-sruc5m.enc \
tex-lbtn-suv2ur.enc \
tex-lbtn-t62t6h.enc \
tex-lbtn-tk3eej.enc \
tex-lbtn-tltjc6.enc \
tex-lbtn-tlukpt.enc \
tex-lbtn-tnngrt.enc \
tex-lbtn-trvg3w.enc \
tex-lbtn-txfk5t.enc \
tex-lbtn-u442ab.enc \
tex-lbtn-u4pufl.enc \
tex-lbtn-u7qtuy.enc \
tex-lbtn-ufdkzv.enc \
tex-lbtn-ulngvd.enc \
tex-lbtn-uqwtgw.enc \
tex-lbtn-urpt4g.enc \
tex-lbtn-usa6cb.enc \
tex-lbtn-utckyy.enc \
tex-lbtn-uwivlq.enc \
tex-lbtn-v2xmgd.enc \
tex-lbtn-v3uc42.enc \
tex-lbtn-vezqth.enc \
tex-lbtn-vfdxlw.enc \
tex-lbtn-vhl5ch.enc \
tex-lbtn-vm42ve.enc \
tex-lbtn-voilzo.enc \
tex-lbtn-volajt.enc \
tex-lbtn-vp3gac.enc \
tex-lbtn-vpeqwl.enc \
tex-lbtn-vpjqew.enc \
tex-lbtn-vsrqlo.enc \
tex-lbtn-vump27.enc \
tex-lbtn-vyzecs.enc \
tex-lbtn-w5h3ip.enc \
tex-lbtn-w6afmj.enc \
tex-lbtn-wcay2e.enc \
tex-lbtn-weuxsp.enc \
tex-lbtn-wnipxy.enc \
tex-lbtn-wruwpj.enc \
tex-lbtn-wyfdnl.enc \
tex-lbtn-wzgokb.enc \
tex-lbtn-x4bvel.enc \
tex-lbtn-x4urtl.enc \
tex-lbtn-xapzkq.enc \
tex-lbtn-xc6c72.enc \
tex-lbtn-xeech7.enc \
tex-lbtn-xie3od.enc \
tex-lbtn-xnyvcl.enc \
tex-lbtn-xogrpz.enc \
tex-lbtn-xpavo4.enc \
tex-lbtn-xsgxhq.enc \
tex-lbtn-xz74p6.enc \
tex-lbtn-xzlo5e.enc \
tex-lbtn-y6cxei.enc \
tex-lbtn-y6gumo.enc \
tex-lbtn-yea32d.enc \
tex-lbtn-yfflrw.enc \
tex-lbtn-yruotg.enc \
tex-lbtn-yvenhr.enc \
tex-lbtn-z254vq.enc \
tex-lbtn-z3bmga.enc \
tex-lbtn-zacdtl.enc \
tex-lbtn-zajy4r.enc \
tex-lbtn-zkaele.enc \
tex-lbtn-zlmmkb.enc \
tex-lbtn-zoexom.enc \
tex-lbtn-zp73k3.enc \
tex-lbtn-zq22hj.enc \
tex-lbtn-zxvhqu.enc \
tex-lbtn-zycpkp.enc \
tex-lbtn-zyymej.enc \
tex-libertine.map \
tex-libertine.sty \
tex-libertineMono.sty \
tex-libertineRoman.sty \
texlive-libertine"

RDEPENDS:${PN} += "/usr/bin/sh \
coreutils \
ed \
findutils \
grep \
sed \
tex-fontaxes.sty \
tex-fontenc.sty \
tex-fontspec.sty \
tex-ifluatex.sty \
tex-ifxetex.sty \
tex-mweights.sty \
tex-textcomp.sty \
tex-updmap.cfg \
tex-xkeyval.sty \
texlive \
texlive-filesystem \
texlive-fontaxes \
texlive-iftex \
texlive-kpathsea \
texlive-kpathsea-bin \
texlive-libertine-fonts \
texlive-mweights \
texlive-scripts \
texlive-scripts-bin \
texlive-xkeyval"

inherit rpm
