SUMMARY = "Lua Documentation for lpeg"
DESCRIPTION = "Documentation and examples included with the library, sometimes \
generated by luadoc or ldoc."
LICENSE = "MIT"

PV = "1.1.0"

RPM_NAME = "lua55-lpeg-doc-1.1.0-3.4.noarch.rpm"
RPM_HASH = "b5b4b01a40e2e053353f68d20d852bd9f617f117ad8eae65afc297a88d5fb3dd20e3147c996831378683ce46aedfb19c232e08d7a9f7c20f6f8805898e7981f6"
REPO_ARCH = "noarch"

RPROVIDES:${PN} += "lua55-lpeg-doc"

RDEPENDS:${PN} += "lua55-lpeg"

inherit rpm
