SUMMARY = "Extension of Bitstream Charter fonts"
DESCRIPTION = "The package presents an extension of Bitstream Charter, which \
provides small caps, oldstyle figures and superior figures in \
all four styles, accompanied by LaTeX font support files. The \
fonts themselves are provided in both Adobe Type 1 and OTF \
formats, with supporting files as necessary."
LICENSE = "LPPL-1.0"

PV = "2026.226.1.26svn71564"

RPM_NAME = "texlive-xcharter-2026.226.1.26svn71564-59.4.noarch.rpm"
RPM_HASH = "c1af7c3715bf305552e410f128d165c292c4fd2a5e6faccf6f88394098ea089344503ea94b49cf3ac245163684e5851a15f66adc424aa90ff1af2ab9cdaf53ed"
REPO_ARCH = "noarch"

RPROVIDES:${PN} += "tex-LY1XCharter-Dnom.fd \
tex-LY1XCharter-Inf.fd \
tex-LY1XCharter-LF.fd \
tex-LY1XCharter-Numr.fd \
tex-LY1XCharter-OsF.fd \
tex-LY1XCharter-Sup.fd \
tex-LY1XCharter-TLF.fd \
tex-LY1XCharter-TOsF.fd \
tex-LY1XCharterTH-osf.fd \
tex-LY1XCharterTH-tlf.fd \
tex-OT1XCharter-Dnom.fd \
tex-OT1XCharter-Inf.fd \
tex-OT1XCharter-LF.fd \
tex-OT1XCharter-Numr.fd \
tex-OT1XCharter-OsF.fd \
tex-OT1XCharter-Sup.fd \
tex-OT1XCharter-TLF.fd \
tex-OT1XCharter-TOsF.fd \
tex-OT1XCharterTH-osf.fd \
tex-OT1XCharterTH-tlf.fd \
tex-OT2XCharter-TLF.fd \
tex-T1XCharter-Dnom.fd \
tex-T1XCharter-Inf.fd \
tex-T1XCharter-LF.fd \
tex-T1XCharter-Numr.fd \
tex-T1XCharter-OsF.fd \
tex-T1XCharter-Sup.fd \
tex-T1XCharter-TLF.fd \
tex-T1XCharter-TOsF.fd \
tex-T1XCharterTH-osf.fd \
tex-T1XCharterTH-tlf.fd \
tex-T2ASRBXCharter-LF.fd \
tex-T2ASRBXCharter-OsF.fd \
tex-T2ASRBXCharter-Sup.fd \
tex-T2ASRBXCharter-TLF.fd \
tex-T2ASRBXCharter-TOsF.fd \
tex-T2AXCharter-LF.fd \
tex-T2AXCharter-OsF.fd \
tex-T2AXCharter-Sup.fd \
tex-T2AXCharter-TLF.fd \
tex-T2AXCharter-TOsF.fd \
tex-TS1XCharter-LF.fd \
tex-TS1XCharter-OsF.fd \
tex-TS1XCharter-TLF.fd \
tex-TS1XCharter-TOsF.fd \
tex-XCharter-Bol-osf.tfm \
tex-XCharter-BolIta-alph.tfm \
tex-XCharter-Bold-dnom-ly1--base.tfm \
tex-XCharter-Bold-dnom-ly1.tfm \
tex-XCharter-Bold-dnom-ly1.vf \
tex-XCharter-Bold-dnom-ot1.tfm \
tex-XCharter-Bold-dnom-t1--base.tfm \
tex-XCharter-Bold-dnom-t1.tfm \
tex-XCharter-Bold-dnom-t1.vf \
tex-XCharter-Bold-inf-ly1--base.tfm \
tex-XCharter-Bold-inf-ly1.tfm \
tex-XCharter-Bold-inf-ly1.vf \
tex-XCharter-Bold-inf-ot1.tfm \
tex-XCharter-Bold-inf-t1--base.tfm \
tex-XCharter-Bold-inf-t1.tfm \
tex-XCharter-Bold-inf-t1.vf \
tex-XCharter-Bold-lf-ly1--base.tfm \
tex-XCharter-Bold-lf-ly1.tfm \
tex-XCharter-Bold-lf-ly1.vf \
tex-XCharter-Bold-lf-ot1.tfm \
tex-XCharter-Bold-lf-sc-ly1--base.tfm \
tex-XCharter-Bold-lf-sc-ly1.tfm \
tex-XCharter-Bold-lf-sc-ly1.vf \
tex-XCharter-Bold-lf-sc-ot1--base.tfm \
tex-XCharter-Bold-lf-sc-ot1.tfm \
tex-XCharter-Bold-lf-sc-ot1.vf \
tex-XCharter-Bold-lf-sc-t1--base.tfm \
tex-XCharter-Bold-lf-sc-t1.tfm \
tex-XCharter-Bold-lf-sc-t1.vf \
tex-XCharter-Bold-lf-sc-t2a--base.tfm \
tex-XCharter-Bold-lf-sc-t2a.tfm \
tex-XCharter-Bold-lf-sc-t2a.vf \
tex-XCharter-Bold-lf-sc-t2asrb--base.tfm \
tex-XCharter-Bold-lf-sc-t2asrb.tfm \
tex-XCharter-Bold-lf-sc-t2asrb.vf \
tex-XCharter-Bold-lf-t1--base.tfm \
tex-XCharter-Bold-lf-t1.tfm \
tex-XCharter-Bold-lf-t1.vf \
tex-XCharter-Bold-lf-t2a.tfm \
tex-XCharter-Bold-lf-t2asrb.tfm \
tex-XCharter-Bold-numr-ly1--base.tfm \
tex-XCharter-Bold-numr-ly1.tfm \
tex-XCharter-Bold-numr-ly1.vf \
tex-XCharter-Bold-numr-ot1.tfm \
tex-XCharter-Bold-numr-t1--base.tfm \
tex-XCharter-Bold-numr-t1.tfm \
tex-XCharter-Bold-numr-t1.vf \
tex-XCharter-Bold-osf-ly1--base.tfm \
tex-XCharter-Bold-osf-ly1.tfm \
tex-XCharter-Bold-osf-ly1.vf \
tex-XCharter-Bold-osf-ot1.tfm \
tex-XCharter-Bold-osf-sc-ly1--base.tfm \
tex-XCharter-Bold-osf-sc-ly1.tfm \
tex-XCharter-Bold-osf-sc-ly1.vf \
tex-XCharter-Bold-osf-sc-ot1--base.tfm \
tex-XCharter-Bold-osf-sc-ot1.tfm \
tex-XCharter-Bold-osf-sc-ot1.vf \
tex-XCharter-Bold-osf-sc-t1--base.tfm \
tex-XCharter-Bold-osf-sc-t1.tfm \
tex-XCharter-Bold-osf-sc-t1.vf \
tex-XCharter-Bold-osf-sc-t2a--base.tfm \
tex-XCharter-Bold-osf-sc-t2a.tfm \
tex-XCharter-Bold-osf-sc-t2a.vf \
tex-XCharter-Bold-osf-sc-t2asrb--base.tfm \
tex-XCharter-Bold-osf-sc-t2asrb.tfm \
tex-XCharter-Bold-osf-sc-t2asrb.vf \
tex-XCharter-Bold-osf-t1--base.tfm \
tex-XCharter-Bold-osf-t1.tfm \
tex-XCharter-Bold-osf-t1.vf \
tex-XCharter-Bold-osf-t2a.tfm \
tex-XCharter-Bold-osf-t2asrb.tfm \
tex-XCharter-Bold-sup-ly1--base.tfm \
tex-XCharter-Bold-sup-ly1.tfm \
tex-XCharter-Bold-sup-ly1.vf \
tex-XCharter-Bold-sup-ot1.tfm \
tex-XCharter-Bold-sup-t1--base.tfm \
tex-XCharter-Bold-sup-t1.tfm \
tex-XCharter-Bold-sup-t1.vf \
tex-XCharter-Bold-sup-t2a.tfm \
tex-XCharter-Bold-sup-t2asrb.tfm \
tex-XCharter-Bold-tlf-ly1--base.tfm \
tex-XCharter-Bold-tlf-ly1.tfm \
tex-XCharter-Bold-tlf-ly1.vf \
tex-XCharter-Bold-tlf-ot1.tfm \
tex-XCharter-Bold-tlf-ot1G.tfm \
tex-XCharter-Bold-tlf-ot1G.vf \
tex-XCharter-Bold-tlf-ot2.tfm \
tex-XCharter-Bold-tlf-sc-ly1--base.tfm \
tex-XCharter-Bold-tlf-sc-ly1.tfm \
tex-XCharter-Bold-tlf-sc-ly1.vf \
tex-XCharter-Bold-tlf-sc-ot1--base.tfm \
tex-XCharter-Bold-tlf-sc-ot1.tfm \
tex-XCharter-Bold-tlf-sc-ot1.vf \
tex-XCharter-Bold-tlf-sc-t1--base.tfm \
tex-XCharter-Bold-tlf-sc-t1.tfm \
tex-XCharter-Bold-tlf-sc-t1.vf \
tex-XCharter-Bold-tlf-sc-t2a--base.tfm \
tex-XCharter-Bold-tlf-sc-t2a.tfm \
tex-XCharter-Bold-tlf-sc-t2a.vf \
tex-XCharter-Bold-tlf-sc-t2asrb--base.tfm \
tex-XCharter-Bold-tlf-sc-t2asrb.tfm \
tex-XCharter-Bold-tlf-sc-t2asrb.vf \
tex-XCharter-Bold-tlf-t1--base.tfm \
tex-XCharter-Bold-tlf-t1.tfm \
tex-XCharter-Bold-tlf-t1.vf \
tex-XCharter-Bold-tlf-t2a.tfm \
tex-XCharter-Bold-tlf-t2asrb.tfm \
tex-XCharter-Bold-tosf-ly1--base.tfm \
tex-XCharter-Bold-tosf-ly1.tfm \
tex-XCharter-Bold-tosf-ly1.vf \
tex-XCharter-Bold-tosf-ot1.tfm \
tex-XCharter-Bold-tosf-sc-ly1--base.tfm \
tex-XCharter-Bold-tosf-sc-ly1.tfm \
tex-XCharter-Bold-tosf-sc-ly1.vf \
tex-XCharter-Bold-tosf-sc-ot1--base.tfm \
tex-XCharter-Bold-tosf-sc-ot1.tfm \
tex-XCharter-Bold-tosf-sc-ot1.vf \
tex-XCharter-Bold-tosf-sc-t1--base.tfm \
tex-XCharter-Bold-tosf-sc-t1.tfm \
tex-XCharter-Bold-tosf-sc-t1.vf \
tex-XCharter-Bold-tosf-sc-t2a--base.tfm \
tex-XCharter-Bold-tosf-sc-t2a.tfm \
tex-XCharter-Bold-tosf-sc-t2a.vf \
tex-XCharter-Bold-tosf-sc-t2asrb--base.tfm \
tex-XCharter-Bold-tosf-sc-t2asrb.tfm \
tex-XCharter-Bold-tosf-sc-t2asrb.vf \
tex-XCharter-Bold-tosf-t1--base.tfm \
tex-XCharter-Bold-tosf-t1.tfm \
tex-XCharter-Bold-tosf-t1.vf \
tex-XCharter-Bold-tosf-t2a.tfm \
tex-XCharter-Bold-tosf-t2asrb.tfm \
tex-XCharter-Bold-ts1--base.tfm \
tex-XCharter-Bold-ts1.tfm \
tex-XCharter-Bold-ts1.vf \
tex-XCharter-BoldItalic-dnom-ly1--base.tfm \
tex-XCharter-BoldItalic-dnom-ly1.tfm \
tex-XCharter-BoldItalic-dnom-ly1.vf \
tex-XCharter-BoldItalic-dnom-ot1.tfm \
tex-XCharter-BoldItalic-dnom-t1--base.tfm \
tex-XCharter-BoldItalic-dnom-t1.tfm \
tex-XCharter-BoldItalic-dnom-t1.vf \
tex-XCharter-BoldItalic-inf-ly1--base.tfm \
tex-XCharter-BoldItalic-inf-ly1.tfm \
tex-XCharter-BoldItalic-inf-ly1.vf \
tex-XCharter-BoldItalic-inf-ot1.tfm \
tex-XCharter-BoldItalic-inf-t1--base.tfm \
tex-XCharter-BoldItalic-inf-t1.tfm \
tex-XCharter-BoldItalic-inf-t1.vf \
tex-XCharter-BoldItalic-lf-ly1--base.tfm \
tex-XCharter-BoldItalic-lf-ly1.tfm \
tex-XCharter-BoldItalic-lf-ly1.vf \
tex-XCharter-BoldItalic-lf-ot1.tfm \
tex-XCharter-BoldItalic-lf-sc-ly1--base.tfm \
tex-XCharter-BoldItalic-lf-sc-ly1.tfm \
tex-XCharter-BoldItalic-lf-sc-ly1.vf \
tex-XCharter-BoldItalic-lf-sc-ot1--base.tfm \
tex-XCharter-BoldItalic-lf-sc-ot1.tfm \
tex-XCharter-BoldItalic-lf-sc-ot1.vf \
tex-XCharter-BoldItalic-lf-sc-t1--base.tfm \
tex-XCharter-BoldItalic-lf-sc-t1.tfm \
tex-XCharter-BoldItalic-lf-sc-t1.vf \
tex-XCharter-BoldItalic-lf-sc-t2a--base.tfm \
tex-XCharter-BoldItalic-lf-sc-t2a.tfm \
tex-XCharter-BoldItalic-lf-sc-t2a.vf \
tex-XCharter-BoldItalic-lf-sc-t2asrb--base.tfm \
tex-XCharter-BoldItalic-lf-sc-t2asrb.tfm \
tex-XCharter-BoldItalic-lf-sc-t2asrb.vf \
tex-XCharter-BoldItalic-lf-t1--base.tfm \
tex-XCharter-BoldItalic-lf-t1.tfm \
tex-XCharter-BoldItalic-lf-t1.vf \
tex-XCharter-BoldItalic-lf-t2a.tfm \
tex-XCharter-BoldItalic-lf-t2asrb.tfm \
tex-XCharter-BoldItalic-numr-ly1--base.tfm \
tex-XCharter-BoldItalic-numr-ly1.tfm \
tex-XCharter-BoldItalic-numr-ly1.vf \
tex-XCharter-BoldItalic-numr-ot1.tfm \
tex-XCharter-BoldItalic-numr-t1--base.tfm \
tex-XCharter-BoldItalic-numr-t1.tfm \
tex-XCharter-BoldItalic-numr-t1.vf \
tex-XCharter-BoldItalic-osf-ly1--base.tfm \
tex-XCharter-BoldItalic-osf-ly1.tfm \
tex-XCharter-BoldItalic-osf-ly1.vf \
tex-XCharter-BoldItalic-osf-ot1.tfm \
tex-XCharter-BoldItalic-osf-sc-ly1--base.tfm \
tex-XCharter-BoldItalic-osf-sc-ly1.tfm \
tex-XCharter-BoldItalic-osf-sc-ly1.vf \
tex-XCharter-BoldItalic-osf-sc-ot1--base.tfm \
tex-XCharter-BoldItalic-osf-sc-ot1.tfm \
tex-XCharter-BoldItalic-osf-sc-ot1.vf \
tex-XCharter-BoldItalic-osf-sc-t1--base.tfm \
tex-XCharter-BoldItalic-osf-sc-t1.tfm \
tex-XCharter-BoldItalic-osf-sc-t1.vf \
tex-XCharter-BoldItalic-osf-sc-t2a--base.tfm \
tex-XCharter-BoldItalic-osf-sc-t2a.tfm \
tex-XCharter-BoldItalic-osf-sc-t2a.vf \
tex-XCharter-BoldItalic-osf-sc-t2asrb--base.tfm \
tex-XCharter-BoldItalic-osf-sc-t2asrb.tfm \
tex-XCharter-BoldItalic-osf-sc-t2asrb.vf \
tex-XCharter-BoldItalic-osf-t1--base.tfm \
tex-XCharter-BoldItalic-osf-t1.tfm \
tex-XCharter-BoldItalic-osf-t1.vf \
tex-XCharter-BoldItalic-osf-t2a.tfm \
tex-XCharter-BoldItalic-osf-t2asrb.tfm \
tex-XCharter-BoldItalic-sup-ly1--base.tfm \
tex-XCharter-BoldItalic-sup-ly1.tfm \
tex-XCharter-BoldItalic-sup-ly1.vf \
tex-XCharter-BoldItalic-sup-ot1.tfm \
tex-XCharter-BoldItalic-sup-t1--base.tfm \
tex-XCharter-BoldItalic-sup-t1.tfm \
tex-XCharter-BoldItalic-sup-t1.vf \
tex-XCharter-BoldItalic-sup-t2a.tfm \
tex-XCharter-BoldItalic-sup-t2asrb.tfm \
tex-XCharter-BoldItalic-tlf-ly1--base.tfm \
tex-XCharter-BoldItalic-tlf-ly1.tfm \
tex-XCharter-BoldItalic-tlf-ly1.vf \
tex-XCharter-BoldItalic-tlf-ot1.tfm \
tex-XCharter-BoldItalic-tlf-ot1G.tfm \
tex-XCharter-BoldItalic-tlf-ot1G.vf \
tex-XCharter-BoldItalic-tlf-ot2.tfm \
tex-XCharter-BoldItalic-tlf-sc-ly1--base.tfm \
tex-XCharter-BoldItalic-tlf-sc-ly1.tfm \
tex-XCharter-BoldItalic-tlf-sc-ly1.vf \
tex-XCharter-BoldItalic-tlf-sc-ot1--base.tfm \
tex-XCharter-BoldItalic-tlf-sc-ot1.tfm \
tex-XCharter-BoldItalic-tlf-sc-ot1.vf \
tex-XCharter-BoldItalic-tlf-sc-t1--base.tfm \
tex-XCharter-BoldItalic-tlf-sc-t1.tfm \
tex-XCharter-BoldItalic-tlf-sc-t1.vf \
tex-XCharter-BoldItalic-tlf-sc-t2a--base.tfm \
tex-XCharter-BoldItalic-tlf-sc-t2a.tfm \
tex-XCharter-BoldItalic-tlf-sc-t2a.vf \
tex-XCharter-BoldItalic-tlf-sc-t2asrb--base.tfm \
tex-XCharter-BoldItalic-tlf-sc-t2asrb.tfm \
tex-XCharter-BoldItalic-tlf-sc-t2asrb.vf \
tex-XCharter-BoldItalic-tlf-t1--base.tfm \
tex-XCharter-BoldItalic-tlf-t1.tfm \
tex-XCharter-BoldItalic-tlf-t1.vf \
tex-XCharter-BoldItalic-tlf-t2a.tfm \
tex-XCharter-BoldItalic-tlf-t2asrb.tfm \
tex-XCharter-BoldItalic-tosf-ly1--base.tfm \
tex-XCharter-BoldItalic-tosf-ly1.tfm \
tex-XCharter-BoldItalic-tosf-ly1.vf \
tex-XCharter-BoldItalic-tosf-ot1.tfm \
tex-XCharter-BoldItalic-tosf-sc-ly1--base.tfm \
tex-XCharter-BoldItalic-tosf-sc-ly1.tfm \
tex-XCharter-BoldItalic-tosf-sc-ly1.vf \
tex-XCharter-BoldItalic-tosf-sc-ot1--base.tfm \
tex-XCharter-BoldItalic-tosf-sc-ot1.tfm \
tex-XCharter-BoldItalic-tosf-sc-ot1.vf \
tex-XCharter-BoldItalic-tosf-sc-t1--base.tfm \
tex-XCharter-BoldItalic-tosf-sc-t1.tfm \
tex-XCharter-BoldItalic-tosf-sc-t1.vf \
tex-XCharter-BoldItalic-tosf-sc-t2a--base.tfm \
tex-XCharter-BoldItalic-tosf-sc-t2a.tfm \
tex-XCharter-BoldItalic-tosf-sc-t2a.vf \
tex-XCharter-BoldItalic-tosf-sc-t2asrb--base.tfm \
tex-XCharter-BoldItalic-tosf-sc-t2asrb.tfm \
tex-XCharter-BoldItalic-tosf-sc-t2asrb.vf \
tex-XCharter-BoldItalic-tosf-t1--base.tfm \
tex-XCharter-BoldItalic-tosf-t1.tfm \
tex-XCharter-BoldItalic-tosf-t1.vf \
tex-XCharter-BoldItalic-tosf-t2a.tfm \
tex-XCharter-BoldItalic-tosf-t2asrb.tfm \
tex-XCharter-BoldItalic-ts1--base.tfm \
tex-XCharter-BoldItalic-ts1.tfm \
tex-XCharter-BoldItalic-ts1.vf \
tex-XCharter-BoldSlanted-dnom-ly1--base.tfm \
tex-XCharter-BoldSlanted-dnom-ly1.tfm \
tex-XCharter-BoldSlanted-dnom-ly1.vf \
tex-XCharter-BoldSlanted-dnom-ot1.tfm \
tex-XCharter-BoldSlanted-dnom-t1--base.tfm \
tex-XCharter-BoldSlanted-dnom-t1.tfm \
tex-XCharter-BoldSlanted-dnom-t1.vf \
tex-XCharter-BoldSlanted-inf-ly1--base.tfm \
tex-XCharter-BoldSlanted-inf-ly1.tfm \
tex-XCharter-BoldSlanted-inf-ly1.vf \
tex-XCharter-BoldSlanted-inf-ot1.tfm \
tex-XCharter-BoldSlanted-inf-t1--base.tfm \
tex-XCharter-BoldSlanted-inf-t1.tfm \
tex-XCharter-BoldSlanted-inf-t1.vf \
tex-XCharter-BoldSlanted-lf-ly1--base.tfm \
tex-XCharter-BoldSlanted-lf-ly1.tfm \
tex-XCharter-BoldSlanted-lf-ly1.vf \
tex-XCharter-BoldSlanted-lf-ot1.tfm \
tex-XCharter-BoldSlanted-lf-sc-ly1--base.tfm \
tex-XCharter-BoldSlanted-lf-sc-ly1.tfm \
tex-XCharter-BoldSlanted-lf-sc-ly1.vf \
tex-XCharter-BoldSlanted-lf-sc-ot1--base.tfm \
tex-XCharter-BoldSlanted-lf-sc-ot1.tfm \
tex-XCharter-BoldSlanted-lf-sc-ot1.vf \
tex-XCharter-BoldSlanted-lf-sc-t1--base.tfm \
tex-XCharter-BoldSlanted-lf-sc-t1.tfm \
tex-XCharter-BoldSlanted-lf-sc-t1.vf \
tex-XCharter-BoldSlanted-lf-sc-t2a--base.tfm \
tex-XCharter-BoldSlanted-lf-sc-t2a.tfm \
tex-XCharter-BoldSlanted-lf-sc-t2a.vf \
tex-XCharter-BoldSlanted-lf-sc-t2asrb--base.tfm \
tex-XCharter-BoldSlanted-lf-sc-t2asrb.tfm \
tex-XCharter-BoldSlanted-lf-sc-t2asrb.vf \
tex-XCharter-BoldSlanted-lf-t1--base.tfm \
tex-XCharter-BoldSlanted-lf-t1.tfm \
tex-XCharter-BoldSlanted-lf-t1.vf \
tex-XCharter-BoldSlanted-lf-t2a.tfm \
tex-XCharter-BoldSlanted-lf-t2asrb.tfm \
tex-XCharter-BoldSlanted-numr-ly1--base.tfm \
tex-XCharter-BoldSlanted-numr-ly1.tfm \
tex-XCharter-BoldSlanted-numr-ly1.vf \
tex-XCharter-BoldSlanted-numr-ot1.tfm \
tex-XCharter-BoldSlanted-numr-t1--base.tfm \
tex-XCharter-BoldSlanted-numr-t1.tfm \
tex-XCharter-BoldSlanted-numr-t1.vf \
tex-XCharter-BoldSlanted-osf-ly1--base.tfm \
tex-XCharter-BoldSlanted-osf-ly1.tfm \
tex-XCharter-BoldSlanted-osf-ly1.vf \
tex-XCharter-BoldSlanted-osf-ot1.tfm \
tex-XCharter-BoldSlanted-osf-sc-ly1--base.tfm \
tex-XCharter-BoldSlanted-osf-sc-ly1.tfm \
tex-XCharter-BoldSlanted-osf-sc-ly1.vf \
tex-XCharter-BoldSlanted-osf-sc-ot1--base.tfm \
tex-XCharter-BoldSlanted-osf-sc-ot1.tfm \
tex-XCharter-BoldSlanted-osf-sc-ot1.vf \
tex-XCharter-BoldSlanted-osf-sc-t1--base.tfm \
tex-XCharter-BoldSlanted-osf-sc-t1.tfm \
tex-XCharter-BoldSlanted-osf-sc-t1.vf \
tex-XCharter-BoldSlanted-osf-sc-t2a--base.tfm \
tex-XCharter-BoldSlanted-osf-sc-t2a.tfm \
tex-XCharter-BoldSlanted-osf-sc-t2a.vf \
tex-XCharter-BoldSlanted-osf-sc-t2asrb--base.tfm \
tex-XCharter-BoldSlanted-osf-sc-t2asrb.tfm \
tex-XCharter-BoldSlanted-osf-sc-t2asrb.vf \
tex-XCharter-BoldSlanted-osf-t1--base.tfm \
tex-XCharter-BoldSlanted-osf-t1.tfm \
tex-XCharter-BoldSlanted-osf-t1.vf \
tex-XCharter-BoldSlanted-osf-t2a.tfm \
tex-XCharter-BoldSlanted-osf-t2asrb.tfm \
tex-XCharter-BoldSlanted-sup-ly1--base.tfm \
tex-XCharter-BoldSlanted-sup-ly1.tfm \
tex-XCharter-BoldSlanted-sup-ly1.vf \
tex-XCharter-BoldSlanted-sup-ot1.tfm \
tex-XCharter-BoldSlanted-sup-t1--base.tfm \
tex-XCharter-BoldSlanted-sup-t1.tfm \
tex-XCharter-BoldSlanted-sup-t1.vf \
tex-XCharter-BoldSlanted-sup-t2a.tfm \
tex-XCharter-BoldSlanted-sup-t2asrb.tfm \
tex-XCharter-BoldSlanted-tlf-ly1--base.tfm \
tex-XCharter-BoldSlanted-tlf-ly1.tfm \
tex-XCharter-BoldSlanted-tlf-ly1.vf \
tex-XCharter-BoldSlanted-tlf-ot1.tfm \
tex-XCharter-BoldSlanted-tlf-ot2.tfm \
tex-XCharter-BoldSlanted-tlf-sc-ly1--base.tfm \
tex-XCharter-BoldSlanted-tlf-sc-ly1.tfm \
tex-XCharter-BoldSlanted-tlf-sc-ly1.vf \
tex-XCharter-BoldSlanted-tlf-sc-ot1--base.tfm \
tex-XCharter-BoldSlanted-tlf-sc-ot1.tfm \
tex-XCharter-BoldSlanted-tlf-sc-ot1.vf \
tex-XCharter-BoldSlanted-tlf-sc-t1--base.tfm \
tex-XCharter-BoldSlanted-tlf-sc-t1.tfm \
tex-XCharter-BoldSlanted-tlf-sc-t1.vf \
tex-XCharter-BoldSlanted-tlf-sc-t2a--base.tfm \
tex-XCharter-BoldSlanted-tlf-sc-t2a.tfm \
tex-XCharter-BoldSlanted-tlf-sc-t2a.vf \
tex-XCharter-BoldSlanted-tlf-sc-t2asrb--base.tfm \
tex-XCharter-BoldSlanted-tlf-sc-t2asrb.tfm \
tex-XCharter-BoldSlanted-tlf-sc-t2asrb.vf \
tex-XCharter-BoldSlanted-tlf-t1--base.tfm \
tex-XCharter-BoldSlanted-tlf-t1.tfm \
tex-XCharter-BoldSlanted-tlf-t1.vf \
tex-XCharter-BoldSlanted-tlf-t2a.tfm \
tex-XCharter-BoldSlanted-tlf-t2asrb.tfm \
tex-XCharter-BoldSlanted-tosf-ly1--base.tfm \
tex-XCharter-BoldSlanted-tosf-ly1.tfm \
tex-XCharter-BoldSlanted-tosf-ly1.vf \
tex-XCharter-BoldSlanted-tosf-ot1.tfm \
tex-XCharter-BoldSlanted-tosf-sc-ly1--base.tfm \
tex-XCharter-BoldSlanted-tosf-sc-ly1.tfm \
tex-XCharter-BoldSlanted-tosf-sc-ly1.vf \
tex-XCharter-BoldSlanted-tosf-sc-ot1--base.tfm \
tex-XCharter-BoldSlanted-tosf-sc-ot1.tfm \
tex-XCharter-BoldSlanted-tosf-sc-ot1.vf \
tex-XCharter-BoldSlanted-tosf-sc-t1--base.tfm \
tex-XCharter-BoldSlanted-tosf-sc-t1.tfm \
tex-XCharter-BoldSlanted-tosf-sc-t1.vf \
tex-XCharter-BoldSlanted-tosf-sc-t2a--base.tfm \
tex-XCharter-BoldSlanted-tosf-sc-t2a.tfm \
tex-XCharter-BoldSlanted-tosf-sc-t2a.vf \
tex-XCharter-BoldSlanted-tosf-sc-t2asrb--base.tfm \
tex-XCharter-BoldSlanted-tosf-sc-t2asrb.tfm \
tex-XCharter-BoldSlanted-tosf-sc-t2asrb.vf \
tex-XCharter-BoldSlanted-tosf-t1--base.tfm \
tex-XCharter-BoldSlanted-tosf-t1.tfm \
tex-XCharter-BoldSlanted-tosf-t1.vf \
tex-XCharter-BoldSlanted-tosf-t2a.tfm \
tex-XCharter-BoldSlanted-tosf-t2asrb.tfm \
tex-XCharter-BoldSlanted-ts1--base.tfm \
tex-XCharter-BoldSlanted-ts1.tfm \
tex-XCharter-BoldSlanted-ts1.vf \
tex-XCharter-Ita-alph.tfm \
tex-XCharter-Italic-dnom-ly1--base.tfm \
tex-XCharter-Italic-dnom-ly1.tfm \
tex-XCharter-Italic-dnom-ly1.vf \
tex-XCharter-Italic-dnom-ot1.tfm \
tex-XCharter-Italic-dnom-t1--base.tfm \
tex-XCharter-Italic-dnom-t1.tfm \
tex-XCharter-Italic-dnom-t1.vf \
tex-XCharter-Italic-inf-ly1--base.tfm \
tex-XCharter-Italic-inf-ly1.tfm \
tex-XCharter-Italic-inf-ly1.vf \
tex-XCharter-Italic-inf-ot1.tfm \
tex-XCharter-Italic-inf-t1--base.tfm \
tex-XCharter-Italic-inf-t1.tfm \
tex-XCharter-Italic-inf-t1.vf \
tex-XCharter-Italic-lf-ly1--base.tfm \
tex-XCharter-Italic-lf-ly1.tfm \
tex-XCharter-Italic-lf-ly1.vf \
tex-XCharter-Italic-lf-ot1.tfm \
tex-XCharter-Italic-lf-sc-ly1--base.tfm \
tex-XCharter-Italic-lf-sc-ly1.tfm \
tex-XCharter-Italic-lf-sc-ly1.vf \
tex-XCharter-Italic-lf-sc-ot1--base.tfm \
tex-XCharter-Italic-lf-sc-ot1.tfm \
tex-XCharter-Italic-lf-sc-ot1.vf \
tex-XCharter-Italic-lf-sc-t1--base.tfm \
tex-XCharter-Italic-lf-sc-t1.tfm \
tex-XCharter-Italic-lf-sc-t1.vf \
tex-XCharter-Italic-lf-sc-t2a--base.tfm \
tex-XCharter-Italic-lf-sc-t2a.tfm \
tex-XCharter-Italic-lf-sc-t2a.vf \
tex-XCharter-Italic-lf-sc-t2asrb--base.tfm \
tex-XCharter-Italic-lf-sc-t2asrb.tfm \
tex-XCharter-Italic-lf-sc-t2asrb.vf \
tex-XCharter-Italic-lf-t1--base.tfm \
tex-XCharter-Italic-lf-t1.tfm \
tex-XCharter-Italic-lf-t1.vf \
tex-XCharter-Italic-lf-t2a.tfm \
tex-XCharter-Italic-lf-t2asrb.tfm \
tex-XCharter-Italic-numr-ly1--base.tfm \
tex-XCharter-Italic-numr-ly1.tfm \
tex-XCharter-Italic-numr-ly1.vf \
tex-XCharter-Italic-numr-ot1.tfm \
tex-XCharter-Italic-numr-t1--base.tfm \
tex-XCharter-Italic-numr-t1.tfm \
tex-XCharter-Italic-numr-t1.vf \
tex-XCharter-Italic-osf-ly1--base.tfm \
tex-XCharter-Italic-osf-ly1.tfm \
tex-XCharter-Italic-osf-ly1.vf \
tex-XCharter-Italic-osf-ot1.tfm \
tex-XCharter-Italic-osf-sc-ly1--base.tfm \
tex-XCharter-Italic-osf-sc-ly1.tfm \
tex-XCharter-Italic-osf-sc-ly1.vf \
tex-XCharter-Italic-osf-sc-ot1--base.tfm \
tex-XCharter-Italic-osf-sc-ot1.tfm \
tex-XCharter-Italic-osf-sc-ot1.vf \
tex-XCharter-Italic-osf-sc-t1--base.tfm \
tex-XCharter-Italic-osf-sc-t1.tfm \
tex-XCharter-Italic-osf-sc-t1.vf \
tex-XCharter-Italic-osf-sc-t2a--base.tfm \
tex-XCharter-Italic-osf-sc-t2a.tfm \
tex-XCharter-Italic-osf-sc-t2a.vf \
tex-XCharter-Italic-osf-sc-t2asrb--base.tfm \
tex-XCharter-Italic-osf-sc-t2asrb.tfm \
tex-XCharter-Italic-osf-sc-t2asrb.vf \
tex-XCharter-Italic-osf-t1--base.tfm \
tex-XCharter-Italic-osf-t1.tfm \
tex-XCharter-Italic-osf-t1.vf \
tex-XCharter-Italic-osf-t2a.tfm \
tex-XCharter-Italic-osf-t2asrb.tfm \
tex-XCharter-Italic-sup-ly1--base.tfm \
tex-XCharter-Italic-sup-ly1.tfm \
tex-XCharter-Italic-sup-ly1.vf \
tex-XCharter-Italic-sup-ot1.tfm \
tex-XCharter-Italic-sup-t1--base.tfm \
tex-XCharter-Italic-sup-t1.tfm \
tex-XCharter-Italic-sup-t1.vf \
tex-XCharter-Italic-sup-t2a.tfm \
tex-XCharter-Italic-sup-t2asrb.tfm \
tex-XCharter-Italic-tlf-ly1--base.tfm \
tex-XCharter-Italic-tlf-ly1.tfm \
tex-XCharter-Italic-tlf-ly1.vf \
tex-XCharter-Italic-tlf-ot1.tfm \
tex-XCharter-Italic-tlf-ot1G.tfm \
tex-XCharter-Italic-tlf-ot1G.vf \
tex-XCharter-Italic-tlf-ot2.tfm \
tex-XCharter-Italic-tlf-sc-ly1--base.tfm \
tex-XCharter-Italic-tlf-sc-ly1.tfm \
tex-XCharter-Italic-tlf-sc-ly1.vf \
tex-XCharter-Italic-tlf-sc-ot1--base.tfm \
tex-XCharter-Italic-tlf-sc-ot1.tfm \
tex-XCharter-Italic-tlf-sc-ot1.vf \
tex-XCharter-Italic-tlf-sc-t1--base.tfm \
tex-XCharter-Italic-tlf-sc-t1.tfm \
tex-XCharter-Italic-tlf-sc-t1.vf \
tex-XCharter-Italic-tlf-sc-t2a--base.tfm \
tex-XCharter-Italic-tlf-sc-t2a.tfm \
tex-XCharter-Italic-tlf-sc-t2a.vf \
tex-XCharter-Italic-tlf-sc-t2asrb--base.tfm \
tex-XCharter-Italic-tlf-sc-t2asrb.tfm \
tex-XCharter-Italic-tlf-sc-t2asrb.vf \
tex-XCharter-Italic-tlf-t1--base.tfm \
tex-XCharter-Italic-tlf-t1.tfm \
tex-XCharter-Italic-tlf-t1.vf \
tex-XCharter-Italic-tlf-t2a.tfm \
tex-XCharter-Italic-tlf-t2asrb.tfm \
tex-XCharter-Italic-tosf-ly1--base.tfm \
tex-XCharter-Italic-tosf-ly1.tfm \
tex-XCharter-Italic-tosf-ly1.vf \
tex-XCharter-Italic-tosf-ot1.tfm \
tex-XCharter-Italic-tosf-sc-ly1--base.tfm \
tex-XCharter-Italic-tosf-sc-ly1.tfm \
tex-XCharter-Italic-tosf-sc-ly1.vf \
tex-XCharter-Italic-tosf-sc-ot1--base.tfm \
tex-XCharter-Italic-tosf-sc-ot1.tfm \
tex-XCharter-Italic-tosf-sc-ot1.vf \
tex-XCharter-Italic-tosf-sc-t1--base.tfm \
tex-XCharter-Italic-tosf-sc-t1.tfm \
tex-XCharter-Italic-tosf-sc-t1.vf \
tex-XCharter-Italic-tosf-sc-t2a--base.tfm \
tex-XCharter-Italic-tosf-sc-t2a.tfm \
tex-XCharter-Italic-tosf-sc-t2a.vf \
tex-XCharter-Italic-tosf-sc-t2asrb--base.tfm \
tex-XCharter-Italic-tosf-sc-t2asrb.tfm \
tex-XCharter-Italic-tosf-sc-t2asrb.vf \
tex-XCharter-Italic-tosf-t1--base.tfm \
tex-XCharter-Italic-tosf-t1.tfm \
tex-XCharter-Italic-tosf-t1.vf \
tex-XCharter-Italic-tosf-t2a.tfm \
tex-XCharter-Italic-tosf-t2asrb.tfm \
tex-XCharter-Italic-ts1--base.tfm \
tex-XCharter-Italic-ts1.tfm \
tex-XCharter-Italic-ts1.vf \
tex-XCharter-Roman-dnom-ly1--base.tfm \
tex-XCharter-Roman-dnom-ly1.tfm \
tex-XCharter-Roman-dnom-ly1.vf \
tex-XCharter-Roman-dnom-ot1.tfm \
tex-XCharter-Roman-dnom-t1--base.tfm \
tex-XCharter-Roman-dnom-t1.tfm \
tex-XCharter-Roman-dnom-t1.vf \
tex-XCharter-Roman-inf-ly1--base.tfm \
tex-XCharter-Roman-inf-ly1.tfm \
tex-XCharter-Roman-inf-ly1.vf \
tex-XCharter-Roman-inf-ot1.tfm \
tex-XCharter-Roman-inf-t1--base.tfm \
tex-XCharter-Roman-inf-t1.tfm \
tex-XCharter-Roman-inf-t1.vf \
tex-XCharter-Roman-lf-ly1--base.tfm \
tex-XCharter-Roman-lf-ly1.tfm \
tex-XCharter-Roman-lf-ly1.vf \
tex-XCharter-Roman-lf-ot1.tfm \
tex-XCharter-Roman-lf-sc-ly1--base.tfm \
tex-XCharter-Roman-lf-sc-ly1.tfm \
tex-XCharter-Roman-lf-sc-ly1.vf \
tex-XCharter-Roman-lf-sc-ot1--base.tfm \
tex-XCharter-Roman-lf-sc-ot1.tfm \
tex-XCharter-Roman-lf-sc-ot1.vf \
tex-XCharter-Roman-lf-sc-t1--base.tfm \
tex-XCharter-Roman-lf-sc-t1.tfm \
tex-XCharter-Roman-lf-sc-t1.vf \
tex-XCharter-Roman-lf-sc-t2a--base.tfm \
tex-XCharter-Roman-lf-sc-t2a.tfm \
tex-XCharter-Roman-lf-sc-t2a.vf \
tex-XCharter-Roman-lf-sc-t2asrb--base.tfm \
tex-XCharter-Roman-lf-sc-t2asrb.tfm \
tex-XCharter-Roman-lf-sc-t2asrb.vf \
tex-XCharter-Roman-lf-t1--base.tfm \
tex-XCharter-Roman-lf-t1.tfm \
tex-XCharter-Roman-lf-t1.vf \
tex-XCharter-Roman-lf-t2a.tfm \
tex-XCharter-Roman-lf-t2asrb.tfm \
tex-XCharter-Roman-numr-ly1--base.tfm \
tex-XCharter-Roman-numr-ly1.tfm \
tex-XCharter-Roman-numr-ly1.vf \
tex-XCharter-Roman-numr-ot1.tfm \
tex-XCharter-Roman-numr-t1--base.tfm \
tex-XCharter-Roman-numr-t1.tfm \
tex-XCharter-Roman-numr-t1.vf \
tex-XCharter-Roman-osf-ly1--base.tfm \
tex-XCharter-Roman-osf-ly1.tfm \
tex-XCharter-Roman-osf-ly1.vf \
tex-XCharter-Roman-osf-ot1.tfm \
tex-XCharter-Roman-osf-sc-ly1--base.tfm \
tex-XCharter-Roman-osf-sc-ly1.tfm \
tex-XCharter-Roman-osf-sc-ly1.vf \
tex-XCharter-Roman-osf-sc-ot1--base.tfm \
tex-XCharter-Roman-osf-sc-ot1.tfm \
tex-XCharter-Roman-osf-sc-ot1.vf \
tex-XCharter-Roman-osf-sc-t1--base.tfm \
tex-XCharter-Roman-osf-sc-t1.tfm \
tex-XCharter-Roman-osf-sc-t1.vf \
tex-XCharter-Roman-osf-sc-t2a--base.tfm \
tex-XCharter-Roman-osf-sc-t2a.tfm \
tex-XCharter-Roman-osf-sc-t2a.vf \
tex-XCharter-Roman-osf-sc-t2asrb--base.tfm \
tex-XCharter-Roman-osf-sc-t2asrb.tfm \
tex-XCharter-Roman-osf-sc-t2asrb.vf \
tex-XCharter-Roman-osf-t1--base.tfm \
tex-XCharter-Roman-osf-t1.tfm \
tex-XCharter-Roman-osf-t1.vf \
tex-XCharter-Roman-osf-t2a.tfm \
tex-XCharter-Roman-osf-t2asrb.tfm \
tex-XCharter-Roman-sup-ly1--base.tfm \
tex-XCharter-Roman-sup-ly1.tfm \
tex-XCharter-Roman-sup-ly1.vf \
tex-XCharter-Roman-sup-ot1.tfm \
tex-XCharter-Roman-sup-t1--base.tfm \
tex-XCharter-Roman-sup-t1.tfm \
tex-XCharter-Roman-sup-t1.vf \
tex-XCharter-Roman-sup-t2a.tfm \
tex-XCharter-Roman-sup-t2asrb.tfm \
tex-XCharter-Roman-tlf-ly1--base.tfm \
tex-XCharter-Roman-tlf-ly1.tfm \
tex-XCharter-Roman-tlf-ly1.vf \
tex-XCharter-Roman-tlf-ot1.tfm \
tex-XCharter-Roman-tlf-ot1G.tfm \
tex-XCharter-Roman-tlf-ot1G.vf \
tex-XCharter-Roman-tlf-ot2.tfm \
tex-XCharter-Roman-tlf-sc-ly1--base.tfm \
tex-XCharter-Roman-tlf-sc-ly1.tfm \
tex-XCharter-Roman-tlf-sc-ly1.vf \
tex-XCharter-Roman-tlf-sc-ot1--base.tfm \
tex-XCharter-Roman-tlf-sc-ot1.tfm \
tex-XCharter-Roman-tlf-sc-ot1.vf \
tex-XCharter-Roman-tlf-sc-t1--base.tfm \
tex-XCharter-Roman-tlf-sc-t1.tfm \
tex-XCharter-Roman-tlf-sc-t1.vf \
tex-XCharter-Roman-tlf-sc-t2a--base.tfm \
tex-XCharter-Roman-tlf-sc-t2a.tfm \
tex-XCharter-Roman-tlf-sc-t2a.vf \
tex-XCharter-Roman-tlf-sc-t2asrb--base.tfm \
tex-XCharter-Roman-tlf-sc-t2asrb.tfm \
tex-XCharter-Roman-tlf-sc-t2asrb.vf \
tex-XCharter-Roman-tlf-t1--base.tfm \
tex-XCharter-Roman-tlf-t1.tfm \
tex-XCharter-Roman-tlf-t1.vf \
tex-XCharter-Roman-tlf-t2a.tfm \
tex-XCharter-Roman-tlf-t2asrb.tfm \
tex-XCharter-Roman-tosf-ly1--base.tfm \
tex-XCharter-Roman-tosf-ly1.tfm \
tex-XCharter-Roman-tosf-ly1.vf \
tex-XCharter-Roman-tosf-ot1.tfm \
tex-XCharter-Roman-tosf-sc-ly1--base.tfm \
tex-XCharter-Roman-tosf-sc-ly1.tfm \
tex-XCharter-Roman-tosf-sc-ly1.vf \
tex-XCharter-Roman-tosf-sc-ot1--base.tfm \
tex-XCharter-Roman-tosf-sc-ot1.tfm \
tex-XCharter-Roman-tosf-sc-ot1.vf \
tex-XCharter-Roman-tosf-sc-t1--base.tfm \
tex-XCharter-Roman-tosf-sc-t1.tfm \
tex-XCharter-Roman-tosf-sc-t1.vf \
tex-XCharter-Roman-tosf-sc-t2a--base.tfm \
tex-XCharter-Roman-tosf-sc-t2a.tfm \
tex-XCharter-Roman-tosf-sc-t2a.vf \
tex-XCharter-Roman-tosf-sc-t2asrb--base.tfm \
tex-XCharter-Roman-tosf-sc-t2asrb.tfm \
tex-XCharter-Roman-tosf-sc-t2asrb.vf \
tex-XCharter-Roman-tosf-t1--base.tfm \
tex-XCharter-Roman-tosf-t1.tfm \
tex-XCharter-Roman-tosf-t1.vf \
tex-XCharter-Roman-tosf-t2a.tfm \
tex-XCharter-Roman-tosf-t2asrb.tfm \
tex-XCharter-Roman-ts1--base.tfm \
tex-XCharter-Roman-ts1.tfm \
tex-XCharter-Roman-ts1.vf \
tex-XCharter-Slanted-dnom-ly1--base.tfm \
tex-XCharter-Slanted-dnom-ly1.tfm \
tex-XCharter-Slanted-dnom-ly1.vf \
tex-XCharter-Slanted-dnom-ot1.tfm \
tex-XCharter-Slanted-dnom-t1--base.tfm \
tex-XCharter-Slanted-dnom-t1.tfm \
tex-XCharter-Slanted-dnom-t1.vf \
tex-XCharter-Slanted-inf-ly1--base.tfm \
tex-XCharter-Slanted-inf-ly1.tfm \
tex-XCharter-Slanted-inf-ly1.vf \
tex-XCharter-Slanted-inf-ot1.tfm \
tex-XCharter-Slanted-inf-t1--base.tfm \
tex-XCharter-Slanted-inf-t1.tfm \
tex-XCharter-Slanted-inf-t1.vf \
tex-XCharter-Slanted-lf-ly1--base.tfm \
tex-XCharter-Slanted-lf-ly1.tfm \
tex-XCharter-Slanted-lf-ly1.vf \
tex-XCharter-Slanted-lf-ot1.tfm \
tex-XCharter-Slanted-lf-sc-ly1--base.tfm \
tex-XCharter-Slanted-lf-sc-ly1.tfm \
tex-XCharter-Slanted-lf-sc-ly1.vf \
tex-XCharter-Slanted-lf-sc-ot1--base.tfm \
tex-XCharter-Slanted-lf-sc-ot1.tfm \
tex-XCharter-Slanted-lf-sc-ot1.vf \
tex-XCharter-Slanted-lf-sc-t1--base.tfm \
tex-XCharter-Slanted-lf-sc-t1.tfm \
tex-XCharter-Slanted-lf-sc-t1.vf \
tex-XCharter-Slanted-lf-sc-t2a--base.tfm \
tex-XCharter-Slanted-lf-sc-t2a.tfm \
tex-XCharter-Slanted-lf-sc-t2a.vf \
tex-XCharter-Slanted-lf-sc-t2asrb--base.tfm \
tex-XCharter-Slanted-lf-sc-t2asrb.tfm \
tex-XCharter-Slanted-lf-sc-t2asrb.vf \
tex-XCharter-Slanted-lf-t1--base.tfm \
tex-XCharter-Slanted-lf-t1.tfm \
tex-XCharter-Slanted-lf-t1.vf \
tex-XCharter-Slanted-lf-t2a.tfm \
tex-XCharter-Slanted-lf-t2asrb.tfm \
tex-XCharter-Slanted-numr-ly1--base.tfm \
tex-XCharter-Slanted-numr-ly1.tfm \
tex-XCharter-Slanted-numr-ly1.vf \
tex-XCharter-Slanted-numr-ot1.tfm \
tex-XCharter-Slanted-numr-t1--base.tfm \
tex-XCharter-Slanted-numr-t1.tfm \
tex-XCharter-Slanted-numr-t1.vf \
tex-XCharter-Slanted-osf-ly1--base.tfm \
tex-XCharter-Slanted-osf-ly1.tfm \
tex-XCharter-Slanted-osf-ly1.vf \
tex-XCharter-Slanted-osf-ot1.tfm \
tex-XCharter-Slanted-osf-sc-ly1--base.tfm \
tex-XCharter-Slanted-osf-sc-ly1.tfm \
tex-XCharter-Slanted-osf-sc-ly1.vf \
tex-XCharter-Slanted-osf-sc-ot1--base.tfm \
tex-XCharter-Slanted-osf-sc-ot1.tfm \
tex-XCharter-Slanted-osf-sc-ot1.vf \
tex-XCharter-Slanted-osf-sc-t1--base.tfm \
tex-XCharter-Slanted-osf-sc-t1.tfm \
tex-XCharter-Slanted-osf-sc-t1.vf \
tex-XCharter-Slanted-osf-sc-t2a--base.tfm \
tex-XCharter-Slanted-osf-sc-t2a.tfm \
tex-XCharter-Slanted-osf-sc-t2a.vf \
tex-XCharter-Slanted-osf-sc-t2asrb--base.tfm \
tex-XCharter-Slanted-osf-sc-t2asrb.tfm \
tex-XCharter-Slanted-osf-sc-t2asrb.vf \
tex-XCharter-Slanted-osf-t1--base.tfm \
tex-XCharter-Slanted-osf-t1.tfm \
tex-XCharter-Slanted-osf-t1.vf \
tex-XCharter-Slanted-osf-t2a.tfm \
tex-XCharter-Slanted-osf-t2asrb.tfm \
tex-XCharter-Slanted-sup-ly1--base.tfm \
tex-XCharter-Slanted-sup-ly1.tfm \
tex-XCharter-Slanted-sup-ly1.vf \
tex-XCharter-Slanted-sup-ot1.tfm \
tex-XCharter-Slanted-sup-t1--base.tfm \
tex-XCharter-Slanted-sup-t1.tfm \
tex-XCharter-Slanted-sup-t1.vf \
tex-XCharter-Slanted-sup-t2a.tfm \
tex-XCharter-Slanted-sup-t2asrb.tfm \
tex-XCharter-Slanted-tlf-ly1--base.tfm \
tex-XCharter-Slanted-tlf-ly1.tfm \
tex-XCharter-Slanted-tlf-ly1.vf \
tex-XCharter-Slanted-tlf-ot1.tfm \
tex-XCharter-Slanted-tlf-ot2.tfm \
tex-XCharter-Slanted-tlf-sc-ly1--base.tfm \
tex-XCharter-Slanted-tlf-sc-ly1.tfm \
tex-XCharter-Slanted-tlf-sc-ly1.vf \
tex-XCharter-Slanted-tlf-sc-ot1--base.tfm \
tex-XCharter-Slanted-tlf-sc-ot1.tfm \
tex-XCharter-Slanted-tlf-sc-ot1.vf \
tex-XCharter-Slanted-tlf-sc-t1--base.tfm \
tex-XCharter-Slanted-tlf-sc-t1.tfm \
tex-XCharter-Slanted-tlf-sc-t1.vf \
tex-XCharter-Slanted-tlf-sc-t2a--base.tfm \
tex-XCharter-Slanted-tlf-sc-t2a.tfm \
tex-XCharter-Slanted-tlf-sc-t2a.vf \
tex-XCharter-Slanted-tlf-sc-t2asrb--base.tfm \
tex-XCharter-Slanted-tlf-sc-t2asrb.tfm \
tex-XCharter-Slanted-tlf-sc-t2asrb.vf \
tex-XCharter-Slanted-tlf-t1--base.tfm \
tex-XCharter-Slanted-tlf-t1.tfm \
tex-XCharter-Slanted-tlf-t1.vf \
tex-XCharter-Slanted-tlf-t2a.tfm \
tex-XCharter-Slanted-tlf-t2asrb.tfm \
tex-XCharter-Slanted-tosf-ly1--base.tfm \
tex-XCharter-Slanted-tosf-ly1.tfm \
tex-XCharter-Slanted-tosf-ly1.vf \
tex-XCharter-Slanted-tosf-ot1.tfm \
tex-XCharter-Slanted-tosf-sc-ly1--base.tfm \
tex-XCharter-Slanted-tosf-sc-ly1.tfm \
tex-XCharter-Slanted-tosf-sc-ly1.vf \
tex-XCharter-Slanted-tosf-sc-ot1--base.tfm \
tex-XCharter-Slanted-tosf-sc-ot1.tfm \
tex-XCharter-Slanted-tosf-sc-ot1.vf \
tex-XCharter-Slanted-tosf-sc-t1--base.tfm \
tex-XCharter-Slanted-tosf-sc-t1.tfm \
tex-XCharter-Slanted-tosf-sc-t1.vf \
tex-XCharter-Slanted-tosf-sc-t2a--base.tfm \
tex-XCharter-Slanted-tosf-sc-t2a.tfm \
tex-XCharter-Slanted-tosf-sc-t2a.vf \
tex-XCharter-Slanted-tosf-sc-t2asrb--base.tfm \
tex-XCharter-Slanted-tosf-sc-t2asrb.tfm \
tex-XCharter-Slanted-tosf-sc-t2asrb.vf \
tex-XCharter-Slanted-tosf-t1--base.tfm \
tex-XCharter-Slanted-tosf-t1.tfm \
tex-XCharter-Slanted-tosf-t1.vf \
tex-XCharter-Slanted-tosf-t2a.tfm \
tex-XCharter-Slanted-tosf-t2asrb.tfm \
tex-XCharter-Slanted-ts1--base.tfm \
tex-XCharter-Slanted-ts1.tfm \
tex-XCharter-Slanted-ts1.vf \
tex-XCharter-osf.tfm \
tex-XCharter.map \
tex-XCharter.sty \
tex-XCharter1-Bold-osf-ly1--base.tfm \
tex-XCharter1-Bold-osf-ly1.tfm \
tex-XCharter1-Bold-osf-ly1.vf \
tex-XCharter1-Bold-osf-ot1.tfm \
tex-XCharter1-Bold-osf-ot1.vf \
tex-XCharter1-Bold-osf-sc-ly1--base.tfm \
tex-XCharter1-Bold-osf-sc-ly1.tfm \
tex-XCharter1-Bold-osf-sc-ly1.vf \
tex-XCharter1-Bold-osf-sc-ot1--base.tfm \
tex-XCharter1-Bold-osf-sc-ot1.tfm \
tex-XCharter1-Bold-osf-sc-ot1.vf \
tex-XCharter1-Bold-osf-sc-t1--base.tfm \
tex-XCharter1-Bold-osf-sc-t1.tfm \
tex-XCharter1-Bold-osf-sc-t1.vf \
tex-XCharter1-Bold-osf-sc-t2a--base.tfm \
tex-XCharter1-Bold-osf-sc-t2a.tfm \
tex-XCharter1-Bold-osf-sc-t2a.vf \
tex-XCharter1-Bold-osf-sc-t2asrb--base.tfm \
tex-XCharter1-Bold-osf-sc-t2asrb.tfm \
tex-XCharter1-Bold-osf-sc-t2asrb.vf \
tex-XCharter1-Bold-osf-t1--base.tfm \
tex-XCharter1-Bold-osf-t1.tfm \
tex-XCharter1-Bold-osf-t1.vf \
tex-XCharter1-Bold-osf-t2a.tfm \
tex-XCharter1-Bold-osf-t2a.vf \
tex-XCharter1-Bold-osf-t2asrb.tfm \
tex-XCharter1-Bold-osf-t2asrb.vf \
tex-XCharter1-Bold-tosf-ly1--base.tfm \
tex-XCharter1-Bold-tosf-ly1.tfm \
tex-XCharter1-Bold-tosf-ly1.vf \
tex-XCharter1-Bold-tosf-ot1.tfm \
tex-XCharter1-Bold-tosf-ot1.vf \
tex-XCharter1-Bold-tosf-sc-ly1--base.tfm \
tex-XCharter1-Bold-tosf-sc-ly1.tfm \
tex-XCharter1-Bold-tosf-sc-ly1.vf \
tex-XCharter1-Bold-tosf-sc-ot1--base.tfm \
tex-XCharter1-Bold-tosf-sc-ot1.tfm \
tex-XCharter1-Bold-tosf-sc-ot1.vf \
tex-XCharter1-Bold-tosf-sc-t1--base.tfm \
tex-XCharter1-Bold-tosf-sc-t1.tfm \
tex-XCharter1-Bold-tosf-sc-t1.vf \
tex-XCharter1-Bold-tosf-sc-t2a--base.tfm \
tex-XCharter1-Bold-tosf-sc-t2a.tfm \
tex-XCharter1-Bold-tosf-sc-t2a.vf \
tex-XCharter1-Bold-tosf-sc-t2asrb--base.tfm \
tex-XCharter1-Bold-tosf-sc-t2asrb.tfm \
tex-XCharter1-Bold-tosf-sc-t2asrb.vf \
tex-XCharter1-Bold-tosf-t1--base.tfm \
tex-XCharter1-Bold-tosf-t1.tfm \
tex-XCharter1-Bold-tosf-t1.vf \
tex-XCharter1-Bold-tosf-t2a.tfm \
tex-XCharter1-Bold-tosf-t2a.vf \
tex-XCharter1-Bold-tosf-t2asrb.tfm \
tex-XCharter1-Bold-tosf-t2asrb.vf \
tex-XCharter1-Bold-ts1--base.tfm \
tex-XCharter1-Bold-ts1.tfm \
tex-XCharter1-Bold-ts1.vf \
tex-XCharter1-BoldItalic-osf-ly1--base.tfm \
tex-XCharter1-BoldItalic-osf-ly1.tfm \
tex-XCharter1-BoldItalic-osf-ly1.vf \
tex-XCharter1-BoldItalic-osf-ot1.tfm \
tex-XCharter1-BoldItalic-osf-ot1.vf \
tex-XCharter1-BoldItalic-osf-sc-ly1--base.tfm \
tex-XCharter1-BoldItalic-osf-sc-ly1.tfm \
tex-XCharter1-BoldItalic-osf-sc-ly1.vf \
tex-XCharter1-BoldItalic-osf-sc-ot1--base.tfm \
tex-XCharter1-BoldItalic-osf-sc-ot1.tfm \
tex-XCharter1-BoldItalic-osf-sc-ot1.vf \
tex-XCharter1-BoldItalic-osf-sc-t1--base.tfm \
tex-XCharter1-BoldItalic-osf-sc-t1.tfm \
tex-XCharter1-BoldItalic-osf-sc-t1.vf \
tex-XCharter1-BoldItalic-osf-sc-t2a--base.tfm \
tex-XCharter1-BoldItalic-osf-sc-t2a.tfm \
tex-XCharter1-BoldItalic-osf-sc-t2a.vf \
tex-XCharter1-BoldItalic-osf-sc-t2asrb--base.tfm \
tex-XCharter1-BoldItalic-osf-sc-t2asrb.tfm \
tex-XCharter1-BoldItalic-osf-sc-t2asrb.vf \
tex-XCharter1-BoldItalic-osf-t1--base.tfm \
tex-XCharter1-BoldItalic-osf-t1.tfm \
tex-XCharter1-BoldItalic-osf-t1.vf \
tex-XCharter1-BoldItalic-osf-t2a.tfm \
tex-XCharter1-BoldItalic-osf-t2a.vf \
tex-XCharter1-BoldItalic-osf-t2asrb.tfm \
tex-XCharter1-BoldItalic-osf-t2asrb.vf \
tex-XCharter1-BoldItalic-tosf-ly1--base.tfm \
tex-XCharter1-BoldItalic-tosf-ly1.tfm \
tex-XCharter1-BoldItalic-tosf-ly1.vf \
tex-XCharter1-BoldItalic-tosf-ot1.tfm \
tex-XCharter1-BoldItalic-tosf-ot1.vf \
tex-XCharter1-BoldItalic-tosf-sc-ly1--base.tfm \
tex-XCharter1-BoldItalic-tosf-sc-ly1.tfm \
tex-XCharter1-BoldItalic-tosf-sc-ly1.vf \
tex-XCharter1-BoldItalic-tosf-sc-ot1--base.tfm \
tex-XCharter1-BoldItalic-tosf-sc-ot1.tfm \
tex-XCharter1-BoldItalic-tosf-sc-ot1.vf \
tex-XCharter1-BoldItalic-tosf-sc-t1--base.tfm \
tex-XCharter1-BoldItalic-tosf-sc-t1.tfm \
tex-XCharter1-BoldItalic-tosf-sc-t1.vf \
tex-XCharter1-BoldItalic-tosf-sc-t2a--base.tfm \
tex-XCharter1-BoldItalic-tosf-sc-t2a.tfm \
tex-XCharter1-BoldItalic-tosf-sc-t2a.vf \
tex-XCharter1-BoldItalic-tosf-sc-t2asrb--base.tfm \
tex-XCharter1-BoldItalic-tosf-sc-t2asrb.tfm \
tex-XCharter1-BoldItalic-tosf-sc-t2asrb.vf \
tex-XCharter1-BoldItalic-tosf-t1--base.tfm \
tex-XCharter1-BoldItalic-tosf-t1.tfm \
tex-XCharter1-BoldItalic-tosf-t1.vf \
tex-XCharter1-BoldItalic-tosf-t2a.tfm \
tex-XCharter1-BoldItalic-tosf-t2a.vf \
tex-XCharter1-BoldItalic-tosf-t2asrb.tfm \
tex-XCharter1-BoldItalic-tosf-t2asrb.vf \
tex-XCharter1-BoldItalic-ts1--base.tfm \
tex-XCharter1-BoldItalic-ts1.tfm \
tex-XCharter1-BoldItalic-ts1.vf \
tex-XCharter1-BoldSlanted-osf-ly1--base.tfm \
tex-XCharter1-BoldSlanted-osf-ly1.tfm \
tex-XCharter1-BoldSlanted-osf-ly1.vf \
tex-XCharter1-BoldSlanted-osf-ot1.tfm \
tex-XCharter1-BoldSlanted-osf-ot1.vf \
tex-XCharter1-BoldSlanted-osf-sc-ly1--base.tfm \
tex-XCharter1-BoldSlanted-osf-sc-ly1.tfm \
tex-XCharter1-BoldSlanted-osf-sc-ly1.vf \
tex-XCharter1-BoldSlanted-osf-sc-ot1--base.tfm \
tex-XCharter1-BoldSlanted-osf-sc-ot1.tfm \
tex-XCharter1-BoldSlanted-osf-sc-ot1.vf \
tex-XCharter1-BoldSlanted-osf-sc-t1--base.tfm \
tex-XCharter1-BoldSlanted-osf-sc-t1.tfm \
tex-XCharter1-BoldSlanted-osf-sc-t1.vf \
tex-XCharter1-BoldSlanted-osf-sc-t2a--base.tfm \
tex-XCharter1-BoldSlanted-osf-sc-t2a.tfm \
tex-XCharter1-BoldSlanted-osf-sc-t2a.vf \
tex-XCharter1-BoldSlanted-osf-sc-t2asrb--base.tfm \
tex-XCharter1-BoldSlanted-osf-sc-t2asrb.tfm \
tex-XCharter1-BoldSlanted-osf-sc-t2asrb.vf \
tex-XCharter1-BoldSlanted-osf-t1--base.tfm \
tex-XCharter1-BoldSlanted-osf-t1.tfm \
tex-XCharter1-BoldSlanted-osf-t1.vf \
tex-XCharter1-BoldSlanted-osf-t2a.tfm \
tex-XCharter1-BoldSlanted-osf-t2a.vf \
tex-XCharter1-BoldSlanted-osf-t2asrb.tfm \
tex-XCharter1-BoldSlanted-osf-t2asrb.vf \
tex-XCharter1-BoldSlanted-tosf-ly1--base.tfm \
tex-XCharter1-BoldSlanted-tosf-ly1.tfm \
tex-XCharter1-BoldSlanted-tosf-ly1.vf \
tex-XCharter1-BoldSlanted-tosf-ot1.tfm \
tex-XCharter1-BoldSlanted-tosf-ot1.vf \
tex-XCharter1-BoldSlanted-tosf-sc-ly1--base.tfm \
tex-XCharter1-BoldSlanted-tosf-sc-ly1.tfm \
tex-XCharter1-BoldSlanted-tosf-sc-ly1.vf \
tex-XCharter1-BoldSlanted-tosf-sc-ot1--base.tfm \
tex-XCharter1-BoldSlanted-tosf-sc-ot1.tfm \
tex-XCharter1-BoldSlanted-tosf-sc-ot1.vf \
tex-XCharter1-BoldSlanted-tosf-sc-t1--base.tfm \
tex-XCharter1-BoldSlanted-tosf-sc-t1.tfm \
tex-XCharter1-BoldSlanted-tosf-sc-t1.vf \
tex-XCharter1-BoldSlanted-tosf-sc-t2a--base.tfm \
tex-XCharter1-BoldSlanted-tosf-sc-t2a.tfm \
tex-XCharter1-BoldSlanted-tosf-sc-t2a.vf \
tex-XCharter1-BoldSlanted-tosf-sc-t2asrb--base.tfm \
tex-XCharter1-BoldSlanted-tosf-sc-t2asrb.tfm \
tex-XCharter1-BoldSlanted-tosf-sc-t2asrb.vf \
tex-XCharter1-BoldSlanted-tosf-t1--base.tfm \
tex-XCharter1-BoldSlanted-tosf-t1.tfm \
tex-XCharter1-BoldSlanted-tosf-t1.vf \
tex-XCharter1-BoldSlanted-tosf-t2a.tfm \
tex-XCharter1-BoldSlanted-tosf-t2a.vf \
tex-XCharter1-BoldSlanted-tosf-t2asrb.tfm \
tex-XCharter1-BoldSlanted-tosf-t2asrb.vf \
tex-XCharter1-BoldSlanted-ts1--base.tfm \
tex-XCharter1-BoldSlanted-ts1.tfm \
tex-XCharter1-BoldSlanted-ts1.vf \
tex-XCharter1-Italic-osf-ly1--base.tfm \
tex-XCharter1-Italic-osf-ly1.tfm \
tex-XCharter1-Italic-osf-ly1.vf \
tex-XCharter1-Italic-osf-ot1.tfm \
tex-XCharter1-Italic-osf-ot1.vf \
tex-XCharter1-Italic-osf-sc-ly1--base.tfm \
tex-XCharter1-Italic-osf-sc-ly1.tfm \
tex-XCharter1-Italic-osf-sc-ly1.vf \
tex-XCharter1-Italic-osf-sc-ot1--base.tfm \
tex-XCharter1-Italic-osf-sc-ot1.tfm \
tex-XCharter1-Italic-osf-sc-ot1.vf \
tex-XCharter1-Italic-osf-sc-t1--base.tfm \
tex-XCharter1-Italic-osf-sc-t1.tfm \
tex-XCharter1-Italic-osf-sc-t1.vf \
tex-XCharter1-Italic-osf-sc-t2a--base.tfm \
tex-XCharter1-Italic-osf-sc-t2a.tfm \
tex-XCharter1-Italic-osf-sc-t2a.vf \
tex-XCharter1-Italic-osf-sc-t2asrb--base.tfm \
tex-XCharter1-Italic-osf-sc-t2asrb.tfm \
tex-XCharter1-Italic-osf-sc-t2asrb.vf \
tex-XCharter1-Italic-osf-t1--base.tfm \
tex-XCharter1-Italic-osf-t1.tfm \
tex-XCharter1-Italic-osf-t1.vf \
tex-XCharter1-Italic-osf-t2a.tfm \
tex-XCharter1-Italic-osf-t2a.vf \
tex-XCharter1-Italic-osf-t2asrb.tfm \
tex-XCharter1-Italic-osf-t2asrb.vf \
tex-XCharter1-Italic-tosf-ly1--base.tfm \
tex-XCharter1-Italic-tosf-ly1.tfm \
tex-XCharter1-Italic-tosf-ly1.vf \
tex-XCharter1-Italic-tosf-ot1.tfm \
tex-XCharter1-Italic-tosf-ot1.vf \
tex-XCharter1-Italic-tosf-sc-ly1--base.tfm \
tex-XCharter1-Italic-tosf-sc-ly1.tfm \
tex-XCharter1-Italic-tosf-sc-ly1.vf \
tex-XCharter1-Italic-tosf-sc-ot1--base.tfm \
tex-XCharter1-Italic-tosf-sc-ot1.tfm \
tex-XCharter1-Italic-tosf-sc-ot1.vf \
tex-XCharter1-Italic-tosf-sc-t1--base.tfm \
tex-XCharter1-Italic-tosf-sc-t1.tfm \
tex-XCharter1-Italic-tosf-sc-t1.vf \
tex-XCharter1-Italic-tosf-sc-t2a--base.tfm \
tex-XCharter1-Italic-tosf-sc-t2a.tfm \
tex-XCharter1-Italic-tosf-sc-t2a.vf \
tex-XCharter1-Italic-tosf-sc-t2asrb--base.tfm \
tex-XCharter1-Italic-tosf-sc-t2asrb.tfm \
tex-XCharter1-Italic-tosf-sc-t2asrb.vf \
tex-XCharter1-Italic-tosf-t1--base.tfm \
tex-XCharter1-Italic-tosf-t1.tfm \
tex-XCharter1-Italic-tosf-t1.vf \
tex-XCharter1-Italic-tosf-t2a.tfm \
tex-XCharter1-Italic-tosf-t2a.vf \
tex-XCharter1-Italic-tosf-t2asrb.tfm \
tex-XCharter1-Italic-tosf-t2asrb.vf \
tex-XCharter1-Italic-ts1--base.tfm \
tex-XCharter1-Italic-ts1.tfm \
tex-XCharter1-Italic-ts1.vf \
tex-XCharter1-Roman-osf-ly1--base.tfm \
tex-XCharter1-Roman-osf-ly1.tfm \
tex-XCharter1-Roman-osf-ly1.vf \
tex-XCharter1-Roman-osf-ot1.tfm \
tex-XCharter1-Roman-osf-ot1.vf \
tex-XCharter1-Roman-osf-sc-ly1--base.tfm \
tex-XCharter1-Roman-osf-sc-ly1.tfm \
tex-XCharter1-Roman-osf-sc-ly1.vf \
tex-XCharter1-Roman-osf-sc-ot1--base.tfm \
tex-XCharter1-Roman-osf-sc-ot1.tfm \
tex-XCharter1-Roman-osf-sc-ot1.vf \
tex-XCharter1-Roman-osf-sc-t1--base.tfm \
tex-XCharter1-Roman-osf-sc-t1.tfm \
tex-XCharter1-Roman-osf-sc-t1.vf \
tex-XCharter1-Roman-osf-sc-t2a--base.tfm \
tex-XCharter1-Roman-osf-sc-t2a.tfm \
tex-XCharter1-Roman-osf-sc-t2a.vf \
tex-XCharter1-Roman-osf-sc-t2asrb--base.tfm \
tex-XCharter1-Roman-osf-sc-t2asrb.tfm \
tex-XCharter1-Roman-osf-sc-t2asrb.vf \
tex-XCharter1-Roman-osf-t1--base.tfm \
tex-XCharter1-Roman-osf-t1.tfm \
tex-XCharter1-Roman-osf-t1.vf \
tex-XCharter1-Roman-osf-t2a.tfm \
tex-XCharter1-Roman-osf-t2a.vf \
tex-XCharter1-Roman-osf-t2asrb.tfm \
tex-XCharter1-Roman-osf-t2asrb.vf \
tex-XCharter1-Roman-tosf-ly1--base.tfm \
tex-XCharter1-Roman-tosf-ly1.tfm \
tex-XCharter1-Roman-tosf-ly1.vf \
tex-XCharter1-Roman-tosf-ot1.tfm \
tex-XCharter1-Roman-tosf-ot1.vf \
tex-XCharter1-Roman-tosf-sc-ly1--base.tfm \
tex-XCharter1-Roman-tosf-sc-ly1.tfm \
tex-XCharter1-Roman-tosf-sc-ly1.vf \
tex-XCharter1-Roman-tosf-sc-ot1--base.tfm \
tex-XCharter1-Roman-tosf-sc-ot1.tfm \
tex-XCharter1-Roman-tosf-sc-ot1.vf \
tex-XCharter1-Roman-tosf-sc-t1--base.tfm \
tex-XCharter1-Roman-tosf-sc-t1.tfm \
tex-XCharter1-Roman-tosf-sc-t1.vf \
tex-XCharter1-Roman-tosf-sc-t2a--base.tfm \
tex-XCharter1-Roman-tosf-sc-t2a.tfm \
tex-XCharter1-Roman-tosf-sc-t2a.vf \
tex-XCharter1-Roman-tosf-sc-t2asrb--base.tfm \
tex-XCharter1-Roman-tosf-sc-t2asrb.tfm \
tex-XCharter1-Roman-tosf-sc-t2asrb.vf \
tex-XCharter1-Roman-tosf-t1--base.tfm \
tex-XCharter1-Roman-tosf-t1.tfm \
tex-XCharter1-Roman-tosf-t1.vf \
tex-XCharter1-Roman-tosf-t2a.tfm \
tex-XCharter1-Roman-tosf-t2a.vf \
tex-XCharter1-Roman-tosf-t2asrb.tfm \
tex-XCharter1-Roman-tosf-t2asrb.vf \
tex-XCharter1-Roman-ts1--base.tfm \
tex-XCharter1-Roman-ts1.tfm \
tex-XCharter1-Roman-ts1.vf \
tex-XCharter1-Slanted-osf-ly1--base.tfm \
tex-XCharter1-Slanted-osf-ly1.tfm \
tex-XCharter1-Slanted-osf-ly1.vf \
tex-XCharter1-Slanted-osf-ot1.tfm \
tex-XCharter1-Slanted-osf-ot1.vf \
tex-XCharter1-Slanted-osf-sc-ly1--base.tfm \
tex-XCharter1-Slanted-osf-sc-ly1.tfm \
tex-XCharter1-Slanted-osf-sc-ly1.vf \
tex-XCharter1-Slanted-osf-sc-ot1--base.tfm \
tex-XCharter1-Slanted-osf-sc-ot1.tfm \
tex-XCharter1-Slanted-osf-sc-ot1.vf \
tex-XCharter1-Slanted-osf-sc-t1--base.tfm \
tex-XCharter1-Slanted-osf-sc-t1.tfm \
tex-XCharter1-Slanted-osf-sc-t1.vf \
tex-XCharter1-Slanted-osf-sc-t2a--base.tfm \
tex-XCharter1-Slanted-osf-sc-t2a.tfm \
tex-XCharter1-Slanted-osf-sc-t2a.vf \
tex-XCharter1-Slanted-osf-sc-t2asrb--base.tfm \
tex-XCharter1-Slanted-osf-sc-t2asrb.tfm \
tex-XCharter1-Slanted-osf-sc-t2asrb.vf \
tex-XCharter1-Slanted-osf-t1--base.tfm \
tex-XCharter1-Slanted-osf-t1.tfm \
tex-XCharter1-Slanted-osf-t1.vf \
tex-XCharter1-Slanted-osf-t2a.tfm \
tex-XCharter1-Slanted-osf-t2a.vf \
tex-XCharter1-Slanted-osf-t2asrb.tfm \
tex-XCharter1-Slanted-osf-t2asrb.vf \
tex-XCharter1-Slanted-tosf-ly1--base.tfm \
tex-XCharter1-Slanted-tosf-ly1.tfm \
tex-XCharter1-Slanted-tosf-ly1.vf \
tex-XCharter1-Slanted-tosf-ot1.tfm \
tex-XCharter1-Slanted-tosf-ot1.vf \
tex-XCharter1-Slanted-tosf-sc-ly1--base.tfm \
tex-XCharter1-Slanted-tosf-sc-ly1.tfm \
tex-XCharter1-Slanted-tosf-sc-ly1.vf \
tex-XCharter1-Slanted-tosf-sc-ot1--base.tfm \
tex-XCharter1-Slanted-tosf-sc-ot1.tfm \
tex-XCharter1-Slanted-tosf-sc-ot1.vf \
tex-XCharter1-Slanted-tosf-sc-t1--base.tfm \
tex-XCharter1-Slanted-tosf-sc-t1.tfm \
tex-XCharter1-Slanted-tosf-sc-t1.vf \
tex-XCharter1-Slanted-tosf-sc-t2a--base.tfm \
tex-XCharter1-Slanted-tosf-sc-t2a.tfm \
tex-XCharter1-Slanted-tosf-sc-t2a.vf \
tex-XCharter1-Slanted-tosf-sc-t2asrb--base.tfm \
tex-XCharter1-Slanted-tosf-sc-t2asrb.tfm \
tex-XCharter1-Slanted-tosf-sc-t2asrb.vf \
tex-XCharter1-Slanted-tosf-t1--base.tfm \
tex-XCharter1-Slanted-tosf-t1.tfm \
tex-XCharter1-Slanted-tosf-t1.vf \
tex-XCharter1-Slanted-tosf-t2a.tfm \
tex-XCharter1-Slanted-tosf-t2a.vf \
tex-XCharter1-Slanted-tosf-t2asrb.tfm \
tex-XCharter1-Slanted-tosf-t2asrb.vf \
tex-XCharter1-Slanted-ts1--base.tfm \
tex-XCharter1-Slanted-ts1.tfm \
tex-XCharter1-Slanted-ts1.vf \
tex-XCharter1TH-BoldItalic-osf-ly1.tfm \
tex-XCharter1TH-BoldItalic-osf-ot1.tfm \
tex-XCharter1TH-BoldItalic-osf-t1.tfm \
tex-XCharter1TH-Italic-osf-ly1.tfm \
tex-XCharter1TH-Italic-osf-ot1.tfm \
tex-XCharter1TH-Italic-osf-t1.tfm \
tex-XCharterMathBMI.tfm \
tex-XCharterMathBRM.tfm \
tex-XCharterMathMI.tfm \
tex-XCharterMathRM.tfm \
tex-XCharterTH-BoldItalic-osf-ly1.tfm \
tex-XCharterTH-BoldItalic-osf-ot1.tfm \
tex-XCharterTH-BoldItalic-osf-t1.tfm \
tex-XCharterTH-BoldItalic-tlf-ly1.tfm \
tex-XCharterTH-BoldItalic-tlf-ot1.tfm \
tex-XCharterTH-BoldItalic-tlf-t1.tfm \
tex-XCharterTH-Italic-osf-ly1.tfm \
tex-XCharterTH-Italic-osf-ot1.tfm \
tex-XCharterTH-Italic-osf-t1.tfm \
tex-XCharterTH-Italic-tlf-ly1.tfm \
tex-XCharterTH-Italic-tlf-ot1.tfm \
tex-XCharterTH-Italic-tlf-t1.tfm \
tex-chalph.enc \
tex-chtabosf.enc \
tex-ly1minxcharter.fd \
tex-newtx-xcharter-subs.tex \
tex-omlzchmi.fd \
tex-ot1minxcharter.fd \
tex-t1minxcharter.fd \
tex-t2asrbcmr.fd \
tex-t2asrbenc.def \
tex-xch-26pbhy.enc \
tex-xch-2itbay.enc \
tex-xch-2jcsfa.enc \
tex-xch-2ne5ra.enc \
tex-xch-34ooqo.enc \
tex-xch-3gllts.enc \
tex-xch-45bsgy.enc \
tex-xch-4difzd.enc \
tex-xch-4j4sw5.enc \
tex-xch-4nycuc.enc \
tex-xch-4sqimf.enc \
tex-xch-4zysyq.enc \
tex-xch-56742i.enc \
tex-xch-5b6tid.enc \
tex-xch-5d4nzt.enc \
tex-xch-5xvt3q.enc \
tex-xch-626iem.enc \
tex-xch-62bu45.enc \
tex-xch-62z5ot.enc \
tex-xch-6335sg.enc \
tex-xch-6hbxgl.enc \
tex-xch-6hzluo.enc \
tex-xch-6mgzuz.enc \
tex-xch-6w7aji.enc \
tex-xch-6xwfqv.enc \
tex-xch-7af5b5.enc \
tex-xch-7aohvb.enc \
tex-xch-7cmdv6.enc \
tex-xch-7qcosn.enc \
tex-xch-7rlj4v.enc \
tex-xch-a6eos7.enc \
tex-xch-aegaiu.enc \
tex-xch-ajf4qe.enc \
tex-xch-aoa5sq.enc \
tex-xch-aw3wom.enc \
tex-xch-bb5vvo.enc \
tex-xch-bbkh3c.enc \
tex-xch-bbupxq.enc \
tex-xch-bigbmo.enc \
tex-xch-bjnaxa.enc \
tex-xch-ccfumi.enc \
tex-xch-ccijuc.enc \
tex-xch-co4ru4.enc \
tex-xch-cos7tu.enc \
tex-xch-crvcmi.enc \
tex-xch-cy5fc2.enc \
tex-xch-dhwwz5.enc \
tex-xch-dp2hrq.enc \
tex-xch-dterbk.enc \
tex-xch-du7ees.enc \
tex-xch-dynzsr.enc \
tex-xch-e3svsw.enc \
tex-xch-en7yt2.enc \
tex-xch-eqlboo.enc \
tex-xch-ev5sn4.enc \
tex-xch-fiqldz.enc \
tex-xch-fz6tql.enc \
tex-xch-g2zr6i.enc \
tex-xch-gcjbtk.enc \
tex-xch-genhdo.enc \
tex-xch-gkuln7.enc \
tex-xch-gpeupc.enc \
tex-xch-gq3xaj.enc \
tex-xch-hgvfee.enc \
tex-xch-hiviyg.enc \
tex-xch-hnm6t3.enc \
tex-xch-i2cund.enc \
tex-xch-ijhcpw.enc \
tex-xch-jeuyxn.enc \
tex-xch-jffewf.enc \
tex-xch-kbmyqk.enc \
tex-xch-ksktz7.enc \
tex-xch-lfc2es.enc \
tex-xch-lhsfh5.enc \
tex-xch-mlyjgq.enc \
tex-xch-mpbiom.enc \
tex-xch-ng7me5.enc \
tex-xch-ngyxqh.enc \
tex-xch-nh3bfv.enc \
tex-xch-nhow2o.enc \
tex-xch-nmcnhp.enc \
tex-xch-npknak.enc \
tex-xch-o2mz2z.enc \
tex-xch-ocih55.enc \
tex-xch-ocj6e4.enc \
tex-xch-ocop3w.enc \
tex-xch-ph46id.enc \
tex-xch-pqp4df.enc \
tex-xch-q7fabp.enc \
tex-xch-qdw4m6.enc \
tex-xch-qfxvo4.enc \
tex-xch-qibaxb.enc \
tex-xch-qp5ku5.enc \
tex-xch-qqwc2g.enc \
tex-xch-qs7dmb.enc \
tex-xch-qxwrge.enc \
tex-xch-ri2bby.enc \
tex-xch-rt3iiq.enc \
tex-xch-ru4hos.enc \
tex-xch-rydp4l.enc \
tex-xch-s4eoyd.enc \
tex-xch-s4nkqe.enc \
tex-xch-saki7p.enc \
tex-xch-sczepj.enc \
tex-xch-t5vgvk.enc \
tex-xch-tcksd3.enc \
tex-xch-tdvtoa.enc \
tex-xch-tipddl.enc \
tex-xch-u5ytlb.enc \
tex-xch-uaipw4.enc \
tex-xch-ukw3hq.enc \
tex-xch-ur4n5e.enc \
tex-xch-v3qzik.enc \
tex-xch-v6llfb.enc \
tex-xch-vyhv3k.enc \
tex-xch-wbcur7.enc \
tex-xch-wd2dbe.enc \
tex-xch-wkfmwg.enc \
tex-xch-worivi.enc \
tex-xch-wqjgnt.enc \
tex-xch-wuciy4.enc \
tex-xch-x36pxl.enc \
tex-xch-x6jczy.enc \
tex-xch-xqcxen.enc \
tex-xch-y3xd77.enc \
tex-xch-yelf2i.enc \
tex-xch-ylqppr.enc \
tex-xch-yr3lcc.enc \
tex-xch-z3wvjz.enc \
tex-xch-zr4od3.enc \
tex-xch1-2itbay.enc \
tex-xch1-2jcsfa.enc \
tex-xch1-45bsgy.enc \
tex-xch1-4sqimf.enc \
tex-xch1-4zysyq.enc \
tex-xch1-56742i.enc \
tex-xch1-5b6tid.enc \
tex-xch1-5xvt3q.enc \
tex-xch1-626iem.enc \
tex-xch1-6xwfqv.enc \
tex-xch1-7aohvb.enc \
tex-xch1-aegaiu.enc \
tex-xch1-ccfumi.enc \
tex-xch1-co4ru4.enc \
tex-xch1-crvcmi.enc \
tex-xch1-dp2hrq.enc \
tex-xch1-dterbk.enc \
tex-xch1-dynzsr.enc \
tex-xch1-e3svsw.enc \
tex-xch1-g2zr6i.enc \
tex-xch1-genhdo.enc \
tex-xch1-gpeupc.enc \
tex-xch1-hgvfee.enc \
tex-xch1-i2cund.enc \
tex-xch1-jeuyxn.enc \
tex-xch1-kbmyqk.enc \
tex-xch1-ksktz7.enc \
tex-xch1-lhsfh5.enc \
tex-xch1-mpbiom.enc \
tex-xch1-ng7me5.enc \
tex-xch1-nh3bfv.enc \
tex-xch1-nhow2o.enc \
tex-xch1-nmcnhp.enc \
tex-xch1-ocj6e4.enc \
tex-xch1-ph46id.enc \
tex-xch1-pqp4df.enc \
tex-xch1-q7fabp.enc \
tex-xch1-qqwc2g.enc \
tex-xch1-ri2bby.enc \
tex-xch1-s4eoyd.enc \
tex-xch1-s4nkqe.enc \
tex-xch1-saki7p.enc \
tex-xch1-sczepj.enc \
tex-xch1-tdvtoa.enc \
tex-xch1-tipddl.enc \
tex-xch1-v3qzik.enc \
tex-xch1-wd2dbe.enc \
tex-xch1-wkfmwg.enc \
tex-xch1-wqjgnt.enc \
tex-xch1-wuciy4.enc \
tex-xch1-x6jczy.enc \
tex-xch1-xqcxen.enc \
tex-xch1-ylqppr.enc \
tex-xch1-yr3lcc.enc \
tex-xch1-z3wvjz.enc \
tex-xch1TH-osf-ly1.enc \
tex-xch1TH-osf-ot1.enc \
tex-xch1TH-osf-t1.enc \
tex-xchTH-osf-ly1.enc \
tex-xchTH-osf-ot1.enc \
tex-xchTH-osf-t1.enc \
tex-xchTH-tlf-ly1.enc \
tex-xchTH-tlf-ot1.enc \
tex-xchTH-tlf-t1.enc \
tex-xcharter-ot2.enc \
tex-zchbmi.tfm \
tex-zchbmi.vf \
tex-zchbmi0.tfm \
tex-zchbmi0.vf \
tex-zchbmi2.tfm \
tex-zchbmi2.vf \
tex-zchbmi3.tfm \
tex-zchbmi3.vf \
tex-zchbmia.tfm \
tex-zchbmia.vf \
tex-zchmi.tfm \
tex-zchmi.vf \
tex-zchmi0.tfm \
tex-zchmi0.vf \
tex-zchmi2.tfm \
tex-zchmi2.vf \
tex-zchmi3.tfm \
tex-zchmi3.vf \
tex-zchmia-fromvf.tfm \
tex-zchmia-fromvf.vf \
tex-zchmia.tfm \
tex-zchmia.vf \
texlive-xcharter"

RDEPENDS:${PN} += "/usr/bin/sh \
coreutils \
ed \
findutils \
grep \
sed \
tex-etoolbox.sty \
tex-fontaxes.sty \
tex-fontenc.sty \
tex-fontspec.sty \
tex-iftex.sty \
tex-ifthen.sty \
tex-mweights.sty \
tex-realscripts.sty \
tex-rtxbmi-ut.tfm \
tex-scalefnt.sty \
tex-stxscr.tfm \
tex-textcomp.sty \
tex-txbmiaSTbb.tfm \
tex-txbmiaX.tfm \
tex-txmiaSTbb.tfm \
tex-txmiaX.tfm \
tex-updmap.cfg \
tex-xcharter-otf.sty \
tex-xkeyval.sty \
tex-xstring.sty \
texlive \
texlive-filesystem \
texlive-kpathsea \
texlive-kpathsea-bin \
texlive-scripts \
texlive-scripts-bin \
texlive-xcharter-fonts"

inherit rpm
