SUMMARY = "Severed fonts for texlive-lxgw-fonts"
DESCRIPTION = "The  separated fonts package for texlive-lxgw-fonts"
LICENSE = "OFL-1.1"

PV = "2026.226.1.521nsvn77682"

RPM_NAME = "texlive-lxgw-fonts-fonts-2026.226.1.521nsvn77682-59.2.noarch.rpm"
RPM_HASH = "6914570f227b407b22ef7636f567938fe566560ebf4164e227cce8b381eda927c79f9dd234384f857e80ce84a2f83969ff1b123313985d02108ba2abe16084dc"
REPO_ARCH = "noarch"

RPROVIDES:${PN} += "font--lang=aa \
font--lang=af \
font--lang=agr \
font--lang=ak \
font--lang=an \
font--lang=ast \
font--lang=av \
font--lang=ay \
font--lang=ayc \
font--lang=az-az \
font--lang=ba \
font--lang=be \
font--lang=bem \
font--lang=ber-dz \
font--lang=bg \
font--lang=bi \
font--lang=bin \
font--lang=bm \
font--lang=br \
font--lang=bs \
font--lang=bua \
font--lang=ca \
font--lang=ce \
font--lang=ch \
font--lang=chm \
font--lang=cmn \
font--lang=co \
font--lang=crh \
font--lang=cs \
font--lang=csb \
font--lang=cv \
font--lang=cy \
font--lang=da \
font--lang=de \
font--lang=dsb \
font--lang=ee \
font--lang=el \
font--lang=en \
font--lang=eo \
font--lang=es \
font--lang=et \
font--lang=eu \
font--lang=fat \
font--lang=ff \
font--lang=fi \
font--lang=fil \
font--lang=fj \
font--lang=fo \
font--lang=fr \
font--lang=fur \
font--lang=fy \
font--lang=ga \
font--lang=gd \
font--lang=gl \
font--lang=gn \
font--lang=gv \
font--lang=ha \
font--lang=hak \
font--lang=haw \
font--lang=ho \
font--lang=hr \
font--lang=hsb \
font--lang=ht \
font--lang=hu \
font--lang=hz \
font--lang=ia \
font--lang=id \
font--lang=ie \
font--lang=ig \
font--lang=ik \
font--lang=io \
font--lang=is \
font--lang=it \
font--lang=ja \
font--lang=jv \
font--lang=kaa \
font--lang=kab \
font--lang=ki \
font--lang=kj \
font--lang=kk \
font--lang=kl \
font--lang=kr \
font--lang=ku-am \
font--lang=ku-tr \
font--lang=kum \
font--lang=kv \
font--lang=kw \
font--lang=kwm \
font--lang=ky \
font--lang=la \
font--lang=lb \
font--lang=lez \
font--lang=lg \
font--lang=li \
font--lang=lij \
font--lang=ln \
font--lang=lt \
font--lang=lv \
font--lang=lzh \
font--lang=mfe \
font--lang=mg \
font--lang=mh \
font--lang=mhr \
font--lang=mi \
font--lang=miq \
font--lang=mjw \
font--lang=mk \
font--lang=mn-mn \
font--lang=mo \
font--lang=ms \
font--lang=mt \
font--lang=na \
font--lang=nan \
font--lang=nb \
font--lang=nds \
font--lang=ng \
font--lang=nhn \
font--lang=niu \
font--lang=nl \
font--lang=nn \
font--lang=no \
font--lang=nr \
font--lang=nso \
font--lang=nv \
font--lang=ny \
font--lang=oc \
font--lang=om \
font--lang=os \
font--lang=pap-an \
font--lang=pap-aw \
font--lang=pl \
font--lang=pt \
font--lang=qu \
font--lang=quz \
font--lang=rif \
font--lang=rm \
font--lang=rn \
font--lang=ro \
font--lang=ru \
font--lang=rw \
font--lang=sah \
font--lang=sc \
font--lang=sco \
font--lang=se \
font--lang=sel \
font--lang=sg \
font--lang=sgs \
font--lang=sh \
font--lang=sk \
font--lang=sl \
font--lang=sm \
font--lang=sma \
font--lang=smj \
font--lang=smn \
font--lang=sms \
font--lang=sn \
font--lang=so \
font--lang=sq \
font--lang=sr \
font--lang=ss \
font--lang=st \
font--lang=su \
font--lang=sv \
font--lang=sw \
font--lang=szl \
font--lang=tg \
font--lang=tk \
font--lang=tl \
font--lang=tn \
font--lang=to \
font--lang=tpi \
font--lang=tr \
font--lang=ts \
font--lang=tt \
font--lang=tw \
font--lang=ty \
font--lang=tyv \
font--lang=uk \
font--lang=unm \
font--lang=uz \
font--lang=ve \
font--lang=vi \
font--lang=vo \
font--lang=vot \
font--lang=wa \
font--lang=wae \
font--lang=wen \
font--lang=wo \
font--lang=xh \
font--lang=yap \
font--lang=yo \
font--lang=yuw \
font--lang=za \
font--lang=zh-cn \
font--lang=zh-sg \
font--lang=zh-tw \
font--lang=zu \
font-lxgwneoxihei \
font-lxgwneoxiheiscreen \
font-lxgwneozhisong \
font-lxgwneozhisongscreen \
font-lxgwwenkaigblite \
font-lxgwzhenkaigb \
font-zhuquefangsong(technicalpreview) \
font-朱雀仿宋（预览测试版） \
font-霞鹜文楷gb轻便版 \
font-霞鹜新晰黑 \
font-霞鹜新晰黑屏幕阅读版 \
font-霞鹜新致宋 \
font-霞鹜新致宋屏幕阅读版 \
font-霞鹜臻楷gb \
texlive-lxgw-fonts-fonts"

RDEPENDS:${PN} += "/usr/bin/sh \
aaa-base \
coreutils \
fontconfig \
ghostscript-fonts-std \
perl"

inherit rpm
