SUMMARY = "Support for the ancient \\emline macro"
DESCRIPTION = "Occasional Documents appear, that use graphics generated by \
texcad from the emtex distribution. These documents often use \
the \\emline macro, which produced lines at an arbitrary \
orientation. The present package emulates the macro, using \
TikZ."
LICENSE = "SUSE-Public-Domain"

PV = "2026.226.1.0svn23440"

RPM_NAME = "texlive-tsemlines-2026.226.1.0svn23440-59.2.noarch.rpm"
RPM_HASH = "b01c2205618bbfd8a050ab5bef01310369b26686f61b07dbd8df8c554647b90c69ab876df6a156dc8e519a15c61e901e7c0e7740938b3302c56046a4c06c4689"
REPO_ARCH = "noarch"

RPROVIDES:${PN} += "tex-tsemlines.sty \
texlive-tsemlines"

RDEPENDS:${PN} += "/usr/bin/sh \
coreutils \
ed \
findutils \
grep \
sed \
texlive \
texlive-filesystem \
texlive-kpathsea \
texlive-kpathsea-bin \
texlive-scripts \
texlive-scripts-bin"

inherit rpm
