SUMMARY = "Fish completion for bugwarden"
DESCRIPTION = "The fish completion script for bugwarden, generated by upstream from the \
command line definition."
LICENSE = "(Apache-2.0 | BSL-1.0) & (Apache-2.0 | ISC | MIT) & (Apache-2.0 | MIT) & (MIT | Unlicense) & Apache-2.0 & BSD-3-Clause & ISC & MIT & Unicode-3.0"

PV = "0.6.0"

RPM_NAME = "bugwarden-fish-completion-0.6.0-1.1.noarch.rpm"
RPM_HASH = "1ffc6d2d1f0221efa84861a23096264cba1bad1fdbcbc3d6c37c8e69fe690a39f8a2f7422b778419dae6b05d4f6f01967dca4bb1defd31fcb95a0f5e5879fe9b"
REPO_ARCH = "noarch"

RPROVIDES:${PN} += "bugwarden-fish-completion"

RDEPENDS:${PN} += "bugwarden"

inherit rpm
