SUMMARY = "Development files for ocaml-sedlex"
DESCRIPTION = "The ocaml-sedlex-devel package contains libraries and signature files for \
developing applications that use ocaml-sedlex."
LICENSE = "MIT"

PV = "3.7"

RPM_NAME = "ocaml-sedlex-devel-3.7-1.3.aarch64.rpm"
RPM_HASH = "97d52c07d0f14c15e0f1fe033fbabb4161ea3e56d6fba467edbd47219002dfdb74f09c21508c496208168fcafe3fe56b4f62274a3cf2e4221b865b719f7403b5"

RPROVIDES:${PN} += "ocaml-Sedlex-ppx \
ocaml-Sedlex-ppx--Iso \
ocaml-Sedlex-ppx--Ppx-sedlex \
ocaml-Sedlex-ppx--Sedlex \
ocaml-Sedlex-ppx--Sedlex-cset \
ocaml-Sedlex-ppx--Unicode \
ocaml-Sedlex-ppx--Utf8 \
ocaml-Sedlex-ppx--Xml \
ocaml-Sedlex-utils \
ocaml-Sedlex-utils--Cset \
ocaml-Sedlexing \
ocaml-sedlex-devel \
ocamlfind-sedlex \
ocamlfind-sedlex.ppx \
ocamlfind-sedlex.utils \
ocamlx-Sedlex-ppx \
ocamlx-Sedlex-ppx--Iso \
ocamlx-Sedlex-ppx--Ppx-sedlex \
ocamlx-Sedlex-ppx--Sedlex \
ocamlx-Sedlex-ppx--Sedlex-cset \
ocamlx-Sedlex-ppx--Unicode \
ocamlx-Sedlex-ppx--Utf8 \
ocamlx-Sedlex-ppx--Xml \
ocamlx-Sedlex-utils \
ocamlx-Sedlex-utils--Cset \
ocamlx-Sedlexing"

RDEPENDS:${PN} += "libc.so.6 \
libm.so.6 \
libzstd.so.1 \
ocaml-Astlib \
ocaml-Astlib-- \
ocaml-Astlib--Ast-408 \
ocaml-Astlib--Ast-409 \
ocaml-Astlib--Ast-410 \
ocaml-Astlib--Ast-411 \
ocaml-Astlib--Ast-412 \
ocaml-Astlib--Ast-413 \
ocaml-Astlib--Ast-414 \
ocaml-Astlib--Ast-500 \
ocaml-Astlib--Ast-501 \
ocaml-Astlib--Ast-502 \
ocaml-Astlib--Ast-503 \
ocaml-Astlib--Ast-504 \
ocaml-Astlib--Ast-505 \
ocaml-Astlib--Location \
ocaml-Astlib--Longident \
ocaml-Astlib--Longident-504 \
ocaml-Astlib--Parse \
ocaml-Asttypes \
ocaml-Build-path-prefix-map \
ocaml-CamlinternalFormatBasics \
ocaml-CamlinternalLazy \
ocaml-CamlinternalOO \
ocaml-Clflags \
ocaml-Cmi-format \
ocaml-Compmisc \
ocaml-Config \
ocaml-Data-types \
ocaml-Env \
ocaml-Format-doc \
ocaml-Gen \
ocaml-Gen-intf \
ocaml-Ident \
ocaml-Identifiable \
ocaml-Load-path \
ocaml-Location \
ocaml-Longident \
ocaml-Misc \
ocaml-Ocaml-common \
ocaml-Ocaml-shadow \
ocaml-Outcometree \
ocaml-Parsetree \
ocaml-Path \
ocaml-Pprintast \
ocaml-Ppxlib \
ocaml-Ppxlib-- \
ocaml-Ppxlib--Ast-builder \
ocaml-Ppxlib--Ast-builder-generated \
ocaml-Ppxlib--Ast-builder-intf \
ocaml-Ppxlib--Ast-pattern \
ocaml-Ppxlib--Ast-pattern-generated \
ocaml-Ppxlib--Ast-pattern0 \
ocaml-Ppxlib--Ast-traverse \
ocaml-Ppxlib--Ast-traverse0 \
ocaml-Ppxlib--Attribute \
ocaml-Ppxlib--Code-path \
ocaml-Ppxlib--Common \
ocaml-Ppxlib--Context-free \
ocaml-Ppxlib--Driver \
ocaml-Ppxlib--Expansion-context \
ocaml-Ppxlib--Extension \
ocaml-Ppxlib--Import \
ocaml-Ppxlib--Loc \
ocaml-Ppxlib--Location \
ocaml-Ppxlib--Longident \
ocaml-Ppxlib--Name \
ocaml-Ppxlib--Utils \
ocaml-Ppxlib-ast \
ocaml-Ppxlib-ast-- \
ocaml-Ppxlib-ast--Ast \
ocaml-Ppxlib-ast--Ast-helper-lite \
ocaml-Ppxlib-ast--Import \
ocaml-Ppxlib-ast--Versions \
ocaml-Ppxlib-traverse-builtins \
ocaml-Primitive \
ocaml-Sexplib0 \
ocaml-Sexplib0-- \
ocaml-Sexplib0--Sexp \
ocaml-Sexplib0--Sexp-conv \
ocaml-Sexplib0--Sexp-conv-grammar \
ocaml-Sexplib0--Sexp-grammar \
ocaml-Sexplib0--Sexpable \
ocaml-Shape \
ocaml-Stdlib \
ocaml-Stdlib--Arg \
ocaml-Stdlib--Array \
ocaml-Stdlib--Buffer \
ocaml-Stdlib--Bytes \
ocaml-Stdlib--BytesLabels \
ocaml-Stdlib--Char \
ocaml-Stdlib--Digest \
ocaml-Stdlib--Domain \
ocaml-Stdlib--Either \
ocaml-Stdlib--Format \
ocaml-Stdlib--Hashtbl \
ocaml-Stdlib--Int32 \
ocaml-Stdlib--Lazy \
ocaml-Stdlib--Lexing \
ocaml-Stdlib--List \
ocaml-Stdlib--ListLabels \
ocaml-Stdlib--Map \
ocaml-Stdlib--Obj \
ocaml-Stdlib--Option \
ocaml-Stdlib--Printf \
ocaml-Stdlib--Result \
ocaml-Stdlib--Seq \
ocaml-Stdlib--Set \
ocaml-Stdlib--StdLabels \
ocaml-Stdlib--String \
ocaml-Stdlib--StringLabels \
ocaml-Stdlib--Sys \
ocaml-Stdlib--Uchar \
ocaml-Stdppx \
ocaml-Subst \
ocaml-Type-immediacy \
ocaml-Types \
ocaml-Unit-info \
ocaml-Warnings \
ocaml-sedlex \
ocamlfind-gen \
ocamlfind-ppxlib \
ocamlfind-ppxlib.ast \
ocamlfind-sedlex \
ocamlfind-sedlex.utils \
ocamlx-CamlinternalOO \
ocamlx-Gen \
ocamlx-Ppxlib--Ast-builder \
ocamlx-Ppxlib--Ast-pattern \
ocamlx-Ppxlib--Ast-traverse \
ocamlx-Ppxlib--Driver \
ocamlx-Ppxlib--Extension \
ocamlx-Ppxlib--Location \
ocamlx-Ppxlib-ast--Ast-helper-lite \
ocamlx-Stdlib \
ocamlx-Stdlib--Array \
ocamlx-Stdlib--Buffer \
ocamlx-Stdlib--Bytes \
ocamlx-Stdlib--Char \
ocamlx-Stdlib--Hashtbl \
ocamlx-Stdlib--List \
ocamlx-Stdlib--Map \
ocamlx-Stdlib--Option \
ocamlx-Stdlib--Printf \
ocamlx-Stdlib--String \
ocamlx-Stdlib--Uchar"

inherit rpm
