SUMMARY = "Plugin nu_plugin_polars for nushell"
DESCRIPTION = "Plugin nu_plugin_polars for nushell."
LICENSE = "MIT"

PV = "0.115.1"

RPM_NAME = "nushell-plugin_polars-0.115.1-1.2.aarch64.rpm"
RPM_HASH = "c9311fc3fd5855754eadb819e58ced6795ab41d77f7886029c1779ed7fadbf4e9a9613446ead11612aad86dff5b2ba7402219db0a7c5fec24c700abefd7765e4"

RPROVIDES:${PN} += "bundled-rust-crate-addr2line \
bundled-rust-crate-adler2 \
bundled-rust-crate-adler32 \
bundled-rust-crate-ahash \
bundled-rust-crate-aho-corasick \
bundled-rust-crate-alloc-no-stdlib \
bundled-rust-crate-alloc-stdlib \
bundled-rust-crate-allocator-api2 \
bundled-rust-crate-anstream \
bundled-rust-crate-anstyle \
bundled-rust-crate-anstyle-parse \
bundled-rust-crate-anstyle-query \
bundled-rust-crate-anyhow \
bundled-rust-crate-ar-archive-writer \
bundled-rust-crate-arc-swap \
bundled-rust-crate-argminmax \
bundled-rust-crate-array-init-cursor \
bundled-rust-crate-arrayvec \
bundled-rust-crate-async-channel \
bundled-rust-crate-async-stream \
bundled-rust-crate-async-stream-impl \
bundled-rust-crate-async-trait \
bundled-rust-crate-atoi-simd \
bundled-rust-crate-atomic \
bundled-rust-crate-atomic-waker \
bundled-rust-crate-autocfg \
bundled-rust-crate-avro-schema \
bundled-rust-crate-aws-config \
bundled-rust-crate-aws-credential-types \
bundled-rust-crate-aws-lc-rs \
bundled-rust-crate-aws-lc-sys \
bundled-rust-crate-aws-runtime \
bundled-rust-crate-aws-sdk-sso \
bundled-rust-crate-aws-sdk-ssooidc \
bundled-rust-crate-aws-sdk-sts \
bundled-rust-crate-aws-sigv4 \
bundled-rust-crate-aws-smithy-async \
bundled-rust-crate-aws-smithy-http \
bundled-rust-crate-aws-smithy-http-client \
bundled-rust-crate-aws-smithy-json \
bundled-rust-crate-aws-smithy-observability \
bundled-rust-crate-aws-smithy-query \
bundled-rust-crate-aws-smithy-runtime \
bundled-rust-crate-aws-smithy-runtime-api \
bundled-rust-crate-aws-smithy-runtime-api-macros \
bundled-rust-crate-aws-smithy-schema \
bundled-rust-crate-aws-smithy-types \
bundled-rust-crate-aws-smithy-xml \
bundled-rust-crate-aws-types \
bundled-rust-crate-backtrace \
bundled-rust-crate-backtrace-ext \
bundled-rust-crate-base64 \
bundled-rust-crate-base64-simd \
bundled-rust-crate-bigdecimal \
bundled-rust-crate-bincode \
bundled-rust-crate-bincode-derive \
bundled-rust-crate-bit-set \
bundled-rust-crate-bit-vec \
bundled-rust-crate-bitflags \
bundled-rust-crate-blake3 \
bundled-rust-crate-block-buffer \
bundled-rust-crate-boxcar \
bundled-rust-crate-brotli \
bundled-rust-crate-brotli-decompressor \
bundled-rust-crate-bstr \
bundled-rust-crate-buf-trait \
bundled-rust-crate-bytemuck \
bundled-rust-crate-bytemuck-derive \
bundled-rust-crate-byteorder \
bundled-rust-crate-bytes \
bundled-rust-crate-bytes-utils \
bundled-rust-crate-byteyarn \
bundled-rust-crate-castaway \
bundled-rust-crate-cc \
bundled-rust-crate-cfg-aliases \
bundled-rust-crate-cfg-if \
bundled-rust-crate-chacha20 \
bundled-rust-crate-chrono \
bundled-rust-crate-chrono-humanize \
bundled-rust-crate-chrono-tz \
bundled-rust-crate-clap \
bundled-rust-crate-clap-builder \
bundled-rust-crate-clap-derive \
bundled-rust-crate-clap-lex \
bundled-rust-crate-cmake \
bundled-rust-crate-cmov \
bundled-rust-crate-colorchoice \
bundled-rust-crate-comfy-table \
bundled-rust-crate-compact-str \
bundled-rust-crate-concurrent-queue \
bundled-rust-crate-const-oid \
bundled-rust-crate-constant-time-eq \
bundled-rust-crate-convert-case \
bundled-rust-crate-cpufeatures \
bundled-rust-crate-crc \
bundled-rust-crate-crc-catalog \
bundled-rust-crate-crc32fast \
bundled-rust-crate-crossbeam-channel \
bundled-rust-crate-crossbeam-deque \
bundled-rust-crate-crossbeam-epoch \
bundled-rust-crate-crossbeam-queue \
bundled-rust-crate-crossbeam-utils \
bundled-rust-crate-crossterm \
bundled-rust-crate-crypto-common \
bundled-rust-crate-ctutils \
bundled-rust-crate-darling \
bundled-rust-crate-darling-core \
bundled-rust-crate-darling-macro \
bundled-rust-crate-debug-unsafe \
bundled-rust-crate-defmt \
bundled-rust-crate-defmt-macros \
bundled-rust-crate-defmt-parser \
bundled-rust-crate-deranged \
bundled-rust-crate-derive-more \
bundled-rust-crate-derive-more-impl \
bundled-rust-crate-derive-setters \
bundled-rust-crate-digest \
bundled-rust-crate-dirs \
bundled-rust-crate-dirs-sys \
bundled-rust-crate-displaydoc \
bundled-rust-crate-doctest-file \
bundled-rust-crate-document-features \
bundled-rust-crate-dunce \
bundled-rust-crate-dyn-clone \
bundled-rust-crate-either \
bundled-rust-crate-env-filter \
bundled-rust-crate-env-logger \
bundled-rust-crate-equivalent \
bundled-rust-crate-erased-serde \
bundled-rust-crate-errno \
bundled-rust-crate-ethnum \
bundled-rust-crate-event-listener \
bundled-rust-crate-event-listener-strategy \
bundled-rust-crate-fallible-streaming-iterator \
bundled-rust-crate-fancy-regex \
bundled-rust-crate-fast-float2 \
bundled-rust-crate-fastrand \
bundled-rust-crate-filedescriptor \
bundled-rust-crate-find-msvc-tools \
bundled-rust-crate-flate2 \
bundled-rust-crate-float-cmp \
bundled-rust-crate-fluent \
bundled-rust-crate-fluent-bundle \
bundled-rust-crate-fluent-langneg \
bundled-rust-crate-fluent-syntax \
bundled-rust-crate-fnv \
bundled-rust-crate-foldhash \
bundled-rust-crate-form-urlencoded \
bundled-rust-crate-fs-extra \
bundled-rust-crate-fs4 \
bundled-rust-crate-futures \
bundled-rust-crate-futures-channel \
bundled-rust-crate-futures-core \
bundled-rust-crate-futures-executor \
bundled-rust-crate-futures-io \
bundled-rust-crate-futures-macro \
bundled-rust-crate-futures-sink \
bundled-rust-crate-futures-task \
bundled-rust-crate-futures-util \
bundled-rust-crate-generic-array \
bundled-rust-crate-getrandom \
bundled-rust-crate-gimli \
bundled-rust-crate-glob \
bundled-rust-crate-h2 \
bundled-rust-crate-half \
bundled-rust-crate-halfbrown \
bundled-rust-crate-hashbrown \
bundled-rust-crate-heck \
bundled-rust-crate-hex \
bundled-rust-crate-hmac \
bundled-rust-crate-home \
bundled-rust-crate-http \
bundled-rust-crate-http-body \
bundled-rust-crate-http-body-util \
bundled-rust-crate-httparse \
bundled-rust-crate-httpdate \
bundled-rust-crate-humantime \
bundled-rust-crate-hybrid-array \
bundled-rust-crate-hyper \
bundled-rust-crate-hyper-rustls \
bundled-rust-crate-hyper-util \
bundled-rust-crate-iana-time-zone \
bundled-rust-crate-icu-collections \
bundled-rust-crate-icu-locale-core \
bundled-rust-crate-icu-normalizer \
bundled-rust-crate-icu-normalizer-data \
bundled-rust-crate-icu-properties \
bundled-rust-crate-icu-properties-data \
bundled-rust-crate-icu-provider \
bundled-rust-crate-ident-case \
bundled-rust-crate-idna \
bundled-rust-crate-idna-adapter \
bundled-rust-crate-indexmap \
bundled-rust-crate-interprocess \
bundled-rust-crate-intl-memoizer \
bundled-rust-crate-intl-pluralrules \
bundled-rust-crate-inventory \
bundled-rust-crate-ipnet \
bundled-rust-crate-is-ci \
bundled-rust-crate-is-terminal-polyfill \
bundled-rust-crate-itertools \
bundled-rust-crate-itoa \
bundled-rust-crate-jiff \
bundled-rust-crate-jiff-core \
bundled-rust-crate-jiff-static \
bundled-rust-crate-jobserver \
bundled-rust-crate-jsonpath-lib-polars-vendor \
bundled-rust-crate-lean-string \
bundled-rust-crate-libc \
bundled-rust-crate-libflate \
bundled-rust-crate-libflate-lz77 \
bundled-rust-crate-libm \
bundled-rust-crate-linux-raw-sys \
bundled-rust-crate-litemap \
bundled-rust-crate-litrs \
bundled-rust-crate-lock-api \
bundled-rust-crate-log \
bundled-rust-crate-lru \
bundled-rust-crate-lru-slab \
bundled-rust-crate-lscolors \
bundled-rust-crate-lz4 \
bundled-rust-crate-lz4-sys \
bundled-rust-crate-md-5 \
bundled-rust-crate-memchr \
bundled-rust-crate-memmap2 \
bundled-rust-crate-miette \
bundled-rust-crate-miette-derive \
bundled-rust-crate-miniz-oxide \
bundled-rust-crate-mio \
bundled-rust-crate-nix \
bundled-rust-crate-now \
bundled-rust-crate-nu-ansi-term \
bundled-rust-crate-nu-config \
bundled-rust-crate-nu-derive-value \
bundled-rust-crate-nu-engine \
bundled-rust-crate-nu-experimental \
bundled-rust-crate-nu-glob \
bundled-rust-crate-nu-path \
bundled-rust-crate-nu-plugin \
bundled-rust-crate-nu-plugin-core \
bundled-rust-crate-nu-plugin-polars \
bundled-rust-crate-nu-plugin-protocol \
bundled-rust-crate-nu-protocol \
bundled-rust-crate-nu-system \
bundled-rust-crate-nu-utils \
bundled-rust-crate-num \
bundled-rust-crate-num-bigint \
bundled-rust-crate-num-complex \
bundled-rust-crate-num-conv \
bundled-rust-crate-num-derive \
bundled-rust-crate-num-format \
bundled-rust-crate-num-integer \
bundled-rust-crate-num-iter \
bundled-rust-crate-num-rational \
bundled-rust-crate-num-threads \
bundled-rust-crate-num-traits \
bundled-rust-crate-object \
bundled-rust-crate-object-store \
bundled-rust-crate-once-cell \
bundled-rust-crate-openssl-probe \
bundled-rust-crate-option-ext \
bundled-rust-crate-os-display \
bundled-rust-crate-os-pipe \
bundled-rust-crate-outref \
bundled-rust-crate-owo-colors \
bundled-rust-crate-parking \
bundled-rust-crate-parking-lot \
bundled-rust-crate-parking-lot-core \
bundled-rust-crate-percent-encoding \
bundled-rust-crate-phf \
bundled-rust-crate-phf-shared \
bundled-rust-crate-pin-project-lite \
bundled-rust-crate-pin-utils \
bundled-rust-crate-pkg-config \
bundled-rust-crate-planus \
bundled-rust-crate-polars \
bundled-rust-crate-polars-arrow \
bundled-rust-crate-polars-arrow-format \
bundled-rust-crate-polars-async \
bundled-rust-crate-polars-buffer \
bundled-rust-crate-polars-compute \
bundled-rust-crate-polars-config \
bundled-rust-crate-polars-core \
bundled-rust-crate-polars-dtype \
bundled-rust-crate-polars-error \
bundled-rust-crate-polars-expr \
bundled-rust-crate-polars-io \
bundled-rust-crate-polars-json \
bundled-rust-crate-polars-lazy \
bundled-rust-crate-polars-mem-engine \
bundled-rust-crate-polars-ooc \
bundled-rust-crate-polars-ops \
bundled-rust-crate-polars-parquet \
bundled-rust-crate-polars-parquet-format \
bundled-rust-crate-polars-plan \
bundled-rust-crate-polars-row \
bundled-rust-crate-polars-schema \
bundled-rust-crate-polars-sql \
bundled-rust-crate-polars-stream \
bundled-rust-crate-polars-time \
bundled-rust-crate-polars-utils \
bundled-rust-crate-potential-utf \
bundled-rust-crate-powerfmt \
bundled-rust-crate-ppv-lite86 \
bundled-rust-crate-proc-macro-error-attr2 \
bundled-rust-crate-proc-macro-error2 \
bundled-rust-crate-proc-macro2 \
bundled-rust-crate-procfs \
bundled-rust-crate-procfs-core \
bundled-rust-crate-psm \
bundled-rust-crate-pure-rust-locales \
bundled-rust-crate-pwd \
bundled-rust-crate-quick-xml \
bundled-rust-crate-quinn \
bundled-rust-crate-quinn-proto \
bundled-rust-crate-quinn-udp \
bundled-rust-crate-quote \
bundled-rust-crate-rand \
bundled-rust-crate-rand-chacha \
bundled-rust-crate-rand-core \
bundled-rust-crate-rand-distr \
bundled-rust-crate-rand-pcg \
bundled-rust-crate-raw-cpuid \
bundled-rust-crate-rayon \
bundled-rust-crate-rayon-core \
bundled-rust-crate-recursive \
bundled-rust-crate-recursive-proc-macro-impl \
bundled-rust-crate-ref-cast \
bundled-rust-crate-ref-cast-impl \
bundled-rust-crate-regex \
bundled-rust-crate-regex-automata \
bundled-rust-crate-regex-lite \
bundled-rust-crate-regex-syntax \
bundled-rust-crate-reqwest \
bundled-rust-crate-ring \
bundled-rust-crate-rle-decode-fast \
bundled-rust-crate-rmp \
bundled-rust-crate-rmp-serde \
bundled-rust-crate-rustc-demangle \
bundled-rust-crate-rustc-hash \
bundled-rust-crate-rustc-version \
bundled-rust-crate-rustix \
bundled-rust-crate-rustls \
bundled-rust-crate-rustls-native-certs \
bundled-rust-crate-rustls-pki-types \
bundled-rust-crate-rustls-webpki \
bundled-rust-crate-rustversion \
bundled-rust-crate-ryu \
bundled-rust-crate-same-file \
bundled-rust-crate-scopeguard \
bundled-rust-crate-self-cell \
bundled-rust-crate-semver \
bundled-rust-crate-serde \
bundled-rust-crate-serde-core \
bundled-rust-crate-serde-derive \
bundled-rust-crate-serde-json \
bundled-rust-crate-serde-stacker \
bundled-rust-crate-serde-urlencoded \
bundled-rust-crate-sha1 \
bundled-rust-crate-sha1-smol \
bundled-rust-crate-sha2 \
bundled-rust-crate-shlex \
bundled-rust-crate-signal-hook \
bundled-rust-crate-signal-hook-mio \
bundled-rust-crate-signal-hook-registry \
bundled-rust-crate-simd-adler32 \
bundled-rust-crate-simd-json \
bundled-rust-crate-simdutf8 \
bundled-rust-crate-siphasher \
bundled-rust-crate-slab \
bundled-rust-crate-slotmap \
bundled-rust-crate-smallvec \
bundled-rust-crate-snap \
bundled-rust-crate-socket2 \
bundled-rust-crate-sqlparser \
bundled-rust-crate-sqlparser-derive \
bundled-rust-crate-stable-deref-trait \
bundled-rust-crate-stacker \
bundled-rust-crate-static-assertions \
bundled-rust-crate-streaming-decompression \
bundled-rust-crate-streaming-iterator \
bundled-rust-crate-strength-reduce \
bundled-rust-crate-strip-ansi-escapes \
bundled-rust-crate-strsim \
bundled-rust-crate-strum \
bundled-rust-crate-strum-macros \
bundled-rust-crate-subtle \
bundled-rust-crate-supports-color \
bundled-rust-crate-supports-hyperlinks \
bundled-rust-crate-supports-unicode \
bundled-rust-crate-syn \
bundled-rust-crate-sync-wrapper \
bundled-rust-crate-synstructure \
bundled-rust-crate-sys-locale \
bundled-rust-crate-sysinfo \
bundled-rust-crate-terminal-size \
bundled-rust-crate-textwrap \
bundled-rust-crate-thiserror \
bundled-rust-crate-thiserror-impl \
bundled-rust-crate-thread-local \
bundled-rust-crate-time \
bundled-rust-crate-time-core \
bundled-rust-crate-time-macros \
bundled-rust-crate-tinystr \
bundled-rust-crate-tinyvec \
bundled-rust-crate-tinyvec-macros \
bundled-rust-crate-tokio \
bundled-rust-crate-tokio-macros \
bundled-rust-crate-tokio-rustls \
bundled-rust-crate-tokio-util \
bundled-rust-crate-tower \
bundled-rust-crate-tower-http \
bundled-rust-crate-tower-layer \
bundled-rust-crate-tower-service \
bundled-rust-crate-tracing \
bundled-rust-crate-tracing-attributes \
bundled-rust-crate-tracing-core \
bundled-rust-crate-try-lock \
bundled-rust-crate-type-map \
bundled-rust-crate-typeid \
bundled-rust-crate-typenum \
bundled-rust-crate-typetag \
bundled-rust-crate-typetag-impl \
bundled-rust-crate-unic-langid \
bundled-rust-crate-unic-langid-impl \
bundled-rust-crate-unicase \
bundled-rust-crate-unicode-ident \
bundled-rust-crate-unicode-linebreak \
bundled-rust-crate-unicode-normalization \
bundled-rust-crate-unicode-reverse \
bundled-rust-crate-unicode-segmentation \
bundled-rust-crate-unicode-width \
bundled-rust-crate-unicode-xid \
bundled-rust-crate-untrusted \
bundled-rust-crate-unty \
bundled-rust-crate-url \
bundled-rust-crate-urlencoding \
bundled-rust-crate-utf8-iter \
bundled-rust-crate-utf8parse \
bundled-rust-crate-uucore \
bundled-rust-crate-uucore-procs \
bundled-rust-crate-uuid \
bundled-rust-crate-value-trait \
bundled-rust-crate-version-check \
bundled-rust-crate-virtue \
bundled-rust-crate-vsimd \
bundled-rust-crate-vte \
bundled-rust-crate-walkdir \
bundled-rust-crate-want \
bundled-rust-crate-web-time \
bundled-rust-crate-webpki-roots \
bundled-rust-crate-winnow \
bundled-rust-crate-writeable \
bundled-rust-crate-xattr \
bundled-rust-crate-xmlparser \
bundled-rust-crate-xxhash-rust \
bundled-rust-crate-yoke \
bundled-rust-crate-yoke-derive \
bundled-rust-crate-zerocopy \
bundled-rust-crate-zerocopy-derive \
bundled-rust-crate-zerofrom \
bundled-rust-crate-zerofrom-derive \
bundled-rust-crate-zeroize \
bundled-rust-crate-zerotrie \
bundled-rust-crate-zerovec \
bundled-rust-crate-zerovec-derive \
bundled-rust-crate-zlib-rs \
bundled-rust-crate-zmij \
bundled-rust-crate-zstd \
bundled-rust-crate-zstd-safe \
bundled-rust-crate-zstd-sys \
nushell-plugin-polars"

RDEPENDS:${PN} += "libc.so.6 \
libgcc-s.so.1 \
libm.so.6 \
nushell"

inherit rpm
