SUMMARY = "Microsoft Azure CLI 2.0"
DESCRIPTION = "Microsoft Azure CLI 2.0 Command Line Utilities"
LICENSE = "MIT"

PV = "2.90.0"

RPM_NAME = "azure-cli-2.90.0-1.1.noarch.rpm"
RPM_HASH = "5ef29992909ed5381b60afd6f6a9d3e2a31b4f2fb1bf9400529d6274757a83c2abafb3ba73eb886ba1647147c0434eef3e2b935e82c87c517f8726d6ace07153"
REPO_ARCH = "noarch"

RPROVIDES:${PN} += "azure-cli \
azure-cli-acr \
azure-cli-acs \
azure-cli-advisor \
azure-cli-ams \
azure-cli-appservice \
azure-cli-backup \
azure-cli-batch \
azure-cli-batchai \
azure-cli-billing \
azure-cli-botservice \
azure-cli-cdn \
azure-cli-cloud \
azure-cli-cognitiveservices \
azure-cli-component \
azure-cli-configure \
azure-cli-consumption \
azure-cli-container \
azure-cli-cosmosdb \
azure-cli-deploymentmanager \
azure-cli-dla \
azure-cli-dls \
azure-cli-dms \
azure-cli-eventgrid \
azure-cli-eventhubs \
azure-cli-extension \
azure-cli-feedback \
azure-cli-find \
azure-cli-hdinsight \
azure-cli-interactive \
azure-cli-iot \
azure-cli-iotcentral \
azure-cli-keyvault \
azure-cli-kusto \
azure-cli-lab \
azure-cli-maps \
azure-cli-monitor \
azure-cli-natgateway \
azure-cli-network \
azure-cli-policyinsights \
azure-cli-privatedns \
azure-cli-profile \
azure-cli-rdbms \
azure-cli-redis \
azure-cli-relay \
azure-cli-reservations \
azure-cli-resource \
azure-cli-role \
azure-cli-search \
azure-cli-security \
azure-cli-servicebus \
azure-cli-servicefabric \
azure-cli-signalr \
azure-cli-sql \
azure-cli-sqlvm \
azure-cli-storage \
azure-cli-vm \
python3.13dist-azure-cli \
python3dist-azure-cli"

RDEPENDS:${PN} += "/usr/bin/python3.13 \
azure-cli-core \
python-abi \
python313-Fabric \
python313-PyGithub \
python313-PyNaCl \
python313-PyYAML \
python313-antlr4-python3-runtime \
python313-azure-ai-projects \
python313-azure-appconfiguration \
python313-azure-batch \
python313-azure-cosmos \
python313-azure-data-tables \
python313-azure-datalake-store \
python313-azure-keyvault-administration \
python313-azure-keyvault-certificates \
python313-azure-keyvault-keys \
python313-azure-keyvault-secrets \
python313-azure-keyvault-securitydomain \
python313-azure-mgmt-advisor \
python313-azure-mgmt-apimanagement \
python313-azure-mgmt-appconfiguration \
python313-azure-mgmt-appcontainers \
python313-azure-mgmt-applicationinsights \
python313-azure-mgmt-authorization \
python313-azure-mgmt-batch \
python313-azure-mgmt-batchai \
python313-azure-mgmt-billing \
python313-azure-mgmt-botservice \
python313-azure-mgmt-cdn \
python313-azure-mgmt-cognitiveservices \
python313-azure-mgmt-compute \
python313-azure-mgmt-containerinstance \
python313-azure-mgmt-containerregistry \
python313-azure-mgmt-containerregistrytasks \
python313-azure-mgmt-containerservice \
python313-azure-mgmt-cosmosdb \
python313-azure-mgmt-datalake-store \
python313-azure-mgmt-datamigration \
python313-azure-mgmt-devtestlabs \
python313-azure-mgmt-domainregistration \
python313-azure-mgmt-eventgrid \
python313-azure-mgmt-eventhub \
python313-azure-mgmt-extendedlocation \
python313-azure-mgmt-hdinsight \
python313-azure-mgmt-imagebuilder \
python313-azure-mgmt-iotcentral \
python313-azure-mgmt-iothub \
python313-azure-mgmt-iothubprovisioningservices \
python313-azure-mgmt-keyvault \
python313-azure-mgmt-loganalytics \
python313-azure-mgmt-managementgroups \
python313-azure-mgmt-maps \
python313-azure-mgmt-marketplaceordering \
python313-azure-mgmt-media \
python313-azure-mgmt-monitor \
python313-azure-mgmt-msi \
python313-azure-mgmt-mysqlflexibleservers \
python313-azure-mgmt-netapp \
python313-azure-mgmt-policyinsights \
python313-azure-mgmt-postgresqlflexibleservers \
python313-azure-mgmt-privatedns \
python313-azure-mgmt-rdbms \
python313-azure-mgmt-recoveryservices \
python313-azure-mgmt-recoveryservicesbackup \
python313-azure-mgmt-redhatopenshift \
python313-azure-mgmt-redis \
python313-azure-mgmt-reservations \
python313-azure-mgmt-resource \
python313-azure-mgmt-resource-deployments \
python313-azure-mgmt-resource-deploymentscripts \
python313-azure-mgmt-resource-deploymentstacks \
python313-azure-mgmt-resource-templatespecs \
python313-azure-mgmt-search \
python313-azure-mgmt-security \
python313-azure-mgmt-servicebus \
python313-azure-mgmt-servicefabric \
python313-azure-mgmt-servicefabricmanagedclusters \
python313-azure-mgmt-servicelinker \
python313-azure-mgmt-signalr \
python313-azure-mgmt-sql \
python313-azure-mgmt-sqlvirtualmachine \
python313-azure-mgmt-storage \
python313-azure-mgmt-synapse \
python313-azure-mgmt-trafficmanager \
python313-azure-mgmt-web \
python313-azure-monitor-query \
python313-azure-storage-blob \
python313-azure-storage-common \
python313-azure-storage-file-datalake \
python313-azure-storage-file-share \
python313-azure-storage-queue \
python313-azure-synapse-accesscontrol \
python313-azure-synapse-artifacts \
python313-azure-synapse-managedprivateendpoints \
python313-azure-synapse-spark \
python313-chardet \
python313-colorama \
python313-distro \
python313-javaproperties \
python313-jsondiff \
python313-packaging \
python313-paramiko \
python313-pycomposefile \
python313-pygments \
python313-scp \
python313-semver \
python313-six \
python313-sshtunnel \
python313-tabulate \
python313-urllib3 \
python313-websocket-client \
python313-xmltodict"

inherit rpm
