SUMMARY = "An extension to pgfplots' \\addplot macro"
DESCRIPTION = "This package is an extension to pgfplots. It extends the \
\\addplot macro by a facility which allows modification of data \
files while they are read. With luaaddplot it is no longer \
necessary to pre-process data files generated by measuring \
devices with external scripts. This package can be used with \
plain LuaTeX or LuaLaTeX."
LICENSE = "LPPL-1.0"

PV = "2026.226.1.0asvn72350"

RPM_NAME = "texlive-luaaddplot-2026.226.1.0asvn72350-59.2.noarch.rpm"
RPM_HASH = "13b0b905bc469330a7e5bd898a33373dcc102b52730a2cf26f76e2496e761e22ee34c5c0b5d2035d299b2827cd9d37fc6f702a88f53164d3d481cbe190f2a3c0"
REPO_ARCH = "noarch"

RPROVIDES:${PN} += "tex-luaaddplot.sty \
tex-luaaddplot.tex \
texlive-luaaddplot"

RDEPENDS:${PN} += "/usr/bin/sh \
coreutils \
ed \
findutils \
grep \
sed \
texlive \
texlive-filesystem \
texlive-kpathsea \
texlive-kpathsea-bin \
texlive-scripts \
texlive-scripts-bin"

inherit rpm
