SUMMARY = "Driver for Xbox One and Xbox Series X|S controllers"
DESCRIPTION = "Linux kernel driver for Xbox One and Xbox Series X|S accessories. \
it serves as a modern replacement for xpad, aiming to be \
compatible with Microsoft's Game Input Protocol (GIP)."
LICENSE = "GPL-2.0-or-later"

PV = "0.5.8_k7.2.4_1"

RPM_NAME = "xone-kmp-default-0.5.8_k7.2.4_1-1.19.aarch64.rpm"
RPM_HASH = "06d7fbbb42224a32a86cec91fd56019dbc599a1cd8bdf3c89dbe3c3788c05b28b7f793eb9554addb3ace996c64eae6ed3dbbbcea49a65cad31f464b0587db4b5"

RPROVIDES:${PN} += "kmod-xone-dongle.ko \
kmod-xone-gip-chatpad.ko \
kmod-xone-gip-gamepad.ko \
kmod-xone-gip-headset.ko \
kmod-xone-gip-madcatz-glam.ko \
kmod-xone-gip-madcatz-strat.ko \
kmod-xone-gip-pdp-jaguar.ko \
kmod-xone-gip.ko \
kmod-xone-wired.ko \
ksym-default---gip-register-driver \
ksym-default-gip-auth-process-pkt \
ksym-default-gip-auth-send-complete \
ksym-default-gip-auth-start-handshake \
ksym-default-gip-create-adapter \
ksym-default-gip-destroy-adapter \
ksym-default-gip-disable-audio \
ksym-default-gip-enable-audio \
ksym-default-gip-has-interface \
ksym-default-gip-init-audio-in \
ksym-default-gip-init-audio-out \
ksym-default-gip-init-battery \
ksym-default-gip-init-extra-data \
ksym-default-gip-init-input \
ksym-default-gip-init-led \
ksym-default-gip-power-off-adapter \
ksym-default-gip-process-buffer \
ksym-default-gip-report-battery \
ksym-default-gip-send-audio-samples \
ksym-default-gip-send-get-serial-number \
ksym-default-gip-send-rumble \
ksym-default-gip-set-audio-volume \
ksym-default-gip-set-led-mode \
ksym-default-gip-set-power-mode \
ksym-default-gip-suggest-audio-format \
ksym-default-gip-unregister-driver \
multiversion-kernel \
xone-kmp \
xone-kmp-default \
xone-kmp-default-k7.2.4-1"

RDEPENDS:${PN} += "/usr/bin/sh \
coreutils \
grep \
kernel-default \
ksym-default---alloc-skb \
ksym-default---devm-add-action \
ksym-default---dynamic-dev-dbg \
ksym-default---dynamic-pr-debug \
ksym-default---flush-workqueue \
ksym-default---fortify-panic \
ksym-default---init-swait-queue-head \
ksym-default---init-waitqueue-head \
ksym-default---kmalloc-cache-noprof \
ksym-default---kmalloc-noprof \
ksym-default---netdev-alloc-skb \
ksym-default---stack-chk-fail \
ksym-default---wake-up \
ksym-default--dev-err \
ksym-default--dev-info \
ksym-default--dev-warn \
ksym-default--raw-spin-lock-irqsave \
ksym-default--raw-spin-unlock-irqrestore \
ksym-default--snd-pcm-stream-lock-irqsave \
ksym-default-add-uevent-var \
ksym-default-alloc-workqueue-noprof \
ksym-default-alt-cb-patch-nops \
ksym-default-bus-register \
ksym-default-bus-unregister \
ksym-default-cancel-delayed-work \
ksym-default-cancel-delayed-work-sync \
ksym-default-cancel-work-sync \
ksym-default-consume-skb \
ksym-default-crypto-akcipher-sync-encrypt \
ksym-default-crypto-alloc-akcipher \
ksym-default-crypto-alloc-kpp \
ksym-default-crypto-alloc-shash \
ksym-default-crypto-destroy-tfm \
ksym-default-crypto-ecdh-encode-key \
ksym-default-crypto-ecdh-key-len \
ksym-default-crypto-req-done \
ksym-default-crypto-shash-digest \
ksym-default-crypto-shash-export \
ksym-default-crypto-shash-finup \
ksym-default-crypto-shash-import \
ksym-default-crypto-shash-init \
ksym-default-crypto-shash-setkey \
ksym-default-crypto-shash-tfm-digest \
ksym-default-delayed-work-timer-fn \
ksym-default-destroy-workqueue \
ksym-default-dev-kfree-skb-any-reason \
ksym-default-dev-set-name \
ksym-default-device-add-groups \
ksym-default-device-register \
ksym-default-device-remove-groups \
ksym-default-device-unregister \
ksym-default-device-wakeup-enable \
ksym-default-devm-input-allocate-device \
ksym-default-devm-kasprintf \
ksym-default-devm-kmalloc \
ksym-default-devm-led-classdev-register-ext \
ksym-default-devm-power-supply-register \
ksym-default-down \
ksym-default-down-interruptible \
ksym-default-down-trylock \
ksym-default-drain-workqueue \
ksym-default-driver-register \
ksym-default-driver-unregister \
ksym-default-dump-stack \
ksym-default-dynamic-might-resched \
ksym-default-finish-wait \
ksym-default-get-random-bytes \
ksym-default-hid-add-device \
ksym-default-hid-allocate-device \
ksym-default-hid-destroy-device \
ksym-default-hid-input-report \
ksym-default-hid-parse-report \
ksym-default-hrtimer-cancel \
ksym-default-hrtimer-cb-get-time \
ksym-default-hrtimer-forward \
ksym-default-hrtimer-setup \
ksym-default-hrtimer-start-range-ns \
ksym-default-ida-alloc-range \
ksym-default-ida-free \
ksym-default-ieee80211-get-hdrlen-from-skb \
ksym-default-init-wait-entry \
ksym-default-input-event \
ksym-default-input-ff-create-memless \
ksym-default-input-register-device \
ksym-default-input-set-abs-params \
ksym-default-input-set-capability \
ksym-default-jiffies \
ksym-default-kfree \
ksym-default-kfree-sensitive \
ksym-default-kmalloc-caches \
ksym-default-kstrtobool \
ksym-default-kstrtoint \
ksym-default-kstrtou8 \
ksym-default-memcpy \
ksym-default-memmove \
ksym-default-memset \
ksym-default-mod-delayed-work-on \
ksym-default-mod-timer \
ksym-default-module-layout \
ksym-default-msleep \
ksym-default-mutex-init-generic \
ksym-default-mutex-lock \
ksym-default-mutex-unlock \
ksym-default-param-array-ops \
ksym-default-param-ops-byte \
ksym-default-param-ops-ushort \
ksym-default-power-supply-changed \
ksym-default-power-supply-get-drvdata \
ksym-default-power-supply-powers \
ksym-default-prepare-to-wait-event \
ksym-default-print-hex-dump \
ksym-default-put-device \
ksym-default-queue-delayed-work-on \
ksym-default-queue-work-on \
ksym-default-random-kmalloc-seed \
ksym-default-release-firmware \
ksym-default-request-firmware \
ksym-default-schedule-timeout \
ksym-default-sg-init-one \
ksym-default-sized-strscpy \
ksym-default-sk-skb-reason-drop \
ksym-default-skb-pull \
ksym-default-skb-push \
ksym-default-skb-put \
ksym-default-skb-trim \
ksym-default-snd-card-free-on-error \
ksym-default-snd-card-register \
ksym-default-snd-devm-card-new \
ksym-default-snd-pcm-new \
ksym-default-snd-pcm-period-elapsed \
ksym-default-snd-pcm-set-managed-buffer-all \
ksym-default-snd-pcm-set-ops \
ksym-default-snd-pcm-stream-unlock-irqrestore \
ksym-default-snprintf \
ksym-default-sprintf \
ksym-default-strcmp \
ksym-default-strlen \
ksym-default-strnlen \
ksym-default-sysfs-emit \
ksym-default-system-percpu-wq \
ksym-default-system-state \
ksym-default-system-wq \
ksym-default-timer-delete-sync \
ksym-default-timer-init-key \
ksym-default-up \
ksym-default-usb-alloc-coherent \
ksym-default-usb-alloc-urb \
ksym-default-usb-altnum-to-altsetting \
ksym-default-usb-anchor-urb \
ksym-default-usb-bulk-msg \
ksym-default-usb-control-msg \
ksym-default-usb-deregister \
ksym-default-usb-driver-claim-interface \
ksym-default-usb-find-common-endpoints \
ksym-default-usb-free-coherent \
ksym-default-usb-free-urb \
ksym-default-usb-get-from-anchor \
ksym-default-usb-ifnum-to-if \
ksym-default-usb-kill-anchored-urbs \
ksym-default-usb-kill-urb \
ksym-default-usb-register-driver \
ksym-default-usb-reset-device \
ksym-default-usb-set-interface \
ksym-default-usb-submit-urb \
ksym-default-usb-unanchor-urb \
ksym-default-usleep-range-state \
ksym-default-wait-for-completion \
suse-kernel-rpm-scriptlets"

inherit rpm
