SUMMARY = "LaTeX support for the Gelasio family of fonts"
DESCRIPTION = "This package provides (pdf)LaTeX, XeLaTeX and LuaLaTeX support \
for the Gelasio family of fonts designed by Eben Sorkin to be \
metric-compatible with Georgia in its Regular and Bold weights. \
Medium and SemiBold weights have been added."
LICENSE = "OFL-1.1"

PV = "2026.226.svn77682"

RPM_NAME = "texlive-gelasio-2026.226.svn77682-60.2.noarch.rpm"
RPM_HASH = "16b086d5e65bba83597279386d06dfeb26ac09b9b5e04d9abed54621562082f5606677b9ff88af3baaf9f6bf194bf46cbba8e21b096bd6ecd5088c07fabf6ed1"
REPO_ARCH = "noarch"

RPROVIDES:${PN} += "tex-Gelasio-Bold-lf-ly1.tfm \
tex-Gelasio-Bold-lf-ot1.tfm \
tex-Gelasio-Bold-lf-t1--base.tfm \
tex-Gelasio-Bold-lf-t1.tfm \
tex-Gelasio-Bold-lf-t1.vf \
tex-Gelasio-Bold-lf-ts1--base.tfm \
tex-Gelasio-Bold-lf-ts1.tfm \
tex-Gelasio-Bold-lf-ts1.vf \
tex-Gelasio-Bold-osf-ly1.tfm \
tex-Gelasio-Bold-osf-ot1.tfm \
tex-Gelasio-Bold-osf-t1--base.tfm \
tex-Gelasio-Bold-osf-t1.tfm \
tex-Gelasio-Bold-osf-t1.vf \
tex-Gelasio-Bold-osf-ts1--base.tfm \
tex-Gelasio-Bold-osf-ts1.tfm \
tex-Gelasio-Bold-osf-ts1.vf \
tex-Gelasio-Bold-sup-ly1.tfm \
tex-Gelasio-Bold-sup-ot1.tfm \
tex-Gelasio-Bold-sup-t1--base.tfm \
tex-Gelasio-Bold-sup-t1.tfm \
tex-Gelasio-Bold-sup-t1.vf \
tex-Gelasio-Bold-tlf-ly1.tfm \
tex-Gelasio-Bold-tlf-ot1.tfm \
tex-Gelasio-Bold-tlf-t1--base.tfm \
tex-Gelasio-Bold-tlf-t1.tfm \
tex-Gelasio-Bold-tlf-t1.vf \
tex-Gelasio-Bold-tlf-ts1--base.tfm \
tex-Gelasio-Bold-tlf-ts1.tfm \
tex-Gelasio-Bold-tlf-ts1.vf \
tex-Gelasio-Bold-tosf-ly1.tfm \
tex-Gelasio-Bold-tosf-ot1.tfm \
tex-Gelasio-Bold-tosf-t1--base.tfm \
tex-Gelasio-Bold-tosf-t1.tfm \
tex-Gelasio-Bold-tosf-t1.vf \
tex-Gelasio-Bold-tosf-ts1--base.tfm \
tex-Gelasio-Bold-tosf-ts1.tfm \
tex-Gelasio-Bold-tosf-ts1.vf \
tex-Gelasio-BoldItalic-lf-ly1.tfm \
tex-Gelasio-BoldItalic-lf-ot1.tfm \
tex-Gelasio-BoldItalic-lf-t1--base.tfm \
tex-Gelasio-BoldItalic-lf-t1.tfm \
tex-Gelasio-BoldItalic-lf-t1.vf \
tex-Gelasio-BoldItalic-lf-ts1--base.tfm \
tex-Gelasio-BoldItalic-lf-ts1.tfm \
tex-Gelasio-BoldItalic-lf-ts1.vf \
tex-Gelasio-BoldItalic-osf-ly1.tfm \
tex-Gelasio-BoldItalic-osf-ot1.tfm \
tex-Gelasio-BoldItalic-osf-t1--base.tfm \
tex-Gelasio-BoldItalic-osf-t1.tfm \
tex-Gelasio-BoldItalic-osf-t1.vf \
tex-Gelasio-BoldItalic-osf-ts1--base.tfm \
tex-Gelasio-BoldItalic-osf-ts1.tfm \
tex-Gelasio-BoldItalic-osf-ts1.vf \
tex-Gelasio-BoldItalic-sup-ly1.tfm \
tex-Gelasio-BoldItalic-sup-ot1.tfm \
tex-Gelasio-BoldItalic-sup-t1--base.tfm \
tex-Gelasio-BoldItalic-sup-t1.tfm \
tex-Gelasio-BoldItalic-sup-t1.vf \
tex-Gelasio-BoldItalic-tlf-ly1.tfm \
tex-Gelasio-BoldItalic-tlf-ot1.tfm \
tex-Gelasio-BoldItalic-tlf-t1--base.tfm \
tex-Gelasio-BoldItalic-tlf-t1.tfm \
tex-Gelasio-BoldItalic-tlf-t1.vf \
tex-Gelasio-BoldItalic-tlf-ts1--base.tfm \
tex-Gelasio-BoldItalic-tlf-ts1.tfm \
tex-Gelasio-BoldItalic-tlf-ts1.vf \
tex-Gelasio-BoldItalic-tosf-ly1.tfm \
tex-Gelasio-BoldItalic-tosf-ot1.tfm \
tex-Gelasio-BoldItalic-tosf-t1--base.tfm \
tex-Gelasio-BoldItalic-tosf-t1.tfm \
tex-Gelasio-BoldItalic-tosf-t1.vf \
tex-Gelasio-BoldItalic-tosf-ts1--base.tfm \
tex-Gelasio-BoldItalic-tosf-ts1.tfm \
tex-Gelasio-BoldItalic-tosf-ts1.vf \
tex-Gelasio-Italic-lf-ly1.tfm \
tex-Gelasio-Italic-lf-ot1.tfm \
tex-Gelasio-Italic-lf-t1--base.tfm \
tex-Gelasio-Italic-lf-t1.tfm \
tex-Gelasio-Italic-lf-t1.vf \
tex-Gelasio-Italic-lf-ts1--base.tfm \
tex-Gelasio-Italic-lf-ts1.tfm \
tex-Gelasio-Italic-lf-ts1.vf \
tex-Gelasio-Italic-osf-ly1.tfm \
tex-Gelasio-Italic-osf-ot1.tfm \
tex-Gelasio-Italic-osf-t1--base.tfm \
tex-Gelasio-Italic-osf-t1.tfm \
tex-Gelasio-Italic-osf-t1.vf \
tex-Gelasio-Italic-osf-ts1--base.tfm \
tex-Gelasio-Italic-osf-ts1.tfm \
tex-Gelasio-Italic-osf-ts1.vf \
tex-Gelasio-Italic-sup-ly1.tfm \
tex-Gelasio-Italic-sup-ot1.tfm \
tex-Gelasio-Italic-sup-t1--base.tfm \
tex-Gelasio-Italic-sup-t1.tfm \
tex-Gelasio-Italic-sup-t1.vf \
tex-Gelasio-Italic-tlf-ly1.tfm \
tex-Gelasio-Italic-tlf-ot1.tfm \
tex-Gelasio-Italic-tlf-t1--base.tfm \
tex-Gelasio-Italic-tlf-t1.tfm \
tex-Gelasio-Italic-tlf-t1.vf \
tex-Gelasio-Italic-tlf-ts1--base.tfm \
tex-Gelasio-Italic-tlf-ts1.tfm \
tex-Gelasio-Italic-tlf-ts1.vf \
tex-Gelasio-Italic-tosf-ly1.tfm \
tex-Gelasio-Italic-tosf-ot1.tfm \
tex-Gelasio-Italic-tosf-t1--base.tfm \
tex-Gelasio-Italic-tosf-t1.tfm \
tex-Gelasio-Italic-tosf-t1.vf \
tex-Gelasio-Italic-tosf-ts1--base.tfm \
tex-Gelasio-Italic-tosf-ts1.tfm \
tex-Gelasio-Italic-tosf-ts1.vf \
tex-Gelasio-Medium-lf-ly1.tfm \
tex-Gelasio-Medium-lf-ot1.tfm \
tex-Gelasio-Medium-lf-t1--base.tfm \
tex-Gelasio-Medium-lf-t1.tfm \
tex-Gelasio-Medium-lf-t1.vf \
tex-Gelasio-Medium-lf-ts1--base.tfm \
tex-Gelasio-Medium-lf-ts1.tfm \
tex-Gelasio-Medium-lf-ts1.vf \
tex-Gelasio-Medium-osf-ly1.tfm \
tex-Gelasio-Medium-osf-ot1.tfm \
tex-Gelasio-Medium-osf-t1--base.tfm \
tex-Gelasio-Medium-osf-t1.tfm \
tex-Gelasio-Medium-osf-t1.vf \
tex-Gelasio-Medium-osf-ts1--base.tfm \
tex-Gelasio-Medium-osf-ts1.tfm \
tex-Gelasio-Medium-osf-ts1.vf \
tex-Gelasio-Medium-sup-ly1.tfm \
tex-Gelasio-Medium-sup-ot1.tfm \
tex-Gelasio-Medium-sup-t1--base.tfm \
tex-Gelasio-Medium-sup-t1.tfm \
tex-Gelasio-Medium-sup-t1.vf \
tex-Gelasio-Medium-tlf-ly1.tfm \
tex-Gelasio-Medium-tlf-ot1.tfm \
tex-Gelasio-Medium-tlf-t1--base.tfm \
tex-Gelasio-Medium-tlf-t1.tfm \
tex-Gelasio-Medium-tlf-t1.vf \
tex-Gelasio-Medium-tlf-ts1--base.tfm \
tex-Gelasio-Medium-tlf-ts1.tfm \
tex-Gelasio-Medium-tlf-ts1.vf \
tex-Gelasio-Medium-tosf-ly1.tfm \
tex-Gelasio-Medium-tosf-ot1.tfm \
tex-Gelasio-Medium-tosf-t1--base.tfm \
tex-Gelasio-Medium-tosf-t1.tfm \
tex-Gelasio-Medium-tosf-t1.vf \
tex-Gelasio-Medium-tosf-ts1--base.tfm \
tex-Gelasio-Medium-tosf-ts1.tfm \
tex-Gelasio-Medium-tosf-ts1.vf \
tex-Gelasio-MediumItalic-lf-ly1.tfm \
tex-Gelasio-MediumItalic-lf-ot1.tfm \
tex-Gelasio-MediumItalic-lf-t1--base.tfm \
tex-Gelasio-MediumItalic-lf-t1.tfm \
tex-Gelasio-MediumItalic-lf-t1.vf \
tex-Gelasio-MediumItalic-lf-ts1--base.tfm \
tex-Gelasio-MediumItalic-lf-ts1.tfm \
tex-Gelasio-MediumItalic-lf-ts1.vf \
tex-Gelasio-MediumItalic-osf-ly1.tfm \
tex-Gelasio-MediumItalic-osf-ot1.tfm \
tex-Gelasio-MediumItalic-osf-t1--base.tfm \
tex-Gelasio-MediumItalic-osf-t1.tfm \
tex-Gelasio-MediumItalic-osf-t1.vf \
tex-Gelasio-MediumItalic-osf-ts1--base.tfm \
tex-Gelasio-MediumItalic-osf-ts1.tfm \
tex-Gelasio-MediumItalic-osf-ts1.vf \
tex-Gelasio-MediumItalic-sup-ly1.tfm \
tex-Gelasio-MediumItalic-sup-ot1.tfm \
tex-Gelasio-MediumItalic-sup-t1--base.tfm \
tex-Gelasio-MediumItalic-sup-t1.tfm \
tex-Gelasio-MediumItalic-sup-t1.vf \
tex-Gelasio-MediumItalic-tlf-ly1.tfm \
tex-Gelasio-MediumItalic-tlf-ot1.tfm \
tex-Gelasio-MediumItalic-tlf-t1--base.tfm \
tex-Gelasio-MediumItalic-tlf-t1.tfm \
tex-Gelasio-MediumItalic-tlf-t1.vf \
tex-Gelasio-MediumItalic-tlf-ts1--base.tfm \
tex-Gelasio-MediumItalic-tlf-ts1.tfm \
tex-Gelasio-MediumItalic-tlf-ts1.vf \
tex-Gelasio-MediumItalic-tosf-ly1.tfm \
tex-Gelasio-MediumItalic-tosf-ot1.tfm \
tex-Gelasio-MediumItalic-tosf-t1--base.tfm \
tex-Gelasio-MediumItalic-tosf-t1.tfm \
tex-Gelasio-MediumItalic-tosf-t1.vf \
tex-Gelasio-MediumItalic-tosf-ts1--base.tfm \
tex-Gelasio-MediumItalic-tosf-ts1.tfm \
tex-Gelasio-MediumItalic-tosf-ts1.vf \
tex-Gelasio-Regular-lf-ly1.tfm \
tex-Gelasio-Regular-lf-ot1.tfm \
tex-Gelasio-Regular-lf-t1--base.tfm \
tex-Gelasio-Regular-lf-t1.tfm \
tex-Gelasio-Regular-lf-t1.vf \
tex-Gelasio-Regular-lf-ts1--base.tfm \
tex-Gelasio-Regular-lf-ts1.tfm \
tex-Gelasio-Regular-lf-ts1.vf \
tex-Gelasio-Regular-osf-ly1.tfm \
tex-Gelasio-Regular-osf-ot1.tfm \
tex-Gelasio-Regular-osf-t1--base.tfm \
tex-Gelasio-Regular-osf-t1.tfm \
tex-Gelasio-Regular-osf-t1.vf \
tex-Gelasio-Regular-osf-ts1--base.tfm \
tex-Gelasio-Regular-osf-ts1.tfm \
tex-Gelasio-Regular-osf-ts1.vf \
tex-Gelasio-Regular-sup-ly1.tfm \
tex-Gelasio-Regular-sup-ot1.tfm \
tex-Gelasio-Regular-sup-t1--base.tfm \
tex-Gelasio-Regular-sup-t1.tfm \
tex-Gelasio-Regular-sup-t1.vf \
tex-Gelasio-Regular-tlf-ly1.tfm \
tex-Gelasio-Regular-tlf-ot1.tfm \
tex-Gelasio-Regular-tlf-t1--base.tfm \
tex-Gelasio-Regular-tlf-t1.tfm \
tex-Gelasio-Regular-tlf-t1.vf \
tex-Gelasio-Regular-tlf-ts1--base.tfm \
tex-Gelasio-Regular-tlf-ts1.tfm \
tex-Gelasio-Regular-tlf-ts1.vf \
tex-Gelasio-Regular-tosf-ly1.tfm \
tex-Gelasio-Regular-tosf-ot1.tfm \
tex-Gelasio-Regular-tosf-t1--base.tfm \
tex-Gelasio-Regular-tosf-t1.tfm \
tex-Gelasio-Regular-tosf-t1.vf \
tex-Gelasio-Regular-tosf-ts1--base.tfm \
tex-Gelasio-Regular-tosf-ts1.tfm \
tex-Gelasio-Regular-tosf-ts1.vf \
tex-Gelasio-SemiBold-lf-ly1.tfm \
tex-Gelasio-SemiBold-lf-ot1.tfm \
tex-Gelasio-SemiBold-lf-t1--base.tfm \
tex-Gelasio-SemiBold-lf-t1.tfm \
tex-Gelasio-SemiBold-lf-t1.vf \
tex-Gelasio-SemiBold-lf-ts1--base.tfm \
tex-Gelasio-SemiBold-lf-ts1.tfm \
tex-Gelasio-SemiBold-lf-ts1.vf \
tex-Gelasio-SemiBold-osf-ly1.tfm \
tex-Gelasio-SemiBold-osf-ot1.tfm \
tex-Gelasio-SemiBold-osf-t1--base.tfm \
tex-Gelasio-SemiBold-osf-t1.tfm \
tex-Gelasio-SemiBold-osf-t1.vf \
tex-Gelasio-SemiBold-osf-ts1--base.tfm \
tex-Gelasio-SemiBold-osf-ts1.tfm \
tex-Gelasio-SemiBold-osf-ts1.vf \
tex-Gelasio-SemiBold-sup-ly1.tfm \
tex-Gelasio-SemiBold-sup-ot1.tfm \
tex-Gelasio-SemiBold-sup-t1--base.tfm \
tex-Gelasio-SemiBold-sup-t1.tfm \
tex-Gelasio-SemiBold-sup-t1.vf \
tex-Gelasio-SemiBold-tlf-ly1.tfm \
tex-Gelasio-SemiBold-tlf-ot1.tfm \
tex-Gelasio-SemiBold-tlf-t1--base.tfm \
tex-Gelasio-SemiBold-tlf-t1.tfm \
tex-Gelasio-SemiBold-tlf-t1.vf \
tex-Gelasio-SemiBold-tlf-ts1--base.tfm \
tex-Gelasio-SemiBold-tlf-ts1.tfm \
tex-Gelasio-SemiBold-tlf-ts1.vf \
tex-Gelasio-SemiBold-tosf-ly1.tfm \
tex-Gelasio-SemiBold-tosf-ot1.tfm \
tex-Gelasio-SemiBold-tosf-t1--base.tfm \
tex-Gelasio-SemiBold-tosf-t1.tfm \
tex-Gelasio-SemiBold-tosf-t1.vf \
tex-Gelasio-SemiBold-tosf-ts1--base.tfm \
tex-Gelasio-SemiBold-tosf-ts1.tfm \
tex-Gelasio-SemiBold-tosf-ts1.vf \
tex-Gelasio-SemiBoldItalic-lf-ly1.tfm \
tex-Gelasio-SemiBoldItalic-lf-ot1.tfm \
tex-Gelasio-SemiBoldItalic-lf-t1--base.tfm \
tex-Gelasio-SemiBoldItalic-lf-t1.tfm \
tex-Gelasio-SemiBoldItalic-lf-t1.vf \
tex-Gelasio-SemiBoldItalic-lf-ts1--base.tfm \
tex-Gelasio-SemiBoldItalic-lf-ts1.tfm \
tex-Gelasio-SemiBoldItalic-lf-ts1.vf \
tex-Gelasio-SemiBoldItalic-osf-ly1.tfm \
tex-Gelasio-SemiBoldItalic-osf-ot1.tfm \
tex-Gelasio-SemiBoldItalic-osf-t1--base.tfm \
tex-Gelasio-SemiBoldItalic-osf-t1.tfm \
tex-Gelasio-SemiBoldItalic-osf-t1.vf \
tex-Gelasio-SemiBoldItalic-osf-ts1--base.tfm \
tex-Gelasio-SemiBoldItalic-osf-ts1.tfm \
tex-Gelasio-SemiBoldItalic-osf-ts1.vf \
tex-Gelasio-SemiBoldItalic-sup-ly1.tfm \
tex-Gelasio-SemiBoldItalic-sup-ot1.tfm \
tex-Gelasio-SemiBoldItalic-sup-t1--base.tfm \
tex-Gelasio-SemiBoldItalic-sup-t1.tfm \
tex-Gelasio-SemiBoldItalic-sup-t1.vf \
tex-Gelasio-SemiBoldItalic-tlf-ly1.tfm \
tex-Gelasio-SemiBoldItalic-tlf-ot1.tfm \
tex-Gelasio-SemiBoldItalic-tlf-t1--base.tfm \
tex-Gelasio-SemiBoldItalic-tlf-t1.tfm \
tex-Gelasio-SemiBoldItalic-tlf-t1.vf \
tex-Gelasio-SemiBoldItalic-tlf-ts1--base.tfm \
tex-Gelasio-SemiBoldItalic-tlf-ts1.tfm \
tex-Gelasio-SemiBoldItalic-tlf-ts1.vf \
tex-Gelasio-SemiBoldItalic-tosf-ly1.tfm \
tex-Gelasio-SemiBoldItalic-tosf-ot1.tfm \
tex-Gelasio-SemiBoldItalic-tosf-t1--base.tfm \
tex-Gelasio-SemiBoldItalic-tosf-t1.tfm \
tex-Gelasio-SemiBoldItalic-tosf-t1.vf \
tex-Gelasio-SemiBoldItalic-tosf-ts1--base.tfm \
tex-Gelasio-SemiBoldItalic-tosf-ts1.tfm \
tex-Gelasio-SemiBoldItalic-tosf-ts1.vf \
tex-LY1Gelasio-LF.fd \
tex-LY1Gelasio-OsF.fd \
tex-LY1Gelasio-Sup.fd \
tex-LY1Gelasio-TLF.fd \
tex-LY1Gelasio-TOsF.fd \
tex-OT1Gelasio-LF.fd \
tex-OT1Gelasio-OsF.fd \
tex-OT1Gelasio-Sup.fd \
tex-OT1Gelasio-TLF.fd \
tex-OT1Gelasio-TOsF.fd \
tex-T1Gelasio-LF.fd \
tex-T1Gelasio-OsF.fd \
tex-T1Gelasio-Sup.fd \
tex-T1Gelasio-TLF.fd \
tex-T1Gelasio-TOsF.fd \
tex-TS1Gelasio-LF.fd \
tex-TS1Gelasio-OsF.fd \
tex-TS1Gelasio-TLF.fd \
tex-TS1Gelasio-TOsF.fd \
tex-gelasio.map \
tex-gelasio.sty \
tex-gls-5xld5w.enc \
tex-gls-6qeh6o.enc \
tex-gls-7npxgm.enc \
tex-gls-7rleul.enc \
tex-gls-ags7qn.enc \
tex-gls-cy3ufi.enc \
tex-gls-gldhmf.enc \
tex-gls-gww56v.enc \
tex-gls-jgoly6.enc \
tex-gls-k4bbiq.enc \
tex-gls-mx2b4h.enc \
tex-gls-ocoxw4.enc \
tex-gls-qndjqi.enc \
tex-gls-ro7vi7.enc \
tex-gls-ttjzpe.enc \
tex-gls-u2frii.enc \
tex-gls-uw7g7y.enc \
tex-gls-vgwtwr.enc \
tex-gls-wlsyn3.enc \
tex-gls-yyujwf.enc \
texlive-gelasio"

RDEPENDS:${PN} += "/usr/bin/sh \
coreutils \
ed \
findutils \
grep \
sed \
tex-fontaxes.sty \
tex-fontenc.sty \
tex-fontspec.sty \
tex-ifluatex.sty \
tex-ifxetex.sty \
tex-mweights.sty \
tex-textcomp.sty \
tex-updmap.cfg \
tex-xkeyval.sty \
texlive \
texlive-filesystem \
texlive-gelasio-fonts \
texlive-kpathsea \
texlive-kpathsea-bin \
texlive-scripts \
texlive-scripts-bin"

inherit rpm
