SUMMARY = "Launch jobs, organize the output, and dissect the results"
DESCRIPTION = "Lancet is designed to help you organize the output of your research \
tools, store it, and dissect the data you have collected. The output \
of a single simulation or analysis rarely contains all the data you \
need; Lancet helps you generate data from many runs and analyse it \
using your own Python code. \
 \
Parameter spaces often need to be explored for the purpose of \
plotting, tuning, or analysis. Lancet helps you extract the \
information you care about from potentially enormous volumes of data \
generated by such parameter exploration."
LICENSE = "BSD-3-Clause"

PV = "0.9.0"

RPM_NAME = "python313-lancet-ioam-0.9.0-3.5.noarch.rpm"
RPM_HASH = "5e541de65932fd616e6dcdef1d4d69d3e2dd214ea29f867865c3ec864f359ba21adf243b390ebfdae7807c59844721a643d6388bb7538575376d78a6d42df7c7"
REPO_ARCH = "noarch"

RPROVIDES:${PN} += "python3-lancet-ioam \
python3.13dist-lancet-ioam \
python313-lancet-ioam \
python3dist-lancet-ioam"

RDEPENDS:${PN} += "python-abi"

inherit rpm
