SUMMARY = "Kalpa Desktop"
DESCRIPTION = "This is the openSUSE Kalpa base system. It contains only fully working immutable desktop system."
LICENSE = "MIT"

PV = "6.1.1"

RPM_NAME = "patterns-kalpa-base-6.1.1-1.2.aarch64.rpm"
RPM_HASH = "cee3ee4d24167aaf4ea085862d66b4a2410659d3867d6ae32b4e04357d795f0eb1491137ccb512fbcdf65d54da8038274fdf080c61360f7ef00a4779948dca06"

RPROVIDES:${PN} += "pattern- \
pattern-category- \
pattern-icon- \
pattern-order- \
pattern-visible- \
patterns-kalpa-base"

RDEPENDS:${PN} += "Kalpa-release \
Mesa-demo-egl \
NetworkManager \
NetworkManager-bluetooth \
NetworkManager-openvpn \
NetworkManager-wifi \
OpenPrintingPPDs \
aaa-base \
adobe-sourcecodepro-fonts \
adobe-sourcesans3-fonts \
adobe-sourcesanspro-fonts \
adobe-sourceserifpro-fonts \
adwaita-fonts \
alsa-ucm-conf \
ark \
audit \
aurorae6 \
avahi \
bash \
bash-completion \
bluedevil6 \
bluez-cups \
bluez-firmware \
bluez-obexd \
bolt \
branding \
branding-Kalpa \
breeze6-wallpapers \
btrfsmaintenance \
btrfsprogs \
build-key \
busybox \
ca-certificates \
ca-certificates-mozilla \
cantarell-fonts \
chrony \
cifs-utils \
container-selinux \
coreutils \
coreutils-systemd \
cups \
cups-filters \
cups-pk-helper \
curl \
ddcutil-i2c-udev-rules \
dejavu-fonts \
desktop-data \
desktop-file-utils \
discover-backend-flatpak \
discover-backend-fwupd \
discover6-notifier \
distribution-logos-openSUSE-Kalpa \
distribution-release \
distrobox \
dolphin \
dosfstools \
epson-inkjet-printer-escpr \
ethtool \
exfatprogs \
falkon \
falkon-kde \
fastfetch \
fcoe-utils \
ffmpegthumbs \
filesystem \
flatpak-kcm6 \
fprintd \
fprintd-pam \
ghostscript \
ghostscript-fonts-std \
ghostscript-fonts-std-converted \
glibc \
glibc-locale \
glibc-locale-base \
google-carlito-fonts \
google-noto-coloremoji-fonts \
google-noto-sans-cjk-fonts \
google-noto-sans-symbols-fonts \
google-noto-sans-symbols2-fonts \
google-opensans-fonts \
google-roboto-fonts \
group-nobody \
grub2-arm64-efi \
grub2-branding-kalpa \
grub2-common \
gstreamer-plugin-pipewire \
gvfs \
gvfs-backends \
gzip \
hack-fonts \
health-checker \
health-checker-plugins-MicroOS \
hicolor-icon-theme-branding-openSUSE \
hostname \
hplip-hpijs \
hwinfo \
ibm-plex-mono-fonts \
iio-sensor-proxy \
iproute2 \
iputils \
irqbalance \
just \
kaccounts-integration \
kaccounts-providers \
kalpa-themes \
kalpa-themes-chefs-recommendation \
kalpa-themes-sddm \
kate \
kde-gtk-config6 \
kde-gtk-config6-gtk3 \
kde-inotify-survey \
kde-print-manager \
kdeconnect-kde \
kdegraphics-thumbnailers \
kdenetwork-filesharing \
kdeplasma6-addons \
kdnssd \
kdump \
kernel-default \
kernel-firmware-all \
kf6-baloo-file \
kf6-purpose \
kf6-qqc2-desktop-style \
kgamma6 \
kio-extras \
kio-fuse \
kio-gdrive \
konsole \
ksshaskpass6 \
kunifiedpush \
kwalletmanager \
lastlog2 \
less \
libappindicator3-1 \
liberation-fonts \
libinput-udev \
libmbim \
libnss-usrfiles2 \
libvulkan-intel \
libvulkan-radeon \
microos-tools \
mokutil \
ntfs-3g \
ntfsprogs \
ocean-sound-theme6 \
openSUSE-build-key \
openssh \
openvpn-auth-pam-plugin \
oxygen5-sounds \
pam \
pam-config \
pam-kwallet6 \
partitionmanager \
phonon-vlc-qt6 \
pinentry \
pipewire-alsa \
pipewire-pulseaudio \
plasma-branding-Kalpa \
plasma-browser-integration \
plasma6-desktop-emojier \
plasma6-nm \
plasma6-nm-openconnect \
plasma6-nm-openvpn \
plasma6-pa \
plasma6-session \
plasma6-systemmonitor \
plasma6-workspace-wallpapers \
podman \
policycoreutils \
policycoreutils-python-utils \
polkit-default-privs \
printer-driver-brlaser \
procps \
qemu-guest-agent \
qt6-imageformats \
rpm \
sane-backends \
sddm-kcm6 \
sddm-qt6 \
selinux-policy-targeted \
selinux-tools \
shadow \
shim \
snapper \
sof-firmware \
spectacle \
spice-vdagent \
steam-devices \
sudo \
sudo-policy-wheel-auth-self \
suse-fonts \
susepaste \
switcheroo-control \
system-config-printer-common \
system-config-printer-dbus-service \
system-group-wheel \
systemd \
systemd-coredump \
systemd-icon-branding-openSUSE \
systemd-presets-branding-Kalpa \
systemd-zram-service \
terminfo-base \
timezone \
tpm2-0-tss \
tpm2.0-abrmd \
tpm2.0-tools \
transactional-update \
transactional-update-notifier \
transactional-update-zypp-config \
udev-configure-printer \
udisks2 \
uefi-mbr \
unzip \
upower \
usbutils \
user-nobody \
util-linux \
vim-small \
wget \
wireguard-tools \
wtmpdb \
xdg-desktop-portal-gtk \
xdg-desktop-portal-kde6 \
xdg-utils \
yakuake \
yast2-logs \
zypper \
zypper-needs-restarting"

inherit rpm
