SUMMARY = "DSP infinite impulse response realtime C++ filter library"
DESCRIPTION = " \
An infinite impulse response (IIR) filter library for Linux, Mac OSX and Windows \
which implements Butterworth, RBJ, Chebychev filters and can easily import coefficients generated by Python (scipy). \
The filter processes the data sample by sample for realtime processing. \
It uses templates to allocate the required memory so that it can run without any malloc / new commands. \
Memory is allocated at compile time so that there is never the risk of memory leaks. \
All realtime filter code is in the header files which guarantees efficient integration into the main program \
and the compiler can optimise both filter code and main program at the same time."
LICENSE = "MIT"

PV = "1.10.0"

RPM_NAME = "libiir1-1.10.0-1.5.aarch64.rpm"
RPM_HASH = "a7d4c61377bf28dbbcde7eca81678ca23e64fb0b365742e130a2eea30986ccef12d0c0735c4e258684468e49384b4d9d80e38fcc4af5feaf1c99984626b0adac"

RPROVIDES:${PN} += "libiir.so.1 \
libiir1"

RDEPENDS:${PN} += "/sbin/ldconfig \
ld-linux-aarch64.so.1 \
libc.so.6 \
libgcc-s.so.1 \
libm.so.6 \
libstdc++.so.6"

inherit rpm
