SUMMARY = "The inter font face with support for LaTeX, XeLaTeX, and LuaLaTeX"
DESCRIPTION = "This package provides LaTeX, pdfLaTeX, XeLaTeX and LuaLaTeX \
support for the Inter Sans family of fonts (version 3.015), \
designed by Rasmus Andersson. Inter is a typeface specially \
designed for user interfaces with focus on high legibility of \
small-to-medium sized text on computer screens. The family \
features a tall x-height to aid in readability of mixed-case \
and lower-case text."
LICENSE = "OFL-1.1"

PV = "2026.226.svn77682"

RPM_NAME = "texlive-inter-2026.226.svn77682-60.2.noarch.rpm"
RPM_HASH = "e44d739c059fc7353b99e1bd2d9117123b343d4cba7606bdfdf42c1bc377a007bfc5c68c9ef2005c0642f50b05700ea1b600ced30c104a5e4c68001df0f83e12"
REPO_ARCH = "noarch"

RPROVIDES:${PN} += "tex-Inter-Black-lf-lgr--base.tfm \
tex-Inter-Black-lf-lgr.tfm \
tex-Inter-Black-lf-lgr.vf \
tex-Inter-Black-lf-ly1--base.tfm \
tex-Inter-Black-lf-ly1.tfm \
tex-Inter-Black-lf-ly1.vf \
tex-Inter-Black-lf-oml--base.tfm \
tex-Inter-Black-lf-oml.tfm \
tex-Inter-Black-lf-oml.vf \
tex-Inter-Black-lf-ot1.tfm \
tex-Inter-Black-lf-sc-lgr--base.tfm \
tex-Inter-Black-lf-sc-lgr.tfm \
tex-Inter-Black-lf-sc-lgr.vf \
tex-Inter-Black-lf-sc-ly1--base.tfm \
tex-Inter-Black-lf-sc-ly1.tfm \
tex-Inter-Black-lf-sc-ly1.vf \
tex-Inter-Black-lf-sc-ot1--base.tfm \
tex-Inter-Black-lf-sc-ot1.tfm \
tex-Inter-Black-lf-sc-ot1.vf \
tex-Inter-Black-lf-sc-t1--base.tfm \
tex-Inter-Black-lf-sc-t1.tfm \
tex-Inter-Black-lf-sc-t1.vf \
tex-Inter-Black-lf-t1--base.tfm \
tex-Inter-Black-lf-t1.tfm \
tex-Inter-Black-lf-t1.vf \
tex-Inter-Black-lf-ts1--base.tfm \
tex-Inter-Black-lf-ts1.tfm \
tex-Inter-Black-lf-ts1.vf \
tex-Inter-Black-sup-lgr--base.tfm \
tex-Inter-Black-sup-lgr.tfm \
tex-Inter-Black-sup-lgr.vf \
tex-Inter-Black-sup-ly1--base.tfm \
tex-Inter-Black-sup-ly1.tfm \
tex-Inter-Black-sup-ly1.vf \
tex-Inter-Black-sup-ot1.tfm \
tex-Inter-Black-sup-t1--base.tfm \
tex-Inter-Black-sup-t1.tfm \
tex-Inter-Black-sup-t1.vf \
tex-Inter-Black-tlf-lgr--base.tfm \
tex-Inter-Black-tlf-lgr.tfm \
tex-Inter-Black-tlf-lgr.vf \
tex-Inter-Black-tlf-ly1--base.tfm \
tex-Inter-Black-tlf-ly1.tfm \
tex-Inter-Black-tlf-ly1.vf \
tex-Inter-Black-tlf-oml--base.tfm \
tex-Inter-Black-tlf-oml.tfm \
tex-Inter-Black-tlf-oml.vf \
tex-Inter-Black-tlf-ot1.tfm \
tex-Inter-Black-tlf-sc-lgr--base.tfm \
tex-Inter-Black-tlf-sc-lgr.tfm \
tex-Inter-Black-tlf-sc-lgr.vf \
tex-Inter-Black-tlf-sc-ly1--base.tfm \
tex-Inter-Black-tlf-sc-ly1.tfm \
tex-Inter-Black-tlf-sc-ly1.vf \
tex-Inter-Black-tlf-sc-ot1--base.tfm \
tex-Inter-Black-tlf-sc-ot1.tfm \
tex-Inter-Black-tlf-sc-ot1.vf \
tex-Inter-Black-tlf-sc-t1--base.tfm \
tex-Inter-Black-tlf-sc-t1.tfm \
tex-Inter-Black-tlf-sc-t1.vf \
tex-Inter-Black-tlf-t1--base.tfm \
tex-Inter-Black-tlf-t1.tfm \
tex-Inter-Black-tlf-t1.vf \
tex-Inter-Black-tlf-ts1--base.tfm \
tex-Inter-Black-tlf-ts1.tfm \
tex-Inter-Black-tlf-ts1.vf \
tex-Inter-BlackItalic-lf-lgr--base.tfm \
tex-Inter-BlackItalic-lf-lgr.tfm \
tex-Inter-BlackItalic-lf-lgr.vf \
tex-Inter-BlackItalic-lf-ly1--base.tfm \
tex-Inter-BlackItalic-lf-ly1.tfm \
tex-Inter-BlackItalic-lf-ly1.vf \
tex-Inter-BlackItalic-lf-oml--base.tfm \
tex-Inter-BlackItalic-lf-oml.tfm \
tex-Inter-BlackItalic-lf-oml.vf \
tex-Inter-BlackItalic-lf-ot1.tfm \
tex-Inter-BlackItalic-lf-sc-lgr--base.tfm \
tex-Inter-BlackItalic-lf-sc-lgr.tfm \
tex-Inter-BlackItalic-lf-sc-lgr.vf \
tex-Inter-BlackItalic-lf-sc-ly1--base.tfm \
tex-Inter-BlackItalic-lf-sc-ly1.tfm \
tex-Inter-BlackItalic-lf-sc-ly1.vf \
tex-Inter-BlackItalic-lf-sc-ot1--base.tfm \
tex-Inter-BlackItalic-lf-sc-ot1.tfm \
tex-Inter-BlackItalic-lf-sc-ot1.vf \
tex-Inter-BlackItalic-lf-sc-t1--base.tfm \
tex-Inter-BlackItalic-lf-sc-t1.tfm \
tex-Inter-BlackItalic-lf-sc-t1.vf \
tex-Inter-BlackItalic-lf-t1--base.tfm \
tex-Inter-BlackItalic-lf-t1.tfm \
tex-Inter-BlackItalic-lf-t1.vf \
tex-Inter-BlackItalic-lf-ts1--base.tfm \
tex-Inter-BlackItalic-lf-ts1.tfm \
tex-Inter-BlackItalic-lf-ts1.vf \
tex-Inter-BlackItalic-sup-lgr--base.tfm \
tex-Inter-BlackItalic-sup-lgr.tfm \
tex-Inter-BlackItalic-sup-lgr.vf \
tex-Inter-BlackItalic-sup-ly1--base.tfm \
tex-Inter-BlackItalic-sup-ly1.tfm \
tex-Inter-BlackItalic-sup-ly1.vf \
tex-Inter-BlackItalic-sup-ot1.tfm \
tex-Inter-BlackItalic-sup-t1--base.tfm \
tex-Inter-BlackItalic-sup-t1.tfm \
tex-Inter-BlackItalic-sup-t1.vf \
tex-Inter-BlackItalic-tlf-lgr--base.tfm \
tex-Inter-BlackItalic-tlf-lgr.tfm \
tex-Inter-BlackItalic-tlf-lgr.vf \
tex-Inter-BlackItalic-tlf-ly1--base.tfm \
tex-Inter-BlackItalic-tlf-ly1.tfm \
tex-Inter-BlackItalic-tlf-ly1.vf \
tex-Inter-BlackItalic-tlf-oml--base.tfm \
tex-Inter-BlackItalic-tlf-oml.tfm \
tex-Inter-BlackItalic-tlf-oml.vf \
tex-Inter-BlackItalic-tlf-ot1.tfm \
tex-Inter-BlackItalic-tlf-sc-lgr--base.tfm \
tex-Inter-BlackItalic-tlf-sc-lgr.tfm \
tex-Inter-BlackItalic-tlf-sc-lgr.vf \
tex-Inter-BlackItalic-tlf-sc-ly1--base.tfm \
tex-Inter-BlackItalic-tlf-sc-ly1.tfm \
tex-Inter-BlackItalic-tlf-sc-ly1.vf \
tex-Inter-BlackItalic-tlf-sc-ot1--base.tfm \
tex-Inter-BlackItalic-tlf-sc-ot1.tfm \
tex-Inter-BlackItalic-tlf-sc-ot1.vf \
tex-Inter-BlackItalic-tlf-sc-t1--base.tfm \
tex-Inter-BlackItalic-tlf-sc-t1.tfm \
tex-Inter-BlackItalic-tlf-sc-t1.vf \
tex-Inter-BlackItalic-tlf-t1--base.tfm \
tex-Inter-BlackItalic-tlf-t1.tfm \
tex-Inter-BlackItalic-tlf-t1.vf \
tex-Inter-BlackItalic-tlf-ts1--base.tfm \
tex-Inter-BlackItalic-tlf-ts1.tfm \
tex-Inter-BlackItalic-tlf-ts1.vf \
tex-Inter-Bold-lf-lgr--base.tfm \
tex-Inter-Bold-lf-lgr.tfm \
tex-Inter-Bold-lf-lgr.vf \
tex-Inter-Bold-lf-ly1--base.tfm \
tex-Inter-Bold-lf-ly1.tfm \
tex-Inter-Bold-lf-ly1.vf \
tex-Inter-Bold-lf-oml--base.tfm \
tex-Inter-Bold-lf-oml.tfm \
tex-Inter-Bold-lf-oml.vf \
tex-Inter-Bold-lf-ot1.tfm \
tex-Inter-Bold-lf-sc-lgr--base.tfm \
tex-Inter-Bold-lf-sc-lgr.tfm \
tex-Inter-Bold-lf-sc-lgr.vf \
tex-Inter-Bold-lf-sc-ly1--base.tfm \
tex-Inter-Bold-lf-sc-ly1.tfm \
tex-Inter-Bold-lf-sc-ly1.vf \
tex-Inter-Bold-lf-sc-ot1--base.tfm \
tex-Inter-Bold-lf-sc-ot1.tfm \
tex-Inter-Bold-lf-sc-ot1.vf \
tex-Inter-Bold-lf-sc-t1--base.tfm \
tex-Inter-Bold-lf-sc-t1.tfm \
tex-Inter-Bold-lf-sc-t1.vf \
tex-Inter-Bold-lf-t1--base.tfm \
tex-Inter-Bold-lf-t1.tfm \
tex-Inter-Bold-lf-t1.vf \
tex-Inter-Bold-lf-ts1--base.tfm \
tex-Inter-Bold-lf-ts1.tfm \
tex-Inter-Bold-lf-ts1.vf \
tex-Inter-Bold-sup-lgr--base.tfm \
tex-Inter-Bold-sup-lgr.tfm \
tex-Inter-Bold-sup-lgr.vf \
tex-Inter-Bold-sup-ly1--base.tfm \
tex-Inter-Bold-sup-ly1.tfm \
tex-Inter-Bold-sup-ly1.vf \
tex-Inter-Bold-sup-ot1.tfm \
tex-Inter-Bold-sup-t1--base.tfm \
tex-Inter-Bold-sup-t1.tfm \
tex-Inter-Bold-sup-t1.vf \
tex-Inter-Bold-tlf-lgr--base.tfm \
tex-Inter-Bold-tlf-lgr.tfm \
tex-Inter-Bold-tlf-lgr.vf \
tex-Inter-Bold-tlf-ly1--base.tfm \
tex-Inter-Bold-tlf-ly1.tfm \
tex-Inter-Bold-tlf-ly1.vf \
tex-Inter-Bold-tlf-oml--base.tfm \
tex-Inter-Bold-tlf-oml.tfm \
tex-Inter-Bold-tlf-oml.vf \
tex-Inter-Bold-tlf-ot1.tfm \
tex-Inter-Bold-tlf-sc-lgr--base.tfm \
tex-Inter-Bold-tlf-sc-lgr.tfm \
tex-Inter-Bold-tlf-sc-lgr.vf \
tex-Inter-Bold-tlf-sc-ly1--base.tfm \
tex-Inter-Bold-tlf-sc-ly1.tfm \
tex-Inter-Bold-tlf-sc-ly1.vf \
tex-Inter-Bold-tlf-sc-ot1--base.tfm \
tex-Inter-Bold-tlf-sc-ot1.tfm \
tex-Inter-Bold-tlf-sc-ot1.vf \
tex-Inter-Bold-tlf-sc-t1--base.tfm \
tex-Inter-Bold-tlf-sc-t1.tfm \
tex-Inter-Bold-tlf-sc-t1.vf \
tex-Inter-Bold-tlf-t1--base.tfm \
tex-Inter-Bold-tlf-t1.tfm \
tex-Inter-Bold-tlf-t1.vf \
tex-Inter-Bold-tlf-ts1--base.tfm \
tex-Inter-Bold-tlf-ts1.tfm \
tex-Inter-Bold-tlf-ts1.vf \
tex-Inter-BoldItalic-lf-lgr--base.tfm \
tex-Inter-BoldItalic-lf-lgr.tfm \
tex-Inter-BoldItalic-lf-lgr.vf \
tex-Inter-BoldItalic-lf-ly1--base.tfm \
tex-Inter-BoldItalic-lf-ly1.tfm \
tex-Inter-BoldItalic-lf-ly1.vf \
tex-Inter-BoldItalic-lf-oml--base.tfm \
tex-Inter-BoldItalic-lf-oml.tfm \
tex-Inter-BoldItalic-lf-oml.vf \
tex-Inter-BoldItalic-lf-ot1.tfm \
tex-Inter-BoldItalic-lf-sc-lgr--base.tfm \
tex-Inter-BoldItalic-lf-sc-lgr.tfm \
tex-Inter-BoldItalic-lf-sc-lgr.vf \
tex-Inter-BoldItalic-lf-sc-ly1--base.tfm \
tex-Inter-BoldItalic-lf-sc-ly1.tfm \
tex-Inter-BoldItalic-lf-sc-ly1.vf \
tex-Inter-BoldItalic-lf-sc-ot1--base.tfm \
tex-Inter-BoldItalic-lf-sc-ot1.tfm \
tex-Inter-BoldItalic-lf-sc-ot1.vf \
tex-Inter-BoldItalic-lf-sc-t1--base.tfm \
tex-Inter-BoldItalic-lf-sc-t1.tfm \
tex-Inter-BoldItalic-lf-sc-t1.vf \
tex-Inter-BoldItalic-lf-t1--base.tfm \
tex-Inter-BoldItalic-lf-t1.tfm \
tex-Inter-BoldItalic-lf-t1.vf \
tex-Inter-BoldItalic-lf-ts1--base.tfm \
tex-Inter-BoldItalic-lf-ts1.tfm \
tex-Inter-BoldItalic-lf-ts1.vf \
tex-Inter-BoldItalic-sup-lgr--base.tfm \
tex-Inter-BoldItalic-sup-lgr.tfm \
tex-Inter-BoldItalic-sup-lgr.vf \
tex-Inter-BoldItalic-sup-ly1--base.tfm \
tex-Inter-BoldItalic-sup-ly1.tfm \
tex-Inter-BoldItalic-sup-ly1.vf \
tex-Inter-BoldItalic-sup-ot1.tfm \
tex-Inter-BoldItalic-sup-t1--base.tfm \
tex-Inter-BoldItalic-sup-t1.tfm \
tex-Inter-BoldItalic-sup-t1.vf \
tex-Inter-BoldItalic-tlf-lgr--base.tfm \
tex-Inter-BoldItalic-tlf-lgr.tfm \
tex-Inter-BoldItalic-tlf-lgr.vf \
tex-Inter-BoldItalic-tlf-ly1--base.tfm \
tex-Inter-BoldItalic-tlf-ly1.tfm \
tex-Inter-BoldItalic-tlf-ly1.vf \
tex-Inter-BoldItalic-tlf-oml--base.tfm \
tex-Inter-BoldItalic-tlf-oml.tfm \
tex-Inter-BoldItalic-tlf-oml.vf \
tex-Inter-BoldItalic-tlf-ot1.tfm \
tex-Inter-BoldItalic-tlf-sc-lgr--base.tfm \
tex-Inter-BoldItalic-tlf-sc-lgr.tfm \
tex-Inter-BoldItalic-tlf-sc-lgr.vf \
tex-Inter-BoldItalic-tlf-sc-ly1--base.tfm \
tex-Inter-BoldItalic-tlf-sc-ly1.tfm \
tex-Inter-BoldItalic-tlf-sc-ly1.vf \
tex-Inter-BoldItalic-tlf-sc-ot1--base.tfm \
tex-Inter-BoldItalic-tlf-sc-ot1.tfm \
tex-Inter-BoldItalic-tlf-sc-ot1.vf \
tex-Inter-BoldItalic-tlf-sc-t1--base.tfm \
tex-Inter-BoldItalic-tlf-sc-t1.tfm \
tex-Inter-BoldItalic-tlf-sc-t1.vf \
tex-Inter-BoldItalic-tlf-t1--base.tfm \
tex-Inter-BoldItalic-tlf-t1.tfm \
tex-Inter-BoldItalic-tlf-t1.vf \
tex-Inter-BoldItalic-tlf-ts1--base.tfm \
tex-Inter-BoldItalic-tlf-ts1.tfm \
tex-Inter-BoldItalic-tlf-ts1.vf \
tex-Inter-ExtraBold-lf-lgr--base.tfm \
tex-Inter-ExtraBold-lf-lgr.tfm \
tex-Inter-ExtraBold-lf-lgr.vf \
tex-Inter-ExtraBold-lf-ly1--base.tfm \
tex-Inter-ExtraBold-lf-ly1.tfm \
tex-Inter-ExtraBold-lf-ly1.vf \
tex-Inter-ExtraBold-lf-oml--base.tfm \
tex-Inter-ExtraBold-lf-oml.tfm \
tex-Inter-ExtraBold-lf-oml.vf \
tex-Inter-ExtraBold-lf-ot1.tfm \
tex-Inter-ExtraBold-lf-sc-lgr--base.tfm \
tex-Inter-ExtraBold-lf-sc-lgr.tfm \
tex-Inter-ExtraBold-lf-sc-lgr.vf \
tex-Inter-ExtraBold-lf-sc-ly1--base.tfm \
tex-Inter-ExtraBold-lf-sc-ly1.tfm \
tex-Inter-ExtraBold-lf-sc-ly1.vf \
tex-Inter-ExtraBold-lf-sc-ot1--base.tfm \
tex-Inter-ExtraBold-lf-sc-ot1.tfm \
tex-Inter-ExtraBold-lf-sc-ot1.vf \
tex-Inter-ExtraBold-lf-sc-t1--base.tfm \
tex-Inter-ExtraBold-lf-sc-t1.tfm \
tex-Inter-ExtraBold-lf-sc-t1.vf \
tex-Inter-ExtraBold-lf-t1--base.tfm \
tex-Inter-ExtraBold-lf-t1.tfm \
tex-Inter-ExtraBold-lf-t1.vf \
tex-Inter-ExtraBold-lf-ts1--base.tfm \
tex-Inter-ExtraBold-lf-ts1.tfm \
tex-Inter-ExtraBold-lf-ts1.vf \
tex-Inter-ExtraBold-sup-lgr--base.tfm \
tex-Inter-ExtraBold-sup-lgr.tfm \
tex-Inter-ExtraBold-sup-lgr.vf \
tex-Inter-ExtraBold-sup-ly1--base.tfm \
tex-Inter-ExtraBold-sup-ly1.tfm \
tex-Inter-ExtraBold-sup-ly1.vf \
tex-Inter-ExtraBold-sup-ot1.tfm \
tex-Inter-ExtraBold-sup-t1--base.tfm \
tex-Inter-ExtraBold-sup-t1.tfm \
tex-Inter-ExtraBold-sup-t1.vf \
tex-Inter-ExtraBold-tlf-lgr--base.tfm \
tex-Inter-ExtraBold-tlf-lgr.tfm \
tex-Inter-ExtraBold-tlf-lgr.vf \
tex-Inter-ExtraBold-tlf-ly1--base.tfm \
tex-Inter-ExtraBold-tlf-ly1.tfm \
tex-Inter-ExtraBold-tlf-ly1.vf \
tex-Inter-ExtraBold-tlf-oml--base.tfm \
tex-Inter-ExtraBold-tlf-oml.tfm \
tex-Inter-ExtraBold-tlf-oml.vf \
tex-Inter-ExtraBold-tlf-ot1.tfm \
tex-Inter-ExtraBold-tlf-sc-lgr--base.tfm \
tex-Inter-ExtraBold-tlf-sc-lgr.tfm \
tex-Inter-ExtraBold-tlf-sc-lgr.vf \
tex-Inter-ExtraBold-tlf-sc-ly1--base.tfm \
tex-Inter-ExtraBold-tlf-sc-ly1.tfm \
tex-Inter-ExtraBold-tlf-sc-ly1.vf \
tex-Inter-ExtraBold-tlf-sc-ot1--base.tfm \
tex-Inter-ExtraBold-tlf-sc-ot1.tfm \
tex-Inter-ExtraBold-tlf-sc-ot1.vf \
tex-Inter-ExtraBold-tlf-sc-t1--base.tfm \
tex-Inter-ExtraBold-tlf-sc-t1.tfm \
tex-Inter-ExtraBold-tlf-sc-t1.vf \
tex-Inter-ExtraBold-tlf-t1--base.tfm \
tex-Inter-ExtraBold-tlf-t1.tfm \
tex-Inter-ExtraBold-tlf-t1.vf \
tex-Inter-ExtraBold-tlf-ts1--base.tfm \
tex-Inter-ExtraBold-tlf-ts1.tfm \
tex-Inter-ExtraBold-tlf-ts1.vf \
tex-Inter-ExtraBoldItalic-lf-lgr--base.tfm \
tex-Inter-ExtraBoldItalic-lf-lgr.tfm \
tex-Inter-ExtraBoldItalic-lf-lgr.vf \
tex-Inter-ExtraBoldItalic-lf-ly1--base.tfm \
tex-Inter-ExtraBoldItalic-lf-ly1.tfm \
tex-Inter-ExtraBoldItalic-lf-ly1.vf \
tex-Inter-ExtraBoldItalic-lf-oml--base.tfm \
tex-Inter-ExtraBoldItalic-lf-oml.tfm \
tex-Inter-ExtraBoldItalic-lf-oml.vf \
tex-Inter-ExtraBoldItalic-lf-ot1.tfm \
tex-Inter-ExtraBoldItalic-lf-sc-lgr--base.tfm \
tex-Inter-ExtraBoldItalic-lf-sc-lgr.tfm \
tex-Inter-ExtraBoldItalic-lf-sc-lgr.vf \
tex-Inter-ExtraBoldItalic-lf-sc-ly1--base.tfm \
tex-Inter-ExtraBoldItalic-lf-sc-ly1.tfm \
tex-Inter-ExtraBoldItalic-lf-sc-ly1.vf \
tex-Inter-ExtraBoldItalic-lf-sc-ot1--base.tfm \
tex-Inter-ExtraBoldItalic-lf-sc-ot1.tfm \
tex-Inter-ExtraBoldItalic-lf-sc-ot1.vf \
tex-Inter-ExtraBoldItalic-lf-sc-t1--base.tfm \
tex-Inter-ExtraBoldItalic-lf-sc-t1.tfm \
tex-Inter-ExtraBoldItalic-lf-sc-t1.vf \
tex-Inter-ExtraBoldItalic-lf-t1--base.tfm \
tex-Inter-ExtraBoldItalic-lf-t1.tfm \
tex-Inter-ExtraBoldItalic-lf-t1.vf \
tex-Inter-ExtraBoldItalic-lf-ts1--base.tfm \
tex-Inter-ExtraBoldItalic-lf-ts1.tfm \
tex-Inter-ExtraBoldItalic-lf-ts1.vf \
tex-Inter-ExtraBoldItalic-sup-lgr--base.tfm \
tex-Inter-ExtraBoldItalic-sup-lgr.tfm \
tex-Inter-ExtraBoldItalic-sup-lgr.vf \
tex-Inter-ExtraBoldItalic-sup-ly1--base.tfm \
tex-Inter-ExtraBoldItalic-sup-ly1.tfm \
tex-Inter-ExtraBoldItalic-sup-ly1.vf \
tex-Inter-ExtraBoldItalic-sup-ot1.tfm \
tex-Inter-ExtraBoldItalic-sup-t1--base.tfm \
tex-Inter-ExtraBoldItalic-sup-t1.tfm \
tex-Inter-ExtraBoldItalic-sup-t1.vf \
tex-Inter-ExtraBoldItalic-tlf-lgr--base.tfm \
tex-Inter-ExtraBoldItalic-tlf-lgr.tfm \
tex-Inter-ExtraBoldItalic-tlf-lgr.vf \
tex-Inter-ExtraBoldItalic-tlf-ly1--base.tfm \
tex-Inter-ExtraBoldItalic-tlf-ly1.tfm \
tex-Inter-ExtraBoldItalic-tlf-ly1.vf \
tex-Inter-ExtraBoldItalic-tlf-oml--base.tfm \
tex-Inter-ExtraBoldItalic-tlf-oml.tfm \
tex-Inter-ExtraBoldItalic-tlf-oml.vf \
tex-Inter-ExtraBoldItalic-tlf-ot1.tfm \
tex-Inter-ExtraBoldItalic-tlf-sc-lgr--base.tfm \
tex-Inter-ExtraBoldItalic-tlf-sc-lgr.tfm \
tex-Inter-ExtraBoldItalic-tlf-sc-lgr.vf \
tex-Inter-ExtraBoldItalic-tlf-sc-ly1--base.tfm \
tex-Inter-ExtraBoldItalic-tlf-sc-ly1.tfm \
tex-Inter-ExtraBoldItalic-tlf-sc-ly1.vf \
tex-Inter-ExtraBoldItalic-tlf-sc-ot1--base.tfm \
tex-Inter-ExtraBoldItalic-tlf-sc-ot1.tfm \
tex-Inter-ExtraBoldItalic-tlf-sc-ot1.vf \
tex-Inter-ExtraBoldItalic-tlf-sc-t1--base.tfm \
tex-Inter-ExtraBoldItalic-tlf-sc-t1.tfm \
tex-Inter-ExtraBoldItalic-tlf-sc-t1.vf \
tex-Inter-ExtraBoldItalic-tlf-t1--base.tfm \
tex-Inter-ExtraBoldItalic-tlf-t1.tfm \
tex-Inter-ExtraBoldItalic-tlf-t1.vf \
tex-Inter-ExtraBoldItalic-tlf-ts1--base.tfm \
tex-Inter-ExtraBoldItalic-tlf-ts1.tfm \
tex-Inter-ExtraBoldItalic-tlf-ts1.vf \
tex-Inter-ExtraLight-lf-lgr--base.tfm \
tex-Inter-ExtraLight-lf-lgr.tfm \
tex-Inter-ExtraLight-lf-lgr.vf \
tex-Inter-ExtraLight-lf-ly1--base.tfm \
tex-Inter-ExtraLight-lf-ly1.tfm \
tex-Inter-ExtraLight-lf-ly1.vf \
tex-Inter-ExtraLight-lf-oml--base.tfm \
tex-Inter-ExtraLight-lf-oml.tfm \
tex-Inter-ExtraLight-lf-oml.vf \
tex-Inter-ExtraLight-lf-ot1.tfm \
tex-Inter-ExtraLight-lf-sc-lgr--base.tfm \
tex-Inter-ExtraLight-lf-sc-lgr.tfm \
tex-Inter-ExtraLight-lf-sc-lgr.vf \
tex-Inter-ExtraLight-lf-sc-ly1--base.tfm \
tex-Inter-ExtraLight-lf-sc-ly1.tfm \
tex-Inter-ExtraLight-lf-sc-ly1.vf \
tex-Inter-ExtraLight-lf-sc-ot1--base.tfm \
tex-Inter-ExtraLight-lf-sc-ot1.tfm \
tex-Inter-ExtraLight-lf-sc-ot1.vf \
tex-Inter-ExtraLight-lf-sc-t1--base.tfm \
tex-Inter-ExtraLight-lf-sc-t1.tfm \
tex-Inter-ExtraLight-lf-sc-t1.vf \
tex-Inter-ExtraLight-lf-t1--base.tfm \
tex-Inter-ExtraLight-lf-t1.tfm \
tex-Inter-ExtraLight-lf-t1.vf \
tex-Inter-ExtraLight-lf-ts1--base.tfm \
tex-Inter-ExtraLight-lf-ts1.tfm \
tex-Inter-ExtraLight-lf-ts1.vf \
tex-Inter-ExtraLight-sup-lgr--base.tfm \
tex-Inter-ExtraLight-sup-lgr.tfm \
tex-Inter-ExtraLight-sup-lgr.vf \
tex-Inter-ExtraLight-sup-ly1--base.tfm \
tex-Inter-ExtraLight-sup-ly1.tfm \
tex-Inter-ExtraLight-sup-ly1.vf \
tex-Inter-ExtraLight-sup-ot1.tfm \
tex-Inter-ExtraLight-sup-t1--base.tfm \
tex-Inter-ExtraLight-sup-t1.tfm \
tex-Inter-ExtraLight-sup-t1.vf \
tex-Inter-ExtraLight-tlf-lgr--base.tfm \
tex-Inter-ExtraLight-tlf-lgr.tfm \
tex-Inter-ExtraLight-tlf-lgr.vf \
tex-Inter-ExtraLight-tlf-ly1--base.tfm \
tex-Inter-ExtraLight-tlf-ly1.tfm \
tex-Inter-ExtraLight-tlf-ly1.vf \
tex-Inter-ExtraLight-tlf-oml--base.tfm \
tex-Inter-ExtraLight-tlf-oml.tfm \
tex-Inter-ExtraLight-tlf-oml.vf \
tex-Inter-ExtraLight-tlf-ot1.tfm \
tex-Inter-ExtraLight-tlf-sc-lgr--base.tfm \
tex-Inter-ExtraLight-tlf-sc-lgr.tfm \
tex-Inter-ExtraLight-tlf-sc-lgr.vf \
tex-Inter-ExtraLight-tlf-sc-ly1--base.tfm \
tex-Inter-ExtraLight-tlf-sc-ly1.tfm \
tex-Inter-ExtraLight-tlf-sc-ly1.vf \
tex-Inter-ExtraLight-tlf-sc-ot1--base.tfm \
tex-Inter-ExtraLight-tlf-sc-ot1.tfm \
tex-Inter-ExtraLight-tlf-sc-ot1.vf \
tex-Inter-ExtraLight-tlf-sc-t1--base.tfm \
tex-Inter-ExtraLight-tlf-sc-t1.tfm \
tex-Inter-ExtraLight-tlf-sc-t1.vf \
tex-Inter-ExtraLight-tlf-t1--base.tfm \
tex-Inter-ExtraLight-tlf-t1.tfm \
tex-Inter-ExtraLight-tlf-t1.vf \
tex-Inter-ExtraLight-tlf-ts1--base.tfm \
tex-Inter-ExtraLight-tlf-ts1.tfm \
tex-Inter-ExtraLight-tlf-ts1.vf \
tex-Inter-ExtraLightItalic-lf-lgr--base.tfm \
tex-Inter-ExtraLightItalic-lf-lgr.tfm \
tex-Inter-ExtraLightItalic-lf-lgr.vf \
tex-Inter-ExtraLightItalic-lf-ly1--base.tfm \
tex-Inter-ExtraLightItalic-lf-ly1.tfm \
tex-Inter-ExtraLightItalic-lf-ly1.vf \
tex-Inter-ExtraLightItalic-lf-oml--base.tfm \
tex-Inter-ExtraLightItalic-lf-oml.tfm \
tex-Inter-ExtraLightItalic-lf-oml.vf \
tex-Inter-ExtraLightItalic-lf-ot1.tfm \
tex-Inter-ExtraLightItalic-lf-sc-lgr--base.tfm \
tex-Inter-ExtraLightItalic-lf-sc-lgr.tfm \
tex-Inter-ExtraLightItalic-lf-sc-lgr.vf \
tex-Inter-ExtraLightItalic-lf-sc-ly1--base.tfm \
tex-Inter-ExtraLightItalic-lf-sc-ly1.tfm \
tex-Inter-ExtraLightItalic-lf-sc-ly1.vf \
tex-Inter-ExtraLightItalic-lf-sc-ot1--base.tfm \
tex-Inter-ExtraLightItalic-lf-sc-ot1.tfm \
tex-Inter-ExtraLightItalic-lf-sc-ot1.vf \
tex-Inter-ExtraLightItalic-lf-sc-t1--base.tfm \
tex-Inter-ExtraLightItalic-lf-sc-t1.tfm \
tex-Inter-ExtraLightItalic-lf-sc-t1.vf \
tex-Inter-ExtraLightItalic-lf-t1--base.tfm \
tex-Inter-ExtraLightItalic-lf-t1.tfm \
tex-Inter-ExtraLightItalic-lf-t1.vf \
tex-Inter-ExtraLightItalic-lf-ts1--base.tfm \
tex-Inter-ExtraLightItalic-lf-ts1.tfm \
tex-Inter-ExtraLightItalic-lf-ts1.vf \
tex-Inter-ExtraLightItalic-sup-lgr--base.tfm \
tex-Inter-ExtraLightItalic-sup-lgr.tfm \
tex-Inter-ExtraLightItalic-sup-lgr.vf \
tex-Inter-ExtraLightItalic-sup-ly1--base.tfm \
tex-Inter-ExtraLightItalic-sup-ly1.tfm \
tex-Inter-ExtraLightItalic-sup-ly1.vf \
tex-Inter-ExtraLightItalic-sup-ot1.tfm \
tex-Inter-ExtraLightItalic-sup-t1--base.tfm \
tex-Inter-ExtraLightItalic-sup-t1.tfm \
tex-Inter-ExtraLightItalic-sup-t1.vf \
tex-Inter-ExtraLightItalic-tlf-lgr--base.tfm \
tex-Inter-ExtraLightItalic-tlf-lgr.tfm \
tex-Inter-ExtraLightItalic-tlf-lgr.vf \
tex-Inter-ExtraLightItalic-tlf-ly1--base.tfm \
tex-Inter-ExtraLightItalic-tlf-ly1.tfm \
tex-Inter-ExtraLightItalic-tlf-ly1.vf \
tex-Inter-ExtraLightItalic-tlf-oml--base.tfm \
tex-Inter-ExtraLightItalic-tlf-oml.tfm \
tex-Inter-ExtraLightItalic-tlf-oml.vf \
tex-Inter-ExtraLightItalic-tlf-ot1.tfm \
tex-Inter-ExtraLightItalic-tlf-sc-lgr--base.tfm \
tex-Inter-ExtraLightItalic-tlf-sc-lgr.tfm \
tex-Inter-ExtraLightItalic-tlf-sc-lgr.vf \
tex-Inter-ExtraLightItalic-tlf-sc-ly1--base.tfm \
tex-Inter-ExtraLightItalic-tlf-sc-ly1.tfm \
tex-Inter-ExtraLightItalic-tlf-sc-ly1.vf \
tex-Inter-ExtraLightItalic-tlf-sc-ot1--base.tfm \
tex-Inter-ExtraLightItalic-tlf-sc-ot1.tfm \
tex-Inter-ExtraLightItalic-tlf-sc-ot1.vf \
tex-Inter-ExtraLightItalic-tlf-sc-t1--base.tfm \
tex-Inter-ExtraLightItalic-tlf-sc-t1.tfm \
tex-Inter-ExtraLightItalic-tlf-sc-t1.vf \
tex-Inter-ExtraLightItalic-tlf-t1--base.tfm \
tex-Inter-ExtraLightItalic-tlf-t1.tfm \
tex-Inter-ExtraLightItalic-tlf-t1.vf \
tex-Inter-ExtraLightItalic-tlf-ts1--base.tfm \
tex-Inter-ExtraLightItalic-tlf-ts1.tfm \
tex-Inter-ExtraLightItalic-tlf-ts1.vf \
tex-Inter-Italic-lf-lgr--base.tfm \
tex-Inter-Italic-lf-lgr.tfm \
tex-Inter-Italic-lf-lgr.vf \
tex-Inter-Italic-lf-ly1--base.tfm \
tex-Inter-Italic-lf-ly1.tfm \
tex-Inter-Italic-lf-ly1.vf \
tex-Inter-Italic-lf-oml--base.tfm \
tex-Inter-Italic-lf-oml.tfm \
tex-Inter-Italic-lf-oml.vf \
tex-Inter-Italic-lf-ot1.tfm \
tex-Inter-Italic-lf-sc-lgr--base.tfm \
tex-Inter-Italic-lf-sc-lgr.tfm \
tex-Inter-Italic-lf-sc-lgr.vf \
tex-Inter-Italic-lf-sc-ly1--base.tfm \
tex-Inter-Italic-lf-sc-ly1.tfm \
tex-Inter-Italic-lf-sc-ly1.vf \
tex-Inter-Italic-lf-sc-ot1--base.tfm \
tex-Inter-Italic-lf-sc-ot1.tfm \
tex-Inter-Italic-lf-sc-ot1.vf \
tex-Inter-Italic-lf-sc-t1--base.tfm \
tex-Inter-Italic-lf-sc-t1.tfm \
tex-Inter-Italic-lf-sc-t1.vf \
tex-Inter-Italic-lf-t1--base.tfm \
tex-Inter-Italic-lf-t1.tfm \
tex-Inter-Italic-lf-t1.vf \
tex-Inter-Italic-lf-ts1--base.tfm \
tex-Inter-Italic-lf-ts1.tfm \
tex-Inter-Italic-lf-ts1.vf \
tex-Inter-Italic-sup-lgr--base.tfm \
tex-Inter-Italic-sup-lgr.tfm \
tex-Inter-Italic-sup-lgr.vf \
tex-Inter-Italic-sup-ly1--base.tfm \
tex-Inter-Italic-sup-ly1.tfm \
tex-Inter-Italic-sup-ly1.vf \
tex-Inter-Italic-sup-ot1.tfm \
tex-Inter-Italic-sup-t1--base.tfm \
tex-Inter-Italic-sup-t1.tfm \
tex-Inter-Italic-sup-t1.vf \
tex-Inter-Italic-tlf-lgr--base.tfm \
tex-Inter-Italic-tlf-lgr.tfm \
tex-Inter-Italic-tlf-lgr.vf \
tex-Inter-Italic-tlf-ly1--base.tfm \
tex-Inter-Italic-tlf-ly1.tfm \
tex-Inter-Italic-tlf-ly1.vf \
tex-Inter-Italic-tlf-oml--base.tfm \
tex-Inter-Italic-tlf-oml.tfm \
tex-Inter-Italic-tlf-oml.vf \
tex-Inter-Italic-tlf-ot1.tfm \
tex-Inter-Italic-tlf-sc-lgr--base.tfm \
tex-Inter-Italic-tlf-sc-lgr.tfm \
tex-Inter-Italic-tlf-sc-lgr.vf \
tex-Inter-Italic-tlf-sc-ly1--base.tfm \
tex-Inter-Italic-tlf-sc-ly1.tfm \
tex-Inter-Italic-tlf-sc-ly1.vf \
tex-Inter-Italic-tlf-sc-ot1--base.tfm \
tex-Inter-Italic-tlf-sc-ot1.tfm \
tex-Inter-Italic-tlf-sc-ot1.vf \
tex-Inter-Italic-tlf-sc-t1--base.tfm \
tex-Inter-Italic-tlf-sc-t1.tfm \
tex-Inter-Italic-tlf-sc-t1.vf \
tex-Inter-Italic-tlf-t1--base.tfm \
tex-Inter-Italic-tlf-t1.tfm \
tex-Inter-Italic-tlf-t1.vf \
tex-Inter-Italic-tlf-ts1--base.tfm \
tex-Inter-Italic-tlf-ts1.tfm \
tex-Inter-Italic-tlf-ts1.vf \
tex-Inter-Light-lf-lgr--base.tfm \
tex-Inter-Light-lf-lgr.tfm \
tex-Inter-Light-lf-lgr.vf \
tex-Inter-Light-lf-ly1--base.tfm \
tex-Inter-Light-lf-ly1.tfm \
tex-Inter-Light-lf-ly1.vf \
tex-Inter-Light-lf-oml--base.tfm \
tex-Inter-Light-lf-oml.tfm \
tex-Inter-Light-lf-oml.vf \
tex-Inter-Light-lf-ot1.tfm \
tex-Inter-Light-lf-sc-lgr--base.tfm \
tex-Inter-Light-lf-sc-lgr.tfm \
tex-Inter-Light-lf-sc-lgr.vf \
tex-Inter-Light-lf-sc-ly1--base.tfm \
tex-Inter-Light-lf-sc-ly1.tfm \
tex-Inter-Light-lf-sc-ly1.vf \
tex-Inter-Light-lf-sc-ot1--base.tfm \
tex-Inter-Light-lf-sc-ot1.tfm \
tex-Inter-Light-lf-sc-ot1.vf \
tex-Inter-Light-lf-sc-t1--base.tfm \
tex-Inter-Light-lf-sc-t1.tfm \
tex-Inter-Light-lf-sc-t1.vf \
tex-Inter-Light-lf-t1--base.tfm \
tex-Inter-Light-lf-t1.tfm \
tex-Inter-Light-lf-t1.vf \
tex-Inter-Light-lf-ts1--base.tfm \
tex-Inter-Light-lf-ts1.tfm \
tex-Inter-Light-lf-ts1.vf \
tex-Inter-Light-sup-lgr--base.tfm \
tex-Inter-Light-sup-lgr.tfm \
tex-Inter-Light-sup-lgr.vf \
tex-Inter-Light-sup-ly1--base.tfm \
tex-Inter-Light-sup-ly1.tfm \
tex-Inter-Light-sup-ly1.vf \
tex-Inter-Light-sup-ot1.tfm \
tex-Inter-Light-sup-t1--base.tfm \
tex-Inter-Light-sup-t1.tfm \
tex-Inter-Light-sup-t1.vf \
tex-Inter-Light-tlf-lgr--base.tfm \
tex-Inter-Light-tlf-lgr.tfm \
tex-Inter-Light-tlf-lgr.vf \
tex-Inter-Light-tlf-ly1--base.tfm \
tex-Inter-Light-tlf-ly1.tfm \
tex-Inter-Light-tlf-ly1.vf \
tex-Inter-Light-tlf-oml--base.tfm \
tex-Inter-Light-tlf-oml.tfm \
tex-Inter-Light-tlf-oml.vf \
tex-Inter-Light-tlf-ot1.tfm \
tex-Inter-Light-tlf-sc-lgr--base.tfm \
tex-Inter-Light-tlf-sc-lgr.tfm \
tex-Inter-Light-tlf-sc-lgr.vf \
tex-Inter-Light-tlf-sc-ly1--base.tfm \
tex-Inter-Light-tlf-sc-ly1.tfm \
tex-Inter-Light-tlf-sc-ly1.vf \
tex-Inter-Light-tlf-sc-ot1--base.tfm \
tex-Inter-Light-tlf-sc-ot1.tfm \
tex-Inter-Light-tlf-sc-ot1.vf \
tex-Inter-Light-tlf-sc-t1--base.tfm \
tex-Inter-Light-tlf-sc-t1.tfm \
tex-Inter-Light-tlf-sc-t1.vf \
tex-Inter-Light-tlf-t1--base.tfm \
tex-Inter-Light-tlf-t1.tfm \
tex-Inter-Light-tlf-t1.vf \
tex-Inter-Light-tlf-ts1--base.tfm \
tex-Inter-Light-tlf-ts1.tfm \
tex-Inter-Light-tlf-ts1.vf \
tex-Inter-LightItalic-lf-lgr--base.tfm \
tex-Inter-LightItalic-lf-lgr.tfm \
tex-Inter-LightItalic-lf-lgr.vf \
tex-Inter-LightItalic-lf-ly1--base.tfm \
tex-Inter-LightItalic-lf-ly1.tfm \
tex-Inter-LightItalic-lf-ly1.vf \
tex-Inter-LightItalic-lf-oml--base.tfm \
tex-Inter-LightItalic-lf-oml.tfm \
tex-Inter-LightItalic-lf-oml.vf \
tex-Inter-LightItalic-lf-ot1.tfm \
tex-Inter-LightItalic-lf-sc-lgr--base.tfm \
tex-Inter-LightItalic-lf-sc-lgr.tfm \
tex-Inter-LightItalic-lf-sc-lgr.vf \
tex-Inter-LightItalic-lf-sc-ly1--base.tfm \
tex-Inter-LightItalic-lf-sc-ly1.tfm \
tex-Inter-LightItalic-lf-sc-ly1.vf \
tex-Inter-LightItalic-lf-sc-ot1--base.tfm \
tex-Inter-LightItalic-lf-sc-ot1.tfm \
tex-Inter-LightItalic-lf-sc-ot1.vf \
tex-Inter-LightItalic-lf-sc-t1--base.tfm \
tex-Inter-LightItalic-lf-sc-t1.tfm \
tex-Inter-LightItalic-lf-sc-t1.vf \
tex-Inter-LightItalic-lf-t1--base.tfm \
tex-Inter-LightItalic-lf-t1.tfm \
tex-Inter-LightItalic-lf-t1.vf \
tex-Inter-LightItalic-lf-ts1--base.tfm \
tex-Inter-LightItalic-lf-ts1.tfm \
tex-Inter-LightItalic-lf-ts1.vf \
tex-Inter-LightItalic-sup-lgr--base.tfm \
tex-Inter-LightItalic-sup-lgr.tfm \
tex-Inter-LightItalic-sup-lgr.vf \
tex-Inter-LightItalic-sup-ly1--base.tfm \
tex-Inter-LightItalic-sup-ly1.tfm \
tex-Inter-LightItalic-sup-ly1.vf \
tex-Inter-LightItalic-sup-ot1.tfm \
tex-Inter-LightItalic-sup-t1--base.tfm \
tex-Inter-LightItalic-sup-t1.tfm \
tex-Inter-LightItalic-sup-t1.vf \
tex-Inter-LightItalic-tlf-lgr--base.tfm \
tex-Inter-LightItalic-tlf-lgr.tfm \
tex-Inter-LightItalic-tlf-lgr.vf \
tex-Inter-LightItalic-tlf-ly1--base.tfm \
tex-Inter-LightItalic-tlf-ly1.tfm \
tex-Inter-LightItalic-tlf-ly1.vf \
tex-Inter-LightItalic-tlf-oml--base.tfm \
tex-Inter-LightItalic-tlf-oml.tfm \
tex-Inter-LightItalic-tlf-oml.vf \
tex-Inter-LightItalic-tlf-ot1.tfm \
tex-Inter-LightItalic-tlf-sc-lgr--base.tfm \
tex-Inter-LightItalic-tlf-sc-lgr.tfm \
tex-Inter-LightItalic-tlf-sc-lgr.vf \
tex-Inter-LightItalic-tlf-sc-ly1--base.tfm \
tex-Inter-LightItalic-tlf-sc-ly1.tfm \
tex-Inter-LightItalic-tlf-sc-ly1.vf \
tex-Inter-LightItalic-tlf-sc-ot1--base.tfm \
tex-Inter-LightItalic-tlf-sc-ot1.tfm \
tex-Inter-LightItalic-tlf-sc-ot1.vf \
tex-Inter-LightItalic-tlf-sc-t1--base.tfm \
tex-Inter-LightItalic-tlf-sc-t1.tfm \
tex-Inter-LightItalic-tlf-sc-t1.vf \
tex-Inter-LightItalic-tlf-t1--base.tfm \
tex-Inter-LightItalic-tlf-t1.tfm \
tex-Inter-LightItalic-tlf-t1.vf \
tex-Inter-LightItalic-tlf-ts1--base.tfm \
tex-Inter-LightItalic-tlf-ts1.tfm \
tex-Inter-LightItalic-tlf-ts1.vf \
tex-Inter-Medium-lf-lgr--base.tfm \
tex-Inter-Medium-lf-lgr.tfm \
tex-Inter-Medium-lf-lgr.vf \
tex-Inter-Medium-lf-ly1--base.tfm \
tex-Inter-Medium-lf-ly1.tfm \
tex-Inter-Medium-lf-ly1.vf \
tex-Inter-Medium-lf-oml--base.tfm \
tex-Inter-Medium-lf-oml.tfm \
tex-Inter-Medium-lf-oml.vf \
tex-Inter-Medium-lf-ot1.tfm \
tex-Inter-Medium-lf-sc-lgr--base.tfm \
tex-Inter-Medium-lf-sc-lgr.tfm \
tex-Inter-Medium-lf-sc-lgr.vf \
tex-Inter-Medium-lf-sc-ly1--base.tfm \
tex-Inter-Medium-lf-sc-ly1.tfm \
tex-Inter-Medium-lf-sc-ly1.vf \
tex-Inter-Medium-lf-sc-ot1--base.tfm \
tex-Inter-Medium-lf-sc-ot1.tfm \
tex-Inter-Medium-lf-sc-ot1.vf \
tex-Inter-Medium-lf-sc-t1--base.tfm \
tex-Inter-Medium-lf-sc-t1.tfm \
tex-Inter-Medium-lf-sc-t1.vf \
tex-Inter-Medium-lf-t1--base.tfm \
tex-Inter-Medium-lf-t1.tfm \
tex-Inter-Medium-lf-t1.vf \
tex-Inter-Medium-lf-ts1--base.tfm \
tex-Inter-Medium-lf-ts1.tfm \
tex-Inter-Medium-lf-ts1.vf \
tex-Inter-Medium-sup-lgr--base.tfm \
tex-Inter-Medium-sup-lgr.tfm \
tex-Inter-Medium-sup-lgr.vf \
tex-Inter-Medium-sup-ly1--base.tfm \
tex-Inter-Medium-sup-ly1.tfm \
tex-Inter-Medium-sup-ly1.vf \
tex-Inter-Medium-sup-ot1.tfm \
tex-Inter-Medium-sup-t1--base.tfm \
tex-Inter-Medium-sup-t1.tfm \
tex-Inter-Medium-sup-t1.vf \
tex-Inter-Medium-tlf-lgr--base.tfm \
tex-Inter-Medium-tlf-lgr.tfm \
tex-Inter-Medium-tlf-lgr.vf \
tex-Inter-Medium-tlf-ly1--base.tfm \
tex-Inter-Medium-tlf-ly1.tfm \
tex-Inter-Medium-tlf-ly1.vf \
tex-Inter-Medium-tlf-oml--base.tfm \
tex-Inter-Medium-tlf-oml.tfm \
tex-Inter-Medium-tlf-oml.vf \
tex-Inter-Medium-tlf-ot1.tfm \
tex-Inter-Medium-tlf-sc-lgr--base.tfm \
tex-Inter-Medium-tlf-sc-lgr.tfm \
tex-Inter-Medium-tlf-sc-lgr.vf \
tex-Inter-Medium-tlf-sc-ly1--base.tfm \
tex-Inter-Medium-tlf-sc-ly1.tfm \
tex-Inter-Medium-tlf-sc-ly1.vf \
tex-Inter-Medium-tlf-sc-ot1--base.tfm \
tex-Inter-Medium-tlf-sc-ot1.tfm \
tex-Inter-Medium-tlf-sc-ot1.vf \
tex-Inter-Medium-tlf-sc-t1--base.tfm \
tex-Inter-Medium-tlf-sc-t1.tfm \
tex-Inter-Medium-tlf-sc-t1.vf \
tex-Inter-Medium-tlf-t1--base.tfm \
tex-Inter-Medium-tlf-t1.tfm \
tex-Inter-Medium-tlf-t1.vf \
tex-Inter-Medium-tlf-ts1--base.tfm \
tex-Inter-Medium-tlf-ts1.tfm \
tex-Inter-Medium-tlf-ts1.vf \
tex-Inter-MediumItalic-lf-lgr--base.tfm \
tex-Inter-MediumItalic-lf-lgr.tfm \
tex-Inter-MediumItalic-lf-lgr.vf \
tex-Inter-MediumItalic-lf-ly1--base.tfm \
tex-Inter-MediumItalic-lf-ly1.tfm \
tex-Inter-MediumItalic-lf-ly1.vf \
tex-Inter-MediumItalic-lf-oml--base.tfm \
tex-Inter-MediumItalic-lf-oml.tfm \
tex-Inter-MediumItalic-lf-oml.vf \
tex-Inter-MediumItalic-lf-ot1.tfm \
tex-Inter-MediumItalic-lf-sc-lgr--base.tfm \
tex-Inter-MediumItalic-lf-sc-lgr.tfm \
tex-Inter-MediumItalic-lf-sc-lgr.vf \
tex-Inter-MediumItalic-lf-sc-ly1--base.tfm \
tex-Inter-MediumItalic-lf-sc-ly1.tfm \
tex-Inter-MediumItalic-lf-sc-ly1.vf \
tex-Inter-MediumItalic-lf-sc-ot1--base.tfm \
tex-Inter-MediumItalic-lf-sc-ot1.tfm \
tex-Inter-MediumItalic-lf-sc-ot1.vf \
tex-Inter-MediumItalic-lf-sc-t1--base.tfm \
tex-Inter-MediumItalic-lf-sc-t1.tfm \
tex-Inter-MediumItalic-lf-sc-t1.vf \
tex-Inter-MediumItalic-lf-t1--base.tfm \
tex-Inter-MediumItalic-lf-t1.tfm \
tex-Inter-MediumItalic-lf-t1.vf \
tex-Inter-MediumItalic-lf-ts1--base.tfm \
tex-Inter-MediumItalic-lf-ts1.tfm \
tex-Inter-MediumItalic-lf-ts1.vf \
tex-Inter-MediumItalic-sup-lgr--base.tfm \
tex-Inter-MediumItalic-sup-lgr.tfm \
tex-Inter-MediumItalic-sup-lgr.vf \
tex-Inter-MediumItalic-sup-ly1--base.tfm \
tex-Inter-MediumItalic-sup-ly1.tfm \
tex-Inter-MediumItalic-sup-ly1.vf \
tex-Inter-MediumItalic-sup-ot1.tfm \
tex-Inter-MediumItalic-sup-t1--base.tfm \
tex-Inter-MediumItalic-sup-t1.tfm \
tex-Inter-MediumItalic-sup-t1.vf \
tex-Inter-MediumItalic-tlf-lgr--base.tfm \
tex-Inter-MediumItalic-tlf-lgr.tfm \
tex-Inter-MediumItalic-tlf-lgr.vf \
tex-Inter-MediumItalic-tlf-ly1--base.tfm \
tex-Inter-MediumItalic-tlf-ly1.tfm \
tex-Inter-MediumItalic-tlf-ly1.vf \
tex-Inter-MediumItalic-tlf-oml--base.tfm \
tex-Inter-MediumItalic-tlf-oml.tfm \
tex-Inter-MediumItalic-tlf-oml.vf \
tex-Inter-MediumItalic-tlf-ot1.tfm \
tex-Inter-MediumItalic-tlf-sc-lgr--base.tfm \
tex-Inter-MediumItalic-tlf-sc-lgr.tfm \
tex-Inter-MediumItalic-tlf-sc-lgr.vf \
tex-Inter-MediumItalic-tlf-sc-ly1--base.tfm \
tex-Inter-MediumItalic-tlf-sc-ly1.tfm \
tex-Inter-MediumItalic-tlf-sc-ly1.vf \
tex-Inter-MediumItalic-tlf-sc-ot1--base.tfm \
tex-Inter-MediumItalic-tlf-sc-ot1.tfm \
tex-Inter-MediumItalic-tlf-sc-ot1.vf \
tex-Inter-MediumItalic-tlf-sc-t1--base.tfm \
tex-Inter-MediumItalic-tlf-sc-t1.tfm \
tex-Inter-MediumItalic-tlf-sc-t1.vf \
tex-Inter-MediumItalic-tlf-t1--base.tfm \
tex-Inter-MediumItalic-tlf-t1.tfm \
tex-Inter-MediumItalic-tlf-t1.vf \
tex-Inter-MediumItalic-tlf-ts1--base.tfm \
tex-Inter-MediumItalic-tlf-ts1.tfm \
tex-Inter-MediumItalic-tlf-ts1.vf \
tex-Inter-Regular-lf-lgr--base.tfm \
tex-Inter-Regular-lf-lgr.tfm \
tex-Inter-Regular-lf-lgr.vf \
tex-Inter-Regular-lf-ly1--base.tfm \
tex-Inter-Regular-lf-ly1.tfm \
tex-Inter-Regular-lf-ly1.vf \
tex-Inter-Regular-lf-oml--base.tfm \
tex-Inter-Regular-lf-oml.tfm \
tex-Inter-Regular-lf-oml.vf \
tex-Inter-Regular-lf-ot1.tfm \
tex-Inter-Regular-lf-sc-lgr--base.tfm \
tex-Inter-Regular-lf-sc-lgr.tfm \
tex-Inter-Regular-lf-sc-lgr.vf \
tex-Inter-Regular-lf-sc-ly1--base.tfm \
tex-Inter-Regular-lf-sc-ly1.tfm \
tex-Inter-Regular-lf-sc-ly1.vf \
tex-Inter-Regular-lf-sc-ot1--base.tfm \
tex-Inter-Regular-lf-sc-ot1.tfm \
tex-Inter-Regular-lf-sc-ot1.vf \
tex-Inter-Regular-lf-sc-t1--base.tfm \
tex-Inter-Regular-lf-sc-t1.tfm \
tex-Inter-Regular-lf-sc-t1.vf \
tex-Inter-Regular-lf-t1--base.tfm \
tex-Inter-Regular-lf-t1.tfm \
tex-Inter-Regular-lf-t1.vf \
tex-Inter-Regular-lf-ts1--base.tfm \
tex-Inter-Regular-lf-ts1.tfm \
tex-Inter-Regular-lf-ts1.vf \
tex-Inter-Regular-sup-lgr--base.tfm \
tex-Inter-Regular-sup-lgr.tfm \
tex-Inter-Regular-sup-lgr.vf \
tex-Inter-Regular-sup-ly1--base.tfm \
tex-Inter-Regular-sup-ly1.tfm \
tex-Inter-Regular-sup-ly1.vf \
tex-Inter-Regular-sup-ot1.tfm \
tex-Inter-Regular-sup-t1--base.tfm \
tex-Inter-Regular-sup-t1.tfm \
tex-Inter-Regular-sup-t1.vf \
tex-Inter-Regular-tlf-lgr--base.tfm \
tex-Inter-Regular-tlf-lgr.tfm \
tex-Inter-Regular-tlf-lgr.vf \
tex-Inter-Regular-tlf-ly1--base.tfm \
tex-Inter-Regular-tlf-ly1.tfm \
tex-Inter-Regular-tlf-ly1.vf \
tex-Inter-Regular-tlf-oml--base.tfm \
tex-Inter-Regular-tlf-oml.tfm \
tex-Inter-Regular-tlf-oml.vf \
tex-Inter-Regular-tlf-ot1.tfm \
tex-Inter-Regular-tlf-sc-lgr--base.tfm \
tex-Inter-Regular-tlf-sc-lgr.tfm \
tex-Inter-Regular-tlf-sc-lgr.vf \
tex-Inter-Regular-tlf-sc-ly1--base.tfm \
tex-Inter-Regular-tlf-sc-ly1.tfm \
tex-Inter-Regular-tlf-sc-ly1.vf \
tex-Inter-Regular-tlf-sc-ot1--base.tfm \
tex-Inter-Regular-tlf-sc-ot1.tfm \
tex-Inter-Regular-tlf-sc-ot1.vf \
tex-Inter-Regular-tlf-sc-t1--base.tfm \
tex-Inter-Regular-tlf-sc-t1.tfm \
tex-Inter-Regular-tlf-sc-t1.vf \
tex-Inter-Regular-tlf-t1--base.tfm \
tex-Inter-Regular-tlf-t1.tfm \
tex-Inter-Regular-tlf-t1.vf \
tex-Inter-Regular-tlf-ts1--base.tfm \
tex-Inter-Regular-tlf-ts1.tfm \
tex-Inter-Regular-tlf-ts1.vf \
tex-Inter-SemiBold-lf-lgr--base.tfm \
tex-Inter-SemiBold-lf-lgr.tfm \
tex-Inter-SemiBold-lf-lgr.vf \
tex-Inter-SemiBold-lf-ly1--base.tfm \
tex-Inter-SemiBold-lf-ly1.tfm \
tex-Inter-SemiBold-lf-ly1.vf \
tex-Inter-SemiBold-lf-oml--base.tfm \
tex-Inter-SemiBold-lf-oml.tfm \
tex-Inter-SemiBold-lf-oml.vf \
tex-Inter-SemiBold-lf-ot1.tfm \
tex-Inter-SemiBold-lf-sc-lgr--base.tfm \
tex-Inter-SemiBold-lf-sc-lgr.tfm \
tex-Inter-SemiBold-lf-sc-lgr.vf \
tex-Inter-SemiBold-lf-sc-ly1--base.tfm \
tex-Inter-SemiBold-lf-sc-ly1.tfm \
tex-Inter-SemiBold-lf-sc-ly1.vf \
tex-Inter-SemiBold-lf-sc-ot1--base.tfm \
tex-Inter-SemiBold-lf-sc-ot1.tfm \
tex-Inter-SemiBold-lf-sc-ot1.vf \
tex-Inter-SemiBold-lf-sc-t1--base.tfm \
tex-Inter-SemiBold-lf-sc-t1.tfm \
tex-Inter-SemiBold-lf-sc-t1.vf \
tex-Inter-SemiBold-lf-t1--base.tfm \
tex-Inter-SemiBold-lf-t1.tfm \
tex-Inter-SemiBold-lf-t1.vf \
tex-Inter-SemiBold-lf-ts1--base.tfm \
tex-Inter-SemiBold-lf-ts1.tfm \
tex-Inter-SemiBold-lf-ts1.vf \
tex-Inter-SemiBold-sup-lgr--base.tfm \
tex-Inter-SemiBold-sup-lgr.tfm \
tex-Inter-SemiBold-sup-lgr.vf \
tex-Inter-SemiBold-sup-ly1--base.tfm \
tex-Inter-SemiBold-sup-ly1.tfm \
tex-Inter-SemiBold-sup-ly1.vf \
tex-Inter-SemiBold-sup-ot1.tfm \
tex-Inter-SemiBold-sup-t1--base.tfm \
tex-Inter-SemiBold-sup-t1.tfm \
tex-Inter-SemiBold-sup-t1.vf \
tex-Inter-SemiBold-tlf-lgr--base.tfm \
tex-Inter-SemiBold-tlf-lgr.tfm \
tex-Inter-SemiBold-tlf-lgr.vf \
tex-Inter-SemiBold-tlf-ly1--base.tfm \
tex-Inter-SemiBold-tlf-ly1.tfm \
tex-Inter-SemiBold-tlf-ly1.vf \
tex-Inter-SemiBold-tlf-oml--base.tfm \
tex-Inter-SemiBold-tlf-oml.tfm \
tex-Inter-SemiBold-tlf-oml.vf \
tex-Inter-SemiBold-tlf-ot1.tfm \
tex-Inter-SemiBold-tlf-sc-lgr--base.tfm \
tex-Inter-SemiBold-tlf-sc-lgr.tfm \
tex-Inter-SemiBold-tlf-sc-lgr.vf \
tex-Inter-SemiBold-tlf-sc-ly1--base.tfm \
tex-Inter-SemiBold-tlf-sc-ly1.tfm \
tex-Inter-SemiBold-tlf-sc-ly1.vf \
tex-Inter-SemiBold-tlf-sc-ot1--base.tfm \
tex-Inter-SemiBold-tlf-sc-ot1.tfm \
tex-Inter-SemiBold-tlf-sc-ot1.vf \
tex-Inter-SemiBold-tlf-sc-t1--base.tfm \
tex-Inter-SemiBold-tlf-sc-t1.tfm \
tex-Inter-SemiBold-tlf-sc-t1.vf \
tex-Inter-SemiBold-tlf-t1--base.tfm \
tex-Inter-SemiBold-tlf-t1.tfm \
tex-Inter-SemiBold-tlf-t1.vf \
tex-Inter-SemiBold-tlf-ts1--base.tfm \
tex-Inter-SemiBold-tlf-ts1.tfm \
tex-Inter-SemiBold-tlf-ts1.vf \
tex-Inter-SemiBoldItalic-lf-lgr--base.tfm \
tex-Inter-SemiBoldItalic-lf-lgr.tfm \
tex-Inter-SemiBoldItalic-lf-lgr.vf \
tex-Inter-SemiBoldItalic-lf-ly1--base.tfm \
tex-Inter-SemiBoldItalic-lf-ly1.tfm \
tex-Inter-SemiBoldItalic-lf-ly1.vf \
tex-Inter-SemiBoldItalic-lf-oml--base.tfm \
tex-Inter-SemiBoldItalic-lf-oml.tfm \
tex-Inter-SemiBoldItalic-lf-oml.vf \
tex-Inter-SemiBoldItalic-lf-ot1.tfm \
tex-Inter-SemiBoldItalic-lf-sc-lgr--base.tfm \
tex-Inter-SemiBoldItalic-lf-sc-lgr.tfm \
tex-Inter-SemiBoldItalic-lf-sc-lgr.vf \
tex-Inter-SemiBoldItalic-lf-sc-ly1--base.tfm \
tex-Inter-SemiBoldItalic-lf-sc-ly1.tfm \
tex-Inter-SemiBoldItalic-lf-sc-ly1.vf \
tex-Inter-SemiBoldItalic-lf-sc-ot1--base.tfm \
tex-Inter-SemiBoldItalic-lf-sc-ot1.tfm \
tex-Inter-SemiBoldItalic-lf-sc-ot1.vf \
tex-Inter-SemiBoldItalic-lf-sc-t1--base.tfm \
tex-Inter-SemiBoldItalic-lf-sc-t1.tfm \
tex-Inter-SemiBoldItalic-lf-sc-t1.vf \
tex-Inter-SemiBoldItalic-lf-t1--base.tfm \
tex-Inter-SemiBoldItalic-lf-t1.tfm \
tex-Inter-SemiBoldItalic-lf-t1.vf \
tex-Inter-SemiBoldItalic-lf-ts1--base.tfm \
tex-Inter-SemiBoldItalic-lf-ts1.tfm \
tex-Inter-SemiBoldItalic-lf-ts1.vf \
tex-Inter-SemiBoldItalic-sup-lgr--base.tfm \
tex-Inter-SemiBoldItalic-sup-lgr.tfm \
tex-Inter-SemiBoldItalic-sup-lgr.vf \
tex-Inter-SemiBoldItalic-sup-ly1--base.tfm \
tex-Inter-SemiBoldItalic-sup-ly1.tfm \
tex-Inter-SemiBoldItalic-sup-ly1.vf \
tex-Inter-SemiBoldItalic-sup-ot1.tfm \
tex-Inter-SemiBoldItalic-sup-t1--base.tfm \
tex-Inter-SemiBoldItalic-sup-t1.tfm \
tex-Inter-SemiBoldItalic-sup-t1.vf \
tex-Inter-SemiBoldItalic-tlf-lgr--base.tfm \
tex-Inter-SemiBoldItalic-tlf-lgr.tfm \
tex-Inter-SemiBoldItalic-tlf-lgr.vf \
tex-Inter-SemiBoldItalic-tlf-ly1--base.tfm \
tex-Inter-SemiBoldItalic-tlf-ly1.tfm \
tex-Inter-SemiBoldItalic-tlf-ly1.vf \
tex-Inter-SemiBoldItalic-tlf-oml--base.tfm \
tex-Inter-SemiBoldItalic-tlf-oml.tfm \
tex-Inter-SemiBoldItalic-tlf-oml.vf \
tex-Inter-SemiBoldItalic-tlf-ot1.tfm \
tex-Inter-SemiBoldItalic-tlf-sc-lgr--base.tfm \
tex-Inter-SemiBoldItalic-tlf-sc-lgr.tfm \
tex-Inter-SemiBoldItalic-tlf-sc-lgr.vf \
tex-Inter-SemiBoldItalic-tlf-sc-ly1--base.tfm \
tex-Inter-SemiBoldItalic-tlf-sc-ly1.tfm \
tex-Inter-SemiBoldItalic-tlf-sc-ly1.vf \
tex-Inter-SemiBoldItalic-tlf-sc-ot1--base.tfm \
tex-Inter-SemiBoldItalic-tlf-sc-ot1.tfm \
tex-Inter-SemiBoldItalic-tlf-sc-ot1.vf \
tex-Inter-SemiBoldItalic-tlf-sc-t1--base.tfm \
tex-Inter-SemiBoldItalic-tlf-sc-t1.tfm \
tex-Inter-SemiBoldItalic-tlf-sc-t1.vf \
tex-Inter-SemiBoldItalic-tlf-t1--base.tfm \
tex-Inter-SemiBoldItalic-tlf-t1.tfm \
tex-Inter-SemiBoldItalic-tlf-t1.vf \
tex-Inter-SemiBoldItalic-tlf-ts1--base.tfm \
tex-Inter-SemiBoldItalic-tlf-ts1.tfm \
tex-Inter-SemiBoldItalic-tlf-ts1.vf \
tex-Inter-Thin-lf-lgr--base.tfm \
tex-Inter-Thin-lf-lgr.tfm \
tex-Inter-Thin-lf-lgr.vf \
tex-Inter-Thin-lf-ly1--base.tfm \
tex-Inter-Thin-lf-ly1.tfm \
tex-Inter-Thin-lf-ly1.vf \
tex-Inter-Thin-lf-oml--base.tfm \
tex-Inter-Thin-lf-oml.tfm \
tex-Inter-Thin-lf-oml.vf \
tex-Inter-Thin-lf-ot1.tfm \
tex-Inter-Thin-lf-sc-lgr--base.tfm \
tex-Inter-Thin-lf-sc-lgr.tfm \
tex-Inter-Thin-lf-sc-lgr.vf \
tex-Inter-Thin-lf-sc-ly1--base.tfm \
tex-Inter-Thin-lf-sc-ly1.tfm \
tex-Inter-Thin-lf-sc-ly1.vf \
tex-Inter-Thin-lf-sc-ot1--base.tfm \
tex-Inter-Thin-lf-sc-ot1.tfm \
tex-Inter-Thin-lf-sc-ot1.vf \
tex-Inter-Thin-lf-sc-t1--base.tfm \
tex-Inter-Thin-lf-sc-t1.tfm \
tex-Inter-Thin-lf-sc-t1.vf \
tex-Inter-Thin-lf-t1--base.tfm \
tex-Inter-Thin-lf-t1.tfm \
tex-Inter-Thin-lf-t1.vf \
tex-Inter-Thin-lf-ts1--base.tfm \
tex-Inter-Thin-lf-ts1.tfm \
tex-Inter-Thin-lf-ts1.vf \
tex-Inter-Thin-sup-lgr--base.tfm \
tex-Inter-Thin-sup-lgr.tfm \
tex-Inter-Thin-sup-lgr.vf \
tex-Inter-Thin-sup-ly1--base.tfm \
tex-Inter-Thin-sup-ly1.tfm \
tex-Inter-Thin-sup-ly1.vf \
tex-Inter-Thin-sup-ot1.tfm \
tex-Inter-Thin-sup-t1--base.tfm \
tex-Inter-Thin-sup-t1.tfm \
tex-Inter-Thin-sup-t1.vf \
tex-Inter-Thin-tlf-lgr--base.tfm \
tex-Inter-Thin-tlf-lgr.tfm \
tex-Inter-Thin-tlf-lgr.vf \
tex-Inter-Thin-tlf-ly1--base.tfm \
tex-Inter-Thin-tlf-ly1.tfm \
tex-Inter-Thin-tlf-ly1.vf \
tex-Inter-Thin-tlf-oml--base.tfm \
tex-Inter-Thin-tlf-oml.tfm \
tex-Inter-Thin-tlf-oml.vf \
tex-Inter-Thin-tlf-ot1.tfm \
tex-Inter-Thin-tlf-sc-lgr--base.tfm \
tex-Inter-Thin-tlf-sc-lgr.tfm \
tex-Inter-Thin-tlf-sc-lgr.vf \
tex-Inter-Thin-tlf-sc-ly1--base.tfm \
tex-Inter-Thin-tlf-sc-ly1.tfm \
tex-Inter-Thin-tlf-sc-ly1.vf \
tex-Inter-Thin-tlf-sc-ot1--base.tfm \
tex-Inter-Thin-tlf-sc-ot1.tfm \
tex-Inter-Thin-tlf-sc-ot1.vf \
tex-Inter-Thin-tlf-sc-t1--base.tfm \
tex-Inter-Thin-tlf-sc-t1.tfm \
tex-Inter-Thin-tlf-sc-t1.vf \
tex-Inter-Thin-tlf-t1--base.tfm \
tex-Inter-Thin-tlf-t1.tfm \
tex-Inter-Thin-tlf-t1.vf \
tex-Inter-Thin-tlf-ts1--base.tfm \
tex-Inter-Thin-tlf-ts1.tfm \
tex-Inter-Thin-tlf-ts1.vf \
tex-Inter-ThinItalic-lf-lgr--base.tfm \
tex-Inter-ThinItalic-lf-lgr.tfm \
tex-Inter-ThinItalic-lf-lgr.vf \
tex-Inter-ThinItalic-lf-ly1--base.tfm \
tex-Inter-ThinItalic-lf-ly1.tfm \
tex-Inter-ThinItalic-lf-ly1.vf \
tex-Inter-ThinItalic-lf-oml--base.tfm \
tex-Inter-ThinItalic-lf-oml.tfm \
tex-Inter-ThinItalic-lf-oml.vf \
tex-Inter-ThinItalic-lf-ot1.tfm \
tex-Inter-ThinItalic-lf-sc-lgr--base.tfm \
tex-Inter-ThinItalic-lf-sc-lgr.tfm \
tex-Inter-ThinItalic-lf-sc-lgr.vf \
tex-Inter-ThinItalic-lf-sc-ly1--base.tfm \
tex-Inter-ThinItalic-lf-sc-ly1.tfm \
tex-Inter-ThinItalic-lf-sc-ly1.vf \
tex-Inter-ThinItalic-lf-sc-ot1--base.tfm \
tex-Inter-ThinItalic-lf-sc-ot1.tfm \
tex-Inter-ThinItalic-lf-sc-ot1.vf \
tex-Inter-ThinItalic-lf-sc-t1--base.tfm \
tex-Inter-ThinItalic-lf-sc-t1.tfm \
tex-Inter-ThinItalic-lf-sc-t1.vf \
tex-Inter-ThinItalic-lf-t1--base.tfm \
tex-Inter-ThinItalic-lf-t1.tfm \
tex-Inter-ThinItalic-lf-t1.vf \
tex-Inter-ThinItalic-lf-ts1--base.tfm \
tex-Inter-ThinItalic-lf-ts1.tfm \
tex-Inter-ThinItalic-lf-ts1.vf \
tex-Inter-ThinItalic-sup-lgr--base.tfm \
tex-Inter-ThinItalic-sup-lgr.tfm \
tex-Inter-ThinItalic-sup-lgr.vf \
tex-Inter-ThinItalic-sup-ly1--base.tfm \
tex-Inter-ThinItalic-sup-ly1.tfm \
tex-Inter-ThinItalic-sup-ly1.vf \
tex-Inter-ThinItalic-sup-ot1.tfm \
tex-Inter-ThinItalic-sup-t1--base.tfm \
tex-Inter-ThinItalic-sup-t1.tfm \
tex-Inter-ThinItalic-sup-t1.vf \
tex-Inter-ThinItalic-tlf-lgr--base.tfm \
tex-Inter-ThinItalic-tlf-lgr.tfm \
tex-Inter-ThinItalic-tlf-lgr.vf \
tex-Inter-ThinItalic-tlf-ly1--base.tfm \
tex-Inter-ThinItalic-tlf-ly1.tfm \
tex-Inter-ThinItalic-tlf-ly1.vf \
tex-Inter-ThinItalic-tlf-oml--base.tfm \
tex-Inter-ThinItalic-tlf-oml.tfm \
tex-Inter-ThinItalic-tlf-oml.vf \
tex-Inter-ThinItalic-tlf-ot1.tfm \
tex-Inter-ThinItalic-tlf-sc-lgr--base.tfm \
tex-Inter-ThinItalic-tlf-sc-lgr.tfm \
tex-Inter-ThinItalic-tlf-sc-lgr.vf \
tex-Inter-ThinItalic-tlf-sc-ly1--base.tfm \
tex-Inter-ThinItalic-tlf-sc-ly1.tfm \
tex-Inter-ThinItalic-tlf-sc-ly1.vf \
tex-Inter-ThinItalic-tlf-sc-ot1--base.tfm \
tex-Inter-ThinItalic-tlf-sc-ot1.tfm \
tex-Inter-ThinItalic-tlf-sc-ot1.vf \
tex-Inter-ThinItalic-tlf-sc-t1--base.tfm \
tex-Inter-ThinItalic-tlf-sc-t1.tfm \
tex-Inter-ThinItalic-tlf-sc-t1.vf \
tex-Inter-ThinItalic-tlf-t1--base.tfm \
tex-Inter-ThinItalic-tlf-t1.tfm \
tex-Inter-ThinItalic-tlf-t1.vf \
tex-Inter-ThinItalic-tlf-ts1--base.tfm \
tex-Inter-ThinItalic-tlf-ts1.tfm \
tex-Inter-ThinItalic-tlf-ts1.vf \
tex-Inter.map \
tex-LGRInter-LF.fd \
tex-LGRInter-Sup.fd \
tex-LGRInter-TLF.fd \
tex-LY1Inter-LF.fd \
tex-LY1Inter-Sup.fd \
tex-LY1Inter-TLF.fd \
tex-OMLInter-LF.fd \
tex-OMLInter-TLF.fd \
tex-OT1Inter-LF.fd \
tex-OT1Inter-Sup.fd \
tex-OT1Inter-TLF.fd \
tex-T1Inter-LF.fd \
tex-T1Inter-Sup.fd \
tex-T1Inter-TLF.fd \
tex-TS1Inter-LF.fd \
tex-TS1Inter-TLF.fd \
tex-a-3kvjgf.enc \
tex-a-3xzi2q.enc \
tex-a-4e7xpp.enc \
tex-a-5l7ypa.enc \
tex-a-6ftb5e.enc \
tex-a-6zlbe6.enc \
tex-a-cq4y6g.enc \
tex-a-djwlf6.enc \
tex-a-dvm45n.enc \
tex-a-eou476.enc \
tex-a-he2k6v.enc \
tex-a-i4h3jj.enc \
tex-a-iuq67p.enc \
tex-a-lmnsa6.enc \
tex-a-odfdzw.enc \
tex-a-pkfct2.enc \
tex-a-qkv7gm.enc \
tex-a-wjmlun.enc \
tex-a-xl7blu.enc \
tex-a-y3ib6m.enc \
tex-a-ykuvzx.enc \
tex-a-yrfexf.enc \
tex-inter.sty \
texlive-inter"

RDEPENDS:${PN} += "/usr/bin/sh \
coreutils \
ed \
findutils \
grep \
sed \
tex-fontaxes.sty \
tex-fontenc.sty \
tex-fontspec.sty \
tex-ifluatex.sty \
tex-ifthen.sty \
tex-ifxetex.sty \
tex-mweights.sty \
tex-textcomp.sty \
tex-updmap.cfg \
tex-xkeyval.sty \
texlive \
texlive-filesystem \
texlive-inter-fonts \
texlive-kpathsea \
texlive-kpathsea-bin \
texlive-scripts \
texlive-scripts-bin"

inherit rpm
