SUMMARY = "Severed fonts for texlive-plex"
DESCRIPTION = "The  separated fonts package for texlive-plex"
LICENSE = "OFL-1.1"

PV = "2026.226.svn77682"

RPM_NAME = "texlive-plex-fonts-2026.226.svn77682-59.2.noarch.rpm"
RPM_HASH = "6256198bbb5a3f43049e180c1a9f14d3594cd65e0e93878194c2edbb9e08b20a29cb76fb58f3ee2d9f8b94da77b28e5571a568556cb5773323af70c802da3e84"
REPO_ARCH = "noarch"

RPROVIDES:${PN} += "config-texlive-plex-fonts \
font--lang=aa \
font--lang=ab \
font--lang=af \
font--lang=agr \
font--lang=an \
font--lang=ast \
font--lang=av \
font--lang=ay \
font--lang=ayc \
font--lang=az-az \
font--lang=ba \
font--lang=be \
font--lang=bem \
font--lang=bg \
font--lang=bi \
font--lang=bin \
font--lang=br \
font--lang=bs \
font--lang=bua \
font--lang=ca \
font--lang=ce \
font--lang=ch \
font--lang=chm \
font--lang=co \
font--lang=crh \
font--lang=cs \
font--lang=csb \
font--lang=cv \
font--lang=cy \
font--lang=da \
font--lang=de \
font--lang=dsb \
font--lang=el \
font--lang=en \
font--lang=eo \
font--lang=es \
font--lang=et \
font--lang=eu \
font--lang=fi \
font--lang=fil \
font--lang=fj \
font--lang=fo \
font--lang=fr \
font--lang=fur \
font--lang=fy \
font--lang=ga \
font--lang=gd \
font--lang=gl \
font--lang=gn \
font--lang=gv \
font--lang=haw \
font--lang=ho \
font--lang=hr \
font--lang=hsb \
font--lang=ht \
font--lang=hu \
font--lang=hz \
font--lang=ia \
font--lang=id \
font--lang=ie \
font--lang=ig \
font--lang=ik \
font--lang=io \
font--lang=is \
font--lang=it \
font--lang=jv \
font--lang=kaa \
font--lang=ki \
font--lang=kj \
font--lang=kk \
font--lang=kl \
font--lang=ku-tr \
font--lang=kum \
font--lang=kv \
font--lang=kwm \
font--lang=ky \
font--lang=la \
font--lang=lb \
font--lang=lez \
font--lang=lg \
font--lang=li \
font--lang=lij \
font--lang=lt \
font--lang=lv \
font--lang=mfe \
font--lang=mg \
font--lang=mh \
font--lang=mhr \
font--lang=mi \
font--lang=miq \
font--lang=mjw \
font--lang=mk \
font--lang=mn-mn \
font--lang=mo \
font--lang=ms \
font--lang=mt \
font--lang=na \
font--lang=nb \
font--lang=nds \
font--lang=ng \
font--lang=nhn \
font--lang=niu \
font--lang=nl \
font--lang=nn \
font--lang=no \
font--lang=nr \
font--lang=nso \
font--lang=ny \
font--lang=oc \
font--lang=om \
font--lang=os \
font--lang=pap-an \
font--lang=pap-aw \
font--lang=pl \
font--lang=pt \
font--lang=qu \
font--lang=quz \
font--lang=rm \
font--lang=rn \
font--lang=ro \
font--lang=ru \
font--lang=rw \
font--lang=sah \
font--lang=sc \
font--lang=se \
font--lang=sel \
font--lang=sg \
font--lang=sgs \
font--lang=sh \
font--lang=shs \
font--lang=sk \
font--lang=sl \
font--lang=sm \
font--lang=sma \
font--lang=smj \
font--lang=smn \
font--lang=sn \
font--lang=so \
font--lang=sq \
font--lang=sr \
font--lang=ss \
font--lang=st \
font--lang=su \
font--lang=sv \
font--lang=sw \
font--lang=szl \
font--lang=tg \
font--lang=tk \
font--lang=tl \
font--lang=tn \
font--lang=to \
font--lang=tpi \
font--lang=tr \
font--lang=ts \
font--lang=tt \
font--lang=ty \
font--lang=tyv \
font--lang=uk \
font--lang=und-zmth \
font--lang=unm \
font--lang=uz \
font--lang=ve \
font--lang=vi \
font--lang=vo \
font--lang=vot \
font--lang=wa \
font--lang=wae \
font--lang=wen \
font--lang=wo \
font--lang=xh \
font--lang=yap \
font--lang=yuw \
font--lang=za \
font--lang=zu \
font-ibmplexmath \
font-ibmplexmono \
font-ibmplexmonoextlt \
font-ibmplexmonolight \
font-ibmplexmonomedm \
font-ibmplexmonosmbld \
font-ibmplexmonotext \
font-ibmplexmonothin \
font-ibmplexsans \
font-ibmplexsanscond \
font-ibmplexsanscondensed \
font-ibmplexsanscondextlt \
font-ibmplexsanscondlight \
font-ibmplexsanscondmedm \
font-ibmplexsanscondsmbld \
font-ibmplexsanscondtext \
font-ibmplexsanscondthin \
font-ibmplexsansextlt \
font-ibmplexsanslight \
font-ibmplexsansmedm \
font-ibmplexsanssmbld \
font-ibmplexsanstext \
font-ibmplexsansthin \
font-ibmplexserif \
font-ibmplexserifextlt \
font-ibmplexseriflight \
font-ibmplexserifmedm \
font-ibmplexserifsmbld \
font-ibmplexseriftext \
font-ibmplexserifthin \
font-plxmono \
font-plxsans \
font-plxsanscondensed \
font-plxserif \
texlive-plex-fonts"

RDEPENDS:${PN} += "/usr/bin/sh \
aaa-base \
coreutils \
fontconfig \
ghostscript-fonts-std \
perl"

inherit rpm
