SUMMARY = "Tailscale applet for the COSMIC Desktop"
DESCRIPTION = "This is a COSMIC applet for Tailscale. It has SSH and Allow Routes \
enable/disable and Tail Drop functionality."
LICENSE = "BSD-3-Clause"

PV = "3.10.2"

RPM_NAME = "cosmic-ext-applet-tailscale-3.10.2-1.2.aarch64.rpm"
RPM_HASH = "377a77b06930fddce9175d2eed1757dc19606ef7c951faadcb8075630a3b72833ec071a8bdf9739dd0087f9caf8e53df34fe127c8c9a2078fd7e8a54e1877611"

RPROVIDES:${PN} += "bundled-rust-crate-ab-glyph \
bundled-rust-crate-ab-glyph-rasterizer \
bundled-rust-crate-accesskit \
bundled-rust-crate-accesskit-atspi-common \
bundled-rust-crate-accesskit-consumer \
bundled-rust-crate-accesskit-unix \
bundled-rust-crate-accesskit-winit \
bundled-rust-crate-adler2 \
bundled-rust-crate-ahash \
bundled-rust-crate-aho-corasick \
bundled-rust-crate-aliasable \
bundled-rust-crate-allocator-api2 \
bundled-rust-crate-almost \
bundled-rust-crate-anyhow \
bundled-rust-crate-apply \
bundled-rust-crate-approx \
bundled-rust-crate-arc-swap \
bundled-rust-crate-arrayref \
bundled-rust-crate-arrayvec \
bundled-rust-crate-as-raw-xcb-connection \
bundled-rust-crate-ash \
bundled-rust-crate-ashpd \
bundled-rust-crate-async-broadcast \
bundled-rust-crate-async-channel \
bundled-rust-crate-async-executor \
bundled-rust-crate-async-io \
bundled-rust-crate-async-lock \
bundled-rust-crate-async-process \
bundled-rust-crate-async-recursion \
bundled-rust-crate-async-signal \
bundled-rust-crate-async-task \
bundled-rust-crate-async-trait \
bundled-rust-crate-atomic-waker \
bundled-rust-crate-atomicwrites \
bundled-rust-crate-atspi \
bundled-rust-crate-atspi-common \
bundled-rust-crate-atspi-proxies \
bundled-rust-crate-auto-enums \
bundled-rust-crate-autocfg \
bundled-rust-crate-base64 \
bundled-rust-crate-basic-toml \
bundled-rust-crate-bit-set \
bundled-rust-crate-bit-vec \
bundled-rust-crate-bitflags \
bundled-rust-crate-block-buffer \
bundled-rust-crate-block2 \
bundled-rust-crate-blocking \
bundled-rust-crate-borsh \
bundled-rust-crate-bs58 \
bundled-rust-crate-bstr \
bundled-rust-crate-btoi \
bundled-rust-crate-by-address \
bundled-rust-crate-bytemuck \
bundled-rust-crate-bytemuck-derive \
bundled-rust-crate-byteorder-lite \
bundled-rust-crate-bytes \
bundled-rust-crate-calloop \
bundled-rust-crate-calloop-wayland-source \
bundled-rust-crate-cc \
bundled-rust-crate-cfg-aliases \
bundled-rust-crate-cfg-if \
bundled-rust-crate-chrono \
bundled-rust-crate-clipboard-wayland \
bundled-rust-crate-clipboard-x11 \
bundled-rust-crate-codespan-reporting \
bundled-rust-crate-color-quant \
bundled-rust-crate-concurrent-queue \
bundled-rust-crate-configparser \
bundled-rust-crate-core-maths \
bundled-rust-crate-cosmic-client-toolkit \
bundled-rust-crate-cosmic-config \
bundled-rust-crate-cosmic-config-derive \
bundled-rust-crate-cosmic-freedesktop-icons \
bundled-rust-crate-cosmic-panel-config \
bundled-rust-crate-cosmic-protocols \
bundled-rust-crate-cosmic-settings-config \
bundled-rust-crate-cosmic-settings-daemon \
bundled-rust-crate-cosmic-text \
bundled-rust-crate-cosmic-theme \
bundled-rust-crate-cpufeatures \
bundled-rust-crate-crc32fast \
bundled-rust-crate-crossbeam-utils \
bundled-rust-crate-cryoglyph \
bundled-rust-crate-crypto-common \
bundled-rust-crate-css-color \
bundled-rust-crate-csscolorparser \
bundled-rust-crate-ctor \
bundled-rust-crate-cursor-icon \
bundled-rust-crate-darling \
bundled-rust-crate-darling-core \
bundled-rust-crate-darling-macro \
bundled-rust-crate-data-url \
bundled-rust-crate-deranged \
bundled-rust-crate-derive-setters \
bundled-rust-crate-derive-utils \
bundled-rust-crate-digest \
bundled-rust-crate-dirs \
bundled-rust-crate-dirs-sys \
bundled-rust-crate-dispatch2 \
bundled-rust-crate-displaydoc \
bundled-rust-crate-dlib \
bundled-rust-crate-dnd \
bundled-rust-crate-document-features \
bundled-rust-crate-downcast-rs \
bundled-rust-crate-dpi \
bundled-rust-crate-drm \
bundled-rust-crate-drm-ffi \
bundled-rust-crate-drm-fourcc \
bundled-rust-crate-drm-sys \
bundled-rust-crate-dtor \
bundled-rust-crate-dyn-clone \
bundled-rust-crate-endi \
bundled-rust-crate-enumflags2 \
bundled-rust-crate-enumflags2-derive \
bundled-rust-crate-equivalent \
bundled-rust-crate-errno \
bundled-rust-crate-etagere \
bundled-rust-crate-euclid \
bundled-rust-crate-event-listener \
bundled-rust-crate-event-listener-strategy \
bundled-rust-crate-fast-srgb8 \
bundled-rust-crate-fastrand \
bundled-rust-crate-fdeflate \
bundled-rust-crate-find-crate \
bundled-rust-crate-find-msvc-tools \
bundled-rust-crate-flate2 \
bundled-rust-crate-float-cmp \
bundled-rust-crate-float-next-after \
bundled-rust-crate-fluent \
bundled-rust-crate-fluent-bundle \
bundled-rust-crate-fluent-langneg \
bundled-rust-crate-fluent-syntax \
bundled-rust-crate-fnv \
bundled-rust-crate-foldhash \
bundled-rust-crate-font-types \
bundled-rust-crate-fontconfig-parser \
bundled-rust-crate-fontdb \
bundled-rust-crate-form-urlencoded \
bundled-rust-crate-freedesktop-desktop-entry \
bundled-rust-crate-futures \
bundled-rust-crate-futures-channel \
bundled-rust-crate-futures-core \
bundled-rust-crate-futures-executor \
bundled-rust-crate-futures-io \
bundled-rust-crate-futures-lite \
bundled-rust-crate-futures-macro \
bundled-rust-crate-futures-sink \
bundled-rust-crate-futures-task \
bundled-rust-crate-futures-util \
bundled-rust-crate-generic-array \
bundled-rust-crate-gethostname \
bundled-rust-crate-getrandom \
bundled-rust-crate-gettext-rs \
bundled-rust-crate-gettext-sys \
bundled-rust-crate-gif \
bundled-rust-crate-glam \
bundled-rust-crate-glow \
bundled-rust-crate-gpu-allocator \
bundled-rust-crate-gpu-descriptor \
bundled-rust-crate-gpu-descriptor-types \
bundled-rust-crate-grid \
bundled-rust-crate-gui-scale-applet \
bundled-rust-crate-guillotiere \
bundled-rust-crate-half \
bundled-rust-crate-harfrust \
bundled-rust-crate-hashbrown \
bundled-rust-crate-heck \
bundled-rust-crate-hex \
bundled-rust-crate-hexf-parse \
bundled-rust-crate-http \
bundled-rust-crate-http-body \
bundled-rust-crate-http-body-util \
bundled-rust-crate-httparse \
bundled-rust-crate-hyper \
bundled-rust-crate-hyper-util \
bundled-rust-crate-i18n-config \
bundled-rust-crate-i18n-embed \
bundled-rust-crate-i18n-embed-fl \
bundled-rust-crate-i18n-embed-impl \
bundled-rust-crate-iana-time-zone \
bundled-rust-crate-iced \
bundled-rust-crate-iced-accessibility \
bundled-rust-crate-iced-core \
bundled-rust-crate-iced-debug \
bundled-rust-crate-iced-futures \
bundled-rust-crate-iced-graphics \
bundled-rust-crate-iced-program \
bundled-rust-crate-iced-renderer \
bundled-rust-crate-iced-runtime \
bundled-rust-crate-iced-tiny-skia \
bundled-rust-crate-iced-wgpu \
bundled-rust-crate-iced-widget \
bundled-rust-crate-iced-winit \
bundled-rust-crate-icu-collections \
bundled-rust-crate-icu-locale-core \
bundled-rust-crate-icu-normalizer \
bundled-rust-crate-icu-normalizer-data \
bundled-rust-crate-icu-properties \
bundled-rust-crate-icu-properties-data \
bundled-rust-crate-icu-provider \
bundled-rust-crate-ident-case \
bundled-rust-crate-idna \
bundled-rust-crate-idna-adapter \
bundled-rust-crate-image \
bundled-rust-crate-image-extras \
bundled-rust-crate-image-webp \
bundled-rust-crate-imagesize \
bundled-rust-crate-indexmap \
bundled-rust-crate-inotify \
bundled-rust-crate-inotify-sys \
bundled-rust-crate-intl-memoizer \
bundled-rust-crate-intl-pluralrules \
bundled-rust-crate-itoa \
bundled-rust-crate-jiff \
bundled-rust-crate-jiff-static \
bundled-rust-crate-jobserver \
bundled-rust-crate-kamadak-exif \
bundled-rust-crate-keyboard-types \
bundled-rust-crate-khronos-egl \
bundled-rust-crate-kurbo \
bundled-rust-crate-lazy-static \
bundled-rust-crate-libc \
bundled-rust-crate-libcosmic \
bundled-rust-crate-libloading \
bundled-rust-crate-libm \
bundled-rust-crate-lilt \
bundled-rust-crate-linebender-resource-handle \
bundled-rust-crate-linux-raw-sys \
bundled-rust-crate-litemap \
bundled-rust-crate-litrs \
bundled-rust-crate-locale-config \
bundled-rust-crate-lock-api \
bundled-rust-crate-log \
bundled-rust-crate-lru \
bundled-rust-crate-lyon \
bundled-rust-crate-lyon-algorithms \
bundled-rust-crate-lyon-geom \
bundled-rust-crate-lyon-path \
bundled-rust-crate-lyon-tessellation \
bundled-rust-crate-memchr \
bundled-rust-crate-memmap2 \
bundled-rust-crate-mime \
bundled-rust-crate-miniz-oxide \
bundled-rust-crate-mio \
bundled-rust-crate-moxcms \
bundled-rust-crate-mutate-once \
bundled-rust-crate-naga \
bundled-rust-crate-notify \
bundled-rust-crate-notify-rust \
bundled-rust-crate-notify-types \
bundled-rust-crate-num-conv \
bundled-rust-crate-num-traits \
bundled-rust-crate-objc2 \
bundled-rust-crate-objc2-core-foundation \
bundled-rust-crate-objc2-encode \
bundled-rust-crate-once-cell \
bundled-rust-crate-option-ext \
bundled-rust-crate-ordered-float \
bundled-rust-crate-ordered-stream \
bundled-rust-crate-ouroboros \
bundled-rust-crate-ouroboros-macro \
bundled-rust-crate-owned-ttf-parser \
bundled-rust-crate-palette \
bundled-rust-crate-palette-derive \
bundled-rust-crate-parking \
bundled-rust-crate-parking-lot \
bundled-rust-crate-parking-lot-core \
bundled-rust-crate-percent-encoding \
bundled-rust-crate-phf \
bundled-rust-crate-phf-generator \
bundled-rust-crate-phf-macros \
bundled-rust-crate-phf-shared \
bundled-rust-crate-pico-args \
bundled-rust-crate-pin-project-lite \
bundled-rust-crate-piper \
bundled-rust-crate-pkg-config \
bundled-rust-crate-png \
bundled-rust-crate-polling \
bundled-rust-crate-pollster \
bundled-rust-crate-potential-utf \
bundled-rust-crate-powerfmt \
bundled-rust-crate-ppv-lite86 \
bundled-rust-crate-presser \
bundled-rust-crate-proc-macro-crate \
bundled-rust-crate-proc-macro-error-attr2 \
bundled-rust-crate-proc-macro-error2 \
bundled-rust-crate-proc-macro2 \
bundled-rust-crate-proc-macro2-diagnostics \
bundled-rust-crate-profiling \
bundled-rust-crate-pxfm \
bundled-rust-crate-quick-error \
bundled-rust-crate-quick-xml \
bundled-rust-crate-quote \
bundled-rust-crate-rand \
bundled-rust-crate-rand-chacha \
bundled-rust-crate-rand-core \
bundled-rust-crate-rangemap \
bundled-rust-crate-raw-window-handle \
bundled-rust-crate-read-fonts \
bundled-rust-crate-ref-cast \
bundled-rust-crate-ref-cast-impl \
bundled-rust-crate-regex \
bundled-rust-crate-regex-automata \
bundled-rust-crate-regex-syntax \
bundled-rust-crate-renderdoc-sys \
bundled-rust-crate-resvg \
bundled-rust-crate-rfd \
bundled-rust-crate-rgb \
bundled-rust-crate-ron \
bundled-rust-crate-roxmltree \
bundled-rust-crate-rust-embed \
bundled-rust-crate-rust-embed-impl \
bundled-rust-crate-rust-embed-utils \
bundled-rust-crate-rustc-hash \
bundled-rust-crate-rustix \
bundled-rust-crate-rustversion \
bundled-rust-crate-rustybuzz \
bundled-rust-crate-same-file \
bundled-rust-crate-schemars \
bundled-rust-crate-scoped-tls \
bundled-rust-crate-scopeguard \
bundled-rust-crate-sctk-adwaita \
bundled-rust-crate-self-cell \
bundled-rust-crate-serde \
bundled-rust-crate-serde-core \
bundled-rust-crate-serde-derive \
bundled-rust-crate-serde-json \
bundled-rust-crate-serde-repr \
bundled-rust-crate-serde-with \
bundled-rust-crate-serde-with-macros \
bundled-rust-crate-sha2 \
bundled-rust-crate-shlex \
bundled-rust-crate-signal-hook-registry \
bundled-rust-crate-simd-adler32 \
bundled-rust-crate-simplecss \
bundled-rust-crate-siphasher \
bundled-rust-crate-skrifa \
bundled-rust-crate-slab \
bundled-rust-crate-slotmap \
bundled-rust-crate-smallvec \
bundled-rust-crate-smithay-client-toolkit \
bundled-rust-crate-smithay-clipboard \
bundled-rust-crate-smol-str \
bundled-rust-crate-socket2 \
bundled-rust-crate-softbuffer \
bundled-rust-crate-spirv \
bundled-rust-crate-stable-deref-trait \
bundled-rust-crate-static-assertions \
bundled-rust-crate-strict-num \
bundled-rust-crate-strsim \
bundled-rust-crate-svg-fmt \
bundled-rust-crate-svgtypes \
bundled-rust-crate-swash \
bundled-rust-crate-syn \
bundled-rust-crate-synstructure \
bundled-rust-crate-sys-locale \
bundled-rust-crate-taffy \
bundled-rust-crate-temp-dir \
bundled-rust-crate-tempfile \
bundled-rust-crate-termcolor \
bundled-rust-crate-thiserror \
bundled-rust-crate-thiserror-impl \
bundled-rust-crate-time \
bundled-rust-crate-time-core \
bundled-rust-crate-time-macros \
bundled-rust-crate-tiny-skia \
bundled-rust-crate-tiny-skia-path \
bundled-rust-crate-tiny-xlib \
bundled-rust-crate-tinystr \
bundled-rust-crate-tinyvec \
bundled-rust-crate-tinyvec-macros \
bundled-rust-crate-tokio \
bundled-rust-crate-tokio-macros \
bundled-rust-crate-tokio-stream \
bundled-rust-crate-toml \
bundled-rust-crate-toml-datetime \
bundled-rust-crate-toml-edit \
bundled-rust-crate-toml-parser \
bundled-rust-crate-tracing \
bundled-rust-crate-tracing-attributes \
bundled-rust-crate-tracing-core \
bundled-rust-crate-try-lock \
bundled-rust-crate-ttf-parser \
bundled-rust-crate-type-map \
bundled-rust-crate-typeid \
bundled-rust-crate-typenum \
bundled-rust-crate-uncased \
bundled-rust-crate-unic-langid \
bundled-rust-crate-unic-langid-impl \
bundled-rust-crate-unicase \
bundled-rust-crate-unicode-bidi \
bundled-rust-crate-unicode-bidi-mirroring \
bundled-rust-crate-unicode-ccc \
bundled-rust-crate-unicode-ident \
bundled-rust-crate-unicode-linebreak \
bundled-rust-crate-unicode-properties \
bundled-rust-crate-unicode-script \
bundled-rust-crate-unicode-segmentation \
bundled-rust-crate-unicode-vo \
bundled-rust-crate-unicode-width \
bundled-rust-crate-url \
bundled-rust-crate-urlencoding \
bundled-rust-crate-usvg \
bundled-rust-crate-utf8-iter \
bundled-rust-crate-uuid \
bundled-rust-crate-version-check \
bundled-rust-crate-walkdir \
bundled-rust-crate-want \
bundled-rust-crate-wayland-backend \
bundled-rust-crate-wayland-client \
bundled-rust-crate-wayland-csd-frame \
bundled-rust-crate-wayland-cursor \
bundled-rust-crate-wayland-protocols \
bundled-rust-crate-wayland-protocols-experimental \
bundled-rust-crate-wayland-protocols-misc \
bundled-rust-crate-wayland-protocols-plasma \
bundled-rust-crate-wayland-protocols-wlr \
bundled-rust-crate-wayland-scanner \
bundled-rust-crate-wayland-server \
bundled-rust-crate-wayland-sys \
bundled-rust-crate-web-time \
bundled-rust-crate-weezl \
bundled-rust-crate-wgpu \
bundled-rust-crate-wgpu-core \
bundled-rust-crate-wgpu-core-deps-windows-linux-android \
bundled-rust-crate-wgpu-hal \
bundled-rust-crate-wgpu-types \
bundled-rust-crate-window-clipboard \
bundled-rust-crate-winit \
bundled-rust-crate-winit-common \
bundled-rust-crate-winit-core \
bundled-rust-crate-winit-wayland \
bundled-rust-crate-winit-x11 \
bundled-rust-crate-winnow \
bundled-rust-crate-writeable \
bundled-rust-crate-x11-dl \
bundled-rust-crate-x11rb \
bundled-rust-crate-x11rb-protocol \
bundled-rust-crate-xcursor \
bundled-rust-crate-xdg \
bundled-rust-crate-xdg-shell-wrapper-config \
bundled-rust-crate-xkbcommon \
bundled-rust-crate-xkbcommon-dl \
bundled-rust-crate-xkeysym \
bundled-rust-crate-xmlwriter \
bundled-rust-crate-yansi \
bundled-rust-crate-yazi \
bundled-rust-crate-yoke \
bundled-rust-crate-yoke-derive \
bundled-rust-crate-zbus \
bundled-rust-crate-zbus-lockstep \
bundled-rust-crate-zbus-lockstep-macros \
bundled-rust-crate-zbus-macros \
bundled-rust-crate-zbus-names \
bundled-rust-crate-zbus-xml \
bundled-rust-crate-zeno \
bundled-rust-crate-zerocopy \
bundled-rust-crate-zerocopy-derive \
bundled-rust-crate-zerofrom \
bundled-rust-crate-zerofrom-derive \
bundled-rust-crate-zerotrie \
bundled-rust-crate-zerovec \
bundled-rust-crate-zerovec-derive \
bundled-rust-crate-zmij \
bundled-rust-crate-zune-core \
bundled-rust-crate-zune-jpeg \
bundled-rust-crate-zvariant \
bundled-rust-crate-zvariant-derive \
bundled-rust-crate-zvariant-utils \
cosmic-ext-applet-tailscale"

RDEPENDS:${PN} += "libc.so.6 \
libgcc-s.so.1 \
libm.so.6 \
libxkbcommon.so.0"

inherit rpm
