SUMMARY = "Blazing fast terminal file manager written in Rust, based on async I/O"
DESCRIPTION = "Yazi (means 'duck') is a terminal file manager written in Rust, based on non-blocking async I/O. It aims to provide an efficient, user-friendly, and customizable file management experience. \
 \
💡 A new article explaining its internal workings: Why is Yazi Fast? \
 \
    🚀 Full Asynchronous Support: All I/O operations are asynchronous, CPU tasks are spread across multiple threads, making the most of available resources. \
    💪 Powerful Async Task Scheduling and Management: Provides real-time progress updates, task cancellation, and internal task priority assignment. \
    🖼️ Built-in Support for Multiple Image Protocols: Also integrated with Überzug++, covering almost all terminals. \
    🌟 Built-in Code Highlighting and Image Decoding: Combined with the pre-loading mechanism, greatly accelerates image and normal file loading. \
    🔌 Concurrent Plugin System: UI plugins (rewriting most of the UI), functional plugins (coming soon), custom previewer, and custom preloader; Just some pieces of Lua. \
    🧰 Integration with fd, rg, fzf, zoxide \
    💫 Vim-like input/select component, auto-completion for cd paths \
    🏷️ Multi-Tab Support, Scrollable Preview (for videos, PDFs, archives, directories, code, etc.) \
    🔄 Bulk Renaming, Visual Mode, File Chooser \
    🎨 Theme System, Custom Layouts, Trash Bin, CSI u \
    ... and more!"
LICENSE = "MIT"

PV = "26.8.15"

RPM_NAME = "yazi-26.8.15-1.2.aarch64.rpm"
RPM_HASH = "7feb164d71dc28f8297a23b89f5757126ea8ed9c71b38cc700502d3f66b4007e320b060225d8abadf31fa294a6bf4f2fba7873e215c857fc53039f7bc05a76ba"

RPROVIDES:${PN} += "bundled-rust-crate-adler2 \
bundled-rust-crate-aead \
bundled-rust-crate-aes \
bundled-rust-crate-aes-gcm \
bundled-rust-crate-aho-corasick \
bundled-rust-crate-allocator-api2 \
bundled-rust-crate-ansi-to-tui \
bundled-rust-crate-anstream \
bundled-rust-crate-anstyle \
bundled-rust-crate-anstyle-parse \
bundled-rust-crate-anstyle-query \
bundled-rust-crate-anyhow \
bundled-rust-crate-approx \
bundled-rust-crate-arc-swap \
bundled-rust-crate-argon2 \
bundled-rust-crate-async-priority-channel \
bundled-rust-crate-atomic-waker \
bundled-rust-crate-autocfg \
bundled-rust-crate-base16ct \
bundled-rust-crate-base64 \
bundled-rust-crate-base64ct \
bundled-rust-crate-bcrypt-pbkdf \
bundled-rust-crate-bincode \
bundled-rust-crate-bit-field \
bundled-rust-crate-bitflags \
bundled-rust-crate-bitvec \
bundled-rust-crate-blake2 \
bundled-rust-crate-block-buffer \
bundled-rust-crate-block-padding \
bundled-rust-crate-blowfish \
bundled-rust-crate-bon \
bundled-rust-crate-bon-macros \
bundled-rust-crate-bs58 \
bundled-rust-crate-bstr \
bundled-rust-crate-by-address \
bundled-rust-crate-bytemuck \
bundled-rust-crate-bytemuck-derive \
bundled-rust-crate-byteorder \
bundled-rust-crate-byteorder-lite \
bundled-rust-crate-bytes \
bundled-rust-crate-castaway \
bundled-rust-crate-cbc \
bundled-rust-crate-cc \
bundled-rust-crate-cfg-aliases \
bundled-rust-crate-cfg-if \
bundled-rust-crate-chacha20 \
bundled-rust-crate-chrono \
bundled-rust-crate-cipher \
bundled-rust-crate-clap \
bundled-rust-crate-clap-builder \
bundled-rust-crate-clap-complete \
bundled-rust-crate-clap-complete-fig \
bundled-rust-crate-clap-complete-nushell \
bundled-rust-crate-clap-derive \
bundled-rust-crate-clap-lex \
bundled-rust-crate-cmov \
bundled-rust-crate-color-quant \
bundled-rust-crate-colorchoice \
bundled-rust-crate-compact-str \
bundled-rust-crate-concurrent-queue \
bundled-rust-crate-const-oid \
bundled-rust-crate-cpubits \
bundled-rust-crate-cpufeatures \
bundled-rust-crate-crc32fast \
bundled-rust-crate-critical-section \
bundled-rust-crate-crossbeam-channel \
bundled-rust-crate-crossbeam-utils \
bundled-rust-crate-crypto-bigint \
bundled-rust-crate-crypto-common \
bundled-rust-crate-crypto-primes \
bundled-rust-crate-ctr \
bundled-rust-crate-ctutils \
bundled-rust-crate-curve25519-dalek \
bundled-rust-crate-darling \
bundled-rust-crate-darling-core \
bundled-rust-crate-darling-macro \
bundled-rust-crate-data-encoding \
bundled-rust-crate-deadpool \
bundled-rust-crate-deadpool-runtime \
bundled-rust-crate-defmt \
bundled-rust-crate-defmt-macros \
bundled-rust-crate-defmt-parser \
bundled-rust-crate-delegate \
bundled-rust-crate-der \
bundled-rust-crate-deranged \
bundled-rust-crate-des \
bundled-rust-crate-digest \
bundled-rust-crate-dirs \
bundled-rust-crate-dirs-sys \
bundled-rust-crate-displaydoc \
bundled-rust-crate-dyn-clone \
bundled-rust-crate-ecdsa \
bundled-rust-crate-ed25519 \
bundled-rust-crate-ed25519-dalek \
bundled-rust-crate-either \
bundled-rust-crate-elliptic-curve \
bundled-rust-crate-enum-dispatch \
bundled-rust-crate-equivalent \
bundled-rust-crate-erased-serde \
bundled-rust-crate-errno \
bundled-rust-crate-event-listener \
bundled-rust-crate-exr \
bundled-rust-crate-fax \
bundled-rust-crate-fdeflate \
bundled-rust-crate-fdlimit \
bundled-rust-crate-ff \
bundled-rust-crate-find-msvc-tools \
bundled-rust-crate-flate2 \
bundled-rust-crate-fnv \
bundled-rust-crate-foldhash \
bundled-rust-crate-form-urlencoded \
bundled-rust-crate-funty \
bundled-rust-crate-futures \
bundled-rust-crate-futures-channel \
bundled-rust-crate-futures-core \
bundled-rust-crate-futures-executor \
bundled-rust-crate-futures-io \
bundled-rust-crate-futures-macro \
bundled-rust-crate-futures-sink \
bundled-rust-crate-futures-task \
bundled-rust-crate-futures-util \
bundled-rust-crate-generic-array \
bundled-rust-crate-getrandom \
bundled-rust-crate-ghash \
bundled-rust-crate-gif \
bundled-rust-crate-globset \
bundled-rust-crate-group \
bundled-rust-crate-half \
bundled-rust-crate-hashbrown \
bundled-rust-crate-heck \
bundled-rust-crate-hex \
bundled-rust-crate-hex-literal \
bundled-rust-crate-hkdf \
bundled-rust-crate-hmac \
bundled-rust-crate-http \
bundled-rust-crate-http-body \
bundled-rust-crate-http-body-util \
bundled-rust-crate-httparse \
bundled-rust-crate-hybrid-array \
bundled-rust-crate-hyper \
bundled-rust-crate-hyper-rustls \
bundled-rust-crate-hyper-util \
bundled-rust-crate-iana-time-zone \
bundled-rust-crate-icu-collections \
bundled-rust-crate-icu-locale-core \
bundled-rust-crate-icu-normalizer \
bundled-rust-crate-icu-normalizer-data \
bundled-rust-crate-icu-properties \
bundled-rust-crate-icu-properties-data \
bundled-rust-crate-icu-provider \
bundled-rust-crate-ident-case \
bundled-rust-crate-idna \
bundled-rust-crate-idna-adapter \
bundled-rust-crate-image \
bundled-rust-crate-image-webp \
bundled-rust-crate-indexmap \
bundled-rust-crate-indoc \
bundled-rust-crate-inotify \
bundled-rust-crate-inotify-sys \
bundled-rust-crate-inout \
bundled-rust-crate-instability \
bundled-rust-crate-internal-russh-num-bigint \
bundled-rust-crate-inventory \
bundled-rust-crate-ipnet \
bundled-rust-crate-is-terminal-polyfill \
bundled-rust-crate-itertools \
bundled-rust-crate-itoa \
bundled-rust-crate-jiff \
bundled-rust-crate-jiff-core \
bundled-rust-crate-kasuari \
bundled-rust-crate-keccak \
bundled-rust-crate-kem \
bundled-rust-crate-lazy-static \
bundled-rust-crate-lebe \
bundled-rust-crate-libc \
bundled-rust-crate-libm \
bundled-rust-crate-line-clipping \
bundled-rust-crate-linux-raw-sys \
bundled-rust-crate-litemap \
bundled-rust-crate-lock-api \
bundled-rust-crate-log \
bundled-rust-crate-lru \
bundled-rust-crate-lua-src \
bundled-rust-crate-luajit-src \
bundled-rust-crate-matchers \
bundled-rust-crate-md5 \
bundled-rust-crate-memchr \
bundled-rust-crate-miniz-oxide \
bundled-rust-crate-mio \
bundled-rust-crate-ml-kem \
bundled-rust-crate-mlua \
bundled-rust-crate-mlua-derive \
bundled-rust-crate-mlua-sys \
bundled-rust-crate-module-lattice \
bundled-rust-crate-moxcms \
bundled-rust-crate-nix \
bundled-rust-crate-nom \
bundled-rust-crate-notify \
bundled-rust-crate-notify-types \
bundled-rust-crate-nu-ansi-term \
bundled-rust-crate-num-bigint \
bundled-rust-crate-num-complex \
bundled-rust-crate-num-conv \
bundled-rust-crate-num-cpus \
bundled-rust-crate-num-integer \
bundled-rust-crate-num-threads \
bundled-rust-crate-num-traits \
bundled-rust-crate-once-cell \
bundled-rust-crate-onig \
bundled-rust-crate-onig-sys \
bundled-rust-crate-openssl-probe \
bundled-rust-crate-option-ext \
bundled-rust-crate-ordered-float \
bundled-rust-crate-p256 \
bundled-rust-crate-p384 \
bundled-rust-crate-p521 \
bundled-rust-crate-palette \
bundled-rust-crate-palette-derive \
bundled-rust-crate-palette-math \
bundled-rust-crate-parking \
bundled-rust-crate-parking-lot \
bundled-rust-crate-parking-lot-core \
bundled-rust-crate-password-hash \
bundled-rust-crate-paste \
bundled-rust-crate-pbkdf2 \
bundled-rust-crate-pem-rfc7468 \
bundled-rust-crate-percent-encoding \
bundled-rust-crate-phc \
bundled-rust-crate-pin-project-lite \
bundled-rust-crate-pkcs1 \
bundled-rust-crate-pkcs5 \
bundled-rust-crate-pkcs8 \
bundled-rust-crate-pkg-config \
bundled-rust-crate-plist \
bundled-rust-crate-png \
bundled-rust-crate-poly1305 \
bundled-rust-crate-polyval \
bundled-rust-crate-portable-atomic \
bundled-rust-crate-potential-utf \
bundled-rust-crate-powerfmt \
bundled-rust-crate-prettyplease \
bundled-rust-crate-primefield \
bundled-rust-crate-primeorder \
bundled-rust-crate-proc-macro2 \
bundled-rust-crate-pulp \
bundled-rust-crate-pulp-wasm-simd-flag \
bundled-rust-crate-pxfm \
bundled-rust-crate-qoi \
bundled-rust-crate-quantette \
bundled-rust-crate-quick-error \
bundled-rust-crate-quick-xml \
bundled-rust-crate-quote \
bundled-rust-crate-radium \
bundled-rust-crate-rand \
bundled-rust-crate-rand-core \
bundled-rust-crate-ratatui-core \
bundled-rust-crate-ratatui-widgets \
bundled-rust-crate-reborrow \
bundled-rust-crate-ref-cast \
bundled-rust-crate-ref-cast-impl \
bundled-rust-crate-regex \
bundled-rust-crate-regex-automata \
bundled-rust-crate-regex-syntax \
bundled-rust-crate-reqwest \
bundled-rust-crate-rfc6979 \
bundled-rust-crate-ring \
bundled-rust-crate-rsa \
bundled-rust-crate-russh \
bundled-rust-crate-russh-cryptovec \
bundled-rust-crate-russh-util \
bundled-rust-crate-rustc-hash \
bundled-rust-crate-rustc-version \
bundled-rust-crate-rustix \
bundled-rust-crate-rustls \
bundled-rust-crate-rustls-native-certs \
bundled-rust-crate-rustls-pki-types \
bundled-rust-crate-rustls-platform-verifier \
bundled-rust-crate-rustls-webpki \
bundled-rust-crate-rustversion \
bundled-rust-crate-ryu \
bundled-rust-crate-salsa20 \
bundled-rust-crate-same-file \
bundled-rust-crate-schemars \
bundled-rust-crate-scopeguard \
bundled-rust-crate-scrypt \
bundled-rust-crate-sec1 \
bundled-rust-crate-semver \
bundled-rust-crate-serde \
bundled-rust-crate-serde-core \
bundled-rust-crate-serde-derive \
bundled-rust-crate-serde-json \
bundled-rust-crate-serde-spanned \
bundled-rust-crate-serde-value \
bundled-rust-crate-serde-with \
bundled-rust-crate-serde-with-macros \
bundled-rust-crate-serdect \
bundled-rust-crate-sha1 \
bundled-rust-crate-sha2 \
bundled-rust-crate-sha3 \
bundled-rust-crate-sharded-slab \
bundled-rust-crate-shlex \
bundled-rust-crate-signal-hook \
bundled-rust-crate-signal-hook-registry \
bundled-rust-crate-signal-hook-tokio \
bundled-rust-crate-signature \
bundled-rust-crate-simd-adler32 \
bundled-rust-crate-simdutf8 \
bundled-rust-crate-slab \
bundled-rust-crate-smallvec \
bundled-rust-crate-socket2 \
bundled-rust-crate-spki \
bundled-rust-crate-sponge-cursor \
bundled-rust-crate-ssh-cipher \
bundled-rust-crate-ssh-encoding \
bundled-rust-crate-ssh-key \
bundled-rust-crate-stable-deref-trait \
bundled-rust-crate-static-assertions \
bundled-rust-crate-strsim \
bundled-rust-crate-strum \
bundled-rust-crate-strum-macros \
bundled-rust-crate-subtle \
bundled-rust-crate-symlink \
bundled-rust-crate-syn \
bundled-rust-crate-sync-wrapper \
bundled-rust-crate-synstructure \
bundled-rust-crate-syntect \
bundled-rust-crate-tap \
bundled-rust-crate-thiserror \
bundled-rust-crate-thiserror-impl \
bundled-rust-crate-thread-local \
bundled-rust-crate-tiff \
bundled-rust-crate-tikv-jemalloc-sys \
bundled-rust-crate-tikv-jemallocator \
bundled-rust-crate-time \
bundled-rust-crate-time-core \
bundled-rust-crate-time-macros \
bundled-rust-crate-tinystr \
bundled-rust-crate-tinyvec \
bundled-rust-crate-tinyvec-macros \
bundled-rust-crate-tokio \
bundled-rust-crate-tokio-macros \
bundled-rust-crate-tokio-rustls \
bundled-rust-crate-tokio-stream \
bundled-rust-crate-tokio-util \
bundled-rust-crate-toml \
bundled-rust-crate-toml-datetime \
bundled-rust-crate-toml-parser \
bundled-rust-crate-toml-writer \
bundled-rust-crate-tower \
bundled-rust-crate-tower-http \
bundled-rust-crate-tower-layer \
bundled-rust-crate-tower-service \
bundled-rust-crate-tracing \
bundled-rust-crate-tracing-appender \
bundled-rust-crate-tracing-attributes \
bundled-rust-crate-tracing-core \
bundled-rust-crate-tracing-log \
bundled-rust-crate-tracing-subscriber \
bundled-rust-crate-trash \
bundled-rust-crate-try-lock \
bundled-rust-crate-twox-hash \
bundled-rust-crate-typed-path \
bundled-rust-crate-typeid \
bundled-rust-crate-typenum \
bundled-rust-crate-unicode-ident \
bundled-rust-crate-unicode-normalization \
bundled-rust-crate-unicode-segmentation \
bundled-rust-crate-unicode-truncate \
bundled-rust-crate-unicode-width \
bundled-rust-crate-universal-hash \
bundled-rust-crate-untrusted \
bundled-rust-crate-url \
bundled-rust-crate-urlencoding \
bundled-rust-crate-utf8-iter \
bundled-rust-crate-utf8parse \
bundled-rust-crate-uzers \
bundled-rust-crate-vergen \
bundled-rust-crate-vergen-gitcl \
bundled-rust-crate-vergen-lib \
bundled-rust-crate-version-check \
bundled-rust-crate-walkdir \
bundled-rust-crate-want \
bundled-rust-crate-weezl \
bundled-rust-crate-which \
bundled-rust-crate-wide \
bundled-rust-crate-winnow \
bundled-rust-crate-wnaf \
bundled-rust-crate-writeable \
bundled-rust-crate-wyz \
bundled-rust-crate-yazi-actor \
bundled-rust-crate-yazi-adapter \
bundled-rust-crate-yazi-binding \
bundled-rust-crate-yazi-boot \
bundled-rust-crate-yazi-cli \
bundled-rust-crate-yazi-codegen \
bundled-rust-crate-yazi-config \
bundled-rust-crate-yazi-core \
bundled-rust-crate-yazi-dds \
bundled-rust-crate-yazi-emulator \
bundled-rust-crate-yazi-ffi \
bundled-rust-crate-yazi-fm \
bundled-rust-crate-yazi-fs \
bundled-rust-crate-yazi-macro \
bundled-rust-crate-yazi-parser \
bundled-rust-crate-yazi-plugin \
bundled-rust-crate-yazi-prebuilt \
bundled-rust-crate-yazi-proxy \
bundled-rust-crate-yazi-runner \
bundled-rust-crate-yazi-scheduler \
bundled-rust-crate-yazi-sftp \
bundled-rust-crate-yazi-shared \
bundled-rust-crate-yazi-shim \
bundled-rust-crate-yazi-term \
bundled-rust-crate-yazi-tty \
bundled-rust-crate-yazi-tui \
bundled-rust-crate-yazi-version \
bundled-rust-crate-yazi-vfs \
bundled-rust-crate-yazi-watcher \
bundled-rust-crate-yazi-widgets \
bundled-rust-crate-yoke \
bundled-rust-crate-yoke-derive \
bundled-rust-crate-zerocopy \
bundled-rust-crate-zerocopy-derive \
bundled-rust-crate-zerofrom \
bundled-rust-crate-zerofrom-derive \
bundled-rust-crate-zeroize \
bundled-rust-crate-zerotrie \
bundled-rust-crate-zerovec \
bundled-rust-crate-zerovec-derive \
bundled-rust-crate-zmij \
bundled-rust-crate-zune-core \
bundled-rust-crate-zune-inflate \
bundled-rust-crate-zune-jpeg \
yazi"

RDEPENDS:${PN} += "file \
libc.so.6 \
libgcc-s.so.1 \
libm.so.6"

inherit rpm
