SUMMARY = "The KDE Plasma Workspace Components"
DESCRIPTION = "This package contains the basic packages for a Plasma workspace."
LICENSE = "GPL-2.0-or-later"

PV = "6.7.5"

RPM_NAME = "plasma6-workspace-6.7.5-1.1.aarch64.rpm"
RPM_HASH = "d2d672416b5db006bb449270923e0793182a87edfce75255df343de02f3a3bc291f4ff1ae8198ff22f3862eb042385176360a6bcc3b8b44f155b5af2ddf90e6b"

RPROVIDES:${PN} += "config-plasma6-workspace \
dbus-org.freedesktop.Notifications \
gmenudbusmenuproxy \
kde-user-manager \
libbatterycontrolplugin.so \
libcalendarplugin.so \
libclockplugin.so \
libcomponents.so \
libcontainmentlayoutmanagerplugin.so \
libdbusplugin.so \
libdigitalclockplugin.so \
libholidayevents.so \
libkeyboardindicatorplugin.so \
libkeyboardlayoutplugin.so \
libkfontinst.so.6 \
libkfontinstui.so.6 \
libkickerplugin.so \
libklipperplugin.so \
libkmprisplugin.so \
liblookandfeelqmlplugin.so \
libnotificationmanagerplugin.so \
libplasma-wallpaper-image.so \
libplasmashell-osd.so \
libplasmashellprivateplugin.so \
libsessionsprivateplugin.so \
libsystemtrayplugin.so \
libtaskmanagerplugin.so \
libtimezoneplugin.so \
libtrianglemousefilterplugin.so \
libworkspacecomponents.so \
plasma5-workspace \
plasma6-workspace \
plasma6-workspace-branding \
plasma6-workspace-branding-upstream \
qt6qmlimport-org.kde.breeze.components \
qt6qmlimport-org.kde.breeze.components.254 \
qt6qmlimport-org.kde.notificationmanager \
qt6qmlimport-org.kde.notificationmanager.254 \
qt6qmlimport-org.kde.notificationmanager.6 \
qt6qmlimport-org.kde.plasma.clock \
qt6qmlimport-org.kde.plasma.clock.254 \
qt6qmlimport-org.kde.plasma.lookandfeel \
qt6qmlimport-org.kde.plasma.lookandfeel.1 \
qt6qmlimport-org.kde.plasma.private.battery \
qt6qmlimport-org.kde.plasma.private.battery.254 \
qt6qmlimport-org.kde.plasma.private.battery.6 \
qt6qmlimport-org.kde.plasma.private.clipboard \
qt6qmlimport-org.kde.plasma.private.clipboard.0 \
qt6qmlimport-org.kde.plasma.private.containmentlayoutmanager \
qt6qmlimport-org.kde.plasma.private.containmentlayoutmanager.1 \
qt6qmlimport-org.kde.plasma.private.digitalclock \
qt6qmlimport-org.kde.plasma.private.digitalclock.1 \
qt6qmlimport-org.kde.plasma.private.holidayevents \
qt6qmlimport-org.kde.plasma.private.holidayevents.254 \
qt6qmlimport-org.kde.plasma.private.keyboardindicator \
qt6qmlimport-org.kde.plasma.private.keyboardindicator.254 \
qt6qmlimport-org.kde.plasma.private.kicker \
qt6qmlimport-org.kde.plasma.private.kicker.0 \
qt6qmlimport-org.kde.plasma.private.mpris \
qt6qmlimport-org.kde.plasma.private.mpris.254 \
qt6qmlimport-org.kde.plasma.private.mpris.6 \
qt6qmlimport-org.kde.plasma.private.sessions \
qt6qmlimport-org.kde.plasma.private.sessions.2 \
qt6qmlimport-org.kde.plasma.private.shell \
qt6qmlimport-org.kde.plasma.private.shell.2 \
qt6qmlimport-org.kde.plasma.private.systemtray \
qt6qmlimport-org.kde.plasma.private.systemtray.254 \
qt6qmlimport-org.kde.plasma.private.systemtray.6 \
qt6qmlimport-org.kde.plasma.shell \
qt6qmlimport-org.kde.plasma.shell.2 \
qt6qmlimport-org.kde.plasma.shell.panel \
qt6qmlimport-org.kde.plasma.shell.panel.0 \
qt6qmlimport-org.kde.plasma.wallpapers.image \
qt6qmlimport-org.kde.plasma.wallpapers.image.2 \
qt6qmlimport-org.kde.plasma.workspace.calendar \
qt6qmlimport-org.kde.plasma.workspace.calendar.2 \
qt6qmlimport-org.kde.plasma.workspace.components \
qt6qmlimport-org.kde.plasma.workspace.components.2 \
qt6qmlimport-org.kde.plasma.workspace.dbus \
qt6qmlimport-org.kde.plasma.workspace.dbus.1 \
qt6qmlimport-org.kde.plasma.workspace.keyboardlayout \
qt6qmlimport-org.kde.plasma.workspace.keyboardlayout.1 \
qt6qmlimport-org.kde.plasma.workspace.osd \
qt6qmlimport-org.kde.plasma.workspace.osd.2 \
qt6qmlimport-org.kde.plasma.workspace.osd.254 \
qt6qmlimport-org.kde.plasma.workspace.osd.6 \
qt6qmlimport-org.kde.plasma.workspace.timezoneselector \
qt6qmlimport-org.kde.plasma.workspace.timezoneselector.254 \
qt6qmlimport-org.kde.plasma.workspace.trianglemousefilter \
qt6qmlimport-org.kde.plasma.workspace.trianglemousefilter.1 \
qt6qmlimport-org.kde.taskmanager \
qt6qmlimport-org.kde.taskmanager.0 \
xembed-sni-proxy \
xembedsniproxy"

RDEPENDS:${PN} += "/usr/bin/env \
/usr/bin/grep \
/usr/bin/sh \
accountsservice \
breeze6 \
cpp \
iso-codes \
iso-codes-lang \
kactivitymanagerd6 \
kde-cli-tools6 \
kf6-frameworkintegration-plugin \
kf6-kconfig-imports \
kf6-kded \
kf6-knewstuff-imports \
kf6-kquickcharts \
kf6-kuserfeedback-imports \
kglobalacceld6 \
kio-extras \
kirigami-addons6 \
knighttime6 \
kscreen6 \
kscreenlocker6 \
ksystemstats6 \
kwin6 \
ld-linux-aarch64.so.1 \
libAppStreamQt.so.3 \
libICE.so.6 \
libKExiv2Qt6.so.0 \
libKF6Archive.so.6 \
libKF6AuthCore.so.6 \
libKF6Baloo.so.6 \
libKF6Bookmarks.so.6 \
libKF6CalendarEvents.so.6 \
libKF6ColorScheme.so.6 \
libKF6Completion.so.6 \
libKF6ConfigCore.so.6 \
libKF6ConfigGui.so.6 \
libKF6ConfigQml.so.6 \
libKF6ConfigWidgets.so.6 \
libKF6CoreAddons.so.6 \
libKF6Crash.so.6 \
libKF6DBusAddons.so.6 \
libKF6GlobalAccel.so.6 \
libKF6GuiAddons.so.6 \
libKF6Holidays.so.6 \
libKF6I18n.so.6 \
libKF6I18nLocaleData.so.6 \
libKF6IconThemes.so.6 \
libKF6IdleTime.so.6 \
libKF6JobWidgets.so.6 \
libKF6KCMUtils.so.6 \
libKF6KCMUtilsCore.so.6 \
libKF6KCMUtilsQuick.so.6 \
libKF6KIOCore.so.6 \
libKF6KIOFileWidgets.so.6 \
libKF6KIOGui.so.6 \
libKF6KIOWidgets.so.6 \
libKF6NetworkManagerQt.so.6 \
libKF6NewStuffCore.so.6 \
libKF6NewStuffWidgets.so.6 \
libKF6Notifications.so.6 \
libKF6Package.so.6 \
libKF6Parts.so.6 \
libKF6Runner.so.6 \
libKF6Service.so.6 \
libKF6Solid.so.6 \
libKF6StatusNotifierItem.so.6 \
libKF6Svg.so.6 \
libKF6TextEditor.so.6 \
libKF6TextWidgets.so.6 \
libKF6UserFeedbackCore.so.6 \
libKF6Wallet.so.6 \
libKF6WidgetsAddons.so.6 \
libKF6WindowSystem.so.6 \
libKF6XmlGui.so.6 \
libKNightTime.so.0 \
libKScreenLocker.so.6 \
libKSysGuardSensorFaces.so.2 \
libKWaylandClient.so.6 \
libLayerShellQtInterface.so.6 \
libPlasma.so.7 \
libPlasmaActivities.so.7 \
libPlasmaActivitiesStats.so.1 \
libPlasmaQuick.so.7 \
libQt6Core.so.6 \
libQt6DBus.so.6 \
libQt6Gui.so.6 \
libQt6Network.so.6 \
libQt6Positioning.so.6 \
libQt6PrintSupport.so.6 \
libQt6Qml.so.6 \
libQt6Quick.so.6 \
libQt6Sql.so.6 \
libQt6Svg.so.6 \
libQt6WaylandClient.so.6 \
libQt6Widgets.so.6 \
libQt6Xml.so.6 \
libSM.so.6 \
libX11.so.6 \
libXcursor.so.1 \
libXfixes.so.3 \
libXft.so.2 \
libXtst.so.6 \
libbatterycontrol.so.6 \
libc.so.6 \
libcanberra.so.0 \
libcrypt.so.1 \
libdbus-1.so.3 \
libfontconfig.so.1 \
libfreetype.so.6 \
libgcc-s.so.1 \
libicui18n.so.78 \
libicuuc.so.78 \
libklipper.so.6 \
libklookandfeel.so.6 \
libkmpris.so.6 \
libkrdb.so \
libkscreen6-plugin \
libkworkspace6.so.6 \
libm.so.6 \
libnotificationmanager.so.1 \
libpackagekitqt6.so.2 \
libplasma6-components \
libprocesscore.so.11 \
libqalculate.so.23 \
libstdc++.so.6 \
libsystemd.so.0 \
libtaskmanager.so.6 \
libudev.so.1 \
libwayland-client.so.0 \
libxcb-composite.so.0 \
libxcb-cursor.so.0 \
libxcb-damage.so.0 \
libxcb-icccm.so.4 \
libxcb-image.so.0 \
libxcb-shape.so.0 \
libxcb-util.so.1 \
libxcb.so.1 \
libz.so.1 \
milou6 \
plasma6-workspace-libs \
qt6-declarative-imports \
qt6-positioning-imports \
qt6-sql-sqlite \
qt6-tools-qdbus \
qt6qmlimport-Qt.labs.qmlmodels \
qt6qmlimport-Qt5Compat.GraphicalEffects \
qt6qmlimport-QtCore \
qt6qmlimport-QtLocation \
qt6qmlimport-QtPositioning \
qt6qmlimport-QtQml \
qt6qmlimport-QtQml.Models \
qt6qmlimport-QtQuick \
qt6qmlimport-QtQuick.Controls \
qt6qmlimport-QtQuick.Dialogs \
qt6qmlimport-QtQuick.Effects \
qt6qmlimport-QtQuick.Layouts \
qt6qmlimport-QtQuick.Templates \
qt6qmlimport-QtQuick.VirtualKeyboard \
qt6qmlimport-QtQuick.Window \
qt6qmlimport-org.kde.config \
qt6qmlimport-org.kde.coreaddons \
qt6qmlimport-org.kde.kcmutils \
qt6qmlimport-org.kde.kholidays \
qt6qmlimport-org.kde.kirigami \
qt6qmlimport-org.kde.kirigami.delegates \
qt6qmlimport-org.kde.kirigamiaddons.components \
qt6qmlimport-org.kde.kirigamiaddons.formcard \
qt6qmlimport-org.kde.kitemmodels \
qt6qmlimport-org.kde.kquickcontrols \
qt6qmlimport-org.kde.kquickcontrolsaddons \
qt6qmlimport-org.kde.ksvg \
qt6qmlimport-org.kde.ksysguard.faces \
qt6qmlimport-org.kde.ksysguard.sensors \
qt6qmlimport-org.kde.kwindowsystem \
qt6qmlimport-org.kde.newstuff \
qt6qmlimport-org.kde.plasma.components \
qt6qmlimport-org.kde.plasma.configuration \
qt6qmlimport-org.kde.plasma.core \
qt6qmlimport-org.kde.plasma.extras \
qt6qmlimport-org.kde.plasma.plasmoid \
qt6qmlimport-org.kde.prison \
xrdb \
xsetroot"

inherit rpm
