SUMMARY = "A JavaScript and TypeScript toolchain"
DESCRIPTION = "A toolchain for web projects, aimed to provide functionalities to maintain \
them. Biome offers formatter and linter, usable via CLI and LSP."
LICENSE = "Apache-2.0 & MIT"

PV = "2.5.0"

RPM_NAME = "biome-2.5.0-1.4.aarch64.rpm"
RPM_HASH = "a6a7948a7b97c926feca7edd6ddc45cae4327e150aaf1f9b2a9f96ca497db54a5212590e7bb39ec4b82335a11018b60ff78df82d868b5d43213c36d4a57419ab"

RPROVIDES:${PN} += "biome \
bundled-rust-crate-addr2line \
bundled-rust-crate-adler2 \
bundled-rust-crate-aho-corasick \
bundled-rust-crate-allocator-api2 \
bundled-rust-crate-anyhow \
bundled-rust-crate-atomic-waker \
bundled-rust-crate-autocfg \
bundled-rust-crate-backtrace \
bundled-rust-crate-base64 \
bundled-rust-crate-biome-analyze \
bundled-rust-crate-biome-analyze-macros \
bundled-rust-crate-biome-aria \
bundled-rust-crate-biome-aria-metadata \
bundled-rust-crate-biome-cli \
bundled-rust-crate-biome-configuration \
bundled-rust-crate-biome-configuration-macros \
bundled-rust-crate-biome-console \
bundled-rust-crate-biome-control-flow \
bundled-rust-crate-biome-css-analyze \
bundled-rust-crate-biome-css-factory \
bundled-rust-crate-biome-css-formatter \
bundled-rust-crate-biome-css-parser \
bundled-rust-crate-biome-css-semantic \
bundled-rust-crate-biome-css-syntax \
bundled-rust-crate-biome-db \
bundled-rust-crate-biome-deserialize \
bundled-rust-crate-biome-deserialize-macros \
bundled-rust-crate-biome-diagnostics \
bundled-rust-crate-biome-diagnostics-categories \
bundled-rust-crate-biome-diagnostics-macros \
bundled-rust-crate-biome-flags \
bundled-rust-crate-biome-formatter \
bundled-rust-crate-biome-fs \
bundled-rust-crate-biome-glob \
bundled-rust-crate-biome-graphql-analyze \
bundled-rust-crate-biome-graphql-factory \
bundled-rust-crate-biome-graphql-formatter \
bundled-rust-crate-biome-graphql-parser \
bundled-rust-crate-biome-graphql-syntax \
bundled-rust-crate-biome-grit-factory \
bundled-rust-crate-biome-grit-formatter \
bundled-rust-crate-biome-grit-parser \
bundled-rust-crate-biome-grit-patterns \
bundled-rust-crate-biome-grit-syntax \
bundled-rust-crate-biome-html-analyze \
bundled-rust-crate-biome-html-factory \
bundled-rust-crate-biome-html-formatter \
bundled-rust-crate-biome-html-parser \
bundled-rust-crate-biome-html-syntax \
bundled-rust-crate-biome-js-analyze \
bundled-rust-crate-biome-js-factory \
bundled-rust-crate-biome-js-formatter \
bundled-rust-crate-biome-js-parser \
bundled-rust-crate-biome-js-semantic \
bundled-rust-crate-biome-js-syntax \
bundled-rust-crate-biome-js-type-info \
bundled-rust-crate-biome-js-type-info-macros \
bundled-rust-crate-biome-jsdoc-comment \
bundled-rust-crate-biome-json-analyze \
bundled-rust-crate-biome-json-factory \
bundled-rust-crate-biome-json-formatter \
bundled-rust-crate-biome-json-parser \
bundled-rust-crate-biome-json-syntax \
bundled-rust-crate-biome-json-value \
bundled-rust-crate-biome-line-index \
bundled-rust-crate-biome-lsp \
bundled-rust-crate-biome-lsp-converters \
bundled-rust-crate-biome-markdown-factory \
bundled-rust-crate-biome-markdown-formatter \
bundled-rust-crate-biome-markdown-parser \
bundled-rust-crate-biome-markdown-syntax \
bundled-rust-crate-biome-markup \
bundled-rust-crate-biome-migrate \
bundled-rust-crate-biome-module-graph \
bundled-rust-crate-biome-module-replacements \
bundled-rust-crate-biome-package \
bundled-rust-crate-biome-parser \
bundled-rust-crate-biome-plugin-loader \
bundled-rust-crate-biome-project-layout \
bundled-rust-crate-biome-resolver \
bundled-rust-crate-biome-rowan \
bundled-rust-crate-biome-rule-options \
bundled-rust-crate-biome-service \
bundled-rust-crate-biome-string-case \
bundled-rust-crate-biome-suppression \
bundled-rust-crate-biome-tailwind-factory \
bundled-rust-crate-biome-tailwind-parser \
bundled-rust-crate-biome-tailwind-syntax \
bundled-rust-crate-biome-text-edit \
bundled-rust-crate-biome-text-size \
bundled-rust-crate-biome-unicode-table \
bundled-rust-crate-biome-yaml-factory \
bundled-rust-crate-biome-yaml-formatter \
bundled-rust-crate-biome-yaml-parser \
bundled-rust-crate-biome-yaml-syntax \
bundled-rust-crate-bitflags \
bundled-rust-crate-bitvec \
bundled-rust-crate-borrow-or-share \
bundled-rust-crate-boxcar \
bundled-rust-crate-bpaf \
bundled-rust-crate-bpaf-derive \
bundled-rust-crate-bstr \
bundled-rust-crate-bytemuck \
bundled-rust-crate-bytemuck-derive \
bundled-rust-crate-byteorder \
bundled-rust-crate-bytes \
bundled-rust-crate-camino \
bundled-rust-crate-caseless \
bundled-rust-crate-cc \
bundled-rust-crate-cfg-aliases \
bundled-rust-crate-cfg-if \
bundled-rust-crate-chrono \
bundled-rust-crate-console \
bundled-rust-crate-countme \
bundled-rust-crate-crossbeam \
bundled-rust-crate-crossbeam-channel \
bundled-rust-crate-crossbeam-deque \
bundled-rust-crate-crossbeam-epoch \
bundled-rust-crate-crossbeam-queue \
bundled-rust-crate-crossbeam-utils \
bundled-rust-crate-darling \
bundled-rust-crate-darling-core \
bundled-rust-crate-darling-macro \
bundled-rust-crate-dashmap \
bundled-rust-crate-deranged \
bundled-rust-crate-derive-builder \
bundled-rust-crate-derive-builder-core \
bundled-rust-crate-derive-builder-macro \
bundled-rust-crate-directories \
bundled-rust-crate-dirs-sys \
bundled-rust-crate-displaydoc \
bundled-rust-crate-drop-bomb \
bundled-rust-crate-dyn-clone \
bundled-rust-crate-either \
bundled-rust-crate-elsa \
bundled-rust-crate-enumflags2 \
bundled-rust-crate-enumflags2-derive \
bundled-rust-crate-equivalent \
bundled-rust-crate-errno \
bundled-rust-crate-fastrand \
bundled-rust-crate-filetime \
bundled-rust-crate-fluent-uri \
bundled-rust-crate-fnv \
bundled-rust-crate-foldhash \
bundled-rust-crate-form-urlencoded \
bundled-rust-crate-funty \
bundled-rust-crate-futures \
bundled-rust-crate-futures-channel \
bundled-rust-crate-futures-core \
bundled-rust-crate-futures-executor \
bundled-rust-crate-futures-io \
bundled-rust-crate-futures-macro \
bundled-rust-crate-futures-sink \
bundled-rust-crate-futures-task \
bundled-rust-crate-futures-util \
bundled-rust-crate-getopts \
bundled-rust-crate-getrandom \
bundled-rust-crate-gimli \
bundled-rust-crate-globset \
bundled-rust-crate-grit-pattern-matcher \
bundled-rust-crate-grit-util \
bundled-rust-crate-h2 \
bundled-rust-crate-hashbrown \
bundled-rust-crate-hashlink \
bundled-rust-crate-htmlize \
bundled-rust-crate-http \
bundled-rust-crate-http-body \
bundled-rust-crate-http-body-util \
bundled-rust-crate-httparse \
bundled-rust-crate-hyper \
bundled-rust-crate-hyper-rustls \
bundled-rust-crate-hyper-util \
bundled-rust-crate-icu-collections \
bundled-rust-crate-icu-locid \
bundled-rust-crate-icu-locid-transform \
bundled-rust-crate-icu-locid-transform-data \
bundled-rust-crate-icu-normalizer \
bundled-rust-crate-icu-normalizer-data \
bundled-rust-crate-icu-properties \
bundled-rust-crate-icu-properties-data \
bundled-rust-crate-icu-provider \
bundled-rust-crate-icu-provider-macros \
bundled-rust-crate-ident-case \
bundled-rust-crate-idna \
bundled-rust-crate-idna-adapter \
bundled-rust-crate-ignore \
bundled-rust-crate-indexmap \
bundled-rust-crate-indicatif \
bundled-rust-crate-inotify \
bundled-rust-crate-inotify-sys \
bundled-rust-crate-intrusive-collections \
bundled-rust-crate-inventory \
bundled-rust-crate-ipnet \
bundled-rust-crate-is-ci \
bundled-rust-crate-is-terminal \
bundled-rust-crate-itertools \
bundled-rust-crate-itoa \
bundled-rust-crate-jiff \
bundled-rust-crate-jiff-static \
bundled-rust-crate-jobserver \
bundled-rust-crate-lazy-static \
bundled-rust-crate-libc \
bundled-rust-crate-linux-raw-sys \
bundled-rust-crate-litemap \
bundled-rust-crate-lock-api \
bundled-rust-crate-log \
bundled-rust-crate-lru-slab \
bundled-rust-crate-ls-types \
bundled-rust-crate-matchers \
bundled-rust-crate-memchr \
bundled-rust-crate-memoffset \
bundled-rust-crate-miniz-oxide \
bundled-rust-crate-mio \
bundled-rust-crate-newtype-uuid \
bundled-rust-crate-notify \
bundled-rust-crate-notify-types \
bundled-rust-crate-nu-ansi-term \
bundled-rust-crate-num-conv \
bundled-rust-crate-num-threads \
bundled-rust-crate-num-traits \
bundled-rust-crate-number-prefix \
bundled-rust-crate-object \
bundled-rust-crate-once-cell \
bundled-rust-crate-option-ext \
bundled-rust-crate-owo-colors \
bundled-rust-crate-papaya \
bundled-rust-crate-parking-lot \
bundled-rust-crate-parking-lot-core \
bundled-rust-crate-pastey \
bundled-rust-crate-path-absolutize \
bundled-rust-crate-path-dedot \
bundled-rust-crate-percent-encoding \
bundled-rust-crate-phf \
bundled-rust-crate-phf-codegen \
bundled-rust-crate-phf-generator \
bundled-rust-crate-phf-macros \
bundled-rust-crate-phf-shared \
bundled-rust-crate-pin-project-lite \
bundled-rust-crate-portable-atomic \
bundled-rust-crate-powerfmt \
bundled-rust-crate-ppv-lite86 \
bundled-rust-crate-prettyplease \
bundled-rust-crate-proc-macro-error-attr2 \
bundled-rust-crate-proc-macro-error2 \
bundled-rust-crate-proc-macro2 \
bundled-rust-crate-pulldown-cmark \
bundled-rust-crate-pulldown-cmark-escape \
bundled-rust-crate-quick-junit \
bundled-rust-crate-quick-xml \
bundled-rust-crate-quinn \
bundled-rust-crate-quinn-proto \
bundled-rust-crate-quinn-udp \
bundled-rust-crate-quote \
bundled-rust-crate-radium \
bundled-rust-crate-rand \
bundled-rust-crate-rand-chacha \
bundled-rust-crate-rand-core \
bundled-rust-crate-rayon \
bundled-rust-crate-rayon-core \
bundled-rust-crate-ref-cast \
bundled-rust-crate-ref-cast-impl \
bundled-rust-crate-regex \
bundled-rust-crate-regex-automata \
bundled-rust-crate-regex-syntax \
bundled-rust-crate-reqwest \
bundled-rust-crate-ring \
bundled-rust-crate-roaring \
bundled-rust-crate-rust-lapper \
bundled-rust-crate-rustc-demangle \
bundled-rust-crate-rustc-hash \
bundled-rust-crate-rustix \
bundled-rust-crate-rustls \
bundled-rust-crate-rustls-pki-types \
bundled-rust-crate-rustls-webpki \
bundled-rust-crate-ryu \
bundled-rust-crate-salsa \
bundled-rust-crate-salsa-macro-rules \
bundled-rust-crate-salsa-macros \
bundled-rust-crate-same-file \
bundled-rust-crate-schemars \
bundled-rust-crate-schemars-derive \
bundled-rust-crate-scopeguard \
bundled-rust-crate-seize \
bundled-rust-crate-self-replace \
bundled-rust-crate-self-update \
bundled-rust-crate-semver \
bundled-rust-crate-serde \
bundled-rust-crate-serde-core \
bundled-rust-crate-serde-derive \
bundled-rust-crate-serde-derive-internals \
bundled-rust-crate-serde-json \
bundled-rust-crate-serde-urlencoded \
bundled-rust-crate-sharded-slab \
bundled-rust-crate-shlex \
bundled-rust-crate-signal-hook-registry \
bundled-rust-crate-similar \
bundled-rust-crate-siphasher \
bundled-rust-crate-slab \
bundled-rust-crate-smallvec \
bundled-rust-crate-socket2 \
bundled-rust-crate-stable-deref-trait \
bundled-rust-crate-static-assertions \
bundled-rust-crate-strip-ansi-escapes \
bundled-rust-crate-strsim \
bundled-rust-crate-subtle \
bundled-rust-crate-supports-color \
bundled-rust-crate-syn \
bundled-rust-crate-sync-wrapper \
bundled-rust-crate-synstructure \
bundled-rust-crate-tap \
bundled-rust-crate-tempfile \
bundled-rust-crate-termcolor \
bundled-rust-crate-terminal-size \
bundled-rust-crate-thin-vec \
bundled-rust-crate-thiserror \
bundled-rust-crate-thiserror-impl \
bundled-rust-crate-thread-local \
bundled-rust-crate-tikv-jemalloc-sys \
bundled-rust-crate-tikv-jemallocator \
bundled-rust-crate-time \
bundled-rust-crate-time-core \
bundled-rust-crate-time-macros \
bundled-rust-crate-tinystr \
bundled-rust-crate-tinyvec \
bundled-rust-crate-tinyvec-macros \
bundled-rust-crate-tokio \
bundled-rust-crate-tokio-macros \
bundled-rust-crate-tokio-rustls \
bundled-rust-crate-tokio-util \
bundled-rust-crate-tower \
bundled-rust-crate-tower-http \
bundled-rust-crate-tower-layer \
bundled-rust-crate-tower-lsp-server \
bundled-rust-crate-tower-service \
bundled-rust-crate-tracing \
bundled-rust-crate-tracing-appender \
bundled-rust-crate-tracing-attributes \
bundled-rust-crate-tracing-core \
bundled-rust-crate-tracing-log \
bundled-rust-crate-tracing-serde \
bundled-rust-crate-tracing-subscriber \
bundled-rust-crate-tracing-tree \
bundled-rust-crate-try-lock \
bundled-rust-crate-typeid \
bundled-rust-crate-unicase \
bundled-rust-crate-unicode-bom \
bundled-rust-crate-unicode-ident \
bundled-rust-crate-unicode-normalization \
bundled-rust-crate-unicode-segmentation \
bundled-rust-crate-unicode-width \
bundled-rust-crate-untrusted \
bundled-rust-crate-url \
bundled-rust-crate-urlencoding \
bundled-rust-crate-utf16-iter \
bundled-rust-crate-utf8-iter \
bundled-rust-crate-uuid \
bundled-rust-crate-version-check \
bundled-rust-crate-vte \
bundled-rust-crate-walkdir \
bundled-rust-crate-want \
bundled-rust-crate-web-time \
bundled-rust-crate-webpki-roots \
bundled-rust-crate-write16 \
bundled-rust-crate-writeable \
bundled-rust-crate-wyz \
bundled-rust-crate-yoke \
bundled-rust-crate-yoke-derive \
bundled-rust-crate-zerofrom \
bundled-rust-crate-zerofrom-derive \
bundled-rust-crate-zeroize \
bundled-rust-crate-zerovec \
bundled-rust-crate-zerovec-derive \
bundled-rust-crate-zmij"

RDEPENDS:${PN} += "libc.so.6 \
libgcc-s.so.1 \
libm.so.6"

inherit rpm
