SUMMARY = "Organize Data in Tables"
DESCRIPTION = "Organization of data in table form is a time-honored and useful method of \
data representation. While columns of data are trivially generated by \
computer through formatted output, even simple tasks like keeping titles \
aligned with the data columns are not trivial, and the one-shot solutions \
one comes up with tend to be particularly hard to maintain. Text::Table \
allows you to create and maintain tables that adapt to alignment \
requirements as you use them."
LICENSE = "ISC"

PV = "1.135"

RPM_NAME = "perl-Text-Table-1.135-1.18.noarch.rpm"
RPM_HASH = "f67d13f9e41f000a4a89859edebfe1e84bebb67e4fce6223423e6e1553223b418c5a0fe64d9517fc3ccd4ed08bd1dc3798a60bf2e602dab35a95220477f3804d"
REPO_ARCH = "noarch"

RPROVIDES:${PN} += "perl-Text--Table \
perl-Text-Table"

RDEPENDS:${PN} += "perl--MODULE-COMPAT-5.44.0 \
perl-Text--Aligner"

inherit rpm
