SUMMARY = "Adobe Flash Player emulator written in Rust"
DESCRIPTION = "Ruffle is an Adobe Flash Player emulator written in the Rust programming \
language. Ruffle targets both the desktop and the web using WebAssembly."
LICENSE = "Apache-2.0 | MIT"

PV = "0.4.1"

RPM_NAME = "ruffle-0.4.1-1.3.aarch64.rpm"
RPM_HASH = "9d7b1c5eff646690245fe4e89c0ef3e44652f120675614765fd9fdcc65cf7b2ca792b53c3709f7fa929a8655a17fb9eb4c44df646bf7ac95d2ebea7c5f64787d"

RPROVIDES:${PN} += "bundled-rust-crate-ab-glyph \
bundled-rust-crate-ab-glyph-rasterizer \
bundled-rust-crate-adler2 \
bundled-rust-crate-ahash \
bundled-rust-crate-aho-corasick \
bundled-rust-crate-allocator-api2 \
bundled-rust-crate-alsa \
bundled-rust-crate-alsa-sys \
bundled-rust-crate-annotate-snippets \
bundled-rust-crate-anstream \
bundled-rust-crate-anstyle \
bundled-rust-crate-anstyle-parse \
bundled-rust-crate-anstyle-query \
bundled-rust-crate-anyhow \
bundled-rust-crate-arboard \
bundled-rust-crate-arrayref \
bundled-rust-crate-arrayvec \
bundled-rust-crate-as-raw-xcb-connection \
bundled-rust-crate-asc \
bundled-rust-crate-ash \
bundled-rust-crate-ashpd \
bundled-rust-crate-async-broadcast \
bundled-rust-crate-async-channel \
bundled-rust-crate-async-io \
bundled-rust-crate-async-recursion \
bundled-rust-crate-async-task \
bundled-rust-crate-async-trait \
bundled-rust-crate-atomic-waker \
bundled-rust-crate-autocfg \
bundled-rust-crate-base64 \
bundled-rust-crate-bit-set \
bundled-rust-crate-bit-vec \
bundled-rust-crate-bitflags \
bundled-rust-crate-bitstream-io \
bundled-rust-crate-block-buffer \
bundled-rust-crate-bstr \
bundled-rust-crate-build-playerglobal \
bundled-rust-crate-bumpalo \
bundled-rust-crate-bytemuck \
bundled-rust-crate-bytemuck-derive \
bundled-rust-crate-byteorder \
bundled-rust-crate-byteorder-lite \
bundled-rust-crate-bytes \
bundled-rust-crate-bzip2 \
bundled-rust-crate-bzip2-sys \
bundled-rust-crate-calloop \
bundled-rust-crate-calloop-wayland-source \
bundled-rust-crate-camino \
bundled-rust-crate-cargo-metadata \
bundled-rust-crate-cargo-platform \
bundled-rust-crate-cc \
bundled-rust-crate-cfg-aliases \
bundled-rust-crate-cfg-if \
bundled-rust-crate-chardetng \
bundled-rust-crate-chrono \
bundled-rust-crate-clap \
bundled-rust-crate-clap-builder \
bundled-rust-crate-clap-derive \
bundled-rust-crate-clap-lex \
bundled-rust-crate-codespan-reporting \
bundled-rust-crate-color-quant \
bundled-rust-crate-colorchoice \
bundled-rust-crate-concurrent-queue \
bundled-rust-crate-convert-case \
bundled-rust-crate-cookie \
bundled-rust-crate-cookie-store \
bundled-rust-crate-core-maths \
bundled-rust-crate-cpal \
bundled-rust-crate-cpufeatures \
bundled-rust-crate-crc \
bundled-rust-crate-crc-catalog \
bundled-rust-crate-crc32fast \
bundled-rust-crate-crossbeam-channel \
bundled-rust-crate-crossbeam-deque \
bundled-rust-crate-crossbeam-epoch \
bundled-rust-crate-crossbeam-utils \
bundled-rust-crate-crypto-common \
bundled-rust-crate-cursor-icon \
bundled-rust-crate-darling \
bundled-rust-crate-darling-core \
bundled-rust-crate-darling-macro \
bundled-rust-crate-dasp \
bundled-rust-crate-dasp-envelope \
bundled-rust-crate-dasp-frame \
bundled-rust-crate-dasp-interpolate \
bundled-rust-crate-dasp-peak \
bundled-rust-crate-dasp-ring-buffer \
bundled-rust-crate-dasp-rms \
bundled-rust-crate-dasp-sample \
bundled-rust-crate-dasp-signal \
bundled-rust-crate-dasp-slice \
bundled-rust-crate-dasp-window \
bundled-rust-crate-deranged \
bundled-rust-crate-derive-builder \
bundled-rust-crate-derive-builder-core \
bundled-rust-crate-derive-builder-macro \
bundled-rust-crate-digest \
bundled-rust-crate-dirs \
bundled-rust-crate-dirs-sys \
bundled-rust-crate-displaydoc \
bundled-rust-crate-dlib \
bundled-rust-crate-document-features \
bundled-rust-crate-downcast-rs \
bundled-rust-crate-dpi \
bundled-rust-crate-ecolor \
bundled-rust-crate-egui \
bundled-rust-crate-egui-extras \
bundled-rust-crate-egui-wgpu \
bundled-rust-crate-egui-winit \
bundled-rust-crate-either \
bundled-rust-crate-emath \
bundled-rust-crate-encoding-rs \
bundled-rust-crate-endi \
bundled-rust-crate-enum-map \
bundled-rust-crate-enum-map-derive \
bundled-rust-crate-enumflags2 \
bundled-rust-crate-enumflags2-derive \
bundled-rust-crate-enumset \
bundled-rust-crate-enumset-derive \
bundled-rust-crate-epaint \
bundled-rust-crate-epaint-default-fonts \
bundled-rust-crate-equivalent \
bundled-rust-crate-errno \
bundled-rust-crate-euclid \
bundled-rust-crate-event-listener \
bundled-rust-crate-event-listener-strategy \
bundled-rust-crate-fastrand \
bundled-rust-crate-fax \
bundled-rust-crate-fdeflate \
bundled-rust-crate-find-msvc-tools \
bundled-rust-crate-flash-lso \
bundled-rust-crate-flate2 \
bundled-rust-crate-float-next-after \
bundled-rust-crate-fluent-bundle \
bundled-rust-crate-fluent-langneg \
bundled-rust-crate-fluent-syntax \
bundled-rust-crate-fluent-template-macros \
bundled-rust-crate-fluent-templates \
bundled-rust-crate-flume \
bundled-rust-crate-flv-rs \
bundled-rust-crate-fnv \
bundled-rust-crate-foldhash \
bundled-rust-crate-fontconfig \
bundled-rust-crate-fontconfig-parser \
bundled-rust-crate-fontdb \
bundled-rust-crate-foreign-types \
bundled-rust-crate-foreign-types-shared \
bundled-rust-crate-form-urlencoded \
bundled-rust-crate-futures \
bundled-rust-crate-futures-channel \
bundled-rust-crate-futures-core \
bundled-rust-crate-futures-executor \
bundled-rust-crate-futures-io \
bundled-rust-crate-futures-lite \
bundled-rust-crate-futures-macro \
bundled-rust-crate-futures-sink \
bundled-rust-crate-futures-task \
bundled-rust-crate-futures-util \
bundled-rust-crate-gc-arena \
bundled-rust-crate-gc-arena-derive \
bundled-rust-crate-generic-array \
bundled-rust-crate-gethostname \
bundled-rust-crate-getrandom \
bundled-rust-crate-gif \
bundled-rust-crate-gilrs \
bundled-rust-crate-gilrs-core \
bundled-rust-crate-globset \
bundled-rust-crate-glow \
bundled-rust-crate-gpu-alloc \
bundled-rust-crate-gpu-alloc-types \
bundled-rust-crate-gpu-descriptor \
bundled-rust-crate-gpu-descriptor-types \
bundled-rust-crate-h2 \
bundled-rust-crate-h263-rs \
bundled-rust-crate-h263-rs-deblock \
bundled-rust-crate-h263-rs-yuv \
bundled-rust-crate-half \
bundled-rust-crate-hashbrown \
bundled-rust-crate-heck \
bundled-rust-crate-hex \
bundled-rust-crate-hexf-parse \
bundled-rust-crate-http \
bundled-rust-crate-http-body \
bundled-rust-crate-http-body-util \
bundled-rust-crate-httparse \
bundled-rust-crate-hyper \
bundled-rust-crate-hyper-rustls \
bundled-rust-crate-hyper-tls \
bundled-rust-crate-hyper-util \
bundled-rust-crate-iana-time-zone \
bundled-rust-crate-id3 \
bundled-rust-crate-ident-case \
bundled-rust-crate-idna \
bundled-rust-crate-idna-adapter \
bundled-rust-crate-ignore \
bundled-rust-crate-image \
bundled-rust-crate-indexmap \
bundled-rust-crate-inotify \
bundled-rust-crate-inotify-sys \
bundled-rust-crate-intl-memoizer \
bundled-rust-crate-intl-pluralrules \
bundled-rust-crate-ipnet \
bundled-rust-crate-is-terminal-polyfill \
bundled-rust-crate-itertools \
bundled-rust-crate-itoa \
bundled-rust-crate-jobserver \
bundled-rust-crate-jpeg-decoder \
bundled-rust-crate-js-sys \
bundled-rust-crate-khronos-egl \
bundled-rust-crate-lazy-static \
bundled-rust-crate-libbz2-rs-sys \
bundled-rust-crate-libc \
bundled-rust-crate-libloading \
bundled-rust-crate-libm \
bundled-rust-crate-libudev-sys \
bundled-rust-crate-linkme \
bundled-rust-crate-linkme-impl \
bundled-rust-crate-linux-raw-sys \
bundled-rust-crate-litrs \
bundled-rust-crate-lock-api \
bundled-rust-crate-log \
bundled-rust-crate-lru \
bundled-rust-crate-lyon \
bundled-rust-crate-lyon-algorithms \
bundled-rust-crate-lyon-geom \
bundled-rust-crate-lyon-path \
bundled-rust-crate-lyon-tessellation \
bundled-rust-crate-lzma-rs \
bundled-rust-crate-matchers \
bundled-rust-crate-memchr \
bundled-rust-crate-memmap2 \
bundled-rust-crate-mime \
bundled-rust-crate-miniz-oxide \
bundled-rust-crate-mio \
bundled-rust-crate-moxcms \
bundled-rust-crate-naga \
bundled-rust-crate-naga-agal \
bundled-rust-crate-naga-pixelbender \
bundled-rust-crate-native-tls \
bundled-rust-crate-nellymoser-rs \
bundled-rust-crate-nihav-codec-support \
bundled-rust-crate-nihav-core \
bundled-rust-crate-nihav-duck \
bundled-rust-crate-nix \
bundled-rust-crate-no-std-io2 \
bundled-rust-crate-nohash-hasher \
bundled-rust-crate-nom \
bundled-rust-crate-nu-ansi-term \
bundled-rust-crate-num-bigint \
bundled-rust-crate-num-complex \
bundled-rust-crate-num-conv \
bundled-rust-crate-num-derive \
bundled-rust-crate-num-integer \
bundled-rust-crate-num-threads \
bundled-rust-crate-num-traits \
bundled-rust-crate-once-cell \
bundled-rust-crate-openssl \
bundled-rust-crate-openssl-macros \
bundled-rust-crate-openssl-probe \
bundled-rust-crate-openssl-sys \
bundled-rust-crate-option-ext \
bundled-rust-crate-ordered-float \
bundled-rust-crate-ordered-stream \
bundled-rust-crate-os-info \
bundled-rust-crate-owned-ttf-parser \
bundled-rust-crate-parking \
bundled-rust-crate-parking-lot \
bundled-rust-crate-parking-lot-core \
bundled-rust-crate-percent-encoding \
bundled-rust-crate-pest \
bundled-rust-crate-pest-derive \
bundled-rust-crate-pest-generator \
bundled-rust-crate-pest-meta \
bundled-rust-crate-pin-project-lite \
bundled-rust-crate-pixel-bender \
bundled-rust-crate-pkg-config \
bundled-rust-crate-png \
bundled-rust-crate-polling \
bundled-rust-crate-pollster \
bundled-rust-crate-powerfmt \
bundled-rust-crate-ppv-lite86 \
bundled-rust-crate-primal-check \
bundled-rust-crate-proc-macro-crate \
bundled-rust-crate-proc-macro-hack \
bundled-rust-crate-proc-macro2 \
bundled-rust-crate-profiling \
bundled-rust-crate-psl-types \
bundled-rust-crate-publicsuffix \
bundled-rust-crate-pxfm \
bundled-rust-crate-quick-error \
bundled-rust-crate-quick-xml \
bundled-rust-crate-quote \
bundled-rust-crate-rand \
bundled-rust-crate-rand-chacha \
bundled-rust-crate-rand-core \
bundled-rust-crate-rascal \
bundled-rust-crate-raw-window-handle \
bundled-rust-crate-rayon \
bundled-rust-crate-rayon-core \
bundled-rust-crate-realfft \
bundled-rust-crate-regex \
bundled-rust-crate-regex-automata \
bundled-rust-crate-regex-syntax \
bundled-rust-crate-regress \
bundled-rust-crate-renderdoc-sys \
bundled-rust-crate-reqwest \
bundled-rust-crate-rfd \
bundled-rust-crate-ring \
bundled-rust-crate-roxmltree \
bundled-rust-crate-ruffle-common \
bundled-rust-crate-ruffle-core \
bundled-rust-crate-ruffle-desktop \
bundled-rust-crate-ruffle-frontend-utils \
bundled-rust-crate-ruffle-macros \
bundled-rust-crate-ruffle-render \
bundled-rust-crate-ruffle-render-wgpu \
bundled-rust-crate-ruffle-video \
bundled-rust-crate-ruffle-video-external \
bundled-rust-crate-ruffle-video-software \
bundled-rust-crate-ruffle-wstr \
bundled-rust-crate-rustc-hash \
bundled-rust-crate-rustdct \
bundled-rust-crate-rustfft \
bundled-rust-crate-rustix \
bundled-rust-crate-rustls \
bundled-rust-crate-rustls-pki-types \
bundled-rust-crate-rustls-webpki \
bundled-rust-crate-rustversion \
bundled-rust-crate-ryu \
bundled-rust-crate-safe-arch \
bundled-rust-crate-same-file \
bundled-rust-crate-scoped-tls \
bundled-rust-crate-scopeguard \
bundled-rust-crate-sctk-adwaita \
bundled-rust-crate-self-cell \
bundled-rust-crate-semver \
bundled-rust-crate-serde \
bundled-rust-crate-serde-core \
bundled-rust-crate-serde-derive \
bundled-rust-crate-serde-json \
bundled-rust-crate-serde-repr \
bundled-rust-crate-serde-spanned \
bundled-rust-crate-serde-urlencoded \
bundled-rust-crate-sha2 \
bundled-rust-crate-sharded-slab \
bundled-rust-crate-shlex \
bundled-rust-crate-signal-hook-registry \
bundled-rust-crate-simd-adler32 \
bundled-rust-crate-simple-asn1 \
bundled-rust-crate-slab \
bundled-rust-crate-slotmap \
bundled-rust-crate-smallvec \
bundled-rust-crate-smithay-client-toolkit \
bundled-rust-crate-smithay-clipboard \
bundled-rust-crate-smol-str \
bundled-rust-crate-socket2 \
bundled-rust-crate-spin \
bundled-rust-crate-spirv \
bundled-rust-crate-static-assertions \
bundled-rust-crate-strength-reduce \
bundled-rust-crate-strict-num \
bundled-rust-crate-strsim \
bundled-rust-crate-subtle \
bundled-rust-crate-swf \
bundled-rust-crate-symlink \
bundled-rust-crate-symphonia \
bundled-rust-crate-symphonia-bundle-mp3 \
bundled-rust-crate-symphonia-codec-aac \
bundled-rust-crate-symphonia-core \
bundled-rust-crate-symphonia-metadata \
bundled-rust-crate-syn \
bundled-rust-crate-sync-wrapper \
bundled-rust-crate-synstructure \
bundled-rust-crate-sys-locale \
bundled-rust-crate-tempfile \
bundled-rust-crate-termcolor \
bundled-rust-crate-terminal-size \
bundled-rust-crate-thiserror \
bundled-rust-crate-thiserror-impl \
bundled-rust-crate-thread-local \
bundled-rust-crate-tiff \
bundled-rust-crate-time \
bundled-rust-crate-time-core \
bundled-rust-crate-time-macros \
bundled-rust-crate-tiny-skia \
bundled-rust-crate-tiny-skia-path \
bundled-rust-crate-tinystr \
bundled-rust-crate-tinyvec \
bundled-rust-crate-tinyvec-macros \
bundled-rust-crate-tokio \
bundled-rust-crate-tokio-macros \
bundled-rust-crate-tokio-native-tls \
bundled-rust-crate-tokio-rustls \
bundled-rust-crate-tokio-util \
bundled-rust-crate-toml \
bundled-rust-crate-toml-datetime \
bundled-rust-crate-toml-edit \
bundled-rust-crate-toml-parser \
bundled-rust-crate-toml-writer \
bundled-rust-crate-tower \
bundled-rust-crate-tower-http \
bundled-rust-crate-tower-layer \
bundled-rust-crate-tower-service \
bundled-rust-crate-tracing \
bundled-rust-crate-tracing-appender \
bundled-rust-crate-tracing-attributes \
bundled-rust-crate-tracing-core \
bundled-rust-crate-tracing-log \
bundled-rust-crate-tracing-subscriber \
bundled-rust-crate-tracing-wasm \
bundled-rust-crate-transpose \
bundled-rust-crate-try-lock \
bundled-rust-crate-ttf-parser \
bundled-rust-crate-type-map \
bundled-rust-crate-typed-path \
bundled-rust-crate-typenum \
bundled-rust-crate-ucd-trie \
bundled-rust-crate-unic-langid \
bundled-rust-crate-unic-langid-impl \
bundled-rust-crate-unic-langid-macros \
bundled-rust-crate-unic-langid-macros-impl \
bundled-rust-crate-unicode-bidi \
bundled-rust-crate-unicode-ident \
bundled-rust-crate-unicode-segmentation \
bundled-rust-crate-unicode-width \
bundled-rust-crate-untrusted \
bundled-rust-crate-url \
bundled-rust-crate-urlencoding \
bundled-rust-crate-utf8-iter \
bundled-rust-crate-utf8parse \
bundled-rust-crate-uuid \
bundled-rust-crate-vcpkg \
bundled-rust-crate-vec-map \
bundled-rust-crate-vergen \
bundled-rust-crate-vergen-gitcl \
bundled-rust-crate-vergen-lib \
bundled-rust-crate-version-check \
bundled-rust-crate-walkdir \
bundled-rust-crate-want \
bundled-rust-crate-wasm-bindgen \
bundled-rust-crate-wasm-bindgen-macro \
bundled-rust-crate-wasm-bindgen-macro-support \
bundled-rust-crate-wasm-bindgen-shared \
bundled-rust-crate-wayland-backend \
bundled-rust-crate-wayland-client \
bundled-rust-crate-wayland-csd-frame \
bundled-rust-crate-wayland-cursor \
bundled-rust-crate-wayland-protocols \
bundled-rust-crate-wayland-protocols-plasma \
bundled-rust-crate-wayland-protocols-wlr \
bundled-rust-crate-wayland-scanner \
bundled-rust-crate-wayland-sys \
bundled-rust-crate-weak-table \
bundled-rust-crate-web-sys \
bundled-rust-crate-web-time \
bundled-rust-crate-webbrowser \
bundled-rust-crate-weezl \
bundled-rust-crate-wgpu \
bundled-rust-crate-wgpu-core \
bundled-rust-crate-wgpu-core-deps-windows-linux-android \
bundled-rust-crate-wgpu-hal \
bundled-rust-crate-wgpu-types \
bundled-rust-crate-wide \
bundled-rust-crate-winit \
bundled-rust-crate-winnow \
bundled-rust-crate-winresource \
bundled-rust-crate-x11-dl \
bundled-rust-crate-x11rb \
bundled-rust-crate-x11rb-protocol \
bundled-rust-crate-xcursor \
bundled-rust-crate-xkbcommon-dl \
bundled-rust-crate-xkeysym \
bundled-rust-crate-yeslogic-fontconfig-sys \
bundled-rust-crate-zbus \
bundled-rust-crate-zbus-macros \
bundled-rust-crate-zbus-names \
bundled-rust-crate-zerocopy \
bundled-rust-crate-zerocopy-derive \
bundled-rust-crate-zerofrom \
bundled-rust-crate-zeroize \
bundled-rust-crate-zerovec \
bundled-rust-crate-zip \
bundled-rust-crate-zlib-rs \
bundled-rust-crate-zmij \
bundled-rust-crate-zopfli \
bundled-rust-crate-zune-core \
bundled-rust-crate-zune-jpeg \
bundled-rust-crate-zvariant \
bundled-rust-crate-zvariant-derive \
bundled-rust-crate-zvariant-utils \
ruffle"

RDEPENDS:${PN} += "libasound.so.2 \
libc.so.6 \
libcrypto.so.3 \
libfontconfig.so.1 \
libgcc-s.so.1 \
libm.so.6 \
libssl.so.3 \
libudev.so.1"

inherit rpm
