SUMMARY = "Support for IBM Plex fonts"
DESCRIPTION = "The package provides LaTeX, pdfLaTeX, XeLaTeX and LuaLaTeX \
support for the IBM Plex families of fonts. Serif, Sans and \
Mono families are available in eight weights: Regular, Light, \
ExtraLight, Thin, Bold, Text, Medium and SemiBold (with \
corresponding italics)."
LICENSE = "OFL-1.1"

PV = "2026.226.svn77682"

RPM_NAME = "texlive-plex-2026.226.svn77682-59.2.noarch.rpm"
RPM_HASH = "c8e84423c445397ab298f0a79447d553ee77ab3e7d11187184aea6c2588bfd67a1bbc4fe3015505f4420e4c35176d23a28921eb5414a61965d2567c09b8c183d"
REPO_ARCH = "noarch"

RPROVIDES:${PN} += "tex-LGRplxSans-Sup.fd \
tex-LGRplxSans-TLF.fd \
tex-LGRplxSans-TOsF.fd \
tex-LGRplxSerif-Sup.fd \
tex-LGRplxSerif-TLF.fd \
tex-LGRplxSerif-TOsF.fd \
tex-LY1plxMono-Sup.fd \
tex-LY1plxMono-TLF.fd \
tex-LY1plxMono-TOsF.fd \
tex-LY1plxSans-Sup.fd \
tex-LY1plxSans-TLF.fd \
tex-LY1plxSans-TOsF.fd \
tex-LY1plxSerif-Sup.fd \
tex-LY1plxSerif-TLF.fd \
tex-LY1plxSerif-TOsF.fd \
tex-OT1plxMono-Sup.fd \
tex-OT1plxMono-TLF.fd \
tex-OT1plxMono-TOsF.fd \
tex-OT1plxSans-Sup.fd \
tex-OT1plxSans-TLF.fd \
tex-OT1plxSans-TOsF.fd \
tex-OT1plxSerif-Sup.fd \
tex-OT1plxSerif-TLF.fd \
tex-OT1plxSerif-TOsF.fd \
tex-T1plxMono-Sup.fd \
tex-T1plxMono-TLF.fd \
tex-T1plxMono-TOsF.fd \
tex-T1plxSans-Sup.fd \
tex-T1plxSans-TLF.fd \
tex-T1plxSans-TOsF.fd \
tex-T1plxSerif-Sup.fd \
tex-T1plxSerif-TLF.fd \
tex-T1plxSerif-TOsF.fd \
tex-TS1plxMono-TLF.fd \
tex-TS1plxMono-TOsF.fd \
tex-TS1plxSans-TLF.fd \
tex-TS1plxSans-TOsF.fd \
tex-TS1plxSerif-TLF.fd \
tex-TS1plxSerif-TOsF.fd \
tex-plex-mono.sty \
tex-plex-sans.sty \
tex-plex-serif.sty \
tex-plex.map \
tex-plx-2jqefy.enc \
tex-plx-2lh64x.enc \
tex-plx-5wdxh7.enc \
tex-plx-6tuc4c.enc \
tex-plx-abnabb.enc \
tex-plx-arhv23.enc \
tex-plx-aytvzj.enc \
tex-plx-bb73my.enc \
tex-plx-be3ach.enc \
tex-plx-bigt6c.enc \
tex-plx-bw3vxo.enc \
tex-plx-cj5svl.enc \
tex-plx-ecciqp.enc \
tex-plx-errukl.enc \
tex-plx-gc6afx.enc \
tex-plx-gmchnq.enc \
tex-plx-h3p6bl.enc \
tex-plx-jbbrju.enc \
tex-plx-koxhod.enc \
tex-plx-lfnaaq.enc \
tex-plx-lxmhqh.enc \
tex-plx-mr3nck.enc \
tex-plx-nercej.enc \
tex-plx-nzsfse.enc \
tex-plx-qnq2j3.enc \
tex-plx-qtqx7y.enc \
tex-plx-rusc4d.enc \
tex-plx-sebx3h.enc \
tex-plx-umrhwx.enc \
tex-plx-zg2afo.enc \
tex-plxMono-Bold-sup-ly1.tfm \
tex-plxMono-Bold-sup-ot1.tfm \
tex-plxMono-Bold-sup-t1--base.tfm \
tex-plxMono-Bold-sup-t1.tfm \
tex-plxMono-Bold-sup-t1.vf \
tex-plxMono-Bold-tlf-ly1.tfm \
tex-plxMono-Bold-tlf-ot1.tfm \
tex-plxMono-Bold-tlf-t1--base.tfm \
tex-plxMono-Bold-tlf-t1.tfm \
tex-plxMono-Bold-tlf-t1.vf \
tex-plxMono-Bold-tlf-ts1--base.tfm \
tex-plxMono-Bold-tlf-ts1.tfm \
tex-plxMono-Bold-tlf-ts1.vf \
tex-plxMono-Bold-tosf-ly1.tfm \
tex-plxMono-Bold-tosf-ot1.tfm \
tex-plxMono-Bold-tosf-t1--base.tfm \
tex-plxMono-Bold-tosf-t1.tfm \
tex-plxMono-Bold-tosf-t1.vf \
tex-plxMono-Bold-tosf-ts1--base.tfm \
tex-plxMono-Bold-tosf-ts1.tfm \
tex-plxMono-Bold-tosf-ts1.vf \
tex-plxMono-BoldItalic-sup-ly1.tfm \
tex-plxMono-BoldItalic-sup-ot1.tfm \
tex-plxMono-BoldItalic-sup-t1--base.tfm \
tex-plxMono-BoldItalic-sup-t1.tfm \
tex-plxMono-BoldItalic-sup-t1.vf \
tex-plxMono-BoldItalic-tlf-ly1.tfm \
tex-plxMono-BoldItalic-tlf-ot1.tfm \
tex-plxMono-BoldItalic-tlf-t1--base.tfm \
tex-plxMono-BoldItalic-tlf-t1.tfm \
tex-plxMono-BoldItalic-tlf-t1.vf \
tex-plxMono-BoldItalic-tlf-ts1--base.tfm \
tex-plxMono-BoldItalic-tlf-ts1.tfm \
tex-plxMono-BoldItalic-tlf-ts1.vf \
tex-plxMono-BoldItalic-tosf-ly1.tfm \
tex-plxMono-BoldItalic-tosf-ot1.tfm \
tex-plxMono-BoldItalic-tosf-t1--base.tfm \
tex-plxMono-BoldItalic-tosf-t1.tfm \
tex-plxMono-BoldItalic-tosf-t1.vf \
tex-plxMono-BoldItalic-tosf-ts1--base.tfm \
tex-plxMono-BoldItalic-tosf-ts1.tfm \
tex-plxMono-BoldItalic-tosf-ts1.vf \
tex-plxMono-ExtLt-sup-ly1.tfm \
tex-plxMono-ExtLt-sup-ot1.tfm \
tex-plxMono-ExtLt-sup-t1--base.tfm \
tex-plxMono-ExtLt-sup-t1.tfm \
tex-plxMono-ExtLt-sup-t1.vf \
tex-plxMono-ExtLt-tlf-ly1.tfm \
tex-plxMono-ExtLt-tlf-ot1.tfm \
tex-plxMono-ExtLt-tlf-t1--base.tfm \
tex-plxMono-ExtLt-tlf-t1.tfm \
tex-plxMono-ExtLt-tlf-t1.vf \
tex-plxMono-ExtLt-tlf-ts1--base.tfm \
tex-plxMono-ExtLt-tlf-ts1.tfm \
tex-plxMono-ExtLt-tlf-ts1.vf \
tex-plxMono-ExtLt-tosf-ly1.tfm \
tex-plxMono-ExtLt-tosf-ot1.tfm \
tex-plxMono-ExtLt-tosf-t1--base.tfm \
tex-plxMono-ExtLt-tosf-t1.tfm \
tex-plxMono-ExtLt-tosf-t1.vf \
tex-plxMono-ExtLt-tosf-ts1--base.tfm \
tex-plxMono-ExtLt-tosf-ts1.tfm \
tex-plxMono-ExtLt-tosf-ts1.vf \
tex-plxMono-ExtLtItalic-sup-ly1.tfm \
tex-plxMono-ExtLtItalic-sup-ot1.tfm \
tex-plxMono-ExtLtItalic-sup-t1--base.tfm \
tex-plxMono-ExtLtItalic-sup-t1.tfm \
tex-plxMono-ExtLtItalic-sup-t1.vf \
tex-plxMono-ExtLtItalic-tlf-ly1.tfm \
tex-plxMono-ExtLtItalic-tlf-ot1.tfm \
tex-plxMono-ExtLtItalic-tlf-t1--base.tfm \
tex-plxMono-ExtLtItalic-tlf-t1.tfm \
tex-plxMono-ExtLtItalic-tlf-t1.vf \
tex-plxMono-ExtLtItalic-tlf-ts1--base.tfm \
tex-plxMono-ExtLtItalic-tlf-ts1.tfm \
tex-plxMono-ExtLtItalic-tlf-ts1.vf \
tex-plxMono-ExtLtItalic-tosf-ly1.tfm \
tex-plxMono-ExtLtItalic-tosf-ot1.tfm \
tex-plxMono-ExtLtItalic-tosf-t1--base.tfm \
tex-plxMono-ExtLtItalic-tosf-t1.tfm \
tex-plxMono-ExtLtItalic-tosf-t1.vf \
tex-plxMono-ExtLtItalic-tosf-ts1--base.tfm \
tex-plxMono-ExtLtItalic-tosf-ts1.tfm \
tex-plxMono-ExtLtItalic-tosf-ts1.vf \
tex-plxMono-Italic-sup-ly1.tfm \
tex-plxMono-Italic-sup-ot1.tfm \
tex-plxMono-Italic-sup-t1--base.tfm \
tex-plxMono-Italic-sup-t1.tfm \
tex-plxMono-Italic-sup-t1.vf \
tex-plxMono-Italic-tlf-ly1.tfm \
tex-plxMono-Italic-tlf-ot1.tfm \
tex-plxMono-Italic-tlf-t1--base.tfm \
tex-plxMono-Italic-tlf-t1.tfm \
tex-plxMono-Italic-tlf-t1.vf \
tex-plxMono-Italic-tlf-ts1--base.tfm \
tex-plxMono-Italic-tlf-ts1.tfm \
tex-plxMono-Italic-tlf-ts1.vf \
tex-plxMono-Italic-tosf-ly1.tfm \
tex-plxMono-Italic-tosf-ot1.tfm \
tex-plxMono-Italic-tosf-t1--base.tfm \
tex-plxMono-Italic-tosf-t1.tfm \
tex-plxMono-Italic-tosf-t1.vf \
tex-plxMono-Italic-tosf-ts1--base.tfm \
tex-plxMono-Italic-tosf-ts1.tfm \
tex-plxMono-Italic-tosf-ts1.vf \
tex-plxMono-Light-sup-ly1.tfm \
tex-plxMono-Light-sup-ot1.tfm \
tex-plxMono-Light-sup-t1--base.tfm \
tex-plxMono-Light-sup-t1.tfm \
tex-plxMono-Light-sup-t1.vf \
tex-plxMono-Light-tlf-ly1.tfm \
tex-plxMono-Light-tlf-ot1.tfm \
tex-plxMono-Light-tlf-t1--base.tfm \
tex-plxMono-Light-tlf-t1.tfm \
tex-plxMono-Light-tlf-t1.vf \
tex-plxMono-Light-tlf-ts1--base.tfm \
tex-plxMono-Light-tlf-ts1.tfm \
tex-plxMono-Light-tlf-ts1.vf \
tex-plxMono-Light-tosf-ly1.tfm \
tex-plxMono-Light-tosf-ot1.tfm \
tex-plxMono-Light-tosf-t1--base.tfm \
tex-plxMono-Light-tosf-t1.tfm \
tex-plxMono-Light-tosf-t1.vf \
tex-plxMono-Light-tosf-ts1--base.tfm \
tex-plxMono-Light-tosf-ts1.tfm \
tex-plxMono-Light-tosf-ts1.vf \
tex-plxMono-LightItalic-sup-ly1.tfm \
tex-plxMono-LightItalic-sup-ot1.tfm \
tex-plxMono-LightItalic-sup-t1--base.tfm \
tex-plxMono-LightItalic-sup-t1.tfm \
tex-plxMono-LightItalic-sup-t1.vf \
tex-plxMono-LightItalic-tlf-ly1.tfm \
tex-plxMono-LightItalic-tlf-ot1.tfm \
tex-plxMono-LightItalic-tlf-t1--base.tfm \
tex-plxMono-LightItalic-tlf-t1.tfm \
tex-plxMono-LightItalic-tlf-t1.vf \
tex-plxMono-LightItalic-tlf-ts1--base.tfm \
tex-plxMono-LightItalic-tlf-ts1.tfm \
tex-plxMono-LightItalic-tlf-ts1.vf \
tex-plxMono-LightItalic-tosf-ly1.tfm \
tex-plxMono-LightItalic-tosf-ot1.tfm \
tex-plxMono-LightItalic-tosf-t1--base.tfm \
tex-plxMono-LightItalic-tosf-t1.tfm \
tex-plxMono-LightItalic-tosf-t1.vf \
tex-plxMono-LightItalic-tosf-ts1--base.tfm \
tex-plxMono-LightItalic-tosf-ts1.tfm \
tex-plxMono-LightItalic-tosf-ts1.vf \
tex-plxMono-Medm-sup-ly1.tfm \
tex-plxMono-Medm-sup-ot1.tfm \
tex-plxMono-Medm-sup-t1--base.tfm \
tex-plxMono-Medm-sup-t1.tfm \
tex-plxMono-Medm-sup-t1.vf \
tex-plxMono-Medm-tlf-ly1.tfm \
tex-plxMono-Medm-tlf-ot1.tfm \
tex-plxMono-Medm-tlf-t1--base.tfm \
tex-plxMono-Medm-tlf-t1.tfm \
tex-plxMono-Medm-tlf-t1.vf \
tex-plxMono-Medm-tlf-ts1--base.tfm \
tex-plxMono-Medm-tlf-ts1.tfm \
tex-plxMono-Medm-tlf-ts1.vf \
tex-plxMono-Medm-tosf-ly1.tfm \
tex-plxMono-Medm-tosf-ot1.tfm \
tex-plxMono-Medm-tosf-t1--base.tfm \
tex-plxMono-Medm-tosf-t1.tfm \
tex-plxMono-Medm-tosf-t1.vf \
tex-plxMono-Medm-tosf-ts1--base.tfm \
tex-plxMono-Medm-tosf-ts1.tfm \
tex-plxMono-Medm-tosf-ts1.vf \
tex-plxMono-MedmItalic-sup-ly1.tfm \
tex-plxMono-MedmItalic-sup-ot1.tfm \
tex-plxMono-MedmItalic-sup-t1--base.tfm \
tex-plxMono-MedmItalic-sup-t1.tfm \
tex-plxMono-MedmItalic-sup-t1.vf \
tex-plxMono-MedmItalic-tlf-ly1.tfm \
tex-plxMono-MedmItalic-tlf-ot1.tfm \
tex-plxMono-MedmItalic-tlf-t1--base.tfm \
tex-plxMono-MedmItalic-tlf-t1.tfm \
tex-plxMono-MedmItalic-tlf-t1.vf \
tex-plxMono-MedmItalic-tlf-ts1--base.tfm \
tex-plxMono-MedmItalic-tlf-ts1.tfm \
tex-plxMono-MedmItalic-tlf-ts1.vf \
tex-plxMono-MedmItalic-tosf-ly1.tfm \
tex-plxMono-MedmItalic-tosf-ot1.tfm \
tex-plxMono-MedmItalic-tosf-t1--base.tfm \
tex-plxMono-MedmItalic-tosf-t1.tfm \
tex-plxMono-MedmItalic-tosf-t1.vf \
tex-plxMono-MedmItalic-tosf-ts1--base.tfm \
tex-plxMono-MedmItalic-tosf-ts1.tfm \
tex-plxMono-MedmItalic-tosf-ts1.vf \
tex-plxMono-SmBld-sup-ly1.tfm \
tex-plxMono-SmBld-sup-ot1.tfm \
tex-plxMono-SmBld-sup-t1--base.tfm \
tex-plxMono-SmBld-sup-t1.tfm \
tex-plxMono-SmBld-sup-t1.vf \
tex-plxMono-SmBld-tlf-ly1.tfm \
tex-plxMono-SmBld-tlf-ot1.tfm \
tex-plxMono-SmBld-tlf-t1--base.tfm \
tex-plxMono-SmBld-tlf-t1.tfm \
tex-plxMono-SmBld-tlf-t1.vf \
tex-plxMono-SmBld-tlf-ts1--base.tfm \
tex-plxMono-SmBld-tlf-ts1.tfm \
tex-plxMono-SmBld-tlf-ts1.vf \
tex-plxMono-SmBld-tosf-ly1.tfm \
tex-plxMono-SmBld-tosf-ot1.tfm \
tex-plxMono-SmBld-tosf-t1--base.tfm \
tex-plxMono-SmBld-tosf-t1.tfm \
tex-plxMono-SmBld-tosf-t1.vf \
tex-plxMono-SmBld-tosf-ts1--base.tfm \
tex-plxMono-SmBld-tosf-ts1.tfm \
tex-plxMono-SmBld-tosf-ts1.vf \
tex-plxMono-SmBldItalic-sup-ly1.tfm \
tex-plxMono-SmBldItalic-sup-ot1.tfm \
tex-plxMono-SmBldItalic-sup-t1--base.tfm \
tex-plxMono-SmBldItalic-sup-t1.tfm \
tex-plxMono-SmBldItalic-sup-t1.vf \
tex-plxMono-SmBldItalic-tlf-ly1.tfm \
tex-plxMono-SmBldItalic-tlf-ot1.tfm \
tex-plxMono-SmBldItalic-tlf-t1--base.tfm \
tex-plxMono-SmBldItalic-tlf-t1.tfm \
tex-plxMono-SmBldItalic-tlf-t1.vf \
tex-plxMono-SmBldItalic-tlf-ts1--base.tfm \
tex-plxMono-SmBldItalic-tlf-ts1.tfm \
tex-plxMono-SmBldItalic-tlf-ts1.vf \
tex-plxMono-SmBldItalic-tosf-ly1.tfm \
tex-plxMono-SmBldItalic-tosf-ot1.tfm \
tex-plxMono-SmBldItalic-tosf-t1--base.tfm \
tex-plxMono-SmBldItalic-tosf-t1.tfm \
tex-plxMono-SmBldItalic-tosf-t1.vf \
tex-plxMono-SmBldItalic-tosf-ts1--base.tfm \
tex-plxMono-SmBldItalic-tosf-ts1.tfm \
tex-plxMono-SmBldItalic-tosf-ts1.vf \
tex-plxMono-Text-sup-ly1.tfm \
tex-plxMono-Text-sup-ot1.tfm \
tex-plxMono-Text-sup-t1--base.tfm \
tex-plxMono-Text-sup-t1.tfm \
tex-plxMono-Text-sup-t1.vf \
tex-plxMono-Text-tlf-ly1.tfm \
tex-plxMono-Text-tlf-ot1.tfm \
tex-plxMono-Text-tlf-t1--base.tfm \
tex-plxMono-Text-tlf-t1.tfm \
tex-plxMono-Text-tlf-t1.vf \
tex-plxMono-Text-tlf-ts1--base.tfm \
tex-plxMono-Text-tlf-ts1.tfm \
tex-plxMono-Text-tlf-ts1.vf \
tex-plxMono-Text-tosf-ly1.tfm \
tex-plxMono-Text-tosf-ot1.tfm \
tex-plxMono-Text-tosf-t1--base.tfm \
tex-plxMono-Text-tosf-t1.tfm \
tex-plxMono-Text-tosf-t1.vf \
tex-plxMono-Text-tosf-ts1--base.tfm \
tex-plxMono-Text-tosf-ts1.tfm \
tex-plxMono-Text-tosf-ts1.vf \
tex-plxMono-TextItalic-sup-ly1.tfm \
tex-plxMono-TextItalic-sup-ot1.tfm \
tex-plxMono-TextItalic-sup-t1--base.tfm \
tex-plxMono-TextItalic-sup-t1.tfm \
tex-plxMono-TextItalic-sup-t1.vf \
tex-plxMono-TextItalic-tlf-ly1.tfm \
tex-plxMono-TextItalic-tlf-ot1.tfm \
tex-plxMono-TextItalic-tlf-t1--base.tfm \
tex-plxMono-TextItalic-tlf-t1.tfm \
tex-plxMono-TextItalic-tlf-t1.vf \
tex-plxMono-TextItalic-tlf-ts1--base.tfm \
tex-plxMono-TextItalic-tlf-ts1.tfm \
tex-plxMono-TextItalic-tlf-ts1.vf \
tex-plxMono-TextItalic-tosf-ly1.tfm \
tex-plxMono-TextItalic-tosf-ot1.tfm \
tex-plxMono-TextItalic-tosf-t1--base.tfm \
tex-plxMono-TextItalic-tosf-t1.tfm \
tex-plxMono-TextItalic-tosf-t1.vf \
tex-plxMono-TextItalic-tosf-ts1--base.tfm \
tex-plxMono-TextItalic-tosf-ts1.tfm \
tex-plxMono-TextItalic-tosf-ts1.vf \
tex-plxMono-Thin-sup-ly1.tfm \
tex-plxMono-Thin-sup-ot1.tfm \
tex-plxMono-Thin-sup-t1--base.tfm \
tex-plxMono-Thin-sup-t1.tfm \
tex-plxMono-Thin-sup-t1.vf \
tex-plxMono-Thin-tlf-ly1.tfm \
tex-plxMono-Thin-tlf-ot1.tfm \
tex-plxMono-Thin-tlf-t1--base.tfm \
tex-plxMono-Thin-tlf-t1.tfm \
tex-plxMono-Thin-tlf-t1.vf \
tex-plxMono-Thin-tlf-ts1--base.tfm \
tex-plxMono-Thin-tlf-ts1.tfm \
tex-plxMono-Thin-tlf-ts1.vf \
tex-plxMono-Thin-tosf-ly1.tfm \
tex-plxMono-Thin-tosf-ot1.tfm \
tex-plxMono-Thin-tosf-t1--base.tfm \
tex-plxMono-Thin-tosf-t1.tfm \
tex-plxMono-Thin-tosf-t1.vf \
tex-plxMono-Thin-tosf-ts1--base.tfm \
tex-plxMono-Thin-tosf-ts1.tfm \
tex-plxMono-Thin-tosf-ts1.vf \
tex-plxMono-ThinItalic-sup-ly1.tfm \
tex-plxMono-ThinItalic-sup-ot1.tfm \
tex-plxMono-ThinItalic-sup-t1--base.tfm \
tex-plxMono-ThinItalic-sup-t1.tfm \
tex-plxMono-ThinItalic-sup-t1.vf \
tex-plxMono-ThinItalic-tlf-ly1.tfm \
tex-plxMono-ThinItalic-tlf-ot1.tfm \
tex-plxMono-ThinItalic-tlf-t1--base.tfm \
tex-plxMono-ThinItalic-tlf-t1.tfm \
tex-plxMono-ThinItalic-tlf-t1.vf \
tex-plxMono-ThinItalic-tlf-ts1--base.tfm \
tex-plxMono-ThinItalic-tlf-ts1.tfm \
tex-plxMono-ThinItalic-tlf-ts1.vf \
tex-plxMono-ThinItalic-tosf-ly1.tfm \
tex-plxMono-ThinItalic-tosf-ot1.tfm \
tex-plxMono-ThinItalic-tosf-t1--base.tfm \
tex-plxMono-ThinItalic-tosf-t1.tfm \
tex-plxMono-ThinItalic-tosf-t1.vf \
tex-plxMono-ThinItalic-tosf-ts1--base.tfm \
tex-plxMono-ThinItalic-tosf-ts1.tfm \
tex-plxMono-ThinItalic-tosf-ts1.vf \
tex-plxMono-sup-ly1.tfm \
tex-plxMono-sup-ot1.tfm \
tex-plxMono-sup-t1--base.tfm \
tex-plxMono-sup-t1.tfm \
tex-plxMono-sup-t1.vf \
tex-plxMono-tlf-ly1.tfm \
tex-plxMono-tlf-ot1.tfm \
tex-plxMono-tlf-t1--base.tfm \
tex-plxMono-tlf-t1.tfm \
tex-plxMono-tlf-t1.vf \
tex-plxMono-tlf-ts1--base.tfm \
tex-plxMono-tlf-ts1.tfm \
tex-plxMono-tlf-ts1.vf \
tex-plxMono-tosf-ly1.tfm \
tex-plxMono-tosf-ot1.tfm \
tex-plxMono-tosf-t1--base.tfm \
tex-plxMono-tosf-t1.tfm \
tex-plxMono-tosf-t1.vf \
tex-plxMono-tosf-ts1--base.tfm \
tex-plxMono-tosf-ts1.tfm \
tex-plxMono-tosf-ts1.vf \
tex-plxMono.map \
tex-plxSans-Bold-sup-lgr.tfm \
tex-plxSans-Bold-sup-ly1.tfm \
tex-plxSans-Bold-sup-ot1.tfm \
tex-plxSans-Bold-sup-t1--base.tfm \
tex-plxSans-Bold-sup-t1.tfm \
tex-plxSans-Bold-sup-t1.vf \
tex-plxSans-Bold-tlf-lgr.tfm \
tex-plxSans-Bold-tlf-ly1.tfm \
tex-plxSans-Bold-tlf-ot1.tfm \
tex-plxSans-Bold-tlf-t1--base.tfm \
tex-plxSans-Bold-tlf-t1.tfm \
tex-plxSans-Bold-tlf-t1.vf \
tex-plxSans-Bold-tlf-ts1--base.tfm \
tex-plxSans-Bold-tlf-ts1.tfm \
tex-plxSans-Bold-tlf-ts1.vf \
tex-plxSans-Bold-tosf-lgr.tfm \
tex-plxSans-Bold-tosf-ly1.tfm \
tex-plxSans-Bold-tosf-ot1.tfm \
tex-plxSans-Bold-tosf-t1--base.tfm \
tex-plxSans-Bold-tosf-t1.tfm \
tex-plxSans-Bold-tosf-t1.vf \
tex-plxSans-Bold-tosf-ts1--base.tfm \
tex-plxSans-Bold-tosf-ts1.tfm \
tex-plxSans-Bold-tosf-ts1.vf \
tex-plxSans-BoldItalic-sup-lgr.tfm \
tex-plxSans-BoldItalic-sup-ly1.tfm \
tex-plxSans-BoldItalic-sup-ot1.tfm \
tex-plxSans-BoldItalic-sup-t1--base.tfm \
tex-plxSans-BoldItalic-sup-t1.tfm \
tex-plxSans-BoldItalic-sup-t1.vf \
tex-plxSans-BoldItalic-tlf-lgr.tfm \
tex-plxSans-BoldItalic-tlf-ly1.tfm \
tex-plxSans-BoldItalic-tlf-ot1.tfm \
tex-plxSans-BoldItalic-tlf-t1--base.tfm \
tex-plxSans-BoldItalic-tlf-t1.tfm \
tex-plxSans-BoldItalic-tlf-t1.vf \
tex-plxSans-BoldItalic-tlf-ts1--base.tfm \
tex-plxSans-BoldItalic-tlf-ts1.tfm \
tex-plxSans-BoldItalic-tlf-ts1.vf \
tex-plxSans-BoldItalic-tosf-lgr.tfm \
tex-plxSans-BoldItalic-tosf-ly1.tfm \
tex-plxSans-BoldItalic-tosf-ot1.tfm \
tex-plxSans-BoldItalic-tosf-t1--base.tfm \
tex-plxSans-BoldItalic-tosf-t1.tfm \
tex-plxSans-BoldItalic-tosf-t1.vf \
tex-plxSans-BoldItalic-tosf-ts1--base.tfm \
tex-plxSans-BoldItalic-tosf-ts1.tfm \
tex-plxSans-BoldItalic-tosf-ts1.vf \
tex-plxSans-ExtLt-sup-lgr.tfm \
tex-plxSans-ExtLt-sup-ly1.tfm \
tex-plxSans-ExtLt-sup-ot1.tfm \
tex-plxSans-ExtLt-sup-t1--base.tfm \
tex-plxSans-ExtLt-sup-t1.tfm \
tex-plxSans-ExtLt-sup-t1.vf \
tex-plxSans-ExtLt-tlf-lgr.tfm \
tex-plxSans-ExtLt-tlf-ly1.tfm \
tex-plxSans-ExtLt-tlf-ot1.tfm \
tex-plxSans-ExtLt-tlf-t1--base.tfm \
tex-plxSans-ExtLt-tlf-t1.tfm \
tex-plxSans-ExtLt-tlf-t1.vf \
tex-plxSans-ExtLt-tlf-ts1--base.tfm \
tex-plxSans-ExtLt-tlf-ts1.tfm \
tex-plxSans-ExtLt-tlf-ts1.vf \
tex-plxSans-ExtLt-tosf-lgr.tfm \
tex-plxSans-ExtLt-tosf-ly1.tfm \
tex-plxSans-ExtLt-tosf-ot1.tfm \
tex-plxSans-ExtLt-tosf-t1--base.tfm \
tex-plxSans-ExtLt-tosf-t1.tfm \
tex-plxSans-ExtLt-tosf-t1.vf \
tex-plxSans-ExtLt-tosf-ts1--base.tfm \
tex-plxSans-ExtLt-tosf-ts1.tfm \
tex-plxSans-ExtLt-tosf-ts1.vf \
tex-plxSans-ExtLtItalic-sup-lgr.tfm \
tex-plxSans-ExtLtItalic-sup-ly1.tfm \
tex-plxSans-ExtLtItalic-sup-ot1.tfm \
tex-plxSans-ExtLtItalic-sup-t1--base.tfm \
tex-plxSans-ExtLtItalic-sup-t1.tfm \
tex-plxSans-ExtLtItalic-sup-t1.vf \
tex-plxSans-ExtLtItalic-tlf-lgr.tfm \
tex-plxSans-ExtLtItalic-tlf-ly1.tfm \
tex-plxSans-ExtLtItalic-tlf-ot1.tfm \
tex-plxSans-ExtLtItalic-tlf-t1--base.tfm \
tex-plxSans-ExtLtItalic-tlf-t1.tfm \
tex-plxSans-ExtLtItalic-tlf-t1.vf \
tex-plxSans-ExtLtItalic-tlf-ts1--base.tfm \
tex-plxSans-ExtLtItalic-tlf-ts1.tfm \
tex-plxSans-ExtLtItalic-tlf-ts1.vf \
tex-plxSans-ExtLtItalic-tosf-lgr.tfm \
tex-plxSans-ExtLtItalic-tosf-ly1.tfm \
tex-plxSans-ExtLtItalic-tosf-ot1.tfm \
tex-plxSans-ExtLtItalic-tosf-t1--base.tfm \
tex-plxSans-ExtLtItalic-tosf-t1.tfm \
tex-plxSans-ExtLtItalic-tosf-t1.vf \
tex-plxSans-ExtLtItalic-tosf-ts1--base.tfm \
tex-plxSans-ExtLtItalic-tosf-ts1.tfm \
tex-plxSans-ExtLtItalic-tosf-ts1.vf \
tex-plxSans-Italic-sup-lgr.tfm \
tex-plxSans-Italic-sup-ly1.tfm \
tex-plxSans-Italic-sup-ot1.tfm \
tex-plxSans-Italic-sup-t1--base.tfm \
tex-plxSans-Italic-sup-t1.tfm \
tex-plxSans-Italic-sup-t1.vf \
tex-plxSans-Italic-tlf-lgr.tfm \
tex-plxSans-Italic-tlf-ly1.tfm \
tex-plxSans-Italic-tlf-ot1.tfm \
tex-plxSans-Italic-tlf-t1--base.tfm \
tex-plxSans-Italic-tlf-t1.tfm \
tex-plxSans-Italic-tlf-t1.vf \
tex-plxSans-Italic-tlf-ts1--base.tfm \
tex-plxSans-Italic-tlf-ts1.tfm \
tex-plxSans-Italic-tlf-ts1.vf \
tex-plxSans-Italic-tosf-lgr.tfm \
tex-plxSans-Italic-tosf-ly1.tfm \
tex-plxSans-Italic-tosf-ot1.tfm \
tex-plxSans-Italic-tosf-t1--base.tfm \
tex-plxSans-Italic-tosf-t1.tfm \
tex-plxSans-Italic-tosf-t1.vf \
tex-plxSans-Italic-tosf-ts1--base.tfm \
tex-plxSans-Italic-tosf-ts1.tfm \
tex-plxSans-Italic-tosf-ts1.vf \
tex-plxSans-Light-sup-lgr.tfm \
tex-plxSans-Light-sup-ly1.tfm \
tex-plxSans-Light-sup-ot1.tfm \
tex-plxSans-Light-sup-t1--base.tfm \
tex-plxSans-Light-sup-t1.tfm \
tex-plxSans-Light-sup-t1.vf \
tex-plxSans-Light-tlf-lgr.tfm \
tex-plxSans-Light-tlf-ly1.tfm \
tex-plxSans-Light-tlf-ot1.tfm \
tex-plxSans-Light-tlf-t1--base.tfm \
tex-plxSans-Light-tlf-t1.tfm \
tex-plxSans-Light-tlf-t1.vf \
tex-plxSans-Light-tlf-ts1--base.tfm \
tex-plxSans-Light-tlf-ts1.tfm \
tex-plxSans-Light-tlf-ts1.vf \
tex-plxSans-Light-tosf-lgr.tfm \
tex-plxSans-Light-tosf-ly1.tfm \
tex-plxSans-Light-tosf-ot1.tfm \
tex-plxSans-Light-tosf-t1--base.tfm \
tex-plxSans-Light-tosf-t1.tfm \
tex-plxSans-Light-tosf-t1.vf \
tex-plxSans-Light-tosf-ts1--base.tfm \
tex-plxSans-Light-tosf-ts1.tfm \
tex-plxSans-Light-tosf-ts1.vf \
tex-plxSans-LightItalic-sup-lgr.tfm \
tex-plxSans-LightItalic-sup-ly1.tfm \
tex-plxSans-LightItalic-sup-ot1.tfm \
tex-plxSans-LightItalic-sup-t1--base.tfm \
tex-plxSans-LightItalic-sup-t1.tfm \
tex-plxSans-LightItalic-sup-t1.vf \
tex-plxSans-LightItalic-tlf-lgr.tfm \
tex-plxSans-LightItalic-tlf-ly1.tfm \
tex-plxSans-LightItalic-tlf-ot1.tfm \
tex-plxSans-LightItalic-tlf-t1--base.tfm \
tex-plxSans-LightItalic-tlf-t1.tfm \
tex-plxSans-LightItalic-tlf-t1.vf \
tex-plxSans-LightItalic-tlf-ts1--base.tfm \
tex-plxSans-LightItalic-tlf-ts1.tfm \
tex-plxSans-LightItalic-tlf-ts1.vf \
tex-plxSans-LightItalic-tosf-lgr.tfm \
tex-plxSans-LightItalic-tosf-ly1.tfm \
tex-plxSans-LightItalic-tosf-ot1.tfm \
tex-plxSans-LightItalic-tosf-t1--base.tfm \
tex-plxSans-LightItalic-tosf-t1.tfm \
tex-plxSans-LightItalic-tosf-t1.vf \
tex-plxSans-LightItalic-tosf-ts1--base.tfm \
tex-plxSans-LightItalic-tosf-ts1.tfm \
tex-plxSans-LightItalic-tosf-ts1.vf \
tex-plxSans-Medm-sup-lgr.tfm \
tex-plxSans-Medm-sup-ly1.tfm \
tex-plxSans-Medm-sup-ot1.tfm \
tex-plxSans-Medm-sup-t1--base.tfm \
tex-plxSans-Medm-sup-t1.tfm \
tex-plxSans-Medm-sup-t1.vf \
tex-plxSans-Medm-tlf-lgr.tfm \
tex-plxSans-Medm-tlf-ly1.tfm \
tex-plxSans-Medm-tlf-ot1.tfm \
tex-plxSans-Medm-tlf-t1--base.tfm \
tex-plxSans-Medm-tlf-t1.tfm \
tex-plxSans-Medm-tlf-t1.vf \
tex-plxSans-Medm-tlf-ts1--base.tfm \
tex-plxSans-Medm-tlf-ts1.tfm \
tex-plxSans-Medm-tlf-ts1.vf \
tex-plxSans-Medm-tosf-lgr.tfm \
tex-plxSans-Medm-tosf-ly1.tfm \
tex-plxSans-Medm-tosf-ot1.tfm \
tex-plxSans-Medm-tosf-t1--base.tfm \
tex-plxSans-Medm-tosf-t1.tfm \
tex-plxSans-Medm-tosf-t1.vf \
tex-plxSans-Medm-tosf-ts1--base.tfm \
tex-plxSans-Medm-tosf-ts1.tfm \
tex-plxSans-Medm-tosf-ts1.vf \
tex-plxSans-MedmItalic-sup-lgr.tfm \
tex-plxSans-MedmItalic-sup-ly1.tfm \
tex-plxSans-MedmItalic-sup-ot1.tfm \
tex-plxSans-MedmItalic-sup-t1--base.tfm \
tex-plxSans-MedmItalic-sup-t1.tfm \
tex-plxSans-MedmItalic-sup-t1.vf \
tex-plxSans-MedmItalic-tlf-lgr.tfm \
tex-plxSans-MedmItalic-tlf-ly1.tfm \
tex-plxSans-MedmItalic-tlf-ot1.tfm \
tex-plxSans-MedmItalic-tlf-t1--base.tfm \
tex-plxSans-MedmItalic-tlf-t1.tfm \
tex-plxSans-MedmItalic-tlf-t1.vf \
tex-plxSans-MedmItalic-tlf-ts1--base.tfm \
tex-plxSans-MedmItalic-tlf-ts1.tfm \
tex-plxSans-MedmItalic-tlf-ts1.vf \
tex-plxSans-MedmItalic-tosf-lgr.tfm \
tex-plxSans-MedmItalic-tosf-ly1.tfm \
tex-plxSans-MedmItalic-tosf-ot1.tfm \
tex-plxSans-MedmItalic-tosf-t1--base.tfm \
tex-plxSans-MedmItalic-tosf-t1.tfm \
tex-plxSans-MedmItalic-tosf-t1.vf \
tex-plxSans-MedmItalic-tosf-ts1--base.tfm \
tex-plxSans-MedmItalic-tosf-ts1.tfm \
tex-plxSans-MedmItalic-tosf-ts1.vf \
tex-plxSans-SmBld-sup-lgr.tfm \
tex-plxSans-SmBld-sup-ly1.tfm \
tex-plxSans-SmBld-sup-ot1.tfm \
tex-plxSans-SmBld-sup-t1--base.tfm \
tex-plxSans-SmBld-sup-t1.tfm \
tex-plxSans-SmBld-sup-t1.vf \
tex-plxSans-SmBld-tlf-lgr.tfm \
tex-plxSans-SmBld-tlf-ly1.tfm \
tex-plxSans-SmBld-tlf-ot1.tfm \
tex-plxSans-SmBld-tlf-t1--base.tfm \
tex-plxSans-SmBld-tlf-t1.tfm \
tex-plxSans-SmBld-tlf-t1.vf \
tex-plxSans-SmBld-tlf-ts1--base.tfm \
tex-plxSans-SmBld-tlf-ts1.tfm \
tex-plxSans-SmBld-tlf-ts1.vf \
tex-plxSans-SmBld-tosf-lgr.tfm \
tex-plxSans-SmBld-tosf-ly1.tfm \
tex-plxSans-SmBld-tosf-ot1.tfm \
tex-plxSans-SmBld-tosf-t1--base.tfm \
tex-plxSans-SmBld-tosf-t1.tfm \
tex-plxSans-SmBld-tosf-t1.vf \
tex-plxSans-SmBld-tosf-ts1--base.tfm \
tex-plxSans-SmBld-tosf-ts1.tfm \
tex-plxSans-SmBld-tosf-ts1.vf \
tex-plxSans-SmBldItalic-sup-lgr.tfm \
tex-plxSans-SmBldItalic-sup-ly1.tfm \
tex-plxSans-SmBldItalic-sup-ot1.tfm \
tex-plxSans-SmBldItalic-sup-t1--base.tfm \
tex-plxSans-SmBldItalic-sup-t1.tfm \
tex-plxSans-SmBldItalic-sup-t1.vf \
tex-plxSans-SmBldItalic-tlf-lgr.tfm \
tex-plxSans-SmBldItalic-tlf-ly1.tfm \
tex-plxSans-SmBldItalic-tlf-ot1.tfm \
tex-plxSans-SmBldItalic-tlf-t1--base.tfm \
tex-plxSans-SmBldItalic-tlf-t1.tfm \
tex-plxSans-SmBldItalic-tlf-t1.vf \
tex-plxSans-SmBldItalic-tlf-ts1--base.tfm \
tex-plxSans-SmBldItalic-tlf-ts1.tfm \
tex-plxSans-SmBldItalic-tlf-ts1.vf \
tex-plxSans-SmBldItalic-tosf-lgr.tfm \
tex-plxSans-SmBldItalic-tosf-ly1.tfm \
tex-plxSans-SmBldItalic-tosf-ot1.tfm \
tex-plxSans-SmBldItalic-tosf-t1--base.tfm \
tex-plxSans-SmBldItalic-tosf-t1.tfm \
tex-plxSans-SmBldItalic-tosf-t1.vf \
tex-plxSans-SmBldItalic-tosf-ts1--base.tfm \
tex-plxSans-SmBldItalic-tosf-ts1.tfm \
tex-plxSans-SmBldItalic-tosf-ts1.vf \
tex-plxSans-Text-sup-lgr.tfm \
tex-plxSans-Text-sup-ly1.tfm \
tex-plxSans-Text-sup-ot1.tfm \
tex-plxSans-Text-sup-t1--base.tfm \
tex-plxSans-Text-sup-t1.tfm \
tex-plxSans-Text-sup-t1.vf \
tex-plxSans-Text-tlf-lgr.tfm \
tex-plxSans-Text-tlf-ly1.tfm \
tex-plxSans-Text-tlf-ot1.tfm \
tex-plxSans-Text-tlf-t1--base.tfm \
tex-plxSans-Text-tlf-t1.tfm \
tex-plxSans-Text-tlf-t1.vf \
tex-plxSans-Text-tlf-ts1--base.tfm \
tex-plxSans-Text-tlf-ts1.tfm \
tex-plxSans-Text-tlf-ts1.vf \
tex-plxSans-Text-tosf-lgr.tfm \
tex-plxSans-Text-tosf-ly1.tfm \
tex-plxSans-Text-tosf-ot1.tfm \
tex-plxSans-Text-tosf-t1--base.tfm \
tex-plxSans-Text-tosf-t1.tfm \
tex-plxSans-Text-tosf-t1.vf \
tex-plxSans-Text-tosf-ts1--base.tfm \
tex-plxSans-Text-tosf-ts1.tfm \
tex-plxSans-Text-tosf-ts1.vf \
tex-plxSans-TextItalic-sup-lgr.tfm \
tex-plxSans-TextItalic-sup-ly1.tfm \
tex-plxSans-TextItalic-sup-ot1.tfm \
tex-plxSans-TextItalic-sup-t1--base.tfm \
tex-plxSans-TextItalic-sup-t1.tfm \
tex-plxSans-TextItalic-sup-t1.vf \
tex-plxSans-TextItalic-tlf-lgr.tfm \
tex-plxSans-TextItalic-tlf-ly1.tfm \
tex-plxSans-TextItalic-tlf-ot1.tfm \
tex-plxSans-TextItalic-tlf-t1--base.tfm \
tex-plxSans-TextItalic-tlf-t1.tfm \
tex-plxSans-TextItalic-tlf-t1.vf \
tex-plxSans-TextItalic-tlf-ts1--base.tfm \
tex-plxSans-TextItalic-tlf-ts1.tfm \
tex-plxSans-TextItalic-tlf-ts1.vf \
tex-plxSans-TextItalic-tosf-lgr.tfm \
tex-plxSans-TextItalic-tosf-ly1.tfm \
tex-plxSans-TextItalic-tosf-ot1.tfm \
tex-plxSans-TextItalic-tosf-t1--base.tfm \
tex-plxSans-TextItalic-tosf-t1.tfm \
tex-plxSans-TextItalic-tosf-t1.vf \
tex-plxSans-TextItalic-tosf-ts1--base.tfm \
tex-plxSans-TextItalic-tosf-ts1.tfm \
tex-plxSans-TextItalic-tosf-ts1.vf \
tex-plxSans-Thin-sup-lgr.tfm \
tex-plxSans-Thin-sup-ly1.tfm \
tex-plxSans-Thin-sup-ot1.tfm \
tex-plxSans-Thin-sup-t1--base.tfm \
tex-plxSans-Thin-sup-t1.tfm \
tex-plxSans-Thin-sup-t1.vf \
tex-plxSans-Thin-tlf-lgr.tfm \
tex-plxSans-Thin-tlf-ly1.tfm \
tex-plxSans-Thin-tlf-ot1.tfm \
tex-plxSans-Thin-tlf-t1--base.tfm \
tex-plxSans-Thin-tlf-t1.tfm \
tex-plxSans-Thin-tlf-t1.vf \
tex-plxSans-Thin-tlf-ts1--base.tfm \
tex-plxSans-Thin-tlf-ts1.tfm \
tex-plxSans-Thin-tlf-ts1.vf \
tex-plxSans-Thin-tosf-lgr.tfm \
tex-plxSans-Thin-tosf-ly1.tfm \
tex-plxSans-Thin-tosf-ot1.tfm \
tex-plxSans-Thin-tosf-t1--base.tfm \
tex-plxSans-Thin-tosf-t1.tfm \
tex-plxSans-Thin-tosf-t1.vf \
tex-plxSans-Thin-tosf-ts1--base.tfm \
tex-plxSans-Thin-tosf-ts1.tfm \
tex-plxSans-Thin-tosf-ts1.vf \
tex-plxSans-ThinItalic-sup-lgr.tfm \
tex-plxSans-ThinItalic-sup-ly1.tfm \
tex-plxSans-ThinItalic-sup-ot1.tfm \
tex-plxSans-ThinItalic-sup-t1--base.tfm \
tex-plxSans-ThinItalic-sup-t1.tfm \
tex-plxSans-ThinItalic-sup-t1.vf \
tex-plxSans-ThinItalic-tlf-lgr.tfm \
tex-plxSans-ThinItalic-tlf-ly1.tfm \
tex-plxSans-ThinItalic-tlf-ot1.tfm \
tex-plxSans-ThinItalic-tlf-t1--base.tfm \
tex-plxSans-ThinItalic-tlf-t1.tfm \
tex-plxSans-ThinItalic-tlf-t1.vf \
tex-plxSans-ThinItalic-tlf-ts1--base.tfm \
tex-plxSans-ThinItalic-tlf-ts1.tfm \
tex-plxSans-ThinItalic-tlf-ts1.vf \
tex-plxSans-ThinItalic-tosf-lgr.tfm \
tex-plxSans-ThinItalic-tosf-ly1.tfm \
tex-plxSans-ThinItalic-tosf-ot1.tfm \
tex-plxSans-ThinItalic-tosf-t1--base.tfm \
tex-plxSans-ThinItalic-tosf-t1.tfm \
tex-plxSans-ThinItalic-tosf-t1.vf \
tex-plxSans-ThinItalic-tosf-ts1--base.tfm \
tex-plxSans-ThinItalic-tosf-ts1.tfm \
tex-plxSans-ThinItalic-tosf-ts1.vf \
tex-plxSans-sup-lgr.tfm \
tex-plxSans-sup-ly1.tfm \
tex-plxSans-sup-ot1.tfm \
tex-plxSans-sup-t1--base.tfm \
tex-plxSans-sup-t1.tfm \
tex-plxSans-sup-t1.vf \
tex-plxSans-tlf-lgr.tfm \
tex-plxSans-tlf-ly1.tfm \
tex-plxSans-tlf-ot1.tfm \
tex-plxSans-tlf-t1--base.tfm \
tex-plxSans-tlf-t1.tfm \
tex-plxSans-tlf-t1.vf \
tex-plxSans-tlf-ts1--base.tfm \
tex-plxSans-tlf-ts1.tfm \
tex-plxSans-tlf-ts1.vf \
tex-plxSans-tosf-lgr.tfm \
tex-plxSans-tosf-ly1.tfm \
tex-plxSans-tosf-ot1.tfm \
tex-plxSans-tosf-t1--base.tfm \
tex-plxSans-tosf-t1.tfm \
tex-plxSans-tosf-t1.vf \
tex-plxSans-tosf-ts1--base.tfm \
tex-plxSans-tosf-ts1.tfm \
tex-plxSans-tosf-ts1.vf \
tex-plxSans.map \
tex-plxSansCond-Bold-sup-lgr--base.tfm \
tex-plxSansCond-Bold-sup-lgr.tfm \
tex-plxSansCond-Bold-sup-lgr.vf \
tex-plxSansCond-Bold-sup-ly1--base.tfm \
tex-plxSansCond-Bold-sup-ly1.tfm \
tex-plxSansCond-Bold-sup-ly1.vf \
tex-plxSansCond-Bold-sup-ot1.tfm \
tex-plxSansCond-Bold-sup-t1--base.tfm \
tex-plxSansCond-Bold-sup-t1.tfm \
tex-plxSansCond-Bold-sup-t1.vf \
tex-plxSansCond-Bold-tlf-lgr--base.tfm \
tex-plxSansCond-Bold-tlf-lgr.tfm \
tex-plxSansCond-Bold-tlf-lgr.vf \
tex-plxSansCond-Bold-tlf-ly1--base.tfm \
tex-plxSansCond-Bold-tlf-ly1.tfm \
tex-plxSansCond-Bold-tlf-ly1.vf \
tex-plxSansCond-Bold-tlf-ot1.tfm \
tex-plxSansCond-Bold-tlf-t1--base.tfm \
tex-plxSansCond-Bold-tlf-t1.tfm \
tex-plxSansCond-Bold-tlf-t1.vf \
tex-plxSansCond-Bold-tlf-ts1--base.tfm \
tex-plxSansCond-Bold-tlf-ts1.tfm \
tex-plxSansCond-Bold-tlf-ts1.vf \
tex-plxSansCond-BoldItalic-sup-lgr--base.tfm \
tex-plxSansCond-BoldItalic-sup-lgr.tfm \
tex-plxSansCond-BoldItalic-sup-lgr.vf \
tex-plxSansCond-BoldItalic-sup-ly1--base.tfm \
tex-plxSansCond-BoldItalic-sup-ly1.tfm \
tex-plxSansCond-BoldItalic-sup-ly1.vf \
tex-plxSansCond-BoldItalic-sup-ot1.tfm \
tex-plxSansCond-BoldItalic-sup-t1--base.tfm \
tex-plxSansCond-BoldItalic-sup-t1.tfm \
tex-plxSansCond-BoldItalic-sup-t1.vf \
tex-plxSansCond-BoldItalic-tlf-lgr--base.tfm \
tex-plxSansCond-BoldItalic-tlf-lgr.tfm \
tex-plxSansCond-BoldItalic-tlf-lgr.vf \
tex-plxSansCond-BoldItalic-tlf-ly1--base.tfm \
tex-plxSansCond-BoldItalic-tlf-ly1.tfm \
tex-plxSansCond-BoldItalic-tlf-ly1.vf \
tex-plxSansCond-BoldItalic-tlf-ot1.tfm \
tex-plxSansCond-BoldItalic-tlf-t1--base.tfm \
tex-plxSansCond-BoldItalic-tlf-t1.tfm \
tex-plxSansCond-BoldItalic-tlf-t1.vf \
tex-plxSansCond-BoldItalic-tlf-ts1--base.tfm \
tex-plxSansCond-BoldItalic-tlf-ts1.tfm \
tex-plxSansCond-BoldItalic-tlf-ts1.vf \
tex-plxSansCond-ExtLt-sup-lgr--base.tfm \
tex-plxSansCond-ExtLt-sup-lgr.tfm \
tex-plxSansCond-ExtLt-sup-lgr.vf \
tex-plxSansCond-ExtLt-sup-ly1--base.tfm \
tex-plxSansCond-ExtLt-sup-ly1.tfm \
tex-plxSansCond-ExtLt-sup-ly1.vf \
tex-plxSansCond-ExtLt-sup-ot1.tfm \
tex-plxSansCond-ExtLt-sup-t1--base.tfm \
tex-plxSansCond-ExtLt-sup-t1.tfm \
tex-plxSansCond-ExtLt-sup-t1.vf \
tex-plxSansCond-ExtLt-tlf-lgr--base.tfm \
tex-plxSansCond-ExtLt-tlf-lgr.tfm \
tex-plxSansCond-ExtLt-tlf-lgr.vf \
tex-plxSansCond-ExtLt-tlf-ly1--base.tfm \
tex-plxSansCond-ExtLt-tlf-ly1.tfm \
tex-plxSansCond-ExtLt-tlf-ly1.vf \
tex-plxSansCond-ExtLt-tlf-ot1.tfm \
tex-plxSansCond-ExtLt-tlf-t1--base.tfm \
tex-plxSansCond-ExtLt-tlf-t1.tfm \
tex-plxSansCond-ExtLt-tlf-t1.vf \
tex-plxSansCond-ExtLt-tlf-ts1--base.tfm \
tex-plxSansCond-ExtLt-tlf-ts1.tfm \
tex-plxSansCond-ExtLt-tlf-ts1.vf \
tex-plxSansCond-ExtLtItalic-sup-lgr--base.tfm \
tex-plxSansCond-ExtLtItalic-sup-lgr.tfm \
tex-plxSansCond-ExtLtItalic-sup-lgr.vf \
tex-plxSansCond-ExtLtItalic-sup-ly1--base.tfm \
tex-plxSansCond-ExtLtItalic-sup-ly1.tfm \
tex-plxSansCond-ExtLtItalic-sup-ly1.vf \
tex-plxSansCond-ExtLtItalic-sup-ot1.tfm \
tex-plxSansCond-ExtLtItalic-sup-t1--base.tfm \
tex-plxSansCond-ExtLtItalic-sup-t1.tfm \
tex-plxSansCond-ExtLtItalic-sup-t1.vf \
tex-plxSansCond-ExtLtItalic-tlf-lgr--base.tfm \
tex-plxSansCond-ExtLtItalic-tlf-lgr.tfm \
tex-plxSansCond-ExtLtItalic-tlf-lgr.vf \
tex-plxSansCond-ExtLtItalic-tlf-ly1--base.tfm \
tex-plxSansCond-ExtLtItalic-tlf-ly1.tfm \
tex-plxSansCond-ExtLtItalic-tlf-ly1.vf \
tex-plxSansCond-ExtLtItalic-tlf-ot1.tfm \
tex-plxSansCond-ExtLtItalic-tlf-t1--base.tfm \
tex-plxSansCond-ExtLtItalic-tlf-t1.tfm \
tex-plxSansCond-ExtLtItalic-tlf-t1.vf \
tex-plxSansCond-ExtLtItalic-tlf-ts1--base.tfm \
tex-plxSansCond-ExtLtItalic-tlf-ts1.tfm \
tex-plxSansCond-ExtLtItalic-tlf-ts1.vf \
tex-plxSansCond-Italic-sup-lgr--base.tfm \
tex-plxSansCond-Italic-sup-lgr.tfm \
tex-plxSansCond-Italic-sup-lgr.vf \
tex-plxSansCond-Italic-sup-ly1--base.tfm \
tex-plxSansCond-Italic-sup-ly1.tfm \
tex-plxSansCond-Italic-sup-ly1.vf \
tex-plxSansCond-Italic-sup-ot1.tfm \
tex-plxSansCond-Italic-sup-t1--base.tfm \
tex-plxSansCond-Italic-sup-t1.tfm \
tex-plxSansCond-Italic-sup-t1.vf \
tex-plxSansCond-Italic-tlf-lgr--base.tfm \
tex-plxSansCond-Italic-tlf-lgr.tfm \
tex-plxSansCond-Italic-tlf-lgr.vf \
tex-plxSansCond-Italic-tlf-ly1--base.tfm \
tex-plxSansCond-Italic-tlf-ly1.tfm \
tex-plxSansCond-Italic-tlf-ly1.vf \
tex-plxSansCond-Italic-tlf-ot1.tfm \
tex-plxSansCond-Italic-tlf-t1--base.tfm \
tex-plxSansCond-Italic-tlf-t1.tfm \
tex-plxSansCond-Italic-tlf-t1.vf \
tex-plxSansCond-Italic-tlf-ts1--base.tfm \
tex-plxSansCond-Italic-tlf-ts1.tfm \
tex-plxSansCond-Italic-tlf-ts1.vf \
tex-plxSansCond-Light-sup-lgr--base.tfm \
tex-plxSansCond-Light-sup-lgr.tfm \
tex-plxSansCond-Light-sup-lgr.vf \
tex-plxSansCond-Light-sup-ly1--base.tfm \
tex-plxSansCond-Light-sup-ly1.tfm \
tex-plxSansCond-Light-sup-ly1.vf \
tex-plxSansCond-Light-sup-ot1.tfm \
tex-plxSansCond-Light-sup-t1--base.tfm \
tex-plxSansCond-Light-sup-t1.tfm \
tex-plxSansCond-Light-sup-t1.vf \
tex-plxSansCond-Light-tlf-lgr--base.tfm \
tex-plxSansCond-Light-tlf-lgr.tfm \
tex-plxSansCond-Light-tlf-lgr.vf \
tex-plxSansCond-Light-tlf-ly1--base.tfm \
tex-plxSansCond-Light-tlf-ly1.tfm \
tex-plxSansCond-Light-tlf-ly1.vf \
tex-plxSansCond-Light-tlf-ot1.tfm \
tex-plxSansCond-Light-tlf-t1--base.tfm \
tex-plxSansCond-Light-tlf-t1.tfm \
tex-plxSansCond-Light-tlf-t1.vf \
tex-plxSansCond-Light-tlf-ts1--base.tfm \
tex-plxSansCond-Light-tlf-ts1.tfm \
tex-plxSansCond-Light-tlf-ts1.vf \
tex-plxSansCond-LightItalic-sup-lgr--base.tfm \
tex-plxSansCond-LightItalic-sup-lgr.tfm \
tex-plxSansCond-LightItalic-sup-lgr.vf \
tex-plxSansCond-LightItalic-sup-ly1--base.tfm \
tex-plxSansCond-LightItalic-sup-ly1.tfm \
tex-plxSansCond-LightItalic-sup-ly1.vf \
tex-plxSansCond-LightItalic-sup-ot1.tfm \
tex-plxSansCond-LightItalic-sup-t1--base.tfm \
tex-plxSansCond-LightItalic-sup-t1.tfm \
tex-plxSansCond-LightItalic-sup-t1.vf \
tex-plxSansCond-LightItalic-tlf-lgr--base.tfm \
tex-plxSansCond-LightItalic-tlf-lgr.tfm \
tex-plxSansCond-LightItalic-tlf-lgr.vf \
tex-plxSansCond-LightItalic-tlf-ly1--base.tfm \
tex-plxSansCond-LightItalic-tlf-ly1.tfm \
tex-plxSansCond-LightItalic-tlf-ly1.vf \
tex-plxSansCond-LightItalic-tlf-ot1.tfm \
tex-plxSansCond-LightItalic-tlf-t1--base.tfm \
tex-plxSansCond-LightItalic-tlf-t1.tfm \
tex-plxSansCond-LightItalic-tlf-t1.vf \
tex-plxSansCond-LightItalic-tlf-ts1--base.tfm \
tex-plxSansCond-LightItalic-tlf-ts1.tfm \
tex-plxSansCond-LightItalic-tlf-ts1.vf \
tex-plxSansCond-Medm-sup-lgr--base.tfm \
tex-plxSansCond-Medm-sup-lgr.tfm \
tex-plxSansCond-Medm-sup-lgr.vf \
tex-plxSansCond-Medm-sup-ly1--base.tfm \
tex-plxSansCond-Medm-sup-ly1.tfm \
tex-plxSansCond-Medm-sup-ly1.vf \
tex-plxSansCond-Medm-sup-ot1.tfm \
tex-plxSansCond-Medm-sup-t1--base.tfm \
tex-plxSansCond-Medm-sup-t1.tfm \
tex-plxSansCond-Medm-sup-t1.vf \
tex-plxSansCond-Medm-tlf-lgr--base.tfm \
tex-plxSansCond-Medm-tlf-lgr.tfm \
tex-plxSansCond-Medm-tlf-lgr.vf \
tex-plxSansCond-Medm-tlf-ly1--base.tfm \
tex-plxSansCond-Medm-tlf-ly1.tfm \
tex-plxSansCond-Medm-tlf-ly1.vf \
tex-plxSansCond-Medm-tlf-ot1.tfm \
tex-plxSansCond-Medm-tlf-t1--base.tfm \
tex-plxSansCond-Medm-tlf-t1.tfm \
tex-plxSansCond-Medm-tlf-t1.vf \
tex-plxSansCond-Medm-tlf-ts1--base.tfm \
tex-plxSansCond-Medm-tlf-ts1.tfm \
tex-plxSansCond-Medm-tlf-ts1.vf \
tex-plxSansCond-MedmItalic-sup-lgr--base.tfm \
tex-plxSansCond-MedmItalic-sup-lgr.tfm \
tex-plxSansCond-MedmItalic-sup-lgr.vf \
tex-plxSansCond-MedmItalic-sup-ly1--base.tfm \
tex-plxSansCond-MedmItalic-sup-ly1.tfm \
tex-plxSansCond-MedmItalic-sup-ly1.vf \
tex-plxSansCond-MedmItalic-sup-ot1.tfm \
tex-plxSansCond-MedmItalic-sup-t1--base.tfm \
tex-plxSansCond-MedmItalic-sup-t1.tfm \
tex-plxSansCond-MedmItalic-sup-t1.vf \
tex-plxSansCond-MedmItalic-tlf-lgr--base.tfm \
tex-plxSansCond-MedmItalic-tlf-lgr.tfm \
tex-plxSansCond-MedmItalic-tlf-lgr.vf \
tex-plxSansCond-MedmItalic-tlf-ly1--base.tfm \
tex-plxSansCond-MedmItalic-tlf-ly1.tfm \
tex-plxSansCond-MedmItalic-tlf-ly1.vf \
tex-plxSansCond-MedmItalic-tlf-ot1.tfm \
tex-plxSansCond-MedmItalic-tlf-t1--base.tfm \
tex-plxSansCond-MedmItalic-tlf-t1.tfm \
tex-plxSansCond-MedmItalic-tlf-t1.vf \
tex-plxSansCond-MedmItalic-tlf-ts1--base.tfm \
tex-plxSansCond-MedmItalic-tlf-ts1.tfm \
tex-plxSansCond-MedmItalic-tlf-ts1.vf \
tex-plxSansCond-SmBld-sup-lgr--base.tfm \
tex-plxSansCond-SmBld-sup-lgr.tfm \
tex-plxSansCond-SmBld-sup-lgr.vf \
tex-plxSansCond-SmBld-sup-ly1--base.tfm \
tex-plxSansCond-SmBld-sup-ly1.tfm \
tex-plxSansCond-SmBld-sup-ly1.vf \
tex-plxSansCond-SmBld-sup-ot1.tfm \
tex-plxSansCond-SmBld-sup-t1--base.tfm \
tex-plxSansCond-SmBld-sup-t1.tfm \
tex-plxSansCond-SmBld-sup-t1.vf \
tex-plxSansCond-SmBld-tlf-lgr--base.tfm \
tex-plxSansCond-SmBld-tlf-lgr.tfm \
tex-plxSansCond-SmBld-tlf-lgr.vf \
tex-plxSansCond-SmBld-tlf-ly1--base.tfm \
tex-plxSansCond-SmBld-tlf-ly1.tfm \
tex-plxSansCond-SmBld-tlf-ly1.vf \
tex-plxSansCond-SmBld-tlf-ot1.tfm \
tex-plxSansCond-SmBld-tlf-t1--base.tfm \
tex-plxSansCond-SmBld-tlf-t1.tfm \
tex-plxSansCond-SmBld-tlf-t1.vf \
tex-plxSansCond-SmBld-tlf-ts1--base.tfm \
tex-plxSansCond-SmBld-tlf-ts1.tfm \
tex-plxSansCond-SmBld-tlf-ts1.vf \
tex-plxSansCond-SmBldItalic-sup-lgr--base.tfm \
tex-plxSansCond-SmBldItalic-sup-lgr.tfm \
tex-plxSansCond-SmBldItalic-sup-lgr.vf \
tex-plxSansCond-SmBldItalic-sup-ly1--base.tfm \
tex-plxSansCond-SmBldItalic-sup-ly1.tfm \
tex-plxSansCond-SmBldItalic-sup-ly1.vf \
tex-plxSansCond-SmBldItalic-sup-ot1.tfm \
tex-plxSansCond-SmBldItalic-sup-t1--base.tfm \
tex-plxSansCond-SmBldItalic-sup-t1.tfm \
tex-plxSansCond-SmBldItalic-sup-t1.vf \
tex-plxSansCond-SmBldItalic-tlf-lgr--base.tfm \
tex-plxSansCond-SmBldItalic-tlf-lgr.tfm \
tex-plxSansCond-SmBldItalic-tlf-lgr.vf \
tex-plxSansCond-SmBldItalic-tlf-ly1--base.tfm \
tex-plxSansCond-SmBldItalic-tlf-ly1.tfm \
tex-plxSansCond-SmBldItalic-tlf-ly1.vf \
tex-plxSansCond-SmBldItalic-tlf-ot1.tfm \
tex-plxSansCond-SmBldItalic-tlf-t1--base.tfm \
tex-plxSansCond-SmBldItalic-tlf-t1.tfm \
tex-plxSansCond-SmBldItalic-tlf-t1.vf \
tex-plxSansCond-SmBldItalic-tlf-ts1--base.tfm \
tex-plxSansCond-SmBldItalic-tlf-ts1.tfm \
tex-plxSansCond-SmBldItalic-tlf-ts1.vf \
tex-plxSansCond-Text-sup-lgr--base.tfm \
tex-plxSansCond-Text-sup-lgr.tfm \
tex-plxSansCond-Text-sup-lgr.vf \
tex-plxSansCond-Text-sup-ly1--base.tfm \
tex-plxSansCond-Text-sup-ly1.tfm \
tex-plxSansCond-Text-sup-ly1.vf \
tex-plxSansCond-Text-sup-ot1.tfm \
tex-plxSansCond-Text-sup-t1--base.tfm \
tex-plxSansCond-Text-sup-t1.tfm \
tex-plxSansCond-Text-sup-t1.vf \
tex-plxSansCond-Text-tlf-lgr--base.tfm \
tex-plxSansCond-Text-tlf-lgr.tfm \
tex-plxSansCond-Text-tlf-lgr.vf \
tex-plxSansCond-Text-tlf-ly1--base.tfm \
tex-plxSansCond-Text-tlf-ly1.tfm \
tex-plxSansCond-Text-tlf-ly1.vf \
tex-plxSansCond-Text-tlf-ot1.tfm \
tex-plxSansCond-Text-tlf-t1--base.tfm \
tex-plxSansCond-Text-tlf-t1.tfm \
tex-plxSansCond-Text-tlf-t1.vf \
tex-plxSansCond-Text-tlf-ts1--base.tfm \
tex-plxSansCond-Text-tlf-ts1.tfm \
tex-plxSansCond-Text-tlf-ts1.vf \
tex-plxSansCond-TextItalic-sup-lgr--base.tfm \
tex-plxSansCond-TextItalic-sup-lgr.tfm \
tex-plxSansCond-TextItalic-sup-lgr.vf \
tex-plxSansCond-TextItalic-sup-ly1--base.tfm \
tex-plxSansCond-TextItalic-sup-ly1.tfm \
tex-plxSansCond-TextItalic-sup-ly1.vf \
tex-plxSansCond-TextItalic-sup-ot1.tfm \
tex-plxSansCond-TextItalic-sup-t1--base.tfm \
tex-plxSansCond-TextItalic-sup-t1.tfm \
tex-plxSansCond-TextItalic-sup-t1.vf \
tex-plxSansCond-TextItalic-tlf-lgr--base.tfm \
tex-plxSansCond-TextItalic-tlf-lgr.tfm \
tex-plxSansCond-TextItalic-tlf-lgr.vf \
tex-plxSansCond-TextItalic-tlf-ly1--base.tfm \
tex-plxSansCond-TextItalic-tlf-ly1.tfm \
tex-plxSansCond-TextItalic-tlf-ly1.vf \
tex-plxSansCond-TextItalic-tlf-ot1.tfm \
tex-plxSansCond-TextItalic-tlf-t1--base.tfm \
tex-plxSansCond-TextItalic-tlf-t1.tfm \
tex-plxSansCond-TextItalic-tlf-t1.vf \
tex-plxSansCond-TextItalic-tlf-ts1--base.tfm \
tex-plxSansCond-TextItalic-tlf-ts1.tfm \
tex-plxSansCond-TextItalic-tlf-ts1.vf \
tex-plxSansCond-Thin-sup-lgr--base.tfm \
tex-plxSansCond-Thin-sup-lgr.tfm \
tex-plxSansCond-Thin-sup-lgr.vf \
tex-plxSansCond-Thin-sup-ly1--base.tfm \
tex-plxSansCond-Thin-sup-ly1.tfm \
tex-plxSansCond-Thin-sup-ly1.vf \
tex-plxSansCond-Thin-sup-ot1.tfm \
tex-plxSansCond-Thin-sup-t1--base.tfm \
tex-plxSansCond-Thin-sup-t1.tfm \
tex-plxSansCond-Thin-sup-t1.vf \
tex-plxSansCond-Thin-tlf-lgr--base.tfm \
tex-plxSansCond-Thin-tlf-lgr.tfm \
tex-plxSansCond-Thin-tlf-lgr.vf \
tex-plxSansCond-Thin-tlf-ly1--base.tfm \
tex-plxSansCond-Thin-tlf-ly1.tfm \
tex-plxSansCond-Thin-tlf-ly1.vf \
tex-plxSansCond-Thin-tlf-ot1.tfm \
tex-plxSansCond-Thin-tlf-t1--base.tfm \
tex-plxSansCond-Thin-tlf-t1.tfm \
tex-plxSansCond-Thin-tlf-t1.vf \
tex-plxSansCond-Thin-tlf-ts1--base.tfm \
tex-plxSansCond-Thin-tlf-ts1.tfm \
tex-plxSansCond-Thin-tlf-ts1.vf \
tex-plxSansCond-ThinItalic-sup-lgr--base.tfm \
tex-plxSansCond-ThinItalic-sup-lgr.tfm \
tex-plxSansCond-ThinItalic-sup-lgr.vf \
tex-plxSansCond-ThinItalic-sup-ly1--base.tfm \
tex-plxSansCond-ThinItalic-sup-ly1.tfm \
tex-plxSansCond-ThinItalic-sup-ly1.vf \
tex-plxSansCond-ThinItalic-sup-ot1.tfm \
tex-plxSansCond-ThinItalic-sup-t1--base.tfm \
tex-plxSansCond-ThinItalic-sup-t1.tfm \
tex-plxSansCond-ThinItalic-sup-t1.vf \
tex-plxSansCond-ThinItalic-tlf-lgr--base.tfm \
tex-plxSansCond-ThinItalic-tlf-lgr.tfm \
tex-plxSansCond-ThinItalic-tlf-lgr.vf \
tex-plxSansCond-ThinItalic-tlf-ly1--base.tfm \
tex-plxSansCond-ThinItalic-tlf-ly1.tfm \
tex-plxSansCond-ThinItalic-tlf-ly1.vf \
tex-plxSansCond-ThinItalic-tlf-ot1.tfm \
tex-plxSansCond-ThinItalic-tlf-t1--base.tfm \
tex-plxSansCond-ThinItalic-tlf-t1.tfm \
tex-plxSansCond-ThinItalic-tlf-t1.vf \
tex-plxSansCond-ThinItalic-tlf-ts1--base.tfm \
tex-plxSansCond-ThinItalic-tlf-ts1.tfm \
tex-plxSansCond-ThinItalic-tlf-ts1.vf \
tex-plxSansCond-sup-lgr--base.tfm \
tex-plxSansCond-sup-lgr.tfm \
tex-plxSansCond-sup-lgr.vf \
tex-plxSansCond-sup-ly1--base.tfm \
tex-plxSansCond-sup-ly1.tfm \
tex-plxSansCond-sup-ly1.vf \
tex-plxSansCond-sup-ot1.tfm \
tex-plxSansCond-sup-t1--base.tfm \
tex-plxSansCond-sup-t1.tfm \
tex-plxSansCond-sup-t1.vf \
tex-plxSansCond-tlf-lgr--base.tfm \
tex-plxSansCond-tlf-lgr.tfm \
tex-plxSansCond-tlf-lgr.vf \
tex-plxSansCond-tlf-ly1--base.tfm \
tex-plxSansCond-tlf-ly1.tfm \
tex-plxSansCond-tlf-ly1.vf \
tex-plxSansCond-tlf-ot1.tfm \
tex-plxSansCond-tlf-t1--base.tfm \
tex-plxSansCond-tlf-t1.tfm \
tex-plxSansCond-tlf-t1.vf \
tex-plxSansCond-tlf-ts1--base.tfm \
tex-plxSansCond-tlf-ts1.tfm \
tex-plxSansCond-tlf-ts1.vf \
tex-plxSerif-Bold-sup-lgr.tfm \
tex-plxSerif-Bold-sup-ly1.tfm \
tex-plxSerif-Bold-sup-ot1.tfm \
tex-plxSerif-Bold-sup-t1--base.tfm \
tex-plxSerif-Bold-sup-t1.tfm \
tex-plxSerif-Bold-sup-t1.vf \
tex-plxSerif-Bold-tlf-lgr.tfm \
tex-plxSerif-Bold-tlf-ly1.tfm \
tex-plxSerif-Bold-tlf-ot1.tfm \
tex-plxSerif-Bold-tlf-t1--base.tfm \
tex-plxSerif-Bold-tlf-t1.tfm \
tex-plxSerif-Bold-tlf-t1.vf \
tex-plxSerif-Bold-tlf-ts1--base.tfm \
tex-plxSerif-Bold-tlf-ts1.tfm \
tex-plxSerif-Bold-tlf-ts1.vf \
tex-plxSerif-Bold-tosf-lgr.tfm \
tex-plxSerif-Bold-tosf-ly1.tfm \
tex-plxSerif-Bold-tosf-ot1.tfm \
tex-plxSerif-Bold-tosf-t1--base.tfm \
tex-plxSerif-Bold-tosf-t1.tfm \
tex-plxSerif-Bold-tosf-t1.vf \
tex-plxSerif-Bold-tosf-ts1--base.tfm \
tex-plxSerif-Bold-tosf-ts1.tfm \
tex-plxSerif-Bold-tosf-ts1.vf \
tex-plxSerif-BoldItalic-sup-lgr.tfm \
tex-plxSerif-BoldItalic-sup-ly1.tfm \
tex-plxSerif-BoldItalic-sup-ot1.tfm \
tex-plxSerif-BoldItalic-sup-t1--base.tfm \
tex-plxSerif-BoldItalic-sup-t1.tfm \
tex-plxSerif-BoldItalic-sup-t1.vf \
tex-plxSerif-BoldItalic-tlf-lgr.tfm \
tex-plxSerif-BoldItalic-tlf-ly1.tfm \
tex-plxSerif-BoldItalic-tlf-ot1.tfm \
tex-plxSerif-BoldItalic-tlf-t1--base.tfm \
tex-plxSerif-BoldItalic-tlf-t1.tfm \
tex-plxSerif-BoldItalic-tlf-t1.vf \
tex-plxSerif-BoldItalic-tlf-ts1--base.tfm \
tex-plxSerif-BoldItalic-tlf-ts1.tfm \
tex-plxSerif-BoldItalic-tlf-ts1.vf \
tex-plxSerif-BoldItalic-tosf-lgr.tfm \
tex-plxSerif-BoldItalic-tosf-ly1.tfm \
tex-plxSerif-BoldItalic-tosf-ot1.tfm \
tex-plxSerif-BoldItalic-tosf-t1--base.tfm \
tex-plxSerif-BoldItalic-tosf-t1.tfm \
tex-plxSerif-BoldItalic-tosf-t1.vf \
tex-plxSerif-BoldItalic-tosf-ts1--base.tfm \
tex-plxSerif-BoldItalic-tosf-ts1.tfm \
tex-plxSerif-BoldItalic-tosf-ts1.vf \
tex-plxSerif-ExtraLight-sup-lgr.tfm \
tex-plxSerif-ExtraLight-sup-ly1.tfm \
tex-plxSerif-ExtraLight-sup-ot1.tfm \
tex-plxSerif-ExtraLight-sup-t1--base.tfm \
tex-plxSerif-ExtraLight-sup-t1.tfm \
tex-plxSerif-ExtraLight-sup-t1.vf \
tex-plxSerif-ExtraLight-tlf-lgr.tfm \
tex-plxSerif-ExtraLight-tlf-ly1.tfm \
tex-plxSerif-ExtraLight-tlf-ot1.tfm \
tex-plxSerif-ExtraLight-tlf-t1--base.tfm \
tex-plxSerif-ExtraLight-tlf-t1.tfm \
tex-plxSerif-ExtraLight-tlf-t1.vf \
tex-plxSerif-ExtraLight-tlf-ts1--base.tfm \
tex-plxSerif-ExtraLight-tlf-ts1.tfm \
tex-plxSerif-ExtraLight-tlf-ts1.vf \
tex-plxSerif-ExtraLight-tosf-lgr.tfm \
tex-plxSerif-ExtraLight-tosf-ly1.tfm \
tex-plxSerif-ExtraLight-tosf-ot1.tfm \
tex-plxSerif-ExtraLight-tosf-t1--base.tfm \
tex-plxSerif-ExtraLight-tosf-t1.tfm \
tex-plxSerif-ExtraLight-tosf-t1.vf \
tex-plxSerif-ExtraLight-tosf-ts1--base.tfm \
tex-plxSerif-ExtraLight-tosf-ts1.tfm \
tex-plxSerif-ExtraLight-tosf-ts1.vf \
tex-plxSerif-ExtraLightItalic-sup-lgr.tfm \
tex-plxSerif-ExtraLightItalic-sup-ly1.tfm \
tex-plxSerif-ExtraLightItalic-sup-ot1.tfm \
tex-plxSerif-ExtraLightItalic-sup-t1--base.tfm \
tex-plxSerif-ExtraLightItalic-sup-t1.tfm \
tex-plxSerif-ExtraLightItalic-sup-t1.vf \
tex-plxSerif-ExtraLightItalic-tlf-lgr.tfm \
tex-plxSerif-ExtraLightItalic-tlf-ly1.tfm \
tex-plxSerif-ExtraLightItalic-tlf-ot1.tfm \
tex-plxSerif-ExtraLightItalic-tlf-t1--base.tfm \
tex-plxSerif-ExtraLightItalic-tlf-t1.tfm \
tex-plxSerif-ExtraLightItalic-tlf-t1.vf \
tex-plxSerif-ExtraLightItalic-tlf-ts1--base.tfm \
tex-plxSerif-ExtraLightItalic-tlf-ts1.tfm \
tex-plxSerif-ExtraLightItalic-tlf-ts1.vf \
tex-plxSerif-ExtraLightItalic-tosf-lgr.tfm \
tex-plxSerif-ExtraLightItalic-tosf-ly1.tfm \
tex-plxSerif-ExtraLightItalic-tosf-ot1.tfm \
tex-plxSerif-ExtraLightItalic-tosf-t1--base.tfm \
tex-plxSerif-ExtraLightItalic-tosf-t1.tfm \
tex-plxSerif-ExtraLightItalic-tosf-t1.vf \
tex-plxSerif-ExtraLightItalic-tosf-ts1--base.tfm \
tex-plxSerif-ExtraLightItalic-tosf-ts1.tfm \
tex-plxSerif-ExtraLightItalic-tosf-ts1.vf \
tex-plxSerif-Italic-sup-lgr.tfm \
tex-plxSerif-Italic-sup-ly1.tfm \
tex-plxSerif-Italic-sup-ot1.tfm \
tex-plxSerif-Italic-sup-t1--base.tfm \
tex-plxSerif-Italic-sup-t1.tfm \
tex-plxSerif-Italic-sup-t1.vf \
tex-plxSerif-Italic-tlf-lgr.tfm \
tex-plxSerif-Italic-tlf-ly1.tfm \
tex-plxSerif-Italic-tlf-ot1.tfm \
tex-plxSerif-Italic-tlf-t1--base.tfm \
tex-plxSerif-Italic-tlf-t1.tfm \
tex-plxSerif-Italic-tlf-t1.vf \
tex-plxSerif-Italic-tlf-ts1--base.tfm \
tex-plxSerif-Italic-tlf-ts1.tfm \
tex-plxSerif-Italic-tlf-ts1.vf \
tex-plxSerif-Italic-tosf-lgr.tfm \
tex-plxSerif-Italic-tosf-ly1.tfm \
tex-plxSerif-Italic-tosf-ot1.tfm \
tex-plxSerif-Italic-tosf-t1--base.tfm \
tex-plxSerif-Italic-tosf-t1.tfm \
tex-plxSerif-Italic-tosf-t1.vf \
tex-plxSerif-Italic-tosf-ts1--base.tfm \
tex-plxSerif-Italic-tosf-ts1.tfm \
tex-plxSerif-Italic-tosf-ts1.vf \
tex-plxSerif-Light-sup-lgr.tfm \
tex-plxSerif-Light-sup-ly1.tfm \
tex-plxSerif-Light-sup-ot1.tfm \
tex-plxSerif-Light-sup-t1--base.tfm \
tex-plxSerif-Light-sup-t1.tfm \
tex-plxSerif-Light-sup-t1.vf \
tex-plxSerif-Light-tlf-lgr.tfm \
tex-plxSerif-Light-tlf-ly1.tfm \
tex-plxSerif-Light-tlf-ot1.tfm \
tex-plxSerif-Light-tlf-t1--base.tfm \
tex-plxSerif-Light-tlf-t1.tfm \
tex-plxSerif-Light-tlf-t1.vf \
tex-plxSerif-Light-tlf-ts1--base.tfm \
tex-plxSerif-Light-tlf-ts1.tfm \
tex-plxSerif-Light-tlf-ts1.vf \
tex-plxSerif-Light-tosf-lgr.tfm \
tex-plxSerif-Light-tosf-ly1.tfm \
tex-plxSerif-Light-tosf-ot1.tfm \
tex-plxSerif-Light-tosf-t1--base.tfm \
tex-plxSerif-Light-tosf-t1.tfm \
tex-plxSerif-Light-tosf-t1.vf \
tex-plxSerif-Light-tosf-ts1--base.tfm \
tex-plxSerif-Light-tosf-ts1.tfm \
tex-plxSerif-Light-tosf-ts1.vf \
tex-plxSerif-LightItalic-sup-lgr.tfm \
tex-plxSerif-LightItalic-sup-ly1.tfm \
tex-plxSerif-LightItalic-sup-ot1.tfm \
tex-plxSerif-LightItalic-sup-t1--base.tfm \
tex-plxSerif-LightItalic-sup-t1.tfm \
tex-plxSerif-LightItalic-sup-t1.vf \
tex-plxSerif-LightItalic-tlf-lgr.tfm \
tex-plxSerif-LightItalic-tlf-ly1.tfm \
tex-plxSerif-LightItalic-tlf-ot1.tfm \
tex-plxSerif-LightItalic-tlf-t1--base.tfm \
tex-plxSerif-LightItalic-tlf-t1.tfm \
tex-plxSerif-LightItalic-tlf-t1.vf \
tex-plxSerif-LightItalic-tlf-ts1--base.tfm \
tex-plxSerif-LightItalic-tlf-ts1.tfm \
tex-plxSerif-LightItalic-tlf-ts1.vf \
tex-plxSerif-LightItalic-tosf-lgr.tfm \
tex-plxSerif-LightItalic-tosf-ly1.tfm \
tex-plxSerif-LightItalic-tosf-ot1.tfm \
tex-plxSerif-LightItalic-tosf-t1--base.tfm \
tex-plxSerif-LightItalic-tosf-t1.tfm \
tex-plxSerif-LightItalic-tosf-t1.vf \
tex-plxSerif-LightItalic-tosf-ts1--base.tfm \
tex-plxSerif-LightItalic-tosf-ts1.tfm \
tex-plxSerif-LightItalic-tosf-ts1.vf \
tex-plxSerif-Medium-sup-lgr.tfm \
tex-plxSerif-Medium-sup-ly1.tfm \
tex-plxSerif-Medium-sup-ot1.tfm \
tex-plxSerif-Medium-sup-t1--base.tfm \
tex-plxSerif-Medium-sup-t1.tfm \
tex-plxSerif-Medium-sup-t1.vf \
tex-plxSerif-Medium-tlf-lgr.tfm \
tex-plxSerif-Medium-tlf-ly1.tfm \
tex-plxSerif-Medium-tlf-ot1.tfm \
tex-plxSerif-Medium-tlf-t1--base.tfm \
tex-plxSerif-Medium-tlf-t1.tfm \
tex-plxSerif-Medium-tlf-t1.vf \
tex-plxSerif-Medium-tlf-ts1--base.tfm \
tex-plxSerif-Medium-tlf-ts1.tfm \
tex-plxSerif-Medium-tlf-ts1.vf \
tex-plxSerif-Medium-tosf-lgr.tfm \
tex-plxSerif-Medium-tosf-ly1.tfm \
tex-plxSerif-Medium-tosf-ot1.tfm \
tex-plxSerif-Medium-tosf-t1--base.tfm \
tex-plxSerif-Medium-tosf-t1.tfm \
tex-plxSerif-Medium-tosf-t1.vf \
tex-plxSerif-Medium-tosf-ts1--base.tfm \
tex-plxSerif-Medium-tosf-ts1.tfm \
tex-plxSerif-Medium-tosf-ts1.vf \
tex-plxSerif-MediumItalic-sup-lgr.tfm \
tex-plxSerif-MediumItalic-sup-ly1.tfm \
tex-plxSerif-MediumItalic-sup-ot1.tfm \
tex-plxSerif-MediumItalic-sup-t1--base.tfm \
tex-plxSerif-MediumItalic-sup-t1.tfm \
tex-plxSerif-MediumItalic-sup-t1.vf \
tex-plxSerif-MediumItalic-tlf-lgr.tfm \
tex-plxSerif-MediumItalic-tlf-ly1.tfm \
tex-plxSerif-MediumItalic-tlf-ot1.tfm \
tex-plxSerif-MediumItalic-tlf-t1--base.tfm \
tex-plxSerif-MediumItalic-tlf-t1.tfm \
tex-plxSerif-MediumItalic-tlf-t1.vf \
tex-plxSerif-MediumItalic-tlf-ts1--base.tfm \
tex-plxSerif-MediumItalic-tlf-ts1.tfm \
tex-plxSerif-MediumItalic-tlf-ts1.vf \
tex-plxSerif-MediumItalic-tosf-lgr.tfm \
tex-plxSerif-MediumItalic-tosf-ly1.tfm \
tex-plxSerif-MediumItalic-tosf-ot1.tfm \
tex-plxSerif-MediumItalic-tosf-t1--base.tfm \
tex-plxSerif-MediumItalic-tosf-t1.tfm \
tex-plxSerif-MediumItalic-tosf-t1.vf \
tex-plxSerif-MediumItalic-tosf-ts1--base.tfm \
tex-plxSerif-MediumItalic-tosf-ts1.tfm \
tex-plxSerif-MediumItalic-tosf-ts1.vf \
tex-plxSerif-Regular-sup-lgr.tfm \
tex-plxSerif-Regular-sup-ly1.tfm \
tex-plxSerif-Regular-sup-ot1.tfm \
tex-plxSerif-Regular-sup-t1--base.tfm \
tex-plxSerif-Regular-sup-t1.tfm \
tex-plxSerif-Regular-sup-t1.vf \
tex-plxSerif-Regular-tlf-lgr.tfm \
tex-plxSerif-Regular-tlf-ly1.tfm \
tex-plxSerif-Regular-tlf-ot1.tfm \
tex-plxSerif-Regular-tlf-t1--base.tfm \
tex-plxSerif-Regular-tlf-t1.tfm \
tex-plxSerif-Regular-tlf-t1.vf \
tex-plxSerif-Regular-tlf-ts1--base.tfm \
tex-plxSerif-Regular-tlf-ts1.tfm \
tex-plxSerif-Regular-tlf-ts1.vf \
tex-plxSerif-Regular-tosf-lgr.tfm \
tex-plxSerif-Regular-tosf-ly1.tfm \
tex-plxSerif-Regular-tosf-ot1.tfm \
tex-plxSerif-Regular-tosf-t1--base.tfm \
tex-plxSerif-Regular-tosf-t1.tfm \
tex-plxSerif-Regular-tosf-t1.vf \
tex-plxSerif-Regular-tosf-ts1--base.tfm \
tex-plxSerif-Regular-tosf-ts1.tfm \
tex-plxSerif-Regular-tosf-ts1.vf \
tex-plxSerif-SemiBold-sup-lgr.tfm \
tex-plxSerif-SemiBold-sup-ly1.tfm \
tex-plxSerif-SemiBold-sup-ot1.tfm \
tex-plxSerif-SemiBold-sup-t1--base.tfm \
tex-plxSerif-SemiBold-sup-t1.tfm \
tex-plxSerif-SemiBold-sup-t1.vf \
tex-plxSerif-SemiBold-tlf-lgr.tfm \
tex-plxSerif-SemiBold-tlf-ly1.tfm \
tex-plxSerif-SemiBold-tlf-ot1.tfm \
tex-plxSerif-SemiBold-tlf-t1--base.tfm \
tex-plxSerif-SemiBold-tlf-t1.tfm \
tex-plxSerif-SemiBold-tlf-t1.vf \
tex-plxSerif-SemiBold-tlf-ts1--base.tfm \
tex-plxSerif-SemiBold-tlf-ts1.tfm \
tex-plxSerif-SemiBold-tlf-ts1.vf \
tex-plxSerif-SemiBold-tosf-lgr.tfm \
tex-plxSerif-SemiBold-tosf-ly1.tfm \
tex-plxSerif-SemiBold-tosf-ot1.tfm \
tex-plxSerif-SemiBold-tosf-t1--base.tfm \
tex-plxSerif-SemiBold-tosf-t1.tfm \
tex-plxSerif-SemiBold-tosf-t1.vf \
tex-plxSerif-SemiBold-tosf-ts1--base.tfm \
tex-plxSerif-SemiBold-tosf-ts1.tfm \
tex-plxSerif-SemiBold-tosf-ts1.vf \
tex-plxSerif-SemiBoldItalic-sup-lgr.tfm \
tex-plxSerif-SemiBoldItalic-sup-ly1.tfm \
tex-plxSerif-SemiBoldItalic-sup-ot1.tfm \
tex-plxSerif-SemiBoldItalic-sup-t1--base.tfm \
tex-plxSerif-SemiBoldItalic-sup-t1.tfm \
tex-plxSerif-SemiBoldItalic-sup-t1.vf \
tex-plxSerif-SemiBoldItalic-tlf-lgr.tfm \
tex-plxSerif-SemiBoldItalic-tlf-ly1.tfm \
tex-plxSerif-SemiBoldItalic-tlf-ot1.tfm \
tex-plxSerif-SemiBoldItalic-tlf-t1--base.tfm \
tex-plxSerif-SemiBoldItalic-tlf-t1.tfm \
tex-plxSerif-SemiBoldItalic-tlf-t1.vf \
tex-plxSerif-SemiBoldItalic-tlf-ts1--base.tfm \
tex-plxSerif-SemiBoldItalic-tlf-ts1.tfm \
tex-plxSerif-SemiBoldItalic-tlf-ts1.vf \
tex-plxSerif-SemiBoldItalic-tosf-lgr.tfm \
tex-plxSerif-SemiBoldItalic-tosf-ly1.tfm \
tex-plxSerif-SemiBoldItalic-tosf-ot1.tfm \
tex-plxSerif-SemiBoldItalic-tosf-t1--base.tfm \
tex-plxSerif-SemiBoldItalic-tosf-t1.tfm \
tex-plxSerif-SemiBoldItalic-tosf-t1.vf \
tex-plxSerif-SemiBoldItalic-tosf-ts1--base.tfm \
tex-plxSerif-SemiBoldItalic-tosf-ts1.tfm \
tex-plxSerif-SemiBoldItalic-tosf-ts1.vf \
tex-plxSerif-Text-sup-lgr.tfm \
tex-plxSerif-Text-sup-ly1.tfm \
tex-plxSerif-Text-sup-ot1.tfm \
tex-plxSerif-Text-sup-t1--base.tfm \
tex-plxSerif-Text-sup-t1.tfm \
tex-plxSerif-Text-sup-t1.vf \
tex-plxSerif-Text-tlf-lgr.tfm \
tex-plxSerif-Text-tlf-ly1.tfm \
tex-plxSerif-Text-tlf-ot1.tfm \
tex-plxSerif-Text-tlf-t1--base.tfm \
tex-plxSerif-Text-tlf-t1.tfm \
tex-plxSerif-Text-tlf-t1.vf \
tex-plxSerif-Text-tlf-ts1--base.tfm \
tex-plxSerif-Text-tlf-ts1.tfm \
tex-plxSerif-Text-tlf-ts1.vf \
tex-plxSerif-Text-tosf-lgr.tfm \
tex-plxSerif-Text-tosf-ly1.tfm \
tex-plxSerif-Text-tosf-ot1.tfm \
tex-plxSerif-Text-tosf-t1--base.tfm \
tex-plxSerif-Text-tosf-t1.tfm \
tex-plxSerif-Text-tosf-t1.vf \
tex-plxSerif-Text-tosf-ts1--base.tfm \
tex-plxSerif-Text-tosf-ts1.tfm \
tex-plxSerif-Text-tosf-ts1.vf \
tex-plxSerif-TextItalic-sup-lgr.tfm \
tex-plxSerif-TextItalic-sup-ly1.tfm \
tex-plxSerif-TextItalic-sup-ot1.tfm \
tex-plxSerif-TextItalic-sup-t1--base.tfm \
tex-plxSerif-TextItalic-sup-t1.tfm \
tex-plxSerif-TextItalic-sup-t1.vf \
tex-plxSerif-TextItalic-tlf-lgr.tfm \
tex-plxSerif-TextItalic-tlf-ly1.tfm \
tex-plxSerif-TextItalic-tlf-ot1.tfm \
tex-plxSerif-TextItalic-tlf-t1--base.tfm \
tex-plxSerif-TextItalic-tlf-t1.tfm \
tex-plxSerif-TextItalic-tlf-t1.vf \
tex-plxSerif-TextItalic-tlf-ts1--base.tfm \
tex-plxSerif-TextItalic-tlf-ts1.tfm \
tex-plxSerif-TextItalic-tlf-ts1.vf \
tex-plxSerif-TextItalic-tosf-lgr.tfm \
tex-plxSerif-TextItalic-tosf-ly1.tfm \
tex-plxSerif-TextItalic-tosf-ot1.tfm \
tex-plxSerif-TextItalic-tosf-t1--base.tfm \
tex-plxSerif-TextItalic-tosf-t1.tfm \
tex-plxSerif-TextItalic-tosf-t1.vf \
tex-plxSerif-TextItalic-tosf-ts1--base.tfm \
tex-plxSerif-TextItalic-tosf-ts1.tfm \
tex-plxSerif-TextItalic-tosf-ts1.vf \
tex-plxSerif-Thin-sup-lgr.tfm \
tex-plxSerif-Thin-sup-ly1.tfm \
tex-plxSerif-Thin-sup-ot1.tfm \
tex-plxSerif-Thin-sup-t1--base.tfm \
tex-plxSerif-Thin-sup-t1.tfm \
tex-plxSerif-Thin-sup-t1.vf \
tex-plxSerif-Thin-tlf-lgr.tfm \
tex-plxSerif-Thin-tlf-ly1.tfm \
tex-plxSerif-Thin-tlf-ot1.tfm \
tex-plxSerif-Thin-tlf-t1--base.tfm \
tex-plxSerif-Thin-tlf-t1.tfm \
tex-plxSerif-Thin-tlf-t1.vf \
tex-plxSerif-Thin-tlf-ts1--base.tfm \
tex-plxSerif-Thin-tlf-ts1.tfm \
tex-plxSerif-Thin-tlf-ts1.vf \
tex-plxSerif-Thin-tosf-lgr.tfm \
tex-plxSerif-Thin-tosf-ly1.tfm \
tex-plxSerif-Thin-tosf-ot1.tfm \
tex-plxSerif-Thin-tosf-t1--base.tfm \
tex-plxSerif-Thin-tosf-t1.tfm \
tex-plxSerif-Thin-tosf-t1.vf \
tex-plxSerif-Thin-tosf-ts1--base.tfm \
tex-plxSerif-Thin-tosf-ts1.tfm \
tex-plxSerif-Thin-tosf-ts1.vf \
tex-plxSerif-ThinItalic-sup-lgr.tfm \
tex-plxSerif-ThinItalic-sup-ly1.tfm \
tex-plxSerif-ThinItalic-sup-ot1.tfm \
tex-plxSerif-ThinItalic-sup-t1--base.tfm \
tex-plxSerif-ThinItalic-sup-t1.tfm \
tex-plxSerif-ThinItalic-sup-t1.vf \
tex-plxSerif-ThinItalic-tlf-lgr.tfm \
tex-plxSerif-ThinItalic-tlf-ly1.tfm \
tex-plxSerif-ThinItalic-tlf-ot1.tfm \
tex-plxSerif-ThinItalic-tlf-t1--base.tfm \
tex-plxSerif-ThinItalic-tlf-t1.tfm \
tex-plxSerif-ThinItalic-tlf-t1.vf \
tex-plxSerif-ThinItalic-tlf-ts1--base.tfm \
tex-plxSerif-ThinItalic-tlf-ts1.tfm \
tex-plxSerif-ThinItalic-tlf-ts1.vf \
tex-plxSerif-ThinItalic-tosf-lgr.tfm \
tex-plxSerif-ThinItalic-tosf-ly1.tfm \
tex-plxSerif-ThinItalic-tosf-ot1.tfm \
tex-plxSerif-ThinItalic-tosf-t1--base.tfm \
tex-plxSerif-ThinItalic-tosf-t1.tfm \
tex-plxSerif-ThinItalic-tosf-t1.vf \
tex-plxSerif-ThinItalic-tosf-ts1--base.tfm \
tex-plxSerif-ThinItalic-tosf-ts1.tfm \
tex-plxSerif-ThinItalic-tosf-ts1.vf \
tex-plxSerif.map \
texlive-plex"

RDEPENDS:${PN} += "/usr/bin/sh \
coreutils \
ed \
findutils \
grep \
sed \
tex-fontaxes.sty \
tex-fontenc.sty \
tex-fontspec.sty \
tex-ifluatex.sty \
tex-ifxetex.sty \
tex-mweights.sty \
tex-textcomp.sty \
tex-updmap.cfg \
tex-xkeyval.sty \
texlive \
texlive-filesystem \
texlive-kpathsea \
texlive-kpathsea-bin \
texlive-plex-fonts \
texlive-scripts \
texlive-scripts-bin"

inherit rpm
