SUMMARY = "Kernel driver"
DESCRIPTION = "This module is the kernel-dependent driver for DRBD. This is split out so \
that multiple kernel driver versions can be installed, one for each \
installed kernel."
LICENSE = "GPL-2.0-or-later"

PV = "9.1.23_k7.2.4_1"

RPM_NAME = "drbd-kmp-64kb-9.1.23_k7.2.4_1-10.3.aarch64.rpm"
RPM_HASH = "bb839030d94eb83c89dc90d1077e74db0b7f87a4cde1debe1c98cb0c874483c60a36b99e06dd28f46eaf432596e40d3ca3e4a455a49cc921fc40ed755448670d"

RPROVIDES:${PN} += "drbd-kmp \
drbd-kmp-64kb \
drbd-kmp-64kb-k7.2.4-1 \
kmod-drbd-transport-tcp.ko \
kmod-drbd.ko \
ksym-64kb---drbd-next-path-ref \
ksym-64kb-drbd-alloc-pages \
ksym-64kb-drbd-destroy-connection \
ksym-64kb-drbd-destroy-path \
ksym-64kb-drbd-find-path-by-addr \
ksym-64kb-drbd-free-pages \
ksym-64kb-drbd-get-listener \
ksym-64kb-drbd-listener-destroy \
ksym-64kb-drbd-path-event \
ksym-64kb-drbd-put-listener \
ksym-64kb-drbd-register-transport-class \
ksym-64kb-drbd-should-abort-listening \
ksym-64kb-drbd-stream-send-timed-out \
ksym-64kb-drbd-unregister-transport-class \
multiversion-kernel"

RDEPENDS:${PN} += "/usr/bin/sh \
coreutils \
grep \
kernel-64kb \
ksym-64kb----ratelimit \
ksym-64kb---alloc-skb \
ksym-64kb---bio-add-page \
ksym-64kb---bitmap-and \
ksym-64kb---bitmap-equal \
ksym-64kb---blk-alloc-disk \
ksym-64kb---cpu-online-mask \
ksym-64kb---cpu-possible-mask \
ksym-64kb---dynamic-pr-debug \
ksym-64kb---folio-put \
ksym-64kb---fortify-panic \
ksym-64kb---free-pages \
ksym-64kb---get-random-u32-below \
ksym-64kb---init-rwsem \
ksym-64kb---init-swait-queue-head \
ksym-64kb---init-waitqueue-head \
ksym-64kb---ipv6-addr-type \
ksym-64kb---kmalloc-cache-noprof \
ksym-64kb---kmalloc-noprof \
ksym-64kb---kmem-cache-create-args \
ksym-64kb---list-add-valid-or-report \
ksym-64kb---list-del-entry-valid-or-report \
ksym-64kb---nla-parse \
ksym-64kb---per-cpu-offset \
ksym-64kb---rb-erase-color \
ksym-64kb---rb-insert-augmented \
ksym-64kb---rcu-read-lock \
ksym-64kb---rcu-read-unlock \
ksym-64kb---register-blkdev \
ksym-64kb---request-module \
ksym-64kb---seq-puts \
ksym-64kb---stack-chk-fail \
ksym-64kb---sw-hweight32 \
ksym-64kb---sw-hweight64 \
ksym-64kb---vmalloc-noprof \
ksym-64kb---wake-up \
ksym-64kb---warn-printk \
ksym-64kb--find-first-bit \
ksym-64kb--find-next-bit \
ksym-64kb--find-next-zero-bit \
ksym-64kb--printk \
ksym-64kb--raw-read-lock \
ksym-64kb--raw-read-lock-irq \
ksym-64kb--raw-read-lock-irqsave \
ksym-64kb--raw-read-unlock \
ksym-64kb--raw-read-unlock-irq \
ksym-64kb--raw-read-unlock-irqrestore \
ksym-64kb--raw-spin-lock \
ksym-64kb--raw-spin-lock-bh \
ksym-64kb--raw-spin-lock-irq \
ksym-64kb--raw-spin-lock-irqsave \
ksym-64kb--raw-spin-unlock \
ksym-64kb--raw-spin-unlock-bh \
ksym-64kb--raw-spin-unlock-irq \
ksym-64kb--raw-spin-unlock-irqrestore \
ksym-64kb--raw-write-lock-bh \
ksym-64kb--raw-write-lock-irq \
ksym-64kb--raw-write-lock-irqsave \
ksym-64kb--raw-write-unlock-bh \
ksym-64kb--raw-write-unlock-irq \
ksym-64kb--raw-write-unlock-irqrestore \
ksym-64kb-alloc-cpumask-var-node \
ksym-64kb-alloc-pages-noprof \
ksym-64kb-alloc-workqueue-noprof \
ksym-64kb-alt-cb-patch-nops \
ksym-64kb-arch-wb-cache-pmem \
ksym-64kb-autoremove-wake-function \
ksym-64kb-bd-link-disk-holder \
ksym-64kb-bd-unlink-disk-holder \
ksym-64kb-bdev-alignment-offset \
ksym-64kb-bdev-discard-alignment \
ksym-64kb-bdev-file-open-by-path \
ksym-64kb-bio-add-page \
ksym-64kb-bio-alloc-bioset \
ksym-64kb-bio-alloc-clone \
ksym-64kb-bio-associate-blkg \
ksym-64kb-bio-end-io-acct-remapped \
ksym-64kb-bio-endio \
ksym-64kb-bio-put \
ksym-64kb-bio-split-to-limits \
ksym-64kb-bio-start-io-acct \
ksym-64kb-bioset-exit \
ksym-64kb-bioset-init \
ksym-64kb-bitmap-parse \
ksym-64kb-blk-check-plugged \
ksym-64kb-blk-finish-plug \
ksym-64kb-blk-set-stacking-limits \
ksym-64kb-blk-stack-limits \
ksym-64kb-blk-start-plug \
ksym-64kb-blk-status-to-errno \
ksym-64kb-blkdev-issue-discard \
ksym-64kb-blkdev-issue-zeroout \
ksym-64kb-call-rcu \
ksym-64kb-call-usermodehelper \
ksym-64kb-cancel-work-sync \
ksym-64kb-capable \
ksym-64kb-complete \
ksym-64kb-complete-all \
ksym-64kb-copy-highpage \
ksym-64kb-crc32c \
ksym-64kb-crypto-alloc-shash \
ksym-64kb-crypto-destroy-tfm \
ksym-64kb-crypto-shash-digest \
ksym-64kb-crypto-shash-finup \
ksym-64kb-crypto-shash-init \
ksym-64kb-crypto-shash-setkey \
ksym-64kb-dax-direct-access \
ksym-64kb-dax-read-lock \
ksym-64kb-dax-read-unlock \
ksym-64kb-debugfs-change-name \
ksym-64kb-debugfs-create-dir \
ksym-64kb-debugfs-create-file-full \
ksym-64kb-debugfs-create-symlink \
ksym-64kb-debugfs-remove \
ksym-64kb-del-gendisk \
ksym-64kb-destroy-workqueue \
ksym-64kb-device-add-disk \
ksym-64kb-down \
ksym-64kb-down-interruptible \
ksym-64kb-down-read \
ksym-64kb-down-trylock \
ksym-64kb-down-write \
ksym-64kb-down-write-trylock \
ksym-64kb-downgrade-write \
ksym-64kb-dynamic-cond-resched \
ksym-64kb-dynamic-might-resched \
ksym-64kb-dynamic-preempt-schedule \
ksym-64kb-errno-to-blk-status \
ksym-64kb-file-bdev \
ksym-64kb-finish-wait \
ksym-64kb-flush-signals \
ksym-64kb-fput \
ksym-64kb-free-cpumask-var \
ksym-64kb-free-pages \
ksym-64kb-fs-bio-set \
ksym-64kb-fs-dax-get-by-bdev \
ksym-64kb-genl-register-family \
ksym-64kb-genl-unregister-family \
ksym-64kb-genlmsg-multicast-allns \
ksym-64kb-genlmsg-put \
ksym-64kb-get-free-pages-noprof \
ksym-64kb-get-random-bytes \
ksym-64kb-get-random-u32 \
ksym-64kb-get-random-u8 \
ksym-64kb-idr-alloc \
ksym-64kb-idr-destroy \
ksym-64kb-idr-find \
ksym-64kb-idr-get-next \
ksym-64kb-idr-remove \
ksym-64kb-init-net \
ksym-64kb-init-wait-entry \
ksym-64kb-iov-iter-bvec \
ksym-64kb-jiffies \
ksym-64kb-kasprintf \
ksym-64kb-kernel-accept \
ksym-64kb-kernel-recvmsg \
ksym-64kb-kernel-sendmsg \
ksym-64kb-kernel-sigaction \
ksym-64kb-kernel-sock-shutdown \
ksym-64kb-kfree \
ksym-64kb-kmalloc-caches \
ksym-64kb-kmem-cache-destroy \
ksym-64kb-kobject-uevent \
ksym-64kb-kstrdup \
ksym-64kb-kstrtoull \
ksym-64kb-kthread-create-on-node \
ksym-64kb-ktime-get \
ksym-64kb-ktime-get-with-offset \
ksym-64kb-kvasprintf \
ksym-64kb-kvfree \
ksym-64kb-kvfree-call-rcu \
ksym-64kb-lc-committed \
ksym-64kb-lc-create \
ksym-64kb-lc-del \
ksym-64kb-lc-destroy \
ksym-64kb-lc-element-by-index \
ksym-64kb-lc-find \
ksym-64kb-lc-get \
ksym-64kb-lc-get-cumulative \
ksym-64kb-lc-is-used \
ksym-64kb-lc-put \
ksym-64kb-lc-reset \
ksym-64kb-lc-seq-dump-details \
ksym-64kb-lc-seq-printf-stats \
ksym-64kb-lc-try-get \
ksym-64kb-lc-try-lock \
ksym-64kb-memcmp \
ksym-64kb-memcpy \
ksym-64kb-memmove \
ksym-64kb-mempool-alloc-noprof \
ksym-64kb-mempool-alloc-pages \
ksym-64kb-mempool-alloc-slab \
ksym-64kb-mempool-exit \
ksym-64kb-mempool-free \
ksym-64kb-mempool-free-pages \
ksym-64kb-mempool-free-slab \
ksym-64kb-mempool-init-noprof \
ksym-64kb-memset \
ksym-64kb-mod-timer \
ksym-64kb-mod-timer-pending \
ksym-64kb-module-layout \
ksym-64kb-module-put \
ksym-64kb-mutex-init-generic \
ksym-64kb-mutex-is-locked \
ksym-64kb-mutex-lock \
ksym-64kb-mutex-lock-interruptible \
ksym-64kb-mutex-trylock \
ksym-64kb-mutex-unlock \
ksym-64kb-netlink-unicast \
ksym-64kb-nla-find \
ksym-64kb-nla-memcpy \
ksym-64kb-nla-put \
ksym-64kb-nla-put-64bit \
ksym-64kb-nla-put-nohdr \
ksym-64kb-nla-reserve \
ksym-64kb-nla-strscpy \
ksym-64kb-nr-cpu-ids \
ksym-64kb-ns-to-timespec64 \
ksym-64kb-panic \
ksym-64kb-param-get-uint \
ksym-64kb-param-ops-bool \
ksym-64kb-param-ops-string \
ksym-64kb-param-ops-uint \
ksym-64kb-prepare-to-wait \
ksym-64kb-prepare-to-wait-event \
ksym-64kb-proc-create-single-data \
ksym-64kb-put-dax \
ksym-64kb-put-disk \
ksym-64kb-queue-limits-commit-update \
ksym-64kb-queue-work-on \
ksym-64kb-radix-tree-tagged \
ksym-64kb-random-kmalloc-seed \
ksym-64kb-rb-next \
ksym-64kb-rcu-barrier \
ksym-64kb-refcount-warn-saturate \
ksym-64kb-remove-proc-entry \
ksym-64kb-sched-set-fifo-low \
ksym-64kb-schedule \
ksym-64kb-schedule-timeout \
ksym-64kb-schedule-timeout-interruptible \
ksym-64kb-schedule-timeout-uninterruptible \
ksym-64kb-scnprintf \
ksym-64kb-send-sig \
ksym-64kb-seq-lseek \
ksym-64kb-seq-printf \
ksym-64kb-seq-putc \
ksym-64kb-seq-read \
ksym-64kb-seq-write \
ksym-64kb-set-capacity-and-notify \
ksym-64kb-set-cpus-allowed-ptr \
ksym-64kb-sigprocmask \
ksym-64kb-single-open \
ksym-64kb-single-release \
ksym-64kb-sized-strscpy \
ksym-64kb-sk-skb-reason-drop \
ksym-64kb-skb-trim \
ksym-64kb-snprintf \
ksym-64kb-sock-create-kern \
ksym-64kb-sock-release \
ksym-64kb-sock-sendmsg \
ksym-64kb-sock-set-keepalive \
ksym-64kb-sprintf \
ksym-64kb-strcmp \
ksym-64kb-strlen \
ksym-64kb-strnlen \
ksym-64kb-strstr \
ksym-64kb-submit-bio \
ksym-64kb-submit-bio-noacct \
ksym-64kb-sync-blockdev \
ksym-64kb-synchronize-rcu \
ksym-64kb-sys-tz \
ksym-64kb-system-percpu-wq \
ksym-64kb-tcp-sock-set-cork \
ksym-64kb-tcp-sock-set-keepcnt \
ksym-64kb-tcp-sock-set-keepidle \
ksym-64kb-tcp-sock-set-keepintvl \
ksym-64kb-tcp-sock-set-nodelay \
ksym-64kb-tcp-sock-set-quickack \
ksym-64kb-time64-to-tm \
ksym-64kb-timer-delete \
ksym-64kb-timer-delete-sync \
ksym-64kb-timer-init-key \
ksym-64kb-timer-shutdown-sync \
ksym-64kb-try-module-get \
ksym-64kb-unregister-blkdev \
ksym-64kb-up \
ksym-64kb-up-read \
ksym-64kb-up-write \
ksym-64kb-vscnprintf \
ksym-64kb-vsnprintf \
ksym-64kb-wait-for-completion \
ksym-64kb-wait-for-completion-interruptible \
ksym-64kb-wake-up-process \
suse-kernel-rpm-scriptlets"

inherit rpm
