SUMMARY = "Sched_ext CPU schedulers"
DESCRIPTION = "sched_ext is a Linux kernel feature which enables implementing kernel thread schedulers in BPF and dynamically loading them. This package contains various scheduler implementations and support utilities."
LICENSE = "GPL-2.0-only"

PV = "1.1.3"

RPM_NAME = "scx-1.1.3-1.1.aarch64.rpm"
RPM_HASH = "34a53a28290fbe224add0739899d032768c37ad7a35f7ddebf975dcf4ead18a00477b9e8d95f50c64604b7e08145377a536fe0b4886bdd88b34986914b744727"

RPROVIDES:${PN} += "bundled-rust-crate-addr2line \
bundled-rust-crate-adler2 \
bundled-rust-crate-affinity \
bundled-rust-crate-ahash \
bundled-rust-crate-aho-corasick \
bundled-rust-crate-allocator-api2 \
bundled-rust-crate-anstream \
bundled-rust-crate-anstyle \
bundled-rust-crate-anstyle-parse \
bundled-rust-crate-anstyle-query \
bundled-rust-crate-anyhow \
bundled-rust-crate-approx \
bundled-rust-crate-arrayvec \
bundled-rust-crate-ascii \
bundled-rust-crate-async-broadcast \
bundled-rust-crate-async-channel \
bundled-rust-crate-async-executor \
bundled-rust-crate-async-io \
bundled-rust-crate-async-lock \
bundled-rust-crate-async-process \
bundled-rust-crate-async-recursion \
bundled-rust-crate-async-signal \
bundled-rust-crate-async-task \
bundled-rust-crate-async-trait \
bundled-rust-crate-atomic \
bundled-rust-crate-atomic-waker \
bundled-rust-crate-autocfg \
bundled-rust-crate-backtrace \
bundled-rust-crate-base64 \
bundled-rust-crate-below-common \
bundled-rust-crate-bindgen \
bundled-rust-crate-bit-set \
bundled-rust-crate-bit-vec \
bundled-rust-crate-bitflags \
bundled-rust-crate-bitvec \
bundled-rust-crate-blazesym \
bundled-rust-crate-block-buffer \
bundled-rust-crate-blocking \
bundled-rust-crate-buddy-system-allocator \
bundled-rust-crate-by-address \
bundled-rust-crate-bytemuck \
bundled-rust-crate-bytes \
bundled-rust-crate-camino \
bundled-rust-crate-cargo-metadata \
bundled-rust-crate-cargo-platform \
bundled-rust-crate-castaway \
bundled-rust-crate-cc \
bundled-rust-crate-cexpr \
bundled-rust-crate-cfg-aliases \
bundled-rust-crate-cfg-if \
bundled-rust-crate-cgroupfs \
bundled-rust-crate-chacha20 \
bundled-rust-crate-chrono \
bundled-rust-crate-chunked-transfer \
bundled-rust-crate-clang-sys \
bundled-rust-crate-clap \
bundled-rust-crate-clap-builder \
bundled-rust-crate-clap-complete \
bundled-rust-crate-clap-derive \
bundled-rust-crate-clap-lex \
bundled-rust-crate-clap-main \
bundled-rust-crate-clap-num \
bundled-rust-crate-colorchoice \
bundled-rust-crate-compact-str \
bundled-rust-crate-concurrent-queue \
bundled-rust-crate-convert-case \
bundled-rust-crate-cpp-demangle \
bundled-rust-crate-cpufeatures \
bundled-rust-crate-crc32fast \
bundled-rust-crate-critical-section \
bundled-rust-crate-crossbeam \
bundled-rust-crate-crossbeam-channel \
bundled-rust-crate-crossbeam-deque \
bundled-rust-crate-crossbeam-epoch \
bundled-rust-crate-crossbeam-queue \
bundled-rust-crate-crossbeam-utils \
bundled-rust-crate-crossterm \
bundled-rust-crate-crypto-common \
bundled-rust-crate-csscolorparser \
bundled-rust-crate-csv \
bundled-rust-crate-csv-core \
bundled-rust-crate-ctrlc \
bundled-rust-crate-cursive \
bundled-rust-crate-cursive-core \
bundled-rust-crate-darling \
bundled-rust-crate-darling-core \
bundled-rust-crate-darling-macro \
bundled-rust-crate-deltae \
bundled-rust-crate-deranged \
bundled-rust-crate-derive-more \
bundled-rust-crate-derive-more-impl \
bundled-rust-crate-digest \
bundled-rust-crate-document-features \
bundled-rust-crate-either \
bundled-rust-crate-encoding-rs \
bundled-rust-crate-endi \
bundled-rust-crate-enum-map \
bundled-rust-crate-enum-map-derive \
bundled-rust-crate-enumflags2 \
bundled-rust-crate-enumflags2-derive \
bundled-rust-crate-enumset \
bundled-rust-crate-enumset-derive \
bundled-rust-crate-equivalent \
bundled-rust-crate-erased-serde \
bundled-rust-crate-errno \
bundled-rust-crate-euclid \
bundled-rust-crate-event-listener \
bundled-rust-crate-event-listener-strategy \
bundled-rust-crate-fancy-regex \
bundled-rust-crate-fastrand \
bundled-rust-crate-fb-procfs \
bundled-rust-crate-filedescriptor \
bundled-rust-crate-filetime \
bundled-rust-crate-find-msvc-tools \
bundled-rust-crate-finl-unicode \
bundled-rust-crate-fixedbitset \
bundled-rust-crate-flate2 \
bundled-rust-crate-fnv \
bundled-rust-crate-foldhash \
bundled-rust-crate-funty \
bundled-rust-crate-futures \
bundled-rust-crate-futures-channel \
bundled-rust-crate-futures-core \
bundled-rust-crate-futures-executor \
bundled-rust-crate-futures-io \
bundled-rust-crate-futures-lite \
bundled-rust-crate-futures-macro \
bundled-rust-crate-futures-sink \
bundled-rust-crate-futures-task \
bundled-rust-crate-futures-util \
bundled-rust-crate-generic-array \
bundled-rust-crate-getrandom \
bundled-rust-crate-gimli \
bundled-rust-crate-glob \
bundled-rust-crate-gpoint \
bundled-rust-crate-hashbrown \
bundled-rust-crate-heck \
bundled-rust-crate-hex \
bundled-rust-crate-home \
bundled-rust-crate-httpdate \
bundled-rust-crate-humantime \
bundled-rust-crate-iana-time-zone \
bundled-rust-crate-ident-case \
bundled-rust-crate-include-dir \
bundled-rust-crate-include-dir-macros \
bundled-rust-crate-indexmap \
bundled-rust-crate-indoc \
bundled-rust-crate-inotify \
bundled-rust-crate-inotify-sys \
bundled-rust-crate-instability \
bundled-rust-crate-is-terminal \
bundled-rust-crate-is-terminal-polyfill \
bundled-rust-crate-itertools \
bundled-rust-crate-itoa \
bundled-rust-crate-kasuari \
bundled-rust-crate-lab \
bundled-rust-crate-lazy-static \
bundled-rust-crate-libbpf-cargo \
bundled-rust-crate-libbpf-rs \
bundled-rust-crate-libbpf-sys \
bundled-rust-crate-libc \
bundled-rust-crate-libloading \
bundled-rust-crate-libm \
bundled-rust-crate-line-clipping \
bundled-rust-crate-linux-raw-sys \
bundled-rust-crate-litrs \
bundled-rust-crate-lock-api \
bundled-rust-crate-log \
bundled-rust-crate-log-panics \
bundled-rust-crate-lru \
bundled-rust-crate-mac-address \
bundled-rust-crate-maplit \
bundled-rust-crate-matchers \
bundled-rust-crate-memchr \
bundled-rust-crate-memmap2 \
bundled-rust-crate-memmem \
bundled-rust-crate-memoffset \
bundled-rust-crate-minimal-lexical \
bundled-rust-crate-miniz-oxide \
bundled-rust-crate-mio \
bundled-rust-crate-nix \
bundled-rust-crate-nom \
bundled-rust-crate-nu-ansi-term \
bundled-rust-crate-num \
bundled-rust-crate-num-bigint \
bundled-rust-crate-num-complex \
bundled-rust-crate-num-conv \
bundled-rust-crate-num-cpus \
bundled-rust-crate-num-derive \
bundled-rust-crate-num-format \
bundled-rust-crate-num-integer \
bundled-rust-crate-num-iter \
bundled-rust-crate-num-rational \
bundled-rust-crate-num-threads \
bundled-rust-crate-num-traits \
bundled-rust-crate-numtoa \
bundled-rust-crate-nvml-wrapper \
bundled-rust-crate-nvml-wrapper-sys \
bundled-rust-crate-object \
bundled-rust-crate-once-cell \
bundled-rust-crate-openat \
bundled-rust-crate-ordered-float \
bundled-rust-crate-ordered-stream \
bundled-rust-crate-owning-ref \
bundled-rust-crate-palette \
bundled-rust-crate-palette-derive \
bundled-rust-crate-palette-math \
bundled-rust-crate-parking \
bundled-rust-crate-parking-lot \
bundled-rust-crate-parking-lot-core \
bundled-rust-crate-paste \
bundled-rust-crate-perfetto-protos \
bundled-rust-crate-pest \
bundled-rust-crate-pest-derive \
bundled-rust-crate-pest-generator \
bundled-rust-crate-pest-meta \
bundled-rust-crate-phf \
bundled-rust-crate-phf-codegen \
bundled-rust-crate-phf-generator \
bundled-rust-crate-phf-macros \
bundled-rust-crate-phf-shared \
bundled-rust-crate-pin-project-lite \
bundled-rust-crate-piper \
bundled-rust-crate-pkg-config \
bundled-rust-crate-plain \
bundled-rust-crate-polling \
bundled-rust-crate-portable-atomic \
bundled-rust-crate-powerfmt \
bundled-rust-crate-prettyplease \
bundled-rust-crate-proc-macro-crate \
bundled-rust-crate-proc-macro2 \
bundled-rust-crate-procfs \
bundled-rust-crate-procfs-core \
bundled-rust-crate-protobuf \
bundled-rust-crate-protobuf-codegen \
bundled-rust-crate-protobuf-parse \
bundled-rust-crate-protobuf-support \
bundled-rust-crate-protoc-bin-vendored \
bundled-rust-crate-protoc-bin-vendored-linux-aarch-64 \
bundled-rust-crate-protoc-bin-vendored-linux-ppcle-64 \
bundled-rust-crate-protoc-bin-vendored-linux-s390-64 \
bundled-rust-crate-protoc-bin-vendored-linux-x86-32 \
bundled-rust-crate-protoc-bin-vendored-linux-x86-64 \
bundled-rust-crate-protoc-bin-vendored-macos-aarch-64 \
bundled-rust-crate-protoc-bin-vendored-macos-x86-64 \
bundled-rust-crate-protoc-bin-vendored-win32 \
bundled-rust-crate-quote \
bundled-rust-crate-radium \
bundled-rust-crate-rand \
bundled-rust-crate-rand-core \
bundled-rust-crate-ratatui \
bundled-rust-crate-ratatui-core \
bundled-rust-crate-ratatui-crossterm \
bundled-rust-crate-ratatui-macros \
bundled-rust-crate-ratatui-termina \
bundled-rust-crate-ratatui-termion \
bundled-rust-crate-ratatui-termwiz \
bundled-rust-crate-ratatui-widgets \
bundled-rust-crate-rayon \
bundled-rust-crate-rayon-core \
bundled-rust-crate-regex \
bundled-rust-crate-regex-automata \
bundled-rust-crate-regex-syntax \
bundled-rust-crate-rlimit \
bundled-rust-crate-rustc-demangle \
bundled-rust-crate-rustc-hash \
bundled-rust-crate-rustc-version \
bundled-rust-crate-rustix \
bundled-rust-crate-rustversion \
bundled-rust-crate-ruzstd \
bundled-rust-crate-ryu \
bundled-rust-crate-same-file \
bundled-rust-crate-scopeguard \
bundled-rust-crate-scx-arena \
bundled-rust-crate-scx-arena-selftests \
bundled-rust-crate-scx-beerland \
bundled-rust-crate-scx-bpf-compat \
bundled-rust-crate-scx-bpfland \
bundled-rust-crate-scx-cake \
bundled-rust-crate-scx-cargo \
bundled-rust-crate-scx-chaos \
bundled-rust-crate-scx-characterize \
bundled-rust-crate-scx-cosmos \
bundled-rust-crate-scx-flash \
bundled-rust-crate-scx-flow \
bundled-rust-crate-scx-forge \
bundled-rust-crate-scx-lavd \
bundled-rust-crate-scx-layered \
bundled-rust-crate-scx-mitosis \
bundled-rust-crate-scx-mlfq \
bundled-rust-crate-scx-p2dq \
bundled-rust-crate-scx-pandemonium \
bundled-rust-crate-scx-raw-pmu \
bundled-rust-crate-scx-rlfifo \
bundled-rust-crate-scx-rustland \
bundled-rust-crate-scx-rustland-core \
bundled-rust-crate-scx-rusty \
bundled-rust-crate-scx-stats \
bundled-rust-crate-scx-stats-derive \
bundled-rust-crate-scx-tickless \
bundled-rust-crate-scx-userspace-arena \
bundled-rust-crate-scx-utils \
bundled-rust-crate-scxtop \
bundled-rust-crate-seccomp \
bundled-rust-crate-seccomp-sys \
bundled-rust-crate-semver \
bundled-rust-crate-serde \
bundled-rust-crate-serde-core \
bundled-rust-crate-serde-derive \
bundled-rust-crate-serde-json \
bundled-rust-crate-serde-repr \
bundled-rust-crate-serde-spanned \
bundled-rust-crate-sha2 \
bundled-rust-crate-sharded-slab \
bundled-rust-crate-shlex \
bundled-rust-crate-signal-hook \
bundled-rust-crate-signal-hook-mio \
bundled-rust-crate-signal-hook-registry \
bundled-rust-crate-simd-adler32 \
bundled-rust-crate-simplelog \
bundled-rust-crate-siphasher \
bundled-rust-crate-slab \
bundled-rust-crate-slog \
bundled-rust-crate-slog-term \
bundled-rust-crate-smallvec \
bundled-rust-crate-smartstring \
bundled-rust-crate-socket2 \
bundled-rust-crate-sorted-vec \
bundled-rust-crate-sscanf \
bundled-rust-crate-sscanf-macro \
bundled-rust-crate-stable-deref-trait \
bundled-rust-crate-static-assertions \
bundled-rust-crate-strsim \
bundled-rust-crate-strum \
bundled-rust-crate-strum-macros \
bundled-rust-crate-syn \
bundled-rust-crate-sysinfo \
bundled-rust-crate-tap \
bundled-rust-crate-tar \
bundled-rust-crate-tempfile \
bundled-rust-crate-term \
bundled-rust-crate-termcolor \
bundled-rust-crate-termina \
bundled-rust-crate-terminal-size \
bundled-rust-crate-terminfo \
bundled-rust-crate-termion \
bundled-rust-crate-termios \
bundled-rust-crate-termwiz \
bundled-rust-crate-thiserror \
bundled-rust-crate-thiserror-impl \
bundled-rust-crate-thread-local \
bundled-rust-crate-threadpool \
bundled-rust-crate-time \
bundled-rust-crate-time-core \
bundled-rust-crate-time-macros \
bundled-rust-crate-tiny-http \
bundled-rust-crate-tokio \
bundled-rust-crate-tokio-macros \
bundled-rust-crate-tokio-util \
bundled-rust-crate-toml \
bundled-rust-crate-toml-datetime \
bundled-rust-crate-toml-edit \
bundled-rust-crate-toml-parser \
bundled-rust-crate-toml-writer \
bundled-rust-crate-tracing \
bundled-rust-crate-tracing-attributes \
bundled-rust-crate-tracing-core \
bundled-rust-crate-tracing-log \
bundled-rust-crate-tracing-subscriber \
bundled-rust-crate-twox-hash \
bundled-rust-crate-typenum \
bundled-rust-crate-ucd-trie \
bundled-rust-crate-unicase \
bundled-rust-crate-unicode-ident \
bundled-rust-crate-unicode-segmentation \
bundled-rust-crate-unicode-truncate \
bundled-rust-crate-unicode-width \
bundled-rust-crate-utf8parse \
bundled-rust-crate-uuid \
bundled-rust-crate-version-check \
bundled-rust-crate-version-compare \
bundled-rust-crate-vsprintf \
bundled-rust-crate-vtparse \
bundled-rust-crate-walkdir \
bundled-rust-crate-wezterm-bidi \
bundled-rust-crate-wezterm-blob-leases \
bundled-rust-crate-wezterm-color-types \
bundled-rust-crate-wezterm-dynamic \
bundled-rust-crate-wezterm-dynamic-derive \
bundled-rust-crate-wezterm-input-types \
bundled-rust-crate-which \
bundled-rust-crate-winnow \
bundled-rust-crate-wrapcenum-derive \
bundled-rust-crate-wyz \
bundled-rust-crate-xattr \
bundled-rust-crate-xdg \
bundled-rust-crate-xi-unicode \
bundled-rust-crate-zbus \
bundled-rust-crate-zbus-macros \
bundled-rust-crate-zbus-names \
bundled-rust-crate-zcheapstr \
bundled-rust-crate-zerocopy \
bundled-rust-crate-zerocopy-derive \
bundled-rust-crate-zlib-rs \
bundled-rust-crate-zmij \
bundled-rust-crate-zvariant \
bundled-rust-crate-zvariant-derive \
bundled-rust-crate-zvariant-utils \
config-scx \
scx"

RDEPENDS:${PN} += "/usr/bin/sh \
libc.so.6 \
libelf.so.1 \
libgcc-s.so.1 \
libm.so.6 \
libseccomp.so.2 \
libz.so.1"

inherit rpm
