SUMMARY = "A new type of shell"
DESCRIPTION = "A modern shell written in Rust."
LICENSE = "MIT"

PV = "0.115.1"

RPM_NAME = "nushell-0.115.1-1.2.aarch64.rpm"
RPM_HASH = "bf007b40e650a59b7c86d7b6dda86701e6af6ca22b87da4566d355352bbfac14bf5712507b92e08380018ce2224a040a63d25cd87070bb02bad84f90aa8e6ac9"

RPROVIDES:${PN} += "bundled-rust-crate-addr2line \
bundled-rust-crate-adler2 \
bundled-rust-crate-aegis-password-generator \
bundled-rust-crate-ahash \
bundled-rust-crate-aho-corasick \
bundled-rust-crate-alloc-no-stdlib \
bundled-rust-crate-alloc-stdlib \
bundled-rust-crate-allocator-api2 \
bundled-rust-crate-alphanumeric-sort \
bundled-rust-crate-annotate-snippets \
bundled-rust-crate-ansi-str \
bundled-rust-crate-ansitok \
bundled-rust-crate-anstream \
bundled-rust-crate-anstyle \
bundled-rust-crate-anstyle-parse \
bundled-rust-crate-anstyle-query \
bundled-rust-crate-anyhow \
bundled-rust-crate-approx \
bundled-rust-crate-arboard \
bundled-rust-crate-arraydeque \
bundled-rust-crate-arrayvec \
bundled-rust-crate-async-trait \
bundled-rust-crate-atoi-simd \
bundled-rust-crate-atomic \
bundled-rust-crate-atomic-waker \
bundled-rust-crate-autocfg \
bundled-rust-crate-aws-lc-rs \
bundled-rust-crate-aws-lc-sys \
bundled-rust-crate-backtrace \
bundled-rust-crate-backtrace-ext \
bundled-rust-crate-base64 \
bundled-rust-crate-better-default \
bundled-rust-crate-bigdecimal \
bundled-rust-crate-bincode \
bundled-rust-crate-bit-set \
bundled-rust-crate-bit-vec \
bundled-rust-crate-bitflags \
bundled-rust-crate-blake3 \
bundled-rust-crate-block-buffer \
bundled-rust-crate-borsh \
bundled-rust-crate-bracoxide \
bundled-rust-crate-brotli \
bundled-rust-crate-brotli-decompressor \
bundled-rust-crate-bstr \
bundled-rust-crate-buf-trait \
bundled-rust-crate-bumpalo \
bundled-rust-crate-by-address \
bundled-rust-crate-bytecount \
bundled-rust-crate-bytemuck \
bundled-rust-crate-bytemuck-derive \
bundled-rust-crate-byteorder \
bundled-rust-crate-byteorder-lite \
bundled-rust-crate-bytes \
bundled-rust-crate-bytesize \
bundled-rust-crate-byteyarn \
bundled-rust-crate-calamine \
bundled-rust-crate-castaway \
bundled-rust-crate-cc \
bundled-rust-crate-cfg-aliases \
bundled-rust-crate-cfg-if \
bundled-rust-crate-chacha20 \
bundled-rust-crate-chardetng \
bundled-rust-crate-chrono \
bundled-rust-crate-chrono-humanize \
bundled-rust-crate-chrono-tz \
bundled-rust-crate-clap \
bundled-rust-crate-clap-builder \
bundled-rust-crate-clap-derive \
bundled-rust-crate-clap-lex \
bundled-rust-crate-cmake \
bundled-rust-crate-cmov \
bundled-rust-crate-codepage \
bundled-rust-crate-colorchoice \
bundled-rust-crate-compact-str \
bundled-rust-crate-console \
bundled-rust-crate-const-format \
bundled-rust-crate-const-format-proc-macros \
bundled-rust-crate-const-oid \
bundled-rust-crate-constant-time-eq \
bundled-rust-crate-convert-case \
bundled-rust-crate-cookie \
bundled-rust-crate-cookie-store \
bundled-rust-crate-cpufeatures \
bundled-rust-crate-crc32fast \
bundled-rust-crate-critical-section \
bundled-rust-crate-crossbeam-channel \
bundled-rust-crate-crossbeam-deque \
bundled-rust-crate-crossbeam-epoch \
bundled-rust-crate-crossbeam-queue \
bundled-rust-crate-crossbeam-utils \
bundled-rust-crate-crossterm \
bundled-rust-crate-crypto-common \
bundled-rust-crate-csv \
bundled-rust-crate-csv-core \
bundled-rust-crate-ctrlc \
bundled-rust-crate-ctutils \
bundled-rust-crate-darling \
bundled-rust-crate-darling-core \
bundled-rust-crate-darling-macro \
bundled-rust-crate-data-encoding \
bundled-rust-crate-debug-unsafe \
bundled-rust-crate-defmt \
bundled-rust-crate-defmt-macros \
bundled-rust-crate-defmt-parser \
bundled-rust-crate-deranged \
bundled-rust-crate-derive-more \
bundled-rust-crate-derive-more-impl \
bundled-rust-crate-derive-setters \
bundled-rust-crate-devicons \
bundled-rust-crate-digest \
bundled-rust-crate-dirs \
bundled-rust-crate-dirs-sys \
bundled-rust-crate-displaydoc \
bundled-rust-crate-dns-lookup \
bundled-rust-crate-doctest-file \
bundled-rust-crate-document-features \
bundled-rust-crate-downcast-rs \
bundled-rust-crate-doxygen-rs \
bundled-rust-crate-dtparse \
bundled-rust-crate-dunce \
bundled-rust-crate-dyn-clone \
bundled-rust-crate-edit \
bundled-rust-crate-edtui \
bundled-rust-crate-edtui-jagged \
bundled-rust-crate-either \
bundled-rust-crate-encoding-rs \
bundled-rust-crate-encoding-rs-io \
bundled-rust-crate-enum-dispatch \
bundled-rust-crate-equivalent \
bundled-rust-crate-erased-serde \
bundled-rust-crate-errno \
bundled-rust-crate-etcetera \
bundled-rust-crate-fallible-iterator \
bundled-rust-crate-fallible-streaming-iterator \
bundled-rust-crate-fancy-regex \
bundled-rust-crate-fast-float2 \
bundled-rust-crate-fastrand \
bundled-rust-crate-fax \
bundled-rust-crate-fd-lock \
bundled-rust-crate-fdeflate \
bundled-rust-crate-fff-grep \
bundled-rust-crate-fff-notify-debouncer-full \
bundled-rust-crate-fff-query-parser \
bundled-rust-crate-fff-search \
bundled-rust-crate-file-id \
bundled-rust-crate-filedescriptor \
bundled-rust-crate-filesize \
bundled-rust-crate-filetime \
bundled-rust-crate-find-msvc-tools \
bundled-rust-crate-fixedbitset \
bundled-rust-crate-flate2 \
bundled-rust-crate-fluent \
bundled-rust-crate-fluent-bundle \
bundled-rust-crate-fluent-langneg \
bundled-rust-crate-fluent-syntax \
bundled-rust-crate-fluent-uri \
bundled-rust-crate-fnv \
bundled-rust-crate-foldhash \
bundled-rust-crate-form-urlencoded \
bundled-rust-crate-fs-extra \
bundled-rust-crate-futures \
bundled-rust-crate-futures-channel \
bundled-rust-crate-futures-core \
bundled-rust-crate-futures-executor \
bundled-rust-crate-futures-io \
bundled-rust-crate-futures-macro \
bundled-rust-crate-futures-sink \
bundled-rust-crate-futures-task \
bundled-rust-crate-futures-util \
bundled-rust-crate-generic-array \
bundled-rust-crate-gethostname \
bundled-rust-crate-getrandom \
bundled-rust-crate-gimli \
bundled-rust-crate-git2 \
bundled-rust-crate-glidesort \
bundled-rust-crate-glob \
bundled-rust-crate-globset \
bundled-rust-crate-granit-parser \
bundled-rust-crate-h2 \
bundled-rust-crate-half \
bundled-rust-crate-hashbrown \
bundled-rust-crate-hashlink \
bundled-rust-crate-heck \
bundled-rust-crate-heed \
bundled-rust-crate-heed-traits \
bundled-rust-crate-heed-types \
bundled-rust-crate-hex \
bundled-rust-crate-home \
bundled-rust-crate-http \
bundled-rust-crate-http-body \
bundled-rust-crate-http-body-util \
bundled-rust-crate-httparse \
bundled-rust-crate-httpdate \
bundled-rust-crate-human-date-parser \
bundled-rust-crate-humantime \
bundled-rust-crate-hybrid-array \
bundled-rust-crate-hyper \
bundled-rust-crate-hyper-rustls \
bundled-rust-crate-hyper-util \
bundled-rust-crate-iana-time-zone \
bundled-rust-crate-icu-collections \
bundled-rust-crate-icu-locale-core \
bundled-rust-crate-icu-normalizer \
bundled-rust-crate-icu-normalizer-data \
bundled-rust-crate-icu-properties \
bundled-rust-crate-icu-properties-data \
bundled-rust-crate-icu-provider \
bundled-rust-crate-ident-case \
bundled-rust-crate-idna \
bundled-rust-crate-idna-adapter \
bundled-rust-crate-ignore \
bundled-rust-crate-image \
bundled-rust-crate-indexmap \
bundled-rust-crate-indicatif \
bundled-rust-crate-indoc \
bundled-rust-crate-inotify \
bundled-rust-crate-inotify-sys \
bundled-rust-crate-instability \
bundled-rust-crate-interprocess \
bundled-rust-crate-intl-memoizer \
bundled-rust-crate-intl-pluralrules \
bundled-rust-crate-inventory \
bundled-rust-crate-ipnet \
bundled-rust-crate-is-ci \
bundled-rust-crate-is-debug \
bundled-rust-crate-is-docker \
bundled-rust-crate-is-executable \
bundled-rust-crate-is-terminal-polyfill \
bundled-rust-crate-is-wsl \
bundled-rust-crate-itertools \
bundled-rust-crate-itoa \
bundled-rust-crate-jiff \
bundled-rust-crate-jiff-core \
bundled-rust-crate-jiff-static \
bundled-rust-crate-jobserver \
bundled-rust-crate-kasuari \
bundled-rust-crate-kdl \
bundled-rust-crate-konst \
bundled-rust-crate-konst-macro-rules \
bundled-rust-crate-lazy-static \
bundled-rust-crate-lean-string \
bundled-rust-crate-lexopt \
bundled-rust-crate-libc \
bundled-rust-crate-libgit2-sys \
bundled-rust-crate-libm \
bundled-rust-crate-libsqlite3-sys \
bundled-rust-crate-libz-sys \
bundled-rust-crate-line-clipping \
bundled-rust-crate-linked-hash-map \
bundled-rust-crate-linux-raw-sys \
bundled-rust-crate-litemap \
bundled-rust-crate-litrs \
bundled-rust-crate-lmdb-master-sys \
bundled-rust-crate-lock-api \
bundled-rust-crate-log \
bundled-rust-crate-lru \
bundled-rust-crate-lru-slab \
bundled-rust-crate-lscolors \
bundled-rust-crate-lsp-server \
bundled-rust-crate-lsp-textdocument \
bundled-rust-crate-lsp-types \
bundled-rust-crate-markdown \
bundled-rust-crate-matchers \
bundled-rust-crate-matrixmultiply \
bundled-rust-crate-md-5 \
bundled-rust-crate-mediatype \
bundled-rust-crate-memchr \
bundled-rust-crate-memmap2 \
bundled-rust-crate-miette \
bundled-rust-crate-miette-derive \
bundled-rust-crate-mime \
bundled-rust-crate-mime-guess \
bundled-rust-crate-minimal-lexical \
bundled-rust-crate-miniz-oxide \
bundled-rust-crate-mio \
bundled-rust-crate-moxcms \
bundled-rust-crate-mq-markdown \
bundled-rust-crate-multipart-rs \
bundled-rust-crate-ndarray \
bundled-rust-crate-neo-frizbee \
bundled-rust-crate-nix \
bundled-rust-crate-nohash-hasher \
bundled-rust-crate-nom \
bundled-rust-crate-notify \
bundled-rust-crate-notify-debouncer-full \
bundled-rust-crate-notify-types \
bundled-rust-crate-nu \
bundled-rust-crate-nu-ansi-term \
bundled-rust-crate-nu-cli \
bundled-rust-crate-nu-cmd-base \
bundled-rust-crate-nu-cmd-extra \
bundled-rust-crate-nu-cmd-lang \
bundled-rust-crate-nu-cmd-plugin \
bundled-rust-crate-nu-color-config \
bundled-rust-crate-nu-command \
bundled-rust-crate-nu-config \
bundled-rust-crate-nu-derive-value \
bundled-rust-crate-nu-engine \
bundled-rust-crate-nu-experimental \
bundled-rust-crate-nu-explore \
bundled-rust-crate-nu-glob \
bundled-rust-crate-nu-heavy-utils \
bundled-rust-crate-nu-json \
bundled-rust-crate-nu-lsp \
bundled-rust-crate-nu-mcp \
bundled-rust-crate-nu-parser \
bundled-rust-crate-nu-path \
bundled-rust-crate-nu-plugin-core \
bundled-rust-crate-nu-plugin-engine \
bundled-rust-crate-nu-plugin-protocol \
bundled-rust-crate-nu-pretty-hex \
bundled-rust-crate-nu-protocol \
bundled-rust-crate-nu-std \
bundled-rust-crate-nu-system \
bundled-rust-crate-nu-table \
bundled-rust-crate-nu-term-grid \
bundled-rust-crate-nu-utils \
bundled-rust-crate-nucleo-matcher \
bundled-rust-crate-num-bigint \
bundled-rust-crate-num-complex \
bundled-rust-crate-num-conv \
bundled-rust-crate-num-cpus \
bundled-rust-crate-num-format \
bundled-rust-crate-num-integer \
bundled-rust-crate-num-threads \
bundled-rust-crate-num-traits \
bundled-rust-crate-nuon \
bundled-rust-crate-object \
bundled-rust-crate-oem-cp \
bundled-rust-crate-once-cell \
bundled-rust-crate-open \
bundled-rust-crate-openssl-probe \
bundled-rust-crate-option-ext \
bundled-rust-crate-os-display \
bundled-rust-crate-os-pipe \
bundled-rust-crate-owo-colors \
bundled-rust-crate-page-size \
bundled-rust-crate-palette \
bundled-rust-crate-palette-derive \
bundled-rust-crate-palette-math \
bundled-rust-crate-papergrid \
bundled-rust-crate-parking-lot \
bundled-rust-crate-parking-lot-core \
bundled-rust-crate-parse-datetime \
bundled-rust-crate-pastey \
bundled-rust-crate-pathdiff \
bundled-rust-crate-percent-encoding \
bundled-rust-crate-pest \
bundled-rust-crate-pest-consume \
bundled-rust-crate-pest-consume-macros \
bundled-rust-crate-pest-derive \
bundled-rust-crate-pest-generator \
bundled-rust-crate-pest-meta \
bundled-rust-crate-petgraph \
bundled-rust-crate-phf \
bundled-rust-crate-phf-generator \
bundled-rust-crate-phf-macros \
bundled-rust-crate-phf-shared \
bundled-rust-crate-pin-project-lite \
bundled-rust-crate-pkg-config \
bundled-rust-crate-platform-info \
bundled-rust-crate-png \
bundled-rust-crate-pori \
bundled-rust-crate-portable-atomic \
bundled-rust-crate-potential-utf \
bundled-rust-crate-powerfmt \
bundled-rust-crate-ppv-lite86 \
bundled-rust-crate-print-positions \
bundled-rust-crate-proc-macro-error-attr2 \
bundled-rust-crate-proc-macro-error2 \
bundled-rust-crate-proc-macro2 \
bundled-rust-crate-procfs \
bundled-rust-crate-procfs-core \
bundled-rust-crate-pure-rust-locales \
bundled-rust-crate-pwd \
bundled-rust-crate-pxfm \
bundled-rust-crate-quick-error \
bundled-rust-crate-quick-xml \
bundled-rust-crate-quinn \
bundled-rust-crate-quinn-proto \
bundled-rust-crate-quinn-udp \
bundled-rust-crate-quote \
bundled-rust-crate-rand \
bundled-rust-crate-rand-chacha \
bundled-rust-crate-rand-core \
bundled-rust-crate-rand-pcg \
bundled-rust-crate-ratatui \
bundled-rust-crate-ratatui-core \
bundled-rust-crate-ratatui-crossterm \
bundled-rust-crate-ratatui-macros \
bundled-rust-crate-ratatui-widgets \
bundled-rust-crate-rawpointer \
bundled-rust-crate-rayon \
bundled-rust-crate-rayon-core \
bundled-rust-crate-reedline \
bundled-rust-crate-ref-cast \
bundled-rust-crate-ref-cast-impl \
bundled-rust-crate-regex \
bundled-rust-crate-regex-automata \
bundled-rust-crate-regex-syntax \
bundled-rust-crate-reqwest \
bundled-rust-crate-ring \
bundled-rust-crate-rmcp \
bundled-rust-crate-rmcp-macros \
bundled-rust-crate-rmp \
bundled-rust-crate-rmp-serde \
bundled-rust-crate-roxmltree \
bundled-rust-crate-rusqlite \
bundled-rust-crate-rust-decimal \
bundled-rust-crate-rustc-demangle \
bundled-rust-crate-rustc-hash \
bundled-rust-crate-rustc-version \
bundled-rust-crate-rustix \
bundled-rust-crate-rustls \
bundled-rust-crate-rustls-native-certs \
bundled-rust-crate-rustls-pki-types \
bundled-rust-crate-rustls-platform-verifier \
bundled-rust-crate-rustls-webpki \
bundled-rust-crate-rustversion \
bundled-rust-crate-ryu \
bundled-rust-crate-same-file \
bundled-rust-crate-schemars \
bundled-rust-crate-schemars-derive \
bundled-rust-crate-scopeguard \
bundled-rust-crate-self-cell \
bundled-rust-crate-semver \
bundled-rust-crate-serde \
bundled-rust-crate-serde-core \
bundled-rust-crate-serde-derive \
bundled-rust-crate-serde-derive-internals \
bundled-rust-crate-serde-json \
bundled-rust-crate-serde-repr \
bundled-rust-crate-serde-saphyr \
bundled-rust-crate-serde-spanned \
bundled-rust-crate-serde-urlencoded \
bundled-rust-crate-sha1-smol \
bundled-rust-crate-sha2 \
bundled-rust-crate-shadow-rs \
bundled-rust-crate-sharded-slab \
bundled-rust-crate-shlex \
bundled-rust-crate-signal-hook \
bundled-rust-crate-signal-hook-mio \
bundled-rust-crate-signal-hook-registry \
bundled-rust-crate-simd-adler32 \
bundled-rust-crate-simplelog \
bundled-rust-crate-siphasher \
bundled-rust-crate-slab \
bundled-rust-crate-smallvec \
bundled-rust-crate-smol-str \
bundled-rust-crate-socket2 \
bundled-rust-crate-socks \
bundled-rust-crate-sse-stream \
bundled-rust-crate-stable-deref-trait \
bundled-rust-crate-static-assertions \
bundled-rust-crate-strip-ansi-escapes \
bundled-rust-crate-strsim \
bundled-rust-crate-strum \
bundled-rust-crate-strum-macros \
bundled-rust-crate-subtle \
bundled-rust-crate-supports-color \
bundled-rust-crate-supports-hyperlinks \
bundled-rust-crate-supports-unicode \
bundled-rust-crate-symlink \
bundled-rust-crate-syn \
bundled-rust-crate-sync-wrapper \
bundled-rust-crate-synchronoise \
bundled-rust-crate-synstructure \
bundled-rust-crate-sys-locale \
bundled-rust-crate-sysinfo \
bundled-rust-crate-tabled \
bundled-rust-crate-tempfile \
bundled-rust-crate-termcolor \
bundled-rust-crate-terminal-size \
bundled-rust-crate-testing-table \
bundled-rust-crate-textwrap \
bundled-rust-crate-thiserror \
bundled-rust-crate-thiserror-impl \
bundled-rust-crate-thread-local \
bundled-rust-crate-thread-tree \
bundled-rust-crate-tiff \
bundled-rust-crate-time \
bundled-rust-crate-time-core \
bundled-rust-crate-time-macros \
bundled-rust-crate-tinystr \
bundled-rust-crate-tinyvec \
bundled-rust-crate-tinyvec-macros \
bundled-rust-crate-titlecase \
bundled-rust-crate-tokio \
bundled-rust-crate-tokio-macros \
bundled-rust-crate-tokio-rustls \
bundled-rust-crate-tokio-stream \
bundled-rust-crate-tokio-util \
bundled-rust-crate-toml \
bundled-rust-crate-toml-datetime \
bundled-rust-crate-toml-edit \
bundled-rust-crate-toml-parser \
bundled-rust-crate-toml-writer \
bundled-rust-crate-tower \
bundled-rust-crate-tower-http \
bundled-rust-crate-tower-layer \
bundled-rust-crate-tower-service \
bundled-rust-crate-tracing \
bundled-rust-crate-tracing-appender \
bundled-rust-crate-tracing-attributes \
bundled-rust-crate-tracing-core \
bundled-rust-crate-tracing-log \
bundled-rust-crate-tracing-subscriber \
bundled-rust-crate-trash \
bundled-rust-crate-tree-magic-mini \
bundled-rust-crate-try-lock \
bundled-rust-crate-tui-tree-widget \
bundled-rust-crate-type-map \
bundled-rust-crate-typed-path \
bundled-rust-crate-typeid \
bundled-rust-crate-typenum \
bundled-rust-crate-typetag \
bundled-rust-crate-typetag-impl \
bundled-rust-crate-ucd-trie \
bundled-rust-crate-umask \
bundled-rust-crate-unic-langid \
bundled-rust-crate-unic-langid-impl \
bundled-rust-crate-unicase \
bundled-rust-crate-unicode-id \
bundled-rust-crate-unicode-ident \
bundled-rust-crate-unicode-linebreak \
bundled-rust-crate-unicode-segmentation \
bundled-rust-crate-unicode-truncate \
bundled-rust-crate-unicode-width \
bundled-rust-crate-unicode-xid \
bundled-rust-crate-unit-prefix \
bundled-rust-crate-untrusted \
bundled-rust-crate-update-informer \
bundled-rust-crate-ureq \
bundled-rust-crate-ureq-proto \
bundled-rust-crate-url \
bundled-rust-crate-urlencoding \
bundled-rust-crate-utf8-iter \
bundled-rust-crate-utf8-zero \
bundled-rust-crate-utf8parse \
bundled-rust-crate-uu-cp \
bundled-rust-crate-uu-mkdir \
bundled-rust-crate-uu-mktemp \
bundled-rust-crate-uu-mv \
bundled-rust-crate-uu-touch \
bundled-rust-crate-uu-uname \
bundled-rust-crate-uu-whoami \
bundled-rust-crate-uucore \
bundled-rust-crate-uucore-procs \
bundled-rust-crate-uuid \
bundled-rust-crate-v-escape-base \
bundled-rust-crate-v-htmlescape \
bundled-rust-crate-vcpkg \
bundled-rust-crate-version-check \
bundled-rust-crate-vte \
bundled-rust-crate-walkdir \
bundled-rust-crate-want \
bundled-rust-crate-wax \
bundled-rust-crate-wayland-backend \
bundled-rust-crate-wayland-client \
bundled-rust-crate-wayland-protocols \
bundled-rust-crate-wayland-protocols-wlr \
bundled-rust-crate-wayland-scanner \
bundled-rust-crate-wayland-sys \
bundled-rust-crate-web-time \
bundled-rust-crate-webpki-roots \
bundled-rust-crate-weezl \
bundled-rust-crate-which \
bundled-rust-crate-winnow \
bundled-rust-crate-winresource \
bundled-rust-crate-wl-clipboard-rs \
bundled-rust-crate-writeable \
bundled-rust-crate-x11rb \
bundled-rust-crate-x11rb-protocol \
bundled-rust-crate-xattr \
bundled-rust-crate-xxhash-rust \
bundled-rust-crate-yoke \
bundled-rust-crate-yoke-derive \
bundled-rust-crate-zerocopy \
bundled-rust-crate-zerocopy-derive \
bundled-rust-crate-zerofrom \
bundled-rust-crate-zerofrom-derive \
bundled-rust-crate-zeroize \
bundled-rust-crate-zerotrie \
bundled-rust-crate-zerovec \
bundled-rust-crate-zerovec-derive \
bundled-rust-crate-zip \
bundled-rust-crate-zlib-rs \
bundled-rust-crate-zmij \
bundled-rust-crate-zopfli \
bundled-rust-crate-zune-core \
bundled-rust-crate-zune-jpeg \
nushell"

RDEPENDS:${PN} += "libc.so.6 \
libgcc-s.so.1 \
libm.so.6 \
libz.so.1"

inherit rpm
