SUMMARY = "Visualizer for output generated by Valgrind's massif tool"
DESCRIPTION = "Massif Visualizer is a tool that visualizes massif data. \
You run your application in Valgrind with --tool=massif and then open the \
generated massif.out.pid file in the visualizer. \
Gzip or Bzip2 compressed massif files can also be opened transparently."
LICENSE = "LGPL-2.0-only"

PV = "26.08.1"

RPM_NAME = "massif-visualizer-26.08.1-1.1.aarch64.rpm"
RPM_HASH = "4d875d7b0d92e6b5f6774c434b818bd10c2eeabe8edc9d73f5e1e0719798dc4f54903be3de3a8090bb4c1d5b7f71c62646f639c9b61d5873338bfac8e6ce2eac"

RPROVIDES:${PN} += "massif-visualizer"

RDEPENDS:${PN} += "kgraphviewer \
ld-linux-aarch64.so.1 \
libKChart6.so.3 \
libKF6Archive.so.6 \
libKF6ColorScheme.so.6 \
libKF6Completion.so.6 \
libKF6ConfigCore.so.6 \
libKF6ConfigGui.so.6 \
libKF6ConfigWidgets.so.6 \
libKF6CoreAddons.so.6 \
libKF6I18n.so.6 \
libKF6KIOCore.so.6 \
libKF6Parts.so.6 \
libKF6WidgetsAddons.so.6 \
libKF6XmlGui.so.6 \
libQt6Core.so.6 \
libQt6Core5Compat.so.6 \
libQt6Gui.so.6 \
libQt6PrintSupport.so.6 \
libQt6Svg.so.6 \
libQt6Widgets.so.6 \
libc.so.6 \
libstdc++.so.6"

inherit rpm
