SUMMARY = "openSUSE Aeon"
DESCRIPTION = "This is the openSUSE Aeon base system. It contains only fully working immutable desktop system."
LICENSE = "MIT"

PV = "5.0"

RPM_NAME = "patterns-aeon-base-5.0-26.2.aarch64.rpm"
RPM_HASH = "977d76a88a7874e222902d37358906cc668da06aefdf56054b1df81532bd098114ee51dcd4d6a86184223da7957b53736482763a043c0e3985f3dc16d5fc00ae"

RPROVIDES:${PN} += "pattern- \
pattern-category- \
pattern-icon- \
pattern-order- \
patterns-aeon-base"

RDEPENDS:${PN} += "/usr/bin/gzip \
/usr/bin/hostname \
Aeon-release \
NetworkManager \
NetworkManager-bluetooth \
NetworkManager-openconnect-gnome \
NetworkManager-openvpn-gnome \
NetworkManager-wifi \
OpenPrintingPPDs \
aaa-base \
adobe-sourcecodepro-fonts \
adobe-sourcesanspro-fonts \
adobe-sourceserifpro-fonts \
adwaita-fonts \
adwaita-icon-theme \
aeon-check \
alsa-ucm-conf \
at-spi2-core \
audit \
avahi \
bash \
bash-completion \
bluez-auto-enable-devices \
bluez-cups \
bluez-firmware \
bluez-obexd \
bolt \
branding \
branding-openSUSE \
brltty-driver-speech-dispatcher \
btrfsmaintenance \
btrfsprogs \
build-key \
busybox \
ca-certificates \
ca-certificates-mozilla \
canberra-gtk-play \
chrome-gnome-shell \
chrony \
cifs-utils \
combustion \
container-selinux \
coreutils \
coreutils-systemd \
cups \
cups-filters \
cups-pk-helper \
curl \
dejavu-fonts \
desktop-file-utils \
distribution-logos-openSUSE-Aeon \
distribution-release \
distrobox \
dosfstools \
dracut-pcr-signature \
efibootmgr \
epson-inkjet-printer-escpr \
ethtool \
exfatprogs \
fcoe-utils \
filesystem \
flatpak \
fprintd \
fprintd-pam \
gcr-ssh-agent \
gcr-ssh-askpass \
gcr3-ssh-askpass \
gdm-branding-Aeon \
ghostscript \
ghostscript-fonts-other \
ghostscript-fonts-std \
gjs \
glibc \
glibc-locale \
glibc-locale-base \
glycin-loaders \
gnome-backgrounds \
gnome-bluetooth \
gnome-branding-Aeon \
gnome-color-manager \
gnome-console \
gnome-control-center-color \
gnome-control-center-goa \
gnome-control-center-user-faces \
gnome-control-center-users \
gnome-disk-utility \
gnome-initial-setup \
gnome-keyring-pam \
gnome-menus-branding-openSUSE \
gnome-online-accounts \
gnome-remote-desktop \
gnome-session-default-session \
gnome-session-wayland \
gnome-shell-calendar \
gnome-shell-search-provider-nautilus \
gnome-software \
gnome-system-monitor \
gnome-user-docs \
google-carlito-fonts \
google-droid-fonts \
google-opensans-fonts \
google-roboto-fonts \
gpgme \
group-nobody \
gsettings-backend-dconf \
gsf-office-thumbnailer \
gstreamer-plugin-pipewire \
gstreamer-plugins-bad \
gstreamer-plugins-good \
gtk2-branding-openSUSE \
gtk3-branding-openSUSE \
gtk4-branding-openSUSE \
gvfs-backend-afc \
gvfs-backend-goa \
gvfs-backend-samba \
gvfs-backends \
gvfs-fuse \
gzip \
health-checker \
health-checker-plugins-MicroOS \
hicolor-icon-theme-branding-openSUSE \
hostname \
hplip-hpijs \
hwinfo \
ignition-dracut \
iio-sensor-proxy \
iproute2 \
iputils \
irqbalance \
jxl-thumbnailer \
kdump \
kernel-default \
kernel-firmware-all \
lastlog2 \
less \
libgnomesu \
libinput-udev \
libmbim \
libnss-usrfiles2 \
libvulkan-intel \
libvulkan-radeon \
malcontent-control \
microos-tools \
mokutil \
nautilus \
nautilus-extension-seahorse \
nautilus-share \
noto-coloremoji-fonts \
noto-emoji-fonts \
noto-sans-fonts \
ntfs-3g \
ntfsprogs \
openSUSE-build-key \
openssh \
openssh-askpass-gnome \
orca \
pam \
pam-config \
pinentry-gnome3 \
pipewire-alsa \
pipewire-pulseaudio \
podman \
policycoreutils \
policycoreutils-python-utils \
polkit-default-privs \
polkit-gnome \
power-profiles-daemon \
printer-driver-brlaser \
procps \
python3-nautilus \
qemu-guest-agent \
rpm \
rsvg-thumbnailer \
samba \
sane-backends \
sdbootutil-rpm-scriptlets \
sdbootutil-snapper \
seahorse-daemon \
selinux-policy-targeted \
selinux-tools \
shadow \
shim \
snapper \
sof-firmware \
speech-dispatcher-module-espeak \
spice-vdagent \
steam-devices \
sudo \
switcheroo-control \
system-config-printer-common \
system-config-printer-dbus-service \
system-group-wheel \
systemd \
systemd-boot \
systemd-coredump \
systemd-experimental \
systemd-icon-branding-openSUSE \
systemd-presets-branding-Aeon \
systemd-repart-branding-Aeon \
systemd-zram-service \
terminfo-base \
timezone \
tpm2-0-tss \
tpm2.0-tools \
transactional-update \
transactional-update-notifier \
transactional-update-zypp-config \
udev-configure-printer \
udisks2 \
uefi-mbr \
unzip \
upower \
user-nobody \
util-linux \
vim-small \
wget \
wtmpdb \
x86-64-v3-branding-Aeon \
xdg-desktop-portal-gnome \
xdg-desktop-portal-gtk \
xdg-user-dirs-gtk \
xdg-utils \
xf86-input-libinput \
xorg-x11-fonts-core \
xorg-x11-server \
yast2-logs \
yelp \
zypp-excludedocs \
zypp-no-multiversion \
zypp-no-recommends \
zypper \
zypper-needs-restarting"

inherit rpm
