SUMMARY = "A sophisticated typesetting engine"
DESCRIPTION = "TeX is a typesetting system that incorporates a macro \
processor. A TeX source document specifies or incorporates a \
number of macro definitions that instruct the TeX engine how to \
typeset the document. The TeX engine also uses font metrics \
generated by Metafont, or by any of several other mechanisms \
that incorporate fonts from other sources into an environment \
suitable for TeX. TeX has been, and continues, a basis and an \
inspiration for several other programs, including e-TeX and \
PDFTeX. The distribution includes the source of Knuth's TeX \
book; this source is there to read, as an example of writing \
TeX -- it should not be processed without Knuth's direct \
permission."
LICENSE = "SUSE-TeX"

PV = "2026.227.3.141592653svn77830"

RPM_NAME = "texlive-tex-2026.227.3.141592653svn77830-62.2.noarch.rpm"
RPM_HASH = "3ee0620d2df31c282c7f9fae4bca0f407d8775fa2e48eafd6551eaac821fb3d8abf3ca735558ccca7df2c720f3471f6c7dea76f4d6d6390dba304d45a0803884"
REPO_ARCH = "noarch"

RPROVIDES:${PN} += "man-initex.1 \
man-tex.1 \
texlive-tex"

RDEPENDS:${PN} += "/usr/bin/sh \
coreutils \
ed \
findutils \
grep \
sed \
tex-language.dat \
tex-language.dat.lua \
tex-language.def \
tex-null.tex \
texlive \
texlive-amsfonts \
texlive-cm \
texlive-cm-super \
texlive-ec \
texlive-epsf \
texlive-filesystem \
texlive-hyph-utf8 \
texlive-hyphen-base \
texlive-knuth-lib \
texlive-kpathsea \
texlive-kpathsea-bin \
texlive-manfnt \
texlive-plain \
texlive-scripts \
texlive-scripts-bin \
texlive-tex-bin"

inherit rpm
