SUMMARY = "Various libraries"
DESCRIPTION = "This package provides various libraries: \
chrome-trace \
dune-action-plugin \
dune-build-info \
dune-configurator \
dune-glob \
dune-private-libs \
dune-rpc \
dune-site \
dyn \
ocamlc-loc \
ordering \
stdune \
xdg"
LICENSE = "MIT"

PV = "3.24.2"

RPM_NAME = "ocaml-dune-devel-3.24.2-1.1.aarch64.rpm"
RPM_HASH = "965791291ba30ed598a4b94adc61352207066d1a9c0b5f5df7354be1bed8d67291112888a2ccd8baac854fb946f8e45accf8bc03f3568c04eee6cfa8d7cc4be5"

RPROVIDES:${PN} += "config-ocaml-dune-devel \
ocaml-Build-info \
ocaml-Build-info-- \
ocaml-Build-info--Build-info-data \
ocaml-Chrome-trace \
ocaml-Configurator \
ocaml-Configurator-- \
ocaml-Configurator--Dune-lang \
ocaml-Configurator--Extract-obj \
ocaml-Configurator--Import \
ocaml-Configurator--Ocaml-config \
ocaml-Configurator--V1 \
ocaml-Dune-action-plugin \
ocaml-Dune-action-plugin-- \
ocaml-Dune-action-plugin--Import \
ocaml-Dune-action-plugin--Path \
ocaml-Dune-action-plugin--Protocol \
ocaml-Dune-action-plugin--Sexpable-intf \
ocaml-Dune-glob \
ocaml-Dune-glob-- \
ocaml-Dune-glob--Glob \
ocaml-Dune-glob--Lexer \
ocaml-Dune-meta-parser \
ocaml-Dune-meta-parser-- \
ocaml-Dune-meta-parser--Meta-lexer \
ocaml-Dune-meta-parser--Meta-parser \
ocaml-Dune-rpc \
ocaml-Dune-rpc-- \
ocaml-Dune-rpc--Client \
ocaml-Dune-rpc--Conv \
ocaml-Dune-rpc--Dbus-address \
ocaml-Dune-rpc--Diagnostics-v1 \
ocaml-Dune-rpc--Exported-types \
ocaml-Dune-rpc--Fiber-intf \
ocaml-Dune-rpc--Import \
ocaml-Dune-rpc--Menu \
ocaml-Dune-rpc--Private \
ocaml-Dune-rpc--Procedures \
ocaml-Dune-rpc--Public \
ocaml-Dune-rpc--Registry \
ocaml-Dune-rpc--Server-notifications \
ocaml-Dune-rpc--Sub \
ocaml-Dune-rpc--Types \
ocaml-Dune-rpc--V1 \
ocaml-Dune-rpc--Version-error \
ocaml-Dune-rpc--Versioned \
ocaml-Dune-rpc--Versioned-intf \
ocaml-Dune-rpc--Where \
ocaml-Dune-section \
ocaml-Dune-site \
ocaml-Dune-site-- \
ocaml-Dune-site--Dune-site-data \
ocaml-Dune-site--Helpers \
ocaml-Dune-site-backend \
ocaml-Dune-site-backend--Linker \
ocaml-Dune-site-backend--dune-site-dynlink-linker-- \
ocaml-Dune-site-backend--dune-site-toplevel-linker-- \
ocaml-Dune-site-plugins \
ocaml-Dune-site-plugins-- \
ocaml-Dune-site-plugins--Dune-site-plugins-data \
ocaml-Dune-site-plugins--Meta-parser \
ocaml-Dune-site-plugins--Plugins \
ocaml-Dune-site-private \
ocaml-Dyn \
ocaml-Fs-io \
ocaml-Ocamlc-loc \
ocaml-Ocamlc-loc-- \
ocaml-Ocamlc-loc--Lexer \
ocaml-Ordering \
ocaml-Stdune \
ocaml-Stdune-- \
ocaml-Stdune--Alias-name \
ocaml-Stdune--Ansi-color \
ocaml-Stdune--Appendable-list \
ocaml-Stdune--Applicative \
ocaml-Stdune--Applicative-intf \
ocaml-Stdune--Array \
ocaml-Stdune--Array-intf \
ocaml-Stdune--At-exit \
ocaml-Stdune--Backend-intf \
ocaml-Stdune--Bin \
ocaml-Stdune--Bit-set \
ocaml-Stdune--Bool \
ocaml-Stdune--Bytes \
ocaml-Stdune--Bytes-unit \
ocaml-Stdune--Caller-id \
ocaml-Stdune--Char \
ocaml-Stdune--Code-error \
ocaml-Stdune--Combinators \
ocaml-Stdune--Compact-position \
ocaml-Stdune--Comparable \
ocaml-Stdune--Comparable-intf \
ocaml-Stdune--Comparator \
ocaml-Stdune--Config \
ocaml-Stdune--Console \
ocaml-Stdune--Counter \
ocaml-Stdune--Debug \
ocaml-Stdune--Dev-null \
ocaml-Stdune--Dumb \
ocaml-Stdune--Either \
ocaml-Stdune--Env \
ocaml-Stdune--Env-path \
ocaml-Stdune--Escape \
ocaml-Stdune--Execution-env \
ocaml-Stdune--Exn \
ocaml-Stdune--Exn-with-backtrace \
ocaml-Stdune--Fd \
ocaml-Stdune--Fdecl \
ocaml-Stdune--File-kind \
ocaml-Stdune--Filename \
ocaml-Stdune--Filename-set \
ocaml-Stdune--Float \
ocaml-Stdune--Flock \
ocaml-Stdune--Format \
ocaml-Stdune--Fpath \
ocaml-Stdune--Global-lock \
ocaml-Stdune--Hashable \
ocaml-Stdune--Hashtbl \
ocaml-Stdune--Hashtbl-intf \
ocaml-Stdune--Id \
ocaml-Stdune--Int \
ocaml-Stdune--Io \
ocaml-Stdune--Io-intf \
ocaml-Stdune--Json \
ocaml-Stdune--Lazy \
ocaml-Stdune--Lexbuf \
ocaml-Stdune--List \
ocaml-Stdune--Loc \
ocaml-Stdune--Loc0 \
ocaml-Stdune--Log \
ocaml-Stdune--Map \
ocaml-Stdune--Map-intf \
ocaml-Stdune--Marshal \
ocaml-Stdune--Metrics \
ocaml-Stdune--Monad \
ocaml-Stdune--Monad-intf \
ocaml-Stdune--Monoid \
ocaml-Stdune--Monoid-intf \
ocaml-Stdune--Mutex0 \
ocaml-Stdune--Nonempty-list \
ocaml-Stdune--Nothing \
ocaml-Stdune--Option \
ocaml-Stdune--Or-exn \
ocaml-Stdune--Path \
ocaml-Stdune--Path-external \
ocaml-Stdune--Path-intf \
ocaml-Stdune--Path0 \
ocaml-Stdune--Per-item \
ocaml-Stdune--Per-item-intf \
ocaml-Stdune--Permissions \
ocaml-Stdune--Pid \
ocaml-Stdune--Platform \
ocaml-Stdune--Poly \
ocaml-Stdune--Pp \
ocaml-Stdune--Predicate \
ocaml-Stdune--Proc \
ocaml-Stdune--Progress \
ocaml-Stdune--Queue \
ocaml-Stdune--Readdir \
ocaml-Stdune--Repr \
ocaml-Stdune--Result \
ocaml-Stdune--Root \
ocaml-Stdune--Scanf \
ocaml-Stdune--Seq \
ocaml-Stdune--Set \
ocaml-Stdune--Set-intf \
ocaml-Stdune--Sexp \
ocaml-Stdune--Signal \
ocaml-Stdune--Staged \
ocaml-Stdune--Stat \
ocaml-Stdune--State \
ocaml-Stdune--String \
ocaml-Stdune--String-builder \
ocaml-Stdune--String-split \
ocaml-Stdune--Sys \
ocaml-Stdune--Table \
ocaml-Stdune--Temp \
ocaml-Stdune--Terminal-persistence \
ocaml-Stdune--Terminal-signals \
ocaml-Stdune--Time \
ocaml-Stdune--Tuple \
ocaml-Stdune--Type-eq \
ocaml-Stdune--Unit \
ocaml-Stdune--Univ-map \
ocaml-Stdune--Univ-map-intf \
ocaml-Stdune--Unix-error \
ocaml-Stdune--User-error \
ocaml-Stdune--User-message \
ocaml-Stdune--User-warning \
ocaml-Top-closure \
ocaml-Top-closure-- \
ocaml-Top-closure--S \
ocaml-Xdg \
ocaml-dune-configurator \
ocaml-dune-configurator-devel \
ocaml-dune-devel \
ocamlfind-chrome-trace \
ocamlfind-dune-action-plugin \
ocamlfind-dune-build-info \
ocamlfind-dune-configurator \
ocamlfind-dune-glob \
ocamlfind-dune-private-libs \
ocamlfind-dune-private-libs.dune-section \
ocamlfind-dune-private-libs.meta-parser \
ocamlfind-dune-rpc \
ocamlfind-dune-site \
ocamlfind-dune-site.dynlink \
ocamlfind-dune-site.linker \
ocamlfind-dune-site.plugins \
ocamlfind-dune-site.private \
ocamlfind-dune-site.toplevel \
ocamlfind-dyn \
ocamlfind-fs-io \
ocamlfind-ocamlc-loc \
ocamlfind-ordering \
ocamlfind-stdune \
ocamlfind-top-closure \
ocamlfind-xdg \
ocamlx-Build-info \
ocamlx-Build-info-- \
ocamlx-Chrome-trace \
ocamlx-Configurator \
ocamlx-Configurator-- \
ocamlx-Configurator--Dune-lang \
ocamlx-Configurator--Extract-obj \
ocamlx-Configurator--Import \
ocamlx-Configurator--Ocaml-config \
ocamlx-Configurator--V1 \
ocamlx-Dune-action-plugin \
ocamlx-Dune-action-plugin-- \
ocamlx-Dune-action-plugin--Import \
ocamlx-Dune-action-plugin--Path \
ocamlx-Dune-action-plugin--Protocol \
ocamlx-Dune-action-plugin--Sexpable-intf \
ocamlx-Dune-glob \
ocamlx-Dune-glob-- \
ocamlx-Dune-glob--Glob \
ocamlx-Dune-glob--Lexer \
ocamlx-Dune-meta-parser \
ocamlx-Dune-meta-parser-- \
ocamlx-Dune-meta-parser--Meta-lexer \
ocamlx-Dune-meta-parser--Meta-parser \
ocamlx-Dune-rpc \
ocamlx-Dune-rpc-- \
ocamlx-Dune-rpc--Client \
ocamlx-Dune-rpc--Conv \
ocamlx-Dune-rpc--Dbus-address \
ocamlx-Dune-rpc--Diagnostics-v1 \
ocamlx-Dune-rpc--Exported-types \
ocamlx-Dune-rpc--Fiber-intf \
ocamlx-Dune-rpc--Import \
ocamlx-Dune-rpc--Menu \
ocamlx-Dune-rpc--Private \
ocamlx-Dune-rpc--Procedures \
ocamlx-Dune-rpc--Public \
ocamlx-Dune-rpc--Registry \
ocamlx-Dune-rpc--Server-notifications \
ocamlx-Dune-rpc--Sub \
ocamlx-Dune-rpc--Types \
ocamlx-Dune-rpc--V1 \
ocamlx-Dune-rpc--Version-error \
ocamlx-Dune-rpc--Versioned \
ocamlx-Dune-rpc--Versioned-intf \
ocamlx-Dune-rpc--Where \
ocamlx-Dune-section \
ocamlx-Dune-site \
ocamlx-Dune-site-- \
ocamlx-Dune-site--Helpers \
ocamlx-Dune-site-backend \
ocamlx-Dune-site-backend--Linker \
ocamlx-Dune-site-backend--dune-site-dynlink-linker-- \
ocamlx-Dune-site-plugins \
ocamlx-Dune-site-plugins-- \
ocamlx-Dune-site-plugins--Meta-parser \
ocamlx-Dune-site-plugins--Plugins \
ocamlx-Dune-site-private \
ocamlx-Dyn \
ocamlx-Fs-io \
ocamlx-Ocamlc-loc \
ocamlx-Ocamlc-loc-- \
ocamlx-Ocamlc-loc--Lexer \
ocamlx-Ordering \
ocamlx-Stdune \
ocamlx-Stdune-- \
ocamlx-Stdune--Alias-name \
ocamlx-Stdune--Ansi-color \
ocamlx-Stdune--Appendable-list \
ocamlx-Stdune--Applicative \
ocamlx-Stdune--Applicative-intf \
ocamlx-Stdune--Array \
ocamlx-Stdune--Array-intf \
ocamlx-Stdune--At-exit \
ocamlx-Stdune--Backend-intf \
ocamlx-Stdune--Bin \
ocamlx-Stdune--Bit-set \
ocamlx-Stdune--Bool \
ocamlx-Stdune--Bytes \
ocamlx-Stdune--Bytes-unit \
ocamlx-Stdune--Caller-id \
ocamlx-Stdune--Char \
ocamlx-Stdune--Code-error \
ocamlx-Stdune--Combinators \
ocamlx-Stdune--Compact-position \
ocamlx-Stdune--Comparable \
ocamlx-Stdune--Comparable-intf \
ocamlx-Stdune--Comparator \
ocamlx-Stdune--Config \
ocamlx-Stdune--Console \
ocamlx-Stdune--Counter \
ocamlx-Stdune--Debug \
ocamlx-Stdune--Dev-null \
ocamlx-Stdune--Dumb \
ocamlx-Stdune--Either \
ocamlx-Stdune--Env \
ocamlx-Stdune--Env-path \
ocamlx-Stdune--Escape \
ocamlx-Stdune--Execution-env \
ocamlx-Stdune--Exn \
ocamlx-Stdune--Exn-with-backtrace \
ocamlx-Stdune--Fd \
ocamlx-Stdune--Fdecl \
ocamlx-Stdune--File-kind \
ocamlx-Stdune--Filename \
ocamlx-Stdune--Filename-set \
ocamlx-Stdune--Float \
ocamlx-Stdune--Flock \
ocamlx-Stdune--Format \
ocamlx-Stdune--Fpath \
ocamlx-Stdune--Global-lock \
ocamlx-Stdune--Hashable \
ocamlx-Stdune--Hashtbl \
ocamlx-Stdune--Hashtbl-intf \
ocamlx-Stdune--Id \
ocamlx-Stdune--Int \
ocamlx-Stdune--Io \
ocamlx-Stdune--Io-intf \
ocamlx-Stdune--Json \
ocamlx-Stdune--Lazy \
ocamlx-Stdune--Lexbuf \
ocamlx-Stdune--List \
ocamlx-Stdune--Loc \
ocamlx-Stdune--Loc0 \
ocamlx-Stdune--Log \
ocamlx-Stdune--Map \
ocamlx-Stdune--Map-intf \
ocamlx-Stdune--Marshal \
ocamlx-Stdune--Metrics \
ocamlx-Stdune--Monad \
ocamlx-Stdune--Monad-intf \
ocamlx-Stdune--Monoid \
ocamlx-Stdune--Monoid-intf \
ocamlx-Stdune--Mutex0 \
ocamlx-Stdune--Nonempty-list \
ocamlx-Stdune--Nothing \
ocamlx-Stdune--Option \
ocamlx-Stdune--Or-exn \
ocamlx-Stdune--Path \
ocamlx-Stdune--Path-external \
ocamlx-Stdune--Path-intf \
ocamlx-Stdune--Path0 \
ocamlx-Stdune--Per-item \
ocamlx-Stdune--Per-item-intf \
ocamlx-Stdune--Permissions \
ocamlx-Stdune--Pid \
ocamlx-Stdune--Platform \
ocamlx-Stdune--Poly \
ocamlx-Stdune--Pp \
ocamlx-Stdune--Predicate \
ocamlx-Stdune--Proc \
ocamlx-Stdune--Progress \
ocamlx-Stdune--Queue \
ocamlx-Stdune--Readdir \
ocamlx-Stdune--Repr \
ocamlx-Stdune--Result \
ocamlx-Stdune--Root \
ocamlx-Stdune--Scanf \
ocamlx-Stdune--Seq \
ocamlx-Stdune--Set \
ocamlx-Stdune--Set-intf \
ocamlx-Stdune--Sexp \
ocamlx-Stdune--Signal \
ocamlx-Stdune--Staged \
ocamlx-Stdune--Stat \
ocamlx-Stdune--State \
ocamlx-Stdune--String \
ocamlx-Stdune--String-builder \
ocamlx-Stdune--String-split \
ocamlx-Stdune--Sys \
ocamlx-Stdune--Table \
ocamlx-Stdune--Temp \
ocamlx-Stdune--Terminal-persistence \
ocamlx-Stdune--Terminal-signals \
ocamlx-Stdune--Time \
ocamlx-Stdune--Tuple \
ocamlx-Stdune--Type-eq \
ocamlx-Stdune--Unit \
ocamlx-Stdune--Univ-map \
ocamlx-Stdune--Univ-map-intf \
ocamlx-Stdune--Unix-error \
ocamlx-Stdune--User-error \
ocamlx-Stdune--User-message \
ocamlx-Stdune--User-warning \
ocamlx-Top-closure \
ocamlx-Top-closure-- \
ocamlx-Top-closure--S \
ocamlx-Xdg"

RDEPENDS:${PN} += "libc.so.6 \
ocaml-Asttypes \
ocaml-Build-path-prefix-map \
ocaml-CamlinternalFormatBasics \
ocaml-CamlinternalLazy \
ocaml-Cmi-format \
ocaml-Csexp \
ocaml-Data-types \
ocaml-Dynlink \
ocaml-Env \
ocaml-Format-doc \
ocaml-Ident \
ocaml-Identifiable \
ocaml-Load-path \
ocaml-Location \
ocaml-Longident \
ocaml-Misc \
ocaml-Oprint \
ocaml-Outcometree \
ocaml-Parsetree \
ocaml-Path \
ocaml-Pp \
ocaml-Primitive \
ocaml-Re \
ocaml-Re-- \
ocaml-Re--Ast \
ocaml-Re--Automata \
ocaml-Re--Category \
ocaml-Re--Color-map \
ocaml-Re--Compile \
ocaml-Re--Core \
ocaml-Re--Cset \
ocaml-Re--Dyn \
ocaml-Re--Fmt \
ocaml-Re--Group \
ocaml-Re--Mark-infos \
ocaml-Re--Pmark \
ocaml-Re--Replace \
ocaml-Shape \
ocaml-Stdlib \
ocaml-Stdlib--Arg \
ocaml-Stdlib--Array \
ocaml-Stdlib--ArrayLabels \
ocaml-Stdlib--Bigarray \
ocaml-Stdlib--Buffer \
ocaml-Stdlib--Bytes \
ocaml-Stdlib--BytesLabels \
ocaml-Stdlib--Char \
ocaml-Stdlib--Complex \
ocaml-Stdlib--Digest \
ocaml-Stdlib--Domain \
ocaml-Stdlib--Either \
ocaml-Stdlib--Filename \
ocaml-Stdlib--Float \
ocaml-Stdlib--Format \
ocaml-Stdlib--Fun \
ocaml-Stdlib--Hashtbl \
ocaml-Stdlib--Int \
ocaml-Stdlib--Int32 \
ocaml-Stdlib--Int64 \
ocaml-Stdlib--Lazy \
ocaml-Stdlib--Lexing \
ocaml-Stdlib--List \
ocaml-Stdlib--ListLabels \
ocaml-Stdlib--Map \
ocaml-Stdlib--Marshal \
ocaml-Stdlib--MoreLabels \
ocaml-Stdlib--Mutex \
ocaml-Stdlib--Nativeint \
ocaml-Stdlib--Obj \
ocaml-Stdlib--Option \
ocaml-Stdlib--Printexc \
ocaml-Stdlib--Printf \
ocaml-Stdlib--Queue \
ocaml-Stdlib--Random \
ocaml-Stdlib--Result \
ocaml-Stdlib--Scanf \
ocaml-Stdlib--Seq \
ocaml-Stdlib--Set \
ocaml-Stdlib--StdLabels \
ocaml-Stdlib--String \
ocaml-Stdlib--StringLabels \
ocaml-Stdlib--Sys \
ocaml-Stdlib--Uchar \
ocaml-Subst \
ocaml-Topdirs \
ocaml-Toploop \
ocaml-Type-immediacy \
ocaml-Types \
ocaml-Unit-info \
ocaml-Unix \
ocaml-Warnings \
ocamlfind-compiler-libs \
ocamlfind-compiler-libs.toplevel \
ocamlfind-csexp \
ocamlfind-dune-glob \
ocamlfind-dune-private-libs.dune-section \
ocamlfind-dune-private-libs.meta-parser \
ocamlfind-dune-rpc \
ocamlfind-dune-site \
ocamlfind-dune-site.linker \
ocamlfind-dune-site.private \
ocamlfind-dyn \
ocamlfind-dynlink \
ocamlfind-fs-io \
ocamlfind-ocamlc-loc \
ocamlfind-ordering \
ocamlfind-pp \
ocamlfind-re \
ocamlfind-stdune \
ocamlfind-threads \
ocamlfind-threads.posix \
ocamlfind-top-closure \
ocamlfind-unix \
ocamlfind-xdg \
ocamlx-CamlinternalLazy \
ocamlx-Csexp \
ocamlx-Dynlink \
ocamlx-Pp \
ocamlx-Re \
ocamlx-Stdlib \
ocamlx-Stdlib--Arg \
ocamlx-Stdlib--Array \
ocamlx-Stdlib--ArrayLabels \
ocamlx-Stdlib--Buffer \
ocamlx-Stdlib--Bytes \
ocamlx-Stdlib--BytesLabels \
ocamlx-Stdlib--Char \
ocamlx-Stdlib--Filename \
ocamlx-Stdlib--Float \
ocamlx-Stdlib--Format \
ocamlx-Stdlib--Fun \
ocamlx-Stdlib--Hashtbl \
ocamlx-Stdlib--Int \
ocamlx-Stdlib--Int32 \
ocamlx-Stdlib--Int64 \
ocamlx-Stdlib--Lazy \
ocamlx-Stdlib--Lexing \
ocamlx-Stdlib--List \
ocamlx-Stdlib--ListLabels \
ocamlx-Stdlib--Marshal \
ocamlx-Stdlib--MoreLabels \
ocamlx-Stdlib--Mutex \
ocamlx-Stdlib--Nativeint \
ocamlx-Stdlib--Option \
ocamlx-Stdlib--Printexc \
ocamlx-Stdlib--Printf \
ocamlx-Stdlib--Queue \
ocamlx-Stdlib--Random \
ocamlx-Stdlib--Scanf \
ocamlx-Stdlib--Seq \
ocamlx-Stdlib--String \
ocamlx-Stdlib--StringLabels \
ocamlx-Stdlib--Sys \
ocamlx-Unix"

inherit rpm
