SUMMARY = "Azure Entra Id authentication PAM module"
DESCRIPTION = "Himmelblau is an interoperability suite for Microsoft Azure Entra Id \
and Intune, which allows users to sign into a Linux machine using Azure \
Entra Id credentials."
LICENSE = "GPL-3.0-or-later"

PV = "3.1.14+git0.7d1ea961"

RPM_NAME = "pam-himmelblau-3.1.14+git0.7d1ea961-1.1.aarch64.rpm"
RPM_HASH = "f2709189d256d9cd2a67268ffe45e3eb9d21e35fb5b31e90ad74e0c0a83d5f9d497a5335629e59f1fc927c844d02704eaee619b3d1b629f271a2bbbfb17675b5"

RPROVIDES:${PN} += "bundled-rust-crate-adler2 \
bundled-rust-crate-aead \
bundled-rust-crate-aes \
bundled-rust-crate-aes-gcm \
bundled-rust-crate-aes-kw \
bundled-rust-crate-aho-corasick \
bundled-rust-crate-allocator-api2 \
bundled-rust-crate-anstream \
bundled-rust-crate-anstyle \
bundled-rust-crate-anstyle-parse \
bundled-rust-crate-anstyle-query \
bundled-rust-crate-anyhow \
bundled-rust-crate-argon2 \
bundled-rust-crate-array-init \
bundled-rust-crate-assert-hex \
bundled-rust-crate-async-trait \
bundled-rust-crate-atomic-waker \
bundled-rust-crate-authenticator \
bundled-rust-crate-autocfg \
bundled-rust-crate-aws-lc-rs \
bundled-rust-crate-aws-lc-sys \
bundled-rust-crate-base16ct \
bundled-rust-crate-base32 \
bundled-rust-crate-base64 \
bundled-rust-crate-base64ct \
bundled-rust-crate-base64urlsafedata \
bundled-rust-crate-binary-stream \
bundled-rust-crate-bindgen \
bundled-rust-crate-binrw \
bundled-rust-crate-binrw-derive \
bundled-rust-crate-bitflags \
bundled-rust-crate-bitmask-enum \
bundled-rust-crate-blake2 \
bundled-rust-crate-block-buffer \
bundled-rust-crate-block-padding \
bundled-rust-crate-bs58 \
bundled-rust-crate-bytemuck \
bundled-rust-crate-byteorder-lite \
bundled-rust-crate-bytes \
bundled-rust-crate-c-types \
bundled-rust-crate-cbc \
bundled-rust-crate-cbindgen \
bundled-rust-crate-cc \
bundled-rust-crate-cexpr \
bundled-rust-crate-cfg-aliases \
bundled-rust-crate-cfg-if \
bundled-rust-crate-chacha20 \
bundled-rust-crate-chrono \
bundled-rust-crate-cipher \
bundled-rust-crate-clang-sys \
bundled-rust-crate-clap \
bundled-rust-crate-clap-builder \
bundled-rust-crate-clap-derive \
bundled-rust-crate-clap-lex \
bundled-rust-crate-cmake \
bundled-rust-crate-colorchoice \
bundled-rust-crate-compact-jwt \
bundled-rust-crate-configparser \
bundled-rust-crate-const-oid \
bundled-rust-crate-constant-time-eq \
bundled-rust-crate-cookie \
bundled-rust-crate-cookie-store \
bundled-rust-crate-cpufeatures \
bundled-rust-crate-crc32fast \
bundled-rust-crate-crypto-bigint \
bundled-rust-crate-crypto-common \
bundled-rust-crate-crypto-glue \
bundled-rust-crate-cssparser \
bundled-rust-crate-cssparser-macros \
bundled-rust-crate-csv \
bundled-rust-crate-csv-core \
bundled-rust-crate-ctr \
bundled-rust-crate-curve25519-dalek \
bundled-rust-crate-darling \
bundled-rust-crate-darling-core \
bundled-rust-crate-darling-macro \
bundled-rust-crate-defmt \
bundled-rust-crate-defmt-macros \
bundled-rust-crate-defmt-parser \
bundled-rust-crate-der \
bundled-rust-crate-der-derive \
bundled-rust-crate-deranged \
bundled-rust-crate-derive-more \
bundled-rust-crate-derive-more-impl \
bundled-rust-crate-digest \
bundled-rust-crate-displaydoc \
bundled-rust-crate-document-features \
bundled-rust-crate-dtoa \
bundled-rust-crate-dtoa-short \
bundled-rust-crate-dunce \
bundled-rust-crate-dyn-clone \
bundled-rust-crate-ecdsa \
bundled-rust-crate-ed25519 \
bundled-rust-crate-ed25519-dalek \
bundled-rust-crate-ego-tree \
bundled-rust-crate-either \
bundled-rust-crate-elliptic-curve \
bundled-rust-crate-encoding-rs \
bundled-rust-crate-equivalent \
bundled-rust-crate-errno \
bundled-rust-crate-fallible-iterator \
bundled-rust-crate-fallible-streaming-iterator \
bundled-rust-crate-fastrand \
bundled-rust-crate-fdeflate \
bundled-rust-crate-ff \
bundled-rust-crate-find-msvc-tools \
bundled-rust-crate-flagset \
bundled-rust-crate-flate2 \
bundled-rust-crate-fnv \
bundled-rust-crate-foldhash \
bundled-rust-crate-foreign-types \
bundled-rust-crate-foreign-types-shared \
bundled-rust-crate-form-urlencoded \
bundled-rust-crate-fs-extra \
bundled-rust-crate-futures \
bundled-rust-crate-futures-channel \
bundled-rust-crate-futures-core \
bundled-rust-crate-futures-executor \
bundled-rust-crate-futures-io \
bundled-rust-crate-futures-macro \
bundled-rust-crate-futures-sink \
bundled-rust-crate-futures-task \
bundled-rust-crate-futures-util \
bundled-rust-crate-generic-array \
bundled-rust-crate-gethostname \
bundled-rust-crate-getopts \
bundled-rust-crate-getrandom \
bundled-rust-crate-ghash \
bundled-rust-crate-glob \
bundled-rust-crate-group \
bundled-rust-crate-h2 \
bundled-rust-crate-half \
bundled-rust-crate-hashbrown \
bundled-rust-crate-hashlink \
bundled-rust-crate-heck \
bundled-rust-crate-hex \
bundled-rust-crate-himmelblau-unix-common \
bundled-rust-crate-hkdf \
bundled-rust-crate-hmac \
bundled-rust-crate-hostname \
bundled-rust-crate-html5ever \
bundled-rust-crate-http \
bundled-rust-crate-http-body \
bundled-rust-crate-http-body-util \
bundled-rust-crate-httparse \
bundled-rust-crate-hybrid-array \
bundled-rust-crate-hyper \
bundled-rust-crate-hyper-rustls \
bundled-rust-crate-hyper-timeout \
bundled-rust-crate-hyper-tls \
bundled-rust-crate-hyper-util \
bundled-rust-crate-iana-time-zone \
bundled-rust-crate-icu-collections \
bundled-rust-crate-icu-locale-core \
bundled-rust-crate-icu-normalizer \
bundled-rust-crate-icu-normalizer-data \
bundled-rust-crate-icu-properties \
bundled-rust-crate-icu-properties-data \
bundled-rust-crate-icu-provider \
bundled-rust-crate-ident-case \
bundled-rust-crate-idmap \
bundled-rust-crate-idna \
bundled-rust-crate-idna-adapter \
bundled-rust-crate-image \
bundled-rust-crate-indexmap \
bundled-rust-crate-inout \
bundled-rust-crate-ipnet \
bundled-rust-crate-iri-string \
bundled-rust-crate-is-terminal-polyfill \
bundled-rust-crate-itertools \
bundled-rust-crate-itoa \
bundled-rust-crate-jiff \
bundled-rust-crate-jiff-core \
bundled-rust-crate-jobserver \
bundled-rust-crate-kanidm-hsm-crypto \
bundled-rust-crate-kanidm-lib-crypto \
bundled-rust-crate-kanidm-lib-file-permissions \
bundled-rust-crate-kanidm-utils-users \
bundled-rust-crate-kbkdf \
bundled-rust-crate-keyutils \
bundled-rust-crate-keyutils-raw \
bundled-rust-crate-lazy-static \
bundled-rust-crate-lber \
bundled-rust-crate-ldap3-proto \
bundled-rust-crate-libc \
bundled-rust-crate-libhimmelblau \
bundled-rust-crate-libkrimes \
bundled-rust-crate-libloading \
bundled-rust-crate-libm \
bundled-rust-crate-libsqlite3-sys \
bundled-rust-crate-libudev \
bundled-rust-crate-libudev-sys \
bundled-rust-crate-linux-raw-sys \
bundled-rust-crate-litemap \
bundled-rust-crate-litrs \
bundled-rust-crate-lock-api \
bundled-rust-crate-log \
bundled-rust-crate-lru \
bundled-rust-crate-lru-slab \
bundled-rust-crate-markup5ever \
bundled-rust-crate-matchers \
bundled-rust-crate-md-5 \
bundled-rust-crate-md4 \
bundled-rust-crate-md5 \
bundled-rust-crate-memchr \
bundled-rust-crate-mime \
bundled-rust-crate-minimal-lexical \
bundled-rust-crate-miniz-oxide \
bundled-rust-crate-mio \
bundled-rust-crate-native-tls \
bundled-rust-crate-new-debug-unreachable \
bundled-rust-crate-nom \
bundled-rust-crate-nu-ansi-term \
bundled-rust-crate-num-bigint-dig \
bundled-rust-crate-num-conv \
bundled-rust-crate-num-enum \
bundled-rust-crate-num-enum-derive \
bundled-rust-crate-num-integer \
bundled-rust-crate-num-iter \
bundled-rust-crate-num-traits \
bundled-rust-crate-oauth2 \
bundled-rust-crate-once-cell \
bundled-rust-crate-opaque-debug \
bundled-rust-crate-openidconnect \
bundled-rust-crate-openssl \
bundled-rust-crate-openssl-macros \
bundled-rust-crate-openssl-probe \
bundled-rust-crate-openssl-sys \
bundled-rust-crate-opentelemetry \
bundled-rust-crate-opentelemetry-http \
bundled-rust-crate-opentelemetry-otlp \
bundled-rust-crate-opentelemetry-proto \
bundled-rust-crate-opentelemetry-sdk \
bundled-rust-crate-opentelemetry-semantic-conventions \
bundled-rust-crate-ordered-float \
bundled-rust-crate-os-release \
bundled-rust-crate-owo-colors \
bundled-rust-crate-p256 \
bundled-rust-crate-p384 \
bundled-rust-crate-p521 \
bundled-rust-crate-pam-himmelblau \
bundled-rust-crate-parking-lot \
bundled-rust-crate-parking-lot-core \
bundled-rust-crate-password-hash \
bundled-rust-crate-pastey \
bundled-rust-crate-pbkdf2 \
bundled-rust-crate-peg \
bundled-rust-crate-peg-macros \
bundled-rust-crate-peg-runtime \
bundled-rust-crate-pem \
bundled-rust-crate-pem-rfc7468 \
bundled-rust-crate-percent-encoding \
bundled-rust-crate-phf \
bundled-rust-crate-phf-codegen \
bundled-rust-crate-phf-generator \
bundled-rust-crate-phf-macros \
bundled-rust-crate-phf-shared \
bundled-rust-crate-pin-project \
bundled-rust-crate-pin-project-internal \
bundled-rust-crate-pin-project-lite \
bundled-rust-crate-pkcs1 \
bundled-rust-crate-pkcs5 \
bundled-rust-crate-pkcs8 \
bundled-rust-crate-pkg-config \
bundled-rust-crate-png \
bundled-rust-crate-polyval \
bundled-rust-crate-potential-utf \
bundled-rust-crate-powerfmt \
bundled-rust-crate-ppv-lite86 \
bundled-rust-crate-precomputed-hash \
bundled-rust-crate-prettyplease \
bundled-rust-crate-primeorder \
bundled-rust-crate-proc-macro-crate \
bundled-rust-crate-proc-macro2 \
bundled-rust-crate-prost \
bundled-rust-crate-prost-derive \
bundled-rust-crate-prost-types \
bundled-rust-crate-psl-types \
bundled-rust-crate-publicsuffix \
bundled-rust-crate-qrcodegen \
bundled-rust-crate-qrcodegen-image \
bundled-rust-crate-quinn \
bundled-rust-crate-quinn-proto \
bundled-rust-crate-quinn-udp \
bundled-rust-crate-quote \
bundled-rust-crate-rand \
bundled-rust-crate-rand-chacha \
bundled-rust-crate-rand-core \
bundled-rust-crate-rand-pcg \
bundled-rust-crate-ref-cast \
bundled-rust-crate-ref-cast-impl \
bundled-rust-crate-regex \
bundled-rust-crate-regex-automata \
bundled-rust-crate-regex-syntax \
bundled-rust-crate-reqwest \
bundled-rust-crate-reqwest-cookie-store \
bundled-rust-crate-rfc6979 \
bundled-rust-crate-ring \
bundled-rust-crate-rpassword \
bundled-rust-crate-rsa \
bundled-rust-crate-rtoolbox \
bundled-rust-crate-runloop \
bundled-rust-crate-rusqlite \
bundled-rust-crate-rustc-hash \
bundled-rust-crate-rustc-version \
bundled-rust-crate-rustix \
bundled-rust-crate-rustls \
bundled-rust-crate-rustls-native-certs \
bundled-rust-crate-rustls-pki-types \
bundled-rust-crate-rustls-platform-verifier \
bundled-rust-crate-rustls-webpki \
bundled-rust-crate-rustversion \
bundled-rust-crate-ryu \
bundled-rust-crate-salsa20 \
bundled-rust-crate-schemars \
bundled-rust-crate-scopeguard \
bundled-rust-crate-scraper \
bundled-rust-crate-scrypt \
bundled-rust-crate-sec1 \
bundled-rust-crate-selectors \
bundled-rust-crate-semver \
bundled-rust-crate-serde \
bundled-rust-crate-serde-binary \
bundled-rust-crate-serde-bytes \
bundled-rust-crate-serde-cbor \
bundled-rust-crate-serde-cbor-2 \
bundled-rust-crate-serde-core \
bundled-rust-crate-serde-derive \
bundled-rust-crate-serde-json \
bundled-rust-crate-serde-path-to-error \
bundled-rust-crate-serde-plain \
bundled-rust-crate-serde-spanned \
bundled-rust-crate-serde-urlencoded \
bundled-rust-crate-serde-value \
bundled-rust-crate-serde-with \
bundled-rust-crate-serde-with-macros \
bundled-rust-crate-servo-arc \
bundled-rust-crate-sha-crypt \
bundled-rust-crate-sha1 \
bundled-rust-crate-sha1-smol \
bundled-rust-crate-sha2 \
bundled-rust-crate-sharded-slab \
bundled-rust-crate-shlex \
bundled-rust-crate-signal-hook-registry \
bundled-rust-crate-signature \
bundled-rust-crate-simd-adler32 \
bundled-rust-crate-siphasher \
bundled-rust-crate-sketching \
bundled-rust-crate-slab \
bundled-rust-crate-smallvec \
bundled-rust-crate-socket2 \
bundled-rust-crate-spin \
bundled-rust-crate-spki \
bundled-rust-crate-stable-deref-trait \
bundled-rust-crate-string-cache \
bundled-rust-crate-string-cache-codegen \
bundled-rust-crate-strsim \
bundled-rust-crate-subtle \
bundled-rust-crate-syn \
bundled-rust-crate-sync-wrapper \
bundled-rust-crate-synstructure \
bundled-rust-crate-tempfile \
bundled-rust-crate-tendril \
bundled-rust-crate-thiserror \
bundled-rust-crate-thiserror-impl \
bundled-rust-crate-thread-local \
bundled-rust-crate-time \
bundled-rust-crate-time-core \
bundled-rust-crate-time-macros \
bundled-rust-crate-tinystr \
bundled-rust-crate-tinyvec \
bundled-rust-crate-tinyvec-macros \
bundled-rust-crate-tls-codec \
bundled-rust-crate-tls-codec-derive \
bundled-rust-crate-tokio \
bundled-rust-crate-tokio-macros \
bundled-rust-crate-tokio-native-tls \
bundled-rust-crate-tokio-rustls \
bundled-rust-crate-tokio-stream \
bundled-rust-crate-tokio-util \
bundled-rust-crate-toml \
bundled-rust-crate-toml-datetime \
bundled-rust-crate-toml-edit \
bundled-rust-crate-toml-parser \
bundled-rust-crate-toml-writer \
bundled-rust-crate-tonic \
bundled-rust-crate-tonic-prost \
bundled-rust-crate-tonic-types \
bundled-rust-crate-totp-rs \
bundled-rust-crate-tower \
bundled-rust-crate-tower-http \
bundled-rust-crate-tower-layer \
bundled-rust-crate-tower-service \
bundled-rust-crate-tracing \
bundled-rust-crate-tracing-attributes \
bundled-rust-crate-tracing-core \
bundled-rust-crate-tracing-forest \
bundled-rust-crate-tracing-log \
bundled-rust-crate-tracing-opentelemetry \
bundled-rust-crate-tracing-subscriber \
bundled-rust-crate-try-lock \
bundled-rust-crate-typenum \
bundled-rust-crate-unicode-ident \
bundled-rust-crate-unicode-width \
bundled-rust-crate-uninit \
bundled-rust-crate-universal-hash \
bundled-rust-crate-untrusted \
bundled-rust-crate-url \
bundled-rust-crate-urlencoding \
bundled-rust-crate-utf8-iter \
bundled-rust-crate-utf8parse \
bundled-rust-crate-uuid \
bundled-rust-crate-uzers \
bundled-rust-crate-vcpkg \
bundled-rust-crate-version-check \
bundled-rust-crate-want \
bundled-rust-crate-web-atoms \
bundled-rust-crate-webpki-roots \
bundled-rust-crate-winnow \
bundled-rust-crate-writeable \
bundled-rust-crate-x509-cert \
bundled-rust-crate-yoke \
bundled-rust-crate-yoke-derive \
bundled-rust-crate-zerocopy \
bundled-rust-crate-zerofrom \
bundled-rust-crate-zerofrom-derive \
bundled-rust-crate-zeroize \
bundled-rust-crate-zeroize-derive \
bundled-rust-crate-zerotrie \
bundled-rust-crate-zerovec \
bundled-rust-crate-zerovec-derive \
bundled-rust-crate-zmij \
pam-himmelblau"

RDEPENDS:${PN} += "himmelblau \
libc.so.6 \
libcrypto.so.3 \
libgcc-s.so.1 \
libm.so.6 \
libpam.so.0 \
libsqlite3.so.0 \
libssl.so.3 \
libudev.so.1 \
libunistring.so.5"

inherit rpm
