SUMMARY = "Core part of Maven"
DESCRIPTION = "Core part of Apache Maven that can be used as a library."
LICENSE = "Apache-2.0 & MIT"

PV = "4.0.0~rc6"

RPM_NAME = "maven4-lib-4.0.0~rc6-2.1.aarch64.rpm"
RPM_HASH = "ffae3153e917fa0eaa0fa95ac7e1d8c008b962c9fd30b9e15325e3d08dc22bb01ee6ca1bff049ece08b083c0e5c040d7d6ff8d924e5e921e9e39ed97a274cc08"

RPROVIDES:${PN} += "config-maven4-lib \
maven4-bootstrap \
maven4-lib \
mvn-org.apache.maven-maven-api-annotations \
mvn-org.apache.maven-maven-api-annotations-pom- \
mvn-org.apache.maven-maven-api-cli \
mvn-org.apache.maven-maven-api-cli-pom- \
mvn-org.apache.maven-maven-api-core \
mvn-org.apache.maven-maven-api-core-pom- \
mvn-org.apache.maven-maven-api-di \
mvn-org.apache.maven-maven-api-di-pom- \
mvn-org.apache.maven-maven-api-metadata \
mvn-org.apache.maven-maven-api-metadata-pom- \
mvn-org.apache.maven-maven-api-model \
mvn-org.apache.maven-maven-api-model-pom- \
mvn-org.apache.maven-maven-api-plugin \
mvn-org.apache.maven-maven-api-plugin-pom- \
mvn-org.apache.maven-maven-api-pom- \
mvn-org.apache.maven-maven-api-settings \
mvn-org.apache.maven-maven-api-settings-pom- \
mvn-org.apache.maven-maven-api-spi \
mvn-org.apache.maven-maven-api-spi-pom- \
mvn-org.apache.maven-maven-api-toolchain \
mvn-org.apache.maven-maven-api-toolchain-pom- \
mvn-org.apache.maven-maven-api-xml \
mvn-org.apache.maven-maven-api-xml-pom- \
mvn-org.apache.maven-maven-artifact-4 \
mvn-org.apache.maven-maven-artifact-4.0.0-rc-6 \
mvn-org.apache.maven-maven-artifact-pom-4 \
mvn-org.apache.maven-maven-artifact-pom-4.0.0-rc-6 \
mvn-org.apache.maven-maven-builder-support-4 \
mvn-org.apache.maven-maven-builder-support-4.0.0-rc-6 \
mvn-org.apache.maven-maven-builder-support-pom-4 \
mvn-org.apache.maven-maven-builder-support-pom-4.0.0-rc-6 \
mvn-org.apache.maven-maven-cli \
mvn-org.apache.maven-maven-cli-pom- \
mvn-org.apache.maven-maven-compat-4 \
mvn-org.apache.maven-maven-compat-4.0.0-rc-6 \
mvn-org.apache.maven-maven-compat-modules-pom- \
mvn-org.apache.maven-maven-compat-pom-4 \
mvn-org.apache.maven-maven-compat-pom-4.0.0-rc-6 \
mvn-org.apache.maven-maven-core-4 \
mvn-org.apache.maven-maven-core-4.0.0-rc-6 \
mvn-org.apache.maven-maven-core-pom-4 \
mvn-org.apache.maven-maven-core-pom-4.0.0-rc-6 \
mvn-org.apache.maven-maven-di \
mvn-org.apache.maven-maven-di-pom- \
mvn-org.apache.maven-maven-embedder-4 \
mvn-org.apache.maven-maven-embedder-4.0.0-rc-6 \
mvn-org.apache.maven-maven-embedder-pom-4 \
mvn-org.apache.maven-maven-embedder-pom-4.0.0-rc-6 \
mvn-org.apache.maven-maven-impl \
mvn-org.apache.maven-maven-impl-modules-pom- \
mvn-org.apache.maven-maven-impl-pom- \
mvn-org.apache.maven-maven-jline-4 \
mvn-org.apache.maven-maven-jline-4.0.0-rc-6 \
mvn-org.apache.maven-maven-jline-pom-4 \
mvn-org.apache.maven-maven-jline-pom-4.0.0-rc-6 \
mvn-org.apache.maven-maven-logging \
mvn-org.apache.maven-maven-logging-pom- \
mvn-org.apache.maven-maven-model-4 \
mvn-org.apache.maven-maven-model-4.0.0-rc-6 \
mvn-org.apache.maven-maven-model-builder-4 \
mvn-org.apache.maven-maven-model-builder-4.0.0-rc-6 \
mvn-org.apache.maven-maven-model-builder-pom-4 \
mvn-org.apache.maven-maven-model-builder-pom-4.0.0-rc-6 \
mvn-org.apache.maven-maven-model-pom-4 \
mvn-org.apache.maven-maven-model-pom-4.0.0-rc-6 \
mvn-org.apache.maven-maven-plugin-api-4 \
mvn-org.apache.maven-maven-plugin-api-4.0.0-rc-6 \
mvn-org.apache.maven-maven-plugin-api-pom-4 \
mvn-org.apache.maven-maven-plugin-api-pom-4.0.0-rc-6 \
mvn-org.apache.maven-maven-pom-4 \
mvn-org.apache.maven-maven-pom-4.0.0-rc-6 \
mvn-org.apache.maven-maven-repository-metadata-4 \
mvn-org.apache.maven-maven-repository-metadata-4.0.0-rc-6 \
mvn-org.apache.maven-maven-repository-metadata-pom-4 \
mvn-org.apache.maven-maven-repository-metadata-pom-4.0.0-rc-6 \
mvn-org.apache.maven-maven-resolver-provider-4 \
mvn-org.apache.maven-maven-resolver-provider-4.0.0-rc-6 \
mvn-org.apache.maven-maven-resolver-provider-pom-4 \
mvn-org.apache.maven-maven-resolver-provider-pom-4.0.0-rc-6 \
mvn-org.apache.maven-maven-settings-4 \
mvn-org.apache.maven-maven-settings-4.0.0-rc-6 \
mvn-org.apache.maven-maven-settings-builder-4 \
mvn-org.apache.maven-maven-settings-builder-4.0.0-rc-6 \
mvn-org.apache.maven-maven-settings-builder-pom-4 \
mvn-org.apache.maven-maven-settings-builder-pom-4.0.0-rc-6 \
mvn-org.apache.maven-maven-settings-pom-4 \
mvn-org.apache.maven-maven-settings-pom-4.0.0-rc-6 \
mvn-org.apache.maven-maven-support \
mvn-org.apache.maven-maven-support-pom- \
mvn-org.apache.maven-maven-toolchain-builder \
mvn-org.apache.maven-maven-toolchain-builder-pom- \
mvn-org.apache.maven-maven-toolchain-model \
mvn-org.apache.maven-maven-toolchain-model-pom- \
mvn-org.apache.maven-maven-xml \
mvn-org.apache.maven-maven-xml-pom-"

RDEPENDS:${PN} += "aopalliance \
apache-commons-cli \
apache-commons-codec \
apache-commons-lang3 \
apache-commons-logging \
atinject \
domtrip \
glassfish-annotation-api \
google-gson \
google-guice \
guava \
httpcomponents-client \
httpcomponents-core \
jakarta-inject \
java-headless \
javapackages-filesystem \
jcl-over-slf4j \
jline3-builtins \
jline3-console \
jline3-console-ui \
jline3-jansi-core \
jline3-native \
jline3-reader \
jline3-style \
jline3-terminal \
jline3-terminal-jni \
jspecify \
jul-to-slf4j \
maven-resolver-api \
maven-resolver-connector-basic \
maven-resolver-impl \
maven-resolver-named-locks \
maven-resolver-spi \
maven-resolver-transport-apache \
maven-resolver-transport-file \
maven-resolver-transport-jdk \
maven-resolver-transport-wagon \
maven-resolver-util \
maven-wagon-file \
maven-wagon-http \
maven-wagon-http-shared \
maven-wagon-provider-api \
methanol \
mvn-aopalliance-aopalliance \
mvn-com.fasterxml.woodstox-woodstox-core \
mvn-com.google.inject-guice--classes- \
mvn-commons-cli-commons-cli \
mvn-eu.maveniverse.maven.domtrip-domtrip-core \
mvn-eu.maveniverse.maven.domtrip-domtrip-maven \
mvn-javax.inject-javax.inject \
mvn-org.apache.maven.resolver-maven-resolver-api \
mvn-org.apache.maven.resolver-maven-resolver-connector-basic \
mvn-org.apache.maven.resolver-maven-resolver-impl \
mvn-org.apache.maven.resolver-maven-resolver-named-locks \
mvn-org.apache.maven.resolver-maven-resolver-spi \
mvn-org.apache.maven.resolver-maven-resolver-transport-apache \
mvn-org.apache.maven.resolver-maven-resolver-transport-file \
mvn-org.apache.maven.resolver-maven-resolver-util \
mvn-org.apache.maven.wagon-wagon-provider-api \
mvn-org.codehaus.plexus-plexus-classworlds \
mvn-org.codehaus.plexus-plexus-component-annotations \
mvn-org.codehaus.plexus-plexus-interactivity-api \
mvn-org.codehaus.plexus-plexus-interpolation \
mvn-org.codehaus.plexus-plexus-sec-dispatcher-4.1.0 \
mvn-org.codehaus.plexus-plexus-utils \
mvn-org.codehaus.plexus-plexus-xml-4 \
mvn-org.codehaus.woodstox-stax2-api \
mvn-org.eclipse.sisu-org.eclipse.sisu.inject \
mvn-org.eclipse.sisu-org.eclipse.sisu.plexus \
mvn-org.jline-jansi-core \
mvn-org.jline-jline-builtins \
mvn-org.jline-jline-console \
mvn-org.jline-jline-console-ui \
mvn-org.jline-jline-reader \
mvn-org.jline-jline-style \
mvn-org.jline-jline-terminal \
mvn-org.jline-jline-terminal-jni \
mvn-org.slf4j-jul-to-slf4j \
mvn-org.slf4j-slf4j-api \
objectweb-asm \
plexus-classworlds \
plexus-containers-component-annotations \
plexus-interactivity-api \
plexus-interpolation \
plexus-sec-dispatcher4 \
plexus-utils \
plexus-xml4 \
sisu-inject \
sisu-plexus \
slf4j \
stax2-api \
woodstox-core"

inherit rpm
