SUMMARY = "A new markup-based typesetting system that is powerful and easy to learn"
DESCRIPTION = "Typst is a new markup-based typesetting system that is designed to be as powerful as LaTeX while being much easier to learn and use."
LICENSE = "Apache-2.0"

PV = "0.15.1"

RPM_NAME = "typst-0.15.1-1.1.aarch64.rpm"
RPM_HASH = "5ad06d75fc95208339b825bc87b83aaaff7ee26d8e18d8f083b105158712ccdd4547cd72d9a4b19319391cff0faa5711f2e88f3358b4d51a56fd392ed6b4e61f"

RPROVIDES:${PN} += "bundled-rust-crate-adler2 \
bundled-rust-crate-aho-corasick \
bundled-rust-crate-anstream \
bundled-rust-crate-anstyle \
bundled-rust-crate-anstyle-parse \
bundled-rust-crate-anstyle-query \
bundled-rust-crate-approx \
bundled-rust-crate-arrayref \
bundled-rust-crate-arrayvec \
bundled-rust-crate-ascii \
bundled-rust-crate-autocfg \
bundled-rust-crate-az \
bundled-rust-crate-base64 \
bundled-rust-crate-biblatex \
bundled-rust-crate-bincode \
bundled-rust-crate-bit-set \
bundled-rust-crate-bit-vec \
bundled-rust-crate-bitflags \
bundled-rust-crate-bumpalo \
bundled-rust-crate-by-address \
bundled-rust-crate-bytemuck \
bundled-rust-crate-bytemuck-derive \
bundled-rust-crate-byteorder \
bundled-rust-crate-byteorder-lite \
bundled-rust-crate-cc \
bundled-rust-crate-cfg-if \
bundled-rust-crate-chinese-number \
bundled-rust-crate-chinese-variant \
bundled-rust-crate-chrono \
bundled-rust-crate-chunked-transfer \
bundled-rust-crate-ciborium \
bundled-rust-crate-ciborium-io \
bundled-rust-crate-ciborium-ll \
bundled-rust-crate-citationberg \
bundled-rust-crate-clap \
bundled-rust-crate-clap-builder \
bundled-rust-crate-clap-complete \
bundled-rust-crate-clap-derive \
bundled-rust-crate-clap-lex \
bundled-rust-crate-clap-mangen \
bundled-rust-crate-cobs \
bundled-rust-crate-codespan-reporting \
bundled-rust-crate-codex \
bundled-rust-crate-color \
bundled-rust-crate-color-print \
bundled-rust-crate-color-print-proc-macro \
bundled-rust-crate-color-quant \
bundled-rust-crate-colorchoice \
bundled-rust-crate-comemo \
bundled-rust-crate-comemo-macros \
bundled-rust-crate-core-maths \
bundled-rust-crate-crc32fast \
bundled-rust-crate-crossbeam-deque \
bundled-rust-crate-crossbeam-epoch \
bundled-rust-crate-crossbeam-utils \
bundled-rust-crate-csv \
bundled-rust-crate-csv-core \
bundled-rust-crate-data-url \
bundled-rust-crate-deranged \
bundled-rust-crate-dirs \
bundled-rust-crate-dirs-sys \
bundled-rust-crate-displaydoc \
bundled-rust-crate-ecow \
bundled-rust-crate-either \
bundled-rust-crate-enum-ordinalize \
bundled-rust-crate-enum-ordinalize-derive \
bundled-rust-crate-env-proxy \
bundled-rust-crate-equivalent \
bundled-rust-crate-errno \
bundled-rust-crate-euclid \
bundled-rust-crate-fancy-regex \
bundled-rust-crate-fast-srgb8 \
bundled-rust-crate-fastrand \
bundled-rust-crate-fdeflate \
bundled-rust-crate-fearless-simd \
bundled-rust-crate-filetime \
bundled-rust-crate-flate2 \
bundled-rust-crate-float-cmp \
bundled-rust-crate-fnv \
bundled-rust-crate-foldhash \
bundled-rust-crate-font-types \
bundled-rust-crate-fontconfig-parser \
bundled-rust-crate-fontdb \
bundled-rust-crate-foreign-types \
bundled-rust-crate-foreign-types-shared \
bundled-rust-crate-form-urlencoded \
bundled-rust-crate-fs-extra \
bundled-rust-crate-getrandom \
bundled-rust-crate-gif \
bundled-rust-crate-glidesort \
bundled-rust-crate-glifo \
bundled-rust-crate-guillotiere \
bundled-rust-crate-half \
bundled-rust-crate-hashbrown \
bundled-rust-crate-hayagriva \
bundled-rust-crate-hayro \
bundled-rust-crate-hayro-ccitt \
bundled-rust-crate-hayro-cmap \
bundled-rust-crate-hayro-interpret \
bundled-rust-crate-hayro-jbig2 \
bundled-rust-crate-hayro-jpeg2000 \
bundled-rust-crate-hayro-postscript \
bundled-rust-crate-hayro-svg \
bundled-rust-crate-hayro-syntax \
bundled-rust-crate-hayro-write \
bundled-rust-crate-heck \
bundled-rust-crate-httpdate \
bundled-rust-crate-hypher \
bundled-rust-crate-iana-time-zone \
bundled-rust-crate-icu-collator \
bundled-rust-crate-icu-collator-data \
bundled-rust-crate-icu-collections \
bundled-rust-crate-icu-locale \
bundled-rust-crate-icu-locale-core \
bundled-rust-crate-icu-locale-data \
bundled-rust-crate-icu-normalizer \
bundled-rust-crate-icu-normalizer-data \
bundled-rust-crate-icu-properties \
bundled-rust-crate-icu-properties-data \
bundled-rust-crate-icu-provider \
bundled-rust-crate-icu-provider-blob \
bundled-rust-crate-icu-segmenter \
bundled-rust-crate-icu-segmenter-data \
bundled-rust-crate-idna \
bundled-rust-crate-idna-adapter \
bundled-rust-crate-image \
bundled-rust-crate-image-webp \
bundled-rust-crate-imagesize \
bundled-rust-crate-indexmap \
bundled-rust-crate-infer \
bundled-rust-crate-inotify \
bundled-rust-crate-inotify-sys \
bundled-rust-crate-is-docker \
bundled-rust-crate-is-terminal-polyfill \
bundled-rust-crate-is-wsl \
bundled-rust-crate-itoa \
bundled-rust-crate-jobserver \
bundled-rust-crate-kamadak-exif \
bundled-rust-crate-krilla \
bundled-rust-crate-krilla-svg \
bundled-rust-crate-kurbo \
bundled-rust-crate-libc \
bundled-rust-crate-libm \
bundled-rust-crate-libz-rs-sys \
bundled-rust-crate-linebender-resource-handle \
bundled-rust-crate-linked-hash-map \
bundled-rust-crate-linux-raw-sys \
bundled-rust-crate-lipsum \
bundled-rust-crate-litemap \
bundled-rust-crate-lock-api \
bundled-rust-crate-log \
bundled-rust-crate-memchr \
bundled-rust-crate-memmap2 \
bundled-rust-crate-minimal-lexical \
bundled-rust-crate-miniz-oxide \
bundled-rust-crate-mio \
bundled-rust-crate-moxcms \
bundled-rust-crate-mutate-once \
bundled-rust-crate-native-tls \
bundled-rust-crate-nom \
bundled-rust-crate-notify \
bundled-rust-crate-notify-types \
bundled-rust-crate-num-bigint \
bundled-rust-crate-num-conv \
bundled-rust-crate-num-integer \
bundled-rust-crate-num-traits \
bundled-rust-crate-once-cell \
bundled-rust-crate-open \
bundled-rust-crate-openssl \
bundled-rust-crate-openssl-macros \
bundled-rust-crate-openssl-probe \
bundled-rust-crate-openssl-sys \
bundled-rust-crate-option-ext \
bundled-rust-crate-palette \
bundled-rust-crate-palette-derive \
bundled-rust-crate-parking-lot \
bundled-rust-crate-parking-lot-core \
bundled-rust-crate-paste \
bundled-rust-crate-pathdiff \
bundled-rust-crate-pdf-writer \
bundled-rust-crate-peniko \
bundled-rust-crate-percent-encoding \
bundled-rust-crate-phf \
bundled-rust-crate-phf-generator \
bundled-rust-crate-phf-macros \
bundled-rust-crate-phf-shared \
bundled-rust-crate-pic-scale \
bundled-rust-crate-pico-args \
bundled-rust-crate-pixglyph \
bundled-rust-crate-pkg-config \
bundled-rust-crate-plist \
bundled-rust-crate-png \
bundled-rust-crate-polycool \
bundled-rust-crate-portable-atomic \
bundled-rust-crate-postcard \
bundled-rust-crate-potential-utf \
bundled-rust-crate-powerfmt \
bundled-rust-crate-ppv-lite86 \
bundled-rust-crate-proc-macro-hack \
bundled-rust-crate-proc-macro2 \
bundled-rust-crate-psm \
bundled-rust-crate-pxfm \
bundled-rust-crate-quick-error \
bundled-rust-crate-quick-xml \
bundled-rust-crate-quote \
bundled-rust-crate-rand \
bundled-rust-crate-rand-chacha \
bundled-rust-crate-rand-core \
bundled-rust-crate-rayon \
bundled-rust-crate-rayon-core \
bundled-rust-crate-read-fonts \
bundled-rust-crate-regex \
bundled-rust-crate-regex-automata \
bundled-rust-crate-regex-syntax \
bundled-rust-crate-resvg \
bundled-rust-crate-rgb \
bundled-rust-crate-roff \
bundled-rust-crate-roman-numerals-rs \
bundled-rust-crate-roxmltree \
bundled-rust-crate-rust-decimal \
bundled-rust-crate-rustc-hash \
bundled-rust-crate-rustix \
bundled-rust-crate-rustybuzz \
bundled-rust-crate-ryu \
bundled-rust-crate-same-file \
bundled-rust-crate-scopeguard \
bundled-rust-crate-semver \
bundled-rust-crate-serde \
bundled-rust-crate-serde-core \
bundled-rust-crate-serde-derive \
bundled-rust-crate-serde-json \
bundled-rust-crate-serde-path-to-error \
bundled-rust-crate-serde-spanned \
bundled-rust-crate-serde-yaml \
bundled-rust-crate-shell-escape \
bundled-rust-crate-shlex \
bundled-rust-crate-sigpipe \
bundled-rust-crate-simd-adler32 \
bundled-rust-crate-simplecss \
bundled-rust-crate-siphasher \
bundled-rust-crate-skrifa \
bundled-rust-crate-slab \
bundled-rust-crate-slotmap \
bundled-rust-crate-smallvec \
bundled-rust-crate-spin \
bundled-rust-crate-stable-deref-trait \
bundled-rust-crate-stacker \
bundled-rust-crate-strict-num \
bundled-rust-crate-strsim \
bundled-rust-crate-strum \
bundled-rust-crate-strum-macros \
bundled-rust-crate-subsetter \
bundled-rust-crate-svgtypes \
bundled-rust-crate-syn \
bundled-rust-crate-synstructure \
bundled-rust-crate-syntect \
bundled-rust-crate-tar \
bundled-rust-crate-tempfile \
bundled-rust-crate-termcolor \
bundled-rust-crate-terminal-size \
bundled-rust-crate-thin-vec \
bundled-rust-crate-thiserror \
bundled-rust-crate-thiserror-impl \
bundled-rust-crate-time \
bundled-rust-crate-time-core \
bundled-rust-crate-time-macros \
bundled-rust-crate-tiny-http \
bundled-rust-crate-tiny-skia \
bundled-rust-crate-tiny-skia-path \
bundled-rust-crate-tinystr \
bundled-rust-crate-tinyvec \
bundled-rust-crate-tinyvec-macros \
bundled-rust-crate-toml \
bundled-rust-crate-toml-datetime \
bundled-rust-crate-toml-edit \
bundled-rust-crate-ttf-parser \
bundled-rust-crate-two-face \
bundled-rust-crate-typed-arena \
bundled-rust-crate-typst \
bundled-rust-crate-typst-assets \
bundled-rust-crate-typst-bundle \
bundled-rust-crate-typst-cli \
bundled-rust-crate-typst-eval \
bundled-rust-crate-typst-html \
bundled-rust-crate-typst-kit \
bundled-rust-crate-typst-layout \
bundled-rust-crate-typst-library \
bundled-rust-crate-typst-macros \
bundled-rust-crate-typst-pdf \
bundled-rust-crate-typst-realize \
bundled-rust-crate-typst-render \
bundled-rust-crate-typst-svg \
bundled-rust-crate-typst-syntax \
bundled-rust-crate-typst-timing \
bundled-rust-crate-typst-utils \
bundled-rust-crate-unic-langid \
bundled-rust-crate-unic-langid-impl \
bundled-rust-crate-unic-langid-macros \
bundled-rust-crate-unic-langid-macros-impl \
bundled-rust-crate-unicode-bidi \
bundled-rust-crate-unicode-bidi-mirroring \
bundled-rust-crate-unicode-ccc \
bundled-rust-crate-unicode-ident \
bundled-rust-crate-unicode-math-class \
bundled-rust-crate-unicode-normalization \
bundled-rust-crate-unicode-properties \
bundled-rust-crate-unicode-script \
bundled-rust-crate-unicode-segmentation \
bundled-rust-crate-unicode-vo \
bundled-rust-crate-unicode-width \
bundled-rust-crate-unsafe-libyaml \
bundled-rust-crate-unscanny \
bundled-rust-crate-ureq \
bundled-rust-crate-url \
bundled-rust-crate-usvg \
bundled-rust-crate-utf16-iter \
bundled-rust-crate-utf8-iter \
bundled-rust-crate-utf8parse \
bundled-rust-crate-vcpkg \
bundled-rust-crate-vello-common \
bundled-rust-crate-vello-cpu \
bundled-rust-crate-version-check \
bundled-rust-crate-walkdir \
bundled-rust-crate-wasmi \
bundled-rust-crate-wasmi-collections \
bundled-rust-crate-wasmi-core \
bundled-rust-crate-wasmi-ir \
bundled-rust-crate-wasmparser \
bundled-rust-crate-weezl \
bundled-rust-crate-winnow \
bundled-rust-crate-write-fonts \
bundled-rust-crate-write16 \
bundled-rust-crate-writeable \
bundled-rust-crate-xattr \
bundled-rust-crate-xmlwriter \
bundled-rust-crate-xmp-writer \
bundled-rust-crate-yaml-rust \
bundled-rust-crate-yoke \
bundled-rust-crate-yoke-derive \
bundled-rust-crate-zerocopy \
bundled-rust-crate-zerocopy-derive \
bundled-rust-crate-zerofrom \
bundled-rust-crate-zerofrom-derive \
bundled-rust-crate-zerotrie \
bundled-rust-crate-zerovec \
bundled-rust-crate-zerovec-derive \
bundled-rust-crate-zlib-rs \
bundled-rust-crate-zune-core \
bundled-rust-crate-zune-jpeg \
typst"

RDEPENDS:${PN} += "libc.so.6 \
libcrypto.so.3 \
libgcc-s.so.1 \
libm.so.6 \
libssl.so.3"

inherit rpm
