SUMMARY = "A CLI tool for code structural search, lint and rewriting"
DESCRIPTION = "ast-grep(sg) is a CLI tool for code structural search, lint, and rewriting."
LICENSE = "MIT"

PV = "0.45.3"

RPM_NAME = "ast-grep-0.45.3-1.1.aarch64.rpm"
RPM_HASH = "fcc1055e0d2c25c5e49d202d7dea0eeed2c04637fd2bd2acd7ca5b4f567b2de4d2458c6b6abe65966be608b02bd141ad7226a639dbacd9eb6312ac701e700a20"

RPROVIDES:${PN} += "ast-grep \
bundled-rust-crate-Inflector \
bundled-rust-crate-aho-corasick \
bundled-rust-crate-ansi-term \
bundled-rust-crate-anstream \
bundled-rust-crate-anstyle \
bundled-rust-crate-anstyle-parse \
bundled-rust-crate-anstyle-query \
bundled-rust-crate-anyhow \
bundled-rust-crate-ast-grep \
bundled-rust-crate-ast-grep-config \
bundled-rust-crate-ast-grep-core \
bundled-rust-crate-ast-grep-dynamic \
bundled-rust-crate-ast-grep-language \
bundled-rust-crate-ast-grep-lsp \
bundled-rust-crate-ast-grep-outline \
bundled-rust-crate-bit-set \
bundled-rust-crate-bit-vec \
bundled-rust-crate-bitflags \
bundled-rust-crate-borrow-or-share \
bundled-rust-crate-borsh \
bundled-rust-crate-borsh-derive \
bundled-rust-crate-bstr \
bundled-rust-crate-bytes \
bundled-rust-crate-cc \
bundled-rust-crate-cfg-aliases \
bundled-rust-crate-cfg-if \
bundled-rust-crate-clap \
bundled-rust-crate-clap-builder \
bundled-rust-crate-clap-complete \
bundled-rust-crate-clap-derive \
bundled-rust-crate-clap-lex \
bundled-rust-crate-codespan-reporting \
bundled-rust-crate-colorchoice \
bundled-rust-crate-convert-case \
bundled-rust-crate-coolor \
bundled-rust-crate-crokey \
bundled-rust-crate-crokey-proc-macros \
bundled-rust-crate-crossbeam \
bundled-rust-crate-crossbeam-channel \
bundled-rust-crate-crossbeam-deque \
bundled-rust-crate-crossbeam-epoch \
bundled-rust-crate-crossbeam-queue \
bundled-rust-crate-crossbeam-utils \
bundled-rust-crate-crossterm \
bundled-rust-crate-dashmap \
bundled-rust-crate-derive-more \
bundled-rust-crate-derive-more-impl \
bundled-rust-crate-document-features \
bundled-rust-crate-dyn-clone \
bundled-rust-crate-equivalent \
bundled-rust-crate-errno \
bundled-rust-crate-find-msvc-tools \
bundled-rust-crate-fluent-uri \
bundled-rust-crate-fnv \
bundled-rust-crate-futures \
bundled-rust-crate-futures-channel \
bundled-rust-crate-futures-core \
bundled-rust-crate-futures-executor \
bundled-rust-crate-futures-io \
bundled-rust-crate-futures-macro \
bundled-rust-crate-futures-sink \
bundled-rust-crate-futures-task \
bundled-rust-crate-futures-util \
bundled-rust-crate-fuzzy-matcher \
bundled-rust-crate-globset \
bundled-rust-crate-hashbrown \
bundled-rust-crate-heck \
bundled-rust-crate-httparse \
bundled-rust-crate-ignore \
bundled-rust-crate-indexmap \
bundled-rust-crate-inquire \
bundled-rust-crate-is-terminal-polyfill \
bundled-rust-crate-itoa \
bundled-rust-crate-lazy-regex \
bundled-rust-crate-lazy-regex-proc-macros \
bundled-rust-crate-lazy-static \
bundled-rust-crate-libc \
bundled-rust-crate-libloading \
bundled-rust-crate-linux-raw-sys \
bundled-rust-crate-litrs \
bundled-rust-crate-lock-api \
bundled-rust-crate-log \
bundled-rust-crate-ls-types \
bundled-rust-crate-matchers \
bundled-rust-crate-memchr \
bundled-rust-crate-minimad \
bundled-rust-crate-mio \
bundled-rust-crate-nix \
bundled-rust-crate-nu-ansi-term \
bundled-rust-crate-once-cell \
bundled-rust-crate-parking-lot \
bundled-rust-crate-parking-lot-core \
bundled-rust-crate-percent-encoding \
bundled-rust-crate-pin-project-lite \
bundled-rust-crate-prettyplease \
bundled-rust-crate-proc-macro-crate \
bundled-rust-crate-proc-macro2 \
bundled-rust-crate-quote \
bundled-rust-crate-ref-cast \
bundled-rust-crate-ref-cast-impl \
bundled-rust-crate-regex \
bundled-rust-crate-regex-automata \
bundled-rust-crate-regex-syntax \
bundled-rust-crate-rustc-version \
bundled-rust-crate-rustix \
bundled-rust-crate-ryu \
bundled-rust-crate-same-file \
bundled-rust-crate-schemafy-core \
bundled-rust-crate-schemafy-lib \
bundled-rust-crate-schemars \
bundled-rust-crate-schemars-derive \
bundled-rust-crate-scopeguard \
bundled-rust-crate-semver \
bundled-rust-crate-serde \
bundled-rust-crate-serde-core \
bundled-rust-crate-serde-derive \
bundled-rust-crate-serde-derive-internals \
bundled-rust-crate-serde-json \
bundled-rust-crate-serde-regex \
bundled-rust-crate-serde-sarif \
bundled-rust-crate-serde-yaml \
bundled-rust-crate-sharded-slab \
bundled-rust-crate-shlex \
bundled-rust-crate-signal-hook \
bundled-rust-crate-signal-hook-mio \
bundled-rust-crate-signal-hook-registry \
bundled-rust-crate-similar \
bundled-rust-crate-slab \
bundled-rust-crate-smallvec \
bundled-rust-crate-streaming-iterator \
bundled-rust-crate-strict \
bundled-rust-crate-strsim \
bundled-rust-crate-strum \
bundled-rust-crate-strum-macros \
bundled-rust-crate-syn \
bundled-rust-crate-sync-wrapper \
bundled-rust-crate-target-triple \
bundled-rust-crate-termcolor \
bundled-rust-crate-termimad \
bundled-rust-crate-terminal-light \
bundled-rust-crate-thiserror \
bundled-rust-crate-thiserror-impl \
bundled-rust-crate-thread-local \
bundled-rust-crate-tokio \
bundled-rust-crate-tokio-macros \
bundled-rust-crate-tokio-util \
bundled-rust-crate-toml-datetime \
bundled-rust-crate-toml-edit \
bundled-rust-crate-toml-parser \
bundled-rust-crate-toml-writer \
bundled-rust-crate-tower \
bundled-rust-crate-tower-layer \
bundled-rust-crate-tower-lsp-server \
bundled-rust-crate-tower-service \
bundled-rust-crate-tracing \
bundled-rust-crate-tracing-attributes \
bundled-rust-crate-tracing-core \
bundled-rust-crate-tracing-log \
bundled-rust-crate-tracing-subscriber \
bundled-rust-crate-tree-sitter \
bundled-rust-crate-tree-sitter-bash \
bundled-rust-crate-tree-sitter-c \
bundled-rust-crate-tree-sitter-c-sharp \
bundled-rust-crate-tree-sitter-cpp \
bundled-rust-crate-tree-sitter-css \
bundled-rust-crate-tree-sitter-dart \
bundled-rust-crate-tree-sitter-elixir \
bundled-rust-crate-tree-sitter-go \
bundled-rust-crate-tree-sitter-haskell \
bundled-rust-crate-tree-sitter-hcl \
bundled-rust-crate-tree-sitter-html \
bundled-rust-crate-tree-sitter-java \
bundled-rust-crate-tree-sitter-javascript \
bundled-rust-crate-tree-sitter-json \
bundled-rust-crate-tree-sitter-kotlin-sg \
bundled-rust-crate-tree-sitter-language \
bundled-rust-crate-tree-sitter-lua \
bundled-rust-crate-tree-sitter-md \
bundled-rust-crate-tree-sitter-nix \
bundled-rust-crate-tree-sitter-php \
bundled-rust-crate-tree-sitter-python \
bundled-rust-crate-tree-sitter-ruby \
bundled-rust-crate-tree-sitter-rust \
bundled-rust-crate-tree-sitter-scala \
bundled-rust-crate-tree-sitter-solidity \
bundled-rust-crate-tree-sitter-swift \
bundled-rust-crate-tree-sitter-typescript \
bundled-rust-crate-tree-sitter-yaml \
bundled-rust-crate-typed-builder \
bundled-rust-crate-typed-builder-macro \
bundled-rust-crate-unicode-ident \
bundled-rust-crate-unicode-segmentation \
bundled-rust-crate-unicode-width \
bundled-rust-crate-unsafe-libyaml \
bundled-rust-crate-uriparse \
bundled-rust-crate-utf8parse \
bundled-rust-crate-walkdir \
bundled-rust-crate-winnow \
bundled-rust-crate-xterm-query \
bundled-rust-crate-zmij"

RDEPENDS:${PN} += "libc.so.6 \
libgcc-s.so.1 \
libm.so.6"

inherit rpm
