SUMMARY = "Include a DVI page into MetaPost output"
DESCRIPTION = "DVItoMP is one of the auxiliary programs available to any \
MetaPost package; it converts a DVI file into a MetaPost file. \
Using it, one can envisage including a DVI page into an EPS \
files generated by MetaPost. Such files allow pages to include \
other pages."
LICENSE = "SUSE-Public-Domain"

PV = "2026.226.1.00svn29349"

RPM_NAME = "texlive-dviincl-2026.226.1.00svn29349-61.4.noarch.rpm"
RPM_HASH = "189fc974422b26cce58046db9290f0ee5e66c6b6bad7ff6333642d1e59ace1d0c5ae53cca6585691bd3b6bbdcff49ec9d8cd2b03603d363a881c6d0272e97044"
REPO_ARCH = "noarch"

RPROVIDES:${PN} += "texlive-dviincl"

RDEPENDS:${PN} += "/usr/bin/sh \
coreutils \
ed \
findutils \
grep \
sed \
texlive \
texlive-filesystem \
texlive-kpathsea \
texlive-kpathsea-bin \
texlive-scripts \
texlive-scripts-bin"

inherit rpm
