SUMMARY = "Kernel firmware files for Intel wireless drivers"
DESCRIPTION = "This package contains kernel firmware files for Intel wireless drivers."
LICENSE = "GPL-2.0-or-later & SUSE-Firmware"

PV = "20260820"

RPM_NAME = "kernel-firmware-iwlwifi-20260820-1.1.noarch.rpm"
RPM_HASH = "3abb45e78b9b776d5b35518b0ac987db5fc3e03ee98f571453a1dd58feed998822c4f4bf02e0fe8ef6e2b2a0a2eba01e463cb13bf4d73d1b7bee55e5a472cbe1"
REPO_ARCH = "noarch"

RPROVIDES:${PN} += "firmware-intel/iwlwifi/iwlwifi-100-5.ucode \
firmware-intel/iwlwifi/iwlwifi-1000-5.ucode \
firmware-intel/iwlwifi/iwlwifi-105-6.ucode \
firmware-intel/iwlwifi/iwlwifi-135-6.ucode \
firmware-intel/iwlwifi/iwlwifi-2000-6.ucode \
firmware-intel/iwlwifi/iwlwifi-2030-6.ucode \
firmware-intel/iwlwifi/iwlwifi-3160-17.ucode \
firmware-intel/iwlwifi/iwlwifi-3168-29.ucode \
firmware-intel/iwlwifi/iwlwifi-3945-2.ucode \
firmware-intel/iwlwifi/iwlwifi-4965-2.ucode \
firmware-intel/iwlwifi/iwlwifi-5000-5.ucode \
firmware-intel/iwlwifi/iwlwifi-5150-2.ucode \
firmware-intel/iwlwifi/iwlwifi-6000-4.ucode \
firmware-intel/iwlwifi/iwlwifi-6000g2a-6.ucode \
firmware-intel/iwlwifi/iwlwifi-6000g2b-6.ucode \
firmware-intel/iwlwifi/iwlwifi-6050-5.ucode \
firmware-intel/iwlwifi/iwlwifi-7260-17.ucode \
firmware-intel/iwlwifi/iwlwifi-7265-17.ucode \
firmware-intel/iwlwifi/iwlwifi-7265D-29.ucode \
firmware-intel/iwlwifi/iwlwifi-8000C-34.ucode \
firmware-intel/iwlwifi/iwlwifi-8000C-36.ucode \
firmware-intel/iwlwifi/iwlwifi-8265-34.ucode \
firmware-intel/iwlwifi/iwlwifi-8265-36.ucode \
firmware-intel/iwlwifi/iwlwifi-9000-pu-b0-jf-b0-34.ucode \
firmware-intel/iwlwifi/iwlwifi-9000-pu-b0-jf-b0-38.ucode \
firmware-intel/iwlwifi/iwlwifi-9000-pu-b0-jf-b0-46.ucode \
firmware-intel/iwlwifi/iwlwifi-9260-th-b0-jf-b0-34.ucode \
firmware-intel/iwlwifi/iwlwifi-9260-th-b0-jf-b0-38.ucode \
firmware-intel/iwlwifi/iwlwifi-9260-th-b0-jf-b0-46.ucode \
firmware-intel/iwlwifi/iwlwifi-Qu-b0-hr-b0-50.ucode \
firmware-intel/iwlwifi/iwlwifi-Qu-b0-hr-b0-59.ucode \
firmware-intel/iwlwifi/iwlwifi-Qu-b0-hr-b0-66.ucode \
firmware-intel/iwlwifi/iwlwifi-Qu-b0-hr-b0-72.ucode \
firmware-intel/iwlwifi/iwlwifi-Qu-b0-hr-b0-73.ucode \
firmware-intel/iwlwifi/iwlwifi-Qu-b0-hr-b0-74.ucode \
firmware-intel/iwlwifi/iwlwifi-Qu-b0-hr-b0-77.ucode \
firmware-intel/iwlwifi/iwlwifi-Qu-b0-jf-b0-50.ucode \
firmware-intel/iwlwifi/iwlwifi-Qu-b0-jf-b0-59.ucode \
firmware-intel/iwlwifi/iwlwifi-Qu-b0-jf-b0-66.ucode \
firmware-intel/iwlwifi/iwlwifi-Qu-b0-jf-b0-72.ucode \
firmware-intel/iwlwifi/iwlwifi-Qu-b0-jf-b0-73.ucode \
firmware-intel/iwlwifi/iwlwifi-Qu-b0-jf-b0-74.ucode \
firmware-intel/iwlwifi/iwlwifi-Qu-b0-jf-b0-77.ucode \
firmware-intel/iwlwifi/iwlwifi-Qu-c0-hr-b0-50.ucode \
firmware-intel/iwlwifi/iwlwifi-Qu-c0-hr-b0-59.ucode \
firmware-intel/iwlwifi/iwlwifi-Qu-c0-hr-b0-66.ucode \
firmware-intel/iwlwifi/iwlwifi-Qu-c0-hr-b0-72.ucode \
firmware-intel/iwlwifi/iwlwifi-Qu-c0-hr-b0-73.ucode \
firmware-intel/iwlwifi/iwlwifi-Qu-c0-hr-b0-74.ucode \
firmware-intel/iwlwifi/iwlwifi-Qu-c0-hr-b0-77.ucode \
firmware-intel/iwlwifi/iwlwifi-Qu-c0-jf-b0-50.ucode \
firmware-intel/iwlwifi/iwlwifi-Qu-c0-jf-b0-59.ucode \
firmware-intel/iwlwifi/iwlwifi-Qu-c0-jf-b0-66.ucode \
firmware-intel/iwlwifi/iwlwifi-Qu-c0-jf-b0-72.ucode \
firmware-intel/iwlwifi/iwlwifi-Qu-c0-jf-b0-73.ucode \
firmware-intel/iwlwifi/iwlwifi-Qu-c0-jf-b0-74.ucode \
firmware-intel/iwlwifi/iwlwifi-Qu-c0-jf-b0-77.ucode \
firmware-intel/iwlwifi/iwlwifi-QuZ-a0-hr-b0-50.ucode \
firmware-intel/iwlwifi/iwlwifi-QuZ-a0-hr-b0-59.ucode \
firmware-intel/iwlwifi/iwlwifi-QuZ-a0-hr-b0-66.ucode \
firmware-intel/iwlwifi/iwlwifi-QuZ-a0-hr-b0-72.ucode \
firmware-intel/iwlwifi/iwlwifi-QuZ-a0-hr-b0-73.ucode \
firmware-intel/iwlwifi/iwlwifi-QuZ-a0-hr-b0-74.ucode \
firmware-intel/iwlwifi/iwlwifi-QuZ-a0-hr-b0-77.ucode \
firmware-intel/iwlwifi/iwlwifi-QuZ-a0-jf-b0-50.ucode \
firmware-intel/iwlwifi/iwlwifi-QuZ-a0-jf-b0-59.ucode \
firmware-intel/iwlwifi/iwlwifi-QuZ-a0-jf-b0-66.ucode \
firmware-intel/iwlwifi/iwlwifi-QuZ-a0-jf-b0-72.ucode \
firmware-intel/iwlwifi/iwlwifi-QuZ-a0-jf-b0-73.ucode \
firmware-intel/iwlwifi/iwlwifi-QuZ-a0-jf-b0-74.ucode \
firmware-intel/iwlwifi/iwlwifi-QuZ-a0-jf-b0-77.ucode \
firmware-intel/iwlwifi/iwlwifi-bz-b0-fm-c0-100.ucode \
firmware-intel/iwlwifi/iwlwifi-bz-b0-fm-c0-101.ucode \
firmware-intel/iwlwifi/iwlwifi-bz-b0-fm-c0-92.ucode \
firmware-intel/iwlwifi/iwlwifi-bz-b0-fm-c0-93.ucode \
firmware-intel/iwlwifi/iwlwifi-bz-b0-fm-c0-94.ucode \
firmware-intel/iwlwifi/iwlwifi-bz-b0-fm-c0-96.ucode \
firmware-intel/iwlwifi/iwlwifi-bz-b0-fm-c0-97.ucode \
firmware-intel/iwlwifi/iwlwifi-bz-b0-fm-c0-98.ucode \
firmware-intel/iwlwifi/iwlwifi-bz-b0-fm-c0-c101.ucode \
firmware-intel/iwlwifi/iwlwifi-bz-b0-fm-c0-c102.ucode \
firmware-intel/iwlwifi/iwlwifi-bz-b0-fm-c0-c103.ucode \
firmware-intel/iwlwifi/iwlwifi-bz-b0-fm-c0-c106.ucode \
firmware-intel/iwlwifi/iwlwifi-bz-b0-fm-c0-c107.ucode \
firmware-intel/iwlwifi/iwlwifi-bz-b0-fm-c0.pnvm \
firmware-intel/iwlwifi/iwlwifi-bz-b0-gf-a0-100.ucode \
firmware-intel/iwlwifi/iwlwifi-bz-b0-gf-a0-92.ucode \
firmware-intel/iwlwifi/iwlwifi-bz-b0-gf-a0-94.ucode \
firmware-intel/iwlwifi/iwlwifi-bz-b0-gf-a0-96.ucode \
firmware-intel/iwlwifi/iwlwifi-bz-b0-gf-a0-97.ucode \
firmware-intel/iwlwifi/iwlwifi-bz-b0-gf-a0-98.ucode \
firmware-intel/iwlwifi/iwlwifi-bz-b0-gf-a0.pnvm \
firmware-intel/iwlwifi/iwlwifi-bz-b0-hr-b0-100.ucode \
firmware-intel/iwlwifi/iwlwifi-bz-b0-hr-b0-93.ucode \
firmware-intel/iwlwifi/iwlwifi-bz-b0-hr-b0-96.ucode \
firmware-intel/iwlwifi/iwlwifi-bz-b0-hr-b0-98.ucode \
firmware-intel/iwlwifi/iwlwifi-bz-b0-hr-b0.pnvm \
firmware-intel/iwlwifi/iwlwifi-bz-b0-wh-b0-c102.ucode \
firmware-intel/iwlwifi/iwlwifi-bz-b0-wh-b0-c103.ucode \
firmware-intel/iwlwifi/iwlwifi-bz-b0-wh-b0-c106.ucode \
firmware-intel/iwlwifi/iwlwifi-bz-b0-wh-b0-c107.ucode \
firmware-intel/iwlwifi/iwlwifi-cc-a0-50.ucode \
firmware-intel/iwlwifi/iwlwifi-cc-a0-59.ucode \
firmware-intel/iwlwifi/iwlwifi-cc-a0-66.ucode \
firmware-intel/iwlwifi/iwlwifi-cc-a0-72.ucode \
firmware-intel/iwlwifi/iwlwifi-cc-a0-73.ucode \
firmware-intel/iwlwifi/iwlwifi-cc-a0-74.ucode \
firmware-intel/iwlwifi/iwlwifi-cc-a0-77.ucode \
firmware-intel/iwlwifi/iwlwifi-gl-c0-fm-c0-100.ucode \
firmware-intel/iwlwifi/iwlwifi-gl-c0-fm-c0-101.ucode \
firmware-intel/iwlwifi/iwlwifi-gl-c0-fm-c0-83.ucode \
firmware-intel/iwlwifi/iwlwifi-gl-c0-fm-c0-86.ucode \
firmware-intel/iwlwifi/iwlwifi-gl-c0-fm-c0-90.ucode \
firmware-intel/iwlwifi/iwlwifi-gl-c0-fm-c0-92.ucode \
firmware-intel/iwlwifi/iwlwifi-gl-c0-fm-c0-94.ucode \
firmware-intel/iwlwifi/iwlwifi-gl-c0-fm-c0-96.ucode \
firmware-intel/iwlwifi/iwlwifi-gl-c0-fm-c0-97.ucode \
firmware-intel/iwlwifi/iwlwifi-gl-c0-fm-c0-98.ucode \
firmware-intel/iwlwifi/iwlwifi-gl-c0-fm-c0-c101.ucode \
firmware-intel/iwlwifi/iwlwifi-gl-c0-fm-c0-c102.ucode \
firmware-intel/iwlwifi/iwlwifi-gl-c0-fm-c0-c103.ucode \
firmware-intel/iwlwifi/iwlwifi-gl-c0-fm-c0-c106.ucode \
firmware-intel/iwlwifi/iwlwifi-gl-c0-fm-c0-c107.ucode \
firmware-intel/iwlwifi/iwlwifi-gl-c0-fm-c0.pnvm \
firmware-intel/iwlwifi/iwlwifi-ma-b0-gf-a0-83.ucode \
firmware-intel/iwlwifi/iwlwifi-ma-b0-gf-a0-86.ucode \
firmware-intel/iwlwifi/iwlwifi-ma-b0-gf-a0-89.ucode \
firmware-intel/iwlwifi/iwlwifi-ma-b0-gf-a0.pnvm \
firmware-intel/iwlwifi/iwlwifi-ma-b0-gf4-a0-83.ucode \
firmware-intel/iwlwifi/iwlwifi-ma-b0-gf4-a0-86.ucode \
firmware-intel/iwlwifi/iwlwifi-ma-b0-gf4-a0-89.ucode \
firmware-intel/iwlwifi/iwlwifi-ma-b0-gf4-a0.pnvm \
firmware-intel/iwlwifi/iwlwifi-ma-b0-hr-b0-83.ucode \
firmware-intel/iwlwifi/iwlwifi-ma-b0-hr-b0-86.ucode \
firmware-intel/iwlwifi/iwlwifi-ma-b0-hr-b0-89.ucode \
firmware-intel/iwlwifi/iwlwifi-sc-a0-fm-c0-c101.ucode \
firmware-intel/iwlwifi/iwlwifi-sc-a0-fm-c0-c102.ucode \
firmware-intel/iwlwifi/iwlwifi-sc-a0-fm-c0-c103.ucode \
firmware-intel/iwlwifi/iwlwifi-sc-a0-fm-c0-c106.ucode \
firmware-intel/iwlwifi/iwlwifi-sc-a0-fm-c0-c107.ucode \
firmware-intel/iwlwifi/iwlwifi-sc-a0-gf-a0-100.ucode \
firmware-intel/iwlwifi/iwlwifi-sc-a0-wh-b0-101.ucode \
firmware-intel/iwlwifi/iwlwifi-sc-a0-wh-b0-c101.ucode \
firmware-intel/iwlwifi/iwlwifi-sc-a0-wh-b0-c102.ucode \
firmware-intel/iwlwifi/iwlwifi-sc-a0-wh-b0-c103.ucode \
firmware-intel/iwlwifi/iwlwifi-sc-a0-wh-b0-c106.ucode \
firmware-intel/iwlwifi/iwlwifi-sc-a0-wh-b0-c107.ucode \
firmware-intel/iwlwifi/iwlwifi-so-a0-gf-a0-72.ucode \
firmware-intel/iwlwifi/iwlwifi-so-a0-gf-a0-73.ucode \
firmware-intel/iwlwifi/iwlwifi-so-a0-gf-a0-74.ucode \
firmware-intel/iwlwifi/iwlwifi-so-a0-gf-a0-77.ucode \
firmware-intel/iwlwifi/iwlwifi-so-a0-gf-a0-78.ucode \
firmware-intel/iwlwifi/iwlwifi-so-a0-gf-a0-79.ucode \
firmware-intel/iwlwifi/iwlwifi-so-a0-gf-a0-81.ucode \
firmware-intel/iwlwifi/iwlwifi-so-a0-gf-a0-83.ucode \
firmware-intel/iwlwifi/iwlwifi-so-a0-gf-a0-84.ucode \
firmware-intel/iwlwifi/iwlwifi-so-a0-gf-a0-86.ucode \
firmware-intel/iwlwifi/iwlwifi-so-a0-gf-a0-89.ucode \
firmware-intel/iwlwifi/iwlwifi-so-a0-gf-a0.pnvm \
firmware-intel/iwlwifi/iwlwifi-so-a0-gf4-a0-72.ucode \
firmware-intel/iwlwifi/iwlwifi-so-a0-gf4-a0-73.ucode \
firmware-intel/iwlwifi/iwlwifi-so-a0-gf4-a0-74.ucode \
firmware-intel/iwlwifi/iwlwifi-so-a0-gf4-a0-77.ucode \
firmware-intel/iwlwifi/iwlwifi-so-a0-gf4-a0-78.ucode \
firmware-intel/iwlwifi/iwlwifi-so-a0-gf4-a0-79.ucode \
firmware-intel/iwlwifi/iwlwifi-so-a0-gf4-a0-81.ucode \
firmware-intel/iwlwifi/iwlwifi-so-a0-gf4-a0-83.ucode \
firmware-intel/iwlwifi/iwlwifi-so-a0-gf4-a0-84.ucode \
firmware-intel/iwlwifi/iwlwifi-so-a0-gf4-a0-86.ucode \
firmware-intel/iwlwifi/iwlwifi-so-a0-gf4-a0-89.ucode \
firmware-intel/iwlwifi/iwlwifi-so-a0-gf4-a0.pnvm \
firmware-intel/iwlwifi/iwlwifi-so-a0-hr-b0-72.ucode \
firmware-intel/iwlwifi/iwlwifi-so-a0-hr-b0-73.ucode \
firmware-intel/iwlwifi/iwlwifi-so-a0-hr-b0-74.ucode \
firmware-intel/iwlwifi/iwlwifi-so-a0-hr-b0-77.ucode \
firmware-intel/iwlwifi/iwlwifi-so-a0-hr-b0-79.ucode \
firmware-intel/iwlwifi/iwlwifi-so-a0-hr-b0-81.ucode \
firmware-intel/iwlwifi/iwlwifi-so-a0-hr-b0-83.ucode \
firmware-intel/iwlwifi/iwlwifi-so-a0-hr-b0-84.ucode \
firmware-intel/iwlwifi/iwlwifi-so-a0-hr-b0-86.ucode \
firmware-intel/iwlwifi/iwlwifi-so-a0-hr-b0-89.ucode \
firmware-intel/iwlwifi/iwlwifi-so-a0-jf-b0-72.ucode \
firmware-intel/iwlwifi/iwlwifi-so-a0-jf-b0-73.ucode \
firmware-intel/iwlwifi/iwlwifi-so-a0-jf-b0-74.ucode \
firmware-intel/iwlwifi/iwlwifi-so-a0-jf-b0-77.ucode \
firmware-intel/iwlwifi/iwlwifi-ty-a0-gf-a0-59.ucode \
firmware-intel/iwlwifi/iwlwifi-ty-a0-gf-a0-66.ucode \
firmware-intel/iwlwifi/iwlwifi-ty-a0-gf-a0-72.ucode \
firmware-intel/iwlwifi/iwlwifi-ty-a0-gf-a0-73.ucode \
firmware-intel/iwlwifi/iwlwifi-ty-a0-gf-a0-74.ucode \
firmware-intel/iwlwifi/iwlwifi-ty-a0-gf-a0-77.ucode \
firmware-intel/iwlwifi/iwlwifi-ty-a0-gf-a0-78.ucode \
firmware-intel/iwlwifi/iwlwifi-ty-a0-gf-a0-79.ucode \
firmware-intel/iwlwifi/iwlwifi-ty-a0-gf-a0-81.ucode \
firmware-intel/iwlwifi/iwlwifi-ty-a0-gf-a0-83.ucode \
firmware-intel/iwlwifi/iwlwifi-ty-a0-gf-a0-84.ucode \
firmware-intel/iwlwifi/iwlwifi-ty-a0-gf-a0-86.ucode \
firmware-intel/iwlwifi/iwlwifi-ty-a0-gf-a0-89.ucode \
firmware-intel/iwlwifi/iwlwifi-ty-a0-gf-a0.pnvm \
firmware-iwlwifi-100-5.ucode \
firmware-iwlwifi-1000-5.ucode \
firmware-iwlwifi-105-6.ucode \
firmware-iwlwifi-135-6.ucode \
firmware-iwlwifi-2000-6.ucode \
firmware-iwlwifi-2030-6.ucode \
firmware-iwlwifi-3160-17.ucode \
firmware-iwlwifi-3168-29.ucode \
firmware-iwlwifi-3945-2.ucode \
firmware-iwlwifi-4965-2.ucode \
firmware-iwlwifi-5000-5.ucode \
firmware-iwlwifi-5150-2.ucode \
firmware-iwlwifi-6000-4.ucode \
firmware-iwlwifi-6000g2a-6.ucode \
firmware-iwlwifi-6000g2b-6.ucode \
firmware-iwlwifi-6050-5.ucode \
firmware-iwlwifi-7260-17.ucode \
firmware-iwlwifi-7265-17.ucode \
firmware-iwlwifi-7265D-29.ucode \
firmware-iwlwifi-8000C-34.ucode \
firmware-iwlwifi-8000C-36.ucode \
firmware-iwlwifi-8265-34.ucode \
firmware-iwlwifi-8265-36.ucode \
firmware-iwlwifi-9000-pu-b0-jf-b0-34.ucode \
firmware-iwlwifi-9000-pu-b0-jf-b0-38.ucode \
firmware-iwlwifi-9000-pu-b0-jf-b0-46.ucode \
firmware-iwlwifi-9260-th-b0-jf-b0-34.ucode \
firmware-iwlwifi-9260-th-b0-jf-b0-38.ucode \
firmware-iwlwifi-9260-th-b0-jf-b0-46.ucode \
firmware-iwlwifi-Qu-b0-hr-b0-50.ucode \
firmware-iwlwifi-Qu-b0-hr-b0-59.ucode \
firmware-iwlwifi-Qu-b0-hr-b0-66.ucode \
firmware-iwlwifi-Qu-b0-hr-b0-72.ucode \
firmware-iwlwifi-Qu-b0-hr-b0-73.ucode \
firmware-iwlwifi-Qu-b0-hr-b0-74.ucode \
firmware-iwlwifi-Qu-b0-hr-b0-77.ucode \
firmware-iwlwifi-Qu-b0-jf-b0-50.ucode \
firmware-iwlwifi-Qu-b0-jf-b0-59.ucode \
firmware-iwlwifi-Qu-b0-jf-b0-66.ucode \
firmware-iwlwifi-Qu-b0-jf-b0-72.ucode \
firmware-iwlwifi-Qu-b0-jf-b0-73.ucode \
firmware-iwlwifi-Qu-b0-jf-b0-74.ucode \
firmware-iwlwifi-Qu-b0-jf-b0-77.ucode \
firmware-iwlwifi-Qu-c0-hr-b0-50.ucode \
firmware-iwlwifi-Qu-c0-hr-b0-59.ucode \
firmware-iwlwifi-Qu-c0-hr-b0-66.ucode \
firmware-iwlwifi-Qu-c0-hr-b0-72.ucode \
firmware-iwlwifi-Qu-c0-hr-b0-73.ucode \
firmware-iwlwifi-Qu-c0-hr-b0-74.ucode \
firmware-iwlwifi-Qu-c0-hr-b0-77.ucode \
firmware-iwlwifi-Qu-c0-jf-b0-50.ucode \
firmware-iwlwifi-Qu-c0-jf-b0-59.ucode \
firmware-iwlwifi-Qu-c0-jf-b0-66.ucode \
firmware-iwlwifi-Qu-c0-jf-b0-72.ucode \
firmware-iwlwifi-Qu-c0-jf-b0-73.ucode \
firmware-iwlwifi-Qu-c0-jf-b0-74.ucode \
firmware-iwlwifi-Qu-c0-jf-b0-77.ucode \
firmware-iwlwifi-QuZ-a0-hr-b0-50.ucode \
firmware-iwlwifi-QuZ-a0-hr-b0-59.ucode \
firmware-iwlwifi-QuZ-a0-hr-b0-66.ucode \
firmware-iwlwifi-QuZ-a0-hr-b0-72.ucode \
firmware-iwlwifi-QuZ-a0-hr-b0-73.ucode \
firmware-iwlwifi-QuZ-a0-hr-b0-74.ucode \
firmware-iwlwifi-QuZ-a0-hr-b0-77.ucode \
firmware-iwlwifi-QuZ-a0-jf-b0-50.ucode \
firmware-iwlwifi-QuZ-a0-jf-b0-59.ucode \
firmware-iwlwifi-QuZ-a0-jf-b0-66.ucode \
firmware-iwlwifi-QuZ-a0-jf-b0-72.ucode \
firmware-iwlwifi-QuZ-a0-jf-b0-73.ucode \
firmware-iwlwifi-QuZ-a0-jf-b0-74.ucode \
firmware-iwlwifi-QuZ-a0-jf-b0-77.ucode \
firmware-iwlwifi-bz-b0-fm-c0-100.ucode \
firmware-iwlwifi-bz-b0-fm-c0-101.ucode \
firmware-iwlwifi-bz-b0-fm-c0-92.ucode \
firmware-iwlwifi-bz-b0-fm-c0-93.ucode \
firmware-iwlwifi-bz-b0-fm-c0-94.ucode \
firmware-iwlwifi-bz-b0-fm-c0-96.ucode \
firmware-iwlwifi-bz-b0-fm-c0-97.ucode \
firmware-iwlwifi-bz-b0-fm-c0-98.ucode \
firmware-iwlwifi-bz-b0-fm-c0-c101.ucode \
firmware-iwlwifi-bz-b0-fm-c0-c102.ucode \
firmware-iwlwifi-bz-b0-fm-c0-c103.ucode \
firmware-iwlwifi-bz-b0-fm-c0-c106.ucode \
firmware-iwlwifi-bz-b0-fm-c0-c107.ucode \
firmware-iwlwifi-bz-b0-fm-c0.pnvm \
firmware-iwlwifi-bz-b0-gf-a0-100.ucode \
firmware-iwlwifi-bz-b0-gf-a0-92.ucode \
firmware-iwlwifi-bz-b0-gf-a0-94.ucode \
firmware-iwlwifi-bz-b0-gf-a0-96.ucode \
firmware-iwlwifi-bz-b0-gf-a0-97.ucode \
firmware-iwlwifi-bz-b0-gf-a0-98.ucode \
firmware-iwlwifi-bz-b0-gf-a0.pnvm \
firmware-iwlwifi-bz-b0-hr-b0-100.ucode \
firmware-iwlwifi-bz-b0-hr-b0-93.ucode \
firmware-iwlwifi-bz-b0-hr-b0-96.ucode \
firmware-iwlwifi-bz-b0-hr-b0-98.ucode \
firmware-iwlwifi-bz-b0-hr-b0.pnvm \
firmware-iwlwifi-bz-b0-wh-b0-c102.ucode \
firmware-iwlwifi-bz-b0-wh-b0-c103.ucode \
firmware-iwlwifi-bz-b0-wh-b0-c106.ucode \
firmware-iwlwifi-bz-b0-wh-b0-c107.ucode \
firmware-iwlwifi-cc-a0-50.ucode \
firmware-iwlwifi-cc-a0-59.ucode \
firmware-iwlwifi-cc-a0-66.ucode \
firmware-iwlwifi-cc-a0-72.ucode \
firmware-iwlwifi-cc-a0-73.ucode \
firmware-iwlwifi-cc-a0-74.ucode \
firmware-iwlwifi-cc-a0-77.ucode \
firmware-iwlwifi-gl-c0-fm-c0-100.ucode \
firmware-iwlwifi-gl-c0-fm-c0-101.ucode \
firmware-iwlwifi-gl-c0-fm-c0-83.ucode \
firmware-iwlwifi-gl-c0-fm-c0-86.ucode \
firmware-iwlwifi-gl-c0-fm-c0-90.ucode \
firmware-iwlwifi-gl-c0-fm-c0-92.ucode \
firmware-iwlwifi-gl-c0-fm-c0-94.ucode \
firmware-iwlwifi-gl-c0-fm-c0-96.ucode \
firmware-iwlwifi-gl-c0-fm-c0-97.ucode \
firmware-iwlwifi-gl-c0-fm-c0-98.ucode \
firmware-iwlwifi-gl-c0-fm-c0-c101.ucode \
firmware-iwlwifi-gl-c0-fm-c0-c102.ucode \
firmware-iwlwifi-gl-c0-fm-c0-c103.ucode \
firmware-iwlwifi-gl-c0-fm-c0-c106.ucode \
firmware-iwlwifi-gl-c0-fm-c0-c107.ucode \
firmware-iwlwifi-gl-c0-fm-c0.pnvm \
firmware-iwlwifi-ma-b0-gf-a0-83.ucode \
firmware-iwlwifi-ma-b0-gf-a0-86.ucode \
firmware-iwlwifi-ma-b0-gf-a0-89.ucode \
firmware-iwlwifi-ma-b0-gf-a0.pnvm \
firmware-iwlwifi-ma-b0-gf4-a0-83.ucode \
firmware-iwlwifi-ma-b0-gf4-a0-86.ucode \
firmware-iwlwifi-ma-b0-gf4-a0-89.ucode \
firmware-iwlwifi-ma-b0-gf4-a0.pnvm \
firmware-iwlwifi-ma-b0-hr-b0-83.ucode \
firmware-iwlwifi-ma-b0-hr-b0-86.ucode \
firmware-iwlwifi-ma-b0-hr-b0-89.ucode \
firmware-iwlwifi-sc-a0-fm-c0-c101.ucode \
firmware-iwlwifi-sc-a0-fm-c0-c102.ucode \
firmware-iwlwifi-sc-a0-fm-c0-c103.ucode \
firmware-iwlwifi-sc-a0-fm-c0-c106.ucode \
firmware-iwlwifi-sc-a0-fm-c0-c107.ucode \
firmware-iwlwifi-sc-a0-gf-a0-100.ucode \
firmware-iwlwifi-sc-a0-wh-b0-101.ucode \
firmware-iwlwifi-sc-a0-wh-b0-c101.ucode \
firmware-iwlwifi-sc-a0-wh-b0-c102.ucode \
firmware-iwlwifi-sc-a0-wh-b0-c103.ucode \
firmware-iwlwifi-sc-a0-wh-b0-c106.ucode \
firmware-iwlwifi-sc-a0-wh-b0-c107.ucode \
firmware-iwlwifi-so-a0-gf-a0-72.ucode \
firmware-iwlwifi-so-a0-gf-a0-73.ucode \
firmware-iwlwifi-so-a0-gf-a0-74.ucode \
firmware-iwlwifi-so-a0-gf-a0-77.ucode \
firmware-iwlwifi-so-a0-gf-a0-78.ucode \
firmware-iwlwifi-so-a0-gf-a0-79.ucode \
firmware-iwlwifi-so-a0-gf-a0-81.ucode \
firmware-iwlwifi-so-a0-gf-a0-83.ucode \
firmware-iwlwifi-so-a0-gf-a0-84.ucode \
firmware-iwlwifi-so-a0-gf-a0-86.ucode \
firmware-iwlwifi-so-a0-gf-a0-89.ucode \
firmware-iwlwifi-so-a0-gf-a0.pnvm \
firmware-iwlwifi-so-a0-gf4-a0-72.ucode \
firmware-iwlwifi-so-a0-gf4-a0-73.ucode \
firmware-iwlwifi-so-a0-gf4-a0-74.ucode \
firmware-iwlwifi-so-a0-gf4-a0-77.ucode \
firmware-iwlwifi-so-a0-gf4-a0-78.ucode \
firmware-iwlwifi-so-a0-gf4-a0-79.ucode \
firmware-iwlwifi-so-a0-gf4-a0-81.ucode \
firmware-iwlwifi-so-a0-gf4-a0-83.ucode \
firmware-iwlwifi-so-a0-gf4-a0-84.ucode \
firmware-iwlwifi-so-a0-gf4-a0-86.ucode \
firmware-iwlwifi-so-a0-gf4-a0-89.ucode \
firmware-iwlwifi-so-a0-gf4-a0.pnvm \
firmware-iwlwifi-so-a0-hr-b0-72.ucode \
firmware-iwlwifi-so-a0-hr-b0-73.ucode \
firmware-iwlwifi-so-a0-hr-b0-74.ucode \
firmware-iwlwifi-so-a0-hr-b0-77.ucode \
firmware-iwlwifi-so-a0-hr-b0-79.ucode \
firmware-iwlwifi-so-a0-hr-b0-81.ucode \
firmware-iwlwifi-so-a0-hr-b0-83.ucode \
firmware-iwlwifi-so-a0-hr-b0-84.ucode \
firmware-iwlwifi-so-a0-hr-b0-86.ucode \
firmware-iwlwifi-so-a0-hr-b0-89.ucode \
firmware-iwlwifi-so-a0-jf-b0-72.ucode \
firmware-iwlwifi-so-a0-jf-b0-73.ucode \
firmware-iwlwifi-so-a0-jf-b0-74.ucode \
firmware-iwlwifi-so-a0-jf-b0-77.ucode \
firmware-iwlwifi-ty-a0-gf-a0-59.ucode \
firmware-iwlwifi-ty-a0-gf-a0-66.ucode \
firmware-iwlwifi-ty-a0-gf-a0-72.ucode \
firmware-iwlwifi-ty-a0-gf-a0-73.ucode \
firmware-iwlwifi-ty-a0-gf-a0-74.ucode \
firmware-iwlwifi-ty-a0-gf-a0-77.ucode \
firmware-iwlwifi-ty-a0-gf-a0-78.ucode \
firmware-iwlwifi-ty-a0-gf-a0-79.ucode \
firmware-iwlwifi-ty-a0-gf-a0-81.ucode \
firmware-iwlwifi-ty-a0-gf-a0-83.ucode \
firmware-iwlwifi-ty-a0-gf-a0-84.ucode \
firmware-iwlwifi-ty-a0-gf-a0-86.ucode \
firmware-iwlwifi-ty-a0-gf-a0-89.ucode \
firmware-iwlwifi-ty-a0-gf-a0.pnvm \
iwl100-ucode \
iwl1000-ucode \
iwl3945-ucode \
iwl4965-ucode \
iwl5000-ucode \
iwl5150-ucode \
iwl6000-ucode \
iwl6000g2-ucode \
iwl6050-ucode \
kernel-firmware-iwlwifi"

RDEPENDS:${PN} += "/usr/bin/mkdir \
/usr/bin/sh \
/usr/bin/touch \
dracut"

inherit rpm
