SUMMARY = "Lua Documentation for lpeg"
DESCRIPTION = "Documentation and examples included with the library, sometimes \
generated by luadoc or ldoc."
LICENSE = "MIT"

PV = "1.1.0"

RPM_NAME = "lua53-lpeg-doc-1.1.0-3.4.noarch.rpm"
RPM_HASH = "91012c0a65ab73e02034fa1e700db6e886c1e5f9de7ba90f80f069c8894fc0a1b11b53230a298c5123817984db5326e537c90f30a99a6db0f6d09845862fccf3"
REPO_ARCH = "noarch"

RPROVIDES:${PN} += "lua53-lpeg-doc"

RDEPENDS:${PN} += "lua53-lpeg"

inherit rpm
