SUMMARY = "A simple Django application to demonstrate RRD plots"
DESCRIPTION = "django-collectd-rest is a simple Django application to demonstrate RRD plots generated by collectd or any other rrd data. \
The application is built on top of django-rest-framework and provides REST API to access the plots."
LICENSE = "BSD-2-Clause"

PV = "0.2.6"

RPM_NAME = "python313-django-collectd-rest-0.2.6-1.10.aarch64.rpm"
RPM_HASH = "22fad1cb36ef0675ffe2275fe0f11a852a8364363636229aa37815648ec8ec5c74a345892863a17c2fe278090df92ff6fcf9f19415dd3f5c2c386b3f86dcb353"

RPROVIDES:${PN} += "python3-django-collectd-rest \
python3.13dist-django-collectd-rest \
python313-django-collectd-rest \
python3dist-django-collectd-rest"

RDEPENDS:${PN} += "libc.so.6 \
librrd.so.8 \
python-abi \
python313-djangorestframework \
rrdtool"

inherit rpm
