SUMMARY = "A GPU-accelerated terminal emulator"
DESCRIPTION = "Alacritty is a terminal emulator written in Rust that leverages the GPU for \
rendering."
LICENSE = "Apache-2.0"

PV = "0.17.0"

RPM_NAME = "alacritty-0.17.0-1.5.aarch64.rpm"
RPM_HASH = "15966ce6b4a860595ac50b09f565f01b7b6f9160d54c4b2704523877aa45229cd1bf5c4d5bd98ce873fa54efc7cb904ae633dd44df45fe2e4ea5034b67fff088"

RPROVIDES:${PN} += "alacritty \
bundled-rust-crate-adler2 \
bundled-rust-crate-ahash \
bundled-rust-crate-aho-corasick \
bundled-rust-crate-alacritty \
bundled-rust-crate-alacritty-config \
bundled-rust-crate-alacritty-config-derive \
bundled-rust-crate-alacritty-terminal \
bundled-rust-crate-anstream \
bundled-rust-crate-anstyle \
bundled-rust-crate-anstyle-parse \
bundled-rust-crate-anstyle-query \
bundled-rust-crate-arrayref \
bundled-rust-crate-arrayvec \
bundled-rust-crate-as-raw-xcb-connection \
bundled-rust-crate-base64 \
bundled-rust-crate-bitflags \
bundled-rust-crate-bytemuck \
bundled-rust-crate-calloop \
bundled-rust-crate-calloop-wayland-source \
bundled-rust-crate-cc \
bundled-rust-crate-cfg-aliases \
bundled-rust-crate-cfg-if \
bundled-rust-crate-clap \
bundled-rust-crate-clap-builder \
bundled-rust-crate-clap-derive \
bundled-rust-crate-clap-lex \
bundled-rust-crate-colorchoice \
bundled-rust-crate-copypasta \
bundled-rust-crate-crc32fast \
bundled-rust-crate-crossfont \
bundled-rust-crate-cstr \
bundled-rust-crate-cursor-icon \
bundled-rust-crate-dlib \
bundled-rust-crate-downcast-rs \
bundled-rust-crate-dpi \
bundled-rust-crate-equivalent \
bundled-rust-crate-errno \
bundled-rust-crate-fastrand \
bundled-rust-crate-fdeflate \
bundled-rust-crate-find-msvc-tools \
bundled-rust-crate-flate2 \
bundled-rust-crate-foreign-types \
bundled-rust-crate-foreign-types-macros \
bundled-rust-crate-foreign-types-shared \
bundled-rust-crate-freetype-rs \
bundled-rust-crate-freetype-sys \
bundled-rust-crate-gethostname \
bundled-rust-crate-getrandom \
bundled-rust-crate-gl-generator \
bundled-rust-crate-glutin \
bundled-rust-crate-glutin-egl-sys \
bundled-rust-crate-glutin-glx-sys \
bundled-rust-crate-hashbrown \
bundled-rust-crate-heck \
bundled-rust-crate-home \
bundled-rust-crate-indexmap \
bundled-rust-crate-inotify \
bundled-rust-crate-inotify-sys \
bundled-rust-crate-is-terminal-polyfill \
bundled-rust-crate-itoa \
bundled-rust-crate-jobserver \
bundled-rust-crate-khronos-api \
bundled-rust-crate-libc \
bundled-rust-crate-libloading \
bundled-rust-crate-linux-raw-sys \
bundled-rust-crate-lock-api \
bundled-rust-crate-log \
bundled-rust-crate-memchr \
bundled-rust-crate-memmap2 \
bundled-rust-crate-miniz-oxide \
bundled-rust-crate-mio \
bundled-rust-crate-notify \
bundled-rust-crate-notify-types \
bundled-rust-crate-once-cell \
bundled-rust-crate-parking-lot \
bundled-rust-crate-parking-lot-core \
bundled-rust-crate-percent-encoding \
bundled-rust-crate-pin-project-lite \
bundled-rust-crate-pkg-config \
bundled-rust-crate-png \
bundled-rust-crate-polling \
bundled-rust-crate-proc-macro2 \
bundled-rust-crate-quick-xml \
bundled-rust-crate-quote \
bundled-rust-crate-raw-window-handle \
bundled-rust-crate-regex-automata \
bundled-rust-crate-regex-syntax \
bundled-rust-crate-rustix \
bundled-rust-crate-rustix-openpty \
bundled-rust-crate-ryu \
bundled-rust-crate-same-file \
bundled-rust-crate-scoped-tls \
bundled-rust-crate-scopeguard \
bundled-rust-crate-sctk-adwaita \
bundled-rust-crate-serde \
bundled-rust-crate-serde-core \
bundled-rust-crate-serde-derive \
bundled-rust-crate-serde-json \
bundled-rust-crate-serde-spanned \
bundled-rust-crate-serde-yaml \
bundled-rust-crate-shlex \
bundled-rust-crate-signal-hook \
bundled-rust-crate-signal-hook-registry \
bundled-rust-crate-simd-adler32 \
bundled-rust-crate-slab \
bundled-rust-crate-smallvec \
bundled-rust-crate-smithay-client-toolkit \
bundled-rust-crate-smithay-clipboard \
bundled-rust-crate-smol-str \
bundled-rust-crate-strict-num \
bundled-rust-crate-strsim \
bundled-rust-crate-syn \
bundled-rust-crate-tempfile \
bundled-rust-crate-thiserror \
bundled-rust-crate-thiserror-impl \
bundled-rust-crate-tiny-skia \
bundled-rust-crate-tiny-skia-path \
bundled-rust-crate-toml \
bundled-rust-crate-toml-datetime \
bundled-rust-crate-toml-edit \
bundled-rust-crate-toml-parser \
bundled-rust-crate-toml-writer \
bundled-rust-crate-tracing \
bundled-rust-crate-tracing-core \
bundled-rust-crate-unicode-ident \
bundled-rust-crate-unicode-width \
bundled-rust-crate-unsafe-libyaml \
bundled-rust-crate-utf8parse \
bundled-rust-crate-version-check \
bundled-rust-crate-vte \
bundled-rust-crate-walkdir \
bundled-rust-crate-wayland-backend \
bundled-rust-crate-wayland-client \
bundled-rust-crate-wayland-csd-frame \
bundled-rust-crate-wayland-cursor \
bundled-rust-crate-wayland-protocols \
bundled-rust-crate-wayland-protocols-experimental \
bundled-rust-crate-wayland-protocols-misc \
bundled-rust-crate-wayland-protocols-plasma \
bundled-rust-crate-wayland-protocols-wlr \
bundled-rust-crate-wayland-scanner \
bundled-rust-crate-wayland-sys \
bundled-rust-crate-winit \
bundled-rust-crate-winnow \
bundled-rust-crate-x11-clipboard \
bundled-rust-crate-x11-dl \
bundled-rust-crate-x11rb \
bundled-rust-crate-x11rb-protocol \
bundled-rust-crate-xcursor \
bundled-rust-crate-xdg \
bundled-rust-crate-xkbcommon-dl \
bundled-rust-crate-xkeysym \
bundled-rust-crate-xml-rs \
bundled-rust-crate-yeslogic-fontconfig-sys \
bundled-rust-crate-zerocopy \
bundled-rust-crate-zmij"

RDEPENDS:${PN} += "libc.so.6 \
libfontconfig.so.1 \
libfreetype.so.6 \
libgcc-s.so.1 \
libm.so.6"

inherit rpm
