SUMMARY = "Utilities for using the EFS file systems"
DESCRIPTION = "This package provides utilities for using the EFS file systems."
LICENSE = "MIT"

PV = "3.2.0"

RPM_NAME = "aws-efs-utils-3.2.0-1.2.aarch64.rpm"
RPM_HASH = "faf936e5507666e753aa9199e944027bbf6e87715826744554baafae2341e41d796854bb27d8482896fe353107898dfcf89a88b8a8ce34651ea21238aaa08983"

RPROVIDES:${PN} += "aws-efs-utils \
bundled-rust-crate-addr2line \
bundled-rust-crate-adler2 \
bundled-rust-crate-aho-corasick \
bundled-rust-crate-allocator-api2 \
bundled-rust-crate-ansi-term \
bundled-rust-crate-anyhow \
bundled-rust-crate-arc-swap \
bundled-rust-crate-assert-json-diff \
bundled-rust-crate-async-trait \
bundled-rust-crate-atomic-enum \
bundled-rust-crate-atomic-waker \
bundled-rust-crate-atty \
bundled-rust-crate-autocfg \
bundled-rust-crate-aws-config \
bundled-rust-crate-aws-credential-types \
bundled-rust-crate-aws-lc-fips-sys \
bundled-rust-crate-aws-lc-rs \
bundled-rust-crate-aws-lc-sys \
bundled-rust-crate-aws-runtime \
bundled-rust-crate-aws-sdk-cloudwatch \
bundled-rust-crate-aws-sdk-cloudwatchlogs \
bundled-rust-crate-aws-sdk-s3 \
bundled-rust-crate-aws-sdk-sso \
bundled-rust-crate-aws-sdk-ssooidc \
bundled-rust-crate-aws-sdk-sts \
bundled-rust-crate-aws-sigv4 \
bundled-rust-crate-aws-smithy-async \
bundled-rust-crate-aws-smithy-cbor \
bundled-rust-crate-aws-smithy-checksums \
bundled-rust-crate-aws-smithy-compression \
bundled-rust-crate-aws-smithy-eventstream \
bundled-rust-crate-aws-smithy-http \
bundled-rust-crate-aws-smithy-http-client \
bundled-rust-crate-aws-smithy-json \
bundled-rust-crate-aws-smithy-observability \
bundled-rust-crate-aws-smithy-protocol-test \
bundled-rust-crate-aws-smithy-query \
bundled-rust-crate-aws-smithy-runtime \
bundled-rust-crate-aws-smithy-runtime-api \
bundled-rust-crate-aws-smithy-runtime-api-macros \
bundled-rust-crate-aws-smithy-schema \
bundled-rust-crate-aws-smithy-types \
bundled-rust-crate-aws-smithy-xml \
bundled-rust-crate-aws-types \
bundled-rust-crate-backtrace \
bundled-rust-crate-base16ct \
bundled-rust-crate-base64 \
bundled-rust-crate-base64-simd \
bundled-rust-crate-base64ct \
bundled-rust-crate-bindgen \
bundled-rust-crate-bitflags \
bundled-rust-crate-block-buffer \
bundled-rust-crate-bs58 \
bundled-rust-crate-byteorder \
bundled-rust-crate-bytes \
bundled-rust-crate-bytes-utils \
bundled-rust-crate-cbor-diag \
bundled-rust-crate-cc \
bundled-rust-crate-cexpr \
bundled-rust-crate-cfg-if \
bundled-rust-crate-chacha20 \
bundled-rust-crate-chrono \
bundled-rust-crate-ciborium \
bundled-rust-crate-ciborium-io \
bundled-rust-crate-ciborium-ll \
bundled-rust-crate-clang-sys \
bundled-rust-crate-clap \
bundled-rust-crate-clap-derive \
bundled-rust-crate-clap-lex \
bundled-rust-crate-cmake \
bundled-rust-crate-cmov \
bundled-rust-crate-const-oid \
bundled-rust-crate-cpufeatures \
bundled-rust-crate-crc-fast \
bundled-rust-crate-crc32fast \
bundled-rust-crate-crossbeam-channel \
bundled-rust-crate-crossbeam-deque \
bundled-rust-crate-crossbeam-epoch \
bundled-rust-crate-crossbeam-utils \
bundled-rust-crate-crypto-bigint \
bundled-rust-crate-crypto-common \
bundled-rust-crate-ctutils \
bundled-rust-crate-dashmap \
bundled-rust-crate-data-encoding \
bundled-rust-crate-der \
bundled-rust-crate-deranged \
bundled-rust-crate-derive-more \
bundled-rust-crate-derive-more-impl \
bundled-rust-crate-destructure-traitobject \
bundled-rust-crate-diff \
bundled-rust-crate-digest \
bundled-rust-crate-displaydoc \
bundled-rust-crate-dunce \
bundled-rust-crate-dyn-clone \
bundled-rust-crate-ecdsa \
bundled-rust-crate-efs-proxy \
bundled-rust-crate-either \
bundled-rust-crate-elliptic-curve \
bundled-rust-crate-env-logger \
bundled-rust-crate-equivalent \
bundled-rust-crate-errno \
bundled-rust-crate-error-chain \
bundled-rust-crate-fastrand \
bundled-rust-crate-ff \
bundled-rust-crate-find-msvc-tools \
bundled-rust-crate-flate2 \
bundled-rust-crate-fnv \
bundled-rust-crate-foldhash \
bundled-rust-crate-form-urlencoded \
bundled-rust-crate-fs-extra \
bundled-rust-crate-futures \
bundled-rust-crate-futures-channel \
bundled-rust-crate-futures-core \
bundled-rust-crate-futures-executor \
bundled-rust-crate-futures-io \
bundled-rust-crate-futures-macro \
bundled-rust-crate-futures-sink \
bundled-rust-crate-futures-task \
bundled-rust-crate-futures-util \
bundled-rust-crate-generic-array \
bundled-rust-crate-getrandom \
bundled-rust-crate-gimli \
bundled-rust-crate-glob \
bundled-rust-crate-group \
bundled-rust-crate-h2 \
bundled-rust-crate-half \
bundled-rust-crate-hashbrown \
bundled-rust-crate-heck \
bundled-rust-crate-hex \
bundled-rust-crate-hmac \
bundled-rust-crate-http \
bundled-rust-crate-http-body \
bundled-rust-crate-http-body-util \
bundled-rust-crate-httparse \
bundled-rust-crate-httpdate \
bundled-rust-crate-humantime \
bundled-rust-crate-hybrid-array \
bundled-rust-crate-hyper \
bundled-rust-crate-hyper-rustls \
bundled-rust-crate-hyper-util \
bundled-rust-crate-iana-time-zone \
bundled-rust-crate-icu-collections \
bundled-rust-crate-icu-locale-core \
bundled-rust-crate-icu-normalizer \
bundled-rust-crate-icu-normalizer-data \
bundled-rust-crate-icu-properties \
bundled-rust-crate-icu-properties-data \
bundled-rust-crate-icu-provider \
bundled-rust-crate-idna \
bundled-rust-crate-idna-adapter \
bundled-rust-crate-indexmap \
bundled-rust-crate-ipnet \
bundled-rust-crate-is-terminal \
bundled-rust-crate-itertools \
bundled-rust-crate-itoa \
bundled-rust-crate-jobserver \
bundled-rust-crate-lazy-static \
bundled-rust-crate-libc \
bundled-rust-crate-libloading \
bundled-rust-crate-litemap \
bundled-rust-crate-lock-api \
bundled-rust-crate-log \
bundled-rust-crate-log-mdc \
bundled-rust-crate-log4rs \
bundled-rust-crate-lru \
bundled-rust-crate-matchers \
bundled-rust-crate-md-5 \
bundled-rust-crate-memchr \
bundled-rust-crate-memoffset \
bundled-rust-crate-minicbor \
bundled-rust-crate-minimal-lexical \
bundled-rust-crate-miniz-oxide \
bundled-rust-crate-mio \
bundled-rust-crate-mock-instant \
bundled-rust-crate-moka \
bundled-rust-crate-nix \
bundled-rust-crate-nom \
bundled-rust-crate-nu-ansi-term \
bundled-rust-crate-num-bigint \
bundled-rust-crate-num-conv \
bundled-rust-crate-num-integer \
bundled-rust-crate-num-rational \
bundled-rust-crate-num-traits \
bundled-rust-crate-object \
bundled-rust-crate-onc-rpc \
bundled-rust-crate-once-cell \
bundled-rust-crate-openssl-probe \
bundled-rust-crate-ordered-float \
bundled-rust-crate-os-str-bytes \
bundled-rust-crate-outref \
bundled-rust-crate-p256 \
bundled-rust-crate-parking-lot \
bundled-rust-crate-parking-lot-core \
bundled-rust-crate-pem-rfc7468 \
bundled-rust-crate-percent-encoding \
bundled-rust-crate-pin-project-lite \
bundled-rust-crate-pin-utils \
bundled-rust-crate-pkcs8 \
bundled-rust-crate-pkg-config \
bundled-rust-crate-portable-atomic \
bundled-rust-crate-potential-utf \
bundled-rust-crate-powerfmt \
bundled-rust-crate-ppv-lite86 \
bundled-rust-crate-pretty-assertions \
bundled-rust-crate-prettyplease \
bundled-rust-crate-primeorder \
bundled-rust-crate-proc-macro-error \
bundled-rust-crate-proc-macro-error-attr \
bundled-rust-crate-proc-macro2 \
bundled-rust-crate-quote \
bundled-rust-crate-rand \
bundled-rust-crate-rand-chacha \
bundled-rust-crate-rand-core \
bundled-rust-crate-rayon \
bundled-rust-crate-rayon-core \
bundled-rust-crate-regex \
bundled-rust-crate-regex-automata \
bundled-rust-crate-regex-lite \
bundled-rust-crate-regex-syntax \
bundled-rust-crate-result \
bundled-rust-crate-rfc6979 \
bundled-rust-crate-ring \
bundled-rust-crate-roxmltree \
bundled-rust-crate-rustc-demangle \
bundled-rust-crate-rustc-hash \
bundled-rust-crate-rustc-version \
bundled-rust-crate-rustls \
bundled-rust-crate-rustls-native-certs \
bundled-rust-crate-rustls-pki-types \
bundled-rust-crate-rustls-webpki \
bundled-rust-crate-rustversion \
bundled-rust-crate-ryu \
bundled-rust-crate-s2n-tls \
bundled-rust-crate-s2n-tls-sys \
bundled-rust-crate-s2n-tls-tokio \
bundled-rust-crate-scopeguard \
bundled-rust-crate-sct \
bundled-rust-crate-sec1 \
bundled-rust-crate-semver \
bundled-rust-crate-separator \
bundled-rust-crate-serde \
bundled-rust-crate-serde-core \
bundled-rust-crate-serde-derive \
bundled-rust-crate-serde-ini \
bundled-rust-crate-serde-json \
bundled-rust-crate-serde-value \
bundled-rust-crate-serde-yaml \
bundled-rust-crate-sha1 \
bundled-rust-crate-sha2 \
bundled-rust-crate-sharded-slab \
bundled-rust-crate-shlex \
bundled-rust-crate-signal-hook-registry \
bundled-rust-crate-signature \
bundled-rust-crate-simd-adler32 \
bundled-rust-crate-slab \
bundled-rust-crate-smallvec \
bundled-rust-crate-socket2 \
bundled-rust-crate-spin \
bundled-rust-crate-spki \
bundled-rust-crate-stable-deref-trait \
bundled-rust-crate-static-assertions \
bundled-rust-crate-strsim \
bundled-rust-crate-strum-macros \
bundled-rust-crate-subtle \
bundled-rust-crate-syn \
bundled-rust-crate-synstructure \
bundled-rust-crate-sysinfo \
bundled-rust-crate-tagptr \
bundled-rust-crate-termcolor \
bundled-rust-crate-textwrap \
bundled-rust-crate-thiserror \
bundled-rust-crate-thiserror-impl \
bundled-rust-crate-thread-id \
bundled-rust-crate-thread-local \
bundled-rust-crate-tikv-jemalloc-sys \
bundled-rust-crate-tikv-jemallocator \
bundled-rust-crate-time \
bundled-rust-crate-time-core \
bundled-rust-crate-time-macros \
bundled-rust-crate-tinystr \
bundled-rust-crate-tinyvec \
bundled-rust-crate-tinyvec-macros \
bundled-rust-crate-tokio \
bundled-rust-crate-tokio-macros \
bundled-rust-crate-tokio-rustls \
bundled-rust-crate-tokio-util \
bundled-rust-crate-tower \
bundled-rust-crate-tower-layer \
bundled-rust-crate-tower-service \
bundled-rust-crate-tracing \
bundled-rust-crate-tracing-attributes \
bundled-rust-crate-tracing-core \
bundled-rust-crate-tracing-log \
bundled-rust-crate-tracing-serde \
bundled-rust-crate-tracing-subscriber \
bundled-rust-crate-try-lock \
bundled-rust-crate-typemap-ors \
bundled-rust-crate-typenum \
bundled-rust-crate-unicode-ident \
bundled-rust-crate-unicode-segmentation \
bundled-rust-crate-unicode-width \
bundled-rust-crate-unicode-xid \
bundled-rust-crate-unsafe-any-ors \
bundled-rust-crate-unsafe-libyaml \
bundled-rust-crate-untrusted \
bundled-rust-crate-url \
bundled-rust-crate-urlencoding \
bundled-rust-crate-utf8-iter \
bundled-rust-crate-uuid \
bundled-rust-crate-vec-map \
bundled-rust-crate-version-check \
bundled-rust-crate-void \
bundled-rust-crate-vsimd \
bundled-rust-crate-want \
bundled-rust-crate-writeable \
bundled-rust-crate-xdr-codec \
bundled-rust-crate-xdrgen \
bundled-rust-crate-xmlparser \
bundled-rust-crate-yansi \
bundled-rust-crate-yoke \
bundled-rust-crate-yoke-derive \
bundled-rust-crate-zerocopy \
bundled-rust-crate-zerocopy-derive \
bundled-rust-crate-zerofrom \
bundled-rust-crate-zerofrom-derive \
bundled-rust-crate-zeroize \
bundled-rust-crate-zerotrie \
bundled-rust-crate-zerovec \
bundled-rust-crate-zerovec-derive \
bundled-rust-crate-zmij \
config-aws-efs-utils"

RDEPENDS:${PN} += "/usr/bin/python3 \
/usr/bin/sh \
libc.so.6 \
libgcc-s.so.1 \
libm.so.6 \
nfs-utils \
python-abi \
stunnel"

inherit rpm
