SUMMARY = "HTML formatted API documention for Log for C++"
DESCRIPTION = "The log4cpp-doc package contains HTML formatted API documention generated by \
the popular doxygen documentation generation tool."
LICENSE = "LGPL-2.1-only"

PV = "1.1.6"

RPM_NAME = "log4cpp-doc-1.1.6-1.4.noarch.rpm"
RPM_HASH = "a4fa95e5dac3035ce4d17c81ff13db25b072cb8ed6bdc5998d979112851b2b8b3926adc4c3931f182bb0b3743e1c0117aa0e0a2d5271de0376da1532be94184d"
REPO_ARCH = "noarch"

RPROVIDES:${PN} += "log4cpp-doc"

RDEPENDS:${PN} += ""

inherit rpm
