SUMMARY = "Romanian hyphenation patterns"
DESCRIPTION = "Hyphenation patterns for Romanian in T1/EC and UTF-8 encodings. \
The UTF-8 patterns use U+0219 for the character 's with comma \
accent' and U+021B for 't with comma accent', but we may \
consider using U+015F and U+0163 as well in the future. \
Generated by PatGen2-output hyphen-level 9."
LICENSE = "LPPL-1.0"

PV = "2026.226.svn78069"

RPM_NAME = "texlive-hyphen-romanian-2026.226.svn78069-60.2.noarch.rpm"
RPM_HASH = "d0785295ec71e19d0cec8624c6fa30633fe47527e679be4193dfb1c757941d24ecb8d4eab3f43a60503a94689b5d13587b4cb0ef0f8a72df1eb1d95fd1f59db7"
REPO_ARCH = "noarch"

RPROVIDES:${PN} += "tex-hyph-ro.ec.tex \
tex-hyph-ro.tex \
tex-loadhyph-ro.tex \
texlive-hyphen-romanian"

RDEPENDS:${PN} += "/usr/bin/sh \
coreutils \
ed \
findutils \
grep \
sed \
tex-language.dat \
tex-language.dat.lua \
tex-language.def \
texlive \
texlive-filesystem \
texlive-hyph-utf8 \
texlive-hyphen-base \
texlive-kpathsea \
texlive-kpathsea-bin \
texlive-scripts \
texlive-scripts-bin"

inherit rpm
