SUMMARY = "Remote tool for accessing a cloud hypervisor instance"
DESCRIPTION = "Remote tool for accessing a cloud hypervisor instance."
LICENSE = "Apache-2.0 & BSD-3-Clause"

PV = "53.0"

RPM_NAME = "cloud-hypervisor-remote-53.0-1.2.aarch64.rpm"
RPM_HASH = "c9dd7f93d233485d165375068c2806d911f62bf2e25135de0caf5b427e41ab3cb5cb47c015b342f27e2db61d5c108860d3beda1c61ba5530f427eaf5fe5677da"

RPROVIDES:${PN} += "bundled-rust-crate-acpi-tables \
bundled-rust-crate-adler2 \
bundled-rust-crate-aho-corasick \
bundled-rust-crate-anstream \
bundled-rust-crate-anstyle \
bundled-rust-crate-anstyle-parse \
bundled-rust-crate-anstyle-query \
bundled-rust-crate-anyhow \
bundled-rust-crate-api-client \
bundled-rust-crate-arc-swap \
bundled-rust-crate-arch \
bundled-rust-crate-base64 \
bundled-rust-crate-bitfield-struct \
bundled-rust-crate-bitflags \
bundled-rust-crate-block \
bundled-rust-crate-block-buffer \
bundled-rust-crate-byteorder \
bundled-rust-crate-cc \
bundled-rust-crate-cfg-if \
bundled-rust-crate-chacha20 \
bundled-rust-crate-clap \
bundled-rust-crate-clap-builder \
bundled-rust-crate-clap-derive \
bundled-rust-crate-clap-lex \
bundled-rust-crate-cloud-hypervisor \
bundled-rust-crate-colorchoice \
bundled-rust-crate-concat-idents \
bundled-rust-crate-const-oid \
bundled-rust-crate-cpufeatures \
bundled-rust-crate-crc-any \
bundled-rust-crate-crc32fast \
bundled-rust-crate-crypto-common \
bundled-rust-crate-darling \
bundled-rust-crate-darling-core \
bundled-rust-crate-darling-macro \
bundled-rust-crate-debug-helper \
bundled-rust-crate-defmt \
bundled-rust-crate-defmt-macros \
bundled-rust-crate-defmt-parser \
bundled-rust-crate-devices \
bundled-rust-crate-digest \
bundled-rust-crate-either \
bundled-rust-crate-enumflags2 \
bundled-rust-crate-enumflags2-derive \
bundled-rust-crate-env-filter \
bundled-rust-crate-env-logger \
bundled-rust-crate-epoll \
bundled-rust-crate-equivalent \
bundled-rust-crate-errno \
bundled-rust-crate-event-monitor \
bundled-rust-crate-fastrand \
bundled-rust-crate-fdt \
bundled-rust-crate-find-msvc-tools \
bundled-rust-crate-flate2 \
bundled-rust-crate-flume \
bundled-rust-crate-futures-core \
bundled-rust-crate-futures-sink \
bundled-rust-crate-getrandom \
bundled-rust-crate-hashbrown \
bundled-rust-crate-heck \
bundled-rust-crate-hybrid-array \
bundled-rust-crate-hypervisor \
bundled-rust-crate-ident-case \
bundled-rust-crate-indexmap \
bundled-rust-crate-io-uring \
bundled-rust-crate-iommufd-bindings \
bundled-rust-crate-iommufd-ioctls \
bundled-rust-crate-is-terminal-polyfill \
bundled-rust-crate-itertools \
bundled-rust-crate-itoa \
bundled-rust-crate-jiff \
bundled-rust-crate-jobserver \
bundled-rust-crate-kvm-bindings \
bundled-rust-crate-kvm-ioctls \
bundled-rust-crate-landlock \
bundled-rust-crate-libc \
bundled-rust-crate-linux-loader \
bundled-rust-crate-linux-raw-sys \
bundled-rust-crate-lock-api \
bundled-rust-crate-log \
bundled-rust-crate-memchr \
bundled-rust-crate-micro-http \
bundled-rust-crate-miniz-oxide \
bundled-rust-crate-net-util \
bundled-rust-crate-num-enum \
bundled-rust-crate-num-enum-derive \
bundled-rust-crate-once-cell \
bundled-rust-crate-open-enum \
bundled-rust-crate-open-enum-derive \
bundled-rust-crate-option-parser \
bundled-rust-crate-pci \
bundled-rust-crate-pkg-config \
bundled-rust-crate-proc-macro-crate \
bundled-rust-crate-proc-macro2 \
bundled-rust-crate-quote \
bundled-rust-crate-rand \
bundled-rust-crate-rand-core \
bundled-rust-crate-rate-limiter \
bundled-rust-crate-regex \
bundled-rust-crate-regex-automata \
bundled-rust-crate-regex-syntax \
bundled-rust-crate-remain \
bundled-rust-crate-ring \
bundled-rust-crate-rustix \
bundled-rust-crate-rustls \
bundled-rust-crate-rustls-pki-types \
bundled-rust-crate-rustls-webpki \
bundled-rust-crate-rustversion \
bundled-rust-crate-scopeguard \
bundled-rust-crate-seccompiler \
bundled-rust-crate-serde \
bundled-rust-crate-serde-core \
bundled-rust-crate-serde-derive \
bundled-rust-crate-serde-json \
bundled-rust-crate-serde-with \
bundled-rust-crate-serde-with-macros \
bundled-rust-crate-serial-buffer \
bundled-rust-crate-sha2 \
bundled-rust-crate-shlex \
bundled-rust-crate-signal-hook \
bundled-rust-crate-signal-hook-registry \
bundled-rust-crate-simd-adler32 \
bundled-rust-crate-smallvec \
bundled-rust-crate-spin \
bundled-rust-crate-strsim \
bundled-rust-crate-subtle \
bundled-rust-crate-syn \
bundled-rust-crate-terminal-size \
bundled-rust-crate-thiserror \
bundled-rust-crate-thiserror-impl \
bundled-rust-crate-toml-datetime \
bundled-rust-crate-toml-edit \
bundled-rust-crate-toml-parser \
bundled-rust-crate-tpm \
bundled-rust-crate-tracer \
bundled-rust-crate-typenum \
bundled-rust-crate-unicode-ident \
bundled-rust-crate-untrusted \
bundled-rust-crate-utf8parse \
bundled-rust-crate-uuid \
bundled-rust-crate-vfio-bindings \
bundled-rust-crate-vfio-ioctls \
bundled-rust-crate-vfio-user \
bundled-rust-crate-vhost \
bundled-rust-crate-virtio-bindings \
bundled-rust-crate-virtio-devices \
bundled-rust-crate-virtio-queue \
bundled-rust-crate-vm-allocator \
bundled-rust-crate-vm-device \
bundled-rust-crate-vm-fdt \
bundled-rust-crate-vm-memory \
bundled-rust-crate-vm-migration \
bundled-rust-crate-vm-virtio \
bundled-rust-crate-vmm \
bundled-rust-crate-vmm-sys-util \
bundled-rust-crate-winnow \
bundled-rust-crate-zerocopy \
bundled-rust-crate-zerocopy-derive \
bundled-rust-crate-zeroize \
bundled-rust-crate-zmij \
bundled-rust-crate-zstd \
bundled-rust-crate-zstd-safe \
bundled-rust-crate-zstd-sys \
cloud-hypervisor-remote"

RDEPENDS:${PN} += "libc.so.6 \
libgcc-s.so.1"

inherit rpm
