SUMMARY = "Advanced font selection for platex and its friends"
DESCRIPTION = "The package contains pLaTeX support files and virtual fonts for \
supporting a wide variety of fonts in LaTeX using the pTeX \
engine."
LICENSE = "BSD-3-Clause"

PV = "2026.226.svn77682"

RPM_NAME = "texlive-japanese-otf-2026.226.svn77682-63.2.noarch.rpm"
RPM_HASH = "833bf58a4fbb365a407d723141e5a427f1c05074b5adf7c2756e0d20c62aa34345fd9ef7d9b2794ca8ebff0a15ccc7cf816591986f8f0d6b72bada6a0185df0a"
REPO_ARCH = "noarch"

RPROVIDES:${PN} += "tex-ajmacros.sty \
tex-brsgexpgothb-h.tfm \
tex-brsgexpgothb-h.vf \
tex-brsgexpgothb-v.tfm \
tex-brsgexpgothb-v.vf \
tex-brsgexpgothbn-h.tfm \
tex-brsgexpgothbn-h.vf \
tex-brsgexpgothbn-v.tfm \
tex-brsgexpgothbn-v.vf \
tex-brsgexpgotheb-h.tfm \
tex-brsgexpgotheb-h.vf \
tex-brsgexpgotheb-v.tfm \
tex-brsgexpgotheb-v.vf \
tex-brsgexpgothebn-h.tfm \
tex-brsgexpgothebn-h.vf \
tex-brsgexpgothebn-v.tfm \
tex-brsgexpgothebn-v.vf \
tex-brsgexpgothr-h.tfm \
tex-brsgexpgothr-h.vf \
tex-brsgexpgothr-v.tfm \
tex-brsgexpgothr-v.vf \
tex-brsgexpgothrn-h.tfm \
tex-brsgexpgothrn-h.vf \
tex-brsgexpgothrn-v.tfm \
tex-brsgexpgothrn-v.vf \
tex-brsgexpmgothr-h.tfm \
tex-brsgexpmgothr-h.vf \
tex-brsgexpmgothr-v.tfm \
tex-brsgexpmgothr-v.vf \
tex-brsgexpmgothrn-h.tfm \
tex-brsgexpmgothrn-h.vf \
tex-brsgexpmgothrn-v.tfm \
tex-brsgexpmgothrn-v.vf \
tex-brsgexpminb-h.tfm \
tex-brsgexpminb-h.vf \
tex-brsgexpminb-v.tfm \
tex-brsgexpminb-v.vf \
tex-brsgexpminbn-h.tfm \
tex-brsgexpminbn-h.vf \
tex-brsgexpminbn-v.tfm \
tex-brsgexpminbn-v.vf \
tex-brsgexpminl-h.tfm \
tex-brsgexpminl-h.vf \
tex-brsgexpminl-v.tfm \
tex-brsgexpminl-v.vf \
tex-brsgexpminln-h.tfm \
tex-brsgexpminln-h.vf \
tex-brsgexpminln-v.tfm \
tex-brsgexpminln-v.vf \
tex-brsgexpminr-h.tfm \
tex-brsgexpminr-h.vf \
tex-brsgexpminr-v.tfm \
tex-brsgexpminr-v.vf \
tex-brsgexpminrn-h.tfm \
tex-brsgexpminrn-h.vf \
tex-brsgexpminrn-v.tfm \
tex-brsgexpminrn-v.vf \
tex-brsgnmlgothb-h.tfm \
tex-brsgnmlgothb-h.vf \
tex-brsgnmlgothb-v.tfm \
tex-brsgnmlgothb-v.vf \
tex-brsgnmlgothbn-h.tfm \
tex-brsgnmlgothbn-h.vf \
tex-brsgnmlgothbn-v.tfm \
tex-brsgnmlgothbn-v.vf \
tex-brsgnmlgotheb-h.tfm \
tex-brsgnmlgotheb-h.vf \
tex-brsgnmlgotheb-v.tfm \
tex-brsgnmlgotheb-v.vf \
tex-brsgnmlgothebn-h.tfm \
tex-brsgnmlgothebn-h.vf \
tex-brsgnmlgothebn-v.tfm \
tex-brsgnmlgothebn-v.vf \
tex-brsgnmlgothr-h.tfm \
tex-brsgnmlgothr-h.vf \
tex-brsgnmlgothr-v.tfm \
tex-brsgnmlgothr-v.vf \
tex-brsgnmlgothrn-h.tfm \
tex-brsgnmlgothrn-h.vf \
tex-brsgnmlgothrn-v.tfm \
tex-brsgnmlgothrn-v.vf \
tex-brsgnmlmgothr-h.tfm \
tex-brsgnmlmgothr-h.vf \
tex-brsgnmlmgothr-v.tfm \
tex-brsgnmlmgothr-v.vf \
tex-brsgnmlmgothrn-h.tfm \
tex-brsgnmlmgothrn-h.vf \
tex-brsgnmlmgothrn-v.tfm \
tex-brsgnmlmgothrn-v.vf \
tex-brsgnmlminb-h.tfm \
tex-brsgnmlminb-h.vf \
tex-brsgnmlminb-v.tfm \
tex-brsgnmlminb-v.vf \
tex-brsgnmlminbn-h.tfm \
tex-brsgnmlminbn-h.vf \
tex-brsgnmlminbn-v.tfm \
tex-brsgnmlminbn-v.vf \
tex-brsgnmlminl-h.tfm \
tex-brsgnmlminl-h.vf \
tex-brsgnmlminl-v.tfm \
tex-brsgnmlminl-v.vf \
tex-brsgnmlminln-h.tfm \
tex-brsgnmlminln-h.vf \
tex-brsgnmlminln-v.tfm \
tex-brsgnmlminln-v.vf \
tex-brsgnmlminr-h.tfm \
tex-brsgnmlminr-h.vf \
tex-brsgnmlminr-v.tfm \
tex-brsgnmlminr-v.vf \
tex-brsgnmlminrn-h.tfm \
tex-brsgnmlminrn-h.vf \
tex-brsgnmlminrn-v.tfm \
tex-brsgnmlminrn-v.vf \
tex-cidcgb--h.tfm \
tex-cidcgb--h.vf \
tex-cidcgb--v.tfm \
tex-cidcgb--v.vf \
tex-cidcge--h.tfm \
tex-cidcge--h.vf \
tex-cidcge--v.tfm \
tex-cidcge--v.vf \
tex-cidcgr--h.tfm \
tex-cidcgr--h.vf \
tex-cidcgr--v.tfm \
tex-cidcgr--v.vf \
tex-cidcmb--h.tfm \
tex-cidcmb--h.vf \
tex-cidcmb--v.tfm \
tex-cidcmb--v.vf \
tex-cidcmgr--h.tfm \
tex-cidcmgr--h.vf \
tex-cidcmgr--v.tfm \
tex-cidcmgr--v.vf \
tex-cidcml--h.tfm \
tex-cidcml--h.vf \
tex-cidcml--v.tfm \
tex-cidcml--v.vf \
tex-cidcmr--h.tfm \
tex-cidcmr--h.vf \
tex-cidcmr--v.tfm \
tex-cidcmr--v.vf \
tex-cidjgb--h.tfm \
tex-cidjgb--h.vf \
tex-cidjgb--v.tfm \
tex-cidjgb--v.vf \
tex-cidjgb0-h.tfm \
tex-cidjgb0-h.vf \
tex-cidjgb0-v.tfm \
tex-cidjgb0-v.vf \
tex-cidjgb1-h.tfm \
tex-cidjgb1-h.vf \
tex-cidjgb1-v.tfm \
tex-cidjgb1-v.vf \
tex-cidjgb2-h.tfm \
tex-cidjgb2-h.vf \
tex-cidjgb2-v.tfm \
tex-cidjgb2-v.vf \
tex-cidjgb3-h.tfm \
tex-cidjgb3-h.vf \
tex-cidjgb3-v.tfm \
tex-cidjgb3-v.vf \
tex-cidjgb4-h.tfm \
tex-cidjgb4-h.vf \
tex-cidjgb4-v.tfm \
tex-cidjgb4-v.vf \
tex-cidjgb5-h.tfm \
tex-cidjgb5-h.vf \
tex-cidjgb5-v.tfm \
tex-cidjgb5-v.vf \
tex-cidjge--h.tfm \
tex-cidjge--h.vf \
tex-cidjge--v.tfm \
tex-cidjge--v.vf \
tex-cidjge0-h.tfm \
tex-cidjge0-h.vf \
tex-cidjge0-v.tfm \
tex-cidjge0-v.vf \
tex-cidjge1-h.tfm \
tex-cidjge1-h.vf \
tex-cidjge1-v.tfm \
tex-cidjge1-v.vf \
tex-cidjge2-h.tfm \
tex-cidjge2-h.vf \
tex-cidjge2-v.tfm \
tex-cidjge2-v.vf \
tex-cidjge3-h.tfm \
tex-cidjge3-h.vf \
tex-cidjge3-v.tfm \
tex-cidjge3-v.vf \
tex-cidjge4-h.tfm \
tex-cidjge4-h.vf \
tex-cidjge4-v.tfm \
tex-cidjge4-v.vf \
tex-cidjge5-h.tfm \
tex-cidjge5-h.vf \
tex-cidjge5-v.tfm \
tex-cidjge5-v.vf \
tex-cidjgr--h.tfm \
tex-cidjgr--h.vf \
tex-cidjgr--v.tfm \
tex-cidjgr--v.vf \
tex-cidjgr0-h.tfm \
tex-cidjgr0-h.vf \
tex-cidjgr0-v.tfm \
tex-cidjgr0-v.vf \
tex-cidjgr1-h.tfm \
tex-cidjgr1-h.vf \
tex-cidjgr1-v.tfm \
tex-cidjgr1-v.vf \
tex-cidjgr2-h.tfm \
tex-cidjgr2-h.vf \
tex-cidjgr2-v.tfm \
tex-cidjgr2-v.vf \
tex-cidjgr3-h.tfm \
tex-cidjgr3-h.vf \
tex-cidjgr3-v.tfm \
tex-cidjgr3-v.vf \
tex-cidjgr4-h.tfm \
tex-cidjgr4-h.vf \
tex-cidjgr4-v.tfm \
tex-cidjgr4-v.vf \
tex-cidjgr5-h.tfm \
tex-cidjgr5-h.vf \
tex-cidjgr5-v.tfm \
tex-cidjgr5-v.vf \
tex-cidjmb--h.tfm \
tex-cidjmb--h.vf \
tex-cidjmb--v.tfm \
tex-cidjmb--v.vf \
tex-cidjmb0-h.tfm \
tex-cidjmb0-h.vf \
tex-cidjmb0-v.tfm \
tex-cidjmb0-v.vf \
tex-cidjmb1-h.tfm \
tex-cidjmb1-h.vf \
tex-cidjmb1-v.tfm \
tex-cidjmb1-v.vf \
tex-cidjmb2-h.tfm \
tex-cidjmb2-h.vf \
tex-cidjmb2-v.tfm \
tex-cidjmb2-v.vf \
tex-cidjmb3-h.tfm \
tex-cidjmb3-h.vf \
tex-cidjmb3-v.tfm \
tex-cidjmb3-v.vf \
tex-cidjmb4-h.tfm \
tex-cidjmb4-h.vf \
tex-cidjmb4-v.tfm \
tex-cidjmb4-v.vf \
tex-cidjmb5-h.tfm \
tex-cidjmb5-h.vf \
tex-cidjmb5-v.tfm \
tex-cidjmb5-v.vf \
tex-cidjmgr--h.tfm \
tex-cidjmgr--h.vf \
tex-cidjmgr--v.tfm \
tex-cidjmgr--v.vf \
tex-cidjmgr0-h.tfm \
tex-cidjmgr0-h.vf \
tex-cidjmgr0-v.tfm \
tex-cidjmgr0-v.vf \
tex-cidjmgr1-h.tfm \
tex-cidjmgr1-h.vf \
tex-cidjmgr1-v.tfm \
tex-cidjmgr1-v.vf \
tex-cidjmgr2-h.tfm \
tex-cidjmgr2-h.vf \
tex-cidjmgr2-v.tfm \
tex-cidjmgr2-v.vf \
tex-cidjmgr3-h.tfm \
tex-cidjmgr3-h.vf \
tex-cidjmgr3-v.tfm \
tex-cidjmgr3-v.vf \
tex-cidjmgr4-h.tfm \
tex-cidjmgr4-h.vf \
tex-cidjmgr4-v.tfm \
tex-cidjmgr4-v.vf \
tex-cidjmgr5-h.tfm \
tex-cidjmgr5-h.vf \
tex-cidjmgr5-v.tfm \
tex-cidjmgr5-v.vf \
tex-cidjml--h.tfm \
tex-cidjml--h.vf \
tex-cidjml--v.tfm \
tex-cidjml--v.vf \
tex-cidjml0-h.tfm \
tex-cidjml0-h.vf \
tex-cidjml0-v.tfm \
tex-cidjml0-v.vf \
tex-cidjml1-h.tfm \
tex-cidjml1-h.vf \
tex-cidjml1-v.tfm \
tex-cidjml1-v.vf \
tex-cidjml2-h.tfm \
tex-cidjml2-h.vf \
tex-cidjml2-v.tfm \
tex-cidjml2-v.vf \
tex-cidjml3-h.tfm \
tex-cidjml3-h.vf \
tex-cidjml3-v.tfm \
tex-cidjml3-v.vf \
tex-cidjml4-h.tfm \
tex-cidjml4-h.vf \
tex-cidjml4-v.tfm \
tex-cidjml4-v.vf \
tex-cidjml5-h.tfm \
tex-cidjml5-h.vf \
tex-cidjml5-v.tfm \
tex-cidjml5-v.vf \
tex-cidjmr--h.tfm \
tex-cidjmr--h.vf \
tex-cidjmr--v.tfm \
tex-cidjmr--v.vf \
tex-cidjmr0-h.tfm \
tex-cidjmr0-h.vf \
tex-cidjmr0-v.tfm \
tex-cidjmr0-v.vf \
tex-cidjmr1-h.tfm \
tex-cidjmr1-h.vf \
tex-cidjmr1-v.tfm \
tex-cidjmr1-v.vf \
tex-cidjmr2-h.tfm \
tex-cidjmr2-h.vf \
tex-cidjmr2-v.tfm \
tex-cidjmr2-v.vf \
tex-cidjmr3-h.tfm \
tex-cidjmr3-h.vf \
tex-cidjmr3-v.tfm \
tex-cidjmr3-v.vf \
tex-cidjmr4-h.tfm \
tex-cidjmr4-h.vf \
tex-cidjmr4-v.tfm \
tex-cidjmr4-v.vf \
tex-cidjmr5-h.tfm \
tex-cidjmr5-h.vf \
tex-cidjmr5-v.tfm \
tex-cidjmr5-v.vf \
tex-cidkgb--h.tfm \
tex-cidkgb--h.vf \
tex-cidkgb--v.tfm \
tex-cidkgb--v.vf \
tex-cidkge--h.tfm \
tex-cidkge--h.vf \
tex-cidkge--v.tfm \
tex-cidkge--v.vf \
tex-cidkgr--h.tfm \
tex-cidkgr--h.vf \
tex-cidkgr--v.tfm \
tex-cidkgr--v.vf \
tex-cidkmb--h.tfm \
tex-cidkmb--h.vf \
tex-cidkmb--v.tfm \
tex-cidkmb--v.vf \
tex-cidkmgr--h.tfm \
tex-cidkmgr--h.vf \
tex-cidkmgr--v.tfm \
tex-cidkmgr--v.vf \
tex-cidkml--h.tfm \
tex-cidkml--h.vf \
tex-cidkml--v.tfm \
tex-cidkml--v.vf \
tex-cidkmr--h.tfm \
tex-cidkmr--h.vf \
tex-cidkmr--v.tfm \
tex-cidkmr--v.vf \
tex-cidtgb--h.tfm \
tex-cidtgb--h.vf \
tex-cidtgb--v.tfm \
tex-cidtgb--v.vf \
tex-cidtge--h.tfm \
tex-cidtge--h.vf \
tex-cidtge--v.tfm \
tex-cidtge--v.vf \
tex-cidtgr--h.tfm \
tex-cidtgr--h.vf \
tex-cidtgr--v.tfm \
tex-cidtgr--v.vf \
tex-cidtmb--h.tfm \
tex-cidtmb--h.vf \
tex-cidtmb--v.tfm \
tex-cidtmb--v.vf \
tex-cidtmgr--h.tfm \
tex-cidtmgr--h.vf \
tex-cidtmgr--v.tfm \
tex-cidtmgr--v.vf \
tex-cidtml--h.tfm \
tex-cidtml--h.vf \
tex-cidtml--v.tfm \
tex-cidtml--v.vf \
tex-cidtmr--h.tfm \
tex-cidtmr--h.vf \
tex-cidtmr--v.tfm \
tex-cidtmr--v.vf \
tex-expgothb-h.tfm \
tex-expgothb-h.vf \
tex-expgothb-v.tfm \
tex-expgothb-v.vf \
tex-expgothbn-h.tfm \
tex-expgothbn-h.vf \
tex-expgothbn-v.tfm \
tex-expgothbn-v.vf \
tex-expgotheb-h.tfm \
tex-expgotheb-h.vf \
tex-expgotheb-v.tfm \
tex-expgotheb-v.vf \
tex-expgothebn-h.tfm \
tex-expgothebn-h.vf \
tex-expgothebn-v.tfm \
tex-expgothebn-v.vf \
tex-expgothr-h.tfm \
tex-expgothr-h.vf \
tex-expgothr-v.tfm \
tex-expgothr-v.vf \
tex-expgothrn-h.tfm \
tex-expgothrn-h.vf \
tex-expgothrn-v.tfm \
tex-expgothrn-v.vf \
tex-expmgothr-h.tfm \
tex-expmgothr-h.vf \
tex-expmgothr-v.tfm \
tex-expmgothr-v.vf \
tex-expmgothrn-h.tfm \
tex-expmgothrn-h.vf \
tex-expmgothrn-v.tfm \
tex-expmgothrn-v.vf \
tex-expminb-h.tfm \
tex-expminb-h.vf \
tex-expminb-v.tfm \
tex-expminb-v.vf \
tex-expminbn-h.tfm \
tex-expminbn-h.vf \
tex-expminbn-v.tfm \
tex-expminbn-v.vf \
tex-expminl-h.tfm \
tex-expminl-h.vf \
tex-expminl-v.tfm \
tex-expminl-v.vf \
tex-expminln-h.tfm \
tex-expminln-h.vf \
tex-expminln-v.tfm \
tex-expminln-v.vf \
tex-expminr-h.tfm \
tex-expminr-h.vf \
tex-expminr-v.tfm \
tex-expminr-v.vf \
tex-expminrn-h.tfm \
tex-expminrn-h.vf \
tex-expminrn-v.tfm \
tex-expminrn-v.vf \
tex-hgothb-h.tfm \
tex-hgothb-v.tfm \
tex-hgothbn-h.tfm \
tex-hgothbn-v.tfm \
tex-hgotheb-h.tfm \
tex-hgotheb-v.tfm \
tex-hgothebn-h.tfm \
tex-hgothebn-v.tfm \
tex-hgothr-h.tfm \
tex-hgothr-v.tfm \
tex-hgothrn-h.tfm \
tex-hgothrn-v.tfm \
tex-hmgothr-h.tfm \
tex-hmgothr-v.tfm \
tex-hmgothrn-h.tfm \
tex-hmgothrn-v.tfm \
tex-hminb-h.tfm \
tex-hminb-v.tfm \
tex-hminbn-h.tfm \
tex-hminbn-v.tfm \
tex-hminl-h.tfm \
tex-hminl-v.tfm \
tex-hminln-h.tfm \
tex-hminln-v.tfm \
tex-hminr-h.tfm \
tex-hminr-v.tfm \
tex-hminrn-h.tfm \
tex-hminrn-v.tfm \
tex-mlcid.sty \
tex-mlutf.sty \
tex-nmlgothb-h.tfm \
tex-nmlgothb-h.vf \
tex-nmlgothb-v.tfm \
tex-nmlgothb-v.vf \
tex-nmlgothbn-h.tfm \
tex-nmlgothbn-h.vf \
tex-nmlgothbn-v.tfm \
tex-nmlgothbn-v.vf \
tex-nmlgotheb-h.tfm \
tex-nmlgotheb-h.vf \
tex-nmlgotheb-v.tfm \
tex-nmlgotheb-v.vf \
tex-nmlgothebn-h.tfm \
tex-nmlgothebn-h.vf \
tex-nmlgothebn-v.tfm \
tex-nmlgothebn-v.vf \
tex-nmlgothr-h.tfm \
tex-nmlgothr-h.vf \
tex-nmlgothr-v.tfm \
tex-nmlgothr-v.vf \
tex-nmlgothrn-h.tfm \
tex-nmlgothrn-h.vf \
tex-nmlgothrn-v.tfm \
tex-nmlgothrn-v.vf \
tex-nmlmgothr-h.tfm \
tex-nmlmgothr-h.vf \
tex-nmlmgothr-v.tfm \
tex-nmlmgothr-v.vf \
tex-nmlmgothrn-h.tfm \
tex-nmlmgothrn-h.vf \
tex-nmlmgothrn-v.tfm \
tex-nmlmgothrn-v.vf \
tex-nmlminb-h.tfm \
tex-nmlminb-h.vf \
tex-nmlminb-v.tfm \
tex-nmlminb-v.vf \
tex-nmlminbn-h.tfm \
tex-nmlminbn-h.vf \
tex-nmlminbn-v.tfm \
tex-nmlminbn-v.vf \
tex-nmlminl-h.tfm \
tex-nmlminl-h.vf \
tex-nmlminl-v.tfm \
tex-nmlminl-v.vf \
tex-nmlminln-h.tfm \
tex-nmlminln-h.vf \
tex-nmlminln-v.tfm \
tex-nmlminln-v.vf \
tex-nmlminr-h.tfm \
tex-nmlminr-h.vf \
tex-nmlminr-v.tfm \
tex-nmlminr-v.vf \
tex-nmlminrn-h.tfm \
tex-nmlminrn-h.vf \
tex-nmlminrn-v.tfm \
tex-nmlminrn-v.vf \
tex-otf-ccgb-h.tfm \
tex-otf-ccgb-v.tfm \
tex-otf-ccge-h.tfm \
tex-otf-ccge-v.tfm \
tex-otf-ccgr-h.tfm \
tex-otf-ccgr-v.tfm \
tex-otf-ccmb-h.tfm \
tex-otf-ccmb-v.tfm \
tex-otf-ccmgr-h.tfm \
tex-otf-ccmgr-v.tfm \
tex-otf-ccml-h.tfm \
tex-otf-ccml-v.tfm \
tex-otf-ccmr-h.tfm \
tex-otf-ccmr-v.tfm \
tex-otf-cjgb-h.tfm \
tex-otf-cjgb-v.tfm \
tex-otf-cjge-h.tfm \
tex-otf-cjge-v.tfm \
tex-otf-cjgr-h.tfm \
tex-otf-cjgr-v.tfm \
tex-otf-cjmb-h.tfm \
tex-otf-cjmb-v.tfm \
tex-otf-cjmgr-h.tfm \
tex-otf-cjmgr-v.tfm \
tex-otf-cjml-h.tfm \
tex-otf-cjml-v.tfm \
tex-otf-cjmr-h.tfm \
tex-otf-cjmr-v.tfm \
tex-otf-ckgb-h.tfm \
tex-otf-ckgb-v.tfm \
tex-otf-ckge-h.tfm \
tex-otf-ckge-v.tfm \
tex-otf-ckgr-h.tfm \
tex-otf-ckgr-v.tfm \
tex-otf-ckmb-h.tfm \
tex-otf-ckmb-v.tfm \
tex-otf-ckmgr-h.tfm \
tex-otf-ckmgr-v.tfm \
tex-otf-ckml-h.tfm \
tex-otf-ckml-v.tfm \
tex-otf-ckmr-h.tfm \
tex-otf-ckmr-v.tfm \
tex-otf-ctgb-h.tfm \
tex-otf-ctgb-v.tfm \
tex-otf-ctge-h.tfm \
tex-otf-ctge-v.tfm \
tex-otf-ctgr-h.tfm \
tex-otf-ctgr-v.tfm \
tex-otf-ctmb-h.tfm \
tex-otf-ctmb-v.tfm \
tex-otf-ctmgr-h.tfm \
tex-otf-ctmgr-v.tfm \
tex-otf-ctml-h.tfm \
tex-otf-ctml-v.tfm \
tex-otf-ctmr-h.tfm \
tex-otf-ctmr-v.tfm \
tex-otf-ucgb-h.tfm \
tex-otf-ucgb-v.tfm \
tex-otf-ucge-h.tfm \
tex-otf-ucge-v.tfm \
tex-otf-ucgr-h.tfm \
tex-otf-ucgr-v.tfm \
tex-otf-ucmb-h.tfm \
tex-otf-ucmb-v.tfm \
tex-otf-ucmgr-h.tfm \
tex-otf-ucmgr-v.tfm \
tex-otf-ucml-h.tfm \
tex-otf-ucml-v.tfm \
tex-otf-ucmr-h.tfm \
tex-otf-ucmr-v.tfm \
tex-otf-ujgb-h.tfm \
tex-otf-ujgb-v.tfm \
tex-otf-ujgbn-h.tfm \
tex-otf-ujgbn-v.tfm \
tex-otf-ujge-h.tfm \
tex-otf-ujge-v.tfm \
tex-otf-ujgen-h.tfm \
tex-otf-ujgen-v.tfm \
tex-otf-ujgr-h.tfm \
tex-otf-ujgr-v.tfm \
tex-otf-ujgrn-h.tfm \
tex-otf-ujgrn-v.tfm \
tex-otf-ujmb-h.tfm \
tex-otf-ujmb-v.tfm \
tex-otf-ujmbn-h.tfm \
tex-otf-ujmbn-v.tfm \
tex-otf-ujmgr-h.tfm \
tex-otf-ujmgr-v.tfm \
tex-otf-ujmgrn-h.tfm \
tex-otf-ujmgrn-v.tfm \
tex-otf-ujml-h.tfm \
tex-otf-ujml-v.tfm \
tex-otf-ujmln-h.tfm \
tex-otf-ujmln-v.tfm \
tex-otf-ujmr-h.tfm \
tex-otf-ujmr-v.tfm \
tex-otf-ujmrn-h.tfm \
tex-otf-ujmrn-v.tfm \
tex-otf-ukgb-h.tfm \
tex-otf-ukgb-v.tfm \
tex-otf-ukge-h.tfm \
tex-otf-ukge-v.tfm \
tex-otf-ukgr-h.tfm \
tex-otf-ukgr-v.tfm \
tex-otf-ukmb-h.tfm \
tex-otf-ukmb-v.tfm \
tex-otf-ukmgr-h.tfm \
tex-otf-ukmgr-v.tfm \
tex-otf-ukml-h.tfm \
tex-otf-ukml-v.tfm \
tex-otf-ukmr-h.tfm \
tex-otf-ukmr-v.tfm \
tex-otf-utgb-h.tfm \
tex-otf-utgb-v.tfm \
tex-otf-utge-h.tfm \
tex-otf-utge-v.tfm \
tex-otf-utgr-h.tfm \
tex-otf-utgr-v.tfm \
tex-otf-utmb-h.tfm \
tex-otf-utmb-v.tfm \
tex-otf-utmgr-h.tfm \
tex-otf-utmgr-v.tfm \
tex-otf-utml-h.tfm \
tex-otf-utml-v.tfm \
tex-otf-utmr-h.tfm \
tex-otf-utmr-v.tfm \
tex-otf.sty \
tex-redeffont.sty \
tex-rubygothb-h.tfm \
tex-rubygothb-h.vf \
tex-rubygothb-v.tfm \
tex-rubygothb-v.vf \
tex-rubygotheb-h.tfm \
tex-rubygotheb-h.vf \
tex-rubygotheb-v.tfm \
tex-rubygotheb-v.vf \
tex-rubygothr-h.tfm \
tex-rubygothr-h.vf \
tex-rubygothr-v.tfm \
tex-rubygothr-v.vf \
tex-rubymgothr-h.tfm \
tex-rubymgothr-h.vf \
tex-rubymgothr-v.tfm \
tex-rubymgothr-v.vf \
tex-rubyminb-h.tfm \
tex-rubyminb-h.vf \
tex-rubyminb-v.tfm \
tex-rubyminb-v.vf \
tex-rubyminl-h.tfm \
tex-rubyminl-h.vf \
tex-rubyminl-v.tfm \
tex-rubyminl-v.vf \
tex-rubyminr-h.tfm \
tex-rubyminr-h.vf \
tex-rubyminr-v.tfm \
tex-rubyminr-v.vf \
tex-upakorgothb-h.tfm \
tex-upakorgothb-v.tfm \
tex-upakorgotheb-h.tfm \
tex-upakorgotheb-v.tfm \
tex-upakorgothr-h.tfm \
tex-upakorgothr-v.tfm \
tex-upakormgothr-h.tfm \
tex-upakormgothr-v.tfm \
tex-upakorminb-h.tfm \
tex-upakorminb-v.tfm \
tex-upakorminl-h.tfm \
tex-upakorminl-v.tfm \
tex-upakorminr-h.tfm \
tex-upakorminr-v.tfm \
tex-upaschgothb-h.tfm \
tex-upaschgothb-v.tfm \
tex-upaschgotheb-h.tfm \
tex-upaschgotheb-v.tfm \
tex-upaschgothr-h.tfm \
tex-upaschgothr-v.tfm \
tex-upaschmgothr-h.tfm \
tex-upaschmgothr-v.tfm \
tex-upaschminb-h.tfm \
tex-upaschminb-v.tfm \
tex-upaschminl-h.tfm \
tex-upaschminl-v.tfm \
tex-upaschminr-h.tfm \
tex-upaschminr-v.tfm \
tex-upatchgothb-h.tfm \
tex-upatchgothb-v.tfm \
tex-upatchgotheb-h.tfm \
tex-upatchgotheb-v.tfm \
tex-upatchgothr-h.tfm \
tex-upatchgothr-v.tfm \
tex-upatchmgothr-h.tfm \
tex-upatchmgothr-v.tfm \
tex-upatchminb-h.tfm \
tex-upatchminb-v.tfm \
tex-upatchminl-h.tfm \
tex-upatchminl-v.tfm \
tex-upatchminr-h.tfm \
tex-upatchminr-v.tfm \
tex-upbrsgexpgothb-h.tfm \
tex-upbrsgexpgothb-h.vf \
tex-upbrsgexpgothb-v.tfm \
tex-upbrsgexpgothb-v.vf \
tex-upbrsgexpgothbn-h.tfm \
tex-upbrsgexpgothbn-h.vf \
tex-upbrsgexpgothbn-v.tfm \
tex-upbrsgexpgothbn-v.vf \
tex-upbrsgexpgotheb-h.tfm \
tex-upbrsgexpgotheb-h.vf \
tex-upbrsgexpgotheb-v.tfm \
tex-upbrsgexpgotheb-v.vf \
tex-upbrsgexpgothebn-h.tfm \
tex-upbrsgexpgothebn-h.vf \
tex-upbrsgexpgothebn-v.tfm \
tex-upbrsgexpgothebn-v.vf \
tex-upbrsgexpgothr-h.tfm \
tex-upbrsgexpgothr-h.vf \
tex-upbrsgexpgothr-v.tfm \
tex-upbrsgexpgothr-v.vf \
tex-upbrsgexpgothrn-h.tfm \
tex-upbrsgexpgothrn-h.vf \
tex-upbrsgexpgothrn-v.tfm \
tex-upbrsgexpgothrn-v.vf \
tex-upbrsgexpmgothr-h.tfm \
tex-upbrsgexpmgothr-h.vf \
tex-upbrsgexpmgothr-v.tfm \
tex-upbrsgexpmgothr-v.vf \
tex-upbrsgexpmgothrn-h.tfm \
tex-upbrsgexpmgothrn-h.vf \
tex-upbrsgexpmgothrn-v.tfm \
tex-upbrsgexpmgothrn-v.vf \
tex-upbrsgexpminb-h.tfm \
tex-upbrsgexpminb-h.vf \
tex-upbrsgexpminb-v.tfm \
tex-upbrsgexpminb-v.vf \
tex-upbrsgexpminbn-h.tfm \
tex-upbrsgexpminbn-h.vf \
tex-upbrsgexpminbn-v.tfm \
tex-upbrsgexpminbn-v.vf \
tex-upbrsgexpminl-h.tfm \
tex-upbrsgexpminl-h.vf \
tex-upbrsgexpminl-v.tfm \
tex-upbrsgexpminl-v.vf \
tex-upbrsgexpminln-h.tfm \
tex-upbrsgexpminln-h.vf \
tex-upbrsgexpminln-v.tfm \
tex-upbrsgexpminln-v.vf \
tex-upbrsgexpminr-h.tfm \
tex-upbrsgexpminr-h.vf \
tex-upbrsgexpminr-v.tfm \
tex-upbrsgexpminr-v.vf \
tex-upbrsgexpminrn-h.tfm \
tex-upbrsgexpminrn-h.vf \
tex-upbrsgexpminrn-v.tfm \
tex-upbrsgexpminrn-v.vf \
tex-upbrsgnmlgothb-h.tfm \
tex-upbrsgnmlgothb-h.vf \
tex-upbrsgnmlgothb-v.tfm \
tex-upbrsgnmlgothb-v.vf \
tex-upbrsgnmlgothbn-h.tfm \
tex-upbrsgnmlgothbn-h.vf \
tex-upbrsgnmlgothbn-v.tfm \
tex-upbrsgnmlgothbn-v.vf \
tex-upbrsgnmlgotheb-h.tfm \
tex-upbrsgnmlgotheb-h.vf \
tex-upbrsgnmlgotheb-v.tfm \
tex-upbrsgnmlgotheb-v.vf \
tex-upbrsgnmlgothebn-h.tfm \
tex-upbrsgnmlgothebn-h.vf \
tex-upbrsgnmlgothebn-v.tfm \
tex-upbrsgnmlgothebn-v.vf \
tex-upbrsgnmlgothr-h.tfm \
tex-upbrsgnmlgothr-h.vf \
tex-upbrsgnmlgothr-v.tfm \
tex-upbrsgnmlgothr-v.vf \
tex-upbrsgnmlgothrn-h.tfm \
tex-upbrsgnmlgothrn-h.vf \
tex-upbrsgnmlgothrn-v.tfm \
tex-upbrsgnmlgothrn-v.vf \
tex-upbrsgnmlmgothr-h.tfm \
tex-upbrsgnmlmgothr-h.vf \
tex-upbrsgnmlmgothr-v.tfm \
tex-upbrsgnmlmgothr-v.vf \
tex-upbrsgnmlmgothrn-h.tfm \
tex-upbrsgnmlmgothrn-h.vf \
tex-upbrsgnmlmgothrn-v.tfm \
tex-upbrsgnmlmgothrn-v.vf \
tex-upbrsgnmlminb-h.tfm \
tex-upbrsgnmlminb-h.vf \
tex-upbrsgnmlminb-v.tfm \
tex-upbrsgnmlminb-v.vf \
tex-upbrsgnmlminbn-h.tfm \
tex-upbrsgnmlminbn-h.vf \
tex-upbrsgnmlminbn-v.tfm \
tex-upbrsgnmlminbn-v.vf \
tex-upbrsgnmlminl-h.tfm \
tex-upbrsgnmlminl-h.vf \
tex-upbrsgnmlminl-v.tfm \
tex-upbrsgnmlminl-v.vf \
tex-upbrsgnmlminln-h.tfm \
tex-upbrsgnmlminln-h.vf \
tex-upbrsgnmlminln-v.tfm \
tex-upbrsgnmlminln-v.vf \
tex-upbrsgnmlminr-h.tfm \
tex-upbrsgnmlminr-h.vf \
tex-upbrsgnmlminr-v.tfm \
tex-upbrsgnmlminr-v.vf \
tex-upbrsgnmlminrn-h.tfm \
tex-upbrsgnmlminrn-h.vf \
tex-upbrsgnmlminrn-v.tfm \
tex-upbrsgnmlminrn-v.vf \
tex-upexpgothb-h.tfm \
tex-upexpgothb-h.vf \
tex-upexpgothb-v.tfm \
tex-upexpgothb-v.vf \
tex-upexpgothbn-h.tfm \
tex-upexpgothbn-h.vf \
tex-upexpgothbn-v.tfm \
tex-upexpgothbn-v.vf \
tex-upexpgotheb-h.tfm \
tex-upexpgotheb-h.vf \
tex-upexpgotheb-v.tfm \
tex-upexpgotheb-v.vf \
tex-upexpgothebn-h.tfm \
tex-upexpgothebn-h.vf \
tex-upexpgothebn-v.tfm \
tex-upexpgothebn-v.vf \
tex-upexpgothr-h.tfm \
tex-upexpgothr-h.vf \
tex-upexpgothr-v.tfm \
tex-upexpgothr-v.vf \
tex-upexpgothrn-h.tfm \
tex-upexpgothrn-h.vf \
tex-upexpgothrn-v.tfm \
tex-upexpgothrn-v.vf \
tex-upexpmgothr-h.tfm \
tex-upexpmgothr-h.vf \
tex-upexpmgothr-v.tfm \
tex-upexpmgothr-v.vf \
tex-upexpmgothrn-h.tfm \
tex-upexpmgothrn-h.vf \
tex-upexpmgothrn-v.tfm \
tex-upexpmgothrn-v.vf \
tex-upexpminb-h.tfm \
tex-upexpminb-h.vf \
tex-upexpminb-v.tfm \
tex-upexpminb-v.vf \
tex-upexpminbn-h.tfm \
tex-upexpminbn-h.vf \
tex-upexpminbn-v.tfm \
tex-upexpminbn-v.vf \
tex-upexpminl-h.tfm \
tex-upexpminl-h.vf \
tex-upexpminl-v.tfm \
tex-upexpminl-v.vf \
tex-upexpminln-h.tfm \
tex-upexpminln-h.vf \
tex-upexpminln-v.tfm \
tex-upexpminln-v.vf \
tex-upexpminr-h.tfm \
tex-upexpminr-h.vf \
tex-upexpminr-v.tfm \
tex-upexpminr-v.vf \
tex-upexpminrn-h.tfm \
tex-upexpminrn-h.vf \
tex-upexpminrn-v.tfm \
tex-upexpminrn-v.vf \
tex-uphgothb-h.tfm \
tex-uphgothb-v.tfm \
tex-uphgothbn-h.tfm \
tex-uphgothbn-v.tfm \
tex-uphgotheb-h.tfm \
tex-uphgotheb-v.tfm \
tex-uphgothebn-h.tfm \
tex-uphgothebn-v.tfm \
tex-uphgothr-h.tfm \
tex-uphgothr-v.tfm \
tex-uphgothrn-h.tfm \
tex-uphgothrn-v.tfm \
tex-uphmgothr-h.tfm \
tex-uphmgothr-v.tfm \
tex-uphmgothrn-h.tfm \
tex-uphmgothrn-v.tfm \
tex-uphminb-h.tfm \
tex-uphminb-v.tfm \
tex-uphminbn-h.tfm \
tex-uphminbn-v.tfm \
tex-uphminl-h.tfm \
tex-uphminl-v.tfm \
tex-uphminln-h.tfm \
tex-uphminln-v.tfm \
tex-uphminr-h.tfm \
tex-uphminr-v.tfm \
tex-uphminrn-h.tfm \
tex-uphminrn-v.tfm \
tex-upnmkorgothb-h.tfm \
tex-upnmkorgothb-h.vf \
tex-upnmkorgothb-v.tfm \
tex-upnmkorgothb-v.vf \
tex-upnmkorgotheb-h.tfm \
tex-upnmkorgotheb-h.vf \
tex-upnmkorgotheb-v.tfm \
tex-upnmkorgotheb-v.vf \
tex-upnmkorgothr-h.tfm \
tex-upnmkorgothr-h.vf \
tex-upnmkorgothr-v.tfm \
tex-upnmkorgothr-v.vf \
tex-upnmkormgothr-h.tfm \
tex-upnmkormgothr-h.vf \
tex-upnmkormgothr-v.tfm \
tex-upnmkormgothr-v.vf \
tex-upnmkorminb-h.tfm \
tex-upnmkorminb-h.vf \
tex-upnmkorminb-v.tfm \
tex-upnmkorminb-v.vf \
tex-upnmkorminl-h.tfm \
tex-upnmkorminl-h.vf \
tex-upnmkorminl-v.tfm \
tex-upnmkorminl-v.vf \
tex-upnmkorminr-h.tfm \
tex-upnmkorminr-h.vf \
tex-upnmkorminr-v.tfm \
tex-upnmkorminr-v.vf \
tex-upnmlgothb-h.tfm \
tex-upnmlgothb-h.vf \
tex-upnmlgothb-v.tfm \
tex-upnmlgothb-v.vf \
tex-upnmlgothbn-h.tfm \
tex-upnmlgothbn-h.vf \
tex-upnmlgothbn-v.tfm \
tex-upnmlgothbn-v.vf \
tex-upnmlgotheb-h.tfm \
tex-upnmlgotheb-h.vf \
tex-upnmlgotheb-v.tfm \
tex-upnmlgotheb-v.vf \
tex-upnmlgothebn-h.tfm \
tex-upnmlgothebn-h.vf \
tex-upnmlgothebn-v.tfm \
tex-upnmlgothebn-v.vf \
tex-upnmlgothr-h.tfm \
tex-upnmlgothr-h.vf \
tex-upnmlgothr-v.tfm \
tex-upnmlgothr-v.vf \
tex-upnmlgothrn-h.tfm \
tex-upnmlgothrn-h.vf \
tex-upnmlgothrn-v.tfm \
tex-upnmlgothrn-v.vf \
tex-upnmlmgothr-h.tfm \
tex-upnmlmgothr-h.vf \
tex-upnmlmgothr-v.tfm \
tex-upnmlmgothr-v.vf \
tex-upnmlmgothrn-h.tfm \
tex-upnmlmgothrn-h.vf \
tex-upnmlmgothrn-v.tfm \
tex-upnmlmgothrn-v.vf \
tex-upnmlminb-h.tfm \
tex-upnmlminb-h.vf \
tex-upnmlminb-v.tfm \
tex-upnmlminb-v.vf \
tex-upnmlminbn-h.tfm \
tex-upnmlminbn-h.vf \
tex-upnmlminbn-v.tfm \
tex-upnmlminbn-v.vf \
tex-upnmlminl-h.tfm \
tex-upnmlminl-h.vf \
tex-upnmlminl-v.tfm \
tex-upnmlminl-v.vf \
tex-upnmlminln-h.tfm \
tex-upnmlminln-h.vf \
tex-upnmlminln-v.tfm \
tex-upnmlminln-v.vf \
tex-upnmlminr-h.tfm \
tex-upnmlminr-h.vf \
tex-upnmlminr-v.tfm \
tex-upnmlminr-v.vf \
tex-upnmlminrn-h.tfm \
tex-upnmlminrn-h.vf \
tex-upnmlminrn-v.tfm \
tex-upnmlminrn-v.vf \
tex-upnmschgothb-h.tfm \
tex-upnmschgothb-h.vf \
tex-upnmschgothb-v.tfm \
tex-upnmschgothb-v.vf \
tex-upnmschgotheb-h.tfm \
tex-upnmschgotheb-h.vf \
tex-upnmschgotheb-v.tfm \
tex-upnmschgotheb-v.vf \
tex-upnmschgothr-h.tfm \
tex-upnmschgothr-h.vf \
tex-upnmschgothr-v.tfm \
tex-upnmschgothr-v.vf \
tex-upnmschmgothr-h.tfm \
tex-upnmschmgothr-h.vf \
tex-upnmschmgothr-v.tfm \
tex-upnmschmgothr-v.vf \
tex-upnmschminb-h.tfm \
tex-upnmschminb-h.vf \
tex-upnmschminb-v.tfm \
tex-upnmschminb-v.vf \
tex-upnmschminl-h.tfm \
tex-upnmschminl-h.vf \
tex-upnmschminl-v.tfm \
tex-upnmschminl-v.vf \
tex-upnmschminr-h.tfm \
tex-upnmschminr-h.vf \
tex-upnmschminr-v.tfm \
tex-upnmschminr-v.vf \
tex-upnmtchgothb-h.tfm \
tex-upnmtchgothb-h.vf \
tex-upnmtchgothb-v.tfm \
tex-upnmtchgothb-v.vf \
tex-upnmtchgotheb-h.tfm \
tex-upnmtchgotheb-h.vf \
tex-upnmtchgotheb-v.tfm \
tex-upnmtchgotheb-v.vf \
tex-upnmtchgothr-h.tfm \
tex-upnmtchgothr-h.vf \
tex-upnmtchgothr-v.tfm \
tex-upnmtchgothr-v.vf \
tex-upnmtchmgothr-h.tfm \
tex-upnmtchmgothr-h.vf \
tex-upnmtchmgothr-v.tfm \
tex-upnmtchmgothr-v.vf \
tex-upnmtchminb-h.tfm \
tex-upnmtchminb-h.vf \
tex-upnmtchminb-v.tfm \
tex-upnmtchminb-v.vf \
tex-upnmtchminl-h.tfm \
tex-upnmtchminl-h.vf \
tex-upnmtchminl-v.tfm \
tex-upnmtchminl-v.vf \
tex-upnmtchminr-h.tfm \
tex-upnmtchminr-h.vf \
tex-upnmtchminr-v.tfm \
tex-upnmtchminr-v.vf \
tex-uprubygothb-h.tfm \
tex-uprubygothb-h.vf \
tex-uprubygothb-v.tfm \
tex-uprubygothb-v.vf \
tex-uprubygotheb-h.tfm \
tex-uprubygotheb-h.vf \
tex-uprubygotheb-v.tfm \
tex-uprubygotheb-v.vf \
tex-uprubygothr-h.tfm \
tex-uprubygothr-h.vf \
tex-uprubygothr-v.tfm \
tex-uprubygothr-v.vf \
tex-uprubymgothr-h.tfm \
tex-uprubymgothr-h.vf \
tex-uprubymgothr-v.tfm \
tex-uprubymgothr-v.vf \
tex-uprubyminb-h.tfm \
tex-uprubyminb-h.vf \
tex-uprubyminb-v.tfm \
tex-uprubyminb-v.vf \
tex-uprubyminl-h.tfm \
tex-uprubyminl-h.vf \
tex-uprubyminl-v.tfm \
tex-uprubyminl-v.vf \
tex-uprubyminr-h.tfm \
tex-uprubyminr-h.vf \
tex-uprubyminr-v.tfm \
tex-uprubyminr-v.vf \
tex-utfcgb--h.tfm \
tex-utfcgb--h.vf \
tex-utfcgb--v.tfm \
tex-utfcgb--v.vf \
tex-utfcge--h.tfm \
tex-utfcge--h.vf \
tex-utfcge--v.tfm \
tex-utfcge--v.vf \
tex-utfcgr--h.tfm \
tex-utfcgr--h.vf \
tex-utfcgr--v.tfm \
tex-utfcgr--v.vf \
tex-utfcmb--h.tfm \
tex-utfcmb--h.vf \
tex-utfcmb--v.tfm \
tex-utfcmb--v.vf \
tex-utfcmgr--h.tfm \
tex-utfcmgr--h.vf \
tex-utfcmgr--v.tfm \
tex-utfcmgr--v.vf \
tex-utfcml--h.tfm \
tex-utfcml--h.vf \
tex-utfcml--v.tfm \
tex-utfcml--v.vf \
tex-utfcmr--h.tfm \
tex-utfcmr--h.vf \
tex-utfcmr--v.tfm \
tex-utfcmr--v.vf \
tex-utfgb--h.tfm \
tex-utfgb--h.vf \
tex-utfgb--v.tfm \
tex-utfgb--v.vf \
tex-utfge--h.tfm \
tex-utfge--h.vf \
tex-utfge--v.tfm \
tex-utfge--v.vf \
tex-utfgr--h.tfm \
tex-utfgr--h.vf \
tex-utfgr--v.tfm \
tex-utfgr--v.vf \
tex-utfjgb--h.tfm \
tex-utfjgb--h.vf \
tex-utfjgb--v.tfm \
tex-utfjgb--v.vf \
tex-utfjgb0-h.tfm \
tex-utfjgb0-h.vf \
tex-utfjgb0-v.tfm \
tex-utfjgb0-v.vf \
tex-utfjgb1-h.tfm \
tex-utfjgb1-h.vf \
tex-utfjgb1-v.tfm \
tex-utfjgb1-v.vf \
tex-utfjgb2-h.tfm \
tex-utfjgb2-h.vf \
tex-utfjgb2-v.tfm \
tex-utfjgb2-v.vf \
tex-utfjgb3-h.tfm \
tex-utfjgb3-h.vf \
tex-utfjgb3-v.tfm \
tex-utfjgb3-v.vf \
tex-utfjgb4-h.tfm \
tex-utfjgb4-h.vf \
tex-utfjgb4-v.tfm \
tex-utfjgb4-v.vf \
tex-utfjgb5-h.tfm \
tex-utfjgb5-h.vf \
tex-utfjgb5-v.tfm \
tex-utfjgb5-v.vf \
tex-utfjgb6-h.tfm \
tex-utfjgb6-h.vf \
tex-utfjgb6-v.tfm \
tex-utfjgb6-v.vf \
tex-utfjgb7-h.tfm \
tex-utfjgb7-h.vf \
tex-utfjgb7-v.tfm \
tex-utfjgb7-v.vf \
tex-utfjgb8-h.tfm \
tex-utfjgb8-h.vf \
tex-utfjgb8-v.tfm \
tex-utfjgb8-v.vf \
tex-utfjgb9-h.tfm \
tex-utfjgb9-h.vf \
tex-utfjgb9-v.tfm \
tex-utfjgb9-v.vf \
tex-utfjgba-h.tfm \
tex-utfjgba-h.vf \
tex-utfjgba-v.tfm \
tex-utfjgba-v.vf \
tex-utfjgbb-h.tfm \
tex-utfjgbb-h.vf \
tex-utfjgbb-v.tfm \
tex-utfjgbb-v.vf \
tex-utfjgbc-h.tfm \
tex-utfjgbc-h.vf \
tex-utfjgbc-v.tfm \
tex-utfjgbc-v.vf \
tex-utfjgbd-h.tfm \
tex-utfjgbd-h.vf \
tex-utfjgbd-v.tfm \
tex-utfjgbd-v.vf \
tex-utfjgbe-h.tfm \
tex-utfjgbe-h.vf \
tex-utfjgbe-v.tfm \
tex-utfjgbe-v.vf \
tex-utfjgbf-h.tfm \
tex-utfjgbf-h.vf \
tex-utfjgbf-v.tfm \
tex-utfjgbf-v.vf \
tex-utfjgbg-h.tfm \
tex-utfjgbg-h.vf \
tex-utfjgbg-v.tfm \
tex-utfjgbg-v.vf \
tex-utfjgbj-h.tfm \
tex-utfjgbj-h.vf \
tex-utfjgbj-v.tfm \
tex-utfjgbj-v.vf \
tex-utfjgbk-h.tfm \
tex-utfjgbk-h.vf \
tex-utfjgbk-v.tfm \
tex-utfjgbk-v.vf \
tex-utfjgbl-h.tfm \
tex-utfjgbl-h.vf \
tex-utfjgbl-v.tfm \
tex-utfjgbl-v.vf \
tex-utfjgbm-h.tfm \
tex-utfjgbm-h.vf \
tex-utfjgbm-v.tfm \
tex-utfjgbm-v.vf \
tex-utfjgbn--h.tfm \
tex-utfjgbn--h.vf \
tex-utfjgbn--v.tfm \
tex-utfjgbn--v.vf \
tex-utfjgbn-h.tfm \
tex-utfjgbn-h.vf \
tex-utfjgbn-v.tfm \
tex-utfjgbn-v.vf \
tex-utfjgbn0-h.tfm \
tex-utfjgbn0-h.vf \
tex-utfjgbn0-v.tfm \
tex-utfjgbn0-v.vf \
tex-utfjgbn1-h.tfm \
tex-utfjgbn1-h.vf \
tex-utfjgbn1-v.tfm \
tex-utfjgbn1-v.vf \
tex-utfjgbn2-h.tfm \
tex-utfjgbn2-h.vf \
tex-utfjgbn2-v.tfm \
tex-utfjgbn2-v.vf \
tex-utfjgbn3-h.tfm \
tex-utfjgbn3-h.vf \
tex-utfjgbn3-v.tfm \
tex-utfjgbn3-v.vf \
tex-utfjgbn4-h.tfm \
tex-utfjgbn4-h.vf \
tex-utfjgbn4-v.tfm \
tex-utfjgbn4-v.vf \
tex-utfjgbn5-h.tfm \
tex-utfjgbn5-h.vf \
tex-utfjgbn5-v.tfm \
tex-utfjgbn5-v.vf \
tex-utfjgbn6-h.tfm \
tex-utfjgbn6-h.vf \
tex-utfjgbn6-v.tfm \
tex-utfjgbn6-v.vf \
tex-utfjgbn7-h.tfm \
tex-utfjgbn7-h.vf \
tex-utfjgbn7-v.tfm \
tex-utfjgbn7-v.vf \
tex-utfjgbn8-h.tfm \
tex-utfjgbn8-h.vf \
tex-utfjgbn8-v.tfm \
tex-utfjgbn8-v.vf \
tex-utfjgbn9-h.tfm \
tex-utfjgbn9-h.vf \
tex-utfjgbn9-v.tfm \
tex-utfjgbn9-v.vf \
tex-utfjgbna-h.tfm \
tex-utfjgbna-h.vf \
tex-utfjgbna-v.tfm \
tex-utfjgbna-v.vf \
tex-utfjgbnb-h.tfm \
tex-utfjgbnb-h.vf \
tex-utfjgbnb-v.tfm \
tex-utfjgbnb-v.vf \
tex-utfjgbnc-h.tfm \
tex-utfjgbnc-h.vf \
tex-utfjgbnc-v.tfm \
tex-utfjgbnc-v.vf \
tex-utfjgbnd-h.tfm \
tex-utfjgbnd-h.vf \
tex-utfjgbnd-v.tfm \
tex-utfjgbnd-v.vf \
tex-utfjgbne-h.tfm \
tex-utfjgbne-h.vf \
tex-utfjgbne-v.tfm \
tex-utfjgbne-v.vf \
tex-utfjgbnf-h.tfm \
tex-utfjgbnf-h.vf \
tex-utfjgbnf-v.tfm \
tex-utfjgbnf-v.vf \
tex-utfjgbo-h.tfm \
tex-utfjgbo-h.vf \
tex-utfjgbo-v.tfm \
tex-utfjgbo-v.vf \
tex-utfjgbp-h.tfm \
tex-utfjgbp-h.vf \
tex-utfjgbp-v.tfm \
tex-utfjgbp-v.vf \
tex-utfjgbq-h.tfm \
tex-utfjgbq-h.vf \
tex-utfjgbq-v.tfm \
tex-utfjgbq-v.vf \
tex-utfjgbr-h.tfm \
tex-utfjgbr-h.vf \
tex-utfjgbr-v.tfm \
tex-utfjgbr-v.vf \
tex-utfjgbs-h.tfm \
tex-utfjgbs-h.vf \
tex-utfjgbs-v.tfm \
tex-utfjgbs-v.vf \
tex-utfjgbt-h.tfm \
tex-utfjgbt-h.vf \
tex-utfjgbt-v.tfm \
tex-utfjgbt-v.vf \
tex-utfjgbu-h.tfm \
tex-utfjgbu-h.vf \
tex-utfjgbu-v.tfm \
tex-utfjgbu-v.vf \
tex-utfjgbv-h.tfm \
tex-utfjgbv-h.vf \
tex-utfjgbv-v.tfm \
tex-utfjgbv-v.vf \
tex-utfjgbx-h.tfm \
tex-utfjgbx-h.vf \
tex-utfjgbx-v.tfm \
tex-utfjgbx-v.vf \
tex-utfjgby-h.tfm \
tex-utfjgby-h.vf \
tex-utfjgby-v.tfm \
tex-utfjgby-v.vf \
tex-utfjgbz-h.tfm \
tex-utfjgbz-h.vf \
tex-utfjgbz-v.tfm \
tex-utfjgbz-v.vf \
tex-utfjge--h.tfm \
tex-utfjge--h.vf \
tex-utfjge--v.tfm \
tex-utfjge--v.vf \
tex-utfjge0-h.tfm \
tex-utfjge0-h.vf \
tex-utfjge0-v.tfm \
tex-utfjge0-v.vf \
tex-utfjge1-h.tfm \
tex-utfjge1-h.vf \
tex-utfjge1-v.tfm \
tex-utfjge1-v.vf \
tex-utfjge2-h.tfm \
tex-utfjge2-h.vf \
tex-utfjge2-v.tfm \
tex-utfjge2-v.vf \
tex-utfjge3-h.tfm \
tex-utfjge3-h.vf \
tex-utfjge3-v.tfm \
tex-utfjge3-v.vf \
tex-utfjge4-h.tfm \
tex-utfjge4-h.vf \
tex-utfjge4-v.tfm \
tex-utfjge4-v.vf \
tex-utfjge5-h.tfm \
tex-utfjge5-h.vf \
tex-utfjge5-v.tfm \
tex-utfjge5-v.vf \
tex-utfjge6-h.tfm \
tex-utfjge6-h.vf \
tex-utfjge6-v.tfm \
tex-utfjge6-v.vf \
tex-utfjge7-h.tfm \
tex-utfjge7-h.vf \
tex-utfjge7-v.tfm \
tex-utfjge7-v.vf \
tex-utfjge8-h.tfm \
tex-utfjge8-h.vf \
tex-utfjge8-v.tfm \
tex-utfjge8-v.vf \
tex-utfjge9-h.tfm \
tex-utfjge9-h.vf \
tex-utfjge9-v.tfm \
tex-utfjge9-v.vf \
tex-utfjgea-h.tfm \
tex-utfjgea-h.vf \
tex-utfjgea-v.tfm \
tex-utfjgea-v.vf \
tex-utfjgeb-h.tfm \
tex-utfjgeb-h.vf \
tex-utfjgeb-v.tfm \
tex-utfjgeb-v.vf \
tex-utfjgec-h.tfm \
tex-utfjgec-h.vf \
tex-utfjgec-v.tfm \
tex-utfjgec-v.vf \
tex-utfjged-h.tfm \
tex-utfjged-h.vf \
tex-utfjged-v.tfm \
tex-utfjged-v.vf \
tex-utfjgee-h.tfm \
tex-utfjgee-h.vf \
tex-utfjgee-v.tfm \
tex-utfjgee-v.vf \
tex-utfjgef-h.tfm \
tex-utfjgef-h.vf \
tex-utfjgef-v.tfm \
tex-utfjgef-v.vf \
tex-utfjgeg-h.tfm \
tex-utfjgeg-h.vf \
tex-utfjgeg-v.tfm \
tex-utfjgeg-v.vf \
tex-utfjgej-h.tfm \
tex-utfjgej-h.vf \
tex-utfjgej-v.tfm \
tex-utfjgej-v.vf \
tex-utfjgek-h.tfm \
tex-utfjgek-h.vf \
tex-utfjgek-v.tfm \
tex-utfjgek-v.vf \
tex-utfjgel-h.tfm \
tex-utfjgel-h.vf \
tex-utfjgel-v.tfm \
tex-utfjgel-v.vf \
tex-utfjgem-h.tfm \
tex-utfjgem-h.vf \
tex-utfjgem-v.tfm \
tex-utfjgem-v.vf \
tex-utfjgen--h.tfm \
tex-utfjgen--h.vf \
tex-utfjgen--v.tfm \
tex-utfjgen--v.vf \
tex-utfjgen-h.tfm \
tex-utfjgen-h.vf \
tex-utfjgen-v.tfm \
tex-utfjgen-v.vf \
tex-utfjgen0-h.tfm \
tex-utfjgen0-h.vf \
tex-utfjgen0-v.tfm \
tex-utfjgen0-v.vf \
tex-utfjgen1-h.tfm \
tex-utfjgen1-h.vf \
tex-utfjgen1-v.tfm \
tex-utfjgen1-v.vf \
tex-utfjgen2-h.tfm \
tex-utfjgen2-h.vf \
tex-utfjgen2-v.tfm \
tex-utfjgen2-v.vf \
tex-utfjgen3-h.tfm \
tex-utfjgen3-h.vf \
tex-utfjgen3-v.tfm \
tex-utfjgen3-v.vf \
tex-utfjgen4-h.tfm \
tex-utfjgen4-h.vf \
tex-utfjgen4-v.tfm \
tex-utfjgen4-v.vf \
tex-utfjgen5-h.tfm \
tex-utfjgen5-h.vf \
tex-utfjgen5-v.tfm \
tex-utfjgen5-v.vf \
tex-utfjgen6-h.tfm \
tex-utfjgen6-h.vf \
tex-utfjgen6-v.tfm \
tex-utfjgen6-v.vf \
tex-utfjgen7-h.tfm \
tex-utfjgen7-h.vf \
tex-utfjgen7-v.tfm \
tex-utfjgen7-v.vf \
tex-utfjgen8-h.tfm \
tex-utfjgen8-h.vf \
tex-utfjgen8-v.tfm \
tex-utfjgen8-v.vf \
tex-utfjgen9-h.tfm \
tex-utfjgen9-h.vf \
tex-utfjgen9-v.tfm \
tex-utfjgen9-v.vf \
tex-utfjgena-h.tfm \
tex-utfjgena-h.vf \
tex-utfjgena-v.tfm \
tex-utfjgena-v.vf \
tex-utfjgenb-h.tfm \
tex-utfjgenb-h.vf \
tex-utfjgenb-v.tfm \
tex-utfjgenb-v.vf \
tex-utfjgenc-h.tfm \
tex-utfjgenc-h.vf \
tex-utfjgenc-v.tfm \
tex-utfjgenc-v.vf \
tex-utfjgend-h.tfm \
tex-utfjgend-h.vf \
tex-utfjgend-v.tfm \
tex-utfjgend-v.vf \
tex-utfjgene-h.tfm \
tex-utfjgene-h.vf \
tex-utfjgene-v.tfm \
tex-utfjgene-v.vf \
tex-utfjgenf-h.tfm \
tex-utfjgenf-h.vf \
tex-utfjgenf-v.tfm \
tex-utfjgenf-v.vf \
tex-utfjgeo-h.tfm \
tex-utfjgeo-h.vf \
tex-utfjgeo-v.tfm \
tex-utfjgeo-v.vf \
tex-utfjgep-h.tfm \
tex-utfjgep-h.vf \
tex-utfjgep-v.tfm \
tex-utfjgep-v.vf \
tex-utfjgeq-h.tfm \
tex-utfjgeq-h.vf \
tex-utfjgeq-v.tfm \
tex-utfjgeq-v.vf \
tex-utfjger-h.tfm \
tex-utfjger-h.vf \
tex-utfjger-v.tfm \
tex-utfjger-v.vf \
tex-utfjges-h.tfm \
tex-utfjges-h.vf \
tex-utfjges-v.tfm \
tex-utfjges-v.vf \
tex-utfjget-h.tfm \
tex-utfjget-h.vf \
tex-utfjget-v.tfm \
tex-utfjget-v.vf \
tex-utfjgeu-h.tfm \
tex-utfjgeu-h.vf \
tex-utfjgeu-v.tfm \
tex-utfjgeu-v.vf \
tex-utfjgev-h.tfm \
tex-utfjgev-h.vf \
tex-utfjgev-v.tfm \
tex-utfjgev-v.vf \
tex-utfjgex-h.tfm \
tex-utfjgex-h.vf \
tex-utfjgex-v.tfm \
tex-utfjgex-v.vf \
tex-utfjgey-h.tfm \
tex-utfjgey-h.vf \
tex-utfjgey-v.tfm \
tex-utfjgey-v.vf \
tex-utfjgez-h.tfm \
tex-utfjgez-h.vf \
tex-utfjgez-v.tfm \
tex-utfjgez-v.vf \
tex-utfjgr--h.tfm \
tex-utfjgr--h.vf \
tex-utfjgr--v.tfm \
tex-utfjgr--v.vf \
tex-utfjgr0-h.tfm \
tex-utfjgr0-h.vf \
tex-utfjgr0-v.tfm \
tex-utfjgr0-v.vf \
tex-utfjgr1-h.tfm \
tex-utfjgr1-h.vf \
tex-utfjgr1-v.tfm \
tex-utfjgr1-v.vf \
tex-utfjgr2-h.tfm \
tex-utfjgr2-h.vf \
tex-utfjgr2-v.tfm \
tex-utfjgr2-v.vf \
tex-utfjgr3-h.tfm \
tex-utfjgr3-h.vf \
tex-utfjgr3-v.tfm \
tex-utfjgr3-v.vf \
tex-utfjgr4-h.tfm \
tex-utfjgr4-h.vf \
tex-utfjgr4-v.tfm \
tex-utfjgr4-v.vf \
tex-utfjgr5-h.tfm \
tex-utfjgr5-h.vf \
tex-utfjgr5-v.tfm \
tex-utfjgr5-v.vf \
tex-utfjgr6-h.tfm \
tex-utfjgr6-h.vf \
tex-utfjgr6-v.tfm \
tex-utfjgr6-v.vf \
tex-utfjgr7-h.tfm \
tex-utfjgr7-h.vf \
tex-utfjgr7-v.tfm \
tex-utfjgr7-v.vf \
tex-utfjgr8-h.tfm \
tex-utfjgr8-h.vf \
tex-utfjgr8-v.tfm \
tex-utfjgr8-v.vf \
tex-utfjgr9-h.tfm \
tex-utfjgr9-h.vf \
tex-utfjgr9-v.tfm \
tex-utfjgr9-v.vf \
tex-utfjgra-h.tfm \
tex-utfjgra-h.vf \
tex-utfjgra-v.tfm \
tex-utfjgra-v.vf \
tex-utfjgrb-h.tfm \
tex-utfjgrb-h.vf \
tex-utfjgrb-v.tfm \
tex-utfjgrb-v.vf \
tex-utfjgrc-h.tfm \
tex-utfjgrc-h.vf \
tex-utfjgrc-v.tfm \
tex-utfjgrc-v.vf \
tex-utfjgrd-h.tfm \
tex-utfjgrd-h.vf \
tex-utfjgrd-v.tfm \
tex-utfjgrd-v.vf \
tex-utfjgre-h.tfm \
tex-utfjgre-h.vf \
tex-utfjgre-v.tfm \
tex-utfjgre-v.vf \
tex-utfjgrf-h.tfm \
tex-utfjgrf-h.vf \
tex-utfjgrf-v.tfm \
tex-utfjgrf-v.vf \
tex-utfjgrg-h.tfm \
tex-utfjgrg-h.vf \
tex-utfjgrg-v.tfm \
tex-utfjgrg-v.vf \
tex-utfjgrj-h.tfm \
tex-utfjgrj-h.vf \
tex-utfjgrj-v.tfm \
tex-utfjgrj-v.vf \
tex-utfjgrk-h.tfm \
tex-utfjgrk-h.vf \
tex-utfjgrk-v.tfm \
tex-utfjgrk-v.vf \
tex-utfjgrl-h.tfm \
tex-utfjgrl-h.vf \
tex-utfjgrl-v.tfm \
tex-utfjgrl-v.vf \
tex-utfjgrm-h.tfm \
tex-utfjgrm-h.vf \
tex-utfjgrm-v.tfm \
tex-utfjgrm-v.vf \
tex-utfjgrn--h.tfm \
tex-utfjgrn--h.vf \
tex-utfjgrn--v.tfm \
tex-utfjgrn--v.vf \
tex-utfjgrn-h.tfm \
tex-utfjgrn-h.vf \
tex-utfjgrn-v.tfm \
tex-utfjgrn-v.vf \
tex-utfjgrn0-h.tfm \
tex-utfjgrn0-h.vf \
tex-utfjgrn0-v.tfm \
tex-utfjgrn0-v.vf \
tex-utfjgrn1-h.tfm \
tex-utfjgrn1-h.vf \
tex-utfjgrn1-v.tfm \
tex-utfjgrn1-v.vf \
tex-utfjgrn2-h.tfm \
tex-utfjgrn2-h.vf \
tex-utfjgrn2-v.tfm \
tex-utfjgrn2-v.vf \
tex-utfjgrn3-h.tfm \
tex-utfjgrn3-h.vf \
tex-utfjgrn3-v.tfm \
tex-utfjgrn3-v.vf \
tex-utfjgrn4-h.tfm \
tex-utfjgrn4-h.vf \
tex-utfjgrn4-v.tfm \
tex-utfjgrn4-v.vf \
tex-utfjgrn5-h.tfm \
tex-utfjgrn5-h.vf \
tex-utfjgrn5-v.tfm \
tex-utfjgrn5-v.vf \
tex-utfjgrn6-h.tfm \
tex-utfjgrn6-h.vf \
tex-utfjgrn6-v.tfm \
tex-utfjgrn6-v.vf \
tex-utfjgrn7-h.tfm \
tex-utfjgrn7-h.vf \
tex-utfjgrn7-v.tfm \
tex-utfjgrn7-v.vf \
tex-utfjgrn8-h.tfm \
tex-utfjgrn8-h.vf \
tex-utfjgrn8-v.tfm \
tex-utfjgrn8-v.vf \
tex-utfjgrn9-h.tfm \
tex-utfjgrn9-h.vf \
tex-utfjgrn9-v.tfm \
tex-utfjgrn9-v.vf \
tex-utfjgrna-h.tfm \
tex-utfjgrna-h.vf \
tex-utfjgrna-v.tfm \
tex-utfjgrna-v.vf \
tex-utfjgrnb-h.tfm \
tex-utfjgrnb-h.vf \
tex-utfjgrnb-v.tfm \
tex-utfjgrnb-v.vf \
tex-utfjgrnc-h.tfm \
tex-utfjgrnc-h.vf \
tex-utfjgrnc-v.tfm \
tex-utfjgrnc-v.vf \
tex-utfjgrnd-h.tfm \
tex-utfjgrnd-h.vf \
tex-utfjgrnd-v.tfm \
tex-utfjgrnd-v.vf \
tex-utfjgrne-h.tfm \
tex-utfjgrne-h.vf \
tex-utfjgrne-v.tfm \
tex-utfjgrne-v.vf \
tex-utfjgrnf-h.tfm \
tex-utfjgrnf-h.vf \
tex-utfjgrnf-v.tfm \
tex-utfjgrnf-v.vf \
tex-utfjgro-h.tfm \
tex-utfjgro-h.vf \
tex-utfjgro-v.tfm \
tex-utfjgro-v.vf \
tex-utfjgrp-h.tfm \
tex-utfjgrp-h.vf \
tex-utfjgrp-v.tfm \
tex-utfjgrp-v.vf \
tex-utfjgrq-h.tfm \
tex-utfjgrq-h.vf \
tex-utfjgrq-v.tfm \
tex-utfjgrq-v.vf \
tex-utfjgrr-h.tfm \
tex-utfjgrr-h.vf \
tex-utfjgrr-v.tfm \
tex-utfjgrr-v.vf \
tex-utfjgrs-h.tfm \
tex-utfjgrs-h.vf \
tex-utfjgrs-v.tfm \
tex-utfjgrs-v.vf \
tex-utfjgrt-h.tfm \
tex-utfjgrt-h.vf \
tex-utfjgrt-v.tfm \
tex-utfjgrt-v.vf \
tex-utfjgru-h.tfm \
tex-utfjgru-h.vf \
tex-utfjgru-v.tfm \
tex-utfjgru-v.vf \
tex-utfjgrv-h.tfm \
tex-utfjgrv-h.vf \
tex-utfjgrv-v.tfm \
tex-utfjgrv-v.vf \
tex-utfjgrx-h.tfm \
tex-utfjgrx-h.vf \
tex-utfjgrx-v.tfm \
tex-utfjgrx-v.vf \
tex-utfjgry-h.tfm \
tex-utfjgry-h.vf \
tex-utfjgry-v.tfm \
tex-utfjgry-v.vf \
tex-utfjgrz-h.tfm \
tex-utfjgrz-h.vf \
tex-utfjgrz-v.tfm \
tex-utfjgrz-v.vf \
tex-utfjmb--h.tfm \
tex-utfjmb--h.vf \
tex-utfjmb--v.tfm \
tex-utfjmb--v.vf \
tex-utfjmb0-h.tfm \
tex-utfjmb0-h.vf \
tex-utfjmb0-v.tfm \
tex-utfjmb0-v.vf \
tex-utfjmb1-h.tfm \
tex-utfjmb1-h.vf \
tex-utfjmb1-v.tfm \
tex-utfjmb1-v.vf \
tex-utfjmb2-h.tfm \
tex-utfjmb2-h.vf \
tex-utfjmb2-v.tfm \
tex-utfjmb2-v.vf \
tex-utfjmb3-h.tfm \
tex-utfjmb3-h.vf \
tex-utfjmb3-v.tfm \
tex-utfjmb3-v.vf \
tex-utfjmb4-h.tfm \
tex-utfjmb4-h.vf \
tex-utfjmb4-v.tfm \
tex-utfjmb4-v.vf \
tex-utfjmb5-h.tfm \
tex-utfjmb5-h.vf \
tex-utfjmb5-v.tfm \
tex-utfjmb5-v.vf \
tex-utfjmb6-h.tfm \
tex-utfjmb6-h.vf \
tex-utfjmb6-v.tfm \
tex-utfjmb6-v.vf \
tex-utfjmb7-h.tfm \
tex-utfjmb7-h.vf \
tex-utfjmb7-v.tfm \
tex-utfjmb7-v.vf \
tex-utfjmb8-h.tfm \
tex-utfjmb8-h.vf \
tex-utfjmb8-v.tfm \
tex-utfjmb8-v.vf \
tex-utfjmb9-h.tfm \
tex-utfjmb9-h.vf \
tex-utfjmb9-v.tfm \
tex-utfjmb9-v.vf \
tex-utfjmba-h.tfm \
tex-utfjmba-h.vf \
tex-utfjmba-v.tfm \
tex-utfjmba-v.vf \
tex-utfjmbb-h.tfm \
tex-utfjmbb-h.vf \
tex-utfjmbb-v.tfm \
tex-utfjmbb-v.vf \
tex-utfjmbc-h.tfm \
tex-utfjmbc-h.vf \
tex-utfjmbc-v.tfm \
tex-utfjmbc-v.vf \
tex-utfjmbd-h.tfm \
tex-utfjmbd-h.vf \
tex-utfjmbd-v.tfm \
tex-utfjmbd-v.vf \
tex-utfjmbe-h.tfm \
tex-utfjmbe-h.vf \
tex-utfjmbe-v.tfm \
tex-utfjmbe-v.vf \
tex-utfjmbf-h.tfm \
tex-utfjmbf-h.vf \
tex-utfjmbf-v.tfm \
tex-utfjmbf-v.vf \
tex-utfjmbg-h.tfm \
tex-utfjmbg-h.vf \
tex-utfjmbg-v.tfm \
tex-utfjmbg-v.vf \
tex-utfjmbj-h.tfm \
tex-utfjmbj-h.vf \
tex-utfjmbj-v.tfm \
tex-utfjmbj-v.vf \
tex-utfjmbk-h.tfm \
tex-utfjmbk-h.vf \
tex-utfjmbk-v.tfm \
tex-utfjmbk-v.vf \
tex-utfjmbl-h.tfm \
tex-utfjmbl-h.vf \
tex-utfjmbl-v.tfm \
tex-utfjmbl-v.vf \
tex-utfjmbm-h.tfm \
tex-utfjmbm-h.vf \
tex-utfjmbm-v.tfm \
tex-utfjmbm-v.vf \
tex-utfjmbn--h.tfm \
tex-utfjmbn--h.vf \
tex-utfjmbn--v.tfm \
tex-utfjmbn--v.vf \
tex-utfjmbn-h.tfm \
tex-utfjmbn-h.vf \
tex-utfjmbn-v.tfm \
tex-utfjmbn-v.vf \
tex-utfjmbn0-h.tfm \
tex-utfjmbn0-h.vf \
tex-utfjmbn0-v.tfm \
tex-utfjmbn0-v.vf \
tex-utfjmbn1-h.tfm \
tex-utfjmbn1-h.vf \
tex-utfjmbn1-v.tfm \
tex-utfjmbn1-v.vf \
tex-utfjmbn2-h.tfm \
tex-utfjmbn2-h.vf \
tex-utfjmbn2-v.tfm \
tex-utfjmbn2-v.vf \
tex-utfjmbn3-h.tfm \
tex-utfjmbn3-h.vf \
tex-utfjmbn3-v.tfm \
tex-utfjmbn3-v.vf \
tex-utfjmbn4-h.tfm \
tex-utfjmbn4-h.vf \
tex-utfjmbn4-v.tfm \
tex-utfjmbn4-v.vf \
tex-utfjmbn5-h.tfm \
tex-utfjmbn5-h.vf \
tex-utfjmbn5-v.tfm \
tex-utfjmbn5-v.vf \
tex-utfjmbn6-h.tfm \
tex-utfjmbn6-h.vf \
tex-utfjmbn6-v.tfm \
tex-utfjmbn6-v.vf \
tex-utfjmbn7-h.tfm \
tex-utfjmbn7-h.vf \
tex-utfjmbn7-v.tfm \
tex-utfjmbn7-v.vf \
tex-utfjmbn8-h.tfm \
tex-utfjmbn8-h.vf \
tex-utfjmbn8-v.tfm \
tex-utfjmbn8-v.vf \
tex-utfjmbn9-h.tfm \
tex-utfjmbn9-h.vf \
tex-utfjmbn9-v.tfm \
tex-utfjmbn9-v.vf \
tex-utfjmbna-h.tfm \
tex-utfjmbna-h.vf \
tex-utfjmbna-v.tfm \
tex-utfjmbna-v.vf \
tex-utfjmbnb-h.tfm \
tex-utfjmbnb-h.vf \
tex-utfjmbnb-v.tfm \
tex-utfjmbnb-v.vf \
tex-utfjmbnc-h.tfm \
tex-utfjmbnc-h.vf \
tex-utfjmbnc-v.tfm \
tex-utfjmbnc-v.vf \
tex-utfjmbnd-h.tfm \
tex-utfjmbnd-h.vf \
tex-utfjmbnd-v.tfm \
tex-utfjmbnd-v.vf \
tex-utfjmbne-h.tfm \
tex-utfjmbne-h.vf \
tex-utfjmbne-v.tfm \
tex-utfjmbne-v.vf \
tex-utfjmbnf-h.tfm \
tex-utfjmbnf-h.vf \
tex-utfjmbnf-v.tfm \
tex-utfjmbnf-v.vf \
tex-utfjmbo-h.tfm \
tex-utfjmbo-h.vf \
tex-utfjmbo-v.tfm \
tex-utfjmbo-v.vf \
tex-utfjmbp-h.tfm \
tex-utfjmbp-h.vf \
tex-utfjmbp-v.tfm \
tex-utfjmbp-v.vf \
tex-utfjmbq-h.tfm \
tex-utfjmbq-h.vf \
tex-utfjmbq-v.tfm \
tex-utfjmbq-v.vf \
tex-utfjmbr-h.tfm \
tex-utfjmbr-h.vf \
tex-utfjmbr-v.tfm \
tex-utfjmbr-v.vf \
tex-utfjmbs-h.tfm \
tex-utfjmbs-h.vf \
tex-utfjmbs-v.tfm \
tex-utfjmbs-v.vf \
tex-utfjmbt-h.tfm \
tex-utfjmbt-h.vf \
tex-utfjmbt-v.tfm \
tex-utfjmbt-v.vf \
tex-utfjmbu-h.tfm \
tex-utfjmbu-h.vf \
tex-utfjmbu-v.tfm \
tex-utfjmbu-v.vf \
tex-utfjmbv-h.tfm \
tex-utfjmbv-h.vf \
tex-utfjmbv-v.tfm \
tex-utfjmbv-v.vf \
tex-utfjmbx-h.tfm \
tex-utfjmbx-h.vf \
tex-utfjmbx-v.tfm \
tex-utfjmbx-v.vf \
tex-utfjmby-h.tfm \
tex-utfjmby-h.vf \
tex-utfjmby-v.tfm \
tex-utfjmby-v.vf \
tex-utfjmbz-h.tfm \
tex-utfjmbz-h.vf \
tex-utfjmbz-v.tfm \
tex-utfjmbz-v.vf \
tex-utfjmgr--h.tfm \
tex-utfjmgr--h.vf \
tex-utfjmgr--v.tfm \
tex-utfjmgr--v.vf \
tex-utfjmgr0-h.tfm \
tex-utfjmgr0-h.vf \
tex-utfjmgr0-v.tfm \
tex-utfjmgr0-v.vf \
tex-utfjmgr1-h.tfm \
tex-utfjmgr1-h.vf \
tex-utfjmgr1-v.tfm \
tex-utfjmgr1-v.vf \
tex-utfjmgr2-h.tfm \
tex-utfjmgr2-h.vf \
tex-utfjmgr2-v.tfm \
tex-utfjmgr2-v.vf \
tex-utfjmgr3-h.tfm \
tex-utfjmgr3-h.vf \
tex-utfjmgr3-v.tfm \
tex-utfjmgr3-v.vf \
tex-utfjmgr4-h.tfm \
tex-utfjmgr4-h.vf \
tex-utfjmgr4-v.tfm \
tex-utfjmgr4-v.vf \
tex-utfjmgr5-h.tfm \
tex-utfjmgr5-h.vf \
tex-utfjmgr5-v.tfm \
tex-utfjmgr5-v.vf \
tex-utfjmgr6-h.tfm \
tex-utfjmgr6-h.vf \
tex-utfjmgr6-v.tfm \
tex-utfjmgr6-v.vf \
tex-utfjmgr7-h.tfm \
tex-utfjmgr7-h.vf \
tex-utfjmgr7-v.tfm \
tex-utfjmgr7-v.vf \
tex-utfjmgr8-h.tfm \
tex-utfjmgr8-h.vf \
tex-utfjmgr8-v.tfm \
tex-utfjmgr8-v.vf \
tex-utfjmgr9-h.tfm \
tex-utfjmgr9-h.vf \
tex-utfjmgr9-v.tfm \
tex-utfjmgr9-v.vf \
tex-utfjmgra-h.tfm \
tex-utfjmgra-h.vf \
tex-utfjmgra-v.tfm \
tex-utfjmgra-v.vf \
tex-utfjmgrb-h.tfm \
tex-utfjmgrb-h.vf \
tex-utfjmgrb-v.tfm \
tex-utfjmgrb-v.vf \
tex-utfjmgrc-h.tfm \
tex-utfjmgrc-h.vf \
tex-utfjmgrc-v.tfm \
tex-utfjmgrc-v.vf \
tex-utfjmgrd-h.tfm \
tex-utfjmgrd-h.vf \
tex-utfjmgrd-v.tfm \
tex-utfjmgrd-v.vf \
tex-utfjmgre-h.tfm \
tex-utfjmgre-h.vf \
tex-utfjmgre-v.tfm \
tex-utfjmgre-v.vf \
tex-utfjmgrf-h.tfm \
tex-utfjmgrf-h.vf \
tex-utfjmgrf-v.tfm \
tex-utfjmgrf-v.vf \
tex-utfjmgrg-h.tfm \
tex-utfjmgrg-h.vf \
tex-utfjmgrg-v.tfm \
tex-utfjmgrg-v.vf \
tex-utfjmgrj-h.tfm \
tex-utfjmgrj-h.vf \
tex-utfjmgrj-v.tfm \
tex-utfjmgrj-v.vf \
tex-utfjmgrk-h.tfm \
tex-utfjmgrk-h.vf \
tex-utfjmgrk-v.tfm \
tex-utfjmgrk-v.vf \
tex-utfjmgrl-h.tfm \
tex-utfjmgrl-h.vf \
tex-utfjmgrl-v.tfm \
tex-utfjmgrl-v.vf \
tex-utfjmgrm-h.tfm \
tex-utfjmgrm-h.vf \
tex-utfjmgrm-v.tfm \
tex-utfjmgrm-v.vf \
tex-utfjmgrn--h.tfm \
tex-utfjmgrn--h.vf \
tex-utfjmgrn--v.tfm \
tex-utfjmgrn--v.vf \
tex-utfjmgrn-h.tfm \
tex-utfjmgrn-h.vf \
tex-utfjmgrn-v.tfm \
tex-utfjmgrn-v.vf \
tex-utfjmgrn0-h.tfm \
tex-utfjmgrn0-h.vf \
tex-utfjmgrn0-v.tfm \
tex-utfjmgrn0-v.vf \
tex-utfjmgrn1-h.tfm \
tex-utfjmgrn1-h.vf \
tex-utfjmgrn1-v.tfm \
tex-utfjmgrn1-v.vf \
tex-utfjmgrn2-h.tfm \
tex-utfjmgrn2-h.vf \
tex-utfjmgrn2-v.tfm \
tex-utfjmgrn2-v.vf \
tex-utfjmgrn3-h.tfm \
tex-utfjmgrn3-h.vf \
tex-utfjmgrn3-v.tfm \
tex-utfjmgrn3-v.vf \
tex-utfjmgrn4-h.tfm \
tex-utfjmgrn4-h.vf \
tex-utfjmgrn4-v.tfm \
tex-utfjmgrn4-v.vf \
tex-utfjmgrn5-h.tfm \
tex-utfjmgrn5-h.vf \
tex-utfjmgrn5-v.tfm \
tex-utfjmgrn5-v.vf \
tex-utfjmgrn6-h.tfm \
tex-utfjmgrn6-h.vf \
tex-utfjmgrn6-v.tfm \
tex-utfjmgrn6-v.vf \
tex-utfjmgrn7-h.tfm \
tex-utfjmgrn7-h.vf \
tex-utfjmgrn7-v.tfm \
tex-utfjmgrn7-v.vf \
tex-utfjmgrn8-h.tfm \
tex-utfjmgrn8-h.vf \
tex-utfjmgrn8-v.tfm \
tex-utfjmgrn8-v.vf \
tex-utfjmgrn9-h.tfm \
tex-utfjmgrn9-h.vf \
tex-utfjmgrn9-v.tfm \
tex-utfjmgrn9-v.vf \
tex-utfjmgrna-h.tfm \
tex-utfjmgrna-h.vf \
tex-utfjmgrna-v.tfm \
tex-utfjmgrna-v.vf \
tex-utfjmgrnb-h.tfm \
tex-utfjmgrnb-h.vf \
tex-utfjmgrnb-v.tfm \
tex-utfjmgrnb-v.vf \
tex-utfjmgrnc-h.tfm \
tex-utfjmgrnc-h.vf \
tex-utfjmgrnc-v.tfm \
tex-utfjmgrnc-v.vf \
tex-utfjmgrnd-h.tfm \
tex-utfjmgrnd-h.vf \
tex-utfjmgrnd-v.tfm \
tex-utfjmgrnd-v.vf \
tex-utfjmgrne-h.tfm \
tex-utfjmgrne-h.vf \
tex-utfjmgrne-v.tfm \
tex-utfjmgrne-v.vf \
tex-utfjmgrnf-h.tfm \
tex-utfjmgrnf-h.vf \
tex-utfjmgrnf-v.tfm \
tex-utfjmgrnf-v.vf \
tex-utfjmgro-h.tfm \
tex-utfjmgro-h.vf \
tex-utfjmgro-v.tfm \
tex-utfjmgro-v.vf \
tex-utfjmgrp-h.tfm \
tex-utfjmgrp-h.vf \
tex-utfjmgrp-v.tfm \
tex-utfjmgrp-v.vf \
tex-utfjmgrq-h.tfm \
tex-utfjmgrq-h.vf \
tex-utfjmgrq-v.tfm \
tex-utfjmgrq-v.vf \
tex-utfjmgrr-h.tfm \
tex-utfjmgrr-h.vf \
tex-utfjmgrr-v.tfm \
tex-utfjmgrr-v.vf \
tex-utfjmgrs-h.tfm \
tex-utfjmgrs-h.vf \
tex-utfjmgrs-v.tfm \
tex-utfjmgrs-v.vf \
tex-utfjmgrt-h.tfm \
tex-utfjmgrt-h.vf \
tex-utfjmgrt-v.tfm \
tex-utfjmgrt-v.vf \
tex-utfjmgru-h.tfm \
tex-utfjmgru-h.vf \
tex-utfjmgru-v.tfm \
tex-utfjmgru-v.vf \
tex-utfjmgrv-h.tfm \
tex-utfjmgrv-h.vf \
tex-utfjmgrv-v.tfm \
tex-utfjmgrv-v.vf \
tex-utfjmgrx-h.tfm \
tex-utfjmgrx-h.vf \
tex-utfjmgrx-v.tfm \
tex-utfjmgrx-v.vf \
tex-utfjmgry-h.tfm \
tex-utfjmgry-h.vf \
tex-utfjmgry-v.tfm \
tex-utfjmgry-v.vf \
tex-utfjmgrz-h.tfm \
tex-utfjmgrz-h.vf \
tex-utfjmgrz-v.tfm \
tex-utfjmgrz-v.vf \
tex-utfjml--h.tfm \
tex-utfjml--h.vf \
tex-utfjml--v.tfm \
tex-utfjml--v.vf \
tex-utfjml0-h.tfm \
tex-utfjml0-h.vf \
tex-utfjml0-v.tfm \
tex-utfjml0-v.vf \
tex-utfjml1-h.tfm \
tex-utfjml1-h.vf \
tex-utfjml1-v.tfm \
tex-utfjml1-v.vf \
tex-utfjml2-h.tfm \
tex-utfjml2-h.vf \
tex-utfjml2-v.tfm \
tex-utfjml2-v.vf \
tex-utfjml3-h.tfm \
tex-utfjml3-h.vf \
tex-utfjml3-v.tfm \
tex-utfjml3-v.vf \
tex-utfjml4-h.tfm \
tex-utfjml4-h.vf \
tex-utfjml4-v.tfm \
tex-utfjml4-v.vf \
tex-utfjml5-h.tfm \
tex-utfjml5-h.vf \
tex-utfjml5-v.tfm \
tex-utfjml5-v.vf \
tex-utfjml6-h.tfm \
tex-utfjml6-h.vf \
tex-utfjml6-v.tfm \
tex-utfjml6-v.vf \
tex-utfjml7-h.tfm \
tex-utfjml7-h.vf \
tex-utfjml7-v.tfm \
tex-utfjml7-v.vf \
tex-utfjml8-h.tfm \
tex-utfjml8-h.vf \
tex-utfjml8-v.tfm \
tex-utfjml8-v.vf \
tex-utfjml9-h.tfm \
tex-utfjml9-h.vf \
tex-utfjml9-v.tfm \
tex-utfjml9-v.vf \
tex-utfjmla-h.tfm \
tex-utfjmla-h.vf \
tex-utfjmla-v.tfm \
tex-utfjmla-v.vf \
tex-utfjmlb-h.tfm \
tex-utfjmlb-h.vf \
tex-utfjmlb-v.tfm \
tex-utfjmlb-v.vf \
tex-utfjmlc-h.tfm \
tex-utfjmlc-h.vf \
tex-utfjmlc-v.tfm \
tex-utfjmlc-v.vf \
tex-utfjmld-h.tfm \
tex-utfjmld-h.vf \
tex-utfjmld-v.tfm \
tex-utfjmld-v.vf \
tex-utfjmle-h.tfm \
tex-utfjmle-h.vf \
tex-utfjmle-v.tfm \
tex-utfjmle-v.vf \
tex-utfjmlf-h.tfm \
tex-utfjmlf-h.vf \
tex-utfjmlf-v.tfm \
tex-utfjmlf-v.vf \
tex-utfjmlg-h.tfm \
tex-utfjmlg-h.vf \
tex-utfjmlg-v.tfm \
tex-utfjmlg-v.vf \
tex-utfjmlj-h.tfm \
tex-utfjmlj-h.vf \
tex-utfjmlj-v.tfm \
tex-utfjmlj-v.vf \
tex-utfjmlk-h.tfm \
tex-utfjmlk-h.vf \
tex-utfjmlk-v.tfm \
tex-utfjmlk-v.vf \
tex-utfjmll-h.tfm \
tex-utfjmll-h.vf \
tex-utfjmll-v.tfm \
tex-utfjmll-v.vf \
tex-utfjmlm-h.tfm \
tex-utfjmlm-h.vf \
tex-utfjmlm-v.tfm \
tex-utfjmlm-v.vf \
tex-utfjmln--h.tfm \
tex-utfjmln--h.vf \
tex-utfjmln--v.tfm \
tex-utfjmln--v.vf \
tex-utfjmln-h.tfm \
tex-utfjmln-h.vf \
tex-utfjmln-v.tfm \
tex-utfjmln-v.vf \
tex-utfjmln0-h.tfm \
tex-utfjmln0-h.vf \
tex-utfjmln0-v.tfm \
tex-utfjmln0-v.vf \
tex-utfjmln1-h.tfm \
tex-utfjmln1-h.vf \
tex-utfjmln1-v.tfm \
tex-utfjmln1-v.vf \
tex-utfjmln2-h.tfm \
tex-utfjmln2-h.vf \
tex-utfjmln2-v.tfm \
tex-utfjmln2-v.vf \
tex-utfjmln3-h.tfm \
tex-utfjmln3-h.vf \
tex-utfjmln3-v.tfm \
tex-utfjmln3-v.vf \
tex-utfjmln4-h.tfm \
tex-utfjmln4-h.vf \
tex-utfjmln4-v.tfm \
tex-utfjmln4-v.vf \
tex-utfjmln5-h.tfm \
tex-utfjmln5-h.vf \
tex-utfjmln5-v.tfm \
tex-utfjmln5-v.vf \
tex-utfjmln6-h.tfm \
tex-utfjmln6-h.vf \
tex-utfjmln6-v.tfm \
tex-utfjmln6-v.vf \
tex-utfjmln7-h.tfm \
tex-utfjmln7-h.vf \
tex-utfjmln7-v.tfm \
tex-utfjmln7-v.vf \
tex-utfjmln8-h.tfm \
tex-utfjmln8-h.vf \
tex-utfjmln8-v.tfm \
tex-utfjmln8-v.vf \
tex-utfjmln9-h.tfm \
tex-utfjmln9-h.vf \
tex-utfjmln9-v.tfm \
tex-utfjmln9-v.vf \
tex-utfjmlna-h.tfm \
tex-utfjmlna-h.vf \
tex-utfjmlna-v.tfm \
tex-utfjmlna-v.vf \
tex-utfjmlnb-h.tfm \
tex-utfjmlnb-h.vf \
tex-utfjmlnb-v.tfm \
tex-utfjmlnb-v.vf \
tex-utfjmlnc-h.tfm \
tex-utfjmlnc-h.vf \
tex-utfjmlnc-v.tfm \
tex-utfjmlnc-v.vf \
tex-utfjmlnd-h.tfm \
tex-utfjmlnd-h.vf \
tex-utfjmlnd-v.tfm \
tex-utfjmlnd-v.vf \
tex-utfjmlne-h.tfm \
tex-utfjmlne-h.vf \
tex-utfjmlne-v.tfm \
tex-utfjmlne-v.vf \
tex-utfjmlnf-h.tfm \
tex-utfjmlnf-h.vf \
tex-utfjmlnf-v.tfm \
tex-utfjmlnf-v.vf \
tex-utfjmlo-h.tfm \
tex-utfjmlo-h.vf \
tex-utfjmlo-v.tfm \
tex-utfjmlo-v.vf \
tex-utfjmlp-h.tfm \
tex-utfjmlp-h.vf \
tex-utfjmlp-v.tfm \
tex-utfjmlp-v.vf \
tex-utfjmlq-h.tfm \
tex-utfjmlq-h.vf \
tex-utfjmlq-v.tfm \
tex-utfjmlq-v.vf \
tex-utfjmlr-h.tfm \
tex-utfjmlr-h.vf \
tex-utfjmlr-v.tfm \
tex-utfjmlr-v.vf \
tex-utfjmls-h.tfm \
tex-utfjmls-h.vf \
tex-utfjmls-v.tfm \
tex-utfjmls-v.vf \
tex-utfjmlt-h.tfm \
tex-utfjmlt-h.vf \
tex-utfjmlt-v.tfm \
tex-utfjmlt-v.vf \
tex-utfjmlu-h.tfm \
tex-utfjmlu-h.vf \
tex-utfjmlu-v.tfm \
tex-utfjmlu-v.vf \
tex-utfjmlv-h.tfm \
tex-utfjmlv-h.vf \
tex-utfjmlv-v.tfm \
tex-utfjmlv-v.vf \
tex-utfjmlx-h.tfm \
tex-utfjmlx-h.vf \
tex-utfjmlx-v.tfm \
tex-utfjmlx-v.vf \
tex-utfjmly-h.tfm \
tex-utfjmly-h.vf \
tex-utfjmly-v.tfm \
tex-utfjmly-v.vf \
tex-utfjmlz-h.tfm \
tex-utfjmlz-h.vf \
tex-utfjmlz-v.tfm \
tex-utfjmlz-v.vf \
tex-utfjmr--h.tfm \
tex-utfjmr--h.vf \
tex-utfjmr--v.tfm \
tex-utfjmr--v.vf \
tex-utfjmr0-h.tfm \
tex-utfjmr0-h.vf \
tex-utfjmr0-v.tfm \
tex-utfjmr0-v.vf \
tex-utfjmr1-h.tfm \
tex-utfjmr1-h.vf \
tex-utfjmr1-v.tfm \
tex-utfjmr1-v.vf \
tex-utfjmr2-h.tfm \
tex-utfjmr2-h.vf \
tex-utfjmr2-v.tfm \
tex-utfjmr2-v.vf \
tex-utfjmr3-h.tfm \
tex-utfjmr3-h.vf \
tex-utfjmr3-v.tfm \
tex-utfjmr3-v.vf \
tex-utfjmr4-h.tfm \
tex-utfjmr4-h.vf \
tex-utfjmr4-v.tfm \
tex-utfjmr4-v.vf \
tex-utfjmr5-h.tfm \
tex-utfjmr5-h.vf \
tex-utfjmr5-v.tfm \
tex-utfjmr5-v.vf \
tex-utfjmr6-h.tfm \
tex-utfjmr6-h.vf \
tex-utfjmr6-v.tfm \
tex-utfjmr6-v.vf \
tex-utfjmr7-h.tfm \
tex-utfjmr7-h.vf \
tex-utfjmr7-v.tfm \
tex-utfjmr7-v.vf \
tex-utfjmr8-h.tfm \
tex-utfjmr8-h.vf \
tex-utfjmr8-v.tfm \
tex-utfjmr8-v.vf \
tex-utfjmr9-h.tfm \
tex-utfjmr9-h.vf \
tex-utfjmr9-v.tfm \
tex-utfjmr9-v.vf \
tex-utfjmra-h.tfm \
tex-utfjmra-h.vf \
tex-utfjmra-v.tfm \
tex-utfjmra-v.vf \
tex-utfjmrb-h.tfm \
tex-utfjmrb-h.vf \
tex-utfjmrb-v.tfm \
tex-utfjmrb-v.vf \
tex-utfjmrc-h.tfm \
tex-utfjmrc-h.vf \
tex-utfjmrc-v.tfm \
tex-utfjmrc-v.vf \
tex-utfjmrd-h.tfm \
tex-utfjmrd-h.vf \
tex-utfjmrd-v.tfm \
tex-utfjmrd-v.vf \
tex-utfjmre-h.tfm \
tex-utfjmre-h.vf \
tex-utfjmre-v.tfm \
tex-utfjmre-v.vf \
tex-utfjmrf-h.tfm \
tex-utfjmrf-h.vf \
tex-utfjmrf-v.tfm \
tex-utfjmrf-v.vf \
tex-utfjmrg-h.tfm \
tex-utfjmrg-h.vf \
tex-utfjmrg-v.tfm \
tex-utfjmrg-v.vf \
tex-utfjmrj-h.tfm \
tex-utfjmrj-h.vf \
tex-utfjmrj-v.tfm \
tex-utfjmrj-v.vf \
tex-utfjmrk-h.tfm \
tex-utfjmrk-h.vf \
tex-utfjmrk-v.tfm \
tex-utfjmrk-v.vf \
tex-utfjmrl-h.tfm \
tex-utfjmrl-h.vf \
tex-utfjmrl-v.tfm \
tex-utfjmrl-v.vf \
tex-utfjmrm-h.tfm \
tex-utfjmrm-h.vf \
tex-utfjmrm-v.tfm \
tex-utfjmrm-v.vf \
tex-utfjmrn--h.tfm \
tex-utfjmrn--h.vf \
tex-utfjmrn--v.tfm \
tex-utfjmrn--v.vf \
tex-utfjmrn-h.tfm \
tex-utfjmrn-h.vf \
tex-utfjmrn-v.tfm \
tex-utfjmrn-v.vf \
tex-utfjmrn0-h.tfm \
tex-utfjmrn0-h.vf \
tex-utfjmrn0-v.tfm \
tex-utfjmrn0-v.vf \
tex-utfjmrn1-h.tfm \
tex-utfjmrn1-h.vf \
tex-utfjmrn1-v.tfm \
tex-utfjmrn1-v.vf \
tex-utfjmrn2-h.tfm \
tex-utfjmrn2-h.vf \
tex-utfjmrn2-v.tfm \
tex-utfjmrn2-v.vf \
tex-utfjmrn3-h.tfm \
tex-utfjmrn3-h.vf \
tex-utfjmrn3-v.tfm \
tex-utfjmrn3-v.vf \
tex-utfjmrn4-h.tfm \
tex-utfjmrn4-h.vf \
tex-utfjmrn4-v.tfm \
tex-utfjmrn4-v.vf \
tex-utfjmrn5-h.tfm \
tex-utfjmrn5-h.vf \
tex-utfjmrn5-v.tfm \
tex-utfjmrn5-v.vf \
tex-utfjmrn6-h.tfm \
tex-utfjmrn6-h.vf \
tex-utfjmrn6-v.tfm \
tex-utfjmrn6-v.vf \
tex-utfjmrn7-h.tfm \
tex-utfjmrn7-h.vf \
tex-utfjmrn7-v.tfm \
tex-utfjmrn7-v.vf \
tex-utfjmrn8-h.tfm \
tex-utfjmrn8-h.vf \
tex-utfjmrn8-v.tfm \
tex-utfjmrn8-v.vf \
tex-utfjmrn9-h.tfm \
tex-utfjmrn9-h.vf \
tex-utfjmrn9-v.tfm \
tex-utfjmrn9-v.vf \
tex-utfjmrna-h.tfm \
tex-utfjmrna-h.vf \
tex-utfjmrna-v.tfm \
tex-utfjmrna-v.vf \
tex-utfjmrnb-h.tfm \
tex-utfjmrnb-h.vf \
tex-utfjmrnb-v.tfm \
tex-utfjmrnb-v.vf \
tex-utfjmrnc-h.tfm \
tex-utfjmrnc-h.vf \
tex-utfjmrnc-v.tfm \
tex-utfjmrnc-v.vf \
tex-utfjmrnd-h.tfm \
tex-utfjmrnd-h.vf \
tex-utfjmrnd-v.tfm \
tex-utfjmrnd-v.vf \
tex-utfjmrne-h.tfm \
tex-utfjmrne-h.vf \
tex-utfjmrne-v.tfm \
tex-utfjmrne-v.vf \
tex-utfjmrnf-h.tfm \
tex-utfjmrnf-h.vf \
tex-utfjmrnf-v.tfm \
tex-utfjmrnf-v.vf \
tex-utfjmro-h.tfm \
tex-utfjmro-h.vf \
tex-utfjmro-v.tfm \
tex-utfjmro-v.vf \
tex-utfjmrp-h.tfm \
tex-utfjmrp-h.vf \
tex-utfjmrp-v.tfm \
tex-utfjmrp-v.vf \
tex-utfjmrq-h.tfm \
tex-utfjmrq-h.vf \
tex-utfjmrq-v.tfm \
tex-utfjmrq-v.vf \
tex-utfjmrr-h.tfm \
tex-utfjmrr-h.vf \
tex-utfjmrr-v.tfm \
tex-utfjmrr-v.vf \
tex-utfjmrs-h.tfm \
tex-utfjmrs-h.vf \
tex-utfjmrs-v.tfm \
tex-utfjmrs-v.vf \
tex-utfjmrt-h.tfm \
tex-utfjmrt-h.vf \
tex-utfjmrt-v.tfm \
tex-utfjmrt-v.vf \
tex-utfjmru-h.tfm \
tex-utfjmru-h.vf \
tex-utfjmru-v.tfm \
tex-utfjmru-v.vf \
tex-utfjmrv-h.tfm \
tex-utfjmrv-h.vf \
tex-utfjmrv-v.tfm \
tex-utfjmrv-v.vf \
tex-utfjmrx-h.tfm \
tex-utfjmrx-h.vf \
tex-utfjmrx-v.tfm \
tex-utfjmrx-v.vf \
tex-utfjmry-h.tfm \
tex-utfjmry-h.vf \
tex-utfjmry-v.tfm \
tex-utfjmry-v.vf \
tex-utfjmrz-h.tfm \
tex-utfjmrz-h.vf \
tex-utfjmrz-v.tfm \
tex-utfjmrz-v.vf \
tex-utfkgb--h.tfm \
tex-utfkgb--h.vf \
tex-utfkgb--v.tfm \
tex-utfkgb--v.vf \
tex-utfkge--h.tfm \
tex-utfkge--h.vf \
tex-utfkge--v.tfm \
tex-utfkge--v.vf \
tex-utfkgr--h.tfm \
tex-utfkgr--h.vf \
tex-utfkgr--v.tfm \
tex-utfkgr--v.vf \
tex-utfkmb--h.tfm \
tex-utfkmb--h.vf \
tex-utfkmb--v.tfm \
tex-utfkmb--v.vf \
tex-utfkmgr--h.tfm \
tex-utfkmgr--h.vf \
tex-utfkmgr--v.tfm \
tex-utfkmgr--v.vf \
tex-utfkml--h.tfm \
tex-utfkml--h.vf \
tex-utfkml--v.tfm \
tex-utfkml--v.vf \
tex-utfkmr--h.tfm \
tex-utfkmr--h.vf \
tex-utfkmr--v.tfm \
tex-utfkmr--v.vf \
tex-utfmb--h.tfm \
tex-utfmb--h.vf \
tex-utfmb--v.tfm \
tex-utfmb--v.vf \
tex-utfmgr--h.tfm \
tex-utfmgr--h.vf \
tex-utfmgr--v.tfm \
tex-utfmgr--v.vf \
tex-utfml--h.tfm \
tex-utfml--h.vf \
tex-utfml--v.tfm \
tex-utfml--v.vf \
tex-utfmr--h.tfm \
tex-utfmr--h.vf \
tex-utfmr--v.tfm \
tex-utfmr--v.vf \
tex-utftgb--h.tfm \
tex-utftgb--h.vf \
tex-utftgb--v.tfm \
tex-utftgb--v.vf \
tex-utftge--h.tfm \
tex-utftge--h.vf \
tex-utftge--v.tfm \
tex-utftge--v.vf \
tex-utftgr--h.tfm \
tex-utftgr--h.vf \
tex-utftgr--v.tfm \
tex-utftgr--v.vf \
tex-utftmb--h.tfm \
tex-utftmb--h.vf \
tex-utftmb--v.tfm \
tex-utftmb--v.vf \
tex-utftmgr--h.tfm \
tex-utftmgr--h.vf \
tex-utftmgr--v.tfm \
tex-utftmgr--v.vf \
tex-utftml--h.tfm \
tex-utftml--h.vf \
tex-utftml--v.tfm \
tex-utftml--v.vf \
tex-utftmr--h.tfm \
tex-utftmr--h.vf \
tex-utftmr--v.tfm \
tex-utftmr--v.vf \
texlive-japanese-otf"

RDEPENDS:${PN} += "/usr/bin/sh \
coreutils \
ed \
findutils \
grep \
sed \
tex-keyval.sty \
tex-updmap.cfg \
texlive \
texlive-filesystem \
texlive-kpathsea \
texlive-kpathsea-bin \
texlive-scripts \
texlive-scripts-bin"

inherit rpm
