SUMMARY = "Development files for opam"
DESCRIPTION = "The opam-devel package contains libraries and signature files for \
developing applications that use opam."
LICENSE = "LGPL-2.1-only-with-OCaml-LGPL-linking-exception"

PV = "2.5.2"

RPM_NAME = "opam-devel-2.5.2-1.3.aarch64.rpm"
RPM_HASH = "78dae0026946cb7248489735d6151724e3df43471184bf81920ad1fec2a2bbde2b298581b43881882f23994d1c26882398d938a2572710f5047c962e23e5f10e"

RPROVIDES:${PN} += "config-opam-devel \
ocaml-Opam-admin-top \
ocaml-OpamAction \
ocaml-OpamActionGraph \
ocaml-OpamAdminCheck \
ocaml-OpamAdminCommand \
ocaml-OpamAdminRepoUpgrade \
ocaml-OpamArg \
ocaml-OpamArgTools \
ocaml-OpamAuxCommands \
ocaml-OpamBuiltin0install \
ocaml-OpamBuiltinMccs \
ocaml-OpamBuiltinZ3 \
ocaml-OpamCLIVersion \
ocaml-OpamCached \
ocaml-OpamCliMain \
ocaml-OpamClient \
ocaml-OpamClientConfig \
ocaml-OpamCmdliner \
ocaml-OpamCmdliner-- \
ocaml-OpamCmdliner--Cmdliner-arg \
ocaml-OpamCmdliner--Cmdliner-base \
ocaml-OpamCmdliner--Cmdliner-cline \
ocaml-OpamCmdliner--Cmdliner-cmd \
ocaml-OpamCmdliner--Cmdliner-docgen \
ocaml-OpamCmdliner--Cmdliner-eval \
ocaml-OpamCmdliner--Cmdliner-info \
ocaml-OpamCmdliner--Cmdliner-manpage \
ocaml-OpamCmdliner--Cmdliner-msg \
ocaml-OpamCmdliner--Cmdliner-term \
ocaml-OpamCmdliner--Cmdliner-term-deprecated \
ocaml-OpamCmdliner--Cmdliner-trie \
ocaml-OpamCommands \
ocaml-OpamCompat \
ocaml-OpamConfigCommand \
ocaml-OpamConsole \
ocaml-OpamCoreConfig \
ocaml-OpamCoreConfigDeveloper \
ocaml-OpamCudf \
ocaml-OpamCudfCriteria \
ocaml-OpamCudfSolver \
ocaml-OpamCudfSolverSig \
ocaml-OpamDarcs \
ocaml-OpamDirTrack \
ocaml-OpamDownload \
ocaml-OpamEmbeddedCygwinSetup \
ocaml-OpamEnv \
ocaml-OpamFile \
ocaml-OpamFileTools \
ocaml-OpamFilename \
ocaml-OpamFilter \
ocaml-OpamFormat \
ocaml-OpamFormatConfig \
ocaml-OpamFormatUpgrade \
ocaml-OpamFormula \
ocaml-OpamGit \
ocaml-OpamGitVersion \
ocaml-OpamGlobalState \
ocaml-OpamHTTP \
ocaml-OpamHash \
ocaml-OpamHg \
ocaml-OpamInitDefaults \
ocaml-OpamInterpLexer \
ocaml-OpamJson \
ocaml-OpamLineLexer \
ocaml-OpamListCommand \
ocaml-OpamLocal \
ocaml-OpamLockCommand \
ocaml-OpamPackage \
ocaml-OpamPackageVar \
ocaml-OpamParallel \
ocaml-OpamPath \
ocaml-OpamPinCommand \
ocaml-OpamPinned \
ocaml-OpamPp \
ocaml-OpamProcess \
ocaml-OpamRepository \
ocaml-OpamRepositoryBackend \
ocaml-OpamRepositoryCommand \
ocaml-OpamRepositoryConfig \
ocaml-OpamRepositoryName \
ocaml-OpamRepositoryPath \
ocaml-OpamRepositoryState \
ocaml-OpamSHA \
ocaml-OpamSWHID \
ocaml-OpamScript \
ocaml-OpamShellCommand \
ocaml-OpamSolution \
ocaml-OpamSolver \
ocaml-OpamSolverConfig \
ocaml-OpamStateConfig \
ocaml-OpamStateTypes \
ocaml-OpamStd \
ocaml-OpamStubs \
ocaml-OpamStubsTypes \
ocaml-OpamSwitch \
ocaml-OpamSwitchAction \
ocaml-OpamSwitchCommand \
ocaml-OpamSwitchState \
ocaml-OpamSysInteract \
ocaml-OpamSysPkg \
ocaml-OpamSysPoll \
ocaml-OpamSystem \
ocaml-OpamTreeCommand \
ocaml-OpamTypes \
ocaml-OpamTypesBase \
ocaml-OpamUpdate \
ocaml-OpamUrl \
ocaml-OpamVCS \
ocaml-OpamVariable \
ocaml-OpamVersion \
ocaml-OpamVersionCompare \
ocaml-OpamVersionInfo \
ocamlfind-opam \
ocamlfind-opam-admin \
ocamlfind-opam-admin.top \
ocamlfind-opam-client \
ocamlfind-opam-core \
ocamlfind-opam-core.cmdliner \
ocamlfind-opam-format \
ocamlfind-opam-installer \
ocamlfind-opam-repository \
ocamlfind-opam-solver \
ocamlfind-opam-state \
ocamlx-Opam-admin-top \
ocamlx-OpamAction \
ocamlx-OpamActionGraph \
ocamlx-OpamAdminCheck \
ocamlx-OpamAdminCommand \
ocamlx-OpamAdminRepoUpgrade \
ocamlx-OpamArg \
ocamlx-OpamArgTools \
ocamlx-OpamAuxCommands \
ocamlx-OpamBuiltin0install \
ocamlx-OpamBuiltinMccs \
ocamlx-OpamBuiltinZ3 \
ocamlx-OpamCLIVersion \
ocamlx-OpamCached \
ocamlx-OpamCliMain \
ocamlx-OpamClient \
ocamlx-OpamClientConfig \
ocamlx-OpamCmdliner \
ocamlx-OpamCmdliner-- \
ocamlx-OpamCmdliner--Cmdliner-arg \
ocamlx-OpamCmdliner--Cmdliner-base \
ocamlx-OpamCmdliner--Cmdliner-cline \
ocamlx-OpamCmdliner--Cmdliner-cmd \
ocamlx-OpamCmdliner--Cmdliner-docgen \
ocamlx-OpamCmdliner--Cmdliner-eval \
ocamlx-OpamCmdliner--Cmdliner-info \
ocamlx-OpamCmdliner--Cmdliner-manpage \
ocamlx-OpamCmdliner--Cmdliner-msg \
ocamlx-OpamCmdliner--Cmdliner-term \
ocamlx-OpamCmdliner--Cmdliner-term-deprecated \
ocamlx-OpamCmdliner--Cmdliner-trie \
ocamlx-OpamCommands \
ocamlx-OpamCompat \
ocamlx-OpamConfigCommand \
ocamlx-OpamConsole \
ocamlx-OpamCoreConfig \
ocamlx-OpamCoreConfigDeveloper \
ocamlx-OpamCudf \
ocamlx-OpamCudfCriteria \
ocamlx-OpamCudfSolver \
ocamlx-OpamCudfSolverSig \
ocamlx-OpamDarcs \
ocamlx-OpamDirTrack \
ocamlx-OpamDownload \
ocamlx-OpamEmbeddedCygwinSetup \
ocamlx-OpamEnv \
ocamlx-OpamFile \
ocamlx-OpamFileTools \
ocamlx-OpamFilename \
ocamlx-OpamFilter \
ocamlx-OpamFormat \
ocamlx-OpamFormatConfig \
ocamlx-OpamFormatUpgrade \
ocamlx-OpamFormula \
ocamlx-OpamGit \
ocamlx-OpamGitVersion \
ocamlx-OpamGlobalState \
ocamlx-OpamHTTP \
ocamlx-OpamHash \
ocamlx-OpamHg \
ocamlx-OpamInitDefaults \
ocamlx-OpamInterpLexer \
ocamlx-OpamJson \
ocamlx-OpamLineLexer \
ocamlx-OpamListCommand \
ocamlx-OpamLocal \
ocamlx-OpamLockCommand \
ocamlx-OpamPackage \
ocamlx-OpamPackageVar \
ocamlx-OpamParallel \
ocamlx-OpamPath \
ocamlx-OpamPinCommand \
ocamlx-OpamPinned \
ocamlx-OpamPp \
ocamlx-OpamProcess \
ocamlx-OpamRepository \
ocamlx-OpamRepositoryBackend \
ocamlx-OpamRepositoryCommand \
ocamlx-OpamRepositoryConfig \
ocamlx-OpamRepositoryName \
ocamlx-OpamRepositoryPath \
ocamlx-OpamRepositoryState \
ocamlx-OpamSHA \
ocamlx-OpamSWHID \
ocamlx-OpamScript \
ocamlx-OpamShellCommand \
ocamlx-OpamSolution \
ocamlx-OpamSolver \
ocamlx-OpamSolverConfig \
ocamlx-OpamStateConfig \
ocamlx-OpamStd \
ocamlx-OpamStubs \
ocamlx-OpamStubsTypes \
ocamlx-OpamSwitch \
ocamlx-OpamSwitchAction \
ocamlx-OpamSwitchCommand \
ocamlx-OpamSwitchState \
ocamlx-OpamSysInteract \
ocamlx-OpamSysPkg \
ocamlx-OpamSysPoll \
ocamlx-OpamSystem \
ocamlx-OpamTreeCommand \
ocamlx-OpamTypesBase \
ocamlx-OpamUpdate \
ocamlx-OpamUrl \
ocamlx-OpamVCS \
ocamlx-OpamVariable \
ocamlx-OpamVersion \
ocamlx-OpamVersionCompare \
ocamlx-OpamVersionInfo \
opam-devel"

RDEPENDS:${PN} += "libc.so.6 \
ocaml-Base64 \
ocaml-CamlinternalFormatBasics \
ocaml-CamlinternalLazy \
ocaml-Cudf \
ocaml-Cudf-conf \
ocaml-Cudf-parser \
ocaml-Cudf-printer \
ocaml-Cudf-types \
ocaml-Dose-algo \
ocaml-Dose-algo--Defaultgraphs \
ocaml-Dose-algo--Depsolver \
ocaml-Dose-algo--Diagnostic \
ocaml-Dose-common \
ocaml-Dose-common--CudfAdd \
ocaml-Dose-common--CudfSolver \
ocaml-Dose-common--Util \
ocaml-Enum \
ocaml-ExtArray \
ocaml-ExtBuffer \
ocaml-ExtHashtbl \
ocaml-ExtLib \
ocaml-ExtList \
ocaml-ExtString \
ocaml-Graph \
ocaml-Graph-- \
ocaml-Graph--Builder \
ocaml-Graph--Components \
ocaml-Graph--Dot \
ocaml-Graph--Dot-ast \
ocaml-Graph--Gml \
ocaml-Graph--Graphml \
ocaml-Graph--Graphviz \
ocaml-Graph--Imperative \
ocaml-Graph--Oper \
ocaml-Graph--Sig \
ocaml-Graph--Topological \
ocaml-Graph--Traverse \
ocaml-IO \
ocaml-Jsonm \
ocaml-Mccs \
ocaml-Opam-0install-cudf \
ocaml-Opam-0install-cudf-- \
ocaml-OpamBaseParser \
ocaml-OpamLexer \
ocaml-OpamParser \
ocaml-OpamParserTypes \
ocaml-OpamPrinter \
ocaml-Option \
ocaml-Patch \
ocaml-Patch-- \
ocaml-Re \
ocaml-Re-- \
ocaml-Re--Ast \
ocaml-Re--Automata \
ocaml-Re--Category \
ocaml-Re--Color-map \
ocaml-Re--Compile \
ocaml-Re--Core \
ocaml-Re--Cset \
ocaml-Re--Dyn \
ocaml-Re--Fmt \
ocaml-Re--Glob \
ocaml-Re--Group \
ocaml-Re--Mark-infos \
ocaml-Re--Pcre \
ocaml-Re--Pmark \
ocaml-Re--Replace \
ocaml-Sha1 \
ocaml-Sha256 \
ocaml-Sha512 \
ocaml-Spdx-licenses \
ocaml-Spdx-licenses-- \
ocaml-Std \
ocaml-Stdlib \
ocaml-Stdlib--Array \
ocaml-Stdlib--Bigarray \
ocaml-Stdlib--Bool \
ocaml-Stdlib--Buffer \
ocaml-Stdlib--Bytes \
ocaml-Stdlib--Char \
ocaml-Stdlib--Complex \
ocaml-Stdlib--Digest \
ocaml-Stdlib--Domain \
ocaml-Stdlib--Either \
ocaml-Stdlib--Filename \
ocaml-Stdlib--Float \
ocaml-Stdlib--Format \
ocaml-Stdlib--Fun \
ocaml-Stdlib--Gc \
ocaml-Stdlib--Hashtbl \
ocaml-Stdlib--Int \
ocaml-Stdlib--Int32 \
ocaml-Stdlib--Int64 \
ocaml-Stdlib--Lazy \
ocaml-Stdlib--Lexing \
ocaml-Stdlib--List \
ocaml-Stdlib--Map \
ocaml-Stdlib--Marshal \
ocaml-Stdlib--Mutex \
ocaml-Stdlib--Nativeint \
ocaml-Stdlib--Obj \
ocaml-Stdlib--Option \
ocaml-Stdlib--Parsing \
ocaml-Stdlib--Printexc \
ocaml-Stdlib--Printf \
ocaml-Stdlib--Queue \
ocaml-Stdlib--Random \
ocaml-Stdlib--Result \
ocaml-Stdlib--Scanf \
ocaml-Stdlib--Seq \
ocaml-Stdlib--Set \
ocaml-Stdlib--String \
ocaml-Stdlib--Sys \
ocaml-Stdlib--Uchar \
ocaml-Swhid-core \
ocaml-Swhid-core--Compute \
ocaml-Swhid-core--Object \
ocaml-Unix \
ocaml-Uutf \
ocamlfind-base64 \
ocamlfind-compiler-libs.toplevel \
ocamlfind-cudf \
ocamlfind-dose3.algo \
ocamlfind-dose3.common \
ocamlfind-jsonm \
ocamlfind-mccs \
ocamlfind-ocamlgraph \
ocamlfind-opam-0install-cudf \
ocamlfind-opam-client \
ocamlfind-opam-core \
ocamlfind-opam-core.cmdliner \
ocamlfind-opam-file-format \
ocamlfind-opam-format \
ocamlfind-opam-repository \
ocamlfind-opam-solver \
ocamlfind-opam-state \
ocamlfind-patch \
ocamlfind-re \
ocamlfind-sha \
ocamlfind-spdx-licenses \
ocamlfind-swhid-core \
ocamlfind-unix \
ocamlfind-uutf \
ocamlx-Base64 \
ocamlx-CamlinternalLazy \
ocamlx-Cudf \
ocamlx-Cudf-parser \
ocamlx-Cudf-printer \
ocamlx-Dose-algo--Defaultgraphs \
ocamlx-Dose-algo--Depsolver \
ocamlx-Dose-algo--Diagnostic \
ocamlx-Dose-common--CudfAdd \
ocamlx-Dose-common--CudfSolver \
ocamlx-Graph--Components \
ocamlx-Graph--Graphviz \
ocamlx-Graph--Imperative \
ocamlx-Graph--Oper \
ocamlx-Graph--Topological \
ocamlx-Graph--Traverse \
ocamlx-Jsonm \
ocamlx-Mccs \
ocamlx-Opam-0install-cudf \
ocamlx-OpamLexer \
ocamlx-OpamParser \
ocamlx-OpamPrinter \
ocamlx-Option \
ocamlx-Patch \
ocamlx-Re \
ocamlx-Re--Glob \
ocamlx-Re--Pcre \
ocamlx-Sha1 \
ocamlx-Sha256 \
ocamlx-Sha512 \
ocamlx-Spdx-licenses \
ocamlx-Stdlib \
ocamlx-Stdlib--Array \
ocamlx-Stdlib--Bool \
ocamlx-Stdlib--Buffer \
ocamlx-Stdlib--Bytes \
ocamlx-Stdlib--Char \
ocamlx-Stdlib--Digest \
ocamlx-Stdlib--Filename \
ocamlx-Stdlib--Float \
ocamlx-Stdlib--Format \
ocamlx-Stdlib--Fun \
ocamlx-Stdlib--Gc \
ocamlx-Stdlib--Hashtbl \
ocamlx-Stdlib--Int \
ocamlx-Stdlib--Int32 \
ocamlx-Stdlib--Int64 \
ocamlx-Stdlib--Lazy \
ocamlx-Stdlib--Lexing \
ocamlx-Stdlib--List \
ocamlx-Stdlib--Map \
ocamlx-Stdlib--Marshal \
ocamlx-Stdlib--Nativeint \
ocamlx-Stdlib--Option \
ocamlx-Stdlib--Parsing \
ocamlx-Stdlib--Printexc \
ocamlx-Stdlib--Printf \
ocamlx-Stdlib--Queue \
ocamlx-Stdlib--Random \
ocamlx-Stdlib--Result \
ocamlx-Stdlib--Scanf \
ocamlx-Stdlib--Seq \
ocamlx-Stdlib--Set \
ocamlx-Stdlib--String \
ocamlx-Stdlib--Sys \
ocamlx-Stdlib--Uchar \
ocamlx-Swhid-core--Compute \
ocamlx-Swhid-core--Object \
ocamlx-Unix \
ocamlx-Uutf \
opam"

inherit rpm
