SUMMARY = "Documentation for poezio"
DESCRIPTION = "Documentation generated by the poezio package, but split out due to size."
LICENSE = "MIT"

PV = "0.18"

RPM_NAME = "poezio-doc-0.18-1.3.noarch.rpm"
RPM_HASH = "d3367b766e7531ae5a4337b3e377c8df839c66a2fe58564ad1db944c9d14289a8a0befb83ac5e81397d0c11323b3704861ffad53848d44d1abad536446563c36"
REPO_ARCH = "noarch"

RPROVIDES:${PN} += "poezio-doc"

RDEPENDS:${PN} += ""

inherit rpm
