SUMMARY = "Splentinex fonts"
DESCRIPTION = "This is a serif font family designed for body text. This \
typeface design was originally crated by Frank Pierpont and \
Fritz Stelzer in 1913 and released by Monotype as Plantin. In \
2025, Ben Byram-Wigfield created Splentino, a new digitization \
of the Plantin design, for inclusion with the music software \
Dorico. Splentinex is a modified repackaging of Splentino."
LICENSE = "OFL-1.1"

PV = "2026.226.1.0svn77682"

RPM_NAME = "texlive-splentinex-2026.226.1.0svn77682-64.2.noarch.rpm"
RPM_HASH = "acb28d888397f7002d73dad467dbd45eb916f1a17c52d1460954abadd78f9a27978ceea112e8aa46b02ae56d1ec781dbe94a51a0801c86a0cbfef4d7b903d11d"
REPO_ARCH = "noarch"

RPROVIDES:${PN} += "tex-LY1Splentinex-LF.fd \
tex-LY1Splentinex-OsF.fd \
tex-LY1Splentinex-Sup.fd \
tex-LY1Splentinex-TLF.fd \
tex-LY1Splentinex-TOsF.fd \
tex-OT1Splentinex-LF.fd \
tex-OT1Splentinex-OsF.fd \
tex-OT1Splentinex-Sup.fd \
tex-OT1Splentinex-TLF.fd \
tex-OT1Splentinex-TOsF.fd \
tex-Splentinex-Bold-lf-ly1--base.tfm \
tex-Splentinex-Bold-lf-ly1.tfm \
tex-Splentinex-Bold-lf-ly1.vf \
tex-Splentinex-Bold-lf-ot1.tfm \
tex-Splentinex-Bold-lf-t1--base.tfm \
tex-Splentinex-Bold-lf-t1.tfm \
tex-Splentinex-Bold-lf-t1.vf \
tex-Splentinex-Bold-lf-ts1--base.tfm \
tex-Splentinex-Bold-lf-ts1.tfm \
tex-Splentinex-Bold-lf-ts1.vf \
tex-Splentinex-Bold-osf-ly1--base.tfm \
tex-Splentinex-Bold-osf-ly1.tfm \
tex-Splentinex-Bold-osf-ly1.vf \
tex-Splentinex-Bold-osf-ot1.tfm \
tex-Splentinex-Bold-osf-t1--base.tfm \
tex-Splentinex-Bold-osf-t1.tfm \
tex-Splentinex-Bold-osf-t1.vf \
tex-Splentinex-Bold-osf-ts1--base.tfm \
tex-Splentinex-Bold-osf-ts1.tfm \
tex-Splentinex-Bold-osf-ts1.vf \
tex-Splentinex-Bold-tlf-ly1--base.tfm \
tex-Splentinex-Bold-tlf-ly1.tfm \
tex-Splentinex-Bold-tlf-ly1.vf \
tex-Splentinex-Bold-tlf-ot1.tfm \
tex-Splentinex-Bold-tlf-t1--base.tfm \
tex-Splentinex-Bold-tlf-t1.tfm \
tex-Splentinex-Bold-tlf-t1.vf \
tex-Splentinex-Bold-tlf-ts1--base.tfm \
tex-Splentinex-Bold-tlf-ts1.tfm \
tex-Splentinex-Bold-tlf-ts1.vf \
tex-Splentinex-Bold-tosf-ly1--base.tfm \
tex-Splentinex-Bold-tosf-ly1.tfm \
tex-Splentinex-Bold-tosf-ly1.vf \
tex-Splentinex-Bold-tosf-ot1.tfm \
tex-Splentinex-Bold-tosf-t1--base.tfm \
tex-Splentinex-Bold-tosf-t1.tfm \
tex-Splentinex-Bold-tosf-t1.vf \
tex-Splentinex-Bold-tosf-ts1--base.tfm \
tex-Splentinex-Bold-tosf-ts1.tfm \
tex-Splentinex-Bold-tosf-ts1.vf \
tex-Splentinex-BoldItalic-lf-ly1--base.tfm \
tex-Splentinex-BoldItalic-lf-ly1.tfm \
tex-Splentinex-BoldItalic-lf-ly1.vf \
tex-Splentinex-BoldItalic-lf-ot1.tfm \
tex-Splentinex-BoldItalic-lf-swash-ly1--base.tfm \
tex-Splentinex-BoldItalic-lf-swash-ly1.tfm \
tex-Splentinex-BoldItalic-lf-swash-ly1.vf \
tex-Splentinex-BoldItalic-lf-swash-ot1.tfm \
tex-Splentinex-BoldItalic-lf-swash-t1--base.tfm \
tex-Splentinex-BoldItalic-lf-swash-t1.tfm \
tex-Splentinex-BoldItalic-lf-swash-t1.vf \
tex-Splentinex-BoldItalic-lf-t1--base.tfm \
tex-Splentinex-BoldItalic-lf-t1.tfm \
tex-Splentinex-BoldItalic-lf-t1.vf \
tex-Splentinex-BoldItalic-lf-ts1--base.tfm \
tex-Splentinex-BoldItalic-lf-ts1.tfm \
tex-Splentinex-BoldItalic-lf-ts1.vf \
tex-Splentinex-BoldItalic-osf-ly1--base.tfm \
tex-Splentinex-BoldItalic-osf-ly1.tfm \
tex-Splentinex-BoldItalic-osf-ly1.vf \
tex-Splentinex-BoldItalic-osf-ot1.tfm \
tex-Splentinex-BoldItalic-osf-swash-ly1--base.tfm \
tex-Splentinex-BoldItalic-osf-swash-ly1.tfm \
tex-Splentinex-BoldItalic-osf-swash-ly1.vf \
tex-Splentinex-BoldItalic-osf-swash-ot1.tfm \
tex-Splentinex-BoldItalic-osf-swash-t1--base.tfm \
tex-Splentinex-BoldItalic-osf-swash-t1.tfm \
tex-Splentinex-BoldItalic-osf-swash-t1.vf \
tex-Splentinex-BoldItalic-osf-t1--base.tfm \
tex-Splentinex-BoldItalic-osf-t1.tfm \
tex-Splentinex-BoldItalic-osf-t1.vf \
tex-Splentinex-BoldItalic-osf-ts1--base.tfm \
tex-Splentinex-BoldItalic-osf-ts1.tfm \
tex-Splentinex-BoldItalic-osf-ts1.vf \
tex-Splentinex-BoldItalic-tlf-ly1--base.tfm \
tex-Splentinex-BoldItalic-tlf-ly1.tfm \
tex-Splentinex-BoldItalic-tlf-ly1.vf \
tex-Splentinex-BoldItalic-tlf-ot1.tfm \
tex-Splentinex-BoldItalic-tlf-swash-ly1--base.tfm \
tex-Splentinex-BoldItalic-tlf-swash-ly1.tfm \
tex-Splentinex-BoldItalic-tlf-swash-ly1.vf \
tex-Splentinex-BoldItalic-tlf-swash-ot1.tfm \
tex-Splentinex-BoldItalic-tlf-swash-t1--base.tfm \
tex-Splentinex-BoldItalic-tlf-swash-t1.tfm \
tex-Splentinex-BoldItalic-tlf-swash-t1.vf \
tex-Splentinex-BoldItalic-tlf-t1--base.tfm \
tex-Splentinex-BoldItalic-tlf-t1.tfm \
tex-Splentinex-BoldItalic-tlf-t1.vf \
tex-Splentinex-BoldItalic-tlf-ts1--base.tfm \
tex-Splentinex-BoldItalic-tlf-ts1.tfm \
tex-Splentinex-BoldItalic-tlf-ts1.vf \
tex-Splentinex-BoldItalic-tosf-ly1--base.tfm \
tex-Splentinex-BoldItalic-tosf-ly1.tfm \
tex-Splentinex-BoldItalic-tosf-ly1.vf \
tex-Splentinex-BoldItalic-tosf-ot1.tfm \
tex-Splentinex-BoldItalic-tosf-swash-ly1--base.tfm \
tex-Splentinex-BoldItalic-tosf-swash-ly1.tfm \
tex-Splentinex-BoldItalic-tosf-swash-ly1.vf \
tex-Splentinex-BoldItalic-tosf-swash-ot1.tfm \
tex-Splentinex-BoldItalic-tosf-swash-t1--base.tfm \
tex-Splentinex-BoldItalic-tosf-swash-t1.tfm \
tex-Splentinex-BoldItalic-tosf-swash-t1.vf \
tex-Splentinex-BoldItalic-tosf-t1--base.tfm \
tex-Splentinex-BoldItalic-tosf-t1.tfm \
tex-Splentinex-BoldItalic-tosf-t1.vf \
tex-Splentinex-BoldItalic-tosf-ts1--base.tfm \
tex-Splentinex-BoldItalic-tosf-ts1.tfm \
tex-Splentinex-BoldItalic-tosf-ts1.vf \
tex-Splentinex-Italic-lf-ly1--base.tfm \
tex-Splentinex-Italic-lf-ly1.tfm \
tex-Splentinex-Italic-lf-ly1.vf \
tex-Splentinex-Italic-lf-ot1.tfm \
tex-Splentinex-Italic-lf-t1--base.tfm \
tex-Splentinex-Italic-lf-t1.tfm \
tex-Splentinex-Italic-lf-t1.vf \
tex-Splentinex-Italic-lf-ts1--base.tfm \
tex-Splentinex-Italic-lf-ts1.tfm \
tex-Splentinex-Italic-lf-ts1.vf \
tex-Splentinex-Italic-osf-ly1--base.tfm \
tex-Splentinex-Italic-osf-ly1.tfm \
tex-Splentinex-Italic-osf-ly1.vf \
tex-Splentinex-Italic-osf-ot1.tfm \
tex-Splentinex-Italic-osf-t1--base.tfm \
tex-Splentinex-Italic-osf-t1.tfm \
tex-Splentinex-Italic-osf-t1.vf \
tex-Splentinex-Italic-osf-ts1--base.tfm \
tex-Splentinex-Italic-osf-ts1.tfm \
tex-Splentinex-Italic-osf-ts1.vf \
tex-Splentinex-Italic-tlf-ly1--base.tfm \
tex-Splentinex-Italic-tlf-ly1.tfm \
tex-Splentinex-Italic-tlf-ly1.vf \
tex-Splentinex-Italic-tlf-ot1.tfm \
tex-Splentinex-Italic-tlf-t1--base.tfm \
tex-Splentinex-Italic-tlf-t1.tfm \
tex-Splentinex-Italic-tlf-t1.vf \
tex-Splentinex-Italic-tlf-ts1--base.tfm \
tex-Splentinex-Italic-tlf-ts1.tfm \
tex-Splentinex-Italic-tlf-ts1.vf \
tex-Splentinex-Italic-tosf-ly1--base.tfm \
tex-Splentinex-Italic-tosf-ly1.tfm \
tex-Splentinex-Italic-tosf-ly1.vf \
tex-Splentinex-Italic-tosf-ot1.tfm \
tex-Splentinex-Italic-tosf-t1--base.tfm \
tex-Splentinex-Italic-tosf-t1.tfm \
tex-Splentinex-Italic-tosf-t1.vf \
tex-Splentinex-Italic-tosf-ts1--base.tfm \
tex-Splentinex-Italic-tosf-ts1.tfm \
tex-Splentinex-Italic-tosf-ts1.vf \
tex-Splentinex-Regular-lf-ly1--base.tfm \
tex-Splentinex-Regular-lf-ly1.tfm \
tex-Splentinex-Regular-lf-ly1.vf \
tex-Splentinex-Regular-lf-ot1.tfm \
tex-Splentinex-Regular-lf-sc-ly1--base.tfm \
tex-Splentinex-Regular-lf-sc-ly1.tfm \
tex-Splentinex-Regular-lf-sc-ly1.vf \
tex-Splentinex-Regular-lf-sc-ot1--base.tfm \
tex-Splentinex-Regular-lf-sc-ot1.tfm \
tex-Splentinex-Regular-lf-sc-ot1.vf \
tex-Splentinex-Regular-lf-sc-t1--base.tfm \
tex-Splentinex-Regular-lf-sc-t1.tfm \
tex-Splentinex-Regular-lf-sc-t1.vf \
tex-Splentinex-Regular-lf-t1--base.tfm \
tex-Splentinex-Regular-lf-t1.tfm \
tex-Splentinex-Regular-lf-t1.vf \
tex-Splentinex-Regular-lf-ts1--base.tfm \
tex-Splentinex-Regular-lf-ts1.tfm \
tex-Splentinex-Regular-lf-ts1.vf \
tex-Splentinex-Regular-osf-ly1--base.tfm \
tex-Splentinex-Regular-osf-ly1.tfm \
tex-Splentinex-Regular-osf-ly1.vf \
tex-Splentinex-Regular-osf-ot1.tfm \
tex-Splentinex-Regular-osf-sc-ly1--base.tfm \
tex-Splentinex-Regular-osf-sc-ly1.tfm \
tex-Splentinex-Regular-osf-sc-ly1.vf \
tex-Splentinex-Regular-osf-sc-ot1--base.tfm \
tex-Splentinex-Regular-osf-sc-ot1.tfm \
tex-Splentinex-Regular-osf-sc-ot1.vf \
tex-Splentinex-Regular-osf-sc-t1--base.tfm \
tex-Splentinex-Regular-osf-sc-t1.tfm \
tex-Splentinex-Regular-osf-sc-t1.vf \
tex-Splentinex-Regular-osf-t1--base.tfm \
tex-Splentinex-Regular-osf-t1.tfm \
tex-Splentinex-Regular-osf-t1.vf \
tex-Splentinex-Regular-osf-ts1--base.tfm \
tex-Splentinex-Regular-osf-ts1.tfm \
tex-Splentinex-Regular-osf-ts1.vf \
tex-Splentinex-Regular-sup-ly1--base.tfm \
tex-Splentinex-Regular-sup-ly1.tfm \
tex-Splentinex-Regular-sup-ly1.vf \
tex-Splentinex-Regular-sup-ot1.tfm \
tex-Splentinex-Regular-sup-t1--base.tfm \
tex-Splentinex-Regular-sup-t1.tfm \
tex-Splentinex-Regular-sup-t1.vf \
tex-Splentinex-Regular-tlf-ly1--base.tfm \
tex-Splentinex-Regular-tlf-ly1.tfm \
tex-Splentinex-Regular-tlf-ly1.vf \
tex-Splentinex-Regular-tlf-ot1.tfm \
tex-Splentinex-Regular-tlf-sc-ly1--base.tfm \
tex-Splentinex-Regular-tlf-sc-ly1.tfm \
tex-Splentinex-Regular-tlf-sc-ly1.vf \
tex-Splentinex-Regular-tlf-sc-ot1--base.tfm \
tex-Splentinex-Regular-tlf-sc-ot1.tfm \
tex-Splentinex-Regular-tlf-sc-ot1.vf \
tex-Splentinex-Regular-tlf-sc-t1--base.tfm \
tex-Splentinex-Regular-tlf-sc-t1.tfm \
tex-Splentinex-Regular-tlf-sc-t1.vf \
tex-Splentinex-Regular-tlf-t1--base.tfm \
tex-Splentinex-Regular-tlf-t1.tfm \
tex-Splentinex-Regular-tlf-t1.vf \
tex-Splentinex-Regular-tlf-ts1--base.tfm \
tex-Splentinex-Regular-tlf-ts1.tfm \
tex-Splentinex-Regular-tlf-ts1.vf \
tex-Splentinex-Regular-tosf-ly1--base.tfm \
tex-Splentinex-Regular-tosf-ly1.tfm \
tex-Splentinex-Regular-tosf-ly1.vf \
tex-Splentinex-Regular-tosf-ot1.tfm \
tex-Splentinex-Regular-tosf-sc-ly1--base.tfm \
tex-Splentinex-Regular-tosf-sc-ly1.tfm \
tex-Splentinex-Regular-tosf-sc-ly1.vf \
tex-Splentinex-Regular-tosf-sc-ot1--base.tfm \
tex-Splentinex-Regular-tosf-sc-ot1.tfm \
tex-Splentinex-Regular-tosf-sc-ot1.vf \
tex-Splentinex-Regular-tosf-sc-t1--base.tfm \
tex-Splentinex-Regular-tosf-sc-t1.tfm \
tex-Splentinex-Regular-tosf-sc-t1.vf \
tex-Splentinex-Regular-tosf-t1--base.tfm \
tex-Splentinex-Regular-tosf-t1.tfm \
tex-Splentinex-Regular-tosf-t1.vf \
tex-Splentinex-Regular-tosf-ts1--base.tfm \
tex-Splentinex-Regular-tosf-ts1.tfm \
tex-Splentinex-Regular-tosf-ts1.vf \
tex-Splentinex.map \
tex-T1Splentinex-LF.fd \
tex-T1Splentinex-OsF.fd \
tex-T1Splentinex-Sup.fd \
tex-T1Splentinex-TLF.fd \
tex-T1Splentinex-TOsF.fd \
tex-TS1Splentinex-LF.fd \
tex-TS1Splentinex-OsF.fd \
tex-TS1Splentinex-TLF.fd \
tex-TS1Splentinex-TOsF.fd \
tex-a-2gekco.enc \
tex-a-2iz2sr.enc \
tex-a-2p2zzs.enc \
tex-a-2pnyws.enc \
tex-a-2znksq.enc \
tex-a-3aazg7.enc \
tex-a-3kplpt.enc \
tex-a-4uxgok.enc \
tex-a-4vbjpw.enc \
tex-a-5xw7lp.enc \
tex-a-62jjtc.enc \
tex-a-6bbor7.enc \
tex-a-7ps5sb.enc \
tex-a-au3tcv.enc \
tex-a-b2rnw3.enc \
tex-a-bdz5es.enc \
tex-a-bhd4sx.enc \
tex-a-bi5jcg.enc \
tex-a-cbhkdk.enc \
tex-a-ciqtcf.enc \
tex-a-e2iuvi.enc \
tex-a-ety7n2.enc \
tex-a-fznad4.enc \
tex-a-g5mnx3.enc \
tex-a-gkjzhd.enc \
tex-a-hsojxt.enc \
tex-a-i7ugwh.enc \
tex-a-jd3ttb.enc \
tex-a-jymrki.enc \
tex-a-kkh65j.enc \
tex-a-lys2ul.enc \
tex-a-m4j3uc.enc \
tex-a-mlamai.enc \
tex-a-n7whle.enc \
tex-a-ohod5z.enc \
tex-a-oimab4.enc \
tex-a-seb2tw.enc \
tex-a-smjuqr.enc \
tex-a-tva6pz.enc \
tex-a-vey3m7.enc \
tex-a-xmjyk6.enc \
tex-a-zlyi4r.enc \
tex-splentinex.sty \
texlive-splentinex"

RDEPENDS:${PN} += "/usr/bin/sh \
coreutils \
ed \
findutils \
grep \
sed \
tex-fontaxes.sty \
tex-fontenc.sty \
tex-ifthen.sty \
tex-textcomp.sty \
tex-updmap.cfg \
tex-xkeyval.sty \
texlive \
texlive-filesystem \
texlive-kpathsea \
texlive-kpathsea-bin \
texlive-scripts \
texlive-scripts-bin \
texlive-splentinex-fonts"

inherit rpm
