SUMMARY = "Support for Technical Reports by US Navy Organizations"
DESCRIPTION = "The navydocs package provides an easy means for creating title \
pages and the following supplementary material pages used in \
technical reports by United States Navy organizations. These \
pages are generated by specifying the page content via a set of \
commands and then calling a macro to create the page at its \
occurrence in the document. This package is provided in the \
hope that it proves useful to other Navy organizations, with \
users contributing macros for their organizations."
LICENSE = "LPPL-1.0"

PV = "2026.226.1.1svn76924"

RPM_NAME = "texlive-navydocs-2026.226.1.1svn76924-61.2.noarch.rpm"
RPM_HASH = "dfbb5856b90bc9bc6d7f751739ef4bbdf3d66f255462a019abbb8624b4b57da480e52f95e40787beedf5ec2df02b0166753bbb4b80a53fc9274786050ff9f2eb"
REPO_ARCH = "noarch"

RPROVIDES:${PN} += "tex-navydocs.sty \
texlive-navydocs"

RDEPENDS:${PN} += "/usr/bin/sh \
coreutils \
ed \
findutils \
grep \
sed \
tex-eso-pic.sty \
tex-fancyhdr.sty \
tex-relsize.sty \
tex-rotating.sty \
tex-setspace.sty \
tex-xparse.sty \
texlive \
texlive-filesystem \
texlive-kpathsea \
texlive-kpathsea-bin \
texlive-scripts \
texlive-scripts-bin"

inherit rpm
