SUMMARY = "Udev files for libstoragemgmt"
DESCRIPTION = "The libstoragemgmt-udev package contains udev rules and helper utilities for \
uevents generated by the kernel."
LICENSE = "GPL-2.0-or-later & LGPL-2.1-or-later"

PV = "1.10.3"

RPM_NAME = "libstoragemgmt-udev-1.10.3-1.3.aarch64.rpm"
RPM_HASH = "a07ca7c503c5ad3ae97282c3ad6c913e5657436519507964cf183ed1cfba3ff94ea0b69a0b3208cc8e1190945ccde6e8668e3999aa15579c403262678500bd24"

RPROVIDES:${PN} += "libstoragemgmt-udev"

RDEPENDS:${PN} += "/usr/bin/sh \
ld-linux-aarch64.so.1 \
libc.so.6"

inherit rpm
