SUMMARY = "Parse partial JSON generated by LLM"
DESCRIPTION = "Parse partial and incomplete JSON strings, such as the streamed output of \
a large language model (LLM). Before the final token of a response is \
received the JSON is broken and cannot be decoded with a normal parser; \
partial-json-parser completes the fragment so the partial structure can be \
used while streaming. It is implemented purely in Python and is \
zero-dependency."
LICENSE = "MIT"

PV = "0.2.1.1.post7"

RPM_NAME = "python313-partial-json-parser-0.2.1.1.post7-1.1.noarch.rpm"
RPM_HASH = "50aa2e59534d79252af94211e38a1ca37216bb7dc5985e52ecfd140886456b5837fb0a8e0f6ded1742d3baefd9529bae72719ef634147cf26f167b751e8d3dcd"
REPO_ARCH = "noarch"

RPROVIDES:${PN} += "python3-partial-json-parser \
python3.13dist-partial-json-parser \
python313-partial-json-parser \
python3dist-partial-json-parser"

RDEPENDS:${PN} += "python-abi"

inherit rpm
