SUMMARY = "Lua Documentation for lpeg"
DESCRIPTION = "Documentation and examples included with the library, sometimes \
generated by luadoc or ldoc."
LICENSE = "MIT"

PV = "1.1.0"

RPM_NAME = "lua54-lpeg-doc-1.1.0-3.4.noarch.rpm"
RPM_HASH = "bc6248ac57d9808da62cc6d378aebe952dd33c14410702b7ca096712cf2861d297addd553f45f1ddddd95a8025bfd9dbe14de07cb24a3bd8dad0718a93573f1e"
REPO_ARCH = "noarch"

RPROVIDES:${PN} += "lua54-lpeg-doc"

RDEPENDS:${PN} += "lua54-lpeg"

inherit rpm
