SUMMARY = "HTML documentation for ZNC"
DESCRIPTION = "HTML Documentation for ZNC, generated by doxygen."
LICENSE = "Apache-2.0"

PV = "1.10.3"

RPM_NAME = "znc-doc-1.10.3-1.1.noarch.rpm"
RPM_HASH = "283c756b9b57d1c0a699e03961303369c12315ec24e39dbda5482da5c340d3720a02c75495b3b217c89afcf9cecb51d6cf2e9e79a7a2f570dc0835128d85cfcb"
REPO_ARCH = "noarch"

RPROVIDES:${PN} += "znc-doc"

RDEPENDS:${PN} += ""

inherit rpm
