SUMMARY = "OBS Source Service and utilities for Rust software packaging"
DESCRIPTION = "This is an OBS Source Service that contains two main utilities: \
- OBS Service Cargo Vendor \
- OBS Service Cargo Vendor Home Registry \
 \
This vendors and audits dependencies for packaging Rust software. \
 \
See the <https://github.com/openSUSE-Rust/obs-service-cargo/blob/master/README.md> \
for full documentation."
LICENSE = "MPL-2.0"

PV = "7.2.2"

RPM_NAME = "obs-service-cargo-7.2.2-2.2.aarch64.rpm"
RPM_HASH = "6c9d593345d95a22a63911df260b013a5113617ad994cef538349498b7a0eaa2216d69afe5643ac829aafe4cb5ec213c7229b73464808ec5946a50d95a9eb0ef"

RPROVIDES:${PN} += "bundled-rust-crate-adler2 \
bundled-rust-crate-aho-corasick \
bundled-rust-crate-allocator-api2 \
bundled-rust-crate-anstream \
bundled-rust-crate-anstyle \
bundled-rust-crate-anstyle-parse \
bundled-rust-crate-anstyle-query \
bundled-rust-crate-arc-swap \
bundled-rust-crate-arrayref \
bundled-rust-crate-arrayvec \
bundled-rust-crate-async-compression \
bundled-rust-crate-atomic-waker \
bundled-rust-crate-autocfg \
bundled-rust-crate-aws-lc-rs \
bundled-rust-crate-aws-lc-sys \
bundled-rust-crate-base64 \
bundled-rust-crate-bitflags \
bundled-rust-crate-blake3 \
bundled-rust-crate-block-buffer \
bundled-rust-crate-borsh \
bundled-rust-crate-bstr \
bundled-rust-crate-byteorder \
bundled-rust-crate-bytes \
bundled-rust-crate-bzip2 \
bundled-rust-crate-bzip2-sys \
bundled-rust-crate-camino \
bundled-rust-crate-cargo-lock \
bundled-rust-crate-cc \
bundled-rust-crate-cfb \
bundled-rust-crate-cfg-aliases \
bundled-rust-crate-cfg-if \
bundled-rust-crate-chacha20 \
bundled-rust-crate-clap \
bundled-rust-crate-clap-builder \
bundled-rust-crate-clap-complete \
bundled-rust-crate-clap-derive \
bundled-rust-crate-clap-lex \
bundled-rust-crate-clru \
bundled-rust-crate-cmake \
bundled-rust-crate-colorchoice \
bundled-rust-crate-compression-codecs \
bundled-rust-crate-compression-core \
bundled-rust-crate-constant-time-eq \
bundled-rust-crate-cpufeatures \
bundled-rust-crate-crc32fast \
bundled-rust-crate-crossbeam-channel \
bundled-rust-crate-crossbeam-deque \
bundled-rust-crate-crossbeam-epoch \
bundled-rust-crate-crossbeam-utils \
bundled-rust-crate-crypto-common \
bundled-rust-crate-cvss \
bundled-rust-crate-defmt \
bundled-rust-crate-defmt-macros \
bundled-rust-crate-defmt-parser \
bundled-rust-crate-deranged \
bundled-rust-crate-digest \
bundled-rust-crate-displaydoc \
bundled-rust-crate-dunce \
bundled-rust-crate-either \
bundled-rust-crate-encoding-rs \
bundled-rust-crate-equivalent \
bundled-rust-crate-errno \
bundled-rust-crate-faster-hex \
bundled-rust-crate-fastrand \
bundled-rust-crate-filetime \
bundled-rust-crate-find-msvc-tools \
bundled-rust-crate-flate2 \
bundled-rust-crate-fnv \
bundled-rust-crate-foldhash \
bundled-rust-crate-form-urlencoded \
bundled-rust-crate-fs-err \
bundled-rust-crate-fs-extra \
bundled-rust-crate-futures-channel \
bundled-rust-crate-futures-core \
bundled-rust-crate-futures-io \
bundled-rust-crate-futures-sink \
bundled-rust-crate-futures-task \
bundled-rust-crate-futures-util \
bundled-rust-crate-generic-array \
bundled-rust-crate-getrandom \
bundled-rust-crate-git2 \
bundled-rust-crate-gix \
bundled-rust-crate-gix-actor \
bundled-rust-crate-gix-attributes \
bundled-rust-crate-gix-bitmap \
bundled-rust-crate-gix-chunk \
bundled-rust-crate-gix-command \
bundled-rust-crate-gix-commitgraph \
bundled-rust-crate-gix-config \
bundled-rust-crate-gix-config-value \
bundled-rust-crate-gix-credentials \
bundled-rust-crate-gix-date \
bundled-rust-crate-gix-diff \
bundled-rust-crate-gix-discover \
bundled-rust-crate-gix-error \
bundled-rust-crate-gix-features \
bundled-rust-crate-gix-filter \
bundled-rust-crate-gix-fs \
bundled-rust-crate-gix-glob \
bundled-rust-crate-gix-hash \
bundled-rust-crate-gix-hashtable \
bundled-rust-crate-gix-ignore \
bundled-rust-crate-gix-index \
bundled-rust-crate-gix-lock \
bundled-rust-crate-gix-negotiate \
bundled-rust-crate-gix-object \
bundled-rust-crate-gix-odb \
bundled-rust-crate-gix-pack \
bundled-rust-crate-gix-packetline \
bundled-rust-crate-gix-path \
bundled-rust-crate-gix-pathspec \
bundled-rust-crate-gix-prompt \
bundled-rust-crate-gix-protocol \
bundled-rust-crate-gix-quote \
bundled-rust-crate-gix-ref \
bundled-rust-crate-gix-refspec \
bundled-rust-crate-gix-revision \
bundled-rust-crate-gix-revwalk \
bundled-rust-crate-gix-sec \
bundled-rust-crate-gix-shallow \
bundled-rust-crate-gix-submodule \
bundled-rust-crate-gix-tempfile \
bundled-rust-crate-gix-trace \
bundled-rust-crate-gix-transport \
bundled-rust-crate-gix-traverse \
bundled-rust-crate-gix-url \
bundled-rust-crate-gix-utils \
bundled-rust-crate-gix-validate \
bundled-rust-crate-gix-worktree \
bundled-rust-crate-gix-worktree-state \
bundled-rust-crate-glob \
bundled-rust-crate-h2 \
bundled-rust-crate-hash32 \
bundled-rust-crate-hashbrown \
bundled-rust-crate-heapless \
bundled-rust-crate-heck \
bundled-rust-crate-hifitime \
bundled-rust-crate-home \
bundled-rust-crate-http \
bundled-rust-crate-http-body \
bundled-rust-crate-http-body-util \
bundled-rust-crate-httparse \
bundled-rust-crate-hyper \
bundled-rust-crate-hyper-rustls \
bundled-rust-crate-hyper-util \
bundled-rust-crate-icu-collections \
bundled-rust-crate-icu-locale-core \
bundled-rust-crate-icu-normalizer \
bundled-rust-crate-icu-normalizer-data \
bundled-rust-crate-icu-properties \
bundled-rust-crate-icu-properties-data \
bundled-rust-crate-icu-provider \
bundled-rust-crate-idna \
bundled-rust-crate-idna-adapter \
bundled-rust-crate-indexmap \
bundled-rust-crate-infer \
bundled-rust-crate-io-close \
bundled-rust-crate-ipnet \
bundled-rust-crate-is-terminal-polyfill \
bundled-rust-crate-itoa \
bundled-rust-crate-jiff \
bundled-rust-crate-jiff-core \
bundled-rust-crate-jiff-static \
bundled-rust-crate-jobserver \
bundled-rust-crate-kstring \
bundled-rust-crate-lazy-static \
bundled-rust-crate-lexical-core \
bundled-rust-crate-lexical-parse-float \
bundled-rust-crate-lexical-parse-integer \
bundled-rust-crate-lexical-util \
bundled-rust-crate-libc \
bundled-rust-crate-libgit2-sys \
bundled-rust-crate-libm \
bundled-rust-crate-libroast \
bundled-rust-crate-libssh2-sys \
bundled-rust-crate-libz-sys \
bundled-rust-crate-linux-raw-sys \
bundled-rust-crate-litemap \
bundled-rust-crate-lock-api \
bundled-rust-crate-log \
bundled-rust-crate-lru-slab \
bundled-rust-crate-lzma-sys \
bundled-rust-crate-matchers \
bundled-rust-crate-maybe-async \
bundled-rust-crate-memchr \
bundled-rust-crate-memmap2 \
bundled-rust-crate-mime \
bundled-rust-crate-minimal-lexical \
bundled-rust-crate-miniz-oxide \
bundled-rust-crate-mio \
bundled-rust-crate-nom \
bundled-rust-crate-nu-ansi-term \
bundled-rust-crate-num-conv \
bundled-rust-crate-num-traits \
bundled-rust-crate-obs-service-cargo \
bundled-rust-crate-once-cell \
bundled-rust-crate-openssl-probe \
bundled-rust-crate-openssl-sys \
bundled-rust-crate-parking-lot \
bundled-rust-crate-parking-lot-core \
bundled-rust-crate-percent-encoding \
bundled-rust-crate-phf \
bundled-rust-crate-phf-codegen \
bundled-rust-crate-phf-generator \
bundled-rust-crate-phf-shared \
bundled-rust-crate-pin-project-lite \
bundled-rust-crate-pkg-config \
bundled-rust-crate-platforms \
bundled-rust-crate-potential-utf \
bundled-rust-crate-powerfmt \
bundled-rust-crate-proc-macro2 \
bundled-rust-crate-prodash \
bundled-rust-crate-quick-xml \
bundled-rust-crate-quinn \
bundled-rust-crate-quinn-proto \
bundled-rust-crate-quinn-udp \
bundled-rust-crate-quote \
bundled-rust-crate-rand \
bundled-rust-crate-rand-core \
bundled-rust-crate-rand-pcg \
bundled-rust-crate-rayon \
bundled-rust-crate-rayon-core \
bundled-rust-crate-regex \
bundled-rust-crate-regex-automata \
bundled-rust-crate-regex-syntax \
bundled-rust-crate-reqwest \
bundled-rust-crate-ring \
bundled-rust-crate-rustc-hash \
bundled-rust-crate-rustc-stable-hash \
bundled-rust-crate-rustix \
bundled-rust-crate-rustls \
bundled-rust-crate-rustls-native-certs \
bundled-rust-crate-rustls-pki-types \
bundled-rust-crate-rustls-platform-verifier \
bundled-rust-crate-rustls-webpki \
bundled-rust-crate-rustsec \
bundled-rust-crate-rustversion \
bundled-rust-crate-same-file \
bundled-rust-crate-scopeguard \
bundled-rust-crate-semver \
bundled-rust-crate-serde \
bundled-rust-crate-serde-core \
bundled-rust-crate-serde-derive \
bundled-rust-crate-serde-json \
bundled-rust-crate-serde-spanned \
bundled-rust-crate-sha1 \
bundled-rust-crate-sha1-checked \
bundled-rust-crate-sharded-slab \
bundled-rust-crate-shell-words \
bundled-rust-crate-shlex \
bundled-rust-crate-signal-hook-registry \
bundled-rust-crate-simd-adler32 \
bundled-rust-crate-siphasher \
bundled-rust-crate-slab \
bundled-rust-crate-smallvec \
bundled-rust-crate-smol-str \
bundled-rust-crate-snafu \
bundled-rust-crate-snafu-derive \
bundled-rust-crate-socket2 \
bundled-rust-crate-stable-deref-trait \
bundled-rust-crate-static-assertions \
bundled-rust-crate-strsim \
bundled-rust-crate-subtle \
bundled-rust-crate-syn \
bundled-rust-crate-sync-wrapper \
bundled-rust-crate-synstructure \
bundled-rust-crate-tame-index \
bundled-rust-crate-tar \
bundled-rust-crate-tempfile \
bundled-rust-crate-terminal-size \
bundled-rust-crate-terminfo \
bundled-rust-crate-thiserror \
bundled-rust-crate-thiserror-impl \
bundled-rust-crate-thread-local \
bundled-rust-crate-time \
bundled-rust-crate-time-core \
bundled-rust-crate-time-macros \
bundled-rust-crate-tinystr \
bundled-rust-crate-tinyvec \
bundled-rust-crate-tinyvec-macros \
bundled-rust-crate-tokio \
bundled-rust-crate-tokio-macros \
bundled-rust-crate-tokio-rustls \
bundled-rust-crate-tokio-util \
bundled-rust-crate-toml \
bundled-rust-crate-toml-datetime \
bundled-rust-crate-toml-parser \
bundled-rust-crate-toml-span \
bundled-rust-crate-toml-writer \
bundled-rust-crate-tower \
bundled-rust-crate-tower-http \
bundled-rust-crate-tower-layer \
bundled-rust-crate-tower-service \
bundled-rust-crate-tracing \
bundled-rust-crate-tracing-attributes \
bundled-rust-crate-tracing-core \
bundled-rust-crate-tracing-log \
bundled-rust-crate-tracing-subscriber \
bundled-rust-crate-try-lock \
bundled-rust-crate-twox-hash \
bundled-rust-crate-typenum \
bundled-rust-crate-uluru \
bundled-rust-crate-unicode-bom \
bundled-rust-crate-unicode-ident \
bundled-rust-crate-unicode-normalization \
bundled-rust-crate-untrusted \
bundled-rust-crate-url \
bundled-rust-crate-utf8-iter \
bundled-rust-crate-utf8parse \
bundled-rust-crate-uuid \
bundled-rust-crate-vcpkg \
bundled-rust-crate-version-check \
bundled-rust-crate-walkdir \
bundled-rust-crate-want \
bundled-rust-crate-web-time \
bundled-rust-crate-winnow \
bundled-rust-crate-writeable \
bundled-rust-crate-xattr \
bundled-rust-crate-xz2 \
bundled-rust-crate-yoke \
bundled-rust-crate-yoke-derive \
bundled-rust-crate-zerofrom \
bundled-rust-crate-zerofrom-derive \
bundled-rust-crate-zeroize \
bundled-rust-crate-zerotrie \
bundled-rust-crate-zerovec \
bundled-rust-crate-zerovec-derive \
bundled-rust-crate-zlib-rs \
bundled-rust-crate-zmij \
bundled-rust-crate-zstd \
bundled-rust-crate-zstd-safe \
bundled-rust-crate-zstd-sys \
obs-service-cargo \
obs-service-cargo-audit \
obs-service-cargo-vendor"

RDEPENDS:${PN} += "cargo-vendor-filterer \
libc.so.6 \
libcrypto.so.3 \
libgcc-s.so.1 \
libm.so.6 \
libssl.so.3 \
libz.so.1 \
libzstd.so.1"

inherit rpm
