SUMMARY = "Basic utilities for writing tests"
DESCRIPTION = "** If you are unfamiliar with testing *read Test::Tutorial first!* ** \
 \
This is an extremely simple, extremely basic module for writing tests \
suitable for CPAN modules and other pursuits. If you wish to do more \
complicated testing, use the Test::More module (a drop-in replacement for \
this one)."
LICENSE = "Artistic-1.0 | GPL-1.0-or-later"

PV = "1.302225"

RPM_NAME = "perl-Test-Simple-1.302225-1.1.noarch.rpm"
RPM_HASH = "3920b190e457182a878f3f9e3f3d74efafe5110a38ca407b3b261faab0d62da2e2eda59e29294793a595647676659c7402699b1421eeb19fca92bc6fa94ccb45"
REPO_ARCH = "noarch"

RPROVIDES:${PN} += "perl-Test--Builder \
perl-Test--Builder--Formatter \
perl-Test--Builder--Module \
perl-Test--Builder--Tester \
perl-Test--Builder--Tester--Color \
perl-Test--Builder--Tester--Tie \
perl-Test--Builder--TodoDiag \
perl-Test--More \
perl-Test--Simple \
perl-Test--Tester \
perl-Test--Tester--Capture \
perl-Test--Tester--CaptureRunner \
perl-Test--Tester--Delegate \
perl-Test--use--ok \
perl-Test-Simple \
perl-Test2 \
perl-Test2--API \
perl-Test2--API--Breakage \
perl-Test2--API--Context \
perl-Test2--API--Instance \
perl-Test2--API--InterceptResult \
perl-Test2--API--InterceptResult--Event \
perl-Test2--API--InterceptResult--Facet \
perl-Test2--API--InterceptResult--Hub \
perl-Test2--API--InterceptResult--Squasher \
perl-Test2--API--Stack \
perl-Test2--AsyncSubtest \
perl-Test2--AsyncSubtest--Event--Attach \
perl-Test2--AsyncSubtest--Event--Detach \
perl-Test2--AsyncSubtest--Formatter \
perl-Test2--AsyncSubtest--Hub \
perl-Test2--Bundle \
perl-Test2--Bundle--Extended \
perl-Test2--Bundle--More \
perl-Test2--Bundle--Simple \
perl-Test2--Compare \
perl-Test2--Compare--Array \
perl-Test2--Compare--Bag \
perl-Test2--Compare--Base \
perl-Test2--Compare--Bool \
perl-Test2--Compare--Custom \
perl-Test2--Compare--DeepRef \
perl-Test2--Compare--Delta \
perl-Test2--Compare--Event \
perl-Test2--Compare--EventMeta \
perl-Test2--Compare--Float \
perl-Test2--Compare--Hash \
perl-Test2--Compare--Isa \
perl-Test2--Compare--Meta \
perl-Test2--Compare--Negatable \
perl-Test2--Compare--Number \
perl-Test2--Compare--Object \
perl-Test2--Compare--OrderedSubset \
perl-Test2--Compare--Pattern \
perl-Test2--Compare--Ref \
perl-Test2--Compare--Regex \
perl-Test2--Compare--Scalar \
perl-Test2--Compare--Set \
perl-Test2--Compare--String \
perl-Test2--Compare--Undef \
perl-Test2--Compare--Wildcard \
perl-Test2--Env \
perl-Test2--Event \
perl-Test2--Event--Bail \
perl-Test2--Event--Diag \
perl-Test2--Event--Encoding \
perl-Test2--Event--Exception \
perl-Test2--Event--Fail \
perl-Test2--Event--Generic \
perl-Test2--Event--Note \
perl-Test2--Event--Ok \
perl-Test2--Event--Pass \
perl-Test2--Event--Plan \
perl-Test2--Event--Skip \
perl-Test2--Event--Subtest \
perl-Test2--Event--TAP--Version \
perl-Test2--Event--V2 \
perl-Test2--Event--Waiting \
perl-Test2--EventFacet \
perl-Test2--EventFacet--About \
perl-Test2--EventFacet--Amnesty \
perl-Test2--EventFacet--Assert \
perl-Test2--EventFacet--Control \
perl-Test2--EventFacet--Error \
perl-Test2--EventFacet--Hub \
perl-Test2--EventFacet--Info \
perl-Test2--EventFacet--Info--Table \
perl-Test2--EventFacet--Meta \
perl-Test2--EventFacet--Parent \
perl-Test2--EventFacet--Plan \
perl-Test2--EventFacet--Render \
perl-Test2--EventFacet--Trace \
perl-Test2--Formatter \
perl-Test2--Formatter--TAP \
perl-Test2--Handle \
perl-Test2--Hub \
perl-Test2--Hub--Interceptor \
perl-Test2--Hub--Interceptor--Terminator \
perl-Test2--Hub--Subtest \
perl-Test2--IPC \
perl-Test2--IPC--Driver \
perl-Test2--IPC--Driver--Files \
perl-Test2--Manual \
perl-Test2--Manual--Anatomy \
perl-Test2--Manual--Anatomy--API \
perl-Test2--Manual--Anatomy--Context \
perl-Test2--Manual--Anatomy--EndToEnd \
perl-Test2--Manual--Anatomy--Event \
perl-Test2--Manual--Anatomy--Hubs \
perl-Test2--Manual--Anatomy--IPC \
perl-Test2--Manual--Anatomy--Utilities \
perl-Test2--Manual--Concurrency \
perl-Test2--Manual--Contributing \
perl-Test2--Manual--Testing \
perl-Test2--Manual--Testing--Introduction \
perl-Test2--Manual--Testing--Migrating \
perl-Test2--Manual--Testing--Planning \
perl-Test2--Manual--Testing--Todo \
perl-Test2--Manual--Tooling \
perl-Test2--Manual--Tooling--FirstTool \
perl-Test2--Manual--Tooling--Formatter \
perl-Test2--Manual--Tooling--Nesting \
perl-Test2--Manual--Tooling--Plugin--TestExit \
perl-Test2--Manual--Tooling--Plugin--TestingDone \
perl-Test2--Manual--Tooling--Plugin--ToolCompletes \
perl-Test2--Manual--Tooling--Plugin--ToolStarts \
perl-Test2--Manual--Tooling--Subtest \
perl-Test2--Manual--Tooling--TestBuilder \
perl-Test2--Manual--Tooling--Testing \
perl-Test2--Mock \
perl-Test2--Plugin \
perl-Test2--Plugin--BailOnFail \
perl-Test2--Plugin--DieOnFail \
perl-Test2--Plugin--ExitSummary \
perl-Test2--Plugin--SRand \
perl-Test2--Plugin--Times \
perl-Test2--Plugin--UTF8 \
perl-Test2--Require \
perl-Test2--Require--AuthorTesting \
perl-Test2--Require--AutomatedTesting \
perl-Test2--Require--EnvVar \
perl-Test2--Require--ExtendedTesting \
perl-Test2--Require--Fork \
perl-Test2--Require--Module \
perl-Test2--Require--NonInteractiveTesting \
perl-Test2--Require--Perl \
perl-Test2--Require--RealFork \
perl-Test2--Require--ReleaseTesting \
perl-Test2--Require--Threads \
perl-Test2--Suite \
perl-Test2--Todo \
perl-Test2--Tools \
perl-Test2--Tools--AsyncSubtest \
perl-Test2--Tools--Basic \
perl-Test2--Tools--Class \
perl-Test2--Tools--ClassicCompare \
perl-Test2--Tools--Compare \
perl-Test2--Tools--Defer \
perl-Test2--Tools--Encoding \
perl-Test2--Tools--Event \
perl-Test2--Tools--Exception \
perl-Test2--Tools--Exports \
perl-Test2--Tools--GenTemp \
perl-Test2--Tools--Grab \
perl-Test2--Tools--Mock \
perl-Test2--Tools--Ref \
perl-Test2--Tools--Refcount \
perl-Test2--Tools--Spec \
perl-Test2--Tools--Subtest \
perl-Test2--Tools--Target \
perl-Test2--Tools--Tester \
perl-Test2--Tools--Tiny \
perl-Test2--Tools--Warnings \
perl-Test2--Util \
perl-Test2--Util--ExternalMeta \
perl-Test2--Util--Facets2Legacy \
perl-Test2--Util--Grabber \
perl-Test2--Util--Guard \
perl-Test2--Util--HashBase \
perl-Test2--Util--Importer \
perl-Test2--Util--Ref \
perl-Test2--Util--Sig \
perl-Test2--Util--Stash \
perl-Test2--Util--Sub \
perl-Test2--Util--Table \
perl-Test2--Util--Table--Cell \
perl-Test2--Util--Table--LineBreak \
perl-Test2--Util--Term \
perl-Test2--Util--Times \
perl-Test2--Util--Trace \
perl-Test2--V0 \
perl-Test2--V1 \
perl-Test2--V1--Base \
perl-Test2--V1--Handle \
perl-Test2--Workflow \
perl-Test2--Workflow--BlockBase \
perl-Test2--Workflow--Build \
perl-Test2--Workflow--Runner \
perl-Test2--Workflow--Task \
perl-Test2--Workflow--Task--Action \
perl-Test2--Workflow--Task--Group \
perl-ok"

RDEPENDS:${PN} += "perl--MODULE-COMPAT-5.44.0 \
perl-Term--Table"

inherit rpm
