SUMMARY = "Crimson fonts with LaTeX support"
DESCRIPTION = "This package provides LaTeX, pdfLaTeX, XeLaTeX, and LuaLaTeX \
support for the Crimson family of fonts, designed by Sebastian \
Kosch. The Crimson family is for book production in the \
tradition of beautiful oldstyle typefaces, inspired \
particularly by the work of people like Jan Tschichold (Sabon), \
Robert Slimbach (Arno, Minion), and Jonathan Hoefler (Hoefler \
Text). Small caps and old-style numerals are mostly available, \
except old-style numerals are not supported in Bold or \
Semibold."
LICENSE = "OFL-1.1"

PV = "2026.226.svn75712"

RPM_NAME = "texlive-crimson-2026.226.svn75712-61.2.noarch.rpm"
RPM_HASH = "e4a922994f3091184cc5aee64737f3a2edd86130eae05164f1965cf1f2c69258832cc605d7367fbff0d1095d6e94d9ec38880e0e2d4c4d2685d4d6ad2c3d8050"
REPO_ARCH = "noarch"

RPROVIDES:${PN} += "tex-Crimson-Bold-tlf-ly1--base.tfm \
tex-Crimson-Bold-tlf-ly1.tfm \
tex-Crimson-Bold-tlf-ly1.vf \
tex-Crimson-Bold-tlf-ot1.tfm \
tex-Crimson-Bold-tlf-sc-ly1--base.tfm \
tex-Crimson-Bold-tlf-sc-ly1.tfm \
tex-Crimson-Bold-tlf-sc-ly1.vf \
tex-Crimson-Bold-tlf-sc-ot1--base.tfm \
tex-Crimson-Bold-tlf-sc-ot1.tfm \
tex-Crimson-Bold-tlf-sc-ot1.vf \
tex-Crimson-Bold-tlf-sc-t1--base.tfm \
tex-Crimson-Bold-tlf-sc-t1.tfm \
tex-Crimson-Bold-tlf-sc-t1.vf \
tex-Crimson-Bold-tlf-t1--base.tfm \
tex-Crimson-Bold-tlf-t1.tfm \
tex-Crimson-Bold-tlf-t1.vf \
tex-Crimson-Bold-tlf-ts1--base.tfm \
tex-Crimson-Bold-tlf-ts1.tfm \
tex-Crimson-Bold-tlf-ts1.vf \
tex-Crimson-BoldItalic-lf-ly1--base.tfm \
tex-Crimson-BoldItalic-lf-ly1.tfm \
tex-Crimson-BoldItalic-lf-ly1.vf \
tex-Crimson-BoldItalic-lf-ot1.tfm \
tex-Crimson-BoldItalic-lf-t1--base.tfm \
tex-Crimson-BoldItalic-lf-t1.tfm \
tex-Crimson-BoldItalic-lf-t1.vf \
tex-Crimson-BoldItalic-lf-ts1--base.tfm \
tex-Crimson-BoldItalic-lf-ts1.tfm \
tex-Crimson-BoldItalic-lf-ts1.vf \
tex-Crimson-BoldItalic-osf-ly1--base.tfm \
tex-Crimson-BoldItalic-osf-ly1.tfm \
tex-Crimson-BoldItalic-osf-ly1.vf \
tex-Crimson-BoldItalic-osf-ot1.tfm \
tex-Crimson-BoldItalic-osf-t1--base.tfm \
tex-Crimson-BoldItalic-osf-t1.tfm \
tex-Crimson-BoldItalic-osf-t1.vf \
tex-Crimson-BoldItalic-osf-ts1--base.tfm \
tex-Crimson-BoldItalic-osf-ts1.tfm \
tex-Crimson-BoldItalic-osf-ts1.vf \
tex-Crimson-BoldItalic-tlf-ly1--base.tfm \
tex-Crimson-BoldItalic-tlf-ly1.tfm \
tex-Crimson-BoldItalic-tlf-ly1.vf \
tex-Crimson-BoldItalic-tlf-ot1.tfm \
tex-Crimson-BoldItalic-tlf-t1--base.tfm \
tex-Crimson-BoldItalic-tlf-t1.tfm \
tex-Crimson-BoldItalic-tlf-t1.vf \
tex-Crimson-BoldItalic-tlf-ts1--base.tfm \
tex-Crimson-BoldItalic-tlf-ts1.tfm \
tex-Crimson-BoldItalic-tlf-ts1.vf \
tex-Crimson-BoldItalic-tosf-ly1--base.tfm \
tex-Crimson-BoldItalic-tosf-ly1.tfm \
tex-Crimson-BoldItalic-tosf-ly1.vf \
tex-Crimson-BoldItalic-tosf-ot1.tfm \
tex-Crimson-BoldItalic-tosf-t1--base.tfm \
tex-Crimson-BoldItalic-tosf-t1.tfm \
tex-Crimson-BoldItalic-tosf-t1.vf \
tex-Crimson-BoldItalic-tosf-ts1--base.tfm \
tex-Crimson-BoldItalic-tosf-ts1.tfm \
tex-Crimson-BoldItalic-tosf-ts1.vf \
tex-Crimson-Italic-lf-ly1--base.tfm \
tex-Crimson-Italic-lf-ly1.tfm \
tex-Crimson-Italic-lf-ly1.vf \
tex-Crimson-Italic-lf-ot1.tfm \
tex-Crimson-Italic-lf-sc-ly1--base.tfm \
tex-Crimson-Italic-lf-sc-ly1.tfm \
tex-Crimson-Italic-lf-sc-ly1.vf \
tex-Crimson-Italic-lf-sc-ot1--base.tfm \
tex-Crimson-Italic-lf-sc-ot1.tfm \
tex-Crimson-Italic-lf-sc-ot1.vf \
tex-Crimson-Italic-lf-sc-t1--base.tfm \
tex-Crimson-Italic-lf-sc-t1.tfm \
tex-Crimson-Italic-lf-sc-t1.vf \
tex-Crimson-Italic-lf-t1--base.tfm \
tex-Crimson-Italic-lf-t1.tfm \
tex-Crimson-Italic-lf-t1.vf \
tex-Crimson-Italic-lf-ts1--base.tfm \
tex-Crimson-Italic-lf-ts1.tfm \
tex-Crimson-Italic-lf-ts1.vf \
tex-Crimson-Italic-osf-ly1--base.tfm \
tex-Crimson-Italic-osf-ly1.tfm \
tex-Crimson-Italic-osf-ly1.vf \
tex-Crimson-Italic-osf-ot1.tfm \
tex-Crimson-Italic-osf-sc-ly1--base.tfm \
tex-Crimson-Italic-osf-sc-ly1.tfm \
tex-Crimson-Italic-osf-sc-ly1.vf \
tex-Crimson-Italic-osf-sc-ot1--base.tfm \
tex-Crimson-Italic-osf-sc-ot1.tfm \
tex-Crimson-Italic-osf-sc-ot1.vf \
tex-Crimson-Italic-osf-sc-t1--base.tfm \
tex-Crimson-Italic-osf-sc-t1.tfm \
tex-Crimson-Italic-osf-sc-t1.vf \
tex-Crimson-Italic-osf-t1--base.tfm \
tex-Crimson-Italic-osf-t1.tfm \
tex-Crimson-Italic-osf-t1.vf \
tex-Crimson-Italic-osf-ts1--base.tfm \
tex-Crimson-Italic-osf-ts1.tfm \
tex-Crimson-Italic-osf-ts1.vf \
tex-Crimson-Italic-tlf-ly1--base.tfm \
tex-Crimson-Italic-tlf-ly1.tfm \
tex-Crimson-Italic-tlf-ly1.vf \
tex-Crimson-Italic-tlf-ot1.tfm \
tex-Crimson-Italic-tlf-sc-ly1--base.tfm \
tex-Crimson-Italic-tlf-sc-ly1.tfm \
tex-Crimson-Italic-tlf-sc-ly1.vf \
tex-Crimson-Italic-tlf-sc-ot1--base.tfm \
tex-Crimson-Italic-tlf-sc-ot1.tfm \
tex-Crimson-Italic-tlf-sc-ot1.vf \
tex-Crimson-Italic-tlf-sc-t1--base.tfm \
tex-Crimson-Italic-tlf-sc-t1.tfm \
tex-Crimson-Italic-tlf-sc-t1.vf \
tex-Crimson-Italic-tlf-t1--base.tfm \
tex-Crimson-Italic-tlf-t1.tfm \
tex-Crimson-Italic-tlf-t1.vf \
tex-Crimson-Italic-tlf-ts1--base.tfm \
tex-Crimson-Italic-tlf-ts1.tfm \
tex-Crimson-Italic-tlf-ts1.vf \
tex-Crimson-Italic-tosf-ly1--base.tfm \
tex-Crimson-Italic-tosf-ly1.tfm \
tex-Crimson-Italic-tosf-ly1.vf \
tex-Crimson-Italic-tosf-ot1.tfm \
tex-Crimson-Italic-tosf-sc-ly1--base.tfm \
tex-Crimson-Italic-tosf-sc-ly1.tfm \
tex-Crimson-Italic-tosf-sc-ly1.vf \
tex-Crimson-Italic-tosf-sc-ot1--base.tfm \
tex-Crimson-Italic-tosf-sc-ot1.tfm \
tex-Crimson-Italic-tosf-sc-ot1.vf \
tex-Crimson-Italic-tosf-sc-t1--base.tfm \
tex-Crimson-Italic-tosf-sc-t1.tfm \
tex-Crimson-Italic-tosf-sc-t1.vf \
tex-Crimson-Italic-tosf-t1--base.tfm \
tex-Crimson-Italic-tosf-t1.tfm \
tex-Crimson-Italic-tosf-t1.vf \
tex-Crimson-Italic-tosf-ts1--base.tfm \
tex-Crimson-Italic-tosf-ts1.tfm \
tex-Crimson-Italic-tosf-ts1.vf \
tex-Crimson-Roman-lf-ly1.tfm \
tex-Crimson-Roman-lf-ot1.tfm \
tex-Crimson-Roman-lf-sc-ly1--base.tfm \
tex-Crimson-Roman-lf-sc-ly1.tfm \
tex-Crimson-Roman-lf-sc-ly1.vf \
tex-Crimson-Roman-lf-sc-ot1--base.tfm \
tex-Crimson-Roman-lf-sc-ot1.tfm \
tex-Crimson-Roman-lf-sc-ot1.vf \
tex-Crimson-Roman-lf-sc-t1--base.tfm \
tex-Crimson-Roman-lf-sc-t1.tfm \
tex-Crimson-Roman-lf-sc-t1.vf \
tex-Crimson-Roman-lf-t1--base.tfm \
tex-Crimson-Roman-lf-t1.tfm \
tex-Crimson-Roman-lf-t1.vf \
tex-Crimson-Roman-lf-ts1--base.tfm \
tex-Crimson-Roman-lf-ts1.tfm \
tex-Crimson-Roman-lf-ts1.vf \
tex-Crimson-Roman-osf-ly1.tfm \
tex-Crimson-Roman-osf-ot1.tfm \
tex-Crimson-Roman-osf-sc-ly1--base.tfm \
tex-Crimson-Roman-osf-sc-ly1.tfm \
tex-Crimson-Roman-osf-sc-ly1.vf \
tex-Crimson-Roman-osf-sc-ot1--base.tfm \
tex-Crimson-Roman-osf-sc-ot1.tfm \
tex-Crimson-Roman-osf-sc-ot1.vf \
tex-Crimson-Roman-osf-sc-t1--base.tfm \
tex-Crimson-Roman-osf-sc-t1.tfm \
tex-Crimson-Roman-osf-sc-t1.vf \
tex-Crimson-Roman-osf-t1--base.tfm \
tex-Crimson-Roman-osf-t1.tfm \
tex-Crimson-Roman-osf-t1.vf \
tex-Crimson-Roman-osf-ts1--base.tfm \
tex-Crimson-Roman-osf-ts1.tfm \
tex-Crimson-Roman-osf-ts1.vf \
tex-Crimson-Roman-tlf-ly1.tfm \
tex-Crimson-Roman-tlf-ot1.tfm \
tex-Crimson-Roman-tlf-sc-ly1--base.tfm \
tex-Crimson-Roman-tlf-sc-ly1.tfm \
tex-Crimson-Roman-tlf-sc-ly1.vf \
tex-Crimson-Roman-tlf-sc-ot1--base.tfm \
tex-Crimson-Roman-tlf-sc-ot1.tfm \
tex-Crimson-Roman-tlf-sc-ot1.vf \
tex-Crimson-Roman-tlf-sc-t1--base.tfm \
tex-Crimson-Roman-tlf-sc-t1.tfm \
tex-Crimson-Roman-tlf-sc-t1.vf \
tex-Crimson-Roman-tlf-t1--base.tfm \
tex-Crimson-Roman-tlf-t1.tfm \
tex-Crimson-Roman-tlf-t1.vf \
tex-Crimson-Roman-tlf-ts1--base.tfm \
tex-Crimson-Roman-tlf-ts1.tfm \
tex-Crimson-Roman-tlf-ts1.vf \
tex-Crimson-Roman-tosf-ly1.tfm \
tex-Crimson-Roman-tosf-ot1.tfm \
tex-Crimson-Roman-tosf-sc-ly1--base.tfm \
tex-Crimson-Roman-tosf-sc-ly1.tfm \
tex-Crimson-Roman-tosf-sc-ly1.vf \
tex-Crimson-Roman-tosf-sc-ot1--base.tfm \
tex-Crimson-Roman-tosf-sc-ot1.tfm \
tex-Crimson-Roman-tosf-sc-ot1.vf \
tex-Crimson-Roman-tosf-sc-t1--base.tfm \
tex-Crimson-Roman-tosf-sc-t1.tfm \
tex-Crimson-Roman-tosf-sc-t1.vf \
tex-Crimson-Roman-tosf-t1--base.tfm \
tex-Crimson-Roman-tosf-t1.tfm \
tex-Crimson-Roman-tosf-t1.vf \
tex-Crimson-Roman-tosf-ts1--base.tfm \
tex-Crimson-Roman-tosf-ts1.tfm \
tex-Crimson-Roman-tosf-ts1.vf \
tex-Crimson-Semibold-lf-ly1--base.tfm \
tex-Crimson-Semibold-lf-ly1.tfm \
tex-Crimson-Semibold-lf-ly1.vf \
tex-Crimson-Semibold-lf-ot1.tfm \
tex-Crimson-Semibold-lf-t1--base.tfm \
tex-Crimson-Semibold-lf-t1.tfm \
tex-Crimson-Semibold-lf-t1.vf \
tex-Crimson-Semibold-lf-ts1--base.tfm \
tex-Crimson-Semibold-lf-ts1.tfm \
tex-Crimson-Semibold-lf-ts1.vf \
tex-Crimson-Semibold-tlf-ly1--base.tfm \
tex-Crimson-Semibold-tlf-ly1.tfm \
tex-Crimson-Semibold-tlf-ly1.vf \
tex-Crimson-Semibold-tlf-ot1.tfm \
tex-Crimson-Semibold-tlf-t1--base.tfm \
tex-Crimson-Semibold-tlf-t1.tfm \
tex-Crimson-Semibold-tlf-t1.vf \
tex-Crimson-Semibold-tlf-ts1--base.tfm \
tex-Crimson-Semibold-tlf-ts1.tfm \
tex-Crimson-Semibold-tlf-ts1.vf \
tex-Crimson-SemiboldItalic-lf-ly1--base.tfm \
tex-Crimson-SemiboldItalic-lf-ly1.tfm \
tex-Crimson-SemiboldItalic-lf-ly1.vf \
tex-Crimson-SemiboldItalic-lf-ot1.tfm \
tex-Crimson-SemiboldItalic-lf-t1--base.tfm \
tex-Crimson-SemiboldItalic-lf-t1.tfm \
tex-Crimson-SemiboldItalic-lf-t1.vf \
tex-Crimson-SemiboldItalic-lf-ts1--base.tfm \
tex-Crimson-SemiboldItalic-lf-ts1.tfm \
tex-Crimson-SemiboldItalic-lf-ts1.vf \
tex-Crimson-SemiboldItalic-tlf-ly1--base.tfm \
tex-Crimson-SemiboldItalic-tlf-ly1.tfm \
tex-Crimson-SemiboldItalic-tlf-ly1.vf \
tex-Crimson-SemiboldItalic-tlf-ot1.tfm \
tex-Crimson-SemiboldItalic-tlf-t1--base.tfm \
tex-Crimson-SemiboldItalic-tlf-t1.tfm \
tex-Crimson-SemiboldItalic-tlf-t1.vf \
tex-Crimson-SemiboldItalic-tlf-ts1--base.tfm \
tex-Crimson-SemiboldItalic-tlf-ts1.tfm \
tex-Crimson-SemiboldItalic-tlf-ts1.vf \
tex-LY1Crimson-LF.fd \
tex-LY1Crimson-OsF.fd \
tex-LY1Crimson-TLF.fd \
tex-LY1Crimson-TOsF.fd \
tex-OT1Crimson-LF.fd \
tex-OT1Crimson-OsF.fd \
tex-OT1Crimson-TLF.fd \
tex-OT1Crimson-TOsF.fd \
tex-T1Crimson-LF.fd \
tex-T1Crimson-OsF.fd \
tex-T1Crimson-TLF.fd \
tex-T1Crimson-TOsF.fd \
tex-TS1Crimson-LF.fd \
tex-TS1Crimson-OsF.fd \
tex-TS1Crimson-TLF.fd \
tex-TS1Crimson-TOsF.fd \
tex-crimson.map \
tex-crimson.sty \
tex-crm-25ecww.enc \
tex-crm-2bk2kf.enc \
tex-crm-2vwhzr.enc \
tex-crm-36b5o4.enc \
tex-crm-3bejww.enc \
tex-crm-47fe7g.enc \
tex-crm-4df3hz.enc \
tex-crm-4wbvex.enc \
tex-crm-5iushh.enc \
tex-crm-64bq2b.enc \
tex-crm-6cvwjz.enc \
tex-crm-7vbuna.enc \
tex-crm-7wq2t4.enc \
tex-crm-ayvnmf.enc \
tex-crm-b5atsz.enc \
tex-crm-bmqojb.enc \
tex-crm-bsm2ek.enc \
tex-crm-bxc7kq.enc \
tex-crm-cuvbeg.enc \
tex-crm-cxrmm4.enc \
tex-crm-d6nadx.enc \
tex-crm-dcyrwq.enc \
tex-crm-dk7p24.enc \
tex-crm-dl3wd7.enc \
tex-crm-dvqsdk.enc \
tex-crm-efj2rd.enc \
tex-crm-fi53q6.enc \
tex-crm-fvnjct.enc \
tex-crm-g3s64i.enc \
tex-crm-gkepkr.enc \
tex-crm-hbjel3.enc \
tex-crm-hhp6ae.enc \
tex-crm-hnx34u.enc \
tex-crm-hw76il.enc \
tex-crm-ihwzbi.enc \
tex-crm-j3frfl.enc \
tex-crm-j6wyjb.enc \
tex-crm-jdlmpi.enc \
tex-crm-kigpiz.enc \
tex-crm-kyf4gw.enc \
tex-crm-lienqd.enc \
tex-crm-ltoc2m.enc \
tex-crm-lxm2kp.enc \
tex-crm-m6va3v.enc \
tex-crm-n3yyou.enc \
tex-crm-n44da6.enc \
tex-crm-ndtoxh.enc \
tex-crm-odbuza.enc \
tex-crm-plxyu3.enc \
tex-crm-qvosxj.enc \
tex-crm-qx2olb.enc \
tex-crm-r6xrf3.enc \
tex-crm-r76pbb.enc \
tex-crm-rbmipx.enc \
tex-crm-rybvc4.enc \
tex-crm-st6vdm.enc \
tex-crm-tbj74c.enc \
tex-crm-tlhunq.enc \
tex-crm-tswdwf.enc \
tex-crm-uoxeaf.enc \
tex-crm-uoygek.enc \
tex-crm-uwd2sh.enc \
tex-crm-vd5n6o.enc \
tex-crm-vjfyui.enc \
tex-crm-wp5ef6.enc \
tex-crm-z6yvvc.enc \
tex-crm-zjsegd.enc \
tex-crm-zk5yn7.enc \
texlive-crimson"

RDEPENDS:${PN} += "/usr/bin/sh \
coreutils \
ed \
findutils \
grep \
sed \
tex-fontaxes.sty \
tex-fontenc.sty \
tex-fontspec.sty \
tex-ifluatex.sty \
tex-ifxetex.sty \
tex-mweights.sty \
tex-textcomp.sty \
tex-updmap.cfg \
tex-xkeyval.sty \
texlive \
texlive-crimson-fonts \
texlive-filesystem \
texlive-kpathsea \
texlive-kpathsea-bin \
texlive-scripts \
texlive-scripts-bin"

inherit rpm
