SUMMARY = "Zsh completion for bugwarden"
DESCRIPTION = "The zsh completion script for bugwarden, generated by upstream from the \
command line definition."
LICENSE = "(Apache-2.0 | BSL-1.0) & (Apache-2.0 | ISC | MIT) & (Apache-2.0 | MIT) & (MIT | Unlicense) & Apache-2.0 & BSD-3-Clause & ISC & MIT & Unicode-3.0"

PV = "0.6.0"

RPM_NAME = "bugwarden-zsh-completion-0.6.0-1.1.noarch.rpm"
RPM_HASH = "3edfe66822d0c0836d3d74a791005a39c7c8269d05b1452b6ebed2ea54f57dc80a2306c7b7c0470244e2166f7a9acded5c3a76529edfb888e37b971d58f32fb5"
REPO_ARCH = "noarch"

RPROVIDES:${PN} += "bugwarden-zsh-completion"

RDEPENDS:${PN} += "bugwarden"

inherit rpm
