SUMMARY = "Development files for coq"
DESCRIPTION = "This package contains development files for Coq."
LICENSE = "LGPL-2.1-only"

PV = "9.2.0"

RPM_NAME = "rocq-devel-9.2.0-2.1.aarch64.rpm"
RPM_HASH = "e40dd2f42d86fcb85f53e4ece18b1d50d3b70b626154e1a476caefd30d08f63978e68374ffcf4e9002b2264821ca03507289b659c79de6d816562e1b1cb09b97"

RPROVIDES:${PN} += "coq-devel \
ocaml-Abbreviation \
ocaml-Abstract \
ocaml-AcyclicGraph \
ocaml-AllScheme \
ocaml-Arguments-renaming \
ocaml-Assumptions \
ocaml-AsyncTaskQueue \
ocaml-Attributes \
ocaml-Auto \
ocaml-Auto-ind-decl \
ocaml-Autorewrite \
ocaml-Aux-file \
ocaml-Boot \
ocaml-Boot--Env \
ocaml-Boot--Path \
ocaml-Boot--Usage \
ocaml-Boot--Util \
ocaml-Btauto-plugin \
ocaml-Btauto-plugin--G-btauto \
ocaml-Btauto-plugin--Refl-btauto \
ocaml-Btermdn \
ocaml-CArray \
ocaml-CAst \
ocaml-CClosure \
ocaml-CDebug \
ocaml-CEphemeron \
ocaml-CErrors \
ocaml-CLexer \
ocaml-CList \
ocaml-CMap \
ocaml-CObj \
ocaml-CPrimitives \
ocaml-CSet \
ocaml-CSig \
ocaml-CString \
ocaml-CThread \
ocaml-CUnix \
ocaml-CWarnings \
ocaml-Canonical \
ocaml-Cases \
ocaml-Cbn \
ocaml-Cbv \
ocaml-Cc-core-plugin \
ocaml-Cc-core-plugin--Ccalgo \
ocaml-Cc-core-plugin--Ccprojectability \
ocaml-Cc-core-plugin--Ccproof \
ocaml-Cc-core-plugin--Cctac \
ocaml-Cc-plugin \
ocaml-Cc-plugin--G-congruence \
ocaml-Ccompile \
ocaml-Class-tactics \
ocaml-Classes \
ocaml-Clenv \
ocaml-Coercion \
ocaml-Coercionops \
ocaml-Colors \
ocaml-ComArguments \
ocaml-ComAssumption \
ocaml-ComCoercion \
ocaml-ComDefinition \
ocaml-ComExtraDeps \
ocaml-ComFixpoint \
ocaml-ComHints \
ocaml-ComInductive \
ocaml-ComPrimitive \
ocaml-ComRewriteRule \
ocaml-ComSearch \
ocaml-ComTactic \
ocaml-Combinators \
ocaml-Common-compile \
ocaml-Constant-typing \
ocaml-Constr \
ocaml-Constr-matching \
ocaml-Constrexpr \
ocaml-Constrexpr-ops \
ocaml-Constrextern \
ocaml-Constrintern \
ocaml-Context \
ocaml-Contradiction \
ocaml-Control \
ocaml-Conv-oracle \
ocaml-Conversion \
ocaml-Cooking \
ocaml-Coq-byte-config \
ocaml-Coq-checklib \
ocaml-Coq-checklib--Analyze \
ocaml-Coq-checklib--Check-stat \
ocaml-Coq-checklib--CheckFlags \
ocaml-Coq-checklib--CheckInductive \
ocaml-Coq-checklib--CheckLibrary \
ocaml-Coq-checklib--Coqchk-main \
ocaml-Coq-checklib--Mod-checking \
ocaml-Coq-checklib--Safe-checking \
ocaml-Coq-checklib--Validate \
ocaml-Coq-checklib--Values \
ocaml-Coq-config \
ocaml-CoqProject-file \
ocaml-Coqargs \
ocaml-Coqc \
ocaml-Coqcargs \
ocaml-Coqdeplib \
ocaml-Coqdeplib--Args \
ocaml-Coqdeplib--Common \
ocaml-Coqdeplib--Dep-info \
ocaml-Coqdeplib--Error \
ocaml-Coqdeplib--File-util \
ocaml-Coqdeplib--Fl \
ocaml-Coqdeplib--Lexer \
ocaml-Coqdeplib--Loadpath \
ocaml-Coqdeplib--Makefile \
ocaml-Coqdeplib--Rocqdep-main \
ocaml-Coqinit \
ocaml-Coqlib \
ocaml-Coqloadpath \
ocaml-Coqloop \
ocaml-Coqrc \
ocaml-Coqrun \
ocaml-Coqtop \
ocaml-CoqworkmgrApi \
ocaml-DAst \
ocaml-Dag \
ocaml-DebugHook \
ocaml-Debugger-support \
ocaml-Declarations \
ocaml-Declare \
ocaml-DeclareInd \
ocaml-DeclareScheme \
ocaml-DeclareUniv \
ocaml-Declaremods \
ocaml-Declareops \
ocaml-Decls \
ocaml-Deprecation \
ocaml-Derive-plugin \
ocaml-Derive-plugin--Derive \
ocaml-Derive-plugin--G-derive \
ocaml-Detyping \
ocaml-Diff2 \
ocaml-Discharge \
ocaml-Dn \
ocaml-Document \
ocaml-Dumpglob \
ocaml-Dyn \
ocaml-EClause \
ocaml-EConstr \
ocaml-Eauto \
ocaml-Egramml \
ocaml-Egramrocq \
ocaml-Elim \
ocaml-Elimschemes \
ocaml-Entries \
ocaml-Envars \
ocaml-Environ \
ocaml-Eqdecide \
ocaml-Eqschemes \
ocaml-Equality \
ocaml-Esubst \
ocaml-Evaluable \
ocaml-Evar \
ocaml-Evar-kinds \
ocaml-Evar-tactics \
ocaml-Evarconv \
ocaml-Evardefine \
ocaml-Evarnames \
ocaml-Evarsolve \
ocaml-Evarutil \
ocaml-Evd \
ocaml-Exninfo \
ocaml-Extend \
ocaml-Extraction-plugin \
ocaml-Extraction-plugin--Common \
ocaml-Extraction-plugin--Extract-env \
ocaml-Extraction-plugin--Extraction \
ocaml-Extraction-plugin--G-extraction \
ocaml-Extraction-plugin--Haskell \
ocaml-Extraction-plugin--Json \
ocaml-Extraction-plugin--Miniml \
ocaml-Extraction-plugin--Mlutil \
ocaml-Extraction-plugin--Modutil \
ocaml-Extraction-plugin--Ocaml \
ocaml-Extraction-plugin--Scheme \
ocaml-Extraction-plugin--Table \
ocaml-Feedback \
ocaml-Find-subterm \
ocaml-Firstorder-core-plugin \
ocaml-Firstorder-core-plugin--Formula \
ocaml-Firstorder-core-plugin--Ground \
ocaml-Firstorder-core-plugin--Instances \
ocaml-Firstorder-core-plugin--Rules \
ocaml-Firstorder-core-plugin--Sequent \
ocaml-Firstorder-core-plugin--Unify \
ocaml-Firstorder-plugin \
ocaml-Firstorder-plugin--G-ground \
ocaml-FixTactics \
ocaml-Flags \
ocaml-Float64 \
ocaml-Float64-common \
ocaml-Ftactic \
ocaml-Funind-plugin \
ocaml-Funind-plugin--Functional-principles-proofs \
ocaml-Funind-plugin--Functional-principles-types \
ocaml-Funind-plugin--G-indfun \
ocaml-Funind-plugin--Gen-principle \
ocaml-Funind-plugin--Glob-term-to-relation \
ocaml-Funind-plugin--Glob-termops \
ocaml-Funind-plugin--Indfun \
ocaml-Funind-plugin--Indfun-common \
ocaml-Funind-plugin--Invfun \
ocaml-Funind-plugin--Recdef \
ocaml-Future \
ocaml-G-constr \
ocaml-G-obligations \
ocaml-G-prim \
ocaml-G-proofs \
ocaml-G-redexpr \
ocaml-G-toplevel \
ocaml-G-vernac \
ocaml-Genarg \
ocaml-Generalize \
ocaml-Genintern \
ocaml-Geninterp \
ocaml-Genlambda \
ocaml-Genprint \
ocaml-Genredexpr \
ocaml-Gensubst \
ocaml-Gentactic \
ocaml-Glob-ops \
ocaml-Glob-term \
ocaml-GlobEnv \
ocaml-Global \
ocaml-Globnames \
ocaml-Goal-select \
ocaml-Goptions \
ocaml-Gramlib \
ocaml-Gramlib--Gramext \
ocaml-Gramlib--Grammar \
ocaml-Gramlib--LStream \
ocaml-Gramlib--Plexing \
ocaml-Gramlib--Stream \
ocaml-HConstr \
ocaml-HMap \
ocaml-Hashcons \
ocaml-Hashset \
ocaml-Heads \
ocaml-Heap \
ocaml-Himsg \
ocaml-Hints \
ocaml-Hipattern \
ocaml-Hook \
ocaml-IStream \
ocaml-Impargs \
ocaml-Implicit-quantifiers \
ocaml-Ind-tables \
ocaml-IndTyping \
ocaml-Indrec \
ocaml-Indschemes \
ocaml-Indtypes \
ocaml-Induction \
ocaml-Inductive \
ocaml-Inductiveops \
ocaml-InferCumulativity \
ocaml-Instr \
ocaml-Int \
ocaml-Interface \
ocaml-Inv \
ocaml-Keys \
ocaml-Lib \
ocaml-LibBinding \
ocaml-Libnames \
ocaml-Libobject \
ocaml-Library \
ocaml-Library-info \
ocaml-Load \
ocaml-Loadpath \
ocaml-Loc \
ocaml-Locality \
ocaml-Locus \
ocaml-Locusops \
ocaml-Logic \
ocaml-Logic-monad \
ocaml-Ltac-plugin \
ocaml-Ltac-plugin--ComRewrite \
ocaml-Ltac-plugin--Coretactics \
ocaml-Ltac-plugin--Extraargs \
ocaml-Ltac-plugin--Extratactics \
ocaml-Ltac-plugin--G-auto \
ocaml-Ltac-plugin--G-class \
ocaml-Ltac-plugin--G-eqdecide \
ocaml-Ltac-plugin--G-ltac \
ocaml-Ltac-plugin--G-rewrite \
ocaml-Ltac-plugin--G-tactic \
ocaml-Ltac-plugin--Internals \
ocaml-Ltac-plugin--Leminv \
ocaml-Ltac-plugin--Pltac \
ocaml-Ltac-plugin--Pptactic \
ocaml-Ltac-plugin--Profile-ltac-tactics \
ocaml-Ltac-plugin--Tacarg \
ocaml-Ltac-plugin--Taccoerce \
ocaml-Ltac-plugin--Tacentries \
ocaml-Ltac-plugin--Tacenv \
ocaml-Ltac-plugin--Tacexpr \
ocaml-Ltac-plugin--Tacintern \
ocaml-Ltac-plugin--Tacinterp \
ocaml-Ltac-plugin--Tacsubst \
ocaml-Ltac-plugin--Tactic-debug \
ocaml-Ltac-plugin--Tactic-matching \
ocaml-Ltac-pretype \
ocaml-Ltac2-ltac1-plugin \
ocaml-Ltac2-ltac1-plugin--G-ltac2-ltac1 \
ocaml-Ltac2-ltac1-plugin--Tac2core-ltac1 \
ocaml-Ltac2-ltac1-plugin--Tac2quote-ltac1 \
ocaml-Ltac2-ltac1-plugin--Tac2stdlib-ltac1 \
ocaml-Ltac2-plugin \
ocaml-Ltac2-plugin--G-ltac2 \
ocaml-Ltac2-plugin--Tac2bt \
ocaml-Ltac2-plugin--Tac2core \
ocaml-Ltac2-plugin--Tac2dyn \
ocaml-Ltac2-plugin--Tac2entries \
ocaml-Ltac2-plugin--Tac2env \
ocaml-Ltac2-plugin--Tac2expr \
ocaml-Ltac2-plugin--Tac2externals \
ocaml-Ltac2-plugin--Tac2extffi \
ocaml-Ltac2-plugin--Tac2extravals \
ocaml-Ltac2-plugin--Tac2ffi \
ocaml-Ltac2-plugin--Tac2intern \
ocaml-Ltac2-plugin--Tac2interp \
ocaml-Ltac2-plugin--Tac2match \
ocaml-Ltac2-plugin--Tac2print \
ocaml-Ltac2-plugin--Tac2qexpr \
ocaml-Ltac2-plugin--Tac2quote \
ocaml-Ltac2-plugin--Tac2stdlib \
ocaml-Ltac2-plugin--Tac2tactics \
ocaml-Ltac2-plugin--Tac2types \
ocaml-Ltac2-plugin--Tac2typing-env \
ocaml-Ltac2-plugin--Tac2val \
ocaml-Memprof-coq \
ocaml-Memtrace-init \
ocaml-Metasyntax \
ocaml-Micromega-core-plugin \
ocaml-Micromega-core-plugin--Micromega \
ocaml-Micromega-core-plugin--Mutils \
ocaml-Micromega-core-plugin--NumCompat \
ocaml-Micromega-core-plugin--Sos \
ocaml-Micromega-core-plugin--Sos-lib \
ocaml-Micromega-core-plugin--Sos-types \
ocaml-Micromega-plugin \
ocaml-Micromega-plugin--Certificate \
ocaml-Micromega-plugin--Coq-micromega \
ocaml-Micromega-plugin--G-micromega \
ocaml-Micromega-plugin--Itv \
ocaml-Micromega-plugin--Linsolve \
ocaml-Micromega-plugin--Persistent-cache \
ocaml-Micromega-plugin--Polynomial \
ocaml-Micromega-plugin--Simplex \
ocaml-Micromega-plugin--Vect \
ocaml-Miscprint \
ocaml-Mltop \
ocaml-Mod-declarations \
ocaml-Mod-subst \
ocaml-Mod-typing \
ocaml-Modintern \
ocaml-Modops \
ocaml-Monad \
ocaml-Mutex-aux \
ocaml-Namegen \
ocaml-Nameops \
ocaml-Names \
ocaml-Nametab \
ocaml-Nativecode \
ocaml-Nativeconv \
ocaml-Nativelambda \
ocaml-Nativelib \
ocaml-Nativelibrary \
ocaml-Nativenorm \
ocaml-Nativevalues \
ocaml-NeList \
ocaml-NewProfile \
ocaml-Notation \
ocaml-Notation-gram \
ocaml-Notation-ops \
ocaml-Notation-term \
ocaml-Notationextern \
ocaml-Notgram-ops \
ocaml-Nsatz-core-plugin \
ocaml-Nsatz-core-plugin--Ideal \
ocaml-Nsatz-core-plugin--Nsatz \
ocaml-Nsatz-core-plugin--Polynom \
ocaml-Nsatz-core-plugin--Utile \
ocaml-Nsatz-plugin \
ocaml-Nsatz-plugin--G-nsatz \
ocaml-NumTok \
ocaml-Number-string-notation-plugin \
ocaml-Number-string-notation-plugin--G-number-string \
ocaml-Number-string-notation-plugin--Number-string \
ocaml-ObjFile \
ocaml-Opaqueproof \
ocaml-Opaques \
ocaml-Option \
ocaml-OrderedType \
ocaml-PConstraints \
ocaml-Parray \
ocaml-Partac \
ocaml-Partial-subst \
ocaml-Pattern \
ocaml-Patternops \
ocaml-Pcoq \
ocaml-Perf \
ocaml-PolyFlags \
ocaml-PolyMap \
ocaml-Pp \
ocaml-Pp-diff \
ocaml-Ppconstr \
ocaml-Ppextend \
ocaml-Ppred \
ocaml-Pputils \
ocaml-Ppvernac \
ocaml-Predicate \
ocaml-Prettyp \
ocaml-Pretype-errors \
ocaml-Pretyping \
ocaml-PrimNotations \
ocaml-Primred \
ocaml-Printer \
ocaml-PrintingFlags \
ocaml-Printmod \
ocaml-Procq \
ocaml-Profile-tactic \
ocaml-Program \
ocaml-Proof \
ocaml-Proof-bullet \
ocaml-Proof-diffs \
ocaml-Proof-using \
ocaml-ProofBlockDelimiter \
ocaml-Proofview \
ocaml-Proofview-monad \
ocaml-Pstring \
ocaml-Pvernac \
ocaml-QGraph \
ocaml-Quickfix \
ocaml-Range \
ocaml-RecLemmas \
ocaml-Record \
ocaml-RedFlags \
ocaml-Redexpr \
ocaml-Redops \
ocaml-Reduction \
ocaml-Reductionops \
ocaml-Refine \
ocaml-Relevanceops \
ocaml-Reserve \
ocaml-RetrieveObl \
ocaml-Retroknowledge \
ocaml-Retyping \
ocaml-Rewrite \
ocaml-Richpp \
ocaml-Ring-plugin \
ocaml-Ring-plugin--G-ring \
ocaml-Ring-plugin--Ring \
ocaml-Ring-plugin--Ring-ast \
ocaml-Rocqlib \
ocaml-Rocqshim \
ocaml-Rtauto-plugin \
ocaml-Rtauto-plugin--G-rtauto \
ocaml-Rtauto-plugin--Proof-search \
ocaml-Rtauto-plugin--Refl-tauto \
ocaml-Rtree \
ocaml-SList \
ocaml-Safe-typing \
ocaml-Search \
ocaml-Section \
ocaml-Segmenttree \
ocaml-Serialize \
ocaml-Smartlocate \
ocaml-Sorts \
ocaml-Spawn \
ocaml-Spawned \
ocaml-Ssreflect-plugin \
ocaml-Ssreflect-plugin--Ssrast \
ocaml-Ssreflect-plugin--Ssrbwd \
ocaml-Ssreflect-plugin--Ssrcommon \
ocaml-Ssreflect-plugin--Ssrelim \
ocaml-Ssreflect-plugin--Ssrequality \
ocaml-Ssreflect-plugin--Ssrfwd \
ocaml-Ssreflect-plugin--Ssripats \
ocaml-Ssreflect-plugin--Ssrparser \
ocaml-Ssreflect-plugin--Ssrprinters \
ocaml-Ssreflect-plugin--Ssrtacs \
ocaml-Ssreflect-plugin--Ssrtacticals \
ocaml-Ssreflect-plugin--Ssrvernac \
ocaml-Ssreflect-plugin--Ssrview \
ocaml-Ssrmatching-plugin \
ocaml-Ssrmatching-plugin--G-ssrmatching \
ocaml-Ssrmatching-plugin--Ssrmatching \
ocaml-Stateid \
ocaml-Stdarg \
ocaml-Stm \
ocaml-Stmargs \
ocaml-Store \
ocaml-Structures \
ocaml-Subproof \
ocaml-Subtyping \
ocaml-Summary \
ocaml-Synterp \
ocaml-System \
ocaml-TQueue \
ocaml-Tacmach \
ocaml-Tacred \
ocaml-Tactic-option \
ocaml-TacticErrors \
ocaml-Tacticals \
ocaml-Tactics \
ocaml-Tactypes \
ocaml-Tauto-plugin \
ocaml-Tauto-plugin--Tauto \
ocaml-TemplateArity \
ocaml-Term \
ocaml-Terminal \
ocaml-Termops \
ocaml-Tok \
ocaml-Top-printers \
ocaml-Topfmt \
ocaml-TransparentState \
ocaml-Trie \
ocaml-Tuto0-plugin \
ocaml-Tuto0-plugin--G-tuto0 \
ocaml-Tuto0-plugin--Tuto0-main \
ocaml-Tuto1-plugin \
ocaml-Tuto1-plugin--G-tuto1 \
ocaml-Tuto1-plugin--Inspector \
ocaml-Tuto1-plugin--Simple-check \
ocaml-Tuto1-plugin--Simple-declare \
ocaml-Tuto1-plugin--Simple-print \
ocaml-Tuto2-plugin \
ocaml-Tuto2-plugin--Counter \
ocaml-Tuto2-plugin--Custom \
ocaml-Tuto2-plugin--G-tuto2 \
ocaml-Tuto2-plugin--Persistent-counter \
ocaml-Tuto3-plugin \
ocaml-Tuto3-plugin--Construction-game \
ocaml-Tuto3-plugin--G-tuto3 \
ocaml-Tuto3-plugin--Tuto-tactic \
ocaml-Tuto4-plugin \
ocaml-Tuto4-plugin--Myexternals \
ocaml-Type-errors \
ocaml-Typeclasses \
ocaml-Typeclasses-errors \
ocaml-Typeops \
ocaml-Typing \
ocaml-UGraph \
ocaml-UState \
ocaml-UVars \
ocaml-Uint63 \
ocaml-Unicode \
ocaml-Unicodetable \
ocaml-Unification \
ocaml-Unionfind \
ocaml-Univ \
ocaml-UnivFlex \
ocaml-UnivGen \
ocaml-UnivMinim \
ocaml-UnivNames \
ocaml-UnivProblem \
ocaml-UnivSubst \
ocaml-UserWarn \
ocaml-Util \
ocaml-Values \
ocaml-Vars \
ocaml-Vconv \
ocaml-Vcs \
ocaml-Vernac \
ocaml-Vernac-classifier \
ocaml-VernacControl \
ocaml-Vernacentries \
ocaml-Vernacexpr \
ocaml-Vernacextend \
ocaml-Vernacinterp \
ocaml-Vernacoptions \
ocaml-Vernacprop \
ocaml-Vernacstate \
ocaml-Vernactypes \
ocaml-Vm \
ocaml-Vm-printers \
ocaml-Vmbytecodes \
ocaml-Vmbytegen \
ocaml-Vmemitcodes \
ocaml-Vmerrors \
ocaml-Vmlambda \
ocaml-Vmlibrary \
ocaml-Vmopcodes \
ocaml-Vmsymtable \
ocaml-Vmvalues \
ocaml-Vnorm \
ocaml-WorkerLoop \
ocaml-WorkerPool \
ocaml-WriteOnceArray \
ocaml-Xml-datatype \
ocaml-Xml-lexer \
ocaml-Xml-parser \
ocaml-Xml-printer \
ocaml-Xmlprotocol \
ocaml-Zify-plugin \
ocaml-Zify-plugin--G-zify \
ocaml-Zify-plugin--Zify \
ocamlx-Abbreviation \
ocamlx-Abstract \
ocamlx-AcyclicGraph \
ocamlx-AllScheme \
ocamlx-Arguments-renaming \
ocamlx-Assumptions \
ocamlx-AsyncTaskQueue \
ocamlx-Attributes \
ocamlx-Auto \
ocamlx-Auto-ind-decl \
ocamlx-Autorewrite \
ocamlx-Aux-file \
ocamlx-Boot \
ocamlx-Boot--Env \
ocamlx-Boot--Path \
ocamlx-Boot--Usage \
ocamlx-Boot--Util \
ocamlx-Btauto-plugin \
ocamlx-Btauto-plugin--G-btauto \
ocamlx-Btauto-plugin--Refl-btauto \
ocamlx-Btermdn \
ocamlx-CArray \
ocamlx-CAst \
ocamlx-CClosure \
ocamlx-CDebug \
ocamlx-CEphemeron \
ocamlx-CErrors \
ocamlx-CLexer \
ocamlx-CList \
ocamlx-CMap \
ocamlx-CObj \
ocamlx-CPrimitives \
ocamlx-CSet \
ocamlx-CString \
ocamlx-CThread \
ocamlx-CUnix \
ocamlx-CWarnings \
ocamlx-Canonical \
ocamlx-Cases \
ocamlx-Cbn \
ocamlx-Cbv \
ocamlx-Cc-core-plugin \
ocamlx-Cc-core-plugin--Ccalgo \
ocamlx-Cc-core-plugin--Ccprojectability \
ocamlx-Cc-core-plugin--Ccproof \
ocamlx-Cc-core-plugin--Cctac \
ocamlx-Cc-plugin \
ocamlx-Cc-plugin--G-congruence \
ocamlx-Ccompile \
ocamlx-Class-tactics \
ocamlx-Classes \
ocamlx-Clenv \
ocamlx-Coercion \
ocamlx-Coercionops \
ocamlx-Colors \
ocamlx-ComArguments \
ocamlx-ComAssumption \
ocamlx-ComCoercion \
ocamlx-ComDefinition \
ocamlx-ComExtraDeps \
ocamlx-ComFixpoint \
ocamlx-ComHints \
ocamlx-ComInductive \
ocamlx-ComPrimitive \
ocamlx-ComRewriteRule \
ocamlx-ComSearch \
ocamlx-ComTactic \
ocamlx-Combinators \
ocamlx-Common-compile \
ocamlx-Constant-typing \
ocamlx-Constr \
ocamlx-Constr-matching \
ocamlx-Constrexpr-ops \
ocamlx-Constrextern \
ocamlx-Constrintern \
ocamlx-Context \
ocamlx-Contradiction \
ocamlx-Control \
ocamlx-Conv-oracle \
ocamlx-Conversion \
ocamlx-Cooking \
ocamlx-Coq-checklib \
ocamlx-Coq-checklib--Analyze \
ocamlx-Coq-checklib--Check-stat \
ocamlx-Coq-checklib--CheckFlags \
ocamlx-Coq-checklib--CheckInductive \
ocamlx-Coq-checklib--CheckLibrary \
ocamlx-Coq-checklib--Coqchk-main \
ocamlx-Coq-checklib--Mod-checking \
ocamlx-Coq-checklib--Safe-checking \
ocamlx-Coq-checklib--Validate \
ocamlx-Coq-checklib--Values \
ocamlx-Coq-config \
ocamlx-CoqProject-file \
ocamlx-Coqargs \
ocamlx-Coqc \
ocamlx-Coqcargs \
ocamlx-Coqdeplib \
ocamlx-Coqdeplib--Args \
ocamlx-Coqdeplib--Common \
ocamlx-Coqdeplib--Dep-info \
ocamlx-Coqdeplib--Error \
ocamlx-Coqdeplib--File-util \
ocamlx-Coqdeplib--Fl \
ocamlx-Coqdeplib--Lexer \
ocamlx-Coqdeplib--Loadpath \
ocamlx-Coqdeplib--Makefile \
ocamlx-Coqdeplib--Rocqdep-main \
ocamlx-Coqinit \
ocamlx-Coqlib \
ocamlx-Coqloadpath \
ocamlx-Coqloop \
ocamlx-Coqrc \
ocamlx-Coqrun \
ocamlx-Coqtop \
ocamlx-CoqworkmgrApi \
ocamlx-DAst \
ocamlx-Dag \
ocamlx-DebugHook \
ocamlx-Debugger-support \
ocamlx-Declare \
ocamlx-DeclareInd \
ocamlx-DeclareScheme \
ocamlx-DeclareUniv \
ocamlx-Declaremods \
ocamlx-Declareops \
ocamlx-Decls \
ocamlx-Deprecation \
ocamlx-Derive-plugin \
ocamlx-Derive-plugin--Derive \
ocamlx-Derive-plugin--G-derive \
ocamlx-Detyping \
ocamlx-Diff2 \
ocamlx-Discharge \
ocamlx-Dn \
ocamlx-Document \
ocamlx-Dumpglob \
ocamlx-Dyn \
ocamlx-EClause \
ocamlx-EConstr \
ocamlx-Eauto \
ocamlx-Egramml \
ocamlx-Egramrocq \
ocamlx-Elim \
ocamlx-Elimschemes \
ocamlx-Envars \
ocamlx-Environ \
ocamlx-Eqdecide \
ocamlx-Eqschemes \
ocamlx-Equality \
ocamlx-Esubst \
ocamlx-Evaluable \
ocamlx-Evar \
ocamlx-Evar-kinds \
ocamlx-Evar-tactics \
ocamlx-Evarconv \
ocamlx-Evardefine \
ocamlx-Evarnames \
ocamlx-Evarsolve \
ocamlx-Evarutil \
ocamlx-Evd \
ocamlx-Exninfo \
ocamlx-Extend \
ocamlx-Extraction-plugin \
ocamlx-Extraction-plugin--Common \
ocamlx-Extraction-plugin--Extract-env \
ocamlx-Extraction-plugin--Extraction \
ocamlx-Extraction-plugin--G-extraction \
ocamlx-Extraction-plugin--Haskell \
ocamlx-Extraction-plugin--Json \
ocamlx-Extraction-plugin--Miniml \
ocamlx-Extraction-plugin--Mlutil \
ocamlx-Extraction-plugin--Modutil \
ocamlx-Extraction-plugin--Ocaml \
ocamlx-Extraction-plugin--Scheme \
ocamlx-Extraction-plugin--Table \
ocamlx-Feedback \
ocamlx-Find-subterm \
ocamlx-Firstorder-core-plugin \
ocamlx-Firstorder-core-plugin--Formula \
ocamlx-Firstorder-core-plugin--Ground \
ocamlx-Firstorder-core-plugin--Instances \
ocamlx-Firstorder-core-plugin--Rules \
ocamlx-Firstorder-core-plugin--Sequent \
ocamlx-Firstorder-core-plugin--Unify \
ocamlx-Firstorder-plugin \
ocamlx-Firstorder-plugin--G-ground \
ocamlx-FixTactics \
ocamlx-Flags \
ocamlx-Float64 \
ocamlx-Float64-common \
ocamlx-Ftactic \
ocamlx-Funind-plugin \
ocamlx-Funind-plugin--Functional-principles-proofs \
ocamlx-Funind-plugin--Functional-principles-types \
ocamlx-Funind-plugin--G-indfun \
ocamlx-Funind-plugin--Gen-principle \
ocamlx-Funind-plugin--Glob-term-to-relation \
ocamlx-Funind-plugin--Glob-termops \
ocamlx-Funind-plugin--Indfun \
ocamlx-Funind-plugin--Indfun-common \
ocamlx-Funind-plugin--Invfun \
ocamlx-Funind-plugin--Recdef \
ocamlx-Future \
ocamlx-G-constr \
ocamlx-G-obligations \
ocamlx-G-prim \
ocamlx-G-proofs \
ocamlx-G-redexpr \
ocamlx-G-toplevel \
ocamlx-G-vernac \
ocamlx-Genarg \
ocamlx-Generalize \
ocamlx-Genintern \
ocamlx-Geninterp \
ocamlx-Genlambda \
ocamlx-Genprint \
ocamlx-Gensubst \
ocamlx-Gentactic \
ocamlx-Glob-ops \
ocamlx-GlobEnv \
ocamlx-Global \
ocamlx-Globnames \
ocamlx-Goal-select \
ocamlx-Goptions \
ocamlx-Gramlib \
ocamlx-Gramlib--Gramext \
ocamlx-Gramlib--Grammar \
ocamlx-Gramlib--LStream \
ocamlx-Gramlib--Stream \
ocamlx-HConstr \
ocamlx-HMap \
ocamlx-Hashcons \
ocamlx-Hashset \
ocamlx-Heads \
ocamlx-Heap \
ocamlx-Himsg \
ocamlx-Hints \
ocamlx-Hipattern \
ocamlx-Hook \
ocamlx-IStream \
ocamlx-Impargs \
ocamlx-Implicit-quantifiers \
ocamlx-Ind-tables \
ocamlx-IndTyping \
ocamlx-Indrec \
ocamlx-Indschemes \
ocamlx-Indtypes \
ocamlx-Induction \
ocamlx-Inductive \
ocamlx-Inductiveops \
ocamlx-InferCumulativity \
ocamlx-Instr \
ocamlx-Int \
ocamlx-Inv \
ocamlx-Keys \
ocamlx-Lib \
ocamlx-LibBinding \
ocamlx-Libnames \
ocamlx-Libobject \
ocamlx-Library \
ocamlx-Library-info \
ocamlx-Load \
ocamlx-Loadpath \
ocamlx-Loc \
ocamlx-Locality \
ocamlx-Locusops \
ocamlx-Logic \
ocamlx-Logic-monad \
ocamlx-Ltac-plugin \
ocamlx-Ltac-plugin--ComRewrite \
ocamlx-Ltac-plugin--Coretactics \
ocamlx-Ltac-plugin--Extraargs \
ocamlx-Ltac-plugin--Extratactics \
ocamlx-Ltac-plugin--G-auto \
ocamlx-Ltac-plugin--G-class \
ocamlx-Ltac-plugin--G-eqdecide \
ocamlx-Ltac-plugin--G-ltac \
ocamlx-Ltac-plugin--G-rewrite \
ocamlx-Ltac-plugin--G-tactic \
ocamlx-Ltac-plugin--Internals \
ocamlx-Ltac-plugin--Leminv \
ocamlx-Ltac-plugin--Pltac \
ocamlx-Ltac-plugin--Pptactic \
ocamlx-Ltac-plugin--Profile-ltac-tactics \
ocamlx-Ltac-plugin--Tacarg \
ocamlx-Ltac-plugin--Taccoerce \
ocamlx-Ltac-plugin--Tacentries \
ocamlx-Ltac-plugin--Tacenv \
ocamlx-Ltac-plugin--Tacintern \
ocamlx-Ltac-plugin--Tacinterp \
ocamlx-Ltac-plugin--Tacsubst \
ocamlx-Ltac-plugin--Tactic-debug \
ocamlx-Ltac-plugin--Tactic-matching \
ocamlx-Ltac2-ltac1-plugin \
ocamlx-Ltac2-ltac1-plugin--G-ltac2-ltac1 \
ocamlx-Ltac2-ltac1-plugin--Tac2core-ltac1 \
ocamlx-Ltac2-ltac1-plugin--Tac2quote-ltac1 \
ocamlx-Ltac2-ltac1-plugin--Tac2stdlib-ltac1 \
ocamlx-Ltac2-plugin \
ocamlx-Ltac2-plugin--G-ltac2 \
ocamlx-Ltac2-plugin--Tac2bt \
ocamlx-Ltac2-plugin--Tac2core \
ocamlx-Ltac2-plugin--Tac2dyn \
ocamlx-Ltac2-plugin--Tac2entries \
ocamlx-Ltac2-plugin--Tac2env \
ocamlx-Ltac2-plugin--Tac2externals \
ocamlx-Ltac2-plugin--Tac2extffi \
ocamlx-Ltac2-plugin--Tac2extravals \
ocamlx-Ltac2-plugin--Tac2ffi \
ocamlx-Ltac2-plugin--Tac2intern \
ocamlx-Ltac2-plugin--Tac2interp \
ocamlx-Ltac2-plugin--Tac2match \
ocamlx-Ltac2-plugin--Tac2print \
ocamlx-Ltac2-plugin--Tac2quote \
ocamlx-Ltac2-plugin--Tac2stdlib \
ocamlx-Ltac2-plugin--Tac2tactics \
ocamlx-Ltac2-plugin--Tac2typing-env \
ocamlx-Ltac2-plugin--Tac2val \
ocamlx-Memprof-coq \
ocamlx-Memtrace-init \
ocamlx-Metasyntax \
ocamlx-Micromega-core-plugin \
ocamlx-Micromega-core-plugin--Micromega \
ocamlx-Micromega-core-plugin--Mutils \
ocamlx-Micromega-core-plugin--NumCompat \
ocamlx-Micromega-core-plugin--Sos \
ocamlx-Micromega-core-plugin--Sos-lib \
ocamlx-Micromega-core-plugin--Sos-types \
ocamlx-Micromega-plugin \
ocamlx-Micromega-plugin--Certificate \
ocamlx-Micromega-plugin--Coq-micromega \
ocamlx-Micromega-plugin--G-micromega \
ocamlx-Micromega-plugin--Itv \
ocamlx-Micromega-plugin--Linsolve \
ocamlx-Micromega-plugin--Persistent-cache \
ocamlx-Micromega-plugin--Polynomial \
ocamlx-Micromega-plugin--Simplex \
ocamlx-Micromega-plugin--Vect \
ocamlx-Miscprint \
ocamlx-Mltop \
ocamlx-Mod-declarations \
ocamlx-Mod-subst \
ocamlx-Mod-typing \
ocamlx-Modintern \
ocamlx-Modops \
ocamlx-Monad \
ocamlx-Mutex-aux \
ocamlx-Namegen \
ocamlx-Nameops \
ocamlx-Names \
ocamlx-Nametab \
ocamlx-Nativecode \
ocamlx-Nativeconv \
ocamlx-Nativelambda \
ocamlx-Nativelib \
ocamlx-Nativelibrary \
ocamlx-Nativenorm \
ocamlx-Nativevalues \
ocamlx-NeList \
ocamlx-NewProfile \
ocamlx-Notation \
ocamlx-Notation-ops \
ocamlx-Notationextern \
ocamlx-Notgram-ops \
ocamlx-Nsatz-core-plugin \
ocamlx-Nsatz-core-plugin--Ideal \
ocamlx-Nsatz-core-plugin--Nsatz \
ocamlx-Nsatz-core-plugin--Polynom \
ocamlx-Nsatz-core-plugin--Utile \
ocamlx-Nsatz-plugin \
ocamlx-Nsatz-plugin--G-nsatz \
ocamlx-NumTok \
ocamlx-Number-string-notation-plugin \
ocamlx-Number-string-notation-plugin--G-number-string \
ocamlx-Number-string-notation-plugin--Number-string \
ocamlx-ObjFile \
ocamlx-Opaqueproof \
ocamlx-Opaques \
ocamlx-Option \
ocamlx-OrderedType \
ocamlx-PConstraints \
ocamlx-Parray \
ocamlx-Partac \
ocamlx-Partial-subst \
ocamlx-Patternops \
ocamlx-Pcoq \
ocamlx-Perf \
ocamlx-PolyFlags \
ocamlx-PolyMap \
ocamlx-Pp \
ocamlx-Pp-diff \
ocamlx-Ppconstr \
ocamlx-Ppextend \
ocamlx-Ppred \
ocamlx-Pputils \
ocamlx-Ppvernac \
ocamlx-Predicate \
ocamlx-Prettyp \
ocamlx-Pretype-errors \
ocamlx-Pretyping \
ocamlx-PrimNotations \
ocamlx-Primred \
ocamlx-Printer \
ocamlx-PrintingFlags \
ocamlx-Printmod \
ocamlx-Procq \
ocamlx-Profile-tactic \
ocamlx-Program \
ocamlx-Proof \
ocamlx-Proof-bullet \
ocamlx-Proof-diffs \
ocamlx-Proof-using \
ocamlx-ProofBlockDelimiter \
ocamlx-Proofview \
ocamlx-Proofview-monad \
ocamlx-Pstring \
ocamlx-Pvernac \
ocamlx-QGraph \
ocamlx-Quickfix \
ocamlx-Range \
ocamlx-RecLemmas \
ocamlx-Record \
ocamlx-RedFlags \
ocamlx-Redexpr \
ocamlx-Redops \
ocamlx-Reduction \
ocamlx-Reductionops \
ocamlx-Refine \
ocamlx-Relevanceops \
ocamlx-Reserve \
ocamlx-RetrieveObl \
ocamlx-Retroknowledge \
ocamlx-Retyping \
ocamlx-Rewrite \
ocamlx-Richpp \
ocamlx-Ring-plugin \
ocamlx-Ring-plugin--G-ring \
ocamlx-Ring-plugin--Ring \
ocamlx-Ring-plugin--Ring-ast \
ocamlx-Rocqlib \
ocamlx-Rocqshim \
ocamlx-Rtauto-plugin \
ocamlx-Rtauto-plugin--G-rtauto \
ocamlx-Rtauto-plugin--Proof-search \
ocamlx-Rtauto-plugin--Refl-tauto \
ocamlx-Rtree \
ocamlx-SList \
ocamlx-Safe-typing \
ocamlx-Search \
ocamlx-Section \
ocamlx-Segmenttree \
ocamlx-Serialize \
ocamlx-Smartlocate \
ocamlx-Sorts \
ocamlx-Spawn \
ocamlx-Spawned \
ocamlx-Ssreflect-plugin \
ocamlx-Ssreflect-plugin--Ssrbwd \
ocamlx-Ssreflect-plugin--Ssrcommon \
ocamlx-Ssreflect-plugin--Ssrelim \
ocamlx-Ssreflect-plugin--Ssrequality \
ocamlx-Ssreflect-plugin--Ssrfwd \
ocamlx-Ssreflect-plugin--Ssripats \
ocamlx-Ssreflect-plugin--Ssrparser \
ocamlx-Ssreflect-plugin--Ssrprinters \
ocamlx-Ssreflect-plugin--Ssrtacs \
ocamlx-Ssreflect-plugin--Ssrtacticals \
ocamlx-Ssreflect-plugin--Ssrvernac \
ocamlx-Ssreflect-plugin--Ssrview \
ocamlx-Ssrmatching-plugin \
ocamlx-Ssrmatching-plugin--G-ssrmatching \
ocamlx-Ssrmatching-plugin--Ssrmatching \
ocamlx-Stateid \
ocamlx-Stdarg \
ocamlx-Stm \
ocamlx-Stmargs \
ocamlx-Store \
ocamlx-Structures \
ocamlx-Subproof \
ocamlx-Subtyping \
ocamlx-Summary \
ocamlx-Synterp \
ocamlx-System \
ocamlx-TQueue \
ocamlx-Tacmach \
ocamlx-Tacred \
ocamlx-Tactic-option \
ocamlx-TacticErrors \
ocamlx-Tacticals \
ocamlx-Tactics \
ocamlx-Tauto-plugin \
ocamlx-Tauto-plugin--Tauto \
ocamlx-TemplateArity \
ocamlx-Term \
ocamlx-Terminal \
ocamlx-Termops \
ocamlx-Tok \
ocamlx-Top-printers \
ocamlx-Topfmt \
ocamlx-TransparentState \
ocamlx-Trie \
ocamlx-Tuto0-plugin \
ocamlx-Tuto0-plugin--G-tuto0 \
ocamlx-Tuto0-plugin--Tuto0-main \
ocamlx-Tuto1-plugin \
ocamlx-Tuto1-plugin--G-tuto1 \
ocamlx-Tuto1-plugin--Inspector \
ocamlx-Tuto1-plugin--Simple-check \
ocamlx-Tuto1-plugin--Simple-declare \
ocamlx-Tuto1-plugin--Simple-print \
ocamlx-Tuto2-plugin \
ocamlx-Tuto2-plugin--Counter \
ocamlx-Tuto2-plugin--Custom \
ocamlx-Tuto2-plugin--G-tuto2 \
ocamlx-Tuto2-plugin--Persistent-counter \
ocamlx-Tuto3-plugin \
ocamlx-Tuto3-plugin--Construction-game \
ocamlx-Tuto3-plugin--G-tuto3 \
ocamlx-Tuto3-plugin--Tuto-tactic \
ocamlx-Tuto4-plugin \
ocamlx-Tuto4-plugin--Myexternals \
ocamlx-Type-errors \
ocamlx-Typeclasses \
ocamlx-Typeclasses-errors \
ocamlx-Typeops \
ocamlx-Typing \
ocamlx-UGraph \
ocamlx-UState \
ocamlx-UVars \
ocamlx-Uint63 \
ocamlx-Unicode \
ocamlx-Unicodetable \
ocamlx-Unification \
ocamlx-Unionfind \
ocamlx-Univ \
ocamlx-UnivFlex \
ocamlx-UnivGen \
ocamlx-UnivMinim \
ocamlx-UnivNames \
ocamlx-UnivProblem \
ocamlx-UnivSubst \
ocamlx-UserWarn \
ocamlx-Util \
ocamlx-Vars \
ocamlx-Vconv \
ocamlx-Vcs \
ocamlx-Vernac \
ocamlx-Vernac-classifier \
ocamlx-VernacControl \
ocamlx-Vernacentries \
ocamlx-Vernacextend \
ocamlx-Vernacinterp \
ocamlx-Vernacoptions \
ocamlx-Vernacprop \
ocamlx-Vernacstate \
ocamlx-Vernactypes \
ocamlx-Vm \
ocamlx-Vm-printers \
ocamlx-Vmbytecodes \
ocamlx-Vmbytegen \
ocamlx-Vmemitcodes \
ocamlx-Vmerrors \
ocamlx-Vmlambda \
ocamlx-Vmlibrary \
ocamlx-Vmopcodes \
ocamlx-Vmsymtable \
ocamlx-Vmvalues \
ocamlx-Vnorm \
ocamlx-WorkerLoop \
ocamlx-WorkerPool \
ocamlx-WriteOnceArray \
ocamlx-Xml-lexer \
ocamlx-Xml-parser \
ocamlx-Xml-printer \
ocamlx-Xmlprotocol \
ocamlx-Zify-plugin \
ocamlx-Zify-plugin--G-zify \
ocamlx-Zify-plugin--Zify \
rocq-devel"

RDEPENDS:${PN} += "ocaml \
ocaml-Asttypes \
ocaml-Big-int-Z \
ocaml-Build-path-prefix-map \
ocaml-CamlinternalFormat \
ocaml-CamlinternalFormatBasics \
ocaml-CamlinternalLazy \
ocaml-CamlinternalMod \
ocaml-CamlinternalOO \
ocaml-Clflags \
ocaml-Cmi-format \
ocaml-Compenv \
ocaml-Config \
ocaml-Data-types \
ocaml-Dynlink \
ocaml-Env \
ocaml-Findlib \
ocaml-Fl-metascanner \
ocaml-Fl-metatoken \
ocaml-Fl-package-base \
ocaml-Format-doc \
ocaml-Ident \
ocaml-Identifiable \
ocaml-Load-path \
ocaml-Location \
ocaml-Longident \
ocaml-Misc \
ocaml-Oprint \
ocaml-Outcometree \
ocaml-Parsetree \
ocaml-Path \
ocaml-Primitive \
ocaml-Q \
ocaml-Shape \
ocaml-Stdlib \
ocaml-Stdlib--Arg \
ocaml-Stdlib--Array \
ocaml-Stdlib--Bigarray \
ocaml-Stdlib--Bool \
ocaml-Stdlib--Buffer \
ocaml-Stdlib--Bytes \
ocaml-Stdlib--Callback \
ocaml-Stdlib--Char \
ocaml-Stdlib--Complex \
ocaml-Stdlib--Condition \
ocaml-Stdlib--Digest \
ocaml-Stdlib--Domain \
ocaml-Stdlib--Either \
ocaml-Stdlib--Ephemeron \
ocaml-Stdlib--Filename \
ocaml-Stdlib--Float \
ocaml-Stdlib--Format \
ocaml-Stdlib--Fun \
ocaml-Stdlib--Gc \
ocaml-Stdlib--Hashtbl \
ocaml-Stdlib--Int \
ocaml-Stdlib--Int32 \
ocaml-Stdlib--Int64 \
ocaml-Stdlib--Lazy \
ocaml-Stdlib--Lexing \
ocaml-Stdlib--List \
ocaml-Stdlib--Map \
ocaml-Stdlib--Marshal \
ocaml-Stdlib--Mutex \
ocaml-Stdlib--Nativeint \
ocaml-Stdlib--Obj \
ocaml-Stdlib--Printexc \
ocaml-Stdlib--Printf \
ocaml-Stdlib--Queue \
ocaml-Stdlib--Random \
ocaml-Stdlib--Result \
ocaml-Stdlib--Scanf \
ocaml-Stdlib--Seq \
ocaml-Stdlib--Set \
ocaml-Stdlib--Stack \
ocaml-Stdlib--String \
ocaml-Stdlib--Sys \
ocaml-Stdlib--Uchar \
ocaml-Stdlib--Weak \
ocaml-Str \
ocaml-Subst \
ocaml-Thread \
ocaml-Toploop \
ocaml-Type-immediacy \
ocaml-Types \
ocaml-Unit-info \
ocaml-Unix \
ocaml-Warnings \
ocaml-Z \
ocamlx-Big-int-Z \
ocamlx-CamlinternalFormat \
ocamlx-CamlinternalLazy \
ocamlx-CamlinternalMod \
ocamlx-CamlinternalOO \
ocamlx-Dynlink \
ocamlx-Q \
ocamlx-Stdlib \
ocamlx-Stdlib--Array \
ocamlx-Stdlib--Bool \
ocamlx-Stdlib--Buffer \
ocamlx-Stdlib--Bytes \
ocamlx-Stdlib--Callback \
ocamlx-Stdlib--Char \
ocamlx-Stdlib--Condition \
ocamlx-Stdlib--Digest \
ocamlx-Stdlib--Ephemeron \
ocamlx-Stdlib--Filename \
ocamlx-Stdlib--Float \
ocamlx-Stdlib--Format \
ocamlx-Stdlib--Fun \
ocamlx-Stdlib--Gc \
ocamlx-Stdlib--Hashtbl \
ocamlx-Stdlib--Int \
ocamlx-Stdlib--Int32 \
ocamlx-Stdlib--Int64 \
ocamlx-Stdlib--Lazy \
ocamlx-Stdlib--Lexing \
ocamlx-Stdlib--List \
ocamlx-Stdlib--Map \
ocamlx-Stdlib--Marshal \
ocamlx-Stdlib--Mutex \
ocamlx-Stdlib--Obj \
ocamlx-Stdlib--Printexc \
ocamlx-Stdlib--Printf \
ocamlx-Stdlib--Queue \
ocamlx-Stdlib--Random \
ocamlx-Stdlib--Result \
ocamlx-Stdlib--Scanf \
ocamlx-Stdlib--Seq \
ocamlx-Stdlib--Set \
ocamlx-Stdlib--Stack \
ocamlx-Stdlib--String \
ocamlx-Stdlib--Sys \
ocamlx-Stdlib--Uchar \
ocamlx-Stdlib--Weak \
ocamlx-Str \
ocamlx-Thread \
ocamlx-Unix \
ocamlx-Z \
rocq"

inherit rpm
