SUMMARY = "Microsoft Azure Resource Management bundle"
DESCRIPTION = "This is the Microsoft Azure Resource Management bundle. \
 \
Azure Resource Manager (ARM) is the next generation of management APIs that \
replace the old Azure Service Management (ASM). \
 \
This package does not contain any code in itself. It installs a set \
of packages that provide management APIs for the various Azure services. \
 \
All packages in this bundle have been tested with Python 2.7, 3.4, 3.5, 3.6 and 3.7."
LICENSE = "MIT"

PV = "4.0.0"

RPM_NAME = "python314-azure-mgmt-4.0.0-28.4.noarch.rpm"
RPM_HASH = "d32573282ebdae490fb3d6b6f4caa194689a96531266bb862c1185e2e647635aca6a5a6a72ca3035f0e1a3a6d46bc5f14cc5db90a76ba3038745a219c914731e"
REPO_ARCH = "noarch"

RPROVIDES:${PN} += "python3.14dist-azure-mgmt \
python314-azure-mgmt \
python3dist-azure-mgmt"

RDEPENDS:${PN} += "python314-azure-mgmt-advisor \
python314-azure-mgmt-agfood \
python314-azure-mgmt-agrifood \
python314-azure-mgmt-alertsmanagement \
python314-azure-mgmt-apicenter \
python314-azure-mgmt-apimanagement \
python314-azure-mgmt-app \
python314-azure-mgmt-appcomplianceautomation \
python314-azure-mgmt-appconfiguration \
python314-azure-mgmt-appcontainers \
python314-azure-mgmt-applicationinsights \
python314-azure-mgmt-appplatform \
python314-azure-mgmt-arizeaiobservabilityeval \
python314-azure-mgmt-astro \
python314-azure-mgmt-attestation \
python314-azure-mgmt-authorization \
python314-azure-mgmt-automanage \
python314-azure-mgmt-automation \
python314-azure-mgmt-avs \
python314-azure-mgmt-azureadb2c \
python314-azure-mgmt-azurearcdata \
python314-azure-mgmt-azurestack \
python314-azure-mgmt-azurestackhci \
python314-azure-mgmt-azurestackhcivm \
python314-azure-mgmt-baremetalinfrastructure \
python314-azure-mgmt-batch \
python314-azure-mgmt-batchai \
python314-azure-mgmt-billing \
python314-azure-mgmt-billingbenefits \
python314-azure-mgmt-botservice \
python314-azure-mgmt-carbonoptimization \
python314-azure-mgmt-cdn \
python314-azure-mgmt-chaos \
python314-azure-mgmt-cloudhealth \
python314-azure-mgmt-cognitiveservices \
python314-azure-mgmt-commerce \
python314-azure-mgmt-communication \
python314-azure-mgmt-compute \
python314-azure-mgmt-computefleet \
python314-azure-mgmt-computerecommender \
python314-azure-mgmt-computeschedule \
python314-azure-mgmt-confidentialledger \
python314-azure-mgmt-confluent \
python314-azure-mgmt-connectedcache \
python314-azure-mgmt-connectedvmware \
python314-azure-mgmt-consumption \
python314-azure-mgmt-containerinstance \
python314-azure-mgmt-containerorchestratorruntime \
python314-azure-mgmt-containerregistry \
python314-azure-mgmt-containerservice \
python314-azure-mgmt-containerservicefleet \
python314-azure-mgmt-containerservicesafeguards \
python314-azure-mgmt-core \
python314-azure-mgmt-cosmosdb \
python314-azure-mgmt-cosmosdbforpostgresql \
python314-azure-mgmt-costmanagement \
python314-azure-mgmt-customproviders \
python314-azure-mgmt-dashboard \
python314-azure-mgmt-databasewatcher \
python314-azure-mgmt-databox \
python314-azure-mgmt-databoxedge \
python314-azure-mgmt-databricks \
python314-azure-mgmt-datadog \
python314-azure-mgmt-datafactory \
python314-azure-mgmt-datalake-analytics \
python314-azure-mgmt-datalake-nspkg \
python314-azure-mgmt-datalake-store \
python314-azure-mgmt-datamigration \
python314-azure-mgmt-dataprotection \
python314-azure-mgmt-datashare \
python314-azure-mgmt-defendereasm \
python314-azure-mgmt-dependencymap \
python314-azure-mgmt-deploymentmanager \
python314-azure-mgmt-desktopvirtualization \
python314-azure-mgmt-devcenter \
python314-azure-mgmt-devhub \
python314-azure-mgmt-deviceregistry \
python314-azure-mgmt-deviceupdate \
python314-azure-mgmt-devopsinfrastructure \
python314-azure-mgmt-devspaces \
python314-azure-mgmt-devtestlabs \
python314-azure-mgmt-digitaltwins \
python314-azure-mgmt-dns \
python314-azure-mgmt-dnsresolver \
python314-azure-mgmt-durabletask \
python314-azure-mgmt-dynatrace \
python314-azure-mgmt-edgegateway \
python314-azure-mgmt-edgeorder \
python314-azure-mgmt-edgezones \
python314-azure-mgmt-education \
python314-azure-mgmt-elastic \
python314-azure-mgmt-elasticsan \
python314-azure-mgmt-eventgrid \
python314-azure-mgmt-eventhub \
python314-azure-mgmt-extendedlocation \
python314-azure-mgmt-fabric \
python314-azure-mgmt-fluidrelay \
python314-azure-mgmt-frontdoor \
python314-azure-mgmt-graphservices \
python314-azure-mgmt-guestconfig \
python314-azure-mgmt-hanaonazure \
python314-azure-mgmt-hardwaresecuritymodules \
python314-azure-mgmt-hdinsight \
python314-azure-mgmt-hdinsightcontainers \
python314-azure-mgmt-healthcareapis \
python314-azure-mgmt-healthdataaiservices \
python314-azure-mgmt-hybridcompute \
python314-azure-mgmt-hybridconnectivity \
python314-azure-mgmt-hybridcontainerservice \
python314-azure-mgmt-hybridkubernetes \
python314-azure-mgmt-hybridnetwork \
python314-azure-mgmt-imagebuilder \
python314-azure-mgmt-impactreporting \
python314-azure-mgmt-informaticadatamanagement \
python314-azure-mgmt-iotcentral \
python314-azure-mgmt-iotfirmwaredefense \
python314-azure-mgmt-iothub \
python314-azure-mgmt-iothubprovisioningservices \
python314-azure-mgmt-iotoperations \
python314-azure-mgmt-keyvault \
python314-azure-mgmt-kubernetesconfiguration \
python314-azure-mgmt-kubernetesconfiguration-extensions \
python314-azure-mgmt-kubernetesconfiguration-extensiontypes \
python314-azure-mgmt-kubernetesconfiguration-fluxconfigurations \
python314-azure-mgmt-kusto \
python314-azure-mgmt-labservices \
python314-azure-mgmt-lambdatesthyperexecute \
python314-azure-mgmt-largeinstance \
python314-azure-mgmt-loadtesting \
python314-azure-mgmt-loadtestservice \
python314-azure-mgmt-loganalytics \
python314-azure-mgmt-logic \
python314-azure-mgmt-logz \
python314-azure-mgmt-machinelearningcompute \
python314-azure-mgmt-machinelearningservices \
python314-azure-mgmt-maintenance \
python314-azure-mgmt-managedapplications \
python314-azure-mgmt-managednetworkfabric \
python314-azure-mgmt-managedservices \
python314-azure-mgmt-managementgroups \
python314-azure-mgmt-managementpartner \
python314-azure-mgmt-maps \
python314-azure-mgmt-marketplaceordering \
python314-azure-mgmt-media \
python314-azure-mgmt-migrationassessment \
python314-azure-mgmt-migrationdiscoverysap \
python314-azure-mgmt-mixedreality \
python314-azure-mgmt-mobilenetwork \
python314-azure-mgmt-mongodbatlas \
python314-azure-mgmt-monitor \
python314-azure-mgmt-msi \
python314-azure-mgmt-mysqlflexibleservers \
python314-azure-mgmt-neonpostgres \
python314-azure-mgmt-netapp \
python314-azure-mgmt-network \
python314-azure-mgmt-networkanalytics \
python314-azure-mgmt-networkcloud \
python314-azure-mgmt-networkfunction \
python314-azure-mgmt-newrelicobservability \
python314-azure-mgmt-nginx \
python314-azure-mgmt-notificationhubs \
python314-azure-mgmt-nspkg \
python314-azure-mgmt-oep \
python314-azure-mgmt-onlineexperimentation \
python314-azure-mgmt-oracledatabase \
python314-azure-mgmt-orbital \
python314-azure-mgmt-paloaltonetworksngfw \
python314-azure-mgmt-peering \
python314-azure-mgmt-pineconevectordb \
python314-azure-mgmt-planetarycomputer \
python314-azure-mgmt-playwright \
python314-azure-mgmt-playwrighttesting \
python314-azure-mgmt-policyinsights \
python314-azure-mgmt-portal \
python314-azure-mgmt-portalservicescopilot \
python314-azure-mgmt-postgresqlflexibleservers \
python314-azure-mgmt-powerbidedicated \
python314-azure-mgmt-powerbiembedded \
python314-azure-mgmt-privatedns \
python314-azure-mgmt-purestorageblock \
python314-azure-mgmt-purview \
python314-azure-mgmt-quantum \
python314-azure-mgmt-qumulo \
python314-azure-mgmt-quota \
python314-azure-mgmt-rdbms \
python314-azure-mgmt-recoveryservices \
python314-azure-mgmt-recoveryservicesbackup \
python314-azure-mgmt-recoveryservicesdatareplication \
python314-azure-mgmt-recoveryservicessiterecovery \
python314-azure-mgmt-redhatopenshift \
python314-azure-mgmt-redis \
python314-azure-mgmt-redisenterprise \
python314-azure-mgmt-regionmove \
python314-azure-mgmt-relay \
python314-azure-mgmt-reservations \
python314-azure-mgmt-resource \
python314-azure-mgmt-resource-bicep \
python314-azure-mgmt-resourceconnector \
python314-azure-mgmt-resourcegraph \
python314-azure-mgmt-resourcehealth \
python314-azure-mgmt-resourcemover \
python314-azure-mgmt-scheduler \
python314-azure-mgmt-scvmm \
python314-azure-mgmt-search \
python314-azure-mgmt-security \
python314-azure-mgmt-securitydevops \
python314-azure-mgmt-securityinsight \
python314-azure-mgmt-selfhelp \
python314-azure-mgmt-serialconsole \
python314-azure-mgmt-servermanager \
python314-azure-mgmt-servicebus \
python314-azure-mgmt-servicefabric \
python314-azure-mgmt-servicefabricmanagedclusters \
python314-azure-mgmt-servicelinker \
python314-azure-mgmt-servicenetworking \
python314-azure-mgmt-signalr \
python314-azure-mgmt-sitemanager \
python314-azure-mgmt-sphere \
python314-azure-mgmt-springappdiscovery \
python314-azure-mgmt-sql \
python314-azure-mgmt-sqlvirtualmachine \
python314-azure-mgmt-standbypool \
python314-azure-mgmt-storage \
python314-azure-mgmt-storageactions \
python314-azure-mgmt-storagecache \
python314-azure-mgmt-storagediscovery \
python314-azure-mgmt-storageimportexport \
python314-azure-mgmt-storagemover \
python314-azure-mgmt-storagepool \
python314-azure-mgmt-storagesync \
python314-azure-mgmt-streamanalytics \
python314-azure-mgmt-subscription \
python314-azure-mgmt-support \
python314-azure-mgmt-synapse \
python314-azure-mgmt-terraform \
python314-azure-mgmt-testbase \
python314-azure-mgmt-timeseriesinsights \
python314-azure-mgmt-trafficmanager \
python314-azure-mgmt-trustedsigning \
python314-azure-mgmt-videoanalyzer \
python314-azure-mgmt-vmwarecloudsimple \
python314-azure-mgmt-voiceservices \
python314-azure-mgmt-web \
python314-azure-mgmt-webpubsub \
python314-azure-mgmt-weightsandbiases \
python314-azure-mgmt-workloadmonitor \
python314-azure-mgmt-workloadorchestration \
python314-azure-mgmt-workloads \
python314-azure-mgmt-workloadssapvirtualinstance"

inherit rpm
