SUMMARY = "Severed fonts for texlive-junicode"
DESCRIPTION = "The  separated fonts package for texlive-junicode"
LICENSE = "OFL-1.1"

PV = "2026.226.2.218svn77682"

RPM_NAME = "texlive-junicode-fonts-2026.226.2.218svn77682-63.2.noarch.rpm"
RPM_HASH = "5a70fcfac7bf3f90b817e7e5efa7123e84af64aead542d0f73439cf9532ab46b2ef27c428a3e12ba69a4572020b6dbc89dc09b6575a95fe8202201c703257059"
REPO_ARCH = "noarch"

RPROVIDES:${PN} += "config-texlive-junicode-fonts \
ctan-junicode-fonts \
font--lang=aa \
font--lang=af \
font--lang=agr \
font--lang=ak \
font--lang=an \
font--lang=ast \
font--lang=ay \
font--lang=ayc \
font--lang=az-az \
font--lang=bem \
font--lang=ber-dz \
font--lang=bi \
font--lang=bin \
font--lang=bm \
font--lang=br \
font--lang=bs \
font--lang=ca \
font--lang=ch \
font--lang=co \
font--lang=crh \
font--lang=cs \
font--lang=csb \
font--lang=cy \
font--lang=da \
font--lang=de \
font--lang=dsb \
font--lang=ee \
font--lang=el \
font--lang=en \
font--lang=eo \
font--lang=es \
font--lang=et \
font--lang=eu \
font--lang=fat \
font--lang=ff \
font--lang=fi \
font--lang=fil \
font--lang=fj \
font--lang=fo \
font--lang=fr \
font--lang=fur \
font--lang=fy \
font--lang=ga \
font--lang=gd \
font--lang=gl \
font--lang=gn \
font--lang=got \
font--lang=gv \
font--lang=ha \
font--lang=haw \
font--lang=ho \
font--lang=hr \
font--lang=hsb \
font--lang=ht \
font--lang=hu \
font--lang=hz \
font--lang=ia \
font--lang=id \
font--lang=ie \
font--lang=ig \
font--lang=io \
font--lang=is \
font--lang=it \
font--lang=jv \
font--lang=kab \
font--lang=ki \
font--lang=kj \
font--lang=kl \
font--lang=ku-tr \
font--lang=kw \
font--lang=kwm \
font--lang=la \
font--lang=lb \
font--lang=lg \
font--lang=li \
font--lang=lij \
font--lang=ln \
font--lang=lt \
font--lang=lv \
font--lang=mfe \
font--lang=mg \
font--lang=mh \
font--lang=mi \
font--lang=miq \
font--lang=mjw \
font--lang=ms \
font--lang=mt \
font--lang=na \
font--lang=nb \
font--lang=nds \
font--lang=ng \
font--lang=nhn \
font--lang=niu \
font--lang=nl \
font--lang=nn \
font--lang=no \
font--lang=nr \
font--lang=nso \
font--lang=nv \
font--lang=ny \
font--lang=oc \
font--lang=om \
font--lang=pap-an \
font--lang=pap-aw \
font--lang=pl \
font--lang=pt \
font--lang=qu \
font--lang=quz \
font--lang=rif \
font--lang=rm \
font--lang=rn \
font--lang=ro \
font--lang=rw \
font--lang=sc \
font--lang=sco \
font--lang=se \
font--lang=sg \
font--lang=sgs \
font--lang=shs \
font--lang=sk \
font--lang=sl \
font--lang=sm \
font--lang=sma \
font--lang=smj \
font--lang=smn \
font--lang=sms \
font--lang=sn \
font--lang=so \
font--lang=sq \
font--lang=ss \
font--lang=st \
font--lang=su \
font--lang=sv \
font--lang=sw \
font--lang=szl \
font--lang=tk \
font--lang=tl \
font--lang=tn \
font--lang=to \
font--lang=tpi \
font--lang=tr \
font--lang=ts \
font--lang=tw \
font--lang=ty \
font--lang=unm \
font--lang=uz \
font--lang=ve \
font--lang=vi \
font--lang=vo \
font--lang=vot \
font--lang=wa \
font--lang=wae \
font--lang=wen \
font--lang=wo \
font--lang=xh \
font--lang=yap \
font--lang=yo \
font--lang=yuw \
font--lang=za \
font--lang=zu \
font-junicode \
font-junicodecond \
font-junicodecondlight \
font-junicodecondmedium \
font-junicodeexp \
font-junicodeexpmedium \
font-junicodeexpsmbold \
font-junicodelight \
font-junicodemedium \
font-junicodesmbold \
font-junicodesmcond \
font-junicodesmcondlight \
font-junicodesmcondmedium \
font-junicodesmexp \
font-junicodesmexpmedium \
font-junicodesmexpsmbold \
texlive-junicode-fonts"

RDEPENDS:${PN} += "/usr/bin/sh \
aaa-base \
coreutils \
fontconfig \
ghostscript-fonts-std \
perl"

inherit rpm
