SUMMARY = "Visualize ABI changes timeline of a C/C++ software library"
DESCRIPTION = "This tool visualizes an ABI changes timeline of a C/C++ software library. \
 \
It requires input profile of the library in JSON format. It can be created \
manually or automatically generated by the ABI Monitor."
LICENSE = "GPL-2.0-or-later | LGPL-2.1-or-later"

PV = "1.11"

RPM_NAME = "abi-tracker-1.11-2.18.noarch.rpm"
RPM_HASH = "ba32f08783a86ce98767a52b14cfcbdf39d5a75f398a08e3e5aa990b5745a60e8d9c831597110a93be044b31b7b95838438208e5353e247d7881f5bc56776f96"
REPO_ARCH = "noarch"

RPROVIDES:${PN} += "abi-tracker \
perl-In"

RDEPENDS:${PN} += "/usr/bin/perl \
abi-compliance-checker \
abi-dumper \
abi-monitor \
binutils \
perl-base \
pkgdiff \
rfcdiff \
vtable-dumper"

inherit rpm
