SUMMARY = "NVIDIA open kernel module driver for GeForce 16 series (GTX 16xx) and newer"
LICENSE = "GPL-2.0-only & MIT"

PV = "615.71.09_k7.2.5_1"

RPM_NAME = "nvidia-open-driver-G07-signed-cuda-kmp-64kb-615.71.09_k7.2.5_1-2.2.aarch64.rpm"
RPM_HASH = "5e65ccfad2203ec530cad9178eb119f58944ee3dc615e2be239b6e4a4368c8cb3b40204ac27b3f0692beb98fca0116690336172261a545485e6d7d2667478659"

RPROVIDES:${PN} += "kmod-nvidia-drm.ko \
kmod-nvidia-modeset.ko \
kmod-nvidia-uvm.ko \
kmod-nvidia.ko \
ksym-64kb-nvKmsKapiF16ToF32 \
ksym-64kb-nvKmsKapiF32Add \
ksym-64kb-nvKmsKapiF32Div \
ksym-64kb-nvKmsKapiF32Mul \
ksym-64kb-nvKmsKapiF32ToF16 \
ksym-64kb-nvKmsKapiF32ToUI32RMinMag \
ksym-64kb-nvKmsKapiGetFunctionsTable \
ksym-64kb-nvKmsKapiUI32ToF32 \
ksym-64kb-nvUvmInterfaceAccessBitsBufAlloc \
ksym-64kb-nvUvmInterfaceAccessBitsBufFree \
ksym-64kb-nvUvmInterfaceAccessBitsDump \
ksym-64kb-nvUvmInterfaceAddressSpaceCreate \
ksym-64kb-nvUvmInterfaceAddressSpaceDestroy \
ksym-64kb-nvUvmInterfaceBindChannelResources \
ksym-64kb-nvUvmInterfaceChannelAllocate \
ksym-64kb-nvUvmInterfaceChannelDestroy \
ksym-64kb-nvUvmInterfaceCslDecrypt \
ksym-64kb-nvUvmInterfaceCslEncrypt \
ksym-64kb-nvUvmInterfaceCslIncrementIv \
ksym-64kb-nvUvmInterfaceCslInitContext \
ksym-64kb-nvUvmInterfaceCslLogEncryption \
ksym-64kb-nvUvmInterfaceCslQueryMessagePool \
ksym-64kb-nvUvmInterfaceCslRotateIv \
ksym-64kb-nvUvmInterfaceCslRotateKey \
ksym-64kb-nvUvmInterfaceCslSign \
ksym-64kb-nvUvmInterfaceDeRegisterUvmEvents \
ksym-64kb-nvUvmInterfaceDeinitCslContext \
ksym-64kb-nvUvmInterfaceDestroyAccessCntrInfo \
ksym-64kb-nvUvmInterfaceDestroyFaultInfo \
ksym-64kb-nvUvmInterfaceDeviceCreate \
ksym-64kb-nvUvmInterfaceDeviceDestroy \
ksym-64kb-nvUvmInterfaceDisableAccessCntr \
ksym-64kb-nvUvmInterfaceDupAddressSpace \
ksym-64kb-nvUvmInterfaceDupAllocation \
ksym-64kb-nvUvmInterfaceDupMemory \
ksym-64kb-nvUvmInterfaceEnableAccessCntr \
ksym-64kb-nvUvmInterfaceFlushReplayableFaultBuffer \
ksym-64kb-nvUvmInterfaceFreeDupedHandle \
ksym-64kb-nvUvmInterfaceGetChannelResourcePtes \
ksym-64kb-nvUvmInterfaceGetEccInfo \
ksym-64kb-nvUvmInterfaceGetExternalAllocPhysAddrs \
ksym-64kb-nvUvmInterfaceGetExternalAllocPtes \
ksym-64kb-nvUvmInterfaceGetFbInfo \
ksym-64kb-nvUvmInterfaceGetGpuInfo \
ksym-64kb-nvUvmInterfaceGetNonReplayableFaults \
ksym-64kb-nvUvmInterfaceGetNvlinkInfo \
ksym-64kb-nvUvmInterfaceGetP2PCaps \
ksym-64kb-nvUvmInterfaceGetPmaObject \
ksym-64kb-nvUvmInterfaceHasPendingNonReplayableFaults \
ksym-64kb-nvUvmInterfaceInitAccessCntrInfo \
ksym-64kb-nvUvmInterfaceInitFaultInfo \
ksym-64kb-nvUvmInterfaceMemoryAllocFB \
ksym-64kb-nvUvmInterfaceMemoryAllocSys \
ksym-64kb-nvUvmInterfaceMemoryCpuMap \
ksym-64kb-nvUvmInterfaceMemoryCpuUnMap \
ksym-64kb-nvUvmInterfaceMemoryFree \
ksym-64kb-nvUvmInterfaceOwnPageFaultIntr \
ksym-64kb-nvUvmInterfaceP2pObjectCreate \
ksym-64kb-nvUvmInterfaceP2pObjectDestroy \
ksym-64kb-nvUvmInterfacePagingChannelAllocate \
ksym-64kb-nvUvmInterfacePagingChannelDestroy \
ksym-64kb-nvUvmInterfacePagingChannelPushStream \
ksym-64kb-nvUvmInterfacePagingChannelsMap \
ksym-64kb-nvUvmInterfacePagingChannelsUnmap \
ksym-64kb-nvUvmInterfacePmaAllocPages \
ksym-64kb-nvUvmInterfacePmaFreePages \
ksym-64kb-nvUvmInterfacePmaPinPages \
ksym-64kb-nvUvmInterfacePmaRegisterEvictionCallbacks \
ksym-64kb-nvUvmInterfacePmaUnregisterEvictionCallbacks \
ksym-64kb-nvUvmInterfaceQueryCaps \
ksym-64kb-nvUvmInterfaceQueryCopyEnginesCaps \
ksym-64kb-nvUvmInterfaceRegisterGpu \
ksym-64kb-nvUvmInterfaceRegisterUvmEvents \
ksym-64kb-nvUvmInterfaceReleaseChannel \
ksym-64kb-nvUvmInterfaceReportFatalError \
ksym-64kb-nvUvmInterfaceReportNonReplayableFault \
ksym-64kb-nvUvmInterfaceRetainChannel \
ksym-64kb-nvUvmInterfaceServiceDeviceInterruptsRM \
ksym-64kb-nvUvmInterfaceSessionCreate \
ksym-64kb-nvUvmInterfaceSessionDestroy \
ksym-64kb-nvUvmInterfaceSetPageDirectory \
ksym-64kb-nvUvmInterfaceStopChannel \
ksym-64kb-nvUvmInterfaceTogglePrefetchFaults \
ksym-64kb-nvUvmInterfaceTsgAllocate \
ksym-64kb-nvUvmInterfaceTsgDestroy \
ksym-64kb-nvUvmInterfaceUnregisterGpu \
ksym-64kb-nvUvmInterfaceUnsetPageDirectory \
ksym-64kb-nvidia-get-rm-ops \
ksym-64kb-nvidia-p2p-destroy-mapping \
ksym-64kb-nvidia-p2p-dma-map-pages \
ksym-64kb-nvidia-p2p-dma-unmap-pages \
ksym-64kb-nvidia-p2p-free-dma-mapping \
ksym-64kb-nvidia-p2p-free-page-table \
ksym-64kb-nvidia-p2p-get-pages \
ksym-64kb-nvidia-p2p-get-pages-persistent \
ksym-64kb-nvidia-p2p-get-rsync-registers \
ksym-64kb-nvidia-p2p-init-mapping \
ksym-64kb-nvidia-p2p-put-pages \
ksym-64kb-nvidia-p2p-put-pages-persistent \
ksym-64kb-nvidia-p2p-put-rsync-registers \
ksym-64kb-nvidia-p2p-register-rsync-driver \
ksym-64kb-nvidia-p2p-unregister-rsync-driver \
ksym-64kb-nvidia-register-error-cb \
ksym-64kb-nvidia-unregister-error-cb \
nvidia-open-driver-G07 \
nvidia-open-driver-G07-signed-cuda-kmp \
nvidia-open-driver-G07-signed-cuda-kmp-64kb \
nvidia-open-driver-G07-signed-cuda-kmp-64kb-k7.2.5-1 \
nvidia-open-driver-G07-signed-kmp \
nvidia-open-driver-G07-signed-kmp-64kb \
nvidia-open-signed-kmp \
nvidia-open-signed-kmp-cuda"

RDEPENDS:${PN} += "/usr/bin/bash \
/usr/bin/sh \
coreutils \
grep \
group-video \
ksym-64kb----ratelimit \
ksym-64kb---acpi-video-get-backlight-type \
ksym-64kb---alloc-pages-noprof \
ksym-64kb---arch-copy-from-user \
ksym-64kb---arch-copy-to-user \
ksym-64kb---bitmap-and \
ksym-64kb---bitmap-andnot \
ksym-64kb---bitmap-clear \
ksym-64kb---bitmap-complement \
ksym-64kb---bitmap-equal \
ksym-64kb---bitmap-or \
ksym-64kb---bitmap-set \
ksym-64kb---bitmap-shift-right \
ksym-64kb---bitmap-subset \
ksym-64kb---bitmap-weight \
ksym-64kb---check-object-size \
ksym-64kb---clk-get-name \
ksym-64kb---const-udelay \
ksym-64kb---cpu-online-mask \
ksym-64kb---dma-sync-sg-for-cpu \
ksym-64kb---dma-sync-sg-for-device \
ksym-64kb---dma-sync-single-for-cpu \
ksym-64kb---dma-sync-single-for-device \
ksym-64kb---drm-atomic-commit-free \
ksym-64kb---drm-atomic-helper-connector-destroy-state \
ksym-64kb---drm-atomic-helper-connector-duplicate-state \
ksym-64kb---drm-atomic-helper-connector-reset \
ksym-64kb---drm-atomic-helper-crtc-destroy-state \
ksym-64kb---drm-atomic-helper-crtc-duplicate-state \
ksym-64kb---drm-atomic-helper-plane-destroy-state \
ksym-64kb---drm-atomic-helper-plane-duplicate-state \
ksym-64kb---drm-dev-dbg \
ksym-64kb---drm-err \
ksym-64kb---folio-lock \
ksym-64kb---folio-put \
ksym-64kb---fortify-panic \
ksym-64kb---free-pages \
ksym-64kb---init-rwsem \
ksym-64kb---init-swait-queue-head \
ksym-64kb---init-waitqueue-head \
ksym-64kb---ioremap-prot \
ksym-64kb---kmalloc-cache-noprof \
ksym-64kb---kmalloc-large-noprof \
ksym-64kb---kmalloc-noprof \
ksym-64kb---kmem-cache-create-args \
ksym-64kb---kvmalloc-node-noprof \
ksym-64kb---list-add-valid-or-report \
ksym-64kb---list-del-entry-valid-or-report \
ksym-64kb---mmap-lock-do-trace-acquire-returned \
ksym-64kb---mmap-lock-do-trace-released \
ksym-64kb---mmap-lock-do-trace-start-locking \
ksym-64kb---mmdrop \
ksym-64kb---mmu-notifier-register \
ksym-64kb---msecs-to-jiffies \
ksym-64kb---ndelay \
ksym-64kb---node-distance \
ksym-64kb---num-possible-cpus \
ksym-64kb---of-parse-phandle-with-args \
ksym-64kb---pci-register-driver \
ksym-64kb---per-cpu-offset \
ksym-64kb---platform-driver-register \
ksym-64kb---pm-runtime-disable \
ksym-64kb---pm-runtime-use-autosuspend \
ksym-64kb---printk-ratelimit \
ksym-64kb---rcu-read-lock \
ksym-64kb---rcu-read-unlock \
ksym-64kb---refrigerator \
ksym-64kb---release-region \
ksym-64kb---request-region \
ksym-64kb---seq-puts \
ksym-64kb---sg-page-iter-dma-next \
ksym-64kb---sg-page-iter-start \
ksym-64kb---stack-chk-fail \
ksym-64kb---sw-hweight32 \
ksym-64kb---sw-hweight64 \
ksym-64kb---sw-hweight8 \
ksym-64kb---task-pid-nr-ns \
ksym-64kb---trace-set-current-state \
ksym-64kb---trace-trigger-soft-disabled \
ksym-64kb---tracepoint-mmap-lock-acquire-returned \
ksym-64kb---tracepoint-mmap-lock-released \
ksym-64kb---tracepoint-mmap-lock-start-locking \
ksym-64kb---tracepoint-sched-set-state-tp \
ksym-64kb---udelay \
ksym-64kb---usecs-to-jiffies \
ksym-64kb---vma-start-write \
ksym-64kb---vmalloc-noprof \
ksym-64kb---wake-up \
ksym-64kb---warn-printk \
ksym-64kb--ctype \
ksym-64kb--dev-info \
ksym-64kb--find-first-bit \
ksym-64kb--find-first-zero-bit \
ksym-64kb--find-last-bit \
ksym-64kb--find-next-bit \
ksym-64kb--find-next-zero-bit \
ksym-64kb--printk \
ksym-64kb--raw-read-lock \
ksym-64kb--raw-read-unlock \
ksym-64kb--raw-spin-lock \
ksym-64kb--raw-spin-lock-irq \
ksym-64kb--raw-spin-lock-irqsave \
ksym-64kb--raw-spin-unlock \
ksym-64kb--raw-spin-unlock-irq \
ksym-64kb--raw-spin-unlock-irqrestore \
ksym-64kb-acpi-evaluate-integer \
ksym-64kb-acpi-evaluate-object \
ksym-64kb-acpi-gbl-FADT \
ksym-64kb-acpi-get-handle \
ksym-64kb-acpi-get-next-object \
ksym-64kb-acpi-get-table \
ksym-64kb-acpi-install-notify-handler \
ksym-64kb-acpi-put-table \
ksym-64kb-acpi-remove-notify-handler \
ksym-64kb-acpi-video-register-backlight \
ksym-64kb-acpi-walk-namespace \
ksym-64kb-add-memory-driver-managed \
ksym-64kb-address-space-init-once \
ksym-64kb-alloc-chrdev-region \
ksym-64kb-alloc-pages-noprof \
ksym-64kb-alt-cb-patch-nops \
ksym-64kb-aperture-remove-conflicting-devices \
ksym-64kb-aperture-remove-conflicting-pci-devices \
ksym-64kb-arm64-use-ng-mappings \
ksym-64kb-backlight-device-register \
ksym-64kb-backlight-device-unregister \
ksym-64kb-bit-wait \
ksym-64kb-bpf-trace-run3 \
ksym-64kb-cache-line-size \
ksym-64kb-cancel-delayed-work \
ksym-64kb-cancel-delayed-work-sync \
ksym-64kb-capable \
ksym-64kb-cc-platform-has \
ksym-64kb-cdev-add \
ksym-64kb-cdev-del \
ksym-64kb-cdev-init \
ksym-64kb-cgroup-get-from-fd \
ksym-64kb-class-create \
ksym-64kb-class-destroy \
ksym-64kb-clear-page \
ksym-64kb-clk-disable \
ksym-64kb-clk-enable \
ksym-64kb-clk-get-rate \
ksym-64kb-clk-prepare \
ksym-64kb-clk-round-rate \
ksym-64kb-clk-set-rate \
ksym-64kb-clk-unprepare \
ksym-64kb-close-fd \
ksym-64kb-complete \
ksym-64kb-complete-all \
ksym-64kb-completion-done \
ksym-64kb-console-lock \
ksym-64kb-console-unlock \
ksym-64kb-cpu-all-bits \
ksym-64kb-cpufreq-get \
ksym-64kb-crypto-aead-decrypt \
ksym-64kb-crypto-aead-encrypt \
ksym-64kb-crypto-aead-setkey \
ksym-64kb-crypto-alloc-aead \
ksym-64kb-crypto-alloc-shash \
ksym-64kb-crypto-alloc-sig \
ksym-64kb-crypto-destroy-tfm \
ksym-64kb-crypto-ecdh-shared-secret \
ksym-64kb-crypto-req-done \
ksym-64kb-crypto-shash-export \
ksym-64kb-crypto-shash-finup \
ksym-64kb-crypto-shash-import \
ksym-64kb-crypto-shash-init \
ksym-64kb-crypto-shash-setkey \
ksym-64kb-crypto-shash-tfm-digest \
ksym-64kb-delayed-work-timer-fn \
ksym-64kb-desc-to-gpio \
ksym-64kb-dev-driver-string \
ksym-64kb-dev-pm-domain-attach \
ksym-64kb-dev-pm-domain-detach \
ksym-64kb-dev-pm-domain-set \
ksym-64kb-dev-pm-genpd-resume \
ksym-64kb-dev-pm-genpd-suspend \
ksym-64kb-dev-pm-opp-add-dynamic \
ksym-64kb-dev-pm-opp-remove \
ksym-64kb-dev-printk-emit \
ksym-64kb-dev-set-name \
ksym-64kb-devfreq-resume-device \
ksym-64kb-devfreq-suspend-device \
ksym-64kb-device-create \
ksym-64kb-device-destroy \
ksym-64kb-device-property-read-u64-array \
ksym-64kb-device-register \
ksym-64kb-device-unregister \
ksym-64kb-devm-clk-bulk-get-all \
ksym-64kb-devm-clk-get \
ksym-64kb-devm-clk-put \
ksym-64kb-devm-devfreq-add-device \
ksym-64kb-devm-devfreq-remove-device \
ksym-64kb-devm-gpio-request-one \
ksym-64kb-devm-ioremap \
ksym-64kb-devm-kmalloc \
ksym-64kb-devm-memunmap-pages \
ksym-64kb-devm-of-icc-get \
ksym-64kb-disable-irq-nosync \
ksym-64kb-dma-alloc-attrs \
ksym-64kb-dma-buf-attach \
ksym-64kb-dma-buf-detach \
ksym-64kb-dma-buf-dynamic-attach \
ksym-64kb-dma-buf-export \
ksym-64kb-dma-buf-fd \
ksym-64kb-dma-buf-get \
ksym-64kb-dma-buf-invalidate-mappings \
ksym-64kb-dma-buf-map-attachment \
ksym-64kb-dma-buf-put \
ksym-64kb-dma-buf-unmap-attachment \
ksym-64kb-dma-fence-add-callback \
ksym-64kb-dma-fence-context-alloc \
ksym-64kb-dma-fence-default-wait \
ksym-64kb-dma-fence-init \
ksym-64kb-dma-fence-release \
ksym-64kb-dma-fence-signal \
ksym-64kb-dma-free-attrs \
ksym-64kb-dma-iova-free \
ksym-64kb-dma-iova-link \
ksym-64kb-dma-iova-sync \
ksym-64kb-dma-iova-try-alloc \
ksym-64kb-dma-iova-unlink \
ksym-64kb-dma-map-page-attrs \
ksym-64kb-dma-map-resource \
ksym-64kb-dma-map-sg-attrs \
ksym-64kb-dma-map-sgtable \
ksym-64kb-dma-resv-add-fence \
ksym-64kb-dma-resv-reserve-fences \
ksym-64kb-dma-set-coherent-mask \
ksym-64kb-dma-set-mask \
ksym-64kb-dma-unmap-page-attrs \
ksym-64kb-dma-unmap-resource \
ksym-64kb-dma-unmap-sg-attrs \
ksym-64kb-dmem-cgroup-pool-state-put \
ksym-64kb-dmem-cgroup-register-region \
ksym-64kb-dmem-cgroup-state-evict-valuable \
ksym-64kb-dmem-cgroup-try-charge \
ksym-64kb-dmem-cgroup-uncharge \
ksym-64kb-dmem-cgroup-unregister-region \
ksym-64kb-dmem-cgrp-subsys-enabled-key \
ksym-64kb-dmi-get-system-info \
ksym-64kb-down \
ksym-64kb-down-interruptible \
ksym-64kb-down-read \
ksym-64kb-down-read-trylock \
ksym-64kb-down-trylock \
ksym-64kb-down-write \
ksym-64kb-down-write-trylock \
ksym-64kb-downgrade-write \
ksym-64kb-drm-atomic-add-affected-connectors \
ksym-64kb-drm-atomic-add-affected-planes \
ksym-64kb-drm-atomic-commit \
ksym-64kb-drm-atomic-commit-alloc \
ksym-64kb-drm-atomic-commit-default-clear \
ksym-64kb-drm-atomic-commit-default-release \
ksym-64kb-drm-atomic-commit-init \
ksym-64kb-drm-atomic-get-colorop-state \
ksym-64kb-drm-atomic-get-connector-state \
ksym-64kb-drm-atomic-get-crtc-state \
ksym-64kb-drm-atomic-get-plane-state \
ksym-64kb-drm-atomic-helper-check \
ksym-64kb-drm-atomic-helper-crtc-reset \
ksym-64kb-drm-atomic-helper-disable-plane \
ksym-64kb-drm-atomic-helper-page-flip \
ksym-64kb-drm-atomic-helper-plane-reset \
ksym-64kb-drm-atomic-helper-prepare-planes \
ksym-64kb-drm-atomic-helper-set-config \
ksym-64kb-drm-atomic-helper-shutdown \
ksym-64kb-drm-atomic-helper-swap-state \
ksym-64kb-drm-atomic-helper-update-legacy-modeset-state \
ksym-64kb-drm-atomic-helper-update-plane \
ksym-64kb-drm-atomic-set-colorop-for-plane \
ksym-64kb-drm-atomic-set-crtc-for-connector \
ksym-64kb-drm-atomic-set-crtc-for-plane \
ksym-64kb-drm-atomic-set-fb-for-plane \
ksym-64kb-drm-atomic-set-mode-prop-for-crtc \
ksym-64kb-drm-client-setup \
ksym-64kb-drm-colorop-cleanup \
ksym-64kb-drm-colorop-set-next-property \
ksym-64kb-drm-compat-ioctl \
ksym-64kb-drm-connector-atomic-hdr-metadata-equal \
ksym-64kb-drm-connector-attach-colorspace-property \
ksym-64kb-drm-connector-attach-content-protection-property \
ksym-64kb-drm-connector-attach-encoder \
ksym-64kb-drm-connector-attach-hdr-output-metadata-property \
ksym-64kb-drm-connector-attach-vrr-capable-property \
ksym-64kb-drm-connector-cleanup \
ksym-64kb-drm-connector-init \
ksym-64kb-drm-connector-list-iter-begin \
ksym-64kb-drm-connector-list-iter-end \
ksym-64kb-drm-connector-list-iter-next \
ksym-64kb-drm-connector-register \
ksym-64kb-drm-connector-set-vrr-capable-property \
ksym-64kb-drm-connector-unregister \
ksym-64kb-drm-connector-update-edid-property \
ksym-64kb-drm-crtc-cleanup \
ksym-64kb-drm-crtc-enable-color-mgmt \
ksym-64kb-drm-crtc-init-with-planes \
ksym-64kb-drm-crtc-send-vblank-event \
ksym-64kb-drm-crtc-vblank-count \
ksym-64kb-drm-crtc-vblank-get \
ksym-64kb-drm-crtc-vblank-off \
ksym-64kb-drm-crtc-vblank-on \
ksym-64kb-drm-crtc-vblank-put \
ksym-64kb-drm-dev-alloc \
ksym-64kb-drm-dev-put \
ksym-64kb-drm-dev-register \
ksym-64kb-drm-dev-unplug \
ksym-64kb-drm-dev-unregister \
ksym-64kb-drm-edid-override-connector-update \
ksym-64kb-drm-encoder-cleanup \
ksym-64kb-drm-encoder-init \
ksym-64kb-drm-fb-helper-set-suspend-unlocked \
ksym-64kb-drm-fbdev-ttm-driver-fbdev-probe \
ksym-64kb-drm-file-get-master \
ksym-64kb-drm-format-info \
ksym-64kb-drm-framebuffer-cleanup \
ksym-64kb-drm-framebuffer-init \
ksym-64kb-drm-gem-create-mmap-offset \
ksym-64kb-drm-gem-handle-create \
ksym-64kb-drm-gem-mmap-obj \
ksym-64kb-drm-gem-object-free \
ksym-64kb-drm-gem-object-lookup \
ksym-64kb-drm-gem-object-release \
ksym-64kb-drm-gem-prime-export \
ksym-64kb-drm-gem-prime-fd-to-handle \
ksym-64kb-drm-gem-prime-handle-to-fd \
ksym-64kb-drm-gem-prime-import \
ksym-64kb-drm-gem-private-object-init \
ksym-64kb-drm-gem-vm-close \
ksym-64kb-drm-gem-vm-open \
ksym-64kb-drm-handle-vblank \
ksym-64kb-drm-hdcp-update-content-protection \
ksym-64kb-drm-helper-hpd-irq-event \
ksym-64kb-drm-helper-mode-fill-fb-struct \
ksym-64kb-drm-helper-probe-single-connector-modes \
ksym-64kb-drm-ioctl \
ksym-64kb-drm-kms-helper-hotplug-event \
ksym-64kb-drm-kms-helper-poll-disable \
ksym-64kb-drm-kms-helper-poll-enable \
ksym-64kb-drm-kms-helper-poll-fini \
ksym-64kb-drm-kms-helper-poll-init \
ksym-64kb-drm-master-put \
ksym-64kb-drm-mode-config-cleanup \
ksym-64kb-drm-mode-config-reset \
ksym-64kb-drm-mode-create \
ksym-64kb-drm-mode-create-dp-colorspace-property \
ksym-64kb-drm-mode-create-dvi-i-properties \
ksym-64kb-drm-mode-create-hdmi-colorspace-property \
ksym-64kb-drm-mode-crtc-set-gamma-size \
ksym-64kb-drm-mode-object-find \
ksym-64kb-drm-mode-object-put \
ksym-64kb-drm-mode-probed-add \
ksym-64kb-drm-mode-set-name \
ksym-64kb-drm-mode-vrefresh \
ksym-64kb-drm-modeset-acquire-fini \
ksym-64kb-drm-modeset-acquire-init \
ksym-64kb-drm-modeset-backoff \
ksym-64kb-drm-modeset-drop-locks \
ksym-64kb-drm-modeset-lock-all \
ksym-64kb-drm-modeset-lock-all-ctx \
ksym-64kb-drm-modeset-unlock-all \
ksym-64kb-drm-object-attach-property \
ksym-64kb-drm-object-property-set-value \
ksym-64kb-drm-open \
ksym-64kb-drm-plane-cleanup \
ksym-64kb-drm-plane-colorop-ctm-3x4-init \
ksym-64kb-drm-plane-colorop-curve-1d-init \
ksym-64kb-drm-plane-colorop-curve-1d-lut-init \
ksym-64kb-drm-plane-colorop-mult-init \
ksym-64kb-drm-plane-create-alpha-property \
ksym-64kb-drm-plane-create-blend-mode-property \
ksym-64kb-drm-plane-create-color-pipeline-property \
ksym-64kb-drm-plane-create-color-properties \
ksym-64kb-drm-plane-create-rotation-property \
ksym-64kb-drm-poll \
ksym-64kb-drm-prime-gem-destroy \
ksym-64kb-drm-prime-pages-to-sg \
ksym-64kb-drm-property-blob-get \
ksym-64kb-drm-property-blob-put \
ksym-64kb-drm-property-create \
ksym-64kb-drm-property-create-bool \
ksym-64kb-drm-property-create-enum \
ksym-64kb-drm-property-create-range \
ksym-64kb-drm-property-lookup-blob \
ksym-64kb-drm-property-replace-global-blob \
ksym-64kb-drm-read \
ksym-64kb-drm-release \
ksym-64kb-drm-send-event-locked \
ksym-64kb-drm-syncobj-add-point \
ksym-64kb-drm-syncobj-find \
ksym-64kb-drm-syncobj-find-fence \
ksym-64kb-drm-syncobj-free \
ksym-64kb-drm-sysfs-connector-property-event \
ksym-64kb-drm-universal-plane-init \
ksym-64kb-drm-vblank-init \
ksym-64kb-drm-vma-node-is-allowed \
ksym-64kb-drm-vma-offset-lookup-locked \
ksym-64kb-drmm-mode-config-init \
ksym-64kb-dump-stack \
ksym-64kb-dynamic-cond-resched \
ksym-64kb-dynamic-might-resched \
ksym-64kb-dynamic-preempt-schedule \
ksym-64kb-dynamic-preempt-schedule-notrace \
ksym-64kb-ecc-digits-from-bytes \
ksym-64kb-ecc-gen-privkey \
ksym-64kb-ecc-get-curve \
ksym-64kb-ecc-is-pubkey-valid-full \
ksym-64kb-ecc-make-pub-key \
ksym-64kb-efi \
ksym-64kb-enable-irq \
ksym-64kb-fd-install \
ksym-64kb-fget \
ksym-64kb-filp-close \
ksym-64kb-filp-open \
ksym-64kb-find-vma \
ksym-64kb-find-vma-intersection \
ksym-64kb-find-vpid \
ksym-64kb-finish-wait \
ksym-64kb-flush-dcache-page \
ksym-64kb-follow-pfnmap-end \
ksym-64kb-follow-pfnmap-start \
ksym-64kb-fput \
ksym-64kb-free-irq \
ksym-64kb-free-pages \
ksym-64kb-freezer-active \
ksym-64kb-freezing-slow-path \
ksym-64kb-full-name-hash \
ksym-64kb-get-dev-pagemap \
ksym-64kb-get-free-pages-noprof \
ksym-64kb-get-mem-cgroup-from-mm \
ksym-64kb-get-random-bytes \
ksym-64kb-get-task-pid \
ksym-64kb-get-unused-fd-flags \
ksym-64kb-get-user-pages-remote \
ksym-64kb-gpio-device-find-by-fwnode \
ksym-64kb-gpio-device-get-chip \
ksym-64kb-gpio-device-get-desc \
ksym-64kb-gpio-device-put \
ksym-64kb-gpio-free \
ksym-64kb-gpio-request \
ksym-64kb-gpio-to-desc \
ksym-64kb-gpiod-direction-input \
ksym-64kb-gpiod-direction-output-raw \
ksym-64kb-gpiod-get-raw-value \
ksym-64kb-gpiod-set-raw-value \
ksym-64kb-gpiod-to-irq \
ksym-64kb-handle-mm-fault \
ksym-64kb-hmm-range-fault \
ksym-64kb-hrtimer-cancel \
ksym-64kb-hrtimer-setup \
ksym-64kb-hrtimer-start-range-ns \
ksym-64kb-i2c-add-adapter \
ksym-64kb-i2c-del-adapter \
ksym-64kb-icc-set-bw \
ksym-64kb-idr-get-next \
ksym-64kb-init-pid-ns \
ksym-64kb-init-wait-entry \
ksym-64kb-int-active-memcg \
ksym-64kb-iomem-resource \
ksym-64kb-iommu-get-domain-for-dev \
ksym-64kb-iommu-sva-bind-device \
ksym-64kb-iommu-sva-get-pasid \
ksym-64kb-iommu-sva-unbind-device \
ksym-64kb-iounmap \
ksym-64kb-iov-iter-kvec \
ksym-64kb-is-acpi-device-node \
ksym-64kb-is-vmalloc-addr \
ksym-64kb-iterate-fd \
ksym-64kb-jiffies \
ksym-64kb-jiffies-to-timespec64 \
ksym-64kb-kernel-read \
ksym-64kb-kernel-write \
ksym-64kb-key-type-asymmetric \
ksym-64kb-kfree \
ksym-64kb-kfree-sensitive \
ksym-64kb-kimage-voffset \
ksym-64kb-kmalloc-caches \
ksym-64kb-kmem-cache-alloc-noprof \
ksym-64kb-kmem-cache-destroy \
ksym-64kb-kmem-cache-free \
ksym-64kb-krealloc-node-align-noprof \
ksym-64kb-ksize \
ksym-64kb-kthread-create-on-node \
ksym-64kb-kthread-should-stop \
ksym-64kb-kthread-stop \
ksym-64kb-ktime-get-raw-ts64 \
ksym-64kb-ktime-get-real-ts64 \
ksym-64kb-kvasprintf \
ksym-64kb-kvfree \
ksym-64kb-logic-inb \
ksym-64kb-logic-inl \
ksym-64kb-logic-inw \
ksym-64kb-logic-outb \
ksym-64kb-logic-outl \
ksym-64kb-logic-outw \
ksym-64kb-make-device-exclusive \
ksym-64kb-mem-section \
ksym-64kb-memcmp \
ksym-64kb-memcpy \
ksym-64kb-memcpy-fromio \
ksym-64kb-memcpy-toio \
ksym-64kb-memmove \
ksym-64kb-memory-block-size-bytes \
ksym-64kb-memory-failure-queue \
ksym-64kb-memremap-pages \
ksym-64kb-memset \
ksym-64kb-memset-io \
ksym-64kb-memstart-addr \
ksym-64kb-memunmap-pages \
ksym-64kb-migrate-device-finalize \
ksym-64kb-migrate-device-pages \
ksym-64kb-migrate-device-range \
ksym-64kb-migrate-vma-finalize \
ksym-64kb-migrate-vma-pages \
ksym-64kb-migrate-vma-setup \
ksym-64kb-misc-cgrp-subsys-enabled-key \
ksym-64kb-mmput \
ksym-64kb-mmu-interval-notifier-insert \
ksym-64kb-mmu-interval-notifier-remove \
ksym-64kb-mmu-interval-read-begin \
ksym-64kb-mod-node-page-state \
ksym-64kb-mod-timer \
ksym-64kb-module-layout \
ksym-64kb-module-put \
ksym-64kb-mpi-alloc \
ksym-64kb-mpi-free \
ksym-64kb-mpi-powm \
ksym-64kb-mpi-read-buffer \
ksym-64kb-mpi-read-raw-data \
ksym-64kb-msleep \
ksym-64kb-mtree-load \
ksym-64kb-mutex-init-generic \
ksym-64kb-mutex-is-locked \
ksym-64kb-mutex-lock \
ksym-64kb-mutex-lock-interruptible \
ksym-64kb-mutex-trylock \
ksym-64kb-mutex-unlock \
ksym-64kb-node-data \
ksym-64kb-node-states \
ksym-64kb-node-to-cpumask-map \
ksym-64kb-noop-llseek \
ksym-64kb-nr-cpu-ids \
ksym-64kb-nr-node-ids \
ksym-64kb-numa-node \
ksym-64kb-of-address-to-resource \
ksym-64kb-of-device-is-available \
ksym-64kb-of-find-compatible-node \
ksym-64kb-of-find-matching-node-and-match \
ksym-64kb-of-find-node-opts-by-path \
ksym-64kb-of-find-property \
ksym-64kb-of-get-child-by-name \
ksym-64kb-of-get-property \
ksym-64kb-of-node-put \
ksym-64kb-of-parse-phandle-with-args-map \
ksym-64kb-of-prop-next-u32 \
ksym-64kb-of-property-count-elems-of-size \
ksym-64kb-of-property-read-bool \
ksym-64kb-of-property-read-string \
ksym-64kb-of-property-read-u64 \
ksym-64kb-of-property-read-variable-u32-array \
ksym-64kb-offline-and-remove-memory \
ksym-64kb-on-each-cpu-cond-mask \
ksym-64kb-out-of-line-wait-on-bit-lock \
ksym-64kb-panic \
ksym-64kb-param-ops-bool \
ksym-64kb-param-ops-charp \
ksym-64kb-param-ops-int \
ksym-64kb-param-ops-uint \
ksym-64kb-param-ops-ulong \
ksym-64kb-pci-assign-unassigned-bus-resources \
ksym-64kb-pci-ats-supported \
ksym-64kb-pci-bus-type \
ksym-64kb-pci-clear-master \
ksym-64kb-pci-dev-present \
ksym-64kb-pci-dev-put \
ksym-64kb-pci-device-is-present \
ksym-64kb-pci-disable-device \
ksym-64kb-pci-disable-msi \
ksym-64kb-pci-disable-msix \
ksym-64kb-pci-enable-atomic-ops-to-root \
ksym-64kb-pci-enable-device \
ksym-64kb-pci-enable-msi \
ksym-64kb-pci-enable-msix-range \
ksym-64kb-pci-find-capability \
ksym-64kb-pci-find-dvsec-capability \
ksym-64kb-pci-find-host-bridge \
ksym-64kb-pci-get-class \
ksym-64kb-pci-get-domain-bus-and-slot \
ksym-64kb-pci-iomap \
ksym-64kb-pci-iounmap \
ksym-64kb-pci-read-config-byte \
ksym-64kb-pci-read-config-dword \
ksym-64kb-pci-read-config-word \
ksym-64kb-pci-rebar-bytes-to-size \
ksym-64kb-pci-rebar-get-possible-sizes \
ksym-64kb-pci-release-regions \
ksym-64kb-pci-release-resource \
ksym-64kb-pci-request-regions \
ksym-64kb-pci-resize-resource \
ksym-64kb-pci-restore-state \
ksym-64kb-pci-save-state \
ksym-64kb-pci-set-master \
ksym-64kb-pci-stop-and-remove-bus-device \
ksym-64kb-pci-unregister-driver \
ksym-64kb-pci-write-config-byte \
ksym-64kb-pci-write-config-dword \
ksym-64kb-pci-write-config-word \
ksym-64kb-pcibios-resource-to-bus \
ksym-64kb-pcie-capability-read-word \
ksym-64kb-pcie-reset-flr \
ksym-64kb-percpu-counter-add-batch \
ksym-64kb-percpu-counter-batch \
ksym-64kb-perf-trace-buf-alloc \
ksym-64kb-perf-trace-run-bpf-submit \
ksym-64kb-pfn-is-map-memory \
ksym-64kb-pid-task \
ksym-64kb-pid-vnr \
ksym-64kb-pin-user-pages \
ksym-64kb-pin-user-pages-remote \
ksym-64kb-platform-driver-unregister \
ksym-64kb-pm-runtime-allow \
ksym-64kb-pm-runtime-enable \
ksym-64kb-pm-runtime-forbid \
ksym-64kb-pm-runtime-set-autosuspend-delay \
ksym-64kb-pm-vt-switch-required \
ksym-64kb-pm-vt-switch-unregister \
ksym-64kb-prepare-to-wait-event \
ksym-64kb-proc-create-data \
ksym-64kb-proc-mkdir-mode \
ksym-64kb-proc-remove \
ksym-64kb-proc-symlink \
ksym-64kb-prot-ns-shared \
ksym-64kb-public-key-verify-signature \
ksym-64kb-put-pid \
ksym-64kb-put-unused-fd \
ksym-64kb-pxm-to-node \
ksym-64kb-queue-delayed-work-on \
ksym-64kb-queue-work-on \
ksym-64kb-radix-tree-delete \
ksym-64kb-radix-tree-insert \
ksym-64kb-radix-tree-lookup \
ksym-64kb-radix-tree-next-chunk \
ksym-64kb-random-kmalloc-seed \
ksym-64kb-rb-erase \
ksym-64kb-rb-insert-color \
ksym-64kb-refcount-warn-saturate \
ksym-64kb-register-acpi-notifier \
ksym-64kb-register-chrdev-region \
ksym-64kb-register-memory-notifier \
ksym-64kb-register-pm-notifier \
ksym-64kb-release-firmware \
ksym-64kb-remap-pfn-range \
ksym-64kb-remove-proc-entry \
ksym-64kb-request-firmware \
ksym-64kb-request-free-mem-region \
ksym-64kb-request-threaded-irq \
ksym-64kb-rsi-present \
ksym-64kb-schedule \
ksym-64kb-schedule-timeout \
ksym-64kb-seq-lseek \
ksym-64kb-seq-printf \
ksym-64kb-seq-read \
ksym-64kb-seq-read-iter \
ksym-64kb-set-cpus-allowed-ptr \
ksym-64kb-set-memory-decrypted \
ksym-64kb-set-memory-encrypted \
ksym-64kb-set-normalized-timespec64 \
ksym-64kb-set-page-dirty \
ksym-64kb-set-page-dirty-lock \
ksym-64kb-sg-alloc-table \
ksym-64kb-sg-alloc-table-from-pages-segment \
ksym-64kb-sg-free-table \
ksym-64kb-sg-init-table \
ksym-64kb-shmem-file-setup \
ksym-64kb-shrinker-alloc \
ksym-64kb-shrinker-free \
ksym-64kb-shrinker-register \
ksym-64kb-simple-strtoul \
ksym-64kb-single-open \
ksym-64kb-single-release \
ksym-64kb-sized-strscpy \
ksym-64kb-snprintf \
ksym-64kb-sort \
ksym-64kb-sprintf \
ksym-64kb-sscanf \
ksym-64kb-strcasecmp \
ksym-64kb-strchr \
ksym-64kb-strcmp \
ksym-64kb-strcpy \
ksym-64kb-strlcat \
ksym-64kb-strlen \
ksym-64kb-strncat \
ksym-64kb-strncmp \
ksym-64kb-strnlen \
ksym-64kb-strrchr \
ksym-64kb-strsep \
ksym-64kb-strstr \
ksym-64kb-sync-file-create \
ksym-64kb-sync-file-get-fence \
ksym-64kb-sysfb-primary-display \
ksym-64kb-system-percpu-wq \
ksym-64kb-task-active-pid-ns \
ksym-64kb-tegra-bpmp-get \
ksym-64kb-tegra-bpmp-transfer \
ksym-64kb-timer-delete-sync \
ksym-64kb-timer-init-key \
ksym-64kb-trace-event-buffer-commit \
ksym-64kb-trace-event-buffer-reserve \
ksym-64kb-trace-event-printf \
ksym-64kb-trace-event-raw-init \
ksym-64kb-trace-event-reg \
ksym-64kb-trace-handle-return \
ksym-64kb-trace-raw-output-prep \
ksym-64kb-tracepoint-srcu \
ksym-64kb-try-module-get \
ksym-64kb-unlock-page \
ksym-64kb-unmap-mapping-range \
ksym-64kb-unpin-user-page \
ksym-64kb-unregister-acpi-notifier \
ksym-64kb-unregister-chrdev-region \
ksym-64kb-unregister-memory-notifier \
ksym-64kb-unregister-pm-notifier \
ksym-64kb-up \
ksym-64kb-up-read \
ksym-64kb-up-write \
ksym-64kb-update-devfreq \
ksym-64kb-usleep-range-state \
ksym-64kb-validate-usercopy-range \
ksym-64kb-vfree \
ksym-64kb-vfs-fallocate \
ksym-64kb-vga-set-legacy-decoding \
ksym-64kb-vm-get-page-prot \
ksym-64kb-vm-insert-page \
ksym-64kb-vmalloc-noprof \
ksym-64kb-vmalloc-to-page \
ksym-64kb-vmap \
ksym-64kb-vmf-insert-mixed \
ksym-64kb-vmf-insert-pfn \
ksym-64kb-vmf-insert-pfn-prot \
ksym-64kb-vprintk \
ksym-64kb-vsnprintf \
ksym-64kb-vunmap \
ksym-64kb-vzalloc-noprof \
ksym-64kb-wait-for-completion \
ksym-64kb-wait-for-completion-interruptible \
ksym-64kb-wait-for-device-probe \
ksym-64kb-wait-for-random-bytes \
ksym-64kb-wake-up-bit \
ksym-64kb-wake-up-process \
ksym-64kb-ww-mutex-lock \
ksym-64kb-ww-mutex-unlock \
ksym-64kb-zone-device-page-init \
perl-Bootloader \
suse-kernel-rpm-scriptlets \
update-alternatives"

inherit rpm
