SUMMARY = "ANTLR 4 Java runtime"
DESCRIPTION = "This package provides Java runtime library used by parsers generated by \
ANTLR 4."
LICENSE = "BSD-3-Clause"

PV = "4.13.0"

RPM_NAME = "antlr4-java-4.13.0-7.5.noarch.rpm"
RPM_HASH = "3e4553af3c7e5318c27d67c7c633fcab8feebce7c506aba7d1abc783e4f090450f446d1ca9e14c43ac897eeda4efd810a88936c92c2c5fe568ce74270b215bb2"
REPO_ARCH = "noarch"

RPROVIDES:${PN} += "antlr4-java \
antlr4-runtime \
mvn-org.antlr-antlr4-master-pom- \
mvn-org.antlr-antlr4-runtime \
mvn-org.antlr-antlr4-runtime-pom- \
osgi-org.antlr.antlr4-runtime"

RDEPENDS:${PN} += "java-headless \
javapackages-filesystem"

inherit rpm
