SUMMARY = "Embed XMP metadata in PDF with LuaTeX"
DESCRIPTION = "This package enables the inclusion of XMP (eXtensible Metadata \
Platform) data in the pdf output generated by (plain) LuaTeX. \
The use of XMP is required by PDF standards such as PDF/A."
LICENSE = "LPPL-1.0"

PV = "2026.226.2025_1.4svn73816"

RPM_NAME = "texlive-minim-xmp-2026.226.2025_1.4svn73816-61.2.noarch.rpm"
RPM_HASH = "9297d44dcef325e8a719ccfcfc2ab6e22e3ab5195a86b0957d9f6d06c3a80ddbbe6f5e83405345768808ec4e34df46d6e12bf997f2ebd7fb0671fee6bf2a8a09"
REPO_ARCH = "noarch"

RPROVIDES:${PN} += "tex-minim-xmp.tex \
texlive-minim-xmp"

RDEPENDS:${PN} += "/usr/bin/sh \
coreutils \
ed \
findutils \
grep \
sed \
texlive \
texlive-filesystem \
texlive-kpathsea \
texlive-kpathsea-bin \
texlive-scripts \
texlive-scripts-bin"

inherit rpm
