SUMMARY = "Driver for Xbox One and Xbox Series X|S controllers"
DESCRIPTION = "Linux kernel driver for Xbox One and Xbox Series X|S accessories. \
it serves as a modern replacement for xpad, aiming to be \
compatible with Microsoft's Game Input Protocol (GIP)."
LICENSE = "GPL-2.0-or-later"

PV = "0.5.8_k7.2.4_1"

RPM_NAME = "xone-kmp-64kb-0.5.8_k7.2.4_1-1.19.aarch64.rpm"
RPM_HASH = "61c7a191740b2991beaad7fbdbbf3a888a48b54a1185f8398d232754bbaf5d221df5996227725daf5f7160e5047e8782be6cd7f2364cfc578842d48e16c68262"

RPROVIDES:${PN} += "kmod-xone-dongle.ko \
kmod-xone-gip-chatpad.ko \
kmod-xone-gip-gamepad.ko \
kmod-xone-gip-headset.ko \
kmod-xone-gip-madcatz-glam.ko \
kmod-xone-gip-madcatz-strat.ko \
kmod-xone-gip-pdp-jaguar.ko \
kmod-xone-gip.ko \
kmod-xone-wired.ko \
ksym-64kb---gip-register-driver \
ksym-64kb-gip-auth-process-pkt \
ksym-64kb-gip-auth-send-complete \
ksym-64kb-gip-auth-start-handshake \
ksym-64kb-gip-create-adapter \
ksym-64kb-gip-destroy-adapter \
ksym-64kb-gip-disable-audio \
ksym-64kb-gip-enable-audio \
ksym-64kb-gip-has-interface \
ksym-64kb-gip-init-audio-in \
ksym-64kb-gip-init-audio-out \
ksym-64kb-gip-init-battery \
ksym-64kb-gip-init-extra-data \
ksym-64kb-gip-init-input \
ksym-64kb-gip-init-led \
ksym-64kb-gip-power-off-adapter \
ksym-64kb-gip-process-buffer \
ksym-64kb-gip-report-battery \
ksym-64kb-gip-send-audio-samples \
ksym-64kb-gip-send-get-serial-number \
ksym-64kb-gip-send-rumble \
ksym-64kb-gip-set-audio-volume \
ksym-64kb-gip-set-led-mode \
ksym-64kb-gip-set-power-mode \
ksym-64kb-gip-suggest-audio-format \
ksym-64kb-gip-unregister-driver \
multiversion-kernel \
xone-kmp \
xone-kmp-64kb \
xone-kmp-64kb-k7.2.4-1"

RDEPENDS:${PN} += "/usr/bin/sh \
coreutils \
grep \
kernel-64kb \
ksym-64kb---alloc-skb \
ksym-64kb---devm-add-action \
ksym-64kb---dynamic-dev-dbg \
ksym-64kb---dynamic-pr-debug \
ksym-64kb---flush-workqueue \
ksym-64kb---fortify-panic \
ksym-64kb---init-swait-queue-head \
ksym-64kb---init-waitqueue-head \
ksym-64kb---kmalloc-cache-noprof \
ksym-64kb---kmalloc-noprof \
ksym-64kb---netdev-alloc-skb \
ksym-64kb---stack-chk-fail \
ksym-64kb---wake-up \
ksym-64kb--dev-err \
ksym-64kb--dev-info \
ksym-64kb--dev-warn \
ksym-64kb--raw-spin-lock-irqsave \
ksym-64kb--raw-spin-unlock-irqrestore \
ksym-64kb--snd-pcm-stream-lock-irqsave \
ksym-64kb-add-uevent-var \
ksym-64kb-alloc-workqueue-noprof \
ksym-64kb-alt-cb-patch-nops \
ksym-64kb-bus-register \
ksym-64kb-bus-unregister \
ksym-64kb-cancel-delayed-work \
ksym-64kb-cancel-delayed-work-sync \
ksym-64kb-cancel-work-sync \
ksym-64kb-consume-skb \
ksym-64kb-crypto-akcipher-sync-encrypt \
ksym-64kb-crypto-alloc-akcipher \
ksym-64kb-crypto-alloc-kpp \
ksym-64kb-crypto-alloc-shash \
ksym-64kb-crypto-destroy-tfm \
ksym-64kb-crypto-ecdh-encode-key \
ksym-64kb-crypto-ecdh-key-len \
ksym-64kb-crypto-req-done \
ksym-64kb-crypto-shash-digest \
ksym-64kb-crypto-shash-export \
ksym-64kb-crypto-shash-finup \
ksym-64kb-crypto-shash-import \
ksym-64kb-crypto-shash-init \
ksym-64kb-crypto-shash-setkey \
ksym-64kb-crypto-shash-tfm-digest \
ksym-64kb-delayed-work-timer-fn \
ksym-64kb-destroy-workqueue \
ksym-64kb-dev-kfree-skb-any-reason \
ksym-64kb-dev-set-name \
ksym-64kb-device-add-groups \
ksym-64kb-device-register \
ksym-64kb-device-remove-groups \
ksym-64kb-device-unregister \
ksym-64kb-device-wakeup-enable \
ksym-64kb-devm-input-allocate-device \
ksym-64kb-devm-kasprintf \
ksym-64kb-devm-kmalloc \
ksym-64kb-devm-led-classdev-register-ext \
ksym-64kb-devm-power-supply-register \
ksym-64kb-down \
ksym-64kb-down-interruptible \
ksym-64kb-down-trylock \
ksym-64kb-drain-workqueue \
ksym-64kb-driver-register \
ksym-64kb-driver-unregister \
ksym-64kb-dump-stack \
ksym-64kb-dynamic-might-resched \
ksym-64kb-finish-wait \
ksym-64kb-get-random-bytes \
ksym-64kb-hid-add-device \
ksym-64kb-hid-allocate-device \
ksym-64kb-hid-destroy-device \
ksym-64kb-hid-input-report \
ksym-64kb-hid-parse-report \
ksym-64kb-hrtimer-cancel \
ksym-64kb-hrtimer-cb-get-time \
ksym-64kb-hrtimer-forward \
ksym-64kb-hrtimer-setup \
ksym-64kb-hrtimer-start-range-ns \
ksym-64kb-ida-alloc-range \
ksym-64kb-ida-free \
ksym-64kb-ieee80211-get-hdrlen-from-skb \
ksym-64kb-init-wait-entry \
ksym-64kb-input-event \
ksym-64kb-input-ff-create-memless \
ksym-64kb-input-register-device \
ksym-64kb-input-set-abs-params \
ksym-64kb-input-set-capability \
ksym-64kb-jiffies \
ksym-64kb-kfree \
ksym-64kb-kfree-sensitive \
ksym-64kb-kmalloc-caches \
ksym-64kb-kstrtobool \
ksym-64kb-kstrtoint \
ksym-64kb-kstrtou8 \
ksym-64kb-memcpy \
ksym-64kb-memmove \
ksym-64kb-memset \
ksym-64kb-mod-delayed-work-on \
ksym-64kb-mod-timer \
ksym-64kb-module-layout \
ksym-64kb-msleep \
ksym-64kb-mutex-init-generic \
ksym-64kb-mutex-lock \
ksym-64kb-mutex-unlock \
ksym-64kb-param-array-ops \
ksym-64kb-param-ops-byte \
ksym-64kb-param-ops-ushort \
ksym-64kb-power-supply-changed \
ksym-64kb-power-supply-get-drvdata \
ksym-64kb-power-supply-powers \
ksym-64kb-prepare-to-wait-event \
ksym-64kb-print-hex-dump \
ksym-64kb-put-device \
ksym-64kb-queue-delayed-work-on \
ksym-64kb-queue-work-on \
ksym-64kb-random-kmalloc-seed \
ksym-64kb-release-firmware \
ksym-64kb-request-firmware \
ksym-64kb-schedule-timeout \
ksym-64kb-sg-init-one \
ksym-64kb-sized-strscpy \
ksym-64kb-sk-skb-reason-drop \
ksym-64kb-skb-pull \
ksym-64kb-skb-push \
ksym-64kb-skb-put \
ksym-64kb-skb-trim \
ksym-64kb-snd-card-free-on-error \
ksym-64kb-snd-card-register \
ksym-64kb-snd-devm-card-new \
ksym-64kb-snd-pcm-new \
ksym-64kb-snd-pcm-period-elapsed \
ksym-64kb-snd-pcm-set-managed-buffer-all \
ksym-64kb-snd-pcm-set-ops \
ksym-64kb-snd-pcm-stream-unlock-irqrestore \
ksym-64kb-snprintf \
ksym-64kb-sprintf \
ksym-64kb-strcmp \
ksym-64kb-strlen \
ksym-64kb-strnlen \
ksym-64kb-sysfs-emit \
ksym-64kb-system-percpu-wq \
ksym-64kb-system-state \
ksym-64kb-system-wq \
ksym-64kb-timer-delete-sync \
ksym-64kb-timer-init-key \
ksym-64kb-up \
ksym-64kb-usb-alloc-coherent \
ksym-64kb-usb-alloc-urb \
ksym-64kb-usb-altnum-to-altsetting \
ksym-64kb-usb-anchor-urb \
ksym-64kb-usb-bulk-msg \
ksym-64kb-usb-control-msg \
ksym-64kb-usb-deregister \
ksym-64kb-usb-driver-claim-interface \
ksym-64kb-usb-find-common-endpoints \
ksym-64kb-usb-free-coherent \
ksym-64kb-usb-free-urb \
ksym-64kb-usb-get-from-anchor \
ksym-64kb-usb-ifnum-to-if \
ksym-64kb-usb-kill-anchored-urbs \
ksym-64kb-usb-kill-urb \
ksym-64kb-usb-register-driver \
ksym-64kb-usb-reset-device \
ksym-64kb-usb-set-interface \
ksym-64kb-usb-submit-urb \
ksym-64kb-usb-unanchor-urb \
ksym-64kb-usleep-range-state \
ksym-64kb-wait-for-completion \
suse-kernel-rpm-scriptlets"

inherit rpm
