SUMMARY = "OpenAI Codex coding agent for the terminal"
DESCRIPTION = "Codex is OpenAI's coding agent for the terminal. It runs an interactive TUI \
that pairs with the Codex models to read, edit and reason about the code in \
the current working directory, run shell commands inside a sandbox and drive \
common developer workflows from the command line. \
 \
The /usr/bin/codex binary is a multicall executable: the helper programs \
(apply_patch, codex-linux-sandbox, codex-execve-wrapper) are dispatched from \
argv[0], and the remaining tools are subcommands (exec, mcp, \
app-server, execpolicy, sandbox, responses-api-proxy, completion, doctor, \
agents, queue)."
LICENSE = "Apache-2.0 & MIT & Unicode-3.0 & MPL-2.0 & ISC & BSD-3-Clause & Zlib & BSD-2-Clause & CC0-1.0 & CDLA-Permissive-2.0"

PV = "0.154.0"

RPM_NAME = "openai-codex-0.154.0-1.1.aarch64.rpm"
RPM_HASH = "57ba7f1c6c215b7427fb632262966b80b0db9cd6cb516d1fb8676df9d6bb1445775e046eb2610310b056fcda99b1a4d7d77531cd46f7ea69f13d2cc787bbb34e"

RPROVIDES:${PN} += "bundled-aws-lc \
bundled-rust-crate-Inflector \
bundled-rust-crate-actix-codec \
bundled-rust-crate-actix-http \
bundled-rust-crate-actix-router \
bundled-rust-crate-actix-rt \
bundled-rust-crate-actix-server \
bundled-rust-crate-actix-service \
bundled-rust-crate-actix-utils \
bundled-rust-crate-actix-web \
bundled-rust-crate-addr2line \
bundled-rust-crate-adler2 \
bundled-rust-crate-aead \
bundled-rust-crate-aes \
bundled-rust-crate-aes-gcm \
bundled-rust-crate-age \
bundled-rust-crate-age-core \
bundled-rust-crate-ahash \
bundled-rust-crate-aho-corasick \
bundled-rust-crate-allocative \
bundled-rust-crate-allocative-derive \
bundled-rust-crate-allocator-api2 \
bundled-rust-crate-annotate-snippets \
bundled-rust-crate-ansi-to-tui \
bundled-rust-crate-anstream \
bundled-rust-crate-anstyle \
bundled-rust-crate-anstyle-parse \
bundled-rust-crate-anstyle-query \
bundled-rust-crate-anyhow \
bundled-rust-crate-approx \
bundled-rust-crate-arboard \
bundled-rust-crate-arc-swap \
bundled-rust-crate-arrayref \
bundled-rust-crate-arrayvec \
bundled-rust-crate-ascii \
bundled-rust-crate-asn1-rs \
bundled-rust-crate-asn1-rs-derive \
bundled-rust-crate-asn1-rs-impl \
bundled-rust-crate-assert-json-diff \
bundled-rust-crate-async-broadcast \
bundled-rust-crate-async-channel \
bundled-rust-crate-async-executor \
bundled-rust-crate-async-fs \
bundled-rust-crate-async-io \
bundled-rust-crate-async-lock \
bundled-rust-crate-async-stream \
bundled-rust-crate-async-stream-impl \
bundled-rust-crate-async-task \
bundled-rust-crate-async-trait \
bundled-rust-crate-asynk-strim \
bundled-rust-crate-atoi \
bundled-rust-crate-atomic \
bundled-rust-crate-atomic-waker \
bundled-rust-crate-autocfg \
bundled-rust-crate-aws-config \
bundled-rust-crate-aws-credential-types \
bundled-rust-crate-aws-lc-rs \
bundled-rust-crate-aws-lc-sys \
bundled-rust-crate-aws-runtime \
bundled-rust-crate-aws-sdk-signin \
bundled-rust-crate-aws-sdk-sso \
bundled-rust-crate-aws-sdk-ssooidc \
bundled-rust-crate-aws-sdk-sts \
bundled-rust-crate-aws-sigv4 \
bundled-rust-crate-aws-smithy-async \
bundled-rust-crate-aws-smithy-http \
bundled-rust-crate-aws-smithy-http-client \
bundled-rust-crate-aws-smithy-json \
bundled-rust-crate-aws-smithy-observability \
bundled-rust-crate-aws-smithy-query \
bundled-rust-crate-aws-smithy-runtime \
bundled-rust-crate-aws-smithy-runtime-api \
bundled-rust-crate-aws-smithy-runtime-api-macros \
bundled-rust-crate-aws-smithy-types \
bundled-rust-crate-aws-smithy-xml \
bundled-rust-crate-aws-types \
bundled-rust-crate-axum \
bundled-rust-crate-axum-core \
bundled-rust-crate-backtrace \
bundled-rust-crate-base16ct \
bundled-rust-crate-base64 \
bundled-rust-crate-base64-simd \
bundled-rust-crate-base64ct \
bundled-rust-crate-basic-toml \
bundled-rust-crate-bech32 \
bundled-rust-crate-beef \
bundled-rust-crate-bincode \
bundled-rust-crate-bit-set \
bundled-rust-crate-bit-vec \
bundled-rust-crate-bitflags \
bundled-rust-crate-blake2 \
bundled-rust-crate-blake3 \
bundled-rust-crate-block-buffer \
bundled-rust-crate-block-padding \
bundled-rust-crate-blocking \
bundled-rust-crate-bm25 \
bundled-rust-crate-borsh \
bundled-rust-crate-bstr \
bundled-rust-crate-bumpalo \
bundled-rust-crate-by-address \
bundled-rust-crate-bytemuck \
bundled-rust-crate-bytemuck-derive \
bundled-rust-crate-byteorder \
bundled-rust-crate-byteorder-lite \
bundled-rust-crate-bytes \
bundled-rust-crate-bytes-utils \
bundled-rust-crate-bytestring \
bundled-rust-crate-bzip2 \
bundled-rust-crate-bzip2-sys \
bundled-rust-crate-cached \
bundled-rust-crate-cached-proc-macro \
bundled-rust-crate-cached-proc-macro-types \
bundled-rust-crate-castaway \
bundled-rust-crate-cbc \
bundled-rust-crate-cc \
bundled-rust-crate-cfg-aliases \
bundled-rust-crate-cfg-if \
bundled-rust-crate-chacha20 \
bundled-rust-crate-chacha20poly1305 \
bundled-rust-crate-chardetng \
bundled-rust-crate-chrono \
bundled-rust-crate-chunked-transfer \
bundled-rust-crate-cipher \
bundled-rust-crate-clap \
bundled-rust-crate-clap-builder \
bundled-rust-crate-clap-complete \
bundled-rust-crate-clap-derive \
bundled-rust-crate-clap-lex \
bundled-rust-crate-clatter \
bundled-rust-crate-clru \
bundled-rust-crate-cmake \
bundled-rust-crate-cmov \
bundled-rust-crate-cmp-any \
bundled-rust-crate-cobs \
bundled-rust-crate-codex-agent-extension \
bundled-rust-crate-codex-agent-graph-store \
bundled-rust-crate-codex-agent-identity \
bundled-rust-crate-codex-agent-roles \
bundled-rust-crate-codex-analytics \
bundled-rust-crate-codex-ansi-escape \
bundled-rust-crate-codex-api \
bundled-rust-crate-codex-app-server \
bundled-rust-crate-codex-app-server-client \
bundled-rust-crate-codex-app-server-daemon \
bundled-rust-crate-codex-app-server-protocol \
bundled-rust-crate-codex-app-server-protocol-noop-macros \
bundled-rust-crate-codex-app-server-test-client \
bundled-rust-crate-codex-app-server-transport \
bundled-rust-crate-codex-apply-patch \
bundled-rust-crate-codex-arg0 \
bundled-rust-crate-codex-async-utils \
bundled-rust-crate-codex-attachment-store \
bundled-rust-crate-codex-aws-auth \
bundled-rust-crate-codex-backend-client \
bundled-rust-crate-codex-backend-openapi-models \
bundled-rust-crate-codex-build-info \
bundled-rust-crate-codex-chatgpt \
bundled-rust-crate-codex-cli \
bundled-rust-crate-codex-client \
bundled-rust-crate-codex-cloud-config \
bundled-rust-crate-codex-cloud-tasks \
bundled-rust-crate-codex-cloud-tasks-client \
bundled-rust-crate-codex-cloud-tasks-mock-client \
bundled-rust-crate-codex-code-mode \
bundled-rust-crate-codex-code-mode-protocol \
bundled-rust-crate-codex-collaboration-mode-templates \
bundled-rust-crate-codex-config \
bundled-rust-crate-codex-connectors \
bundled-rust-crate-codex-connectors-extension \
bundled-rust-crate-codex-context-fragments \
bundled-rust-crate-codex-core \
bundled-rust-crate-codex-core-plugins \
bundled-rust-crate-codex-diagnostics \
bundled-rust-crate-codex-exec \
bundled-rust-crate-codex-exec-server \
bundled-rust-crate-codex-exec-server-protocol \
bundled-rust-crate-codex-execpolicy \
bundled-rust-crate-codex-experimental-api-macros \
bundled-rust-crate-codex-extension-api \
bundled-rust-crate-codex-extension-items \
bundled-rust-crate-codex-external-agent-migration \
bundled-rust-crate-codex-features \
bundled-rust-crate-codex-feedback \
bundled-rust-crate-codex-file-search \
bundled-rust-crate-codex-file-system \
bundled-rust-crate-codex-file-watcher \
bundled-rust-crate-codex-git-attribution \
bundled-rust-crate-codex-git-utils \
bundled-rust-crate-codex-goal-extension \
bundled-rust-crate-codex-guardian-context \
bundled-rust-crate-codex-guardian-v2 \
bundled-rust-crate-codex-history \
bundled-rust-crate-codex-history-notes-extension \
bundled-rust-crate-codex-home \
bundled-rust-crate-codex-hooks \
bundled-rust-crate-codex-http-client \
bundled-rust-crate-codex-image-generation-extension \
bundled-rust-crate-codex-install-context \
bundled-rust-crate-codex-keyring-store \
bundled-rust-crate-codex-linux-sandbox \
bundled-rust-crate-codex-lmstudio \
bundled-rust-crate-codex-login \
bundled-rust-crate-codex-mcp \
bundled-rust-crate-codex-mcp-extension \
bundled-rust-crate-codex-memories-extension \
bundled-rust-crate-codex-memories-read \
bundled-rust-crate-codex-memories-write \
bundled-rust-crate-codex-message-history \
bundled-rust-crate-codex-model-provider \
bundled-rust-crate-codex-model-provider-info \
bundled-rust-crate-codex-models-manager \
bundled-rust-crate-codex-network-proxy \
bundled-rust-crate-codex-ollama \
bundled-rust-crate-codex-otel \
bundled-rust-crate-codex-plugin \
bundled-rust-crate-codex-process-hardening \
bundled-rust-crate-codex-prompts \
bundled-rust-crate-codex-protocol \
bundled-rust-crate-codex-queue-extension \
bundled-rust-crate-codex-response-debug-context \
bundled-rust-crate-codex-responses-api-proxy \
bundled-rust-crate-codex-rmcp-client \
bundled-rust-crate-codex-rollout \
bundled-rust-crate-codex-rollout-trace \
bundled-rust-crate-codex-sandboxing \
bundled-rust-crate-codex-secrets \
bundled-rust-crate-codex-shell-command \
bundled-rust-crate-codex-shell-escalation \
bundled-rust-crate-codex-skills \
bundled-rust-crate-codex-skills-extension \
bundled-rust-crate-codex-state \
bundled-rust-crate-codex-stdio-to-uds \
bundled-rust-crate-codex-terminal-detection \
bundled-rust-crate-codex-thread-store \
bundled-rust-crate-codex-tools \
bundled-rust-crate-codex-tui \
bundled-rust-crate-codex-uds \
bundled-rust-crate-codex-utils-absolute-path \
bundled-rust-crate-codex-utils-approval-presets \
bundled-rust-crate-codex-utils-audio \
bundled-rust-crate-codex-utils-cache \
bundled-rust-crate-codex-utils-cli \
bundled-rust-crate-codex-utils-elapsed \
bundled-rust-crate-codex-utils-fuzzy-match \
bundled-rust-crate-codex-utils-git-discovery \
bundled-rust-crate-codex-utils-home-dir \
bundled-rust-crate-codex-utils-image \
bundled-rust-crate-codex-utils-json-to-toml \
bundled-rust-crate-codex-utils-oss \
bundled-rust-crate-codex-utils-output-truncation \
bundled-rust-crate-codex-utils-path \
bundled-rust-crate-codex-utils-path-uri \
bundled-rust-crate-codex-utils-plugins \
bundled-rust-crate-codex-utils-pty \
bundled-rust-crate-codex-utils-redacted-string \
bundled-rust-crate-codex-utils-rustls-provider \
bundled-rust-crate-codex-utils-sandbox-summary \
bundled-rust-crate-codex-utils-sleep-inhibitor \
bundled-rust-crate-codex-utils-stream-parser \
bundled-rust-crate-codex-utils-string \
bundled-rust-crate-codex-utils-template \
bundled-rust-crate-codex-web-search-extension \
bundled-rust-crate-codex-websocket-client \
bundled-rust-crate-codex-windows-sandbox \
bundled-rust-crate-codex-workload-identity \
bundled-rust-crate-codex-worktree \
bundled-rust-crate-color-eyre \
bundled-rust-crate-color-quant \
bundled-rust-crate-color-spantrace \
bundled-rust-crate-colorchoice \
bundled-rust-crate-compact-str \
bundled-rust-crate-concurrent-queue \
bundled-rust-crate-const-format \
bundled-rust-crate-const-format-proc-macros \
bundled-rust-crate-const-hex \
bundled-rust-crate-const-oid \
bundled-rust-crate-constant-time-eq \
bundled-rust-crate-convert-case \
bundled-rust-crate-cookie \
bundled-rust-crate-cookie-factory \
bundled-rust-crate-cookie-store \
bundled-rust-crate-cpufeatures \
bundled-rust-crate-crc \
bundled-rust-crate-crc-catalog \
bundled-rust-crate-crc32fast \
bundled-rust-crate-critical-section \
bundled-rust-crate-crossbeam-channel \
bundled-rust-crate-crossbeam-deque \
bundled-rust-crate-crossbeam-epoch \
bundled-rust-crate-crossbeam-queue \
bundled-rust-crate-crossbeam-utils \
bundled-rust-crate-crossterm \
bundled-rust-crate-crypto-bigint \
bundled-rust-crate-crypto-box \
bundled-rust-crate-crypto-common \
bundled-rust-crate-crypto-secretbox \
bundled-rust-crate-csscolorparser \
bundled-rust-crate-csv \
bundled-rust-crate-csv-core \
bundled-rust-crate-ctor \
bundled-rust-crate-ctor-proc-macro \
bundled-rust-crate-ctr \
bundled-rust-crate-ctutils \
bundled-rust-crate-curve25519-dalek \
bundled-rust-crate-darling \
bundled-rust-crate-darling-core \
bundled-rust-crate-darling-macro \
bundled-rust-crate-dashmap \
bundled-rust-crate-data-encoding \
bundled-rust-crate-dbus \
bundled-rust-crate-dbus-secret-service \
bundled-rust-crate-deadpool \
bundled-rust-crate-deadpool-runtime \
bundled-rust-crate-debugid \
bundled-rust-crate-debugserver-types \
bundled-rust-crate-deflate64 \
bundled-rust-crate-deltae \
bundled-rust-crate-der \
bundled-rust-crate-der-parser \
bundled-rust-crate-deranged \
bundled-rust-crate-derivative \
bundled-rust-crate-derive-more \
bundled-rust-crate-derive-more-impl \
bundled-rust-crate-deunicode \
bundled-rust-crate-diffy \
bundled-rust-crate-digest \
bundled-rust-crate-dirs \
bundled-rust-crate-dirs-next \
bundled-rust-crate-dirs-sys \
bundled-rust-crate-dirs-sys-next \
bundled-rust-crate-display-container \
bundled-rust-crate-displaydoc \
bundled-rust-crate-dns-lookup \
bundled-rust-crate-document-features \
bundled-rust-crate-dotenvy \
bundled-rust-crate-downcast-rs \
bundled-rust-crate-dtor \
bundled-rust-crate-dtor-proc-macro \
bundled-rust-crate-dunce \
bundled-rust-crate-dupe \
bundled-rust-crate-dupe-derive \
bundled-rust-crate-dyn-clone \
bundled-rust-crate-ecdsa \
bundled-rust-crate-ed25519 \
bundled-rust-crate-ed25519-dalek \
bundled-rust-crate-either \
bundled-rust-crate-elliptic-curve \
bundled-rust-crate-embedded-io \
bundled-rust-crate-encoding-rs \
bundled-rust-crate-endi \
bundled-rust-crate-endian-type \
bundled-rust-crate-enum-as-inner \
bundled-rust-crate-enumflags2 \
bundled-rust-crate-enumflags2-derive \
bundled-rust-crate-env-filter \
bundled-rust-crate-env-home \
bundled-rust-crate-env-logger \
bundled-rust-crate-equivalent \
bundled-rust-crate-erased-serde \
bundled-rust-crate-errno \
bundled-rust-crate-euclid \
bundled-rust-crate-event-listener \
bundled-rust-crate-event-listener-strategy \
bundled-rust-crate-eventsource-stream \
bundled-rust-crate-extended \
bundled-rust-crate-eyre \
bundled-rust-crate-fancy-regex \
bundled-rust-crate-fast-srgb8 \
bundled-rust-crate-faster-hex \
bundled-rust-crate-fastrand \
bundled-rust-crate-fax \
bundled-rust-crate-fax-derive \
bundled-rust-crate-fd-lock \
bundled-rust-crate-fdeflate \
bundled-rust-crate-ff \
bundled-rust-crate-filedescriptor \
bundled-rust-crate-filetime \
bundled-rust-crate-find-crate \
bundled-rust-crate-find-msvc-tools \
bundled-rust-crate-findshlibs \
bundled-rust-crate-finl-unicode \
bundled-rust-crate-fixed-decimal \
bundled-rust-crate-fixedbitset \
bundled-rust-crate-flate2 \
bundled-rust-crate-fluent \
bundled-rust-crate-fluent-bundle \
bundled-rust-crate-fluent-langneg \
bundled-rust-crate-fluent-syntax \
bundled-rust-crate-fluent-uri \
bundled-rust-crate-flume \
bundled-rust-crate-fnv \
bundled-rust-crate-foldhash \
bundled-rust-crate-foreign-types \
bundled-rust-crate-foreign-types-shared \
bundled-rust-crate-form-urlencoded \
bundled-rust-crate-fs-extra \
bundled-rust-crate-futures \
bundled-rust-crate-futures-channel \
bundled-rust-crate-futures-core \
bundled-rust-crate-futures-executor \
bundled-rust-crate-futures-intrusive \
bundled-rust-crate-futures-io \
bundled-rust-crate-futures-lite \
bundled-rust-crate-futures-macro \
bundled-rust-crate-futures-sink \
bundled-rust-crate-futures-task \
bundled-rust-crate-futures-util \
bundled-rust-crate-fxhash \
bundled-rust-crate-generic-array \
bundled-rust-crate-gethostname \
bundled-rust-crate-getrandom \
bundled-rust-crate-ghash \
bundled-rust-crate-gif \
bundled-rust-crate-gimli \
bundled-rust-crate-gix \
bundled-rust-crate-gix-actor \
bundled-rust-crate-gix-archive \
bundled-rust-crate-gix-attributes \
bundled-rust-crate-gix-bitmap \
bundled-rust-crate-gix-blame \
bundled-rust-crate-gix-chunk \
bundled-rust-crate-gix-command \
bundled-rust-crate-gix-commitgraph \
bundled-rust-crate-gix-config \
bundled-rust-crate-gix-config-value \
bundled-rust-crate-gix-date \
bundled-rust-crate-gix-diff \
bundled-rust-crate-gix-dir \
bundled-rust-crate-gix-discover \
bundled-rust-crate-gix-error \
bundled-rust-crate-gix-features \
bundled-rust-crate-gix-filter \
bundled-rust-crate-gix-fs \
bundled-rust-crate-gix-glob \
bundled-rust-crate-gix-hash \
bundled-rust-crate-gix-hashtable \
bundled-rust-crate-gix-ignore \
bundled-rust-crate-gix-index \
bundled-rust-crate-gix-lock \
bundled-rust-crate-gix-merge \
bundled-rust-crate-gix-negotiate \
bundled-rust-crate-gix-object \
bundled-rust-crate-gix-odb \
bundled-rust-crate-gix-pack \
bundled-rust-crate-gix-packetline \
bundled-rust-crate-gix-path \
bundled-rust-crate-gix-pathspec \
bundled-rust-crate-gix-protocol \
bundled-rust-crate-gix-quote \
bundled-rust-crate-gix-ref \
bundled-rust-crate-gix-refspec \
bundled-rust-crate-gix-revision \
bundled-rust-crate-gix-revwalk \
bundled-rust-crate-gix-sec \
bundled-rust-crate-gix-shallow \
bundled-rust-crate-gix-status \
bundled-rust-crate-gix-submodule \
bundled-rust-crate-gix-tempfile \
bundled-rust-crate-gix-trace \
bundled-rust-crate-gix-transport \
bundled-rust-crate-gix-traverse \
bundled-rust-crate-gix-url \
bundled-rust-crate-gix-utils \
bundled-rust-crate-gix-validate \
bundled-rust-crate-gix-worktree \
bundled-rust-crate-gix-worktree-state \
bundled-rust-crate-gix-worktree-stream \
bundled-rust-crate-glob \
bundled-rust-crate-globset \
bundled-rust-crate-group \
bundled-rust-crate-h2 \
bundled-rust-crate-half \
bundled-rust-crate-hash32 \
bundled-rust-crate-hashbrown \
bundled-rust-crate-hashlink \
bundled-rust-crate-headers \
bundled-rust-crate-headers-core \
bundled-rust-crate-heapless \
bundled-rust-crate-heck \
bundled-rust-crate-hex \
bundled-rust-crate-hickory-proto \
bundled-rust-crate-hickory-resolver \
bundled-rust-crate-hkdf \
bundled-rust-crate-hmac \
bundled-rust-crate-home \
bundled-rust-crate-hostname \
bundled-rust-crate-http \
bundled-rust-crate-http-body \
bundled-rust-crate-http-body-util \
bundled-rust-crate-http-range-header \
bundled-rust-crate-httparse \
bundled-rust-crate-httpdate \
bundled-rust-crate-hybrid-array \
bundled-rust-crate-hyper \
bundled-rust-crate-hyper-rustls \
bundled-rust-crate-hyper-timeout \
bundled-rust-crate-hyper-tls \
bundled-rust-crate-hyper-util \
bundled-rust-crate-i18n-config \
bundled-rust-crate-i18n-embed \
bundled-rust-crate-i18n-embed-fl \
bundled-rust-crate-i18n-embed-impl \
bundled-rust-crate-iana-time-zone \
bundled-rust-crate-icu-collections \
bundled-rust-crate-icu-decimal \
bundled-rust-crate-icu-decimal-data \
bundled-rust-crate-icu-locale \
bundled-rust-crate-icu-locale-core \
bundled-rust-crate-icu-locale-data \
bundled-rust-crate-icu-normalizer \
bundled-rust-crate-icu-normalizer-data \
bundled-rust-crate-icu-plurals \
bundled-rust-crate-icu-plurals-data \
bundled-rust-crate-icu-properties \
bundled-rust-crate-icu-properties-data \
bundled-rust-crate-icu-provider \
bundled-rust-crate-ident-case \
bundled-rust-crate-idna \
bundled-rust-crate-idna-adapter \
bundled-rust-crate-ignore \
bundled-rust-crate-image \
bundled-rust-crate-image-webp \
bundled-rust-crate-imara-diff \
bundled-rust-crate-impl-more \
bundled-rust-crate-include-dir \
bundled-rust-crate-include-dir-macros \
bundled-rust-crate-indenter \
bundled-rust-crate-indexmap \
bundled-rust-crate-indoc \
bundled-rust-crate-inotify \
bundled-rust-crate-inotify-sys \
bundled-rust-crate-inout \
bundled-rust-crate-instability \
bundled-rust-crate-intl-memoizer \
bundled-rust-crate-intl-pluralrules \
bundled-rust-crate-inventory \
bundled-rust-crate-io-close \
bundled-rust-crate-io-tee \
bundled-rust-crate-ipnet \
bundled-rust-crate-iri-string \
bundled-rust-crate-is-ci \
bundled-rust-crate-is-terminal \
bundled-rust-crate-is-terminal-polyfill \
bundled-rust-crate-itertools \
bundled-rust-crate-itoa \
bundled-rust-crate-jiff \
bundled-rust-crate-jiff-static \
bundled-rust-crate-jobserver \
bundled-rust-crate-jsonptr \
bundled-rust-crate-jsonwebtoken \
bundled-rust-crate-kasuari \
bundled-rust-crate-keccak \
bundled-rust-crate-kem \
bundled-rust-crate-keyring \
bundled-rust-crate-kstring \
bundled-rust-crate-lab \
bundled-rust-crate-landlock \
bundled-rust-crate-language-tags \
bundled-rust-crate-lazy-static \
bundled-rust-crate-libc \
bundled-rust-crate-libdbus-sys \
bundled-rust-crate-libm \
bundled-rust-crate-libsqlite3-sys \
bundled-rust-crate-line-clipping \
bundled-rust-crate-link-section \
bundled-rust-crate-linked-hash-map \
bundled-rust-crate-linktime-proc-macro \
bundled-rust-crate-linux-keyutils \
bundled-rust-crate-linux-raw-sys \
bundled-rust-crate-litemap \
bundled-rust-crate-litrs \
bundled-rust-crate-local-waker \
bundled-rust-crate-lock-api \
bundled-rust-crate-lock-free-hashtable \
bundled-rust-crate-log \
bundled-rust-crate-logos \
bundled-rust-crate-logos-codegen \
bundled-rust-crate-logos-derive \
bundled-rust-crate-lru \
bundled-rust-crate-lru-slab \
bundled-rust-crate-lsp-types \
bundled-rust-crate-lzma-rs \
bundled-rust-crate-lzma-sys \
bundled-rust-crate-mac-address \
bundled-rust-crate-maplit \
bundled-rust-crate-matchers \
bundled-rust-crate-matchit \
bundled-rust-crate-maybe-async \
bundled-rust-crate-md-5 \
bundled-rust-crate-md5 \
bundled-rust-crate-memchr \
bundled-rust-crate-memmap2 \
bundled-rust-crate-memmem \
bundled-rust-crate-memoffset \
bundled-rust-crate-mime \
bundled-rust-crate-mime-guess \
bundled-rust-crate-minimal-lexical \
bundled-rust-crate-miniz-oxide \
bundled-rust-crate-mio \
bundled-rust-crate-ml-kem \
bundled-rust-crate-moka \
bundled-rust-crate-moxcms \
bundled-rust-crate-multimap \
bundled-rust-crate-native-tls \
bundled-rust-crate-nibble-vec \
bundled-rust-crate-nix \
bundled-rust-crate-nom \
bundled-rust-crate-nonempty \
bundled-rust-crate-notify \
bundled-rust-crate-notify-types \
bundled-rust-crate-nu-ansi-term \
bundled-rust-crate-nucleo \
bundled-rust-crate-nucleo-matcher \
bundled-rust-crate-num \
bundled-rust-crate-num-bigint \
bundled-rust-crate-num-complex \
bundled-rust-crate-num-conv \
bundled-rust-crate-num-cpus \
bundled-rust-crate-num-derive \
bundled-rust-crate-num-integer \
bundled-rust-crate-num-iter \
bundled-rust-crate-num-rational \
bundled-rust-crate-num-threads \
bundled-rust-crate-num-traits \
bundled-rust-crate-numtoa \
bundled-rust-crate-oauth2 \
bundled-rust-crate-object \
bundled-rust-crate-oid-registry \
bundled-rust-crate-once-cell \
bundled-rust-crate-onig \
bundled-rust-crate-onig-sys \
bundled-rust-crate-opaque-debug \
bundled-rust-crate-openssl \
bundled-rust-crate-openssl-macros \
bundled-rust-crate-openssl-probe \
bundled-rust-crate-openssl-src \
bundled-rust-crate-openssl-sys \
bundled-rust-crate-opentelemetry \
bundled-rust-crate-opentelemetry-appender-tracing \
bundled-rust-crate-opentelemetry-http \
bundled-rust-crate-opentelemetry-otlp \
bundled-rust-crate-opentelemetry-proto \
bundled-rust-crate-opentelemetry-sdk \
bundled-rust-crate-opentelemetry-semantic-conventions \
bundled-rust-crate-option-ext \
bundled-rust-crate-ordered-float \
bundled-rust-crate-ordered-stream \
bundled-rust-crate-os-info \
bundled-rust-crate-os-pipe \
bundled-rust-crate-outref \
bundled-rust-crate-owo-colors \
bundled-rust-crate-p256 \
bundled-rust-crate-pagable \
bundled-rust-crate-pagable-derive \
bundled-rust-crate-palette \
bundled-rust-crate-palette-derive \
bundled-rust-crate-parking \
bundled-rust-crate-parking-lot \
bundled-rust-crate-parking-lot-core \
bundled-rust-crate-paste \
bundled-rust-crate-pastey \
bundled-rust-crate-pathdiff \
bundled-rust-crate-pbkdf2 \
bundled-rust-crate-pem \
bundled-rust-crate-pem-rfc7468 \
bundled-rust-crate-percent-encoding \
bundled-rust-crate-pest \
bundled-rust-crate-pest-derive \
bundled-rust-crate-pest-generator \
bundled-rust-crate-pest-meta \
bundled-rust-crate-petgraph \
bundled-rust-crate-phf \
bundled-rust-crate-phf-codegen \
bundled-rust-crate-phf-generator \
bundled-rust-crate-phf-macros \
bundled-rust-crate-phf-shared \
bundled-rust-crate-pin-project \
bundled-rust-crate-pin-project-internal \
bundled-rust-crate-pin-project-lite \
bundled-rust-crate-pin-utils \
bundled-rust-crate-piper \
bundled-rust-crate-pkcs8 \
bundled-rust-crate-pkg-config \
bundled-rust-crate-plist \
bundled-rust-crate-png \
bundled-rust-crate-polling \
bundled-rust-crate-poly1305 \
bundled-rust-crate-polyval \
bundled-rust-crate-portable-atomic \
bundled-rust-crate-portable-pty \
bundled-rust-crate-postcard \
bundled-rust-crate-potential-utf \
bundled-rust-crate-powerfmt \
bundled-rust-crate-ppv-lite86 \
bundled-rust-crate-prettyplease \
bundled-rust-crate-primeorder \
bundled-rust-crate-proc-macro-crate \
bundled-rust-crate-proc-macro-error-attr2 \
bundled-rust-crate-proc-macro-error2 \
bundled-rust-crate-proc-macro2 \
bundled-rust-crate-process-wrap \
bundled-rust-crate-prodash \
bundled-rust-crate-proptest \
bundled-rust-crate-prost \
bundled-rust-crate-prost-build \
bundled-rust-crate-prost-derive \
bundled-rust-crate-prost-types \
bundled-rust-crate-protoc-bin-vendored \
bundled-rust-crate-protoc-bin-vendored-linux-aarch-64 \
bundled-rust-crate-protoc-bin-vendored-linux-ppcle-64 \
bundled-rust-crate-protoc-bin-vendored-linux-s390-64 \
bundled-rust-crate-protoc-bin-vendored-linux-x86-32 \
bundled-rust-crate-protoc-bin-vendored-linux-x86-64 \
bundled-rust-crate-protoc-bin-vendored-macos-aarch-64 \
bundled-rust-crate-protoc-bin-vendored-macos-x86-64 \
bundled-rust-crate-protoc-bin-vendored-win32 \
bundled-rust-crate-psl \
bundled-rust-crate-psl-types \
bundled-rust-crate-publicsuffix \
bundled-rust-crate-pulldown-cmark \
bundled-rust-crate-pulldown-cmark-escape \
bundled-rust-crate-pxfm \
bundled-rust-crate-quick-error \
bundled-rust-crate-quick-xml \
bundled-rust-crate-quickcheck \
bundled-rust-crate-quinn \
bundled-rust-crate-quinn-proto \
bundled-rust-crate-quinn-udp \
bundled-rust-crate-quote \
bundled-rust-crate-radix-trie \
bundled-rust-crate-rama-core \
bundled-rust-crate-rama-dns \
bundled-rust-crate-rama-error \
bundled-rust-crate-rama-http \
bundled-rust-crate-rama-http-backend \
bundled-rust-crate-rama-http-core \
bundled-rust-crate-rama-http-headers \
bundled-rust-crate-rama-http-types \
bundled-rust-crate-rama-macros \
bundled-rust-crate-rama-net \
bundled-rust-crate-rama-socks5 \
bundled-rust-crate-rama-tcp \
bundled-rust-crate-rama-tls-rustls \
bundled-rust-crate-rama-udp \
bundled-rust-crate-rama-unix \
bundled-rust-crate-rama-utils \
bundled-rust-crate-rand \
bundled-rust-crate-rand-chacha \
bundled-rust-crate-rand-core \
bundled-rust-crate-rand-xorshift \
bundled-rust-crate-ratatui \
bundled-rust-crate-ratatui-core \
bundled-rust-crate-ratatui-crossterm \
bundled-rust-crate-ratatui-macros \
bundled-rust-crate-ratatui-termina \
bundled-rust-crate-ratatui-termion \
bundled-rust-crate-ratatui-termwiz \
bundled-rust-crate-ratatui-widgets \
bundled-rust-crate-rayon \
bundled-rust-crate-rayon-core \
bundled-rust-crate-rcgen \
bundled-rust-crate-ref-cast \
bundled-rust-crate-ref-cast-impl \
bundled-rust-crate-regex \
bundled-rust-crate-regex-automata \
bundled-rust-crate-regex-lite \
bundled-rust-crate-regex-syntax \
bundled-rust-crate-reqwest \
bundled-rust-crate-resolv-conf \
bundled-rust-crate-rfc6979 \
bundled-rust-crate-ring \
bundled-rust-crate-rmcp \
bundled-rust-crate-rmcp-macros \
bundled-rust-crate-rust-embed \
bundled-rust-crate-rust-embed-impl \
bundled-rust-crate-rust-embed-utils \
bundled-rust-crate-rust-stemmers \
bundled-rust-crate-rustc-demangle \
bundled-rust-crate-rustc-hash \
bundled-rust-crate-rustc-version \
bundled-rust-crate-rusticata-macros \
bundled-rust-crate-rustix \
bundled-rust-crate-rustls \
bundled-rust-crate-rustls-native-certs \
bundled-rust-crate-rustls-pki-types \
bundled-rust-crate-rustls-webpki \
bundled-rust-crate-rustversion \
bundled-rust-crate-rustyline \
bundled-rust-crate-ryu \
bundled-rust-crate-salsa20 \
bundled-rust-crate-same-file \
bundled-rust-crate-schemafy \
bundled-rust-crate-schemafy-core \
bundled-rust-crate-schemafy-lib \
bundled-rust-crate-schemars \
bundled-rust-crate-schemars-derive \
bundled-rust-crate-scopeguard \
bundled-rust-crate-scrypt \
bundled-rust-crate-sec1 \
bundled-rust-crate-seccompiler \
bundled-rust-crate-secrecy \
bundled-rust-crate-secret-service \
bundled-rust-crate-self-cell \
bundled-rust-crate-semver \
bundled-rust-crate-sentry \
bundled-rust-crate-sentry-actix \
bundled-rust-crate-sentry-backtrace \
bundled-rust-crate-sentry-contexts \
bundled-rust-crate-sentry-core \
bundled-rust-crate-sentry-debug-images \
bundled-rust-crate-sentry-panic \
bundled-rust-crate-sentry-tracing \
bundled-rust-crate-sentry-types \
bundled-rust-crate-sequence-trie \
bundled-rust-crate-serde \
bundled-rust-crate-serde-core \
bundled-rust-crate-serde-derive \
bundled-rust-crate-serde-derive-internals \
bundled-rust-crate-serde-html-form \
bundled-rust-crate-serde-ignored \
bundled-rust-crate-serde-json \
bundled-rust-crate-serde-path-to-error \
bundled-rust-crate-serde-repr \
bundled-rust-crate-serde-spanned \
bundled-rust-crate-serde-urlencoded \
bundled-rust-crate-serde-with \
bundled-rust-crate-serde-with-macros \
bundled-rust-crate-serde-yaml \
bundled-rust-crate-serial2 \
bundled-rust-crate-sha1 \
bundled-rust-crate-sha1-checked \
bundled-rust-crate-sha1-smol \
bundled-rust-crate-sha2 \
bundled-rust-crate-sha3 \
bundled-rust-crate-sharded-slab \
bundled-rust-crate-shell-words \
bundled-rust-crate-shlex \
bundled-rust-crate-signal-hook \
bundled-rust-crate-signal-hook-mio \
bundled-rust-crate-signal-hook-registry \
bundled-rust-crate-signature \
bundled-rust-crate-simd-adler32 \
bundled-rust-crate-simdutf8 \
bundled-rust-crate-similar \
bundled-rust-crate-simple-asn1 \
bundled-rust-crate-siphasher \
bundled-rust-crate-slab \
bundled-rust-crate-smallvec \
bundled-rust-crate-smawk \
bundled-rust-crate-smol-str \
bundled-rust-crate-socket2 \
bundled-rust-crate-sorted-vector-map \
bundled-rust-crate-spin \
bundled-rust-crate-spki \
bundled-rust-crate-sqlx \
bundled-rust-crate-sqlx-core \
bundled-rust-crate-sqlx-macros \
bundled-rust-crate-sqlx-macros-core \
bundled-rust-crate-sqlx-mysql \
bundled-rust-crate-sqlx-postgres \
bundled-rust-crate-sqlx-sqlite \
bundled-rust-crate-sse-stream \
bundled-rust-crate-stable-deref-trait \
bundled-rust-crate-starlark \
bundled-rust-crate-starlark-derive \
bundled-rust-crate-starlark-map \
bundled-rust-crate-starlark-syntax \
bundled-rust-crate-static-assertions \
bundled-rust-crate-static-interner \
bundled-rust-crate-stop-words \
bundled-rust-crate-streaming-iterator \
bundled-rust-crate-stringprep \
bundled-rust-crate-strong-hash \
bundled-rust-crate-strong-hash-derive \
bundled-rust-crate-strsim \
bundled-rust-crate-strum \
bundled-rust-crate-strum-macros \
bundled-rust-crate-subtle \
bundled-rust-crate-supports-color \
bundled-rust-crate-symphonia \
bundled-rust-crate-symphonia-bundle-mp3 \
bundled-rust-crate-symphonia-common \
bundled-rust-crate-symphonia-core \
bundled-rust-crate-symphonia-format-isomp4 \
bundled-rust-crate-symphonia-format-mkv \
bundled-rust-crate-symphonia-format-ogg \
bundled-rust-crate-symphonia-format-riff \
bundled-rust-crate-symphonia-metadata \
bundled-rust-crate-syn \
bundled-rust-crate-sync-wrapper \
bundled-rust-crate-synstructure \
bundled-rust-crate-syntect \
bundled-rust-crate-sys-locale \
bundled-rust-crate-tagptr \
bundled-rust-crate-take-mut \
bundled-rust-crate-tar \
bundled-rust-crate-tempfile \
bundled-rust-crate-termcolor \
bundled-rust-crate-termina \
bundled-rust-crate-terminal-size \
bundled-rust-crate-terminfo \
bundled-rust-crate-termion \
bundled-rust-crate-termios \
bundled-rust-crate-termwiz \
bundled-rust-crate-textwrap \
bundled-rust-crate-thiserror \
bundled-rust-crate-thiserror-impl \
bundled-rust-crate-thiserror-impl-no-std \
bundled-rust-crate-thiserror-no-std \
bundled-rust-crate-thread-local \
bundled-rust-crate-tiff \
bundled-rust-crate-time \
bundled-rust-crate-time-core \
bundled-rust-crate-time-macros \
bundled-rust-crate-tiny-http \
bundled-rust-crate-tinystr \
bundled-rust-crate-tinyvec \
bundled-rust-crate-tinyvec-macros \
bundled-rust-crate-tokio \
bundled-rust-crate-tokio-graceful \
bundled-rust-crate-tokio-macros \
bundled-rust-crate-tokio-native-tls \
bundled-rust-crate-tokio-rustls \
bundled-rust-crate-tokio-stream \
bundled-rust-crate-tokio-test \
bundled-rust-crate-tokio-tungstenite \
bundled-rust-crate-tokio-util \
bundled-rust-crate-toml \
bundled-rust-crate-toml-datetime \
bundled-rust-crate-toml-edit \
bundled-rust-crate-toml-parser \
bundled-rust-crate-toml-writer \
bundled-rust-crate-tonic \
bundled-rust-crate-tonic-build \
bundled-rust-crate-tonic-prost \
bundled-rust-crate-tonic-prost-build \
bundled-rust-crate-tower \
bundled-rust-crate-tower-http \
bundled-rust-crate-tower-layer \
bundled-rust-crate-tower-service \
bundled-rust-crate-tracing \
bundled-rust-crate-tracing-appender \
bundled-rust-crate-tracing-attributes \
bundled-rust-crate-tracing-core \
bundled-rust-crate-tracing-error \
bundled-rust-crate-tracing-log \
bundled-rust-crate-tracing-opentelemetry \
bundled-rust-crate-tracing-serde \
bundled-rust-crate-tracing-subscriber \
bundled-rust-crate-tree-magic-mini \
bundled-rust-crate-tree-sitter \
bundled-rust-crate-tree-sitter-bash \
bundled-rust-crate-tree-sitter-language \
bundled-rust-crate-tree-sitter-powershell \
bundled-rust-crate-triomphe \
bundled-rust-crate-try-lock \
bundled-rust-crate-ts-rs \
bundled-rust-crate-ts-rs-macros \
bundled-rust-crate-tungstenite \
bundled-rust-crate-two-face \
bundled-rust-crate-type-map \
bundled-rust-crate-typeid \
bundled-rust-crate-typenum \
bundled-rust-crate-ucd-trie \
bundled-rust-crate-uname \
bundled-rust-crate-unarray \
bundled-rust-crate-unic-langid \
bundled-rust-crate-unic-langid-impl \
bundled-rust-crate-unicase \
bundled-rust-crate-unicode-bidi \
bundled-rust-crate-unicode-bom \
bundled-rust-crate-unicode-ident \
bundled-rust-crate-unicode-linebreak \
bundled-rust-crate-unicode-normalization \
bundled-rust-crate-unicode-properties \
bundled-rust-crate-unicode-segmentation \
bundled-rust-crate-unicode-truncate \
bundled-rust-crate-unicode-width \
bundled-rust-crate-unicode-xid \
bundled-rust-crate-universal-hash \
bundled-rust-crate-unsafe-libyaml \
bundled-rust-crate-untrusted \
bundled-rust-crate-ureq \
bundled-rust-crate-ureq-proto \
bundled-rust-crate-url \
bundled-rust-crate-urlencoding \
bundled-rust-crate-utf-8 \
bundled-rust-crate-utf8-iter \
bundled-rust-crate-utf8parse \
bundled-rust-crate-uuid \
bundled-rust-crate-vcpkg \
bundled-rust-crate-version-check \
bundled-rust-crate-vsimd \
bundled-rust-crate-vtparse \
bundled-rust-crate-walkdir \
bundled-rust-crate-want \
bundled-rust-crate-wayland-backend \
bundled-rust-crate-wayland-client \
bundled-rust-crate-wayland-protocols \
bundled-rust-crate-wayland-protocols-wlr \
bundled-rust-crate-wayland-scanner \
bundled-rust-crate-wayland-sys \
bundled-rust-crate-web-time \
bundled-rust-crate-webbrowser \
bundled-rust-crate-webpki-root-certs \
bundled-rust-crate-webpki-roots \
bundled-rust-crate-weezl \
bundled-rust-crate-wezterm-bidi \
bundled-rust-crate-wezterm-blob-leases \
bundled-rust-crate-wezterm-color-types \
bundled-rust-crate-wezterm-dynamic \
bundled-rust-crate-wezterm-dynamic-derive \
bundled-rust-crate-wezterm-input-types \
bundled-rust-crate-which \
bundled-rust-crate-whoami \
bundled-rust-crate-wildcard \
bundled-rust-crate-wildmatch \
bundled-rust-crate-windows \
bundled-rust-crate-windows-core \
bundled-rust-crate-windows-implement \
bundled-rust-crate-windows-interface \
bundled-rust-crate-windows-result \
bundled-rust-crate-windows-strings \
bundled-rust-crate-windows-targets \
bundled-rust-crate-winnow \
bundled-rust-crate-wiremock \
bundled-rust-crate-wl-clipboard-rs \
bundled-rust-crate-writeable \
bundled-rust-crate-x11rb \
bundled-rust-crate-x11rb-protocol \
bundled-rust-crate-x25519-dalek \
bundled-rust-crate-x509-parser \
bundled-rust-crate-xdg-home \
bundled-rust-crate-xmlparser \
bundled-rust-crate-xz2 \
bundled-rust-crate-yaml-rust \
bundled-rust-crate-yasna \
bundled-rust-crate-yoke \
bundled-rust-crate-yoke-derive \
bundled-rust-crate-zbus \
bundled-rust-crate-zbus-macros \
bundled-rust-crate-zbus-names \
bundled-rust-crate-zerocopy \
bundled-rust-crate-zerocopy-derive \
bundled-rust-crate-zerofrom \
bundled-rust-crate-zerofrom-derive \
bundled-rust-crate-zeroize \
bundled-rust-crate-zeroize-derive \
bundled-rust-crate-zerotrie \
bundled-rust-crate-zerovec \
bundled-rust-crate-zerovec-derive \
bundled-rust-crate-zip \
bundled-rust-crate-zlib-rs \
bundled-rust-crate-zmij \
bundled-rust-crate-zopfli \
bundled-rust-crate-zstd \
bundled-rust-crate-zstd-safe \
bundled-rust-crate-zstd-sys \
bundled-rust-crate-zune-core \
bundled-rust-crate-zune-jpeg \
bundled-rust-crate-zvariant \
bundled-rust-crate-zvariant-derive \
bundled-rust-crate-zvariant-utils \
openai-codex"

RDEPENDS:${PN} += "bubblewrap \
git-core \
libbz2.so.1 \
libc.so.6 \
libcrypto.so.3 \
libgcc-s.so.1 \
liblzma.so.5 \
libm.so.6 \
libonig.so.5 \
libsqlite3.so.0 \
libssl.so.3 \
libzstd.so.1"

inherit rpm
