SUMMARY = "Lua Documentation for lpeg"
DESCRIPTION = "Documentation and examples included with the library, sometimes \
generated by luadoc or ldoc."
LICENSE = "MIT"

PV = "1.1.0"

RPM_NAME = "luajit-lpeg-doc-1.1.0-3.4.noarch.rpm"
RPM_HASH = "97098f25be351c65dee6c6cf9faa1761b6cb140f2f662915a39ee469248aecb366a001c5d05cab8774e5be5f8622371ab761306fcadf9c074a7b0ffb1509e7c6"
REPO_ARCH = "noarch"

RPROVIDES:${PN} += "luajit-lpeg-doc"

RDEPENDS:${PN} += "luajit-lpeg"

inherit rpm
