SUMMARY = "Kernel driver"
DESCRIPTION = "This module is the kernel-dependent driver for DRBD. This is split out so \
that multiple kernel driver versions can be installed, one for each \
installed kernel."
LICENSE = "GPL-2.0-or-later"

PV = "9.1.23_k7.2.4_1"

RPM_NAME = "drbd-kmp-default-9.1.23_k7.2.4_1-10.3.aarch64.rpm"
RPM_HASH = "d599e965891b94ab176dde591c61f3dd363138f23d966ebcc5af3f279bbaf805b6ae5b11731a7d7ed707827ee092b8714856244f101c5c0a1616c9d1f1808a97"

RPROVIDES:${PN} += "drbd-kmp \
drbd-kmp-default \
drbd-kmp-default-k7.2.4-1 \
kmod-drbd-transport-tcp.ko \
kmod-drbd.ko \
ksym-default---drbd-next-path-ref \
ksym-default-drbd-alloc-pages \
ksym-default-drbd-destroy-connection \
ksym-default-drbd-destroy-path \
ksym-default-drbd-find-path-by-addr \
ksym-default-drbd-free-pages \
ksym-default-drbd-get-listener \
ksym-default-drbd-listener-destroy \
ksym-default-drbd-path-event \
ksym-default-drbd-put-listener \
ksym-default-drbd-register-transport-class \
ksym-default-drbd-should-abort-listening \
ksym-default-drbd-stream-send-timed-out \
ksym-default-drbd-unregister-transport-class \
multiversion-kernel"

RDEPENDS:${PN} += "/usr/bin/sh \
coreutils \
grep \
kernel-default \
ksym-default----ratelimit \
ksym-default---alloc-skb \
ksym-default---bio-add-page \
ksym-default---bitmap-and \
ksym-default---bitmap-equal \
ksym-default---blk-alloc-disk \
ksym-default---cpu-online-mask \
ksym-default---cpu-possible-mask \
ksym-default---dynamic-pr-debug \
ksym-default---folio-put \
ksym-default---fortify-panic \
ksym-default---free-pages \
ksym-default---get-random-u32-below \
ksym-default---init-rwsem \
ksym-default---init-swait-queue-head \
ksym-default---init-waitqueue-head \
ksym-default---ipv6-addr-type \
ksym-default---kmalloc-cache-noprof \
ksym-default---kmalloc-noprof \
ksym-default---kmem-cache-create-args \
ksym-default---list-add-valid-or-report \
ksym-default---list-del-entry-valid-or-report \
ksym-default---nla-parse \
ksym-default---per-cpu-offset \
ksym-default---rb-erase-color \
ksym-default---rb-insert-augmented \
ksym-default---rcu-read-lock \
ksym-default---rcu-read-unlock \
ksym-default---register-blkdev \
ksym-default---request-module \
ksym-default---seq-puts \
ksym-default---stack-chk-fail \
ksym-default---sw-hweight32 \
ksym-default---sw-hweight64 \
ksym-default---vmalloc-noprof \
ksym-default---wake-up \
ksym-default---warn-printk \
ksym-default--find-first-bit \
ksym-default--find-next-bit \
ksym-default--find-next-zero-bit \
ksym-default--printk \
ksym-default--raw-read-lock \
ksym-default--raw-read-lock-irq \
ksym-default--raw-read-lock-irqsave \
ksym-default--raw-read-unlock \
ksym-default--raw-read-unlock-irq \
ksym-default--raw-read-unlock-irqrestore \
ksym-default--raw-spin-lock \
ksym-default--raw-spin-lock-bh \
ksym-default--raw-spin-lock-irq \
ksym-default--raw-spin-lock-irqsave \
ksym-default--raw-spin-unlock \
ksym-default--raw-spin-unlock-bh \
ksym-default--raw-spin-unlock-irq \
ksym-default--raw-spin-unlock-irqrestore \
ksym-default--raw-write-lock-bh \
ksym-default--raw-write-lock-irq \
ksym-default--raw-write-lock-irqsave \
ksym-default--raw-write-unlock-bh \
ksym-default--raw-write-unlock-irq \
ksym-default--raw-write-unlock-irqrestore \
ksym-default-alloc-cpumask-var-node \
ksym-default-alloc-pages-noprof \
ksym-default-alloc-workqueue-noprof \
ksym-default-alt-cb-patch-nops \
ksym-default-arch-wb-cache-pmem \
ksym-default-autoremove-wake-function \
ksym-default-bd-link-disk-holder \
ksym-default-bd-unlink-disk-holder \
ksym-default-bdev-alignment-offset \
ksym-default-bdev-discard-alignment \
ksym-default-bdev-file-open-by-path \
ksym-default-bio-add-page \
ksym-default-bio-alloc-bioset \
ksym-default-bio-alloc-clone \
ksym-default-bio-associate-blkg \
ksym-default-bio-end-io-acct-remapped \
ksym-default-bio-endio \
ksym-default-bio-put \
ksym-default-bio-split-to-limits \
ksym-default-bio-start-io-acct \
ksym-default-bioset-exit \
ksym-default-bioset-init \
ksym-default-bitmap-parse \
ksym-default-blk-check-plugged \
ksym-default-blk-finish-plug \
ksym-default-blk-set-stacking-limits \
ksym-default-blk-stack-limits \
ksym-default-blk-start-plug \
ksym-default-blk-status-to-errno \
ksym-default-blkdev-issue-discard \
ksym-default-blkdev-issue-zeroout \
ksym-default-call-rcu \
ksym-default-call-usermodehelper \
ksym-default-cancel-work-sync \
ksym-default-capable \
ksym-default-complete \
ksym-default-complete-all \
ksym-default-copy-highpage \
ksym-default-crc32c \
ksym-default-crypto-alloc-shash \
ksym-default-crypto-destroy-tfm \
ksym-default-crypto-shash-digest \
ksym-default-crypto-shash-finup \
ksym-default-crypto-shash-init \
ksym-default-crypto-shash-setkey \
ksym-default-dax-direct-access \
ksym-default-dax-read-lock \
ksym-default-dax-read-unlock \
ksym-default-debugfs-change-name \
ksym-default-debugfs-create-dir \
ksym-default-debugfs-create-file-full \
ksym-default-debugfs-create-symlink \
ksym-default-debugfs-remove \
ksym-default-del-gendisk \
ksym-default-destroy-workqueue \
ksym-default-device-add-disk \
ksym-default-down \
ksym-default-down-interruptible \
ksym-default-down-read \
ksym-default-down-trylock \
ksym-default-down-write \
ksym-default-down-write-trylock \
ksym-default-downgrade-write \
ksym-default-dynamic-cond-resched \
ksym-default-dynamic-might-resched \
ksym-default-dynamic-preempt-schedule \
ksym-default-errno-to-blk-status \
ksym-default-file-bdev \
ksym-default-finish-wait \
ksym-default-flush-signals \
ksym-default-fput \
ksym-default-free-cpumask-var \
ksym-default-free-pages \
ksym-default-fs-bio-set \
ksym-default-fs-dax-get-by-bdev \
ksym-default-genl-register-family \
ksym-default-genl-unregister-family \
ksym-default-genlmsg-multicast-allns \
ksym-default-genlmsg-put \
ksym-default-get-free-pages-noprof \
ksym-default-get-random-bytes \
ksym-default-get-random-u32 \
ksym-default-get-random-u8 \
ksym-default-idr-alloc \
ksym-default-idr-destroy \
ksym-default-idr-find \
ksym-default-idr-get-next \
ksym-default-idr-remove \
ksym-default-init-net \
ksym-default-init-wait-entry \
ksym-default-iov-iter-bvec \
ksym-default-jiffies \
ksym-default-kasprintf \
ksym-default-kernel-accept \
ksym-default-kernel-recvmsg \
ksym-default-kernel-sendmsg \
ksym-default-kernel-sigaction \
ksym-default-kernel-sock-shutdown \
ksym-default-kfree \
ksym-default-kmalloc-caches \
ksym-default-kmem-cache-destroy \
ksym-default-kobject-uevent \
ksym-default-kstrdup \
ksym-default-kstrtoull \
ksym-default-kthread-create-on-node \
ksym-default-ktime-get \
ksym-default-ktime-get-with-offset \
ksym-default-kvasprintf \
ksym-default-kvfree \
ksym-default-kvfree-call-rcu \
ksym-default-lc-committed \
ksym-default-lc-create \
ksym-default-lc-del \
ksym-default-lc-destroy \
ksym-default-lc-element-by-index \
ksym-default-lc-find \
ksym-default-lc-get \
ksym-default-lc-get-cumulative \
ksym-default-lc-is-used \
ksym-default-lc-put \
ksym-default-lc-reset \
ksym-default-lc-seq-dump-details \
ksym-default-lc-seq-printf-stats \
ksym-default-lc-try-get \
ksym-default-lc-try-lock \
ksym-default-memcmp \
ksym-default-memcpy \
ksym-default-memmove \
ksym-default-mempool-alloc-noprof \
ksym-default-mempool-alloc-pages \
ksym-default-mempool-alloc-slab \
ksym-default-mempool-exit \
ksym-default-mempool-free \
ksym-default-mempool-free-pages \
ksym-default-mempool-free-slab \
ksym-default-mempool-init-noprof \
ksym-default-memset \
ksym-default-mod-timer \
ksym-default-mod-timer-pending \
ksym-default-module-layout \
ksym-default-module-put \
ksym-default-mutex-init-generic \
ksym-default-mutex-is-locked \
ksym-default-mutex-lock \
ksym-default-mutex-lock-interruptible \
ksym-default-mutex-trylock \
ksym-default-mutex-unlock \
ksym-default-netlink-unicast \
ksym-default-nla-find \
ksym-default-nla-memcpy \
ksym-default-nla-put \
ksym-default-nla-put-64bit \
ksym-default-nla-put-nohdr \
ksym-default-nla-reserve \
ksym-default-nla-strscpy \
ksym-default-nr-cpu-ids \
ksym-default-ns-to-timespec64 \
ksym-default-panic \
ksym-default-param-get-uint \
ksym-default-param-ops-bool \
ksym-default-param-ops-string \
ksym-default-param-ops-uint \
ksym-default-prepare-to-wait \
ksym-default-prepare-to-wait-event \
ksym-default-proc-create-single-data \
ksym-default-put-dax \
ksym-default-put-disk \
ksym-default-queue-limits-commit-update \
ksym-default-queue-work-on \
ksym-default-radix-tree-tagged \
ksym-default-random-kmalloc-seed \
ksym-default-rb-next \
ksym-default-rcu-barrier \
ksym-default-refcount-warn-saturate \
ksym-default-remove-proc-entry \
ksym-default-sched-set-fifo-low \
ksym-default-schedule \
ksym-default-schedule-timeout \
ksym-default-schedule-timeout-interruptible \
ksym-default-schedule-timeout-uninterruptible \
ksym-default-scnprintf \
ksym-default-send-sig \
ksym-default-seq-lseek \
ksym-default-seq-printf \
ksym-default-seq-putc \
ksym-default-seq-read \
ksym-default-seq-write \
ksym-default-set-capacity-and-notify \
ksym-default-set-cpus-allowed-ptr \
ksym-default-sigprocmask \
ksym-default-single-open \
ksym-default-single-release \
ksym-default-sized-strscpy \
ksym-default-sk-skb-reason-drop \
ksym-default-skb-trim \
ksym-default-snprintf \
ksym-default-sock-create-kern \
ksym-default-sock-release \
ksym-default-sock-sendmsg \
ksym-default-sock-set-keepalive \
ksym-default-sprintf \
ksym-default-strcmp \
ksym-default-strlen \
ksym-default-strnlen \
ksym-default-strstr \
ksym-default-submit-bio \
ksym-default-submit-bio-noacct \
ksym-default-sync-blockdev \
ksym-default-synchronize-rcu \
ksym-default-sys-tz \
ksym-default-system-percpu-wq \
ksym-default-tcp-sock-set-cork \
ksym-default-tcp-sock-set-keepcnt \
ksym-default-tcp-sock-set-keepidle \
ksym-default-tcp-sock-set-keepintvl \
ksym-default-tcp-sock-set-nodelay \
ksym-default-tcp-sock-set-quickack \
ksym-default-time64-to-tm \
ksym-default-timer-delete \
ksym-default-timer-delete-sync \
ksym-default-timer-init-key \
ksym-default-timer-shutdown-sync \
ksym-default-try-module-get \
ksym-default-unregister-blkdev \
ksym-default-up \
ksym-default-up-read \
ksym-default-up-write \
ksym-default-vscnprintf \
ksym-default-vsnprintf \
ksym-default-wait-for-completion \
ksym-default-wait-for-completion-interruptible \
ksym-default-wake-up-process \
suse-kernel-rpm-scriptlets"

inherit rpm
