SUMMARY = "Utilities for working with libt3key terminal descriptions"
DESCRIPTION = "libt3key is library that provides a database of mappings from escape \
sequences as generated by different consoles and terminals or \
emulators, to key symbols. \
 \
This subpackage contains the t3learnkeys and t3keyc programs."
LICENSE = "GPL-3.0-only"

PV = "0.2.11"

RPM_NAME = "libt3key-utils-0.2.11-1.8.aarch64.rpm"
RPM_HASH = "71534f263cab24213435932218955ac0a3d728abdf2a238f84dca4ca84ab7e053cbf8834e20af0ed716a06ed7e09bb29823ec25154334e6eef48a544692ff683"

RPROVIDES:${PN} += "libt3key-utils"

RDEPENDS:${PN} += "libc.so.6 \
libt3config.so.0 \
libtinfo.so.6 \
libxcb.so.1"

inherit rpm
