SUMMARY = "Configuration utilities for bcachefs"
DESCRIPTION = "Bcachefs is a filesystem for Linux, with an emphasis on reliability \
and robustness. \
 \
* Copy on write (COW) like zfs or btrfs \
* Full data and metadata checksumming \
* Multiple devices \
* Replication \
* Erasure coding \
* Caching \
* Compression \
* Encryption \
* Snapshots \
 \
This package contains utilities for creating and mounting bcachefs."
LICENSE = "Apache-2.0 & (Apache-2.0 | MIT) & (Apache-2.0 | Apache-2.0-with-LLVM-exception | MIT) & MIT & MPL-2.0 & (MIT | Unlicense) & BSD-3-Clause & GPL-2.0-only & GPL-2.0-or-later & LGPL-2.1-only"

PV = "1.39.6_k7.2.5_1"

RPM_NAME = "bcachefs-kmp-64kb-1.39.6_k7.2.5_1-1.1.aarch64.rpm"
RPM_HASH = "0cc672215d136d9e68bcc375aa95e7725af54b9c290c2f1a01a1e668728eeb8c0f1aea6887b1fa5ca32d09b8ac9e40e8d65f90ba9dafac9dbcbd9cf135d92d92"

RPROVIDES:${PN} += "bcachefs-kmp \
bcachefs-kmp-64kb \
bcachefs-kmp-64kb-k7.2.5-1 \
kmod-bcachefs.ko \
ksym-64kb---six-lock-init \
ksym-64kb-bch2-run-thread-with-stdout \
ksym-64kb-mean-and-variance-get-mad \
ksym-64kb-mean-and-variance-get-mean \
ksym-64kb-mean-and-variance-get-median \
ksym-64kb-mean-and-variance-get-stddev \
ksym-64kb-six-lock-contended \
ksym-64kb-six-lock-counts \
ksym-64kb-six-lock-downgrade \
ksym-64kb-six-lock-exit \
ksym-64kb-six-lock-increment \
ksym-64kb-six-lock-ip-waiter \
ksym-64kb-six-lock-readers-add \
ksym-64kb-six-lock-tryupgrade \
ksym-64kb-six-lock-wakeup-all \
ksym-64kb-six-relock-ip \
ksym-64kb-six-trylock-convert \
ksym-64kb-six-trylock-ip \
ksym-64kb-six-unlock-ip \
multiversion-kernel"

RDEPENDS:${PN} += "/usr/bin/sh \
coreutils \
grep \
kernel-64kb \
ksym-64kb----ratelimit \
ksym-64kb---arch-clear-user \
ksym-64kb---arch-copy-from-user \
ksym-64kb---arch-copy-to-user \
ksym-64kb---audit-inode-child \
ksym-64kb---bio-advance \
ksym-64kb---bio-release-pages \
ksym-64kb---bitmap-and \
ksym-64kb---bitmap-andnot \
ksym-64kb---bitmap-or \
ksym-64kb---bitmap-weight \
ksym-64kb---check-object-size \
ksym-64kb---cpu-online-mask \
ksym-64kb---cpu-possible-mask \
ksym-64kb---destroy-inode \
ksym-64kb---dynamic-pr-debug \
ksym-64kb---filemap-get-folio-mpol \
ksym-64kb---filemap-set-wb-err \
ksym-64kb---folio-batch-release \
ksym-64kb---folio-lock \
ksym-64kb---folio-put \
ksym-64kb---folio-start-writeback \
ksym-64kb---fortify-panic \
ksym-64kb---genradix-free \
ksym-64kb---genradix-iter-peek \
ksym-64kb---genradix-iter-peek-prev \
ksym-64kb---genradix-prealloc \
ksym-64kb---genradix-ptr \
ksym-64kb---genradix-ptr-alloc \
ksym-64kb---get-random-u32-below \
ksym-64kb---init-rwsem \
ksym-64kb---init-swait-queue-head \
ksym-64kb---init-waitqueue-head \
ksym-64kb---kmalloc-cache-noprof \
ksym-64kb---kmalloc-noprof \
ksym-64kb---kmem-cache-create-args \
ksym-64kb---kvmalloc-node-noprof \
ksym-64kb---list-add-valid-or-report \
ksym-64kb---list-del-entry-valid-or-report \
ksym-64kb---module-get \
ksym-64kb---msecs-to-jiffies \
ksym-64kb---num-online-cpus \
ksym-64kb---num-possible-cpus \
ksym-64kb---per-cpu-offset \
ksym-64kb---percpu-down-read \
ksym-64kb---percpu-init-rwsem \
ksym-64kb---percpu-up-read \
ksym-64kb---posix-acl-chmod \
ksym-64kb---put-task-struct-rcu-cb \
ksym-64kb---rcu-read-lock \
ksym-64kb---rcu-read-unlock \
ksym-64kb---refrigerator \
ksym-64kb---register-chrdev \
ksym-64kb---rhashtable-init-noprof \
ksym-64kb---rhltable-init-noprof \
ksym-64kb---rht-bucket-nested \
ksym-64kb---seq-puts \
ksym-64kb---srcu-read-lock \
ksym-64kb---srcu-read-unlock \
ksym-64kb---stack-chk-fail \
ksym-64kb---sw-hweight32 \
ksym-64kb---sw-hweight64 \
ksym-64kb---trace-set-current-state \
ksym-64kb---trace-trigger-soft-disabled \
ksym-64kb---traceiter-contention-begin \
ksym-64kb---traceiter-contention-end \
ksym-64kb---tracepoint-contention-begin \
ksym-64kb---tracepoint-contention-end \
ksym-64kb---tracepoint-sched-set-state-tp \
ksym-64kb---unregister-chrdev \
ksym-64kb---vmalloc-noprof \
ksym-64kb---wake-up \
ksym-64kb---warn-printk \
ksym-64kb---zero-page \
ksym-64kb--find-first-bit \
ksym-64kb--find-next-andnot-bit \
ksym-64kb--find-next-bit \
ksym-64kb--find-next-zero-bit \
ksym-64kb--printk \
ksym-64kb--raw-spin-lock \
ksym-64kb--raw-spin-lock-irq \
ksym-64kb--raw-spin-lock-irqsave \
ksym-64kb--raw-spin-unlock \
ksym-64kb--raw-spin-unlock-irq \
ksym-64kb--raw-spin-unlock-irqrestore \
ksym-64kb--totalram-pages \
ksym-64kb-LZ4-compress-HC \
ksym-64kb-LZ4-compress-destSize \
ksym-64kb-LZ4-decompress-safe-partial \
ksym-64kb-alloc-workqueue-noprof \
ksym-64kb-alt-cb-patch-nops \
ksym-64kb-anon-inode-getfile \
ksym-64kb-arm64-use-ng-mappings \
ksym-64kb-balance-dirty-pages-ratelimited \
ksym-64kb-bdev-file-open-by-path \
ksym-64kb-bdev-fput \
ksym-64kb-bdev-freeze \
ksym-64kb-bdev-thaw \
ksym-64kb-bio-add-folio \
ksym-64kb-bio-add-folio-nofail \
ksym-64kb-bio-add-virt-nofail \
ksym-64kb-bio-add-vmalloc \
ksym-64kb-bio-alloc-bioset \
ksym-64kb-bio-alloc-clone \
ksym-64kb-bio-associate-blkg \
ksym-64kb-bio-chain \
ksym-64kb-bio-copy-data \
ksym-64kb-bio-endio \
ksym-64kb-bio-init \
ksym-64kb-bio-kmalloc \
ksym-64kb-bio-put \
ksym-64kb-bio-reset \
ksym-64kb-bio-split \
ksym-64kb-bioset-exit \
ksym-64kb-bioset-init \
ksym-64kb-bit-wait \
ksym-64kb-bit-wait-io \
ksym-64kb-blk-finish-plug \
ksym-64kb-blk-start-plug \
ksym-64kb-blkdev-issue-discard \
ksym-64kb-bpf-trace-run2 \
ksym-64kb-call-rcu \
ksym-64kb-call-srcu \
ksym-64kb-cancel-delayed-work \
ksym-64kb-cancel-delayed-work-sync \
ksym-64kb-cancel-work-sync \
ksym-64kb-capable \
ksym-64kb-chacha-crypt \
ksym-64kb-class-register \
ksym-64kb-class-unregister \
ksym-64kb-cleanup-srcu-struct \
ksym-64kb-clear-inode \
ksym-64kb-complete \
ksym-64kb-console-trylock \
ksym-64kb-console-unlock \
ksym-64kb-copy-folio-from-iter-atomic \
ksym-64kb-copy-from-user-nofault \
ksym-64kb-copy-to-user-nofault \
ksym-64kb-cpumask-local-spread \
ksym-64kb-crc32c \
ksym-64kb-crc64-be \
ksym-64kb-current-time \
ksym-64kb-d-instantiate \
ksym-64kb-d-invalidate \
ksym-64kb-d-make-root \
ksym-64kb-d-mark-dontcache \
ksym-64kb-d-mark-tmpfile \
ksym-64kb-d-obtain-alias \
ksym-64kb-d-parent-ino \
ksym-64kb-d-prune-aliases \
ksym-64kb-d-splice-alias \
ksym-64kb-deactivate-locked-super \
ksym-64kb-debugfs-create-dir \
ksym-64kb-debugfs-create-file-full \
ksym-64kb-debugfs-remove \
ksym-64kb-delayed-work-timer-fn \
ksym-64kb-destroy-workqueue \
ksym-64kb-device-create \
ksym-64kb-device-destroy \
ksym-64kb-device-unregister \
ksym-64kb-dget-parent \
ksym-64kb-discard-new-inode \
ksym-64kb-down-read \
ksym-64kb-down-read-trylock \
ksym-64kb-down-trylock \
ksym-64kb-down-write \
ksym-64kb-dput \
ksym-64kb-drain-workqueue \
ksym-64kb-dump-stack \
ksym-64kb-dynamic-cond-resched \
ksym-64kb-dynamic-might-resched \
ksym-64kb-dynamic-preempt-schedule \
ksym-64kb-dynamic-preempt-schedule-notrace \
ksym-64kb-end-creating-path \
ksym-64kb-errname \
ksym-64kb-errseq-set \
ksym-64kb-evict-inodes \
ksym-64kb-fault-in-iov-iter-readable \
ksym-64kb-fault-in-readable \
ksym-64kb-fault-in-writeable \
ksym-64kb-fd-install \
ksym-64kb-fiemap-fill-next-extent \
ksym-64kb-fiemap-prep \
ksym-64kb-file-bdev \
ksym-64kb-file-check-and-advance-wb-err \
ksym-64kb-file-modified \
ksym-64kb-file-remove-privs \
ksym-64kb-file-update-time \
ksym-64kb-file-write-and-wait-range \
ksym-64kb-fileattr-fill-xflags \
ksym-64kb-filemap-add-folio \
ksym-64kb-filemap-alloc-folio-noprof \
ksym-64kb-filemap-dirty-folio \
ksym-64kb-filemap-dontcache-kick-writeback \
ksym-64kb-filemap-fault \
ksym-64kb-filemap-get-folios \
ksym-64kb-filemap-map-pages \
ksym-64kb-filemap-migrate-folio \
ksym-64kb-filemap-read \
ksym-64kb-filemap-splice-read \
ksym-64kb-filemap-write-and-wait-range \
ksym-64kb-filp-open \
ksym-64kb-finish-open \
ksym-64kb-finish-wait \
ksym-64kb-flush-dcache-folio \
ksym-64kb-flush-dcache-page \
ksym-64kb-flush-work \
ksym-64kb-folio-end-read \
ksym-64kb-folio-end-writeback \
ksym-64kb-folio-mark-dirty \
ksym-64kb-folio-mkclean \
ksym-64kb-folio-unlock \
ksym-64kb-folio-wait-stable \
ksym-64kb-fput \
ksym-64kb-free-pages \
ksym-64kb-free-percpu \
ksym-64kb-freezer-active \
ksym-64kb-freezing-slow-path \
ksym-64kb-from-kgid \
ksym-64kb-from-kqid \
ksym-64kb-from-kuid \
ksym-64kb-from-vfsgid \
ksym-64kb-from-vfsuid \
ksym-64kb-fs-bio-set \
ksym-64kb-fs-kobj \
ksym-64kb-fsnotify \
ksym-64kb-generic-ci-d-compare \
ksym-64kb-generic-ci-d-hash \
ksym-64kb-generic-error-remove-folio \
ksym-64kb-generic-file-llseek \
ksym-64kb-generic-file-llseek-size \
ksym-64kb-generic-file-open \
ksym-64kb-generic-read-dir \
ksym-64kb-generic-remap-file-range-prep \
ksym-64kb-generic-shutdown-super \
ksym-64kb-generic-write-checks \
ksym-64kb-get-free-pages-noprof \
ksym-64kb-get-random-bytes \
ksym-64kb-get-random-u64 \
ksym-64kb-get-state-synchronize-rcu \
ksym-64kb-get-state-synchronize-srcu \
ksym-64kb-get-unused-fd-flags \
ksym-64kb-hex-asc \
ksym-64kb-hex2bin \
ksym-64kb-ida-alloc-range \
ksym-64kb-ida-destroy \
ksym-64kb-ida-find-first-range \
ksym-64kb-ida-free \
ksym-64kb-idr-alloc \
ksym-64kb-idr-find \
ksym-64kb-idr-remove \
ksym-64kb-igrab \
ksym-64kb-ihold \
ksym-64kb-import-ubuf \
ksym-64kb-in-group-or-capable \
ksym-64kb-init-special-inode \
ksym-64kb-init-srcu-struct \
ksym-64kb-init-user-ns \
ksym-64kb-init-wait-entry \
ksym-64kb-inode-bit-waitqueue \
ksym-64kb-inode-dio-wait \
ksym-64kb-inode-init-always-gfp \
ksym-64kb-inode-init-once \
ksym-64kb-inode-newsize-ok \
ksym-64kb-inode-nohighmem \
ksym-64kb-inode-owner-or-capable \
ksym-64kb-inode-permission \
ksym-64kb-inode-sb-list-add \
ksym-64kb-inode-set-ctime-to-ts \
ksym-64kb-invalidate-bdev \
ksym-64kb-invalidate-inode-pages2-range \
ksym-64kb-io-schedule-timeout \
ksym-64kb-iov-iter-advance \
ksym-64kb-iov-iter-extract-pages \
ksym-64kb-iov-iter-npages \
ksym-64kb-iov-iter-revert \
ksym-64kb-iov-iter-single-seg-count \
ksym-64kb-iput \
ksym-64kb-irq-work-queue \
ksym-64kb-is-bad-inode \
ksym-64kb-is-vmalloc-addr \
ksym-64kb-iter-file-splice-write \
ksym-64kb-jiffies \
ksym-64kb-kasprintf \
ksym-64kb-kernel-read \
ksym-64kb-key-put \
ksym-64kb-key-type-user \
ksym-64kb-kfree \
ksym-64kb-kmalloc-caches \
ksym-64kb-kmem-cache-alloc-lru-noprof \
ksym-64kb-kmem-cache-alloc-noprof \
ksym-64kb-kmem-cache-destroy \
ksym-64kb-kmem-cache-free \
ksym-64kb-kmem-cache-free-bulk \
ksym-64kb-kmemdup-noprof \
ksym-64kb-kobject-add \
ksym-64kb-kobject-del \
ksym-64kb-kobject-init \
ksym-64kb-kobject-put \
ksym-64kb-kobject-uevent-env \
ksym-64kb-krealloc-node-align-noprof \
ksym-64kb-kstrdup \
ksym-64kb-kstrtouint \
ksym-64kb-kstrtoull \
ksym-64kb-kthread-create-on-node \
ksym-64kb-kthread-should-stop \
ksym-64kb-kthread-stop \
ksym-64kb-kthread-unuse-mm \
ksym-64kb-kthread-use-mm \
ksym-64kb-ktime-get \
ksym-64kb-ktime-get-coarse-real-ts64 \
ksym-64kb-ktime-get-real-seconds \
ksym-64kb-ktime-get-with-offset \
ksym-64kb-kvfree \
ksym-64kb-kvfree-call-rcu \
ksym-64kb-kvrealloc-node-align-noprof \
ksym-64kb-llist-reverse-order \
ksym-64kb-lock-two-nondirectories \
ksym-64kb-lockref-get \
ksym-64kb-logfc \
ksym-64kb-lookup-bdev \
ksym-64kb-lookup-constant \
ksym-64kb-make-bad-inode \
ksym-64kb-make-kgid \
ksym-64kb-make-kprojid \
ksym-64kb-make-kuid \
ksym-64kb-make-vfsgid \
ksym-64kb-make-vfsuid \
ksym-64kb-match-string \
ksym-64kb-memchr \
ksym-64kb-memcmp \
ksym-64kb-memcpy \
ksym-64kb-memcpy-and-pad \
ksym-64kb-memmove \
ksym-64kb-mempool-alloc-noprof \
ksym-64kb-mempool-exit \
ksym-64kb-mempool-free \
ksym-64kb-mempool-init-noprof \
ksym-64kb-mempool-kfree \
ksym-64kb-mempool-kmalloc \
ksym-64kb-memscan \
ksym-64kb-memset \
ksym-64kb-migrate-disable \
ksym-64kb-migrate-enable \
ksym-64kb-mnt-drop-write \
ksym-64kb-mnt-drop-write-file \
ksym-64kb-mnt-want-write \
ksym-64kb-mnt-want-write-file \
ksym-64kb-mod-delayed-work-on \
ksym-64kb-module-layout \
ksym-64kb-module-put \
ksym-64kb-msleep \
ksym-64kb-mul-u64-add-u64-div-u64 \
ksym-64kb-mutex-init-generic \
ksym-64kb-mutex-lock \
ksym-64kb-mutex-trylock \
ksym-64kb-mutex-unlock \
ksym-64kb-nonseekable-open \
ksym-64kb-nop-posix-acl-access \
ksym-64kb-nop-posix-acl-default \
ksym-64kb-nr-cpu-ids \
ksym-64kb-nsecs-to-jiffies \
ksym-64kb-out-of-line-wait-on-bit \
ksym-64kb-out-of-line-wait-on-bit-lock \
ksym-64kb-out-of-line-wait-on-bit-timeout \
ksym-64kb-page-get-link \
ksym-64kb-page-symlink \
ksym-64kb-panic \
ksym-64kb-param-ops-bool \
ksym-64kb-param-ops-uint \
ksym-64kb-param-set-bool \
ksym-64kb-path-put \
ksym-64kb-pcpu-alloc-noprof \
ksym-64kb-percpu-down-write \
ksym-64kb-percpu-free-rwsem \
ksym-64kb-percpu-ref-exit \
ksym-64kb-percpu-ref-init \
ksym-64kb-percpu-ref-is-zero \
ksym-64kb-percpu-ref-kill-and-confirm \
ksym-64kb-percpu-ref-reinit \
ksym-64kb-percpu-up-write \
ksym-64kb-perf-trace-buf-alloc \
ksym-64kb-perf-trace-run-bpf-submit \
ksym-64kb-poll-state-synchronize-rcu \
ksym-64kb-poll-state-synchronize-srcu \
ksym-64kb-poly1305-final \
ksym-64kb-poly1305-init \
ksym-64kb-poly1305-update \
ksym-64kb-posix-acl-alloc \
ksym-64kb-posix-acl-create \
ksym-64kb-posix-acl-update-mode \
ksym-64kb-power-supply-is-system-supplied \
ksym-64kb-power-supply-reg-notifier \
ksym-64kb-power-supply-unreg-notifier \
ksym-64kb-prepare-to-wait \
ksym-64kb-prepare-to-wait-event \
ksym-64kb-put-unused-fd \
ksym-64kb-queue-delayed-work-on \
ksym-64kb-queue-work-on \
ksym-64kb-quota-send-warning \
ksym-64kb-raid6-gen-syndrome \
ksym-64kb-raid6-recov-2data \
ksym-64kb-raid6-recov-datap \
ksym-64kb-random-kmalloc-seed \
ksym-64kb-rcu-barrier \
ksym-64kb-refcount-warn-saturate \
ksym-64kb-register-filesystem \
ksym-64kb-request-key-tag \
ksym-64kb-rhashtable-destroy \
ksym-64kb-rhashtable-free-and-destroy \
ksym-64kb-rhashtable-insert-slow \
ksym-64kb-rht-bucket-nested \
ksym-64kb-rht-bucket-nested-insert \
ksym-64kb-rw-verify-area \
ksym-64kb-sched-clock \
ksym-64kb-schedule \
ksym-64kb-schedule-timeout \
ksym-64kb-scnprintf \
ksym-64kb-security-inode-init-security \
ksym-64kb-security-path-mkdir \
ksym-64kb-seq-buf-printf \
ksym-64kb-seq-printf \
ksym-64kb-seq-putc \
ksym-64kb-set-cached-acl \
ksym-64kb-set-freezable \
ksym-64kb-set-nlink \
ksym-64kb-set-normalized-timespec64 \
ksym-64kb-setattr-prepare \
ksym-64kb-sget-fc \
ksym-64kb-sha256 \
ksym-64kb-shrink-dcache-parent \
ksym-64kb-shrink-dcache-sb \
ksym-64kb-shrinker-alloc \
ksym-64kb-shrinker-free \
ksym-64kb-shrinker-register \
ksym-64kb-si-mem-available \
ksym-64kb-si-meminfo \
ksym-64kb-siphash-2u64 \
ksym-64kb-sized-strscpy \
ksym-64kb-snprintf \
ksym-64kb-sort \
ksym-64kb-sort-nonatomic \
ksym-64kb-sort-r \
ksym-64kb-sort-r-nonatomic \
ksym-64kb-sprintf \
ksym-64kb-srcu-barrier \
ksym-64kb-stack-trace-save-tsk \
ksym-64kb-start-creating-user-path \
ksym-64kb-start-poll-synchronize-rcu \
ksym-64kb-start-poll-synchronize-srcu \
ksym-64kb-start-removing-dentry \
ksym-64kb-static-key-count \
ksym-64kb-static-key-disable \
ksym-64kb-static-key-enable \
ksym-64kb-strchrnul \
ksym-64kb-strcmp \
ksym-64kb-strcspn \
ksym-64kb-strim \
ksym-64kb-strlen \
ksym-64kb-strncmp \
ksym-64kb-strncpy-from-user \
ksym-64kb-strndup-user \
ksym-64kb-strnlen \
ksym-64kb-strrchr \
ksym-64kb-strsep \
ksym-64kb-submit-bio \
ksym-64kb-submit-bio-wait \
ksym-64kb-super-setup-bdi \
ksym-64kb-sync-filesystem \
ksym-64kb-sync-inode-metadata \
ksym-64kb-sync-inodes-sb \
ksym-64kb-synchronize-rcu \
ksym-64kb-synchronize-srcu-expedited \
ksym-64kb-sysfs-create-bin-file \
ksym-64kb-sysfs-create-file-ns \
ksym-64kb-sysfs-create-link \
ksym-64kb-sysfs-remove-bin-file \
ksym-64kb-sysfs-remove-link \
ksym-64kb-system-dfl-wq \
ksym-64kb-system-highpri-wq \
ksym-64kb-system-long-wq \
ksym-64kb-system-percpu-wq \
ksym-64kb-thp-get-unmapped-area \
ksym-64kb-timer-init-key \
ksym-64kb-touch-atime \
ksym-64kb-trace-event-buffer-commit \
ksym-64kb-trace-event-buffer-reserve \
ksym-64kb-trace-event-printf \
ksym-64kb-trace-event-raw-init \
ksym-64kb-trace-event-reg \
ksym-64kb-trace-handle-return \
ksym-64kb-trace-raw-output-prep \
ksym-64kb-tracepoint-srcu \
ksym-64kb-truncate-inode-pages-final \
ksym-64kb-truncate-pagecache \
ksym-64kb-truncate-pagecache-range \
ksym-64kb-truncate-setsize \
ksym-64kb-try-module-get \
ksym-64kb-unlock-two-nondirectories \
ksym-64kb-unpin-user-folio \
ksym-64kb-unpin-user-page \
ksym-64kb-unregister-filesystem \
ksym-64kb-up \
ksym-64kb-up-read \
ksym-64kb-up-write \
ksym-64kb-user-path-at \
ksym-64kb-utf8-casefold \
ksym-64kb-utf8-load \
ksym-64kb-utf8-unload \
ksym-64kb-validate-usercopy-range \
ksym-64kb-vfs-fsync-range \
ksym-64kb-vfs-setpos \
ksym-64kb-vmalloc-noprof \
ksym-64kb-vmap \
ksym-64kb-vprintk \
ksym-64kb-vsnprintf \
ksym-64kb-vunmap \
ksym-64kb-wait-for-completion \
ksym-64kb-wait-for-completion-timeout \
ksym-64kb-wake-up-bit \
ksym-64kb-wake-up-process \
ksym-64kb-wake-up-var \
ksym-64kb-work-busy \
ksym-64kb-write-inode-now \
ksym-64kb-writeback-iter \
ksym-64kb-xa-load \
ksym-64kb-xor-gen \
ksym-64kb-xxh64-digest \
ksym-64kb-xxh64-reset \
ksym-64kb-xxh64-update \
ksym-64kb-zlib-deflate \
ksym-64kb-zlib-deflate-workspacesize \
ksym-64kb-zlib-deflateEnd \
ksym-64kb-zlib-deflateInit2 \
ksym-64kb-zlib-inflate \
ksym-64kb-zlib-inflate-workspacesize \
ksym-64kb-zlib-inflateInit2 \
ksym-64kb-zstd-cctx-workspace-bound \
ksym-64kb-zstd-compress-cctx \
ksym-64kb-zstd-dctx-workspace-bound \
ksym-64kb-zstd-decompress-dctx \
ksym-64kb-zstd-get-error-code \
ksym-64kb-zstd-get-params \
ksym-64kb-zstd-init-cctx \
ksym-64kb-zstd-init-dctx \
ksym-64kb-zstd-is-error \
ksym-64kb-zstd-max-clevel \
suse-kernel-rpm-scriptlets"

inherit rpm
