SUMMARY = "DSP infinite impulse response realtime C++ filter library"
DESCRIPTION = " \
An infinite impulse response (IIR) filter library for Linux, Mac OSX and Windows \
which implements Butterworth, RBJ, Chebychev filters and can easily import coefficients generated by Python (scipy). \
The filter processes the data sample by sample for realtime processing. \
It uses templates to allocate the required memory so that it can run without any malloc / new commands. \
Memory is allocated at compile time so that there is never the risk of memory leaks. \
All realtime filter code is in the header files which guarantees efficient integration into the main program \
and the compiler can optimise both filter code and main program at the same time."
LICENSE = "MIT"

PV = "1.10.0"

RPM_NAME = "libiir-devel-1.10.0-1.5.aarch64.rpm"
RPM_HASH = "89f842905d3750715a1b2b768e8868ac17fc933bded20eaf6bb025dec9bd6c24e43773232c0bb959b5a3ba95eef72115056ed8080ed6d1c0c4b83fb311d87007"

RPROVIDES:${PN} += "cmake-iir \
libiir-devel \
pkgconfig-iir"

RDEPENDS:${PN} += "/usr/bin/pkg-config \
libiir1"

inherit rpm
