SUMMARY = "Verify provenance from SLSA compliant builders"
DESCRIPTION = "slsa-verifier is a tool for verifying SLSA provenance that was generated by \
CI/CD builders. slsa-verifier verifies the provenance by verifying the \
cryptographic signatures on provenance to make sure it was created by the \
expected builder. It then verifies that various values such as the builder id, \
source code repository, ref (branch or tag) matches the expected values."
LICENSE = "Apache-2.0"

PV = "2.7.1"

RPM_NAME = "slsa-verifier-2.7.1-1.8.aarch64.rpm"
RPM_HASH = "acfb31849e4771960167577543974ef8780a1f758a8ba8da6c96666b95470d6f26b1d23041bd4a7002586c196f12875f3cf8031dff56803a1ba862972d8cefb4"

RPROVIDES:${PN} += "slsa-verifier"

RDEPENDS:${PN} += "libc.so.6"

inherit rpm
