SUMMARY = "Generate random mazes"
DESCRIPTION = "This package can generate random square mazes of a specified \
size. The mazes generated by this package are natural and their \
solution is not too obvious. The output it based on the picture \
environment."
LICENSE = "LPPL-1.0"

PV = "2026.226.1.2svn76924"

RPM_NAME = "texlive-maze-2026.226.1.2svn76924-59.2.noarch.rpm"
RPM_HASH = "395b1cd0ae7d4f08dee1fe0f5f1717053276986e18f98d6674e57907347d829b772b5bcdbff01170ad6538dfc207a0d404ae7e1fa645e7352ebbf2c5de67f31d"
REPO_ARCH = "noarch"

RPROVIDES:${PN} += "tex-maze.sty \
texlive-maze"

RDEPENDS:${PN} += "/usr/bin/sh \
coreutils \
ed \
findutils \
grep \
sed \
texlive \
texlive-filesystem \
texlive-kpathsea \
texlive-kpathsea-bin \
texlive-scripts \
texlive-scripts-bin"

inherit rpm
