SUMMARY = "Launch jobs, organize the output, and dissect the results"
DESCRIPTION = "Lancet is designed to help you organize the output of your research \
tools, store it, and dissect the data you have collected. The output \
of a single simulation or analysis rarely contains all the data you \
need; Lancet helps you generate data from many runs and analyse it \
using your own Python code. \
 \
Parameter spaces often need to be explored for the purpose of \
plotting, tuning, or analysis. Lancet helps you extract the \
information you care about from potentially enormous volumes of data \
generated by such parameter exploration."
LICENSE = "BSD-3-Clause"

PV = "0.9.0"

RPM_NAME = "python314-lancet-ioam-0.9.0-3.5.noarch.rpm"
RPM_HASH = "d4eb0b68d10c9276de8063136bede6173c7d406c3100f4304fcfacb019b3ef80596214e3c3b454a0d1cdb83651e4e16c159b6dc303b59a2555988cc1d1bb82e8"
REPO_ARCH = "noarch"

RPROVIDES:${PN} += "python3.14dist-lancet-ioam \
python314-lancet-ioam \
python3dist-lancet-ioam"

RDEPENDS:${PN} += "python-abi"

inherit rpm
