SUMMARY = "All Noto Fonts except CJK and Emoji"
DESCRIPTION = "Noto's design goal is to achieve visual harmonization (e.g., compatible heights and stroke \
thicknesses) across languages. This package contains most noto fonts except for CJK and Emoji."
LICENSE = "OFL-1.1"

PV = "20260901"

RPM_NAME = "google-noto-fonts-20260901-1.1.noarch.rpm"
RPM_HASH = "10e4a840be54fb0dbf5f441ed4ee4a128031dd7e9432c61b629d0eb3329f62a658b01c454ccc9ad025255eaa38a9877179312169637f08d5b31f98c4978b984a"
REPO_ARCH = "noarch"

RPROVIDES:${PN} += "google-noto-fonts \
noto-fonts"

RDEPENDS:${PN} += "google-noto-fangsongkssrotated-fonts \
google-noto-fangsongkssvertical-fonts \
google-noto-kufiarabic-fonts \
google-noto-music-fonts \
google-noto-naskharabic-fonts \
google-noto-nastaliqurdu-fonts \
google-noto-rashihebrew-fonts \
google-noto-sans-adlam-fonts \
google-noto-sans-adlamunjoined-fonts \
google-noto-sans-anatolianhieroglyphs-fonts \
google-noto-sans-arabic-fonts \
google-noto-sans-armenian-fonts \
google-noto-sans-avestan-fonts \
google-noto-sans-balinese-fonts \
google-noto-sans-bamum-fonts \
google-noto-sans-bassavah-fonts \
google-noto-sans-batak-fonts \
google-noto-sans-bengali-fonts \
google-noto-sans-bhaiksuki-fonts \
google-noto-sans-brahmi-fonts \
google-noto-sans-buginese-fonts \
google-noto-sans-buhid-fonts \
google-noto-sans-canadianaboriginal-fonts \
google-noto-sans-carian-fonts \
google-noto-sans-caucasianalbanian-fonts \
google-noto-sans-chakma-fonts \
google-noto-sans-cham-fonts \
google-noto-sans-cherokee-fonts \
google-noto-sans-chorasmian-fonts \
google-noto-sans-coptic-fonts \
google-noto-sans-cuneiform-fonts \
google-noto-sans-cypriot-fonts \
google-noto-sans-cyprominoan-fonts \
google-noto-sans-deseret-fonts \
google-noto-sans-devanagari-fonts \
google-noto-sans-duployan-fonts \
google-noto-sans-egyptianhieroglyphs-fonts \
google-noto-sans-elbasan-fonts \
google-noto-sans-elymaic-fonts \
google-noto-sans-ethiopic-fonts \
google-noto-sans-fonts \
google-noto-sans-georgian-fonts \
google-noto-sans-glagolitic-fonts \
google-noto-sans-gothic-fonts \
google-noto-sans-grantha-fonts \
google-noto-sans-gujarati-fonts \
google-noto-sans-gunjalagondi-fonts \
google-noto-sans-gurmukhi-fonts \
google-noto-sans-hanifirohingya-fonts \
google-noto-sans-hanunoo-fonts \
google-noto-sans-hatran-fonts \
google-noto-sans-hebrew-fonts \
google-noto-sans-imperialaramaic-fonts \
google-noto-sans-indicsiyaqnumbers-fonts \
google-noto-sans-inscriptionalpahlavi-fonts \
google-noto-sans-inscriptionalparthian-fonts \
google-noto-sans-javanese-fonts \
google-noto-sans-kaithi-fonts \
google-noto-sans-kannada-fonts \
google-noto-sans-kawi-fonts \
google-noto-sans-kayahli-fonts \
google-noto-sans-kharoshthi-fonts \
google-noto-sans-khmer-fonts \
google-noto-sans-khojki-fonts \
google-noto-sans-khudawadi-fonts \
google-noto-sans-lao-fonts \
google-noto-sans-laolooped-fonts \
google-noto-sans-lepcha-fonts \
google-noto-sans-limbu-fonts \
google-noto-sans-lineara-fonts \
google-noto-sans-linearb-fonts \
google-noto-sans-lisu-fonts \
google-noto-sans-lycian-fonts \
google-noto-sans-lydian-fonts \
google-noto-sans-mahajani-fonts \
google-noto-sans-malayalam-fonts \
google-noto-sans-mandaic-fonts \
google-noto-sans-manichaean-fonts \
google-noto-sans-marchen-fonts \
google-noto-sans-masaramgondi-fonts \
google-noto-sans-math-fonts \
google-noto-sans-mayannumerals-fonts \
google-noto-sans-medefaidrin-fonts \
google-noto-sans-meeteimayek-fonts \
google-noto-sans-mendekikakui-fonts \
google-noto-sans-meroitic-fonts \
google-noto-sans-miao-fonts \
google-noto-sans-modi-fonts \
google-noto-sans-mongolian-fonts \
google-noto-sans-mono-fonts \
google-noto-sans-mro-fonts \
google-noto-sans-multani-fonts \
google-noto-sans-myanmar-fonts \
google-noto-sans-nabataean-fonts \
google-noto-sans-nagmundari-fonts \
google-noto-sans-nandinagari-fonts \
google-noto-sans-newa-fonts \
google-noto-sans-newtailue-fonts \
google-noto-sans-nko-fonts \
google-noto-sans-nkounjoined-fonts \
google-noto-sans-nushu-fonts \
google-noto-sans-ogham-fonts \
google-noto-sans-olchiki-fonts \
google-noto-sans-oldhungarian-fonts \
google-noto-sans-olditalic-fonts \
google-noto-sans-oldnortharabian-fonts \
google-noto-sans-oldpermic-fonts \
google-noto-sans-oldpersian-fonts \
google-noto-sans-oldsogdian-fonts \
google-noto-sans-oldsoutharabian-fonts \
google-noto-sans-oldturkic-fonts \
google-noto-sans-oriya-fonts \
google-noto-sans-osage-fonts \
google-noto-sans-osmanya-fonts \
google-noto-sans-pahawhhmong-fonts \
google-noto-sans-palmyrene-fonts \
google-noto-sans-paucinhau-fonts \
google-noto-sans-phagspa-fonts \
google-noto-sans-phoenician-fonts \
google-noto-sans-psalterpahlavi-fonts \
google-noto-sans-rejang-fonts \
google-noto-sans-runic-fonts \
google-noto-sans-samaritan-fonts \
google-noto-sans-saurashtra-fonts \
google-noto-sans-sharada-fonts \
google-noto-sans-shavian-fonts \
google-noto-sans-siddham-fonts \
google-noto-sans-signwriting-fonts \
google-noto-sans-sinhala-fonts \
google-noto-sans-sogdian-fonts \
google-noto-sans-sorasompeng-fonts \
google-noto-sans-soyombo-fonts \
google-noto-sans-sundanese-fonts \
google-noto-sans-sunuwar-fonts \
google-noto-sans-sylotinagri-fonts \
google-noto-sans-symbols-fonts \
google-noto-sans-symbols2-fonts \
google-noto-sans-syriac-fonts \
google-noto-sans-syriaceastern-fonts \
google-noto-sans-syriacwestern-fonts \
google-noto-sans-tagalog-fonts \
google-noto-sans-tagbanwa-fonts \
google-noto-sans-taile-fonts \
google-noto-sans-taitham-fonts \
google-noto-sans-taiviet-fonts \
google-noto-sans-takri-fonts \
google-noto-sans-tamil-fonts \
google-noto-sans-tamilsupplement-fonts \
google-noto-sans-tangsa-fonts \
google-noto-sans-telugu-fonts \
google-noto-sans-thaana-fonts \
google-noto-sans-thai-fonts \
google-noto-sans-thailooped-fonts \
google-noto-sans-tifinagh-fonts \
google-noto-sans-tirhuta-fonts \
google-noto-sans-ugaritic-fonts \
google-noto-sans-vai-fonts \
google-noto-sans-vithkuqi-fonts \
google-noto-sans-wancho-fonts \
google-noto-sans-warangciti-fonts \
google-noto-sans-yi-fonts \
google-noto-sans-zanabazarsquare-fonts \
google-noto-serif-ahom-fonts \
google-noto-serif-armenian-fonts \
google-noto-serif-balinese-fonts \
google-noto-serif-bengali-fonts \
google-noto-serif-devanagari-fonts \
google-noto-serif-display-fonts \
google-noto-serif-divesakuru-fonts \
google-noto-serif-dogra-fonts \
google-noto-serif-ethiopic-fonts \
google-noto-serif-fonts \
google-noto-serif-georgian-fonts \
google-noto-serif-grantha-fonts \
google-noto-serif-gujarati-fonts \
google-noto-serif-gurmukhi-fonts \
google-noto-serif-hebrew-fonts \
google-noto-serif-hentaigana-fonts \
google-noto-serif-kannada-fonts \
google-noto-serif-khitansmallscript-fonts \
google-noto-serif-khmer-fonts \
google-noto-serif-khojki-fonts \
google-noto-serif-lao-fonts \
google-noto-serif-makasar-fonts \
google-noto-serif-malayalam-fonts \
google-noto-serif-myanmar-fonts \
google-noto-serif-nphmong-fonts \
google-noto-serif-olduyghur-fonts \
google-noto-serif-oriya-fonts \
google-noto-serif-ottomansiyaq-fonts \
google-noto-serif-sinhala-fonts \
google-noto-serif-tamil-fonts \
google-noto-serif-tangut-fonts \
google-noto-serif-telugu-fonts \
google-noto-serif-thai-fonts \
google-noto-serif-tibetan-fonts \
google-noto-serif-todhri-fonts \
google-noto-serif-toto-fonts \
google-noto-serif-vithkuqi-fonts \
google-noto-serif-yezidi-fonts \
google-noto-traditionalnushu-fonts \
google-noto-znamennymusicalnotation-fonts"

inherit rpm
