SUMMARY = "A documentation generator for GObject-based libraries"
DESCRIPTION = "GI-DocGen is a document generator for GObject-based libraries. \
GObject is the base type system of the GNOME project. GI-Docgen \
reuses the introspection data generated by GObject-based libraries \
to generate the API reference of these libraries, as well as other \
ancillary documentation."
LICENSE = "(Apache-2.0 | GPL-3.0-or-later) & CC0-1.0 & MIT & OFL-1.1"

PV = "2026.1"

RPM_NAME = "gi-docgen-2026.1-1.1.noarch.rpm"
RPM_HASH = "516a000f68d4ce140ab4af9832a5e89c9220f686b1f3721e3844f330af3d941eac8437e3bb0ff473e606c8ad25be35cee20b62b25e090aff5e321316b6d530e9"
REPO_ARCH = "noarch"

RPROVIDES:${PN} += "gi-docgen \
pkgconfig-gi-docgen \
python3-gi-docgen \
python3.13dist-gi-docgen \
python3dist-gi-docgen"

RDEPENDS:${PN} += "/usr/bin/pkg-config \
/usr/bin/python3.13 \
python-abi \
python3-Jinja2 \
python3-Markdown \
python3-MarkupSafe \
python3-Pygments \
python3-base \
python3-packaging \
python3-typogrify"

inherit rpm
