SUMMARY = "Perl 5 bindings for the libdnf library"
DESCRIPTION = "Perl 5 bindings for the libdnf library."
LICENSE = "LGPL-2.1-or-later"

PV = "5.4.2.1"

RPM_NAME = "perl-libdnf5-5.4.2.1-1.3.aarch64.rpm"
RPM_HASH = "ab4290190b61c067573aad8a5ac8a5409bdf227b0164b1c34314b8e5bc2ae5744d46629bf444681dcf0f667549d58a45fba013a9a67eb846f046873159857c41"

RPROVIDES:${PN} += "perl-libdnf5 \
perl-libdnf5--advisory \
perl-libdnf5--advisory--Advisory \
perl-libdnf5--advisory--AdvisoryCollection \
perl-libdnf5--advisory--AdvisoryId \
perl-libdnf5--advisory--AdvisoryModule \
perl-libdnf5--advisory--AdvisoryPackage \
perl-libdnf5--advisory--AdvisoryQuery \
perl-libdnf5--advisory--AdvisoryReference \
perl-libdnf5--advisory--AdvisorySet \
perl-libdnf5--advisory--AdvisorySetIterator \
perl-libdnf5--advisory--VectorAdvisoryCollection \
perl-libdnf5--advisory--VectorAdvisoryModule \
perl-libdnf5--advisory--VectorAdvisoryPackage \
perl-libdnf5--advisory--VectorAdvisoryReference \
perl-libdnf5--advisoryc \
perl-libdnf5--base \
perl-libdnf5--base--ActiveTransactionInfo \
perl-libdnf5--base--Base \
perl-libdnf5--base--BaseWeakPtr \
perl-libdnf5--base--Goal \
perl-libdnf5--base--GoalJobSettings \
perl-libdnf5--base--LogEvent \
perl-libdnf5--base--ResolveSpecSettings \
perl-libdnf5--base--SolverProblems \
perl-libdnf5--base--Transaction \
perl-libdnf5--base--TransactionEnvironment \
perl-libdnf5--base--TransactionGroup \
perl-libdnf5--base--TransactionPackage \
perl-libdnf5--base--VarsWeakPtr \
perl-libdnf5--base--VectorBaseTransactionEnvironment \
perl-libdnf5--base--VectorBaseTransactionGroup \
perl-libdnf5--base--VectorBaseTransactionPackage \
perl-libdnf5--base--VectorLogEvent \
perl-libdnf5--base--VectorPluginInfo \
perl-libdnf5--basec \
perl-libdnf5--common \
perl-libdnf5--common--EmptyMessage \
perl-libdnf5--common--MapStringMapStringString \
perl-libdnf5--common--MapStringPairStringString \
perl-libdnf5--common--MapStringString \
perl-libdnf5--common--Message \
perl-libdnf5--common--PairStringString \
perl-libdnf5--common--PreserveOrderMapStringPreserveOrderMapStringString \
perl-libdnf5--common--PreserveOrderMapStringString \
perl-libdnf5--common--VectorPairStringString \
perl-libdnf5--common--VectorString \
perl-libdnf5--commonc \
perl-libdnf5--comps \
perl-libdnf5--comps--CompsSack \
perl-libdnf5--comps--CompsSackWeakPtr \
perl-libdnf5--comps--Environment \
perl-libdnf5--comps--EnvironmentId \
perl-libdnf5--comps--EnvironmentQuery \
perl-libdnf5--comps--Group \
perl-libdnf5--comps--GroupId \
perl-libdnf5--comps--GroupQuery \
perl-libdnf5--comps--Package \
perl-libdnf5--comps--SackQueryEnvironment \
perl-libdnf5--comps--SackQueryGroup \
perl-libdnf5--comps--SetConstIteratorEnvironment \
perl-libdnf5--comps--SetConstIteratorGroup \
perl-libdnf5--comps--SetEnvironment \
perl-libdnf5--comps--SetGroup \
perl-libdnf5--comps--VectorPackage \
perl-libdnf5--compsc \
perl-libdnf5--conf \
perl-libdnf5--conf--Config \
perl-libdnf5--conf--ConfigMain \
perl-libdnf5--conf--ConfigParser \
perl-libdnf5--conf--Item \
perl-libdnf5--conf--LibraryVersion \
perl-libdnf5--conf--Option \
perl-libdnf5--conf--OptionBinds \
perl-libdnf5--conf--OptionBindsIterator \
perl-libdnf5--conf--OptionBool \
perl-libdnf5--conf--OptionChildBool \
perl-libdnf5--conf--OptionChildEnum \
perl-libdnf5--conf--OptionChildNumberFloat \
perl-libdnf5--conf--OptionChildNumberInt32 \
perl-libdnf5--conf--OptionChildNumberUInt32 \
perl-libdnf5--conf--OptionChildSeconds \
perl-libdnf5--conf--OptionChildString \
perl-libdnf5--conf--OptionChildStringAppendList \
perl-libdnf5--conf--OptionChildStringAppendSet \
perl-libdnf5--conf--OptionChildStringList \
perl-libdnf5--conf--OptionChildStringSet \
perl-libdnf5--conf--OptionEnum \
perl-libdnf5--conf--OptionNumberFloat \
perl-libdnf5--conf--OptionNumberInt32 \
perl-libdnf5--conf--OptionNumberInt64 \
perl-libdnf5--conf--OptionNumberUInt32 \
perl-libdnf5--conf--OptionNumberUInt64 \
perl-libdnf5--conf--OptionPath \
perl-libdnf5--conf--OptionSeconds \
perl-libdnf5--conf--OptionString \
perl-libdnf5--conf--OptionStringAppendList \
perl-libdnf5--conf--OptionStringAppendSet \
perl-libdnf5--conf--OptionStringList \
perl-libdnf5--conf--OptionStringSet \
perl-libdnf5--conf--PairConstStringItemPtr \
perl-libdnf5--conf--PluginAPIVersion \
perl-libdnf5--conf--StringUniquePtr \
perl-libdnf5--conf--Variable \
perl-libdnf5--conf--Vars \
perl-libdnf5--confc \
perl-libdnf5--exception \
perl-libdnf5--exception--AssertionError \
perl-libdnf5--exception--AssertionErrorNested \
perl-libdnf5--exception--BaseActiveTransactionInfoParseError \
perl-libdnf5--exception--BaseActiveTransactionInfoParseErrorNested \
perl-libdnf5--exception--BaseTransactionError \
perl-libdnf5--exception--BaseTransactionErrorNested \
perl-libdnf5--exception--CompsInvalidPackageType \
perl-libdnf5--exception--CompsInvalidPackageTypeNested \
perl-libdnf5--exception--ConfigParserError \
perl-libdnf5--exception--ConfigParserErrorNested \
perl-libdnf5--exception--ConfigParserOptionNotFoundError \
perl-libdnf5--exception--ConfigParserOptionNotFoundErrorNested \
perl-libdnf5--exception--ConfigParserSectionNotFoundError \
perl-libdnf5--exception--ConfigParserSectionNotFoundErrorNested \
perl-libdnf5--exception--Error \
perl-libdnf5--exception--ErrorNested \
perl-libdnf5--exception--FileSystemError \
perl-libdnf5--exception--FileSystemErrorNested \
perl-libdnf5--exception--InaccessibleConfigError \
perl-libdnf5--exception--InaccessibleConfigErrorNested \
perl-libdnf5--exception--InvalidConfigError \
perl-libdnf5--exception--InvalidConfigErrorNested \
perl-libdnf5--exception--MissingConfigError \
perl-libdnf5--exception--MissingConfigErrorNested \
perl-libdnf5--exception--NonLibdnf5Exception \
perl-libdnf5--exception--NonLibdnf5ExceptionNested \
perl-libdnf5--exception--OptionBindsError \
perl-libdnf5--exception--OptionBindsErrorNested \
perl-libdnf5--exception--OptionBindsOptionAlreadyExistsError \
perl-libdnf5--exception--OptionBindsOptionAlreadyExistsErrorNested \
perl-libdnf5--exception--OptionBindsOptionNotFoundError \
perl-libdnf5--exception--OptionBindsOptionNotFoundErrorNested \
perl-libdnf5--exception--OptionError \
perl-libdnf5--exception--OptionErrorNested \
perl-libdnf5--exception--OptionInvalidValueError \
perl-libdnf5--exception--OptionInvalidValueErrorNested \
perl-libdnf5--exception--OptionPathNotFoundError \
perl-libdnf5--exception--OptionValueNotAllowedError \
perl-libdnf5--exception--OptionValueNotAllowedErrorNested \
perl-libdnf5--exception--OptionValueNotSetError \
perl-libdnf5--exception--OptionValueNotSetErrorNested \
perl-libdnf5--exception--ReadOnlyVariableError \
perl-libdnf5--exception--ReadOnlyVariableErrorNested \
perl-libdnf5--exception--RepoCacheError \
perl-libdnf5--exception--RepoCacheErrorNested \
perl-libdnf5--exception--RepoCacheonlyError \
perl-libdnf5--exception--RepoCacheonlyErrorNested \
perl-libdnf5--exception--RepoCompsError \
perl-libdnf5--exception--RepoCompsErrorNested \
perl-libdnf5--exception--RepoDownloadError \
perl-libdnf5--exception--RepoDownloadErrorNested \
perl-libdnf5--exception--RepoError \
perl-libdnf5--exception--RepoErrorNested \
perl-libdnf5--exception--RepoFileDownloadError \
perl-libdnf5--exception--RepoFileDownloadErrorNested \
perl-libdnf5--exception--RepoIdAlreadyExistsError \
perl-libdnf5--exception--RepoIdAlreadyExistsErrorNested \
perl-libdnf5--exception--RepoPackageDownloadError \
perl-libdnf5--exception--RepoPackageDownloadErrorNested \
perl-libdnf5--exception--RepoPgpError \
perl-libdnf5--exception--RepoPgpErrorNested \
perl-libdnf5--exception--RepoRpmError \
perl-libdnf5--exception--RepoRpmErrorNested \
perl-libdnf5--exception--RpmKeyImportError \
perl-libdnf5--exception--RpmKeyImportErrorNested \
perl-libdnf5--exception--RpmNevraIncorrectInputError \
perl-libdnf5--exception--RpmNevraIncorrectInputErrorNested \
perl-libdnf5--exception--RpmSignatureCheckError \
perl-libdnf5--exception--RpmSignatureCheckErrorNested \
perl-libdnf5--exception--RuntimeError \
perl-libdnf5--exception--RuntimeErrorNested \
perl-libdnf5--exception--SystemError \
perl-libdnf5--exception--SystemErrorNested \
perl-libdnf5--exception--TransactionInvalidTransactionItemAction \
perl-libdnf5--exception--TransactionInvalidTransactionItemActionNested \
perl-libdnf5--exception--TransactionInvalidTransactionItemReason \
perl-libdnf5--exception--TransactionInvalidTransactionItemReasonNested \
perl-libdnf5--exception--TransactionInvalidTransactionItemState \
perl-libdnf5--exception--TransactionInvalidTransactionItemStateNested \
perl-libdnf5--exception--TransactionInvalidTransactionItemType \
perl-libdnf5--exception--TransactionInvalidTransactionItemTypeNested \
perl-libdnf5--exception--TransactionInvalidTransactionState \
perl-libdnf5--exception--TransactionInvalidTransactionStateNested \
perl-libdnf5--exception--UserAssertionError \
perl-libdnf5--exception--UserAssertionErrorNested \
perl-libdnf5--exceptionc \
perl-libdnf5--logger \
perl-libdnf5--logger--GlobalLogger \
perl-libdnf5--logger--LogRouter \
perl-libdnf5--logger--LogRouterWeakPtr \
perl-libdnf5--logger--Logger \
perl-libdnf5--logger--LoggerUniquePtr \
perl-libdnf5--logger--MemoryBufferLogger \
perl-libdnf5--logger--MemoryBufferLoggerUniquePtr \
perl-libdnf5--logger--RotatingFileLogger \
perl-libdnf5--logger--StringLogger \
perl-libdnf5--loggerc \
perl-libdnf5--plugin \
perl-libdnf5--plugin--IPlugin \
perl-libdnf5--plugin--IPlugin2-1 \
perl-libdnf5--plugin--PluginInfo \
perl-libdnf5--plugin--Version \
perl-libdnf5--pluginc \
perl-libdnf5--repo \
perl-libdnf5--repo--ConfigRepo \
perl-libdnf5--repo--DownloadCallbacks \
perl-libdnf5--repo--DownloadCallbacksUniquePtr \
perl-libdnf5--repo--FileDownloader \
perl-libdnf5--repo--PackageDownloader \
perl-libdnf5--repo--Repo \
perl-libdnf5--repo--RepoCache \
perl-libdnf5--repo--RepoCacheRemoveStatistics \
perl-libdnf5--repo--RepoCallbacks \
perl-libdnf5--repo--RepoCallbacks2-1 \
perl-libdnf5--repo--RepoCallbacksUniquePtr \
perl-libdnf5--repo--RepoQuery \
perl-libdnf5--repo--RepoSack \
perl-libdnf5--repo--RepoSackWeakPtr \
perl-libdnf5--repo--RepoWeakPtr \
perl-libdnf5--repo--SackQueryRepoWeakPtr \
perl-libdnf5--repo--SackRepoRepoQuery \
perl-libdnf5--repo--SetConstIteratorRepoWeakPtr \
perl-libdnf5--repo--SetRepoWeakPtr \
perl-libdnf5--repoc \
perl-libdnf5--rpm \
perl-libdnf5--rpm--Changelog \
perl-libdnf5--rpm--Checksum \
perl-libdnf5--rpm--KeyInfo \
perl-libdnf5--rpm--Nevra \
perl-libdnf5--rpm--Package \
perl-libdnf5--rpm--PackageId \
perl-libdnf5--rpm--PackageQuery \
perl-libdnf5--rpm--PackageSack \
perl-libdnf5--rpm--PackageSackWeakPtr \
perl-libdnf5--rpm--PackageSet \
perl-libdnf5--rpm--PackageSetIterator \
perl-libdnf5--rpm--PairBoolNevra \
perl-libdnf5--rpm--Reldep \
perl-libdnf5--rpm--ReldepId \
perl-libdnf5--rpm--ReldepList \
perl-libdnf5--rpm--ReldepListIterator \
perl-libdnf5--rpm--RpmSignature \
perl-libdnf5--rpm--TransactionCallbacks \
perl-libdnf5--rpm--TransactionCallbacksUniquePtr \
perl-libdnf5--rpm--VectorChangelog \
perl-libdnf5--rpm--VectorKeyInfo \
perl-libdnf5--rpm--VectorNevra \
perl-libdnf5--rpm--VectorNevraForm \
perl-libdnf5--rpm--VectorPackage \
perl-libdnf5--rpm--VectorVectorPackage \
perl-libdnf5--rpm--VectorVersionlockCondition \
perl-libdnf5--rpm--VectorVersionlockPackage \
perl-libdnf5--rpm--VersionlockCondition \
perl-libdnf5--rpm--VersionlockConfig \
perl-libdnf5--rpm--VersionlockPackage \
perl-libdnf5--rpmc \
perl-libdnf5--transaction \
perl-libdnf5--transaction--CompsEnvironment \
perl-libdnf5--transaction--CompsEnvironmentGroup \
perl-libdnf5--transaction--CompsGroup \
perl-libdnf5--transaction--CompsGroupPackage \
perl-libdnf5--transaction--Package \
perl-libdnf5--transaction--Transaction \
perl-libdnf5--transaction--TransactionHistory \
perl-libdnf5--transaction--TransactionHistoryWeakPtr \
perl-libdnf5--transaction--TransactionItem \
perl-libdnf5--transaction--VectorTransaction \
perl-libdnf5--transaction--VectorTransactionPackage \
perl-libdnf5--transactionc \
perl-libdnf5--utils \
perl-libdnf5--utils--Locale \
perl-libdnf5--utils--Locker \
perl-libdnf5--utilsc"

RDEPENDS:${PN} += "ld-linux-aarch64.so.1 \
libc.so.6 \
libdnf5-2 \
libdnf5.so.2 \
libfmt.so.12 \
libgcc-s.so.1 \
libperl.so \
libstdc++.so.6"

inherit rpm
