SUMMARY = "leancrypto Kernel Module Package"
LICENSE = "BSD-3-Clause | GPL-2.0-only"

PV = "1.8.0_k7.2.4_1"

RPM_NAME = "leancrypto-kmp-default-1.8.0_k7.2.4_1-3.4.aarch64.rpm"
RPM_HASH = "113b8fd1a78a28eb18640a85e605cefda1fb8af6218eb78f9c8023feb48615405307f21653498240acb995b1e477c1e897ea1d44e25a3fd30023ddd851eccd6b"

RPROVIDES:${PN} += "kmod-aes-cbc-dec-tester.ko \
kmod-aes-cbc-enc-tester.ko \
kmod-aes-ctr-tester.ko \
kmod-aes-dec-tester.ko \
kmod-aes-enc-tester.ko \
kmod-aes-gcm-tester.ko \
kmod-aes-kw-tester.ko \
kmod-aes-xts-tester.ko \
kmod-ascon-256-tester.ko \
kmod-ascon-crypt-test.ko \
kmod-ascon-keccak-crypt-iuf-test.ko \
kmod-ascon-keccak-crypt-test.ko \
kmod-ascon-xof-tester.ko \
kmod-bike-1-tester.ko \
kmod-bike-3-tester.ko \
kmod-bike-5-tester.ko \
kmod-chacha20-block-tester.ko \
kmod-chacha20-drng-tester.ko \
kmod-chacha20-stream-tester.ko \
kmod-chacha20poly1305-tester.ko \
kmod-cshake-128-tester.ko \
kmod-cshake-256-tester.ko \
kmod-cshake-crypt-test.ko \
kmod-cshake-ctx-256-tester.ko \
kmod-cshake-drng-tester.ko \
kmod-ctr-drbg-tester.ko \
kmod-dilithium-44-ed25519-tester.ko \
kmod-dilithium-44-ed448-tester.ko \
kmod-dilithium-44-invalid-tester.ko \
kmod-dilithium-44-tester-c.ko \
kmod-dilithium-44-tester-common.ko \
kmod-dilithium-44-tester-official.ko \
kmod-dilithium-65-ed25519-tester.ko \
kmod-dilithium-65-ed448-tester.ko \
kmod-dilithium-65-invalid-tester.ko \
kmod-dilithium-65-tester-armv8.ko \
kmod-dilithium-65-tester-c.ko \
kmod-dilithium-65-tester-common.ko \
kmod-dilithium-65-tester-iuf-armv8.ko \
kmod-dilithium-65-tester-official.ko \
kmod-dilithium-ed25519-tester.ko \
kmod-dilithium-ed448-tester.ko \
kmod-dilithium-invalid-tester.ko \
kmod-dilithium-tester-armv8.ko \
kmod-dilithium-tester-c.ko \
kmod-dilithium-tester-common.ko \
kmod-dilithium-tester-iuf-armv8.ko \
kmod-dilithium-tester-official.ko \
kmod-hash-crypt-test.ko \
kmod-hash-drbg-tester.ko \
kmod-hkdf-tester.ko \
kmod-hmac-drbg-tester.ko \
kmod-hmac-sha2-256-tester.ko \
kmod-hqc-128-tester.ko \
kmod-hqc-192-tester.ko \
kmod-hqc-256-tester.ko \
kmod-kdf-ctr-tester.ko \
kmod-kdf-dpi-tester.ko \
kmod-kdf-fb-tester.ko \
kmod-keccak-tester.ko \
kmod-kmac-128-tester.ko \
kmod-kmac-256-tester.ko \
kmod-kmac-crypt-test.ko \
kmod-kmac-drng-tester.ko \
kmod-kmac-xof-more-tester.ko \
kmod-kmac-xof-tester.ko \
kmod-kyber-512-ies-tester.ko \
kmod-kyber-512-invalid-tester.ko \
kmod-kyber-512-kem-kdf-tester-c.ko \
kmod-kyber-512-kem-kdf-tester-common.ko \
kmod-kyber-512-kem-tester-c.ko \
kmod-kyber-512-kem-tester-common.ko \
kmod-kyber-512-kex-tester.ko \
kmod-kyber-512-modulus-tester.ko \
kmod-kyber-768-ies-tester.ko \
kmod-kyber-768-invalid-tester.ko \
kmod-kyber-768-kem-kdf-tester-armv8.ko \
kmod-kyber-768-kem-kdf-tester-c.ko \
kmod-kyber-768-kem-kdf-tester-common.ko \
kmod-kyber-768-kem-tester-armv8.ko \
kmod-kyber-768-kem-tester-c.ko \
kmod-kyber-768-kem-tester-common.ko \
kmod-kyber-768-kex-tester.ko \
kmod-kyber-768-modulus-tester.ko \
kmod-kyber-ies-tester.ko \
kmod-kyber-ies-x25519-tester.ko \
kmod-kyber-ies-x448-tester.ko \
kmod-kyber-invalid-tester.ko \
kmod-kyber-kem-kdf-tester-armv8.ko \
kmod-kyber-kem-kdf-tester-c.ko \
kmod-kyber-kem-kdf-tester-common.ko \
kmod-kyber-kem-tester-armv8.ko \
kmod-kyber-kem-tester-c.ko \
kmod-kyber-kem-tester-common.ko \
kmod-kyber-kem-x25519-tester.ko \
kmod-kyber-kem-x448-tester.ko \
kmod-kyber-kex-tester.ko \
kmod-kyber-kex-x25519-tester.ko \
kmod-kyber-kex-x448-tester.ko \
kmod-kyber-modulus-tester.ko \
kmod-leancrypto-kernel-aead-ascon-tester.ko \
kmod-leancrypto-kernel-aes-cbc-tester.ko \
kmod-leancrypto-kernel-aes-ctr-tester.ko \
kmod-leancrypto-kernel-aes-gcm-tester.ko \
kmod-leancrypto-kernel-aes-xts-tester.ko \
kmod-leancrypto-kernel-ascon-tester.ko \
kmod-leancrypto-kernel-bike-1-tester.ko \
kmod-leancrypto-kernel-bike-3-tester.ko \
kmod-leancrypto-kernel-bike-5-tester.ko \
kmod-leancrypto-kernel-chacha20-poly1305-tester.ko \
kmod-leancrypto-kernel-chacha20-tester.ko \
kmod-leancrypto-kernel-dilithium-44-ed25519-tester.ko \
kmod-leancrypto-kernel-dilithium-44-ed448-tester.ko \
kmod-leancrypto-kernel-dilithium-44-tester.ko \
kmod-leancrypto-kernel-dilithium-65-ed25519-tester.ko \
kmod-leancrypto-kernel-dilithium-65-ed448-tester.ko \
kmod-leancrypto-kernel-dilithium-65-tester.ko \
kmod-leancrypto-kernel-dilithium-87-ed25519-tester.ko \
kmod-leancrypto-kernel-dilithium-87-ed448-tester.ko \
kmod-leancrypto-kernel-dilithium-87-tester.ko \
kmod-leancrypto-kernel-hmac-tester.ko \
kmod-leancrypto-kernel-hqc-128-tester.ko \
kmod-leancrypto-kernel-hqc-192-tester.ko \
kmod-leancrypto-kernel-hqc-256-tester.ko \
kmod-leancrypto-kernel-kmac-tester.ko \
kmod-leancrypto-kernel-kyber-1024-tester.ko \
kmod-leancrypto-kernel-kyber-1024-x25519-tester.ko \
kmod-leancrypto-kernel-kyber-1024-x448-tester.ko \
kmod-leancrypto-kernel-kyber-512-tester.ko \
kmod-leancrypto-kernel-kyber-512-x25519-tester.ko \
kmod-leancrypto-kernel-kyber-512-x448-tester.ko \
kmod-leancrypto-kernel-kyber-768-tester.ko \
kmod-leancrypto-kernel-kyber-768-x25519-tester.ko \
kmod-leancrypto-kernel-kyber-768-x448-tester.ko \
kmod-leancrypto-kernel-rng-tester.ko \
kmod-leancrypto-kernel-sha256-tester.ko \
kmod-leancrypto-kernel-sha3-tester.ko \
kmod-leancrypto-kernel-sha512-tester.ko \
kmod-leancrypto-kernel-sphincs-shake-128f-tester.ko \
kmod-leancrypto-kernel-sphincs-shake-128s-tester.ko \
kmod-leancrypto-kernel-sphincs-shake-192s-tester.ko \
kmod-leancrypto-kernel-sphincs-shake-256f-tester.ko \
kmod-leancrypto-kernel-sphincs-shake-256s-tester.ko \
kmod-leancrypto.ko \
kmod-pbkdf2-tester.ko \
kmod-rerun-one-selftest-tester.ko \
kmod-rerun-selftests-tester.ko \
kmod-sha256-tester.ko \
kmod-sha3-224-tester.ko \
kmod-sha3-256-tester.ko \
kmod-sha3-384-tester.ko \
kmod-sha3-512-tester.ko \
kmod-sha384-tester.ko \
kmod-sha512-tester.ko \
kmod-shake-squeeze-more-tester.ko \
kmod-shake128-tester.ko \
kmod-shake256-tester.ko \
kmod-sphincs-tester-128f-c.ko \
kmod-sphincs-tester-128f.ko \
kmod-sphincs-tester-128s-c.ko \
kmod-sphincs-tester-128s.ko \
kmod-sphincs-tester-192f-c.ko \
kmod-sphincs-tester-192f.ko \
kmod-sphincs-tester-192s-c.ko \
kmod-sphincs-tester-192s.ko \
kmod-sphincs-tester-256f-c.ko \
kmod-sphincs-tester-256f.ko \
kmod-sphincs-tester-256s-c.ko \
kmod-sphincs-tester-256s.ko \
kmod-sphincs-tester-official.ko \
kmod-status-tester.ko \
kmod-symhmac-test.ko \
kmod-symkmac128-test.ko \
kmod-symkmac256-test.ko \
kmod-uuid-tester.ko \
kmod-xdrbg128-tester.ko \
kmod-xdrbg256-tester.ko \
kmod-xdrbg512-tester.ko \
ksym-default-cc20-block \
ksym-default-crypto-scalarmult-curve25519 \
ksym-default-crypto-scalarmult-curve25519-base \
ksym-default-lc-OID-to-data \
ksym-default-lc-aead-alg-status \
ksym-default-lc-aead-ctx-alg-status \
ksym-default-lc-aead-dec-final \
ksym-default-lc-aead-dec-init \
ksym-default-lc-aead-dec-update \
ksym-default-lc-aead-decrypt \
ksym-default-lc-aead-enc-final \
ksym-default-lc-aead-enc-init \
ksym-default-lc-aead-enc-update \
ksym-default-lc-aead-encrypt \
ksym-default-lc-aead-setkey \
ksym-default-lc-aead-setkey-from-ctx \
ksym-default-lc-aead-zero \
ksym-default-lc-aead-zero-free \
ksym-default-lc-aes \
ksym-default-lc-aes-aesni \
ksym-default-lc-aes-armce \
ksym-default-lc-aes-c \
ksym-default-lc-aes-cbc \
ksym-default-lc-aes-cbc-aesni \
ksym-default-lc-aes-cbc-armce \
ksym-default-lc-aes-cbc-c \
ksym-default-lc-aes-cbc-riscv64 \
ksym-default-lc-aes-ct \
ksym-default-lc-aes-ctr \
ksym-default-lc-aes-ctr-aesni \
ksym-default-lc-aes-ctr-armce \
ksym-default-lc-aes-ctr-c \
ksym-default-lc-aes-ctr-riscv64 \
ksym-default-lc-aes-gcm-aead \
ksym-default-lc-aes-gcm-alloc \
ksym-default-lc-aes-gcm-generate-iv \
ksym-default-lc-aes-kw \
ksym-default-lc-aes-kw-aesni \
ksym-default-lc-aes-kw-armce \
ksym-default-lc-aes-kw-c \
ksym-default-lc-aes-kw-decrypt \
ksym-default-lc-aes-kw-encrypt \
ksym-default-lc-aes-kw-riscv64 \
ksym-default-lc-aes-riscv64 \
ksym-default-lc-aes-sbox \
ksym-default-lc-aes-xts \
ksym-default-lc-aes-xts-aesni \
ksym-default-lc-aes-xts-armce \
ksym-default-lc-aes-xts-c \
ksym-default-lc-aes-xts-riscv64 \
ksym-default-lc-ak-alloc \
ksym-default-lc-ak-alloc-taglen \
ksym-default-lc-al-alloc \
ksym-default-lc-alg-disable-selftests \
ksym-default-lc-alloc-aligned \
ksym-default-lc-alloc-aligned-secure \
ksym-default-lc-alloc-high-aligned \
ksym-default-lc-ascon-128a \
ksym-default-lc-ascon-128a-arm-neon \
ksym-default-lc-ascon-128a-avx512 \
ksym-default-lc-ascon-128a-c \
ksym-default-lc-ascon-256 \
ksym-default-lc-ascon-256-arm-neon \
ksym-default-lc-ascon-256-avx512 \
ksym-default-lc-ascon-256-c \
ksym-default-lc-ascon-aead \
ksym-default-lc-ascon-keccak-aead \
ksym-default-lc-ascon-xof \
ksym-default-lc-ascon-xof-arm-neon \
ksym-default-lc-ascon-xof-avx512 \
ksym-default-lc-ascon-xof-c \
ksym-default-lc-asn1-ber-decoder \
ksym-default-lc-asn1-ber-encoder \
ksym-default-lc-asn1-ber-encoder-small \
ksym-default-lc-bike-1-dec \
ksym-default-lc-bike-1-dec-kdf \
ksym-default-lc-bike-1-enc \
ksym-default-lc-bike-1-enc-internal \
ksym-default-lc-bike-1-enc-kdf \
ksym-default-lc-bike-1-keypair \
ksym-default-lc-bike-1-keypair-from-seed \
ksym-default-lc-bike-3-dec \
ksym-default-lc-bike-3-dec-kdf \
ksym-default-lc-bike-3-enc \
ksym-default-lc-bike-3-enc-internal \
ksym-default-lc-bike-3-enc-kdf \
ksym-default-lc-bike-3-keypair \
ksym-default-lc-bike-3-keypair-from-seed \
ksym-default-lc-bike-5-dec \
ksym-default-lc-bike-5-dec-kdf \
ksym-default-lc-bike-5-enc \
ksym-default-lc-bike-5-enc-internal \
ksym-default-lc-bike-5-enc-kdf \
ksym-default-lc-bike-5-keypair \
ksym-default-lc-bike-5-keypair-from-seed \
ksym-default-lc-bike-alg-status \
ksym-default-lc-bike-ct-load \
ksym-default-lc-bike-ct-ptr \
ksym-default-lc-bike-ct-size \
ksym-default-lc-bike-ct-type \
ksym-default-lc-bike-dec \
ksym-default-lc-bike-dec-kdf \
ksym-default-lc-bike-enc \
ksym-default-lc-bike-enc-kdf \
ksym-default-lc-bike-keypair \
ksym-default-lc-bike-keypair-from-seed \
ksym-default-lc-bike-pk-load \
ksym-default-lc-bike-pk-ptr \
ksym-default-lc-bike-pk-size \
ksym-default-lc-bike-pk-type \
ksym-default-lc-bike-sk-load \
ksym-default-lc-bike-sk-ptr \
ksym-default-lc-bike-sk-size \
ksym-default-lc-bike-sk-type \
ksym-default-lc-bike-ss-load \
ksym-default-lc-bike-ss-ptr \
ksym-default-lc-bike-ss-size \
ksym-default-lc-bike-ss-type \
ksym-default-lc-cc-alloc \
ksym-default-lc-cc20-drng \
ksym-default-lc-cc20-drng-alloc \
ksym-default-lc-chacha20 \
ksym-default-lc-chacha20-avx2 \
ksym-default-lc-chacha20-avx512 \
ksym-default-lc-chacha20-c \
ksym-default-lc-chacha20-neon \
ksym-default-lc-chacha20-poly1305-aead \
ksym-default-lc-chacha20-poly1305-alloc \
ksym-default-lc-chacha20-riscv64-v-zbb \
ksym-default-lc-compare \
ksym-default-lc-cpu-feature-available \
ksym-default-lc-cpu-feature-disable \
ksym-default-lc-cpu-feature-enable \
ksym-default-lc-cpu-feature-set \
ksym-default-lc-cshake-aead \
ksym-default-lc-cshake-ctx-alloc \
ksym-default-lc-cshake-ctx-final \
ksym-default-lc-cshake-ctx-init \
ksym-default-lc-cshake-ctx-reinit \
ksym-default-lc-cshake-ctx-update \
ksym-default-lc-cshake-ctx-zero-free \
ksym-default-lc-cshake-init \
ksym-default-lc-cshake128 \
ksym-default-lc-cshake128-arm-asm \
ksym-default-lc-cshake128-arm-ce \
ksym-default-lc-cshake128-arm-neon \
ksym-default-lc-cshake128-avx2 \
ksym-default-lc-cshake128-avx512 \
ksym-default-lc-cshake128-c \
ksym-default-lc-cshake128-riscv-asm \
ksym-default-lc-cshake128-riscv-asm-zbb \
ksym-default-lc-cshake256 \
ksym-default-lc-cshake256-arm-asm \
ksym-default-lc-cshake256-arm-ce \
ksym-default-lc-cshake256-arm-neon \
ksym-default-lc-cshake256-avx2 \
ksym-default-lc-cshake256-avx512 \
ksym-default-lc-cshake256-c \
ksym-default-lc-cshake256-drng \
ksym-default-lc-cshake256-drng-alloc \
ksym-default-lc-cshake256-riscv-asm \
ksym-default-lc-cshake256-riscv-asm-zbb \
ksym-default-lc-ctr-drbg \
ksym-default-lc-dilithium-44-ctx-alloc \
ksym-default-lc-dilithium-44-ctx-alloc-ahat \
ksym-default-lc-dilithium-44-ctx-zero-free \
ksym-default-lc-dilithium-44-ed25519-ctx-alloc \
ksym-default-lc-dilithium-44-ed25519-ctx-zero-free \
ksym-default-lc-dilithium-44-ed25519-keypair \
ksym-default-lc-dilithium-44-ed25519-pk-from-sk \
ksym-default-lc-dilithium-44-ed25519-sign \
ksym-default-lc-dilithium-44-ed25519-sign-ctx \
ksym-default-lc-dilithium-44-ed25519-sign-final \
ksym-default-lc-dilithium-44-ed25519-sign-init \
ksym-default-lc-dilithium-44-ed25519-sign-update \
ksym-default-lc-dilithium-44-ed25519-verify \
ksym-default-lc-dilithium-44-ed25519-verify-ctx \
ksym-default-lc-dilithium-44-ed25519-verify-final \
ksym-default-lc-dilithium-44-ed25519-verify-init \
ksym-default-lc-dilithium-44-ed25519-verify-update \
ksym-default-lc-dilithium-44-ed448-ctx-alloc \
ksym-default-lc-dilithium-44-ed448-ctx-zero-free \
ksym-default-lc-dilithium-44-ed448-keypair \
ksym-default-lc-dilithium-44-ed448-pk-from-sk \
ksym-default-lc-dilithium-44-ed448-sign \
ksym-default-lc-dilithium-44-ed448-sign-ctx \
ksym-default-lc-dilithium-44-ed448-sign-final \
ksym-default-lc-dilithium-44-ed448-sign-init \
ksym-default-lc-dilithium-44-ed448-sign-update \
ksym-default-lc-dilithium-44-ed448-verify \
ksym-default-lc-dilithium-44-ed448-verify-ctx \
ksym-default-lc-dilithium-44-ed448-verify-final \
ksym-default-lc-dilithium-44-ed448-verify-init \
ksym-default-lc-dilithium-44-ed448-verify-update \
ksym-default-lc-dilithium-44-keypair \
ksym-default-lc-dilithium-44-keypair-c \
ksym-default-lc-dilithium-44-keypair-from-seed \
ksym-default-lc-dilithium-44-keypair-from-seed-c \
ksym-default-lc-dilithium-44-pk-from-sk \
ksym-default-lc-dilithium-44-pk-from-sk-c \
ksym-default-lc-dilithium-44-sign \
ksym-default-lc-dilithium-44-sign-c \
ksym-default-lc-dilithium-44-sign-ctx \
ksym-default-lc-dilithium-44-sign-ctx-c \
ksym-default-lc-dilithium-44-sign-final \
ksym-default-lc-dilithium-44-sign-final-c \
ksym-default-lc-dilithium-44-sign-init \
ksym-default-lc-dilithium-44-sign-init-c \
ksym-default-lc-dilithium-44-sign-update \
ksym-default-lc-dilithium-44-sign-update-c \
ksym-default-lc-dilithium-44-verify \
ksym-default-lc-dilithium-44-verify-c \
ksym-default-lc-dilithium-44-verify-ctx \
ksym-default-lc-dilithium-44-verify-ctx-c \
ksym-default-lc-dilithium-44-verify-final \
ksym-default-lc-dilithium-44-verify-final-c \
ksym-default-lc-dilithium-44-verify-init \
ksym-default-lc-dilithium-44-verify-init-c \
ksym-default-lc-dilithium-44-verify-update \
ksym-default-lc-dilithium-44-verify-update-c \
ksym-default-lc-dilithium-65-ctx-alloc \
ksym-default-lc-dilithium-65-ctx-alloc-ahat \
ksym-default-lc-dilithium-65-ctx-zero-free \
ksym-default-lc-dilithium-65-ed25519-ctx-alloc \
ksym-default-lc-dilithium-65-ed25519-ctx-zero-free \
ksym-default-lc-dilithium-65-ed25519-keypair \
ksym-default-lc-dilithium-65-ed25519-pk-from-sk \
ksym-default-lc-dilithium-65-ed25519-sign \
ksym-default-lc-dilithium-65-ed25519-sign-ctx \
ksym-default-lc-dilithium-65-ed25519-sign-final \
ksym-default-lc-dilithium-65-ed25519-sign-init \
ksym-default-lc-dilithium-65-ed25519-sign-update \
ksym-default-lc-dilithium-65-ed25519-verify \
ksym-default-lc-dilithium-65-ed25519-verify-ctx \
ksym-default-lc-dilithium-65-ed25519-verify-final \
ksym-default-lc-dilithium-65-ed25519-verify-init \
ksym-default-lc-dilithium-65-ed25519-verify-update \
ksym-default-lc-dilithium-65-ed448-ctx-alloc \
ksym-default-lc-dilithium-65-ed448-ctx-zero-free \
ksym-default-lc-dilithium-65-ed448-keypair \
ksym-default-lc-dilithium-65-ed448-pk-from-sk \
ksym-default-lc-dilithium-65-ed448-sign \
ksym-default-lc-dilithium-65-ed448-sign-ctx \
ksym-default-lc-dilithium-65-ed448-sign-final \
ksym-default-lc-dilithium-65-ed448-sign-init \
ksym-default-lc-dilithium-65-ed448-sign-update \
ksym-default-lc-dilithium-65-ed448-verify \
ksym-default-lc-dilithium-65-ed448-verify-ctx \
ksym-default-lc-dilithium-65-ed448-verify-final \
ksym-default-lc-dilithium-65-ed448-verify-init \
ksym-default-lc-dilithium-65-ed448-verify-update \
ksym-default-lc-dilithium-65-keypair \
ksym-default-lc-dilithium-65-keypair-armv8 \
ksym-default-lc-dilithium-65-keypair-c \
ksym-default-lc-dilithium-65-keypair-from-seed \
ksym-default-lc-dilithium-65-keypair-from-seed-armv8 \
ksym-default-lc-dilithium-65-keypair-from-seed-c \
ksym-default-lc-dilithium-65-pk-from-sk \
ksym-default-lc-dilithium-65-pk-from-sk-armv8 \
ksym-default-lc-dilithium-65-pk-from-sk-c \
ksym-default-lc-dilithium-65-sign \
ksym-default-lc-dilithium-65-sign-armv8 \
ksym-default-lc-dilithium-65-sign-c \
ksym-default-lc-dilithium-65-sign-ctx \
ksym-default-lc-dilithium-65-sign-ctx-armv8 \
ksym-default-lc-dilithium-65-sign-ctx-c \
ksym-default-lc-dilithium-65-sign-final \
ksym-default-lc-dilithium-65-sign-final-armv8 \
ksym-default-lc-dilithium-65-sign-final-c \
ksym-default-lc-dilithium-65-sign-init \
ksym-default-lc-dilithium-65-sign-init-armv8 \
ksym-default-lc-dilithium-65-sign-init-c \
ksym-default-lc-dilithium-65-sign-update \
ksym-default-lc-dilithium-65-sign-update-armv8 \
ksym-default-lc-dilithium-65-sign-update-c \
ksym-default-lc-dilithium-65-verify \
ksym-default-lc-dilithium-65-verify-armv8 \
ksym-default-lc-dilithium-65-verify-c \
ksym-default-lc-dilithium-65-verify-ctx \
ksym-default-lc-dilithium-65-verify-ctx-armv8 \
ksym-default-lc-dilithium-65-verify-ctx-c \
ksym-default-lc-dilithium-65-verify-final \
ksym-default-lc-dilithium-65-verify-final-armv8 \
ksym-default-lc-dilithium-65-verify-final-c \
ksym-default-lc-dilithium-65-verify-init \
ksym-default-lc-dilithium-65-verify-init-armv8 \
ksym-default-lc-dilithium-65-verify-init-c \
ksym-default-lc-dilithium-65-verify-update \
ksym-default-lc-dilithium-65-verify-update-armv8 \
ksym-default-lc-dilithium-65-verify-update-c \
ksym-default-lc-dilithium-87-ctx-alloc \
ksym-default-lc-dilithium-87-ctx-alloc-ahat \
ksym-default-lc-dilithium-87-ctx-zero-free \
ksym-default-lc-dilithium-87-ed25519-ctx-alloc \
ksym-default-lc-dilithium-87-ed25519-ctx-zero-free \
ksym-default-lc-dilithium-87-ed25519-keypair \
ksym-default-lc-dilithium-87-ed25519-pk-from-sk \
ksym-default-lc-dilithium-87-ed25519-sign \
ksym-default-lc-dilithium-87-ed25519-sign-ctx \
ksym-default-lc-dilithium-87-ed25519-sign-final \
ksym-default-lc-dilithium-87-ed25519-sign-init \
ksym-default-lc-dilithium-87-ed25519-sign-update \
ksym-default-lc-dilithium-87-ed25519-verify \
ksym-default-lc-dilithium-87-ed25519-verify-ctx \
ksym-default-lc-dilithium-87-ed25519-verify-final \
ksym-default-lc-dilithium-87-ed25519-verify-init \
ksym-default-lc-dilithium-87-ed25519-verify-update \
ksym-default-lc-dilithium-87-ed448-ctx-alloc \
ksym-default-lc-dilithium-87-ed448-ctx-zero-free \
ksym-default-lc-dilithium-87-ed448-keypair \
ksym-default-lc-dilithium-87-ed448-pk-from-sk \
ksym-default-lc-dilithium-87-ed448-sign \
ksym-default-lc-dilithium-87-ed448-sign-ctx \
ksym-default-lc-dilithium-87-ed448-sign-final \
ksym-default-lc-dilithium-87-ed448-sign-init \
ksym-default-lc-dilithium-87-ed448-sign-update \
ksym-default-lc-dilithium-87-ed448-verify \
ksym-default-lc-dilithium-87-ed448-verify-ctx \
ksym-default-lc-dilithium-87-ed448-verify-final \
ksym-default-lc-dilithium-87-ed448-verify-init \
ksym-default-lc-dilithium-87-ed448-verify-update \
ksym-default-lc-dilithium-87-keypair \
ksym-default-lc-dilithium-87-keypair-armv8 \
ksym-default-lc-dilithium-87-keypair-c \
ksym-default-lc-dilithium-87-keypair-from-seed \
ksym-default-lc-dilithium-87-keypair-from-seed-armv8 \
ksym-default-lc-dilithium-87-keypair-from-seed-c \
ksym-default-lc-dilithium-87-pk-from-sk \
ksym-default-lc-dilithium-87-pk-from-sk-armv8 \
ksym-default-lc-dilithium-87-pk-from-sk-c \
ksym-default-lc-dilithium-87-sign \
ksym-default-lc-dilithium-87-sign-armv8 \
ksym-default-lc-dilithium-87-sign-c \
ksym-default-lc-dilithium-87-sign-ctx \
ksym-default-lc-dilithium-87-sign-ctx-armv8 \
ksym-default-lc-dilithium-87-sign-ctx-c \
ksym-default-lc-dilithium-87-sign-final \
ksym-default-lc-dilithium-87-sign-final-armv8 \
ksym-default-lc-dilithium-87-sign-final-c \
ksym-default-lc-dilithium-87-sign-init \
ksym-default-lc-dilithium-87-sign-init-armv8 \
ksym-default-lc-dilithium-87-sign-init-c \
ksym-default-lc-dilithium-87-sign-update \
ksym-default-lc-dilithium-87-sign-update-armv8 \
ksym-default-lc-dilithium-87-sign-update-c \
ksym-default-lc-dilithium-87-verify \
ksym-default-lc-dilithium-87-verify-armv8 \
ksym-default-lc-dilithium-87-verify-c \
ksym-default-lc-dilithium-87-verify-ctx \
ksym-default-lc-dilithium-87-verify-ctx-armv8 \
ksym-default-lc-dilithium-87-verify-ctx-c \
ksym-default-lc-dilithium-87-verify-final \
ksym-default-lc-dilithium-87-verify-final-armv8 \
ksym-default-lc-dilithium-87-verify-final-c \
ksym-default-lc-dilithium-87-verify-init \
ksym-default-lc-dilithium-87-verify-init-armv8 \
ksym-default-lc-dilithium-87-verify-init-c \
ksym-default-lc-dilithium-87-verify-update \
ksym-default-lc-dilithium-87-verify-update-armv8 \
ksym-default-lc-dilithium-87-verify-update-c \
ksym-default-lc-dilithium-alg-status \
ksym-default-lc-dilithium-ctx-alloc \
ksym-default-lc-dilithium-ctx-alloc-ahat \
ksym-default-lc-dilithium-ctx-drop-ahat \
ksym-default-lc-dilithium-ctx-external-mu \
ksym-default-lc-dilithium-ctx-hash \
ksym-default-lc-dilithium-ctx-internal \
ksym-default-lc-dilithium-ctx-userctx \
ksym-default-lc-dilithium-ctx-zero \
ksym-default-lc-dilithium-ctx-zero-free \
ksym-default-lc-dilithium-ed25519-ctx-alloc \
ksym-default-lc-dilithium-ed25519-ctx-hash \
ksym-default-lc-dilithium-ed25519-ctx-internal \
ksym-default-lc-dilithium-ed25519-ctx-userctx \
ksym-default-lc-dilithium-ed25519-ctx-zero \
ksym-default-lc-dilithium-ed25519-ctx-zero-free \
ksym-default-lc-dilithium-ed25519-keypair \
ksym-default-lc-dilithium-ed25519-pk-from-sk \
ksym-default-lc-dilithium-ed25519-pk-load \
ksym-default-lc-dilithium-ed25519-pk-ptr \
ksym-default-lc-dilithium-ed25519-pk-size \
ksym-default-lc-dilithium-ed25519-pk-type \
ksym-default-lc-dilithium-ed25519-sig-load \
ksym-default-lc-dilithium-ed25519-sig-ptr \
ksym-default-lc-dilithium-ed25519-sig-size \
ksym-default-lc-dilithium-ed25519-sig-type \
ksym-default-lc-dilithium-ed25519-sign \
ksym-default-lc-dilithium-ed25519-sign-ctx \
ksym-default-lc-dilithium-ed25519-sign-final \
ksym-default-lc-dilithium-ed25519-sign-init \
ksym-default-lc-dilithium-ed25519-sign-update \
ksym-default-lc-dilithium-ed25519-sk-load \
ksym-default-lc-dilithium-ed25519-sk-ptr \
ksym-default-lc-dilithium-ed25519-sk-size \
ksym-default-lc-dilithium-ed25519-sk-type \
ksym-default-lc-dilithium-ed25519-verify \
ksym-default-lc-dilithium-ed25519-verify-ctx \
ksym-default-lc-dilithium-ed25519-verify-final \
ksym-default-lc-dilithium-ed25519-verify-init \
ksym-default-lc-dilithium-ed25519-verify-update \
ksym-default-lc-dilithium-ed448-ctx-alloc \
ksym-default-lc-dilithium-ed448-ctx-hash \
ksym-default-lc-dilithium-ed448-ctx-internal \
ksym-default-lc-dilithium-ed448-ctx-userctx \
ksym-default-lc-dilithium-ed448-ctx-zero \
ksym-default-lc-dilithium-ed448-ctx-zero-free \
ksym-default-lc-dilithium-ed448-keypair \
ksym-default-lc-dilithium-ed448-pk-from-sk \
ksym-default-lc-dilithium-ed448-pk-load \
ksym-default-lc-dilithium-ed448-pk-ptr \
ksym-default-lc-dilithium-ed448-pk-size \
ksym-default-lc-dilithium-ed448-pk-type \
ksym-default-lc-dilithium-ed448-sig-load \
ksym-default-lc-dilithium-ed448-sig-ptr \
ksym-default-lc-dilithium-ed448-sig-size \
ksym-default-lc-dilithium-ed448-sig-type \
ksym-default-lc-dilithium-ed448-sign \
ksym-default-lc-dilithium-ed448-sign-ctx \
ksym-default-lc-dilithium-ed448-sign-final \
ksym-default-lc-dilithium-ed448-sign-init \
ksym-default-lc-dilithium-ed448-sign-update \
ksym-default-lc-dilithium-ed448-sk-load \
ksym-default-lc-dilithium-ed448-sk-ptr \
ksym-default-lc-dilithium-ed448-sk-size \
ksym-default-lc-dilithium-ed448-sk-type \
ksym-default-lc-dilithium-ed448-verify \
ksym-default-lc-dilithium-ed448-verify-ctx \
ksym-default-lc-dilithium-ed448-verify-final \
ksym-default-lc-dilithium-ed448-verify-init \
ksym-default-lc-dilithium-ed448-verify-update \
ksym-default-lc-dilithium-keypair \
ksym-default-lc-dilithium-keypair-from-seed \
ksym-default-lc-dilithium-pct \
ksym-default-lc-dilithium-pk-from-sk \
ksym-default-lc-dilithium-pk-load \
ksym-default-lc-dilithium-pk-ptr \
ksym-default-lc-dilithium-pk-size \
ksym-default-lc-dilithium-pk-type \
ksym-default-lc-dilithium-sig-load \
ksym-default-lc-dilithium-sig-ptr \
ksym-default-lc-dilithium-sig-size \
ksym-default-lc-dilithium-sig-type \
ksym-default-lc-dilithium-sign \
ksym-default-lc-dilithium-sign-ctx \
ksym-default-lc-dilithium-sign-final \
ksym-default-lc-dilithium-sign-init \
ksym-default-lc-dilithium-sign-update \
ksym-default-lc-dilithium-sk-load \
ksym-default-lc-dilithium-sk-ptr \
ksym-default-lc-dilithium-sk-size \
ksym-default-lc-dilithium-sk-type \
ksym-default-lc-dilithium-verify \
ksym-default-lc-dilithium-verify-ctx \
ksym-default-lc-dilithium-verify-final \
ksym-default-lc-dilithium-verify-init \
ksym-default-lc-dilithium-verify-update \
ksym-default-lc-disable-selftest \
ksym-default-lc-drbg-ctr-no-df-alloc \
ksym-default-lc-drbg-ctr-use-df-alloc \
ksym-default-lc-drbg-hash-alloc \
ksym-default-lc-drbg-hash-healthcheck-sanity \
ksym-default-lc-drbg-hmac-alloc \
ksym-default-lc-drbg-hmac-healthcheck-sanity \
ksym-default-lc-ed25519-alg-status \
ksym-default-lc-ed25519-keypair \
ksym-default-lc-ed25519-pk-load \
ksym-default-lc-ed25519-pk-ptr \
ksym-default-lc-ed25519-pk-size \
ksym-default-lc-ed25519-sig-load \
ksym-default-lc-ed25519-sig-ptr \
ksym-default-lc-ed25519-sig-size \
ksym-default-lc-ed25519-sign \
ksym-default-lc-ed25519-sk-load \
ksym-default-lc-ed25519-sk-ptr \
ksym-default-lc-ed25519-sk-size \
ksym-default-lc-ed25519-verify \
ksym-default-lc-ed25519ph-sign \
ksym-default-lc-ed25519ph-verify \
ksym-default-lc-ed448-alg-status \
ksym-default-lc-ed448-keypair \
ksym-default-lc-ed448-pk-load \
ksym-default-lc-ed448-pk-ptr \
ksym-default-lc-ed448-pk-size \
ksym-default-lc-ed448-sig-load \
ksym-default-lc-ed448-sig-ptr \
ksym-default-lc-ed448-sig-size \
ksym-default-lc-ed448-sign \
ksym-default-lc-ed448-sk-load \
ksym-default-lc-ed448-sk-ptr \
ksym-default-lc-ed448-sk-size \
ksym-default-lc-ed448-verify \
ksym-default-lc-ed448ph-sign \
ksym-default-lc-ed448ph-verify \
ksym-default-lc-fips-integrity-checker \
ksym-default-lc-free \
ksym-default-lc-free-high-aligned \
ksym-default-lc-gmtime \
ksym-default-lc-hash \
ksym-default-lc-hash-aead \
ksym-default-lc-hash-alg-status \
ksym-default-lc-hash-alloc \
ksym-default-lc-hash-blocksize \
ksym-default-lc-hash-ctx-alg-status \
ksym-default-lc-hash-ctxsize \
ksym-default-lc-hash-digestsize \
ksym-default-lc-hash-drbg \
ksym-default-lc-hash-final \
ksym-default-lc-hash-init \
ksym-default-lc-hash-set-ctx \
ksym-default-lc-hash-set-digestsize \
ksym-default-lc-hash-update \
ksym-default-lc-hash-zero \
ksym-default-lc-hash-zero-free \
ksym-default-lc-hc-alloc \
ksym-default-lc-hkdf \
ksym-default-lc-hkdf-alg-status \
ksym-default-lc-hkdf-alloc \
ksym-default-lc-hkdf-expand \
ksym-default-lc-hkdf-expand-prk \
ksym-default-lc-hkdf-extract \
ksym-default-lc-hkdf-extract-prk \
ksym-default-lc-hkdf-rng \
ksym-default-lc-hkdf-rng-alloc \
ksym-default-lc-hkdf-zero \
ksym-default-lc-hkdf-zero-free \
ksym-default-lc-hmac \
ksym-default-lc-hmac-alg-status \
ksym-default-lc-hmac-alloc \
ksym-default-lc-hmac-ctx-alg-status \
ksym-default-lc-hmac-drbg \
ksym-default-lc-hmac-final \
ksym-default-lc-hmac-init \
ksym-default-lc-hmac-init-with-hmac-key \
ksym-default-lc-hmac-macsize \
ksym-default-lc-hmac-reinit \
ksym-default-lc-hmac-setkey \
ksym-default-lc-hmac-update \
ksym-default-lc-hmac-zero \
ksym-default-lc-hmac-zero-free \
ksym-default-lc-hqc-128-dec \
ksym-default-lc-hqc-128-dec-c \
ksym-default-lc-hqc-128-dec-kdf \
ksym-default-lc-hqc-128-dec-kdf-c \
ksym-default-lc-hqc-128-enc \
ksym-default-lc-hqc-128-enc-c \
ksym-default-lc-hqc-128-enc-internal \
ksym-default-lc-hqc-128-enc-internal-c \
ksym-default-lc-hqc-128-enc-kdf \
ksym-default-lc-hqc-128-enc-kdf-c \
ksym-default-lc-hqc-128-keypair \
ksym-default-lc-hqc-128-keypair-c \
ksym-default-lc-hqc-128-keypair-from-seed \
ksym-default-lc-hqc-128-keypair-from-seed-c \
ksym-default-lc-hqc-192-dec \
ksym-default-lc-hqc-192-dec-c \
ksym-default-lc-hqc-192-dec-kdf \
ksym-default-lc-hqc-192-dec-kdf-c \
ksym-default-lc-hqc-192-enc \
ksym-default-lc-hqc-192-enc-c \
ksym-default-lc-hqc-192-enc-internal \
ksym-default-lc-hqc-192-enc-internal-c \
ksym-default-lc-hqc-192-enc-kdf \
ksym-default-lc-hqc-192-enc-kdf-c \
ksym-default-lc-hqc-192-keypair \
ksym-default-lc-hqc-192-keypair-c \
ksym-default-lc-hqc-192-keypair-from-seed \
ksym-default-lc-hqc-192-keypair-from-seed-c \
ksym-default-lc-hqc-256-dec \
ksym-default-lc-hqc-256-dec-c \
ksym-default-lc-hqc-256-dec-kdf \
ksym-default-lc-hqc-256-dec-kdf-c \
ksym-default-lc-hqc-256-enc \
ksym-default-lc-hqc-256-enc-c \
ksym-default-lc-hqc-256-enc-internal \
ksym-default-lc-hqc-256-enc-internal-c \
ksym-default-lc-hqc-256-enc-kdf \
ksym-default-lc-hqc-256-enc-kdf-c \
ksym-default-lc-hqc-256-keypair \
ksym-default-lc-hqc-256-keypair-c \
ksym-default-lc-hqc-256-keypair-from-seed \
ksym-default-lc-hqc-256-keypair-from-seed-c \
ksym-default-lc-hqc-alg-status \
ksym-default-lc-hqc-ct-load \
ksym-default-lc-hqc-ct-ptr \
ksym-default-lc-hqc-ct-size \
ksym-default-lc-hqc-ct-type \
ksym-default-lc-hqc-dec \
ksym-default-lc-hqc-dec-kdf \
ksym-default-lc-hqc-enc \
ksym-default-lc-hqc-enc-kdf \
ksym-default-lc-hqc-keypair \
ksym-default-lc-hqc-keypair-from-seed \
ksym-default-lc-hqc-pk-load \
ksym-default-lc-hqc-pk-ptr \
ksym-default-lc-hqc-pk-size \
ksym-default-lc-hqc-pk-type \
ksym-default-lc-hqc-sk-load \
ksym-default-lc-hqc-sk-ptr \
ksym-default-lc-hqc-sk-size \
ksym-default-lc-hqc-sk-type \
ksym-default-lc-hqc-ss-load \
ksym-default-lc-hqc-ss-ptr \
ksym-default-lc-hqc-ss-size \
ksym-default-lc-hqc-ss-type \
ksym-default-lc-kc-alloc \
ksym-default-lc-kdf-ctr \
ksym-default-lc-kdf-ctr-alg-status \
ksym-default-lc-kdf-ctr-generate \
ksym-default-lc-kdf-ctr-init \
ksym-default-lc-kdf-ctr-rng \
ksym-default-lc-kdf-ctr-rng-alloc \
ksym-default-lc-kdf-dpi \
ksym-default-lc-kdf-dpi-alg-status \
ksym-default-lc-kdf-dpi-generate \
ksym-default-lc-kdf-dpi-init \
ksym-default-lc-kdf-fb \
ksym-default-lc-kdf-fb-alg-status \
ksym-default-lc-kdf-fb-generate \
ksym-default-lc-kdf-fb-init \
ksym-default-lc-kex-1024-ake-initiator-init \
ksym-default-lc-kex-1024-ake-initiator-init-internal \
ksym-default-lc-kex-1024-ake-initiator-ss \
ksym-default-lc-kex-1024-ake-responder-ss \
ksym-default-lc-kex-1024-ake-responder-ss-internal \
ksym-default-lc-kex-1024-uake-initiator-init \
ksym-default-lc-kex-1024-uake-initiator-init-internal \
ksym-default-lc-kex-1024-uake-initiator-ss \
ksym-default-lc-kex-1024-uake-responder-ss \
ksym-default-lc-kex-1024-uake-responder-ss-internal \
ksym-default-lc-kex-1024-x25519-ake-initiator-init \
ksym-default-lc-kex-1024-x25519-ake-initiator-init-internal \
ksym-default-lc-kex-1024-x25519-ake-initiator-ss \
ksym-default-lc-kex-1024-x25519-ake-responder-ss \
ksym-default-lc-kex-1024-x25519-ake-responder-ss-internal \
ksym-default-lc-kex-1024-x25519-uake-initiator-init \
ksym-default-lc-kex-1024-x25519-uake-initiator-init-internal \
ksym-default-lc-kex-1024-x25519-uake-initiator-ss \
ksym-default-lc-kex-1024-x25519-uake-responder-ss \
ksym-default-lc-kex-1024-x25519-uake-responder-ss-internal \
ksym-default-lc-kex-1024-x448-ake-initiator-init \
ksym-default-lc-kex-1024-x448-ake-initiator-init-internal \
ksym-default-lc-kex-1024-x448-ake-initiator-ss \
ksym-default-lc-kex-1024-x448-ake-responder-ss \
ksym-default-lc-kex-1024-x448-ake-responder-ss-internal \
ksym-default-lc-kex-1024-x448-uake-initiator-init \
ksym-default-lc-kex-1024-x448-uake-initiator-init-internal \
ksym-default-lc-kex-1024-x448-uake-initiator-ss \
ksym-default-lc-kex-1024-x448-uake-responder-ss \
ksym-default-lc-kex-1024-x448-uake-responder-ss-internal \
ksym-default-lc-kex-512-ake-initiator-init \
ksym-default-lc-kex-512-ake-initiator-init-internal \
ksym-default-lc-kex-512-ake-initiator-ss \
ksym-default-lc-kex-512-ake-responder-ss \
ksym-default-lc-kex-512-ake-responder-ss-internal \
ksym-default-lc-kex-512-uake-initiator-init \
ksym-default-lc-kex-512-uake-initiator-init-internal \
ksym-default-lc-kex-512-uake-initiator-ss \
ksym-default-lc-kex-512-uake-responder-ss \
ksym-default-lc-kex-512-uake-responder-ss-internal \
ksym-default-lc-kex-512-x25519-ake-initiator-init \
ksym-default-lc-kex-512-x25519-ake-initiator-init-internal \
ksym-default-lc-kex-512-x25519-ake-initiator-ss \
ksym-default-lc-kex-512-x25519-ake-responder-ss \
ksym-default-lc-kex-512-x25519-ake-responder-ss-internal \
ksym-default-lc-kex-512-x25519-uake-initiator-init \
ksym-default-lc-kex-512-x25519-uake-initiator-init-internal \
ksym-default-lc-kex-512-x25519-uake-initiator-ss \
ksym-default-lc-kex-512-x25519-uake-responder-ss \
ksym-default-lc-kex-512-x25519-uake-responder-ss-internal \
ksym-default-lc-kex-512-x448-ake-initiator-init \
ksym-default-lc-kex-512-x448-ake-initiator-init-internal \
ksym-default-lc-kex-512-x448-ake-initiator-ss \
ksym-default-lc-kex-512-x448-ake-responder-ss \
ksym-default-lc-kex-512-x448-ake-responder-ss-internal \
ksym-default-lc-kex-512-x448-uake-initiator-init \
ksym-default-lc-kex-512-x448-uake-initiator-init-internal \
ksym-default-lc-kex-512-x448-uake-initiator-ss \
ksym-default-lc-kex-512-x448-uake-responder-ss \
ksym-default-lc-kex-512-x448-uake-responder-ss-internal \
ksym-default-lc-kex-768-ake-initiator-init \
ksym-default-lc-kex-768-ake-initiator-init-internal \
ksym-default-lc-kex-768-ake-initiator-ss \
ksym-default-lc-kex-768-ake-responder-ss \
ksym-default-lc-kex-768-ake-responder-ss-internal \
ksym-default-lc-kex-768-uake-initiator-init \
ksym-default-lc-kex-768-uake-initiator-init-internal \
ksym-default-lc-kex-768-uake-initiator-ss \
ksym-default-lc-kex-768-uake-responder-ss \
ksym-default-lc-kex-768-uake-responder-ss-internal \
ksym-default-lc-kex-768-x25519-ake-initiator-init \
ksym-default-lc-kex-768-x25519-ake-initiator-init-internal \
ksym-default-lc-kex-768-x25519-ake-initiator-ss \
ksym-default-lc-kex-768-x25519-ake-responder-ss \
ksym-default-lc-kex-768-x25519-ake-responder-ss-internal \
ksym-default-lc-kex-768-x25519-uake-initiator-init \
ksym-default-lc-kex-768-x25519-uake-initiator-init-internal \
ksym-default-lc-kex-768-x25519-uake-initiator-ss \
ksym-default-lc-kex-768-x25519-uake-responder-ss \
ksym-default-lc-kex-768-x25519-uake-responder-ss-internal \
ksym-default-lc-kex-768-x448-ake-initiator-init \
ksym-default-lc-kex-768-x448-ake-initiator-init-internal \
ksym-default-lc-kex-768-x448-ake-initiator-ss \
ksym-default-lc-kex-768-x448-ake-responder-ss \
ksym-default-lc-kex-768-x448-ake-responder-ss-internal \
ksym-default-lc-kex-768-x448-uake-initiator-init \
ksym-default-lc-kex-768-x448-uake-initiator-init-internal \
ksym-default-lc-kex-768-x448-uake-initiator-ss \
ksym-default-lc-kex-768-x448-uake-responder-ss \
ksym-default-lc-kex-768-x448-uake-responder-ss-internal \
ksym-default-lc-kex-ake-initiator-init \
ksym-default-lc-kex-ake-initiator-ss \
ksym-default-lc-kex-ake-responder-ss \
ksym-default-lc-kex-uake-initiator-init \
ksym-default-lc-kex-uake-initiator-ss \
ksym-default-lc-kex-uake-responder-ss \
ksym-default-lc-kex-x25519-ake-initiator-init \
ksym-default-lc-kex-x25519-ake-initiator-ss \
ksym-default-lc-kex-x25519-ake-responder-ss \
ksym-default-lc-kex-x25519-uake-initiator-init \
ksym-default-lc-kex-x25519-uake-initiator-ss \
ksym-default-lc-kex-x25519-uake-responder-ss \
ksym-default-lc-kex-x448-ake-initiator-init \
ksym-default-lc-kex-x448-ake-initiator-ss \
ksym-default-lc-kex-x448-ake-responder-ss \
ksym-default-lc-kex-x448-uake-initiator-init \
ksym-default-lc-kex-x448-uake-initiator-ss \
ksym-default-lc-kex-x448-uake-responder-ss \
ksym-default-lc-kh-alloc \
ksym-default-lc-kmac \
ksym-default-lc-kmac-aead \
ksym-default-lc-kmac-alg-status \
ksym-default-lc-kmac-alloc \
ksym-default-lc-kmac-ctx-alg-status \
ksym-default-lc-kmac-final \
ksym-default-lc-kmac-final-xof \
ksym-default-lc-kmac-init \
ksym-default-lc-kmac-macsize \
ksym-default-lc-kmac-reinit \
ksym-default-lc-kmac-rng \
ksym-default-lc-kmac-rng-alloc \
ksym-default-lc-kmac-update \
ksym-default-lc-kmac-xof \
ksym-default-lc-kmac-zero \
ksym-default-lc-kmac-zero-free \
ksym-default-lc-kmac256-drng \
ksym-default-lc-kmac256-drng-alloc \
ksym-default-lc-kyber-1024-dec \
ksym-default-lc-kyber-1024-dec-c \
ksym-default-lc-kyber-1024-dec-kdf \
ksym-default-lc-kyber-1024-dec-kdf-c \
ksym-default-lc-kyber-1024-enc \
ksym-default-lc-kyber-1024-enc-c \
ksym-default-lc-kyber-1024-enc-internal \
ksym-default-lc-kyber-1024-enc-kdf \
ksym-default-lc-kyber-1024-enc-kdf-c \
ksym-default-lc-kyber-1024-enc-kdf-internal \
ksym-default-lc-kyber-1024-ies-dec \
ksym-default-lc-kyber-1024-ies-dec-init \
ksym-default-lc-kyber-1024-ies-enc \
ksym-default-lc-kyber-1024-ies-enc-init \
ksym-default-lc-kyber-1024-ies-enc-init-internal \
ksym-default-lc-kyber-1024-ies-enc-internal \
ksym-default-lc-kyber-1024-keypair \
ksym-default-lc-kyber-1024-keypair-c \
ksym-default-lc-kyber-1024-keypair-from-seed \
ksym-default-lc-kyber-1024-keypair-from-seed-c \
ksym-default-lc-kyber-1024-pk-from-sk \
ksym-default-lc-kyber-1024-pk-from-sk-c \
ksym-default-lc-kyber-1024-x25519-dec \
ksym-default-lc-kyber-1024-x25519-dec-kdf \
ksym-default-lc-kyber-1024-x25519-enc \
ksym-default-lc-kyber-1024-x25519-enc-kdf \
ksym-default-lc-kyber-1024-x25519-enc-kdf-internal \
ksym-default-lc-kyber-1024-x25519-ies-dec \
ksym-default-lc-kyber-1024-x25519-ies-dec-init \
ksym-default-lc-kyber-1024-x25519-ies-enc \
ksym-default-lc-kyber-1024-x25519-ies-enc-init \
ksym-default-lc-kyber-1024-x25519-ies-enc-init-internal \
ksym-default-lc-kyber-1024-x25519-ies-enc-internal \
ksym-default-lc-kyber-1024-x25519-keypair \
ksym-default-lc-kyber-1024-x25519-pk-from-sk \
ksym-default-lc-kyber-1024-x448-dec \
ksym-default-lc-kyber-1024-x448-dec-kdf \
ksym-default-lc-kyber-1024-x448-enc \
ksym-default-lc-kyber-1024-x448-enc-kdf \
ksym-default-lc-kyber-1024-x448-enc-kdf-internal \
ksym-default-lc-kyber-1024-x448-ies-dec \
ksym-default-lc-kyber-1024-x448-ies-dec-init \
ksym-default-lc-kyber-1024-x448-ies-enc \
ksym-default-lc-kyber-1024-x448-ies-enc-init \
ksym-default-lc-kyber-1024-x448-ies-enc-init-internal \
ksym-default-lc-kyber-1024-x448-ies-enc-internal \
ksym-default-lc-kyber-1024-x448-keypair \
ksym-default-lc-kyber-1024-x448-pk-from-sk \
ksym-default-lc-kyber-512-dec \
ksym-default-lc-kyber-512-dec-c \
ksym-default-lc-kyber-512-dec-kdf \
ksym-default-lc-kyber-512-dec-kdf-c \
ksym-default-lc-kyber-512-enc \
ksym-default-lc-kyber-512-enc-c \
ksym-default-lc-kyber-512-enc-internal \
ksym-default-lc-kyber-512-enc-kdf \
ksym-default-lc-kyber-512-enc-kdf-c \
ksym-default-lc-kyber-512-enc-kdf-internal \
ksym-default-lc-kyber-512-ies-dec \
ksym-default-lc-kyber-512-ies-dec-init \
ksym-default-lc-kyber-512-ies-enc \
ksym-default-lc-kyber-512-ies-enc-init \
ksym-default-lc-kyber-512-ies-enc-init-internal \
ksym-default-lc-kyber-512-ies-enc-internal \
ksym-default-lc-kyber-512-keypair \
ksym-default-lc-kyber-512-keypair-c \
ksym-default-lc-kyber-512-keypair-from-seed \
ksym-default-lc-kyber-512-keypair-from-seed-c \
ksym-default-lc-kyber-512-pk-from-sk \
ksym-default-lc-kyber-512-pk-from-sk-c \
ksym-default-lc-kyber-512-x25519-dec \
ksym-default-lc-kyber-512-x25519-dec-kdf \
ksym-default-lc-kyber-512-x25519-enc \
ksym-default-lc-kyber-512-x25519-enc-kdf \
ksym-default-lc-kyber-512-x25519-enc-kdf-internal \
ksym-default-lc-kyber-512-x25519-ies-dec \
ksym-default-lc-kyber-512-x25519-ies-dec-init \
ksym-default-lc-kyber-512-x25519-ies-enc \
ksym-default-lc-kyber-512-x25519-ies-enc-init \
ksym-default-lc-kyber-512-x25519-ies-enc-init-internal \
ksym-default-lc-kyber-512-x25519-ies-enc-internal \
ksym-default-lc-kyber-512-x25519-keypair \
ksym-default-lc-kyber-512-x25519-pk-from-sk \
ksym-default-lc-kyber-512-x448-dec \
ksym-default-lc-kyber-512-x448-dec-kdf \
ksym-default-lc-kyber-512-x448-enc \
ksym-default-lc-kyber-512-x448-enc-kdf \
ksym-default-lc-kyber-512-x448-enc-kdf-internal \
ksym-default-lc-kyber-512-x448-ies-dec \
ksym-default-lc-kyber-512-x448-ies-dec-init \
ksym-default-lc-kyber-512-x448-ies-enc \
ksym-default-lc-kyber-512-x448-ies-enc-init \
ksym-default-lc-kyber-512-x448-ies-enc-init-internal \
ksym-default-lc-kyber-512-x448-ies-enc-internal \
ksym-default-lc-kyber-512-x448-keypair \
ksym-default-lc-kyber-512-x448-pk-from-sk \
ksym-default-lc-kyber-768-dec \
ksym-default-lc-kyber-768-dec-c \
ksym-default-lc-kyber-768-dec-kdf \
ksym-default-lc-kyber-768-dec-kdf-c \
ksym-default-lc-kyber-768-enc \
ksym-default-lc-kyber-768-enc-c \
ksym-default-lc-kyber-768-enc-internal \
ksym-default-lc-kyber-768-enc-kdf \
ksym-default-lc-kyber-768-enc-kdf-c \
ksym-default-lc-kyber-768-enc-kdf-internal \
ksym-default-lc-kyber-768-ies-dec \
ksym-default-lc-kyber-768-ies-dec-init \
ksym-default-lc-kyber-768-ies-enc \
ksym-default-lc-kyber-768-ies-enc-init \
ksym-default-lc-kyber-768-ies-enc-init-internal \
ksym-default-lc-kyber-768-ies-enc-internal \
ksym-default-lc-kyber-768-keypair \
ksym-default-lc-kyber-768-keypair-c \
ksym-default-lc-kyber-768-keypair-from-seed \
ksym-default-lc-kyber-768-keypair-from-seed-c \
ksym-default-lc-kyber-768-pk-from-sk \
ksym-default-lc-kyber-768-pk-from-sk-c \
ksym-default-lc-kyber-768-x25519-dec \
ksym-default-lc-kyber-768-x25519-dec-kdf \
ksym-default-lc-kyber-768-x25519-enc \
ksym-default-lc-kyber-768-x25519-enc-kdf \
ksym-default-lc-kyber-768-x25519-enc-kdf-internal \
ksym-default-lc-kyber-768-x25519-ies-dec \
ksym-default-lc-kyber-768-x25519-ies-dec-init \
ksym-default-lc-kyber-768-x25519-ies-enc \
ksym-default-lc-kyber-768-x25519-ies-enc-init \
ksym-default-lc-kyber-768-x25519-ies-enc-init-internal \
ksym-default-lc-kyber-768-x25519-ies-enc-internal \
ksym-default-lc-kyber-768-x25519-keypair \
ksym-default-lc-kyber-768-x25519-pk-from-sk \
ksym-default-lc-kyber-768-x448-dec \
ksym-default-lc-kyber-768-x448-dec-kdf \
ksym-default-lc-kyber-768-x448-enc \
ksym-default-lc-kyber-768-x448-enc-kdf \
ksym-default-lc-kyber-768-x448-enc-kdf-internal \
ksym-default-lc-kyber-768-x448-ies-dec \
ksym-default-lc-kyber-768-x448-ies-dec-init \
ksym-default-lc-kyber-768-x448-ies-enc \
ksym-default-lc-kyber-768-x448-ies-enc-init \
ksym-default-lc-kyber-768-x448-ies-enc-init-internal \
ksym-default-lc-kyber-768-x448-ies-enc-internal \
ksym-default-lc-kyber-768-x448-keypair \
ksym-default-lc-kyber-768-x448-pk-from-sk \
ksym-default-lc-kyber-alg-status \
ksym-default-lc-kyber-ct-load \
ksym-default-lc-kyber-ct-ptr \
ksym-default-lc-kyber-ct-size \
ksym-default-lc-kyber-ct-type \
ksym-default-lc-kyber-dec \
ksym-default-lc-kyber-dec-kdf \
ksym-default-lc-kyber-enc \
ksym-default-lc-kyber-enc-kdf \
ksym-default-lc-kyber-ies-dec \
ksym-default-lc-kyber-ies-dec-final \
ksym-default-lc-kyber-ies-dec-init \
ksym-default-lc-kyber-ies-dec-update \
ksym-default-lc-kyber-ies-enc \
ksym-default-lc-kyber-ies-enc-final \
ksym-default-lc-kyber-ies-enc-init \
ksym-default-lc-kyber-ies-enc-update \
ksym-default-lc-kyber-keypair \
ksym-default-lc-kyber-keypair-from-seed \
ksym-default-lc-kyber-pct \
ksym-default-lc-kyber-pk-from-sk \
ksym-default-lc-kyber-pk-load \
ksym-default-lc-kyber-pk-ptr \
ksym-default-lc-kyber-pk-size \
ksym-default-lc-kyber-pk-type \
ksym-default-lc-kyber-sk-load \
ksym-default-lc-kyber-sk-ptr \
ksym-default-lc-kyber-sk-size \
ksym-default-lc-kyber-sk-type \
ksym-default-lc-kyber-ss-load \
ksym-default-lc-kyber-ss-ptr \
ksym-default-lc-kyber-ss-size \
ksym-default-lc-kyber-ss-type \
ksym-default-lc-kyber-x25519-ct-load \
ksym-default-lc-kyber-x25519-ct-ptr \
ksym-default-lc-kyber-x25519-ct-size \
ksym-default-lc-kyber-x25519-ct-type \
ksym-default-lc-kyber-x25519-dec \
ksym-default-lc-kyber-x25519-dec-kdf \
ksym-default-lc-kyber-x25519-enc \
ksym-default-lc-kyber-x25519-enc-kdf \
ksym-default-lc-kyber-x25519-ies-dec \
ksym-default-lc-kyber-x25519-ies-dec-final \
ksym-default-lc-kyber-x25519-ies-dec-init \
ksym-default-lc-kyber-x25519-ies-dec-update \
ksym-default-lc-kyber-x25519-ies-enc \
ksym-default-lc-kyber-x25519-ies-enc-final \
ksym-default-lc-kyber-x25519-ies-enc-init \
ksym-default-lc-kyber-x25519-ies-enc-update \
ksym-default-lc-kyber-x25519-keypair \
ksym-default-lc-kyber-x25519-pk-from-sk \
ksym-default-lc-kyber-x25519-pk-load \
ksym-default-lc-kyber-x25519-pk-ptr \
ksym-default-lc-kyber-x25519-pk-size \
ksym-default-lc-kyber-x25519-pk-type \
ksym-default-lc-kyber-x25519-sk-load \
ksym-default-lc-kyber-x25519-sk-ptr \
ksym-default-lc-kyber-x25519-sk-size \
ksym-default-lc-kyber-x25519-sk-type \
ksym-default-lc-kyber-x25519-ss-load \
ksym-default-lc-kyber-x25519-ss-ptr \
ksym-default-lc-kyber-x25519-ss-size \
ksym-default-lc-kyber-x25519-ss-type \
ksym-default-lc-kyber-x448-ct-load \
ksym-default-lc-kyber-x448-ct-ptr \
ksym-default-lc-kyber-x448-ct-size \
ksym-default-lc-kyber-x448-ct-type \
ksym-default-lc-kyber-x448-dec \
ksym-default-lc-kyber-x448-dec-kdf \
ksym-default-lc-kyber-x448-enc \
ksym-default-lc-kyber-x448-enc-kdf \
ksym-default-lc-kyber-x448-ies-dec \
ksym-default-lc-kyber-x448-ies-dec-final \
ksym-default-lc-kyber-x448-ies-dec-init \
ksym-default-lc-kyber-x448-ies-dec-update \
ksym-default-lc-kyber-x448-ies-enc \
ksym-default-lc-kyber-x448-ies-enc-final \
ksym-default-lc-kyber-x448-ies-enc-init \
ksym-default-lc-kyber-x448-ies-enc-update \
ksym-default-lc-kyber-x448-keypair \
ksym-default-lc-kyber-x448-pk-from-sk \
ksym-default-lc-kyber-x448-pk-load \
ksym-default-lc-kyber-x448-pk-ptr \
ksym-default-lc-kyber-x448-pk-size \
ksym-default-lc-kyber-x448-pk-type \
ksym-default-lc-kyber-x448-sk-load \
ksym-default-lc-kyber-x448-sk-ptr \
ksym-default-lc-kyber-x448-sk-size \
ksym-default-lc-kyber-x448-sk-type \
ksym-default-lc-kyber-x448-ss-load \
ksym-default-lc-kyber-x448-ss-ptr \
ksym-default-lc-kyber-x448-ss-size \
ksym-default-lc-kyber-x448-ss-type \
ksym-default-lc-lib-alg-status \
ksym-default-lc-look-up-OID \
ksym-default-lc-memcmp-secure \
ksym-default-lc-memcpy-secure \
ksym-default-lc-mode-cbc-c \
ksym-default-lc-mode-ctr-c \
ksym-default-lc-mode-xts-c \
ksym-default-lc-pbkdf2 \
ksym-default-lc-pbkdf2-alg-status \
ksym-default-lc-pem-decode \
ksym-default-lc-pem-decode-len \
ksym-default-lc-pem-encode \
ksym-default-lc-pem-encode-len \
ksym-default-lc-pem-is-encoded \
ksym-default-lc-pem-type \
ksym-default-lc-pkcs7-decode \
ksym-default-lc-pkcs7-decode-ctx \
ksym-default-lc-pkcs7-decode-ctx-clear \
ksym-default-lc-pkcs7-decode-ctx-init \
ksym-default-lc-pkcs7-decode-ctx-set-aa-content-type \
ksym-default-lc-pkcs7-decode-ctx-set-pkcs7 \
ksym-default-lc-pkcs7-encode \
ksym-default-lc-pkcs7-encode-ctx \
ksym-default-lc-pkcs7-encode-ctx-clear \
ksym-default-lc-pkcs7-encode-ctx-init \
ksym-default-lc-pkcs7-encode-ctx-set-pkcs7 \
ksym-default-lc-pkcs7-encode-ctx-set-signer-data-type \
ksym-default-lc-pkcs7-get-content-data \
ksym-default-lc-pkcs7-get-digest \
ksym-default-lc-pkcs7-message-clear \
ksym-default-lc-pkcs7-set-certificate \
ksym-default-lc-pkcs7-set-data \
ksym-default-lc-pkcs7-set-data-with-type \
ksym-default-lc-pkcs7-set-signer \
ksym-default-lc-pkcs7-supply-detached-data \
ksym-default-lc-pkcs7-trust-store-add \
ksym-default-lc-pkcs7-trust-store-clear \
ksym-default-lc-pkcs7-verify \
ksym-default-lc-pkcs8-decode \
ksym-default-lc-pkcs8-encode \
ksym-default-lc-pkcs8-get-signature-size-from-sk \
ksym-default-lc-pkcs8-key-type \
ksym-default-lc-pkcs8-message-clear \
ksym-default-lc-pkcs8-set-privkey \
ksym-default-lc-pkcs8-signature-gen \
ksym-default-lc-poly1305-final \
ksym-default-lc-poly1305-init \
ksym-default-lc-poly1305-update \
ksym-default-lc-rerun-one-selftest \
ksym-default-lc-rerun-selftests \
ksym-default-lc-rng-alg-status \
ksym-default-lc-rng-check \
ksym-default-lc-rng-ctx-alg-status \
ksym-default-lc-rng-generate \
ksym-default-lc-rng-seed \
ksym-default-lc-rng-set-seeded \
ksym-default-lc-rng-zero \
ksym-default-lc-rng-zero-free \
ksym-default-lc-seeded-rng \
ksym-default-lc-sh-alloc \
ksym-default-lc-sha256 \
ksym-default-lc-sha256-arm-ce \
ksym-default-lc-sha256-arm-neon \
ksym-default-lc-sha256-avx2 \
ksym-default-lc-sha256-c \
ksym-default-lc-sha256-riscv \
ksym-default-lc-sha256-riscv-zbb \
ksym-default-lc-sha256-shani \
ksym-default-lc-sha3-224 \
ksym-default-lc-sha3-224-arm-asm \
ksym-default-lc-sha3-224-arm-ce \
ksym-default-lc-sha3-224-arm-neon \
ksym-default-lc-sha3-224-avx2 \
ksym-default-lc-sha3-224-avx512 \
ksym-default-lc-sha3-224-c \
ksym-default-lc-sha3-224-riscv-asm \
ksym-default-lc-sha3-224-riscv-asm-zbb \
ksym-default-lc-sha3-256 \
ksym-default-lc-sha3-256-arm-asm \
ksym-default-lc-sha3-256-arm-ce \
ksym-default-lc-sha3-256-arm-neon \
ksym-default-lc-sha3-256-avx2 \
ksym-default-lc-sha3-256-avx512 \
ksym-default-lc-sha3-256-c \
ksym-default-lc-sha3-256-riscv-asm \
ksym-default-lc-sha3-256-riscv-asm-zbb \
ksym-default-lc-sha3-384 \
ksym-default-lc-sha3-384-arm-asm \
ksym-default-lc-sha3-384-arm-ce \
ksym-default-lc-sha3-384-arm-neon \
ksym-default-lc-sha3-384-avx2 \
ksym-default-lc-sha3-384-avx512 \
ksym-default-lc-sha3-384-c \
ksym-default-lc-sha3-384-riscv-asm \
ksym-default-lc-sha3-384-riscv-asm-zbb \
ksym-default-lc-sha3-512 \
ksym-default-lc-sha3-512-arm-asm \
ksym-default-lc-sha3-512-arm-ce \
ksym-default-lc-sha3-512-arm-neon \
ksym-default-lc-sha3-512-avx2 \
ksym-default-lc-sha3-512-avx512 \
ksym-default-lc-sha3-512-c \
ksym-default-lc-sha3-512-riscv-asm \
ksym-default-lc-sha3-512-riscv-asm-zbb \
ksym-default-lc-sha384 \
ksym-default-lc-sha384-arm-ce \
ksym-default-lc-sha384-arm-neon \
ksym-default-lc-sha384-avx2 \
ksym-default-lc-sha384-c \
ksym-default-lc-sha384-riscv \
ksym-default-lc-sha384-riscv-zbb \
ksym-default-lc-sha384-shani \
ksym-default-lc-sha512 \
ksym-default-lc-sha512-arm-ce \
ksym-default-lc-sha512-arm-neon \
ksym-default-lc-sha512-avx2 \
ksym-default-lc-sha512-c \
ksym-default-lc-sha512-riscv \
ksym-default-lc-sha512-riscv-zbb \
ksym-default-lc-sha512-shani \
ksym-default-lc-shake128 \
ksym-default-lc-shake128-arm-asm \
ksym-default-lc-shake128-arm-ce \
ksym-default-lc-shake128-arm-neon \
ksym-default-lc-shake128-avx2 \
ksym-default-lc-shake128-avx512 \
ksym-default-lc-shake128-c \
ksym-default-lc-shake128-riscv-asm \
ksym-default-lc-shake128-riscv-asm-zbb \
ksym-default-lc-shake256 \
ksym-default-lc-shake256-arm-asm \
ksym-default-lc-shake256-arm-ce \
ksym-default-lc-shake256-arm-neon \
ksym-default-lc-shake256-avx2 \
ksym-default-lc-shake256-avx512 \
ksym-default-lc-shake256-c \
ksym-default-lc-shake256-riscv-asm \
ksym-default-lc-shake256-riscv-asm-zbb \
ksym-default-lc-shake512 \
ksym-default-lc-shake512-arm-asm \
ksym-default-lc-shake512-arm-ce \
ksym-default-lc-shake512-arm-neon \
ksym-default-lc-shake512-avx2 \
ksym-default-lc-shake512-avx512 \
ksym-default-lc-shake512-c \
ksym-default-lc-shake512-riscv-asm \
ksym-default-lc-shake512-riscv-asm-zbb \
ksym-default-lc-sphincs-alg-status \
ksym-default-lc-sphincs-ctx-alloc \
ksym-default-lc-sphincs-ctx-hash \
ksym-default-lc-sphincs-ctx-internal \
ksym-default-lc-sphincs-ctx-userctx \
ksym-default-lc-sphincs-ctx-zero \
ksym-default-lc-sphincs-ctx-zero-free \
ksym-default-lc-sphincs-keypair \
ksym-default-lc-sphincs-keypair-from-seed \
ksym-default-lc-sphincs-pct \
ksym-default-lc-sphincs-pk-from-sk \
ksym-default-lc-sphincs-pk-load \
ksym-default-lc-sphincs-pk-ptr \
ksym-default-lc-sphincs-pk-set-keytype-fast \
ksym-default-lc-sphincs-pk-set-keytype-small \
ksym-default-lc-sphincs-pk-size \
ksym-default-lc-sphincs-pk-type \
ksym-default-lc-sphincs-shake-128f-ctx-alloc \
ksym-default-lc-sphincs-shake-128f-ctx-zero-free \
ksym-default-lc-sphincs-shake-128f-keypair \
ksym-default-lc-sphincs-shake-128f-keypair-from-seed \
ksym-default-lc-sphincs-shake-128f-pk-from-sk \
ksym-default-lc-sphincs-shake-128f-sign \
ksym-default-lc-sphincs-shake-128f-sign-ctx \
ksym-default-lc-sphincs-shake-128f-sign-final \
ksym-default-lc-sphincs-shake-128f-sign-init \
ksym-default-lc-sphincs-shake-128f-sign-update \
ksym-default-lc-sphincs-shake-128f-verify \
ksym-default-lc-sphincs-shake-128f-verify-ctx \
ksym-default-lc-sphincs-shake-128f-verify-final \
ksym-default-lc-sphincs-shake-128f-verify-init \
ksym-default-lc-sphincs-shake-128f-verify-update \
ksym-default-lc-sphincs-shake-128s-ctx-alloc \
ksym-default-lc-sphincs-shake-128s-ctx-zero-free \
ksym-default-lc-sphincs-shake-128s-keypair \
ksym-default-lc-sphincs-shake-128s-keypair-from-seed \
ksym-default-lc-sphincs-shake-128s-pk-from-sk \
ksym-default-lc-sphincs-shake-128s-sign \
ksym-default-lc-sphincs-shake-128s-sign-ctx \
ksym-default-lc-sphincs-shake-128s-sign-final \
ksym-default-lc-sphincs-shake-128s-sign-init \
ksym-default-lc-sphincs-shake-128s-sign-update \
ksym-default-lc-sphincs-shake-128s-verify \
ksym-default-lc-sphincs-shake-128s-verify-ctx \
ksym-default-lc-sphincs-shake-128s-verify-final \
ksym-default-lc-sphincs-shake-128s-verify-init \
ksym-default-lc-sphincs-shake-128s-verify-update \
ksym-default-lc-sphincs-shake-192f-ctx-alloc \
ksym-default-lc-sphincs-shake-192f-ctx-zero-free \
ksym-default-lc-sphincs-shake-192f-keypair \
ksym-default-lc-sphincs-shake-192f-keypair-from-seed \
ksym-default-lc-sphincs-shake-192f-pk-from-sk \
ksym-default-lc-sphincs-shake-192f-sign \
ksym-default-lc-sphincs-shake-192f-sign-ctx \
ksym-default-lc-sphincs-shake-192f-sign-final \
ksym-default-lc-sphincs-shake-192f-sign-init \
ksym-default-lc-sphincs-shake-192f-sign-update \
ksym-default-lc-sphincs-shake-192f-verify \
ksym-default-lc-sphincs-shake-192f-verify-ctx \
ksym-default-lc-sphincs-shake-192f-verify-final \
ksym-default-lc-sphincs-shake-192f-verify-init \
ksym-default-lc-sphincs-shake-192f-verify-update \
ksym-default-lc-sphincs-shake-192s-ctx-alloc \
ksym-default-lc-sphincs-shake-192s-ctx-zero-free \
ksym-default-lc-sphincs-shake-192s-keypair \
ksym-default-lc-sphincs-shake-192s-keypair-from-seed \
ksym-default-lc-sphincs-shake-192s-pk-from-sk \
ksym-default-lc-sphincs-shake-192s-sign \
ksym-default-lc-sphincs-shake-192s-sign-ctx \
ksym-default-lc-sphincs-shake-192s-sign-final \
ksym-default-lc-sphincs-shake-192s-sign-init \
ksym-default-lc-sphincs-shake-192s-sign-update \
ksym-default-lc-sphincs-shake-192s-verify \
ksym-default-lc-sphincs-shake-192s-verify-ctx \
ksym-default-lc-sphincs-shake-192s-verify-final \
ksym-default-lc-sphincs-shake-192s-verify-init \
ksym-default-lc-sphincs-shake-192s-verify-update \
ksym-default-lc-sphincs-shake-256f-ctx-alloc \
ksym-default-lc-sphincs-shake-256f-ctx-zero-free \
ksym-default-lc-sphincs-shake-256f-keypair \
ksym-default-lc-sphincs-shake-256f-keypair-from-seed \
ksym-default-lc-sphincs-shake-256f-pk-from-sk \
ksym-default-lc-sphincs-shake-256f-sign \
ksym-default-lc-sphincs-shake-256f-sign-ctx \
ksym-default-lc-sphincs-shake-256f-sign-final \
ksym-default-lc-sphincs-shake-256f-sign-init \
ksym-default-lc-sphincs-shake-256f-sign-update \
ksym-default-lc-sphincs-shake-256f-verify \
ksym-default-lc-sphincs-shake-256f-verify-ctx \
ksym-default-lc-sphincs-shake-256f-verify-final \
ksym-default-lc-sphincs-shake-256f-verify-init \
ksym-default-lc-sphincs-shake-256f-verify-update \
ksym-default-lc-sphincs-shake-256s-ctx-alloc \
ksym-default-lc-sphincs-shake-256s-ctx-zero-free \
ksym-default-lc-sphincs-shake-256s-keypair \
ksym-default-lc-sphincs-shake-256s-keypair-from-seed \
ksym-default-lc-sphincs-shake-256s-pk-from-sk \
ksym-default-lc-sphincs-shake-256s-sign \
ksym-default-lc-sphincs-shake-256s-sign-ctx \
ksym-default-lc-sphincs-shake-256s-sign-final \
ksym-default-lc-sphincs-shake-256s-sign-init \
ksym-default-lc-sphincs-shake-256s-sign-update \
ksym-default-lc-sphincs-shake-256s-verify \
ksym-default-lc-sphincs-shake-256s-verify-ctx \
ksym-default-lc-sphincs-shake-256s-verify-final \
ksym-default-lc-sphincs-shake-256s-verify-init \
ksym-default-lc-sphincs-shake-256s-verify-update \
ksym-default-lc-sphincs-sig-load \
ksym-default-lc-sphincs-sig-ptr \
ksym-default-lc-sphincs-sig-size \
ksym-default-lc-sphincs-sig-type \
ksym-default-lc-sphincs-sign \
ksym-default-lc-sphincs-sign-ctx \
ksym-default-lc-sphincs-sign-final \
ksym-default-lc-sphincs-sign-init \
ksym-default-lc-sphincs-sign-update \
ksym-default-lc-sphincs-sk-load \
ksym-default-lc-sphincs-sk-ptr \
ksym-default-lc-sphincs-sk-set-keytype-fast \
ksym-default-lc-sphincs-sk-set-keytype-small \
ksym-default-lc-sphincs-sk-size \
ksym-default-lc-sphincs-sk-type \
ksym-default-lc-sphincs-verify \
ksym-default-lc-sphincs-verify-ctx \
ksym-default-lc-sphincs-verify-final \
ksym-default-lc-sphincs-verify-init \
ksym-default-lc-sphincs-verify-update \
ksym-default-lc-sponge \
ksym-default-lc-sponge-add-bytes \
ksym-default-lc-sponge-extract-bytes \
ksym-default-lc-sponge-newstate \
ksym-default-lc-status \
ksym-default-lc-status-get-result \
ksym-default-lc-sym-alg-status \
ksym-default-lc-sym-alloc \
ksym-default-lc-sym-ctx-alg-status \
ksym-default-lc-sym-decrypt \
ksym-default-lc-sym-decrypt-iv \
ksym-default-lc-sym-encrypt \
ksym-default-lc-sym-encrypt-iv \
ksym-default-lc-sym-getiv \
ksym-default-lc-sym-init \
ksym-default-lc-sym-init-iv \
ksym-default-lc-sym-setiv \
ksym-default-lc-sym-setkey \
ksym-default-lc-sym-zero \
ksym-default-lc-sym-zero-free \
ksym-default-lc-symhmac-aead \
ksym-default-lc-symkmac-aead \
ksym-default-lc-uuid-bin2hex \
ksym-default-lc-uuid-hex2bin \
ksym-default-lc-uuid-random \
ksym-default-lc-uuid-time \
ksym-default-lc-x25519-alg-status \
ksym-default-lc-x25519-keypair \
ksym-default-lc-x25519-pk-load \
ksym-default-lc-x25519-pk-ptr \
ksym-default-lc-x25519-sk-load \
ksym-default-lc-x25519-sk-ptr \
ksym-default-lc-x25519-ss \
ksym-default-lc-x25519-ss-load \
ksym-default-lc-x25519-ss-ptr \
ksym-default-lc-x448-alg-status \
ksym-default-lc-x448-keypair \
ksym-default-lc-x448-pk-load \
ksym-default-lc-x448-pk-ptr \
ksym-default-lc-x448-sk-load \
ksym-default-lc-x448-sk-ptr \
ksym-default-lc-x448-ss \
ksym-default-lc-x448-ss-load \
ksym-default-lc-x448-ss-ptr \
ksym-default-lc-x509-cert-check-issuer-ca \
ksym-default-lc-x509-cert-clear \
ksym-default-lc-x509-cert-decode \
ksym-default-lc-x509-cert-encode \
ksym-default-lc-x509-cert-get-akid \
ksym-default-lc-x509-cert-get-eku \
ksym-default-lc-x509-cert-get-eku-val \
ksym-default-lc-x509-cert-get-issuer-c \
ksym-default-lc-x509-cert-get-issuer-cn \
ksym-default-lc-x509-cert-get-issuer-email \
ksym-default-lc-x509-cert-get-issuer-o \
ksym-default-lc-x509-cert-get-issuer-ou \
ksym-default-lc-x509-cert-get-issuer-st \
ksym-default-lc-x509-cert-get-keyusage \
ksym-default-lc-x509-cert-get-keyusage-val \
ksym-default-lc-x509-cert-get-pubkey \
ksym-default-lc-x509-cert-get-san-dns \
ksym-default-lc-x509-cert-get-san-ip \
ksym-default-lc-x509-cert-get-serial \
ksym-default-lc-x509-cert-get-skid \
ksym-default-lc-x509-cert-get-subject-c \
ksym-default-lc-x509-cert-get-subject-cn \
ksym-default-lc-x509-cert-get-subject-email \
ksym-default-lc-x509-cert-get-subject-o \
ksym-default-lc-x509-cert-get-subject-ou \
ksym-default-lc-x509-cert-get-subject-st \
ksym-default-lc-x509-cert-get-valid-from \
ksym-default-lc-x509-cert-get-valid-to \
ksym-default-lc-x509-cert-load-pk-dilithium-ed25519 \
ksym-default-lc-x509-cert-load-pk-dilithium-ed448 \
ksym-default-lc-x509-cert-set-akid \
ksym-default-lc-x509-cert-set-ca \
ksym-default-lc-x509-cert-set-ca-pathlen \
ksym-default-lc-x509-cert-set-eku \
ksym-default-lc-x509-cert-set-eku-val \
ksym-default-lc-x509-cert-set-issuer-c \
ksym-default-lc-x509-cert-set-issuer-cn \
ksym-default-lc-x509-cert-set-issuer-email \
ksym-default-lc-x509-cert-set-issuer-o \
ksym-default-lc-x509-cert-set-issuer-ou \
ksym-default-lc-x509-cert-set-issuer-st \
ksym-default-lc-x509-cert-set-keyusage \
ksym-default-lc-x509-cert-set-keyusage-val \
ksym-default-lc-x509-cert-set-san-dns \
ksym-default-lc-x509-cert-set-san-email \
ksym-default-lc-x509-cert-set-san-ip \
ksym-default-lc-x509-cert-set-serial \
ksym-default-lc-x509-cert-set-signer \
ksym-default-lc-x509-cert-set-skid \
ksym-default-lc-x509-cert-set-subject-c \
ksym-default-lc-x509-cert-set-subject-cn \
ksym-default-lc-x509-cert-set-subject-email \
ksym-default-lc-x509-cert-set-subject-o \
ksym-default-lc-x509-cert-set-subject-ou \
ksym-default-lc-x509-cert-set-subject-st \
ksym-default-lc-x509-cert-set-valid-from \
ksym-default-lc-x509-cert-set-valid-to \
ksym-default-lc-x509-cert-verify \
ksym-default-lc-x509-csr-decode \
ksym-default-lc-x509-csr-encode \
ksym-default-lc-x509-dec-san-ip \
ksym-default-lc-x509-enc-san-ip \
ksym-default-lc-x509-get-signature-size-from-cert \
ksym-default-lc-x509-get-signature-size-from-sk \
ksym-default-lc-x509-hash-to-name \
ksym-default-lc-x509-hash-to-oid \
ksym-default-lc-x509-keypair-data-alloc \
ksym-default-lc-x509-keypair-data-zero-free \
ksym-default-lc-x509-keypair-gen \
ksym-default-lc-x509-keypair-load \
ksym-default-lc-x509-keypair-pk \
ksym-default-lc-x509-keys-alloc \
ksym-default-lc-x509-keys-dilithium-alloc \
ksym-default-lc-x509-keys-dilithium-ed25519-alloc \
ksym-default-lc-x509-keys-dilithium-ed448-alloc \
ksym-default-lc-x509-keys-sphincs-alloc \
ksym-default-lc-x509-keys-zero-free \
ksym-default-lc-x509-name-to-eku \
ksym-default-lc-x509-name-to-hash \
ksym-default-lc-x509-name-to-keyusage \
ksym-default-lc-x509-oid-to-hash \
ksym-default-lc-x509-pk-decode \
ksym-default-lc-x509-pkey-name-to-algorithm \
ksym-default-lc-x509-policy-can-validate-crls \
ksym-default-lc-x509-policy-cert-subject-match \
ksym-default-lc-x509-policy-cert-valid \
ksym-default-lc-x509-policy-is-ca \
ksym-default-lc-x509-policy-is-root-ca \
ksym-default-lc-x509-policy-is-selfsigned \
ksym-default-lc-x509-policy-match-akid \
ksym-default-lc-x509-policy-match-extended-key-usage \
ksym-default-lc-x509-policy-match-key-usage \
ksym-default-lc-x509-policy-match-skid \
ksym-default-lc-x509-policy-time-valid \
ksym-default-lc-x509-policy-time-valid-now \
ksym-default-lc-x509-policy-verify-cert \
ksym-default-lc-x509-privkeys-alloc \
ksym-default-lc-x509-privkeys-dilithium-alloc \
ksym-default-lc-x509-privkeys-dilithium-ed25519-alloc \
ksym-default-lc-x509-privkeys-dilithium-ed448-alloc \
ksym-default-lc-x509-privkeys-sphincs-alloc \
ksym-default-lc-x509-sig-type-to-hash \
ksym-default-lc-x509-sig-type-to-name \
ksym-default-lc-x509-signature-gen \
ksym-default-lc-x509-signature-verify \
ksym-default-lc-x509-sk-decode \
ksym-default-lc-x509-sk-encode \
ksym-default-lc-x509-sufficient-size \
ksym-default-lc-xdrbg128-drng \
ksym-default-lc-xdrbg128-drng-alloc \
ksym-default-lc-xdrbg256-drng \
ksym-default-lc-xdrbg256-drng-alloc \
ksym-default-lc-xdrbg512-drng \
ksym-default-lc-xdrbg512-drng-alloc \
ksym-default-lc-xof \
leancrypto-kmp \
leancrypto-kmp-default \
leancrypto-kmp-default-k7.2.4-1 \
multiversion-kernel"

RDEPENDS:${PN} += "/usr/bin/sh \
coreutils \
grep \
ksym-default---crypto-memneq \
ksym-default---fortify-panic \
ksym-default---free-pages \
ksym-default---init-swait-queue-head \
ksym-default---kmalloc-cache-noprof \
ksym-default---kmalloc-large-noprof \
ksym-default---kmalloc-noprof \
ksym-default---stack-chk-fail \
ksym-default---warn-printk \
ksym-default---write-overflow-field \
ksym-default--printk \
ksym-default-alloc-pages-noprof \
ksym-default-alt-cb-patch-nops \
ksym-default-bin2hex \
ksym-default-complete \
ksym-default-crypto-aead-decrypt \
ksym-default-crypto-aead-encrypt \
ksym-default-crypto-aead-setauthsize \
ksym-default-crypto-aead-setkey \
ksym-default-crypto-alloc-aead \
ksym-default-crypto-alloc-kpp \
ksym-default-crypto-alloc-rng \
ksym-default-crypto-alloc-shash \
ksym-default-crypto-alloc-sig \
ksym-default-crypto-alloc-skcipher \
ksym-default-crypto-destroy-tfm \
ksym-default-crypto-register-aeads \
ksym-default-crypto-register-alg \
ksym-default-crypto-register-kpp \
ksym-default-crypto-register-rngs \
ksym-default-crypto-register-shashes \
ksym-default-crypto-register-sig \
ksym-default-crypto-register-skciphers \
ksym-default-crypto-rng-reset \
ksym-default-crypto-shash-finup \
ksym-default-crypto-shash-init \
ksym-default-crypto-shash-setkey \
ksym-default-crypto-skcipher-decrypt \
ksym-default-crypto-skcipher-encrypt \
ksym-default-crypto-skcipher-setkey \
ksym-default-crypto-unregister-aeads \
ksym-default-crypto-unregister-alg \
ksym-default-crypto-unregister-kpp \
ksym-default-crypto-unregister-rngs \
ksym-default-crypto-unregister-shashes \
ksym-default-crypto-unregister-sig \
ksym-default-crypto-unregister-skciphers \
ksym-default-get-random-bytes \
ksym-default-jiffies \
ksym-default-kernel-neon-begin \
ksym-default-kernel-neon-end \
ksym-default-kfree \
ksym-default-kfree-sensitive \
ksym-default-kmalloc-caches \
ksym-default-ktime-get-with-offset \
ksym-default-memcmp \
ksym-default-memcpy \
ksym-default-memcpy-from-sglist \
ksym-default-memcpy-to-sglist \
ksym-default-memset \
ksym-default-memstart-addr \
ksym-default-module-layout \
ksym-default-mutex-init-generic \
ksym-default-mutex-lock \
ksym-default-mutex-unlock \
ksym-default-param-ops-uint \
ksym-default-pfn-is-map-memory \
ksym-default-proc-create-single-data \
ksym-default-random-kmalloc-seed \
ksym-default-remove-proc-subtree \
ksym-default-scatterwalk-ffwd \
ksym-default-seq-write \
ksym-default-sg-copy-from-buffer \
ksym-default-sg-copy-to-buffer \
ksym-default-sg-init-one \
ksym-default-sg-init-table \
ksym-default-sg-nents-for-len \
ksym-default-sg-pcopy-from-buffer \
ksym-default-skcipher-walk-aead-decrypt \
ksym-default-skcipher-walk-aead-encrypt \
ksym-default-skcipher-walk-done \
ksym-default-skcipher-walk-virt \
ksym-default-snprintf \
ksym-default-strlen \
ksym-default-strnlen \
ksym-default-wait-for-completion \
suse-kernel-rpm-scriptlets"

inherit rpm
