SUMMARY = "Cooling control and monitoring"
DESCRIPTION = "This is the system daemon for CoolerControl, \
an application for monitoring and controlling supported cooling \
devices. It features flexible control options, and live thermal data."
LICENSE = "GPL-3.0-or-later"

PV = "4.3.1"

RPM_NAME = "coolercontrold-4.3.1-1.3.aarch64.rpm"
RPM_HASH = "1d785ab39fb354a4145cfecee06710a31f7f4f819af360a42d38dbb094c45667be59f7001f21fc89090ef20513d2d11892afe62e37af1ce80e1c9d3f9fc0fb59"

RPROVIDES:${PN} += "bundled-rust-crate-adler2 \
bundled-rust-crate-aead \
bundled-rust-crate-aes \
bundled-rust-crate-aes-gcm \
bundled-rust-crate-ahash \
bundled-rust-crate-aho-corasick \
bundled-rust-crate-aide \
bundled-rust-crate-aligned-vec \
bundled-rust-crate-alloc-no-stdlib \
bundled-rust-crate-alloc-stdlib \
bundled-rust-crate-anstream \
bundled-rust-crate-anstyle \
bundled-rust-crate-anstyle-parse \
bundled-rust-crate-anstyle-query \
bundled-rust-crate-anyhow \
bundled-rust-crate-arc-swap \
bundled-rust-crate-arg-enum-proc-macro \
bundled-rust-crate-argon2 \
bundled-rust-crate-arrayref \
bundled-rust-crate-arrayvec \
bundled-rust-crate-ash \
bundled-rust-crate-asn1-rs \
bundled-rust-crate-asn1-rs-derive \
bundled-rust-crate-asn1-rs-impl \
bundled-rust-crate-async-broadcast \
bundled-rust-crate-async-compression \
bundled-rust-crate-async-trait \
bundled-rust-crate-atomic-waker \
bundled-rust-crate-autocfg \
bundled-rust-crate-av1-grain \
bundled-rust-crate-avif-serialize \
bundled-rust-crate-axum \
bundled-rust-crate-axum-core \
bundled-rust-crate-axum-macros \
bundled-rust-crate-axum-server \
bundled-rust-crate-axum-typed-multipart \
bundled-rust-crate-axum-typed-multipart-macros \
bundled-rust-crate-base64 \
bundled-rust-crate-base64ct \
bundled-rust-crate-bit-set \
bundled-rust-crate-bit-vec \
bundled-rust-crate-bitflags \
bundled-rust-crate-bitstream-io \
bundled-rust-crate-bitvec \
bundled-rust-crate-blake2 \
bundled-rust-crate-block-buffer \
bundled-rust-crate-borsh \
bundled-rust-crate-borsh-derive \
bundled-rust-crate-brotli \
bundled-rust-crate-brotli-decompressor \
bundled-rust-crate-built \
bundled-rust-crate-bumpalo \
bundled-rust-crate-bytecheck \
bundled-rust-crate-bytecheck-derive \
bundled-rust-crate-bytemuck \
bundled-rust-crate-bytemuck-derive \
bundled-rust-crate-byteorder-lite \
bundled-rust-crate-bytes \
bundled-rust-crate-cc \
bundled-rust-crate-cc-detect \
bundled-rust-crate-cc-image \
bundled-rust-crate-cc-stress \
bundled-rust-crate-cfg-aliases \
bundled-rust-crate-cfg-if \
bundled-rust-crate-chrono \
bundled-rust-crate-cipher \
bundled-rust-crate-clap \
bundled-rust-crate-clap-builder \
bundled-rust-crate-clap-derive \
bundled-rust-crate-clap-lex \
bundled-rust-crate-codespan-reporting \
bundled-rust-crate-color-quant \
bundled-rust-crate-colorchoice \
bundled-rust-crate-compression-codecs \
bundled-rust-crate-compression-core \
bundled-rust-crate-concurrent-queue \
bundled-rust-crate-const-oid \
bundled-rust-crate-convert-case \
bundled-rust-crate-cookie \
bundled-rust-crate-coolercontrold \
bundled-rust-crate-cpufeatures \
bundled-rust-crate-crc32fast \
bundled-rust-crate-crossbeam-channel \
bundled-rust-crate-crossbeam-deque \
bundled-rust-crate-crossbeam-epoch \
bundled-rust-crate-crossbeam-utils \
bundled-rust-crate-crypto-common \
bundled-rust-crate-ctr \
bundled-rust-crate-darling \
bundled-rust-crate-darling-core \
bundled-rust-crate-darling-macro \
bundled-rust-crate-data-encoding \
bundled-rust-crate-defmt \
bundled-rust-crate-defmt-macros \
bundled-rust-crate-defmt-parser \
bundled-rust-crate-der-parser \
bundled-rust-crate-deranged \
bundled-rust-crate-derive-more \
bundled-rust-crate-derive-more-impl \
bundled-rust-crate-digest \
bundled-rust-crate-displaydoc \
bundled-rust-crate-document-features \
bundled-rust-crate-dyn-clone \
bundled-rust-crate-either \
bundled-rust-crate-encoding-rs \
bundled-rust-crate-endi \
bundled-rust-crate-enumflags2 \
bundled-rust-crate-enumflags2-derive \
bundled-rust-crate-env-filter \
bundled-rust-crate-env-logger \
bundled-rust-crate-equator \
bundled-rust-crate-equator-macro \
bundled-rust-crate-equivalent \
bundled-rust-crate-errno \
bundled-rust-crate-event-listener \
bundled-rust-crate-event-listener-strategy \
bundled-rust-crate-fastrand \
bundled-rust-crate-fax \
bundled-rust-crate-fdeflate \
bundled-rust-crate-find-msvc-tools \
bundled-rust-crate-fixedbitset \
bundled-rust-crate-flate2 \
bundled-rust-crate-fnv \
bundled-rust-crate-foldhash \
bundled-rust-crate-fontdue \
bundled-rust-crate-form-urlencoded \
bundled-rust-crate-fs-err \
bundled-rust-crate-funty \
bundled-rust-crate-futures \
bundled-rust-crate-futures-channel \
bundled-rust-crate-futures-core \
bundled-rust-crate-futures-executor \
bundled-rust-crate-futures-io \
bundled-rust-crate-futures-lite \
bundled-rust-crate-futures-macro \
bundled-rust-crate-futures-sink \
bundled-rust-crate-futures-task \
bundled-rust-crate-futures-util \
bundled-rust-crate-generic-array \
bundled-rust-crate-getrandom \
bundled-rust-crate-ghash \
bundled-rust-crate-gif \
bundled-rust-crate-gif-dispose \
bundled-rust-crate-gifski \
bundled-rust-crate-glow \
bundled-rust-crate-gpu-alloc \
bundled-rust-crate-gpu-alloc-types \
bundled-rust-crate-gpu-descriptor \
bundled-rust-crate-gpu-descriptor-types \
bundled-rust-crate-h2 \
bundled-rust-crate-half \
bundled-rust-crate-hashbrown \
bundled-rust-crate-heck \
bundled-rust-crate-hex \
bundled-rust-crate-hexf-parse \
bundled-rust-crate-hkdf \
bundled-rust-crate-hmac \
bundled-rust-crate-http \
bundled-rust-crate-http-body \
bundled-rust-crate-http-body-util \
bundled-rust-crate-http-range-header \
bundled-rust-crate-httparse \
bundled-rust-crate-httpdate \
bundled-rust-crate-hybrid-array \
bundled-rust-crate-hyper \
bundled-rust-crate-hyper-timeout \
bundled-rust-crate-hyper-util \
bundled-rust-crate-iana-time-zone \
bundled-rust-crate-ident-case \
bundled-rust-crate-image \
bundled-rust-crate-image-webp \
bundled-rust-crate-imagequant \
bundled-rust-crate-imgref \
bundled-rust-crate-include-dir \
bundled-rust-crate-include-dir-macros \
bundled-rust-crate-indexmap \
bundled-rust-crate-inout \
bundled-rust-crate-is-terminal-polyfill \
bundled-rust-crate-itertools \
bundled-rust-crate-itoa \
bundled-rust-crate-jiff \
bundled-rust-crate-jobserver \
bundled-rust-crate-khronos-egl \
bundled-rust-crate-lazy-static \
bundled-rust-crate-libc \
bundled-rust-crate-libdrm-amdgpu-sys \
bundled-rust-crate-libloading \
bundled-rust-crate-linux-raw-sys \
bundled-rust-crate-litrs \
bundled-rust-crate-lock-api \
bundled-rust-crate-log \
bundled-rust-crate-loop9 \
bundled-rust-crate-matchit \
bundled-rust-crate-maybe-rayon \
bundled-rust-crate-memchr \
bundled-rust-crate-memoffset \
bundled-rust-crate-mime \
bundled-rust-crate-mime-guess \
bundled-rust-crate-minimal-lexical \
bundled-rust-crate-miniz-oxide \
bundled-rust-crate-mio \
bundled-rust-crate-moro-local \
bundled-rust-crate-moxcms \
bundled-rust-crate-multer \
bundled-rust-crate-multimap \
bundled-rust-crate-naga \
bundled-rust-crate-new-debug-unreachable \
bundled-rust-crate-nix \
bundled-rust-crate-nom \
bundled-rust-crate-noop-proc-macro \
bundled-rust-crate-nu-glob \
bundled-rust-crate-num-bigint \
bundled-rust-crate-num-conv \
bundled-rust-crate-num-derive \
bundled-rust-crate-num-integer \
bundled-rust-crate-num-rational \
bundled-rust-crate-num-traits \
bundled-rust-crate-nvml-wrapper \
bundled-rust-crate-nvml-wrapper-sys \
bundled-rust-crate-oid-registry \
bundled-rust-crate-once-cell \
bundled-rust-crate-opaque-debug \
bundled-rust-crate-ordered-channel \
bundled-rust-crate-ordered-float \
bundled-rust-crate-ordered-stream \
bundled-rust-crate-parking \
bundled-rust-crate-parking-lot \
bundled-rust-crate-parking-lot-core \
bundled-rust-crate-password-hash \
bundled-rust-crate-paste \
bundled-rust-crate-pem \
bundled-rust-crate-percent-encoding \
bundled-rust-crate-petgraph \
bundled-rust-crate-pin-project \
bundled-rust-crate-pin-project-internal \
bundled-rust-crate-pin-project-lite \
bundled-rust-crate-pkg-config \
bundled-rust-crate-png \
bundled-rust-crate-polyval \
bundled-rust-crate-powerfmt \
bundled-rust-crate-ppv-lite86 \
bundled-rust-crate-prettyplease \
bundled-rust-crate-proc-macro-crate \
bundled-rust-crate-proc-macro-error-attr2 \
bundled-rust-crate-proc-macro-error2 \
bundled-rust-crate-proc-macro2 \
bundled-rust-crate-profiling \
bundled-rust-crate-profiling-procmacros \
bundled-rust-crate-prost \
bundled-rust-crate-prost-build \
bundled-rust-crate-prost-derive \
bundled-rust-crate-prost-types \
bundled-rust-crate-ptr-meta \
bundled-rust-crate-ptr-meta-derive \
bundled-rust-crate-pulldown-cmark \
bundled-rust-crate-pulldown-cmark-to-cmark \
bundled-rust-crate-pxfm \
bundled-rust-crate-quick-error \
bundled-rust-crate-quote \
bundled-rust-crate-radium \
bundled-rust-crate-rand \
bundled-rust-crate-rand-chacha \
bundled-rust-crate-rand-core \
bundled-rust-crate-rav1e \
bundled-rust-crate-ravif \
bundled-rust-crate-raw-window-handle \
bundled-rust-crate-rayon \
bundled-rust-crate-rayon-core \
bundled-rust-crate-rcgen \
bundled-rust-crate-ref-cast \
bundled-rust-crate-ref-cast-impl \
bundled-rust-crate-regex \
bundled-rust-crate-regex-automata \
bundled-rust-crate-regex-syntax \
bundled-rust-crate-rend \
bundled-rust-crate-renderdoc-sys \
bundled-rust-crate-resize \
bundled-rust-crate-rgb \
bundled-rust-crate-ril \
bundled-rust-crate-ring \
bundled-rust-crate-rkyv \
bundled-rust-crate-rkyv-derive \
bundled-rust-crate-rust-decimal \
bundled-rust-crate-rustc-hash \
bundled-rust-crate-rustc-version \
bundled-rust-crate-rusticata-macros \
bundled-rust-crate-rustix \
bundled-rust-crate-rustls \
bundled-rust-crate-rustls-pki-types \
bundled-rust-crate-rustls-webpki \
bundled-rust-crate-rustversion \
bundled-rust-crate-ryu \
bundled-rust-crate-schemars \
bundled-rust-crate-schemars-derive \
bundled-rust-crate-scopeguard \
bundled-rust-crate-seahash \
bundled-rust-crate-semver \
bundled-rust-crate-serde \
bundled-rust-crate-serde-core \
bundled-rust-crate-serde-derive \
bundled-rust-crate-serde-derive-internals \
bundled-rust-crate-serde-json \
bundled-rust-crate-serde-path-to-error \
bundled-rust-crate-serde-qs \
bundled-rust-crate-serde-repr \
bundled-rust-crate-serde-spanned \
bundled-rust-crate-serde-urlencoded \
bundled-rust-crate-sha2 \
bundled-rust-crate-shlex \
bundled-rust-crate-signal-hook-registry \
bundled-rust-crate-simd-adler32 \
bundled-rust-crate-simd-helpers \
bundled-rust-crate-simdutf8 \
bundled-rust-crate-slab \
bundled-rust-crate-smallvec \
bundled-rust-crate-socket2 \
bundled-rust-crate-spin \
bundled-rust-crate-spirv \
bundled-rust-crate-static-assertions \
bundled-rust-crate-strict-num \
bundled-rust-crate-strsim \
bundled-rust-crate-strum \
bundled-rust-crate-strum-macros \
bundled-rust-crate-subtle \
bundled-rust-crate-syn \
bundled-rust-crate-sync-wrapper \
bundled-rust-crate-synstructure \
bundled-rust-crate-sysinfo \
bundled-rust-crate-systemd-journal-logger \
bundled-rust-crate-tap \
bundled-rust-crate-tempfile \
bundled-rust-crate-termcolor \
bundled-rust-crate-thiserror \
bundled-rust-crate-thiserror-impl \
bundled-rust-crate-thread-local \
bundled-rust-crate-tiff \
bundled-rust-crate-time \
bundled-rust-crate-time-core \
bundled-rust-crate-time-macros \
bundled-rust-crate-tiny-skia \
bundled-rust-crate-tiny-skia-path \
bundled-rust-crate-tinyvec \
bundled-rust-crate-tinyvec-macros \
bundled-rust-crate-tokio \
bundled-rust-crate-tokio-macros \
bundled-rust-crate-tokio-rustls \
bundled-rust-crate-tokio-stream \
bundled-rust-crate-tokio-util \
bundled-rust-crate-toml \
bundled-rust-crate-toml-datetime \
bundled-rust-crate-toml-edit \
bundled-rust-crate-toml-parser \
bundled-rust-crate-toml-write \
bundled-rust-crate-toml-writer \
bundled-rust-crate-tonic \
bundled-rust-crate-tonic-build \
bundled-rust-crate-tonic-health \
bundled-rust-crate-tonic-prost \
bundled-rust-crate-tonic-prost-build \
bundled-rust-crate-tonic-reflection \
bundled-rust-crate-tower \
bundled-rust-crate-tower-cookies \
bundled-rust-crate-tower-http \
bundled-rust-crate-tower-layer \
bundled-rust-crate-tower-serve-static \
bundled-rust-crate-tower-service \
bundled-rust-crate-tower-sessions \
bundled-rust-crate-tower-sessions-core \
bundled-rust-crate-tower-sessions-memory-store \
bundled-rust-crate-tracing \
bundled-rust-crate-tracing-attributes \
bundled-rust-crate-tracing-core \
bundled-rust-crate-try-lock \
bundled-rust-crate-ttf-parser \
bundled-rust-crate-typenum \
bundled-rust-crate-ubyte \
bundled-rust-crate-unicase \
bundled-rust-crate-unicode-ident \
bundled-rust-crate-unicode-segmentation \
bundled-rust-crate-unicode-width \
bundled-rust-crate-unicode-xid \
bundled-rust-crate-universal-hash \
bundled-rust-crate-untrusted \
bundled-rust-crate-utf8parse \
bundled-rust-crate-uuid \
bundled-rust-crate-v-frame \
bundled-rust-crate-version-check \
bundled-rust-crate-want \
bundled-rust-crate-wasm-bindgen \
bundled-rust-crate-wasm-bindgen-macro \
bundled-rust-crate-wasm-bindgen-macro-support \
bundled-rust-crate-wasm-bindgen-shared \
bundled-rust-crate-weezl \
bundled-rust-crate-wgpu \
bundled-rust-crate-wgpu-core \
bundled-rust-crate-wgpu-hal \
bundled-rust-crate-wgpu-types \
bundled-rust-crate-winnow \
bundled-rust-crate-wrapcenum-derive \
bundled-rust-crate-wyz \
bundled-rust-crate-x509-parser \
bundled-rust-crate-yasna \
bundled-rust-crate-zbus \
bundled-rust-crate-zbus-macros \
bundled-rust-crate-zbus-names \
bundled-rust-crate-zerocopy \
bundled-rust-crate-zerocopy-derive \
bundled-rust-crate-zeroize \
bundled-rust-crate-zmij \
bundled-rust-crate-zstd \
bundled-rust-crate-zstd-safe \
bundled-rust-crate-zstd-sys \
bundled-rust-crate-zune-core \
bundled-rust-crate-zune-jpeg \
bundled-rust-crate-zvariant \
bundled-rust-crate-zvariant-derive \
bundled-rust-crate-zvariant-utils \
coolercontrold"

RDEPENDS:${PN} += "/usr/bin/sh \
libc.so.6 \
libgcc-s.so.1 \
libm.so.6"

inherit rpm
