SUMMARY = "Terminal UI and CLI for NetBox"
DESCRIPTION = "Terminal UI, CLI, and MCP server for NetBox. \
Fast search, IPAM lookups, and device context."
LICENSE = "Apache-2.0 | MIT"

PV = "0.14.0"

RPM_NAME = "nbox-0.14.0-1.2.aarch64.rpm"
RPM_HASH = "d30fa2c78d590e6644f848f9310eeea4444d077472c0e53f36aa0157e6be4f241fd995897979ef1249b63f673ab0533cea40c940bf57abc47d75bd0d575f9343"

RPROVIDES:${PN} += "bundled-rust-crate-adler2 \
bundled-rust-crate-aho-corasick \
bundled-rust-crate-allocator-api2 \
bundled-rust-crate-anstream \
bundled-rust-crate-anstyle \
bundled-rust-crate-anstyle-parse \
bundled-rust-crate-anstyle-query \
bundled-rust-crate-anyhow \
bundled-rust-crate-approx \
bundled-rust-crate-arboard \
bundled-rust-crate-async-trait \
bundled-rust-crate-atomic \
bundled-rust-crate-atomic-waker \
bundled-rust-crate-autocfg \
bundled-rust-crate-axum \
bundled-rust-crate-axum-core \
bundled-rust-crate-base16ct \
bundled-rust-crate-base64 \
bundled-rust-crate-base64ct \
bundled-rust-crate-bit-set \
bundled-rust-crate-bit-vec \
bundled-rust-crate-bitflags \
bundled-rust-crate-block-buffer \
bundled-rust-crate-by-address \
bundled-rust-crate-bytemuck \
bundled-rust-crate-byteorder-lite \
bundled-rust-crate-bytes \
bundled-rust-crate-castaway \
bundled-rust-crate-cc \
bundled-rust-crate-cfg-aliases \
bundled-rust-crate-cfg-if \
bundled-rust-crate-chacha20 \
bundled-rust-crate-chrono \
bundled-rust-crate-clap \
bundled-rust-crate-clap-builder \
bundled-rust-crate-clap-complete \
bundled-rust-crate-clap-derive \
bundled-rust-crate-clap-lex \
bundled-rust-crate-clap-mangen \
bundled-rust-crate-colorchoice \
bundled-rust-crate-compact-str \
bundled-rust-crate-const-oid \
bundled-rust-crate-convert-case \
bundled-rust-crate-cookie \
bundled-rust-crate-cookie-store \
bundled-rust-crate-cpufeatures \
bundled-rust-crate-crc32fast \
bundled-rust-crate-critical-section \
bundled-rust-crate-crossbeam-channel \
bundled-rust-crate-crossbeam-deque \
bundled-rust-crate-crossbeam-epoch \
bundled-rust-crate-crossbeam-utils \
bundled-rust-crate-crossterm \
bundled-rust-crate-crypto-bigint \
bundled-rust-crate-crypto-common \
bundled-rust-crate-csscolorparser \
bundled-rust-crate-curve25519-dalek \
bundled-rust-crate-darling \
bundled-rust-crate-darling-core \
bundled-rust-crate-darling-macro \
bundled-rust-crate-deltae \
bundled-rust-crate-der \
bundled-rust-crate-deranged \
bundled-rust-crate-derive-more \
bundled-rust-crate-derive-more-impl \
bundled-rust-crate-digest \
bundled-rust-crate-dirs \
bundled-rust-crate-dirs-sys \
bundled-rust-crate-displaydoc \
bundled-rust-crate-document-features \
bundled-rust-crate-dyn-clone \
bundled-rust-crate-ecdsa \
bundled-rust-crate-ed25519 \
bundled-rust-crate-ed25519-dalek \
bundled-rust-crate-either \
bundled-rust-crate-elliptic-curve \
bundled-rust-crate-equivalent \
bundled-rust-crate-errno \
bundled-rust-crate-etcetera \
bundled-rust-crate-euclid \
bundled-rust-crate-fancy-regex \
bundled-rust-crate-fast-srgb8 \
bundled-rust-crate-fax \
bundled-rust-crate-fdeflate \
bundled-rust-crate-ff \
bundled-rust-crate-filedescriptor \
bundled-rust-crate-find-msvc-tools \
bundled-rust-crate-finl-unicode \
bundled-rust-crate-fixedbitset \
bundled-rust-crate-flate2 \
bundled-rust-crate-fnv \
bundled-rust-crate-foldhash \
bundled-rust-crate-form-urlencoded \
bundled-rust-crate-futures \
bundled-rust-crate-futures-channel \
bundled-rust-crate-futures-core \
bundled-rust-crate-futures-executor \
bundled-rust-crate-futures-io \
bundled-rust-crate-futures-macro \
bundled-rust-crate-futures-sink \
bundled-rust-crate-futures-task \
bundled-rust-crate-futures-util \
bundled-rust-crate-generic-array \
bundled-rust-crate-gethostname \
bundled-rust-crate-getrandom \
bundled-rust-crate-group \
bundled-rust-crate-h2 \
bundled-rust-crate-half \
bundled-rust-crate-hashbrown \
bundled-rust-crate-heck \
bundled-rust-crate-hex \
bundled-rust-crate-hkdf \
bundled-rust-crate-hmac \
bundled-rust-crate-home \
bundled-rust-crate-http \
bundled-rust-crate-http-body \
bundled-rust-crate-http-body-util \
bundled-rust-crate-httparse \
bundled-rust-crate-httpdate \
bundled-rust-crate-hybrid-array \
bundled-rust-crate-hyper \
bundled-rust-crate-hyper-rustls \
bundled-rust-crate-hyper-util \
bundled-rust-crate-iana-time-zone \
bundled-rust-crate-icu-collections \
bundled-rust-crate-icu-locale-core \
bundled-rust-crate-icu-normalizer \
bundled-rust-crate-icu-normalizer-data \
bundled-rust-crate-icu-properties \
bundled-rust-crate-icu-properties-data \
bundled-rust-crate-icu-provider \
bundled-rust-crate-ident-case \
bundled-rust-crate-idna \
bundled-rust-crate-idna-adapter \
bundled-rust-crate-image \
bundled-rust-crate-indexmap \
bundled-rust-crate-indoc \
bundled-rust-crate-instability \
bundled-rust-crate-ipnet \
bundled-rust-crate-is-docker \
bundled-rust-crate-is-terminal \
bundled-rust-crate-is-terminal-polyfill \
bundled-rust-crate-is-wsl \
bundled-rust-crate-itertools \
bundled-rust-crate-itoa \
bundled-rust-crate-jsonwebtoken \
bundled-rust-crate-kasuari \
bundled-rust-crate-lab \
bundled-rust-crate-lazy-static \
bundled-rust-crate-libc \
bundled-rust-crate-libm \
bundled-rust-crate-line-clipping \
bundled-rust-crate-linux-raw-sys \
bundled-rust-crate-litemap \
bundled-rust-crate-litrs \
bundled-rust-crate-lock-api \
bundled-rust-crate-log \
bundled-rust-crate-lru \
bundled-rust-crate-lru-slab \
bundled-rust-crate-mac-address \
bundled-rust-crate-matchers \
bundled-rust-crate-matchit \
bundled-rust-crate-memchr \
bundled-rust-crate-memmem \
bundled-rust-crate-memoffset \
bundled-rust-crate-mime \
bundled-rust-crate-minimal-lexical \
bundled-rust-crate-miniz-oxide \
bundled-rust-crate-mio \
bundled-rust-crate-moxcms \
bundled-rust-crate-nbox \
bundled-rust-crate-nix \
bundled-rust-crate-nom \
bundled-rust-crate-nu-ansi-term \
bundled-rust-crate-nucleo \
bundled-rust-crate-nucleo-matcher \
bundled-rust-crate-num-bigint \
bundled-rust-crate-num-bigint-dig \
bundled-rust-crate-num-conv \
bundled-rust-crate-num-derive \
bundled-rust-crate-num-integer \
bundled-rust-crate-num-iter \
bundled-rust-crate-num-threads \
bundled-rust-crate-num-traits \
bundled-rust-crate-once-cell \
bundled-rust-crate-open \
bundled-rust-crate-option-ext \
bundled-rust-crate-ordered-float \
bundled-rust-crate-p256 \
bundled-rust-crate-p384 \
bundled-rust-crate-palette \
bundled-rust-crate-palette-derive \
bundled-rust-crate-parking-lot \
bundled-rust-crate-parking-lot-core \
bundled-rust-crate-pastey \
bundled-rust-crate-pem \
bundled-rust-crate-pem-rfc7468 \
bundled-rust-crate-percent-encoding \
bundled-rust-crate-pest \
bundled-rust-crate-pest-derive \
bundled-rust-crate-pest-generator \
bundled-rust-crate-pest-meta \
bundled-rust-crate-phf \
bundled-rust-crate-phf-codegen \
bundled-rust-crate-phf-generator \
bundled-rust-crate-phf-macros \
bundled-rust-crate-phf-shared \
bundled-rust-crate-pin-project-lite \
bundled-rust-crate-pkcs1 \
bundled-rust-crate-pkcs8 \
bundled-rust-crate-png \
bundled-rust-crate-portable-atomic \
bundled-rust-crate-potential-utf \
bundled-rust-crate-powerfmt \
bundled-rust-crate-ppv-lite86 \
bundled-rust-crate-primeorder \
bundled-rust-crate-proc-macro2 \
bundled-rust-crate-pxfm \
bundled-rust-crate-quick-error \
bundled-rust-crate-quinn \
bundled-rust-crate-quinn-proto \
bundled-rust-crate-quinn-udp \
bundled-rust-crate-quote \
bundled-rust-crate-rand \
bundled-rust-crate-rand-chacha \
bundled-rust-crate-rand-core \
bundled-rust-crate-rand-pcg \
bundled-rust-crate-ratatui \
bundled-rust-crate-ratatui-cheese \
bundled-rust-crate-ratatui-core \
bundled-rust-crate-ratatui-crossterm \
bundled-rust-crate-ratatui-macros \
bundled-rust-crate-ratatui-termina \
bundled-rust-crate-ratatui-termwiz \
bundled-rust-crate-ratatui-widgets \
bundled-rust-crate-rayon \
bundled-rust-crate-rayon-core \
bundled-rust-crate-ref-cast \
bundled-rust-crate-ref-cast-impl \
bundled-rust-crate-regex \
bundled-rust-crate-regex-automata \
bundled-rust-crate-regex-syntax \
bundled-rust-crate-reqwest \
bundled-rust-crate-rfc6979 \
bundled-rust-crate-ring \
bundled-rust-crate-rmcp \
bundled-rust-crate-rmcp-macros \
bundled-rust-crate-roff \
bundled-rust-crate-rsa \
bundled-rust-crate-rustc-hash \
bundled-rust-crate-rustc-version \
bundled-rust-crate-rustix \
bundled-rust-crate-rustls \
bundled-rust-crate-rustls-pki-types \
bundled-rust-crate-rustls-webpki \
bundled-rust-crate-rustversion \
bundled-rust-crate-ryu \
bundled-rust-crate-schemars \
bundled-rust-crate-schemars-derive \
bundled-rust-crate-scopeguard \
bundled-rust-crate-sec1 \
bundled-rust-crate-semver \
bundled-rust-crate-serde \
bundled-rust-crate-serde-core \
bundled-rust-crate-serde-derive \
bundled-rust-crate-serde-derive-internals \
bundled-rust-crate-serde-json \
bundled-rust-crate-serde-path-to-error \
bundled-rust-crate-serde-spanned \
bundled-rust-crate-serde-urlencoded \
bundled-rust-crate-sha2 \
bundled-rust-crate-sharded-slab \
bundled-rust-crate-shlex \
bundled-rust-crate-signal-hook \
bundled-rust-crate-signal-hook-mio \
bundled-rust-crate-signal-hook-registry \
bundled-rust-crate-signature \
bundled-rust-crate-simd-adler32 \
bundled-rust-crate-simple-asn1 \
bundled-rust-crate-siphasher \
bundled-rust-crate-slab \
bundled-rust-crate-smallvec \
bundled-rust-crate-socket2 \
bundled-rust-crate-spin \
bundled-rust-crate-spki \
bundled-rust-crate-sse-stream \
bundled-rust-crate-stable-deref-trait \
bundled-rust-crate-static-assertions \
bundled-rust-crate-strsim \
bundled-rust-crate-strum \
bundled-rust-crate-strum-macros \
bundled-rust-crate-subtle \
bundled-rust-crate-symlink \
bundled-rust-crate-syn \
bundled-rust-crate-sync-wrapper \
bundled-rust-crate-synstructure \
bundled-rust-crate-termina \
bundled-rust-crate-terminfo \
bundled-rust-crate-termios \
bundled-rust-crate-termwiz \
bundled-rust-crate-thiserror \
bundled-rust-crate-thiserror-impl \
bundled-rust-crate-thread-local \
bundled-rust-crate-tiff \
bundled-rust-crate-time \
bundled-rust-crate-time-core \
bundled-rust-crate-time-macros \
bundled-rust-crate-tinystr \
bundled-rust-crate-tinyvec \
bundled-rust-crate-tinyvec-macros \
bundled-rust-crate-tokio \
bundled-rust-crate-tokio-macros \
bundled-rust-crate-tokio-rustls \
bundled-rust-crate-tokio-stream \
bundled-rust-crate-tokio-util \
bundled-rust-crate-toml \
bundled-rust-crate-toml-datetime \
bundled-rust-crate-toml-edit \
bundled-rust-crate-toml-parser \
bundled-rust-crate-toml-writer \
bundled-rust-crate-tower \
bundled-rust-crate-tower-http \
bundled-rust-crate-tower-layer \
bundled-rust-crate-tower-service \
bundled-rust-crate-tracing \
bundled-rust-crate-tracing-appender \
bundled-rust-crate-tracing-attributes \
bundled-rust-crate-tracing-core \
bundled-rust-crate-tracing-log \
bundled-rust-crate-tracing-subscriber \
bundled-rust-crate-try-lock \
bundled-rust-crate-typenum \
bundled-rust-crate-ucd-trie \
bundled-rust-crate-unicode-ident \
bundled-rust-crate-unicode-segmentation \
bundled-rust-crate-unicode-truncate \
bundled-rust-crate-unicode-width \
bundled-rust-crate-untrusted \
bundled-rust-crate-update-informer \
bundled-rust-crate-ureq \
bundled-rust-crate-ureq-proto \
bundled-rust-crate-url \
bundled-rust-crate-utf8-iter \
bundled-rust-crate-utf8-zero \
bundled-rust-crate-utf8parse \
bundled-rust-crate-uuid \
bundled-rust-crate-version-check \
bundled-rust-crate-vtparse \
bundled-rust-crate-want \
bundled-rust-crate-webpki-roots \
bundled-rust-crate-weezl \
bundled-rust-crate-wezterm-bidi \
bundled-rust-crate-wezterm-blob-leases \
bundled-rust-crate-wezterm-color-types \
bundled-rust-crate-wezterm-dynamic \
bundled-rust-crate-wezterm-dynamic-derive \
bundled-rust-crate-wezterm-input-types \
bundled-rust-crate-winnow \
bundled-rust-crate-writeable \
bundled-rust-crate-x11rb \
bundled-rust-crate-x11rb-protocol \
bundled-rust-crate-yoke \
bundled-rust-crate-yoke-derive \
bundled-rust-crate-zerocopy \
bundled-rust-crate-zerocopy-derive \
bundled-rust-crate-zerofrom \
bundled-rust-crate-zerofrom-derive \
bundled-rust-crate-zeroize \
bundled-rust-crate-zeroize-derive \
bundled-rust-crate-zerotrie \
bundled-rust-crate-zerovec \
bundled-rust-crate-zerovec-derive \
bundled-rust-crate-zmij \
bundled-rust-crate-zune-core \
bundled-rust-crate-zune-jpeg \
nbox"

RDEPENDS:${PN} += "libc.so.6 \
libgcc-s.so.1 \
libm.so.6"

inherit rpm
