SUMMARY = "NVIDIA open kernel module driver for GeForce 16 series (GTX 16xx) and newer"
DESCRIPTION = "This package provides the open-source NVIDIA kernel module driver \
for GeForce 16 series (GTX 16xx) and newer GPUs, i.e. Turing GPU family \
and newer (Turing, Ampere, Ada Lavelace, Hopper, Blackwell, ...). \
This driver variant is meant to be used when using the GFX repository \
below \
 \
  https://download.nvidia.com/suse/ \
  https://download.nvidia.com/opensuse/ \
 \
for user-space driver installation."
LICENSE = "GPL-2.0-only & MIT"

PV = "595.99.02_k7.2.5_1"

RPM_NAME = "nvidia-open-driver-G07-signed-kmp-default-595.99.02_k7.2.5_1-2.2.aarch64.rpm"
RPM_HASH = "486886068e6902cafcee9c15c47c4f6b6a63444eaab76b84507c397b777dc1b0519605b8cea7eeace94d3c4d759a7a167bde44b3cb2f5bb9601d4fb0943585ec"

RPROVIDES:${PN} += "kmod-nvidia-drm.ko \
kmod-nvidia-modeset.ko \
kmod-nvidia-uvm.ko \
kmod-nvidia.ko \
ksym-default-nvKmsKapiF16ToF32 \
ksym-default-nvKmsKapiF32Add \
ksym-default-nvKmsKapiF32Div \
ksym-default-nvKmsKapiF32Mul \
ksym-default-nvKmsKapiF32ToF16 \
ksym-default-nvKmsKapiF32ToUI32RMinMag \
ksym-default-nvKmsKapiGetFunctionsTable \
ksym-default-nvKmsKapiUI32ToF32 \
ksym-default-nvUvmInterfaceAccessBitsBufAlloc \
ksym-default-nvUvmInterfaceAccessBitsBufFree \
ksym-default-nvUvmInterfaceAccessBitsDump \
ksym-default-nvUvmInterfaceAddressSpaceCreate \
ksym-default-nvUvmInterfaceAddressSpaceDestroy \
ksym-default-nvUvmInterfaceBindChannelResources \
ksym-default-nvUvmInterfaceChannelAllocate \
ksym-default-nvUvmInterfaceChannelDestroy \
ksym-default-nvUvmInterfaceCslDecrypt \
ksym-default-nvUvmInterfaceCslEncrypt \
ksym-default-nvUvmInterfaceCslIncrementIv \
ksym-default-nvUvmInterfaceCslInitContext \
ksym-default-nvUvmInterfaceCslLogEncryption \
ksym-default-nvUvmInterfaceCslQueryMessagePool \
ksym-default-nvUvmInterfaceCslRotateIv \
ksym-default-nvUvmInterfaceCslRotateKey \
ksym-default-nvUvmInterfaceCslSign \
ksym-default-nvUvmInterfaceDeRegisterUvmEvents \
ksym-default-nvUvmInterfaceDeinitCslContext \
ksym-default-nvUvmInterfaceDestroyAccessCntrInfo \
ksym-default-nvUvmInterfaceDestroyFaultInfo \
ksym-default-nvUvmInterfaceDeviceCreate \
ksym-default-nvUvmInterfaceDeviceDestroy \
ksym-default-nvUvmInterfaceDisableAccessCntr \
ksym-default-nvUvmInterfaceDupAddressSpace \
ksym-default-nvUvmInterfaceDupAllocation \
ksym-default-nvUvmInterfaceDupMemory \
ksym-default-nvUvmInterfaceEnableAccessCntr \
ksym-default-nvUvmInterfaceFlushReplayableFaultBuffer \
ksym-default-nvUvmInterfaceFreeDupedHandle \
ksym-default-nvUvmInterfaceGetChannelResourcePtes \
ksym-default-nvUvmInterfaceGetEccInfo \
ksym-default-nvUvmInterfaceGetExternalAllocPhysAddrs \
ksym-default-nvUvmInterfaceGetExternalAllocPtes \
ksym-default-nvUvmInterfaceGetFbInfo \
ksym-default-nvUvmInterfaceGetGpuInfo \
ksym-default-nvUvmInterfaceGetNonReplayableFaults \
ksym-default-nvUvmInterfaceGetNvlinkInfo \
ksym-default-nvUvmInterfaceGetP2PCaps \
ksym-default-nvUvmInterfaceGetPmaObject \
ksym-default-nvUvmInterfaceHasPendingNonReplayableFaults \
ksym-default-nvUvmInterfaceInitAccessCntrInfo \
ksym-default-nvUvmInterfaceInitFaultInfo \
ksym-default-nvUvmInterfaceMemoryAllocFB \
ksym-default-nvUvmInterfaceMemoryAllocSys \
ksym-default-nvUvmInterfaceMemoryCpuMap \
ksym-default-nvUvmInterfaceMemoryCpuUnMap \
ksym-default-nvUvmInterfaceMemoryFree \
ksym-default-nvUvmInterfaceOwnPageFaultIntr \
ksym-default-nvUvmInterfaceP2pObjectCreate \
ksym-default-nvUvmInterfaceP2pObjectDestroy \
ksym-default-nvUvmInterfacePagingChannelAllocate \
ksym-default-nvUvmInterfacePagingChannelDestroy \
ksym-default-nvUvmInterfacePagingChannelPushStream \
ksym-default-nvUvmInterfacePagingChannelsMap \
ksym-default-nvUvmInterfacePagingChannelsUnmap \
ksym-default-nvUvmInterfacePmaAllocPages \
ksym-default-nvUvmInterfacePmaFreePages \
ksym-default-nvUvmInterfacePmaPinPages \
ksym-default-nvUvmInterfacePmaRegisterEvictionCallbacks \
ksym-default-nvUvmInterfacePmaUnregisterEvictionCallbacks \
ksym-default-nvUvmInterfaceQueryCaps \
ksym-default-nvUvmInterfaceQueryCopyEnginesCaps \
ksym-default-nvUvmInterfaceRegisterGpu \
ksym-default-nvUvmInterfaceRegisterUvmEvents \
ksym-default-nvUvmInterfaceReleaseChannel \
ksym-default-nvUvmInterfaceReportFatalError \
ksym-default-nvUvmInterfaceReportNonReplayableFault \
ksym-default-nvUvmInterfaceRetainChannel \
ksym-default-nvUvmInterfaceServiceDeviceInterruptsRM \
ksym-default-nvUvmInterfaceSessionCreate \
ksym-default-nvUvmInterfaceSessionDestroy \
ksym-default-nvUvmInterfaceSetPageDirectory \
ksym-default-nvUvmInterfaceStopChannel \
ksym-default-nvUvmInterfaceTogglePrefetchFaults \
ksym-default-nvUvmInterfaceTsgAllocate \
ksym-default-nvUvmInterfaceTsgDestroy \
ksym-default-nvUvmInterfaceUnregisterGpu \
ksym-default-nvUvmInterfaceUnsetPageDirectory \
ksym-default-nvidia-get-rm-ops \
ksym-default-nvidia-p2p-destroy-mapping \
ksym-default-nvidia-p2p-dma-map-pages \
ksym-default-nvidia-p2p-dma-unmap-pages \
ksym-default-nvidia-p2p-free-dma-mapping \
ksym-default-nvidia-p2p-free-page-table \
ksym-default-nvidia-p2p-get-pages \
ksym-default-nvidia-p2p-get-pages-persistent \
ksym-default-nvidia-p2p-get-rsync-registers \
ksym-default-nvidia-p2p-init-mapping \
ksym-default-nvidia-p2p-put-pages \
ksym-default-nvidia-p2p-put-pages-persistent \
ksym-default-nvidia-p2p-put-rsync-registers \
ksym-default-nvidia-p2p-register-rsync-driver \
ksym-default-nvidia-p2p-unregister-rsync-driver \
ksym-default-nvidia-register-error-cb \
ksym-default-nvidia-unregister-error-cb \
nvidia-open-driver-G07 \
nvidia-open-driver-G07-signed-kmp \
nvidia-open-driver-G07-signed-kmp-default \
nvidia-open-driver-G07-signed-kmp-default-k7.2.5-1 \
nvidia-open-signed-kmp \
nvidia-open-signed-kmp-gfx \
open-driver-non-cuda-variant"

RDEPENDS:${PN} += "/usr/bin/bash \
/usr/bin/sh \
coreutils \
grep \
group-video \
ksym-default----ratelimit \
ksym-default---acpi-video-get-backlight-type \
ksym-default---alloc-pages-noprof \
ksym-default---arch-copy-from-user \
ksym-default---arch-copy-to-user \
ksym-default---bitmap-and \
ksym-default---bitmap-andnot \
ksym-default---bitmap-clear \
ksym-default---bitmap-complement \
ksym-default---bitmap-equal \
ksym-default---bitmap-intersects \
ksym-default---bitmap-or \
ksym-default---bitmap-set \
ksym-default---bitmap-shift-left \
ksym-default---bitmap-shift-right \
ksym-default---bitmap-subset \
ksym-default---bitmap-weight \
ksym-default---check-object-size \
ksym-default---clk-get-name \
ksym-default---const-udelay \
ksym-default---cpu-online-mask \
ksym-default---dma-sync-sg-for-device \
ksym-default---dma-sync-single-for-cpu \
ksym-default---dma-sync-single-for-device \
ksym-default---drm-atomic-commit-free \
ksym-default---drm-atomic-helper-connector-destroy-state \
ksym-default---drm-atomic-helper-connector-duplicate-state \
ksym-default---drm-atomic-helper-connector-reset \
ksym-default---drm-atomic-helper-crtc-destroy-state \
ksym-default---drm-atomic-helper-crtc-duplicate-state \
ksym-default---drm-atomic-helper-plane-destroy-state \
ksym-default---drm-atomic-helper-plane-duplicate-state \
ksym-default---drm-dev-dbg \
ksym-default---drm-err \
ksym-default---folio-lock \
ksym-default---folio-put \
ksym-default---fortify-panic \
ksym-default---free-pages \
ksym-default---init-rwsem \
ksym-default---init-swait-queue-head \
ksym-default---init-waitqueue-head \
ksym-default---ioremap-prot \
ksym-default---kmalloc-cache-noprof \
ksym-default---kmalloc-large-noprof \
ksym-default---kmalloc-noprof \
ksym-default---kmem-cache-create-args \
ksym-default---kvmalloc-node-noprof \
ksym-default---list-add-valid-or-report \
ksym-default---list-del-entry-valid-or-report \
ksym-default---mmap-lock-do-trace-acquire-returned \
ksym-default---mmap-lock-do-trace-released \
ksym-default---mmap-lock-do-trace-start-locking \
ksym-default---mmdrop \
ksym-default---mmu-notifier-register \
ksym-default---msecs-to-jiffies \
ksym-default---ndelay \
ksym-default---node-distance \
ksym-default---num-possible-cpus \
ksym-default---of-parse-phandle-with-args \
ksym-default---pci-register-driver \
ksym-default---per-cpu-offset \
ksym-default---platform-driver-register \
ksym-default---pm-runtime-disable \
ksym-default---pm-runtime-use-autosuspend \
ksym-default---printk-ratelimit \
ksym-default---rcu-read-lock \
ksym-default---rcu-read-unlock \
ksym-default---refrigerator \
ksym-default---release-region \
ksym-default---request-region \
ksym-default---seq-puts \
ksym-default---sg-page-iter-dma-next \
ksym-default---sg-page-iter-start \
ksym-default---stack-chk-fail \
ksym-default---sw-hweight32 \
ksym-default---sw-hweight64 \
ksym-default---sw-hweight8 \
ksym-default---task-pid-nr-ns \
ksym-default---trace-set-current-state \
ksym-default---trace-trigger-soft-disabled \
ksym-default---tracepoint-mmap-lock-acquire-returned \
ksym-default---tracepoint-mmap-lock-released \
ksym-default---tracepoint-mmap-lock-start-locking \
ksym-default---tracepoint-sched-set-state-tp \
ksym-default---udelay \
ksym-default---usecs-to-jiffies \
ksym-default---vma-start-write \
ksym-default---vmalloc-noprof \
ksym-default---wake-up \
ksym-default---warn-printk \
ksym-default---zero-page \
ksym-default--ctype \
ksym-default--find-first-bit \
ksym-default--find-first-zero-bit \
ksym-default--find-last-bit \
ksym-default--find-next-bit \
ksym-default--find-next-zero-bit \
ksym-default--printk \
ksym-default--raw-read-lock \
ksym-default--raw-read-unlock \
ksym-default--raw-spin-lock \
ksym-default--raw-spin-lock-irq \
ksym-default--raw-spin-lock-irqsave \
ksym-default--raw-spin-unlock \
ksym-default--raw-spin-unlock-irq \
ksym-default--raw-spin-unlock-irqrestore \
ksym-default-acpi-evaluate-integer \
ksym-default-acpi-evaluate-object \
ksym-default-acpi-gbl-FADT \
ksym-default-acpi-get-handle \
ksym-default-acpi-get-next-object \
ksym-default-acpi-get-table \
ksym-default-acpi-install-notify-handler \
ksym-default-acpi-put-table \
ksym-default-acpi-remove-notify-handler \
ksym-default-acpi-video-register-backlight \
ksym-default-acpi-walk-namespace \
ksym-default-add-memory-driver-managed \
ksym-default-address-space-init-once \
ksym-default-alloc-chrdev-region \
ksym-default-alloc-pages-noprof \
ksym-default-alt-cb-patch-nops \
ksym-default-aperture-remove-conflicting-devices \
ksym-default-aperture-remove-conflicting-pci-devices \
ksym-default-arm64-use-ng-mappings \
ksym-default-backlight-device-register \
ksym-default-backlight-device-unregister \
ksym-default-bit-wait \
ksym-default-bpf-trace-run3 \
ksym-default-cache-line-size \
ksym-default-cancel-delayed-work \
ksym-default-cancel-delayed-work-sync \
ksym-default-capable \
ksym-default-cc-platform-has \
ksym-default-cdev-add \
ksym-default-cdev-del \
ksym-default-cdev-init \
ksym-default-class-create \
ksym-default-class-destroy \
ksym-default-clear-page \
ksym-default-clk-disable \
ksym-default-clk-enable \
ksym-default-clk-get-rate \
ksym-default-clk-prepare \
ksym-default-clk-round-rate \
ksym-default-clk-set-rate \
ksym-default-clk-unprepare \
ksym-default-close-fd \
ksym-default-complete \
ksym-default-complete-all \
ksym-default-completion-done \
ksym-default-console-lock \
ksym-default-console-unlock \
ksym-default-cpu-all-bits \
ksym-default-cpufreq-get \
ksym-default-crypto-aead-decrypt \
ksym-default-crypto-aead-encrypt \
ksym-default-crypto-aead-setkey \
ksym-default-crypto-alloc-aead \
ksym-default-crypto-alloc-shash \
ksym-default-crypto-alloc-sig \
ksym-default-crypto-destroy-tfm \
ksym-default-crypto-ecdh-shared-secret \
ksym-default-crypto-req-done \
ksym-default-crypto-shash-export \
ksym-default-crypto-shash-finup \
ksym-default-crypto-shash-import \
ksym-default-crypto-shash-init \
ksym-default-crypto-shash-setkey \
ksym-default-crypto-shash-tfm-digest \
ksym-default-delayed-work-timer-fn \
ksym-default-desc-to-gpio \
ksym-default-dev-driver-string \
ksym-default-dev-pm-domain-attach \
ksym-default-dev-pm-domain-detach \
ksym-default-dev-pm-domain-set \
ksym-default-dev-pm-genpd-resume \
ksym-default-dev-pm-genpd-suspend \
ksym-default-dev-pm-opp-add-dynamic \
ksym-default-dev-pm-opp-remove \
ksym-default-dev-set-name \
ksym-default-devfreq-resume-device \
ksym-default-devfreq-suspend-device \
ksym-default-device-create \
ksym-default-device-destroy \
ksym-default-device-property-read-u64-array \
ksym-default-device-register \
ksym-default-device-unregister \
ksym-default-devm-clk-bulk-get-all \
ksym-default-devm-clk-get \
ksym-default-devm-clk-put \
ksym-default-devm-devfreq-add-device \
ksym-default-devm-devfreq-remove-device \
ksym-default-devm-gpio-request-one \
ksym-default-devm-ioremap \
ksym-default-devm-kmalloc \
ksym-default-devm-memunmap-pages \
ksym-default-devm-of-icc-get \
ksym-default-disable-irq-nosync \
ksym-default-dma-alloc-attrs \
ksym-default-dma-buf-attach \
ksym-default-dma-buf-detach \
ksym-default-dma-buf-export \
ksym-default-dma-buf-fd \
ksym-default-dma-buf-get \
ksym-default-dma-buf-map-attachment \
ksym-default-dma-buf-put \
ksym-default-dma-buf-unmap-attachment \
ksym-default-dma-fence-add-callback \
ksym-default-dma-fence-context-alloc \
ksym-default-dma-fence-default-wait \
ksym-default-dma-fence-init \
ksym-default-dma-fence-release \
ksym-default-dma-fence-signal \
ksym-default-dma-free-attrs \
ksym-default-dma-map-page-attrs \
ksym-default-dma-map-sg-attrs \
ksym-default-dma-resv-add-fence \
ksym-default-dma-resv-reserve-fences \
ksym-default-dma-set-coherent-mask \
ksym-default-dma-set-mask \
ksym-default-dma-unmap-page-attrs \
ksym-default-dma-unmap-sg-attrs \
ksym-default-dmi-get-system-info \
ksym-default-down \
ksym-default-down-interruptible \
ksym-default-down-read \
ksym-default-down-read-trylock \
ksym-default-down-trylock \
ksym-default-down-write \
ksym-default-down-write-trylock \
ksym-default-downgrade-write \
ksym-default-drm-atomic-add-affected-connectors \
ksym-default-drm-atomic-add-affected-planes \
ksym-default-drm-atomic-commit \
ksym-default-drm-atomic-commit-alloc \
ksym-default-drm-atomic-commit-default-clear \
ksym-default-drm-atomic-commit-default-release \
ksym-default-drm-atomic-commit-init \
ksym-default-drm-atomic-get-connector-state \
ksym-default-drm-atomic-get-crtc-state \
ksym-default-drm-atomic-get-plane-state \
ksym-default-drm-atomic-helper-check \
ksym-default-drm-atomic-helper-crtc-reset \
ksym-default-drm-atomic-helper-disable-plane \
ksym-default-drm-atomic-helper-page-flip \
ksym-default-drm-atomic-helper-plane-reset \
ksym-default-drm-atomic-helper-prepare-planes \
ksym-default-drm-atomic-helper-set-config \
ksym-default-drm-atomic-helper-shutdown \
ksym-default-drm-atomic-helper-swap-state \
ksym-default-drm-atomic-helper-update-legacy-modeset-state \
ksym-default-drm-atomic-helper-update-plane \
ksym-default-drm-atomic-set-crtc-for-connector \
ksym-default-drm-atomic-set-crtc-for-plane \
ksym-default-drm-atomic-set-fb-for-plane \
ksym-default-drm-atomic-set-mode-prop-for-crtc \
ksym-default-drm-client-setup \
ksym-default-drm-compat-ioctl \
ksym-default-drm-connector-atomic-hdr-metadata-equal \
ksym-default-drm-connector-attach-colorspace-property \
ksym-default-drm-connector-attach-encoder \
ksym-default-drm-connector-attach-hdr-output-metadata-property \
ksym-default-drm-connector-attach-vrr-capable-property \
ksym-default-drm-connector-cleanup \
ksym-default-drm-connector-init \
ksym-default-drm-connector-list-iter-begin \
ksym-default-drm-connector-list-iter-end \
ksym-default-drm-connector-list-iter-next \
ksym-default-drm-connector-register \
ksym-default-drm-connector-set-vrr-capable-property \
ksym-default-drm-connector-unregister \
ksym-default-drm-connector-update-edid-property \
ksym-default-drm-crtc-cleanup \
ksym-default-drm-crtc-enable-color-mgmt \
ksym-default-drm-crtc-init-with-planes \
ksym-default-drm-crtc-send-vblank-event \
ksym-default-drm-dev-alloc \
ksym-default-drm-dev-put \
ksym-default-drm-dev-register \
ksym-default-drm-dev-unplug \
ksym-default-drm-dev-unregister \
ksym-default-drm-edid-override-connector-update \
ksym-default-drm-encoder-cleanup \
ksym-default-drm-encoder-init \
ksym-default-drm-fb-helper-set-suspend-unlocked \
ksym-default-drm-fbdev-ttm-driver-fbdev-probe \
ksym-default-drm-file-get-master \
ksym-default-drm-format-info \
ksym-default-drm-framebuffer-cleanup \
ksym-default-drm-framebuffer-init \
ksym-default-drm-gem-create-mmap-offset \
ksym-default-drm-gem-handle-create \
ksym-default-drm-gem-mmap-obj \
ksym-default-drm-gem-object-free \
ksym-default-drm-gem-object-lookup \
ksym-default-drm-gem-object-release \
ksym-default-drm-gem-prime-export \
ksym-default-drm-gem-prime-fd-to-handle \
ksym-default-drm-gem-prime-handle-to-fd \
ksym-default-drm-gem-prime-import \
ksym-default-drm-gem-private-object-init \
ksym-default-drm-gem-vm-close \
ksym-default-drm-gem-vm-open \
ksym-default-drm-helper-hpd-irq-event \
ksym-default-drm-helper-mode-fill-fb-struct \
ksym-default-drm-helper-probe-single-connector-modes \
ksym-default-drm-ioctl \
ksym-default-drm-kms-helper-hotplug-event \
ksym-default-drm-kms-helper-poll-disable \
ksym-default-drm-kms-helper-poll-enable \
ksym-default-drm-kms-helper-poll-fini \
ksym-default-drm-kms-helper-poll-init \
ksym-default-drm-master-put \
ksym-default-drm-mode-config-cleanup \
ksym-default-drm-mode-config-reset \
ksym-default-drm-mode-create \
ksym-default-drm-mode-create-dp-colorspace-property \
ksym-default-drm-mode-create-dvi-i-properties \
ksym-default-drm-mode-create-hdmi-colorspace-property \
ksym-default-drm-mode-crtc-set-gamma-size \
ksym-default-drm-mode-object-find \
ksym-default-drm-mode-object-put \
ksym-default-drm-mode-probed-add \
ksym-default-drm-mode-set-name \
ksym-default-drm-mode-vrefresh \
ksym-default-drm-modeset-acquire-fini \
ksym-default-drm-modeset-acquire-init \
ksym-default-drm-modeset-backoff \
ksym-default-drm-modeset-drop-locks \
ksym-default-drm-modeset-lock-all \
ksym-default-drm-modeset-lock-all-ctx \
ksym-default-drm-modeset-unlock-all \
ksym-default-drm-object-attach-property \
ksym-default-drm-object-property-set-value \
ksym-default-drm-open \
ksym-default-drm-plane-cleanup \
ksym-default-drm-plane-create-alpha-property \
ksym-default-drm-plane-create-blend-mode-property \
ksym-default-drm-plane-create-color-properties \
ksym-default-drm-plane-create-rotation-property \
ksym-default-drm-poll \
ksym-default-drm-prime-gem-destroy \
ksym-default-drm-prime-pages-to-sg \
ksym-default-drm-property-blob-get \
ksym-default-drm-property-blob-put \
ksym-default-drm-property-create \
ksym-default-drm-property-create-enum \
ksym-default-drm-property-create-range \
ksym-default-drm-property-lookup-blob \
ksym-default-drm-read \
ksym-default-drm-release \
ksym-default-drm-universal-plane-init \
ksym-default-drm-vma-node-is-allowed \
ksym-default-drm-vma-offset-lookup-locked \
ksym-default-drmm-mode-config-init \
ksym-default-dump-stack \
ksym-default-dynamic-cond-resched \
ksym-default-dynamic-might-resched \
ksym-default-dynamic-preempt-schedule \
ksym-default-dynamic-preempt-schedule-notrace \
ksym-default-ecc-digits-from-bytes \
ksym-default-ecc-gen-privkey \
ksym-default-ecc-get-curve \
ksym-default-ecc-is-pubkey-valid-full \
ksym-default-ecc-make-pub-key \
ksym-default-efi \
ksym-default-enable-irq \
ksym-default-fd-install \
ksym-default-fget \
ksym-default-filp-close \
ksym-default-filp-open \
ksym-default-find-vma \
ksym-default-find-vma-intersection \
ksym-default-finish-wait \
ksym-default-flush-dcache-page \
ksym-default-follow-pfnmap-end \
ksym-default-follow-pfnmap-start \
ksym-default-fput \
ksym-default-free-irq \
ksym-default-free-pages \
ksym-default-freezer-active \
ksym-default-freezing-slow-path \
ksym-default-full-name-hash \
ksym-default-get-dev-pagemap \
ksym-default-get-free-pages-noprof \
ksym-default-get-mem-cgroup-from-mm \
ksym-default-get-random-bytes \
ksym-default-get-task-pid \
ksym-default-get-unused-fd-flags \
ksym-default-get-user-pages-remote \
ksym-default-gpio-device-find-by-fwnode \
ksym-default-gpio-device-get-chip \
ksym-default-gpio-device-get-desc \
ksym-default-gpio-device-put \
ksym-default-gpio-free \
ksym-default-gpio-request \
ksym-default-gpio-to-desc \
ksym-default-gpiod-direction-input \
ksym-default-gpiod-direction-output-raw \
ksym-default-gpiod-get-raw-value \
ksym-default-gpiod-set-raw-value \
ksym-default-gpiod-to-irq \
ksym-default-handle-mm-fault \
ksym-default-hmm-range-fault \
ksym-default-hrtimer-cancel \
ksym-default-hrtimer-setup \
ksym-default-hrtimer-start-range-ns \
ksym-default-i2c-add-adapter \
ksym-default-i2c-del-adapter \
ksym-default-icc-set-bw \
ksym-default-idr-get-next \
ksym-default-init-pid-ns \
ksym-default-init-wait-entry \
ksym-default-int-active-memcg \
ksym-default-iomem-resource \
ksym-default-iommu-get-domain-for-dev \
ksym-default-iommu-sva-bind-device \
ksym-default-iommu-sva-get-pasid \
ksym-default-iommu-sva-unbind-device \
ksym-default-iounmap \
ksym-default-iov-iter-kvec \
ksym-default-is-acpi-device-node \
ksym-default-is-vmalloc-addr \
ksym-default-iterate-fd \
ksym-default-jiffies \
ksym-default-jiffies-to-timespec64 \
ksym-default-kernel-read \
ksym-default-kernel-write \
ksym-default-key-type-asymmetric \
ksym-default-kfree \
ksym-default-kfree-sensitive \
ksym-default-kimage-voffset \
ksym-default-kmalloc-caches \
ksym-default-kmem-cache-alloc-noprof \
ksym-default-kmem-cache-destroy \
ksym-default-kmem-cache-free \
ksym-default-krealloc-node-align-noprof \
ksym-default-ksize \
ksym-default-kthread-create-on-node \
ksym-default-kthread-should-stop \
ksym-default-kthread-stop \
ksym-default-ktime-get-raw-ts64 \
ksym-default-ktime-get-real-ts64 \
ksym-default-kvasprintf \
ksym-default-kvfree \
ksym-default-logic-inb \
ksym-default-logic-inl \
ksym-default-logic-inw \
ksym-default-logic-outb \
ksym-default-logic-outl \
ksym-default-logic-outw \
ksym-default-make-device-exclusive \
ksym-default-memcmp \
ksym-default-memcpy \
ksym-default-memcpy-fromio \
ksym-default-memcpy-toio \
ksym-default-memmove \
ksym-default-memory-block-size-bytes \
ksym-default-memory-failure-queue \
ksym-default-memremap-pages \
ksym-default-memset \
ksym-default-memset-io \
ksym-default-memstart-addr \
ksym-default-memunmap-pages \
ksym-default-migrate-device-finalize \
ksym-default-migrate-device-pages \
ksym-default-migrate-device-range \
ksym-default-migrate-vma-finalize \
ksym-default-migrate-vma-pages \
ksym-default-migrate-vma-setup \
ksym-default-mmput \
ksym-default-mmu-interval-notifier-insert \
ksym-default-mmu-interval-notifier-remove \
ksym-default-mmu-interval-read-begin \
ksym-default-mod-node-page-state \
ksym-default-mod-timer \
ksym-default-module-layout \
ksym-default-module-put \
ksym-default-mpi-alloc \
ksym-default-mpi-free \
ksym-default-mpi-powm \
ksym-default-mpi-read-buffer \
ksym-default-mpi-read-raw-data \
ksym-default-msleep \
ksym-default-mtree-load \
ksym-default-mutex-init-generic \
ksym-default-mutex-is-locked \
ksym-default-mutex-lock \
ksym-default-mutex-lock-interruptible \
ksym-default-mutex-trylock \
ksym-default-mutex-unlock \
ksym-default-node-data \
ksym-default-node-states \
ksym-default-node-to-cpumask-map \
ksym-default-noop-llseek \
ksym-default-nr-cpu-ids \
ksym-default-numa-node \
ksym-default-of-address-to-resource \
ksym-default-of-device-is-available \
ksym-default-of-find-compatible-node \
ksym-default-of-find-matching-node-and-match \
ksym-default-of-find-node-opts-by-path \
ksym-default-of-find-property \
ksym-default-of-get-child-by-name \
ksym-default-of-get-property \
ksym-default-of-node-put \
ksym-default-of-parse-phandle-with-args-map \
ksym-default-of-prop-next-u32 \
ksym-default-of-property-count-elems-of-size \
ksym-default-of-property-read-bool \
ksym-default-of-property-read-string \
ksym-default-of-property-read-u64 \
ksym-default-of-property-read-variable-u32-array \
ksym-default-offline-and-remove-memory \
ksym-default-on-each-cpu-cond-mask \
ksym-default-out-of-line-wait-on-bit-lock \
ksym-default-panic \
ksym-default-param-ops-bool \
ksym-default-param-ops-charp \
ksym-default-param-ops-int \
ksym-default-param-ops-uint \
ksym-default-param-ops-ulong \
ksym-default-pci-assign-unassigned-bus-resources \
ksym-default-pci-ats-supported \
ksym-default-pci-bus-type \
ksym-default-pci-clear-master \
ksym-default-pci-dev-present \
ksym-default-pci-dev-put \
ksym-default-pci-device-is-present \
ksym-default-pci-disable-device \
ksym-default-pci-disable-msi \
ksym-default-pci-disable-msix \
ksym-default-pci-enable-atomic-ops-to-root \
ksym-default-pci-enable-device \
ksym-default-pci-enable-msi \
ksym-default-pci-enable-msix-range \
ksym-default-pci-find-capability \
ksym-default-pci-find-host-bridge \
ksym-default-pci-get-class \
ksym-default-pci-get-domain-bus-and-slot \
ksym-default-pci-iomap \
ksym-default-pci-iounmap \
ksym-default-pci-read-config-byte \
ksym-default-pci-read-config-dword \
ksym-default-pci-read-config-word \
ksym-default-pci-rebar-bytes-to-size \
ksym-default-pci-rebar-get-possible-sizes \
ksym-default-pci-release-regions \
ksym-default-pci-release-resource \
ksym-default-pci-request-regions \
ksym-default-pci-resize-resource \
ksym-default-pci-restore-state \
ksym-default-pci-save-state \
ksym-default-pci-set-master \
ksym-default-pci-stop-and-remove-bus-device \
ksym-default-pci-unregister-driver \
ksym-default-pci-write-config-byte \
ksym-default-pci-write-config-dword \
ksym-default-pci-write-config-word \
ksym-default-pcibios-resource-to-bus \
ksym-default-pcie-capability-read-word \
ksym-default-pcie-reset-flr \
ksym-default-percpu-counter-add-batch \
ksym-default-percpu-counter-batch \
ksym-default-perf-trace-buf-alloc \
ksym-default-perf-trace-run-bpf-submit \
ksym-default-pfn-is-map-memory \
ksym-default-pid-vnr \
ksym-default-pin-user-pages \
ksym-default-pin-user-pages-remote \
ksym-default-platform-driver-unregister \
ksym-default-pm-runtime-allow \
ksym-default-pm-runtime-enable \
ksym-default-pm-runtime-forbid \
ksym-default-pm-runtime-set-autosuspend-delay \
ksym-default-pm-vt-switch-required \
ksym-default-pm-vt-switch-unregister \
ksym-default-prepare-to-wait-event \
ksym-default-proc-create-data \
ksym-default-proc-mkdir-mode \
ksym-default-proc-remove \
ksym-default-proc-symlink \
ksym-default-prot-ns-shared \
ksym-default-public-key-verify-signature \
ksym-default-put-pid \
ksym-default-put-unused-fd \
ksym-default-pxm-to-node \
ksym-default-queue-delayed-work-on \
ksym-default-queue-work-on \
ksym-default-radix-tree-delete \
ksym-default-radix-tree-gang-lookup \
ksym-default-radix-tree-insert \
ksym-default-radix-tree-lookup \
ksym-default-radix-tree-next-chunk \
ksym-default-random-kmalloc-seed \
ksym-default-rb-erase \
ksym-default-rb-insert-color \
ksym-default-refcount-warn-saturate \
ksym-default-register-acpi-notifier \
ksym-default-register-chrdev-region \
ksym-default-register-memory-notifier \
ksym-default-register-pm-notifier \
ksym-default-release-firmware \
ksym-default-remap-pfn-range \
ksym-default-remove-proc-entry \
ksym-default-request-firmware \
ksym-default-request-free-mem-region \
ksym-default-request-threaded-irq \
ksym-default-rsi-present \
ksym-default-schedule \
ksym-default-schedule-timeout \
ksym-default-seq-lseek \
ksym-default-seq-printf \
ksym-default-seq-read \
ksym-default-seq-read-iter \
ksym-default-set-cpus-allowed-ptr \
ksym-default-set-memory-decrypted \
ksym-default-set-memory-encrypted \
ksym-default-set-normalized-timespec64 \
ksym-default-set-page-dirty \
ksym-default-set-page-dirty-lock \
ksym-default-sg-alloc-table \
ksym-default-sg-alloc-table-from-pages-segment \
ksym-default-sg-free-table \
ksym-default-sg-init-table \
ksym-default-shrinker-alloc \
ksym-default-shrinker-free \
ksym-default-shrinker-register \
ksym-default-simple-strtoul \
ksym-default-single-open \
ksym-default-single-release \
ksym-default-sized-strscpy \
ksym-default-snprintf \
ksym-default-sort \
ksym-default-sprintf \
ksym-default-sscanf \
ksym-default-strcasecmp \
ksym-default-strchr \
ksym-default-strcmp \
ksym-default-strcpy \
ksym-default-strlcat \
ksym-default-strlen \
ksym-default-strncat \
ksym-default-strncmp \
ksym-default-strnlen \
ksym-default-strrchr \
ksym-default-strsep \
ksym-default-strstr \
ksym-default-sync-file-create \
ksym-default-sync-file-get-fence \
ksym-default-sysfb-primary-display \
ksym-default-system-percpu-wq \
ksym-default-task-active-pid-ns \
ksym-default-tegra-bpmp-get \
ksym-default-tegra-bpmp-transfer \
ksym-default-timer-delete-sync \
ksym-default-timer-init-key \
ksym-default-trace-event-buffer-commit \
ksym-default-trace-event-buffer-reserve \
ksym-default-trace-event-printf \
ksym-default-trace-event-raw-init \
ksym-default-trace-event-reg \
ksym-default-trace-handle-return \
ksym-default-trace-raw-output-prep \
ksym-default-tracepoint-srcu \
ksym-default-try-module-get \
ksym-default-unlock-page \
ksym-default-unmap-mapping-range \
ksym-default-unpin-user-page \
ksym-default-unregister-acpi-notifier \
ksym-default-unregister-chrdev-region \
ksym-default-unregister-memory-notifier \
ksym-default-unregister-pm-notifier \
ksym-default-up \
ksym-default-up-read \
ksym-default-up-write \
ksym-default-update-devfreq \
ksym-default-usleep-range-state \
ksym-default-validate-usercopy-range \
ksym-default-vfree \
ksym-default-vga-set-legacy-decoding \
ksym-default-vm-get-page-prot \
ksym-default-vm-insert-page \
ksym-default-vmalloc-noprof \
ksym-default-vmalloc-to-page \
ksym-default-vmap \
ksym-default-vmf-insert-mixed \
ksym-default-vmf-insert-pfn \
ksym-default-vmf-insert-pfn-prot \
ksym-default-vprintk \
ksym-default-vsnprintf \
ksym-default-vunmap \
ksym-default-vzalloc-noprof \
ksym-default-wait-for-completion \
ksym-default-wait-for-completion-interruptible \
ksym-default-wait-for-random-bytes \
ksym-default-wake-up-bit \
ksym-default-wake-up-process \
ksym-default-ww-mutex-lock \
ksym-default-ww-mutex-unlock \
ksym-default-zone-device-page-init \
perl-Bootloader \
suse-kernel-rpm-scriptlets \
update-alternatives"

inherit rpm
