SUMMARY = "X.Org fonts"
DESCRIPTION = "This package contains fonts maintained and shipped with X.Org."
LICENSE = "MIT"

PV = "7.6"

RPM_NAME = "xorg-x11-fonts-7.6-49.3.noarch.rpm"
RPM_HASH = "f8147868d5a12f602fc413d39b8419a26966fc34275a85403f2722854a53fc5dfcecda8623249255039e0aac74f4b2e4637304d47528087c0f8d4aab20c40222"
REPO_ARCH = "noarch"

RPROVIDES:${PN} += "font--lang=aa \
font--lang=af \
font--lang=agr \
font--lang=am \
font--lang=an \
font--lang=ay \
font--lang=ayc \
font--lang=bem \
font--lang=bi \
font--lang=br \
font--lang=bs \
font--lang=byn \
font--lang=ca \
font--lang=ch \
font--lang=co \
font--lang=crh \
font--lang=cs \
font--lang=csb \
font--lang=da \
font--lang=de \
font--lang=dsb \
font--lang=en \
font--lang=eo \
font--lang=es \
font--lang=et \
font--lang=eu \
font--lang=fi \
font--lang=fil \
font--lang=fj \
font--lang=fo \
font--lang=fr \
font--lang=fur \
font--lang=fy \
font--lang=gd \
font--lang=gez \
font--lang=gl \
font--lang=gv \
font--lang=ho \
font--lang=hr \
font--lang=hsb \
font--lang=ht \
font--lang=hu \
font--lang=ia \
font--lang=id \
font--lang=ie \
font--lang=io \
font--lang=is \
font--lang=it \
font--lang=jv \
font--lang=ki \
font--lang=kj \
font--lang=kl \
font--lang=ku-tr \
font--lang=kwm \
font--lang=la \
font--lang=lb \
font--lang=lg \
font--lang=li \
font--lang=lij \
font--lang=lt \
font--lang=lv \
font--lang=mfe \
font--lang=mg \
font--lang=mh \
font--lang=mi \
font--lang=mjw \
font--lang=ms \
font--lang=mt \
font--lang=na \
font--lang=nb \
font--lang=nds \
font--lang=ng \
font--lang=nhn \
font--lang=niu \
font--lang=nl \
font--lang=nn \
font--lang=no \
font--lang=nr \
font--lang=nso \
font--lang=ny \
font--lang=oc \
font--lang=om \
font--lang=pap-an \
font--lang=pap-aw \
font--lang=pl \
font--lang=pt \
font--lang=rm \
font--lang=rn \
font--lang=ro \
font--lang=rw \
font--lang=sc \
font--lang=se \
font--lang=sg \
font--lang=sid \
font--lang=sk \
font--lang=sl \
font--lang=sma \
font--lang=smj \
font--lang=smn \
font--lang=sn \
font--lang=so \
font--lang=sq \
font--lang=ss \
font--lang=st \
font--lang=su \
font--lang=sv \
font--lang=sw \
font--lang=syr \
font--lang=szl \
font--lang=ti-er \
font--lang=ti-et \
font--lang=tig \
font--lang=tk \
font--lang=tl \
font--lang=tn \
font--lang=tpi \
font--lang=tr \
font--lang=ts \
font--lang=unm \
font--lang=uz \
font--lang=vo \
font--lang=vot \
font--lang=wa \
font--lang=wae \
font--lang=wal \
font--lang=wen \
font--lang=wo \
font--lang=xh \
font--lang=yap \
font--lang=yuw \
font--lang=za \
font--lang=zu \
font-eastsyriacadiabene \
font-eastsyriacctesiphon \
font-estrangeloantioch \
font-estrangeloedessa \
font-estrangelomidyat \
font-estrangelonisibin \
font-estrangelonisibinoutline \
font-estrangeloquenneshrin \
font-estrangelotalada \
font-estrangeloturabdin \
font-goha-tibebzemen \
font-luximono \
font-luxisans \
font-luxiserif \
font-sertobatnan \
font-sertojerusalem \
font-sertojerusalemoutline \
font-sertokharput \
font-sertomalankara \
font-sertomardin \
font-sertourhoy \
xorg-x11-fonts \
xorg-x11-fonts-cyrillic \
xorg-x11-fonts-scalable \
xorg-x11-fonts-syriac"

RDEPENDS:${PN} += "/usr/bin/sh \
fonts-config \
xorg-x11-fonts-core"

inherit rpm
