SUMMARY = "User Space Tools for Kernel Auditing"
DESCRIPTION = "The audit package contains the user space utilities for storing and \
processing the audit records generated by the audit subsystem in the \
Linux kernel."
LICENSE = "LGPL-2.1-or-later"

PV = "4.0.2"

RPM_NAME = "audit-4.0.2-3.5.aarch64.rpm"
RPM_HASH = "4dea68ad305b31aad6fa88f36f4adb1ccc2cb892c6cd8e8ae3d45cff343bcdaad0fa09f25b0eb8f5fd689ebdb59969cb3634ffad3605094d54dce59230162ab1"

RPROVIDES:${PN} += "audit \
config-audit"

RDEPENDS:${PN} += "/usr/bin/sh \
audit-libs \
audit-rules \
coreutils \
group-audit \
ld-linux-aarch64.so.1 \
libaudit.so.1 \
libauparse.so.0 \
libc.so.6 \
libcap-ng.so.0 \
libwrap.so.0"

inherit rpm
