SUMMARY = "Access to formulas in PDF files by assistive technologies"
DESCRIPTION = "PDF documents containing formulas generated by LaTeX are \
usually not accessible by assistive technologies for visually \
impaired people and people with special educational needs \
(i.e., by screen readers and braille displays). The \
axessibility package manages this issue, allowing to create a \
PDF document where the formulas are read by these assistive \
technologies, since it automatically generates hidden comments \
in the PDF document (by means of the /ActualText attribute \
and/or suitable tags) in correspondence to each formula."
LICENSE = "LPPL-1.0"

PV = "2026.226.3.0svn77682"

RPM_NAME = "texlive-axessibility-2026.226.3.0svn77682-60.2.noarch.rpm"
RPM_HASH = "264b51874e46b10323d303d00530cacd5d887538e784021ce3f8bd6564f6c9bfbe3ac714905149a5d7e53c15e0edde36fc067512d58f6c91ba9f24fb586d1a63"
REPO_ARCH = "noarch"

RPROVIDES:${PN} += "tex-axessibility.sty \
texlive-axessibility"

RDEPENDS:${PN} += "/usr/bin/sh \
coreutils \
ed \
findutils \
grep \
sed \
tex-accsupp.sty \
tex-amsmath.sty \
tex-amssymb.sty \
tex-fontenc.sty \
tex-fontspec.sty \
tex-luacode.sty \
tex-tagpdf.sty \
tex-xstring.sty \
texlive \
texlive-filesystem \
texlive-kpathsea \
texlive-kpathsea-bin \
texlive-scripts \
texlive-scripts-bin"

inherit rpm
