SUMMARY = "Severed fonts for texlive-ysabeau"
DESCRIPTION = "The  separated fonts package for texlive-ysabeau"
LICENSE = "OFL-1.1"

PV = "2026.226.1.6svn77682"

RPM_NAME = "texlive-ysabeau-fonts-2026.226.1.6svn77682-59.4.noarch.rpm"
RPM_HASH = "ac388d5b6390ae46458e1a7e1488fb09e3e0ac4604f957c8b2836f5c60b5d304ca8faf8c2bc4753be256138f8f4fe5a23f4b39ca889a3f5fa4d8e11d5ec678df"
REPO_ARCH = "noarch"

RPROVIDES:${PN} += "config-texlive-ysabeau-fonts \
font--lang=aa \
font--lang=ab \
font--lang=af \
font--lang=agr \
font--lang=ak \
font--lang=an \
font--lang=ast \
font--lang=av \
font--lang=ay \
font--lang=ayc \
font--lang=az-az \
font--lang=ba \
font--lang=be \
font--lang=bem \
font--lang=ber-dz \
font--lang=bg \
font--lang=bi \
font--lang=bin \
font--lang=bm \
font--lang=br \
font--lang=bs \
font--lang=bua \
font--lang=ca \
font--lang=ce \
font--lang=ch \
font--lang=chm \
font--lang=co \
font--lang=crh \
font--lang=cs \
font--lang=csb \
font--lang=cv \
font--lang=cy \
font--lang=da \
font--lang=de \
font--lang=dsb \
font--lang=ee \
font--lang=el \
font--lang=en \
font--lang=eo \
font--lang=es \
font--lang=et \
font--lang=eu \
font--lang=fat \
font--lang=ff \
font--lang=fi \
font--lang=fil \
font--lang=fj \
font--lang=fo \
font--lang=fr \
font--lang=fur \
font--lang=fy \
font--lang=ga \
font--lang=gd \
font--lang=gl \
font--lang=gn \
font--lang=gv \
font--lang=ha \
font--lang=haw \
font--lang=ho \
font--lang=hr \
font--lang=hsb \
font--lang=ht \
font--lang=hu \
font--lang=hz \
font--lang=ia \
font--lang=id \
font--lang=ie \
font--lang=ig \
font--lang=ik \
font--lang=io \
font--lang=is \
font--lang=it \
font--lang=jv \
font--lang=kaa \
font--lang=kab \
font--lang=ki \
font--lang=kj \
font--lang=kk \
font--lang=kl \
font--lang=ku-am \
font--lang=ku-tr \
font--lang=kum \
font--lang=kv \
font--lang=kw \
font--lang=kwm \
font--lang=ky \
font--lang=la \
font--lang=lb \
font--lang=lez \
font--lang=lg \
font--lang=li \
font--lang=lij \
font--lang=ln \
font--lang=lt \
font--lang=lv \
font--lang=mfe \
font--lang=mg \
font--lang=mh \
font--lang=mhr \
font--lang=mi \
font--lang=miq \
font--lang=mjw \
font--lang=mk \
font--lang=mn-mn \
font--lang=mo \
font--lang=ms \
font--lang=mt \
font--lang=na \
font--lang=nb \
font--lang=nds \
font--lang=ng \
font--lang=nhn \
font--lang=niu \
font--lang=nl \
font--lang=nn \
font--lang=no \
font--lang=nr \
font--lang=nso \
font--lang=nv \
font--lang=ny \
font--lang=oc \
font--lang=om \
font--lang=os \
font--lang=pap-an \
font--lang=pap-aw \
font--lang=pl \
font--lang=pt \
font--lang=qu \
font--lang=quz \
font--lang=rif \
font--lang=rm \
font--lang=rn \
font--lang=ro \
font--lang=ru \
font--lang=rw \
font--lang=sah \
font--lang=sc \
font--lang=se \
font--lang=sel \
font--lang=sg \
font--lang=sgs \
font--lang=sh \
font--lang=sk \
font--lang=sl \
font--lang=sm \
font--lang=sma \
font--lang=smj \
font--lang=smn \
font--lang=sms \
font--lang=sn \
font--lang=so \
font--lang=sq \
font--lang=sr \
font--lang=ss \
font--lang=st \
font--lang=su \
font--lang=sv \
font--lang=sw \
font--lang=szl \
font--lang=tg \
font--lang=tk \
font--lang=tl \
font--lang=tn \
font--lang=to \
font--lang=tpi \
font--lang=tr \
font--lang=ts \
font--lang=tt \
font--lang=tw \
font--lang=ty \
font--lang=tyv \
font--lang=uk \
font--lang=unm \
font--lang=uz \
font--lang=ve \
font--lang=vi \
font--lang=vo \
font--lang=vot \
font--lang=wa \
font--lang=wae \
font--lang=wen \
font--lang=wo \
font--lang=xh \
font--lang=yap \
font--lang=yo \
font--lang=yuw \
font--lang=za \
font--lang=zu \
font-ysabeau \
font-ysabeau-black \
font-ysabeau-blackitalic \
font-ysabeau-bold \
font-ysabeau-bolditalic \
font-ysabeau-extrabold \
font-ysabeau-extrabolditalic \
font-ysabeau-extralight \
font-ysabeau-extralightitalic \
font-ysabeau-hairline \
font-ysabeau-hairlineitalic \
font-ysabeau-italic \
font-ysabeau-light \
font-ysabeau-lightitalic \
font-ysabeau-medium \
font-ysabeau-mediumitalic \
font-ysabeau-regular \
font-ysabeau-semibold \
font-ysabeau-semibolditalic \
font-ysabeau-thin \
font-ysabeau-thinitalic \
font-ysabeaublack \
font-ysabeauextrabold \
font-ysabeauextralight \
font-ysabeauhairline \
font-ysabeaulight \
font-ysabeaumedium \
font-ysabeausemibold \
font-ysabeauthin \
texlive-ysabeau-fonts"

RDEPENDS:${PN} += "/usr/bin/sh \
aaa-base \
coreutils \
fontconfig \
ghostscript-fonts-std \
perl"

inherit rpm
