SUMMARY = "Terminal email client"
DESCRIPTION = "Terminal email client with support for multiple accounts and Maildir / mbox / notmuch / IMAP / JMAP."
LICENSE = "GPL-3.0-or-later"

PV = "0.8.11"

RPM_NAME = "meli-with-debug-tracing-0.8.11-1.9.aarch64.rpm"
RPM_HASH = "324bfbc72fc51df9fbe0d095391b13f494e0f65cc566f4ce8bdc35f5eee44278018df31b1c2f90f4015f07b1c4fcdb96cf745319c78aae82405ca4207c7eaf1e"

RPROVIDES:${PN} += "bundled-rust-crate-abnf-core \
bundled-rust-crate-adler2 \
bundled-rust-crate-ahash \
bundled-rust-crate-aho-corasick \
bundled-rust-crate-allocator-api2 \
bundled-rust-crate-async-channel \
bundled-rust-crate-async-executor \
bundled-rust-crate-async-fn-stream \
bundled-rust-crate-async-fs \
bundled-rust-crate-async-io \
bundled-rust-crate-async-lock \
bundled-rust-crate-async-net \
bundled-rust-crate-async-process \
bundled-rust-crate-async-signal \
bundled-rust-crate-async-task \
bundled-rust-crate-atomic-waker \
bundled-rust-crate-autocfg \
bundled-rust-crate-base64 \
bundled-rust-crate-bitflags \
bundled-rust-crate-blocking \
bundled-rust-crate-bounded-static \
bundled-rust-crate-bounded-static-derive \
bundled-rust-crate-bytes \
bundled-rust-crate-castaway \
bundled-rust-crate-cc \
bundled-rust-crate-cfg-aliases \
bundled-rust-crate-cfg-if \
bundled-rust-crate-chrono \
bundled-rust-crate-clap \
bundled-rust-crate-concurrent-queue \
bundled-rust-crate-crc32fast \
bundled-rust-crate-crossbeam \
bundled-rust-crate-crossbeam-channel \
bundled-rust-crate-crossbeam-deque \
bundled-rust-crate-crossbeam-epoch \
bundled-rust-crate-crossbeam-queue \
bundled-rust-crate-crossbeam-utils \
bundled-rust-crate-csv \
bundled-rust-crate-csv-core \
bundled-rust-crate-curl \
bundled-rust-crate-curl-sys \
bundled-rust-crate-data-encoding \
bundled-rust-crate-dbus \
bundled-rust-crate-deranged \
bundled-rust-crate-encoding-rs \
bundled-rust-crate-equivalent \
bundled-rust-crate-errno \
bundled-rust-crate-event-listener \
bundled-rust-crate-event-listener-strategy \
bundled-rust-crate-fallible-iterator \
bundled-rust-crate-fallible-streaming-iterator \
bundled-rust-crate-fastrand \
bundled-rust-crate-filetime \
bundled-rust-crate-flate2 \
bundled-rust-crate-fnv \
bundled-rust-crate-foreign-types \
bundled-rust-crate-foreign-types-shared \
bundled-rust-crate-form-urlencoded \
bundled-rust-crate-futures \
bundled-rust-crate-futures-channel \
bundled-rust-crate-futures-core \
bundled-rust-crate-futures-executor \
bundled-rust-crate-futures-io \
bundled-rust-crate-futures-lite \
bundled-rust-crate-futures-macro \
bundled-rust-crate-futures-sink \
bundled-rust-crate-futures-task \
bundled-rust-crate-futures-util \
bundled-rust-crate-getrandom \
bundled-rust-crate-hashbrown \
bundled-rust-crate-hashlink \
bundled-rust-crate-heck \
bundled-rust-crate-http \
bundled-rust-crate-iana-time-zone \
bundled-rust-crate-idna \
bundled-rust-crate-imap-codec \
bundled-rust-crate-imap-types \
bundled-rust-crate-indexmap \
bundled-rust-crate-inotify \
bundled-rust-crate-inotify-sys \
bundled-rust-crate-isahc \
bundled-rust-crate-itoa \
bundled-rust-crate-lazy-static \
bundled-rust-crate-libc \
bundled-rust-crate-libdbus-sys \
bundled-rust-crate-libloading \
bundled-rust-crate-libnghttp2-sys \
bundled-rust-crate-libsqlite3-sys \
bundled-rust-crate-libz-sys \
bundled-rust-crate-linkify \
bundled-rust-crate-linux-raw-sys \
bundled-rust-crate-log \
bundled-rust-crate-meli \
bundled-rust-crate-melib \
bundled-rust-crate-memchr \
bundled-rust-crate-memoffset \
bundled-rust-crate-mime \
bundled-rust-crate-minimal-lexical \
bundled-rust-crate-miniz-oxide \
bundled-rust-crate-mio \
bundled-rust-crate-native-tls \
bundled-rust-crate-nix \
bundled-rust-crate-nom \
bundled-rust-crate-notify \
bundled-rust-crate-notify-rust \
bundled-rust-crate-num-conv \
bundled-rust-crate-num-traits \
bundled-rust-crate-numtoa \
bundled-rust-crate-once-cell \
bundled-rust-crate-openssl \
bundled-rust-crate-openssl-macros \
bundled-rust-crate-openssl-probe \
bundled-rust-crate-openssl-src \
bundled-rust-crate-openssl-sys \
bundled-rust-crate-parking \
bundled-rust-crate-percent-encoding \
bundled-rust-crate-pin-project \
bundled-rust-crate-pin-project-internal \
bundled-rust-crate-pin-project-lite \
bundled-rust-crate-pin-utils \
bundled-rust-crate-piper \
bundled-rust-crate-pkg-config \
bundled-rust-crate-polling \
bundled-rust-crate-powerfmt \
bundled-rust-crate-proc-macro-error \
bundled-rust-crate-proc-macro-error-attr \
bundled-rust-crate-proc-macro2 \
bundled-rust-crate-quote \
bundled-rust-crate-regex \
bundled-rust-crate-regex-automata \
bundled-rust-crate-regex-syntax \
bundled-rust-crate-rusqlite \
bundled-rust-crate-rustix \
bundled-rust-crate-ryu \
bundled-rust-crate-same-file \
bundled-rust-crate-serde \
bundled-rust-crate-serde-derive \
bundled-rust-crate-serde-json \
bundled-rust-crate-serde-path-to-error \
bundled-rust-crate-serde-spanned \
bundled-rust-crate-sha1-smol \
bundled-rust-crate-shlex \
bundled-rust-crate-signal-hook \
bundled-rust-crate-signal-hook-registry \
bundled-rust-crate-slab \
bundled-rust-crate-sluice \
bundled-rust-crate-smallvec \
bundled-rust-crate-smol \
bundled-rust-crate-socket2 \
bundled-rust-crate-structopt \
bundled-rust-crate-structopt-derive \
bundled-rust-crate-syn \
bundled-rust-crate-termion \
bundled-rust-crate-textwrap \
bundled-rust-crate-thiserror \
bundled-rust-crate-thiserror-impl \
bundled-rust-crate-time \
bundled-rust-crate-time-core \
bundled-rust-crate-time-macros \
bundled-rust-crate-tinyvec \
bundled-rust-crate-tinyvec-macros \
bundled-rust-crate-toml \
bundled-rust-crate-toml-datetime \
bundled-rust-crate-toml-edit \
bundled-rust-crate-tracing \
bundled-rust-crate-tracing-attributes \
bundled-rust-crate-tracing-core \
bundled-rust-crate-tracing-futures \
bundled-rust-crate-unicode-bidi \
bundled-rust-crate-unicode-ident \
bundled-rust-crate-unicode-normalization \
bundled-rust-crate-unicode-segmentation \
bundled-rust-crate-unicode-width \
bundled-rust-crate-url \
bundled-rust-crate-uuid \
bundled-rust-crate-vcpkg \
bundled-rust-crate-version-check \
bundled-rust-crate-waker-fn \
bundled-rust-crate-walkdir \
bundled-rust-crate-winnow \
bundled-rust-crate-xdg \
bundled-rust-crate-zerocopy \
meli \
meli-with-debug-tracing"

RDEPENDS:${PN} += "libc.so.6 \
libgcc-s.so.1 \
libm.so.6"

inherit rpm
