SUMMARY = "RPM provides for QML modules from qtdeclarative"
DESCRIPTION = "A separately built package to avoid a build cycle."
LICENSE = "GPL-3.0-or-later"

PV = "1.0"

RPM_NAME = "qtdeclarative-imports-provides-qt6-1.0-1.57.aarch64.rpm"
RPM_HASH = "f3899a02b4a57620949627aa2f3fce38720fd1a1126242515666901814ce362d21b6e639806462ae2bebc47e13fc6eea0a914a6caad71924951e66a6c0a51ffd"

RPROVIDES:${PN} += "qt6qmlimport-QML \
qt6qmlimport-QmlTime \
qt6qmlimport-Qt.labs.StyleKit \
qt6qmlimport-Qt.labs.StyleKit.2 \
qt6qmlimport-Qt.labs.StyleKit.254 \
qt6qmlimport-Qt.labs.StyleKit.6 \
qt6qmlimport-Qt.labs.StyleKit.impl \
qt6qmlimport-Qt.labs.StyleKit.impl.2 \
qt6qmlimport-Qt.labs.StyleKit.impl.254 \
qt6qmlimport-Qt.labs.StyleKit.impl.6 \
qt6qmlimport-Qt.labs.animation \
qt6qmlimport-Qt.labs.animation.1 \
qt6qmlimport-Qt.labs.animation.6 \
qt6qmlimport-Qt.labs.folderlistmodel \
qt6qmlimport-Qt.labs.folderlistmodel.1 \
qt6qmlimport-Qt.labs.folderlistmodel.2 \
qt6qmlimport-Qt.labs.folderlistmodel.6 \
qt6qmlimport-Qt.labs.platform \
qt6qmlimport-Qt.labs.platform.1 \
qt6qmlimport-Qt.labs.qmlmodels \
qt6qmlimport-Qt.labs.qmlmodels.1 \
qt6qmlimport-Qt.labs.qmlmodels.6 \
qt6qmlimport-Qt.labs.settings \
qt6qmlimport-Qt.labs.settings.1 \
qt6qmlimport-Qt.labs.settings.6 \
qt6qmlimport-Qt.labs.sharedimage \
qt6qmlimport-Qt.labs.sharedimage.1 \
qt6qmlimport-Qt.labs.sharedimage.6 \
qt6qmlimport-Qt.labs.synchronizer \
qt6qmlimport-Qt.labs.synchronizer.6 \
qt6qmlimport-Qt.labs.wavefrontmesh \
qt6qmlimport-Qt.labs.wavefrontmesh.1 \
qt6qmlimport-Qt.labs.wavefrontmesh.6 \
qt6qmlimport-Qt.test.controls \
qt6qmlimport-Qt.test.controls.6 \
qt6qmlimport-QtCore \
qt6qmlimport-QtCore.6 \
qt6qmlimport-QtNetwork \
qt6qmlimport-QtNetwork.6 \
qt6qmlimport-QtQml \
qt6qmlimport-QtQml.2 \
qt6qmlimport-QtQml.6 \
qt6qmlimport-QtQml.Models \
qt6qmlimport-QtQml.Models.2 \
qt6qmlimport-QtQml.Models.6 \
qt6qmlimport-QtQml.WorkerScript \
qt6qmlimport-QtQml.WorkerScript.2 \
qt6qmlimport-QtQml.WorkerScript.6 \
qt6qmlimport-QtQml.XmlListModel \
qt6qmlimport-QtQml.XmlListModel.6 \
qt6qmlimport-QtQuick \
qt6qmlimport-QtQuick.2 \
qt6qmlimport-QtQuick.6 \
qt6qmlimport-QtQuick.Controls \
qt6qmlimport-QtQuick.Controls.2 \
qt6qmlimport-QtQuick.Controls.6 \
qt6qmlimport-QtQuick.Controls.Basic \
qt6qmlimport-QtQuick.Controls.Basic.2 \
qt6qmlimport-QtQuick.Controls.Basic.6 \
qt6qmlimport-QtQuick.Controls.Basic.impl \
qt6qmlimport-QtQuick.Controls.Basic.impl.2 \
qt6qmlimport-QtQuick.Controls.Basic.impl.6 \
qt6qmlimport-QtQuick.Controls.FluentWinUI3 \
qt6qmlimport-QtQuick.Controls.FluentWinUI3.2 \
qt6qmlimport-QtQuick.Controls.FluentWinUI3.6 \
qt6qmlimport-QtQuick.Controls.FluentWinUI3.impl \
qt6qmlimport-QtQuick.Controls.FluentWinUI3.impl.2 \
qt6qmlimport-QtQuick.Controls.FluentWinUI3.impl.6 \
qt6qmlimport-QtQuick.Controls.Fusion \
qt6qmlimport-QtQuick.Controls.Fusion.2 \
qt6qmlimport-QtQuick.Controls.Fusion.6 \
qt6qmlimport-QtQuick.Controls.Fusion.impl \
qt6qmlimport-QtQuick.Controls.Fusion.impl.2 \
qt6qmlimport-QtQuick.Controls.Fusion.impl.6 \
qt6qmlimport-QtQuick.Controls.Imagine \
qt6qmlimport-QtQuick.Controls.Imagine.2 \
qt6qmlimport-QtQuick.Controls.Imagine.6 \
qt6qmlimport-QtQuick.Controls.Imagine.impl \
qt6qmlimport-QtQuick.Controls.Imagine.impl.6 \
qt6qmlimport-QtQuick.Controls.Material \
qt6qmlimport-QtQuick.Controls.Material.2 \
qt6qmlimport-QtQuick.Controls.Material.6 \
qt6qmlimport-QtQuick.Controls.Material.impl \
qt6qmlimport-QtQuick.Controls.Material.impl.2 \
qt6qmlimport-QtQuick.Controls.Material.impl.6 \
qt6qmlimport-QtQuick.Controls.Universal \
qt6qmlimport-QtQuick.Controls.Universal.2 \
qt6qmlimport-QtQuick.Controls.Universal.6 \
qt6qmlimport-QtQuick.Controls.Universal.impl \
qt6qmlimport-QtQuick.Controls.Universal.impl.2 \
qt6qmlimport-QtQuick.Controls.Universal.impl.6 \
qt6qmlimport-QtQuick.Controls.impl \
qt6qmlimport-QtQuick.Controls.impl.2 \
qt6qmlimport-QtQuick.Controls.impl.6 \
qt6qmlimport-QtQuick.Dialogs \
qt6qmlimport-QtQuick.Dialogs.6 \
qt6qmlimport-QtQuick.Dialogs.quickimpl \
qt6qmlimport-QtQuick.Dialogs.quickimpl.2 \
qt6qmlimport-QtQuick.Dialogs.quickimpl.6 \
qt6qmlimport-QtQuick.Effects \
qt6qmlimport-QtQuick.Effects.2 \
qt6qmlimport-QtQuick.Effects.6 \
qt6qmlimport-QtQuick.Layouts \
qt6qmlimport-QtQuick.Layouts.1 \
qt6qmlimport-QtQuick.Layouts.2 \
qt6qmlimport-QtQuick.Layouts.6 \
qt6qmlimport-QtQuick.LocalStorage \
qt6qmlimport-QtQuick.LocalStorage.2 \
qt6qmlimport-QtQuick.LocalStorage.6 \
qt6qmlimport-QtQuick.Particles \
qt6qmlimport-QtQuick.Particles.2 \
qt6qmlimport-QtQuick.Particles.6 \
qt6qmlimport-QtQuick.Shapes \
qt6qmlimport-QtQuick.Shapes.1 \
qt6qmlimport-QtQuick.Shapes.2 \
qt6qmlimport-QtQuick.Shapes.6 \
qt6qmlimport-QtQuick.Shapes.DesignHelpers \
qt6qmlimport-QtQuick.Shapes.DesignHelpers.1 \
qt6qmlimport-QtQuick.Shapes.DesignHelpers.2 \
qt6qmlimport-QtQuick.Shapes.DesignHelpers.6 \
qt6qmlimport-QtQuick.Templates \
qt6qmlimport-QtQuick.Templates.2 \
qt6qmlimport-QtQuick.Templates.6 \
qt6qmlimport-QtQuick.VectorImage \
qt6qmlimport-QtQuick.VectorImage.2 \
qt6qmlimport-QtQuick.VectorImage.6 \
qt6qmlimport-QtQuick.VectorImage.Helpers \
qt6qmlimport-QtQuick.VectorImage.Helpers.2 \
qt6qmlimport-QtQuick.VectorImage.Helpers.6 \
qt6qmlimport-QtQuick.Window \
qt6qmlimport-QtQuick.Window.2 \
qt6qmlimport-QtQuick.Window.6 \
qt6qmlimport-QtQuick.tooling \
qt6qmlimport-QtQuick.tooling.1 \
qt6qmlimport-QtQuick.tooling.6 \
qt6qmlimport-QtTest \
qt6qmlimport-QtTest.1 \
qt6qmlimport-QtTest.6 \
qtdeclarative-imports-provides-qt6"

RDEPENDS:${PN} += "qt6-declarative-imports"

inherit rpm
