SUMMARY = "LaTeX support for EBGaramond fonts"
DESCRIPTION = "EB Garamond is a revival by Georg Duffner of the 16th century \
fonts designed by Claude Garamond. The LaTeX support package \
works for (pdf)LaTeX, XeLaTeX and LuaLaTeX users; configuration \
files for use with microtype are provided."
LICENSE = "OFL-1.1"

PV = "2026.226.svn77682"

RPM_NAME = "texlive-ebgaramond-2026.226.svn77682-61.4.noarch.rpm"
RPM_HASH = "9d49d15d9c4e297a7b02de4a43b6ad52322d1fe57632e87cb3e604e58c6e3fe0772df07272cec6561fa7fce1ef98200e936380a78ca672595dc951312cac1229"
REPO_ARCH = "noarch"

RPROVIDES:${PN} += "tex-EBGaramond-Bold-inf-lgr.tfm \
tex-EBGaramond-Bold-inf-ly1.tfm \
tex-EBGaramond-Bold-inf-ot1.tfm \
tex-EBGaramond-Bold-inf-t1--base.tfm \
tex-EBGaramond-Bold-inf-t1.tfm \
tex-EBGaramond-Bold-inf-t1.vf \
tex-EBGaramond-Bold-lf-lgr.tfm \
tex-EBGaramond-Bold-lf-ly1.tfm \
tex-EBGaramond-Bold-lf-ot1.tfm \
tex-EBGaramond-Bold-lf-sc-lgr.tfm \
tex-EBGaramond-Bold-lf-sc-ly1--base.tfm \
tex-EBGaramond-Bold-lf-sc-ly1.tfm \
tex-EBGaramond-Bold-lf-sc-ly1.vf \
tex-EBGaramond-Bold-lf-sc-ot1--base.tfm \
tex-EBGaramond-Bold-lf-sc-ot1.tfm \
tex-EBGaramond-Bold-lf-sc-ot1.vf \
tex-EBGaramond-Bold-lf-sc-t1--base.tfm \
tex-EBGaramond-Bold-lf-sc-t1.tfm \
tex-EBGaramond-Bold-lf-sc-t1.vf \
tex-EBGaramond-Bold-lf-swash-lgr.tfm \
tex-EBGaramond-Bold-lf-swash-ly1.tfm \
tex-EBGaramond-Bold-lf-swash-ot1.tfm \
tex-EBGaramond-Bold-lf-swash-t1--base.tfm \
tex-EBGaramond-Bold-lf-swash-t1.tfm \
tex-EBGaramond-Bold-lf-swash-t1.vf \
tex-EBGaramond-Bold-lf-t1--base.tfm \
tex-EBGaramond-Bold-lf-t1.tfm \
tex-EBGaramond-Bold-lf-t1.vf \
tex-EBGaramond-Bold-lf-ts1--base.tfm \
tex-EBGaramond-Bold-lf-ts1.tfm \
tex-EBGaramond-Bold-lf-ts1.vf \
tex-EBGaramond-Bold-osf-lgr.tfm \
tex-EBGaramond-Bold-osf-ly1.tfm \
tex-EBGaramond-Bold-osf-ot1.tfm \
tex-EBGaramond-Bold-osf-sc-lgr.tfm \
tex-EBGaramond-Bold-osf-sc-ly1--base.tfm \
tex-EBGaramond-Bold-osf-sc-ly1.tfm \
tex-EBGaramond-Bold-osf-sc-ly1.vf \
tex-EBGaramond-Bold-osf-sc-ot1--base.tfm \
tex-EBGaramond-Bold-osf-sc-ot1.tfm \
tex-EBGaramond-Bold-osf-sc-ot1.vf \
tex-EBGaramond-Bold-osf-sc-t1--base.tfm \
tex-EBGaramond-Bold-osf-sc-t1.tfm \
tex-EBGaramond-Bold-osf-sc-t1.vf \
tex-EBGaramond-Bold-osf-swash-lgr.tfm \
tex-EBGaramond-Bold-osf-swash-ly1.tfm \
tex-EBGaramond-Bold-osf-swash-ot1.tfm \
tex-EBGaramond-Bold-osf-swash-t1--base.tfm \
tex-EBGaramond-Bold-osf-swash-t1.tfm \
tex-EBGaramond-Bold-osf-swash-t1.vf \
tex-EBGaramond-Bold-osf-t1--base.tfm \
tex-EBGaramond-Bold-osf-t1.tfm \
tex-EBGaramond-Bold-osf-t1.vf \
tex-EBGaramond-Bold-osf-ts1--base.tfm \
tex-EBGaramond-Bold-osf-ts1.tfm \
tex-EBGaramond-Bold-osf-ts1.vf \
tex-EBGaramond-Bold-sup-lgr.tfm \
tex-EBGaramond-Bold-sup-ly1.tfm \
tex-EBGaramond-Bold-sup-ot1.tfm \
tex-EBGaramond-Bold-sup-t1--base.tfm \
tex-EBGaramond-Bold-sup-t1.tfm \
tex-EBGaramond-Bold-sup-t1.vf \
tex-EBGaramond-Bold-tlf-lgr.tfm \
tex-EBGaramond-Bold-tlf-ly1.tfm \
tex-EBGaramond-Bold-tlf-ot1.tfm \
tex-EBGaramond-Bold-tlf-sc-lgr.tfm \
tex-EBGaramond-Bold-tlf-sc-ly1--base.tfm \
tex-EBGaramond-Bold-tlf-sc-ly1.tfm \
tex-EBGaramond-Bold-tlf-sc-ly1.vf \
tex-EBGaramond-Bold-tlf-sc-ot1--base.tfm \
tex-EBGaramond-Bold-tlf-sc-ot1.tfm \
tex-EBGaramond-Bold-tlf-sc-ot1.vf \
tex-EBGaramond-Bold-tlf-sc-t1--base.tfm \
tex-EBGaramond-Bold-tlf-sc-t1.tfm \
tex-EBGaramond-Bold-tlf-sc-t1.vf \
tex-EBGaramond-Bold-tlf-swash-lgr.tfm \
tex-EBGaramond-Bold-tlf-swash-ly1.tfm \
tex-EBGaramond-Bold-tlf-swash-ot1.tfm \
tex-EBGaramond-Bold-tlf-swash-t1--base.tfm \
tex-EBGaramond-Bold-tlf-swash-t1.tfm \
tex-EBGaramond-Bold-tlf-swash-t1.vf \
tex-EBGaramond-Bold-tlf-t1--base.tfm \
tex-EBGaramond-Bold-tlf-t1.tfm \
tex-EBGaramond-Bold-tlf-t1.vf \
tex-EBGaramond-Bold-tlf-ts1--base.tfm \
tex-EBGaramond-Bold-tlf-ts1.tfm \
tex-EBGaramond-Bold-tlf-ts1.vf \
tex-EBGaramond-Bold-tosf-lgr.tfm \
tex-EBGaramond-Bold-tosf-ly1.tfm \
tex-EBGaramond-Bold-tosf-ot1.tfm \
tex-EBGaramond-Bold-tosf-sc-lgr.tfm \
tex-EBGaramond-Bold-tosf-sc-ly1--base.tfm \
tex-EBGaramond-Bold-tosf-sc-ly1.tfm \
tex-EBGaramond-Bold-tosf-sc-ly1.vf \
tex-EBGaramond-Bold-tosf-sc-ot1--base.tfm \
tex-EBGaramond-Bold-tosf-sc-ot1.tfm \
tex-EBGaramond-Bold-tosf-sc-ot1.vf \
tex-EBGaramond-Bold-tosf-sc-t1--base.tfm \
tex-EBGaramond-Bold-tosf-sc-t1.tfm \
tex-EBGaramond-Bold-tosf-sc-t1.vf \
tex-EBGaramond-Bold-tosf-swash-lgr.tfm \
tex-EBGaramond-Bold-tosf-swash-ly1.tfm \
tex-EBGaramond-Bold-tosf-swash-ot1.tfm \
tex-EBGaramond-Bold-tosf-swash-t1--base.tfm \
tex-EBGaramond-Bold-tosf-swash-t1.tfm \
tex-EBGaramond-Bold-tosf-swash-t1.vf \
tex-EBGaramond-Bold-tosf-t1--base.tfm \
tex-EBGaramond-Bold-tosf-t1.tfm \
tex-EBGaramond-Bold-tosf-t1.vf \
tex-EBGaramond-Bold-tosf-ts1--base.tfm \
tex-EBGaramond-Bold-tosf-ts1.tfm \
tex-EBGaramond-Bold-tosf-ts1.vf \
tex-EBGaramond-BoldItalic-inf-lgr.tfm \
tex-EBGaramond-BoldItalic-inf-ly1.tfm \
tex-EBGaramond-BoldItalic-inf-ot1.tfm \
tex-EBGaramond-BoldItalic-inf-t1--base.tfm \
tex-EBGaramond-BoldItalic-inf-t1.tfm \
tex-EBGaramond-BoldItalic-inf-t1.vf \
tex-EBGaramond-BoldItalic-lf-lgr.tfm \
tex-EBGaramond-BoldItalic-lf-ly1.tfm \
tex-EBGaramond-BoldItalic-lf-ot1.tfm \
tex-EBGaramond-BoldItalic-lf-sc-lgr.tfm \
tex-EBGaramond-BoldItalic-lf-sc-ly1--base.tfm \
tex-EBGaramond-BoldItalic-lf-sc-ly1.tfm \
tex-EBGaramond-BoldItalic-lf-sc-ly1.vf \
tex-EBGaramond-BoldItalic-lf-sc-ot1--base.tfm \
tex-EBGaramond-BoldItalic-lf-sc-ot1.tfm \
tex-EBGaramond-BoldItalic-lf-sc-ot1.vf \
tex-EBGaramond-BoldItalic-lf-sc-t1--base.tfm \
tex-EBGaramond-BoldItalic-lf-sc-t1.tfm \
tex-EBGaramond-BoldItalic-lf-sc-t1.vf \
tex-EBGaramond-BoldItalic-lf-swash-lgr.tfm \
tex-EBGaramond-BoldItalic-lf-swash-ly1.tfm \
tex-EBGaramond-BoldItalic-lf-swash-ot1.tfm \
tex-EBGaramond-BoldItalic-lf-swash-t1--base.tfm \
tex-EBGaramond-BoldItalic-lf-swash-t1.tfm \
tex-EBGaramond-BoldItalic-lf-swash-t1.vf \
tex-EBGaramond-BoldItalic-lf-t1--base.tfm \
tex-EBGaramond-BoldItalic-lf-t1.tfm \
tex-EBGaramond-BoldItalic-lf-t1.vf \
tex-EBGaramond-BoldItalic-lf-ts1--base.tfm \
tex-EBGaramond-BoldItalic-lf-ts1.tfm \
tex-EBGaramond-BoldItalic-lf-ts1.vf \
tex-EBGaramond-BoldItalic-osf-lgr.tfm \
tex-EBGaramond-BoldItalic-osf-ly1.tfm \
tex-EBGaramond-BoldItalic-osf-ot1.tfm \
tex-EBGaramond-BoldItalic-osf-sc-lgr.tfm \
tex-EBGaramond-BoldItalic-osf-sc-ly1--base.tfm \
tex-EBGaramond-BoldItalic-osf-sc-ly1.tfm \
tex-EBGaramond-BoldItalic-osf-sc-ly1.vf \
tex-EBGaramond-BoldItalic-osf-sc-ot1--base.tfm \
tex-EBGaramond-BoldItalic-osf-sc-ot1.tfm \
tex-EBGaramond-BoldItalic-osf-sc-ot1.vf \
tex-EBGaramond-BoldItalic-osf-sc-t1--base.tfm \
tex-EBGaramond-BoldItalic-osf-sc-t1.tfm \
tex-EBGaramond-BoldItalic-osf-sc-t1.vf \
tex-EBGaramond-BoldItalic-osf-swash-lgr.tfm \
tex-EBGaramond-BoldItalic-osf-swash-ly1.tfm \
tex-EBGaramond-BoldItalic-osf-swash-ot1.tfm \
tex-EBGaramond-BoldItalic-osf-swash-t1--base.tfm \
tex-EBGaramond-BoldItalic-osf-swash-t1.tfm \
tex-EBGaramond-BoldItalic-osf-swash-t1.vf \
tex-EBGaramond-BoldItalic-osf-t1--base.tfm \
tex-EBGaramond-BoldItalic-osf-t1.tfm \
tex-EBGaramond-BoldItalic-osf-t1.vf \
tex-EBGaramond-BoldItalic-osf-ts1--base.tfm \
tex-EBGaramond-BoldItalic-osf-ts1.tfm \
tex-EBGaramond-BoldItalic-osf-ts1.vf \
tex-EBGaramond-BoldItalic-sup-lgr.tfm \
tex-EBGaramond-BoldItalic-sup-ly1.tfm \
tex-EBGaramond-BoldItalic-sup-ot1.tfm \
tex-EBGaramond-BoldItalic-sup-t1--base.tfm \
tex-EBGaramond-BoldItalic-sup-t1.tfm \
tex-EBGaramond-BoldItalic-sup-t1.vf \
tex-EBGaramond-BoldItalic-tlf-lgr.tfm \
tex-EBGaramond-BoldItalic-tlf-ly1.tfm \
tex-EBGaramond-BoldItalic-tlf-ot1.tfm \
tex-EBGaramond-BoldItalic-tlf-sc-lgr.tfm \
tex-EBGaramond-BoldItalic-tlf-sc-ly1--base.tfm \
tex-EBGaramond-BoldItalic-tlf-sc-ly1.tfm \
tex-EBGaramond-BoldItalic-tlf-sc-ly1.vf \
tex-EBGaramond-BoldItalic-tlf-sc-ot1--base.tfm \
tex-EBGaramond-BoldItalic-tlf-sc-ot1.tfm \
tex-EBGaramond-BoldItalic-tlf-sc-ot1.vf \
tex-EBGaramond-BoldItalic-tlf-sc-t1--base.tfm \
tex-EBGaramond-BoldItalic-tlf-sc-t1.tfm \
tex-EBGaramond-BoldItalic-tlf-sc-t1.vf \
tex-EBGaramond-BoldItalic-tlf-swash-lgr.tfm \
tex-EBGaramond-BoldItalic-tlf-swash-ly1.tfm \
tex-EBGaramond-BoldItalic-tlf-swash-ot1.tfm \
tex-EBGaramond-BoldItalic-tlf-swash-t1--base.tfm \
tex-EBGaramond-BoldItalic-tlf-swash-t1.tfm \
tex-EBGaramond-BoldItalic-tlf-swash-t1.vf \
tex-EBGaramond-BoldItalic-tlf-t1--base.tfm \
tex-EBGaramond-BoldItalic-tlf-t1.tfm \
tex-EBGaramond-BoldItalic-tlf-t1.vf \
tex-EBGaramond-BoldItalic-tlf-ts1--base.tfm \
tex-EBGaramond-BoldItalic-tlf-ts1.tfm \
tex-EBGaramond-BoldItalic-tlf-ts1.vf \
tex-EBGaramond-BoldItalic-tosf-lgr.tfm \
tex-EBGaramond-BoldItalic-tosf-ly1.tfm \
tex-EBGaramond-BoldItalic-tosf-ot1.tfm \
tex-EBGaramond-BoldItalic-tosf-sc-lgr.tfm \
tex-EBGaramond-BoldItalic-tosf-sc-ly1--base.tfm \
tex-EBGaramond-BoldItalic-tosf-sc-ly1.tfm \
tex-EBGaramond-BoldItalic-tosf-sc-ly1.vf \
tex-EBGaramond-BoldItalic-tosf-sc-ot1--base.tfm \
tex-EBGaramond-BoldItalic-tosf-sc-ot1.tfm \
tex-EBGaramond-BoldItalic-tosf-sc-ot1.vf \
tex-EBGaramond-BoldItalic-tosf-sc-t1--base.tfm \
tex-EBGaramond-BoldItalic-tosf-sc-t1.tfm \
tex-EBGaramond-BoldItalic-tosf-sc-t1.vf \
tex-EBGaramond-BoldItalic-tosf-swash-lgr.tfm \
tex-EBGaramond-BoldItalic-tosf-swash-ly1.tfm \
tex-EBGaramond-BoldItalic-tosf-swash-ot1.tfm \
tex-EBGaramond-BoldItalic-tosf-swash-t1--base.tfm \
tex-EBGaramond-BoldItalic-tosf-swash-t1.tfm \
tex-EBGaramond-BoldItalic-tosf-swash-t1.vf \
tex-EBGaramond-BoldItalic-tosf-t1--base.tfm \
tex-EBGaramond-BoldItalic-tosf-t1.tfm \
tex-EBGaramond-BoldItalic-tosf-t1.vf \
tex-EBGaramond-BoldItalic-tosf-ts1--base.tfm \
tex-EBGaramond-BoldItalic-tosf-ts1.tfm \
tex-EBGaramond-BoldItalic-tosf-ts1.vf \
tex-EBGaramond-ExtraBold-inf-lgr.tfm \
tex-EBGaramond-ExtraBold-inf-ly1.tfm \
tex-EBGaramond-ExtraBold-inf-ot1.tfm \
tex-EBGaramond-ExtraBold-inf-t1--base.tfm \
tex-EBGaramond-ExtraBold-inf-t1.tfm \
tex-EBGaramond-ExtraBold-inf-t1.vf \
tex-EBGaramond-ExtraBold-lf-lgr.tfm \
tex-EBGaramond-ExtraBold-lf-ly1.tfm \
tex-EBGaramond-ExtraBold-lf-ot1.tfm \
tex-EBGaramond-ExtraBold-lf-sc-lgr.tfm \
tex-EBGaramond-ExtraBold-lf-sc-ly1--base.tfm \
tex-EBGaramond-ExtraBold-lf-sc-ly1.tfm \
tex-EBGaramond-ExtraBold-lf-sc-ly1.vf \
tex-EBGaramond-ExtraBold-lf-sc-ot1--base.tfm \
tex-EBGaramond-ExtraBold-lf-sc-ot1.tfm \
tex-EBGaramond-ExtraBold-lf-sc-ot1.vf \
tex-EBGaramond-ExtraBold-lf-sc-t1--base.tfm \
tex-EBGaramond-ExtraBold-lf-sc-t1.tfm \
tex-EBGaramond-ExtraBold-lf-sc-t1.vf \
tex-EBGaramond-ExtraBold-lf-swash-lgr.tfm \
tex-EBGaramond-ExtraBold-lf-swash-ly1.tfm \
tex-EBGaramond-ExtraBold-lf-swash-ot1.tfm \
tex-EBGaramond-ExtraBold-lf-swash-t1--base.tfm \
tex-EBGaramond-ExtraBold-lf-swash-t1.tfm \
tex-EBGaramond-ExtraBold-lf-swash-t1.vf \
tex-EBGaramond-ExtraBold-lf-t1--base.tfm \
tex-EBGaramond-ExtraBold-lf-t1.tfm \
tex-EBGaramond-ExtraBold-lf-t1.vf \
tex-EBGaramond-ExtraBold-lf-ts1--base.tfm \
tex-EBGaramond-ExtraBold-lf-ts1.tfm \
tex-EBGaramond-ExtraBold-lf-ts1.vf \
tex-EBGaramond-ExtraBold-osf-lgr.tfm \
tex-EBGaramond-ExtraBold-osf-ly1.tfm \
tex-EBGaramond-ExtraBold-osf-ot1.tfm \
tex-EBGaramond-ExtraBold-osf-sc-lgr.tfm \
tex-EBGaramond-ExtraBold-osf-sc-ly1--base.tfm \
tex-EBGaramond-ExtraBold-osf-sc-ly1.tfm \
tex-EBGaramond-ExtraBold-osf-sc-ly1.vf \
tex-EBGaramond-ExtraBold-osf-sc-ot1--base.tfm \
tex-EBGaramond-ExtraBold-osf-sc-ot1.tfm \
tex-EBGaramond-ExtraBold-osf-sc-ot1.vf \
tex-EBGaramond-ExtraBold-osf-sc-t1--base.tfm \
tex-EBGaramond-ExtraBold-osf-sc-t1.tfm \
tex-EBGaramond-ExtraBold-osf-sc-t1.vf \
tex-EBGaramond-ExtraBold-osf-swash-lgr.tfm \
tex-EBGaramond-ExtraBold-osf-swash-ly1.tfm \
tex-EBGaramond-ExtraBold-osf-swash-ot1.tfm \
tex-EBGaramond-ExtraBold-osf-swash-t1--base.tfm \
tex-EBGaramond-ExtraBold-osf-swash-t1.tfm \
tex-EBGaramond-ExtraBold-osf-swash-t1.vf \
tex-EBGaramond-ExtraBold-osf-t1--base.tfm \
tex-EBGaramond-ExtraBold-osf-t1.tfm \
tex-EBGaramond-ExtraBold-osf-t1.vf \
tex-EBGaramond-ExtraBold-osf-ts1--base.tfm \
tex-EBGaramond-ExtraBold-osf-ts1.tfm \
tex-EBGaramond-ExtraBold-osf-ts1.vf \
tex-EBGaramond-ExtraBold-sup-lgr.tfm \
tex-EBGaramond-ExtraBold-sup-ly1.tfm \
tex-EBGaramond-ExtraBold-sup-ot1.tfm \
tex-EBGaramond-ExtraBold-sup-t1--base.tfm \
tex-EBGaramond-ExtraBold-sup-t1.tfm \
tex-EBGaramond-ExtraBold-sup-t1.vf \
tex-EBGaramond-ExtraBold-tlf-lgr.tfm \
tex-EBGaramond-ExtraBold-tlf-ly1.tfm \
tex-EBGaramond-ExtraBold-tlf-ot1.tfm \
tex-EBGaramond-ExtraBold-tlf-sc-lgr.tfm \
tex-EBGaramond-ExtraBold-tlf-sc-ly1--base.tfm \
tex-EBGaramond-ExtraBold-tlf-sc-ly1.tfm \
tex-EBGaramond-ExtraBold-tlf-sc-ly1.vf \
tex-EBGaramond-ExtraBold-tlf-sc-ot1--base.tfm \
tex-EBGaramond-ExtraBold-tlf-sc-ot1.tfm \
tex-EBGaramond-ExtraBold-tlf-sc-ot1.vf \
tex-EBGaramond-ExtraBold-tlf-sc-t1--base.tfm \
tex-EBGaramond-ExtraBold-tlf-sc-t1.tfm \
tex-EBGaramond-ExtraBold-tlf-sc-t1.vf \
tex-EBGaramond-ExtraBold-tlf-swash-lgr.tfm \
tex-EBGaramond-ExtraBold-tlf-swash-ly1.tfm \
tex-EBGaramond-ExtraBold-tlf-swash-ot1.tfm \
tex-EBGaramond-ExtraBold-tlf-swash-t1--base.tfm \
tex-EBGaramond-ExtraBold-tlf-swash-t1.tfm \
tex-EBGaramond-ExtraBold-tlf-swash-t1.vf \
tex-EBGaramond-ExtraBold-tlf-t1--base.tfm \
tex-EBGaramond-ExtraBold-tlf-t1.tfm \
tex-EBGaramond-ExtraBold-tlf-t1.vf \
tex-EBGaramond-ExtraBold-tlf-ts1--base.tfm \
tex-EBGaramond-ExtraBold-tlf-ts1.tfm \
tex-EBGaramond-ExtraBold-tlf-ts1.vf \
tex-EBGaramond-ExtraBold-tosf-lgr.tfm \
tex-EBGaramond-ExtraBold-tosf-ly1.tfm \
tex-EBGaramond-ExtraBold-tosf-ot1.tfm \
tex-EBGaramond-ExtraBold-tosf-sc-lgr.tfm \
tex-EBGaramond-ExtraBold-tosf-sc-ly1--base.tfm \
tex-EBGaramond-ExtraBold-tosf-sc-ly1.tfm \
tex-EBGaramond-ExtraBold-tosf-sc-ly1.vf \
tex-EBGaramond-ExtraBold-tosf-sc-ot1--base.tfm \
tex-EBGaramond-ExtraBold-tosf-sc-ot1.tfm \
tex-EBGaramond-ExtraBold-tosf-sc-ot1.vf \
tex-EBGaramond-ExtraBold-tosf-sc-t1--base.tfm \
tex-EBGaramond-ExtraBold-tosf-sc-t1.tfm \
tex-EBGaramond-ExtraBold-tosf-sc-t1.vf \
tex-EBGaramond-ExtraBold-tosf-swash-lgr.tfm \
tex-EBGaramond-ExtraBold-tosf-swash-ly1.tfm \
tex-EBGaramond-ExtraBold-tosf-swash-ot1.tfm \
tex-EBGaramond-ExtraBold-tosf-swash-t1--base.tfm \
tex-EBGaramond-ExtraBold-tosf-swash-t1.tfm \
tex-EBGaramond-ExtraBold-tosf-swash-t1.vf \
tex-EBGaramond-ExtraBold-tosf-t1--base.tfm \
tex-EBGaramond-ExtraBold-tosf-t1.tfm \
tex-EBGaramond-ExtraBold-tosf-t1.vf \
tex-EBGaramond-ExtraBold-tosf-ts1--base.tfm \
tex-EBGaramond-ExtraBold-tosf-ts1.tfm \
tex-EBGaramond-ExtraBold-tosf-ts1.vf \
tex-EBGaramond-ExtraBoldItalic-inf-lgr.tfm \
tex-EBGaramond-ExtraBoldItalic-inf-ly1.tfm \
tex-EBGaramond-ExtraBoldItalic-inf-ot1.tfm \
tex-EBGaramond-ExtraBoldItalic-inf-t1--base.tfm \
tex-EBGaramond-ExtraBoldItalic-inf-t1.tfm \
tex-EBGaramond-ExtraBoldItalic-inf-t1.vf \
tex-EBGaramond-ExtraBoldItalic-lf-lgr.tfm \
tex-EBGaramond-ExtraBoldItalic-lf-ly1.tfm \
tex-EBGaramond-ExtraBoldItalic-lf-ot1.tfm \
tex-EBGaramond-ExtraBoldItalic-lf-sc-lgr.tfm \
tex-EBGaramond-ExtraBoldItalic-lf-sc-ly1--base.tfm \
tex-EBGaramond-ExtraBoldItalic-lf-sc-ly1.tfm \
tex-EBGaramond-ExtraBoldItalic-lf-sc-ly1.vf \
tex-EBGaramond-ExtraBoldItalic-lf-sc-ot1--base.tfm \
tex-EBGaramond-ExtraBoldItalic-lf-sc-ot1.tfm \
tex-EBGaramond-ExtraBoldItalic-lf-sc-ot1.vf \
tex-EBGaramond-ExtraBoldItalic-lf-sc-t1--base.tfm \
tex-EBGaramond-ExtraBoldItalic-lf-sc-t1.tfm \
tex-EBGaramond-ExtraBoldItalic-lf-sc-t1.vf \
tex-EBGaramond-ExtraBoldItalic-lf-swash-lgr.tfm \
tex-EBGaramond-ExtraBoldItalic-lf-swash-ly1.tfm \
tex-EBGaramond-ExtraBoldItalic-lf-swash-ot1.tfm \
tex-EBGaramond-ExtraBoldItalic-lf-swash-t1--base.tfm \
tex-EBGaramond-ExtraBoldItalic-lf-swash-t1.tfm \
tex-EBGaramond-ExtraBoldItalic-lf-swash-t1.vf \
tex-EBGaramond-ExtraBoldItalic-lf-t1--base.tfm \
tex-EBGaramond-ExtraBoldItalic-lf-t1.tfm \
tex-EBGaramond-ExtraBoldItalic-lf-t1.vf \
tex-EBGaramond-ExtraBoldItalic-lf-ts1--base.tfm \
tex-EBGaramond-ExtraBoldItalic-lf-ts1.tfm \
tex-EBGaramond-ExtraBoldItalic-lf-ts1.vf \
tex-EBGaramond-ExtraBoldItalic-osf-lgr.tfm \
tex-EBGaramond-ExtraBoldItalic-osf-ly1.tfm \
tex-EBGaramond-ExtraBoldItalic-osf-ot1.tfm \
tex-EBGaramond-ExtraBoldItalic-osf-sc-lgr.tfm \
tex-EBGaramond-ExtraBoldItalic-osf-sc-ly1--base.tfm \
tex-EBGaramond-ExtraBoldItalic-osf-sc-ly1.tfm \
tex-EBGaramond-ExtraBoldItalic-osf-sc-ly1.vf \
tex-EBGaramond-ExtraBoldItalic-osf-sc-ot1--base.tfm \
tex-EBGaramond-ExtraBoldItalic-osf-sc-ot1.tfm \
tex-EBGaramond-ExtraBoldItalic-osf-sc-ot1.vf \
tex-EBGaramond-ExtraBoldItalic-osf-sc-t1--base.tfm \
tex-EBGaramond-ExtraBoldItalic-osf-sc-t1.tfm \
tex-EBGaramond-ExtraBoldItalic-osf-sc-t1.vf \
tex-EBGaramond-ExtraBoldItalic-osf-swash-lgr.tfm \
tex-EBGaramond-ExtraBoldItalic-osf-swash-ly1.tfm \
tex-EBGaramond-ExtraBoldItalic-osf-swash-ot1.tfm \
tex-EBGaramond-ExtraBoldItalic-osf-swash-t1--base.tfm \
tex-EBGaramond-ExtraBoldItalic-osf-swash-t1.tfm \
tex-EBGaramond-ExtraBoldItalic-osf-swash-t1.vf \
tex-EBGaramond-ExtraBoldItalic-osf-t1--base.tfm \
tex-EBGaramond-ExtraBoldItalic-osf-t1.tfm \
tex-EBGaramond-ExtraBoldItalic-osf-t1.vf \
tex-EBGaramond-ExtraBoldItalic-osf-ts1--base.tfm \
tex-EBGaramond-ExtraBoldItalic-osf-ts1.tfm \
tex-EBGaramond-ExtraBoldItalic-osf-ts1.vf \
tex-EBGaramond-ExtraBoldItalic-sup-lgr.tfm \
tex-EBGaramond-ExtraBoldItalic-sup-ly1.tfm \
tex-EBGaramond-ExtraBoldItalic-sup-ot1.tfm \
tex-EBGaramond-ExtraBoldItalic-sup-t1--base.tfm \
tex-EBGaramond-ExtraBoldItalic-sup-t1.tfm \
tex-EBGaramond-ExtraBoldItalic-sup-t1.vf \
tex-EBGaramond-ExtraBoldItalic-tlf-lgr.tfm \
tex-EBGaramond-ExtraBoldItalic-tlf-ly1.tfm \
tex-EBGaramond-ExtraBoldItalic-tlf-ot1.tfm \
tex-EBGaramond-ExtraBoldItalic-tlf-sc-lgr.tfm \
tex-EBGaramond-ExtraBoldItalic-tlf-sc-ly1--base.tfm \
tex-EBGaramond-ExtraBoldItalic-tlf-sc-ly1.tfm \
tex-EBGaramond-ExtraBoldItalic-tlf-sc-ly1.vf \
tex-EBGaramond-ExtraBoldItalic-tlf-sc-ot1--base.tfm \
tex-EBGaramond-ExtraBoldItalic-tlf-sc-ot1.tfm \
tex-EBGaramond-ExtraBoldItalic-tlf-sc-ot1.vf \
tex-EBGaramond-ExtraBoldItalic-tlf-sc-t1--base.tfm \
tex-EBGaramond-ExtraBoldItalic-tlf-sc-t1.tfm \
tex-EBGaramond-ExtraBoldItalic-tlf-sc-t1.vf \
tex-EBGaramond-ExtraBoldItalic-tlf-swash-lgr.tfm \
tex-EBGaramond-ExtraBoldItalic-tlf-swash-ly1.tfm \
tex-EBGaramond-ExtraBoldItalic-tlf-swash-ot1.tfm \
tex-EBGaramond-ExtraBoldItalic-tlf-swash-t1--base.tfm \
tex-EBGaramond-ExtraBoldItalic-tlf-swash-t1.tfm \
tex-EBGaramond-ExtraBoldItalic-tlf-swash-t1.vf \
tex-EBGaramond-ExtraBoldItalic-tlf-t1--base.tfm \
tex-EBGaramond-ExtraBoldItalic-tlf-t1.tfm \
tex-EBGaramond-ExtraBoldItalic-tlf-t1.vf \
tex-EBGaramond-ExtraBoldItalic-tlf-ts1--base.tfm \
tex-EBGaramond-ExtraBoldItalic-tlf-ts1.tfm \
tex-EBGaramond-ExtraBoldItalic-tlf-ts1.vf \
tex-EBGaramond-ExtraBoldItalic-tosf-lgr.tfm \
tex-EBGaramond-ExtraBoldItalic-tosf-ly1.tfm \
tex-EBGaramond-ExtraBoldItalic-tosf-ot1.tfm \
tex-EBGaramond-ExtraBoldItalic-tosf-sc-lgr.tfm \
tex-EBGaramond-ExtraBoldItalic-tosf-sc-ly1--base.tfm \
tex-EBGaramond-ExtraBoldItalic-tosf-sc-ly1.tfm \
tex-EBGaramond-ExtraBoldItalic-tosf-sc-ly1.vf \
tex-EBGaramond-ExtraBoldItalic-tosf-sc-ot1--base.tfm \
tex-EBGaramond-ExtraBoldItalic-tosf-sc-ot1.tfm \
tex-EBGaramond-ExtraBoldItalic-tosf-sc-ot1.vf \
tex-EBGaramond-ExtraBoldItalic-tosf-sc-t1--base.tfm \
tex-EBGaramond-ExtraBoldItalic-tosf-sc-t1.tfm \
tex-EBGaramond-ExtraBoldItalic-tosf-sc-t1.vf \
tex-EBGaramond-ExtraBoldItalic-tosf-swash-lgr.tfm \
tex-EBGaramond-ExtraBoldItalic-tosf-swash-ly1.tfm \
tex-EBGaramond-ExtraBoldItalic-tosf-swash-ot1.tfm \
tex-EBGaramond-ExtraBoldItalic-tosf-swash-t1--base.tfm \
tex-EBGaramond-ExtraBoldItalic-tosf-swash-t1.tfm \
tex-EBGaramond-ExtraBoldItalic-tosf-swash-t1.vf \
tex-EBGaramond-ExtraBoldItalic-tosf-t1--base.tfm \
tex-EBGaramond-ExtraBoldItalic-tosf-t1.tfm \
tex-EBGaramond-ExtraBoldItalic-tosf-t1.vf \
tex-EBGaramond-ExtraBoldItalic-tosf-ts1--base.tfm \
tex-EBGaramond-ExtraBoldItalic-tosf-ts1.tfm \
tex-EBGaramond-ExtraBoldItalic-tosf-ts1.vf \
tex-EBGaramond-Italic-inf-lgr.tfm \
tex-EBGaramond-Italic-inf-ly1.tfm \
tex-EBGaramond-Italic-inf-ot1.tfm \
tex-EBGaramond-Italic-inf-t1--base.tfm \
tex-EBGaramond-Italic-inf-t1.tfm \
tex-EBGaramond-Italic-inf-t1.vf \
tex-EBGaramond-Italic-lf-lgr.tfm \
tex-EBGaramond-Italic-lf-ly1.tfm \
tex-EBGaramond-Italic-lf-ot1.tfm \
tex-EBGaramond-Italic-lf-sc-lgr.tfm \
tex-EBGaramond-Italic-lf-sc-ly1--base.tfm \
tex-EBGaramond-Italic-lf-sc-ly1.tfm \
tex-EBGaramond-Italic-lf-sc-ly1.vf \
tex-EBGaramond-Italic-lf-sc-ot1--base.tfm \
tex-EBGaramond-Italic-lf-sc-ot1.tfm \
tex-EBGaramond-Italic-lf-sc-ot1.vf \
tex-EBGaramond-Italic-lf-sc-t1--base.tfm \
tex-EBGaramond-Italic-lf-sc-t1.tfm \
tex-EBGaramond-Italic-lf-sc-t1.vf \
tex-EBGaramond-Italic-lf-swash-lgr.tfm \
tex-EBGaramond-Italic-lf-swash-ly1.tfm \
tex-EBGaramond-Italic-lf-swash-ot1.tfm \
tex-EBGaramond-Italic-lf-swash-t1--base.tfm \
tex-EBGaramond-Italic-lf-swash-t1.tfm \
tex-EBGaramond-Italic-lf-swash-t1.vf \
tex-EBGaramond-Italic-lf-t1--base.tfm \
tex-EBGaramond-Italic-lf-t1.tfm \
tex-EBGaramond-Italic-lf-t1.vf \
tex-EBGaramond-Italic-lf-ts1--base.tfm \
tex-EBGaramond-Italic-lf-ts1.tfm \
tex-EBGaramond-Italic-lf-ts1.vf \
tex-EBGaramond-Italic-osf-lgr.tfm \
tex-EBGaramond-Italic-osf-ly1.tfm \
tex-EBGaramond-Italic-osf-ot1.tfm \
tex-EBGaramond-Italic-osf-sc-lgr.tfm \
tex-EBGaramond-Italic-osf-sc-ly1--base.tfm \
tex-EBGaramond-Italic-osf-sc-ly1.tfm \
tex-EBGaramond-Italic-osf-sc-ly1.vf \
tex-EBGaramond-Italic-osf-sc-ot1--base.tfm \
tex-EBGaramond-Italic-osf-sc-ot1.tfm \
tex-EBGaramond-Italic-osf-sc-ot1.vf \
tex-EBGaramond-Italic-osf-sc-t1--base.tfm \
tex-EBGaramond-Italic-osf-sc-t1.tfm \
tex-EBGaramond-Italic-osf-sc-t1.vf \
tex-EBGaramond-Italic-osf-swash-lgr.tfm \
tex-EBGaramond-Italic-osf-swash-ly1.tfm \
tex-EBGaramond-Italic-osf-swash-ot1.tfm \
tex-EBGaramond-Italic-osf-swash-t1--base.tfm \
tex-EBGaramond-Italic-osf-swash-t1.tfm \
tex-EBGaramond-Italic-osf-swash-t1.vf \
tex-EBGaramond-Italic-osf-t1--base.tfm \
tex-EBGaramond-Italic-osf-t1.tfm \
tex-EBGaramond-Italic-osf-t1.vf \
tex-EBGaramond-Italic-osf-ts1--base.tfm \
tex-EBGaramond-Italic-osf-ts1.tfm \
tex-EBGaramond-Italic-osf-ts1.vf \
tex-EBGaramond-Italic-sup-lgr.tfm \
tex-EBGaramond-Italic-sup-ly1.tfm \
tex-EBGaramond-Italic-sup-ot1.tfm \
tex-EBGaramond-Italic-sup-t1--base.tfm \
tex-EBGaramond-Italic-sup-t1.tfm \
tex-EBGaramond-Italic-sup-t1.vf \
tex-EBGaramond-Italic-tlf-lgr.tfm \
tex-EBGaramond-Italic-tlf-ly1.tfm \
tex-EBGaramond-Italic-tlf-ot1.tfm \
tex-EBGaramond-Italic-tlf-sc-lgr.tfm \
tex-EBGaramond-Italic-tlf-sc-ly1--base.tfm \
tex-EBGaramond-Italic-tlf-sc-ly1.tfm \
tex-EBGaramond-Italic-tlf-sc-ly1.vf \
tex-EBGaramond-Italic-tlf-sc-ot1--base.tfm \
tex-EBGaramond-Italic-tlf-sc-ot1.tfm \
tex-EBGaramond-Italic-tlf-sc-ot1.vf \
tex-EBGaramond-Italic-tlf-sc-t1--base.tfm \
tex-EBGaramond-Italic-tlf-sc-t1.tfm \
tex-EBGaramond-Italic-tlf-sc-t1.vf \
tex-EBGaramond-Italic-tlf-swash-lgr.tfm \
tex-EBGaramond-Italic-tlf-swash-ly1.tfm \
tex-EBGaramond-Italic-tlf-swash-ot1.tfm \
tex-EBGaramond-Italic-tlf-swash-t1--base.tfm \
tex-EBGaramond-Italic-tlf-swash-t1.tfm \
tex-EBGaramond-Italic-tlf-swash-t1.vf \
tex-EBGaramond-Italic-tlf-t1--base.tfm \
tex-EBGaramond-Italic-tlf-t1.tfm \
tex-EBGaramond-Italic-tlf-t1.vf \
tex-EBGaramond-Italic-tlf-ts1--base.tfm \
tex-EBGaramond-Italic-tlf-ts1.tfm \
tex-EBGaramond-Italic-tlf-ts1.vf \
tex-EBGaramond-Italic-tosf-lgr.tfm \
tex-EBGaramond-Italic-tosf-ly1.tfm \
tex-EBGaramond-Italic-tosf-ot1.tfm \
tex-EBGaramond-Italic-tosf-sc-lgr.tfm \
tex-EBGaramond-Italic-tosf-sc-ly1--base.tfm \
tex-EBGaramond-Italic-tosf-sc-ly1.tfm \
tex-EBGaramond-Italic-tosf-sc-ly1.vf \
tex-EBGaramond-Italic-tosf-sc-ot1--base.tfm \
tex-EBGaramond-Italic-tosf-sc-ot1.tfm \
tex-EBGaramond-Italic-tosf-sc-ot1.vf \
tex-EBGaramond-Italic-tosf-sc-t1--base.tfm \
tex-EBGaramond-Italic-tosf-sc-t1.tfm \
tex-EBGaramond-Italic-tosf-sc-t1.vf \
tex-EBGaramond-Italic-tosf-swash-lgr.tfm \
tex-EBGaramond-Italic-tosf-swash-ly1.tfm \
tex-EBGaramond-Italic-tosf-swash-ot1.tfm \
tex-EBGaramond-Italic-tosf-swash-t1--base.tfm \
tex-EBGaramond-Italic-tosf-swash-t1.tfm \
tex-EBGaramond-Italic-tosf-swash-t1.vf \
tex-EBGaramond-Italic-tosf-t1--base.tfm \
tex-EBGaramond-Italic-tosf-t1.tfm \
tex-EBGaramond-Italic-tosf-t1.vf \
tex-EBGaramond-Italic-tosf-ts1--base.tfm \
tex-EBGaramond-Italic-tosf-ts1.tfm \
tex-EBGaramond-Italic-tosf-ts1.vf \
tex-EBGaramond-Medium-inf-lgr.tfm \
tex-EBGaramond-Medium-inf-ly1.tfm \
tex-EBGaramond-Medium-inf-ot1.tfm \
tex-EBGaramond-Medium-inf-t1--base.tfm \
tex-EBGaramond-Medium-inf-t1.tfm \
tex-EBGaramond-Medium-inf-t1.vf \
tex-EBGaramond-Medium-lf-lgr.tfm \
tex-EBGaramond-Medium-lf-ly1.tfm \
tex-EBGaramond-Medium-lf-ot1.tfm \
tex-EBGaramond-Medium-lf-sc-lgr.tfm \
tex-EBGaramond-Medium-lf-sc-ly1--base.tfm \
tex-EBGaramond-Medium-lf-sc-ly1.tfm \
tex-EBGaramond-Medium-lf-sc-ly1.vf \
tex-EBGaramond-Medium-lf-sc-ot1--base.tfm \
tex-EBGaramond-Medium-lf-sc-ot1.tfm \
tex-EBGaramond-Medium-lf-sc-ot1.vf \
tex-EBGaramond-Medium-lf-sc-t1--base.tfm \
tex-EBGaramond-Medium-lf-sc-t1.tfm \
tex-EBGaramond-Medium-lf-sc-t1.vf \
tex-EBGaramond-Medium-lf-swash-lgr.tfm \
tex-EBGaramond-Medium-lf-swash-ly1.tfm \
tex-EBGaramond-Medium-lf-swash-ot1.tfm \
tex-EBGaramond-Medium-lf-swash-t1--base.tfm \
tex-EBGaramond-Medium-lf-swash-t1.tfm \
tex-EBGaramond-Medium-lf-swash-t1.vf \
tex-EBGaramond-Medium-lf-t1--base.tfm \
tex-EBGaramond-Medium-lf-t1.tfm \
tex-EBGaramond-Medium-lf-t1.vf \
tex-EBGaramond-Medium-lf-ts1--base.tfm \
tex-EBGaramond-Medium-lf-ts1.tfm \
tex-EBGaramond-Medium-lf-ts1.vf \
tex-EBGaramond-Medium-osf-lgr.tfm \
tex-EBGaramond-Medium-osf-ly1.tfm \
tex-EBGaramond-Medium-osf-ot1.tfm \
tex-EBGaramond-Medium-osf-sc-lgr.tfm \
tex-EBGaramond-Medium-osf-sc-ly1--base.tfm \
tex-EBGaramond-Medium-osf-sc-ly1.tfm \
tex-EBGaramond-Medium-osf-sc-ly1.vf \
tex-EBGaramond-Medium-osf-sc-ot1--base.tfm \
tex-EBGaramond-Medium-osf-sc-ot1.tfm \
tex-EBGaramond-Medium-osf-sc-ot1.vf \
tex-EBGaramond-Medium-osf-sc-t1--base.tfm \
tex-EBGaramond-Medium-osf-sc-t1.tfm \
tex-EBGaramond-Medium-osf-sc-t1.vf \
tex-EBGaramond-Medium-osf-swash-lgr.tfm \
tex-EBGaramond-Medium-osf-swash-ly1.tfm \
tex-EBGaramond-Medium-osf-swash-ot1.tfm \
tex-EBGaramond-Medium-osf-swash-t1--base.tfm \
tex-EBGaramond-Medium-osf-swash-t1.tfm \
tex-EBGaramond-Medium-osf-swash-t1.vf \
tex-EBGaramond-Medium-osf-t1--base.tfm \
tex-EBGaramond-Medium-osf-t1.tfm \
tex-EBGaramond-Medium-osf-t1.vf \
tex-EBGaramond-Medium-osf-ts1--base.tfm \
tex-EBGaramond-Medium-osf-ts1.tfm \
tex-EBGaramond-Medium-osf-ts1.vf \
tex-EBGaramond-Medium-sup-lgr.tfm \
tex-EBGaramond-Medium-sup-ly1.tfm \
tex-EBGaramond-Medium-sup-ot1.tfm \
tex-EBGaramond-Medium-sup-t1--base.tfm \
tex-EBGaramond-Medium-sup-t1.tfm \
tex-EBGaramond-Medium-sup-t1.vf \
tex-EBGaramond-Medium-tlf-lgr.tfm \
tex-EBGaramond-Medium-tlf-ly1.tfm \
tex-EBGaramond-Medium-tlf-ot1.tfm \
tex-EBGaramond-Medium-tlf-sc-lgr.tfm \
tex-EBGaramond-Medium-tlf-sc-ly1--base.tfm \
tex-EBGaramond-Medium-tlf-sc-ly1.tfm \
tex-EBGaramond-Medium-tlf-sc-ly1.vf \
tex-EBGaramond-Medium-tlf-sc-ot1--base.tfm \
tex-EBGaramond-Medium-tlf-sc-ot1.tfm \
tex-EBGaramond-Medium-tlf-sc-ot1.vf \
tex-EBGaramond-Medium-tlf-sc-t1--base.tfm \
tex-EBGaramond-Medium-tlf-sc-t1.tfm \
tex-EBGaramond-Medium-tlf-sc-t1.vf \
tex-EBGaramond-Medium-tlf-swash-lgr.tfm \
tex-EBGaramond-Medium-tlf-swash-ly1.tfm \
tex-EBGaramond-Medium-tlf-swash-ot1.tfm \
tex-EBGaramond-Medium-tlf-swash-t1--base.tfm \
tex-EBGaramond-Medium-tlf-swash-t1.tfm \
tex-EBGaramond-Medium-tlf-swash-t1.vf \
tex-EBGaramond-Medium-tlf-t1--base.tfm \
tex-EBGaramond-Medium-tlf-t1.tfm \
tex-EBGaramond-Medium-tlf-t1.vf \
tex-EBGaramond-Medium-tlf-ts1--base.tfm \
tex-EBGaramond-Medium-tlf-ts1.tfm \
tex-EBGaramond-Medium-tlf-ts1.vf \
tex-EBGaramond-Medium-tosf-lgr.tfm \
tex-EBGaramond-Medium-tosf-ly1.tfm \
tex-EBGaramond-Medium-tosf-ot1.tfm \
tex-EBGaramond-Medium-tosf-sc-lgr.tfm \
tex-EBGaramond-Medium-tosf-sc-ly1--base.tfm \
tex-EBGaramond-Medium-tosf-sc-ly1.tfm \
tex-EBGaramond-Medium-tosf-sc-ly1.vf \
tex-EBGaramond-Medium-tosf-sc-ot1--base.tfm \
tex-EBGaramond-Medium-tosf-sc-ot1.tfm \
tex-EBGaramond-Medium-tosf-sc-ot1.vf \
tex-EBGaramond-Medium-tosf-sc-t1--base.tfm \
tex-EBGaramond-Medium-tosf-sc-t1.tfm \
tex-EBGaramond-Medium-tosf-sc-t1.vf \
tex-EBGaramond-Medium-tosf-swash-lgr.tfm \
tex-EBGaramond-Medium-tosf-swash-ly1.tfm \
tex-EBGaramond-Medium-tosf-swash-ot1.tfm \
tex-EBGaramond-Medium-tosf-swash-t1--base.tfm \
tex-EBGaramond-Medium-tosf-swash-t1.tfm \
tex-EBGaramond-Medium-tosf-swash-t1.vf \
tex-EBGaramond-Medium-tosf-t1--base.tfm \
tex-EBGaramond-Medium-tosf-t1.tfm \
tex-EBGaramond-Medium-tosf-t1.vf \
tex-EBGaramond-Medium-tosf-ts1--base.tfm \
tex-EBGaramond-Medium-tosf-ts1.tfm \
tex-EBGaramond-Medium-tosf-ts1.vf \
tex-EBGaramond-MediumItalic-inf-lgr.tfm \
tex-EBGaramond-MediumItalic-inf-ly1.tfm \
tex-EBGaramond-MediumItalic-inf-ot1.tfm \
tex-EBGaramond-MediumItalic-inf-t1--base.tfm \
tex-EBGaramond-MediumItalic-inf-t1.tfm \
tex-EBGaramond-MediumItalic-inf-t1.vf \
tex-EBGaramond-MediumItalic-lf-lgr.tfm \
tex-EBGaramond-MediumItalic-lf-ly1.tfm \
tex-EBGaramond-MediumItalic-lf-ot1.tfm \
tex-EBGaramond-MediumItalic-lf-sc-lgr.tfm \
tex-EBGaramond-MediumItalic-lf-sc-ly1--base.tfm \
tex-EBGaramond-MediumItalic-lf-sc-ly1.tfm \
tex-EBGaramond-MediumItalic-lf-sc-ly1.vf \
tex-EBGaramond-MediumItalic-lf-sc-ot1--base.tfm \
tex-EBGaramond-MediumItalic-lf-sc-ot1.tfm \
tex-EBGaramond-MediumItalic-lf-sc-ot1.vf \
tex-EBGaramond-MediumItalic-lf-sc-t1--base.tfm \
tex-EBGaramond-MediumItalic-lf-sc-t1.tfm \
tex-EBGaramond-MediumItalic-lf-sc-t1.vf \
tex-EBGaramond-MediumItalic-lf-swash-lgr.tfm \
tex-EBGaramond-MediumItalic-lf-swash-ly1.tfm \
tex-EBGaramond-MediumItalic-lf-swash-ot1.tfm \
tex-EBGaramond-MediumItalic-lf-swash-t1--base.tfm \
tex-EBGaramond-MediumItalic-lf-swash-t1.tfm \
tex-EBGaramond-MediumItalic-lf-swash-t1.vf \
tex-EBGaramond-MediumItalic-lf-t1--base.tfm \
tex-EBGaramond-MediumItalic-lf-t1.tfm \
tex-EBGaramond-MediumItalic-lf-t1.vf \
tex-EBGaramond-MediumItalic-lf-ts1--base.tfm \
tex-EBGaramond-MediumItalic-lf-ts1.tfm \
tex-EBGaramond-MediumItalic-lf-ts1.vf \
tex-EBGaramond-MediumItalic-osf-lgr.tfm \
tex-EBGaramond-MediumItalic-osf-ly1.tfm \
tex-EBGaramond-MediumItalic-osf-ot1.tfm \
tex-EBGaramond-MediumItalic-osf-sc-lgr.tfm \
tex-EBGaramond-MediumItalic-osf-sc-ly1--base.tfm \
tex-EBGaramond-MediumItalic-osf-sc-ly1.tfm \
tex-EBGaramond-MediumItalic-osf-sc-ly1.vf \
tex-EBGaramond-MediumItalic-osf-sc-ot1--base.tfm \
tex-EBGaramond-MediumItalic-osf-sc-ot1.tfm \
tex-EBGaramond-MediumItalic-osf-sc-ot1.vf \
tex-EBGaramond-MediumItalic-osf-sc-t1--base.tfm \
tex-EBGaramond-MediumItalic-osf-sc-t1.tfm \
tex-EBGaramond-MediumItalic-osf-sc-t1.vf \
tex-EBGaramond-MediumItalic-osf-swash-lgr.tfm \
tex-EBGaramond-MediumItalic-osf-swash-ly1.tfm \
tex-EBGaramond-MediumItalic-osf-swash-ot1.tfm \
tex-EBGaramond-MediumItalic-osf-swash-t1--base.tfm \
tex-EBGaramond-MediumItalic-osf-swash-t1.tfm \
tex-EBGaramond-MediumItalic-osf-swash-t1.vf \
tex-EBGaramond-MediumItalic-osf-t1--base.tfm \
tex-EBGaramond-MediumItalic-osf-t1.tfm \
tex-EBGaramond-MediumItalic-osf-t1.vf \
tex-EBGaramond-MediumItalic-osf-ts1--base.tfm \
tex-EBGaramond-MediumItalic-osf-ts1.tfm \
tex-EBGaramond-MediumItalic-osf-ts1.vf \
tex-EBGaramond-MediumItalic-sup-lgr.tfm \
tex-EBGaramond-MediumItalic-sup-ly1.tfm \
tex-EBGaramond-MediumItalic-sup-ot1.tfm \
tex-EBGaramond-MediumItalic-sup-t1--base.tfm \
tex-EBGaramond-MediumItalic-sup-t1.tfm \
tex-EBGaramond-MediumItalic-sup-t1.vf \
tex-EBGaramond-MediumItalic-tlf-lgr.tfm \
tex-EBGaramond-MediumItalic-tlf-ly1.tfm \
tex-EBGaramond-MediumItalic-tlf-ot1.tfm \
tex-EBGaramond-MediumItalic-tlf-sc-lgr.tfm \
tex-EBGaramond-MediumItalic-tlf-sc-ly1--base.tfm \
tex-EBGaramond-MediumItalic-tlf-sc-ly1.tfm \
tex-EBGaramond-MediumItalic-tlf-sc-ly1.vf \
tex-EBGaramond-MediumItalic-tlf-sc-ot1--base.tfm \
tex-EBGaramond-MediumItalic-tlf-sc-ot1.tfm \
tex-EBGaramond-MediumItalic-tlf-sc-ot1.vf \
tex-EBGaramond-MediumItalic-tlf-sc-t1--base.tfm \
tex-EBGaramond-MediumItalic-tlf-sc-t1.tfm \
tex-EBGaramond-MediumItalic-tlf-sc-t1.vf \
tex-EBGaramond-MediumItalic-tlf-swash-lgr.tfm \
tex-EBGaramond-MediumItalic-tlf-swash-ly1.tfm \
tex-EBGaramond-MediumItalic-tlf-swash-ot1.tfm \
tex-EBGaramond-MediumItalic-tlf-swash-t1--base.tfm \
tex-EBGaramond-MediumItalic-tlf-swash-t1.tfm \
tex-EBGaramond-MediumItalic-tlf-swash-t1.vf \
tex-EBGaramond-MediumItalic-tlf-t1--base.tfm \
tex-EBGaramond-MediumItalic-tlf-t1.tfm \
tex-EBGaramond-MediumItalic-tlf-t1.vf \
tex-EBGaramond-MediumItalic-tlf-ts1--base.tfm \
tex-EBGaramond-MediumItalic-tlf-ts1.tfm \
tex-EBGaramond-MediumItalic-tlf-ts1.vf \
tex-EBGaramond-MediumItalic-tosf-lgr.tfm \
tex-EBGaramond-MediumItalic-tosf-ly1.tfm \
tex-EBGaramond-MediumItalic-tosf-ot1.tfm \
tex-EBGaramond-MediumItalic-tosf-sc-lgr.tfm \
tex-EBGaramond-MediumItalic-tosf-sc-ly1--base.tfm \
tex-EBGaramond-MediumItalic-tosf-sc-ly1.tfm \
tex-EBGaramond-MediumItalic-tosf-sc-ly1.vf \
tex-EBGaramond-MediumItalic-tosf-sc-ot1--base.tfm \
tex-EBGaramond-MediumItalic-tosf-sc-ot1.tfm \
tex-EBGaramond-MediumItalic-tosf-sc-ot1.vf \
tex-EBGaramond-MediumItalic-tosf-sc-t1--base.tfm \
tex-EBGaramond-MediumItalic-tosf-sc-t1.tfm \
tex-EBGaramond-MediumItalic-tosf-sc-t1.vf \
tex-EBGaramond-MediumItalic-tosf-swash-lgr.tfm \
tex-EBGaramond-MediumItalic-tosf-swash-ly1.tfm \
tex-EBGaramond-MediumItalic-tosf-swash-ot1.tfm \
tex-EBGaramond-MediumItalic-tosf-swash-t1--base.tfm \
tex-EBGaramond-MediumItalic-tosf-swash-t1.tfm \
tex-EBGaramond-MediumItalic-tosf-swash-t1.vf \
tex-EBGaramond-MediumItalic-tosf-t1--base.tfm \
tex-EBGaramond-MediumItalic-tosf-t1.tfm \
tex-EBGaramond-MediumItalic-tosf-t1.vf \
tex-EBGaramond-MediumItalic-tosf-ts1--base.tfm \
tex-EBGaramond-MediumItalic-tosf-ts1.tfm \
tex-EBGaramond-MediumItalic-tosf-ts1.vf \
tex-EBGaramond-Regular-inf-lgr.tfm \
tex-EBGaramond-Regular-inf-ly1.tfm \
tex-EBGaramond-Regular-inf-ot1.tfm \
tex-EBGaramond-Regular-inf-t1--base.tfm \
tex-EBGaramond-Regular-inf-t1.tfm \
tex-EBGaramond-Regular-inf-t1.vf \
tex-EBGaramond-Regular-lf-lgr.tfm \
tex-EBGaramond-Regular-lf-ly1.tfm \
tex-EBGaramond-Regular-lf-ot1.tfm \
tex-EBGaramond-Regular-lf-sc-lgr.tfm \
tex-EBGaramond-Regular-lf-sc-ly1--base.tfm \
tex-EBGaramond-Regular-lf-sc-ly1.tfm \
tex-EBGaramond-Regular-lf-sc-ly1.vf \
tex-EBGaramond-Regular-lf-sc-ot1--base.tfm \
tex-EBGaramond-Regular-lf-sc-ot1.tfm \
tex-EBGaramond-Regular-lf-sc-ot1.vf \
tex-EBGaramond-Regular-lf-sc-t1--base.tfm \
tex-EBGaramond-Regular-lf-sc-t1.tfm \
tex-EBGaramond-Regular-lf-sc-t1.vf \
tex-EBGaramond-Regular-lf-swash-lgr.tfm \
tex-EBGaramond-Regular-lf-swash-ly1.tfm \
tex-EBGaramond-Regular-lf-swash-ot1.tfm \
tex-EBGaramond-Regular-lf-swash-t1--base.tfm \
tex-EBGaramond-Regular-lf-swash-t1.tfm \
tex-EBGaramond-Regular-lf-swash-t1.vf \
tex-EBGaramond-Regular-lf-t1--base.tfm \
tex-EBGaramond-Regular-lf-t1.tfm \
tex-EBGaramond-Regular-lf-t1.vf \
tex-EBGaramond-Regular-lf-ts1--base.tfm \
tex-EBGaramond-Regular-lf-ts1.tfm \
tex-EBGaramond-Regular-lf-ts1.vf \
tex-EBGaramond-Regular-osf-lgr.tfm \
tex-EBGaramond-Regular-osf-ly1.tfm \
tex-EBGaramond-Regular-osf-ot1.tfm \
tex-EBGaramond-Regular-osf-sc-lgr.tfm \
tex-EBGaramond-Regular-osf-sc-ly1--base.tfm \
tex-EBGaramond-Regular-osf-sc-ly1.tfm \
tex-EBGaramond-Regular-osf-sc-ly1.vf \
tex-EBGaramond-Regular-osf-sc-ot1--base.tfm \
tex-EBGaramond-Regular-osf-sc-ot1.tfm \
tex-EBGaramond-Regular-osf-sc-ot1.vf \
tex-EBGaramond-Regular-osf-sc-t1--base.tfm \
tex-EBGaramond-Regular-osf-sc-t1.tfm \
tex-EBGaramond-Regular-osf-sc-t1.vf \
tex-EBGaramond-Regular-osf-swash-lgr.tfm \
tex-EBGaramond-Regular-osf-swash-ly1.tfm \
tex-EBGaramond-Regular-osf-swash-ot1.tfm \
tex-EBGaramond-Regular-osf-swash-t1--base.tfm \
tex-EBGaramond-Regular-osf-swash-t1.tfm \
tex-EBGaramond-Regular-osf-swash-t1.vf \
tex-EBGaramond-Regular-osf-t1--base.tfm \
tex-EBGaramond-Regular-osf-t1.tfm \
tex-EBGaramond-Regular-osf-t1.vf \
tex-EBGaramond-Regular-osf-ts1--base.tfm \
tex-EBGaramond-Regular-osf-ts1.tfm \
tex-EBGaramond-Regular-osf-ts1.vf \
tex-EBGaramond-Regular-sup-lgr.tfm \
tex-EBGaramond-Regular-sup-ly1.tfm \
tex-EBGaramond-Regular-sup-ot1.tfm \
tex-EBGaramond-Regular-sup-t1--base.tfm \
tex-EBGaramond-Regular-sup-t1.tfm \
tex-EBGaramond-Regular-sup-t1.vf \
tex-EBGaramond-Regular-tlf-lgr.tfm \
tex-EBGaramond-Regular-tlf-ly1.tfm \
tex-EBGaramond-Regular-tlf-ot1.tfm \
tex-EBGaramond-Regular-tlf-sc-lgr.tfm \
tex-EBGaramond-Regular-tlf-sc-ly1--base.tfm \
tex-EBGaramond-Regular-tlf-sc-ly1.tfm \
tex-EBGaramond-Regular-tlf-sc-ly1.vf \
tex-EBGaramond-Regular-tlf-sc-ot1--base.tfm \
tex-EBGaramond-Regular-tlf-sc-ot1.tfm \
tex-EBGaramond-Regular-tlf-sc-ot1.vf \
tex-EBGaramond-Regular-tlf-sc-t1--base.tfm \
tex-EBGaramond-Regular-tlf-sc-t1.tfm \
tex-EBGaramond-Regular-tlf-sc-t1.vf \
tex-EBGaramond-Regular-tlf-swash-lgr.tfm \
tex-EBGaramond-Regular-tlf-swash-ly1.tfm \
tex-EBGaramond-Regular-tlf-swash-ot1.tfm \
tex-EBGaramond-Regular-tlf-swash-t1--base.tfm \
tex-EBGaramond-Regular-tlf-swash-t1.tfm \
tex-EBGaramond-Regular-tlf-swash-t1.vf \
tex-EBGaramond-Regular-tlf-t1--base.tfm \
tex-EBGaramond-Regular-tlf-t1.tfm \
tex-EBGaramond-Regular-tlf-t1.vf \
tex-EBGaramond-Regular-tlf-ts1--base.tfm \
tex-EBGaramond-Regular-tlf-ts1.tfm \
tex-EBGaramond-Regular-tlf-ts1.vf \
tex-EBGaramond-Regular-tosf-lgr.tfm \
tex-EBGaramond-Regular-tosf-ly1.tfm \
tex-EBGaramond-Regular-tosf-ot1.tfm \
tex-EBGaramond-Regular-tosf-sc-lgr.tfm \
tex-EBGaramond-Regular-tosf-sc-ly1--base.tfm \
tex-EBGaramond-Regular-tosf-sc-ly1.tfm \
tex-EBGaramond-Regular-tosf-sc-ly1.vf \
tex-EBGaramond-Regular-tosf-sc-ot1--base.tfm \
tex-EBGaramond-Regular-tosf-sc-ot1.tfm \
tex-EBGaramond-Regular-tosf-sc-ot1.vf \
tex-EBGaramond-Regular-tosf-sc-t1--base.tfm \
tex-EBGaramond-Regular-tosf-sc-t1.tfm \
tex-EBGaramond-Regular-tosf-sc-t1.vf \
tex-EBGaramond-Regular-tosf-swash-lgr.tfm \
tex-EBGaramond-Regular-tosf-swash-ly1.tfm \
tex-EBGaramond-Regular-tosf-swash-ot1.tfm \
tex-EBGaramond-Regular-tosf-swash-t1--base.tfm \
tex-EBGaramond-Regular-tosf-swash-t1.tfm \
tex-EBGaramond-Regular-tosf-swash-t1.vf \
tex-EBGaramond-Regular-tosf-t1--base.tfm \
tex-EBGaramond-Regular-tosf-t1.tfm \
tex-EBGaramond-Regular-tosf-t1.vf \
tex-EBGaramond-Regular-tosf-ts1--base.tfm \
tex-EBGaramond-Regular-tosf-ts1.tfm \
tex-EBGaramond-Regular-tosf-ts1.vf \
tex-EBGaramond-SemiBold-inf-lgr.tfm \
tex-EBGaramond-SemiBold-inf-ly1.tfm \
tex-EBGaramond-SemiBold-inf-ot1.tfm \
tex-EBGaramond-SemiBold-inf-t1--base.tfm \
tex-EBGaramond-SemiBold-inf-t1.tfm \
tex-EBGaramond-SemiBold-inf-t1.vf \
tex-EBGaramond-SemiBold-lf-lgr.tfm \
tex-EBGaramond-SemiBold-lf-ly1.tfm \
tex-EBGaramond-SemiBold-lf-ot1.tfm \
tex-EBGaramond-SemiBold-lf-sc-lgr.tfm \
tex-EBGaramond-SemiBold-lf-sc-ly1--base.tfm \
tex-EBGaramond-SemiBold-lf-sc-ly1.tfm \
tex-EBGaramond-SemiBold-lf-sc-ly1.vf \
tex-EBGaramond-SemiBold-lf-sc-ot1--base.tfm \
tex-EBGaramond-SemiBold-lf-sc-ot1.tfm \
tex-EBGaramond-SemiBold-lf-sc-ot1.vf \
tex-EBGaramond-SemiBold-lf-sc-t1--base.tfm \
tex-EBGaramond-SemiBold-lf-sc-t1.tfm \
tex-EBGaramond-SemiBold-lf-sc-t1.vf \
tex-EBGaramond-SemiBold-lf-swash-lgr.tfm \
tex-EBGaramond-SemiBold-lf-swash-ly1.tfm \
tex-EBGaramond-SemiBold-lf-swash-ot1.tfm \
tex-EBGaramond-SemiBold-lf-swash-t1--base.tfm \
tex-EBGaramond-SemiBold-lf-swash-t1.tfm \
tex-EBGaramond-SemiBold-lf-swash-t1.vf \
tex-EBGaramond-SemiBold-lf-t1--base.tfm \
tex-EBGaramond-SemiBold-lf-t1.tfm \
tex-EBGaramond-SemiBold-lf-t1.vf \
tex-EBGaramond-SemiBold-lf-ts1--base.tfm \
tex-EBGaramond-SemiBold-lf-ts1.tfm \
tex-EBGaramond-SemiBold-lf-ts1.vf \
tex-EBGaramond-SemiBold-osf-lgr.tfm \
tex-EBGaramond-SemiBold-osf-ly1.tfm \
tex-EBGaramond-SemiBold-osf-ot1.tfm \
tex-EBGaramond-SemiBold-osf-sc-lgr.tfm \
tex-EBGaramond-SemiBold-osf-sc-ly1--base.tfm \
tex-EBGaramond-SemiBold-osf-sc-ly1.tfm \
tex-EBGaramond-SemiBold-osf-sc-ly1.vf \
tex-EBGaramond-SemiBold-osf-sc-ot1--base.tfm \
tex-EBGaramond-SemiBold-osf-sc-ot1.tfm \
tex-EBGaramond-SemiBold-osf-sc-ot1.vf \
tex-EBGaramond-SemiBold-osf-sc-t1--base.tfm \
tex-EBGaramond-SemiBold-osf-sc-t1.tfm \
tex-EBGaramond-SemiBold-osf-sc-t1.vf \
tex-EBGaramond-SemiBold-osf-swash-lgr.tfm \
tex-EBGaramond-SemiBold-osf-swash-ly1.tfm \
tex-EBGaramond-SemiBold-osf-swash-ot1.tfm \
tex-EBGaramond-SemiBold-osf-swash-t1--base.tfm \
tex-EBGaramond-SemiBold-osf-swash-t1.tfm \
tex-EBGaramond-SemiBold-osf-swash-t1.vf \
tex-EBGaramond-SemiBold-osf-t1--base.tfm \
tex-EBGaramond-SemiBold-osf-t1.tfm \
tex-EBGaramond-SemiBold-osf-t1.vf \
tex-EBGaramond-SemiBold-osf-ts1--base.tfm \
tex-EBGaramond-SemiBold-osf-ts1.tfm \
tex-EBGaramond-SemiBold-osf-ts1.vf \
tex-EBGaramond-SemiBold-sup-lgr.tfm \
tex-EBGaramond-SemiBold-sup-ly1.tfm \
tex-EBGaramond-SemiBold-sup-ot1.tfm \
tex-EBGaramond-SemiBold-sup-t1--base.tfm \
tex-EBGaramond-SemiBold-sup-t1.tfm \
tex-EBGaramond-SemiBold-sup-t1.vf \
tex-EBGaramond-SemiBold-tlf-lgr.tfm \
tex-EBGaramond-SemiBold-tlf-ly1.tfm \
tex-EBGaramond-SemiBold-tlf-ot1.tfm \
tex-EBGaramond-SemiBold-tlf-sc-lgr.tfm \
tex-EBGaramond-SemiBold-tlf-sc-ly1--base.tfm \
tex-EBGaramond-SemiBold-tlf-sc-ly1.tfm \
tex-EBGaramond-SemiBold-tlf-sc-ly1.vf \
tex-EBGaramond-SemiBold-tlf-sc-ot1--base.tfm \
tex-EBGaramond-SemiBold-tlf-sc-ot1.tfm \
tex-EBGaramond-SemiBold-tlf-sc-ot1.vf \
tex-EBGaramond-SemiBold-tlf-sc-t1--base.tfm \
tex-EBGaramond-SemiBold-tlf-sc-t1.tfm \
tex-EBGaramond-SemiBold-tlf-sc-t1.vf \
tex-EBGaramond-SemiBold-tlf-swash-lgr.tfm \
tex-EBGaramond-SemiBold-tlf-swash-ly1.tfm \
tex-EBGaramond-SemiBold-tlf-swash-ot1.tfm \
tex-EBGaramond-SemiBold-tlf-swash-t1--base.tfm \
tex-EBGaramond-SemiBold-tlf-swash-t1.tfm \
tex-EBGaramond-SemiBold-tlf-swash-t1.vf \
tex-EBGaramond-SemiBold-tlf-t1--base.tfm \
tex-EBGaramond-SemiBold-tlf-t1.tfm \
tex-EBGaramond-SemiBold-tlf-t1.vf \
tex-EBGaramond-SemiBold-tlf-ts1--base.tfm \
tex-EBGaramond-SemiBold-tlf-ts1.tfm \
tex-EBGaramond-SemiBold-tlf-ts1.vf \
tex-EBGaramond-SemiBold-tosf-lgr.tfm \
tex-EBGaramond-SemiBold-tosf-ly1.tfm \
tex-EBGaramond-SemiBold-tosf-ot1.tfm \
tex-EBGaramond-SemiBold-tosf-sc-lgr.tfm \
tex-EBGaramond-SemiBold-tosf-sc-ly1--base.tfm \
tex-EBGaramond-SemiBold-tosf-sc-ly1.tfm \
tex-EBGaramond-SemiBold-tosf-sc-ly1.vf \
tex-EBGaramond-SemiBold-tosf-sc-ot1--base.tfm \
tex-EBGaramond-SemiBold-tosf-sc-ot1.tfm \
tex-EBGaramond-SemiBold-tosf-sc-ot1.vf \
tex-EBGaramond-SemiBold-tosf-sc-t1--base.tfm \
tex-EBGaramond-SemiBold-tosf-sc-t1.tfm \
tex-EBGaramond-SemiBold-tosf-sc-t1.vf \
tex-EBGaramond-SemiBold-tosf-swash-lgr.tfm \
tex-EBGaramond-SemiBold-tosf-swash-ly1.tfm \
tex-EBGaramond-SemiBold-tosf-swash-ot1.tfm \
tex-EBGaramond-SemiBold-tosf-swash-t1--base.tfm \
tex-EBGaramond-SemiBold-tosf-swash-t1.tfm \
tex-EBGaramond-SemiBold-tosf-swash-t1.vf \
tex-EBGaramond-SemiBold-tosf-t1--base.tfm \
tex-EBGaramond-SemiBold-tosf-t1.tfm \
tex-EBGaramond-SemiBold-tosf-t1.vf \
tex-EBGaramond-SemiBold-tosf-ts1--base.tfm \
tex-EBGaramond-SemiBold-tosf-ts1.tfm \
tex-EBGaramond-SemiBold-tosf-ts1.vf \
tex-EBGaramond-SemiBoldItalic-inf-lgr.tfm \
tex-EBGaramond-SemiBoldItalic-inf-ly1.tfm \
tex-EBGaramond-SemiBoldItalic-inf-ot1.tfm \
tex-EBGaramond-SemiBoldItalic-inf-t1--base.tfm \
tex-EBGaramond-SemiBoldItalic-inf-t1.tfm \
tex-EBGaramond-SemiBoldItalic-inf-t1.vf \
tex-EBGaramond-SemiBoldItalic-lf-lgr.tfm \
tex-EBGaramond-SemiBoldItalic-lf-ly1.tfm \
tex-EBGaramond-SemiBoldItalic-lf-ot1.tfm \
tex-EBGaramond-SemiBoldItalic-lf-sc-lgr.tfm \
tex-EBGaramond-SemiBoldItalic-lf-sc-ly1--base.tfm \
tex-EBGaramond-SemiBoldItalic-lf-sc-ly1.tfm \
tex-EBGaramond-SemiBoldItalic-lf-sc-ly1.vf \
tex-EBGaramond-SemiBoldItalic-lf-sc-ot1--base.tfm \
tex-EBGaramond-SemiBoldItalic-lf-sc-ot1.tfm \
tex-EBGaramond-SemiBoldItalic-lf-sc-ot1.vf \
tex-EBGaramond-SemiBoldItalic-lf-sc-t1--base.tfm \
tex-EBGaramond-SemiBoldItalic-lf-sc-t1.tfm \
tex-EBGaramond-SemiBoldItalic-lf-sc-t1.vf \
tex-EBGaramond-SemiBoldItalic-lf-swash-lgr.tfm \
tex-EBGaramond-SemiBoldItalic-lf-swash-ly1.tfm \
tex-EBGaramond-SemiBoldItalic-lf-swash-ot1.tfm \
tex-EBGaramond-SemiBoldItalic-lf-swash-t1--base.tfm \
tex-EBGaramond-SemiBoldItalic-lf-swash-t1.tfm \
tex-EBGaramond-SemiBoldItalic-lf-swash-t1.vf \
tex-EBGaramond-SemiBoldItalic-lf-t1--base.tfm \
tex-EBGaramond-SemiBoldItalic-lf-t1.tfm \
tex-EBGaramond-SemiBoldItalic-lf-t1.vf \
tex-EBGaramond-SemiBoldItalic-lf-ts1--base.tfm \
tex-EBGaramond-SemiBoldItalic-lf-ts1.tfm \
tex-EBGaramond-SemiBoldItalic-lf-ts1.vf \
tex-EBGaramond-SemiBoldItalic-osf-lgr.tfm \
tex-EBGaramond-SemiBoldItalic-osf-ly1.tfm \
tex-EBGaramond-SemiBoldItalic-osf-ot1.tfm \
tex-EBGaramond-SemiBoldItalic-osf-sc-lgr.tfm \
tex-EBGaramond-SemiBoldItalic-osf-sc-ly1--base.tfm \
tex-EBGaramond-SemiBoldItalic-osf-sc-ly1.tfm \
tex-EBGaramond-SemiBoldItalic-osf-sc-ly1.vf \
tex-EBGaramond-SemiBoldItalic-osf-sc-ot1--base.tfm \
tex-EBGaramond-SemiBoldItalic-osf-sc-ot1.tfm \
tex-EBGaramond-SemiBoldItalic-osf-sc-ot1.vf \
tex-EBGaramond-SemiBoldItalic-osf-sc-t1--base.tfm \
tex-EBGaramond-SemiBoldItalic-osf-sc-t1.tfm \
tex-EBGaramond-SemiBoldItalic-osf-sc-t1.vf \
tex-EBGaramond-SemiBoldItalic-osf-swash-lgr.tfm \
tex-EBGaramond-SemiBoldItalic-osf-swash-ly1.tfm \
tex-EBGaramond-SemiBoldItalic-osf-swash-ot1.tfm \
tex-EBGaramond-SemiBoldItalic-osf-swash-t1--base.tfm \
tex-EBGaramond-SemiBoldItalic-osf-swash-t1.tfm \
tex-EBGaramond-SemiBoldItalic-osf-swash-t1.vf \
tex-EBGaramond-SemiBoldItalic-osf-t1--base.tfm \
tex-EBGaramond-SemiBoldItalic-osf-t1.tfm \
tex-EBGaramond-SemiBoldItalic-osf-t1.vf \
tex-EBGaramond-SemiBoldItalic-osf-ts1--base.tfm \
tex-EBGaramond-SemiBoldItalic-osf-ts1.tfm \
tex-EBGaramond-SemiBoldItalic-osf-ts1.vf \
tex-EBGaramond-SemiBoldItalic-sup-lgr.tfm \
tex-EBGaramond-SemiBoldItalic-sup-ly1.tfm \
tex-EBGaramond-SemiBoldItalic-sup-ot1.tfm \
tex-EBGaramond-SemiBoldItalic-sup-t1--base.tfm \
tex-EBGaramond-SemiBoldItalic-sup-t1.tfm \
tex-EBGaramond-SemiBoldItalic-sup-t1.vf \
tex-EBGaramond-SemiBoldItalic-tlf-lgr.tfm \
tex-EBGaramond-SemiBoldItalic-tlf-ly1.tfm \
tex-EBGaramond-SemiBoldItalic-tlf-ot1.tfm \
tex-EBGaramond-SemiBoldItalic-tlf-sc-lgr.tfm \
tex-EBGaramond-SemiBoldItalic-tlf-sc-ly1--base.tfm \
tex-EBGaramond-SemiBoldItalic-tlf-sc-ly1.tfm \
tex-EBGaramond-SemiBoldItalic-tlf-sc-ly1.vf \
tex-EBGaramond-SemiBoldItalic-tlf-sc-ot1--base.tfm \
tex-EBGaramond-SemiBoldItalic-tlf-sc-ot1.tfm \
tex-EBGaramond-SemiBoldItalic-tlf-sc-ot1.vf \
tex-EBGaramond-SemiBoldItalic-tlf-sc-t1--base.tfm \
tex-EBGaramond-SemiBoldItalic-tlf-sc-t1.tfm \
tex-EBGaramond-SemiBoldItalic-tlf-sc-t1.vf \
tex-EBGaramond-SemiBoldItalic-tlf-swash-lgr.tfm \
tex-EBGaramond-SemiBoldItalic-tlf-swash-ly1.tfm \
tex-EBGaramond-SemiBoldItalic-tlf-swash-ot1.tfm \
tex-EBGaramond-SemiBoldItalic-tlf-swash-t1--base.tfm \
tex-EBGaramond-SemiBoldItalic-tlf-swash-t1.tfm \
tex-EBGaramond-SemiBoldItalic-tlf-swash-t1.vf \
tex-EBGaramond-SemiBoldItalic-tlf-t1--base.tfm \
tex-EBGaramond-SemiBoldItalic-tlf-t1.tfm \
tex-EBGaramond-SemiBoldItalic-tlf-t1.vf \
tex-EBGaramond-SemiBoldItalic-tlf-ts1--base.tfm \
tex-EBGaramond-SemiBoldItalic-tlf-ts1.tfm \
tex-EBGaramond-SemiBoldItalic-tlf-ts1.vf \
tex-EBGaramond-SemiBoldItalic-tosf-lgr.tfm \
tex-EBGaramond-SemiBoldItalic-tosf-ly1.tfm \
tex-EBGaramond-SemiBoldItalic-tosf-ot1.tfm \
tex-EBGaramond-SemiBoldItalic-tosf-sc-lgr.tfm \
tex-EBGaramond-SemiBoldItalic-tosf-sc-ly1--base.tfm \
tex-EBGaramond-SemiBoldItalic-tosf-sc-ly1.tfm \
tex-EBGaramond-SemiBoldItalic-tosf-sc-ly1.vf \
tex-EBGaramond-SemiBoldItalic-tosf-sc-ot1--base.tfm \
tex-EBGaramond-SemiBoldItalic-tosf-sc-ot1.tfm \
tex-EBGaramond-SemiBoldItalic-tosf-sc-ot1.vf \
tex-EBGaramond-SemiBoldItalic-tosf-sc-t1--base.tfm \
tex-EBGaramond-SemiBoldItalic-tosf-sc-t1.tfm \
tex-EBGaramond-SemiBoldItalic-tosf-sc-t1.vf \
tex-EBGaramond-SemiBoldItalic-tosf-swash-lgr.tfm \
tex-EBGaramond-SemiBoldItalic-tosf-swash-ly1.tfm \
tex-EBGaramond-SemiBoldItalic-tosf-swash-ot1.tfm \
tex-EBGaramond-SemiBoldItalic-tosf-swash-t1--base.tfm \
tex-EBGaramond-SemiBoldItalic-tosf-swash-t1.tfm \
tex-EBGaramond-SemiBoldItalic-tosf-swash-t1.vf \
tex-EBGaramond-SemiBoldItalic-tosf-t1--base.tfm \
tex-EBGaramond-SemiBoldItalic-tosf-t1.tfm \
tex-EBGaramond-SemiBoldItalic-tosf-t1.vf \
tex-EBGaramond-SemiBoldItalic-tosf-ts1--base.tfm \
tex-EBGaramond-SemiBoldItalic-tosf-ts1.tfm \
tex-EBGaramond-SemiBoldItalic-tosf-ts1.vf \
tex-EBGaramond.map \
tex-EBGaramondInitials-tlf-lgr.tfm \
tex-EBGaramondInitials-tlf-lgr.vf \
tex-EBGaramondInitials-tlf-ly1--base.tfm \
tex-EBGaramondInitials-tlf-ly1.tfm \
tex-EBGaramondInitials-tlf-ly1.vf \
tex-EBGaramondInitials-tlf-ot1.tfm \
tex-EBGaramondInitials-tlf-t1--base.tfm \
tex-EBGaramondInitials-tlf-t1.tfm \
tex-EBGaramondInitials-tlf-t1.vf \
tex-EBGaramondInitials-tlf-ts1.tfm \
tex-EBGaramondInitials-tlf-ts1.vf \
tex-LGREBGaramond-Inf.fd \
tex-LGREBGaramond-LF.fd \
tex-LGREBGaramond-OsF.fd \
tex-LGREBGaramond-Sup.fd \
tex-LGREBGaramond-TLF.fd \
tex-LGREBGaramond-TOsF.fd \
tex-LGREBGaramondInitials-TLF.fd \
tex-LY1EBGaramond-Inf.fd \
tex-LY1EBGaramond-LF.fd \
tex-LY1EBGaramond-OsF.fd \
tex-LY1EBGaramond-Sup.fd \
tex-LY1EBGaramond-TLF.fd \
tex-LY1EBGaramond-TOsF.fd \
tex-LY1EBGaramondInitials-TLF.fd \
tex-OT1EBGaramond-Inf.fd \
tex-OT1EBGaramond-LF.fd \
tex-OT1EBGaramond-OsF.fd \
tex-OT1EBGaramond-Sup.fd \
tex-OT1EBGaramond-TLF.fd \
tex-OT1EBGaramond-TOsF.fd \
tex-OT1EBGaramondInitials-TLF.fd \
tex-T1EBGaramond-Inf.fd \
tex-T1EBGaramond-LF.fd \
tex-T1EBGaramond-OsF.fd \
tex-T1EBGaramond-Sup.fd \
tex-T1EBGaramond-TLF.fd \
tex-T1EBGaramond-TOsF.fd \
tex-T1EBGaramondInitials-TLF.fd \
tex-TS1EBGaramond-LF.fd \
tex-TS1EBGaramond-OsF.fd \
tex-TS1EBGaramond-TLF.fd \
tex-TS1EBGaramond-TOsF.fd \
tex-TS1EBGaramondInitials-TLF.fd \
tex-ebg-2ybfsp.enc \
tex-ebg-3fqt6z.enc \
tex-ebg-3uowis.enc \
tex-ebg-3vzm4e.enc \
tex-ebg-3zuots.enc \
tex-ebg-44fx2b.enc \
tex-ebg-4a6c3c.enc \
tex-ebg-5xwr64.enc \
tex-ebg-67ivnh.enc \
tex-ebg-6f65kf.enc \
tex-ebg-6vgerf.enc \
tex-ebg-76r3mr.enc \
tex-ebg-7bnove.enc \
tex-ebg-7kld4e.enc \
tex-ebg-a47fbg.enc \
tex-ebg-a56nal.enc \
tex-ebg-aetq3h.enc \
tex-ebg-b3o4f3.enc \
tex-ebg-bisgyq.enc \
tex-ebg-bk5d2z.enc \
tex-ebg-brg5ul.enc \
tex-ebg-bszlvl.enc \
tex-ebg-byuyni.enc \
tex-ebg-chpilv.enc \
tex-ebg-cqx43s.enc \
tex-ebg-csz5sy.enc \
tex-ebg-cxm7q6.enc \
tex-ebg-czgldd.enc \
tex-ebg-dacnth.enc \
tex-ebg-dueoe2.enc \
tex-ebg-egxhgf.enc \
tex-ebg-fbpsnn.enc \
tex-ebg-fc5dte.enc \
tex-ebg-gom7pk.enc \
tex-ebg-hp76oj.enc \
tex-ebg-hw36ef.enc \
tex-ebg-io7fa4.enc \
tex-ebg-jcj62x.enc \
tex-ebg-jnlxoz.enc \
tex-ebg-kcfom2.enc \
tex-ebg-kfeykp.enc \
tex-ebg-kntoon.enc \
tex-ebg-l5gusm.enc \
tex-ebg-ldtcgl.enc \
tex-ebg-liamow.enc \
tex-ebg-ljow5q.enc \
tex-ebg-lusvph.enc \
tex-ebg-lwn542.enc \
tex-ebg-mfbzjz.enc \
tex-ebg-mknaq2.enc \
tex-ebg-mnmcle.enc \
tex-ebg-myzmkp.enc \
tex-ebg-ne3tkd.enc \
tex-ebg-nfvoop.enc \
tex-ebg-nhfy4v.enc \
tex-ebg-notamz.enc \
tex-ebg-omaeoe.enc \
tex-ebg-oskdwa.enc \
tex-ebg-oyql7g.enc \
tex-ebg-pp67px.enc \
tex-ebg-pt4oo6.enc \
tex-ebg-q5xwdw.enc \
tex-ebg-q66dhc.enc \
tex-ebg-qn2lct.enc \
tex-ebg-qn3sxp.enc \
tex-ebg-qopy46.enc \
tex-ebg-qtn4jw.enc \
tex-ebg-qwnohr.enc \
tex-ebg-r6u53g.enc \
tex-ebg-rqcrtt.enc \
tex-ebg-ssaxzz.enc \
tex-ebg-swtfyq.enc \
tex-ebg-t35j2l.enc \
tex-ebg-tcdnmr.enc \
tex-ebg-tnqsun.enc \
tex-ebg-tupdk5.enc \
tex-ebg-uq734l.enc \
tex-ebg-utcbyj.enc \
tex-ebg-utfkrl.enc \
tex-ebg-vqtmeh.enc \
tex-ebg-vrf56d.enc \
tex-ebg-vxqeam.enc \
tex-ebg-wuzenr.enc \
tex-ebg-xoskhe.enc \
tex-ebg-xvcw4o.enc \
tex-ebg-xzodth.enc \
tex-ebg-yjkoc2.enc \
tex-ebg-yod6vr.enc \
tex-ebg-zesep7.enc \
tex-ebg-zkec3z.enc \
tex-ebg-zw743z.enc \
tex-ebgaramond.sty \
texlive-ebgaramond"

RDEPENDS:${PN} += "/usr/bin/sh \
coreutils \
ed \
findutils \
grep \
sed \
tex-fontaxes.sty \
tex-fontenc.sty \
tex-fontspec.sty \
tex-ifluatex.sty \
tex-ifxetex.sty \
tex-mweights.sty \
tex-textcomp.sty \
tex-updmap.cfg \
tex-xkeyval.sty \
texlive \
texlive-ebgaramond-fonts \
texlive-filesystem \
texlive-kpathsea \
texlive-kpathsea-bin \
texlive-scripts \
texlive-scripts-bin"

inherit rpm
