SUMMARY = "Support for using Libertinus fonts with LaTeX/pdfLaTeX"
DESCRIPTION = "This package provides support for use of Libertinus fonts with \
traditional processing engines (LaTeX with dvips or dvipdfmx, \
or pdfLaTeX)."
LICENSE = "GPL-2.0-or-later"

PV = "2026.226.svn76891"

RPM_NAME = "texlive-libertinus-type1-2026.226.svn76891-61.2.noarch.rpm"
RPM_HASH = "fc59d91f0745ca87cfe2357594a9f5b8b4138ea0fe65090eefd97751d2c8de883590d12ce2e7d9fd8e073bf3246d34dc9caa7b4d4a9fcce4b1792865b61e8525"
REPO_ARCH = "noarch"

RPROVIDES:${PN} += "tex-LGRLibertinusMono-TLF.fd \
tex-LGRLibertinusSans-LF.fd \
tex-LGRLibertinusSans-OsF.fd \
tex-LGRLibertinusSans-Sup.fd \
tex-LGRLibertinusSans-TLF.fd \
tex-LGRLibertinusSans-TOsF.fd \
tex-LGRLibertinusSerif-LF.fd \
tex-LGRLibertinusSerif-OsF.fd \
tex-LGRLibertinusSerif-Sup.fd \
tex-LGRLibertinusSerif-TLF.fd \
tex-LGRLibertinusSerif-TOsF.fd \
tex-LY1LibertinusMono-TLF.fd \
tex-LY1LibertinusSans-LF.fd \
tex-LY1LibertinusSans-OsF.fd \
tex-LY1LibertinusSans-Sup.fd \
tex-LY1LibertinusSans-TLF.fd \
tex-LY1LibertinusSans-TOsF.fd \
tex-LY1LibertinusSerif-LF.fd \
tex-LY1LibertinusSerif-OsF.fd \
tex-LY1LibertinusSerif-Sup.fd \
tex-LY1LibertinusSerif-TLF.fd \
tex-LY1LibertinusSerif-TOsF.fd \
tex-LY1LibertinusSerifDisplay-LF.fd \
tex-LY1LibertinusSerifDisplay-OsF.fd \
tex-LY1LibertinusSerifDisplay-Sup.fd \
tex-LY1LibertinusSerifDisplay-TLF.fd \
tex-LY1LibertinusSerifDisplay-TOsF.fd \
tex-LibertinusMono-Bold-tlf-ly1--base.tfm \
tex-LibertinusMono-Bold-tlf-ly1.tfm \
tex-LibertinusMono-Bold-tlf-ly1.vf \
tex-LibertinusMono-Bold-tlf-ot1.tfm \
tex-LibertinusMono-Bold-tlf-t1--base.tfm \
tex-LibertinusMono-Bold-tlf-t1.tfm \
tex-LibertinusMono-Bold-tlf-t1.vf \
tex-LibertinusMono-Bold-tlf-ts1--base.tfm \
tex-LibertinusMono-Bold-tlf-ts1.tfm \
tex-LibertinusMono-Bold-tlf-ts1.vf \
tex-LibertinusMono-BoldItalic-tlf-ly1--base.tfm \
tex-LibertinusMono-BoldItalic-tlf-ly1.tfm \
tex-LibertinusMono-BoldItalic-tlf-ly1.vf \
tex-LibertinusMono-BoldItalic-tlf-ot1.tfm \
tex-LibertinusMono-BoldItalic-tlf-t1--base.tfm \
tex-LibertinusMono-BoldItalic-tlf-t1.tfm \
tex-LibertinusMono-BoldItalic-tlf-t1.vf \
tex-LibertinusMono-BoldItalic-tlf-ts1--base.tfm \
tex-LibertinusMono-BoldItalic-tlf-ts1.tfm \
tex-LibertinusMono-BoldItalic-tlf-ts1.vf \
tex-LibertinusMono-Italic-tlf-ly1--base.tfm \
tex-LibertinusMono-Italic-tlf-ly1.tfm \
tex-LibertinusMono-Italic-tlf-ly1.vf \
tex-LibertinusMono-Italic-tlf-ot1.tfm \
tex-LibertinusMono-Italic-tlf-t1--base.tfm \
tex-LibertinusMono-Italic-tlf-t1.tfm \
tex-LibertinusMono-Italic-tlf-t1.vf \
tex-LibertinusMono-Italic-tlf-ts1--base.tfm \
tex-LibertinusMono-Italic-tlf-ts1.tfm \
tex-LibertinusMono-Italic-tlf-ts1.vf \
tex-LibertinusMono-Regular-tlf-lgr--base.tfm \
tex-LibertinusMono-Regular-tlf-lgr.tfm \
tex-LibertinusMono-Regular-tlf-lgr.vf \
tex-LibertinusMono-Regular-tlf-ly1--base.tfm \
tex-LibertinusMono-Regular-tlf-ly1.tfm \
tex-LibertinusMono-Regular-tlf-ly1.vf \
tex-LibertinusMono-Regular-tlf-ot1.tfm \
tex-LibertinusMono-Regular-tlf-t1--base.tfm \
tex-LibertinusMono-Regular-tlf-t1.tfm \
tex-LibertinusMono-Regular-tlf-t1.vf \
tex-LibertinusMono-Regular-tlf-t2a.tfm \
tex-LibertinusMono-Regular-tlf-t2b.tfm \
tex-LibertinusMono-Regular-tlf-t2c.tfm \
tex-LibertinusMono-Regular-tlf-ts1--base.tfm \
tex-LibertinusMono-Regular-tlf-ts1.tfm \
tex-LibertinusMono-Regular-tlf-ts1.vf \
tex-LibertinusMono.map \
tex-LibertinusSans-Bold-lf-lgr.tfm \
tex-LibertinusSans-Bold-lf-ly1.tfm \
tex-LibertinusSans-Bold-lf-ot1.tfm \
tex-LibertinusSans-Bold-lf-sc-lgr.tfm \
tex-LibertinusSans-Bold-lf-sc-ly1--base.tfm \
tex-LibertinusSans-Bold-lf-sc-ly1.tfm \
tex-LibertinusSans-Bold-lf-sc-ly1.vf \
tex-LibertinusSans-Bold-lf-sc-ot1--base.tfm \
tex-LibertinusSans-Bold-lf-sc-ot1.tfm \
tex-LibertinusSans-Bold-lf-sc-ot1.vf \
tex-LibertinusSans-Bold-lf-sc-t1--base.tfm \
tex-LibertinusSans-Bold-lf-sc-t1.tfm \
tex-LibertinusSans-Bold-lf-sc-t1.vf \
tex-LibertinusSans-Bold-lf-sc-t2a--base.tfm \
tex-LibertinusSans-Bold-lf-sc-t2a.tfm \
tex-LibertinusSans-Bold-lf-sc-t2a.vf \
tex-LibertinusSans-Bold-lf-sc-t2b--base.tfm \
tex-LibertinusSans-Bold-lf-sc-t2b.tfm \
tex-LibertinusSans-Bold-lf-sc-t2b.vf \
tex-LibertinusSans-Bold-lf-sc-t2c--base.tfm \
tex-LibertinusSans-Bold-lf-sc-t2c.tfm \
tex-LibertinusSans-Bold-lf-sc-t2c.vf \
tex-LibertinusSans-Bold-lf-t1--base.tfm \
tex-LibertinusSans-Bold-lf-t1.tfm \
tex-LibertinusSans-Bold-lf-t1.vf \
tex-LibertinusSans-Bold-lf-t2a.tfm \
tex-LibertinusSans-Bold-lf-t2b.tfm \
tex-LibertinusSans-Bold-lf-t2c.tfm \
tex-LibertinusSans-Bold-lf-ts1--base.tfm \
tex-LibertinusSans-Bold-lf-ts1.tfm \
tex-LibertinusSans-Bold-lf-ts1.vf \
tex-LibertinusSans-Bold-osf-lgr.tfm \
tex-LibertinusSans-Bold-osf-ly1.tfm \
tex-LibertinusSans-Bold-osf-ot1.tfm \
tex-LibertinusSans-Bold-osf-sc-lgr.tfm \
tex-LibertinusSans-Bold-osf-sc-ly1--base.tfm \
tex-LibertinusSans-Bold-osf-sc-ly1.tfm \
tex-LibertinusSans-Bold-osf-sc-ly1.vf \
tex-LibertinusSans-Bold-osf-sc-ot1--base.tfm \
tex-LibertinusSans-Bold-osf-sc-ot1.tfm \
tex-LibertinusSans-Bold-osf-sc-ot1.vf \
tex-LibertinusSans-Bold-osf-sc-t1--base.tfm \
tex-LibertinusSans-Bold-osf-sc-t1.tfm \
tex-LibertinusSans-Bold-osf-sc-t1.vf \
tex-LibertinusSans-Bold-osf-sc-t2a--base.tfm \
tex-LibertinusSans-Bold-osf-sc-t2a.tfm \
tex-LibertinusSans-Bold-osf-sc-t2a.vf \
tex-LibertinusSans-Bold-osf-sc-t2b--base.tfm \
tex-LibertinusSans-Bold-osf-sc-t2b.tfm \
tex-LibertinusSans-Bold-osf-sc-t2b.vf \
tex-LibertinusSans-Bold-osf-sc-t2c--base.tfm \
tex-LibertinusSans-Bold-osf-sc-t2c.tfm \
tex-LibertinusSans-Bold-osf-sc-t2c.vf \
tex-LibertinusSans-Bold-osf-t1--base.tfm \
tex-LibertinusSans-Bold-osf-t1.tfm \
tex-LibertinusSans-Bold-osf-t1.vf \
tex-LibertinusSans-Bold-osf-t2a.tfm \
tex-LibertinusSans-Bold-osf-t2b.tfm \
tex-LibertinusSans-Bold-osf-t2c.tfm \
tex-LibertinusSans-Bold-osf-ts1--base.tfm \
tex-LibertinusSans-Bold-osf-ts1.tfm \
tex-LibertinusSans-Bold-osf-ts1.vf \
tex-LibertinusSans-Bold-sup-lgr.tfm \
tex-LibertinusSans-Bold-sup-ly1.tfm \
tex-LibertinusSans-Bold-sup-ot1.tfm \
tex-LibertinusSans-Bold-sup-t1--base.tfm \
tex-LibertinusSans-Bold-sup-t1.tfm \
tex-LibertinusSans-Bold-sup-t1.vf \
tex-LibertinusSans-Bold-sup-t2a.tfm \
tex-LibertinusSans-Bold-sup-t2b.tfm \
tex-LibertinusSans-Bold-sup-t2c.tfm \
tex-LibertinusSans-Bold-tlf-lgr.tfm \
tex-LibertinusSans-Bold-tlf-ly1.tfm \
tex-LibertinusSans-Bold-tlf-ot1.tfm \
tex-LibertinusSans-Bold-tlf-sc-lgr.tfm \
tex-LibertinusSans-Bold-tlf-sc-ly1--base.tfm \
tex-LibertinusSans-Bold-tlf-sc-ly1.tfm \
tex-LibertinusSans-Bold-tlf-sc-ly1.vf \
tex-LibertinusSans-Bold-tlf-sc-ot1--base.tfm \
tex-LibertinusSans-Bold-tlf-sc-ot1.tfm \
tex-LibertinusSans-Bold-tlf-sc-ot1.vf \
tex-LibertinusSans-Bold-tlf-sc-t1--base.tfm \
tex-LibertinusSans-Bold-tlf-sc-t1.tfm \
tex-LibertinusSans-Bold-tlf-sc-t1.vf \
tex-LibertinusSans-Bold-tlf-sc-t2a--base.tfm \
tex-LibertinusSans-Bold-tlf-sc-t2a.tfm \
tex-LibertinusSans-Bold-tlf-sc-t2a.vf \
tex-LibertinusSans-Bold-tlf-sc-t2b--base.tfm \
tex-LibertinusSans-Bold-tlf-sc-t2b.tfm \
tex-LibertinusSans-Bold-tlf-sc-t2b.vf \
tex-LibertinusSans-Bold-tlf-sc-t2c--base.tfm \
tex-LibertinusSans-Bold-tlf-sc-t2c.tfm \
tex-LibertinusSans-Bold-tlf-sc-t2c.vf \
tex-LibertinusSans-Bold-tlf-t1--base.tfm \
tex-LibertinusSans-Bold-tlf-t1.tfm \
tex-LibertinusSans-Bold-tlf-t1.vf \
tex-LibertinusSans-Bold-tlf-t2a.tfm \
tex-LibertinusSans-Bold-tlf-t2b.tfm \
tex-LibertinusSans-Bold-tlf-t2c.tfm \
tex-LibertinusSans-Bold-tlf-ts1--base.tfm \
tex-LibertinusSans-Bold-tlf-ts1.tfm \
tex-LibertinusSans-Bold-tlf-ts1.vf \
tex-LibertinusSans-Bold-tosf-lgr.tfm \
tex-LibertinusSans-Bold-tosf-ly1.tfm \
tex-LibertinusSans-Bold-tosf-ot1.tfm \
tex-LibertinusSans-Bold-tosf-sc-lgr.tfm \
tex-LibertinusSans-Bold-tosf-sc-ly1--base.tfm \
tex-LibertinusSans-Bold-tosf-sc-ly1.tfm \
tex-LibertinusSans-Bold-tosf-sc-ly1.vf \
tex-LibertinusSans-Bold-tosf-sc-ot1--base.tfm \
tex-LibertinusSans-Bold-tosf-sc-ot1.tfm \
tex-LibertinusSans-Bold-tosf-sc-ot1.vf \
tex-LibertinusSans-Bold-tosf-sc-t1--base.tfm \
tex-LibertinusSans-Bold-tosf-sc-t1.tfm \
tex-LibertinusSans-Bold-tosf-sc-t1.vf \
tex-LibertinusSans-Bold-tosf-sc-t2a--base.tfm \
tex-LibertinusSans-Bold-tosf-sc-t2a.tfm \
tex-LibertinusSans-Bold-tosf-sc-t2a.vf \
tex-LibertinusSans-Bold-tosf-sc-t2b--base.tfm \
tex-LibertinusSans-Bold-tosf-sc-t2b.tfm \
tex-LibertinusSans-Bold-tosf-sc-t2b.vf \
tex-LibertinusSans-Bold-tosf-sc-t2c--base.tfm \
tex-LibertinusSans-Bold-tosf-sc-t2c.tfm \
tex-LibertinusSans-Bold-tosf-sc-t2c.vf \
tex-LibertinusSans-Bold-tosf-t1--base.tfm \
tex-LibertinusSans-Bold-tosf-t1.tfm \
tex-LibertinusSans-Bold-tosf-t1.vf \
tex-LibertinusSans-Bold-tosf-t2a.tfm \
tex-LibertinusSans-Bold-tosf-t2b.tfm \
tex-LibertinusSans-Bold-tosf-t2c.tfm \
tex-LibertinusSans-Bold-tosf-ts1--base.tfm \
tex-LibertinusSans-Bold-tosf-ts1.tfm \
tex-LibertinusSans-Bold-tosf-ts1.vf \
tex-LibertinusSans-Italic-lf-lgr--base.tfm \
tex-LibertinusSans-Italic-lf-lgr.tfm \
tex-LibertinusSans-Italic-lf-lgr.vf \
tex-LibertinusSans-Italic-lf-ly1--base.tfm \
tex-LibertinusSans-Italic-lf-ly1.tfm \
tex-LibertinusSans-Italic-lf-ly1.vf \
tex-LibertinusSans-Italic-lf-ot1.tfm \
tex-LibertinusSans-Italic-lf-sc-lgr--base.tfm \
tex-LibertinusSans-Italic-lf-sc-lgr.tfm \
tex-LibertinusSans-Italic-lf-sc-lgr.vf \
tex-LibertinusSans-Italic-lf-sc-ly1--base.tfm \
tex-LibertinusSans-Italic-lf-sc-ly1.tfm \
tex-LibertinusSans-Italic-lf-sc-ly1.vf \
tex-LibertinusSans-Italic-lf-sc-ot1--base.tfm \
tex-LibertinusSans-Italic-lf-sc-ot1.tfm \
tex-LibertinusSans-Italic-lf-sc-ot1.vf \
tex-LibertinusSans-Italic-lf-sc-t1--base.tfm \
tex-LibertinusSans-Italic-lf-sc-t1.tfm \
tex-LibertinusSans-Italic-lf-sc-t1.vf \
tex-LibertinusSans-Italic-lf-sc-t2a--base.tfm \
tex-LibertinusSans-Italic-lf-sc-t2a.tfm \
tex-LibertinusSans-Italic-lf-sc-t2a.vf \
tex-LibertinusSans-Italic-lf-sc-t2b--base.tfm \
tex-LibertinusSans-Italic-lf-sc-t2b.tfm \
tex-LibertinusSans-Italic-lf-sc-t2b.vf \
tex-LibertinusSans-Italic-lf-sc-t2c--base.tfm \
tex-LibertinusSans-Italic-lf-sc-t2c.tfm \
tex-LibertinusSans-Italic-lf-sc-t2c.vf \
tex-LibertinusSans-Italic-lf-t1--base.tfm \
tex-LibertinusSans-Italic-lf-t1.tfm \
tex-LibertinusSans-Italic-lf-t1.vf \
tex-LibertinusSans-Italic-lf-t2a.tfm \
tex-LibertinusSans-Italic-lf-t2b.tfm \
tex-LibertinusSans-Italic-lf-t2c.tfm \
tex-LibertinusSans-Italic-lf-ts1--base.tfm \
tex-LibertinusSans-Italic-lf-ts1.tfm \
tex-LibertinusSans-Italic-lf-ts1.vf \
tex-LibertinusSans-Italic-osf-lgr--base.tfm \
tex-LibertinusSans-Italic-osf-lgr.tfm \
tex-LibertinusSans-Italic-osf-lgr.vf \
tex-LibertinusSans-Italic-osf-ly1--base.tfm \
tex-LibertinusSans-Italic-osf-ly1.tfm \
tex-LibertinusSans-Italic-osf-ly1.vf \
tex-LibertinusSans-Italic-osf-ot1.tfm \
tex-LibertinusSans-Italic-osf-sc-lgr--base.tfm \
tex-LibertinusSans-Italic-osf-sc-lgr.tfm \
tex-LibertinusSans-Italic-osf-sc-lgr.vf \
tex-LibertinusSans-Italic-osf-sc-ly1--base.tfm \
tex-LibertinusSans-Italic-osf-sc-ly1.tfm \
tex-LibertinusSans-Italic-osf-sc-ly1.vf \
tex-LibertinusSans-Italic-osf-sc-ot1--base.tfm \
tex-LibertinusSans-Italic-osf-sc-ot1.tfm \
tex-LibertinusSans-Italic-osf-sc-ot1.vf \
tex-LibertinusSans-Italic-osf-sc-t1--base.tfm \
tex-LibertinusSans-Italic-osf-sc-t1.tfm \
tex-LibertinusSans-Italic-osf-sc-t1.vf \
tex-LibertinusSans-Italic-osf-sc-t2a--base.tfm \
tex-LibertinusSans-Italic-osf-sc-t2a.tfm \
tex-LibertinusSans-Italic-osf-sc-t2a.vf \
tex-LibertinusSans-Italic-osf-sc-t2b--base.tfm \
tex-LibertinusSans-Italic-osf-sc-t2b.tfm \
tex-LibertinusSans-Italic-osf-sc-t2b.vf \
tex-LibertinusSans-Italic-osf-sc-t2c--base.tfm \
tex-LibertinusSans-Italic-osf-sc-t2c.tfm \
tex-LibertinusSans-Italic-osf-sc-t2c.vf \
tex-LibertinusSans-Italic-osf-t1--base.tfm \
tex-LibertinusSans-Italic-osf-t1.tfm \
tex-LibertinusSans-Italic-osf-t1.vf \
tex-LibertinusSans-Italic-osf-t2a.tfm \
tex-LibertinusSans-Italic-osf-t2b.tfm \
tex-LibertinusSans-Italic-osf-t2c.tfm \
tex-LibertinusSans-Italic-osf-ts1--base.tfm \
tex-LibertinusSans-Italic-osf-ts1.tfm \
tex-LibertinusSans-Italic-osf-ts1.vf \
tex-LibertinusSans-Italic-sup-lgr--base.tfm \
tex-LibertinusSans-Italic-sup-lgr.tfm \
tex-LibertinusSans-Italic-sup-lgr.vf \
tex-LibertinusSans-Italic-sup-ly1--base.tfm \
tex-LibertinusSans-Italic-sup-ly1.tfm \
tex-LibertinusSans-Italic-sup-ly1.vf \
tex-LibertinusSans-Italic-sup-ot1.tfm \
tex-LibertinusSans-Italic-sup-t1--base.tfm \
tex-LibertinusSans-Italic-sup-t1.tfm \
tex-LibertinusSans-Italic-sup-t1.vf \
tex-LibertinusSans-Italic-sup-t2a.tfm \
tex-LibertinusSans-Italic-sup-t2b.tfm \
tex-LibertinusSans-Italic-sup-t2c.tfm \
tex-LibertinusSans-Italic-tlf-lgr--base.tfm \
tex-LibertinusSans-Italic-tlf-lgr.tfm \
tex-LibertinusSans-Italic-tlf-lgr.vf \
tex-LibertinusSans-Italic-tlf-ly1--base.tfm \
tex-LibertinusSans-Italic-tlf-ly1.tfm \
tex-LibertinusSans-Italic-tlf-ly1.vf \
tex-LibertinusSans-Italic-tlf-ot1.tfm \
tex-LibertinusSans-Italic-tlf-sc-lgr--base.tfm \
tex-LibertinusSans-Italic-tlf-sc-lgr.tfm \
tex-LibertinusSans-Italic-tlf-sc-lgr.vf \
tex-LibertinusSans-Italic-tlf-sc-ly1--base.tfm \
tex-LibertinusSans-Italic-tlf-sc-ly1.tfm \
tex-LibertinusSans-Italic-tlf-sc-ly1.vf \
tex-LibertinusSans-Italic-tlf-sc-ot1--base.tfm \
tex-LibertinusSans-Italic-tlf-sc-ot1.tfm \
tex-LibertinusSans-Italic-tlf-sc-ot1.vf \
tex-LibertinusSans-Italic-tlf-sc-t1--base.tfm \
tex-LibertinusSans-Italic-tlf-sc-t1.tfm \
tex-LibertinusSans-Italic-tlf-sc-t1.vf \
tex-LibertinusSans-Italic-tlf-sc-t2a--base.tfm \
tex-LibertinusSans-Italic-tlf-sc-t2a.tfm \
tex-LibertinusSans-Italic-tlf-sc-t2a.vf \
tex-LibertinusSans-Italic-tlf-sc-t2b--base.tfm \
tex-LibertinusSans-Italic-tlf-sc-t2b.tfm \
tex-LibertinusSans-Italic-tlf-sc-t2b.vf \
tex-LibertinusSans-Italic-tlf-sc-t2c--base.tfm \
tex-LibertinusSans-Italic-tlf-sc-t2c.tfm \
tex-LibertinusSans-Italic-tlf-sc-t2c.vf \
tex-LibertinusSans-Italic-tlf-t1--base.tfm \
tex-LibertinusSans-Italic-tlf-t1.tfm \
tex-LibertinusSans-Italic-tlf-t1.vf \
tex-LibertinusSans-Italic-tlf-t2a.tfm \
tex-LibertinusSans-Italic-tlf-t2b.tfm \
tex-LibertinusSans-Italic-tlf-t2c.tfm \
tex-LibertinusSans-Italic-tlf-ts1--base.tfm \
tex-LibertinusSans-Italic-tlf-ts1.tfm \
tex-LibertinusSans-Italic-tlf-ts1.vf \
tex-LibertinusSans-Italic-tosf-lgr--base.tfm \
tex-LibertinusSans-Italic-tosf-lgr.tfm \
tex-LibertinusSans-Italic-tosf-lgr.vf \
tex-LibertinusSans-Italic-tosf-ly1--base.tfm \
tex-LibertinusSans-Italic-tosf-ly1.tfm \
tex-LibertinusSans-Italic-tosf-ly1.vf \
tex-LibertinusSans-Italic-tosf-ot1.tfm \
tex-LibertinusSans-Italic-tosf-sc-lgr--base.tfm \
tex-LibertinusSans-Italic-tosf-sc-lgr.tfm \
tex-LibertinusSans-Italic-tosf-sc-lgr.vf \
tex-LibertinusSans-Italic-tosf-sc-ly1--base.tfm \
tex-LibertinusSans-Italic-tosf-sc-ly1.tfm \
tex-LibertinusSans-Italic-tosf-sc-ly1.vf \
tex-LibertinusSans-Italic-tosf-sc-ot1--base.tfm \
tex-LibertinusSans-Italic-tosf-sc-ot1.tfm \
tex-LibertinusSans-Italic-tosf-sc-ot1.vf \
tex-LibertinusSans-Italic-tosf-sc-t1--base.tfm \
tex-LibertinusSans-Italic-tosf-sc-t1.tfm \
tex-LibertinusSans-Italic-tosf-sc-t1.vf \
tex-LibertinusSans-Italic-tosf-sc-t2a--base.tfm \
tex-LibertinusSans-Italic-tosf-sc-t2a.tfm \
tex-LibertinusSans-Italic-tosf-sc-t2a.vf \
tex-LibertinusSans-Italic-tosf-sc-t2b--base.tfm \
tex-LibertinusSans-Italic-tosf-sc-t2b.tfm \
tex-LibertinusSans-Italic-tosf-sc-t2b.vf \
tex-LibertinusSans-Italic-tosf-sc-t2c--base.tfm \
tex-LibertinusSans-Italic-tosf-sc-t2c.tfm \
tex-LibertinusSans-Italic-tosf-sc-t2c.vf \
tex-LibertinusSans-Italic-tosf-t1--base.tfm \
tex-LibertinusSans-Italic-tosf-t1.tfm \
tex-LibertinusSans-Italic-tosf-t1.vf \
tex-LibertinusSans-Italic-tosf-t2a.tfm \
tex-LibertinusSans-Italic-tosf-t2b.tfm \
tex-LibertinusSans-Italic-tosf-t2c.tfm \
tex-LibertinusSans-Italic-tosf-ts1--base.tfm \
tex-LibertinusSans-Italic-tosf-ts1.tfm \
tex-LibertinusSans-Italic-tosf-ts1.vf \
tex-LibertinusSans-Regular-lf-lgr.tfm \
tex-LibertinusSans-Regular-lf-ly1.tfm \
tex-LibertinusSans-Regular-lf-ot1.tfm \
tex-LibertinusSans-Regular-lf-sc-lgr.tfm \
tex-LibertinusSans-Regular-lf-sc-ly1--base.tfm \
tex-LibertinusSans-Regular-lf-sc-ly1.tfm \
tex-LibertinusSans-Regular-lf-sc-ly1.vf \
tex-LibertinusSans-Regular-lf-sc-ot1--base.tfm \
tex-LibertinusSans-Regular-lf-sc-ot1.tfm \
tex-LibertinusSans-Regular-lf-sc-ot1.vf \
tex-LibertinusSans-Regular-lf-sc-t1--base.tfm \
tex-LibertinusSans-Regular-lf-sc-t1.tfm \
tex-LibertinusSans-Regular-lf-sc-t1.vf \
tex-LibertinusSans-Regular-lf-sc-t2a--base.tfm \
tex-LibertinusSans-Regular-lf-sc-t2a.tfm \
tex-LibertinusSans-Regular-lf-sc-t2a.vf \
tex-LibertinusSans-Regular-lf-sc-t2b--base.tfm \
tex-LibertinusSans-Regular-lf-sc-t2b.tfm \
tex-LibertinusSans-Regular-lf-sc-t2b.vf \
tex-LibertinusSans-Regular-lf-sc-t2c--base.tfm \
tex-LibertinusSans-Regular-lf-sc-t2c.tfm \
tex-LibertinusSans-Regular-lf-sc-t2c.vf \
tex-LibertinusSans-Regular-lf-t1--base.tfm \
tex-LibertinusSans-Regular-lf-t1.tfm \
tex-LibertinusSans-Regular-lf-t1.vf \
tex-LibertinusSans-Regular-lf-t2a.tfm \
tex-LibertinusSans-Regular-lf-t2b.tfm \
tex-LibertinusSans-Regular-lf-t2c.tfm \
tex-LibertinusSans-Regular-lf-ts1--base.tfm \
tex-LibertinusSans-Regular-lf-ts1.tfm \
tex-LibertinusSans-Regular-lf-ts1.vf \
tex-LibertinusSans-Regular-osf-lgr.tfm \
tex-LibertinusSans-Regular-osf-ly1.tfm \
tex-LibertinusSans-Regular-osf-ot1.tfm \
tex-LibertinusSans-Regular-osf-sc-lgr.tfm \
tex-LibertinusSans-Regular-osf-sc-ly1--base.tfm \
tex-LibertinusSans-Regular-osf-sc-ly1.tfm \
tex-LibertinusSans-Regular-osf-sc-ly1.vf \
tex-LibertinusSans-Regular-osf-sc-ot1--base.tfm \
tex-LibertinusSans-Regular-osf-sc-ot1.tfm \
tex-LibertinusSans-Regular-osf-sc-ot1.vf \
tex-LibertinusSans-Regular-osf-sc-t1--base.tfm \
tex-LibertinusSans-Regular-osf-sc-t1.tfm \
tex-LibertinusSans-Regular-osf-sc-t1.vf \
tex-LibertinusSans-Regular-osf-sc-t2a--base.tfm \
tex-LibertinusSans-Regular-osf-sc-t2a.tfm \
tex-LibertinusSans-Regular-osf-sc-t2a.vf \
tex-LibertinusSans-Regular-osf-sc-t2b--base.tfm \
tex-LibertinusSans-Regular-osf-sc-t2b.tfm \
tex-LibertinusSans-Regular-osf-sc-t2b.vf \
tex-LibertinusSans-Regular-osf-sc-t2c--base.tfm \
tex-LibertinusSans-Regular-osf-sc-t2c.tfm \
tex-LibertinusSans-Regular-osf-sc-t2c.vf \
tex-LibertinusSans-Regular-osf-t1--base.tfm \
tex-LibertinusSans-Regular-osf-t1.tfm \
tex-LibertinusSans-Regular-osf-t1.vf \
tex-LibertinusSans-Regular-osf-t2a.tfm \
tex-LibertinusSans-Regular-osf-t2b.tfm \
tex-LibertinusSans-Regular-osf-t2c.tfm \
tex-LibertinusSans-Regular-osf-ts1--base.tfm \
tex-LibertinusSans-Regular-osf-ts1.tfm \
tex-LibertinusSans-Regular-osf-ts1.vf \
tex-LibertinusSans-Regular-sup-lgr.tfm \
tex-LibertinusSans-Regular-sup-ly1.tfm \
tex-LibertinusSans-Regular-sup-ot1.tfm \
tex-LibertinusSans-Regular-sup-t1--base.tfm \
tex-LibertinusSans-Regular-sup-t1.tfm \
tex-LibertinusSans-Regular-sup-t1.vf \
tex-LibertinusSans-Regular-sup-t2a.tfm \
tex-LibertinusSans-Regular-sup-t2b.tfm \
tex-LibertinusSans-Regular-sup-t2c.tfm \
tex-LibertinusSans-Regular-tlf-lgr.tfm \
tex-LibertinusSans-Regular-tlf-ly1.tfm \
tex-LibertinusSans-Regular-tlf-ot1.tfm \
tex-LibertinusSans-Regular-tlf-sc-lgr.tfm \
tex-LibertinusSans-Regular-tlf-sc-ly1--base.tfm \
tex-LibertinusSans-Regular-tlf-sc-ly1.tfm \
tex-LibertinusSans-Regular-tlf-sc-ly1.vf \
tex-LibertinusSans-Regular-tlf-sc-ot1--base.tfm \
tex-LibertinusSans-Regular-tlf-sc-ot1.tfm \
tex-LibertinusSans-Regular-tlf-sc-ot1.vf \
tex-LibertinusSans-Regular-tlf-sc-t1--base.tfm \
tex-LibertinusSans-Regular-tlf-sc-t1.tfm \
tex-LibertinusSans-Regular-tlf-sc-t1.vf \
tex-LibertinusSans-Regular-tlf-sc-t2a--base.tfm \
tex-LibertinusSans-Regular-tlf-sc-t2a.tfm \
tex-LibertinusSans-Regular-tlf-sc-t2a.vf \
tex-LibertinusSans-Regular-tlf-sc-t2b--base.tfm \
tex-LibertinusSans-Regular-tlf-sc-t2b.tfm \
tex-LibertinusSans-Regular-tlf-sc-t2b.vf \
tex-LibertinusSans-Regular-tlf-sc-t2c--base.tfm \
tex-LibertinusSans-Regular-tlf-sc-t2c.tfm \
tex-LibertinusSans-Regular-tlf-sc-t2c.vf \
tex-LibertinusSans-Regular-tlf-t1--base.tfm \
tex-LibertinusSans-Regular-tlf-t1.tfm \
tex-LibertinusSans-Regular-tlf-t1.vf \
tex-LibertinusSans-Regular-tlf-t2a.tfm \
tex-LibertinusSans-Regular-tlf-t2b.tfm \
tex-LibertinusSans-Regular-tlf-t2c.tfm \
tex-LibertinusSans-Regular-tlf-ts1--base.tfm \
tex-LibertinusSans-Regular-tlf-ts1.tfm \
tex-LibertinusSans-Regular-tlf-ts1.vf \
tex-LibertinusSans-Regular-tosf-lgr.tfm \
tex-LibertinusSans-Regular-tosf-ly1.tfm \
tex-LibertinusSans-Regular-tosf-ot1.tfm \
tex-LibertinusSans-Regular-tosf-sc-lgr.tfm \
tex-LibertinusSans-Regular-tosf-sc-ly1--base.tfm \
tex-LibertinusSans-Regular-tosf-sc-ly1.tfm \
tex-LibertinusSans-Regular-tosf-sc-ly1.vf \
tex-LibertinusSans-Regular-tosf-sc-ot1--base.tfm \
tex-LibertinusSans-Regular-tosf-sc-ot1.tfm \
tex-LibertinusSans-Regular-tosf-sc-ot1.vf \
tex-LibertinusSans-Regular-tosf-sc-t1--base.tfm \
tex-LibertinusSans-Regular-tosf-sc-t1.tfm \
tex-LibertinusSans-Regular-tosf-sc-t1.vf \
tex-LibertinusSans-Regular-tosf-sc-t2a--base.tfm \
tex-LibertinusSans-Regular-tosf-sc-t2a.tfm \
tex-LibertinusSans-Regular-tosf-sc-t2a.vf \
tex-LibertinusSans-Regular-tosf-sc-t2b--base.tfm \
tex-LibertinusSans-Regular-tosf-sc-t2b.tfm \
tex-LibertinusSans-Regular-tosf-sc-t2b.vf \
tex-LibertinusSans-Regular-tosf-sc-t2c--base.tfm \
tex-LibertinusSans-Regular-tosf-sc-t2c.tfm \
tex-LibertinusSans-Regular-tosf-sc-t2c.vf \
tex-LibertinusSans-Regular-tosf-t1--base.tfm \
tex-LibertinusSans-Regular-tosf-t1.tfm \
tex-LibertinusSans-Regular-tosf-t1.vf \
tex-LibertinusSans-Regular-tosf-t2a.tfm \
tex-LibertinusSans-Regular-tosf-t2b.tfm \
tex-LibertinusSans-Regular-tosf-t2c.tfm \
tex-LibertinusSans-Regular-tosf-ts1--base.tfm \
tex-LibertinusSans-Regular-tosf-ts1.tfm \
tex-LibertinusSans-Regular-tosf-ts1.vf \
tex-LibertinusSerif-Bold-lf-lgr.tfm \
tex-LibertinusSerif-Bold-lf-ly1.tfm \
tex-LibertinusSerif-Bold-lf-ot1.tfm \
tex-LibertinusSerif-Bold-lf-sc-lgr.tfm \
tex-LibertinusSerif-Bold-lf-sc-ly1--base.tfm \
tex-LibertinusSerif-Bold-lf-sc-ly1.tfm \
tex-LibertinusSerif-Bold-lf-sc-ly1.vf \
tex-LibertinusSerif-Bold-lf-sc-ot1--base.tfm \
tex-LibertinusSerif-Bold-lf-sc-ot1.tfm \
tex-LibertinusSerif-Bold-lf-sc-ot1.vf \
tex-LibertinusSerif-Bold-lf-sc-t1--base.tfm \
tex-LibertinusSerif-Bold-lf-sc-t1.tfm \
tex-LibertinusSerif-Bold-lf-sc-t1.vf \
tex-LibertinusSerif-Bold-lf-sc-t2a--base.tfm \
tex-LibertinusSerif-Bold-lf-sc-t2a.tfm \
tex-LibertinusSerif-Bold-lf-sc-t2a.vf \
tex-LibertinusSerif-Bold-lf-sc-t2b--base.tfm \
tex-LibertinusSerif-Bold-lf-sc-t2b.tfm \
tex-LibertinusSerif-Bold-lf-sc-t2b.vf \
tex-LibertinusSerif-Bold-lf-sc-t2c--base.tfm \
tex-LibertinusSerif-Bold-lf-sc-t2c.tfm \
tex-LibertinusSerif-Bold-lf-sc-t2c.vf \
tex-LibertinusSerif-Bold-lf-t1--base.tfm \
tex-LibertinusSerif-Bold-lf-t1.tfm \
tex-LibertinusSerif-Bold-lf-t1.vf \
tex-LibertinusSerif-Bold-lf-t2a.tfm \
tex-LibertinusSerif-Bold-lf-t2b.tfm \
tex-LibertinusSerif-Bold-lf-t2c.tfm \
tex-LibertinusSerif-Bold-lf-ts1--base.tfm \
tex-LibertinusSerif-Bold-lf-ts1.tfm \
tex-LibertinusSerif-Bold-lf-ts1.vf \
tex-LibertinusSerif-Bold-osf-lgr.tfm \
tex-LibertinusSerif-Bold-osf-ly1.tfm \
tex-LibertinusSerif-Bold-osf-ot1.tfm \
tex-LibertinusSerif-Bold-osf-sc-lgr.tfm \
tex-LibertinusSerif-Bold-osf-sc-ly1--base.tfm \
tex-LibertinusSerif-Bold-osf-sc-ly1.tfm \
tex-LibertinusSerif-Bold-osf-sc-ly1.vf \
tex-LibertinusSerif-Bold-osf-sc-ot1--base.tfm \
tex-LibertinusSerif-Bold-osf-sc-ot1.tfm \
tex-LibertinusSerif-Bold-osf-sc-ot1.vf \
tex-LibertinusSerif-Bold-osf-sc-t1--base.tfm \
tex-LibertinusSerif-Bold-osf-sc-t1.tfm \
tex-LibertinusSerif-Bold-osf-sc-t1.vf \
tex-LibertinusSerif-Bold-osf-sc-t2a--base.tfm \
tex-LibertinusSerif-Bold-osf-sc-t2a.tfm \
tex-LibertinusSerif-Bold-osf-sc-t2a.vf \
tex-LibertinusSerif-Bold-osf-sc-t2b--base.tfm \
tex-LibertinusSerif-Bold-osf-sc-t2b.tfm \
tex-LibertinusSerif-Bold-osf-sc-t2b.vf \
tex-LibertinusSerif-Bold-osf-sc-t2c--base.tfm \
tex-LibertinusSerif-Bold-osf-sc-t2c.tfm \
tex-LibertinusSerif-Bold-osf-sc-t2c.vf \
tex-LibertinusSerif-Bold-osf-t1--base.tfm \
tex-LibertinusSerif-Bold-osf-t1.tfm \
tex-LibertinusSerif-Bold-osf-t1.vf \
tex-LibertinusSerif-Bold-osf-t2a.tfm \
tex-LibertinusSerif-Bold-osf-t2b.tfm \
tex-LibertinusSerif-Bold-osf-t2c.tfm \
tex-LibertinusSerif-Bold-osf-ts1--base.tfm \
tex-LibertinusSerif-Bold-osf-ts1.tfm \
tex-LibertinusSerif-Bold-osf-ts1.vf \
tex-LibertinusSerif-Bold-sup-lgr.tfm \
tex-LibertinusSerif-Bold-sup-ly1.tfm \
tex-LibertinusSerif-Bold-sup-ot1.tfm \
tex-LibertinusSerif-Bold-sup-t1--base.tfm \
tex-LibertinusSerif-Bold-sup-t1.tfm \
tex-LibertinusSerif-Bold-sup-t1.vf \
tex-LibertinusSerif-Bold-sup-t2a.tfm \
tex-LibertinusSerif-Bold-sup-t2b.tfm \
tex-LibertinusSerif-Bold-sup-t2c.tfm \
tex-LibertinusSerif-Bold-tlf-lgr.tfm \
tex-LibertinusSerif-Bold-tlf-ly1.tfm \
tex-LibertinusSerif-Bold-tlf-ot1.tfm \
tex-LibertinusSerif-Bold-tlf-sc-lgr.tfm \
tex-LibertinusSerif-Bold-tlf-sc-ly1--base.tfm \
tex-LibertinusSerif-Bold-tlf-sc-ly1.tfm \
tex-LibertinusSerif-Bold-tlf-sc-ly1.vf \
tex-LibertinusSerif-Bold-tlf-sc-ot1--base.tfm \
tex-LibertinusSerif-Bold-tlf-sc-ot1.tfm \
tex-LibertinusSerif-Bold-tlf-sc-ot1.vf \
tex-LibertinusSerif-Bold-tlf-sc-t1--base.tfm \
tex-LibertinusSerif-Bold-tlf-sc-t1.tfm \
tex-LibertinusSerif-Bold-tlf-sc-t1.vf \
tex-LibertinusSerif-Bold-tlf-sc-t2a--base.tfm \
tex-LibertinusSerif-Bold-tlf-sc-t2a.tfm \
tex-LibertinusSerif-Bold-tlf-sc-t2a.vf \
tex-LibertinusSerif-Bold-tlf-sc-t2b--base.tfm \
tex-LibertinusSerif-Bold-tlf-sc-t2b.tfm \
tex-LibertinusSerif-Bold-tlf-sc-t2b.vf \
tex-LibertinusSerif-Bold-tlf-sc-t2c--base.tfm \
tex-LibertinusSerif-Bold-tlf-sc-t2c.tfm \
tex-LibertinusSerif-Bold-tlf-sc-t2c.vf \
tex-LibertinusSerif-Bold-tlf-t1--base.tfm \
tex-LibertinusSerif-Bold-tlf-t1.tfm \
tex-LibertinusSerif-Bold-tlf-t1.vf \
tex-LibertinusSerif-Bold-tlf-t2a.tfm \
tex-LibertinusSerif-Bold-tlf-t2b.tfm \
tex-LibertinusSerif-Bold-tlf-t2c.tfm \
tex-LibertinusSerif-Bold-tlf-ts1--base.tfm \
tex-LibertinusSerif-Bold-tlf-ts1.tfm \
tex-LibertinusSerif-Bold-tlf-ts1.vf \
tex-LibertinusSerif-Bold-tosf-lgr.tfm \
tex-LibertinusSerif-Bold-tosf-ly1.tfm \
tex-LibertinusSerif-Bold-tosf-ot1.tfm \
tex-LibertinusSerif-Bold-tosf-sc-lgr.tfm \
tex-LibertinusSerif-Bold-tosf-sc-ly1--base.tfm \
tex-LibertinusSerif-Bold-tosf-sc-ly1.tfm \
tex-LibertinusSerif-Bold-tosf-sc-ly1.vf \
tex-LibertinusSerif-Bold-tosf-sc-ot1--base.tfm \
tex-LibertinusSerif-Bold-tosf-sc-ot1.tfm \
tex-LibertinusSerif-Bold-tosf-sc-ot1.vf \
tex-LibertinusSerif-Bold-tosf-sc-t1--base.tfm \
tex-LibertinusSerif-Bold-tosf-sc-t1.tfm \
tex-LibertinusSerif-Bold-tosf-sc-t1.vf \
tex-LibertinusSerif-Bold-tosf-sc-t2a--base.tfm \
tex-LibertinusSerif-Bold-tosf-sc-t2a.tfm \
tex-LibertinusSerif-Bold-tosf-sc-t2a.vf \
tex-LibertinusSerif-Bold-tosf-sc-t2b--base.tfm \
tex-LibertinusSerif-Bold-tosf-sc-t2b.tfm \
tex-LibertinusSerif-Bold-tosf-sc-t2b.vf \
tex-LibertinusSerif-Bold-tosf-sc-t2c--base.tfm \
tex-LibertinusSerif-Bold-tosf-sc-t2c.tfm \
tex-LibertinusSerif-Bold-tosf-sc-t2c.vf \
tex-LibertinusSerif-Bold-tosf-t1--base.tfm \
tex-LibertinusSerif-Bold-tosf-t1.tfm \
tex-LibertinusSerif-Bold-tosf-t1.vf \
tex-LibertinusSerif-Bold-tosf-t2a.tfm \
tex-LibertinusSerif-Bold-tosf-t2b.tfm \
tex-LibertinusSerif-Bold-tosf-t2c.tfm \
tex-LibertinusSerif-Bold-tosf-ts1--base.tfm \
tex-LibertinusSerif-Bold-tosf-ts1.tfm \
tex-LibertinusSerif-Bold-tosf-ts1.vf \
tex-LibertinusSerif-BoldItalic-lf-lgr.tfm \
tex-LibertinusSerif-BoldItalic-lf-ly1.tfm \
tex-LibertinusSerif-BoldItalic-lf-ot1.tfm \
tex-LibertinusSerif-BoldItalic-lf-sc-lgr.tfm \
tex-LibertinusSerif-BoldItalic-lf-sc-ly1--base.tfm \
tex-LibertinusSerif-BoldItalic-lf-sc-ly1.tfm \
tex-LibertinusSerif-BoldItalic-lf-sc-ly1.vf \
tex-LibertinusSerif-BoldItalic-lf-sc-ot1--base.tfm \
tex-LibertinusSerif-BoldItalic-lf-sc-ot1.tfm \
tex-LibertinusSerif-BoldItalic-lf-sc-ot1.vf \
tex-LibertinusSerif-BoldItalic-lf-sc-t1--base.tfm \
tex-LibertinusSerif-BoldItalic-lf-sc-t1.tfm \
tex-LibertinusSerif-BoldItalic-lf-sc-t1.vf \
tex-LibertinusSerif-BoldItalic-lf-sc-t2a--base.tfm \
tex-LibertinusSerif-BoldItalic-lf-sc-t2a.tfm \
tex-LibertinusSerif-BoldItalic-lf-sc-t2a.vf \
tex-LibertinusSerif-BoldItalic-lf-sc-t2b--base.tfm \
tex-LibertinusSerif-BoldItalic-lf-sc-t2b.tfm \
tex-LibertinusSerif-BoldItalic-lf-sc-t2b.vf \
tex-LibertinusSerif-BoldItalic-lf-sc-t2c--base.tfm \
tex-LibertinusSerif-BoldItalic-lf-sc-t2c.tfm \
tex-LibertinusSerif-BoldItalic-lf-sc-t2c.vf \
tex-LibertinusSerif-BoldItalic-lf-t1--base.tfm \
tex-LibertinusSerif-BoldItalic-lf-t1.tfm \
tex-LibertinusSerif-BoldItalic-lf-t1.vf \
tex-LibertinusSerif-BoldItalic-lf-t2a.tfm \
tex-LibertinusSerif-BoldItalic-lf-t2b.tfm \
tex-LibertinusSerif-BoldItalic-lf-t2c.tfm \
tex-LibertinusSerif-BoldItalic-lf-ts1--base.tfm \
tex-LibertinusSerif-BoldItalic-lf-ts1.tfm \
tex-LibertinusSerif-BoldItalic-lf-ts1.vf \
tex-LibertinusSerif-BoldItalic-osf-lgr.tfm \
tex-LibertinusSerif-BoldItalic-osf-ly1.tfm \
tex-LibertinusSerif-BoldItalic-osf-ot1.tfm \
tex-LibertinusSerif-BoldItalic-osf-sc-lgr.tfm \
tex-LibertinusSerif-BoldItalic-osf-sc-ly1--base.tfm \
tex-LibertinusSerif-BoldItalic-osf-sc-ly1.tfm \
tex-LibertinusSerif-BoldItalic-osf-sc-ly1.vf \
tex-LibertinusSerif-BoldItalic-osf-sc-ot1--base.tfm \
tex-LibertinusSerif-BoldItalic-osf-sc-ot1.tfm \
tex-LibertinusSerif-BoldItalic-osf-sc-ot1.vf \
tex-LibertinusSerif-BoldItalic-osf-sc-t1--base.tfm \
tex-LibertinusSerif-BoldItalic-osf-sc-t1.tfm \
tex-LibertinusSerif-BoldItalic-osf-sc-t1.vf \
tex-LibertinusSerif-BoldItalic-osf-sc-t2a--base.tfm \
tex-LibertinusSerif-BoldItalic-osf-sc-t2a.tfm \
tex-LibertinusSerif-BoldItalic-osf-sc-t2a.vf \
tex-LibertinusSerif-BoldItalic-osf-sc-t2b--base.tfm \
tex-LibertinusSerif-BoldItalic-osf-sc-t2b.tfm \
tex-LibertinusSerif-BoldItalic-osf-sc-t2b.vf \
tex-LibertinusSerif-BoldItalic-osf-sc-t2c--base.tfm \
tex-LibertinusSerif-BoldItalic-osf-sc-t2c.tfm \
tex-LibertinusSerif-BoldItalic-osf-sc-t2c.vf \
tex-LibertinusSerif-BoldItalic-osf-t1--base.tfm \
tex-LibertinusSerif-BoldItalic-osf-t1.tfm \
tex-LibertinusSerif-BoldItalic-osf-t1.vf \
tex-LibertinusSerif-BoldItalic-osf-t2a.tfm \
tex-LibertinusSerif-BoldItalic-osf-t2b.tfm \
tex-LibertinusSerif-BoldItalic-osf-t2c.tfm \
tex-LibertinusSerif-BoldItalic-osf-ts1--base.tfm \
tex-LibertinusSerif-BoldItalic-osf-ts1.tfm \
tex-LibertinusSerif-BoldItalic-osf-ts1.vf \
tex-LibertinusSerif-BoldItalic-sup-lgr.tfm \
tex-LibertinusSerif-BoldItalic-sup-ly1.tfm \
tex-LibertinusSerif-BoldItalic-sup-ot1.tfm \
tex-LibertinusSerif-BoldItalic-sup-t1--base.tfm \
tex-LibertinusSerif-BoldItalic-sup-t1.tfm \
tex-LibertinusSerif-BoldItalic-sup-t1.vf \
tex-LibertinusSerif-BoldItalic-sup-t2a.tfm \
tex-LibertinusSerif-BoldItalic-sup-t2b.tfm \
tex-LibertinusSerif-BoldItalic-sup-t2c.tfm \
tex-LibertinusSerif-BoldItalic-tlf-lgr.tfm \
tex-LibertinusSerif-BoldItalic-tlf-ly1.tfm \
tex-LibertinusSerif-BoldItalic-tlf-ot1.tfm \
tex-LibertinusSerif-BoldItalic-tlf-sc-lgr.tfm \
tex-LibertinusSerif-BoldItalic-tlf-sc-ly1--base.tfm \
tex-LibertinusSerif-BoldItalic-tlf-sc-ly1.tfm \
tex-LibertinusSerif-BoldItalic-tlf-sc-ly1.vf \
tex-LibertinusSerif-BoldItalic-tlf-sc-ot1--base.tfm \
tex-LibertinusSerif-BoldItalic-tlf-sc-ot1.tfm \
tex-LibertinusSerif-BoldItalic-tlf-sc-ot1.vf \
tex-LibertinusSerif-BoldItalic-tlf-sc-t1--base.tfm \
tex-LibertinusSerif-BoldItalic-tlf-sc-t1.tfm \
tex-LibertinusSerif-BoldItalic-tlf-sc-t1.vf \
tex-LibertinusSerif-BoldItalic-tlf-sc-t2a--base.tfm \
tex-LibertinusSerif-BoldItalic-tlf-sc-t2a.tfm \
tex-LibertinusSerif-BoldItalic-tlf-sc-t2a.vf \
tex-LibertinusSerif-BoldItalic-tlf-sc-t2b--base.tfm \
tex-LibertinusSerif-BoldItalic-tlf-sc-t2b.tfm \
tex-LibertinusSerif-BoldItalic-tlf-sc-t2b.vf \
tex-LibertinusSerif-BoldItalic-tlf-sc-t2c--base.tfm \
tex-LibertinusSerif-BoldItalic-tlf-sc-t2c.tfm \
tex-LibertinusSerif-BoldItalic-tlf-sc-t2c.vf \
tex-LibertinusSerif-BoldItalic-tlf-t1--base.tfm \
tex-LibertinusSerif-BoldItalic-tlf-t1.tfm \
tex-LibertinusSerif-BoldItalic-tlf-t1.vf \
tex-LibertinusSerif-BoldItalic-tlf-t2a.tfm \
tex-LibertinusSerif-BoldItalic-tlf-t2b.tfm \
tex-LibertinusSerif-BoldItalic-tlf-t2c.tfm \
tex-LibertinusSerif-BoldItalic-tlf-ts1--base.tfm \
tex-LibertinusSerif-BoldItalic-tlf-ts1.tfm \
tex-LibertinusSerif-BoldItalic-tlf-ts1.vf \
tex-LibertinusSerif-BoldItalic-tosf-lgr.tfm \
tex-LibertinusSerif-BoldItalic-tosf-ly1.tfm \
tex-LibertinusSerif-BoldItalic-tosf-ot1.tfm \
tex-LibertinusSerif-BoldItalic-tosf-sc-lgr.tfm \
tex-LibertinusSerif-BoldItalic-tosf-sc-ly1--base.tfm \
tex-LibertinusSerif-BoldItalic-tosf-sc-ly1.tfm \
tex-LibertinusSerif-BoldItalic-tosf-sc-ly1.vf \
tex-LibertinusSerif-BoldItalic-tosf-sc-ot1--base.tfm \
tex-LibertinusSerif-BoldItalic-tosf-sc-ot1.tfm \
tex-LibertinusSerif-BoldItalic-tosf-sc-ot1.vf \
tex-LibertinusSerif-BoldItalic-tosf-sc-t1--base.tfm \
tex-LibertinusSerif-BoldItalic-tosf-sc-t1.tfm \
tex-LibertinusSerif-BoldItalic-tosf-sc-t1.vf \
tex-LibertinusSerif-BoldItalic-tosf-sc-t2a--base.tfm \
tex-LibertinusSerif-BoldItalic-tosf-sc-t2a.tfm \
tex-LibertinusSerif-BoldItalic-tosf-sc-t2a.vf \
tex-LibertinusSerif-BoldItalic-tosf-sc-t2b--base.tfm \
tex-LibertinusSerif-BoldItalic-tosf-sc-t2b.tfm \
tex-LibertinusSerif-BoldItalic-tosf-sc-t2b.vf \
tex-LibertinusSerif-BoldItalic-tosf-sc-t2c--base.tfm \
tex-LibertinusSerif-BoldItalic-tosf-sc-t2c.tfm \
tex-LibertinusSerif-BoldItalic-tosf-sc-t2c.vf \
tex-LibertinusSerif-BoldItalic-tosf-t1--base.tfm \
tex-LibertinusSerif-BoldItalic-tosf-t1.tfm \
tex-LibertinusSerif-BoldItalic-tosf-t1.vf \
tex-LibertinusSerif-BoldItalic-tosf-t2a.tfm \
tex-LibertinusSerif-BoldItalic-tosf-t2b.tfm \
tex-LibertinusSerif-BoldItalic-tosf-t2c.tfm \
tex-LibertinusSerif-BoldItalic-tosf-ts1--base.tfm \
tex-LibertinusSerif-BoldItalic-tosf-ts1.tfm \
tex-LibertinusSerif-BoldItalic-tosf-ts1.vf \
tex-LibertinusSerif-Italic-lf-lgr.tfm \
tex-LibertinusSerif-Italic-lf-ly1.tfm \
tex-LibertinusSerif-Italic-lf-ot1.tfm \
tex-LibertinusSerif-Italic-lf-sc-lgr.tfm \
tex-LibertinusSerif-Italic-lf-sc-ly1--base.tfm \
tex-LibertinusSerif-Italic-lf-sc-ly1.tfm \
tex-LibertinusSerif-Italic-lf-sc-ly1.vf \
tex-LibertinusSerif-Italic-lf-sc-ot1--base.tfm \
tex-LibertinusSerif-Italic-lf-sc-ot1.tfm \
tex-LibertinusSerif-Italic-lf-sc-ot1.vf \
tex-LibertinusSerif-Italic-lf-sc-t1--base.tfm \
tex-LibertinusSerif-Italic-lf-sc-t1.tfm \
tex-LibertinusSerif-Italic-lf-sc-t1.vf \
tex-LibertinusSerif-Italic-lf-sc-t2a--base.tfm \
tex-LibertinusSerif-Italic-lf-sc-t2a.tfm \
tex-LibertinusSerif-Italic-lf-sc-t2a.vf \
tex-LibertinusSerif-Italic-lf-sc-t2b--base.tfm \
tex-LibertinusSerif-Italic-lf-sc-t2b.tfm \
tex-LibertinusSerif-Italic-lf-sc-t2b.vf \
tex-LibertinusSerif-Italic-lf-sc-t2c--base.tfm \
tex-LibertinusSerif-Italic-lf-sc-t2c.tfm \
tex-LibertinusSerif-Italic-lf-sc-t2c.vf \
tex-LibertinusSerif-Italic-lf-t1--base.tfm \
tex-LibertinusSerif-Italic-lf-t1.tfm \
tex-LibertinusSerif-Italic-lf-t1.vf \
tex-LibertinusSerif-Italic-lf-t2a.tfm \
tex-LibertinusSerif-Italic-lf-t2b.tfm \
tex-LibertinusSerif-Italic-lf-t2c.tfm \
tex-LibertinusSerif-Italic-lf-ts1--base.tfm \
tex-LibertinusSerif-Italic-lf-ts1.tfm \
tex-LibertinusSerif-Italic-lf-ts1.vf \
tex-LibertinusSerif-Italic-osf-lgr.tfm \
tex-LibertinusSerif-Italic-osf-ly1.tfm \
tex-LibertinusSerif-Italic-osf-ot1.tfm \
tex-LibertinusSerif-Italic-osf-sc-lgr.tfm \
tex-LibertinusSerif-Italic-osf-sc-ly1--base.tfm \
tex-LibertinusSerif-Italic-osf-sc-ly1.tfm \
tex-LibertinusSerif-Italic-osf-sc-ly1.vf \
tex-LibertinusSerif-Italic-osf-sc-ot1--base.tfm \
tex-LibertinusSerif-Italic-osf-sc-ot1.tfm \
tex-LibertinusSerif-Italic-osf-sc-ot1.vf \
tex-LibertinusSerif-Italic-osf-sc-t1--base.tfm \
tex-LibertinusSerif-Italic-osf-sc-t1.tfm \
tex-LibertinusSerif-Italic-osf-sc-t1.vf \
tex-LibertinusSerif-Italic-osf-sc-t2a--base.tfm \
tex-LibertinusSerif-Italic-osf-sc-t2a.tfm \
tex-LibertinusSerif-Italic-osf-sc-t2a.vf \
tex-LibertinusSerif-Italic-osf-sc-t2b--base.tfm \
tex-LibertinusSerif-Italic-osf-sc-t2b.tfm \
tex-LibertinusSerif-Italic-osf-sc-t2b.vf \
tex-LibertinusSerif-Italic-osf-sc-t2c--base.tfm \
tex-LibertinusSerif-Italic-osf-sc-t2c.tfm \
tex-LibertinusSerif-Italic-osf-sc-t2c.vf \
tex-LibertinusSerif-Italic-osf-t1--base.tfm \
tex-LibertinusSerif-Italic-osf-t1.tfm \
tex-LibertinusSerif-Italic-osf-t1.vf \
tex-LibertinusSerif-Italic-osf-t2a.tfm \
tex-LibertinusSerif-Italic-osf-t2b.tfm \
tex-LibertinusSerif-Italic-osf-t2c.tfm \
tex-LibertinusSerif-Italic-osf-ts1--base.tfm \
tex-LibertinusSerif-Italic-osf-ts1.tfm \
tex-LibertinusSerif-Italic-osf-ts1.vf \
tex-LibertinusSerif-Italic-sup-lgr.tfm \
tex-LibertinusSerif-Italic-sup-ly1.tfm \
tex-LibertinusSerif-Italic-sup-ot1.tfm \
tex-LibertinusSerif-Italic-sup-t1--base.tfm \
tex-LibertinusSerif-Italic-sup-t1.tfm \
tex-LibertinusSerif-Italic-sup-t1.vf \
tex-LibertinusSerif-Italic-sup-t2a.tfm \
tex-LibertinusSerif-Italic-sup-t2b.tfm \
tex-LibertinusSerif-Italic-sup-t2c.tfm \
tex-LibertinusSerif-Italic-tlf-lgr.tfm \
tex-LibertinusSerif-Italic-tlf-ly1.tfm \
tex-LibertinusSerif-Italic-tlf-ot1.tfm \
tex-LibertinusSerif-Italic-tlf-sc-lgr.tfm \
tex-LibertinusSerif-Italic-tlf-sc-ly1--base.tfm \
tex-LibertinusSerif-Italic-tlf-sc-ly1.tfm \
tex-LibertinusSerif-Italic-tlf-sc-ly1.vf \
tex-LibertinusSerif-Italic-tlf-sc-ot1--base.tfm \
tex-LibertinusSerif-Italic-tlf-sc-ot1.tfm \
tex-LibertinusSerif-Italic-tlf-sc-ot1.vf \
tex-LibertinusSerif-Italic-tlf-sc-t1--base.tfm \
tex-LibertinusSerif-Italic-tlf-sc-t1.tfm \
tex-LibertinusSerif-Italic-tlf-sc-t1.vf \
tex-LibertinusSerif-Italic-tlf-sc-t2a--base.tfm \
tex-LibertinusSerif-Italic-tlf-sc-t2a.tfm \
tex-LibertinusSerif-Italic-tlf-sc-t2a.vf \
tex-LibertinusSerif-Italic-tlf-sc-t2b--base.tfm \
tex-LibertinusSerif-Italic-tlf-sc-t2b.tfm \
tex-LibertinusSerif-Italic-tlf-sc-t2b.vf \
tex-LibertinusSerif-Italic-tlf-sc-t2c--base.tfm \
tex-LibertinusSerif-Italic-tlf-sc-t2c.tfm \
tex-LibertinusSerif-Italic-tlf-sc-t2c.vf \
tex-LibertinusSerif-Italic-tlf-t1--base.tfm \
tex-LibertinusSerif-Italic-tlf-t1.tfm \
tex-LibertinusSerif-Italic-tlf-t1.vf \
tex-LibertinusSerif-Italic-tlf-t2a.tfm \
tex-LibertinusSerif-Italic-tlf-t2b.tfm \
tex-LibertinusSerif-Italic-tlf-t2c.tfm \
tex-LibertinusSerif-Italic-tlf-ts1--base.tfm \
tex-LibertinusSerif-Italic-tlf-ts1.tfm \
tex-LibertinusSerif-Italic-tlf-ts1.vf \
tex-LibertinusSerif-Italic-tosf-lgr.tfm \
tex-LibertinusSerif-Italic-tosf-ly1.tfm \
tex-LibertinusSerif-Italic-tosf-ot1.tfm \
tex-LibertinusSerif-Italic-tosf-sc-lgr.tfm \
tex-LibertinusSerif-Italic-tosf-sc-ly1--base.tfm \
tex-LibertinusSerif-Italic-tosf-sc-ly1.tfm \
tex-LibertinusSerif-Italic-tosf-sc-ly1.vf \
tex-LibertinusSerif-Italic-tosf-sc-ot1--base.tfm \
tex-LibertinusSerif-Italic-tosf-sc-ot1.tfm \
tex-LibertinusSerif-Italic-tosf-sc-ot1.vf \
tex-LibertinusSerif-Italic-tosf-sc-t1--base.tfm \
tex-LibertinusSerif-Italic-tosf-sc-t1.tfm \
tex-LibertinusSerif-Italic-tosf-sc-t1.vf \
tex-LibertinusSerif-Italic-tosf-sc-t2a--base.tfm \
tex-LibertinusSerif-Italic-tosf-sc-t2a.tfm \
tex-LibertinusSerif-Italic-tosf-sc-t2a.vf \
tex-LibertinusSerif-Italic-tosf-sc-t2b--base.tfm \
tex-LibertinusSerif-Italic-tosf-sc-t2b.tfm \
tex-LibertinusSerif-Italic-tosf-sc-t2b.vf \
tex-LibertinusSerif-Italic-tosf-sc-t2c--base.tfm \
tex-LibertinusSerif-Italic-tosf-sc-t2c.tfm \
tex-LibertinusSerif-Italic-tosf-sc-t2c.vf \
tex-LibertinusSerif-Italic-tosf-t1--base.tfm \
tex-LibertinusSerif-Italic-tosf-t1.tfm \
tex-LibertinusSerif-Italic-tosf-t1.vf \
tex-LibertinusSerif-Italic-tosf-t2a.tfm \
tex-LibertinusSerif-Italic-tosf-t2b.tfm \
tex-LibertinusSerif-Italic-tosf-t2c.tfm \
tex-LibertinusSerif-Italic-tosf-ts1--base.tfm \
tex-LibertinusSerif-Italic-tosf-ts1.tfm \
tex-LibertinusSerif-Italic-tosf-ts1.vf \
tex-LibertinusSerif-Regular-lf-lgr.tfm \
tex-LibertinusSerif-Regular-lf-ly1.tfm \
tex-LibertinusSerif-Regular-lf-ot1.tfm \
tex-LibertinusSerif-Regular-lf-sc-lgr.tfm \
tex-LibertinusSerif-Regular-lf-sc-ly1--base.tfm \
tex-LibertinusSerif-Regular-lf-sc-ly1.tfm \
tex-LibertinusSerif-Regular-lf-sc-ly1.vf \
tex-LibertinusSerif-Regular-lf-sc-ot1--base.tfm \
tex-LibertinusSerif-Regular-lf-sc-ot1.tfm \
tex-LibertinusSerif-Regular-lf-sc-ot1.vf \
tex-LibertinusSerif-Regular-lf-sc-t1--base.tfm \
tex-LibertinusSerif-Regular-lf-sc-t1.tfm \
tex-LibertinusSerif-Regular-lf-sc-t1.vf \
tex-LibertinusSerif-Regular-lf-sc-t2a--base.tfm \
tex-LibertinusSerif-Regular-lf-sc-t2a.tfm \
tex-LibertinusSerif-Regular-lf-sc-t2a.vf \
tex-LibertinusSerif-Regular-lf-sc-t2b--base.tfm \
tex-LibertinusSerif-Regular-lf-sc-t2b.tfm \
tex-LibertinusSerif-Regular-lf-sc-t2b.vf \
tex-LibertinusSerif-Regular-lf-sc-t2c--base.tfm \
tex-LibertinusSerif-Regular-lf-sc-t2c.tfm \
tex-LibertinusSerif-Regular-lf-sc-t2c.vf \
tex-LibertinusSerif-Regular-lf-t1--base.tfm \
tex-LibertinusSerif-Regular-lf-t1.tfm \
tex-LibertinusSerif-Regular-lf-t1.vf \
tex-LibertinusSerif-Regular-lf-t2a.tfm \
tex-LibertinusSerif-Regular-lf-t2b.tfm \
tex-LibertinusSerif-Regular-lf-t2c.tfm \
tex-LibertinusSerif-Regular-lf-ts1--base.tfm \
tex-LibertinusSerif-Regular-lf-ts1.tfm \
tex-LibertinusSerif-Regular-lf-ts1.vf \
tex-LibertinusSerif-Regular-osf-lgr.tfm \
tex-LibertinusSerif-Regular-osf-ly1.tfm \
tex-LibertinusSerif-Regular-osf-ot1.tfm \
tex-LibertinusSerif-Regular-osf-sc-lgr.tfm \
tex-LibertinusSerif-Regular-osf-sc-ly1--base.tfm \
tex-LibertinusSerif-Regular-osf-sc-ly1.tfm \
tex-LibertinusSerif-Regular-osf-sc-ly1.vf \
tex-LibertinusSerif-Regular-osf-sc-ot1--base.tfm \
tex-LibertinusSerif-Regular-osf-sc-ot1.tfm \
tex-LibertinusSerif-Regular-osf-sc-ot1.vf \
tex-LibertinusSerif-Regular-osf-sc-t1--base.tfm \
tex-LibertinusSerif-Regular-osf-sc-t1.tfm \
tex-LibertinusSerif-Regular-osf-sc-t1.vf \
tex-LibertinusSerif-Regular-osf-sc-t2a--base.tfm \
tex-LibertinusSerif-Regular-osf-sc-t2a.tfm \
tex-LibertinusSerif-Regular-osf-sc-t2a.vf \
tex-LibertinusSerif-Regular-osf-sc-t2b--base.tfm \
tex-LibertinusSerif-Regular-osf-sc-t2b.tfm \
tex-LibertinusSerif-Regular-osf-sc-t2b.vf \
tex-LibertinusSerif-Regular-osf-sc-t2c--base.tfm \
tex-LibertinusSerif-Regular-osf-sc-t2c.tfm \
tex-LibertinusSerif-Regular-osf-sc-t2c.vf \
tex-LibertinusSerif-Regular-osf-t1--base.tfm \
tex-LibertinusSerif-Regular-osf-t1.tfm \
tex-LibertinusSerif-Regular-osf-t1.vf \
tex-LibertinusSerif-Regular-osf-t2a.tfm \
tex-LibertinusSerif-Regular-osf-t2b.tfm \
tex-LibertinusSerif-Regular-osf-t2c.tfm \
tex-LibertinusSerif-Regular-osf-ts1--base.tfm \
tex-LibertinusSerif-Regular-osf-ts1.tfm \
tex-LibertinusSerif-Regular-osf-ts1.vf \
tex-LibertinusSerif-Regular-sup-lgr.tfm \
tex-LibertinusSerif-Regular-sup-ly1.tfm \
tex-LibertinusSerif-Regular-sup-ot1.tfm \
tex-LibertinusSerif-Regular-sup-t1--base.tfm \
tex-LibertinusSerif-Regular-sup-t1.tfm \
tex-LibertinusSerif-Regular-sup-t1.vf \
tex-LibertinusSerif-Regular-sup-t2a.tfm \
tex-LibertinusSerif-Regular-sup-t2b.tfm \
tex-LibertinusSerif-Regular-sup-t2c.tfm \
tex-LibertinusSerif-Regular-tlf-lgr.tfm \
tex-LibertinusSerif-Regular-tlf-ly1.tfm \
tex-LibertinusSerif-Regular-tlf-ot1.tfm \
tex-LibertinusSerif-Regular-tlf-sc-lgr.tfm \
tex-LibertinusSerif-Regular-tlf-sc-ly1--base.tfm \
tex-LibertinusSerif-Regular-tlf-sc-ly1.tfm \
tex-LibertinusSerif-Regular-tlf-sc-ly1.vf \
tex-LibertinusSerif-Regular-tlf-sc-ot1--base.tfm \
tex-LibertinusSerif-Regular-tlf-sc-ot1.tfm \
tex-LibertinusSerif-Regular-tlf-sc-ot1.vf \
tex-LibertinusSerif-Regular-tlf-sc-t1--base.tfm \
tex-LibertinusSerif-Regular-tlf-sc-t1.tfm \
tex-LibertinusSerif-Regular-tlf-sc-t1.vf \
tex-LibertinusSerif-Regular-tlf-sc-t2a--base.tfm \
tex-LibertinusSerif-Regular-tlf-sc-t2a.tfm \
tex-LibertinusSerif-Regular-tlf-sc-t2a.vf \
tex-LibertinusSerif-Regular-tlf-sc-t2b--base.tfm \
tex-LibertinusSerif-Regular-tlf-sc-t2b.tfm \
tex-LibertinusSerif-Regular-tlf-sc-t2b.vf \
tex-LibertinusSerif-Regular-tlf-sc-t2c--base.tfm \
tex-LibertinusSerif-Regular-tlf-sc-t2c.tfm \
tex-LibertinusSerif-Regular-tlf-sc-t2c.vf \
tex-LibertinusSerif-Regular-tlf-t1--base.tfm \
tex-LibertinusSerif-Regular-tlf-t1.tfm \
tex-LibertinusSerif-Regular-tlf-t1.vf \
tex-LibertinusSerif-Regular-tlf-t2a.tfm \
tex-LibertinusSerif-Regular-tlf-t2b.tfm \
tex-LibertinusSerif-Regular-tlf-t2c.tfm \
tex-LibertinusSerif-Regular-tlf-ts1--base.tfm \
tex-LibertinusSerif-Regular-tlf-ts1.tfm \
tex-LibertinusSerif-Regular-tlf-ts1.vf \
tex-LibertinusSerif-Regular-tosf-lgr.tfm \
tex-LibertinusSerif-Regular-tosf-ly1.tfm \
tex-LibertinusSerif-Regular-tosf-ot1.tfm \
tex-LibertinusSerif-Regular-tosf-sc-lgr.tfm \
tex-LibertinusSerif-Regular-tosf-sc-ly1--base.tfm \
tex-LibertinusSerif-Regular-tosf-sc-ly1.tfm \
tex-LibertinusSerif-Regular-tosf-sc-ly1.vf \
tex-LibertinusSerif-Regular-tosf-sc-ot1--base.tfm \
tex-LibertinusSerif-Regular-tosf-sc-ot1.tfm \
tex-LibertinusSerif-Regular-tosf-sc-ot1.vf \
tex-LibertinusSerif-Regular-tosf-sc-t1--base.tfm \
tex-LibertinusSerif-Regular-tosf-sc-t1.tfm \
tex-LibertinusSerif-Regular-tosf-sc-t1.vf \
tex-LibertinusSerif-Regular-tosf-sc-t2a--base.tfm \
tex-LibertinusSerif-Regular-tosf-sc-t2a.tfm \
tex-LibertinusSerif-Regular-tosf-sc-t2a.vf \
tex-LibertinusSerif-Regular-tosf-sc-t2b--base.tfm \
tex-LibertinusSerif-Regular-tosf-sc-t2b.tfm \
tex-LibertinusSerif-Regular-tosf-sc-t2b.vf \
tex-LibertinusSerif-Regular-tosf-sc-t2c--base.tfm \
tex-LibertinusSerif-Regular-tosf-sc-t2c.tfm \
tex-LibertinusSerif-Regular-tosf-sc-t2c.vf \
tex-LibertinusSerif-Regular-tosf-t1--base.tfm \
tex-LibertinusSerif-Regular-tosf-t1.tfm \
tex-LibertinusSerif-Regular-tosf-t1.vf \
tex-LibertinusSerif-Regular-tosf-t2a.tfm \
tex-LibertinusSerif-Regular-tosf-t2b.tfm \
tex-LibertinusSerif-Regular-tosf-t2c.tfm \
tex-LibertinusSerif-Regular-tosf-ts1--base.tfm \
tex-LibertinusSerif-Regular-tosf-ts1.tfm \
tex-LibertinusSerif-Regular-tosf-ts1.vf \
tex-LibertinusSerif-Semibold-lf-lgr.tfm \
tex-LibertinusSerif-Semibold-lf-ly1.tfm \
tex-LibertinusSerif-Semibold-lf-ot1.tfm \
tex-LibertinusSerif-Semibold-lf-sc-lgr.tfm \
tex-LibertinusSerif-Semibold-lf-sc-ly1--base.tfm \
tex-LibertinusSerif-Semibold-lf-sc-ly1.tfm \
tex-LibertinusSerif-Semibold-lf-sc-ly1.vf \
tex-LibertinusSerif-Semibold-lf-sc-ot1--base.tfm \
tex-LibertinusSerif-Semibold-lf-sc-ot1.tfm \
tex-LibertinusSerif-Semibold-lf-sc-ot1.vf \
tex-LibertinusSerif-Semibold-lf-sc-t1--base.tfm \
tex-LibertinusSerif-Semibold-lf-sc-t1.tfm \
tex-LibertinusSerif-Semibold-lf-sc-t1.vf \
tex-LibertinusSerif-Semibold-lf-sc-t2a--base.tfm \
tex-LibertinusSerif-Semibold-lf-sc-t2a.tfm \
tex-LibertinusSerif-Semibold-lf-sc-t2a.vf \
tex-LibertinusSerif-Semibold-lf-sc-t2b--base.tfm \
tex-LibertinusSerif-Semibold-lf-sc-t2b.tfm \
tex-LibertinusSerif-Semibold-lf-sc-t2b.vf \
tex-LibertinusSerif-Semibold-lf-sc-t2c--base.tfm \
tex-LibertinusSerif-Semibold-lf-sc-t2c.tfm \
tex-LibertinusSerif-Semibold-lf-sc-t2c.vf \
tex-LibertinusSerif-Semibold-lf-t1--base.tfm \
tex-LibertinusSerif-Semibold-lf-t1.tfm \
tex-LibertinusSerif-Semibold-lf-t1.vf \
tex-LibertinusSerif-Semibold-lf-t2a.tfm \
tex-LibertinusSerif-Semibold-lf-t2b.tfm \
tex-LibertinusSerif-Semibold-lf-t2c.tfm \
tex-LibertinusSerif-Semibold-lf-ts1--base.tfm \
tex-LibertinusSerif-Semibold-lf-ts1.tfm \
tex-LibertinusSerif-Semibold-lf-ts1.vf \
tex-LibertinusSerif-Semibold-osf-lgr.tfm \
tex-LibertinusSerif-Semibold-osf-ly1.tfm \
tex-LibertinusSerif-Semibold-osf-ot1.tfm \
tex-LibertinusSerif-Semibold-osf-sc-lgr.tfm \
tex-LibertinusSerif-Semibold-osf-sc-ly1--base.tfm \
tex-LibertinusSerif-Semibold-osf-sc-ly1.tfm \
tex-LibertinusSerif-Semibold-osf-sc-ly1.vf \
tex-LibertinusSerif-Semibold-osf-sc-ot1--base.tfm \
tex-LibertinusSerif-Semibold-osf-sc-ot1.tfm \
tex-LibertinusSerif-Semibold-osf-sc-ot1.vf \
tex-LibertinusSerif-Semibold-osf-sc-t1--base.tfm \
tex-LibertinusSerif-Semibold-osf-sc-t1.tfm \
tex-LibertinusSerif-Semibold-osf-sc-t1.vf \
tex-LibertinusSerif-Semibold-osf-sc-t2a--base.tfm \
tex-LibertinusSerif-Semibold-osf-sc-t2a.tfm \
tex-LibertinusSerif-Semibold-osf-sc-t2a.vf \
tex-LibertinusSerif-Semibold-osf-sc-t2b--base.tfm \
tex-LibertinusSerif-Semibold-osf-sc-t2b.tfm \
tex-LibertinusSerif-Semibold-osf-sc-t2b.vf \
tex-LibertinusSerif-Semibold-osf-sc-t2c--base.tfm \
tex-LibertinusSerif-Semibold-osf-sc-t2c.tfm \
tex-LibertinusSerif-Semibold-osf-sc-t2c.vf \
tex-LibertinusSerif-Semibold-osf-t1--base.tfm \
tex-LibertinusSerif-Semibold-osf-t1.tfm \
tex-LibertinusSerif-Semibold-osf-t1.vf \
tex-LibertinusSerif-Semibold-osf-t2a.tfm \
tex-LibertinusSerif-Semibold-osf-t2b.tfm \
tex-LibertinusSerif-Semibold-osf-t2c.tfm \
tex-LibertinusSerif-Semibold-osf-ts1--base.tfm \
tex-LibertinusSerif-Semibold-osf-ts1.tfm \
tex-LibertinusSerif-Semibold-osf-ts1.vf \
tex-LibertinusSerif-Semibold-sup-lgr.tfm \
tex-LibertinusSerif-Semibold-sup-ly1.tfm \
tex-LibertinusSerif-Semibold-sup-ot1.tfm \
tex-LibertinusSerif-Semibold-sup-t1--base.tfm \
tex-LibertinusSerif-Semibold-sup-t1.tfm \
tex-LibertinusSerif-Semibold-sup-t1.vf \
tex-LibertinusSerif-Semibold-sup-t2a.tfm \
tex-LibertinusSerif-Semibold-sup-t2b.tfm \
tex-LibertinusSerif-Semibold-sup-t2c.tfm \
tex-LibertinusSerif-Semibold-tlf-lgr.tfm \
tex-LibertinusSerif-Semibold-tlf-ly1.tfm \
tex-LibertinusSerif-Semibold-tlf-ot1.tfm \
tex-LibertinusSerif-Semibold-tlf-sc-lgr.tfm \
tex-LibertinusSerif-Semibold-tlf-sc-ly1--base.tfm \
tex-LibertinusSerif-Semibold-tlf-sc-ly1.tfm \
tex-LibertinusSerif-Semibold-tlf-sc-ly1.vf \
tex-LibertinusSerif-Semibold-tlf-sc-ot1--base.tfm \
tex-LibertinusSerif-Semibold-tlf-sc-ot1.tfm \
tex-LibertinusSerif-Semibold-tlf-sc-ot1.vf \
tex-LibertinusSerif-Semibold-tlf-sc-t1--base.tfm \
tex-LibertinusSerif-Semibold-tlf-sc-t1.tfm \
tex-LibertinusSerif-Semibold-tlf-sc-t1.vf \
tex-LibertinusSerif-Semibold-tlf-sc-t2a--base.tfm \
tex-LibertinusSerif-Semibold-tlf-sc-t2a.tfm \
tex-LibertinusSerif-Semibold-tlf-sc-t2a.vf \
tex-LibertinusSerif-Semibold-tlf-sc-t2b--base.tfm \
tex-LibertinusSerif-Semibold-tlf-sc-t2b.tfm \
tex-LibertinusSerif-Semibold-tlf-sc-t2b.vf \
tex-LibertinusSerif-Semibold-tlf-sc-t2c--base.tfm \
tex-LibertinusSerif-Semibold-tlf-sc-t2c.tfm \
tex-LibertinusSerif-Semibold-tlf-sc-t2c.vf \
tex-LibertinusSerif-Semibold-tlf-t1--base.tfm \
tex-LibertinusSerif-Semibold-tlf-t1.tfm \
tex-LibertinusSerif-Semibold-tlf-t1.vf \
tex-LibertinusSerif-Semibold-tlf-t2a.tfm \
tex-LibertinusSerif-Semibold-tlf-t2b.tfm \
tex-LibertinusSerif-Semibold-tlf-t2c.tfm \
tex-LibertinusSerif-Semibold-tlf-ts1--base.tfm \
tex-LibertinusSerif-Semibold-tlf-ts1.tfm \
tex-LibertinusSerif-Semibold-tlf-ts1.vf \
tex-LibertinusSerif-Semibold-tosf-lgr.tfm \
tex-LibertinusSerif-Semibold-tosf-ly1.tfm \
tex-LibertinusSerif-Semibold-tosf-ot1.tfm \
tex-LibertinusSerif-Semibold-tosf-sc-lgr.tfm \
tex-LibertinusSerif-Semibold-tosf-sc-ly1--base.tfm \
tex-LibertinusSerif-Semibold-tosf-sc-ly1.tfm \
tex-LibertinusSerif-Semibold-tosf-sc-ly1.vf \
tex-LibertinusSerif-Semibold-tosf-sc-ot1--base.tfm \
tex-LibertinusSerif-Semibold-tosf-sc-ot1.tfm \
tex-LibertinusSerif-Semibold-tosf-sc-ot1.vf \
tex-LibertinusSerif-Semibold-tosf-sc-t1--base.tfm \
tex-LibertinusSerif-Semibold-tosf-sc-t1.tfm \
tex-LibertinusSerif-Semibold-tosf-sc-t1.vf \
tex-LibertinusSerif-Semibold-tosf-sc-t2a--base.tfm \
tex-LibertinusSerif-Semibold-tosf-sc-t2a.tfm \
tex-LibertinusSerif-Semibold-tosf-sc-t2a.vf \
tex-LibertinusSerif-Semibold-tosf-sc-t2b--base.tfm \
tex-LibertinusSerif-Semibold-tosf-sc-t2b.tfm \
tex-LibertinusSerif-Semibold-tosf-sc-t2b.vf \
tex-LibertinusSerif-Semibold-tosf-sc-t2c--base.tfm \
tex-LibertinusSerif-Semibold-tosf-sc-t2c.tfm \
tex-LibertinusSerif-Semibold-tosf-sc-t2c.vf \
tex-LibertinusSerif-Semibold-tosf-t1--base.tfm \
tex-LibertinusSerif-Semibold-tosf-t1.tfm \
tex-LibertinusSerif-Semibold-tosf-t1.vf \
tex-LibertinusSerif-Semibold-tosf-t2a.tfm \
tex-LibertinusSerif-Semibold-tosf-t2b.tfm \
tex-LibertinusSerif-Semibold-tosf-t2c.tfm \
tex-LibertinusSerif-Semibold-tosf-ts1--base.tfm \
tex-LibertinusSerif-Semibold-tosf-ts1.tfm \
tex-LibertinusSerif-Semibold-tosf-ts1.vf \
tex-LibertinusSerif-SemiboldItalic-lf-lgr.tfm \
tex-LibertinusSerif-SemiboldItalic-lf-ly1--base.tfm \
tex-LibertinusSerif-SemiboldItalic-lf-ly1.tfm \
tex-LibertinusSerif-SemiboldItalic-lf-ly1.vf \
tex-LibertinusSerif-SemiboldItalic-lf-ot1--base.tfm \
tex-LibertinusSerif-SemiboldItalic-lf-ot1.tfm \
tex-LibertinusSerif-SemiboldItalic-lf-ot1.vf \
tex-LibertinusSerif-SemiboldItalic-lf-sc-lgr.tfm \
tex-LibertinusSerif-SemiboldItalic-lf-sc-ly1--base.tfm \
tex-LibertinusSerif-SemiboldItalic-lf-sc-ly1.tfm \
tex-LibertinusSerif-SemiboldItalic-lf-sc-ly1.vf \
tex-LibertinusSerif-SemiboldItalic-lf-sc-ot1--base.tfm \
tex-LibertinusSerif-SemiboldItalic-lf-sc-ot1.tfm \
tex-LibertinusSerif-SemiboldItalic-lf-sc-ot1.vf \
tex-LibertinusSerif-SemiboldItalic-lf-sc-t1--base.tfm \
tex-LibertinusSerif-SemiboldItalic-lf-sc-t1.tfm \
tex-LibertinusSerif-SemiboldItalic-lf-sc-t1.vf \
tex-LibertinusSerif-SemiboldItalic-lf-sc-t2a--base.tfm \
tex-LibertinusSerif-SemiboldItalic-lf-sc-t2a.tfm \
tex-LibertinusSerif-SemiboldItalic-lf-sc-t2a.vf \
tex-LibertinusSerif-SemiboldItalic-lf-sc-t2b--base.tfm \
tex-LibertinusSerif-SemiboldItalic-lf-sc-t2b.tfm \
tex-LibertinusSerif-SemiboldItalic-lf-sc-t2b.vf \
tex-LibertinusSerif-SemiboldItalic-lf-sc-t2c--base.tfm \
tex-LibertinusSerif-SemiboldItalic-lf-sc-t2c.tfm \
tex-LibertinusSerif-SemiboldItalic-lf-sc-t2c.vf \
tex-LibertinusSerif-SemiboldItalic-lf-t1--base.tfm \
tex-LibertinusSerif-SemiboldItalic-lf-t1.tfm \
tex-LibertinusSerif-SemiboldItalic-lf-t1.vf \
tex-LibertinusSerif-SemiboldItalic-lf-t2a--base.tfm \
tex-LibertinusSerif-SemiboldItalic-lf-t2a.tfm \
tex-LibertinusSerif-SemiboldItalic-lf-t2a.vf \
tex-LibertinusSerif-SemiboldItalic-lf-t2b--base.tfm \
tex-LibertinusSerif-SemiboldItalic-lf-t2b.tfm \
tex-LibertinusSerif-SemiboldItalic-lf-t2b.vf \
tex-LibertinusSerif-SemiboldItalic-lf-t2c--base.tfm \
tex-LibertinusSerif-SemiboldItalic-lf-t2c.tfm \
tex-LibertinusSerif-SemiboldItalic-lf-t2c.vf \
tex-LibertinusSerif-SemiboldItalic-lf-ts1--base.tfm \
tex-LibertinusSerif-SemiboldItalic-lf-ts1.tfm \
tex-LibertinusSerif-SemiboldItalic-lf-ts1.vf \
tex-LibertinusSerif-SemiboldItalic-osf-lgr.tfm \
tex-LibertinusSerif-SemiboldItalic-osf-ly1--base.tfm \
tex-LibertinusSerif-SemiboldItalic-osf-ly1.tfm \
tex-LibertinusSerif-SemiboldItalic-osf-ly1.vf \
tex-LibertinusSerif-SemiboldItalic-osf-ot1--base.tfm \
tex-LibertinusSerif-SemiboldItalic-osf-ot1.tfm \
tex-LibertinusSerif-SemiboldItalic-osf-ot1.vf \
tex-LibertinusSerif-SemiboldItalic-osf-sc-lgr.tfm \
tex-LibertinusSerif-SemiboldItalic-osf-sc-ly1--base.tfm \
tex-LibertinusSerif-SemiboldItalic-osf-sc-ly1.tfm \
tex-LibertinusSerif-SemiboldItalic-osf-sc-ly1.vf \
tex-LibertinusSerif-SemiboldItalic-osf-sc-ot1--base.tfm \
tex-LibertinusSerif-SemiboldItalic-osf-sc-ot1.tfm \
tex-LibertinusSerif-SemiboldItalic-osf-sc-ot1.vf \
tex-LibertinusSerif-SemiboldItalic-osf-sc-t1--base.tfm \
tex-LibertinusSerif-SemiboldItalic-osf-sc-t1.tfm \
tex-LibertinusSerif-SemiboldItalic-osf-sc-t1.vf \
tex-LibertinusSerif-SemiboldItalic-osf-sc-t2a--base.tfm \
tex-LibertinusSerif-SemiboldItalic-osf-sc-t2a.tfm \
tex-LibertinusSerif-SemiboldItalic-osf-sc-t2a.vf \
tex-LibertinusSerif-SemiboldItalic-osf-sc-t2b--base.tfm \
tex-LibertinusSerif-SemiboldItalic-osf-sc-t2b.tfm \
tex-LibertinusSerif-SemiboldItalic-osf-sc-t2b.vf \
tex-LibertinusSerif-SemiboldItalic-osf-sc-t2c--base.tfm \
tex-LibertinusSerif-SemiboldItalic-osf-sc-t2c.tfm \
tex-LibertinusSerif-SemiboldItalic-osf-sc-t2c.vf \
tex-LibertinusSerif-SemiboldItalic-osf-t1--base.tfm \
tex-LibertinusSerif-SemiboldItalic-osf-t1.tfm \
tex-LibertinusSerif-SemiboldItalic-osf-t1.vf \
tex-LibertinusSerif-SemiboldItalic-osf-t2a--base.tfm \
tex-LibertinusSerif-SemiboldItalic-osf-t2a.tfm \
tex-LibertinusSerif-SemiboldItalic-osf-t2a.vf \
tex-LibertinusSerif-SemiboldItalic-osf-t2b--base.tfm \
tex-LibertinusSerif-SemiboldItalic-osf-t2b.tfm \
tex-LibertinusSerif-SemiboldItalic-osf-t2b.vf \
tex-LibertinusSerif-SemiboldItalic-osf-t2c--base.tfm \
tex-LibertinusSerif-SemiboldItalic-osf-t2c.tfm \
tex-LibertinusSerif-SemiboldItalic-osf-t2c.vf \
tex-LibertinusSerif-SemiboldItalic-osf-ts1--base.tfm \
tex-LibertinusSerif-SemiboldItalic-osf-ts1.tfm \
tex-LibertinusSerif-SemiboldItalic-osf-ts1.vf \
tex-LibertinusSerif-SemiboldItalic-sup-lgr.tfm \
tex-LibertinusSerif-SemiboldItalic-sup-ly1.tfm \
tex-LibertinusSerif-SemiboldItalic-sup-ot1.tfm \
tex-LibertinusSerif-SemiboldItalic-sup-t1--base.tfm \
tex-LibertinusSerif-SemiboldItalic-sup-t1.tfm \
tex-LibertinusSerif-SemiboldItalic-sup-t1.vf \
tex-LibertinusSerif-SemiboldItalic-sup-t2a.tfm \
tex-LibertinusSerif-SemiboldItalic-sup-t2b.tfm \
tex-LibertinusSerif-SemiboldItalic-sup-t2c.tfm \
tex-LibertinusSerif-SemiboldItalic-tlf-lgr.tfm \
tex-LibertinusSerif-SemiboldItalic-tlf-ly1--base.tfm \
tex-LibertinusSerif-SemiboldItalic-tlf-ly1.tfm \
tex-LibertinusSerif-SemiboldItalic-tlf-ly1.vf \
tex-LibertinusSerif-SemiboldItalic-tlf-ot1--base.tfm \
tex-LibertinusSerif-SemiboldItalic-tlf-ot1.tfm \
tex-LibertinusSerif-SemiboldItalic-tlf-ot1.vf \
tex-LibertinusSerif-SemiboldItalic-tlf-sc-lgr.tfm \
tex-LibertinusSerif-SemiboldItalic-tlf-sc-ly1--base.tfm \
tex-LibertinusSerif-SemiboldItalic-tlf-sc-ly1.tfm \
tex-LibertinusSerif-SemiboldItalic-tlf-sc-ly1.vf \
tex-LibertinusSerif-SemiboldItalic-tlf-sc-ot1--base.tfm \
tex-LibertinusSerif-SemiboldItalic-tlf-sc-ot1.tfm \
tex-LibertinusSerif-SemiboldItalic-tlf-sc-ot1.vf \
tex-LibertinusSerif-SemiboldItalic-tlf-sc-t1--base.tfm \
tex-LibertinusSerif-SemiboldItalic-tlf-sc-t1.tfm \
tex-LibertinusSerif-SemiboldItalic-tlf-sc-t1.vf \
tex-LibertinusSerif-SemiboldItalic-tlf-sc-t2a--base.tfm \
tex-LibertinusSerif-SemiboldItalic-tlf-sc-t2a.tfm \
tex-LibertinusSerif-SemiboldItalic-tlf-sc-t2a.vf \
tex-LibertinusSerif-SemiboldItalic-tlf-sc-t2b--base.tfm \
tex-LibertinusSerif-SemiboldItalic-tlf-sc-t2b.tfm \
tex-LibertinusSerif-SemiboldItalic-tlf-sc-t2b.vf \
tex-LibertinusSerif-SemiboldItalic-tlf-sc-t2c--base.tfm \
tex-LibertinusSerif-SemiboldItalic-tlf-sc-t2c.tfm \
tex-LibertinusSerif-SemiboldItalic-tlf-sc-t2c.vf \
tex-LibertinusSerif-SemiboldItalic-tlf-t1--base.tfm \
tex-LibertinusSerif-SemiboldItalic-tlf-t1.tfm \
tex-LibertinusSerif-SemiboldItalic-tlf-t1.vf \
tex-LibertinusSerif-SemiboldItalic-tlf-t2a--base.tfm \
tex-LibertinusSerif-SemiboldItalic-tlf-t2a.tfm \
tex-LibertinusSerif-SemiboldItalic-tlf-t2a.vf \
tex-LibertinusSerif-SemiboldItalic-tlf-t2b--base.tfm \
tex-LibertinusSerif-SemiboldItalic-tlf-t2b.tfm \
tex-LibertinusSerif-SemiboldItalic-tlf-t2b.vf \
tex-LibertinusSerif-SemiboldItalic-tlf-t2c--base.tfm \
tex-LibertinusSerif-SemiboldItalic-tlf-t2c.tfm \
tex-LibertinusSerif-SemiboldItalic-tlf-t2c.vf \
tex-LibertinusSerif-SemiboldItalic-tlf-ts1--base.tfm \
tex-LibertinusSerif-SemiboldItalic-tlf-ts1.tfm \
tex-LibertinusSerif-SemiboldItalic-tlf-ts1.vf \
tex-LibertinusSerif-SemiboldItalic-tosf-lgr.tfm \
tex-LibertinusSerif-SemiboldItalic-tosf-ly1--base.tfm \
tex-LibertinusSerif-SemiboldItalic-tosf-ly1.tfm \
tex-LibertinusSerif-SemiboldItalic-tosf-ly1.vf \
tex-LibertinusSerif-SemiboldItalic-tosf-ot1--base.tfm \
tex-LibertinusSerif-SemiboldItalic-tosf-ot1.tfm \
tex-LibertinusSerif-SemiboldItalic-tosf-ot1.vf \
tex-LibertinusSerif-SemiboldItalic-tosf-sc-lgr.tfm \
tex-LibertinusSerif-SemiboldItalic-tosf-sc-ly1--base.tfm \
tex-LibertinusSerif-SemiboldItalic-tosf-sc-ly1.tfm \
tex-LibertinusSerif-SemiboldItalic-tosf-sc-ly1.vf \
tex-LibertinusSerif-SemiboldItalic-tosf-sc-ot1--base.tfm \
tex-LibertinusSerif-SemiboldItalic-tosf-sc-ot1.tfm \
tex-LibertinusSerif-SemiboldItalic-tosf-sc-ot1.vf \
tex-LibertinusSerif-SemiboldItalic-tosf-sc-t1--base.tfm \
tex-LibertinusSerif-SemiboldItalic-tosf-sc-t1.tfm \
tex-LibertinusSerif-SemiboldItalic-tosf-sc-t1.vf \
tex-LibertinusSerif-SemiboldItalic-tosf-sc-t2a--base.tfm \
tex-LibertinusSerif-SemiboldItalic-tosf-sc-t2a.tfm \
tex-LibertinusSerif-SemiboldItalic-tosf-sc-t2a.vf \
tex-LibertinusSerif-SemiboldItalic-tosf-sc-t2b--base.tfm \
tex-LibertinusSerif-SemiboldItalic-tosf-sc-t2b.tfm \
tex-LibertinusSerif-SemiboldItalic-tosf-sc-t2b.vf \
tex-LibertinusSerif-SemiboldItalic-tosf-sc-t2c--base.tfm \
tex-LibertinusSerif-SemiboldItalic-tosf-sc-t2c.tfm \
tex-LibertinusSerif-SemiboldItalic-tosf-sc-t2c.vf \
tex-LibertinusSerif-SemiboldItalic-tosf-t1--base.tfm \
tex-LibertinusSerif-SemiboldItalic-tosf-t1.tfm \
tex-LibertinusSerif-SemiboldItalic-tosf-t1.vf \
tex-LibertinusSerif-SemiboldItalic-tosf-t2a--base.tfm \
tex-LibertinusSerif-SemiboldItalic-tosf-t2a.tfm \
tex-LibertinusSerif-SemiboldItalic-tosf-t2a.vf \
tex-LibertinusSerif-SemiboldItalic-tosf-t2b--base.tfm \
tex-LibertinusSerif-SemiboldItalic-tosf-t2b.tfm \
tex-LibertinusSerif-SemiboldItalic-tosf-t2b.vf \
tex-LibertinusSerif-SemiboldItalic-tosf-t2c--base.tfm \
tex-LibertinusSerif-SemiboldItalic-tosf-t2c.tfm \
tex-LibertinusSerif-SemiboldItalic-tosf-t2c.vf \
tex-LibertinusSerif-SemiboldItalic-tosf-ts1--base.tfm \
tex-LibertinusSerif-SemiboldItalic-tosf-ts1.tfm \
tex-LibertinusSerif-SemiboldItalic-tosf-ts1.vf \
tex-LibertinusSerifDisplay-Regular-lf-ly1--base.tfm \
tex-LibertinusSerifDisplay-Regular-lf-ly1.tfm \
tex-LibertinusSerifDisplay-Regular-lf-ly1.vf \
tex-LibertinusSerifDisplay-Regular-lf-ot1.tfm \
tex-LibertinusSerifDisplay-Regular-lf-t1--base.tfm \
tex-LibertinusSerifDisplay-Regular-lf-t1.tfm \
tex-LibertinusSerifDisplay-Regular-lf-t1.vf \
tex-LibertinusSerifDisplay-Regular-lf-ts1--base.tfm \
tex-LibertinusSerifDisplay-Regular-lf-ts1.tfm \
tex-LibertinusSerifDisplay-Regular-lf-ts1.vf \
tex-LibertinusSerifDisplay-Regular-osf-ly1--base.tfm \
tex-LibertinusSerifDisplay-Regular-osf-ly1.tfm \
tex-LibertinusSerifDisplay-Regular-osf-ly1.vf \
tex-LibertinusSerifDisplay-Regular-osf-ot1.tfm \
tex-LibertinusSerifDisplay-Regular-osf-t1--base.tfm \
tex-LibertinusSerifDisplay-Regular-osf-t1.tfm \
tex-LibertinusSerifDisplay-Regular-osf-t1.vf \
tex-LibertinusSerifDisplay-Regular-osf-ts1--base.tfm \
tex-LibertinusSerifDisplay-Regular-osf-ts1.tfm \
tex-LibertinusSerifDisplay-Regular-osf-ts1.vf \
tex-LibertinusSerifDisplay-Regular-sup-ly1--base.tfm \
tex-LibertinusSerifDisplay-Regular-sup-ly1.tfm \
tex-LibertinusSerifDisplay-Regular-sup-ly1.vf \
tex-LibertinusSerifDisplay-Regular-sup-ot1.tfm \
tex-LibertinusSerifDisplay-Regular-sup-t1--base.tfm \
tex-LibertinusSerifDisplay-Regular-sup-t1.tfm \
tex-LibertinusSerifDisplay-Regular-sup-t1.vf \
tex-LibertinusSerifDisplay-Regular-tlf-ly1--base.tfm \
tex-LibertinusSerifDisplay-Regular-tlf-ly1.tfm \
tex-LibertinusSerifDisplay-Regular-tlf-ly1.vf \
tex-LibertinusSerifDisplay-Regular-tlf-ot1.tfm \
tex-LibertinusSerifDisplay-Regular-tlf-t1--base.tfm \
tex-LibertinusSerifDisplay-Regular-tlf-t1.tfm \
tex-LibertinusSerifDisplay-Regular-tlf-t1.vf \
tex-LibertinusSerifDisplay-Regular-tlf-ts1--base.tfm \
tex-LibertinusSerifDisplay-Regular-tlf-ts1.tfm \
tex-LibertinusSerifDisplay-Regular-tlf-ts1.vf \
tex-LibertinusSerifDisplay-Regular-tosf-ly1--base.tfm \
tex-LibertinusSerifDisplay-Regular-tosf-ly1.tfm \
tex-LibertinusSerifDisplay-Regular-tosf-ly1.vf \
tex-LibertinusSerifDisplay-Regular-tosf-ot1.tfm \
tex-LibertinusSerifDisplay-Regular-tosf-t1--base.tfm \
tex-LibertinusSerifDisplay-Regular-tosf-t1.tfm \
tex-LibertinusSerifDisplay-Regular-tosf-t1.vf \
tex-LibertinusSerifDisplay-Regular-tosf-ts1--base.tfm \
tex-LibertinusSerifDisplay-Regular-tosf-ts1.tfm \
tex-LibertinusSerifDisplay-Regular-tosf-ts1.vf \
tex-OT1LibertinusMono-TLF.fd \
tex-OT1LibertinusSans-LF.fd \
tex-OT1LibertinusSans-OsF.fd \
tex-OT1LibertinusSans-Sup.fd \
tex-OT1LibertinusSans-TLF.fd \
tex-OT1LibertinusSans-TOsF.fd \
tex-OT1LibertinusSerif-LF.fd \
tex-OT1LibertinusSerif-OsF.fd \
tex-OT1LibertinusSerif-Sup.fd \
tex-OT1LibertinusSerif-TLF.fd \
tex-OT1LibertinusSerif-TOsF.fd \
tex-OT1LibertinusSerifDisplay-LF.fd \
tex-OT1LibertinusSerifDisplay-OsF.fd \
tex-OT1LibertinusSerifDisplay-Sup.fd \
tex-OT1LibertinusSerifDisplay-TLF.fd \
tex-OT1LibertinusSerifDisplay-TOsF.fd \
tex-T1LibertinusMono-TLF.fd \
tex-T1LibertinusSans-LF.fd \
tex-T1LibertinusSans-OsF.fd \
tex-T1LibertinusSans-Sup.fd \
tex-T1LibertinusSans-TLF.fd \
tex-T1LibertinusSans-TOsF.fd \
tex-T1LibertinusSerif-LF.fd \
tex-T1LibertinusSerif-OsF.fd \
tex-T1LibertinusSerif-Sup.fd \
tex-T1LibertinusSerif-TLF.fd \
tex-T1LibertinusSerif-TOsF.fd \
tex-T1LibertinusSerifDisplay-LF.fd \
tex-T1LibertinusSerifDisplay-OsF.fd \
tex-T1LibertinusSerifDisplay-Sup.fd \
tex-T1LibertinusSerifDisplay-TLF.fd \
tex-T1LibertinusSerifDisplay-TOsF.fd \
tex-T2ALibertinusMono-TLF.fd \
tex-T2ALibertinusSans-LF.fd \
tex-T2ALibertinusSans-OsF.fd \
tex-T2ALibertinusSans-Sup.fd \
tex-T2ALibertinusSans-TLF.fd \
tex-T2ALibertinusSans-TOsF.fd \
tex-T2ALibertinusSerif-LF.fd \
tex-T2ALibertinusSerif-OsF.fd \
tex-T2ALibertinusSerif-Sup.fd \
tex-T2ALibertinusSerif-TLF.fd \
tex-T2ALibertinusSerif-TOsF.fd \
tex-T2BLibertinusMono-TLF.fd \
tex-T2BLibertinusSans-LF.fd \
tex-T2BLibertinusSans-OsF.fd \
tex-T2BLibertinusSans-Sup.fd \
tex-T2BLibertinusSans-TLF.fd \
tex-T2BLibertinusSans-TOsF.fd \
tex-T2BLibertinusSerif-LF.fd \
tex-T2BLibertinusSerif-OsF.fd \
tex-T2BLibertinusSerif-Sup.fd \
tex-T2BLibertinusSerif-TLF.fd \
tex-T2BLibertinusSerif-TOsF.fd \
tex-T2CLibertinusMono-TLF.fd \
tex-T2CLibertinusSans-LF.fd \
tex-T2CLibertinusSans-OsF.fd \
tex-T2CLibertinusSans-Sup.fd \
tex-T2CLibertinusSans-TLF.fd \
tex-T2CLibertinusSans-TOsF.fd \
tex-T2CLibertinusSerif-LF.fd \
tex-T2CLibertinusSerif-OsF.fd \
tex-T2CLibertinusSerif-Sup.fd \
tex-T2CLibertinusSerif-TLF.fd \
tex-T2CLibertinusSerif-TOsF.fd \
tex-TS1LibertinusMono-TLF.fd \
tex-TS1LibertinusSans-LF.fd \
tex-TS1LibertinusSans-OsF.fd \
tex-TS1LibertinusSans-TLF.fd \
tex-TS1LibertinusSans-TOsF.fd \
tex-TS1LibertinusSerif-LF.fd \
tex-TS1LibertinusSerif-OsF.fd \
tex-TS1LibertinusSerif-TLF.fd \
tex-TS1LibertinusSerif-TOsF.fd \
tex-TS1LibertinusSerifDisplay-LF.fd \
tex-TS1LibertinusSerifDisplay-OsF.fd \
tex-TS1LibertinusSerifDisplay-TLF.fd \
tex-TS1LibertinusSerifDisplay-TOsF.fd \
tex-lbn1-2dnbtf.enc \
tex-lbn1-2fcdyd.enc \
tex-lbn1-2tlncs.enc \
tex-lbn1-2vfnnw.enc \
tex-lbn1-2y652m.enc \
tex-lbn1-2yds7f.enc \
tex-lbn1-35favc.enc \
tex-lbn1-36t55i.enc \
tex-lbn1-37i5h5.enc \
tex-lbn1-37jtjx.enc \
tex-lbn1-3cokjk.enc \
tex-lbn1-3d54jy.enc \
tex-lbn1-3j5xjf.enc \
tex-lbn1-3jolak.enc \
tex-lbn1-3kirmv.enc \
tex-lbn1-3kmpct.enc \
tex-lbn1-3m644f.enc \
tex-lbn1-3qta4x.enc \
tex-lbn1-3ssu23.enc \
tex-lbn1-3un72f.enc \
tex-lbn1-3vqmyw.enc \
tex-lbn1-3yrfnt.enc \
tex-lbn1-45gf2l.enc \
tex-lbn1-4crdwc.enc \
tex-lbn1-4d42wm.enc \
tex-lbn1-4gaomz.enc \
tex-lbn1-4hcz3c.enc \
tex-lbn1-4mrx7q.enc \
tex-lbn1-4q6kep.enc \
tex-lbn1-4sdcjk.enc \
tex-lbn1-4uwsiq.enc \
tex-lbn1-4wbnoe.enc \
tex-lbn1-4xoyfg.enc \
tex-lbn1-4zqa2g.enc \
tex-lbn1-57bjkg.enc \
tex-lbn1-5acxeg.enc \
tex-lbn1-5cy3nd.enc \
tex-lbn1-5f7tjt.enc \
tex-lbn1-5h7qbk.enc \
tex-lbn1-5jnf2k.enc \
tex-lbn1-63ftwl.enc \
tex-lbn1-667eeu.enc \
tex-lbn1-674lrv.enc \
tex-lbn1-6caxtj.enc \
tex-lbn1-6ewxxu.enc \
tex-lbn1-6gletg.enc \
tex-lbn1-6h6srf.enc \
tex-lbn1-6hdezz.enc \
tex-lbn1-6l4fbc.enc \
tex-lbn1-6lk76t.enc \
tex-lbn1-6muo3k.enc \
tex-lbn1-6wmeer.enc \
tex-lbn1-72youc.enc \
tex-lbn1-75t36g.enc \
tex-lbn1-76vk5v.enc \
tex-lbn1-76xdns.enc \
tex-lbn1-77jah4.enc \
tex-lbn1-77t54r.enc \
tex-lbn1-7aen2t.enc \
tex-lbn1-7bccbz.enc \
tex-lbn1-7d2mhk.enc \
tex-lbn1-7hmj2z.enc \
tex-lbn1-7lwjes.enc \
tex-lbn1-7mm7zy.enc \
tex-lbn1-7np5uz.enc \
tex-lbn1-7oodvn.enc \
tex-lbn1-7vsebg.enc \
tex-lbn1-7yclm6.enc \
tex-lbn1-a3f66t.enc \
tex-lbn1-aidrin.enc \
tex-lbn1-at32ur.enc \
tex-lbn1-avlujb.enc \
tex-lbn1-avlydd.enc \
tex-lbn1-ayzaac.enc \
tex-lbn1-b4oezt.enc \
tex-lbn1-b5fzbp.enc \
tex-lbn1-b5ulzv.enc \
tex-lbn1-b7xqh5.enc \
tex-lbn1-bgegdt.enc \
tex-lbn1-bjbyqz.enc \
tex-lbn1-bn2i3n.enc \
tex-lbn1-bvhzzu.enc \
tex-lbn1-bwr4ko.enc \
tex-lbn1-bxwrog.enc \
tex-lbn1-c3bv3f.enc \
tex-lbn1-c4i7ev.enc \
tex-lbn1-c4nx3a.enc \
tex-lbn1-c6vmpn.enc \
tex-lbn1-c7grr2.enc \
tex-lbn1-calslh.enc \
tex-lbn1-cb34qf.enc \
tex-lbn1-cefqwa.enc \
tex-lbn1-ckbdgg.enc \
tex-lbn1-ckenly.enc \
tex-lbn1-cpinjp.enc \
tex-lbn1-cslza4.enc \
tex-lbn1-cykel7.enc \
tex-lbn1-d2pxsd.enc \
tex-lbn1-d37b7c.enc \
tex-lbn1-d7j3zj.enc \
tex-lbn1-dashch.enc \
tex-lbn1-dgc4ye.enc \
tex-lbn1-dhtsou.enc \
tex-lbn1-dkknmm.enc \
tex-lbn1-dn22no.enc \
tex-lbn1-dprkig.enc \
tex-lbn1-dsfsze.enc \
tex-lbn1-dzyoth.enc \
tex-lbn1-e2cf4v.enc \
tex-lbn1-e35iwk.enc \
tex-lbn1-e5lu6a.enc \
tex-lbn1-eclek4.enc \
tex-lbn1-ecxtyf.enc \
tex-lbn1-ed5ai4.enc \
tex-lbn1-eejjqw.enc \
tex-lbn1-ep5pfz.enc \
tex-lbn1-epdddg.enc \
tex-lbn1-ercrba.enc \
tex-lbn1-erdvwd.enc \
tex-lbn1-esgnlu.enc \
tex-lbn1-et5tau.enc \
tex-lbn1-exfok6.enc \
tex-lbn1-f2r76x.enc \
tex-lbn1-f3pcwn.enc \
tex-lbn1-fafj4h.enc \
tex-lbn1-fili27.enc \
tex-lbn1-fmdp7p.enc \
tex-lbn1-fmriqv.enc \
tex-lbn1-fph2zj.enc \
tex-lbn1-fszxp3.enc \
tex-lbn1-fuyass.enc \
tex-lbn1-fy3had.enc \
tex-lbn1-g3dkmi.enc \
tex-lbn1-g6etas.enc \
tex-lbn1-gazpeh.enc \
tex-lbn1-gh4gmp.enc \
tex-lbn1-gr4hit.enc \
tex-lbn1-gxlsis.enc \
tex-lbn1-gz7arp.enc \
tex-lbn1-hahfqq.enc \
tex-lbn1-hej6xm.enc \
tex-lbn1-hgpggj.enc \
tex-lbn1-hhbt6z.enc \
tex-lbn1-hhmpft.enc \
tex-lbn1-hhyopg.enc \
tex-lbn1-hm3bfr.enc \
tex-lbn1-hrrrjq.enc \
tex-lbn1-hvubca.enc \
tex-lbn1-hvvyjb.enc \
tex-lbn1-hxvdny.enc \
tex-lbn1-hzjkgg.enc \
tex-lbn1-i52ngl.enc \
tex-lbn1-iadd5v.enc \
tex-lbn1-iaq24h.enc \
tex-lbn1-ibb6ig.enc \
tex-lbn1-icmtyb.enc \
tex-lbn1-ighl2q.enc \
tex-lbn1-igmfoi.enc \
tex-lbn1-ihkzot.enc \
tex-lbn1-ihsp6n.enc \
tex-lbn1-iknsvo.enc \
tex-lbn1-inpbes.enc \
tex-lbn1-ipd343.enc \
tex-lbn1-iskk3a.enc \
tex-lbn1-iv4zj2.enc \
tex-lbn1-j6sgbi.enc \
tex-lbn1-jb5pke.enc \
tex-lbn1-jdjwkh.enc \
tex-lbn1-jfamas.enc \
tex-lbn1-jiz4dk.enc \
tex-lbn1-jrenuz.enc \
tex-lbn1-jvtoya.enc \
tex-lbn1-jwzfsl.enc \
tex-lbn1-k62zaj.enc \
tex-lbn1-kbhblx.enc \
tex-lbn1-kehxxc.enc \
tex-lbn1-kirbtk.enc \
tex-lbn1-koaj57.enc \
tex-lbn1-komy7m.enc \
tex-lbn1-kq3xmd.enc \
tex-lbn1-kwkowq.enc \
tex-lbn1-kynajb.enc \
tex-lbn1-l5ujiv.enc \
tex-lbn1-l5vej2.enc \
tex-lbn1-l6vzgi.enc \
tex-lbn1-l74upk.enc \
tex-lbn1-laenbp.enc \
tex-lbn1-lafzha.enc \
tex-lbn1-lhntva.enc \
tex-lbn1-lkanbr.enc \
tex-lbn1-llns2d.enc \
tex-lbn1-llzec3.enc \
tex-lbn1-lsubum.enc \
tex-lbn1-lwzthx.enc \
tex-lbn1-lyzgu3.enc \
tex-lbn1-lzae2z.enc \
tex-lbn1-lzywtf.enc \
tex-lbn1-m254rf.enc \
tex-lbn1-m2klan.enc \
tex-lbn1-m3c2oj.enc \
tex-lbn1-m3l6fs.enc \
tex-lbn1-m5c6xi.enc \
tex-lbn1-m7sqdm.enc \
tex-lbn1-mbfmc4.enc \
tex-lbn1-mfadfl.enc \
tex-lbn1-mi54ls.enc \
tex-lbn1-mll6fo.enc \
tex-lbn1-mlwm27.enc \
tex-lbn1-mmgovh.enc \
tex-lbn1-mphtgh.enc \
tex-lbn1-mrbizy.enc \
tex-lbn1-mru3ev.enc \
tex-lbn1-mvzwgg.enc \
tex-lbn1-mxiee2.enc \
tex-lbn1-myww54.enc \
tex-lbn1-n3cifc.enc \
tex-lbn1-n3dtgz.enc \
tex-lbn1-n4gj6t.enc \
tex-lbn1-n4tewx.enc \
tex-lbn1-nl47lc.enc \
tex-lbn1-nufysp.enc \
tex-lbn1-o7mh5o.enc \
tex-lbn1-oaaihm.enc \
tex-lbn1-obzz72.enc \
tex-lbn1-oe5ee4.enc \
tex-lbn1-of47id.enc \
tex-lbn1-of4nbw.enc \
tex-lbn1-olk76w.enc \
tex-lbn1-olw3tj.enc \
tex-lbn1-onayya.enc \
tex-lbn1-opzo24.enc \
tex-lbn1-or3pzs.enc \
tex-lbn1-ork5hb.enc \
tex-lbn1-orvmfm.enc \
tex-lbn1-osdvzf.enc \
tex-lbn1-oxank3.enc \
tex-lbn1-p2xkqy.enc \
tex-lbn1-p5b3to.enc \
tex-lbn1-p7snj6.enc \
tex-lbn1-pb7os7.enc \
tex-lbn1-pdot6l.enc \
tex-lbn1-peeabe.enc \
tex-lbn1-pkzsom.enc \
tex-lbn1-poicuj.enc \
tex-lbn1-ponsko.enc \
tex-lbn1-pquqdo.enc \
tex-lbn1-ptnx64.enc \
tex-lbn1-pydski.enc \
tex-lbn1-q2cvbs.enc \
tex-lbn1-q2ibpc.enc \
tex-lbn1-q4imkx.enc \
tex-lbn1-q4q2yp.enc \
tex-lbn1-qbwrql.enc \
tex-lbn1-qcfvgl.enc \
tex-lbn1-qe2yqv.enc \
tex-lbn1-qgowik.enc \
tex-lbn1-qpph5c.enc \
tex-lbn1-qqnp2h.enc \
tex-lbn1-qsv3bx.enc \
tex-lbn1-qzwhi6.enc \
tex-lbn1-r37ntu.enc \
tex-lbn1-r4goj2.enc \
tex-lbn1-r7yss2.enc \
tex-lbn1-rcarnw.enc \
tex-lbn1-rchowm.enc \
tex-lbn1-rfuadt.enc \
tex-lbn1-ridgvo.enc \
tex-lbn1-rlktsf.enc \
tex-lbn1-rpeiua.enc \
tex-lbn1-rqhkdi.enc \
tex-lbn1-rt44aj.enc \
tex-lbn1-rtitj6.enc \
tex-lbn1-rvhnvp.enc \
tex-lbn1-rwdf67.enc \
tex-lbn1-s4apdz.enc \
tex-lbn1-sceraq.enc \
tex-lbn1-segm3u.enc \
tex-lbn1-sewfus.enc \
tex-lbn1-sfissr.enc \
tex-lbn1-sihybe.enc \
tex-lbn1-sjlxxx.enc \
tex-lbn1-slsqbu.enc \
tex-lbn1-sncvby.enc \
tex-lbn1-snijqp.enc \
tex-lbn1-sppvmf.enc \
tex-lbn1-srwzhm.enc \
tex-lbn1-st5lk5.enc \
tex-lbn1-sut3w7.enc \
tex-lbn1-szn4yf.enc \
tex-lbn1-szwnvb.enc \
tex-lbn1-t2ckkh.enc \
tex-lbn1-tc5bjz.enc \
tex-lbn1-tevnlg.enc \
tex-lbn1-tg6ewh.enc \
tex-lbn1-tll2u3.enc \
tex-lbn1-trmgk4.enc \
tex-lbn1-trxlme.enc \
tex-lbn1-tvlhp3.enc \
tex-lbn1-tzl7op.enc \
tex-lbn1-tzy66j.enc \
tex-lbn1-u7nqae.enc \
tex-lbn1-ubtjzz.enc \
tex-lbn1-ucipzb.enc \
tex-lbn1-ucscsg.enc \
tex-lbn1-ugujza.enc \
tex-lbn1-uhcuvh.enc \
tex-lbn1-uhqgc3.enc \
tex-lbn1-uhwxqu.enc \
tex-lbn1-uoecuf.enc \
tex-lbn1-usfuuy.enc \
tex-lbn1-usl52j.enc \
tex-lbn1-usz5ut.enc \
tex-lbn1-utifxg.enc \
tex-lbn1-uwmf7x.enc \
tex-lbn1-uxbjn5.enc \
tex-lbn1-uxf4m5.enc \
tex-lbn1-uywzpa.enc \
tex-lbn1-v5z4kv.enc \
tex-lbn1-vejg7h.enc \
tex-lbn1-vftr22.enc \
tex-lbn1-vgw5na.enc \
tex-lbn1-vhmker.enc \
tex-lbn1-vizicw.enc \
tex-lbn1-vjxogo.enc \
tex-lbn1-vmhi4g.enc \
tex-lbn1-vmjjgq.enc \
tex-lbn1-vtz4pu.enc \
tex-lbn1-vu5j2r.enc \
tex-lbn1-vvzoei.enc \
tex-lbn1-w42dre.enc \
tex-lbn1-w5ro75.enc \
tex-lbn1-wbnhrd.enc \
tex-lbn1-wogi6j.enc \
tex-lbn1-wozmdw.enc \
tex-lbn1-wrg6fm.enc \
tex-lbn1-wyvtce.enc \
tex-lbn1-x7beke.enc \
tex-lbn1-xaezkf.enc \
tex-lbn1-xfy7gm.enc \
tex-lbn1-xgmem5.enc \
tex-lbn1-xh3iko.enc \
tex-lbn1-xhfw3j.enc \
tex-lbn1-xrj6hp.enc \
tex-lbn1-y2inml.enc \
tex-lbn1-ya3yeu.enc \
tex-lbn1-yaf6wf.enc \
tex-lbn1-yahecb.enc \
tex-lbn1-yaunjw.enc \
tex-lbn1-ygr64v.enc \
tex-lbn1-yk7y77.enc \
tex-lbn1-yki2t7.enc \
tex-lbn1-ynfuvy.enc \
tex-lbn1-ysaokq.enc \
tex-lbn1-yt5vb5.enc \
tex-lbn1-yuwgqp.enc \
tex-lbn1-yzuq4p.enc \
tex-lbn1-z4iz37.enc \
tex-lbn1-z6nnva.enc \
tex-lbn1-zh5q6t.enc \
tex-lbn1-zjhiql.enc \
tex-lbn1-znslmj.enc \
tex-lbn1-zpwads.enc \
tex-lbn1-zqzvht.enc \
tex-libertinus-type1.sty \
tex-libertinus.map \
texlive-libertinus-type1"

RDEPENDS:${PN} += "/usr/bin/sh \
coreutils \
ed \
findutils \
grep \
sed \
tex-fontaxes.sty \
tex-fontenc.sty \
tex-ifluatex.sty \
tex-ifxetex.sty \
tex-textcomp.sty \
tex-updmap.cfg \
tex-xkeyval.sty \
texlive \
texlive-filesystem \
texlive-kpathsea \
texlive-kpathsea-bin \
texlive-libertinus-type1-fonts \
texlive-scripts \
texlive-scripts-bin"

inherit rpm
