SUMMARY = "Helper for correctly compacting PDF files created by TeX"
DESCRIPTION = "This tool helps compacting PDF files generated by the TeX \
typesetting system by extracting meta data like page mode and named \
destinations (link targets) and saving them in a PDFmark file. The \
PDFmark file can then be used by ghostscript when processing the \
TeX-generated PDF to make sure that the final output contains correct \
page mode and link targets. Such post-processing of TeX-generated PDF \
output is often useful to reduce the size of the final PDF document, \
e.g. by removing duplicate font sets."
LICENSE = "GPL-3.0-or-later"

PV = "1.1.1"

RPM_NAME = "extractpdfmark-1.1.1-1.17.aarch64.rpm"
RPM_HASH = "f7aba76f1b36aff2aeb72a3fda44114115ca6e927f4804121af0f82577bef9ee53256b42d1c35bd173ae60f6b4d6658728c8ac357883dfbb5bf4237f3bac00d8"

RPROVIDES:${PN} += "extractpdfmark"

RDEPENDS:${PN} += "ld-linux-aarch64.so.1 \
libc.so.6 \
libgcc-s.so.1 \
libpoppler-cpp.so.3 \
libstdc++.so.6"

inherit rpm
