SUMMARY = "Bash completion for bugwarden"
DESCRIPTION = "The bash completion script for bugwarden, generated by upstream from the \
command line definition."
LICENSE = "(Apache-2.0 | BSL-1.0) & (Apache-2.0 | ISC | MIT) & (Apache-2.0 | MIT) & (MIT | Unlicense) & Apache-2.0 & BSD-3-Clause & ISC & MIT & Unicode-3.0"

PV = "0.6.0"

RPM_NAME = "bugwarden-bash-completion-0.6.0-1.1.noarch.rpm"
RPM_HASH = "2ad9c3e1828d7cdf0aadb84ef460f7340f3111a755b8fae945c9eb6b64b9d388025f8b494b642cb52cabbd2de29360740951e236e06865edf9ed1f7432ed46fb"
REPO_ARCH = "noarch"

RPROVIDES:${PN} += "bugwarden-bash-completion"

RDEPENDS:${PN} += "bash-completion \
bugwarden"

inherit rpm
