SUMMARY = "GAP: Adjoint groups of finite rings"
DESCRIPTION = "The Circle package provides functionality for computations in adjoint \
groups of finite associative rings. It allows to construct circle \
objects that will respect the circle multiplication r*s=r+s+rs, \
create multiplicative groups, generated by such objects, and compute \
groups of elements, invertible with respect to this operation."
LICENSE = "GPL-2.0-or-later"

PV = "1.7.1"

RPM_NAME = "gap-circle-1.7.1-1.1.noarch.rpm"
RPM_HASH = "bb3679b83f7d888f3761fcfb48bd1002a279bde324c8b49eb12210637772281267dfd68380cb879c69ae823cd57c3431eebac8d09ac83a987e878ae4f5ff975a"
REPO_ARCH = "noarch"

RPROVIDES:${PN} += "gap-circle"

RDEPENDS:${PN} += "gap-core"

inherit rpm
