SUMMARY = "Dynamically typeset numbers and values in LaTeX through 'symbolic links'"
DESCRIPTION = "This package dynamically typesets values generated by different \
kinds of scripts in LaTeX through the use of 'symbolic links' \
(which are not in any way related to the 'symbolic links' used \
in UNIX systems!). The aim is to reduce errors resulting from \
out-of-date numbers by directly setting them in the number \
generating file and importing a 'symbolic link' into the LaTeX \
source file. It can be used to import not only numerical \
values, but strings and pieces of code are also possible. \
Currently only MATLAB and Python are supported to produce \
Dynamic Number list files."
LICENSE = "LPPL-1.0"

PV = "2026.226.0.0.1.3svn38726"

RPM_NAME = "texlive-dynamicnumber-2026.226.0.0.1.3svn38726-61.4.noarch.rpm"
RPM_HASH = "d93816ede8735ea7d26e61c7830eac463f3c167c0067b16862a11587fd46f707db1a2efcda226c9247f5ee0a35a883f337702b21a36b33737e60f0ffd7b98f96"
REPO_ARCH = "noarch"

RPROVIDES:${PN} += "tex-dynamicnumber.sty \
texlive-dynamicnumber"

RDEPENDS:${PN} += "/usr/bin/sh \
coreutils \
ed \
findutils \
grep \
sed \
tex-pgfkeys.sty \
tex-xparse.sty \
texlive \
texlive-filesystem \
texlive-kpathsea \
texlive-kpathsea-bin \
texlive-scripts \
texlive-scripts-bin"

inherit rpm
