SUMMARY = "Parse partial JSON generated by LLM"
DESCRIPTION = "Parse partial and incomplete JSON strings, such as the streamed output of \
a large language model (LLM). Before the final token of a response is \
received the JSON is broken and cannot be decoded with a normal parser; \
partial-json-parser completes the fragment so the partial structure can be \
used while streaming. It is implemented purely in Python and is \
zero-dependency."
LICENSE = "MIT"

PV = "0.2.1.1.post7"

RPM_NAME = "python314-partial-json-parser-0.2.1.1.post7-1.1.noarch.rpm"
RPM_HASH = "8fe8eda6abc87fbb91d52031a171bed5c582c267faa043e3477317b07b22bfda73c9e92e95837877ae193288cc816139cbffb054071872cf1723695c03c43887"
REPO_ARCH = "noarch"

RPROVIDES:${PN} += "python3.14dist-partial-json-parser \
python314-partial-json-parser \
python3dist-partial-json-parser"

RDEPENDS:${PN} += "python-abi"

inherit rpm
