SUMMARY = "Semantic patch utility"
DESCRIPTION = "Coccinelle is a program matching and transformation engine which \
provides the language SmPL (Semantic Patch Language) for specifying \
desired matches and transformations in C code. [It does not recognize \
C++.] \
 \
Coccinelle performs collateral evolutions in software. Such \
evolutions comprise the changes that are needed in client code in \
response to evolutions in library APIs, and may include modifications \
such as renaming a function, adding a function argument whose value \
is somehow context-dependent, and reorganizing a data structure. \
Beyond collateral evolutions, Coccinelle is used for finding and \
fixing bugs in systems code."
LICENSE = "GPL-2.0-only"

PV = "1.3.2"

RPM_NAME = "coccinelle-1.3.2-1.1.aarch64.rpm"
RPM_HASH = "0753e2b878e64e4074663358b6edbe62db669c3ce35c0d7643bd7fced9e36d8e41c9b4ba7f98a7f4c304745a5fb7bdbf7433944ce5dd3ffc56db6403b86083f2"

RPROVIDES:${PN} += "coccinelle \
ocaml-Adjacency \
ocaml-Adjust-pragmas \
ocaml-Arity \
ocaml-Ast-c \
ocaml-Ast-cocci \
ocaml-Ast0-cocci \
ocaml-Ast0toast \
ocaml-Check-meta \
ocaml-Cleanup-rules \
ocaml-Cocci-args \
ocaml-Cocci-grep \
ocaml-Cocciconfig \
ocaml-Coccilib \
ocaml-Comm-assoc \
ocaml-Command-line \
ocaml-Commands \
ocaml-Commas-on-lists \
ocaml-Comment-annotater-c \
ocaml-Common \
ocaml-Compare-c \
ocaml-Compute-lines \
ocaml-Context-neg \
ocaml-Control-flow-c \
ocaml-Control-flow-c-build \
ocaml-Cpp-analysis-c \
ocaml-Cpp-ast-c \
ocaml-Cpp-token-c \
ocaml-Danger \
ocaml-Data \
ocaml-Disjdistr \
ocaml-Dpll \
ocaml-Dumper \
ocaml-Exposed-modules \
ocaml-Externalanalysis \
ocaml-Flag \
ocaml-Flag-parsing-c \
ocaml-Flag-parsing-cocci \
ocaml-Free-vars \
ocaml-Function-prototypes \
ocaml-Get-constants2 \
ocaml-Get-metas \
ocaml-Git-grep \
ocaml-Id-utils \
ocaml-Includes \
ocaml-Includes-cache \
ocaml-Index \
ocaml-Insert-plus \
ocaml-Internal-print-c \
ocaml-Internal-print-cocci \
ocaml-Iso-compile \
ocaml-Iso-pattern \
ocaml-Iteration \
ocaml-Lexer-c \
ocaml-Lexer-cli \
ocaml-Lexer-cocci \
ocaml-Lexer-parser \
ocaml-Lexer-script \
ocaml-Lib-parsing-c \
ocaml-Ocamlcocci-aux \
ocaml-Ograph-extended \
ocaml-Ograph-simple \
ocaml-Parmap \
ocaml-Parse-aux \
ocaml-Parse-c \
ocaml-Parse-cocci \
ocaml-Parse-printf \
ocaml-Parse-string-c \
ocaml-Parser-c \
ocaml-Parser-cocci-menhir \
ocaml-Parsing-consistency-c \
ocaml-Parsing-hacks \
ocaml-Parsing-recovery-c \
ocaml-Parsing-stat \
ocaml-Patch-diff \
ocaml-Prepare-ocamlcocci \
ocaml-Pretty-print-c \
ocaml-Pretty-print-cocci \
ocaml-Re-constraints \
ocaml-Regexp \
ocaml-Regexp-pcre \
ocaml-Run-ocamlcocci \
ocaml-Safe-for-multi-decls \
ocaml-Semantic-c \
ocaml-Semantic-cocci \
ocaml-Simple-assignments \
ocaml-Single-statement \
ocaml-Stmtlist \
ocaml-Strip-ast \
ocaml-Test-exps \
ocaml-Test-parsing-c \
ocaml-Token-annot \
ocaml-Token-c \
ocaml-Token-helpers \
ocaml-Token-views-c \
ocaml-Top-level \
ocaml-Type-annoter-c \
ocaml-Type-c \
ocaml-Type-infer \
ocaml-Unify-ast \
ocaml-Unitary-ast0 \
ocaml-Unparse-ast0 \
ocaml-Unparse-c \
ocaml-Unparse-cocci \
ocaml-Unparse-hrule \
ocaml-Visitor-ast \
ocaml-Visitor-ast0 \
ocaml-Visitor-ast0-types \
ocaml-Visitor-c \
ocaml-Yes-prepare-ocamlcocci \
ocamlx-Adjacency \
ocamlx-Adjust-pragmas \
ocamlx-Arity \
ocamlx-Ast-c \
ocamlx-Ast-cocci \
ocamlx-Ast0-cocci \
ocamlx-Ast0toast \
ocamlx-Check-meta \
ocamlx-Cleanup-rules \
ocamlx-Cocci-args \
ocamlx-Cocci-grep \
ocamlx-Cocciconfig \
ocamlx-Coccilib \
ocamlx-Comm-assoc \
ocamlx-Command-line \
ocamlx-Commands \
ocamlx-Commas-on-lists \
ocamlx-Comment-annotater-c \
ocamlx-Common \
ocamlx-Compare-c \
ocamlx-Compute-lines \
ocamlx-Context-neg \
ocamlx-Control-flow-c \
ocamlx-Control-flow-c-build \
ocamlx-Cpp-analysis-c \
ocamlx-Cpp-ast-c \
ocamlx-Cpp-token-c \
ocamlx-Danger \
ocamlx-Data \
ocamlx-Disjdistr \
ocamlx-Dpll \
ocamlx-Dumper \
ocamlx-Exposed-modules \
ocamlx-Externalanalysis \
ocamlx-Flag \
ocamlx-Flag-parsing-c \
ocamlx-Flag-parsing-cocci \
ocamlx-Free-vars \
ocamlx-Function-prototypes \
ocamlx-Get-constants2 \
ocamlx-Get-metas \
ocamlx-Git-grep \
ocamlx-Id-utils \
ocamlx-Includes \
ocamlx-Includes-cache \
ocamlx-Index \
ocamlx-Insert-plus \
ocamlx-Internal-print-c \
ocamlx-Internal-print-cocci \
ocamlx-Iso-compile \
ocamlx-Iso-pattern \
ocamlx-Iteration \
ocamlx-Lexer-c \
ocamlx-Lexer-cli \
ocamlx-Lexer-cocci \
ocamlx-Lexer-parser \
ocamlx-Lexer-script \
ocamlx-Lib-parsing-c \
ocamlx-Ocamlcocci-aux \
ocamlx-Ograph-extended \
ocamlx-Ograph-simple \
ocamlx-Parmap \
ocamlx-Parse-aux \
ocamlx-Parse-c \
ocamlx-Parse-cocci \
ocamlx-Parse-printf \
ocamlx-Parse-string-c \
ocamlx-Parser-c \
ocamlx-Parser-cocci-menhir \
ocamlx-Parsing-consistency-c \
ocamlx-Parsing-hacks \
ocamlx-Parsing-recovery-c \
ocamlx-Parsing-stat \
ocamlx-Patch-diff \
ocamlx-Prepare-ocamlcocci \
ocamlx-Pretty-print-c \
ocamlx-Pretty-print-cocci \
ocamlx-Re-constraints \
ocamlx-Regexp \
ocamlx-Regexp-pcre \
ocamlx-Run-ocamlcocci \
ocamlx-Safe-for-multi-decls \
ocamlx-Semantic-c \
ocamlx-Semantic-cocci \
ocamlx-Simple-assignments \
ocamlx-Single-statement \
ocamlx-Stmtlist \
ocamlx-Strip-ast \
ocamlx-Test-exps \
ocamlx-Test-parsing-c \
ocamlx-Token-annot \
ocamlx-Token-c \
ocamlx-Token-helpers \
ocamlx-Token-views-c \
ocamlx-Top-level \
ocamlx-Type-annoter-c \
ocamlx-Type-c \
ocamlx-Type-infer \
ocamlx-Unify-ast \
ocamlx-Unitary-ast0 \
ocamlx-Unparse-ast0 \
ocamlx-Unparse-c \
ocamlx-Unparse-cocci \
ocamlx-Unparse-hrule \
ocamlx-Visitor-ast \
ocamlx-Visitor-ast0 \
ocamlx-Visitor-ast0-types \
ocamlx-Visitor-c \
ocamlx-Yes-prepare-ocamlcocci"

RDEPENDS:${PN} += "/usr/bin/python3.13 \
findutils \
grep \
libc.so.6 \
libm.so.6 \
libpcre2-8.so.0 \
libzstd.so.1 \
ocaml-Asttypes \
ocaml-Build-path-prefix-map \
ocaml-Bytearray \
ocaml-CamlinternalFormatBasics \
ocaml-CamlinternalLazy \
ocaml-CamlinternalOO \
ocaml-Cmi-format \
ocaml-Dynlink \
ocaml-Format-doc \
ocaml-Ident \
ocaml-Identifiable \
ocaml-Location \
ocaml-Longident \
ocaml-Misc \
ocaml-Outcometree \
ocaml-Parmap-compat \
ocaml-Parmap-utils \
ocaml-Parsetree \
ocaml-Path \
ocaml-Pcre2 \
ocaml-Primitive \
ocaml-Setcore \
ocaml-Shape \
ocaml-Stdcompat \
ocaml-Stdcompat--init \
ocaml-Stdcompat--stdlib-s \
ocaml-Stdlib \
ocaml-Stdlib--Arg \
ocaml-Stdlib--Array \
ocaml-Stdlib--Bigarray \
ocaml-Stdlib--Buffer \
ocaml-Stdlib--Char \
ocaml-Stdlib--Complex \
ocaml-Stdlib--Digest \
ocaml-Stdlib--Domain \
ocaml-Stdlib--Either \
ocaml-Stdlib--Filename \
ocaml-Stdlib--Format \
ocaml-Stdlib--Gc \
ocaml-Stdlib--Hashtbl \
ocaml-Stdlib--Int32 \
ocaml-Stdlib--Int64 \
ocaml-Stdlib--Lazy \
ocaml-Stdlib--Lexing \
ocaml-Stdlib--List \
ocaml-Stdlib--Map \
ocaml-Stdlib--Marshal \
ocaml-Stdlib--Nativeint \
ocaml-Stdlib--Obj \
ocaml-Stdlib--Parsing \
ocaml-Stdlib--Printexc \
ocaml-Stdlib--Printf \
ocaml-Stdlib--Random \
ocaml-Stdlib--Result \
ocaml-Stdlib--Seq \
ocaml-Stdlib--Set \
ocaml-Stdlib--String \
ocaml-Stdlib--Sys \
ocaml-Stdlib--Uchar \
ocaml-Str \
ocaml-Type-immediacy \
ocaml-Types \
ocaml-Unit-info \
ocaml-Unix \
ocaml-Warnings \
ocamlx-Bytearray \
ocamlx-CamlinternalOO \
ocamlx-Cmi-format \
ocamlx-Dynlink \
ocamlx-Ident \
ocamlx-Parmap-compat \
ocamlx-Parmap-utils \
ocamlx-Pcre2 \
ocamlx-Setcore \
ocamlx-Stdlib \
ocamlx-Stdlib--Arg \
ocamlx-Stdlib--Array \
ocamlx-Stdlib--Bigarray \
ocamlx-Stdlib--Buffer \
ocamlx-Stdlib--Filename \
ocamlx-Stdlib--Format \
ocamlx-Stdlib--Gc \
ocamlx-Stdlib--Hashtbl \
ocamlx-Stdlib--Int64 \
ocamlx-Stdlib--Lexing \
ocamlx-Stdlib--List \
ocamlx-Stdlib--Map \
ocamlx-Stdlib--Marshal \
ocamlx-Stdlib--Obj \
ocamlx-Stdlib--Parsing \
ocamlx-Stdlib--Printexc \
ocamlx-Stdlib--Printf \
ocamlx-Stdlib--Random \
ocamlx-Stdlib--Set \
ocamlx-Stdlib--String \
ocamlx-Stdlib--Sys \
ocamlx-Str \
ocamlx-Unix \
python-abi \
which"

inherit rpm
