SUMMARY = "GStreamer Streaming-Media Framework Plug-Ins"
DESCRIPTION = "GStreamer is a streaming media framework based on graphs of filters \
that operate on media data. Applications using this library can do \
anything media-related,from real-time sound processing to playing \
videos. Its plug-in-based architecture means that new data types or \
processing capabilities can be added simply by installing new plug-ins."
LICENSE = "LGPL-2.1-or-later"

PV = "1.28.7"

RPM_NAME = "gstreamer-plugins-bad-1.28.7-1.1.aarch64.rpm"
RPM_HASH = "e1c87d7546fa2c2f6c045041026d1928d6b14e74bc06c25766818ecb6e90c779003d66b76d99c092f1bfd4cd4b976637a2ec53146d08109860bc098bd9480fb6"

RPROVIDES:${PN} += "gst-plugins-bad \
gstreamer-1.20-plugin-openh264 \
gstreamer-plugin-openh264 \
gstreamer-plugins-bad \
gstreamer1 \
libgstaccurip.so \
libgstadpcmdec.so \
libgstadpcmenc.so \
libgstaes.so \
libgstaiff.so \
libgstanalyticsoverlay.so \
libgstaom.so \
libgstasfmux.so \
libgstassrender.so \
libgstaudiobuffersplit.so \
libgstaudiofxbad.so \
libgstaudiolatency.so \
libgstaudiomixmatrix.so \
libgstaudiovisualizers.so \
libgstautoconvert.so \
libgstavtp.so \
libgstbayer.so \
libgstbluez.so \
libgstbs2b.so \
libgstbz2.so \
libgstcamerabin.so \
libgstclosedcaption.so \
libgstcodec2json.so \
libgstcodecalpha.so \
libgstcodectimestamper.so \
libgstcoloreffects.so \
libgstcolormanagement.so \
libgstcurl.so \
libgstdash.so \
libgstdc1394.so \
libgstdebugutilsbad.so \
libgstdtls.so \
libgstdtsdec.so \
libgstdvb.so \
libgstdvbsubenc.so \
libgstdvbsuboverlay.so \
libgstdvdspu.so \
libgstfaad.so \
libgstfaceoverlay.so \
libgstfbdevsink.so \
libgstfdkaac.so \
libgstfieldanalysis.so \
libgstfreeverb.so \
libgstfrei0r.so \
libgstgaudieffects.so \
libgstgdp.so \
libgstgeometrictransform.so \
libgstgme.so \
libgstgsm.so \
libgstgtkwayland.so \
libgsthip.so \
libgsthls.so \
libgstid3tag.so \
libgstinsertbin.so \
libgstinter.so \
libgstinterlace.so \
libgstipcpipeline.so \
libgstivfparse.so \
libgstivtc.so \
libgstjp2kdecimator.so \
libgstjpegformat.so \
libgstkms.so \
libgstladspa.so \
libgstlc3.so \
libgstldac.so \
libgstlegacyrawparse.so \
libgstlv2.so \
libgstmicrodns.so \
libgstmidi.so \
libgstmpegpsdemux.so \
libgstmpegpsmux.so \
libgstmpegtsdemux.so \
libgstmpegtsmux.so \
libgstmse.so \
libgstmusepack.so \
libgstmxf.so \
libgstneonhttpsrc.so \
libgstnetsim.so \
libgstnvcodec.so \
libgstopenal.so \
libgstopenexr.so \
libgstopenh264.so \
libgstopenjpeg.so \
libgstopenmpt.so \
libgstopusparse.so \
libgstpcapparse.so \
libgstpnm.so \
libgstproxy.so \
libgstqroverlay.so \
libgstremovesilence.so \
libgstresindvd.so \
libgstrfbsrc.so \
libgstrist.so \
libgstrsvg.so \
libgstrtmp2.so \
libgstrtpmanagerbad.so \
libgstrtponvif.so \
libgstsbc.so \
libgstsctp.so \
libgstsdpelem.so \
libgstsegmentclip.so \
libgstshm.so \
libgstsiren.so \
libgstsmooth.so \
libgstsmoothstreaming.so \
libgstsndfile.so \
libgstsoundtouch.so \
libgstspandsp.so \
libgstspeed.so \
libgstsrt.so \
libgstsrtp.so \
libgstsubenc.so \
libgstsvtav1.so \
libgstswitchbin.so \
libgstteletext.so \
libgsttensordecoders.so \
libgsttimecode.so \
libgstttmlsubs.so \
libgstunixfd.so \
libgstuvcgadget.so \
libgstuvch264.so \
libgstv4l2codecs.so \
libgstva.so \
libgstvideofiltersbad.so \
libgstvideoframe-audiolevel.so \
libgstvideoparsersbad.so \
libgstvideosignal.so \
libgstvmaf.so \
libgstvmnc.so \
libgstvoamrwbenc.so \
libgstvulkan.so \
libgstwaylandsink.so \
libgstwebp.so \
libgstwebrtc.so \
libgstwebrtcdsp.so \
libgstzbar.so \
libgstzxing.so \
patched-subset"

RDEPENDS:${PN} += "glib2-tools \
ld-linux-aarch64.so.1 \
libIex-3-4.so.33 \
libImath-3-2.so.30 \
libOpenEXR-3-4.so.33 \
libSoundTouch.so.1 \
libSvtAv1Enc.so.4 \
libX11.so.6 \
libZXing.so.4 \
libaom.so.3 \
libass.so.9 \
libavtp.so.0 \
libbs2b.so.0 \
libbz2.so.1 \
libc.so.6 \
libcairo.so.2 \
libcrypto.so.3 \
libcurl.so.4 \
libdc1394.so.26 \
libdca.so.0 \
libdrm.so.2 \
libdvdnav.so.4 \
libdvdread.so.8 \
libfaad.so.2 \
libfdk-aac.so.2 \
libgcc-s.so.1 \
libgdk-3.so.0 \
libgio-2.0.so.0 \
libglib-2.0.so.0 \
libgme.so.0 \
libgmodule-2.0.so.0 \
libgobject-2.0.so.0 \
libgsm.so.1 \
libgstadaptivedemux-1.0.so.0 \
libgstallocators-1.0.so.0 \
libgstanalytics-1.0.so.0 \
libgstapp-1.0.so.0 \
libgstaudio-1.0.so.0 \
libgstbadaudio-1.0.so.0 \
libgstbase-1.0.so.0 \
libgstbasecamerabinsrc-1.0.so.0 \
libgstcodecparsers-1.0.so.0 \
libgstcodecs-1.0.so.0 \
libgstcuda-1.0.so.0 \
libgstfft-1.0.so.0 \
libgstgl-1.0.so.0 \
libgsthip-1.0.so.0 \
libgstinsertbin-1.0.so.0 \
libgstisoff-1.0.so.0 \
libgstmpegts-1.0.so.0 \
libgstmse-1.0.so.0 \
libgstnet-1.0.so.0 \
libgstpbutils-1.0.so.0 \
libgstphotography-1.0.so.0 \
libgstreamer-1.0.so.0 \
libgstrtp-1.0.so.0 \
libgstsctp-1.0.so.0 \
libgstsdp-1.0.so.0 \
libgsttag-1.0.so.0 \
libgsturidownloader-1.0.so.0 \
libgstva-1.0.so.0 \
libgstvideo-1.0.so.0 \
libgstvulkan-1.0.so.0 \
libgstwayland-1.0.so.0 \
libgstwebrtc-1.0.so.0 \
libgstwebrtcnice-1.0.so.0 \
libgtk-3.so.0 \
libgudev-1.0.so.0 \
libjson-glib-1.0.so.0 \
liblc3.so.1 \
liblcms2.so.2 \
libldacBT-enc.so.2 \
liblilv-0.so.0 \
libm.so.6 \
libmicrodns.so.1 \
libmpcdec.so.6 \
libneon.so.27 \
libopenal.so.1 \
libopenh264.so.8 \
libopenjp2.so.7 \
libopenmpt.so.0 \
libopus.so.0 \
liborc-0.4.so.0 \
libpango-1.0.so.0 \
libpangocairo-1.0.so.0 \
libqrencode.so.4 \
librsvg-2.so.2 \
libsbc.so.1 \
libsndfile.so.1 \
libspandsp.so.3 \
libsrt.so.1.5 \
libsrtp2.so.1 \
libssl.so.3 \
libstdc++.so.6 \
libusb-1.0.so.0 \
libva.so.2 \
libvmaf.so.3 \
libvo-amrwbenc.so.0 \
libvulkan.so.1 \
libwayland-client.so.0 \
libwebp.so.7 \
libwebpmux.so.3 \
libwebrtc-audio-processing-1.so.3 \
libxml2.so.16 \
libzbar.so.0 \
libzvbi.so.0"

inherit rpm
