SUMMARY = "Java bindings for VTK"
DESCRIPTION = "VTK is a software system for image processing, 3D graphics, volume \
rendering and visualization. VTK includes many advanced algorithms \
(e.g. surface reconstruction, implicit modelling, decimation) and \
rendering techniques (e.g. hardware-accelerated volume rendering, \
LOD control). \
 \
This package provides java bindings for VTK."
LICENSE = "BSD-3-Clause"

PV = "9.6.1"

RPM_NAME = "vtk-java-9.6.1-2.2.aarch64.rpm"
RPM_HASH = "39a7fa2b431e29fec0cdf27e483dbc206591655083fb568596dcc66634934b2979e15b087f99aa242230836dfcddb8098175571d22529dc63f990b08cc88f191"

RPROVIDES:${PN} += "libvtkChartsCoreJava.so \
libvtkCommonColorJava.so \
libvtkCommonComputationalGeometryJava.so \
libvtkCommonCoreJava.so \
libvtkCommonDataModelJava.so \
libvtkCommonExecutionModelJava.so \
libvtkCommonMathJava.so \
libvtkCommonMiscJava.so \
libvtkCommonPythonJava.so \
libvtkCommonSystemJava.so \
libvtkCommonTransformsJava.so \
libvtkDomainsChemistryJava.so \
libvtkDomainsChemistryOpenGL2Java.so \
libvtkFiltersAMRJava.so \
libvtkFiltersCellGridJava.so \
libvtkFiltersCoreJava.so \
libvtkFiltersExtractionJava.so \
libvtkFiltersFlowPathsJava.so \
libvtkFiltersGeneralJava.so \
libvtkFiltersGenericJava.so \
libvtkFiltersGeometryJava.so \
libvtkFiltersGeometryPreviewJava.so \
libvtkFiltersHybridJava.so \
libvtkFiltersHyperTreeJava.so \
libvtkFiltersImagingJava.so \
libvtkFiltersModelingJava.so \
libvtkFiltersParallelDIY2Java.so \
libvtkFiltersParallelImagingJava.so \
libvtkFiltersParallelJava.so \
libvtkFiltersParallelStatisticsJava.so \
libvtkFiltersParallelVerdictJava.so \
libvtkFiltersPointsJava.so \
libvtkFiltersProgrammableJava.so \
libvtkFiltersPythonJava.so \
libvtkFiltersReductionJava.so \
libvtkFiltersSMPJava.so \
libvtkFiltersSelectionJava.so \
libvtkFiltersSourcesJava.so \
libvtkFiltersStatisticsJava.so \
libvtkFiltersTemporalJava.so \
libvtkFiltersTensorJava.so \
libvtkFiltersTextureJava.so \
libvtkFiltersTopologyJava.so \
libvtkFiltersVerdictJava.so \
libvtkGeovisCoreJava.so \
libvtkIOAMRJava.so \
libvtkIOAsynchronousJava.so \
libvtkIOAvmeshJava.so \
libvtkIOCGNSReaderJava.so \
libvtkIOCONVERGECFDJava.so \
libvtkIOCellGridJava.so \
libvtkIOCesium3DTilesJava.so \
libvtkIOChemistryJava.so \
libvtkIOCityGMLJava.so \
libvtkIOCoreJava.so \
libvtkIOERFJava.so \
libvtkIOEnSightJava.so \
libvtkIOEngysJava.so \
libvtkIOExodusJava.so \
libvtkIOExportJava.so \
libvtkIOExportPDFJava.so \
libvtkIOFDSJava.so \
libvtkIOFLUENTCFFJava.so \
libvtkIOGeometryJava.so \
libvtkIOH5RageJava.so \
libvtkIOH5partJava.so \
libvtkIOHDFJava.so \
libvtkIOIOSSJava.so \
libvtkIOImageJava.so \
libvtkIOImportJava.so \
libvtkIOInfovisJava.so \
libvtkIOLANLX3DJava.so \
libvtkIOLSDynaJava.so \
libvtkIOLegacyJava.so \
libvtkIOMINCJava.so \
libvtkIOMotionFXJava.so \
libvtkIOMovieJava.so \
libvtkIONetCDFJava.so \
libvtkIOOMFJava.so \
libvtkIOOggTheoraJava.so \
libvtkIOPIOJava.so \
libvtkIOPLYJava.so \
libvtkIOParallelExodusJava.so \
libvtkIOParallelJava.so \
libvtkIOParallelLSDynaJava.so \
libvtkIOParallelXMLJava.so \
libvtkIOSQLJava.so \
libvtkIOSegYJava.so \
libvtkIOTRUCHASJava.so \
libvtkIOTecplotTableJava.so \
libvtkIOVPICJava.so \
libvtkIOVeraOutJava.so \
libvtkIOVideoJava.so \
libvtkIOXMLJava.so \
libvtkIOXMLParserJava.so \
libvtkIOXdmf2Java.so \
libvtkImagingColorJava.so \
libvtkImagingCoreJava.so \
libvtkImagingFourierJava.so \
libvtkImagingGeneralJava.so \
libvtkImagingHybridJava.so \
libvtkImagingMathJava.so \
libvtkImagingMorphologicalJava.so \
libvtkImagingSourcesJava.so \
libvtkImagingStatisticsJava.so \
libvtkImagingStencilJava.so \
libvtkInfovisCoreJava.so \
libvtkInfovisLayoutJava.so \
libvtkInteractionImageJava.so \
libvtkInteractionStyleJava.so \
libvtkInteractionWidgetsJava.so \
libvtkParallelCoreJava.so \
libvtkPythonContext2DJava.so \
libvtkRenderingAnnotationJava.so \
libvtkRenderingCellGridJava.so \
libvtkRenderingContext2DJava.so \
libvtkRenderingContextOpenGL2Java.so \
libvtkRenderingCoreJava.so \
libvtkRenderingFreeTypeJava.so \
libvtkRenderingGridAxesJava.so \
libvtkRenderingHyperTreeGridJava.so \
libvtkRenderingImageJava.so \
libvtkRenderingLODJava.so \
libvtkRenderingLabelJava.so \
libvtkRenderingMatplotlibJava.so \
libvtkRenderingOpenGL2Java.so \
libvtkRenderingParallelJava.so \
libvtkRenderingQtJava.so \
libvtkRenderingSceneGraphJava.so \
libvtkRenderingUIJava.so \
libvtkRenderingVRModelsJava.so \
libvtkRenderingVolumeAMRJava.so \
libvtkRenderingVolumeJava.so \
libvtkRenderingVolumeOpenGL2Java.so \
libvtkRenderingVtkJSJava.so \
libvtkTestingRenderingJava.so \
libvtkViewsContext2DJava.so \
libvtkViewsCoreJava.so \
libvtkViewsInfovisJava.so \
libvtkWebCoreJava.so \
libvtkWebGLExporterJava.so \
vtk-java"

RDEPENDS:${PN} += "/sbin/ldconfig \
ld-linux-aarch64.so.1 \
libc.so.6 \
libgcc-s.so.1 \
libjawt.so \
libm.so.6 \
libstdc++.so.6 \
libvtk1 \
libvtkChartsCore.so.1 \
libvtkCommonColor.so.1 \
libvtkCommonComputationalGeometry.so.1 \
libvtkCommonCore.so.1 \
libvtkCommonDataModel.so.1 \
libvtkCommonExecutionModel.so.1 \
libvtkCommonMath.so.1 \
libvtkCommonMisc.so.1 \
libvtkCommonSystem.so.1 \
libvtkCommonTransforms.so.1 \
libvtkDomainsChemistry.so.1 \
libvtkDomainsChemistryOpenGL2.so.1 \
libvtkFiltersAMR.so.1 \
libvtkFiltersCellGrid.so.1 \
libvtkFiltersCore.so.1 \
libvtkFiltersExtraction.so.1 \
libvtkFiltersFlowPaths.so.1 \
libvtkFiltersGeneral.so.1 \
libvtkFiltersGeneric.so.1 \
libvtkFiltersGeometry.so.1 \
libvtkFiltersGeometryPreview.so.1 \
libvtkFiltersHybrid.so.1 \
libvtkFiltersHyperTree.so.1 \
libvtkFiltersImaging.so.1 \
libvtkFiltersModeling.so.1 \
libvtkFiltersParallel.so.1 \
libvtkFiltersParallelDIY2.so.1 \
libvtkFiltersParallelImaging.so.1 \
libvtkFiltersParallelStatistics.so.1 \
libvtkFiltersParallelVerdict.so.1 \
libvtkFiltersPoints.so.1 \
libvtkFiltersProgrammable.so.1 \
libvtkFiltersReduction.so.1 \
libvtkFiltersSMP.so.1 \
libvtkFiltersSelection.so.1 \
libvtkFiltersSources.so.1 \
libvtkFiltersStatistics.so.1 \
libvtkFiltersTemporal.so.1 \
libvtkFiltersTensor.so.1 \
libvtkFiltersTexture.so.1 \
libvtkFiltersTopology.so.1 \
libvtkFiltersVerdict.so.1 \
libvtkGeovisCore.so.1 \
libvtkIOAMR.so.1 \
libvtkIOAsynchronous.so.1 \
libvtkIOAvmesh.so.1 \
libvtkIOCGNSReader.so.1 \
libvtkIOCONVERGECFD.so.1 \
libvtkIOCellGrid.so.1 \
libvtkIOCesium3DTiles.so.1 \
libvtkIOChemistry.so.1 \
libvtkIOCityGML.so.1 \
libvtkIOCore.so.1 \
libvtkIOERF.so.1 \
libvtkIOEnSight.so.1 \
libvtkIOEngys.so.1 \
libvtkIOExodus.so.1 \
libvtkIOExport.so.1 \
libvtkIOExportPDF.so.1 \
libvtkIOFDS.so.1 \
libvtkIOFLUENTCFF.so.1 \
libvtkIOGeometry.so.1 \
libvtkIOH5Rage.so.1 \
libvtkIOH5part.so.1 \
libvtkIOHDF.so.1 \
libvtkIOIOSS.so.1 \
libvtkIOImage.so.1 \
libvtkIOImport.so.1 \
libvtkIOInfovis.so.1 \
libvtkIOLANLX3D.so.1 \
libvtkIOLSDyna.so.1 \
libvtkIOLegacy.so.1 \
libvtkIOMINC.so.1 \
libvtkIOMotionFX.so.1 \
libvtkIOMovie.so.1 \
libvtkIONetCDF.so.1 \
libvtkIOOMF.so.1 \
libvtkIOOggTheora.so.1 \
libvtkIOPIO.so.1 \
libvtkIOPLY.so.1 \
libvtkIOParallel.so.1 \
libvtkIOParallelExodus.so.1 \
libvtkIOParallelLSDyna.so.1 \
libvtkIOParallelXML.so.1 \
libvtkIOSQL.so.1 \
libvtkIOSegY.so.1 \
libvtkIOTRUCHAS.so.1 \
libvtkIOTecplotTable.so.1 \
libvtkIOVPIC.so.1 \
libvtkIOVeraOut.so.1 \
libvtkIOVideo.so.1 \
libvtkIOXML.so.1 \
libvtkIOXMLParser.so.1 \
libvtkIOXdmf2.so.1 \
libvtkImagingColor.so.1 \
libvtkImagingCore.so.1 \
libvtkImagingFourier.so.1 \
libvtkImagingGeneral.so.1 \
libvtkImagingHybrid.so.1 \
libvtkImagingMath.so.1 \
libvtkImagingMorphological.so.1 \
libvtkImagingSources.so.1 \
libvtkImagingStatistics.so.1 \
libvtkImagingStencil.so.1 \
libvtkInfovisCore.so.1 \
libvtkInfovisLayout.so.1 \
libvtkInteractionImage.so.1 \
libvtkInteractionStyle.so.1 \
libvtkInteractionWidgets.so.1 \
libvtkJava.so.1 \
libvtkParallelCore.so.1 \
libvtkRenderingAnnotation.so.1 \
libvtkRenderingCellGrid.so.1 \
libvtkRenderingContext2D.so.1 \
libvtkRenderingContextOpenGL2.so.1 \
libvtkRenderingCore.so.1 \
libvtkRenderingFreeType.so.1 \
libvtkRenderingGridAxes.so.1 \
libvtkRenderingHyperTreeGrid.so.1 \
libvtkRenderingImage.so.1 \
libvtkRenderingLOD.so.1 \
libvtkRenderingLabel.so.1 \
libvtkRenderingMatplotlib.so.1 \
libvtkRenderingOpenGL2.so.1 \
libvtkRenderingParallel.so.1 \
libvtkRenderingQt.so.1 \
libvtkRenderingSceneGraph.so.1 \
libvtkRenderingUI.so.1 \
libvtkRenderingVRModels.so.1 \
libvtkRenderingVolume.so.1 \
libvtkRenderingVolumeAMR.so.1 \
libvtkRenderingVolumeOpenGL2.so.1 \
libvtkRenderingVtkJS.so.1 \
libvtkTestingRendering.so.1 \
libvtkViewsContext2D.so.1 \
libvtkViewsCore.so.1 \
libvtkViewsInfovis.so.1 \
libvtkWebCore.so.1 \
libvtkWebGLExporter.so.1 \
libvtksys.so.1 \
libvtktoken.so.1"

inherit rpm
