SUMMARY = "Trees and other linguists' macros"
DESCRIPTION = "The package defines a mechanism for specifying connected trees \
that uses a tabular environment to generate node positions. The \
package uses PostScript code, loaded by dvips, so output can \
only be generated by use of dvips. The package lingmacros.sty \
defines a few macros for linguists: \\enumsentence for \
enumerating sentence examples, simple tabular-based \
non-connected tree macros, and gloss macros."
LICENSE = "LPPL-1.0"

PV = "2026.226.0.0.91svn21751"

RPM_NAME = "texlive-tree-dvips-2026.226.0.0.91svn21751-59.2.noarch.rpm"
RPM_HASH = "d51b49a68949e45296ab01d8de19defd421c6233435dea5f6ccf440484f6922ee9b37bf3e4ac5e0ebaf6c02cfc56ac7511aedc069dec4023fe68d74fc5a00856"
REPO_ARCH = "noarch"

RPROVIDES:${PN} += "tex-lingmacros.sty \
tex-tree-dvips.sty \
texlive-tree-dvips"

RDEPENDS:${PN} += "/usr/bin/sh \
coreutils \
ed \
findutils \
grep \
sed \
texlive \
texlive-filesystem \
texlive-kpathsea \
texlive-kpathsea-bin \
texlive-scripts \
texlive-scripts-bin"

inherit rpm
