SUMMARY = "RPM macros for building of Python modules"
DESCRIPTION = "This package contains SUSE RPM macros for Python build automation. \
You should BuildRequire this package unless you are sure that you \
are only building for distros newer than Leap 42.2"
LICENSE = "WTFPL"

PV = "20260909.65d2791"

RPM_NAME = "python-rpm-macros-20260909.65d2791-1.1.noarch.rpm"
RPM_HASH = "188679282106882fea83a0dc043605824f71309fac1a9a8e3b3f5397b1e67fad6c465a4aa4d2027ed96057cccf50363f5fb2399441298bf5bdb4e1cd4d909d99"
REPO_ARCH = "noarch"

RPROVIDES:${PN} += "python-rpm-macros \
python2-rpm-macros \
python3-rpm-macros \
rpm-macro--pyproject-anywheeldir \
rpm-macro--pyproject-wheeldir \
rpm-macro--pypy3-bin-suffix \
rpm-macro--python-definitions \
rpm-macro--python-macro-init \
rpm-macro--python-scan-spec \
rpm-macro--python-stash-flavor \
rpm-macro--python-sysconfig-path \
rpm-macro--python-sysconfig-var \
rpm-macro--python-use-flavor \
rpm-macro--rec-macro-helper \
rpm-macro--without-python2 \
rpm-macro-add-python \
rpm-macro-alternative-for \
rpm-macro-buildsystem-pyproject-build \
rpm-macro-buildsystem-pyproject-check \
rpm-macro-buildsystem-pyproject-conf \
rpm-macro-buildsystem-pyproject-generate-buildrequires \
rpm-macro-buildsystem-pyproject-install \
rpm-macro-if-not-python-kind \
rpm-macro-if-python-kind \
rpm-macro-ifpycache \
rpm-macro-ifpypy3 \
rpm-macro-ifpython2 \
rpm-macro-ifpython3 \
rpm-macro-ifpython310 \
rpm-macro-ifpython311 \
rpm-macro-ifpython312 \
rpm-macro-ifpython313 \
rpm-macro-ifpython314 \
rpm-macro-ifpython315 \
rpm-macro-install-alternative \
rpm-macro-modern-python \
rpm-macro-prepare-alternative \
rpm-macro-primary-python \
rpm-macro-py-dist-name \
rpm-macro-py-setup \
rpm-macro-py-shbang-opts \
rpm-macro-py-ver \
rpm-macro-py2-build \
rpm-macro-py2-dist \
rpm-macro-py2-install \
rpm-macro-py2-shbang-opts \
rpm-macro-py2-ver \
rpm-macro-py3-build \
rpm-macro-py3-dist \
rpm-macro-py3-install \
rpm-macro-py3-shbang-opts \
rpm-macro-py3-ver \
rpm-macro-pycache-only \
rpm-macro-pyproject-install \
rpm-macro-pyproject-install-args \
rpm-macro-pyproject-wheel \
rpm-macro-pyproject-wheel-args \
rpm-macro-pypy3-alternative \
rpm-macro-pypy3-alternative-conf \
rpm-macro-pypy3-bin-suffix \
rpm-macro-pypy3-build \
rpm-macro-pypy3-compile \
rpm-macro-pypy3-fix-shebang \
rpm-macro-pypy3-fix-shebang-path \
rpm-macro-pypy3-install \
rpm-macro-pypy3-install-alternative \
rpm-macro-pypy3-only \
rpm-macro-pypy3-prefix \
rpm-macro-pypy3-provides \
rpm-macro-pypy3-pyproject-install \
rpm-macro-pypy3-pyproject-wheel \
rpm-macro-pypy3-pytest \
rpm-macro-pypy3-pytest-arch \
rpm-macro-pypy3-pyunittest \
rpm-macro-pypy3-pyunittest-arch \
rpm-macro-pypy3-reset-alternative \
rpm-macro-pypy3-shbang-opts \
rpm-macro-pypy3-sitearch \
rpm-macro-pypy3-sitelib \
rpm-macro-pypy3-sysconfig-path \
rpm-macro-pypy3-sysconfig-var \
rpm-macro-pypy3-uninstall-alternative \
rpm-macro-pypy3-version \
rpm-macro-pypy3-version-nodots \
rpm-macro-pytest \
rpm-macro-pytest-arch \
rpm-macro-python-alternative \
rpm-macro-python-alternative-conf \
rpm-macro-python-bin-suffix \
rpm-macro-python-build \
rpm-macro-python-clone \
rpm-macro-python-compileall \
rpm-macro-python-dist-name \
rpm-macro-python-enable-dependency-generator \
rpm-macro-python-exec \
rpm-macro-python-expand \
rpm-macro-python-files \
rpm-macro-python-find-lang \
rpm-macro-python-flavor \
rpm-macro-python-flavored-alternatives \
rpm-macro-python-for-executables \
rpm-macro-python-group-libalternatives \
rpm-macro-python-install \
rpm-macro-python-install-alternative \
rpm-macro-python-libalternatives-reset-alternative \
rpm-macro-python-module \
rpm-macro-python-module-iter \
rpm-macro-python-module-iter-STOP \
rpm-macro-python-module-lua \
rpm-macro-python-prefix \
rpm-macro-python-provides \
rpm-macro-python-sitearch \
rpm-macro-python-sitearch-module \
rpm-macro-python-sitelib \
rpm-macro-python-sitelib-module \
rpm-macro-python-subpackages \
rpm-macro-python-sysconfig-path \
rpm-macro-python-sysconfig-var \
rpm-macro-python-uninstall-alternative \
rpm-macro-python-version \
rpm-macro-python-version-nodots \
rpm-macro-python2-alternative \
rpm-macro-python2-alternative-conf \
rpm-macro-python2-bin-suffix \
rpm-macro-python2-build \
rpm-macro-python2-compile \
rpm-macro-python2-dist \
rpm-macro-python2-fix-shebang \
rpm-macro-python2-fix-shebang-path \
rpm-macro-python2-install \
rpm-macro-python2-install-alternative \
rpm-macro-python2-only \
rpm-macro-python2-prefix \
rpm-macro-python2-provides \
rpm-macro-python2-pyproject-install \
rpm-macro-python2-pyproject-wheel \
rpm-macro-python2-pytest \
rpm-macro-python2-pytest-arch \
rpm-macro-python2-pyunittest \
rpm-macro-python2-pyunittest-arch \
rpm-macro-python2-reset-alternative \
rpm-macro-python2-shbang-opts \
rpm-macro-python2-sitearch \
rpm-macro-python2-sitelib \
rpm-macro-python2-sysconfig-path \
rpm-macro-python2-sysconfig-var \
rpm-macro-python2-uninstall-alternative \
rpm-macro-python2-version \
rpm-macro-python2-version-nodots \
rpm-macro-python3-alternative \
rpm-macro-python3-alternative-conf \
rpm-macro-python3-bin-suffix \
rpm-macro-python3-build \
rpm-macro-python3-compile \
rpm-macro-python3-dist \
rpm-macro-python3-fix-shebang \
rpm-macro-python3-fix-shebang-path \
rpm-macro-python3-install \
rpm-macro-python3-install-alternative \
rpm-macro-python3-only \
rpm-macro-python3-prefix \
rpm-macro-python3-provides \
rpm-macro-python3-pyproject-install \
rpm-macro-python3-pyproject-wheel \
rpm-macro-python3-pytest \
rpm-macro-python3-pytest-arch \
rpm-macro-python3-pyunittest \
rpm-macro-python3-pyunittest-arch \
rpm-macro-python3-reset-alternative \
rpm-macro-python3-shbang-opts \
rpm-macro-python3-sitearch \
rpm-macro-python3-sitelib \
rpm-macro-python3-sysconfig-path \
rpm-macro-python3-sysconfig-var \
rpm-macro-python3-uninstall-alternative \
rpm-macro-python3-version \
rpm-macro-python3-version-nodots \
rpm-macro-python310-alternative \
rpm-macro-python310-alternative-conf \
rpm-macro-python310-bin-suffix \
rpm-macro-python310-build \
rpm-macro-python310-compile \
rpm-macro-python310-fix-shebang \
rpm-macro-python310-fix-shebang-path \
rpm-macro-python310-install \
rpm-macro-python310-install-alternative \
rpm-macro-python310-only \
rpm-macro-python310-prefix \
rpm-macro-python310-provides \
rpm-macro-python310-pyproject-install \
rpm-macro-python310-pyproject-wheel \
rpm-macro-python310-pytest \
rpm-macro-python310-pytest-arch \
rpm-macro-python310-pyunittest \
rpm-macro-python310-pyunittest-arch \
rpm-macro-python310-reset-alternative \
rpm-macro-python310-shbang-opts \
rpm-macro-python310-sitearch \
rpm-macro-python310-sitelib \
rpm-macro-python310-sysconfig-path \
rpm-macro-python310-sysconfig-var \
rpm-macro-python310-uninstall-alternative \
rpm-macro-python310-version \
rpm-macro-python310-version-nodots \
rpm-macro-python311-alternative \
rpm-macro-python311-alternative-conf \
rpm-macro-python311-bin-suffix \
rpm-macro-python311-build \
rpm-macro-python311-compile \
rpm-macro-python311-fix-shebang \
rpm-macro-python311-fix-shebang-path \
rpm-macro-python311-install \
rpm-macro-python311-install-alternative \
rpm-macro-python311-only \
rpm-macro-python311-prefix \
rpm-macro-python311-provides \
rpm-macro-python311-pyproject-install \
rpm-macro-python311-pyproject-wheel \
rpm-macro-python311-pytest \
rpm-macro-python311-pytest-arch \
rpm-macro-python311-pyunittest \
rpm-macro-python311-pyunittest-arch \
rpm-macro-python311-reset-alternative \
rpm-macro-python311-shbang-opts \
rpm-macro-python311-sitearch \
rpm-macro-python311-sitelib \
rpm-macro-python311-sysconfig-path \
rpm-macro-python311-sysconfig-var \
rpm-macro-python311-uninstall-alternative \
rpm-macro-python311-version \
rpm-macro-python311-version-nodots \
rpm-macro-python312-alternative \
rpm-macro-python312-alternative-conf \
rpm-macro-python312-bin-suffix \
rpm-macro-python312-build \
rpm-macro-python312-compile \
rpm-macro-python312-fix-shebang \
rpm-macro-python312-fix-shebang-path \
rpm-macro-python312-install \
rpm-macro-python312-install-alternative \
rpm-macro-python312-only \
rpm-macro-python312-prefix \
rpm-macro-python312-provides \
rpm-macro-python312-pyproject-install \
rpm-macro-python312-pyproject-wheel \
rpm-macro-python312-pytest \
rpm-macro-python312-pytest-arch \
rpm-macro-python312-pyunittest \
rpm-macro-python312-pyunittest-arch \
rpm-macro-python312-reset-alternative \
rpm-macro-python312-shbang-opts \
rpm-macro-python312-sitearch \
rpm-macro-python312-sitelib \
rpm-macro-python312-sysconfig-path \
rpm-macro-python312-sysconfig-var \
rpm-macro-python312-uninstall-alternative \
rpm-macro-python312-version \
rpm-macro-python312-version-nodots \
rpm-macro-python313-alternative \
rpm-macro-python313-alternative-conf \
rpm-macro-python313-bin-suffix \
rpm-macro-python313-build \
rpm-macro-python313-compile \
rpm-macro-python313-fix-shebang \
rpm-macro-python313-fix-shebang-path \
rpm-macro-python313-install \
rpm-macro-python313-install-alternative \
rpm-macro-python313-only \
rpm-macro-python313-prefix \
rpm-macro-python313-provides \
rpm-macro-python313-pyproject-install \
rpm-macro-python313-pyproject-wheel \
rpm-macro-python313-pytest \
rpm-macro-python313-pytest-arch \
rpm-macro-python313-pyunittest \
rpm-macro-python313-pyunittest-arch \
rpm-macro-python313-reset-alternative \
rpm-macro-python313-shbang-opts \
rpm-macro-python313-sitearch \
rpm-macro-python313-sitelib \
rpm-macro-python313-sysconfig-path \
rpm-macro-python313-sysconfig-var \
rpm-macro-python313-uninstall-alternative \
rpm-macro-python313-version \
rpm-macro-python313-version-nodots \
rpm-macro-python314-alternative \
rpm-macro-python314-alternative-conf \
rpm-macro-python314-bin-suffix \
rpm-macro-python314-build \
rpm-macro-python314-compile \
rpm-macro-python314-fix-shebang \
rpm-macro-python314-fix-shebang-path \
rpm-macro-python314-install \
rpm-macro-python314-install-alternative \
rpm-macro-python314-only \
rpm-macro-python314-prefix \
rpm-macro-python314-provides \
rpm-macro-python314-pyproject-install \
rpm-macro-python314-pyproject-wheel \
rpm-macro-python314-pytest \
rpm-macro-python314-pytest-arch \
rpm-macro-python314-pyunittest \
rpm-macro-python314-pyunittest-arch \
rpm-macro-python314-reset-alternative \
rpm-macro-python314-shbang-opts \
rpm-macro-python314-sitearch \
rpm-macro-python314-sitelib \
rpm-macro-python314-sysconfig-path \
rpm-macro-python314-sysconfig-var \
rpm-macro-python314-uninstall-alternative \
rpm-macro-python314-version \
rpm-macro-python314-version-nodots \
rpm-macro-python315-alternative \
rpm-macro-python315-alternative-conf \
rpm-macro-python315-bin-suffix \
rpm-macro-python315-build \
rpm-macro-python315-compile \
rpm-macro-python315-fix-shebang \
rpm-macro-python315-fix-shebang-path \
rpm-macro-python315-install \
rpm-macro-python315-install-alternative \
rpm-macro-python315-only \
rpm-macro-python315-prefix \
rpm-macro-python315-provides \
rpm-macro-python315-pyproject-install \
rpm-macro-python315-pyproject-wheel \
rpm-macro-python315-pytest \
rpm-macro-python315-pytest-arch \
rpm-macro-python315-pyunittest \
rpm-macro-python315-pyunittest-arch \
rpm-macro-python315-reset-alternative \
rpm-macro-python315-shbang-opts \
rpm-macro-python315-sitearch \
rpm-macro-python315-sitelib \
rpm-macro-python315-sysconfig-path \
rpm-macro-python315-sysconfig-var \
rpm-macro-python315-uninstall-alternative \
rpm-macro-python315-version \
rpm-macro-python315-version-nodots \
rpm-macro-pythons \
rpm-macro-pythons-for-pypi \
rpm-macro-pyunittest \
rpm-macro-pyunittest-arch \
rpm-macro-reset-alternative \
rpm-macro-single-pythons-311plus \
rpm-macro-system-python \
rpm-macro-uninstall-alternative"

RDEPENDS:${PN} += ""

inherit rpm
