SUMMARY = "Make PDF files searchable and copyable"
DESCRIPTION = "The cmap package provides character map tables, which make PDF \
files generated by pdfLaTeX both searchable and copy-able in \
acrobat reader and other compliant PDF viewers. Encodings \
supported are OT1, OT6, T1, T2A, T2B, T2C and T5, together with \
LAE (Arabic), LFE (Farsi) and LGR (Greek) and a variant OT1tt \
for cmtt-like fonts. The package's main limitation currently is \
the inability to work with virtual fonts, because of \
limitations of pdfTeX. This restriction may be resolved in a \
future version of pdfTeX."
LICENSE = "LPPL-1.0"

PV = "2026.226.1.0jsvn77682"

RPM_NAME = "texlive-cmap-2026.226.1.0jsvn77682-60.2.noarch.rpm"
RPM_HASH = "84158ea65a11081f0148aab162abf9e1e8d4d5f2e4d1a4bedecc4cba73e4288bec63faaf3b0bc3c1656867b80663ed1423aa85ba5de4c7317860cfb326d7b91f"
REPO_ARCH = "noarch"

RPROVIDES:${PN} += "tex-cmap.sty \
texlive-cmap"

RDEPENDS:${PN} += "/usr/bin/sh \
coreutils \
ed \
findutils \
grep \
sed \
texlive \
texlive-filesystem \
texlive-kpathsea \
texlive-kpathsea-bin \
texlive-scripts \
texlive-scripts-bin"

inherit rpm
