SUMMARY = "An idiomatic & safe pure-Rust implementation of Git"
DESCRIPTION = "gitoxide is an implementation of git written in Rust for providing a pleasant \
and unsurprising developer experience."
LICENSE = "(Apache-2.0 | MIT) & MPL-2.0"

PV = "0.58.0"

RPM_NAME = "gitoxide-0.58.0-1.2.aarch64.rpm"
RPM_HASH = "256c702fa4d8cb9b47011e03315f07ef33d9d28faffc1c4d037d0a408b6e7c4ff1a6dd00bddecd3b1039101c07fa71206456b60286fe48a92328056549dbe830"

RPROVIDES:${PN} += "bundled-rust-crate-aho-corasick \
bundled-rust-crate-allocator-api2 \
bundled-rust-crate-anstream \
bundled-rust-crate-anstyle \
bundled-rust-crate-anstyle-parse \
bundled-rust-crate-anstyle-query \
bundled-rust-crate-anyhow \
bundled-rust-crate-approx \
bundled-rust-crate-arc-swap \
bundled-rust-crate-arrayvec \
bundled-rust-crate-async-channel \
bundled-rust-crate-async-io \
bundled-rust-crate-autocfg \
bundled-rust-crate-base64 \
bundled-rust-crate-bitflags \
bundled-rust-crate-block-buffer \
bundled-rust-crate-bstr \
bundled-rust-crate-by-address \
bundled-rust-crate-byteorder \
bundled-rust-crate-bytes \
bundled-rust-crate-bytesize \
bundled-rust-crate-castaway \
bundled-rust-crate-cc \
bundled-rust-crate-cfg-if \
bundled-rust-crate-clap \
bundled-rust-crate-clap-builder \
bundled-rust-crate-clap-complete \
bundled-rust-crate-clap-derive \
bundled-rust-crate-clap-lex \
bundled-rust-crate-clru \
bundled-rust-crate-colorchoice \
bundled-rust-crate-compact-str \
bundled-rust-crate-concurrent-queue \
bundled-rust-crate-convert-case \
bundled-rust-crate-cpufeatures \
bundled-rust-crate-crc32fast \
bundled-rust-crate-crossbeam \
bundled-rust-crate-crossbeam-channel \
bundled-rust-crate-crossbeam-deque \
bundled-rust-crate-crossbeam-epoch \
bundled-rust-crate-crossbeam-queue \
bundled-rust-crate-crossbeam-utils \
bundled-rust-crate-crossterm \
bundled-rust-crate-crosstermion \
bundled-rust-crate-crypto-common \
bundled-rust-crate-curl \
bundled-rust-crate-curl-sys \
bundled-rust-crate-darling \
bundled-rust-crate-darling-core \
bundled-rust-crate-darling-macro \
bundled-rust-crate-dashmap \
bundled-rust-crate-defmt \
bundled-rust-crate-defmt-macros \
bundled-rust-crate-defmt-parser \
bundled-rust-crate-deranged \
bundled-rust-crate-derive-more \
bundled-rust-crate-derive-more-impl \
bundled-rust-crate-diff \
bundled-rust-crate-digest \
bundled-rust-crate-directories \
bundled-rust-crate-dirs-sys \
bundled-rust-crate-document-features \
bundled-rust-crate-dua-core \
bundled-rust-crate-either \
bundled-rust-crate-encoding-rs \
bundled-rust-crate-env-filter \
bundled-rust-crate-env-logger \
bundled-rust-crate-equivalent \
bundled-rust-crate-errno \
bundled-rust-crate-event-listener \
bundled-rust-crate-event-listener-strategy \
bundled-rust-crate-fallible-iterator \
bundled-rust-crate-fallible-streaming-iterator \
bundled-rust-crate-faster-hex \
bundled-rust-crate-fastrand \
bundled-rust-crate-filetime \
bundled-rust-crate-find-msvc-tools \
bundled-rust-crate-flate2 \
bundled-rust-crate-fnv \
bundled-rust-crate-foldhash \
bundled-rust-crate-fs-err \
bundled-rust-crate-futures-channel \
bundled-rust-crate-futures-core \
bundled-rust-crate-futures-io \
bundled-rust-crate-futures-lite \
bundled-rust-crate-futures-macro \
bundled-rust-crate-futures-sink \
bundled-rust-crate-futures-task \
bundled-rust-crate-futures-timer \
bundled-rust-crate-futures-util \
bundled-rust-crate-generic-array \
bundled-rust-crate-getopts \
bundled-rust-crate-getrandom \
bundled-rust-crate-gitoxide \
bundled-rust-crate-gitoxide-core \
bundled-rust-crate-gix \
bundled-rust-crate-gix-actor \
bundled-rust-crate-gix-archive \
bundled-rust-crate-gix-attributes \
bundled-rust-crate-gix-bitmap \
bundled-rust-crate-gix-blame \
bundled-rust-crate-gix-chunk \
bundled-rust-crate-gix-command \
bundled-rust-crate-gix-commitgraph \
bundled-rust-crate-gix-config \
bundled-rust-crate-gix-config-value \
bundled-rust-crate-gix-credentials \
bundled-rust-crate-gix-date \
bundled-rust-crate-gix-diff \
bundled-rust-crate-gix-dir \
bundled-rust-crate-gix-discover \
bundled-rust-crate-gix-error \
bundled-rust-crate-gix-features \
bundled-rust-crate-gix-filter \
bundled-rust-crate-gix-fs \
bundled-rust-crate-gix-fsck \
bundled-rust-crate-gix-glob \
bundled-rust-crate-gix-hash \
bundled-rust-crate-gix-hashtable \
bundled-rust-crate-gix-ignore \
bundled-rust-crate-gix-imara-diff \
bundled-rust-crate-gix-index \
bundled-rust-crate-gix-lock \
bundled-rust-crate-gix-macros \
bundled-rust-crate-gix-mailmap \
bundled-rust-crate-gix-merge \
bundled-rust-crate-gix-negotiate \
bundled-rust-crate-gix-note \
bundled-rust-crate-gix-object \
bundled-rust-crate-gix-odb \
bundled-rust-crate-gix-pack \
bundled-rust-crate-gix-packetline \
bundled-rust-crate-gix-path \
bundled-rust-crate-gix-pathspec \
bundled-rust-crate-gix-prompt \
bundled-rust-crate-gix-protocol \
bundled-rust-crate-gix-quote \
bundled-rust-crate-gix-ref \
bundled-rust-crate-gix-refspec \
bundled-rust-crate-gix-revision \
bundled-rust-crate-gix-revwalk \
bundled-rust-crate-gix-sec \
bundled-rust-crate-gix-shallow \
bundled-rust-crate-gix-status \
bundled-rust-crate-gix-submodule \
bundled-rust-crate-gix-tempfile \
bundled-rust-crate-gix-tix \
bundled-rust-crate-gix-trace \
bundled-rust-crate-gix-transport \
bundled-rust-crate-gix-traverse \
bundled-rust-crate-gix-url \
bundled-rust-crate-gix-utils \
bundled-rust-crate-gix-validate \
bundled-rust-crate-gix-worktree \
bundled-rust-crate-gix-worktree-state \
bundled-rust-crate-gix-worktree-stream \
bundled-rust-crate-gix-zlib \
bundled-rust-crate-glob \
bundled-rust-crate-hash32 \
bundled-rust-crate-hashbrown \
bundled-rust-crate-hashlink \
bundled-rust-crate-heapless \
bundled-rust-crate-heck \
bundled-rust-crate-human-format \
bundled-rust-crate-hybrid-array \
bundled-rust-crate-ident-case \
bundled-rust-crate-indexmap \
bundled-rust-crate-indoc \
bundled-rust-crate-inotify \
bundled-rust-crate-inotify-sys \
bundled-rust-crate-instability \
bundled-rust-crate-io-close \
bundled-rust-crate-is-docker \
bundled-rust-crate-is-terminal \
bundled-rust-crate-is-terminal-polyfill \
bundled-rust-crate-is-wsl \
bundled-rust-crate-itertools \
bundled-rust-crate-itoa \
bundled-rust-crate-jiff \
bundled-rust-crate-jiff-core \
bundled-rust-crate-jiff-static \
bundled-rust-crate-kasuari \
bundled-rust-crate-layout-rs \
bundled-rust-crate-lazy-static \
bundled-rust-crate-libc \
bundled-rust-crate-libm \
bundled-rust-crate-libsqlite3-sys \
bundled-rust-crate-libz-sys \
bundled-rust-crate-line-clipping \
bundled-rust-crate-linux-raw-sys \
bundled-rust-crate-litrs \
bundled-rust-crate-lock-api \
bundled-rust-crate-log \
bundled-rust-crate-lru \
bundled-rust-crate-memchr \
bundled-rust-crate-memmap2 \
bundled-rust-crate-mio \
bundled-rust-crate-nonempty \
bundled-rust-crate-notify \
bundled-rust-crate-notify-types \
bundled-rust-crate-nu-ansi-term \
bundled-rust-crate-num-conv \
bundled-rust-crate-num-threads \
bundled-rust-crate-num-traits \
bundled-rust-crate-once-cell \
bundled-rust-crate-open \
bundled-rust-crate-openssl-probe \
bundled-rust-crate-openssl-sys \
bundled-rust-crate-option-ext \
bundled-rust-crate-palette \
bundled-rust-crate-palette-derive \
bundled-rust-crate-palette-math \
bundled-rust-crate-parking \
bundled-rust-crate-parking-lot \
bundled-rust-crate-parking-lot-core \
bundled-rust-crate-percent-encoding \
bundled-rust-crate-pin-project-lite \
bundled-rust-crate-pkg-config \
bundled-rust-crate-polling \
bundled-rust-crate-portable-atomic \
bundled-rust-crate-powerfmt \
bundled-rust-crate-pretty-assertions \
bundled-rust-crate-proc-macro-crate \
bundled-rust-crate-proc-macro2 \
bundled-rust-crate-prodash \
bundled-rust-crate-pulldown-cmark \
bundled-rust-crate-pulldown-cmark-escape \
bundled-rust-crate-quote \
bundled-rust-crate-ratatui \
bundled-rust-crate-ratatui-core \
bundled-rust-crate-ratatui-crossterm \
bundled-rust-crate-ratatui-widgets \
bundled-rust-crate-rawzip \
bundled-rust-crate-regex \
bundled-rust-crate-regex-automata \
bundled-rust-crate-regex-syntax \
bundled-rust-crate-relative-path \
bundled-rust-crate-rstest \
bundled-rust-crate-rstest-macros \
bundled-rust-crate-rusqlite \
bundled-rust-crate-rustc-version \
bundled-rust-crate-rustix \
bundled-rust-crate-rustversion \
bundled-rust-crate-ryu \
bundled-rust-crate-same-file \
bundled-rust-crate-scopeguard \
bundled-rust-crate-semver \
bundled-rust-crate-serde \
bundled-rust-crate-serde-core \
bundled-rust-crate-serde-derive \
bundled-rust-crate-serde-json \
bundled-rust-crate-sha1 \
bundled-rust-crate-sha1-checked \
bundled-rust-crate-sha2 \
bundled-rust-crate-sharded-slab \
bundled-rust-crate-shell-words \
bundled-rust-crate-shlex \
bundled-rust-crate-signal-hook \
bundled-rust-crate-signal-hook-mio \
bundled-rust-crate-signal-hook-registry \
bundled-rust-crate-slab \
bundled-rust-crate-smallvec \
bundled-rust-crate-socket2 \
bundled-rust-crate-stable-deref-trait \
bundled-rust-crate-static-assertions \
bundled-rust-crate-strsim \
bundled-rust-crate-strum \
bundled-rust-crate-strum-macros \
bundled-rust-crate-symlink \
bundled-rust-crate-syn \
bundled-rust-crate-sysinfo \
bundled-rust-crate-tar \
bundled-rust-crate-tempfile \
bundled-rust-crate-terminal-colorsaurus \
bundled-rust-crate-terminal-size \
bundled-rust-crate-terminal-trx \
bundled-rust-crate-thiserror \
bundled-rust-crate-thiserror-impl \
bundled-rust-crate-thread-local \
bundled-rust-crate-time \
bundled-rust-crate-time-core \
bundled-rust-crate-time-macros \
bundled-rust-crate-tinyvec \
bundled-rust-crate-tinyvec-macros \
bundled-rust-crate-toml-datetime \
bundled-rust-crate-toml-edit \
bundled-rust-crate-toml-parser \
bundled-rust-crate-tracing \
bundled-rust-crate-tracing-appender \
bundled-rust-crate-tracing-attributes \
bundled-rust-crate-tracing-core \
bundled-rust-crate-tracing-forest \
bundled-rust-crate-tracing-log \
bundled-rust-crate-tracing-subscriber \
bundled-rust-crate-tui-markdown \
bundled-rust-crate-tui-react \
bundled-rust-crate-typenum \
bundled-rust-crate-uluru \
bundled-rust-crate-unicase \
bundled-rust-crate-unicode-bom \
bundled-rust-crate-unicode-ident \
bundled-rust-crate-unicode-normalization \
bundled-rust-crate-unicode-segmentation \
bundled-rust-crate-unicode-truncate \
bundled-rust-crate-unicode-width \
bundled-rust-crate-utf8parse \
bundled-rust-crate-value-bag \
bundled-rust-crate-vcpkg \
bundled-rust-crate-version-check \
bundled-rust-crate-walkdir \
bundled-rust-crate-winnow \
bundled-rust-crate-xattr \
bundled-rust-crate-xterm-color \
bundled-rust-crate-yansi \
bundled-rust-crate-zlib-rs \
bundled-rust-crate-zmij \
gitoxide"

RDEPENDS:${PN} += "libc.so.6 \
libcrypto.so.3 \
libgcc-s.so.1 \
libm.so.6 \
libssl.so.3 \
libz.so.1"

inherit rpm
